### ISSUE TITLE
How to use openBLAS with a single thread

### ISSUE THREAD

**Issue by zhaofan0622** [xianyi/OpenBLAS#1001]
(1)  I make openBLAS for windows with USE_THREAD=0 successfully, but when I use libopenblas.dll in my c++ program(build in vs2013), I find it still runs with multi threads.

(2) I can't make openBLAS for Android (armv7a) with USE_THREAD=0 ,

make[1]: Leaving directory `/home/houyongshun/Desktop/caffe-android-libarmeabi-v7a-hard-softfpwithNEON/OpenBLAS/kernel'

 OpenBLAS build complete. (BLAS CBLAS)

  OS               ... Android             
  Architecture     ... arm               
  BINARY           ... 32bit                 
  C compiler       ... GCC  (command line : /home/houyongshun/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/home/houyongshun/android-ndk-r10e/platforms/android-19/arch-arm)
  Fortran compiler ... GFORTRAN  (command line : /home/houyongshun/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gfortran --sysroot=/home/houyongshun/android-ndk-r10e/platforms/android-19/arch-arm)
  Library Name     ... libopenblas_armv7p-r0.2.18.a (Multi threaded; Max num-threads is 8)

 Use OpenMP in the multithreading. Because of ignoring OPENBLAS_NUM_THREADS and GOTO_NUM_THREADS flags, 
 you should use OMP_NUM_THREADS environment variable to control the number of threads.

To install the library, you can run "make PREFIX=/path/to/your/installation install".

make -j 24 -f Makefile.install install
make[1]: Entering directory `/home/houyongshun/Desktop/caffe-android-libarmeabi-v7a-hard-softfpwithNEON/OpenBLAS'
Generating openblas_config.h in /home/houyongshun/Desktop/caffe-android-libarmeabi-v7a-hard-softfpwithNEON/android_lib/openblas/include
Generating f77blas.h in /home/houyongshun/Desktop/caffe-android-libarmeabi-v7a-hard-softfpwithNEON/android_lib/openblas/include
Generating cblas.h in /home/houyongshun/Desktop/caffe-android-libarmeabi-v7a-hard-softfpwithNEON/android_lib/openblas/include
Copying the static library to /home/houyongshun/Desktop/caffe-android-libarmeabi-v7a-hard-softfpwithNEON/android_lib/openblas/lib
install: cannot stat ‘libopenblas_armv7-r0.2.18.a’: No such file or directory
make[1]: *** [install] Error 1
make[1]: Leaving directory `/home/houyongshun/Desktop/caffe-android-libarmeabi-v7a-hard-softfpwithNEON/OpenBLAS'
make: *** [install] Error 2

**Comment by martin-frbg** [comment]
How or where did you specify the USE_THREAD=0 ? Perhaps try to edit the corresponding line in Makefile.rule directly to make sure this option is not ignored during the build. Also do a "make clean"
before building, if you built with different settings before. (Please upload the full log if the problem persists)

**Comment by zhaofan0622** [comment]
@martin-frbg 
(1) I really edited the corresponding line in Makefile.rule directly.
(2) When making openBLAS for Android (armv7a) with USE_THREAD=0,  I first get two output files successfully ,whcih are “libopenblas.a” and "libopenblas_armv7p-r0.2.18.a".  Then, I get an error, reviewed above.

**Comment by martin-frbg** [comment]
Please excuse what is probably a silly question, but did you remember to remove the hash character
(#) before the USE_THREAD entry in Makefile.rule ?
