### ISSUE TITLE
make[1]: *** [../libopenblas_nehalemp-r0.2.20.dev.so] Error 1

### ISSUE THREAD

**Issue by 694982827** [xianyi/OpenBLAS#1005]
My environment is an Ubuntu docker container on Ubuntu14，when I make in the OpeBLAS directory，there are some wrongs appear：
 END OF TESTS
make[1]: Leaving directory `/data/open/OpenBLAS/ctest'
make[1]: Entering directory `/data/open/OpenBLAS/exports'
make[1]: warning: -jN forced in submake: disabling jobserver mode.
perl ./gensymbol linktest  x86_64 _ 0 0 0 0 0 0 "" "" 1 > linktest.c
gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=16 -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  -shared -o ../libopenblas_nehalemp-r0.2.20.dev.so \
	-Wl,--whole-archive ../libopenblas_nehalemp-r0.2.20.dev.a -Wl,--no-whole-archive \
	-Wl,-soname,libopenblas.so.0 -lm -lpthread -lgfortran -lm -lpthread -lgfortran
/usr/bin/ld: cannot find -lgfortran
collect2: ld returned 1 exit status
make[1]: *** [../libopenblas_nehalemp-r0.2.20.dev.so] Error 1
make[1]: Leaving directory `/data/open/OpenBLAS/exports'
make: *** [shared] Error 2
root@8e94cb680de7:/data/open/OpenBLAS# make install
make -j 16 -f Makefile.install install
make[1]: Entering directory `/data/open/OpenBLAS'
Generating openblas_config.h in /opt/OpenBLAS/include
Generating f77blas.h in /opt/OpenBLAS/include
Generating cblas.h in /opt/OpenBLAS/include
Copying LAPACKE header files to /opt/OpenBLAS/include
Copying the static library to /opt/OpenBLAS/lib
Copying the shared library to /opt/OpenBLAS/lib
install: cannot stat 'libopenblas_nehalemp-r0.2.20.dev.so': No such file or directory
make[1]: *** [install] Error 1
make[1]: Leaving directory `/data/open/OpenBLAS'
make: *** [install] Error 2
root@8e94cb680de7:/data/open/OpenBLAS#

**Comment by martin-frbg** [comment]
This is the important part:
>/usr/bin/ld: cannot find -lgfortran

meaning that your container probably lacks a package named like libgfortran-dev, libgfortran-(version number)-dev or similar. If you are only interested in the BLAS functionality, you can build with NO_LAPACK=1 to leave out all LAPACK functions (which require fortran).

**Comment by martin-frbg** [comment]
Did you manage to get it working in the meantime, or would you like further assistance ?

**Comment by xgh45** [comment]
@martin-frbg 
hello,I have install gfortran ,but got the error:/usr/bin/ld: cannot find -lgfortran,and I ldconfig the libgfortran.so ,but still have this problem,could you please tell me how to solve it?

**Comment by martin-frbg** [comment]
Could be that you need to install an additional package named libgfortran, gfortran-devel or similar. Do you have just a single libgfortran.so somewhere down in the installation path of the compiler, or similarly
named files (typically with a version number appended after the .so) in the regular library locations like /usr/lib or /usr/lib64 ?
