### ISSUE TITLE
[arm64] ../kernel/arm64/sgemm_kernel_4x4.S:1550: Error: bad instruction ldp d12,d13,[sp,#(2*16)]' 

### ISSUE THREAD

**Issue by zhangyifu2016** [xianyi/OpenBLAS#1011]
Hi, @xianyi, I used "make TARGET=ARMV8 BINARY=64 HOSTCC=gcc CC=/home/linux/gcc-linaro-arm-linux-gnueabihf-4.9-2014.07_linux/bin/arm-linux-gnueabihf-gcc NOFORTRAN=1 USE_THREAD=1". but the building stops with this error:

make[1]: *** No rule to make target ../kernel/arm64/amax.S', needed bysamax_k.o'. Stop.

I find that libopenblas_armv8p-r0.2.19.a has been generated, but .so not.

When I add "ARCH=arm64", this issue is solved, but building stops with another error:

../kernel/arm64/sgemm_kernel_4x4.S:1550: Error: bad instruction ldp d12,d13,[sp,#(2*16)]' ../kernel/arm64/sgemm_kernel_4x4.S:1551: Error: bad instructionldp d14,d15,[sp,#(316)]'
../kernel/arm64/sgemm_kernel_4x4.S:1552: Error: bad instruction `ldp d16,d17,[sp,#(416)]'
../kernel/arm64/sgemm_kernel_4x4.S:1553: Error: bad instruction ldp x18,x19,[sp,#(5*16)]' ../kernel/arm64/sgemm_kernel_4x4.S:1554: Error: bad instructionldp x20,x21,[sp,#(616)]'
../kernel/arm64/sgemm_kernel_4x4.S:1555: Error: bad instruction `ldp x22,x23,[sp,#(716)]'
../kernel/arm64/sgemm_kernel_4x4.S:1556: Error: bad instruction ldp x24,x25,[sp,#(8*16)]' ../kernel/arm64/sgemm_kernel_4x4.S:1557: Error: bad instructionldp x26,x27,[sp,#(916)]'
../kernel/arm64/sgemm_kernel_4x4.S:1558: Error: ARM register expected -- `ldr x28,[sp,#(1016)]'
../kernel/arm64/sgemm_kernel_4x4.S:1560: Error: bad instruction `ret'

How to solve it?

Thank you in advance.

**Comment by ashwinyes** [comment]
You are trying to compile armv8 code using an armv7 compiler (arm-linux-gnueabihf-gcc).

Please switch to armv8 compiler.

**Comment by zhangyifu2016** [comment]
@ashwinyes You are right. I always thought I used an armv8 compiler form the beginning.

I have compiled it with armv8 compiler.
Thank you!
