### ISSUE TITLE
openblas compile error please see logs

### ISSUE THREAD

**Issue by ludi1981** [xianyi/OpenBLAS#1012]
Hi xianyi,

I downloaded OpenBLAS v0.2.15 and compiled with error. Please see my attachment. I tried P2 and nehalem cpu type. Could you please advise how I can fix this error? thanks.
My cpu is Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz
Linux version is RHEL6.5.
[make_log.zip](https://github.com/xianyi/OpenBLAS/files/588614/make_log.zip)

**Comment by martin-frbg** [comment]
>linktest.c:(.text+0x3591): undefined reference to `goto_set_num_threads'
linktest.c:(.text+0x70a1): undefined reference to `openblas_set_num_threads'
../libopenblas_nehalem-r0.2.15.so: undefined reference to `dsymv_thread_U'
...

To me this looks like you tried to build a multithreaded version first, and there are still files from that build around that clash with the current build. Can you try doing a "make clean" and then "make" again ?
(Also I'd update to current v0.2.19 unless you have a very specific reason to use 0.2.15. And E5-2690v3 is most likely Haswell not the older and less powerful Nehalem. Wasn't the cpu type detected automatically ?)

**Comment by brada4** [comment]
RHEL 6.5 needs tweaks from FAQ-s (namely devtoolset binutils)

... both your build logs are not after 'make clean'

**Comment by ludi1981** [comment]
thanks martin-frbg and brada4.

Yes. 'make clean' and set 'TARGET' to 'NEHALEM'. It wokrs.

**Comment by brada4** [comment]
It has to be TARGET=Haswell to employ AVX2 or TARGET=Sandybridge for AVX (first needs devtoolset binutils)
