### ISSUE TITLE
Does OpenBLAS support Intel Celeron series?

### ISSUE THREAD

**Issue by tjx0726** [xianyi/OpenBLAS#1013]
Hi
I want to install OpenBLAS on my laptop. However my laptop seems not to be very popular so that the installation failed. 
The CPU is Intel Celeron CPU N2810.

When will OpenBLAS support it?

**Comment by brada4** [comment]
Since October 16:
https://github.com/xianyi/OpenBLAS/commit/3409bccb21d10364e037cf3ef334dd97949ae9b1
i.e you need to get master branch, later version than 0.2.19
You can force Atom core on older versions

**Comment by brada4** [comment]
Did you manage to check?
