### ISSUE TITLE
OpenBLAS linking error

### ISSUE THREAD

**Issue by edavt** [xianyi/OpenBLAS#1021]
Hello!  I'm new to OpenBLAS.  I'm compiling it as part of TORCH and I keep getting linking errors:

../libopenblas_haswellp-r0.2.20.dev.a(blas_server.o): In function `exec_blas':
blas_server_omp.c:(.text+0x486): undefined reference to `GOMP_parallel'

I've read through the forums, but nothing is helping.  I'm running Ubuntu 15.10 with an Intel i7 6700 using gcc 4.9 (required by TORCH).  I've attached the gory details from the Make output.  THe actual MAKE command is:

                         make NO_AFFINITY=1 USE_OPENMP=1 CC='/usr/bin/gcc-4.9'

Any assistance would be greatly appreciated!
[blas.txt](https://github.com/xianyi/OpenBLAS/files/623392/blas.txt)

**Comment by brada4** [comment]
You also need to use older gfortran if you use old gcc (e.g. CC=gcc-6 FC=gfortran-6)
Ubuntu has hard time linking together modules from different compiler versions.

**Comment by martin-frbg** [comment]
Did you manage to get it working in the meantime, or would you like further assistance ?

**Comment by edavt** [comment]
Hi Folks

1) Thanks for the responses!  I've been pulled onto something else so I had to put this down for a few weeks.

2) I updated the gfortran links to use gfortran 4.9.  This did not resolve the issue.

Not sure where to go next.  Are any of the dependencies compiled on the fly that would lead to the compiler/linker version issue?

**Comment by martin-frbg** [comment]
Did you do a "make clean" before retrying the make, to get rid of any modules already compiled by the "wrong" version of gfortran ?

**Comment by edavt** [comment]
I removed all dependencies, deleted all folders and started from a fresh git pull.  I did some playing and I can compile it with USE_OPENMP=0.  However, give that I have an 8 core machine, I'd like to leverage that.

**Comment by martin-frbg** [comment]
Are you specifying the FC to use (like you did for CC in your first message), or is this picked automatically (and possibly still wrong if the "other" gfortran is still in the system search PATH) ? Perhaps try passing "-v" via FFLAGS to make the active gfortran write its version number to the build log, and/or check Makefile.conf for unexpected paths on the FEXTRALIB line

**Comment by edavt** [comment]
I'll try that.  I'm including the explicit path to both.  I also changed the symlinks to point to 4.9 for both.  GCC, G++ and GFortran --version return 4.9.

**Comment by edavt** [comment]
I don't see any issues.  My Makefile FEXTRALIB looks like this:

FEXTRALIB=-L/usr/local/cuda/lib64/../lib -L/home/edt/anaconda3/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.9 -L/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/home/edt/CUDNN/cuda/lib64 -L/home/edt/CUDNN/cuda/lib64 -L/usr/local/cuda/lib64 -L/lib/x86_64-linux-gnu -L/home/edt/anaconda3/lib -L/usr/lib/gcc/x86_64-linux-gnu/4.9/../../..  -lgfortran -lm -lgomp -lquadmath -lm -lpthread -lc

**Comment by martin-frbg** [comment]
Does anaconda3 come with its own copy of libgfortran perchance, or do you have one in /usr/local/cuda/lib ? Perhaps pruning or rearranging the -L entries in FEXTRALIB to move the gcc-4.9 ones to the front will help

**Comment by brada4** [comment]
Missing libgomp.so.* means that your GCC is not working/installed correcly.
Default in ubuntu 15.10 while it was supported was 5.2.1 and LUA (and inherently must be torch) is compiled using that.

**Comment by edavt** [comment]
A-ha!  Libgomp.so is in Anaconda/lib.  I'll clean up makefile.config and see what happens.

After spending 20 years with Windows C++/MatLab, I'm a little behind the learning curve here.  Anything I need to worry about when moving things around in FEXTRALIB?

I appreciate the help!!

**Comment by martin-frbg** [comment]
I expect you can simply remove the anaconda entries from FEXTRALIB, which should be sufficient for the system to find the correct one that belongs to gfortran 4.9

**Comment by brada4** [comment]
matlab also has gomp and gfortran libs around /usr in unlikely places.
Probably it is best to start with empty fextralib and add them one by one...

**Comment by edavt** [comment]
Thanks for all the help.  Anaconda was the culprit.  I got the library to compile and install.

Thanks again!
