### ISSUE TITLE
AR erorr: sorry - this program has been built without plugin support

### ISSUE THREAD

**Issue by Squall87** [xianyi/OpenBLAS#1022]
Hello!

I am trying to cross compile OpenBLAS for both Linux amd64 and Linux armhf.
I managed to build it for amd64 straight away, but I've been struggling about the armhf for three day so far.

I'm using the Linaro toolchain to cross compile it, specifically running:

`make  CC=arm-linux-gnueabihf-gcc-4.8.3 FC=arm-linux-gnueabihf-gfortran HOSTCC=gcc TARGET=CORTEXA15`

And it always ends up to this error:

> arm-linux-gnueabihf-gcc-ar  -ru ../libopenblas_cortexa15p-r0.2.19.a saxpy.o sswap.o scopy.o sscal.o sdot.o sdsdot.o dsdot.o sasum.o snrm2.o smax.o samax.o ismax.o isamax.o smin.o samin.o ismin.o isamin.o srot.o srotg.o srotm.o srotmg.o saxpby.o cblas_isamax.o cblas_sasum.o cblas_saxpy.o cblas_scopy.o cblas_sdot.o cblas_sdsdot.o cblas_dsdot.o cblas_srot.o cblas_srotg.o cblas_srotm.o cblas_srotmg.o cblas_sscal.o cblas_sswap.o cblas_snrm2.o cblas_saxpby.o sgemv.o sger.o strsv.o strmv.o ssymv.o ssyr.o ssyr2.o sgbmv.o ssbmv.o sspmv.o sspr.o sspr2.o stbsv.o stbmv.o stpsv.o stpmv.o cblas_sgemv.o cblas_sger.o cblas_ssymv.o cblas_strmv.o cblas_strsv.o cblas_ssyr.o cblas_ssyr2.o cblas_sgbmv.o cblas_ssbmv.o cblas_sspmv.o cblas_sspr.o cblas_sspr2.o cblas_stbmv.o cblas_stbsv.o cblas_stpmv.o cblas_stpsv.o sgemm.o ssymm.o strmm.o strsm.o ssyrk.o ssyr2k.o somatcopy.o simatcopy.o sgeadd.o cblas_sgemm.o cblas_ssymm.o cblas_strmm.o cblas_strsm.o cblas_ssyrk.o cblas_ssyr2k.o cblas_somatcopy.o cblas_simatcopy.o cblas_sgeadd.o sgetrf.o sgetrs.o spotrf.o sgetf2.o spotf2.o slaswp.o sgesv.o slauu2.o slauum.o strti2.o strtri.o daxpy.o dswap.o dcopy.o dscal.o ddot.o dasum.o dnrm2.o dmax.o damax.o idmax.o idamax.o dmin.o damin.o idmin.o idamin.o drot.o drotg.o drotm.o drotmg.o daxpby.o cblas_idamax.o cblas_dasum.o cblas_daxpy.o cblas_dcopy.o cblas_ddot.o cblas_drot.o cblas_drotg.o cblas_drotm.o cblas_drotmg.o cblas_dscal.o cblas_dswap.o cblas_dnrm2.o cblas_daxpby.o dgemv.o dger.o dtrsv.o dtrmv.o dsymv.o dsyr.o dsyr2.o dgbmv.o dsbmv.o dspmv.o dspr.o dspr2.o dtbsv.o dtbmv.o dtpsv.o dtpmv.o cblas_dgemv.o cblas_dger.o cblas_dsymv.o cblas_dtrmv.o cblas_dtrsv.o cblas_dsyr.o cblas_dsyr2.o cblas_dgbmv.o cblas_dsbmv.o cblas_dspmv.o cblas_dspr.o cblas_dspr2.o cblas_dtbmv.o cblas_dtbsv.o cblas_dtpmv.o cblas_dtpsv.o dgemm.o dsymm.o dtrmm.o dtrsm.o dsyrk.o dsyr2k.o domatcopy.o dimatcopy.o dgeadd.o cblas_dgemm.o cblas_dsymm.o cblas_dtrmm.o cblas_dtrsm.o cblas_dsyrk.o cblas_dsyr2k.o cblas_domatcopy.o cblas_dimatcopy.o cblas_dgeadd.o dgetrf.o dgetrs.o dpotrf.o dgetf2.o dpotf2.o dlaswp.o dgesv.o dlauu2.o dlauum.o dtrti2.o dtrtri.o caxpy.o caxpyc.o cswap.o ccopy.o cscal.o csscal.o cdotc.o cdotu.o scasum.o scnrm2.o scamax.o icamax.o scamin.o icamin.o csrot.o crotg.o caxpby.o cblas_icamax.o cblas_scasum.o cblas_caxpy.o cblas_ccopy.o cblas_cdotc.o cblas_cdotu.o cblas_cdotc_sub.o cblas_cdotu_sub.o cblas_cscal.o cblas_csscal.o cblas_cswap.o cblas_scnrm2.o cblas_caxpby.o cgemv.o cgeru.o cgerc.o ctrsv.o ctrmv.o csymv.o csyr.o csyr2.o cgbmv.o csbmv.o cspmv.o cspr.o cspr2.o ctbsv.o ctbmv.o ctpsv.o ctpmv.o chemv.o chbmv.o cher.o cher2.o chpmv.o chpr.o chpr2.o cblas_cgemv.o cblas_cgerc.o cblas_cgeru.o cblas_cgbmv.o cblas_chbmv.o cblas_chemv.o cblas_cher.o cblas_cher2.o cblas_chpmv.o cblas_chpr.o cblas_chpr2.o cblas_ctbmv.o cblas_ctbsv.o cblas_ctpmv.o cblas_ctpsv.o cblas_ctrmv.o cblas_ctrsv.o cgemm.o csymm.o ctrmm.o ctrsm.o csyrk.o csyr2k.o chemm.o cherk.o cher2k.o comatcopy.o cimatcopy.o cgeadd.o cblas_cgemm.o cblas_csymm.o cblas_ctrmm.o cblas_ctrsm.o cblas_csyrk.o cblas_csyr2k.o cblas_chemm.o cblas_cherk.o cblas_cher2k.o cblas_comatcopy.o cblas_cimatcopy.o cblas_cgeadd.o cgetrf.o cgetrs.o cpotrf.o cgetf2.o cpotf2.o claswp.o cgesv.o clauu2.o clauum.o ctrti2.o ctrtri.o zaxpy.o zaxpyc.o zswap.o zcopy.o zscal.o zdscal.o zdotc.o zdotu.o dzasum.o dznrm2.o dzamax.o izamax.o dzamin.o izamin.o zdrot.o zrotg.o zaxpby.o cblas_izamax.o cblas_dzasum.o cblas_zaxpy.o cblas_zcopy.o cblas_zdotc.o cblas_zdotu.o cblas_zdotc_sub.o cblas_zdotu_sub.o cblas_zscal.o cblas_zdscal.o cblas_zswap.o cblas_dznrm2.o cblas_zaxpby.o zgemv.o zgeru.o zgerc.o ztrsv.o ztrmv.o zsymv.o zsyr.o zsyr2.o zgbmv.o zsbmv.o zspmv.o zspr.o zspr2.o ztbsv.o ztbmv.o ztpsv.o ztpmv.o zhemv.o zhbmv.o zher.o zher2.o zhpmv.o zhpr.o zhpr2.o cblas_zgemv.o cblas_zgerc.o cblas_zgeru.o cblas_zgbmv.o cblas_zhbmv.o cblas_zhemv.o cblas_zher.o cblas_zher2.o cblas_zhpmv.o cblas_zhpr.o cblas_zhpr2.o cblas_ztbmv.o cblas_ztbsv.o cblas_ztpmv.o cblas_ztpsv.o cblas_ztrmv.o cblas_ztrsv.o zgemm.o zsymm.o ztrmm.o ztrsm.o zsyrk.o zsyr2k.o zhemm.o zherk.o zher2k.o zomatcopy.o zimatcopy.o zgeadd.o cblas_zgemm.o cblas_zsymm.o cblas_ztrmm.o cblas_ztrsm.o cblas_zsyrk.o cblas_zsyr2k.o cblas_zhemm.o cblas_zherk.o cblas_zher2k.o cblas_zomatcopy.o cblas_zimatcopy.o cblas_zgeadd.o zgetrf.o zgetrs.o zpotrf.o zgetf2.o zpotf2.o zlaswp.o zgesv.o zlauu2.o zlauum.o ztrti2.o ztrtri.o
error		sorry - this program has been built without plugin support

Any suggestions?

**Comment by martin-frbg** [comment]
This http://www.spinics.net/lists/gcchelp/msg35938.html makes it look like a fault in the Linaro toolchain,
or the wrong copy of ar gets called by the arm-...-gcc-ar wrapper

**Comment by martin-frbg** [comment]
Did you find a solution for this ? (If you cannot change the toolchain, perhaps you can work around the issue by providing an AR= argument to make that points to the actual "ar" rather than a wrapper - if indeed the wrapper is the problem)

**Comment by Squall87** [comment]
yes Martin, you were right: it was because a faulty AR binary in the Linaro toolchain. I tried to make the AR pointing to the actual one, but I couldn't manage to make it work that way.
Then I tried another toolchain (the ubuntu one) and it simply worked straightaway.
