### ISSUE TITLE
CBLAS-Testing - Error in cblas_[c,z]her2k and cblas_[c,z]syr2k on IBM Power 8

### ISSUE THREAD

**Issue by grisuthedragon** [xianyi/OpenBLAS#1023]
After compiling the current development branch of OpenBLAS on an IBM Power 8 system and running the CBLAS test suite (out of http://www.netlib.org/blas/blast-forum/cblas.tgz)  I got the following computational errors: 

Complex Single Precision: 
```
 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
                       EXPECTED RESULT                    COMPUTED RESULT
       1  (   0.585866E-01,   0.831542E-01)  (   0.544071E-01,   0.858043E-01)
       2  (  -0.386742E-01,  -0.956527E-01)  (  -0.301157E-01,  -0.982754E-01)
       3  (  -0.521090E-01,  -0.110169    )  (  -0.666067E-01,  -0.100567    )
       4  (  -0.395289E-01,   0.674874E-02)  (  -0.395289E-01,    0.00000    )
      THESE ARE THE RESULTS FOR COLUMN   4
 ******* cblas_cher2k FAILED ON CALL NUMBER:
   1120: cblas_cher2k( CblasColMajor,    CblasUpper,  CblasNoTrans,
            9,  1, ( 1.0, 0.0), A, 10, B 10, 0.0, C, 10).
 ******* cblas_cher2k FAILED ON CALL NUMBER:
    217: cblas_cher2k( CblasRowMajor,    CblasUpper,  CblasNoTrans,
            1,  0, ( 0.0, 0.0), A,  2, B  2, 0.0, C,  2).


 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
                       EXPECTED RESULT                    COMPUTED RESULT
       1  (  -0.998673E-01,   0.215587E-01)  (  -0.100679    ,   0.166547E-01)
       2  (   0.367265E-01,  -0.153457E-01)  (   0.377764E-01,  -0.120559E-01)
       3  (   0.150602    ,  -0.266754E-01)  (   0.143768    ,  -0.474012E-01)
       4  (   0.175306E-01,  -0.426881E-01)  (   0.241157E-01,  -0.385708E-01)
      THESE ARE THE RESULTS FOR COLUMN   4
 ******* cblas_csyr2k FAILED ON CALL NUMBER:
   1120: cblas_csyr2k( CblasColMajor,    CblasUpper,  CblasNoTrans,
            9,  1, ( 1.0, 0.0), A, 10, B 10, ( 0.0, 0.0), C, 10).
 ******* cblas_csyr2k FAILED ON CALL NUMBER:
    217: cblas_csyr2k( CblasRowMajor,    CblasUpper,  CblasNoTrans,
            1,  0, ( 0.0, 0.0), A,  2, B  2, ( 0.0, 0.0), C,  2).
```

and for Complex Double Precision: 
```
 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
                       EXPECTED RESULT                    COMPUTED RESULT
       1  (   0.618795E-01,   0.810662E-01)  (   0.544071E-01,   0.858043E-01)
       2  (  -0.349027E-01,  -0.968084E-01)  (  -0.301157E-01,  -0.982754E-01)
       3  (  -0.753648E-01,  -0.947662E-01)  (  -0.666067E-01,  -0.100567    )
       4  (  -0.395289E-01,   0.192543E-02)  (  -0.395289E-01,    0.00000    )
      THESE ARE THE RESULTS FOR COLUMN   4
 ******* cblas_zher2k FAILED ON CALL NUMBER:
   1120: cblas_zher2k( CblasColMajor,    CblasUpper,  CblasNoTrans,
            9,  1, ( 1.0, 0.0), A, 10, B 10, 0.0, C, 10).
 ******* cblas_zher2k FAILED ON CALL NUMBER:
    217: cblas_zher2k( CblasRowMajor,    CblasUpper,  CblasNoTrans,
            1,  0, ( 0.0, 0.0), A,  2, B  2, 0.0, C,  2).


 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
                       EXPECTED RESULT                    COMPUTED RESULT
       1  (  -0.992281E-01,   0.254224E-01)  (  -0.100679    ,   0.166547E-01)
       2  (   0.371892E-01,  -0.138959E-01)  (   0.377764E-01,  -0.120559E-01)
       3  (   0.139640    ,  -0.599215E-01)  (   0.143768    ,  -0.474012E-01)
       4  (   0.222370E-01,  -0.397455E-01)  (   0.241157E-01,  -0.385708E-01)
      THESE ARE THE RESULTS FOR COLUMN   4
 ******* cblas_zsyr2k FAILED ON CALL NUMBER:
   1120: cblas_zsyr2k( CblasColMajor,    CblasUpper,  CblasNoTrans,
            9,  1, ( 1.0, 0.0), A, 10, B 10, ( 0.0, 0.0), C, 10).
 ******* cblas_zsyr2k FAILED ON CALL NUMBER:
    217: cblas_zsyr2k( CblasRowMajor,    CblasUpper,  CblasNoTrans,
            1,  0, ( 0.0, 0.0), A,  2, B  2, ( 0.0, 0.0), C,  2).

```

The used system is and Ubuntu 16.04 ppc64le on an IBM Power8 (POWER8NVL) with gcc (Ubuntu/IBM 5.4.0-6ubuntu1~16.04.4).

**Comment by brada4** [comment]
Which test?

**Comment by grisuthedragon** [comment]
I compiled the CBLAS package and linked it to openblas and there I got the results above for both level 3 complex test suites.

**Comment by martin-frbg** [comment]
Perhaps try setting zscal in kernel/power/KERNEL.POWER8 to the generic reference code (ZSCALKERNEL=../arm/zscal.c) or just try reverting the fix for #929 first (as it appears to be the latest change in that area) ?

**Comment by grisuthedragon** [comment]
I tried both, changing the kernel to the generic one and reverting the fix of #929 but nothing changes. I also tested the following setup: 

Compile OpenBLAS using `make NO_CBLAS=1 NO_LAPACK=1` and use the complete CBLAS interface from Netlib and the same error occurs again.

**Comment by martin-frbg** [comment]
Does it work with pure netlib BLAS then (just to rule out compiler or hardware problems), or after removing any optimization from the compiler options (in case either the compiler or the expectation of the test is too optimistic) ?

**Comment by grisuthedragon** [comment]
Using the netlib reference implementation compiled with the O3 optimization and without does not produce this error. From this point of view everything works fine.

**Comment by martin-frbg** [comment]
Sorry about the bad hunch regarding zscal, perhaps try reverting the ZGEMMKERNEL entry in KERNEL.POWER8 to the generic one instead ?

**Comment by grisuthedragon** [comment]
I comment out all [Z,C]GEMM lines in KERNEL.POWER8 to only work with the generic implementation and than even the Fortran-BLAS tests done by OpenBLAS fail.

**Comment by martin-frbg** [comment]
Poking around in the driver/level3 files these were the only candidates I could identify, so it seems I am
out of my depth here. One last suggestion though - do you see the same errors with a single thread (assuming that your power8nvr build is multithreading by default) ?

**Comment by grisuthedragon** [comment]
I check it once by setting the threads at runtime and a second time by compiling it with `NUM_THREADS=1` and in both cases it fails with the same results.

**Comment by martin-frbg** [comment]
It seems to me that the ctest subdirectory of OpenBLAS is identical to the netlib-CBLAS testing one save for a handful of recent bugfixes. Did you change any parameters in the tests (there is an old issue still open about tests apparently failing if one increases N beyond a certain threshold) or does the OpenBLAS Makefile for POWER architecture not run the tests automatically at the end of the 
build process ? (What does "make tests" in the OpenBLAS build directory report on your Power8 machine ?)

**Comment by grisuthedragon** [comment]
I figured out that there where no significant differences in the testing data. But the CBLAS tests inside OpenBLAS proceed without errors.  I start checking the difference between the CBLAS inside OpenBLAS and the cblas.tgz and the one from the lapack-reference repository.

**Comment by martin-frbg** [comment]
One important aspect is that the difference would have to be such that it affects only specific platforms - I could not reproduce your issue on x86 (with both Haswell and Nehalem builds).

**Comment by grisuthedragon** [comment]
I reimported the whole C BLAS interface from LAPACK's git repository and the error is fixed.  So from this point of view the version provided as reference on the netlib website is not usable.

**Comment by martin-frbg** [comment]
Sorry, it is not quite clear to me what you did here - did you get it working (only) by overwriting the cblas part of your OpenBLAS tree with netlib cblas, which would still point at an error in OpenBLAS, or are you assuming something went wrong with your earlier test setup ?

**Comment by grisuthedragon** [comment]
I reproduced a similar error with ATLAS as blas implementation and so  it seems to that the bug lies inside the reference  Cblas implementation and not in openblas
