### ISSUE TITLE
arm-linux-androideabi-g++ Compiler Error in /cpuid_arm.c

### ISSUE THREAD

**Issue by mfoster96** [xianyi/OpenBLAS#1024]
**int get_feature(char *search)**

Line 77: 	if( p == NULL ) return;

Compiler requires non-void function to return a value;

**Comment by martin-frbg** [comment]
That's one picky compiler (but it is right of course). Does the build run to completion when you change that line to end with "return 0" ?

**Comment by mfoster96** [comment]
Yes! Thanks

**Comment by martin-frbg** [comment]
Great. Would you like to prepare a pull request with the fix, or should I ?

**Comment by mfoster96** [comment]
I created a pull request. Thank you.
