### ISSUE TITLE
How to build Android version openblas when armeabi-v7a-hard is no longer supported by ndk

### ISSUE THREAD

**Issue by austingg** [xianyi/OpenBLAS#1026]
Since the new ndk  no longer supports armeabi-v7a-hard abi, how to build and use openblas in android or arm?

**Comment by martin-frbg** [comment]
See build script and documentation at the end of #963 please.

**Comment by austingg** [comment]
@martin-frbg  great material. but that still armeabi-v7a-hard, I will try when use CFLAGS and LDFLAGS

**Comment by martin-frbg** [comment]
Sorry, I missed the significance of that aspect as I am far from being familiar with this platform. 
It seems that the resolved issues concerning building with (beta versions of) NDK 12 were all about building for arm64 so their eventual success after fixing paths and cflags may be of little value to you.
Discussions in #853 suggest that a rewrite of at least the register part of the affected assembly routines would be required to restore compatibility with NDK12 and beyond for ARMV7, so it might be easier to stay with NDK11 until everybody wants to use aarch64 anyway.

**Comment by brada4** [comment]
You can build ARMV5 target which has only C kernels and no assembly at all.

**Comment by austingg** [comment]
thanks @martin-frbg and @ brada4. I successfully build the android version openblas on armeabi-v7a after I carefully reference the wiki.

**Comment by xiaodaxia** [comment]
@austingg I had the same question with you and in your solution, you said carefully reference the wiki, do you mean the wiki at the following location
[https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android#linking-openblas-for-armv7](url)
I am a bit confused, as when I use flags like the wiki page,
CFLAGS += -mhard-float -D_NDK_MATH_NO_SOFTFP=1
LDFLAGS += -Wl,--no-warn-mismatch -lm_hard
I got the error  solved by this issue[https://github.com/xianyi/OpenBLAS/issues/853](url). The linker always complain the error "uses VFP register arguments, output does not", so I am writing to you for help.
How would modify the Android.mk or Application.mk, or adding CFLAGS and LDFLAGS will make openblas work with android armeabi-v7a platform.

**Comment by austingg** [comment]
@xiaodaxia yes，I reference that wiki.  
You may try TARGETS_CLFLAGS and TARGETS_LDFLAGS for a quick test. 
if that failed, paste some code of your Android.mk to show how you line the openblas,  then I can help you fix the problem.

**Comment by xiaodaxia** [comment]
Thanks for your help! It did work.
Also note the correct macro is TARGET_CFLAGS and TARGET_LDFLAGS.

**Comment by austingg** [comment]
@xiaodaxia  great!  I have updated the wiki for people who want to use openblas on Android.

**Comment by xianyi** [comment]
Thank you for the update.
