### ISSUE TITLE
Build error when using DYNAMIC_ARCH=1 inside a virtual machine

### ISSUE THREAD

**Issue by knedlsepp** [xianyi/OpenBLAS#1027]
I am inside a KVM virtual machine, which has generic CPU-Information
```
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 2
model name      : QEMU Virtual CPU version 1.0
stepping        : 3
microcode       : 0x1
cpu MHz         : 2899.998
cache size      : 4096 KB
fpu             : yes
fpu_exception   : yes
cpuid level     : 4
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm rep_good nopl pni vmx cx16 popcnt hypervisor lahf_lm
bogomips        : 5799.99
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:
```
The build fails with the error:
```
getarch_2nd.c:12:35: error: ‘SGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function)
     printf("SGEMM_UNROLL_M=%d\n", SGEMM_DEFAULT_UNROLL_M);
```
even though `DYNAMIC_ARCH=1` is used during configuration, which indicates that the CPU was not detected properly.
My expected behaviour is that the build should generate a generic library.
Is it really necessary to set the `TARGET`, as it is done e.g. in the .travis.yml: https://github.com/xianyi/OpenBLAS/blob/develop/.travis.yml ?

**Comment by martin-frbg** [comment]
Seems your virtual machine received  a set of cpu capabilities that matches no "known" actual processor model, so choosing a TARGET becomes necessary.

**Comment by knedlsepp** [comment]
@martin-frbg: I'd like to be able to build a general version of openblas (which I was expecting to get with DYNAMIC_ARCH) which would run fine (and preferably fast) on all machines I'd copy the binary to.

**Comment by martin-frbg** [comment]
DYNAMIC_ARCH build will still contain all available cpu-specific codes for the architecture (and runtime cpu detection to choose one), but the build still needs to know what the cpu in the build host is.

**Comment by knedlsepp** [comment]
@martin-frbg: I don't quite understand why the build needs to know which cpu architecture the build host has. Shouldn't the build be independent of the build-host cpu-type?

**Comment by martin-frbg** [comment]
Could be something as mundane as the DYNAMIC_ARCH of being a later add-on on top of the host-specific build, or to be able to run the tests as part of the build process (not sure if current versions still do this for DYNAMIC_ARCH builds, but the general code dates back to libgoto). Probably not worth rewriting the build system just to save a small fraction of the user base the trouble of configuring a "sane" cpu in their emulator.

**Comment by brada4** [comment]
As years old faq says - expose realistic CPU (or look in Makefile.rule to avoid reality checks)
https://github.com/xianyi/OpenBLAS/wiki/faq#qemu

**Comment by martin-frbg** [comment]
I see that this has now been addressed in the original context (nixOS) by supplying a low-featured cpu type as a TARGET to the build task. Any objections to closing this here as well ?

**Comment by knedlsepp** [comment]
For me personally it solves the problem, so I don't oppose closing the issue.
