### ISSUE TITLE
Build error: gfortran: error: libgfortran.spec: No such file or directory

### ISSUE THREAD

**Issue by andrewrech** [xianyi/OpenBLAS#1029]
I receive the following error when building and am not sure how to proceed.

> make[2]: Entering directory '/root/OpenBLAS/lapack-netlib/INSTALL'
> gfortran -pthread -Wall -m64 -fPIC -lm -lpthread -lgfortran -o testlsame lsame.o lsametst.o
> gfortran -pthread -Wall -m64 -fPIC -lm -lpthread -lgfortran -o testslamch slamch.o lsame.o slamchtst.o
> gfortran -pthread -Wall -m64 -fPIC -lm -lpthread -lgfortran -o testdlamch dlamch.o lsame.o dlamchtst.o
> gfortran: error: libgfortran.spec: No such file or directory

```shell
gfortran --version
```

```
Using built-in specs.
COLLECT_GCC=gfortran
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.1-2ubuntu1~16.04' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.1 20160904 (Ubuntu 5.4.1-2ubuntu1~16.04)
```

```shell
gcc --version
```

```
Using built-in specs.
COLLECT_GCC=gcc
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.1-2ubuntu1~16.04' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.1 20160904 (Ubuntu 5.4.1-2ubuntu1~16.04)
```

`find / -name libgfortran.spec` returns 

> /usr/lib/gcc-snapshot/lib32/libgfortran.spec
> /usr/lib/gcc-snapshot/lib/libgfortran.spec
> /usr/lib/gcc-snapshot/libx32/libgfortran.spec

I tried adding these directories to PATH / LD_LIBRARY_PATH.

Thank you

**Comment by martin-frbg** [comment]
Could it be that you have/had several versions of gfortran installed, and the /usr/lib/gcc-snapshot/lib/libgfortran.spec belongs to a different version ? (The other two appear to be 32bit versions so would be not relevant for a 64bit compile). What does "gfortran --version" return (the gcc appears to be a snapshot of 5.4.1) ?

**Comment by brada4** [comment]
Could you remove outdated gcc snapshot and use system compiler instead? (Should be 5.3.1 a system compiler and 6.2.1 as snapshot, I suspect you are trying to use leftovers that were not upgraded by major system upgrade)

**Comment by andrewrech** [comment]
Thank you Martin and Brad for your helpful comments that pointed me in the right direction. I did indeed have several versions of gfortran installed. I removed all versions of gcc and gfortran and then re-installed a single version, set my $PATH appropriately, and compiled without an issue.

**Comment by akruppa** [comment]
I just ran into the same error message while compiling Sage. I had Fortran libraries installed from the OpenSuse Leap 15.0 distribution, but not the Fortran compiler. Is it possible that this combination trips your build system?

After installing the Fortran compiler from OpenSuse dist package, the compilation proceeded fine. If you need more info about my build system, please let me know.

**Comment by Sherry112** [comment]
I am facing this issue again. I am trying to compile OpenBlas inside Yocto environment. Added below are the logs. i have tried  the latest version of OpenBlas and it also throws the same error.

> Log data follows:
> | DEBUG: Executing shell function do_configure
> | -- The C compiler identification is GNU 8.3.0
> | -- The ASM compiler identification is GNU
> | -- Found assembler: /home/ubuntu/code/iot-device-yocto-systec/build/tmp/work/aarch64-poky-linux/openblas/0.3.14-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc
> | -- Check for working C compiler: /home/ubuntu/code/iot-device-yocto-systec/build/tmp/work/aarch64-poky-linux/openblas/0.3.14-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc
> | -- Check for working C compiler: /home/ubuntu/code/iot-device-yocto-systec/build/tmp/work/aarch64-poky-linux/openblas/0.3.14-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc -- works
> | -- Detecting C compiler ABI info
> | -- Detecting C compiler ABI info - done
> | -- Detecting C compile features
> | -- Detecting C compile features - done
> | CMake Warning at CMakeLists.txt:70 (message):
> |   CMake support is experimental.  It does not yet support all build options
> |   and may not produce the same Makefiles that OpenBLAS ships with.
> |
> |
> | -- Looking for stdatomic.h
> | -- Looking for stdatomic.h - found
> | -- -- -- -- -- -- -- -- -- -- -- -- -- --
> | -- Targeting the ARMV8 architecture.
> | -- GEMM multithread threshold set to 4.
> | -- Looking for a Fortran compiler
> | -- Looking for a Fortran compiler - /home/ubuntu/code/iot-device-yocto-systec/build/tmp/work/aarch64-poky-linux/openblas/0.3.14-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gfortran
> | -- The Fortran compiler identification is GNU 8.3.0
> | -- Check for working Fortran compiler: /home/ubuntu/code/iot-device-yocto-systec/build/tmp/work/aarch64-poky-linux/openblas/0.3.14-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gfortran
> | -- Check for working Fortran compiler: /home/ubuntu/code/iot-device-yocto-systec/build/tmp/work/aarch64-poky-linux/openblas/0.3.14-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gfortran  -- broken
> | CMake Error at /home/ubuntu/code/iot-device-yocto-systec/build/tmp/work/aarch64-poky-linux/openblas/0.3.14-r0/recipe-sysroot-native/usr/share/cmake-3.16/Modules/CMakeTestFortranCompiler.cmake:45 (message):
> |   The Fortran compiler
> |
> |     "/home/ubuntu/code/iot-device-yocto-systec/build/tmp/work/aarch64-poky-linux/openblas/0.3.14-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gfortran"
> |
> |   is not able to compile a simple test program.
> |
> |   It fails with the following output:
> |
> |     Change Dir: /home/ubuntu/code/iot-device-yocto-systec/build/tmp/work/aarch64-poky-linux/openblas/0.3.14-r0/build/CMakeFiles/CMakeTmp
> |
> |     Run Build Command(s):ninja cmTC_516cf && [1/4] Building Fortran preprocessed CMakeFiles/cmTC_516cf.dir/testFortranCompiler.f-pp.f
> |     [2/4] Generating Fortran dyndep file CMakeFiles/cmTC_516cf.dir/Fortran.dd
> |     [3/4] Building Fortran object CMakeFiles/cmTC_516cf.dir/testFortranCompiler.f.o
> |     [4/4] Linking Fortran executable cmTC_516cf
> |     FAILED: cmTC_516cf
> |     : && /home/ubuntu/code/iot-device-yocto-systec/build/tmp/work/aarch64-poky-linux/openblas/0.3.14-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gfortran  -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fstack-protector-strong -Wl,-z,relro,-z,now  CMakeFiles/cmTC_516cf.dir/testFortranCompiler.f.o  -o cmTC_516cf   && :
> |     aarch64-poky-linux-gfortran: error: libgfortran.spec: No such file or directory
> |     ninja: build stopped: subcommand failed.
> |
> |
> |
> |
> |
> |   CMake will not be able to correctly generate this project.
> | Call Stack (most recent call first):
> |   cmake/f_check.cmake:27 (enable_language)
> |   cmake/prebuild.cmake:89 (include)
> |   cmake/system.cmake:148 (include)
> |   CMakeLists.txt:73 (include)
> |
> |
> | -- Configuring incomplete, errors occurred!
> | See also "/home/ubuntu/code/iot-device-yocto-systec/build/tmp/work/aarch64-poky-linux/openblas/0.3.14-r0/build/CMakeFiles/CMakeOutput.log".
> | See also "/home/ubuntu/code/iot-device-yocto-systec/build/tmp/work/aarch64-poky-linux/openblas/0.3.14-r0/build/CMakeFiles/CMakeError.log".
> | WARNING: exit code 1 from a shell command.
> | ERROR: Execution of '/home/ubuntu/code/iot-device-yocto-systec/build/tmp/work/aarch64-poky-linux/openblas/0.3.14-r0/temp/run.do_configure.27098' failed with exit code 1:
> | -- The C compiler identification is GNU 8.3.0
> | -- The ASM compiler identification is GNU
> | -- Found assembler: /home/ubuntu/code/iot-device-yocto-systec/build/tmp/work/aarch64-poky-linux/openblas/0.3.14-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc
> | -- Check for working C compiler: /home/ubuntu/code/iot-device-yocto-systec/build/tmp/work/aarch64-poky-linux/openblas/0.3.14-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc
> | -- Check for working C compiler: /home/ubuntu/code/iot-device-yocto-systec/build/tmp/work/aarch64-poky-linux/openblas/0.3.14-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc -- works
> | -- Detecting C compiler ABI info
> | -- Detecting C compiler ABI info - done
> | -- Detecting C compile features
> | -- Detecting C compile features - done
> | CMake Warning at CMakeLists.txt:70 (message):
> |   CMake support is experimental.  It does not yet support all build options
> |   and may not produce the same Makefiles that OpenBLAS ships with.
> |
> |
> | -- Looking for stdatomic.h
> | -- Looking for stdatomic.h - found
> | -- -- -- -- -- -- -- -- -- -- -- -- -- --
> | -- Targeting the ARMV8 architecture.
> | -- GEMM multithread threshold set to 4.
> | -- Looking for a Fortran compiler
> | -- Looking for a Fortran compiler - /home/ubuntu/code/iot-device-yocto-systec/build/tmp/work/aarch64-poky-linux/openblas/0.3.14-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gfortran
> | -- The Fortran compiler identification is GNU 8.3.0
> |                                                                                                                                                                                                  [10/1836]
> | -- Looking for stdatomic.h
> | -- Looking for stdatomic.h - found
> | -- -- -- -- -- -- -- -- -- -- -- -- -- --
> | -- Targeting the ARMV8 architecture.
> | -- GEMM multithread threshold set to 4.
> | -- Looking for a Fortran compiler
> | -- Looking for a Fortran compiler - /home/ubuntu/code/iot-device-yocto-systec/build/tmp/work/aarch64-poky-linux/openblas/0.3.14-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gfo
> rtran
> | -- The Fortran compiler identification is GNU 8.3.0
> | -- Check for working Fortran compiler: /home/ubuntu/code/iot-device-yocto-systec/build/tmp/work/aarch64-poky-linux/openblas/0.3.14-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gfortran
> | -- Check for working Fortran compiler: /home/ubuntu/code/iot-device-yocto-systec/build/tmp/work/aarch64-poky-linux/openblas/0.3.14-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux$gfortran  -- broken
> | CMake Error at /home/ubuntu/code/iot-device-yocto-systec/build/tmp/work/aarch64-poky-linux/openblas/0.3.14-r0/recipe-sysroot-native/usr/share/cmake-3.16/Modules/CMakeTestFortranCompiler.cmake:45 (messa$e):
> |   The Fortran compiler
> |
> |     "/home/ubuntu/code/iot-device-yocto-systec/build/tmp/work/aarch64-poky-linux/openblas/0.3.14-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gfortran"
> |
> |   is not able to compile a simple test program.
> |
> |   It fails with the following output:
> |
> |     Change Dir: /home/ubuntu/code/iot-device-yocto-systec/build/tmp/work/aarch64-poky-linux/openblas/0.3.14-r0/build/CMakeFiles/CMakeTmp
> |
> |     Run Build Command(s):ninja cmTC_516cf && [1/4] Building Fortran preprocessed CMakeFiles/cmTC_516cf.dir/testFortranCompiler.f-pp.f
> |     [2/4] Generating Fortran dyndep file CMakeFiles/cmTC_516cf.dir/Fortran.dd
> |     [3/4] Building Fortran object CMakeFiles/cmTC_516cf.dir/testFortranCompiler.f.o
> |     [4/4] Linking Fortran executable cmTC_516cf
> |     FAILED: cmTC_516cf
> |     : && /home/ubuntu/code/iot-device-yocto-systec/build/tmp/work/aarch64-poky-linux/openblas/0.3.14-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gfortran  -Wl,-O1 -Wl,--hash-$tyle=gnu -Wl,--as-needed -fstack-protector-strong -Wl,-z,relro,-z,now  CMakeFiles/cmTC_516cf.dir/testFortranCompiler.f.o  -o cmTC_516cf   && :
> |     aarch64-poky-linux-gfortran: error: libgfortran.spec: No such file or directory
> |     ninja: build stopped: subcommand failed.

I have gcc version 8.3 which I using from [here](https://github.com/OE4T/meta-tegra/tree/dunfell-l4t-r32.4.3/contrib/recipes-devtools/gcc-8)

These are my build configs:

> Build Configuration:
> BB_VERSION           = "1.46.0"
> BUILD_SYS            = "x86_64-linux"
> NATIVELSBSTRING      = "universal"
> TARGET_SYS           = "aarch64-poky-linux"
> MACHINE              = "edgedev"
> DISTRO               = "poky"
> DISTRO_VERSION       = "3.1.3"
> TUNE_FEATURES        = "aarch64 armv8a crc"
> TARGET_FPU           = ""
> meta-edgedev         = "feature/netclient-vpn:b1c6f00d29462ca004706110b9dca56ade526c58"
> meta-tegra           = "dunfell-l4t-r32.4.3:bfafb644fca4c77a2599f2ce34e7c61dd96ec2f8"
> meta-java            = "HEAD:6e84638d77ac921aac46649095bca5ddbde94d2a"
> meta-virtualization  = "HEAD:ff997b6b3ba800978546098ab3cdaa113b6695e1"
> meta-filesystems
> meta-networking
> meta-oe
> meta-python          = "HEAD:2a5c534d2b9f01e9c0f39701fccd7fc874945b1c"
> meta
> meta-poky
> meta-yocto-bsp       = "HEAD:2aed817e09567bd1812ce75e9fa95852ceec7a8a"
> meta-laird-cp        = "HEAD:08e137f78234615046bc56fb7fcf679941546bec"
> meta-aws             = "HEAD:e34ed15a87e36fa4199c63a184630fa370abac55"
> meta-rauc            = "dunfell:9a160b970bb1586472dcbfe1020338b2fc0ed437"
> contrib              = "dunfell-l4t-r32.4.3:bfafb644fca4c77a2599f2ce34e7c61dd96ec2f8"

**Comment by martin-frbg** [comment]
No experience with that platform, but this does look like an installation problem with the compiler - do you have a libgfortran.spec somewhere in your /home/ubuntu/code/iot-device-yocto-systec/build/tmp/work/aarch64-poky-linux/openblas/0.3.14-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux ? (If you have both .../recipe-sysroot-native/usr/lib and .../recipe-sysroot-native/usr/lib64 and a libgfortran.spec is only in one of them, try copying it to the other.)
