### ISSUE TITLE
increase default threading cutoff

### ISSUE THREAD

**Issue by JeffBezanson** [xianyi/OpenBLAS#103]
With OPENBLAS_NUM_THREADS=1:

julia> a=rand(10,10); @time for i=1:100000; a*a; end
elapsed time: 0.11344099044799805 seconds

With OPENBLAS_NUM_THREADS=2:

julia> a=rand(10,10); @time for i=1:100000; a*a; end
elapsed time: 0.23067402839660645 seconds

This is openblas v0.1.1 on a core i5 650. There seems to be a slowdown for small matrices with threads enabled. In the same setup I see nice speedups for big matrices, e.g. over 100x100.

Can anything be done about this? Setting OPENBLAS_NUM_THREADS is easy, but we'd rather get the best of both worlds if possible :)

**Comment by ViralBShah** [comment]
In Julia, we have been using 50 as the threshold which works well. Given that there is a way to address this in the build system, this could be closed.

**Comment by martin-frbg** [comment]
I find it worrying that your threshold of 50 is so far from the current default, and if anything the threading behaviour has become more complicated with individual magic numbers used as threshold
values in specific BLAS functions. So I am hesitating to close this - at the very least, the description
of this parameter in Makefile.rule should be amended to make it clear that the sane range of values
extends to (or it seems some may think, begins around) 50. 
On reviewing this thread, there was also a comment by jiahao https://github.com/xianyi/OpenBLAS/issues/103#issuecomment-38914601 about improvements seen with choosing a different OpenMP loop scheduler in blas_server_omp, which sadly elicited no response. Thoughts ?

**Comment by ViralBShah** [comment]
I'm not familiar with the openmp work, but one issue is that openmp is not available on all the platforms/OS combinations.

**Comment by martin-frbg** [comment]
> one issue is that openmp is not available on all the platforms

I am certainly aware of that. I see OpenMP in this context as a subtopic that got buried quickly the first time it came up, and I would like to get some comment on it before it gets buried again. A speed gain
from switching away from the "static" scheduler would appear to suggest an unbalanced workload where some threads take longer than others  ?(Though the example given in https://github.com/JuliaLang/julia/issues/3239#issuecomment-38355077 was a bit vague in that it picked the `auto` scheduler without determining what the compiler chose).

**Comment by martin-frbg** [comment]
My own experiments with the OMP scheduler were a bit inconclusive - which scheduler works best seems to depend very much on the functions and workload, so #1620 makes the choice available at
build time (or by picking the runtime scheduler, even at runtime through setting OMP_SCHEDULE).
I have also documented the changed meaning of GEMM_MULTITHREAD_THRESHOLD in Makefile.rule and Julia*s use of the value 50 there.

**Comment by nalimilan** [comment]
Wouldn't it make sense to increase the default value of `GEMM_MULTITHREAD_THRESHOLD`? Given how far it is from Julia's choice, either OpenBLAS or Julia use a bad value.

**Comment by martin-frbg** [comment]
So far there does not appear to be consensus on what the good value is. The last time the threshold was changed, it was reverted quickly (#216), though inconsistent use of the variable in GEMM vs GEMV may have been an issue back then. With new contributors taking a fresh look on the threading behaviour of OpenBLAS now I hope this will eventually be resolved.
