### ISSUE TITLE
scipy.linalg.test result = 0-th dimension must be fixed to _ but got _

### ISSUE THREAD

**Issue by cvax** [xianyi/OpenBLAS#1035]
Is this a problem? https://github.com/xianyi/OpenBLAS/issues/783 didn't state one way or another if these 0-th dimensions were a pass or not... 
I am running scipy.linalg.test() on a core i7 2640m sandy bridge laptop and get this.

```
....................................................................................................0-th dimension must be fixed to 3 but got 15
..0-th dimension must be fixed to 3 but got 5
..............0-th dimension must be fixed to 4 but got 2
0-th dimension must be fixed to 4 but got 2
.0-th dimension must be fixed to 4 but got 2
0-th dimension must be fixed to 4 but got 2
.0-th dimension must be fixed to 4 but got 2
0-th dimension must be fixed to 4 but got 2
0-th dimension must be fixed to 4 but got 2
0-th dimension must be fixed to 4 but got 2
0-th dimension must be fixed to 4 but got 2
0-th dimension must be fixed to 4 but got 2
................................
```
Thanks for the help.

**Comment by martin-frbg** [comment]
I'm not that experienced with python, but the trivial answer seems to be - if it does not print FAIL: after the fragment you quoted the tests passed. (As confirmend by the first comments from jeromerobert and matthew-brett in the issue you linked to)
From what I gather, the "0-th dimension must be fixed to" warnings translate to something like "formally that function was declared to expect a vector of X arguments but you called it with Y elements here". Probably harmless if the function actually accepts a variable number of arguments, but perhaps put this question to the scipy folks whose code it is ?

**Comment by brada4** [comment]
If you use Debian or similar scipy you might be calling very old netlib lapack as a wrapper around quite old openblas (later comes with extra configuration). 
Can you make minimal effort to convince that any openblas is actually used and the result you are getting is different from atlas or netlib blas or any other competing library of your choice?

**Comment by martin-frbg** [comment]
@brada4 is that really necessary given the previous discussion in #783 that cvax wanted clarified ?

**Comment by brada4** [comment]
If problem is in e.g. Ubuntu LTS libopenblas-base = 0.2.8-6ubuntu1 I dont think this is right place to get reminded LTS means old versions you have to cope with...

**Comment by martin-frbg** [comment]
Methinks the "problem" is at most one of sloppy coding (or excessive warning level) in the tests (at least as long as we are talking about the "dimension must be fixed to..." with no FAIL in the summary). Hence my suggestion to take it up with the scipy project if desired, but I see no harm in leaving this open until cvax had a chance to read and reply.

**Comment by cvax** [comment]
Thanks for the replies. I am not sure how exactly to confirm which OpenBLAS version I may or may not be using. I am trying this on a Ubuntu 16.04 VM as well as Win10's Subsystem for Linux which is also on 16.04. 

The packages I am using are the No-MKL versions of scipy and numpy from Anaconda. According to [this](https://www.continuum.io/blog/developer-blog/anaconda-25-release-now-mkl-optimizations), since the environments are Linux, they will be using OpenBLAS. Is there some code I could run to confirm OpenBLASness of my packages from Python?

**Comment by brada4** [comment]
Some reality check:
Do you get (radically) different result with MKL?
Even a bit off with OPENBLAS_CORETYPE=Prescott set before measurement?

Anaconda forum would be obvious place to get help with their product, especially answer if OpenBLAS they ship is fresher than the old bug you refer to...

**Comment by cvax** [comment]
I just found [this comment](https://github.com/scipy/scipy/issues/5917#issuecomment-191382745) from the scipy guys. Looks like the messages I got are expected and don't matter. Thanks for the help.
