### ISSUE TITLE
Wrong printf specifier

### ISSUE THREAD

**Issue by eschnett** [xianyi/OpenBLAS#1038]
I see this warning:
```
xerbla.c:65:13: warning: format specifies type 'int' but the argument has type 'blasint' (aka 'long') [-Wformat]
          message, *info);
                   ^~~~~
```
I'm building with 64-bit integers, and in this case, the `%d` in this line needs to be probably `%ld` instead.

**Comment by brada4** [comment]
In theory it should be shortest int possible as formatting is %2d and it represents number of wrong argument , i,e, maximum something like 20. while you can edit the file (in driver/others/) to your liking proper fix involves reviewing 100+ possible callers or dirty quick ifdef wrapping.

**Comment by martin-frbg** [comment]
Probably best to #ifdef the formatting on INTERFACE64 (quick and dirty would be to cast the *info to int for the sole purpose of the printf, which would certainly work now but might cause problems in some distant future)

**Comment by eschnett** [comment]
If you're fine with casting, then unconditionally cast to `long long` in `printf`; the additional run time overhead will be negligible.

**Comment by brada4** [comment]
I objected ;)

**Comment by martin-frbg** [comment]
Thanks. I had a feeling that I had copied something wrong when I recreated the patch on another machine between travels but absolutely did not see it.
