### ISSUE TITLE
Valgrind reports errors in dswap_k (similar to issue #191)

### ISSUE THREAD

**Issue by vanhala** [xianyi/OpenBLAS#1041]
I was debugging some numerical code using OpenBLAS when I ran into this valgrind error that I have not been able to resolve so far. I am using the LAPACK function dsteqr which diagonalizes a tridiagonal matrix. I compile the OpenBLAS development branch (last commit 8f9975e01340e1eeb418df434d6402ae1df6d05f) using gcc 4.9.3 with the command

make TARGET=SANDYBRIDGE DEBUG=1

I then get the following report from valgrind:

==46969== Memcheck, a memory error detector
==46969== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==46969== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==46969== Command: tests/EDSolverTest/edsolver_test
==46969== 
==46969== Invalid read of size 8
==46969==    at 0x6370621: dswap_k (swap_sse2.S:424)
==46969==    by 0x6C15AE3: dsteqr_ (dsteqr.f:562)
==46969==    by 0x4F6901: lanczos::steqr(char, long long, double*, double*, double*, long long, double*) (lanczos.cpp:86)
==46969==    by 0x4F6A9E: lanczos::EigenvectorsAndEigenvaluesTridiag(arma::Col<double>&, arma::Mat<double>&, arma::Col<double> const&, arma::Col<double> const&) (lanczos.cpp:113)
[...]

==46969==  Address 0x8b1e778 is 0 bytes after a block of size 200 alloc'd
==46969==    at 0x4C27588: memalign (vg_replace_malloc.c:727)
==46969==    by 0x4C27623: posix_memalign (vg_replace_malloc.c:876)
==46969==    by 0x4C02B5: double* arma::memory::acquire<double>(unsigned long long) (memory.hpp:75)
==46969==    by 0x4CE906: arma::Mat<double>::init_warm(unsigned long long, unsigned long long) (Mat_meat.hpp:331)
==46969==    by 0x4CB032: arma::Mat<double>::set_size(unsigned long long, unsigned long long) (Mat_meat.hpp:6145)
[...]

==46969== 
==46969== 
==46969== HEAP SUMMARY:
==46969==     in use at exit: 8 bytes in 1 blocks
==46969==   total heap usage: 36,533 allocs, 36,532 frees, 73,057,448 bytes allocated
==46969== 
==46969== LEAK SUMMARY:
==46969==    definitely lost: 0 bytes in 0 blocks
==46969==    indirectly lost: 0 bytes in 0 blocks
==46969==      possibly lost: 0 bytes in 0 blocks
==46969==    still reachable: 8 bytes in 1 blocks
==46969==         suppressed: 0 bytes in 0 blocks
==46969== Rerun with --leak-check=full to see details of leaked memory
==46969== 
==46969== For counts of detected and suppressed errors, rerun with: -v
==46969== ERROR SUMMARY: 10 errors from 1 contexts (suppressed: 6 from 6)

I have not yet had time to look at the parameters to the dsteqr call. However, I noticed that if I use

make DSWAPKERNEL=../arm/swap.c TARGET=SANDYBRIDGE DEBUG=1

to compile OpenBLAS, then the error disappears. The DSWAPKERNEL parameter chooses the kernel to use for the dswap call, so this leads me to suspect that there might be something strange happening in swap_sse2.S.

This is also very similar to the bug reported in issue #191. Perhaps there is a regression?

I can later try to produce a minimal example to reproduce this if needed, but I don't have time right now.

**Comment by martin-frbg** [comment]
Yes a minimal example would be highly desirable - among other things, it would make it easy to assess if the problem occurs for other cpu implementations as well. Contrary to #191 I see no immediate connection to one of the few optimized LAPACK routines provided by OpenBLAS so it could be that there is an actual off-by-one access bug within swap_sse2.S (for some inputs) rather than in its caller.
BTW which operating system are you using, and is this on actual Sandybridge hardware or emulator ?

**Comment by vanhala** [comment]
This seems to reproduce it:

```
typedef int lapack_int;

extern "C" void dswap_(lapack_int * N,double * x,lapack_int * INCX,double * y,lapack_int * INCY);

int main()
{   
    lapack_int N=5;
    lapack_int INCX=1;
    lapack_int INCY=1;

    double * space=new double[2*N+1];

    double * x=space+1;
    double * y=x+N;

    dswap_(&N,x,&INCX,y,&INCY);

    delete[] space;

    return(0);
}
```

Note that the +1 in x=space+1 is needed to trigger the error for me. It seems that the flow of the swap function depends on the alignment of the memory or something. I don't know if the implementation of malloc then affects this example, since it might return differently aligned arrays. With valgrind I get

```
==48486== Memcheck, a memory error detector
==48486== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==48486== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==48486== Command: ./example
==48486==
==48486== Invalid read of size 8
==48486==    at 0x51F4621: dswap_k (swap_sse2.S:424)
==48486==    by 0x400817: main (example.cpp:17)
==48486==  Address 0x72029b8 is 0 bytes after a block of size 88 alloc'd
==48486==    at 0x4C29192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==48486==    by 0x4007D0: main (example.cpp:12)
==48486==
==48486==
==48486== HEAP SUMMARY:
==48486==     in use at exit: 0 bytes in 0 blocks
==48486==   total heap usage: 36 allocs, 36 frees, 53,333 bytes allocated
==48486==
==48486== All heap blocks were freed -- no leaks are possible
==48486==
==48486== For counts of detected and suppressed errors, rerun with: -v
==48486== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 6 from 6)
```

I'm on a Linux machine (RHEL6) with a sandy bridge cpu (E5-2670).

**Comment by martin-frbg** [comment]
Not reproduced on Skylake using gcc 4.8.5 and valgrind 3.12.0 (I notice you are using an old valgrind, perhaps you could update that and test again in case it is a false alarm ?)

**Comment by vanhala** [comment]
I compiled valgrind 3.12.0 from source and indeed, the error is gone.

So maybe the valgrind errors in issue #191 were also unrelated to the actual bug which was fixed. I have to ask our admins to upgrade the installed valgrind.

Thank you for your help.

**Comment by brada4** [comment]
Yes, close the issue and ask your admins to upgrade to centos 7
You will not get much newer valgrind (or AVX-2 capable GDB) on CentOS6,
best latest is here: https://www.softwarecollections.org/en/scls/rhscl/devtoolset-3/
