### ISSUE TITLE
building OpenBLAS 0.2.19 with LAPACK 3.7.0 fails

### ISSUE THREAD

**Issue by boegel** [xianyi/OpenBLAS#1042]
We usually build OpenBLAS together with the latest available LAPACK version, rather than the LAPACK that is included in the OpenBLAS release (to profit from LAPACK bug fixes included in a more recent LAPACK version than the one included with OpenBLAS).

This works fine to build OpenBLAS 0.2.19 with LAPACK 3.6.1, but it fails with the latest LAPACK 3.7.0:

```
make[1]: Entering directory `/tmp/easybuild_build/OpenBLAS/0.2.19/GCC-6.3.0-2.27-LAPACK-3.7.0/OpenBLAS-0.2.19/exports'
make[1]: warning: -jN forced in submake: disabling jobserver mode.
perl ./gensymbol linktest  x86_64 _ 0 0 0 0 0 0 "" "" 1 > linktest.c
gcc -O2 -march=native -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=24 -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I. -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=24 -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I.. -L/apps/GCCcore/6.3.0/lib64 -L/apps/GCCcore/6.3.0/lib -shared -o ../libopenblas_haswellp-r0.2.19.so \
-Wl,--whole-archive ../libopenblas_haswellp-r0.2.19.a -Wl,--no-whole-archive \
-Wl,-soname,libopenblas.so.0 -lm -lpthread -lgfortran -lm -lpthread -lgfortran
/apps/binutils/2.27-GCCcore-6.3.0/bin/ld.gold: error: ../libopenblas_haswellp-r0.2.19.a(ztplqt.o): multiple definition of 'ztplqt_'
/apps/binutils/2.27-GCCcore-6.3.0/bin/ld.gold: ../libopenblas_haswellp-r0.2.19.a(ztplqt.o): previous definition here
/apps/binutils/2.27-GCCcore-6.3.0/bin/ld.gold: error: ../libopenblas_haswellp-r0.2.19.a(ztplqt2.o): multiple definition of 'ztplqt2_'
/apps/binutils/2.27-GCCcore-6.3.0/bin/ld.gold: ../libopenblas_haswellp-r0.2.19.a(ztplqt2.o): previous definition here
/apps/binutils/2.27-GCCcore-6.3.0/bin/ld.gold: error: ../libopenblas_haswellp-r0.2.19.a(ztpmlqt.o): multiple definition of 'ztpmlqt_'
/apps/binutils/2.27-GCCcore-6.3.0/bin/ld.gold: ../libopenblas_haswellp-r0.2.19.a(ztpmlqt.o): previous definition here
collect2: error: ld returned 1 exit status
make[1]: *** [../libopenblas_haswellp-r0.2.19.so] Error 1
make[1]: Leaving directory `/tmp/easybuild_build/OpenBLAS/0.2.19/GCC-6.3.0-2.27-LAPACK-3.7.0/OpenBLAS-0.2.19/exports'
make: *** [shared] Error 2
```

The problem seems to be related to the extended LAPACK API in LAPACK 3.7.0.

Does this mean LAPACK 3.7.0 can't be used as a drop-in replacement for the LAPACK 3.6.0 that is included with OpenBLAS 0.2.19? Is there a workaround, or are there significant changes requires to make this work?

**Comment by martin-frbg** [comment]
If I recall correctly. the "gensymbol" script acts on a static list of function names to which any new LAPACK routines will have to be added.

**Comment by martin-frbg** [comment]
Also note that the LAPACK that ships with OpenBLAS is not generally a static copy of the respective netlib release, it may already contain fixes cherry-picked from the netlib develop branch or (at least historically when netlib had only a mailing list for bug reports) ones accepted into OpenBLAS first.

**Comment by brada4** [comment]
You can build any lapack version providing NO_LAPACK (static) build of openblas as BLASLIB (Debian does it and Fedora to some degree)
Probably that is what you want.

**Comment by boegel** [comment]
@brada4 any pointers to how to do that in more details?

**Comment by brada4** [comment]
make clean
make DYNAMIC_ARCH=1 NO_SHARED=1 NO_CBLAS=1 NO_LAPACK=1 NUM_THREADS=???
??? is maximum cores you will encounter in single machine in foreseeable future
then resulting libopenblas*a can be passed as BLASLIB to netlib lapack 3.7.0 build (they have instructions and makefiles for that)

**Comment by boegel** [comment]
So, are there any (dis)advantages of doing this compared to baking LAPACK into the OpenBLAS library?

**Comment by martin-frbg** [comment]
There is a handful of optimized LAPACK routines (in the "lapack" directory) that you'd miss, and perhaps a few interprocedural optimization opportunities depending on the compiler, but nothing spectacular as far as I know. Note that there is at least one erratum for LAPACK 3.7.0 that probably also explains your current build issue here - see https://github.com/Reference-LAPACK/lapack/issues/105

**Comment by boegel** [comment]
@martin-frbg ah, yes, that sure looks like the problem I'm running into! I'll look into including the straightforward patch for LAPACK 3.7.0, retest building the combination of OpenBLAS 0.2.19 and LAPACK 3.7.0, and report back.

**Comment by boegel** [comment]
OK, applying that patch (from https://github.com/Reference-LAPACK/lapack/commit/c5788233f95fed2c7f008ea079e8257a85348287) indeed worked.

I also had to apply a minor fix to copy `lapacke_mangling.h`, since the source file got renamed in LAPACK 3.7.0 (was `lapacke_mangling_with_flags.h`, now is `lapacke_mangling.h` just like the target file).

Complete patch to build OpenBLAS 0.2.19 with LAPACK 3.7.0 in https://gist.github.com/boegel/06e42355f09bbb7be1830a2e4af1dab2.

**Comment by martin-frbg** [comment]
Thanks for your feedback. Closing now as LAPACK 3.7.0+ has just landed on the OpenBLAS develop branch thanks to wernsaar.
