### ISSUE TITLE
Slower performance of OpenBLAS for inverse operation on ARMv7

### ISSUE THREAD

**Issue by sohailshuaib** [xianyi/OpenBLAS#1045]
Hi All,

I have done some benchmarking for multiplication and inverse operations for ARMv7. I am using the armadillo c++ library which itself uses BLAS and LAPACK. The performance of OpenBLAS for multiplication is way better than the normal BLAS. Howevever, for inverse, armadillo makes use of LAPACK routines which in turn use BLAS implementations to compute the inverse using LU factorization. Using OpenBLAS leads to a slower performance compared to the normal unoptimized BLAS. At the first sight, this does not make sense because the LAPACK routine make use of BLAS for solving the LU factorization problem, or is it some extra overhead (vectorization) being incurred due to the particular nature of LU factorization. or something else is at play here?

I am using buildroot to cross compile the OpenBLAS for ARM A53.

**Comment by martin-frbg** [comment]
Slow performance of (banded) LU factorization was reported in #901 but by all accounts appeared to be specific to Haswell systems running OSX. Could you run your test code on some other platform to see if it is generic or limited to the ARMv7 target, or could you provide a (small,self-contained) testcase ?

**Comment by sohailshuaib** [comment]
Thanks for the comment @martin-frbg . Well, i indeed ran my benchmarking code for Intel Haswel running CentOS, and experienced similar behaviour. However, for a higher matrix size, e.g., 1000, OpenBLAS was faster. This led to me conclude, in my first post, that some overhead of vectorization could be at play here. However, i could not replicate the same scenario on ARM; increasing the matrix size took longer for OpenBLAS.

**Comment by brada4** [comment]
Does it work faster with single thread than many?

**Comment by brada4** [comment]
Can you extract BLAS or LAPACK call that is 'SLOW'? (or provide code sample so we can do it)
Can you show situation where it is 'FAST' for comparison?

**Comment by martin-frbg** [comment]
Did you build OpenBLAS with the included LAPACK or without (i.e. make NO_LAPACK=1) ? I found out the hard way today that the LAPACK compile step within OpenBLAS does not inherit the default "-O2" optimization level of its BLAS counterpart. So if one not does not set the FFLAGS environment variable or edit Makefile.system accordingly, one may end up with a set of LAPACK modules that perform noticably poorer than a regular "Release mode" build of the exact same sources from netlib...

**Comment by sohailshuaib** [comment]
@brada4 I only used a single thread. And it is the cgetrf_ cgerti_ routines of LAPACK that perform the inverse using LU factorization and slower.

**Comment by sohailshuaib** [comment]
@martin-frbg I indeed use NO_LAPACK=1 because my toolchain does not have a cross fortran compiler and build a CLAPACK package separately linking it with OpenBLAS manually.

**Comment by sohailshuaib** [comment]
Below is the test code. Unfortunately it is not self contained. To run it, one must have the armadillo library installed (which is fairly straightforward). 

main.cpp
`#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>
#include <float.h>
#include <assert.h>
#include <complex>

#define ARMA_DONT_USE_WRAPPER

#include <armadillo>



/* Basic data types */
typedef signed char             tInt8;
typedef unsigned char           tUint8;
typedef short                   tInt16;
typedef unsigned short          tUint16;
typedef int                     tInt32;
typedef unsigned int            tUint32;
typedef long long               tInt64;
typedef unsigned long long      tUint64;
typedef unsigned char           tBoolean;
typedef signed int              tError;
typedef float                   tFloat;
typedef float _Complex          tCFloat;
typedef double                  tDouble;

static std::complex<float>* Amatrixmem = NULL;
static std::complex<float>* Bmatrixmem = NULL;
static std::complex<float>* Cmatrixmem = NULL;
static std::complex<float>* Dmatrixmem = NULL;
static std::complex<float>* Ematrixmem = NULL;

using namespace arma;

//extern "C" void openblas_set_num_threads(int num_threads);

void init_matrixinverse(tUint32 N, tUint32 K){
	int i = 0;
	Dmatrixmem = new std::complex<float>[N*N*K];
	Ematrixmem = new std::complex<float>[N*N*K];
	
	for (i=0; i<K; i++) {
		cx_fmat D(Dmatrixmem+i*N*N, N, N, false, true);
		D.randu();
		
		cx_fmat E(Ematrixmem+i*N*N, N, N, false, true);
		E.fill(0);
	}
}


void init_matrixmultiply(tUint32 N, tUint32 K){
	int i = 0;
	Amatrixmem = new std::complex<float>[N*N*K];
	Bmatrixmem = new std::complex<float>[N*N*K];
	Cmatrixmem = new std::complex<float>[N*N*K];
	
	for (i=0; i<K; i++) {
		cx_fmat A(Amatrixmem+i*N*N, N, N, false, true);
		A.randu();
		
		cx_fmat B(Bmatrixmem+i*N*N, N, N, false, true);
		B.randu();
		
		cx_fmat C(Cmatrixmem+i*N*N, N, N, false, true);
		C.fill(0);
	}
}

void destroy() {
	if(Amatrixmem != NULL) {
		delete Amatrixmem;
	}
	
	if(Bmatrixmem != NULL) {
		delete Bmatrixmem;
	}
	
	if(Cmatrixmem != NULL) {
		delete Cmatrixmem;
	}
	
	if(Dmatrixmem != NULL) {
		delete Dmatrixmem;
	}
	
	if(Ematrixmem != NULL) {
		delete Ematrixmem;
	}
}

void exec_matrixmultiply(tUint32 N, tUint32 K) {
	int i = 0;
	for (i=0; i<K; i++) {
		cx_fmat A(Amatrixmem+i*N*N, N, N, false, true);
		cx_fmat B(Bmatrixmem+i*N*N, N, N, false, true);
		cx_fmat C(Cmatrixmem+i*N*N, N, N, false, true);
		C = A * B;
	}
}


void exec_matrixinverse(tUint32 N, tUint32 K) {
	int i = 0;
	for (i=0; i<K; i++) {
		cx_fmat D(Dmatrixmem+i*N*N, N, N, false, true);
		cx_fmat E(Ematrixmem+i*N*N, N, N, false, true);
		E = D.i();
	}
}

void display_matrixmultiply(tUint32 N, tUint32 K) {
	int i = 0;
	for (i=0; i<K; i++) {
		cx_fmat A(Amatrixmem+i*N*N, N, N, false, true);
		cx_fmat B(Bmatrixmem+i*N*N, N, N, false, true);
		cx_fmat C(Cmatrixmem+i*N*N, N, N, false, true);
		cout << C << endl << " = " << endl << A << endl << " * " << endl << B << endl;
	}

}

void display_matrixinverse(tUint32 N, tUint32 K) {
	int i = 0;
	for (i=0; i<K; i++) {
		cx_fmat D(Dmatrixmem+i*N*N, N, N, false, true);
		cx_fmat E(Ematrixmem+i*N*N, N, N, false, true);
		cout << E << endl << " = " << endl << D << endl << "^-1 " << endl ;
	}

}


int main(int argc, char *argv[]) {
	int i;
	// command line parameters
	tUint32 N,K = 0;
	bool display = false;
	bool matrixmult = false;
	bool matrixinv = false;
	int nthreads = 0;

	clock_t start;
	tFloat elapsed_time = 0;

	// get command line parameters
	if( argc == 1 )
	{
		printf("Usage:\n\n");
		printf("--lines : specify the matrix row size\n");
		printf("--tones : specify the number of tones\n");
		printf("--display\n");
		printf("--inv\n");
		printf("--mul\n");		
		printf("--nthreads\n");
		return 0;
	}

	for( i = 1; i < argc; i++ )
	{

		if( !strcmp( argv[i], "--lines" ) )
		{
			N = atoi(argv[++i]);
		}
		else if( !strcmp( argv[i], "--tones" ) )
		{
			K = atoi(argv[++i]);
		}
		else if( !strcmp( argv[i], "--display" ) )
		{
			display = true;
		}
		else if( !strcmp( argv[i], "--mul" ) )
		{
			matrixmult = true;
		}
		else if( !strcmp( argv[i], "--inv" ) )
		{
			matrixinv = true;
		}		
		else if ( !strcmp( argv[i], "--nthreads" ) ) 
		{
			nthreads = atoi(argv[++i]);
		}
	}

	if (nthreads != 0) {
	//	openblas_set_num_threads(nthreads);
	}
	
	// check parameter consistency
	if(N == 0){
		printf("No size specified! Use --size <number> to define the matrix size.\n");
		return 0;
	}	
	if(K == 0){
		printf("No number of tones specified! Use --tones <number> to define the number of tones.\n");
		return 0;
	}
	if(!matrixinv && !matrixmult) {
		printf("no mult or inv specified!\n");
		return 0;
	}

	// initialize data structures
	
	if(matrixmult) {
		init_matrixmultiply(N, K);

		start = clock();
		exec_matrixmultiply(N,K);
		elapsed_time = ((float)(clock()-start))/CLOCKS_PER_SEC;
		printf("Matrix multiply for %u lines and %u tones took %f seconds\n\n\n", N, K, elapsed_time);
		
		if(display){
			display_matrixmultiply(N,K);
		}
	}

	
	if(matrixinv) {
		init_matrixinverse(N,K);	
		
		start = clock();
		exec_matrixinverse(N,K);
		elapsed_time = ((float)(clock()-start))/CLOCKS_PER_SEC;
		printf("Matrix inverse for %u lines and %u tones took %f seconds\n\n\n", N, K, elapsed_time);
		
		if(display){
			display_matrixinverse(N,K);
		}

	}

	// free memory
	destroy();

	return 0;
}`

Makefile
`CPPFLAGS += -DNO_PROTOTYPES=1 -DDEBUG=0 -O3 -mhard-float


LDLIBS += -llapack
LDLIBS += -lopenblas
LDLIBS += -lm 
 
all: main
 
main: main.cpp 
	$(CXX) $(CFLAGS) $(CPPFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)
 
 clean:
	rm -f *.o main
 
 .PHONY: all clean
`

Usage:
./main --lines 1000 --tones 1 --inv

**Comment by sohailshuaib** [comment]
Unfortunately i do not have a self contained test case. One has to have armadillo installed (which is fairly straightforward) to run it. Would that be possible for you @martin-frbg ?

**Comment by xianyi** [comment]
OpenBLAS didn't use ARM Neon (SIMD) instruction for ARMv7. Therefore, the performance is not good.

**Comment by sohailshuaib** [comment]
@xianyi the performance is not good when computing the inverse. It is definitely good while doing multiplication. Are there any plans for supporting ARM Neon instructions in the future?

**Comment by sohailshuaib** [comment]
@xianyi Does OpenBLAS with ARMv8 target use ARM Neon instructions?

**Comment by martin-frbg** [comment]
According to #854 the ARMv8 target optimization uses Advanced SIMD (NEON) instructions.

**Comment by sohailshuaib** [comment]
@martin-frbg I used the lapack that comes with OpenBLAS, and indeed, as you mentioned, it is worse than the standalone lapack. I tried passing -O2 opimization flags in the Makefile.system but it does not seem to work. Also i see that OPT variable in the make.inc correctly holds the -O2 optimization flag. How were you able to do it?

**Comment by brada4** [comment]
Just clone a fresh copy of develop branch.

**Comment by martin-frbg** [comment]
That problem should be solved in the "develop" tree now, basically you need to add the "-O2" option on 
the line that starts with "override FFLAGS" (around line 1000 in Makefile.system) so that it is seen by the
fortran compiler (and not only by the c compiler used when building blas)

**Comment by sirop** [comment]
@martin-frbg 
https://github.com/xianyi/OpenBLAS/issues/1045#issuecomment-271972504 gave me an at least 30% speed up with  LAPACKE_dgels on atom cpu  with a 3x3 matrix. Big leap for me. :)

Thanks.

**Comment by brada4** [comment]
inversion/decomposition is at complexity above O(dimension^3) while multiplication is below that.
All the locality optimisations will only give linear speedup. Unless you make algorithmic breakthrough there is no chance it gets simpler.

**Comment by sirop** [comment]
@brada4 
I believe you, but then it means that the multiplication within LAPACKE_dgels was so much slower before and got so much faster now?

**Comment by martin-frbg** [comment]
That complexity comment was probably adressed to sohailshuaib who started this topic, but I guess it is largely irrelevant as the issue was not that the computation appears to be slower in general but slower when done with OpenBLAS.

**Comment by sohailshuaib** [comment]
@martin-frbg @brada4 @xianyi there is some further update regarding the topic. I have done some profiling of using lapack with OpenBLAS vs netlib-blas on an Intel Haswell architecture. At first sight, an apparent difference is the implementation level 2 routine (cgeru) with level 1 routine (caxpy) which could probably be the cause of the bad performance or could there be something else at play here? I have tried perusing the code to look for a way not to have this transformation between level 1 and 2, but it seems impossible. I am attaching below the profile with the call graph for both OpenBLAS and netlib-blas. I did not use the lapack that comes along with OpenBLAS. Any thoughts or ideas are welcome.

OpenBLAS:
Flat profile:

Each sample counts as 0.01 seconds.
  %   cumulative   self              self     total
 time   seconds   seconds    calls  us/call  us/call  name
 65.79      0.25     0.25        0     0.00           blas_thread_server
 23.68      0.34     0.09        0     0.00           cswap_k
 10.53      0.38     0.04        0     0.00           legacy_exec
  0.00      0.38     0.00  2262016     0.00           caxpy_k
  0.00      0.38     0.00    97280     0.00           cscal_
  0.00      0.38     0.00    96256     0.00           cscal_k
  0.00      0.38     0.00    89118     0.00           blas_level1_thread
  0.00      0.38     0.00    89118     0.00           cswap_
  0.00      0.38     0.00    89118     0.00           exec_blas
  0.00      0.38     0.00    89118     0.00           exec_blas_async
  0.00      0.38     0.00    89118     0.00           exec_blas_async_wait
  0.00      0.38     0.00    49152     0.00           ctrmv_
  0.00      0.38     0.00    49152     0.00           icamax_
  0.00      0.38     0.00    49152     0.00           icamax_k
  0.00      0.38     0.00    48128     0.00           c_abs
  0.00      0.38     0.00    48128     0.00           cgemv_
  0.00      0.38     0.00    48128     0.00           cgeru_
  0.00      0.38     0.00    48128     0.00           cgeru_k
  0.00      0.38     0.00        7     0.00           blas_memory_alloc
  0.00      0.38     0.00        7     0.00           blas_memory_free
  0.00      0.38     0.00        1     0.00           blas_get_cpu_number
  0.00      0.38     0.00        1     0.00           blas_set_parameter
  0.00      0.38     0.00        1     0.00           blas_shutdown
  0.00      0.38     0.00        1     0.00           blas_thread_init
  0.00      0.38     0.00        1     0.00           blas_thread_shutdown_
  0.00      0.38     0.00        1     0.00           get_num_procs
  0.00      0.38     0.00        1     0.00           openblas_block_factor
  0.00      0.38     0.00        1     0.00           openblas_fork_handler
  0.00      0.38     0.00        1     0.00           openblas_goto_num_threads_env
  0.00      0.38     0.00        1     0.00           openblas_num_threads_env
  0.00      0.38     0.00        1     0.00           openblas_omp_num_threads_env
  0.00      0.38     0.00        1     0.00           openblas_read_env
  0.00      0.38     0.00        1     0.00           openblas_thread_timeout

index % time    self  children    called     name

[0]      0.0    0.00    0.00        0         gotoblas_quit [0]
                0.00    0.00        1/1           blas_shutdown [2005]
-----------------------------------------------
[1]      0.0    0.00    0.00        0         gotoblas_init [1]
                0.00    0.00        1/1           blas_thread_init [2026]
                0.00    0.00        1/1           blas_get_cpu_number [1998]
                0.00    0.00        1/1           openblas_read_env [2023]
                0.00    0.00        1/1           openblas_fork_handler [1997]
-----------------------------------------------
                0.00    0.00    89118/89118       <UNKNOWN>
[96]     0.0    0.00    0.00    89118         cswap_ [96]
                0.00    0.00    89118/89118       blas_level1_thread [2034]
-----------------------------------------------
                0.00    0.00    97280/97280       <UNKNOWN>
[98]     0.0    0.00    0.00    97280         cscal_ [98]
                0.00    0.00    96256/96256       cscal_k [2255]
-----------------------------------------------
                0.00    0.00    49152/49152       <UNKNOWN>
[105]    0.0    0.00    0.00    49152         icamax_ [105]
                0.00    0.00    49152/49152       icamax_k [2236]
-----------------------------------------------
                0.00    0.00    48128/48128       <UNKNOWN>
[111]    0.0    0.00    0.00    48128         cgemv_ [111]
-----------------------------------------------
                0.00    0.00    48128/48128       <UNKNOWN>
[112]    0.0    0.00    0.00    48128         cgeru_ [112]
                0.00    0.00    48128/48128       cgeru_k [2300]
-----------------------------------------------
                0.00    0.00    49152/49152       <UNKNOWN>
[115]    0.0    0.00    0.00    49152         ctrmv_ [115]
-----------------------------------------------
[607]    0.0    0.00    0.00        0         ctrmv_NUN [607]
                0.00    0.00  1106944/2262016     caxpy_k [2240]
-----------------------------------------------
                0.00    0.00        1/1           blas_get_cpu_number [1998]
[1995]   0.0    0.00    0.00        1         get_num_procs [1995]
-----------------------------------------------
                0.00    0.00        1/1           gotoblas_init [1]
[1997]   0.0    0.00    0.00        1         openblas_fork_handler [1997]
-----------------------------------------------
                0.00    0.00        1/1           gotoblas_init [1]
[1998]   0.0    0.00    0.00        1         blas_get_cpu_number [1998]
                0.00    0.00        1/1           openblas_omp_num_threads_env [2022]
                0.00    0.00        1/1           openblas_goto_num_threads_env [2021]
                0.00    0.00        1/1           openblas_num_threads_env [2020]
                0.00    0.00        1/1           get_num_procs [1995]
-----------------------------------------------
                0.25    0.00        7/7           blas_thread_server [2025]
[2001]   0.0    0.00    0.00        7         blas_memory_alloc [2001]
                0.00    0.00        1/1           blas_set_parameter [2036]
-----------------------------------------------
                0.25    0.00        7/7           blas_thread_server [2025]
[2002]   0.0    0.00    0.00        7         blas_memory_free [2002]
-----------------------------------------------
                0.00    0.00        1/1           gotoblas_quit [0]
[2005]   0.0    0.00    0.00        1         blas_shutdown [2005]
                0.00    0.00        1/1           blas_thread_shutdown_ [2033]
-----------------------------------------------
                0.00    0.00    48128/48128       <UNKNOWN>
[2007]   0.0    0.00    0.00    48128         c_abs [2007]
-----------------------------------------------
                0.00    0.00        1/1           blas_thread_init [2026]
[2018]   0.0    0.00    0.00        1         openblas_thread_timeout [2018]
-----------------------------------------------
                0.00    0.00        1/1           blas_set_parameter [2036]
[2019]   0.0    0.00    0.00        1         openblas_block_factor [2019]
-----------------------------------------------
                0.00    0.00        1/1           blas_get_cpu_number [1998]
[2020]   0.0    0.00    0.00        1         openblas_num_threads_env [2020]
-----------------------------------------------
                0.00    0.00        1/1           blas_get_cpu_number [1998]
[2021]   0.0    0.00    0.00        1         openblas_goto_num_threads_env [2021]
-----------------------------------------------
                0.00    0.00        1/1           blas_get_cpu_number [1998]
[2022]   0.0    0.00    0.00        1         openblas_omp_num_threads_env [2022]
-----------------------------------------------
                0.00    0.00        1/1           gotoblas_init [1]
[2023]   0.0    0.00    0.00        1         openblas_read_env [2023]
-----------------------------------------------
[2025]  65.8    0.25    0.00        0         blas_thread_server [2025]
                0.00    0.00        7/7           blas_memory_free [2002]
                0.00    0.00        7/7           blas_memory_alloc [2001]
-----------------------------------------------
                0.00    0.00        1/1           gotoblas_init [1]
[2026]   0.0    0.00    0.00        1         blas_thread_init [2026]
                0.00    0.00        1/1           openblas_thread_timeout [2018]
-----------------------------------------------
                0.00    0.00    89118/89118       exec_blas [2029]
[2027]   0.0    0.00    0.00    89118         exec_blas_async [2027]
-----------------------------------------------
                0.00    0.00    89118/89118       exec_blas [2029]
[2028]   0.0    0.00    0.00    89118         exec_blas_async_wait [2028]
-----------------------------------------------
                0.00    0.00    89118/89118       blas_level1_thread [2034]
[2029]   0.0    0.00    0.00    89118         exec_blas [2029]
                0.00    0.00    89118/89118       exec_blas_async_wait [2028]
                0.00    0.00    89118/89118       exec_blas_async [2027]
-----------------------------------------------
                0.00    0.00        1/1           blas_shutdown [2005]
[2033]   0.0    0.00    0.00        1         blas_thread_shutdown_ [2033]
-----------------------------------------------
                0.00    0.00    89118/89118       cswap_ [96]
[2034]   0.0    0.00    0.00    89118         blas_level1_thread [2034]
                0.00    0.00    89118/89118       exec_blas [2029]
-----------------------------------------------
                0.00    0.00        1/1           blas_memory_alloc [2001]
[2036]   0.0    0.00    0.00        1         blas_set_parameter [2036]
                0.00    0.00        1/1           openblas_block_factor [2019]
-----------------------------------------------
                0.00    0.00    49152/49152       icamax_ [105]
[2236]   0.0    0.00    0.00    49152         icamax_k [2236]
-----------------------------------------------
                0.00    0.00  1106944/2262016     ctrmv_NUN [607]
                0.00    0.00  1155072/2262016     cgeru_k [2300]
[2240]   0.0    0.00    0.00  2262016         caxpy_k [2240]
-----------------------------------------------
                0.00    0.00    96256/96256       cscal_ [98]
[2255]   0.0    0.00    0.00    96256         cscal_k [2255]
-----------------------------------------------
                0.00    0.00    48128/48128       cgeru_ [112]
[2300]   0.0    0.00    0.00    48128         cgeru_k [2300]
                0.00    0.00  1155072/2262016     caxpy_k [2240]
-----------------------------------------------


Netlib-BLAS:

Flat profile:

Each sample counts as 0.01 seconds.
  %   cumulative   self              self     total
 time   seconds   seconds    calls  us/call  us/call  name
 33.33      0.05     0.05    48128     1.04           cgemv_
 26.67      0.09     0.04    48128     0.83           cgeru_
 20.00      0.12     0.03    49152     0.61           ctrmv_
 13.33      0.14     0.02  1328539     0.02           scabs1_
  6.67      0.15     0.01    89118     0.11           cswap_
  0.00      0.15     0.00  1328539     0.00           r_imag
  0.00      0.15     0.00   145408     0.00           c_abs
  0.00      0.15     0.00    97280     0.00           cscal_
  0.00      0.15     0.00    49152     0.00           icamax_
  0.00      0.15     0.00    48128     0.00           f__cabs
  0.00      0.15     0.00    16384     0.00           s_copy

index % time    self  children    called     name

                0.00    0.00  1328539/1328539     icamax_ [73]
[70]    13.3    0.02    0.00  1328539         scabs1_ [70]
                0.00    0.00  1328539/1328539     r_imag [156]
-----------------------------------------------
                0.00    0.00    49152/49152       <UNKNOWN>
[73]     0.0    0.00    0.00    49152         icamax_ [73]
                0.02    0.00  1328539/1328539     scabs1_ [70]
-----------------------------------------------
                0.00    0.00    97280/97280       <UNKNOWN>
[80]     0.0    0.00    0.00    97280         cscal_ [80]
-----------------------------------------------
                0.00    0.00    89118/89118       <UNKNOWN>
[81]     6.7    0.01    0.00    89118         cswap_ [81]
-----------------------------------------------
                0.00    0.00    48128/48128       <UNKNOWN>
[83]    33.3    0.05    0.00    48128         cgemv_ [83]
-----------------------------------------------
                0.00    0.00    49152/49152       <UNKNOWN>
[88]    20.0    0.03    0.00    49152         ctrmv_ [88]
-----------------------------------------------
                0.00    0.00    48128/48128       <UNKNOWN>
[95]    26.7    0.04    0.00    48128         cgeru_ [95]
-----------------------------------------------
                0.00    0.00   145408/145408      <UNKNOWN>
[151]    0.0    0.00    0.00   145408         c_abs [151]
-----------------------------------------------
                0.02    0.00  1328539/1328539     scabs1_ [70]
[156]    0.0    0.00    0.00  1328539         r_imag [156]
-----------------------------------------------
                0.00    0.00    16384/16384       <UNKNOWN>
[162]    0.0    0.00    0.00    16384         s_copy [162]
-----------------------------------------------
                0.00    0.00    48128/48128       <UNKNOWN>
[163]    0.0    0.00    0.00    48128         f__cabs [163]
-----------------------------------------------

**Comment by martin-frbg** [comment]
I am not sure if I can provide much insight here, but how exactly are you testing - what argument sizes, how many threads ? (Does performance improve when you limit the number of threads created to 2 or even just 1 by setting the environment variable OPENBLAS_NUM_THREADS accordingly ?)

**Comment by sohailshuaib** [comment]
Well, i am using a single thread only, to keep a comparison with netlib-blas valid. The size of matrix i am trying to invert is 48, and i typically perform this action a 1024 times. Are there any possibilities to backport a particular routine to its native implementation?
 

    On Tuesday, 17 January 2017, 20:11, Martin Kroeker <notifications@github.com> wrote:
 

 I am not sure if I can provide much insight here, but how exactly are you testing - what argument sizes, how many threads ? (Does performance improve when you limit the number of threads created to 2 or even just 1 by setting the environment variable OPENBLAS_NUM_THREADS accordingly ?)—

**Comment by martin-frbg** [comment]
I _guess_ it would be possible to link the netlib cgeru (or equivalent c code) into your application so that the OpenBLAS implementation is not called, or alternatively to add netlib's straightforward algorithm to the function(s) under the CNAME alias in ger_thread.c so that it gets used in place of the more elaborate code whenever lda is small. (I seem to remember something similar being discussed in earlier issues where the OpenBLAS implementation is overkill for tiny matrix sizes)

**Comment by sohailshuaib** [comment]
Thanks @martin-frbg for the suggestions. However, being a newbie to openblas, i am finding it difficult to wade through the apparently complex implementation of openblas. I have located the aliases you mentioned and put a few printfs around in the code to have a feeling of the code flow. It compiles successfully, but does not print anything. I have tried, but could not figure out if printfs are being re routed or suppressed altogether by openblas? Is there some other documentation i could consult to have an understanding of the code structure/design and code flow of openblas?

**Comment by ashwinyes** [comment]
@sohailshuaib Are you building for ARMv8 ? The topic says ARMv7 but in the comment you mentioned A53. This is contradicting.

If you are indeed building for ARMv8, can you please try building with make option "TARGET=CORTEXA57"

**Comment by sohailshuaib** [comment]
@ashwinyes it is possible to build for ARMv7 on a A53 device. The discussion has evolved to be rather independent of ARMvx and relates to lower performance of openblas when used for certain operations (e.g. matrix inverse)

**Comment by sohailshuaib** [comment]
@martin-frbg i can corroborate your thoughts on openblas being an overkill for tiny matrices. I was able to confirm this by profiling for larger (on the order of 1000) sized matrices.

**Comment by ashwinyes** [comment]
@sohailshuaib Thanks for clarifying.

The reason I asked is because I saw the following question in one of the comments.
>> Does OpenBLAS with ARMv8 target use ARM Neon instructions?

To clarify further, "TARGET=ARMV8" uses default C implementations for majority of the APIs. 
However "TARGET=CORTEXA57" uses the assembly implementations which has the ARMv8 SIMD instructions.

Anyways, my suggestion doesn't look relevant to this discussion. Hence please ignore it.

**Comment by sohailshuaib** [comment]
@ashwinyes thanks for the input. Just for the record, I, indeed, tried your suggestion, but to no effect.

**Comment by martin-frbg** [comment]
@sohailshuaib the only documentation I am aware of is https://github.com/xianyi/OpenBLAS/wiki/Developer-manual which at least provides a quick overview of the code layout. And as far as I know, fprintf(stderr,...) should work everywhere (though with all the CNAME substitution it is sometimes helpful to consult the local Makefile to find which file gets compiled into which function under the influence of which defines or un-defines).

**Comment by sohailshuaib** [comment]
Thanks @martin-frbg , the developer manual had good hints.

**Comment by ashwinyes** [comment]
@sohailshuaib One more suggestion if you have not already tried it.

The profiling dat  that you shared in file libOpenblasLapackWithLibraryDebugEnabled.txt shows that blas_thread_server is taking up the majority of time.

You can try by completely disable threading in OpenBLAS by using make option "USE_THREAD=0".

**Comment by sohailshuaib** [comment]
trying to replace a level 2 implementation of openblas with its netlib-blas (using clapack) counterpart has led me to a confusion with regards to the implementation of complex data in openblas routines. For example CGERU (zger.c) expects FLOAT which in itself is mapped to the primitive float instead of a complex datatype as in netlib-blas. Is it the case or am i missing something?

**Comment by martin-frbg** [comment]
Without looking at the code I would suspect that the array is treated as paired real and imaginary parts internally ?

**Comment by sohailshuaib** [comment]
i could observe some improvements after using netlib-blas implementation of some routines e.g cgeru etc. In the meanwhile i also tried the suggestion of @ashwinyes which turned out to be the real deal breaker. Using this option, i can report that openblas performed better than netlib-blas for matrix inverse. I need to see in detail why this could have been a bottleneck earlier, and also test it on ARM. Currently i tested this on Intel Haswell.

**Comment by ashwinyes** [comment]
Good to know that this worked. Using threads for small problem sizes is obviously an overhead.

However, setting OPENBLAS_NUM_THREADS=1 with multithreaded OpenBLAS library also should have seen similar performance improvemnet

**Comment by martin-frbg** [comment]
Shouldn't CGERU (zger.c) use a single thread for small problem sizes automatically, thanks to jeromerobert's work on #731 ? Perhaps there is another similar bottleneck elsewhere.

**Comment by brada4** [comment]
Without code sample I cannot guess which of dozen LU factorisation functions to approach....
@ashwinyes can you run perf record yourprogram ; perf report -U > profile.txt and attach file?

**Comment by sohailshuaib** [comment]
So the fix was to not to build openblas in a multithreaded configuration or enforce to use a single thread at runtime by setting OPENBLAS_NUM_THREADS=1. Essentially, creating and managing threads for small problems introduces additional overheads which far outweighs the gains of openblas. With this lesson, the issue can be closed now. Thanks to everyone who shared their suggestions and helping remarks :).
