### ISSUE TITLE
Does not compile succefully due to link error

### ISSUE THREAD

**Issue by MigMuc** [xianyi/OpenBLAS#1048]
I have checked out the latest development branch. The following error occurs:
`perl ./gensymbol linktest  x86_64 _ 0 0 0 0 0 0 "" "" 1 > linktest.c
gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  -shared -o ../libopenblas_piledriver-r0.2.20.dev.so \
        -Wl,--whole-archive ../libopenblas_piledriver-r0.2.20.dev.a -Wl,--no-whole-archive \
        -Wl,-soname,libopenblas.so.0 -lm -lgfortran -lm -lgfortran
gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  -w -o linktest linktest.c ../libopenblas_piledriver-r0.2.20.dev.so -L/usr/lib/gcc/x86_64-linux-gnu/4.8 -L/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.8/../../..  -lgfortran -lm -lquadmath -lm -lc   && echo OK.
/tmp/ccdKVOCU.o: In Funktion `main':
linktest.c:(.text.startup+0x37eb): Nicht definierter Verweis auf `blas_thread_shutdown_'
collect2: error: ld returned 1 exit status`

**Comment by martin-frbg** [comment]
Somehow you seem to have mixed files from a multithreaded and a singlethread build, is this the first time you built OpenBLAS in that directory ?

**Comment by martin-frbg** [comment]
Nevermind - this symbol was added to the "misc_underscore_objs" list in the gensymbol script through
the recent commit by @wernsaar just a few hours ago. It is not immediately clear to me why it would be needed there now, and it appears it should be excluded when USE_THREAD=0 (which unfortunately does not appear to be passed to gensymbol currently).

**Comment by MigMuc** [comment]
This is indeed a singlethread build with USE_THREAD=0 from scratch.

**Comment by martin-frbg** [comment]
Just removing the offending line 123 from exports/gensymbol should fix this for now - I just do not want to step in and revert that part of wernsaar's commit in the middle of his night (1am CET)

**Comment by wernsaar** [comment]
I removed blas_thread_shutdown from gensymbol.

@xianyi 
travis should also test the single threaded build.

Best regards
Werner
