### ISSUE TITLE
Error while building with MinGW on Windows

### ISSUE THREAD

**Issue by tuannhtn** [xianyi/OpenBLAS#1056]
Hello, it's good that OpenBlas's now updated with Lapack 3.7.0. But the same problem I encountered when building it on Windows MinGW. I understand the cause was in lapack-netlib\LAPACKE\src\Makefile, it should divide multiple source files into chunks. But I do not know how. Could some one give me a hand?

**Comment by brada4** [comment]
Same error to WHAT?

**Comment by tuannhtn** [comment]
The same error as https://github.com/xianyi/OpenBLAS/issues/325

**Comment by martin-frbg** [comment]
Apparently a recurring problem that comes up whenever a new major release of LAPACK is merged - after #325 came #699, now again it looks like the specially crafted LAPACKE Makefile was overwritten by the stock netlib one. Perhaps it should be tried to get this change merged "upstream" in https://github.com/Reference-LAPACK/lapack ?

**Comment by martin-frbg** [comment]
Please try again with the updated Makefile - as I have only reapplied the previous fix there is still a small possibility that the addition of new functions in 3.7.0 makes it necessary to introduce yet another split of the list.

**Comment by tuannhtn** [comment]
Thanks, martin-frbg. I tried but the same error occurred, it was: 
make[3]: expcvp: ar: Bad file number
make[3]: *** [../../../libopenblas_sandybridgep-r0.2.20.dev.a Error 127.

**Comment by brada4** [comment]
Can you show at least 10 lines above the error?
Can you edit Makefile.system around line 200 there is AR={...}ar and replace ar in the end with gcc-ar?
i.e if it is windows limitation or just a bad luck with binutils.

**Comment by tuannhtn** [comment]
Thanks brada4, the errors were:
lapacke_zgeqpf_work.o
make[3]: execvp: ar: Bad file number
make[3]: *** [../../../libopenblas_sandybridgep-r0.2.20.dev.a Error 127.
make[3]: Leaving directory '/home/tuannhtn/OpenBlas/lapack-netlib/LAPACKE/src'
make[2]: *** [lapacke] Error 2
make[2]: Leaving directory '/home/tuannhtn/OpenBlas/lapack-netlib/LAPACKE'
make[1]: *** [lapackelib] Error 1
make[1]: Leaving directory '/home/tuannhtn/OpenBlas/lapack-netlib'
make: *** [netlib] Error 2

**Comment by martin-frbg** [comment]
Sorry, my mistake - my change missed the actual important part, namely doing two subsequent calls to "ar" each with a part of the original, overly long object list.
Could you please try with the appended file placed in lapack-netlib/LAPACKE/src (and renamed to "Makefile", the github interface seems to insist on adding a ".txt" ending here)
[Makefile.txt](https://github.com/xianyi/OpenBLAS/files/696672/Makefile.txt)

**Comment by tuannhtn** [comment]
Thanks, martin-frgb. Now new errors appear:
Cannot export LAPACKE_zlatms_work: symbol not defined
collect2.exe: error: ld returned 1 exit status
make[1]: *** [../libopenblas.dll] Error 1
make[1]: Leaving directory '/home/tuannhtn/OpenBlas/exports'
make: *** [shared] Error 2

**Comment by martin-frbg** [comment]
Thanks. That one appears (to me at least) to be an unrelated problem ? Strangely a comment in the gensymbol script notes that LAPACKE_zlatms_work and others from the MATGEN_OBJ list are not to
be exported, so I am unsure how you would end up with that error.

**Comment by martin-frbg** [comment]
Did you do a "make clean" before trying the new Makefile ? (Just in case there might be some half-broken archive created during the previous build attempt that creates the problem)

**Comment by brada4** [comment]
Can windows do something like \* in place of * ?

**Comment by tuannhtn** [comment]
Thanks martin-frbg and brada4. Firstly, I rebuilt OpenBlas after performing the command line **make clean**, but the same errors occurred. Then, I downloaded the new OpenBlas source code and rebuilt once again. And the problems disappeared. Thank you all.

**Comment by martin-frbg** [comment]
Great. I do wonder though why this problem is not picked up by the automated build tests that are run whenever something gets changed in the source code. Are you using a very old version of mingw perhaps ?

**Comment by tuannhtn** [comment]
I use GCC 6.2.0 with latest MinGW distro. And a small problem appear now: when I carried out the command line make install, the file lapacke_mangling.h was not copied to install folder.

**Comment by martin-frbg** [comment]
Do you see any error messages associated with the copying of lapacke_mangling.h ? The line that does the copying (actually of the generated lapacke_mangling_with_flags.h to lapacke_mangling.h) appears to still be in Makefile.install.
And did the other header files (lapacke.h, lapacke_config.h, lapacke_utils.h) get copied ?

**Comment by ChristopheEcabert** [comment]
@martin-frbg there is the following error when installing :
```
...
Copying LAPACKE header files to <install_prefix>/include
install: cannot stat './lapack-netlib/LAPACKE/include/lapacke_mangling_with_flags.h' : No such file or directory
make[1]: [install] Error 1 (ignored)
...
```
Does not complain about other files.

**Comment by martin-frbg** [comment]
Got it now - this appears to be a recent change on the netlib side : previously the file was contained in the  LAPACK distribution as lapacke_mangling_with_flags.h with the expectation that it should be renamed  to lapacke_mangling.h when it is copied to /usr/include. Now the distribution has it named lapacke_mangling.h already so the line 53 in OpenBLAS' Makefile.install that copies it around needs to be changed accordingly.

**Comment by martin-frbg** [comment]
Makefile.install updated through #1064

**Comment by brada4** [comment]
does it change anything whether you use CMD.EXE or MSYS2.EXE shells?

**Comment by tuannhtn** [comment]
@martin-frbg : It is perfect now. Thank you.
@brada4 : I did not really understand you question. I used msys2.exe only. Thank you.

**Comment by brada4** [comment]
can you try to get errors if you start build from cmd.exe?

**Comment by tuannhtn** [comment]
@brada4 : I never try that. Instead, I always build OpenBlas with MinGW and then use it with Visual Studio.

**Comment by brada4** [comment]
i dont have windows. just that cmd should show different error messages.

**Comment by martin-frbg** [comment]
brada4 I am not sure I understand why you would expect using cmd instead of msys2 shell to impose a different limit on the number of arguments the mingw ar can handle ?
I noticed the build instructions for the Windows platform as provided on the netlib site call for running cmake to set up the compilation, maybe there is something in their CMakeFiles (or in the general cmake setup for Visual Studio/Windows) that works around the problem. (Or it could just be that building LAPACKE in that environment is less well tested ?)

**Comment by brada4** [comment]
Because CMD.exe will tell if script line is too long, path does not exist, and most importantly from where ar.exe was taken.

**Comment by martin-frbg** [comment]
I've floated the issue with netlib lapack to see if we can avoid falling into this trap with every new update.

**Comment by martin-frbg** [comment]
Julien Langou has kindly accepted the Makefile change into the netlib reference LAPACK, so hopefully this issue will not come up a fourth time in the future.
