### ISSUE TITLE
Lapack is not built when compiling with GCC 6.3.0

### ISSUE THREAD

**Issue by tuannhtn** [xianyi/OpenBLAS#1065]
Hello every one, I encountered a new issue when building OpenBlas with GCC 6.3.0. There was no error but OpenBlas was built without the lapack library. I did not know why since there was no error message. Did some one meet the same issue?

**Comment by martin-frbg** [comment]
Please make sure that your GCC 6.3.0 installation includes the FORTRAN compiler (gfortran)

**Comment by tuannhtn** [comment]
Thanks @martin-frbg, I checked and gfortran was missing in my GCC 6.3.0.
