### ISSUE TITLE
OpenBLAS installation fails on MSYS2 (proposed fix included)

### ISSUE THREAD

**Issue by mgrabner** [xianyi/OpenBLAS#1066]
The command "DESTDIR=/D/Software make PREFIX=/opt install" fails on MSYS2 (http://msys2.github.io) with the following error:

cp: cannot create regular file '/opt/bin': No such file or directory

Apparently a "$(DESTDIR)" is missing in Makefile.install, the following patch fixes the issue for me:

```
--- Makefile.install.orig       2017-01-16 09:30:56.755982900 +0100
+++ Makefile.install    2017-01-16 09:29:57.075254900 +0100
@@ -91,7 +91,7 @@
        @-cp $(LIBDLLNAME).a "$(DESTDIR)$(OPENBLAS_LIBRARY_DIR)"
 endif
 ifeq ($(OSNAME), CYGWIN_NT)
-       @-cp $(LIBDLLNAME) $(OPENBLAS_BINARY_DIR)
+       @-cp $(LIBDLLNAME) "$(DESTDIR)$(OPENBLAS_BINARY_DIR)"
 endif
 endif
 #Generating OpenBLASConfig.cmake
```

Kind regards,
Markus

**Comment by martin-frbg** [comment]
This indeed looks like a simple oversight, thanks for the notice and patch.
