### ISSUE TITLE
openblas centos problem of installation and use 

### ISSUE THREAD

**Issue by xuyan-piestat** [xianyi/OpenBLAS#1070]
my os is centos 6.6 ,when i make for openblas .at last error is :
linktest.c:(.text+0x3218): undefined reference to `zlatme_'
linktest.c:(.text+0x321f): undefined reference to `zlatmr_'
linktest.c:(.text+0x3226): undefined reference to `zlatms_'
linktest.c:(.text+0x322d): undefined reference to `zlatmt_'
collect2: ld returned 1 exit status
make[1]: *** [../libopenblas_haswellp-r0.2.19.so] Error 1
make[1]: Leaving directory `/home/OpenBLAS-0.2.19/exports'

why?

then i can make install to /opt/openblas
when i use R language to test  openblas，
update-alternatives --config libblas.so.3，no any output,
 i have installed blas and openblas 
blas is in /usr/lib64
openblas is in /opt/openblas

go to r shell 
x <- matrix(1:(3000 * 3000), 3000, 3000)
> system.time(tmp <- x %*% x)
   user  system elapsed 
 38.817   0.061  38.866 
i force to subtitude libblas.so.3 to openblas version 
unlink /usr/lib64/libblas.so.3
ln -s  ln -s /opt/OpenBLAS/lib/libopenblas.so /usr/lib64/libblas.so.3
unlink /usr/lib64/liblapack.so.3
ln -s /opt/OpenBLAS/lib/libopenblas.so /usr/lib64/openblas/liblapack.so.3
> system.time(tmp <- x %*% x)
   user  system elapsed 
 35.217   0.049  35.255 
echo $LD_LIBRARY_PATH   , result is 
/home/data2/daqi/pcre-8.39/lib:/home/data2/daqi/xz-5.2.2/lib:/home/data2/daqi/hdf5-1.8.8/lib:/usr/local/lib64/R/lib:/usr/local/lib:/usr/lib:/usr/lib64:

both almost have no difference .  I donot know why.
anyone tell me which step is wrong in my process.

**Comment by brada4** [comment]
Build error:
seek OpenBLAS FAQ which tells how to acquire recent binutils on CentOS 6
Then make clean before next build, and make sure to attach full build log, as the missing files are consequence of earlier errors.

R configuration:
Fedora has no alternatives mechanism for libblas.so as Debian.
You need to put symlink replacing libRblas.so (or install R from fedora EPEL to do that for you)
I dont think symlink juggling to emulate Ubuntu alternatives configuration has any effect whatsoever on CentOS or Fedora

**Comment by xuyan-piestat** [comment]
i  have  installed binutils 
install file is 
pb-binutils224-2.24-1.x86_64.rpm
and set its path in /etc/profile
echo $PATH
/opt/pb/binutils-2.24/bin:/home/data2/daqi/ncl/bin:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/home/data2/daqi/curl-7.51.0/bin:/home/data2/daqi/netcdf-4.1.3/bin:/root/bin




 
------------------ Original ------------------

**Comment by xuyan-piestat** [comment]
i am sure i make clean befor next make ,stiil have those error.
i am sure i repalce  libRblas.so.3 
Do i need to replace  libRblas.so?
 
------------------ Original ------------------

**Comment by brada4** [comment]
Can we get through with successful OpenBLAS build including attaching build log?
I am afraid I can help with drop-in replacement of OpenBLAS on top of vendor RPMs. Your 1km long PATH means it is unfixable.

**Comment by xuyan-piestat** [comment]
can you give me a binutils installation package,format of rpm or tar for centos and our openblas that can used?


 
------------------ Original ------------------

**Comment by martin-frbg** [comment]
Try http://sourceforge.net/projects/slurm-roll/files/addons/6.2.0/rpms/binutils/pb-binutils225-2.25-1.x86_64.rpm (and remember to update your path so tha/opt/pb/binutils-2.25/bin
gets tried first). If compilation still does not work, please upload the log here.

**Comment by brada4** [comment]
Or better this:
https://github.com/xianyi/OpenBLAS/wiki/faq#binutils

**Comment by xuyan-piestat** [comment]
now i update my gcc version fro old 4.4.7 to 4.8 ,
new version is in /usr/local/bin and /usr/local/lib64 ,
old version is in /usr/bin and /usr/lib64/ , 
then 
 update-alternatives --install /usr/bin/gcc gcc /usr/local/bin/gcc 101
updatedb
echo /usr/local/lib64 make  >> /etc/ld.so.conf
ldconfig
result is :
 gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-unknown-linux-gnu/4.8.0/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ../gcc-4.8.0/configure --enable-checking=release --enable-languages=c,c++,fortran,go --disable-multilib
Thread model: posix
gcc version 4.8.0 (GCC) 




then make my openblas ,stiil have errors as :
gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=48 -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  -w -o linktest linktest.c ../libopenblas_haswellp-r0.2.19.so -L/usr/local/lib/gcc/x86_64-unknown-linux-gnu/4.8.0 -L/usr/local/lib/gcc/x86_64-unknown-linux-gnu/4.8.0/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/local/lib/gcc/x86_64-unknown-linux-gnu/4.8.0/../../..  -lgfortran -lm -lquadmath -lm -lc   && echo OK.
/tmp/ccGoZCI8.o: In function `main':
linktest.c:(.text.startup+0x2f16): undefined reference to `clagge_'
linktest.c:(.text.startup+0x2f1d): undefined reference to `claghe_'
linktest.c:(.text.startup+0x2f24): undefined reference to `clagsy_'
linktest.c:(.text.startup+0x2f2b): undefined reference to `clahilb_'
linktest.c:(.text.startup+0x2f32): undefined reference to `clakf2_'
linktest.c:(.text.startup+0x2f39): undefined reference to `clarge_'
linktest.c:(.text.startup+0x2f40): undefined reference to `clarnd_'
linktest.c:(.text.startup+0x2f47): undefined reference to `claror_'
linktest.c:(.text.startup+0x2f4e): undefined reference to `clarot_'
linktest.c:(.text.startup+0x2f55): undefined reference to `clatm1_'
linktest.c:(.text.startup+0x2f5c): undefined reference to `clatm2_'
linktest.c:(.text.startup+0x2f63): undefined reference to `clatm3_'
linktest.c:(.text.startup+0x2f6a): undefined reference to `clatm5_'
linktest.c:(.text.startup+0x2f71): undefined reference to `clatm6_'
linktest.c:(.text.startup+0x2f78): undefined reference to `clatme_'
linktest.c:(.text.startup+0x2f7f): undefined reference to `clatmr_'
linktest.c:(.text.startup+0x2f86): undefined reference to `clatms_'
linktest.c:(.text.startup+0x2f8d): undefined reference to `clatmt_'
linktest.c:(.text.startup+0x2ff6): undefined reference to `dlagge_'
linktest.c:(.text.startup+0x2ffd): undefined reference to `dlagsy_'
linktest.c:(.text.startup+0x3004): undefined reference to `dlahilb_'
linktest.c:(.text.startup+0x300b): undefined reference to `dlakf2_'
linktest.c:(.text.startup+0x3012): undefined reference to `dlaran_'
linktest.c:(.text.startup+0x3019): undefined reference to `dlarge_'
linktest.c:(.text.startup+0x3020): undefined reference to `dlarnd_'
linktest.c:(.text.startup+0x3027): undefined reference to `dlaror_'
linktest.c:(.text.startup+0x302e): undefined reference to `dlarot_'
linktest.c:(.text.startup+0x3035): undefined reference to `dlatm1_'
linktest.c:(.text.startup+0x303c): undefined reference to `dlatm2_'
linktest.c:(.text.startup+0x3043): undefined reference to `dlatm3_'
linktest.c:(.text.startup+0x304a): undefined reference to `dlatm5_'
linktest.c:(.text.startup+0x3051): undefined reference to `dlatm6_'
linktest.c:(.text.startup+0x3058): undefined reference to `dlatm7_'
linktest.c:(.text.startup+0x305f): undefined reference to `dlatme_'
linktest.c:(.text.startup+0x3066): undefined reference to `dlatmr_'
linktest.c:(.text.startup+0x306d): undefined reference to `dlatms_'
linktest.c:(.text.startup+0x3074): undefined reference to `dlatmt_'
linktest.c:(.text.startup+0x30d6): undefined reference to `slagge_'
linktest.c:(.text.startup+0x30dd): undefined reference to `slagsy_'
linktest.c:(.text.startup+0x30e4): undefined reference to `slahilb_'
linktest.c:(.text.startup+0x30eb): undefined reference to `slakf2_'
linktest.c:(.text.startup+0x30f2): undefined reference to `slaran_'
linktest.c:(.text.startup+0x30f9): undefined reference to `slarge_'
linktest.c:(.text.startup+0x3100): undefined reference to `slarnd_'
linktest.c:(.text.startup+0x3107): undefined reference to `slaror_'
linktest.c:(.text.startup+0x310e): undefined reference to `slarot_'
linktest.c:(.text.startup+0x3115): undefined reference to `slatm1_'
linktest.c:(.text.startup+0x311c): undefined reference to `slatm2_'
linktest.c:(.text.startup+0x3123): undefined reference to `slatm3_'
linktest.c:(.text.startup+0x312a): undefined reference to `slatm5_'
linktest.c:(.text.startup+0x3131): undefined reference to `slatm6_'
linktest.c:(.text.startup+0x3138): undefined reference to `slatm7_'
linktest.c:(.text.startup+0x313f): undefined reference to `slatme_'
linktest.c:(.text.startup+0x3146): undefined reference to `slatmr_'
linktest.c:(.text.startup+0x314d): undefined reference to `slatms_'
linktest.c:(.text.startup+0x3154): undefined reference to `slatmt_'
linktest.c:(.text.startup+0x31b6): undefined reference to `zlagge_'
linktest.c:(.text.startup+0x31bd): undefined reference to `zlaghe_'
linktest.c:(.text.startup+0x31c4): undefined reference to `zlagsy_'
linktest.c:(.text.startup+0x31cb): undefined reference to `zlahilb_'
linktest.c:(.text.startup+0x31d2): undefined reference to `zlakf2_'
linktest.c:(.text.startup+0x31d9): undefined reference to `zlarge_'
linktest.c:(.text.startup+0x31e0): undefined reference to `zlarnd_'
linktest.c:(.text.startup+0x31e7): undefined reference to `zlaror_'
linktest.c:(.text.startup+0x31ee): undefined reference to `zlarot_'
linktest.c:(.text.startup+0x31f5): undefined reference to `zlatm1_'
linktest.c:(.text.startup+0x31fc): undefined reference to `zlatm2_'
linktest.c:(.text.startup+0x3203): undefined reference to `zlatm3_'
linktest.c:(.text.startup+0x320a): undefined reference to `zlatm5_'
linktest.c:(.text.startup+0x3211): undefined reference to `zlatm6_'
linktest.c:(.text.startup+0x3218): undefined reference to `zlatme_'
linktest.c:(.text.startup+0x321f): undefined reference to `zlatmr_'
linktest.c:(.text.startup+0x3226): undefined reference to `zlatms_'
linktest.c:(.text.startup+0x322d): undefined reference to `zlatmt_'
collect2: error: ld returned 1 exit status
make[1]: *** [../libopenblas_haswellp-r0.2.19.so] Error 1
make[1]: Leaving directory `/home/OpenBLAS-0.2.19/exports'
make: *** [shared] Error 2



which library(****.so) i should change from 4.4.7 to 4.8 version?  or any suggest?
 
 
------------------ Original ------------------

**Comment by xuyan-piestat** [comment]
can i speak chinese about problem of installation?
 
 
------------------ Original ------------------

**Comment by martin-frbg** [comment]
These are the LAPACK function which are written in FORTRAN, maybe you did not install gcc-gfortran ?

**Comment by brada4** [comment]
No need to speak Chinese.
OpenBLAS builds perfectly with gcc and gfortran included in
RHEL5 AVX2 via binutils=devtoolset 2.1, min kernel 5U10
6 AVX2 via devtoolst 3+, min kernel 6U3
7 = all supported without any change

Please just choose:
Recipe A 
# yum install gcc gcc-gfortran
$ make NO_AVX2=1
Recipe B
# yum install epel-release
# yum install openblas-devel
Recipe C
is outlined in FAQ

You add too much variables with homebrew build of GCC, it will not be possible to fix any issues.
Please install official software so that we have chance to run into any problems you encounter.

**Comment by martin-frbg** [comment]
I expect there are enough people here who read Chinese - certainly xianyi at least, and us illiterate westerners can at least try google translate.
Perhaps it would be a good idea to have the FAQ and Installation Guide in the wiki in Chinese (and eventually Arabic) as well ?

**Comment by brada4** [comment]
Or adhere to simplified english idea in current faq at least...

**Comment by xuyan-piestat** [comment]
i still failed. i am not new hand  of linux .i am sure that i installed gcc-gfortran, two version :4.4.7 and your 4.8  of update.now i switched to your 4.8 version of gcc , and i have no error such as "no ***.so library",    i also changed some softlink of /usr/lib64 about libgcc and libgfortran from 4.4.77 to 4.8 . 


i  also executed the command such as :
yum install blas blas-devel lapack lapack-devel atlas atlas-devel --nogpgcheck
then make FC=gfortran   still have errors:
linktest.c:(.text.startup+0x76b3): undefined reference to `LAPACKE_zpotrf2'
linktest.c:(.text.startup+0x76ba): undefined reference to `LAPACKE_zpotrf2_work'
linktest.c:(.text.startup+0x76c1): undefined reference to `LAPACKE_zsytrf_rook'
linktest.c:(.text.startup+0x76c8): undefined reference to `LAPACKE_zsytrf_rook_work'
linktest.c:(.text.startup+0x76cf): undefined reference to `LAPACKE_zsytrs_rook'
linktest.c:(.text.startup+0x76d6): undefined reference to `LAPACKE_zsytrs_rook_work'
linktest.c:(.text.startup+0x76dd): undefined reference to `LAPACKE_zuncsd2by1'
linktest.c:(.text.startup+0x76e4): undefined reference to `LAPACKE_zuncsd2by1_work'
collect2: error: ld returned 1 exit status
 
 why? maybe i should set some path for lapack?
i locate lapack  ,the result is as :
/usr/lib64/liblapack.a
/usr/lib64/liblapack.so
/usr/lib64/liblapack.so.3
/usr/lib64/liblapack.so.3.2.1
/usr/lib64/liblapack_pic.a
/usr/lib64/atlas/libclapack.so
/usr/lib64/atlas/libclapack.so.3
/usr/lib64/atlas/libclapack.so.3.0
/usr/lib64/atlas/liblapack.a
/usr/lib64/atlas/liblapack.so
/usr/lib64/atlas/liblapack.so.3
/usr/lib64/atlas/liblapack.so.3.0
/usr/lib64/openblas/liblapack.so.3



------------------ Original ------------------

**Comment by brada4** [comment]
Can you first decide if you want atlas or you want openblas.

**Comment by martin-frbg** [comment]
> yum install blas blas-devel lapack lapack-devel atlas atlas-devel --nogpgcheck
Not sure why you did this, this installs alternatives to OpenBLAS. 
If you want only the BLAS part from OpenBLAS, you can build it with "make clean; make NO_LAPACK=1"
