### ISSUE TITLE
OpenBLAS-v0.2.19-Win32.zip is incomplete

### ISSUE THREAD

**Issue by ketigid** [xianyi/OpenBLAS#1073]
Hi,

I downloaded OpenBLAS-v0.2.19-Win32.zip prebuilt binaries from sourceforge but it was incomplete. libopenblas.dll.a and libopenblas.dll are missing.

**Comment by brada4** [comment]
They are last present in v0.2.15

**Comment by martin-frbg** [comment]
Could you check if these work (cross-compiled on Linux using the MXE flavor of mingw32-gcc.4.9.2, using the options documented in the readme.txt of xianyi's zip archive) ?
[libs.zip](https://github.com/xianyi/OpenBLAS/files/725155/libs.zip)

**Comment by ketigid** [comment]
v0.2.15 works. I have not tested the libs.zip though. Thanks anyway.

**Comment by lofrank** [comment]
@martin-frbg 
Thanks for your win32 version, it works for me.
