### ISSUE TITLE
compiling issue with OpenBLASS

### ISSUE THREAD

**Issue by deepakaswadhati** [xianyi/OpenBLAS#1075]
hello 
i am getting  issue while i am compiling OpenBLASS source code on my ubuntu x86pc
for compiling i am using this command  
step:
cd OpenBLASS
make TARGET=ARMV8 BINARY=64
error:
../libopenblas_nehalemp-r0.2.20.dev.a(ssymv_U.o): In function `ssymv_U':
(.text+0x2e2): undefined reference to `PREFETCHSIZE'
../libopenblas_nehalemp-r0.2.20.dev.a(ssymv_U.o): In function `ssymv_U':
(.text+0x32a): undefined reference to `PREFETCHSIZE'
../libopenblas_nehalemp-r0.2.20.dev.a(ssymv_U.o): In function `ssymv_U':
(.text+0x38b): undefined reference to `PREFETCHSIZE'
../libopenblas_nehalemp-r0.2.20.dev.a(ssymv_U.o): In function `ssymv_U':
(.text+0x42c): undefined reference to `PREFETCHSIZE'
../libopenblas_nehalemp-r0.2.20.dev.a(ssymv_U.o): In function `ssymv_U':
(.text+0x474): undefined reference to `PREFETCHSIZE'
../libopenblas_nehalemp-r0.2.20.dev.a(ssymv_U.o):(.text+0x4d6): more undefined references to `PREFETCHSIZE' follow
gfortran -Wall -m64   -o sblat3 sblat3.o ../libopenblas_nehalemp-r0.2.20.dev.a -lm -lpthread -lgfortran -lm -lpthread -lgfortran 
../libopenblas_nehalemp-r0.2.20.dev.a(dsymv_U.o): In function `dsymv_U':
(.text+0x2ca): undefined reference to `PREFETCHSIZE'
../libopenblas_nehalemp-r0.2.20.dev.a(dsymv_U.o): In function `dsymv_U':
(.text+0x31c): undefined reference to `PREFETCHSIZE'
../libopenblas_nehalemp-r0.2.20.dev.a(dsymv_U.o): In function `dsymv_U':
(.text+0x372): undefined reference to `PREFETCHSIZE'
../libopenblas_nehalemp-r0.2.20.dev.a(dsymv_U.o): In function `dsymv_U':
(.text+0x44c): undefined reference to `PREFETCHSIZE'
../libopenblas_nehalemp-r0.2.20.dev.a(dsymv_U.o): In function `dsymv_U':
(.text+0x49e): undefined reference to `PREFETCHSIZE'
../libopenblas_nehalemp-r0.2.20.dev.a(dsymv_U.o):(.text+0x4f4): more undefined references to `PREFETCHSIZE' follow
../libopenblas_nehalemp-r0.2.20.dev.a(zhemv_U.o): In function `zhemv_U':
(.text+0x370): undefined reference to `PREFETCHSIZE'
../libopenblas_nehalemp-r0.2.20.dev.a(zhemv_U.o): In function `zhemv_U':
(.text+0x3e7): undefined reference to `PREFETCHSIZE'
../libopenblas_nehalemp-r0.2.20.dev.a(zhemv_U.o): In function `zhemv_U':
(.text+0x4b2): undefined reference to `PREFETCHSIZE'
../libopenblas_nehalemp-r0.2.20.dev.a(zhemv_U.o): In function `zhemv_U':
(.text+0x540): undefined reference to `PREFETCHSIZE'
../libopenblas_nehalemp-r0.2.20.dev.a(zhemv_L.o): In function `zhemv_L':
(.text+0x3d8): undefined reference to `PREFETCHSIZE'
../libopenblas_nehalemp-r0.2.20.dev.a(zhemv_L.o):(.text+0x44f): more undefined references to `PREFETCHSIZE' follow
gfortran -Wall -m64   -o dblat3 dblat3.o ../libopenblas_nehalemp-r0.2.20.dev.a -lm -lpthread -lgfortran -lm -lpthread -lgfortran 
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
Makefile:144: recipe for target 'sblat2' failed
make[1]: *** [sblat2] Error 1
make[1]: *** Waiting for unfinished jobs....
Makefile:147: recipe for target 'dblat2' failed
make[1]: *** [dblat2] Error 1
Makefile:153: recipe for target 'zblat2' failed
make[1]: *** [zblat2] Error 1
make[1]: Leaving directory '/home/deepak/OpenBLAS/test'
Makefile:111: recipe for target 'tests' failed
make: *** [tests] Error 2
 
please give me the solution

**Comment by ashwinyes** [comment]
I believe you are trying to compile for aarch64. In that case, you are using the native x86 compiler to cross compile for aarch64 which is obviously not the right thing to do.

Install the aarch64 cross compiler on Ubuntu.
sudo apt-get install gcc-aarch64-linux-gnu

Use the installed aarch64 cross compiler to cross compile. I would suggest using TARGET=CORTEXA57 as it has more optimized implementations compared to TARGET=ARMV8.
make CC=aarch64-linux-gnu-gcc FC=aarch64-linux-gnu-gfortran HOSTCC=gcc TARGET=CORTEXA57

**Comment by deepakaswadhati** [comment]
hello
i am compiling the OpenBLAS tool on ubuntu ARM architecture board build is done successfully but while running phase test cases i am getting issues give me some hint to overcome.
command i have used: cd OpenBLAS
   export OPENBLAS_NUM_THREADS=1
    taskset -c 0 ./sgemm.goto 200 4000 200
Error:
./sgemm.goto: 3: ./sgemm.goto: Syntax error: word unexpected (expecting ")")

**Comment by ashwinyes** [comment]
You may be trying to run cross compiled executable on a host system.

Please explain the following properly.
1. Are you compiling for ARM (32 bit) or Aarch64 (ARM 64 bit) ??
2. Details of the machine where you are compiling OpenBLAS.
3. Details of the machine where you are going to run OpenBLAS.

**Comment by brada4** [comment]
cross-compilation does not build tests. Please run 'make clean' before building again.

**Comment by martin-frbg** [comment]
Did you get this sorted in the meantime, or would you like further assistance ?
