### ISSUE TITLE
Error:(69, 38) error: unknown register name 'r2' in asm

### ISSUE THREAD

**Issue by liuyi999111** [xianyi/OpenBLAS#1099]
I have build OpenBlas for a Android project. I get the static lib and link it to my native project. But when I compile Android project get back this error message. 

![image](https://cloud.githubusercontent.com/assets/13236407/22959625/d1a4d9a2-f372-11e6-97ff-e51a18850556.png)

**Comment by martin-frbg** [comment]
Can you describe your compile process in more detail please (I assume you are cross-compiling on a pc, what toolchain do you use) ? 
I understand the compilation of OpenBLAS itself was successful (?) and that error looks a bit as if you picked a different compiler when you tried to build your own project - possibly the native x86 compiler that does not understand ARM assembly.

**Comment by liuyi999111** [comment]
The compilation of OpenBLAS itself was successful. The toolchain I use like arm-linux-androideabi-4.9 for darwin-x86_64. 
I replace that toolchain whith aarch64-linux-android-4.9 and add a abiFilter in my Gradle script.It's works. I use CMake to compile my native code.

**Comment by brada4** [comment]
Can you drill down issue to a single command?
The ASM section in that header file is pretty legitimate, it just looks that you supposedly ARM gcc picks x86 assembler instead of ARM one.
