### ISSUE TITLE
Compiling openBLAS:  ar: strmm_kernel_LN.o: No such file or directory

### ISSUE THREAD

**Issue by himanshubdave** [xianyi/OpenBLAS#1106]
**uname -a:**
Linux laptop 4.4.14-smp #2 SMP Fri Jun 24 14:44:24 CDT 2016 i686 Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz GenuineIntel GNU/Linux

while compiling openBLAS, at library building stage I get an error:
ar: strmm_kernel_LN.o: No such file or directory
../Makefile.tail:40: recipe for target 'libs' failed
make[1]: *** [libs] Error 1
make[1]: Leaving directory '/home/hbd/Downloads/xianyi-OpenBLAS-bcfc298/kernel'
Makefile:133: recipe for target 'libs' failed
make: *** [libs] Error 1

Help requested.

**Comment by brada4** [comment]
Please run 'make clean' before next build.
Any compelling reason to have 32bit system on a very recent 64bit CPU?

**Comment by brada4** [comment]
Can you post /proc/cpuid (just last core info, this ULT Haswell is not with CPUID range with other Haswel)
TARGET=Haswell should build for your CPU

**Comment by martin-frbg** [comment]
Please try building with "make BINARY=32" after the "make clean" (this should work but will give only NEHALEM-class optimization, see #657)

**Comment by himanshubdave** [comment]
[A] from /proc/cpuinfo:
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 69
model name      : Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz
stepping        : 1
microcode       : 0x17
cpu MHz         : 1599.992
cache size      : 3072 KB
---------------------------------------------------------------------
[B]
with: make clean and make TARGET=Haswell
No luck, same error

[C] with  make BINARY=32  it worked!
OpenBLAS build complete. (BLAS CBLAS LAPACK LAPACKE)
  OS               ... Linux             
  Architecture     ... x86               
  BINARY           ... 32bit                 
  C compiler       ... GCC  (command line : gcc)
  Fortran compiler ... GFORTRAN  (command line : gfortran)
  Library Name     ... libopenblas_nehalemp-r0.2.19.a (Multi threaded; Max num-threads is 4)

[D] Why 32-bit system on a 64-bit machine?: My older laptop went dead just a couple of hours before the first day of an engineer's  training series which I needed to engage. Already having a DVD of Slackware 14.2 (32-bit), compelled me to install it on the new 64-bit machine.

Thanks a lot for help.

**Comment by himanshubdave** [comment]
[A] from /proc/cpuinfo:
processor : 0
vendor_id : GenuineIntel
cpu family : 6
model : 69
model name : Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz
stepping : 1
microcode : 0x17
cpu MHz : 1599.992
cache size : 3072 KB

[B]
with: make clean and make TARGET=Haswell
No luck, same error

[C] with make BINARY=32 it worked!
OpenBLAS build complete. (BLAS CBLAS LAPACK LAPACKE)
OS ... Linux
Architecture ... x86
BINARY ... 32bit
C compiler ... GCC (command line : gcc)
Fortran compiler ... GFORTRAN (command line : gfortran)
Library Name ... libopenblas_nehalemp-r0.2.19.a (Multi threaded; Max
num-threads is 4)

[D] Why 32-bit system on a 64-bit machine?: My older laptop went dead just
a couple of hours before the first day of an engineer's training series
which I needed to engage. Already having a DVD of Slackware 14.2 (32-bit),
compelled me to install it on the new 64-bit machine.

*Thanks a lot for help*.

--
-- HBDave
Senior Consultant (Training), eInfochips, Ahmedabad, India



*May you do good and not evil May you find forgiveness for yourself and
forgive others May you share freely, never taking more than you give.*

*                                       -- from Sqlite3 source code*

**Comment by himanshubdave** [comment]
[A] from /proc/cpuinfo:
processor : 0
vendor_id : GenuineIntel
cpu family : 6
model : 69
model name : Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz
stepping : 1
microcode : 0x17
cpu MHz : 1599.992
cache size : 3072 KB

[B]
with: make clean and make TARGET=Haswell
No luck, same error

[C] with make BINARY=32 it worked!
OpenBLAS build complete. (BLAS CBLAS LAPACK LAPACKE)
OS ... Linux
Architecture ... x86
BINARY ... 32bit
C compiler ... GCC (command line : gcc)
Fortran compiler ... GFORTRAN (command line : gfortran)
Library Name ... libopenblas_nehalemp-r0.2.19.a (Multi threaded; Max
num-threads is 4)

[D] Why 32-bit system on a 64-bit machine?: My older laptop went dead just
a couple of hours before the first day of an engineer's training series
which I needed to engage. Already having a DVD of Slackware 14.2 (32-bit),
compelled me to install it on the new 64-bit machine.

*Thanks a lot for help.*

--
-- HBDave
Senior Consultant (Training), eInfochips, Ahmedabad, India



*May you do good and not evil May you find forgiveness for yourself and
forgive others May you share freely, never taking more than you give.*

*                                       -- from Sqlite3 source code*

**Comment by DuZhengyuan** [comment]
with make BINARY=32 can work.
Thanks a lot.
