### ISSUE TITLE
Windows binary distribution missing DLL dependencies

### ISSUE THREAD

**Issue by twadleigh** [xianyi/OpenBLAS#1112]
The windows distribution ships `libopenblas.dll` but does not include its dependencies:
 - `libgcc_s_seh-1.dll`
 - `libgfortran-3.dll`
 - `libquadmath-0.dll`

As the typical user of the windows binary distribution (I would assert) ought not be required to already have these on their system (if they did, they'd more likely be inclined to build from source), so I would suggest they be included in the download bundle.

The discussion in #296 touches on the dependency issue, but there the discussion veers toward statically linking the dependencies. That would be fine with me, but so would just distributing these extras in the bundle.

**Comment by martin-frbg** [comment]
These libraries appear to be available as separate bundles already,
http://sourceforge.net/projects/openblas/files/v0.2.12/mingw64_dll.zip/download
http://sourceforge.net/projects/openblas/files/v0.2.12/mingw32_dll.zip/download
(following a request on the OpenBLAS-users mailing list back in october 2014) so possibly it is just the project download area on sf.net that needs to be reorganized to make them more obvious

**Comment by brada4** [comment]
Do you always report a bug when you need next vcredist.exe ?

**Comment by twadleigh** [comment]
@martin-frbg OK I see those files. I wouldn't have known to find them there, though. In fact, after reading your comment I started by just looking closer at the SF downloads to see if I could find them myself, but could not.

Maybe it would be sufficient to put a note in README of the bundle pointing to the additional DLLs and/or add a link to the extras next to the binary package link on the [www.openblas.net front page](http://www.openblas.net/)?

**Comment by martin-frbg** [comment]
Have to defer to xianyi on this (and #1073) as I do not have write access to the SF download area or the openblas.net page unfortunately.

**Comment by martin-frbg** [comment]
thx for reminding me to mention the location of the mingw dependencies on the openblas.net site. (I got access to the website sources in the meantime, but not to the sf.net account where the binaries are hosted)

**Comment by EricGrange** [comment]
Last version depends on a libgfortran-5.dll, any clues where it could be found ?

The mingw-w64 releases have a libgfortran-3 for 5.4, libgfortran-4 for 7.3, but the 8.1 release has no libgfortran at all anymore ?

**Comment by martin-frbg** [comment]
Are you referring to https://github.com/xianyi/OpenBLAS/releases/download/v0.3.10/OpenBLAS-0.3.10-x64.zip as the last version, or one of the older releases on sf.net ? (The Windows binaries are currently cross-compiled with
the MXE version of mingw on Linux, which is gcc 5.5.0)

**Comment by EricGrange** [comment]
Hmm, no I started following links from the website and ended up downloading OpenBLAS.v0.3.0.x86_64-w64-mingw32-gcc8.tar.gz

The version you linked works like a charm however. I will stick to the github content now, thanks!
