### ISSUE TITLE
cross compile on x86_64 for cortexA57 target fail!!!please help

### ISSUE THREAD

**Issue by huanhuanxixi** [xianyi/OpenBLAS#1116]
i have install aarch64-linux-gnu-gcc and set the $PATH
but when i git clone the source code of openblas using:
make BINARY=64 ARCH=arm64  CC=aarch64-linux-gnu-gcc HOSTCC=gcc TARGET=CORTEXA57
it returns to this:
```
getarch.c:80:19: fatal error: stdio.h: No such file or directory
compilation terminated.
make: *** [getarch] Error 1
Makefile.system:169: Makefile.conf: No such file or directory
make: *** No rule to make target `Makefile.conf'.  Stop.
```
but the stdio.h does exist:
`find / -name stdio.h
/usr/local/arm-toolchain/aarch64-gnu/lib/gcc/aarch64-linux-gnu/5.4.1/include/ssp/stdio.h
/usr/local/arm-toolchain/aarch64-gnu/aarch64-linux-gnu/libc/usr/include/stdio.h
/usr/local/arm-toolchain/aarch64-gnu/aarch64-linux-gnu/libc/usr/include/bits/stdio.h
/usr/local/arm-toolchain/aarch64-gnu/aarch64-linux-gnu/include/c++/5.4.1/tr1/stdio.h
`

cloud anyone help me? any advice or suggestions will be helpful,thanks.

**Comment by ashwinyes** [comment]
getarch.c is compiled using HOSTCC.

Check whether stdio.h is available for your HOSTCC.

**Comment by huanhuanxixi** [comment]
thanks ashwinyes for your advice.it really works~~~even though i spent 1.5days to slove the problem that build-essentiall couldn't be installed through the apt source offered by inner companny.

thanks again~~~@ashwinyes
