### ISSUE TITLE
ppc64le instead of power in OpenBLAS/kernel/ppc64le/KERNEL.POWER8

### ISSUE THREAD

**Issue by JaeseungYeom** [xianyi/OpenBLAS#1120]
cmake is trying to access OpenBLAS/kernel/ppc64le/KERNEL.POWER8 which does not exist

**Comment by martin-frbg** [comment]
How are you building OpenBLAS ? 
For this problem to occur, I think the build system would somehow have to see "ARCH" as "ppc64le" instead of "power" (so that this wrong phrase gets inserted into the KERNELDIR variable by cmake/system.cmake) and I do not yet see how this could happen. Nothing in the autodetection uses "ppc64le", the only spot where "ppc" appears - at the start of the c_check script where it parses the output from "uname", it is used to define hostarch as "power".

**Comment by JaeseungYeom** [comment]
uname -m shows ppcle64

clang -E ctest.c shows belw
`COMPILER_CLANG
COMPILER_GNU
OS_LINUX
ARCH_POWER
BINARY_64`

build command as below
`cmake -D CMAKE_CXX_COMPILER=clang++ \
-D CMAKE_C_COMPILER=clang \
-D CMAKE_Fortran_COMPILER=gfortran \
-D GFORTRAN_LIB=/usr/...../gcc/gcc-4.9.3/lib64/libgfortran.so \
-D TARGET=POWER8 \
-D ARCH=power \
-D CC=clang ..`

Finally, the message I am getting is as below
`-- Targetting the POWER8 architecture.
-- GEMM multithread threshold set to 4.
-- Running getarch
-- GETARCH results:
CORE=POWER8
LIBCORE=power8
NUM_CORES=160
MAKE += -j 160

-- SMP enabled.
-- Building Single Precision
-- Building Double Precision
-- Building Complex Precision
-- Building Double Complex Precision
-- Reading vars from /....../OpenBLAS/kernel/ppc64le/KERNEL...
CMake Error at cmake/utils.cmake:18 (file):
  file STRINGS file
  "/......OpenBLAS/kernel/ppc64le/KERNEL" cannot be
  read.
Call Stack (most recent call first):
  kernel/CMakeLists.txt:21 (ParseMakefileVars)


-- Reading vars from /....../OpenBLAS/kernel/ppc64le/KERNEL.POWER8...
CMake Error at cmake/utils.cmake:18 (file):
  file STRINGS file
  "/......OpenBLAS/kernel/ppc64le/KERNEL.POWER8" cannot
  be read.
Call Stack (most recent call first):
  kernel/CMakeLists.txt:22 (ParseMakefileVars)


-- Configuring incomplete, errors occurred!
`

**Comment by martin-frbg** [comment]
Strange - it seems to have ARCH=power and still set KERNELDIR to something else.
The brute force workaround would seem to be to edit the 

  set(KERNELDIR   "${PROJECT_SOURCE_DIR}/kernel/${ARCH}")

near the middle of cmake/system.cmake to replace ${ARCH} with "power" 
(or insert a line "set(ARCH power)" before it).

**Comment by JaeseungYeom** [comment]
The above stage has passed and configuration is done.
Now I am seeing other error as below

-- Configuring done
CMake Error at CMakeLists.txt:170 (add_library):
  Cannot find source file:

    /....../OpenBLAS/lapack-netlib/SRC/zlasy_aa.f

I see a file zlasyf_aa.f, which is quite similar to zlasy_aa.f
Perhaps, I should change this somewhere and retry?

**Comment by martin-frbg** [comment]
That indeed looks like a typo in cmake/lapack.cmake (and probably mine, sorry). I wonder why this was not caught earlier.

**Comment by martin-frbg** [comment]
Both hopefully fixed now (seems cmake does not use the c_check binary but tries to deduct equivalent information from the cmake builtins via c_check.cmake).

**Comment by JaeseungYeom** [comment]
Thanks for helping me to get through this.
Fixing that typo allowed me to complete cmake configuration stage.
following make generates some other errors.
/usr/workspace/wsb/yeom2/ray/OpenBLAS/common.h:648:3: error: use of undeclared identifier 'MB'
I suspect that the corrected architecture detection might solve the issue. Will see.

**Comment by JaeseungYeom** [comment]
I also want to mention that it compiles fine using gcc. The issue might be triggered by how clang is installed on my local system.

**Comment by martin-frbg** [comment]
I suspect you used the (less well tested) cmake environment with clang, and plain "make" with gcc ? At least all the problems you encountered are/were genuine bugs in the OpenBLAS cmake files (I strongly suspect the "undeclared identifier MB" comes from common.h being unable to include "power.h" as it gets told that ARCH is "ppc64le")

**Comment by JaeseungYeom** [comment]
I agree with you on MB related error coming from common.h being unable to include correct header due to confused architecture.

**Comment by JaeseungYeom** [comment]
We had some system upgrade and the above `MB` problem is somehow gone. However, another compiling issue I have encountered is `unknown register name 'vs32' in asm`. I wonder if this is a clang problem. There are about a dozen files that include this under `kernel/power`. 
When I try 'gcc -S' on these files, it works. However, it does not with 'clang -mcpu=power8 -faltivec'
If I use `TARGET=POWER6` instead of `POWER8`, it compiles probably because those files that include VSX registers are excluded.

**Comment by martin-frbg** [comment]
Strange (unless you pulled my supposed fixes for the ARCH misreporting). Guess you could try adding  "-no-integrated-as" to CFLAGS to make it use the GNU as (or whatever else is available on the system).

**Comment by JaeseungYeom** [comment]
Indeed, I already pulled your fixes. Thanks a lot for the helps.

**Comment by martin-frbg** [comment]
For the vsx issue, could you try with "-mvsx" and/or "-mpower8-vector" in case this is not already implied by the -mcpu=power8 ?
(It could be that the vsx dependency was added only very recently as part of #1078, and the cmakefiles need to be updated to include such option)

**Comment by JaeseungYeom** [comment]
I tried both and they don't seem to be effective with clang version I have. I will just have to compile using gcc. Nevertheless, that was a good information to have.

**Comment by edelsohn** [comment]
@JaeseungYeom Please open this issue in the LLVM community for compatibility with GCC.

**Comment by martin-frbg** [comment]
Did anybody follow up on this ? I suspect the vsx support issue may have been due to the old version 3.8.0 of LLVM used, and I would like to close this issue ticket as the original problem has been fixed.
