### ISSUE TITLE
Openblas crash on android

### ISSUE THREAD

**Issue by gaoqiang** [xianyi/OpenBLAS#1125]
Hi, 
I did successfully finish the cross-compile(TARGET=ARMv7) according to https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android. When linking the generated static library with NDK, I got the error:
uses VFP register arguments, output does not 

Then I did set  the params in my Android.mk, and the error gone. 
LOCAL_CFLAGS += -mhard-float -D_NDK_MATH_NO_SOFTFP=1
LOCAL_LDFLAGS += -Wl,--no-warn-mismatch -lm_hard.

But when  I ran the simple example, my app crashed without any info:
#include <cblas.h>
#include <stdio.h>

void main()
{
  int i=0;
  double A[6] = {1.0,2.0,1.0,-3.0,4.0,-1.0};         
  double B[6] = {1.0,2.0,1.0,-3.0,4.0,-1.0};  
  double C[9] = {.5,.5,.5,.5,.5,.5,.5,.5,.5}; 
  cblas_dgemm(CblasColMajor, CblasNoTrans, CblasTrans,3,3,2,1,A, 3, B, 3,2,C,3);

  for(i=0; i<9; i++)
    printf("%lf ", C[i]);
  printf("\n");
}

I will really appreciate if you can help me.

**Comment by brada4** [comment]
Is it a spelling error?
s/LOCAL/TARGET/g

**Comment by gaoqiang** [comment]
Not a spelling error. It did seems that 'LOCAL' cleans the link error, though the apk still cannot run. And I have tried 'TARGET'，but it didn't work. I did not find some variables named "TARGET_CFLAGS " or "TARGET_LDFLAGS " at https://developer.android.google.cn/ndk/guides/android_mk.html , while I was wondering why did you use 'TARGET'. Or did I have any misunderstand?

**Comment by brada4** [comment]
The warning message you show comes exactly from not setting TARGET_ variables.

**Comment by brada4** [comment]
Can you make consistent set build log and backtrace from crash?
Preferably with single-threaded openblas if it crashes in that case (easier to debug with your hands)

**Comment by gaoqiang** [comment]
The TARGET_ variables works for me finally! The crash is just one naive mistake having nothing to do with openblas! thx so much!

**Comment by xiestone1992** [comment]
@gaoqiang 
hey ! I just have the same problem with you , can you explain more detail about solutions?  Where did you set the  "TARGET_" variables?

**Comment by xiestone1992** [comment]
@brada4 
Hey! I just want to ask you where should I set "TARGET_" variables?  in Android.mk ?

**Comment by brada4** [comment]
Typically in application.mk, system environment is valid too.

**Comment by xiestone1992** [comment]
@brada4 Thanks for quick reply.  I will try.

**Comment by gaoqiang** [comment]
I set "TARGET_" variables in Android.mk and it worked. I did not try application.mk.

**Comment by xiestone1992** [comment]
@gaoqiang  THX ! I will try it .
