### ISSUE TITLE
About P,Q,R meaning

### ISSUE THREAD

**Issue by ccJia** [xianyi/OpenBLAS#1136]
Hi, we are reading the function "blas_set_parameter", but we have trouble understanding the meaning of GEMM_P, GEMM_Q, GEMM_R. Could anyone explaint them to us. Thanks a lot for your help.For now we know they are some consts relevant to the system.

**Comment by martin-frbg** [comment]
I expect these follow the notation used by K.Goto in his seminal article on optimizing GEMM for modern computers with multiple levels of cache - Goto, Kazushige; van de Geijn, Robert A; Anatomy of high-performance matrix multiplication. ACM Transactions on  Mathematical Software (TOMS). Volume 34 Issue 3, May 2008 
While this article is paywalled and too old for preprints to be available on arxiv.org, more recent 
publications like https://arxiv.org/pdf/1609.00076 contain at least a brief description of the algorithm.

**Comment by silrep** [comment]
@martin-frbg 
Hi, martin. I've read the paper you gave. It seems that GEMM_P * GEMM_Q is the L2 cache size and GEMM_R * GEMM_Q is the L3 cache size.  However, it still confuses me that how "GEMM_P = 224 ..." comes out.

**Comment by ashwinyes** [comment]
There is no strict rule that PxQ and RxQ to be equal to L2 or L3 cache sizes. 

These params determines the block sizes and for most cases the values are fixed as the best values obtained through experimentation.

I believe Normally the best numbers are seen when PxQ is about half the size of L2 cache. So it is used as an indicator while doing the experiments.

**Comment by martin-frbg** [comment]
Closing after copying the information to the FAQ
