### ISSUE TITLE
Compile error getarch_2nd AMD barcelona: SGEMM_DEFAULT_UNROLL_M undeclared

### ISSUE THREAD

**Issue by JohannesBuchner** [xianyi/OpenBLAS#1139]
I get the following issue when trying to build with make: 
- make calls a build of getarch_2nd, which fails. It continues anyway but ultimately the build fails.
- The problem is that SGEMM_DEFAULT_UNROLL_N is not defined given the specific FLAGS that are automatically set. I suspect this a problem with the #ifdef branches?
- This is a AMD barcelona CPU (see flags at the end).

```
$ gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME=getarch_2nd -DASMFNAME=getarch_2nd_ -DNAME=getarch_2nd_ -DCNAME=getarch_2nd -DCHAR_NAME=\"getarch_2nd_\" -DCHAR_CNAME=\"getarch_2nd\" -DNO_AFFINITY -I.    getarch_2nd.c   -o getarch_2nd
getarch_2nd.c:4:2: warning: #warning "before config.h" [-Wcpp]
 #warning "before config.h"
  ^
getarch_2nd.c:10:2: warning: #warning "before param.h" [-Wcpp]
 #warning "before param.h"
  ^
In file included from getarch_2nd.c:11:0:
param.h:75:2: warning: #warning "start of param.h" [-Wcpp]
 #warning "start of param.h"
  ^
getarch_2nd.c:12:2: warning: #warning "before common.h" [-Wcpp]
 #warning "before common.h"
  ^
In file included from getarch_2nd.c:13:0:
common.h:41:2: warning: #warning "start of common.h" [-Wcpp]
 #warning "start of common.h"
  ^
In file included from getarch_2nd.c:13:0:
common.h:477:2: warning: #warning "before param.h" [-Wcpp]
 #warning "before param.h"
  ^
common.h:479:2: warning: #warning "before common_param.h" [-Wcpp]
 #warning "before common_param.h"
  ^
getarch_2nd.c: In function ‘main’:
getarch_2nd.c:18:35: error: ‘SGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function)
     printf("SGEMM_UNROLL_M=%d\n", SGEMM_DEFAULT_UNROLL_M);
                                   ^
getarch_2nd.c:18:35: note: each undeclared identifier is reported only once for each function it appears in
getarch_2nd.c:19:35: error: ‘SGEMM_DEFAULT_UNROLL_N’ undeclared (first use in this function)
     printf("SGEMM_UNROLL_N=%d\n", SGEMM_DEFAULT_UNROLL_N);
                                   ^
getarch_2nd.c:20:35: error: ‘DGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function)
     printf("DGEMM_UNROLL_M=%d\n", DGEMM_DEFAULT_UNROLL_M);
                                   ^
getarch_2nd.c:21:35: error: ‘DGEMM_DEFAULT_UNROLL_N’ undeclared (first use in this function)
     printf("DGEMM_UNROLL_N=%d\n", DGEMM_DEFAULT_UNROLL_N);
                                   ^
getarch_2nd.c:25:35: error: ‘CGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function)
     printf("CGEMM_UNROLL_M=%d\n", CGEMM_DEFAULT_UNROLL_M);
                                   ^
getarch_2nd.c:26:35: error: ‘CGEMM_DEFAULT_UNROLL_N’ undeclared (first use in this function)
     printf("CGEMM_UNROLL_N=%d\n", CGEMM_DEFAULT_UNROLL_N);
                                   ^
getarch_2nd.c:27:35: error: ‘ZGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function)
     printf("ZGEMM_UNROLL_M=%d\n", ZGEMM_DEFAULT_UNROLL_M);
                                   ^
getarch_2nd.c:28:35: error: ‘ZGEMM_DEFAULT_UNROLL_N’ undeclared (first use in this function)
     printf("ZGEMM_UNROLL_N=%d\n", ZGEMM_DEFAULT_UNROLL_N);
                                   ^
getarch_2nd.c:73:50: error: ‘SGEMM_DEFAULT_Q’ undeclared (first use in this function)
     printf("#define SLOCAL_BUFFER_SIZE\t%ld\n", (SGEMM_DEFAULT_Q * SGEMM_DEFAULT_UNROLL_N * 4 * 1 *  sizeof(float)));
                                                  ^
getarch_2nd.c:74:50: error: ‘DGEMM_DEFAULT_Q’ undeclared (first use in this function)
     printf("#define DLOCAL_BUFFER_SIZE\t%ld\n", (DGEMM_DEFAULT_Q * DGEMM_DEFAULT_UNROLL_N * 2 * 1 *  sizeof(double)));
                                                  ^
getarch_2nd.c:75:50: error: ‘CGEMM_DEFAULT_Q’ undeclared (first use in this function)
     printf("#define CLOCAL_BUFFER_SIZE\t%ld\n", (CGEMM_DEFAULT_Q * CGEMM_DEFAULT_UNROLL_N * 4 * 2 *  sizeof(float)));
                                                  ^
getarch_2nd.c:76:50: error: ‘ZGEMM_DEFAULT_Q’ undeclared (first use in this function)
     printf("#define ZLOCAL_BUFFER_SIZE\t%ld\n", (ZGEMM_DEFAULT_Q * ZGEMM_DEFAULT_UNROLL_N * 2 * 2 *  sizeof(double)));
                                                  ^
getarch_2nd.c:81:64: error: ‘GEMM_MULTITHREAD_THRESHOLD’ undeclared (first use in this function)
  printf("#define GEMM_MULTITHREAD_THRESHOLD\t%ld\n", (long int)GEMM_MULTITHREAD_THRESHOLD);
                                                                ^

```

$ ./getarch 0
CORE=BARCELONA
LIBCORE=barcelona
NUM_CORES=4
HAVE_MMX=1
HAVE_SSE=1
HAVE_SSE2=1
HAVE_SSE3=1
HAVE_SSSE3=1
HAVE_SSE4_1=1
HAVE_SSE4_2=1
HAVE_SSE4A=1
HAVE_AVX=1
MAKE += -j 4
$ ./getarch 1
#define AMD_UNKNOWN
#define L1_CODE_SIZE 32768
#define L1_CODE_ASSOCIATIVE 8
#define L1_CODE_LINESIZE 64
#define L1_DATA_SIZE 32768
#define L1_DATA_ASSOCIATIVE 8
#define L1_DATA_LINESIZE 64
#define L2_SIZE 2097152
#define L2_ASSOCIATIVE 16
#define L2_LINESIZE 64
#define ITB_SIZE 4096
#define ITB_ASSOCIATIVE 0
#define ITB_ENTRIES 32
#define DTB_SIZE 4096
#define DTB_ASSOCIATIVE 0
#define DTB_DEFAULT_ENTRIES 40
#define HAVE_CMOV
#define HAVE_MMX
#define HAVE_SSE
#define HAVE_SSE2
#define HAVE_SSE3
#define HAVE_SSSE3
#define HAVE_SSE4_1
#define HAVE_SSE4_2
#define HAVE_SSE4A
#define HAVE_AVX
#define HAVE_CFLUSH
#define HAVE_MISALIGNSSE
#define HAVE_128BITFPU
#define HAVE_FASTMOVU
#define NUM_SHAREDCACHE 1
#define NUM_CORES 1
#define CORE_BARCELONA
#define CHAR_CORENAME "BARCELONA"
$ ./getarch 2
SMP=1

config.h:
# cat config.h 
#define OS_LINUX	1
#define ARCH_X86_64	1
#define C_GCC	1
#define __64BIT__	1
#define PTHREAD_CREATE_FUNC	pthread_create
#define BUNDERSCORE	_
#define NEEDBUNDERSCORE	1
#define AMD_UNKNOWN
#define L1_CODE_SIZE 32768
#define L1_CODE_ASSOCIATIVE 8
#define L1_CODE_LINESIZE 64
#define L1_DATA_SIZE 32768
#define L1_DATA_ASSOCIATIVE 8
#define L1_DATA_LINESIZE 64
#define L2_SIZE 2097152
#define L2_ASSOCIATIVE 16
#define L2_LINESIZE 64
#define ITB_SIZE 4096
#define ITB_ASSOCIATIVE 0
#define ITB_ENTRIES 32
#define DTB_SIZE 4096
#define DTB_ASSOCIATIVE 0
#define DTB_DEFAULT_ENTRIES 40
#define HAVE_CMOV
#define HAVE_MMX
#define HAVE_SSE
#define HAVE_SSE2
#define HAVE_SSE3
#define HAVE_SSSE3
#define HAVE_SSE4_1
#define HAVE_SSE4_2
#define HAVE_SSE4A
#define HAVE_AVX
#define HAVE_CFLUSH
#define HAVE_MISALIGNSSE
#define HAVE_128BITFPU
#define HAVE_FASTMOVU
#define NUM_SHAREDCACHE 1
#define NUM_CORES 1
#define CORE_BARCELONA
#define CHAR_CORENAME "BARCELONA"

I am using 0.2.19.

**Comment by JohannesBuchner** [comment]
`$ make TARGET=BARCELONA` seems to work. 
Can I help improve the auto-detection situation?

**Comment by brada4** [comment]
By first trying current deve;lopment version and if that fails attaching content of /proc/cpuinfo ?

**Comment by JohannesBuchner** [comment]
Tried, same result (bcfc298).

 $ cat /proc/cpuinfo 
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 22
model		: 48
model name	: AMD A8-6410 APU with AMD Radeon R5 Graphics
stepping	: 1
microcode	: 0x7030104
cpu MHz		: 2000.000
cache size	: 2048 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good acc_power nopl nonstop_tsc extd_apicid aperfmperf eagerfpu pni pclmulqdq monitor ssse3 cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt topoext perfctr_nb bpext ptsc perfctr_l2 cpb hw_pstate vmmcall bmi1 xsaveopt arat npt lbrv svm_lock nrip_save tsc_scale flushbyasid decodeassists pausefilter pfthreshold overflow_recov
bugs		: fxsave_leak sysret_ss_attrs null_seg
bogomips	: 3992.41
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management: ts ttp tm 100mhzsteps hwpstate cpb acc_power [13]

processor	: 1
vendor_id	: AuthenticAMD
cpu family	: 22
model		: 48
model name	: AMD A8-6410 APU with AMD Radeon R5 Graphics
stepping	: 1
microcode	: 0x7030104
cpu MHz		: 2000.000
cache size	: 2048 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 4
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good acc_power nopl nonstop_tsc extd_apicid aperfmperf eagerfpu pni pclmulqdq monitor ssse3 cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt topoext perfctr_nb bpext ptsc perfctr_l2 cpb hw_pstate vmmcall bmi1 xsaveopt arat npt lbrv svm_lock nrip_save tsc_scale flushbyasid decodeassists pausefilter pfthreshold overflow_recov
bugs		: fxsave_leak sysret_ss_attrs null_seg
bogomips	: 3991.67
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management: ts ttp tm 100mhzsteps hwpstate cpb acc_power [13]

processor	: 2
vendor_id	: AuthenticAMD
cpu family	: 22
model		: 48
model name	: AMD A8-6410 APU with AMD Radeon R5 Graphics
stepping	: 1
microcode	: 0x7030104
cpu MHz		: 2000.000
cache size	: 2048 KB
physical id	: 0
siblings	: 4
core id		: 2
cpu cores	: 4
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good acc_power nopl nonstop_tsc extd_apicid aperfmperf eagerfpu pni pclmulqdq monitor ssse3 cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt topoext perfctr_nb bpext ptsc perfctr_l2 cpb hw_pstate vmmcall bmi1 xsaveopt arat npt lbrv svm_lock nrip_save tsc_scale flushbyasid decodeassists pausefilter pfthreshold overflow_recov
bugs		: fxsave_leak sysret_ss_attrs null_seg
bogomips	: 3991.66
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management: ts ttp tm 100mhzsteps hwpstate cpb acc_power [13]

processor	: 3
vendor_id	: AuthenticAMD
cpu family	: 22
model		: 48
model name	: AMD A8-6410 APU with AMD Radeon R5 Graphics
stepping	: 1
microcode	: 0x7030104
cpu MHz		: 2000.000
cache size	: 2048 KB
physical id	: 0
siblings	: 4
core id		: 3
cpu cores	: 4
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good acc_power nopl nonstop_tsc extd_apicid aperfmperf eagerfpu pni pclmulqdq monitor ssse3 cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt topoext perfctr_nb bpext ptsc perfctr_l2 cpb hw_pstate vmmcall bmi1 xsaveopt arat npt lbrv svm_lock nrip_save tsc_scale flushbyasid decodeassists pausefilter pfthreshold overflow_recov
bugs		: fxsave_leak sysret_ss_attrs null_seg
bogomips	: 3991.68
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management: ts ttp tm 100mhzsteps hwpstate cpb acc_power [13]

**Comment by brada4** [comment]
Same result as old patch?
Please ATTACH build log. Not paste.

**Comment by JohannesBuchner** [comment]
Same result as 0.2.19 release. 
[build.txt](https://github.com/xianyi/OpenBLAS/files/889095/build.txt)

**Comment by martin-frbg** [comment]
Seems we need something like
`case 22:`
`             return CPUTYPE_BARCELONA;`
before line 1342 of cpuid_x86.c (i.e. inserted between the last "break" and the closing brace above the
return CPUTYPE_AMD_UNKNOWN) to fix detection of this system.

**Comment by JohannesBuchner** [comment]
Thanks @martin-frbg, that pushed me in the right direction. Patch is referenced above.

**Comment by martin-frbg** [comment]
Ah right, cpufamily=22 decodes to family 15 (0xf) exfamily 7. Thanks for the PR, will merge as soon as the checks complete. As far as I can tell, the corresponding runtime detection for DYNAMIC_ARCH builds in driver/others/memory.c defaults to BARCELONA already.

**Comment by JohannesBuchner** [comment]
A more informative failure output may also be worth thinking about; for instance, if something is UNKNOWN while creating config.h, warn about it. Otherwise one just sees getarch_2nd failing whenever make is invoked. At least let the user somehow know that cpu-detection is the issue.

**Comment by martin-frbg** [comment]
Normally the "make" run should terminate with the message

> Makefile:123: *** OpenBLAS: Detecting CPU failed. Please set TARGET explicitly, e.g. make TARGET=your_cpu_target. Please read README for the detail..  Stop.

already, not sure yet why it did not do this in your case (perhaps the special case of AMD_UNKNOWN lets it proceed to a different point than it would for Intel or non-x86 architectures that have no such fallback).
