### ISSUE TITLE
Could not install package 'OpenBLAS 0.2.14' nuget

### ISSUE THREAD

**Issue by Zerseu** [xianyi/OpenBLAS#1143]
Could not install package 'OpenBLAS 0.2.14'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly 
references or content files that are compatible with that framework.

Using Microsoft Visual Studio 2015 targeting .NET Framework 4.6.

**Comment by martin-frbg** [comment]
Did you try asking the NuGet folks already ? Offhand this sounds like a packaging issue with their build, besides 0.2.14 is two years old.

**Comment by brada4** [comment]
Only way to report NuGet problems is to try to contact package owner, asking to replace his upstream link (here) with a place where he stashes his vcproj files.
If you mean this package https://www.nuget.org/packages/OpenBLAS/0.2.14 - this release pre-dates .net 4.6, thus no chance it will work for you (aka packaging problem that @martin-frbg mentioned)

**Comment by martin-frbg** [comment]
FYI, there appears to be a newer package repository on nuget under the name "OpenBLASLibs" that has a 0.2.19 at https://www.nuget.org/packages/OpenBLASLibs/0.2.19.2
