### ISSUE TITLE
OpenBLAS performance

### ISSUE THREAD

**Issue by AlexanderPaniutin** [xianyi/OpenBLAS#1150]
Hello everyone.
First of all, thanks for supporting this library and I really appreciate you put an extra time that you couldve spend with your family or just watching a TV. :)

I am trying to optimize a naive method of multiplying matrix to vector which takes ~ 48% CPU time

1. I tried ATLAS and it was blazingly fast with ~2% CPU. But I have problems compiling it for ARM7
2. Tried OpenBLAS and it did compile for ARMV7 (didnt run yet) but before I watnetd to check how fast its gonna be on MAC.
3. So when I run it for a first time, it created 3 threads that took 30% CPU each (its 90% total) and left me only less than 10% :(
4. When I disabled threading, CPU time was still ~ 68%. Any idea why or what I am doing wrong?

Original Naive method
<img width="508" alt="screen shot 2017-04-11 at 12 30 06 pm" src="https://cloud.githubusercontent.com/assets/14287789/24927117/b415ffae-1eb2-11e7-8d69-07a08bac2de1.png">

OpenBLAS default
`make`
<img width="435" alt="screen shot 2017-04-11 at 12 23 25 pm" src="https://cloud.githubusercontent.com/assets/14287789/24926879/ef5219a0-1eb1-11e7-9921-aa4423d99b77.png">
<img width="594" alt="screen shot 2017-04-11 at 12 23 57 pm" src="https://cloud.githubusercontent.com/assets/14287789/24926890/f7288f1a-1eb1-11e7-9901-7c7ba635f63b.png">

OpenBLAS no threads
`make USE_THREAD=0`
<img width="572" alt="screen shot 2017-04-11 at 12 10 48 pm" src="https://cloud.githubusercontent.com/assets/14287789/24926396/421279c0-1eb0-11e7-9262-99062d082658.png">

My mac has 2.4 GHz Intel Core i7 and OS 10.12.3

I hope I am doing something wrong but Why 3 threads take 90% CPU? 
OR why the single thread version takes longer than the naive original?
Any ideas anyone?

**Comment by brada4** [comment]
in one picture it almost adds to 100% in other not really. Probably your profiler documentation can help you get along with pictures.

**Comment by AlexanderPaniutin** [comment]
@brada4 I sliced screenshots from "Instruments". the app takes 100% all the time which is expected (due to internal infinite loop of data processing) but I was hoping BLAS can help to reduce the load.
I found that kernel has 2 versions. the one with 4*4 implementation and rolled out the inputs and other use asm injections. I guess somehow the optimized version did not get picked out.

**Comment by brada4** [comment]
Are you fending off app nap (and in case of laptop - that your power adapter is connected and a good battery is fully charged)

For naive implementation - sgemv does **y := alpha*A*x + beta*y** , it is pretty easy to optimize out scaling (alpha/beta) and do less in your own implementation.

You can actually build multi-threaded OpenBLAS and disable threading by setting environment OPENBLAS_NUM_THREADS/OMP_NUM_THREADS to 1

What are arguments to cblas_sgemv? (Sizes and transforms matter, sgemv processing time does not depend on matrix content)

What processor you have? There are at least three 2.4GHz i7 shipped by apple at different times.

Can you measure timings (total wall time spent) in (multiple invocations of) cblas_sgemv with one thread and with all threads and with half of threads in case you have hyperthreading.

So far it looks that your profiler mis-accounts idle worker threads towards impressive percent.

Apple has own BLAS implementation called Accelerate Framework included in any OSX, it might be of value to have its timings as a comparison too.

**Comment by brada4** [comment]
Kernel choice is made measuring their behavior on real hardware, it is not a wild guess.
it can be naive - with one temp variable, or for all sorts of SIMD support in compilers - with 2..4..8..16, or assembly.
On top of that comes fortran interface (sgemv_ in interface/gemv.c) written in C which chooses to parallelize or not. 
Above that comes cblas_sgemv which does short checks on arguments, then swaps arguments, transforms inputs, copies them as needed or calls xerbla in case arguments are not viable.

**Comment by AlexanderPaniutin** [comment]
@brada4 Appreciate your answers.
I will try to use OPENBLAS_NUM_THREADS/OMP_NUM_THREADS = 1
I multiply matrix 256x256 256x1. no alpha no betta.

Yesterday I compiled for NEHALEM and SANDYBRIDGE but didnt see much of a difference in performance. I have no idea what is my processor is. Will check it in a bit.

Also I did check a few files and cgemv_n_microk_bulldozer-4.c seems like what I need to run: a vectorized version.
I guess we can stop calling this thread an issue. Seems like its a normal behavior of a library.

**Comment by brada4** [comment]
Timings before overly general maybes and guesses?
At the end of build you see current CPU.
Could you build with DYNAMIC_ARCH=1 and let OpenBLAS select optimal kernels at runtime?

**Comment by AlexanderPaniutin** [comment]
Thanks. Will give a try (hopefully tonight)

**Comment by AlexanderPaniutin** [comment]
Forgot to update. 
Tried with DYNAMIC_ARCH=1 and with DYNAMIC_ARCH=1 OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1. Both versions gave about same results (like naive method). I guess this is expected. Thanks for help @brada4.

Thread/issue can be closed.

**Comment by brada4** [comment]
DYNAMIC_ARCH is build variable (which saves you guessing the right CPU type)
*_NUM_THREADS are environment variables to override automatic CPU detection.

**Comment by AlexanderPaniutin** [comment]
Sorry, my bad. will give a try with those env vars too :)

**Comment by brada4** [comment]
Try DYNAMIC_ARCH=1 build
Then run the sample with OPENBLAS_NUM_THREADS=1 vs2 vs 4
If 2 is slower than 1 it is a performance regression
If 4 is slower than 2 it is just an observation regarding hyperthreading
