### ISSUE TITLE
cblas_xerbla not provided

### ISSUE THREAD

**Issue by brada4** [xianyi/OpenBLAS#1151]
In absence of fortran compiler (like `make FC=nothing`) resulting library includes fortran API, but cblas api misses cblas_xerbla. It should be there.

**Comment by martin-frbg** [comment]
Not sure if lacking FC is the key to this, offhand it looks more like cblas_xerbla unconditionally not being exported through gensymbol. (Looking at the history of that file, this seems to have been the case for several years at least.)

**Comment by brada4** [comment]
It is not urgent, just my probably misguided attempt at ./configure script...

**Comment by martin-frbg** [comment]
The longer explanation appears to be that all CBLAS routines are taken from "our" own implementations in interface/ instead of the lapack-netlib/SRC/CBLAS tree. Contrary to netlib these call BLASFUNC(xerbla) directly when necessary instead of going through a separate cblas_xerbla wrapper. So the question seems to be whether OpenBLAS should be expected to provide a cblas_xerbla() interface for API compatibility or if no user program is expected to ever call this function.

**Comment by martin-frbg** [comment]
I have taken the liberty to change the issue title (after confirming that FC or not has no bearing)

**Comment by brada4** [comment]
I am pretty sure somebody used it before (though it is pretty useless API to call), https://packages.debian.org/source/jessie/openblas -> unpack source -> shared-blas-lapack.patch 
There it adds few missing exports to resulting library.
[shared-blas-lapack.patch.txt](https://github.com/xianyi/OpenBLAS/files/920301/shared-blas-lapack.patch.txt)

**Comment by martin-frbg** [comment]
That tells us only that somebody noticed the lack of a cblas_xerbla while trying to split OpenBLAS into separate blas and lapack parts, not that anyone actually wanted to call cblas_xerbla from their code. The usual case rather appears to be people wanting to override (cblas_)xerbla with their own, less cryptic version of an error handler. Nevertheless at least netlib, atlas, mkl appear to provide actual implementations while OpenBLAS (and libGoto2 before it) only has the prototype in cblas.h so it could be called a lack in compatibility.

**Comment by brada4** [comment]
I dont need it (past 'good to know'), just that I found small inconsistency, changed my test to 1*1 via cblas_dgemm, reflecting actual usage, and problem went away.

**Comment by brada4** [comment]
Looks sufficient, thanks.
