### ISSUE TITLE
AMD Steamroller is not correctly detected

### ISSUE THREAD

**Issue by gcp** [xianyi/OpenBLAS#1159]
Public release fail runtime detection and uses Prescott kernels. Overriding via the enviroment var works. Compiling current git fails with

Makefile:123: *** OpenBLAS: Detecting CPU failed. Please set TARGET explicitly, e.g. make TARGET=your_cpu_target. Please read README for the detail..  Stop.

processor       : 3
vendor_id       : AuthenticAMD
cpu family      : 21
model           : 56
model name      : AMD A10-7860K Radeon R7, 12 Compute Cores 4C+8G
stepping        : 1
microcode       : 0x6003106
cpu MHz         : 1400.000
cache size      : 2048 KB
physical id     : 0
siblings        : 4
core id         : 3
cpu cores       : 2
apicid          : 19
initial apicid  : 3
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt lwp fma4 tce nodeid_msr tbm topoext perfctr_core perfctr_nb bpext ptsc cpb hw_pstate vmmcall fsgsbase bmi1 xsaveopt arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold overflow_recov
bugs            : fxsave_leak sysret_ss_attrs null_seg
bogomips        : 7186.56
TLB size        : 1536 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management: ts ttp tm 100mhzsteps hwpstate cpb eff_freq_ro [13]

**Comment by martin-frbg** [comment]
Somewhat related to #945 which also still needs the cpuid detection fix but to me AMDs naming scheme seems even more confusing than Intel's.

**Comment by martin-frbg** [comment]
Thanks for the patch. I wonder if there would be any drawback to making cpuid_x86.c write the (extended) family and model numbers of an unknown cpu to stderr so that running "getarch 1"  would provide a quick way of obtaining them in the form required for the switch cascade in get_cpuname()...
It also seems to me that Carrizo (family 15h model 60h) should be supported since 0.2.15 so perhaps #945 should be closed as well (assuming that user was trying to build an even older version back then).
