### ISSUE TITLE
can't compile on VS2015 

### ISSUE THREAD

**Issue by wguo68** [xianyi/OpenBLAS#1161]
'perl' 不是内部或外部命令，也不是可运行的程序

**Comment by brada4** [comment]
You need to install PERL (like strawberry perl).
Also Visual Studio build will not include optimized assembly, you will get better performing DLL from MSYS2 build or cross-build on Linux.

**Comment by wguo68** [comment]
Thank you. I will try.

**Comment by martin-frbg** [comment]
Closing this as you opened #1162 for the problem with cblas_mangling.h
