### ISSUE TITLE
 fatal error C1083: Cannot open include file: 'cblas_mangling.h': No such file or directory

### ISSUE THREAD

**Issue by wguo68** [xianyi/OpenBLAS#1162]
I didn't find this header file in openblas include dir.

**Comment by wguo68** [comment]
I commented this line ,then okay.
//#include "cblas_mangling.h"

**Comment by martin-frbg** [comment]
Which version are you building ? I believe this problem of the 0.2.19 release should be fixed in the current "develop" branch already (something to do with import of the netlib lapack 3.7.0 release without noticing that a filename was changed compared to 3.6.x)

**Comment by brada4** [comment]
When you go to 'code' tab of this github project you can download .zip file with current develop version.

**Comment by martin-frbg** [comment]
Actually I am no longer sure if there was a fix for this as such - while cblas_mangling.h (or actually a precursor for it) is included in the netlib CBLAS, it should not be installed or required as the build system of OpenBLAS creates its own cblas.h that does not use it. If you encounter this error (while compiling what ?), it could be that the compiler picked up a different copy of cblas.h installed somewhere else on your system.

**Comment by martin-frbg** [comment]
@wguo68, did you have the problematic "#include cblas_mangling.h" in your own code, or where ? I believe this is internal to the netlib version (their cblas.h includes it, but for instance it is not present in the ATLAS blas either) and should not appear in user code. If you found that include in a cblas.h somewhere on your system, it cannot have been the cblas.h that is installed by OpenBLAS
