### ISSUE TITLE
Openblas execution does not support more than 2 threads

### ISSUE THREAD

**Issue by akashsridhar** [xianyi/OpenBLAS#1170]
Hi,

I am running openblas(single threaded and multi-threaded). I am building openblas on Arch Linux with a target to mips64 architecture (I6400 target).

The benchmarks executes perfectly for single-thread version and two-thread version. But, when I build the benchmarks for four-threads, the benchmarks only run on two threads (not using the remaining two threads). This is the build command I use for 4 threads,

make BINARY=64 BINARY64=1 CC=mips-img-linux-gnu-gcc AR=mips-img-linux-gnu-ar RANLIB=mips-img-linux-gnu-ranlib HOSTCC=gcc CFLAGS="-EL" FFLAGS=$CFLAGS LDFLAGS=$CFLAGS TARGET=I6400 NUM_THREADS=4

And the build is successful.

make[1]: Leaving directory '~/build/release/run/OpenBLAS-0.2.19/exports'

 OpenBLAS build complete. (BLAS CBLAS)

  OS               ... Linux             
  Architecture     ... mips64               
  BINARY           ... 64bit                 
  C compiler       ... GCC  (command line : mips-img-linux-gnu-gcc)
  Library Name     ... libopenblas_i6400p-r0.2.19.a (Multi threaded; Max num-threads is 4)

I compile the benchmark/gemm.c using the following command,

mips-img-linux-gnu-gcc -EL -fno-PIC -mabi=64 -mips64r6 -g -static -fno-stack-protector -Ofast -mno-check-zero-division -funroll-loops -fno-inline  -msym32  -mcompact-branches=always -T../msym32.ld -DDOUBLE=0 -o gemm.mips64 gemm.c ../libopenblas_i6400p-r0.2.19.a -lpthread

It would be great if I can get some help with this.

Thanks

**Comment by brada4** [comment]
how do you measure that it uses two threads?

**Comment by akashsridhar** [comment]
I build the openblas package with NUM_THREADS=2.

I build the benchmark again and run the benchmark executable on ESESC simulator with dual core configuration.

I repeat the same process for NUM_THREADS=4 on a quad core simulation setup. But, the simulator uses only two out of the four threads.

I had no issues when running NUM_THREADS=2 and USE_THREAD=0 (single threaded version) of openblas on the simulator

**Comment by brada4** [comment]
Simulators hardly reflect real hardware that openblas is tuned for. You may find that simpler ISAs run much faster than ones with enormous register files compared to host.

**Comment by martin-frbg** [comment]
Could also be that the default matrix size in the benchmark is too small to warrant creation of additional threads - I think some optimizations in this regard were made sometime last summer.

**Comment by brada4** [comment]
It could be one thread in emulator that emulates 256 cpu cores and other that runs IO polling.

**Comment by brada4** [comment]
You need to check esesc report for cpu usage. 
OS threads say nothing at all about how simulated CPU worked.
Only chance to get it virtualising and using CPU core for virtual CPU is to run ARM on ARM.
