### ISSUE TITLE
how can i build a static dll ?

### ISSUE THREAD

**Issue by baiheshu** [xianyi/OpenBLAS#1172]
how can i build a static dll ? 
ineed to build  libgcc_s_dw2-1.dll, libgfortran-3.dll and libquadmath-0.dll into the  libopenblas.dll with the gcc static compiler? 
i use the command:
make BINARY=32 DYNAMIC_ARCH=1

where to add the -static option?

**Comment by martin-frbg** [comment]
Try providing your own CFLAGS, something like 
`make CFLAGS='-O2 -static -static-libgcc'`

**Comment by brada4** [comment]
dll is meant to be dynamic, first letter says it.
You can skip fortran library dependency by not building lapack or hiding gfortran compiler.

**Comment by baiheshu** [comment]
thanks

**Comment by brada4** [comment]
Can you close the issue?
