### ISSUE TITLE
Compilation failure on AArch64 with DYNAMIC_ARCH=1

### ISSUE THREAD

**Issue by staticfloat** [xianyi/OpenBLAS#1174]
I've been testing compiling OpenBLAS on multiple architectures using the new GCC 7.1.0 release, and it looks like something has changed on AArch64.  Compilation of [this line](https://github.com/xianyi/OpenBLAS/blob/5ee1cf02230ce7365a13fa021b0f98a4eeb9ff17/driver/others/dynamic.c#L100-L101) now fails with the following error message:

```
gcc -march=armv8-a -O2 -DMAX_STACK_ALLOC=2048 -Wall -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=8 -march=armv8-a+crc+crypto+fp+simd -mtune=cortex-a57 -DASMNAME=dynamic -DASMFNAME=dynamic_ -DNAME=dynamic_ -DCNAME=dynamic -DCHAR_NAME=\"dynamic_\" -DCHAR_CNAME=\"dynamic\" -DNO_AFFINITY -I../.. -c dynamic.c -o dynamic.o
dynamic.c: In function 'support_avx':
dynamic.c:110:3: warning: implicit declaration of function 'cpuid' [-Wimplicit-function-declaration]
   cpuid(1, &eax, &ebx, &ecx, &edx);
   ^~~~~
dynamic.c:100:3: error: impossible constraint in 'asm'
   __asm__ __volatile__
   ^~~~~~~
Makefile:83: recipe for target 'dynamic.o' failed
```

**Comment by martin-frbg** [comment]
Probably a silly question from me (again), but does this target support AVX ? Both the inline assembly and the call to cpuid() are in `#ifndef NO_AVX` blocks - perhaps something in the cpu detection code changed (or shows changed behaviour when compiled with gcc7) ?

**Comment by ashwinyes** [comment]
@staticfloat Please let me know the command that you used to build.

**Comment by brada4** [comment]
dynamic.c is not compiled on aarch64. Maybe you are using x86 compiler on x86 platform?

**Comment by staticfloat** [comment]
> Please let me know the command that you used to build.

I am building this within the `julia` source tree, but the eventual `make` invocation to OpenBLAS is:
```
make CC="gcc -march=armv8-a" FC="gfortran -march=armv8-a" RANLIB=ranlib FFLAGS="-O2 -fPIC" TARGET= BINARY= USE_THREAD=1 GEMM_MULTITHREADING_THRESHOLD=50 NUM_THREADS=8 NO_AFFINITY=1 DYNAMIC_ARCH=1 MAKE_NB_JOBS=0
```

> dynamic.c is not compiled on aarch64. Maybe you are using x86 compiler on x86 platform?

Definitely not.  This is running on an `AArch64` box, with a GCC 7.1.0 freshly compiled.  Running `gcc -dumpmachine` gives `aarch64-unknown-linux-gnu`.

It actually looks like this is due to us setting `DYNAMIC_ARCH=1` on an AArch64 system.  Is that not allowed?

**Comment by staticfloat** [comment]
I just confirmed that compiling with GCC 6.3.0 has the same error, so this isn't anything new with GCC 7.

**Comment by brada4** [comment]
It should have no effect ideally, dynamic.c has only x86 codes so far.

**Comment by martin-frbg** [comment]
Not sure if this is actually documented anywhere, but looking in Makefile.system the list of supported cpu cores for DYNAMIC_ARCH=1 is definitely x86-only. (Actually DYNAMIC_ARCH is supposed to be unset
there automatically if the list of DYNAMIC_CORES is empty, perhaps this does not work as expected ?)

**Comment by staticfloat** [comment]
Thanks for the tip @martin-frbg, I've opened a PR that works on my machine: https://github.com/xianyi/OpenBLAS/pull/1176

**Comment by martin-frbg** [comment]
Thanks for the PR - neat trick to print the settings, but did you check that setting DYNAMIC_ARCH to zero is safe (i.e. that there is no place that has `ifndef DYNAMIC_ARCH`) ?

**Comment by staticfloat** [comment]
No, all I did was compile it to make sure it gets all the way through.

```
$ grep -E 'ifn?def' -R . | grep DYNAMIC_ARCH
./common_q.h:#ifndef DYNAMIC_ARCH
./common_param.h:#ifdef DYNAMIC_ARCH
./Makefile:#ifdef DYNAMIC_ARCH
./common_c.h:#ifndef DYNAMIC_ARCH
./common_d.h:#ifndef DYNAMIC_ARCH
./kernel/Makefile:#ifdef DYNAMIC_ARCH
./driver/others/openblas_get_config.c:#ifdef DYNAMIC_ARCH
./driver/others/openblas_get_config.c:#ifndef DYNAMIC_ARCH
./driver/others/openblas_get_config.c:#ifdef DYNAMIC_ARCH
./driver/others/openblas_get_config.c:#ifndef DYNAMIC_ARCH
./driver/others/openblas_get_config.c:#ifndef DYNAMIC_ARCH
./driver/others/memory.c:#ifdef DYNAMIC_ARCH
./driver/others/memory.c:#ifdef DYNAMIC_ARCH
./driver/others/memory.c:#ifndef DYNAMIC_ARCH
./driver/others/memory.c:#ifdef DYNAMIC_ARCH
./driver/others/memory.c:#ifdef DYNAMIC_ARCH
./driver/others/memory.c:#ifdef DYNAMIC_ARCH
./common_x.h:#ifndef DYNAMIC_ARCH
./common_z.h:#ifndef DYNAMIC_ARCH
./common_s.h:#ifndef DYNAMIC_ARCH
```

Looks like there's quite a few instances of that within C code, but within the Makefiles they're all commented out.  (I had to do a few double-takes to realize that `#ifdef DYNAMIC_ARCH` in a Makefile doesn't actually do anything)

**Comment by staticfloat** [comment]
I verified that using `override DYNAMIC_ARCH=` works as well, so I changed it to do that instead.
