### ISSUE TITLE
fatal error: stdio.h: No such file or directory , compile error stm32f4 on RIOT

### ISSUE THREAD

**Issue by tuanle311** [xianyi/OpenBLAS#1177]
I got this issue when i compile hello world for board stm32f4 discovery, RIOT

tuanle@TuanLe ~/RIOT/examples/hello-world $ BOARD=stm32f4discovery make
Building application "hello-world" for "stm32f4discovery" with MCU "stm32f4".

/home/tuanle/RIOT/examples/hello-world/main.c:23:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminate d.
/home/tuanle/RIOT/Makefile.base:64: recipe for target '/home/tuanle/RIOT/examples/hello-world/bin/stm32f4discovery/hello-world/main.o' failed
make[1]: *** [/home/tuanle/RIOT/examples/hello-world/bin/stm32f4discovery/hello-world/main.o] Error 1
/home/tuanle/RIOT/examples/hello-world/../../Makefile.include:277: recipe for target 'all' failed
make: *** [all] Error 2

Can you help me for this issue , thank you very much

**Comment by ashwinyes** [comment]
This doesn't look like anything related to OpenBLAS unless I am mistaken.

You may have posted in the wrong forum.

**Comment by martin-frbg** [comment]
This appears to be an issue with your compiler, libc or operating system installation - stdio.h is a fairly fundamental file for compiling things and not in any way specific to OpenBLAS. Please ask the RIOT-OS folks.
