### ISSUE TITLE
make failed--computer crashes

### ISSUE THREAD

**Issue by ahndroo** [xianyi/OpenBLAS#1180]
I'm dont think this is related to the source itself, but everytime I run `make FC=gfortran` on my computer, it crashes.  CPU is AMD FX8350.  There was one time when it finished, but had errors in it...but I didn't get to catch the errors it showed.  Now when I run it, the CPU load jumps to 100% and the desktop crashes.  Any suggestions of what might be going wrong?

**Comment by martin-frbg** [comment]
Disk full, defective memory or insufficient cooling perhaps - if you can exclude these, try reinstalling your gfortran in case one of its files got damaged on disk.

**Comment by brada4** [comment]
100% CPU sounds windows. It usually drops something in event log regarding thermal throttling before such meltdown.

**Comment by martin-frbg** [comment]
Any updates ? I'm not sure there is anything we can change in OpenBLAS or its Makefiles to improve the health of your computer...

**Comment by ahndroo** [comment]
Sorry about that! I watched the CPU temps while running and they spiked up to about 75C before the desktop crashed. Got a new giant cooler for the CPU and it installed no problem.
