### ISSUE TITLE
openblas compilation errors 

### ISSUE THREAD

**Issue by svaksha** [xianyi/OpenBLAS#1183]
Hi, 
While installing Julia on Ubuntu 17.04, i ran into some compilation errors: https://github.com/JuliaLang/julia/issues/13842#issuecomment-295333554
Tried to overcome it by not using the system openblas but installing from source failed too: https://gist.github.com/svaksha/037cb9776737d103383b9fa742d2a25a

**Comment by martin-frbg** [comment]
Seems you had a spelling error (missing "n") in your first attempt:
> make FC=gfortra
>OpenBLAS: Detecting fortran compiler failed. Cannot compile LAPACK. Only compile BLAS.

and you did not do "make clean" before the second attempt (with `make TARGET=NEHALEM`) which may have led to a mixed build with some parts of the code expecting lapack functions to be present.
What is your CPU ? I would expect anything from two years ago (when that julia issue was new) to be detected correctly by a recent OpenBLAS so a TARGET option should not be necessary.

**Comment by brada4** [comment]
You can plant very fresh OpenBLAS as system libblas.so.3 at disposal of julia, numpy and friends:
https://github.com/xianyi/OpenBLAS/wiki/Faq#debianlts
Or do nothing as long as both products are recent from distribution (they know their ways with compilers better)

**Comment by svaksha** [comment]
Thanks Martin and Andrew. I will try these and report.
Aside, right after filing this bug, I cloned a fresh dev-version of julia
and compiled it - voila, no openblas errors. This strange behaviour
perplexed me. Any idea what is going on?

SVAKSHA ॥  http://about.me/svaksha  ॥

**Comment by martin-frbg** [comment]
That would seem to fit my speculation that the build system should be able to figure out the CPU type (and the fortran compiler) automatically. If OpenBLAS is built as part of the Julia installation, either someone had the foresight to issue a `make clean` at the start of the build process "just in case", or the checkout also fetched a fresh copy of OpenBLAS, oblitterating any broken bits that may have been left over from your previous attempt.

**Comment by svaksha** [comment]
On Wed, May 17, 2017 at 1:55 PM, Martin Kroeker <notifications@github.com>
wrote:

> That would seem to fit my speculation that the build system should be able
> to figure out the CPU type (and the fortran compiler) automatically. If
> OpenBLAS is built as part of the Julia installation, either someone had the
> foresight to issue a make clean at the start of the build process "just
> in case", or the checkout also fetched a fresh copy of OpenBLAS,
> oblitterating any broken bits that may have been left over from your
> previous attempt.
>
​
well, when ever the julia src build fails for openblas I do a combination
of the following and build it for the NEHALEM arch till the openblas error
goes away.

make clean
make distclean
make -C deps clean-uv
make -C deps distclean
git clean -fdx
make -C deps distclean-libgit2 && make

​that day, none of these worked so ​i got rid of the system openblas and
tried to compile from source.

SVAKSHA ॥  http://about.me/svaksha  ॥
​

**Comment by martin-frbg** [comment]
The i7-7600U (as you mentioned in the julia issue comment) should be recognized by the current git "develop" source tree, though not yet by the 0.2.19 release. (HASWELL target should be more appropriate for that cpu rather than the much older and less advanced NEHALEM, unless you intend to use the same library build on older machines as well). Not sure about the earlier issues but glad that they appear to have gone away :-)

**Comment by brada4** [comment]
You can export OPENBLAS_CORETYPE=Haswell with ububtu-supplied OpenBLAS or supplant it with develop OpenBLAS. Either will be significantly quicker than old cpu architecture builds.

**Comment by martin-frbg** [comment]
@svaksha was this sufficient to solve your problem(s), or would you like further assistance ?

**Comment by svaksha** [comment]
@brada4, thanks. " make OPENBLAS_TARGET_ARCH=HASWELL" fixed the build failures. (<-- for folks having similar issues).
@martin-frbg, solved now, thanks!
