### ISSUE TITLE
CMake config.h

### ISSUE THREAD

**Issue by diorcety** [xianyi/OpenBLAS#1184]
With cmake, the headers are put in prefix/include directory. Aside polution from all openblas files, there is config.h file at prefix/include/config.h. Which can trigger major issues with other compilations

**Comment by martin-frbg** [comment]
Indeed the brute force GLOB_RECURSE in the toplevel CMakeLists.txt does look seriously wrong - only a very small number of headers should actually get installed, with the config.h only used as input for building openblas_config.h

**Comment by martin-frbg** [comment]
This is what I have come up with so far - the unresolved part is adding the contents of the openblas_config_template.h and the final "endif" to openblas_config.h . (Redirection and concatenation does not appear to work with cmake like it does with plain Makefiles, and my awk is a bit rusty)
[CMakeLists.txt](https://github.com/xianyi/OpenBLAS/files/1018039/CMakeLists.txt)

**Comment by martin-frbg** [comment]
Not sure what to make of the error message from the Appveyor build on Windows -  _'NF' is not recognized as an internal or external command,  operable program or batch file._ Or is it simply not finding the `awk` program itself ?

**Comment by martin-frbg** [comment]
Meh. Need help finding the right awk idiom for whatever Windows flavour of awk is used in the Appveyor environment.

**Comment by martin-frbg** [comment]
Seems to work now after replacing the lengthy awk command for building openblas_config.h with a quick-and-dirty utility written in C. I simply could not come up with the right combination of quotes and escape characters to make the same awk call work on both Linux and Windows. Now I am sure there must be lots of ways to do this better - for one I do not get why I need to query LOCATION of the newly built tool to get cmake to realize it needs to use the .exe name on Windows.
