### ISSUE TITLE
Is there any document about the functions in the cblas.h?

### ISSUE THREAD

**Issue by ray3572** [xianyi/OpenBLAS#1185]
I need a matrix dot product function and a function to get a sum of elements in the same col, but I can't find those functions···please help me···
我需要一个矩阵点乘以及一个求矩阵每行所有元素和的函数，然而并没有找到他们，向大家求助，感激不尽

**Comment by martin-frbg** [comment]
OpenBLAS is for the most part "just" an optimized implementation of the standard BLAS library, so the
official documentation for that one at http://netlib.org/blas/index.html still applies. CBLAS on the other hand is just an interface that allows calling these FORTRAN functions from C with its different conventions for argument passing and array ordering.

**Comment by brada4** [comment]
Level 1 BLAS _dot function takes incx parameter and can make sums you need from a matrix, or you transfrom matrix and do same with incx=1, you need to measure which is faster. It is mostly memory -bound, which means parallelisation will not have big impact.

**Comment by ray3572** [comment]
thanks  a lot !
