### ISSUE TITLE
OpenMP creates more threads than expectation

### ISSUE THREAD

**Issue by shenck0** [xianyi/OpenBLAS#1194]
Hi! I'm using OpenBLAS in my application, and it works well until I started using OpenMP. After I add OpenMP calls, program will create threads more than OMP_NUM_THREADS variable indicated. My code looks like:
```
// CPU have 4 physical cores with hyper-threading enabled
putenv("OMP_NUM_THREADS=4");
cblas_sgemm(....); // some OpenBLAS function calls
#pragma omp parallel for // OpenMP calls
for (....){
  // other code without OpenBLAS
}

```
Without OpenMP calls, program have 4 threads as I expected.
With OpenMP calls, program have 11 (=1+(4-1)+(8-1)) threads which cause obvious drop of performance.
By the way, OpenBLAS dynamic library is built with USE_OPENMP=1 on Windows using MinGW.

**Comment by brada4** [comment]
That variable is read once in DLL init section. There is no effect of any threading contols later.

**Comment by shenck0** [comment]
@brada4 
Thanks for your reply. 
I will use num_threads clause in #pragma omp.

**Comment by brada4** [comment]
See #1192 too. I think it is same limitation.
Pragma in your code will have no effect whatsoever on openblas thread pool initialized long ago.
Probably you need to https://github.com/xianyi/OpenBLAS/wiki/OpenBLAS-Extensions openblas_set_num_threads(omp_get_num_threads()) between/before blas calls later
