### ISSUE TITLE
running time too long in ARMV7

### ISSUE THREAD

**Issue by yhx123456** [xianyi/OpenBLAS#1201]
The issue is that the running time of matrix multiplication(cblas_sgemm()) is too long in ARMV7.
Details:
Cross complie: make TARGET=ARMV7 HOSTCC=gcc USE_MASS=1 CC=arm-openwrt-linux-gcc NOFORTRAN=1 NO_SHARED=1  
  OpenBLAS build complete. (BLAS CBLAS)
  OS               ... Linux             
  Architecture     ... arm               
  BINARY           ... 32bit                 
  C compiler       ... GCC  (command line : arm-openwrt-linux-gcc)
  Library Name     ... libopenblas_armv7p-r0.2.20.dev.a (Multi threaded; Max num-threads is 24)

Install:  make PREFIX=/home/yanghongxiao/openblas/ install NO_SHARED=1

  Generating openblas_config.h in /home/yanghongxiao/openblas//include
  Generating f77blas.h in /home/yanghongxiao/openblas//include
  Generating cblas.h in /home/yanghongxiao/openblas//include
  Copying LAPACKE header files to /home/yanghongxiao/openblas//include
  Copying the static library to /home/yanghongxiao/openblas//lib
  Generating openblas.pc in /home/yanghongxiao/openblas//lib/pkgconfig
  Generating OpenBLASConfig.cmake in /home/yanghongxiao/openblas//lib/cmake/openblas
  Generating OpenBLASConfigVersion.cmake in /home/yanghongxiao/openblas//lib/cmake/openblas
  Install OK!

arm-openwrt-linux-gcc -o test matrix/test.c -I openblas/include/  openblas/lib/libopenblas_armv7p-r0.2.20.dev.a -lpthread
The running time: 440x512x512     2.272080 s      101.531075 MFLOPS
                            440x256x256     0.585930 s      98.427589 MFLOPS
                            440x512x512     2.273612 s      101.462654 MFLOPS
                            440x512x512     2.351710 s      98.093178 MFLOPS
                            440x512x512     2.345992 s      98.332268 MFLOPS
                            512x512x521     2.738963 s      99.729012 MFLOPS
I wonder where I went wrong.

**Comment by martin-frbg** [comment]
Please try limiting the number of threads. What kind of hardware is this, could it be another case of a big.little cpu combination where half of the cores (or more) are much slower than the others ?

**Comment by yhx123456** [comment]
Hello, I tried many times. The number of threads is 1 and the cpu is ARM R8. But the run time is always so long.  I think it's too slow, so I wonder whether the complied parameter is right?

**Comment by brada4** [comment]
For a single thread you should probably set NUM_THREADS=1 to remove all threading code (It actually defaults to CPUs found on build machine, not target)
It is realtime CPU, can you run something like perf record/perf report to ensure realtime clock interrupts do not steal too much time? If input is graphics then best optimisation would be to halve resolution until time is satisfactory and no detail lost.

**Comment by ctgushiwei** [comment]
@yhx123456  canyou share the version of the openblas you compile?the develop version or armv7 version or arm_soft_fp_abi? my test code can not work normal

**Comment by yhx123456** [comment]
@ctgushiwei  https://github.com/xianyi/OpenBLAS.git . I haven't made any changes.

**Comment by ctgushiwei** [comment]
@yhx123456  you mean you use the develop version

**Comment by yhx123456** [comment]
Yeap,Is there any problem with this version?

**Comment by yhx123456** [comment]
@ctgushiwei  Yeap，Is there any problem with this version?

**Comment by ctgushiwei** [comment]
I have another question?Is assembly language can compile sucessfully on ARMV7 target?

**Comment by ctgushiwei** [comment]
@yhx123456   I can compiled 0.2.19 release version successfully ,but when i test cblas_sgemm,i go to segmentation error. i have known the reason,the code at openblas_0.2.19/kernel/ can not compile to .o file,i do not know how to solve this problem

**Comment by ibaldonl** [comment]
This is from 2017 and I think there was some confusion about how to compile and set the correct number of threads.
So it seems this issue should be closed now, thanks.
