### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by boyce-xx** [xianyi/OpenBLAS#1202]
Hi, I got an error when building this with cross-compiler. please help:

> #! /usr/bin/env bash
> 
> cd OpenBLAS-develop
> 
> export PATH=/home/king/opt/gcc-linaro-6.3.1-2017.02-x86_64_arm-linux-gnueabi/bin:$PATH
> 
> make TARGET=ARMV7 HOSTCC=gcc BINARY=64 CC=arm-linux-gnueabi-gcc FC=arm-linux-gnueabi-gfortran 
> #make PREFIX=/home/king/Project/DB20_Linux/AVS/Alexa_Make/AvsEnv install

My target platform is:

> / # uname -a
> Linux apq8009 3.18.44 #1 SMP PREEMPT Fri Jun 2 09:11:05 CST 2017 armv7l GNU/Linux

Thank you!.

**Comment by martin-frbg** [comment]
Mind telling us what error you got ?

**Comment by boyce-xx** [comment]
@martin-frbg Sorry, this is the error message:

> make[1]: Entering directory `/home/king/BuildEnvironment/AVS_CrossCompiler/OpenBLAS-develop/interface'
> arm-linux-gnueabi-gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -marm -mfpu=vfpv3  -mfloat-abi=hard -march=armv7-a -DASMNAME=saxpy -DASMFNAME=saxpy_ -DNAME=saxpy_ -DCNAME=saxpy -DCHAR_NAME=\"saxpy_\" -DCHAR_CNAME=\"saxpy\" -DNO_AFFINITY -I.. -I. -UDOUBLE  -UCOMPLEX -c axpy.c -o saxpy.o
> arm-linux-gnueabi-gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -marm -mfpu=vfpv3  -mfloat-abi=hard -march=armv7-a -DASMNAME=sswap -DASMFNAME=sswap_ -DNAME=sswap_ -DCNAME=sswap -DCHAR_NAME=\"sswap_\" -DCHAR_CNAME=\"sswap\" -DNO_AFFINITY -I.. -I. -UDOUBLE  -UCOMPLEX -c swap.c -o sswap.o
> arm-linux-gnueabi-gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -marm -mfpu=vfpv3  -mfloat-abi=hard -march=armv7-a -DASMNAME=scopy -DASMFNAME=scopy_ -DNAME=scopy_ -DCNAME=scopy -DCHAR_NAME=\"scopy_\" -DCHAR_CNAME=\"scopy\" -DNO_AFFINITY -I.. -I. -UDOUBLE  -UCOMPLEX -c copy.c -o scopy.o
> arm-linux-gnueabi-gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -marm -mfpu=vfpv3  -mfloat-abi=hard -march=armv7-a -DASMNAME=sscal -DASMFNAME=sscal_ -DNAME=sscal_ -DCNAME=sscal -DCHAR_NAME=\"sscal_\" -DCHAR_CNAME=\"sscal\" -DNO_AFFINITY -I.. -I. -UDOUBLE  -UCOMPLEX -c scal.c -o sscal.o
> In file included from /home/king/opt/gcc-linaro-6.3.1-2017.02-x86_64_arm-linux-gnueabi/arm-linux-gnueabi/libc/usr/include/features.h:392:0,
>                  from /home/king/opt/gcc-linaro-6.3.1-2017.02-x86_64_arm-linux-gnueabi/arm-linux-gnueabi/libc/usr/include/stdio.h:27,
>                  from swap.c:39:
> /home/king/opt/gcc-linaro-6.3.1-2017.02-x86_64_arm-linux-gnueabi/arm-linux-gnueabi/libc/usr/include/gnu/stubs.h:10:29: fatal error: gnu/stubs-hard.h: No such file or directory
>  # include <gnu/stubs-hard.h>
>                              ^
> compilation terminated.
> make[1]: *** [sswap.o] Error 1
> make[1]: *** Waiting for unfinished jobs....
> In file included from /home/king/opt/gcc-linaro-6.3.1-2017.02-x86_64_arm-linux-gnueabi/arm-linux-gnueabi/libc/usr/include/features.h:392:0,
>                  from /home/king/opt/gcc-linaro-6.3.1-2017.02-x86_64_arm-linux-gnueabi/arm-linux-gnueabi/libc/usr/include/stdio.h:27,
>                  from copy.c:39:
> /home/king/opt/gcc-linaro-6.3.1-2017.02-x86_64_arm-linux-gnueabi/arm-linux-gnueabi/libc/usr/include/gnu/stubs.h:10:29: fatal error: gnu/stubs-hard.h: No such file or directory
>  # include <gnu/stubs-hard.h>
>                              ^
> compilation terminated.
> make[1]: *** [scopy.o] Error 1
> In file included from /home/king/opt/gcc-linaro-6.3.1-2017.02-x86_64_arm-linux-gnueabi/arm-linux-gnueabi/libc/usr/include/features.h:392:0,
>                  from /home/king/opt/gcc-linaro-6.3.1-2017.02-x86_64_arm-linux-gnueabi/arm-linux-gnueabi/libc/usr/include/stdio.h:27,
>                  from scal.c:39:
> /home/king/opt/gcc-linaro-6.3.1-2017.02-x86_64_arm-linux-gnueabi/arm-linux-gnueabi/libc/usr/include/gnu/stubs.h:10:29: fatal error: gnu/stubs-hard.h: No such file or directory
>  # include <gnu/stubs-hard.h>
>                              ^
> compilation terminated.
> make[1]: *** [sscal.o] Error 1
> In file included from /home/king/opt/gcc-linaro-6.3.1-2017.02-x86_64_arm-linux-gnueabi/arm-linux-gnueabi/libc/usr/include/features.h:392:0,
>                  from /home/king/opt/gcc-linaro-6.3.1-2017.02-x86_64_arm-linux-gnueabi/arm-linux-gnueabi/libc/usr/include/stdio.h:27,
>                  from axpy.c:39:
> /home/king/opt/gcc-linaro-6.3.1-2017.02-x86_64_arm-linux-gnueabi/arm-linux-gnueabi/libc/usr/include/gnu/stubs.h:10:29: fatal error: gnu/stubs-hard.h: No such file or directory
>  # include <gnu/stubs-hard.h>
>                              ^
> compilation terminated.
> make[1]: *** [saxpy.o] Error 1
> make[1]: Leaving directory `/home/king/BuildEnvironment/AVS_CrossCompiler/OpenBLAS-develop/interface'
> make: *** [libs] Error 1

**Comment by martin-frbg** [comment]
Looks like your toolchain does not provide support for ARM "hardware floating point". Perhaps there is a version named something like arm-linux-gnueabihf available ? (But see #1145 for potential problems)
