### ISSUE TITLE
TARGET error

### ISSUE THREAD

**Issue by Jadamso** [xianyi/OpenBLAS#1203]
When I make, 
    $ make PREFIX=$HOME FC=gfortran

I get the following error
    make: *** [getarch_2nd] Error 1
    Makefile:131: *** OpenBLAS: Detecting CPU failed. Please set TARGET explicitly, e.g. make TARGET=your_cpu_target. Please read README for the detail..  Stop

I am not sure how to find my TARGET to match what is in the readme. I have a brand new lenovo.

$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    2
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 142
Model name:            Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
Stepping:              9
CPU MHz:               1097.695
BogoMIPS:              5800.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              4096K
NUMA node0 CPU(s):     0-3
```

**Comment by martin-frbg** [comment]
make TARGET=HASWELL
next version should autodetect it

**Comment by martin-frbg** [comment]
Did this work for you, or would you like further assistance ?

**Comment by Jadamso** [comment]
It works. Thank you.
