### ISSUE TITLE
cbals_sgemm use on ARMV7

### ISSUE THREAD

**Issue by ctgushiwei** [xianyi/OpenBLAS#1205]
i have compile openBlas V0.2.19,and generate lib on arm,but when i use cblas_sgemm,it can not work.how can i sole this problem

**Comment by brada4** [comment]
Please show:
- parameters passed to 'make' command
- /proc/cpuinfo
- last report after make ended
- backtrace from crash (in gdb 't a a bt')

**Comment by martin-frbg** [comment]
Continued in #1206 apparently, so closing this
