### ISSUE TITLE
segmentation fault when use cblas_sgemm.

### ISSUE THREAD

**Issue by ctgushiwei** [xianyi/OpenBLAS#1206]
cpuinfo: processors:4      ARMv7     rev1      cpu arch:7   Hardware:hi3536
make:TARGET=ARMV7 NOFORTRAN=1 HOSTCC=gcc NO_LAPACK=1 ONLY_CBLAS=1

my openblas is 0.2.19.when i use cblas_sgemm,  backtrace from crash:blas_server.c and the fault is segmentation fault

how can i solve this problem

**Comment by brada4** [comment]
Could you close previous issue on same subject?

- does it crash with single-thereaded OpenBLAS
- can you generate backtrace: run your program in gdb, then when it catches fault run 't a a bt' in gdb, and attach resulting output (do not copy/paste)

**Comment by martin-frbg** [comment]
Can you show a simple example of your cblas_sgemm usage ? It could be that you got some calling parameter wrong, in particular if you used the documentation for the regular blas function sgemm, as array handling differs between c (cblas) and fortran (blas).

**Comment by ctgushiwei** [comment]
@brada4  both single-threaded OpenBLAS or multi-threaded OpenBLAS crash at the same function. blas_sever.c when use exec_blas function..   and my test code is sample,it is ok when test at PC.

**Comment by ctgushiwei** [comment]
@brada4 @martin-frbg  my test code is

float Aa[2*3]={1,2,3,4,5,6};
float Bb[3*4]={1,2,3,4,5,6,7,8,9,10,11,12};
float y1[2*4]={1,2,3,4,5,6,7,8};

cblas_sgemm(CblasRowMajor,CblasNoTrans,CblasNoTrans,2,4,3,1.0,Aa,3,Bb,4,1.0,4);
printf("%f",y1[0]);

when use single-threaded OpenBLAS it crashed at the int exec_blas(BLASLONG num,blas_queue_t*queue) when call (routine)(queue->args,queue->range_m,queue->range_n,queue->sa,queue->sb,0)

when use multi-threaded OpenBLAS ,it can not call the blas_sever.c,i do not know what function it use?because it only generate blas_server.o

how can i  solve this problem

**Comment by brada4** [comment]
Are you compiling/linking OpenBLAS and your program with 'hardfp' ?
Does it stop crashing when using ARMV5 target instead (which is C-only and works with softfp)?

**Comment by ctgushiwei** [comment]
sorry,i have not a ARMV5  target.both softfp and hardfp can not work normly. when I test the cblas_sgemv, it output bus error..i do not kown the reason

**Comment by brada4** [comment]
You need to run 'make clean' between rebuilds. I suspect your gcc somehow defaults to softfp and built library is not usable. gdb backtrace would show that in no time.
ARMV5 kernels will run on ARMV7, slower, but run in any floating point ABI.

**Comment by martin-frbg** [comment]
As an alternative to building for ARMV5, you could try the arm_soft_fp_api branch of the current development version - while this is still incomplete, it appears to include an implementation of sgemm that should work in your environment. (On the "Code" tab of this webpage, there is a "Branch:" selector between the table heading and the latest commit line. Switch this from "develop" to "arm_soft_fp_api" (a couple of lines above "develop" in the menu), the green "Clone or download" button will offer you a download of this branch as a zip archive.)

**Comment by ctgushiwei** [comment]
@martin-frbg @brada4 @notaz @JohannesBuchner @IvanUkhov  
I have known the reason. the function at  /kernel/ did not compiled, when i exect the code from kernel/generic/gemmkernel_2x2.c the code can work..

i do not konw how to complie code at /kernel/arm/  .could you help me

**Comment by brada4** [comment]
Please refer to https://github.com/xianyi/OpenBLAS/issues/1206#issuecomment-308941267

**Comment by ctgushiwei** [comment]
@martin-frbg  could you share the "arm_soft_fp_api" to me?I can not download normly

**Comment by brada4** [comment]
Here: https://github.com/xianyi/OpenBLAS/archive/arm_soft_fp_abi.zip
