### ISSUE TITLE
Unable to start correctly when using openblas+armadillo with VS2015

### ISSUE THREAD

**Issue by daydayup2017** [xianyi/OpenBLAS#1207]
Hi,

I can use the armadillo and original blas library in VS2015. but when I am using openblas binary packages for replacing blas library in the armadillo, I write a simple program in Visual Studio 2015, X64 platform, and I got a problem: 
“The application was unable to start correctly (0xc000007b). Click ok to close the application”
Then the program exit without results.
How can I fix this problem?
Thanks.

**Comment by martin-frbg** [comment]
Make sure that you got the right (64bit) version of the openblas binary - error 0xc000007b usually comes from mixing 32 and 64 bit libraries in an application.

**Comment by daydayup2017** [comment]
Yes, some dependency dll is wrong. I got it right. thanks!
