### ISSUE TITLE
Issue compiling OpenBLAS

### ISSUE THREAD

**Issue by mariasmo** [xianyi/OpenBLAS#1208]
Hi,

I am running into an issue trying to compile the OpenBLAS as part of compiling Kaldi for Android. I followed all the instructions on this blog(http://jcsilva.github.io/2017/03/18/compile-kaldi-android/ ) until the following where I am stuck:

make TARGET=ARMV7 HOSTCC=gcc CC=arm-linux-androideabi-gcc NOFORTRAN=1 NUM_THREADS=32 libs 

This is the error I am getting when trying to run the above command:
-----------------------------------------------------------------
C Compiler (arm-linux-androideabi-gcc) is something wrong.
1 at ./c_check line 28.
make: *** [config.h] Error 2
Makefile.system:165: Makefile.conf: No such file or directory
Makefile.system:912: Makefile.: No such file or directory
make: *** No rule to make target `Makefile.'. Stop.
-----------------------------------------------------------------

I got the latest branch of OpenBLAS.

I did set the PATH to the android tool chain correctly.

I am running out of options.

Any help is greatly appreciated.

Thanks in advance.

**Comment by martin-frbg** [comment]
Still looks as if the PATH to the android toolchain is not set correctly (or the toolchain is incomplete).
At that point in c_check it tries to run the command `arm-linux-androideabi-gcc -E ctest.c` - you could try entering this on a command line to see what error message you get.

**Comment by brada4** [comment]
Unlikely there will be 32-core 32bit android any time soon. What is your NDK vrsion? Is it recent clang-based?

**Comment by mariasmo** [comment]
Hi martin-frbg & brada4: thanks for your responses.

The issue seemed to be that it did not have permissions to the toolchain directory when running as my user. As a test, i ran it as root and it compiled fine. 

My NDK version is:
15.0.4075724 

Thanks again for your help.( I will ping if I run into any more issues::))

**Comment by brada4** [comment]
But close this issue in the meantime, Android NDK is not OpenBLAS component.

**Comment by mariasmo** [comment]
Hi martin-frbg & brada4: 

I ran into the issue described in the following thread:

https://github.com/xianyi/OpenBLAS/issues/1173

Since that thread was closed, I am putting in my questions here:

So after doing the 
make TARGET=ARMV7 HOSTCC=gcc CC=arm-linux-androideabi-gcc NOFORTRAN=1 NUM_THREADS=32 libs

command, I executed the following command:

make install PREFIX=`pwd` /install

But it failed saying that it could not find libopenblas_armv7p-r0.2.20.dev.so

When I searched for the error, I came across the above thread. Then as per the instructions in that thread, I executed the following:

make TARGET=ARMV7 HOSTCC=gcc CC=arm-linux-androideabi-gcc NOFORTRAN=1 NUM_THREADS=32 libs shared

Then it gave me couple of errors(I am copying only the error outputs:)

~/androidstudio/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lgfortran

~/androidstudio/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lquadmath

and then at the end:

../libopenblas_armv7p-r0.2.20.dev.so: error: undefined reference to 'stderr'
collect2: error: ld returned 1 exit status
make[1]: *** [../libopenblas_armv7p-r0.2.20.dev.so] Error 1


But I do have lgfortran installed and is in /usr/bin. I did not find "quadmath" though.

The I ran the make command with just "shared"(i.e without libs option) and it seemed to be successful.

But I did see some message stating that LAPACK could not be built because lgfortran was not found and only BLAS was built.

Then when I do the install command , it seemed to have successfully created the above mentioned .so file.

Is this ok? Will I run into issues when running the programs on a mobile device?

Thanks in advance

**Comment by brada4** [comment]
You need to run 'make clean' before building with different parameters.
You can set FC=NoThing or something similarily fake to disable all fortran/lapack. It seems that build system picks gfortran present on build host which is obvioulsy x86 and will not suffice for lapack in your library.

**Comment by mariasmo** [comment]
Hi Brada4,

What do you mean by the following statement?

**It seems that build system picks gfortran present on build host which is obvioulsy x86 and will not suffice for lapack in your library.**

My system is definitely 64 bit( and 64 bit debian jessie installed)

lscpu output:

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                12
On-line CPU(s) list:   0-11
Thread(s) per core:    2
Core(s) per socket:    6
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU @ 2.30GHz
Stepping:              0
CPU MHz:               2300.000
BogoMIPS:              4600.00
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              46080K
NUMA node0 CPU(s):     0-11

**Comment by brada4** [comment]
I dont see how that could emit armeabi binaries.

**Comment by mariasmo** [comment]
can u please elaborate? I am completely new to OpenBLAS. Am I doing things wrong?
Let me know so that I will correct myself and proceed.

Thanks

**Comment by mariasmo** [comment]
make TARGET=ARMV7 HOSTCC=gcc CC=arm-linux-androideabi-gcc NOFORTRAN=1 NUM_THREADS=32 libs

This is the first statement when I run the above make command. 

OpenBLAS: Detecting fortran compiler failed. Cannot compile LAPACK. Only compile BLAS.

Why is it not able to recognize the fortran installed on my machine? I am really surprised.

Here is the output for ls -l /usr/bin | grep fortran

lrwxrwxrwx 1 root root         12 Feb 25  2015 gfortran -> gfortran-4.9
-rwxr-xr-x 1 root root     834680 Dec 25  2014 gfortran-4.9
lrwxrwxrwx 1 root root         12 Feb 25  2015 x86_64-linux-gnu-gfortran -> gfortran-4.9
lrwxrwxrwx 1 root root         12 Dec 25  2014 x86_64-linux-gnu-gfortran-4.9 -> gfortran-4.9

**Comment by brada4** [comment]
-lgfortran comes from previous failed build. You sort of try to build without fortran already, I just suggested other option to disable fortran and lapack.

**Comment by mariasmo** [comment]
Hi ,

Can someone please help? I am stuck here unable to proceed further. Basically I am not able to successfully compile the shared library libopenblas_armv7p-r0.2.20.dev.so.

Basically this is my first step which finishes without any errors:

make TARGET=ARMV7 HOSTCC=gcc CC=arm-linux-androideabi-gcc NOFORTRAN=1 NUM_THREADS=32 libs 

Since it did not build the .so file, I then did the following which fails(the .so file is created though..but it throws the same stderr error when used in another native project) 

make TARGET=ARMV7 HOSTCC=gcc CC=arm-linux-androideabi-gcc NOFORTRAN=1 NUM_THREADS=32 shared

I am pasting the output from the make command. May be the warnings might throw some light(please note that the last warning about libc). Please let me know if there are issues in my configuration(i.e what is the incompatibility here??). Thanks in advance.

make[1]: Entering directory `/AS/OpenBLAS/exports'
perl ./gensymbol linktest  arm _ 0 0 1 1 0 0 "" "" 1 > linktest.c
arm-linux-androideabi-gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -DF_INTERFACE_GFORT -fPIC -DNO_LAPACK -DNO_LAPACKE -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=32 -marm -mfpu=neon  -mfloat-abi=hard -march=armv7-a -Wl,--no-warn-mismatch -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  -shared -o ../libopenblas_armv7p-r0.2.20.dev.so \
	-Wl,--whole-archive ../libopenblas_armv7p-r0.2.20.dev.a -Wl,--no-whole-archive \
	-Wl,-soname,libopenblas.so 
arm-linux-androideabi-gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -DF_INTERFACE_GFORT -fPIC -DNO_LAPACK -DNO_LAPACKE -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=32 -marm -mfpu=neon  -mfloat-abi=hard -march=armv7-a -Wl,--no-warn-mismatch -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  -w -o linktest linktest.c ../libopenblas_armv7p-r0.2.20.dev.so -L/usr/lib/gcc/x86_64-linux-gnu/4.9 -L/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.9/../../..  -lgfortran -lm -lquadmath -lm -lc   && echo OK.
/AS/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: warning: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.9/libgfortran.so while searching for gfortran
/AS/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lgfortran
/AS/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: warning: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libm.so while searching for m
/AS/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: warning: skipping incompatible /usr/lib/x86_64-linux-gnu/libm.so while searching for m
/AS/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: warning: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.9/libquadmath.so while searching for quadmath
/AS/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lquadmath
/AS/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: warning: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libm.so while searching for m
/AS/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: warning: skipping incompatible /usr/lib/x86_64-linux-gnu/libm.so while searching for m
/AS/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: warning: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libc.so while searching for c
/AS/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: warning: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libdl.so while searching for dl
/AS/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: warning: skipping incompatible /usr/lib/x86_64-linux-gnu/libdl.so while searching for dl
/AS/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: warning: skipping incompatible /usr/lib/x86_64-linux-gnu/libc.so while searching for c
/AS/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: warning: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libc.so while searching for c
/AS/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: warning: skipping incompatible /usr/lib/x86_64-linux-gnu/libc.so while searching for c
../libopenblas_armv7p-r0.2.20.dev.so: error: undefined reference to 'stderr'
collect2: error: ld returned 1 exit status
make[1]: *** [../libopenblas_armv7p-r0.2.20.dev.so] Error 1
make[1]: Leaving directory `/AS/OpenBLAS/exports'
Makefile:85: recipe for target 'shared' failed
make: *** [shared] Error 2

**Comment by mariasmo** [comment]
So after doing little bit more googling, this is what i understood:

I am trying to build 32 bit binaries on a 64 bit machine and since the make system did not find the 32 bit libraries to link, it skips them. However it results in an error eventually.

Am I correct in my understanding?

If so what are my options?

1) Do I need to get the 32 bit versions of all the libs( I am concerned about doing this since i might corrupt my system - with both the 32 bit and 64 bit conflicts)

2) Do I have to then build the aarch64 binaries instead then?( but from the Android NDK documentation it says we should be able to build 32 bit android binaries on a 64 bit machine)

Any thoughts?

Thanks

**Comment by brada4** [comment]
If you mix up system compilers with cross compilers they dont produce valid executable modules.
Can you fix your compilers before trying a new build?

**Comment by martin-frbg** [comment]
Seems there is something wrong with your Android toolchain setup, the linker appears to be finding the local x86 libraries of the build host instead of the Android ones provided by the NDK. And the fact that it tries to link with libgfortran (and its dependency libquadmath) at all suggests that you may have object files around from a previous build attempt where you forgot to specifiy NOFORTRAN=1. Best review your NDK installation and then do a `make clean` followed by `make TARGET=ARMV7 HOSTCC=gcc CC=arm-linux-androideabi-gcc NOFORTRAN=1 NUM_THREADS=32` (note no "libs" or "shared" at the end of the command line, this should do the complete build in one go).

**Comment by mariasmo** [comment]
Hi brada4 & martin-frbg

After lot of googling around and redoing the compilation multiple times, i found the following:

As per this link http://jcsilva.github.io/2017/03/18/compile-kaldi-android/
I used the same version as mentioned in the above link i.e commit SHA 99880f7 seemed to be working( atleast i am able to compile that particualr version of OpenBLAS without any errors on Ubuntu since the post mentioned Ubuntu..the latest OpenBLAS version failed on Ubuntu as well.so i checkedout the SHA 99880f7 and it compiled successfully. my original OS is Debian Jessie. I will go back to it and test it out as well. But I am guessing it should work for the specified OpenBLAS version) 

Hope this helps in identifying the issue. Please let me know if it's an issue in the code and when/if it's fixed.

Thanks

**Comment by brada4** [comment]
I dont know why your NDK picks files from system library path. Do you set something like LD_LIB_PATH before failed builds?

**Comment by mariasmo** [comment]
No. I dont set the LD_LIB_PATH. I just add the toolchain/bin to the PATH variable.

One other thing I have noticed is that the latest version of OpenBLAS tries to build the libopenblas_armv7p-r0.2.20.dev.so file and that is where it's erroring out.

While the 99880f7 commit doesnt build the above mentioned .so file.

**Comment by mariasmo** [comment]
sorry.spoke too early.
still have the same issues. even though compiling OpenBLAS was successful, linking with other c++ project still failed.

/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lm_hard
/OpenBLAS/lib/libopenblas.a(blas_server.o):blas_server.c:function blas_thread_init: error: undefined reference to 'stderr'
/OpenBLAS/lib/libopenblas.a(blas_server.o):blas_server.c:function exec_blas: error: undefined reference to 'stderr'

**Comment by martin-frbg** [comment]
Maybe you need to set ANDROID_NDK_PATH or NDK_ROOT so that it can find all parts of itself ?
A build script was posted as part of #963 (and I have been meaning to add it but never got around to doing that it seems), perhaps it helps ?

**Comment by xianyi** [comment]
I have compiled Android static lib and shared library on My Mac.

For example, softfp ABI.

```
make TARGET=ARMV7 HOSTCC=clang CC=arm-linux-androideabi-gcc NO_LAPACK=1 ARM_SOFTFP_ABI=1

make TARGET=ARMV7 HOSTCC=clang CC=arm-linux-androideabi-gcc NO_LAPACK=1 USE_THREAD=0 ARM_SOFTFP_ABI=1 shared


make TARGET=ARMV7 HOSTCC=clang CC=arm-linux-androideabi-gcc NO_LAPACK=1 USE_THREAD=0 ARM_SOFTFP_ABI=1 PREFIX=/to/your/path install
```

In first step, you may  meet some errors in building test. It is OK.

**Comment by mariasmo** [comment]
Hi xianyi,

As per your instructions here https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android

you ask us to do only "libs". Is it ok to try the shared as well?

Also I have not been specifying these two options:
NO_LAPACK=1 ARM_SOFTFP_ABI=1

Do I need to?

If I have to build hard floating points, what is the command line option?
ARM_SOFTFP_ABI=0 
Would putting the above option to 0 work??

Thanks again for your help.
(I am stuck on this for a week now...i am confident i will be able to successfully compile with the help of you all::))
Really appreciate everyone's help.

**Comment by mariasmo** [comment]
Hello,

Looks like the issue is caused by the NDK removing support for Hard Float ABI. As I was looking at the issues, looks like it's already being discussed here in the thread:
https://github.com/xianyi/OpenBLAS/issues/1215

So to sum up, my issues were caused in r15 of NDK but not in r14 - because as i read that the hard float ABI support is "removed" from NDK r15 onwards.

Relevant info from another forum:
"
The hard float ABI support was "removed" from the NDK in r12 https://android.googlesource.com/platform/ndk/+/master/docs/HardFloatAbi.md), but they really removed it only in r15.
"


So this issue can be closed or combined with 1215.

Thanks everyone.

**Comment by brada4** [comment]
Compile with older NDK?

**Comment by mariasmo** [comment]
yes. successfully compiled with r14

**Comment by lixiaohang** [comment]
> Hi ,
> 
> Can someone please help? I am stuck here unable to proceed further. Basically I am not able to successfully compile the shared library libopenblas_armv7p-r0.2.20.dev.so.
> 
> Basically this is my first step which finishes without any errors:
> 
> make TARGET=ARMV7 HOSTCC=gcc CC=arm-linux-androideabi-gcc NOFORTRAN=1 NUM_THREADS=32 libs
> 
> Since it did not build the .so file, I then did the following which fails(the .so file is created though..but it throws the same stderr error when used in another native project)
> 
> make TARGET=ARMV7 HOSTCC=gcc CC=arm-linux-androideabi-gcc NOFORTRAN=1 NUM_THREADS=32 shared
> 
> I am pasting the output from the make command. May be the warnings might throw some light(please note that the last warning about libc). Please let me know if there are issues in my configuration(i.e what is the incompatibility here??). Thanks in advance.
> 
> make[1]: Entering directory `/AS/OpenBLAS/exports'
> perl ./gensymbol linktest arm _ 0 0 1 1 0 0 "" "" 1 > linktest.c
> arm-linux-androideabi-gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -DF_INTERFACE_GFORT -fPIC -DNO_LAPACK -DNO_LAPACKE -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=32 -marm -mfpu=neon -mfloat-abi=hard -march=armv7-a -Wl,--no-warn-mismatch -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME="_" -DCHAR_CNAME="" -DNO_AFFINITY -I.. -shared -o ../libopenblas_armv7p-r0.2.20.dev.so -Wl,--whole-archive ../libopenblas_armv7p-r0.2.20.dev.a -Wl,--no-whole-archive -Wl,-soname,libopenblas.so arm-linux-androideabi-gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -DF_INTERFACE_GFORT -fPIC -DNO_LAPACK -DNO_LAPACKE -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=32 -marm -mfpu=neon -mfloat-abi=hard -march=armv7-a -Wl,--no-warn-mismatch -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME="_" -DCHAR_CNAME="" -DNO_AFFINITY -I.. -w -o linktest linktest.c ../libopenblas_armv7p-r0.2.20.dev.so -L/usr/lib/gcc/x86_64-linux-gnu/4.9 -L/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.9/../../.. -lgfortran -lm -lquadmath -lm -lc && echo OK.
> 
> /AS/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: warning: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.9/libgfortran.so while searching for gfortran
> 
> /AS/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lgfortran
> 
> /AS/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: warning: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libm.so while searching for m
> 
> /AS/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: warning: skipping incompatible /usr/lib/x86_64-linux-gnu/libm.so while searching for m
> 
> /AS/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: warning: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.9/libquadmath.so while searching for quadmath
> 
> /AS/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lquadmath
> 
> /AS/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: warning: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libm.so while searching for m
> 
> /AS/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: warning: skipping incompatible /usr/lib/x86_64-linux-gnu/libm.so while searching for m
> 
> /AS/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: warning: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libc.so while searching for c
> 
> /AS/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: warning: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libdl.so while searching for dl
> 
> /AS/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: warning: skipping incompatible /usr/lib/x86_64-linux-gnu/libdl.so while searching for dl
> 
> /AS/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: warning: skipping incompatible /usr/lib/x86_64-linux-gnu/libc.so while searching for c
> 
> /AS/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: warning: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libc.so while searching for c
> 
> /AS/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: warning: skipping incompatible /usr/lib/x86_64-linux-gnu/libc.so while searching for c
> ../libopenblas_armv7p-r0.2.20.dev.so: error: undefined reference to 'stderr'
> collect2: error: ld returned 1 exit status
> make[1]: *** [../libopenblas_armv7p-r0.2.20.dev.so] Error 1
> make[1]: Leaving directory `/AS/OpenBLAS/exports'
> Makefile:85: recipe for target 'shared' failed
> make: *** [shared] Error 2

Hi :
How did you solver this Problem ?
