### ISSUE TITLE
how to complie openblas release version on armv7 without fortran complie?

### ISSUE THREAD

**Issue by ctgushiwei** [xianyi/OpenBLAS#1209]
@xianyi my openblas is 0.2.19 release version,and have not fortran compiler ,my arm is hisi 3536.
could you tell me how to compile openblas and use cblas_sgemm normly

**Comment by brada4** [comment]
You can examine Makefile.rule for options available. ONLY_CBLAS=1 will skip fortran api (sgemm_) and fortran compiler (all LAPACK)
Sure read guide for proper options to set for android NDK required options.
