### ISSUE TITLE
Bug in kernel/arm/axpy_vfp.S

### ISSUE THREAD

**Issue by ashwinyes** [xianyi/OpenBLAS#1219]
While trying to add the softfp support to  kernel/arm/axpy_vfp.S, noticed that there is an actual bug in the file for complex precision.

SAMPLE CODE

```
float valf[16] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};

int main()
{
   int i;
   float alphaf[2] = {2.0, 2.0};
   cblas_caxpy(8, alphaf, valf, 1, valf, 1);
   for (i = 0; i < 16; i++) printf("%.2lf ", valf[i]);
   printf("\n");

   return 0;
}

```
With kernel/arm/axpy_vfp.S, the output is 
`-2.00 3.00 0.00 13.00 2.00 23.00 4.00 33.00 6.00 43.00 8.00 53.00 10.00 63.00 12.00 73.00`

While with kernel/arm/axpy.c and x86 implementation gives output  as
`-2.00 -1.00 0.00 9.00 2.00 19.00 4.00 29.00 6.00 39.00 8.00 49.00 10.00 59.00 12.00 69.00`

**Comment by brada4** [comment]
Not a bug... Inconsistency between undefined behaviours is still under umbrella of undefined behaviour.
Most likely assembly puts all in registers and does not get modified in-output.

**Comment by martin-frbg** [comment]
Does the problem persist when you provide a separate array for the second vector argument ?

**Comment by brada4** [comment]
Actually VFP solution is correct one and other is affected by overlapping args.
`(A,Bi)(2,2i)+(A,Bi) = (3A-2B,3Bi+2Ai)`
`-2 3 0 13 .... 12 73`

**Comment by ashwinyes** [comment]
@martin-frbg @brada4 
Thanks for suggestions. This seems to be an issue when first and second arguments are same. Not happening when different vectors are given as arguments.

Closing the issue.
