### ISSUE TITLE
undefined reference to `__assert_func'

### ISSUE THREAD

**Issue by syeh106** [xianyi/OpenBLAS#1224]
Hi,  I'm new to OpenBLAS.  I've been trying to compile OpenBLAS v0.2.19 on Cygwin64 with the following command:

make FC=gfortran

However,I kept getting the following errors.  I was wondering if someone know what I might do to fix it.  Thanks a lot!

Best regards,
Steve

gfortran -Wall -m64  -o zblat1 zblat1.o ../libopenblas_penrynp-r0.2.19.a -lgfortran -lgfortran
gfortran -Wall -m64  -o sblat2 sblat2.o ../libopenblas_penrynp-r0.2.19.a -lgfortran -lgfortran
gfortran -Wall -m64  -o dblat2 dblat2.o ../libopenblas_penrynp-r0.2.19.a -lgfortran -lgfortran
../libopenblas_penrynp-r0.2.19.a(sgemv.o):gemv.c:(.text+0x3a5): undefined reference to `__assert_fun             c'
../libopenblas_penrynp-r0.2.19.a(sger.o):ger.c:(.text+0x275): undefined reference to `__assert_func'
collect2.exe: error: ld returned 1 exit status
../libopenblas_penrynp-r0.2.19.a(dgemv.o):gemv.c:(.text+0x3a5): undefined reference to `__assert_fun             c'
../libopenblas_penrynp-r0.2.19.a(dger.o):ger.c:(.text+0x275): undefined reference to `__assert_func'
collect2.exe: error: ld returned 1 exit status
make[1]: *** [Makefile:144: sblat2] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:147: dblat2] Error 1
make[1]: Leaving directory '/home/steve/OpenBLAS-0.2.19-b/test'
make: *** [Makefile:112: tests] Error 2

**Comment by martin-frbg** [comment]
Which C compiler did you use ? It could be just that it is not linking to libcygwin in these tests, or you have multiple versions of gcc installed and it is somehow picking an incompatible one.

**Comment by syeh106** [comment]
I'm using gcc v5.4.0.  For the 2 possibilities, can you elaborate a bit more about what commands/actions I may use to find out if one of them is the cause?  Thanks!

**Comment by brada4** [comment]
Do you have some libgfortran*.dll somewhere in DLL search paths, like for mingw or so?

**Comment by syeh106** [comment]
BTW, if I just do

make

without "FC=gfortran", it compiled successfully.  (But I would lose LAPACK.)

I did a quick a quick search for 'libgfortran*.dll', but didn't find it.  I'll search more thoroughly a little later.

**Comment by martin-frbg** [comment]
Wonder why it does not autodetect the presence of gfortran then, though this could be a feature on Windows. Are both gcc and gfortran same version 5.4.0 ? (I seem to remember someone mentioning in an earlier issue ticket that some Makefile is carelessly invoking the compiler instead of the actual linker to link things, which could go wrong if they are different generations)

**Comment by syeh106** [comment]
Thanks a lot, martin-frbg !  It's indeed due to inconsistent versions of gcc & gfortran.  It turned out my gfortran version was v4.9.2.  After updating it to v5.4.0, the problem went away!

**Comment by ashwinyes** [comment]
@syeh106 Please close the issue if it is solved.
