### ISSUE TITLE
There is no libopenblas.so after cross-compile for armv7

### ISSUE THREAD

**Issue by samsun639** [xianyi/OpenBLAS#1227]
**steps to reproduce:**

export PATH=/path/to/standalone-toolchain/bin:$PATH
make TARGET=ARMV7 HOSTCC=gcc CC=arm-linux-androideabi-gcc NOFORTRAN=1 libs
make PREFIX=/root/openblas/OpenBLAS/install/ install

**ERROR:**
make PREFIX=/root/openblas/OpenBLAS/install/ install
make -j 8 -f Makefile.install install
make[1]: Entering directory `/local/mnt/openblas/OpenBLAS'
Generating openblas_config.h in /root/openblas/OpenBLAS/install//include
Generating f77blas.h in /root/openblas/OpenBLAS/install//include
Generating cblas.h in /root/openblas/OpenBLAS/install//include
Copying the static library to /root/openblas/OpenBLAS/install//lib
Copying the shared library to /root/openblas/OpenBLAS/install//lib
install: cannot stat ‘libopenblas_armv7p-r0.2.20.dev.so’: No such file or directory
make[1]: *** [install] Error 1
make[1]: Leaving directory `/local/mnt/openblas/OpenBLAS'
make: *** [install] Error 2

How can I build libopenblas.so?
Thanks in advance.

**Comment by xianyi** [comment]
`make TARGET=ARMV7 HOSTCC=gcc CC=arm-linux-androideabi-gcc NOFORTRAN=1 shared`

**Comment by samsun639** [comment]
worked, thanks!
