### ISSUE TITLE
Update Android installation instructions

### ISSUE THREAD

**Issue by cconrads-scicomp** [xianyi/OpenBLAS#1228]
To get a pkg-config file with proper compiler and linker flags, the same command line options must be given to Make during compilation and linking, cf. #1199. The wiki entry [_How to build OpenBLAS for Android_](https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android) should thus be updated as follows:

> When you are done, install OpenBLAS into the desired directory using the *same* command line options used for compilation, e.g.,
> ```
> make TARGET=ARMV8 BINARY=64 HOSTCC=gcc CC=aarch64-linux-android-gcc NOFORTRAN=1 libs
> make TARGET=ARMV8 BINARY=64 HOSTCC=gcc CC=aarch64-linux-android-gcc NOFORTRAN=1 PREFIX=/path/to/install-dir install
> ```

**Comment by martin-frbg** [comment]
This is true for all targets as far as I know, and the special instruction to perform just the "libs" part of the
build for Android will go as soon as 0.2.20 with added support for shared library builds on Android is released.

**Comment by brada4** [comment]
@cconrads-scicomp but you can edit wiki at will in accordance with your directions.

**Comment by martin-frbg** [comment]
I have updated the wiki article to (hopefully) address this and the improvements coming in 0.2.20.
