### ISSUE TITLE
Publishing Nuget package

### ISSUE THREAD

**Issue by xoviat** [xianyi/OpenBLAS#1240]
Would you mind publishing an official nuget package? It [is not difficult using appveyor](https://www.appveyor.com/docs/deployment/nuget/).

**Comment by xoviat** [comment]
I am aware of the existing packages but they do not contain an update 32 bit version.

**Comment by brada4** [comment]
Those unofficial packages pointlessly point to default openblas home page, especially the most downloaded one is old and buggy.
It is not that easy - MSVC build with appveyor is not the fast assembly one, current windows dll on sf.net is cross-built on Linux.
If you think you can do it right - go ahead.

**Comment by xoviat** [comment]
so should this one be uploaded? https://travis-ci.org/xianyi/OpenBLAS/jobs/253894094

**Comment by brada4** [comment]
How that is a valid release?

**Comment by xoviat** [comment]
It's not. this would be done with git tags.

**Comment by brada4** [comment]
Or ideally as part of release packaging.... Do you happen to know how to get pdb file, even partial, out of mingw build? Without that no big advantage over current binary zip.
