### ISSUE TITLE
Self Tests Fail (L2/L3) When Using IBM Compilers

### ISSUE THREAD

**Issue by hughes-c** [xianyi/OpenBLAS#1248]
The self and link tests fail when using the IBM build tools but work fine on the same system with gcc 5.4.0. I have not tried with MASS or without OpenMP;  nor have I compared the assembly produced by the different compilers yet. I have tried everything from O0 to O5 with and without the strict flag and the results are the same. 

I have included a file with the test output below and will update the issue when I know more.

System Details:

- RHEL 7 Little Endian
- IBM Power8 (8335-GTA) (dual socket 8PE/8thread per socket)
- xlc-14..1(beta 6)/xlf-16.1(beta 6)

Make/Compilation:
`VERBOSE=1 USE_OPENMP=1 TARGET=POWER8 make tests  `
`xlc -Ofast -q64 -qstrict -qarch=pwr8 -qtune=pwr8 -qalign=linuxppc -DUSE_OPENMP -qsmp=omp  `
`xlf90_r -q64 -qpic=large -O2 -q64 -qstrict -qfixed -qarch=pwr8 -qtune=pwr8 -qalign=bindc=linuxppc -DUSE_OPENMP -qsmp=omp ` 
I have also tried including `-L${XLF_ROOT}/lib -L${XLC_ROOT}/lib -lxlf90_r -lxlopt -lxlsmp -lxl -lxlfmath `

[build-tests.txt](https://github.com/xianyi/OpenBLAS/files/1173331/build-tests.txt)

**Comment by martin-frbg** [comment]
Can you test with 0.2.20 or current "develop" snapshot rather than 0.2.19 ? There have been several fixes for unwanted side effects of Power8 assembly routines recently. (If RHEL on Power8 uses something other than glibc please use "develop", otherwise 0.2.20 and develop are practically identical)

**Comment by hughes-c** [comment]
Working from the develop branch:  

```
xlc -c -Ofast -q64 -qstrict -qarch=pwr8 -qtune=pwr8 -qalign=linuxppc -DUSE_OPENMP -qsmp=omp -DMAX_STACK_ALLOC=2048 -DF_INTERFACE_IBM -qpic=large -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=128 -DASMNAME=dtrmm_oltucopy -DASMFNAME=dtrmm_oltucopy -DNAME=dtrmm_oltucopy -DCNAME=dtrmm_oltucopy -DCHAR_NAME=\"dtrmm_oltucopy\" -DCHAR_CNAME=\"dtrmm_oltucopy\" -DNO_AFFINITY -I.. -DDOUBLE  -UCOMPLEX  -DDOUBLE -UCOMPLEX -DOUTER -DLOWER -DUNIT generic/trmm_ltcopy_4.c -o dtrmm_oltucopy.o                                                                                                                                                                                                                                     
In file included from ../kernel/power/sdot.c:39:                                                                                                                                                                                               
../kernel/power/sdot_microk_power8.c:169:8: error: unknown register name 'vs32' in asm                                                                                                                                                         
       "vs32","vs33","vs34","vs35","vs36","vs37","vs38","vs39",                                                                                                                                                                                
       ^                                                                                                                                                                                                                                       
1 error generated.                                                                                                                                                                                                                             
Error while processing ../kernel/power/sdot.c.                                                                                                                                                                                                 
make[1]: *** [sdot_k.o] Error 1                                                                                                                                                                                                                
make[1]: *** Waiting for unfinished jobs....                                                                                                                                                                                                   
In file included from ../kernel/power/scopy.c:39:                                                                                                                                                                                              
../kernel/power/scopy_microk_power8.c:110:8: error: unknown register name 'vs40' in asm                                                                                                                                                        
       "vs40","vs41","vs42","vs43","vs44","vs45","vs46","vs47"
```

It keeps going like that for some time.

**Comment by martin-frbg** [comment]
That's bad, these vs registers were added to the assembly clobber lists as part of the fix. This now looks like the clang compiler problem #1120 so could be the file uses some gnu assembler idiom for register naming.

**Comment by martin-frbg** [comment]
Things I found on the 'net suggest compiler options like -qaltivec or -maltivec might be needed for xlc to enable compiler support for vector data types and instructions. No idea if that is true...

**Comment by hughes-c** [comment]
It looks like a problem with the clobber list. I had a similar issue before where the list was self-referencing (e.g. %0, %1) and xlc produced warnings about register names. I did try adding -qasm=gcc to the compile flags with no success. 

I'll try -qaltivec this afternoon but when i tried adding it on Friday, it gave me a lot more errors.

**Comment by martin-frbg** [comment]
I haven't used xlc since the days of the RS6000 so I cannot really help. All I managed to find was this discussion https://redmine.gromacs.org/issues/2102 which has a link to the manual of a somewhat older xlc version. (Perhaps knowing what the other errors were would help others to identify the problem)

**Comment by brada4** [comment]
If it builds with gcc (Like found at fedora epel) you can call functions from xlc? ASM is extension to C standards and in absence of documentation impossible to guess what goes wrong.

**Comment by hughes-c** [comment]
Yup. I can build it with gcc, including MASS, with no problem. However, I would like to be able to use IBM's toolchain, so I'll keep working on this and report back when I have an update.

**Comment by brada4** [comment]
Please run 'make clean' before new build and record output with 'script'
Fo not run 'make tests' before 'make' completes (ideally plain 'make' runs tests already and you can not mix up build options...)
when i last ran xlc on pSeries it overhauled assemblies at high optimisation levels. Try like '-O1' for starters.

**Comment by brada4** [comment]
Also add `MAKE_NB_JOBS=1` (very slow 1-cpu build) to sync commands with error outputs.
curent output shows _trmm compilation command next to _dot assembly error....

**Comment by hughes-c** [comment]
I've attached the output that you requested.

[power8_build.txt](https://github.com/xianyi/OpenBLAS/files/1209172/power8_build.txt)

**Comment by brada4** [comment]
Maybe the other shadow registers need to be saved go figure.

**Comment by martin-frbg** [comment]
So still no luck finding an xlc option that makes it accept vsx in clobber lists ?

**Comment by brada4** [comment]
maybe -qvsx iff it exists?

**Comment by hughes-c** [comment]
@martin-frbg I have a feeling that it has to do with using altivec, which I'm unable to do. When `qaltivec` is used, the build fails with:  
```
/home/projects/pwr8-rhel73-lsf/ibm/xl/xlC/14.1.0/include/stddef.h: Assembler messages:
/home/projects/pwr8-rhel73-lsf/ibm/xl/xlC/14.1.0/include/stddef.h:34: Error: unrecognized opcode: `typedef'
```
I think that this is a problem with xlc recognizing the vector type but haven't had time to test that hypothesis.

**Comment by brada4** [comment]
Reduce optimisation level?

**Comment by martin-frbg** [comment]
I struggle to understand why -qaltivec would make the _assembler_ try to process the C headers, apparently taking "typedef" for an instruction mnemonic. 
Perhaps it would help to know the complete set of "make" options you are using. (Did the assembler name slip into the CC environment variable ? And why would it take an 822LC a week to build a relatively small library ??)

**Comment by brada4** [comment]
I asked to build on one cpu (normally hours on haswell pc)

**Comment by hughes-c** [comment]
Oh, no, I can compile the OpenBLAS libraries in a couple of minutes. The other comments were a separate issue and I've removed them to avoid confusion.

**Comment by brada4** [comment]
Look around qaltivec in xlc manuals
should be something to unlock more registers....

**Comment by martin-frbg** [comment]
Which file is it that triggers the assembler error ? From a bit of googling this sort of thing can apparently happen when the relevant `#include <stddef.h>` is not guarded by `#ifndef ASSEMBLER`. (Note it could be that stddef.h is itself included by some other header, not sure if xlc would show this like gcc does)

**Comment by hughes-c** [comment]
@martin-frbg It looks like the problem is with amax.S, which includes common.h, which includes cblas.h, which includes stddef.h. I did add guards around the include in cblas.h, but that did not correct the error.

`xlc -c -Ofast -q64 -qstrict -qarch=pwr8 -qtune=pwr8:st -qalign=linuxppc -qaltivec  -DMAX_STACK_ALLOC=2048 -DF_INTERFACE_IBM -qsmp=omp -qpic=large -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=160 -DASMNAME=samax_k -DASMFNAME=samax_k -DNAME=samax_k -DCNAME=samax_k -DCHAR_NAME=\"samax_k\" -DCHAR_CNAME=\"samax_k\" -DNO_AFFINITY -I.. -UDOUBLE  -UCOMPLEX -UCOMPLEX -UDOUBLE  -DUSE_ABS -UUSE_MIN ../kernel/power/amax.S -o samax_k.o`

**Comment by martin-frbg** [comment]
Not sure what the guard needs to look like exactly, perhaps the xlc assembler defines `__ASSEMBLER__` with double underscores or something like that (if it defines anything at all)
(Hm wait - we define ASSEMBLER ourselves in amax.S so that guard should work. Not sure why -qaltivec would make things go astray anyway)

**Comment by martin-frbg** [comment]
Which version are you building that leads to this error- I see __isuruf__ fixed a few unguarded typedefs in the common.h file itself just 17 days ago.

**Comment by hughes-c** [comment]
I'm on develop:https://github.com/xianyi/OpenBLAS/commit/a8a342ccc49bb6e6824c60905ca015d2dd35cb0d

**Comment by hughes-c** [comment]
I did pull out the sdot_kernel_16 function and attempted to compile it with: `xlc -qarch=pwr8 -qtune=pwr8 -qaltivec` and it still won't recognize the registers.
```
error: unknown register name 'vs32' in asm
       "vs32","vs33","vs34","vs35","vs36","vs37","vs38","vs39",

```

**Comment by brada4** [comment]
Small reality check:
Has the problem ever occurred with any non-beta compiler?
Are you sure `as` is from XLC and not from /usr/bin ?

**Comment by martin-frbg** [comment]
Can you try adding "-qhot" to your compiler options please ? (As that is supposed to enable "high order transformations" implying auto-vectorization of loops, it would seem to require the toolchain to understand vsx registers. -qaltivec may only be useful to unlock access to C extensions for vector math. At least provided what I read on the Interwebs is true...)

**Comment by martin-frbg** [comment]
@hughes-c I have confirmed the problems with the "community edition" xlc 13.1.5 , but please see #1078 for the ensuing communication with IBM's David Edelsohn. (In short, the "vs32" naming issue could be worked around but is not the only problem - if anything these issues should be reported as xlc bugs)
