### ISSUE TITLE
Undefined symbol pthread_atfork when load library

### ISSUE THREAD

**Issue by phuclb1** [xianyi/OpenBLAS#1250]
When i load library mxnet (using Openblas) in ARMv7 board, i got this error: 
Undefined symbol: pthread_atfork. 
My rootfs using glibc 2.22 seem like doesn't support function pthread_atfork. 
How can i bypass this error?
Thank and best regard

**Comment by martin-frbg** [comment]
Sounds like you are loading an OpenBLAS that has been compiled with pthread-based multithreading support and need to load libpthread as well.

**Comment by brada4** [comment]
If you can not get threading libraries right (that symbol is in -lpthread) you can always resort to a single-threaded OpenBLAS

**Comment by martin-frbg** [comment]
@phuclb1 did you manage to get it working or would you like further assistance ?
