### ISSUE TITLE
Crosscompile (Android):no such file sgemm_kernel.o

### ISSUE THREAD

**Issue by xsacha** [xianyi/OpenBLAS#1251]
Can't figure out how to compile this thing.
Version: Latest 0.2.20 as well as 0.2.19

Using android clang with the following make line:
make NO_SHARED=1 TARGET=ARMV8 BINARY=64 HOSTCC=gcc CROSS=1 NOFORTRAN=1 ONLY_CBLAS=1 CC=/home/sacha/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang AR=/home/sacha/Android/Sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar CFLAGS="-funwind-tables -no-canonical-prefixes -D__ANDROID_API__=21 -fexceptions -O3 -DNDEBUG"

Error:
1 warning generated.
../kernel/x86_64/../generic/zimatcopy_rnc.c:37:15: warning: unused variable 'bptr' [-Wunused-variable]
        FLOAT *aptr,*bptr;
                     ^
1 warning generated.
/home/sacha/Android/Sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar: sgemm_kernel.o: No such file or directory
make[4]: *** [../Makefile.tail:40: libs] Error 1
make[3]: *** [Makefile:133: libs] Error 1
make[2]: *** [CMakeFiles/OpenBLAS.dir/build.make:115: OpenBLAS-prefix/src/OpenBLAS-stamp/OpenBLAS-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/OpenBLAS.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by brada4** [comment]
Can you post (attach) full build log? Unused variable that gets optimized away does not cause compiled object to disappear.

**Comment by martin-frbg** [comment]
Did both versions fail in the same way ? With 0.2.19 I think there were a few inline assembly instructions that the clang from the ndk did not like (though that may have affected the ARMV7 code only).

**Comment by xsacha** [comment]
Both failed in the same way.
I don't think this object file was ever compiled. Don't have a lot output on me right now but assumed someone would know the cause as this happens on every machine I have tried with just the make line shown in the wiki.
I tried adding more options (as shown) just in case but to no avail.

**Comment by ashwinyes** [comment]
I dont think this is related to OpenBLAS. I think proper flags are not passed to clang.

When cross-compiling, I believe clang requires a target triplet to properly cross-compile. Otherwise I think it will compile only for the host architecture. 

Below was the commands that I used to compile for armv7 (notice the -target arm-linux-androideabi option being passed). I am not able to figure the equivalent for armv8. If I get it, I will post it here.

Meanwhile @xsacha can try himself.


export NDK_ROOT=/path/to/ndk-bundle
export LDFLAGS="-L${NDK_ROOT}/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x"
export FLAGS="-target arm-linux-androideabi -marm -mfpu=vfp -mfloat-abi=softfp --sysroot ${NDK_ROOT}/platforms/android-23/arch-arm"

#OpenBLAS Compile
make TARGET=ARMV7 NO_LAPACK=1 USE_THREAD=0 AR=ar CC="clang ${FLAGS}" HOSTCC=gcc ONLY_CBLAS=1 -j4

**Comment by xsacha** [comment]
Thanks. I will test that out and update wiki if I have success.

**Comment by brada4** [comment]
It has to be develop version in place of 0.2.20, later is likely to fail without glibc

**Comment by ashwinyes** [comment]
Figured out the steps for aarch64. 

```
export NDK_ROOT=/path/to/ndk-bundle/

# Export PATH to contain directories of clang and aarch64-linux-android-ld
export PATH=${NDK_ROOT}/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/:${NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH

# Setup LDFLAGS so that loader can find libgcc and pass -lm for sqrt
export LDFLAGS="-L${NDK_ROOT}/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x -lm"

# Setup the clang cross compile options
export TARGET_TRIPLET="-target aarch64-linux-android"
export SYSROOT_OPTION="--sysroot ${NDK_ROOT}/platforms/android-23/arch-arm64"

# Compile
make TARGET=ARMV8 NO_LAPACK=1 USE_THREAD=0 AR=ar CC="clang ${TARGET_TRIPLET} ${SYSROOT_OPTION}"  HOSTCC=gcc ONLY_CBLAS=1 -j4
```

Let me know whether the above works for you. 

Also suggest you to also try TARGET=CORTEXA57 as it has much better optimized implementations than TARGET=ARMV8.

**Comment by xsacha** [comment]
Some of the devices targeted would be cortexa53. I am guessing that wouldn't work with TARGET=CORTEX-A57?

**Comment by ashwinyes** [comment]
The ISA is same for cortexa57 and cortexa53. Only internal pipelines are different.

So it will work.

Also please note its "TARGET=CORTEXA57" (No hyphen)

**Comment by xsacha** [comment]
So is there a reason not to use cortexa57?

By the way, I get this error now with the above:
ld: unknown option: --sysroot=/Users/sacha/Library/Android/sdk/ndk-bundle/platforms/android-26/arch-arm64
Note: I haven't put any equals sign in there, it looks like yours. It is just finding the wrong ld.

**Comment by ashwinyes** [comment]
>> ld: unknown option: --sysroot=/Users/sacha/Library/Android/sdk/ndk-bundle/platforms/android-26/arch-arm64

There should not be "=" after --sysroot. 

Please follow the steps properly.

**Comment by xsacha** [comment]
Mine is:
export SYSROOT_OPTION="--sysroot ${ANDROID_NDK}/platforms/android-26/arch-arm64"

My host system does not support the option --sysroot, so relying on host doesn't work.

Is there a way to override the LD being used in Makefile?

**Comment by martin-frbg** [comment]
Should not be able to find the "wrong" (non-ndk) ld if the ndk location precedes the system paths in PATH.. could it be that there is something wrong with the value of ANDROID_NDK ? Perhaps the "="
between `sysroot` and the start of the path comes from there, if a set or export command went slightly wrong ?

**Comment by xsacha** [comment]
I have it working with a host LD that support --sysroot:

 OpenBLAS build complete. (CBLAS)

  OS               ... Android             
  Architecture     ... arm64               
  BINARY           ... 64bit                 
  C compiler       ... CLANG  (command line : /home/sacha/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target aarch64-none-linux-android --sysroot /home/sacha/Android/Sdk/ndk-bundle/platforms/android-21/arch-arm64)
  Library Name     ... libopenblas_armv8p-r0.2.20.a (Multi threaded; Max num-threads is 12)

Thanks

I will update wiki later

**Comment by ashwinyes** [comment]
Know this issue is closed.  But the error you might be getting will be becuase of this.

**-target aarch64-none-linux-android**
clang will look for **aarch64-none-linux-android-ld** and will not find it in the ndk paths.

Try giving **-target aarch64-linux-android** as **aarch64-linux-android-ld** is present in the ndk paths (atleast its present in my ndk).
