### ISSUE TITLE
Building v0.2.20 fails on non-glibc systems

### ISSUE THREAD

**Issue by pbregener** [xianyi/OpenBLAS#1252]
Building OpenBLAS 0.2.20 fails on non-glibc systems, due to unsafe use of the `__GLIBC_PREREQ` preprocessor macro. Will there be a patch release soon or should downstream maintainers patch this?

**Comment by brada4** [comment]
It is #1247 that reverts offending change

**Comment by martin-frbg** [comment]
Master branch has the problematic change already reverted in anticipation of a quick interim release,
current develop branch has a **partially** fixed version of the intended functionality (**that still breaks when compiled with NO_AFFINITY=1, hopefully fixed for good in a few hours**)

**Comment by brada4** [comment]
I think it is more to @xianyi if he intends 0.2.21 tomorrow....

**Comment by martin-frbg** [comment]
Inadvertently closed with my PR for develop - reopening until 0.2.21 is out.

**Comment by martin-frbg** [comment]
Guess we can skip 0.2.21 now as it would no longer be a "quick fix" after six months have passed, but hopefully 0.3.0 can be released "very soon now".
