### ISSUE TITLE
Windows single threaded version compiled with mingw64 does not work

### ISSUE THREAD

**Issue by seechuenteck** [xianyi/OpenBLAS#1253]
I have used 'make USE_THREAD=0 USE_OPENMP=0' on 0.2.19 & 0.2.20 & compiled on mingw64 using msys2 & it does not work. Compiling using 'make' works fine on windows.

**Comment by martin-frbg** [comment]
How does "it does not work" manifest itself ? Do you get errors while compiling, or does the resulting library fail in any way ?

**Comment by brada4** [comment]
Did you run 'make clean' between builds with different options?

**Comment by seechuenteck** [comment]
Yes, I did a clean build. No compliation error. The program crashes when runned. In unix it is ok. 

In addition, when I compiled openblas  on mingw64 using 'make' & then runned using SET "OPENBLAS_NUM_THREADS=1", the program crashes. However, "OPENBLAS_NUM_THREADS=2" works fine.

**Comment by martin-frbg** [comment]
Which version of mingw, and did you specify any other options apart from USE_THREAD and USE_OPENMP ?

**Comment by seechuenteck** [comment]
I have compiled using mSYS2. The version was mingw-w64-gcc 7.1.0 (x86_64). As described eariler, using 'make' & setting "OPENBLAS_NUM_THREADS=1", the program crashes. However, "OPENBLAS_NUM_THREADS=2" works fine.

**Comment by martin-frbg** [comment]
Can you tell if it is a specific function call that crashes ? (We do not know what your program is or does)

**Comment by seechuenteck** [comment]
The single thread version on win hangs when dpotrf_(..) is called. Openblas is compiled on mingw64 as a dll & linked to program in msvc. > 1 thread works fine.

**Comment by brada4** [comment]
Can you check with a debugger where exactly it hung?
Like short backtrace of calls (with arguments) and disasm around IP, and module file layout in RAM?
trmv called behind the scenes was corrected after 0.2.20 - can you try develop  branch?
