### ISSUE TITLE
OpenBLAS has issues solving triangular matrices on win32

### ISSUE THREAD

**Issue by ghost** [xianyi/OpenBLAS#1270]
Using the 32 bit openblas causes timeouts while running the scipy tests:

**Comment by ghost** [comment]
https://ci.appveyor.com/project/scipy/scipy/build/1.0.40/job/7vqlq835677r4xde

**Comment by martin-frbg** [comment]
Do I read that correctly - you are using a binary distribution of 0.2.19 from some third party site (which could be one of the sourceforge mirrors sites, but then again could be something else) ? Could you retest with the current "develop" snapshot which has a bunch of fixes vs. 0.2.19 (or at least build 0.2.19 yourself on your platform to see if it passes the built-in tests) ? In any case I guess a minimal example run on a well-defined system would be preferable to a big unedited dump from an appveyor vm.

**Comment by ghost** [comment]
That was built 12 days ago: https://github.com/scipy/scipy/pull/7616#issuecomment-318169023

**Comment by ghost** [comment]
>In any case I guess a minimal example run on a well-defined system would be preferable to a big unedited dump from an appveyor vm.

Is there any way to turn on debug output?

**Comment by ghost** [comment]
excuse me; the URL was not apparently correct. Retrying with 2.20 now.

**Comment by martin-frbg** [comment]
not sure if 0.2.20 will build in your environment (depending on how and where you build - a cross-compile on linux like the binaries provided on sourceforge will probably go okay. the issue is a botched commit that breaks things on non-glibc systems, waiting for xianyi to release 0.2.21) which is why I suggested taking a snapshot of "develop" (easily done by clicking on the green "Clone or download" button on the "Code" tab here). Normal build from source should run a few tests at the end automatically (though as a Linux guy I am not completely sure it does this on Windows as well.

**Comment by martin-frbg** [comment]
Thanks for the link to the scipy issue. From reading that, it seems your tests were (at least at some point in the history of that PR) already done with 0.2.20 (?) 
Do you still believe the problematic behaviour is with potrf specifically ?

**Comment by ghost** [comment]
> Thanks for the link to the scipy issue. From reading that, it seems your tests were (at least at some point in the history of that PR) already done with 0.2.20 (?)

That's what I thought, but HEAD had 2.19. I updated to 2.20 just now.

> Do you still believe the problematic behaviour is with potrf specifically ?

That is my suspicion; @carlkl used a completely different build method and still had issues with OpenBLAS on win32 but not win_amd64. Of course it would be helpful to get more debug output in order to understand what is happening.

**Comment by ghost** [comment]
> That is my suspicion; @carlkl used a completely different build method

Specifically he used cross compiling with gcc rather than building with MSVC.

**Comment by martin-frbg** [comment]
Cross compiling with gcc will currently get you the hand-optimized assembly functions (which use inline assembly and AT&T notation that MSVC does not support), building with MSVC will use generic C implementations instead (which are possibly still a bit faster than the netlib reference implementation).
Latest commits to "develop" allow compiling with clang which supports the optimized assembly (but will need a windows flang compiler for completeness)

**Comment by brada4** [comment]
Specifically what lapack is imported by arpack?

**Comment by ghost** [comment]
> Specifically what lapack is imported by arpack?

Lapack and BLAS both come from OpenBLAS.

**Comment by ghost** [comment]
https://ci.appveyor.com/project/scipy/scipy/build/1.0.44/job/wix716oq76ft44r4

Looks like we still have issues:

```
  File "C:\Python36\lib\site-packages\scipy\optimize\tests\test_trustregion.py", line 76, in test_solver_concordance
    options={'return_all': True})
  File "C:\Python36\lib\site-packages\scipy\optimize\_minimize.py", line 486, in minimize
    callback=callback, **options)
  File "C:\Python36\lib\site-packages\scipy\optimize\_trustregion_exact.py", line 43, in _minimize_trustregion_exact
    **trust_region_options)
  File "C:\Python36\lib\site-packages\scipy\optimize\_trustregion.py", line 184, in _minimize_trust_region
    p, hits_boundary = m.solve(trust_radius)
  File "C:\Python36\lib\site-packages\scipy\optimize\_trustregion_exact.py", line 418, in solve
    delta, v = singular_leading_submatrix(H, U, info)
  File "C:\Python36\lib\site-packages\scipy\optimize\_trustregion_exact.py", line 185, in singular_leading_submatrix
    return delta, v
+++++++++++++++++++++++++++++++++++ Timeout ++++++++++++++++++++++++++++++++++++
[gw3] node down: Not properly terminated
fReplacing crashed slave gw3
...................F....F..........x................................................
```

It's not to difficult to reproduce; just download and install python 32 bit, install the wheel from appveyor and run the test. I can also instrument this if you want, just tell me what tooling I need to use.

**Comment by ghost** [comment]
>  (but will need a windows flang compiler for completeness)

Yeah, I actually opened an issue on flang for that; if anyone has time, I would be greatly appreciative.

**Comment by brada4** [comment]
Sure, and your binary numpy too, ten times.
Some backtrace would be nice....

**Comment by ghost** [comment]
> Some backtrace would be nice....
> I can also instrument this if you want, just tell me what tooling I need to use.

Sorry but I am not so familiar with debugging OpenBLAS. I am happy to provide a backtrace but I need assistance here.

**Comment by ghost** [comment]
The problem that I don't know how to debug an MSVC lib that has called into a gcc lib.

**Comment by ghost** [comment]
@matthew-brett Perhaps you would be better at obtaining the backtrace?

**Comment by matthew-brett** [comment]
The OpenBLAS build is with a slightly aged Mingw variant over at https://anaconda.org/carlkl/mingwpy.  See: https://mingwpy.github.io.  The build runs on Windows (not a cross-compile).

I've just set off a build from OpenBLAS master, in case that's useful:

* https://github.com/matthew-brett/build-openblas/commit/269689a02d41f2c859f08342f8cc76e35dfcfdac
* https://ci.appveyor.com/project/matthew-brett/build-openblas/build/1.0.76

**Comment by matthew-brett** [comment]
@xoviat - sadly I'm not experienced with this either.

**Comment by brada4** [comment]
Excuse me? You pull binary numpy linked against unknown BLAS and say that specifically OpenBLAS is at fault. Without backtrace that sadly goes nowhere.

**Comment by ghost** [comment]
Numpy is not being called here. We are calling OpenBLAS directly.

**Comment by ghost** [comment]
Numpy is only used for numpy.distutils.

**Comment by ghost** [comment]
> Without backtrace that sadly goes nowhere.

I agree that this impossible to solve without a backtrace. How can I do this?

**Comment by brada4** [comment]
Usually you get debugger next to compiler.

**Comment by ghost** [comment]
My guess is that this is going to be undebuggable:

MSVC EXE (python) ==> MSVC DLL (*.pyd) ==> gcc DLL (OpenBLAS)

**Comment by matthew-brett** [comment]
Just to check we're on the same page:

* We're reporting some crashes, and some numerical _test failures_ with the Scipy tests when linking Scipy Fortran code against OpenBLAS.
* OpenBLAS is being built with a reproducible build on Appveyor using (a version of) gcc mingw-w64, linking against MSVCRT - links to the build above;
* Numpy is being built with another reproducible build on Appveyor, using the OpenBLAS from the step above, using MSVC as a C compiler;
* Scipy is being built with a reproducible build on Appveyor, using the OpenBLAS above, using MSVC as s C compiler, and mingw-w64 gfortran as a Fortran compiler.

Using this same rig, all running on 64-bit, we get no test failures or crashes.

**Comment by brada4** [comment]
Can you break into frozen process with a debugger? Is it reproducable?

**Comment by martin-frbg** [comment]
I think what would be ideal is a fortran test case linked against OpenBLAS with no numpy/scipy involved at all. This should also eliminate any risk of a conflict between mingw and msvc runtime libraries.
(Or I guess just the input to potrf would suffice for building such a test case - but wading through a big appveyor log and scipy issue thread is a bit strenuous if done after regular work hours. Also do you have any indication what OpenBLAS thinks it is running on (CPU type) in the failing appveyor tests. (May be its in there somewhere but I missed it). 32bit windows probably sees less testing nowadays than the other platforms. Any chance to run the test on some local win32 system rather than appveyor virtual-whatever ?

**Comment by carlkl** [comment]
I also got identical scipy errors on 32bit with OpenBLAS-0.2.19, OpenBLAS-0.2.20 as well as OpenBLAS-develop. I also made tests with different OPENBLAS_CORETYPE settings. However, I still didn't dig very deep into these errors right now.

For the interested: recent 32bit OpenBLAS binaries with debug informations can be found here:
[libopenblas-v0.2.20-15-g1e9247c_win32_debug.7z](http://fda027ea07bdfccae9da-8ba14c47c99aef97f78f6f79b7427909.r53.cf2.rackcdn.com/libopenblas-v0.2.20-15-g1e9247c_win32_debug.7z)
The name of the DLL is `libopenblas_v0.2.20_mingwpy.dll`, so the DLL can be used as a drop-in replacement for the libopenblas DLL with identical name inside @matthew-brett's numpy builds.

**Comment by brada4** [comment]
Can you reduce test case to few lines of python maximum? Like something fitting in a single page.
It does not even tell what was last that crashed slave did before crashing....
If you dont tell which function is called out of your provided or openblas-provided DLL it is hard to tell between 200 exported functions which one is wrong....
PS i dont have windows, some say x64dbg can parse both mingw and pdb symbols.

**Comment by carlkl** [comment]
@pv created a testcase: https://github.com/scipy/scipy/pull/7616#issuecomment-320892300
results: https://github.com/scipy/scipy/pull/7616#issuecomment-321028819
as well as a list of failing Lapack functions:

- dsygvd
- dsygvx
- dsygv
- chegvd
- chegvx
- chegv

**Comment by pv** [comment]
More easily copypastable test case https://gist.github.com/pv/d5939656dcc0e36e0b66f4a4e7f1c6ba (copying from the github comment drops newlines...)

**Comment by carlkl** [comment]
this testcase compiled with debug symbols:
[testdpotr_test_gh_2691.exe](http://fda027ea07bdfccae9da-8ba14c47c99aef97f78f6f79b7427909.r53.cf2.rackcdn.com/testdpotr_test_gh_2691.exe)   (28,2Mb !)

**Comment by carlkl** [comment]
As all failing routines are Lapack Fortran functions I will recompile OpenBLAS with a different gfortran version and test again. Due to time constraints this may take some time.

**Comment by brada4** [comment]
Script sample looks reasonable, i will get off the beach next week and try it out (on linux)
We are not here with dll forensics, you could try with x64dbg on your own system, at least call chain best with arguments leading to crash(es). Small minimal screenshot is ok. Thanks already.

**Comment by pv** [comment]
I'm not sure the claims above about crashes are accurate -- if I'm not wrong it's only wrong results that have been verified. The "crashes" in the tests are only timeouts, probably due to infinite (or nearly enough so) loops entered due to garbage output. Moreover, note that it passes on win64, so it may be specific to the win32 platform, or to the specific toolchain, or even the specific builds.

**Comment by ghost** [comment]
Yeah, I was wrong about the crashes. My guess would be an overflow.

**Comment by brada4** [comment]
Can you try develop version? @martin-frbg recently commited some crash fix of the type.

**Comment by ghost** [comment]
I think we just tried that.

**Comment by ghost** [comment]
I think we should just wait until you get back from vacation, as that will be the most time-efficient for everyone.

**Comment by brada4** [comment]
Thanks for sample. It is ennough for now.

**Comment by brada4** [comment]
Can you get appveyor vm cpuid? It is in variables.
Sample does not crash android-gnuroot-debian-armv7.

**Comment by ghost** [comment]
@matthew-brett Rebuilt HEAD with different compiler arguments and that resolved the problems. I am not sure whether you want to proceed with this issue.

**Comment by brada4** [comment]
test sample can stay in a closed issue. Can you share problematic args?

**Comment by martin-frbg** [comment]
I'm wondering if #1271 could be related, i.e. xianyi's prebuilt windows binaries on sourceforge may be equally affected if it is a compiler version or options issue.

**Comment by carlkl** [comment]
See https://github.com/scipy/scipy/pull/7616#issuecomment-321371519. This error did show up on 32bit mingw-w64 based on gcc-5.3. Other releases of mingw-w64 works well. This needs definitely more examinations.

**Comment by matthew-brett** [comment]
In [this build](https://ci.appveyor.com/project/matthew-brett/openblas-tests/build/1.0.8) I built commit 5f998ef with current mingw-w64 32-bit toolchain, and we don't see any errors for @pv's [gfortran test case](https://github.com/matthew-brett/openblas-tests/blob/master/test.f90) -
 and all the other Scipy crashes and failures [go away](https://ci.appveyor.com/project/scipy/scipy/build/1.0.88/job/jawk9bxg04o50q14).  On my [previous mingwpy build](https://ci.appveyor.com/project/matthew-brett/build-openblas/build/job/yfkl0jr0u9vjpjnb) I built the same commit, with @carlkl's Mingwpy toolchain, to get the [failure on the test function](https://ci.appveyor.com/project/matthew-brett/openblas-tests/build/1.0.2#L159) as well as the failures you've seen in the logs above.

**Comment by martin-frbg** [comment]
#1253 is another one that could be related, again dpotrf is implicated but that compilation was with mingw-w64 7.1.0 which appears to be what your successful build uses. Building without thread support
probably is a wholly different use case than yours however.

**Comment by brada4** [comment]
While betting on buffer sizing that sounds feasible theory.

**Comment by martin-frbg** [comment]
Thinking of #1141 here ? This definitely needs looking into.

**Comment by carlkl** [comment]
It seems that *newer* mingw-w64 versions can build Lapack without this error. This could be either an gcc bug or more likely a bug with mingw-w64 itself. Compiling OpenBLAS with a recent version of mingw-w64 and testing on this bugs seems to be a reasonable workaround right now.

**Comment by brada4** [comment]
@martin-frbg it needs backtrace and/or coretype, currently it is in state of trying to induce same testcase problem for whole day.

**Comment by carlkl** [comment]
For comparison I compiled openblas_v0.2.20_1e9247c (develop) with mingw-build gcc-7.1 for 32bit. The dpotrf testcase https://github.com/xianyi/OpenBLAS/issues/1270#issuecomment-321391585 now runs without error. And all 32bit scipy wheels compiled with mingwpy also runs without errors and failures. (these builds are different from that created by @xoviat and mentioned in the comment above).

It seems, that mingw-w64 toolchains based on gcc-5.3 and gcc-4.9 has problems with Lapack.

**Comment by brada4** [comment]
It should be all fortran77 from netlib
Can you build openblas without lapack and then netlib produce with `-lopenblas` ?

**Comment by carlkl** [comment]
The mingw-w64 based builds mentioned in https://github.com/scipy/scipy/pull/7616#issuecomment-321803978 do not exhibit this erroneous behaviour. Is there a need to experiment with netlib Lapack as well? I may find some time this weekend to do some debugging the faulty build, lets see.

**Comment by brada4** [comment]
we have almost no windows. Just to blame original build scripts or small adjustments made for building w openblas, or well windows compilers you use.

**Comment by carlkl** [comment]
OpenBLAS uses `interface/lapack/potrf.c` (out-of-source) instead of original lapack's `dpotrf.f`. Using `dpotrf.f` instead, I have no problems regardless what version of mingw-w64 I'm using.

**Comment by martin-frbg** [comment]
Guess we could add something like 
```
#if defined(OS_WINDOWS) && (defined(__MINGW32__) && <gcc version below 7.1>)
(nothing)
#else 
(code overriding *potrf.f)
#endif
```
in interface/lapack/potrf.c to work around the apparent miscompilation on affected platforms ?

**Comment by brada4** [comment]
Actually all logs come from -march=native builds. Probably omitting all -O99 series would complete the build without a single problem

**Comment by martin-frbg** [comment]
I take it you are suggesting that compiling interface/lapack/potrf.c with -O0 instead of the default -O2 would solve the problem with older mingw versions ? Not sure how easy it would be to cater for that in the Makefiles (not sure if -march=native is actually what they are using or intending to use, if my understanding is correct they are preparing a distribution package of some sort).

**Comment by brada4** [comment]
-march=pentium4 -msse2 -fpmath=sse ...
It is miscompilation by C compiler, not something to work around. Since build logs/options are not around for each and every 'build' and 'gcc version' i would take gcc7 claim with a big grain of salt.

**Comment by martin-frbg** [comment]
Once again I am not sure I can follow your cryptic messages. My suggestion was to omit compilation of the problematic potrf interface if there is reason to believe the compiler is not up to that task.

**Comment by brada4** [comment]
It compiles just fine with gcc 4.6 included with windows rtools (compilers for r packages).
I am quite certain aggressive/unpopolar compiler options lead to miscompilation in this case.

**Comment by carlkl** [comment]
I'm not going to create a PR to OpenBLAS with a patch to something without further diagnosis and debugging. However, using mingw-w64 with gcc-7.1 seems to be a workaround to this issue right now,

**Comment by brada4** [comment]
You dont even have exact compiler options for each failed case.
Your PR will be wrong, as old gcc can compile OpenBLAS without any problems. Please find problematic compiler option and report a compiler bug first.

**Comment by martin-frbg** [comment]
@brada4 alienating developers of other projects helps noone. Even if your gcc 4.6 from rtools happens to be identical to the mingw-w64 build of the same version number this does nothing to refute the claim that at least the 4.9 and 5.3 versions miscompile potrf.c . If we really want to get to the bottom of this I guess we would need the intermediate assembler (gcc -S) output for this file from both "good" and "bad" compilers __and__ someone who is capable of spotting the _relevant_ differences. 
For now, adding a note to the wiki (and perhaps ensuring that any future pre-compiled binaries for win32 made available on the project page at sourceforge are built with a recent gcc cross-compiler "just in case the problem carries over to cross-compilations") may be sufficient ?

**Comment by brada4** [comment]
I dont have compiler on windows. I can try to cross-compile with old and new crosscompiler and run test case on 64bit windows...
My speculation is based on assumption that typical distribution compiler option sets (-O2 -march=early-i686 -msome-memory-protector ) are million times better tested in GCC than -march=better-cpu

**Comment by martin-frbg** [comment]
Please note that this issue appears to be specifically about mingw-w64 **on** Windows **32bit** then.

**Comment by brada4** [comment]
Yes, yes, 32bit dll+exe running on 64bit windows.
It is very important to have it running at top quality since all alternatives are fading away.

**Comment by carlkl** [comment]
I'm willing to dig into this. However, This takes some time as there are some topics with higher priority for me right now.

**Comment by brada4** [comment]
You are not alone. As a minimum find a linux distribution with good and recent gcc that produces production quality 32bit DLL

**Comment by martin-frbg** [comment]
Have there been any new insights since then ? I tried to track any seemingly related numpy/scipy issues but as far as I could tell the discussions there seem to have moved on to inadvertent use of the 80bit extended precision Intel FPU mode causing problems in cdflib. So should we add a warning in the wiki to use at least version 7.1 of the mingw gcc for 32bit builds on Windows, or are there any indications that the problem may be bigger and in OpenBLAS itself ?

**Comment by ghost** [comment]
It turns out that we were compiling with a non-standard toolchain called mingwpy. We decided to drop that toolchain in favor of vanilla mingw. That seemed to resolve the problems.
