### ISSUE TITLE
problem when using LAPACKE_dpotrf with dynamic array

### ISSUE THREAD

**Issue by yhuo2017** [xianyi/OpenBLAS#1271]
Hello,

I'm trying to use the LAPACK Cholesky decomposition function. When I use static array as follows it works fine:
double a[9] = { 1.0, .6, .3, .6, 1., .5, .3, .5, 1 };
int info = LAPACKE_dpotrf(LAPACK_ROW_MAJOR, 'L', 3, a, 3);

However, when I use dynamic array
int n=59;
double * a = new double[n*n];
//assign values to a
int info = LAPACKE_dpotrf(LAPACK_ROW_MAJOR, 'L', n, a, n);

It's complaining about the 5th parameter, which is the LDA. The result stored in a doesn't make sense.
I wonder if anyone had this issue.
Thanks in advance.

**Comment by brada4** [comment]
What should be cholesky factorisation of uninitialised memory (typically all zeroes)?

**Comment by martin-frbg** [comment]
I assume the "//assign values to a" is just a placeholder for brevity, but perhaps it would help to print the contents of the array before the dpotrf call to make sure that the allocation and assignment worked (could be a memory management error much earlier in the code that leads to undefined behaviour here) . Perhaps it would also help to know if the same error occurs when the program is linked against the standard netlib lapack.
(Also what is it complaining about - usually the routine will abort without producing a result in such cases, so what is stored in "a" would probably still correspond to the input.)

**Comment by yhuo2017** [comment]
Thanks for the reply.
Yes,  the "//assign values to a" is just a placeholder for brevity. I printed out the array, and the allocation and assignment works fine. The error is: "Wrong parameter 5 in LAPACKE_dpotrf_work". and info is -5.
Yes, after running the function, "a" is still the same as the input (the lower triangle is not overwritten by the Cholesky L matrix), which means operation is aborted.

This piece of code is embedded in some class. If I try to do something similar in a standalone main() function, I don't have this issue. Guess there's some memory management error, but I don't know what it is.

**Comment by martin-frbg** [comment]
If you are running this code on some form of Linux you could try using valgrind to check if memory management goes wrong somewhere earlier. As noted above you could also try with plain netlib lapack/lapacke in case it is some other function in OpenBLAS that has unintended side effects. Which version of OpenBLAS and what CPU and operating system is this all about by the way?

**Comment by yhuo2017** [comment]
I'm using the binary of: OpenBLAS-v0.2.14-Win64-int64
CPU: Intel(R) Xeon(R) CPU E5-1650 

Am I able to download netlib lapack/lapacke from the same sourceforge page as openBLAS? (sourceforge is forbidden in my workplace). 
Thanks.

**Comment by martin-frbg** [comment]
0.2.14 is quite old, two years actually, there should be prebuilt binaries of at least 0.2.19 available (though I am not sure if these include a Win64-int64 version). Reference netlib version is on netlib.org,
which links to http://icl.cs.utk.edu/lapack-for-windows/lapack/ for the windows binaries.
Pity about sourceforge being blocked, but I know there was some dodgy behaviour with adware/malware getting bundled with unsuspecting projects under their previous owner.

**Comment by yhuo2017** [comment]
Hi Martin,
I switched to the netlib lapacke you referred to, and it works! So it might be a OpenBLAS issue. 
BTW, I tried 0.2.19 Win32, and it has the same problem.
Thanks a lot.

**Comment by martin-frbg** [comment]
Thanks for checking. This will be hard to track down if the problem is caused by some other OpenBLAS function that got called sometime before LAPACKE_dpotrf(_work) - would you happen to know which
function that could be ?

**Comment by brada4** [comment]
There are some mentions of dpotrf in netlib release notes during last years. Probably later LAPACK than from 2014 will have problem fixed.

**Comment by yhuo2017** [comment]
Martin, I'm not using any other OpenBLAS function before LAPACKE_dpotrf.
brada4, OpenBLAS-v0.2.19-Win64-int32 was released in 2016. So it should include LAPACK fixes from 2014?

**Comment by martin-frbg** [comment]
0.2.19 at least had netlib 3.6.0 already (0.2.20/0.2.21 has 3.7.0, but there are no windows binaries yet) so it would have to be a recent fix. (On the other hand, seeing that no other lapack or blas function gets called before the dpotrf does make it likely that the problem is in the dpotrf code itself. I notice that OpenBLAS seems to supplant the potrf source it inherits from netlib with an own, parallelized version - assuming that one gets used on Windows at all.)

**Comment by martin-frbg** [comment]
Neither lapacke_dpotrf.c nor lapacke_dpotrf_work.c changed significantly in the past two years, and at the time the _work function gets called obviously none of the actual potrf code has run. So perhaps this is some more general ABI problem calling the provided (probably mingw-compiled) library from a (possibly) MSVC-compiled main program. (Needs input from someone more familiar with the windows builds I guess)

**Comment by carlkl** [comment]
This could be a problem with mingw-w64: see: https://github.com/xianyi/OpenBLAS/issues/1270#issuecomment-321372302 and https://github.com/scipy/scipy/pull/7616#issuecomment-321371519

**Comment by yhuo2017** [comment]
When using netlib lapacke as suggested by Martin (which works), I used the same copy of mingw64 dll files. 
I even renamed libgfortran-3.dll as libgfortran_64-3.dll since I don't have libgfortran_64-3.dll. It didn't cause problem though.

**Comment by carlkl** [comment]
@yhuo2017, can you run `gcc -v` on the command line and show the output here? It may be helpful to know the mingw-w64 version you are using.
