### ISSUE TITLE
building OpenBLAS 0.2.20 with LAPACK 3.7.1 fails with unresolved symbols

### ISSUE THREAD

**Issue by boegel** [xianyi/OpenBLAS#1273]
We usually building OpenBLAS with an official release of LAPACK included, rather than using the `lapack-netlib` directory as is.

This approach, where we basically just replace `lapack-netlib` with the unpacked source tarball for the (usually latest) LAPACK release, has worked fine in the past (e.g. with OpenBLAS 0.2.19 & LAPACK 3.7.0, or OpenBLAS 0.2.18 & LAPACK 3.6.1).

When trying to build the latest OpenBLAS 0.2.20 with the latest LAPACK 3.7.1, I'm running into problems however:

```
make[1]: Entering directory `/tmp/OpenBLAS/0.2.20/GCC-6.4.0-2.28-LAPACK-3.7.1/OpenBLAS-0.2.20/exports'
make[1]: warning: -jN forced in submake: disabling jobserver mode.
perl ./gensymbol linktest  x86_64 _ 0 0 0 0 0 0 "" "" 1 > linktest.c
gcc -O2 -march=native -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=24 -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I. -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=24 -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I.. -L/prefix/software/GCCcore/6.4.0/lib64 -L/prefix/software/GCCcore/6.4.0/lib -shared -o ../libopenblas_haswellp-r0.2.20.so \
-Wl,--whole-archive ../libopenblas_haswellp-r0.2.20.a -Wl,--no-whole-archive \
-Wl,-soname,libopenblas.so.0 -lm -lpthread -lgfortran -lm -lpthread -lgfortran
gcc -O2 -march=native -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=24 -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I. -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=24 -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I.. -L/prefix/software/GCCcore/6.4.0/lib64 -L/prefix/software/GCCcore/6.4.0/lib -w -o linktest linktest.c ../libopenblas_haswellp-r0.2.20.so -L/prefix/software/GCCcore/6.4.0/bin/../lib/gcc/x86_64-pc-linux-gnu/6.4.0 -L/prefix/software/GCCcore/6.4.0/bin/../lib/gcc -L/prefix/software/GCCcore/6.4.0/lib64/../lib64 -L/prefix/software/GCCcore/6.4.0/lib/../lib64 -L/prefix/software/GCCcore/6.4.0/bin/../lib/gcc/x86_64-pc-linux-gnu/6.4.0/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/prefix/software/binutils/2.28-GCCcore-6.4.0/lib -L/prefix/software/GCCcore/6.4.0/lib64 -L/prefix/software/GCCcore/6.4.0/lib -L/prefix/software/GCCcore/6.4.0/bin/../lib/gcc/x86_64-pc-linux-gnu/6.4.0/../../..  -lgfortran -lm -lquadmath -lm -lc   && echo OK.
/tmp/eb-vlSJIi/ccsLO4XL.o:linktest.c:function main: error: undefined reference to 'LAPACKE_clatms'
/tmp/eb-vlSJIi/ccsLO4XL.o:linktest.c:function main: error: undefined reference to 'LAPACKE_clatms_work'
/tmp/eb-vlSJIi/ccsLO4XL.o:linktest.c:function main: error: undefined reference to 'LAPACKE_dlatms'
/tmp/eb-vlSJIi/ccsLO4XL.o:linktest.c:function main: error: undefined reference to 'LAPACKE_dlatms_work'
/tmp/eb-vlSJIi/ccsLO4XL.o:linktest.c:function main: error: undefined reference to 'LAPACKE_slatms'
/tmp/eb-vlSJIi/ccsLO4XL.o:linktest.c:function main: error: undefined reference to 'LAPACKE_slatms_work'
/tmp/eb-vlSJIi/ccsLO4XL.o:linktest.c:function main: error: undefined reference to 'LAPACKE_zlatms'
/tmp/eb-vlSJIi/ccsLO4XL.o:linktest.c:function main: error: undefined reference to 'LAPACKE_zlatms_work'
/tmp/eb-vlSJIi/ccsLO4XL.o:linktest.c:function main: error: undefined reference to 'LAPACKE_clagge'
/tmp/eb-vlSJIi/ccsLO4XL.o:linktest.c:function main: error: undefined reference to 'LAPACKE_clagge_work'
/tmp/eb-vlSJIi/ccsLO4XL.o:linktest.c:function main: error: undefined reference to 'LAPACKE_dlagge'
/tmp/eb-vlSJIi/ccsLO4XL.o:linktest.c:function main: error: undefined reference to 'LAPACKE_dlagge_work'
/tmp/eb-vlSJIi/ccsLO4XL.o:linktest.c:function main: error: undefined reference to 'LAPACKE_slagge'
/tmp/eb-vlSJIi/ccsLO4XL.o:linktest.c:function main: error: undefined reference to 'LAPACKE_slagge_work'
/tmp/eb-vlSJIi/ccsLO4XL.o:linktest.c:function main: error: undefined reference to 'LAPACKE_zlagge'
/tmp/eb-vlSJIi/ccsLO4XL.o:linktest.c:function main: error: undefined reference to 'LAPACKE_zlagge_work'
/tmp/eb-vlSJIi/ccsLO4XL.o:linktest.c:function main: error: undefined reference to 'LAPACKE_claghe'
/tmp/eb-vlSJIi/ccsLO4XL.o:linktest.c:function main: error: undefined reference to 'LAPACKE_claghe_work'
/tmp/eb-vlSJIi/ccsLO4XL.o:linktest.c:function main: error: undefined reference to 'LAPACKE_zlaghe'
/tmp/eb-vlSJIi/ccsLO4XL.o:linktest.c:function main: error: undefined reference to 'LAPACKE_zlaghe_work'
/tmp/eb-vlSJIi/ccsLO4XL.o:linktest.c:function main: error: undefined reference to 'LAPACKE_clagsy'
/tmp/eb-vlSJIi/ccsLO4XL.o:linktest.c:function main: error: undefined reference to 'LAPACKE_clagsy_work'
/tmp/eb-vlSJIi/ccsLO4XL.o:linktest.c:function main: error: undefined reference to 'LAPACKE_dlagsy'
/tmp/eb-vlSJIi/ccsLO4XL.o:linktest.c:function main: error: undefined reference to 'LAPACKE_dlagsy_work'
/tmp/eb-vlSJIi/ccsLO4XL.o:linktest.c:function main: error: undefined reference to 'LAPACKE_slagsy'
/tmp/eb-vlSJIi/ccsLO4XL.o:linktest.c:function main: error: undefined reference to 'LAPACKE_slagsy_work'
/tmp/eb-vlSJIi/ccsLO4XL.o:linktest.c:function main: error: undefined reference to 'LAPACKE_zlagsy'
/tmp/eb-vlSJIi/ccsLO4XL.o:linktest.c:function main: error: undefined reference to 'LAPACKE_zlagsy_work'
collect2: error: ld returned 1 exit status
make[1]: *** [../libopenblas_haswellp-r0.2.20.so] Error 1
make[1]: Leaving directory `/tmp/OpenBLAS/0.2.20/GCC-6.4.0-2.28-LAPACK-3.7.1/OpenBLAS-0.2.20/exports'
make: *** [shared] Error 2
```

This surprised me a bit, since the `lapack-netlib` copy included in OpenBLAS 0.2.20 is basically LAPACK 3.7.0 + a couple of backported patches on top.

Are any other changes required in order to use an official LAPACK release as a drop-in replacement for the `lapack-netlib` directory as of recent?

On the side: are there any plans for updating the shipped `lapack-netlib` to LAPACK 3.7.1?
I'm willing to try and look into this myself, is there any documentation available on the procedure to follow for this?

I noticed that an update is required to `lapack-netlib/LAPACKE/src/Makefile` to avoid build issues with mingw (cfr. #1057, #1060), but I was hoping for a more complete outlined procedure that could help?

**Comment by boegel** [comment]
Maybe @wernsaar has some comments on this, cfr. the last update to LAPACK 3.7.0 + upstream patches in #1046?

**Comment by martin-frbg** [comment]
Why would you expect a newer/different lapack to be a simple drop-in replacement, when the "new" version is very likely to come with new, deprecated or rearranged functions ? I believe the Makefile fixes you mentioned were applied upstream as well (but later superseded by a rewrite), what you are looking at now is the OpenBLAS-specific link test (in "exports) that gets run on the static library before its dynamic counterpart is built. The full build log will tell you if the missing lapacke functions were compiled at all, and perhaps also what if anything happened to them. 
There are certainly plans to update to 3.7.1 at some point (or at least I have them...), but most of the fixes in that release have already been applied in the OpenBLAS copy and it is not entirely trivial to merge a new lapack (as you are seeing for yourself). Given the current lack of available developers
(wernsaar you are trying to contact has not been seen here since january) and the number of recent issues this is probably not the top priority.

**Comment by martin-frbg** [comment]
Most likely you introduced a problem in lapack-netlib/LAPACKE/src/Makefile if/when you tried to reapply the mingw fixes - from looking at the file history in the netlib repository (apparently the netlib maintainers have not gotten around to providing a changelog for 3.7.1 yet) lapacke_clagge et al. have grown an additional interface for switching off NaN detection so depend on a new nancheck module now.
(I believe netlib nowadays relies predominantly on cmake, so maybe you actually found a bug in the netlib lapacke Makefile - I have not checked this)

**Comment by boegel** [comment]
@martin-frbg Using a LAPACK release as a drop-in replacement has worked fine before, so I don't think it's unreasonable to expect it would still work now (but maybe I'm being naive).

I literally only replaced `lapack-netlib` with an unpacked LAPACK 3.7.1 tarball, I didn't make any other changes. Since I'm building on Linux with GCC, I don't need to tweak the Makefile to split the list of objects in two different lists.

Thanks for the clarifications, I think we'll go ahead and just use the shipped LAPACK going forward.

I'm still interested in helping out with updating `lapack-netlib` to LAPACK 3.7.1, but I understand this is not top priority. Is there any write-up available on the procedure to follow for this, which (potential) changes need to be made both inside & outside of `lapack-netlib`?

**Comment by martin-frbg** [comment]
I suspect your previous drop-in replacements worked only insofar as the subset of functions already present in the older LAPACK were still accessible, but none of the additional ones would have been
available in the shared libopenblas.so at least.
There is no writeup available as far as I know, your best bet is to look at what the relevant earlier commits touched. Basically you'd need to read the netlib changelog (if/when available, or their git history) to see what is new, check that it all builds with make and cmake after replacing the lapack-netlib tree and adapt the exports/gensymbol perl script as needed. This has the list of functions that should be present in the library, and linktest.c is generated by it.
Did you check if there were any earlier error messages in your build log, if you have a LAPACKE_clatms.o somewhere under lapack-netlib/LAPACKE in your unsuccessful build, and if libopenblas.a contains any symbols named LAPACKE_clatms etc. ?

**Comment by martin-frbg** [comment]
A quick check shows several changes in the Makefiles distributed with 3.7.1. Apart from the addition of new functions and a splitting of the "make clean" target into "cleanobj" and "cleanlib" , the lapacke functions you were missing in your build have been made conditional on a LAPACKE_WITH_TMG that the OpenBLAS build system obviously does not yet know it has to define.
I will prepare a PR for updating to 3.7.1 later, possibly next week.

**Comment by brada4** [comment]
One can build openblas without builtin lapack, and then laapack/lapacke with '-lopenblas'

**Comment by martin-frbg** [comment]
FWIW of the impressive list of 780 files that differ between the current OpenBLAS snapshot of lapack-netlib and 3.7.1, the overwhelming majority are changes to the function documentations in the comments at the start of each file (additions, typo fixes, version number or year updates). We may be missing a few recent LAPACKE fixes and enhancements that were committed to netlib since May.

**Comment by martin-frbg** [comment]
PR #1366 has the ~~majority of~~ changes for updating to 3.8.0 (testers needed, ~~also cmake updates not done yet~~)
