### ISSUE TITLE
OpenBLAS + TBB

### ISSUE THREAD

**Issue by sbudenkov** [xianyi/OpenBLAS#1282]
Hi,
I want to use OpenBLAS with application that uses TBB multi-threading for parallel computation, but it is too slow in all configuration (Single-threaded, Multi-threaded, OpenMP). As I understand it is memory bottleneck, coz OpenBLAS uses the same global memory in different TBB threads. Maybe do you have any ideas?

**Comment by martin-frbg** [comment]
Can you provide some more details please - your hardware and operating system, which version of OpenBLAS you are trying to use and which BLAS/LAPACK functions (and perhaps matrix sizes) you are experiencing this slowness with ? It may also help to know which application it is (unless it is a closed source one of your own)

**Comment by brada4** [comment]
Care to mention operating system?

**Comment by sbudenkov** [comment]
It is applicable for Windows and Linux (Ubuntu), CPU is i7 (8 logical cores), 0.2.20 version. I am calling cblas_sgemm() for matrix multiplication. If I set the number of threads to 8 it is fast, but when I use TBB for parallel execution (for example, create a thread for 2 matrix rows) and single-threaded OpenBLAS it is too slow. I've reviewed code and found in memory.c OpenBLAS allocates memory array using the number of cores (threads) and uses lock/unlock for reading/writing to this memory area ... I suppose it is bottleneck, if each external thread try to use the same memory.

**Comment by sbudenkov** [comment]
Also I've observed the same problem https://github.com/xianyi/OpenBLAS/issues/1283 in valgrind.

**Comment by brada4** [comment]
Can you post full CPU name that everybody can google?

What you get is core oversubscription, I have in works omp hierarchy support.

You are not right about shared memory. you dont have NUMA in your small CPU, unless data fits in 2.5MB outer cache attached to core (with 2 hyperthreads) - base RAM is same for all.

How big is sgemm input and output?

**Comment by martin-frbg** [comment]
From my (still very limited) understanding of TBB, it is C++ only, while OpenBLAS itself is a mix of C (BLAS part, handful of re-implemented LAPACK functions) and FORTRAN (LAPACK imported from the netlib reference implementation). So my current impression is that adding proper TBB support to OpenBLAS would imply a major redesign/rewrite. _If_ a major bottleneck is actually  memory.c, perhaps building for a very low number of threads (like `make NUM_THREADS=2`) would provide an acceptable tradeoff ?

**Comment by brianborchers** [comment]
A possible issue here is that the TBB parallelism is breaking down problems into very tiny blocks so that when OpenMP is called it is having to deal with small matrices.  What are the sizes of the matrices being passed into OpenMP sgemm() calls?

**Comment by sbudenkov** [comment]
Sorry for late reply. The sizes of the matrices are small. I think your suggestion is right, because when I don't split matrix multiply using TBB, results are satisfactory.

**Comment by brianborchers** [comment]
This appears to be an example of the broader problem that occurs whenever there is parallel threading going on at multiple levels in the software without communication between the levels- If the processor appears to have 8 cores, then the top level will start 8 threads in parallel.  Later on, each thread will start 8 threads at its level, and all of a sudden you have 64 threads contending with each other.  The best solution is to use a single multithreading scheme (e.g. OpenMP) throughout the code and let higher level threads determine when lower-level threads should go single threaded.   Another possibility is to compile the lower-level code (e.g. OpenBLAS) to just always run single threaded.  A third option (often best when the lower level is BLAS and nearly all of the computational work is at the lower level) is to compile the upper-level code to run single-threaded.

**Comment by sbudenkov** [comment]
Thanks for the detailed answer. In my case, I'm using  single threaded OpenBLAS version with TBB parallelism. I think the issue can be closed.

**Comment by goplanid** [comment]
@sbudenkov Can you please tell me how did you achieve single threaded OpenBLAS with TBB parallelism?

**Comment by brada4** [comment]
@goplanid check makefile.rule - disable threading and enable locking.
