### ISSUE TITLE
Strange performance result: sgemm_itcopy taking up lots of time?

### ISSUE THREAD

**Issue by chrisics** [xianyi/OpenBLAS#1283]
I've got a strange result of a performance profile of OpenBlas, where sgemm_itcopy seems to take up most of the time?  
OpenBlas was compiled without multi-threading support. (make USE_THREAD=0)
As a result, a pure C-version was faster on Intel ! 

On Intel: (i5 6440HQ 2.6 Ghz), running on Ubuntu 16.06
     C-version             567 ms
     openBlas              1075 ms !

On Arm: (Cortex A53, 1.2 Ghz), raspberry pi 3
     C-version:           12630 ms
     openBlas             5166 ms

The call is: cblas_sgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans, M, N, K, ALPHA, A, lda, B, ldb, BETA, C, ldc);

Attached is a detail of the performance profile. (via perf record --call-graph dwarf ...)

Any ideas? Thanks.
Christophe

![screenshot-openblas-detail](https://user-images.githubusercontent.com/2297967/29610430-6908f956-87fa-11e7-8059-fe772b4c0b3c.png)

**Comment by martin-frbg** [comment]
Which version of OpenBLAS (everything before current "develop" is likely to misdetect L1 cache size on Haswell and beyond, not sure if that plays a role here), and what matrix size ?

**Comment by ashwinyes** [comment]
>> As a result, a pure C-version was faster on Intel !

Could you explain what you meant by pure C-version ??

**Comment by chrisics** [comment]
The version of OpenBlas = 0.2.20 - the release version
The size of the matrixes is M = 18, N = 128, K = 300

The pure C version is a version that doesn't use assembly or intrinsics:

void gemm_nn(int M, int N, int K, float ALPHA, float *A, int lda,   float *B, int ldb,  float *C, int ldc){
  int i,j,k;
  for(i = 0; i < M; ++i){
    for(k = 0; k < K; ++k){
      register float A_PART = ALPHA*A[i*lda+k];
      for(j = 0; j < N; ++j){
        C[i*ldc+j] += A_PART*B[k*ldb+j];
      }
    }
  }
}

**Comment by ashwinyes** [comment]
Thanks. Could you check whether your observation is correct for large sizes as well.

Lets say M=N=K=1000 ?

**Comment by chrisics** [comment]
I found the problem: (to my shame ...)

The applications is calling cblas_sgemm(CblasRowMajor, ...
and the data is organised differently then I thought: The sizes are **M=1**, N = 128, K = 128.
I need to do this differently...

Thanks for your help!

**Comment by brada4** [comment]
Secret codename is 'sgemv'

**Comment by chrisics** [comment]
Thanks, now it is as expected!

**Comment by martin-frbg** [comment]
May be a worthwile optimization to forward such calls automatically from gemm to gemv ?

**Comment by brada4** [comment]
Yes, that passed my mind too. Julia does it above blas calls, R started recently partially, rest will just gain speed...
Correction: R was swimming in chrisics's pond until release 3.4.0
