### ISSUE TITLE
OMP build should not import pthreads lib

### ISSUE THREAD

**Issue by brada4** [xianyi/OpenBLAS#1287]
It comes from c_check, where I could not figure how to conditionally get rid of it plus 2 other places where it is easily ripped or ifdef-d out.
There are few pthread_mutex_lock() in omp code paths which I can take care of (at least I am trying...)

**Comment by martin-frbg** [comment]
How so ? As I understand it, c_check (on Linux) will only #define a PTHREAD_CREATE_FUNC which in itself should be harmless. Places e.g. in driver/others/memory.c that use LOCK_COMMAND should effectively be calling either phtread_mutex_lock() or the inline blas_lock that corresponds to YIELDING depending on USE_PTHREAD_LOCK. 
If there is a bug here, perhaps it is the setting of USE_PTHREAD_LOCK regardless of USE_OPENMP in common.h when SMP is defined ?

**Comment by brada4** [comment]
-lpthread is sort of written in generated config files unconditionally.

**Comment by martin-frbg** [comment]
Seems to me that at least the opensuse-supplied libgomp _is_ dependent on libpthread (that information comes from parsing the "gcc -v ctest2.o" output in c_check so is provided by the compiler/linker actually in use)

**Comment by brada4** [comment]
Probably OMP locks are macros wrapping pthread locks.... 
I will do something about pthread API being called where it should be accessed via (in fact) OMP wrappers
