### ISSUE TITLE
OpenBLAS fails self-tests

### ISSUE THREAD

**Issue by jon-mueller** [xianyi/OpenBLAS#1291]
I'm trying to install OpenBLAS on the Linux subsystem for Windows 10, and it fails multiple self-tests.

- CPU: Intel Core i5 660K
- OS: Windows 10 with developer mode, using ubuntu on linux subsystem for windows
- Compiler: gcc 4.8.4
- Makefile.rule is attached

The results of the self-tests are attached.  As an example, see the results of DSYMV in test_results.txt .  Some of the computed results are on the order of 1e+76.  What is interesting is that the computed test results are not consistent.  For example, if I rerun the tests sometimes it will pass DSYMV and fail other tests.

Any thoughts?

[Makefile.rule.txt](https://github.com/xianyi/OpenBLAS/files/1273582/Makefile.rule.txt)
[test_results.txt](https://github.com/xianyi/OpenBLAS/files/1273583/test_results.txt)
[ctest_results.txt](https://github.com/xianyi/OpenBLAS/files/1273584/ctest_results.txt)

**Comment by brada4** [comment]
I5-660 (westmere) or I5-6600K(skylake) ?
Can you share last lines of 'make' output telling detected core type and used compiler?
Does it always fail in same exact tests or more like random?

**Comment by martin-frbg** [comment]
~~Also which version of OpenBLAS is this ?~~ 
Can you provide the complete build log (as an attachment here or uploaded to gist) please ?

**Comment by quickwritereader** [comment]
Firstly, You should provide full log and etc as guys noted above. And also try early versions of Openblas to see if the same problems exist.

"What is interesting is that the computed test results are not consistent"

It might be there left some uninitialized or not zerod variables in base blas functions on which other blas funcs depends. 
Try also debug build to see if numbers differs in exact places, too. 
Also you could run test only for unpassed ones. For example, See din3 zin3 files under ctest to make your own rules for blas3 and to check only gemm. You will easily figure how to run the wanted tests.

**Comment by jon-mueller** [comment]
- i5-660K skylake
- I've attached Makefile.conf_last.  @brada4 is that what you wanted?
- @brada4 : it does not always fail the same tests, it is more like random.
- @martin-frbg : attached
- @quickwritereader : I'll try earlier versions of Openblas and comment again.  I tried debug build with make DEBUG=1, and it still fails the self tests.  I've attached results of 6 runs of the dgemm test with the same debug build of Openblas.  Five of them failed in different ways while one of them passed.


[ctest_results1.txt](https://github.com/xianyi/OpenBLAS/files/1274714/ctest_results1.txt)
[ctest_results2.txt](https://github.com/xianyi/OpenBLAS/files/1274716/ctest_results2.txt)
[ctest_results3.txt](https://github.com/xianyi/OpenBLAS/files/1274717/ctest_results3.txt)
[ctest_results4.txt](https://github.com/xianyi/OpenBLAS/files/1274718/ctest_results4.txt)
[ctest_results5.txt](https://github.com/xianyi/OpenBLAS/files/1274719/ctest_results5.txt)
[ctest_results6.txt](https://github.com/xianyi/OpenBLAS/files/1274715/ctest_results6.txt)
[build_log.txt](https://github.com/xianyi/OpenBLAS/files/1274647/build_log.txt)
[Makefile.conf_last.txt](https://github.com/xianyi/OpenBLAS/files/1274611/Makefile.conf_last.txt)

**Comment by brada4** [comment]
Can you run 'make clean' and capture *all* output of build with 'script' ?
Must be i5-6600K, your posted CPU name does not exist.
Can you make extra build with NO_AVX2=1 set
There are some reports of AVX2 not being instrumented 100% 
https://github.com/Microsoft/BashOnWindows/issues/2234

**Comment by jon-mueller** [comment]
@brada4 attached

[build_log_full.txt](https://github.com/xianyi/OpenBLAS/files/1274834/build_log_full.txt)

**Comment by brada4** [comment]
Can you make it fail when built with NO_AVX2=1 set?

**Comment by jon-mueller** [comment]
It did fail some tests with NO_AVX2=1 .  See attached.

[build_no_avx2.txt](https://github.com/xianyi/OpenBLAS/files/1274861/build_no_avx2.txt)

**Comment by brada4** [comment]
No tests should fail to call resultant library usable.
Haswell and Sandybridge kernels (...you tested so far) survive tests impeccably ... usually. 
Now try `NO_AVX=1 NO_AVX2=1` (still picking on Windows10Ubuntu CPU scheduler)
And attach what is in /proc/cpuinfo

**Comment by jon-mueller** [comment]
Attached results of `NO_AVX=1 NO_AVX2=1` and /proc/cpuinfo.  The build failed self-tests and then complained about exports.

Probably related: I also occasionally use Octave on Windows 10 on the same machine (not using the subsystem for linux), and I see similar issues when I use the OpenBLAS library in Octave.  For example, when I multiply large matrices in Octave, some entries are anomalously large (1e+300) similar to how the self-tests are failed.  So I don't think this problem is confined to the linux subsystem.


[build_no_avx_avx2.txt](https://github.com/xianyi/OpenBLAS/files/1274901/build_no_avx_avx2.txt)
[cpuinfo.txt](https://github.com/xianyi/OpenBLAS/files/1274903/cpuinfo.txt)

**Comment by brada4** [comment]
You need to run 'make clean' between changing build options, in command line or Makefile.rule, last build log says you did not and while build failed before even considering any tests. Please redo both limited builds with 'make clean' in between.

What I see in CPUID, there is no AVX2 in CPUID, while your CPU certainly has it supported (it should be exactly 'avx2' in that line if supported).

Do you happen to know what version of OpenBLAS your octave is using? 0.2.20 is oldest that recognizes your CPU, otherwise it thinks it is prescott (though should be accurate either way).

~~Also - is your CPU microcode updated and/or configured to evade a bug:~~
~~https://www.theregister.co.uk/2017/06/25/intel_skylake_kaby_lake_hyperthreading/~~
It is fine. No HT supported.

**Comment by jon-mueller** [comment]
Attached updated logs.  `NO_AVX2=1` failed self-tests, but `NO_AVX=1 NO_AVX2=1` passed.

I'm not sure what version of OpenBLAS Octave uses.  I'm running tests on older versions of OpenBLAS now.  And you're right - I don't have HT.


[build_no_avx2.txt](https://github.com/xianyi/OpenBLAS/files/1275039/build_no_avx2.txt)
[build_no_avx_avx2.txt](https://github.com/xianyi/OpenBLAS/files/1275045/build_no_avx_avx2.txt)

**Comment by jon-mueller** [comment]
Update @quickwritereader :  I was able to build v0.2.15 - v0.2.19 too and they all fail self-tests in similar ways to v0.2.20 .  ~~I'll update my build script (need to specify cpu target) and try v0.2.0 - v0.2.14 soon.~~ 
  Let me know if you want me to try any other specific builds.

**Comment by brada4** [comment]
It is pretty much in line with linked windows10ubuntu ticket. It looks like AVX2 is masked from CPU features, but AVX present there is not for real either...
I remember something similar when MMX was new and one ran 2 MMX programs ....

You can build something like TARGET=Atom until either windows bash gets AVX2 (or at least AVX) support or we figure out how to detect corrupt AVX state quickly (before compiling anything...) or you install ubuntu in whatever free virtualisation product you can find that allows AVX2 or at least AVX passthrough.

**Comment by quickwritereader** [comment]
@jon-mueller 
It seems Nehalem worked for you. But not SandyBridge which afaik works for many. I never used windows 10 linux subsystem. But if possible upgrade your gcc gfortran and etc
Thanks.

**Comment by jon-mueller** [comment]
Thanks all for the help.  It seems the problem is definitely with AVX.  

Since I also had very similar problems in Octave on Windows 10, I decided to check MKL with numpy/scipy in Windows 10 (not linux subsystem), and it shows the same problems; sometimes when I multiply numpy matrices together, I get huge wrong answers (~1e+300).  My guess is that it's a problem with AVX in my CPU, maybe related to [SKL121](https://www-ssl.intel.com/content/www/us/en/processors/core/desktop-6th-gen-core-family-spec-update.html).  I'll look for a way to disable AVX globally if possible, but that's certainly not your problem or a problem with Openblas.

**Comment by brada4** [comment]
You need to test your hardware if native windows applications fail. Then it has nothing to do with OpenBLAS or AVX.

**Comment by brada4** [comment]
SKL121 does not explain AVX(-128) failures. Update BIOS as a minimum and re-open issue if it is unique to OpenBLAS and not seen in MKL.
