### ISSUE TITLE
GCC 7.X and `-funroll-loops` will produce seg-faults

### ISSUE THREAD

**Issue by zerothi** [xianyi/OpenBLAS#1292]
I am pretty sure this is a compiler bug, but for completeness sake (and for other users) it may be valuable to have it here. 
If you think this warrants a bug-report for GCC, let me know and I will create it.

I have tried to compile OpenBLAS with these flags:

    FC/CFLAGS = 
    FC/CFLAGS = -funroll-loops

For the first case everything runs smoothly, tests works etc. For the second case seg-faults appear. Hence, one should not compile OpenBLAS with `-funroll-loops` for GCC 7.X.

For GCC 6.X `-funroll-loops` produces no seg-faults and works as expected.

Note that many other high optimization flags does not produce seg-faults, i.e. `-O3 -fexpensive-optimizations -ftree-vectorize -fprefetch-loop-arrays -march=native` works fine for both 6 and 7.

Perhaps you can `filter-out` the flag `-funroll-loops` from the `CFLAGS`/`FCFLAGS` env vars, if used?

**Comment by martin-frbg** [comment]
If this is specific to gcc 7.x on some (which?) platform, please create a bug report for gcc. But I expect like us they will need much more detail (where do the segfaults occur, does it happen on more than one processor model ?) to be able to act on it.

**Comment by zerothi** [comment]
Yes, I thought so too, it was just that I was unsure whether the complex nature of OpenBLAS could be one cause. Once I get more information I will make a cross-link.

**Comment by brada4** [comment]
Here as minimum we need backtrace - just repeating crashing command in GDB, then when crash is caught run 't a a bt' .
Which OpenBLAS version?
Does it build correctly with default flags, like typing 'make'?

**Comment by zerothi** [comment]
Thanks, as written above, it only crashes if `-funroll-loops` are in the CFLAGS, otherwise everything runs as expected.
I have compiled with `USE_THREAD=0`, will redo with `USE_THREAD=1`.
It is the developer version (HEAD).

Here is the backtrace:
```
OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 ./dblat2 < ./dblat2.dat

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x2aeec50dd02f in ???
#1  0x420687 in dgemv_kernel_4x4
	at ../kernel/x86_64/dgemv_n_microk_haswell-4.c:38
#2  0x421371 in dgemv_n
	at ../kernel/x86_64/dgemv_n_4.c:265
#3  0x40f71a in dgemv_
	at /home/nicpa/LA/OpenBLAS/interface/gemv.c:231
#4  0x40a744 in ???
#5  0x40f2cb in ???
#6  0x40103e in ???
#7  0x2aeec50ca2b0 in ???
#8  0x401099 in ???
#9  0xffffffffffffffff in ???
```

with `gdb`
```
gdb ./dblat2
$> run < ./dblat2.dat
Program received signal SIGSEGV, Segmentation fault.
0x0000000000420687 in dgemv_kernel_4x4 (n=-2072, ap=ap@entry=0x7fffffff8de0, 
    x=x@entry=0x7fffffffa7c0, y=0x7fffffffaf60, alpha=0x7fffffff8dd8)
    at ../kernel/x86_64/dgemv_n_microk_haswell-4.c:38
38		__asm__  __volatile__
$> t a a bt

Thread 1 (process 3350):
#0  0x0000000000420687 in dgemv_kernel_4x4 (n=-2072, 
    ap=ap@entry=0x7fffffff8de0, x=x@entry=0x7fffffffa7c0, y=0x7fffffffaf60, 
    alpha=0x7fffffff8dd8) at ../kernel/x86_64/dgemv_n_microk_haswell-4.c:38
#1  0x0000000000421372 in dgemv_n (m=<optimized out>, n=31, 
    dummy1=<optimized out>, alpha=<optimized out>, a=0x637640 <aa>, lda=16, 
    x=0x7fffffffa740, inc_x=1, y=<optimized out>, inc_y=1, 
    buffer=<optimized out>) at ../kernel/x86_64/dgemv_n_4.c:265
#2  0x000000000040f71b in dgemv_ (TRANS=<optimized out>, M=<optimized out>, 
    N=<optimized out>, ALPHA=<optimized out>, a=<optimized out>, 
    LDA=<optimized out>, x=<optimized out>, INCX=0x7fffffff92dc, 
    BETA=<optimized out>, y=<optimized out>, INCY=0x7fffffff92e0)
    at gemv.c:231
#3  0x000000000040a745 in dchk1_ ()
#4  0x000000000040f2cc in MAIN__ ()
#5  0x000000000040103f in main ()
```

From the output you can see it is a haswell core.

**Comment by zerothi** [comment]
@brada4 same thing for `USE_THREAD=1`, the backtrace is the same.

The only (slight) difference is `t a a bt`:
```
(gdb) t a a bt

Thread 2 (Thread 0x2aaaabfb9700 (LWP 27894)):
#0  0x00002aaaabaebca7 in sched_yield () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x0000000000431686 in blas_thread_server (arg=<optimized out>) at blas_server.c:320
#2  0x00002aaaab3ae494 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00002aaaabb02aff in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 1 (Thread 0x2aaaaaaefd00 (LWP 27890)):
#0  0x0000000000436e87 in dgemv_kernel_4x4 (n=-2072, ap=ap@entry=0x7fffffff8dd0, 
    x=x@entry=0x7fffffffa7b0, y=0x7fffffffaf50, alpha=0x7fffffff8dc8)
    at ../kernel/x86_64/dgemv_n_microk_haswell-4.c:38
#1  0x0000000000437b72 in dgemv_n (m=<optimized out>, n=31, dummy1=<optimized out>, 
    alpha=<optimized out>, a=0x6518c0 <aa>, lda=16, x=0x7fffffffa730, inc_x=1, 
    y=<optimized out>, inc_y=1, buffer=<optimized out>) at ../kernel/x86_64/dgemv_n_4.c:265
#2  0x0000000000410576 in dgemv_ (TRANS=<optimized out>, M=<optimized out>, N=<optimized out>, 
    ALPHA=<optimized out>, a=<optimized out>, LDA=<optimized out>, x=<optimized out>, 
    INCX=0x7fffffff92cc, BETA=<optimized out>, y=<optimized out>, INCY=0x7fffffff92d0)
    at gemv.c:231
#3  0x000000000040b585 in dchk1_ ()
#4  0x000000000041010c in MAIN__ ()
#5  0x0000000000401e4f in main ()
```

**Comment by brada4** [comment]
Way too much optimized out to understand on the spot....
What about '-O0 -funroll-loops' ? i.e clearly attribute problem to miscompilation with this option present or absent. This will make better backtrace if failing.
Default flags make no crash ?

**Comment by zerothi** [comment]
Sorry, I had forgotten to set `*COMMON_OPT` in env.

I have re-runned with
```
COMMON_OPT=-O0 -funroll-loops -g
CFLAGS=-O0 -funroll-loops -g
FCOMMON_OPT=-O0 -funroll-loops -g -fbacktrace
FCFLAGS=-O0 -funroll-loops -g -fbacktrace
```
and then the crash disappears. So it has to do with optimizations. I will try and make a report for gcc team.

(note I also tried with `-Og`, to no avail, the crash still disappears).

As said previously. Default flags works as expected.

**Comment by brada4** [comment]
Flip all 100 compiler flags one by one until bug reappears and report a bug to GCC. There is nothing OpenBLAS can change to cure miscompilation.

**Comment by martin-frbg** [comment]
On a hunch can you try `-funroll-loops -mstackrealign` (with or without `-O2`) ? It has been observed before that some of the assembly routines use instructions that expect data to be aligned, and will segfault otherwise.

**Comment by brada4** [comment]
Fails on my atom (suse tumbleweed and system gcc 7.1.1) too in same place, indifferent of stackrealign flag. I am trying to reduce -O below 2 and then will let it drill to options across the new border line.

**Comment by brada4** [comment]
OK border is between -O1 and -O2
`-O2 turns on all optimization flags specified by -O.  It also turns on the following optimization flags: 
blah blah blah 20h or so to go to check every single of them`

**Comment by brada4** [comment]
-Os is good.... that makes things faster....
`-Os disables the following optimization flags: -falign-functions  -falign-jumps  -falign-loops -falign-labels  -freorder-blocks  -freorder-blocks-algorithm=stc -freorder-blocks-and-partition  -fprefetch-loop-arrays`

**Comment by martin-frbg** [comment]
Seems to be caused by one of the `-fipa-...' options, have not checked which of the eight that get enabled at O2 it is

**Comment by zerothi** [comment]
We agree that you only see this if `-funroll-loops` is used? I mean `-O3 -fexpensive-optimizations -ftree-vectorize -fprefetch-loop-arrays -march=native` produces no seg-fault for me.

**Comment by brada4** [comment]
OK
-O1 -Os generates valid code, while -O2 -O3 generates invalid code with -funroll-loops
flipping options (all 8 different at once or one by one) does not change outcome (atom tested by me on SuSE tumbleweed with their GCC 7.1.1, and some haswell on unknown OS with unknown GCC 7.X by you).
Please report the bug to GCC and post back link to your report. IPA options are not documented as difference between -Os and -O2.

**Comment by zerothi** [comment]
Thanks, will proceed.

OS: Debian stretch k4.9.30-2+deb9u3
GCC: 7.2.0

**Comment by brada4** [comment]
You can try Debian first. Few times I asked they were much better than just helpful (though obvious that issue is upstream)

**Comment by martin-frbg** [comment]
For gcc-7.2 on Kaby Lake (Haswell kernel), the minimum combination of options to reproduce the fault is `-O1 -funroll-loops -fipa-ra`
On the other hand, `-Os -funroll-loops -fipa-ra` does not show the problem, indeed `-fipa-ra` is on by default at `-Os`. This option set overall is almost identical to that of `-O2`, differing only in `-finline-functions`  and `-foptimize-strlen` (according to the output of `gcc -Q -Os -help=optimizers` at least - of course this does tell of any defects in the compiler code).

**Comment by martin-frbg** [comment]
FWIW gdb puts the actual location of the segfaulting instruction inside the inline assembly block at line 67 of dgemv_n_microk_haswell-4.c which is ` "vmovups        -32(%3,%0,8), %%ymm8           \n\t"    // 4 * y` (or `vmovups -0x20(%rcx,%rax,8),%ymm8` as it shows up in gdb). This is not on the first invocation by far, and suspiciously the "n" parameter appears to be zero on invocation (which I suspect should never happen, and does not seem to be guarded against in the assembly). So it looks to me as if the invoking loop in dgemv_n_4.c got unrolled one time too many.

**Comment by zerothi** [comment]
I have posted the bug here:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=82133

**Comment by martin-frbg** [comment]
BTW did you see a significant speedup from the use of this option (where it worked), or are you just trying it on OpenBLAS as it proved to be beneficial with your own code ?

**Comment by zerothi** [comment]
The `funroll-loops` flag was not specifically for OpenBLAS but for another program I installed. So it was a leftover env-var in the installation program.

However, I suspect it could influence the LAPACK performance. So now I do this:
```
LAPACK_FFLAGS='$FCFLAGS' LAPACK_CFLAGS='$CFLAGS'"
FCOMMON_OPT='${FCFLAGS//-funroll-loops/}' COMMON_OPT='${CFLAGS//-funroll-loops/}'"
```
I haven't done a careful study of the influence on OpenBLAS.

**Comment by brada4** [comment]
From archaelogical memory around starts of gcc3 - it unrolls very long loops making sure they dont fit caches. Probably it is better, but it fits just X megs in cache.

**Comment by martin-frbg** [comment]
From https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58529 it seems advisable to do some performance tests with the gcc option `--param max-unroll-times=` to find the sweet spot for loop unrolling. Generally looking at the gcc bugzilla does not exactly raise hopes for a quick resolution, but I am not (yet) convinced this is a case where the OpenBLAS build system should try to intervene.

**Comment by kristerw** [comment]
The reason for this seg-fault is that the operands of `dgemv_kernel_4x4` inline assembly do not describe correctly what the code is doing. GCC is not that good at re-using the registers with inline assembly – that is why this code usually works – but GCC is "lucky" in this case, and manages to optimize away an "useless" re-initialization of a register.

What is happening is that the compiler generates a call to `dgemv_kernel_4x4` which takes the loop count `n` as an input operand, which GCC places in `%rdi`
```
mov    %r13,%rdi
callq  dgemv_kernel_4x4
```
It then calls `dgemv_kernel_4x4` a few instructions later (because of unrolling), and the compiler sees that `%rdi` has not been changed (as it only is an input operand to the inline assembly, and inline assembly must not modify input operands), so it does not need to re-initialize it. But the inline assembly _does_ change `%rdi` when looping
```
subq $4, %1
jnz  1b
```
and this subsequent call will be called with `%rdi` containing the value 0, which will make the code misbehave...

The GCC manual has some text about how to fix this in [the section describing "input operands"](https://gcc.gnu.org/onlinedocs/gcc-7.2.0/gcc.pdf#InputOperands), but there are no good options... :(

**Comment by martin-frbg** [comment]
Ugh. Thanks for your insight. Subtracting from (or adding to) input operands %0 and/or %1 appears to be a quite common feature of the x86_64 kernels (at least). While my assembler knowledge is still rather sketchy, am I right in assuming that it should be possible to copy %rdi to some other register at the start of the function, and use that for keeping track of iterations instead ?

**Comment by martin-frbg** [comment]
Indeed seems to survive all tests with 7.2.0 and -funroll-loops when I add a "movq %1, %%r13\n\t" at the start of each inline asm file for the gem functions, and do all the subq etc. on r13 as well. (That register was picked at random after finding that using rax for this purpose led to problems, any suggestions for which is preferable ?)

**Comment by kristerw** [comment]
Choosing a register (and adding it as a "clobber") _should_ work, but I'm a bit scared of doing this – it is the kind of thing that trigger obscure corner cases in the register allocator, and I would not be surprised if this sometimes fails in interesting ways... (Btw, what problem did you see by choosing `rax`?)

It is usually better to let the compiler give you a register to use. You can do this by defining a temporary variable
```
BLASLONG tmp;
```
and add this as an output register
```
: "=&r" (tmp)
```
Note the `&` constraint modifier – it tells the compiler that it cannot choose a register that is used as an input register, as it would be bad if `dgemv_kernel_4x4` used the same register for both this temporary register and for `y`...

But there is a better way to fix `dgemv_kernel_4x4` – change `i` and `n` to be both input and output registers by changing the operands to
```
	:
          "+r" (i),	// 0	
	  "+r" (n),  	// 1
        : 
          "r" (x),      // 2
          "r" (y),      // 3
          "r" (ap[0]),  // 4
          "r" (ap[1]),  // 5
          "r" (ap[2]),  // 6
          "r" (ap[3]),  // 7
          "r" (alpha)   // 8
	: "cc", 
	  "%xmm4", "%xmm5", 
	  "%xmm6", "%xmm7", 
	  "%xmm8", "%xmm9", 
	  "%xmm12", "%xmm13", "%xmm14", "%xmm15",
	  "memory"
	);
```
This will work in this case without any change to the assembly code – the only difference is that it will change the C variables `i` and `n` as a side effect, but they are local to the function anyway, so it does not matter...

**Comment by martin-frbg** [comment]
Thank you very much for that. (With rax, I got a segmentation fault in one of the later statements that moved elements of the input vector to the xmms register via addressing like (%2,%0,8) - cannot exclude that I had another mistake there at the time though. As I was fishing around for examples, using r-something seemed like the next best idea and it worked, so I stuck with it. Letting the compiler pick an appropriate choice does make sense obviously.)
There appear to be around 100 files in kernel/x86_64 that use `addq ..., %1`or `subq ...,%1` - unsurprising as most of the assembly contributed in recent years was the work of a single developer.
Probably not all are as vulnerable to optimization as the gemv case, but I expect all will need fixing now that the problem is known.
