### ISSUE TITLE
Build error: unresolved external symbol _cblas_dscal

### ISSUE THREAD

**Issue by travek** [xianyi/OpenBLAS#1296]
Hi!
I'm trying to build a project with Blassupport. I'using MS VS 2015. I'm using precompiled liblarires from OpenBLAS-v0.2.19-Win64-int32.zip
I included .lib into project with Linker. 
When I do the buildIget the following:
1>rates_indicators.obj : error LNK2001: unresolved external symbol _cblas_dscal
1>rates_indicators.obj : error LNK2001: unresolved external symbol _cblas_dger
1>rates_indicators.obj : error LNK2001: unresolved external symbol _cblas_daxpy

I checked cblas.h, There's no _cblas_dscal declaration but only cblas_dscal.
How to fix this issue ?

**Comment by brada4** [comment]
Check for any /Gx compile option. Should be /Gz for stdcall

**Comment by travek** [comment]
I setup /Gz option. With this setup I have the following issue:
1>rates_indicators.obj : error LNK2001: unresolved external symbol _cblas_dscal@20
1>rates_indicators.obj : error LNK2001: unresolved external symbol _cblas_dger@44
1>rates_indicators.obj : error LNK2001: unresolved external symbol _cblas_daxpy@28

**Comment by quickwritereader** [comment]
From the Openblas guide. 
[How-to-use-OpenBLAS-in-Microsoft-Visual-Studio](https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-in-Microsoft-Visual-Studio)

> Copy the import library (before 0.2.10: "OPENBLAS_TOP_DIR/exports/libopenblas.lib", 0.2.10 and after: "OPENBLAS_TOP_DIR/libopenblas.dll.a") and .dll library "libopenblas.dll" into the same folder(The folder of your project that is going to use the BLAS library. **You may need to add the libopenblas.dll.a to the linker input list: properties->Linker->Input**).

And also you could do with explicit linkage:
Calling  dumpbin on dll showed function name is cblas_dscal, cblas_* (without underscore as those are exported)
[Linking Explicitly](https://msdn.microsoft.com/en-us/library/784bt7z7.aspx)

**Comment by martin-frbg** [comment]
Did this help to solve the problem, or did you drop the issue ? From the issues you opened with the dlib project you appear to be trying with MKL now ?

**Comment by travek** [comment]
@martin-frbg 
I'm closing the issue. 
I setup Intel MKL and compiled dlib with Intel MKL following Intel MKL linking guide. All works fine with this setup.
