### ISSUE TITLE
Must I have cblas to install OpenBLAS?

### ISSUE THREAD

**Issue by yxchng** [xianyi/OpenBLAS#1297]
Must I have cblas to install OpenBLAS? Currently my system keeps complaining that I do not have cblas. Can I confirm that I need cblas to use OpenBLAS?

**Comment by martin-frbg** [comment]
CBLAS is a part of OpenBLAS (though you can disable it at build time).

**Comment by yxchng** [comment]
@martin-frbg So is it a dependencies? or is it a requirement?

**Comment by martin-frbg** [comment]
No, it is provided by OpenBLAS. Can you post the error messages you got, and what you did ?

**Comment by brada4** [comment]
If it is windows system just put libopenblas.dll under 10 names based on APIs it provides, e.g. blas.dll cblas.dll lapack.dll

**Comment by martin-frbg** [comment]
@yxchng did the above answer your question, or do you need further assistance ?
