### ISSUE TITLE
Why do the kernels process 4 and not 8 floats at a time?

### ISSUE THREAD

**Issue by chrisics** [xianyi/OpenBLAS#1298]
AFAICT, kernels such as sgemv_kernel_4x8 load 8 times 4 floats in the registers and then use fma instructions (on Haswell) to multiply and add 4 floats at a time.

	"vbroadcastss    (%2), %%ymm12	 \n\t"	// x0 
	"vbroadcastss   4(%2), %%ymm13	 \n\t"	// x1 
	"vbroadcastss   8(%2), %%ymm14	 \n\t"	// x2 
	"vbroadcastss  12(%2), %%ymm15 \n\t"// x3 
	"vbroadcastss  16(%2), %%ymm0 	 \n\t"	// x4 
	"vbroadcastss  20(%2), %%ymm1 	 \n\t"	// x5 
	"vbroadcastss  24(%2), %%ymm2 	 \n\t"	// x6 
	"vbroadcastss  28(%2), %%ymm3 	 \n\t"	// x7 

	...

	"vfmadd231ps (%4,%0,4), %%xmm12, %%xmm4 \n\t" 
	"vfmadd231ps (%5,%0,4), %%xmm13, %%xmm5 \n\t" 
	"vfmadd231ps (%6,%0,4), %%xmm14, %%xmm4 \n\t" 
	 "vfmadd231ps (%7,%0,4), %%xmm15, %%xmm5 \n\t" 
...

What is the reason behind this? Why not use 8 floats instead? Performance or complexity? Could the code be optimized further?

Thanks.

**Comment by quickwritereader** [comment]
Those inner micro-kernels are used by  sgemv_n_4.c or  sgemv_t_4.c. (in your example it is sgemv_n_4.c. There is c code, too).  As you see its inner block is 4 and this template are used for previous architectures,too. 
There is always room for further optimizations. But it is always declining till it reaches optimal. As far as I know gemv is still memory bound. So I do not know if doing it as 16x4 or 8x8 will make great changes. But it could be tested and you are welcomed to do it.

**Comment by brada4** [comment]
It is to trick C compiler spread variables across registers. If you cannot hold more than 4 variables in register(s) no point using more as it brings just memory access, 100x slower than register access. Sure kernrl sets are fine tuned to find fastest of 1 2 4 8 16 on each CPU platform.

**Comment by martin-frbg** [comment]
I agree that it cannot hurt to test this if you happen to have the time and interest - for all we know this may have been coded with the intention to provide an optimal implementation _within the existing framework_ initially and revisit it later.

**Comment by chrisics** [comment]
Thanks for the clarification.
