### ISSUE TITLE
Please add support for generic System z (z900)

### ISSUE THREAD

**Issue by svillemot** [xianyi/OpenBLAS#1307]
Hi,

A kernel for the z13 arch has recently been added to OpenBLAS.

I therefore wanted to build official OpenBLAS binaries for the Debian “s390x” architecture (which is the name of the Debian port for System z).

However, this is not possible, because the Debian port supports all System z machines, including the oldest one (z900). The z13 kernel does not run on such older systems, since it is not generic enough.

If possible, please provide a generic System z kernel (z900), and ideally a runtime selection between that z900 kernel and the z13 one.

For background information, here is the discussion that happened within Debian on this issue: https://bugs.debian.org/875618

Best,

**Comment by martin-frbg** [comment]
I believe there is a generic ZARCH target already, that maps to pure C kernels.

**Comment by svillemot** [comment]
@martin-frbg Indeed there is a `ZARCH_GENERIC` target, thanks.

However it is not possible to force it (with something like `TARGET=ZARCH_GENERIC`). I am going to submit a patch.

Closing this issue (though it would still be nice to have runtime selection between the Z13 and ZARCH_GENERIC kernels).

**Comment by martin-frbg** [comment]
Not sure what would be needed besides copying from cpuid_zarch.c into driver/others/dynamic.c, but there is probably no fundamental reason why runtime selection should be limited to x86 (except their greater range of broadly similar cpu models).
