### ISSUE TITLE
Makefile using ARCH for name of AR command

### ISSUE THREAD

**Issue by sellcey** [xianyi/OpenBLAS#1309]
I am looking at Makefile in OpenBLAS 0.2.20 and It has these lines when making make.inc:

        -@echo "ARCH        = $(AR)" >> $(NETLIB_LAPACK_DIR)/make.inc
        -@echo "ARCHFLAGS   = -ru" >> $(NETLIB_LAPACK_DIR)/make.inc

I don't think it should be setting ARCH to $(AR), I think these are supposed to be
"AR = $(AR)" and "ARFLAGS = -ru".  Likewise OpenBLAS-0.2.20/lapack-netlib/SRC/Makefile
and OpenBLAS-0.2.20/lapack-netlib/SRC/VARIANTS/Makefile should use AR/ARFLAGS
instead of ARCH/ARCHFLAGS.  Using ARCH confuses things when ARCH is also used as
the architecture of the platform being built.

**Comment by martin-frbg** [comment]
This part is actually imported from netlib LAPACK (which, being FORTRAN, does not bother with architectural differences). As `ar` is/was also known as the "archiver" tool, some confusion seems unavoidable but this here is only used to propagate build information to the bundled lapack.

**Comment by sellcey** [comment]
I am trying to build a 'generic' lapack/blas using only C code (to compare it to the hand coded assembly) and am doing 'make TARGET=GENERIC ARCH=generic' (I had to create a kernel/generic/KERNEL file for this to work). This seems to work on x86 but not on aarch64 where the ARCH variable here is getting used as the AR command  in several makefiles.  Maybe I shouldn't be setting ARCH on the command line but I haven't found any other way to do what I am trying to do.  I have asked on the OpenBLAS google maling list but not gotten any response so far.

**Comment by martin-frbg** [comment]
Are you sure that you need to set the architecture at all ? If you look in getarch.c, forcing the "GENERIC" target should drop ARCHITECTURE and several related defines to GENERIC as well.

**Comment by sellcey** [comment]
I think you are right, I should use TARGET=GENERIC and not specify ARCH.  When I  do that on x86 it works, when I  do it on aarch64 I get:

make[1]: *** No rule to make target '../kernel/arm64/amin.S', needed by 'samin_k.o'.  Stop.

But I think the right solution to that is to have something like this in the arm64/KERNEL file:

ifndef SAMINKERNEL
SAMINKERNEL = ../arm/amin.c
endif

I am not sure how many of these I will need to add.  Does this look right?

**Comment by martin-frbg** [comment]
Yes it does (to my untrained eye at least). Judging from KERNEL.ARMV8 there may be quite a number of these - in fact "ARMV8" appears to be the GENERIC target on that architecture ("historic" reasons maybe - GENERIC will likely have been in K.Goto's original, x86-only libgoto already while all other architectures are later additions). Seems you will encounter the same with 32bit ARM as well, where ARMV5 appears to be a C-only target.

**Comment by sellcey** [comment]
OK, ARMV8 has only one .S file.  I can just override that and get what I want.  I tried to create my own KERNEL.ARMV8_GENERIC file but I see that cpuid_arm64.c also has to change to do that.  In the end I just tweaked my build to add 'SGEMMKERNEL = ../generic/gemmkernel_2x2.c' to the end of the existing KERNEL file and then do the build and got what I wanted.  I will close this issue now.

**Comment by ashwinyes** [comment]
If you are using ../generic/gemmkernel_2x2.c then change the following parameters from 4 to **2** in param.h under the ARMV8 ifdef.

#define SGEMM_DEFAULT_UNROLL_M  4
#define SGEMM_DEFAULT_UNROLL_N  4
