### ISSUE TITLE
Misleading info on FreeBSD install

### ISSUE THREAD

**Issue by outpaddling** [xianyi/OpenBLAS#1311]
Hello,

FYI, there has been a "FreeBSD port" for openblas for some time now.
The instructions on your Wiki ([https://github.com/xianyi/OpenBLAS/wiki/Installation-Guide](https://github.com/xianyi/OpenBLAS/wiki/Installation-Guide)) are useful for the port maintainer, but the general user population should probably be told just to use the port or binary package.  Example instructions below.

Cheers,

    Jason

===
To install via the binary package, simply run:

    pkg install openblas

To build and install from source code, run:

    cd /usr/ports/math/openblas && make install

Building from source allows installing to a different prefix and
in some cases, building with non-default options.

For more information, visit https://www.freebsd.org/ports/index.html.
===

**Comment by martin-frbg** [comment]
Not sure I understand in what way the current information would be misleading - these are instructions for building from source, e.g. if someone wants to try the latest "develop" snapshot instead of whatever version was last added to ports. I am fairly certain there are prebuilt packages for at least some Linux distributions and for Windows "somewhere out there" as well. It may make sense to create a wiki page for collecting links to such packages however...

**Comment by outpaddling** [comment]
Hi Martin,
I support research computing for a living and can tell you that most scientists who need an open source package will go to the developer website and attempt to follow the installation instructions provided there without a second thought.  They will often fail and possibly make a mess of their OS installation in the process.  They tend to be unaware that they could have used a simple "pkg install", "apt-get install", or similar command.  Smart people, of course, but usually not knowledgeable about sysadmin tasks.  I've been watching this happen for 15 years and trying to educate people about it.

I think it would be good to point out the easy and safe options for the users who just want to install the latest release, which is the vast majority in my experience.

There is indeed a Debian package as well:
[https://packages.qa.debian.org/o/openblas.html](https://packages.qa.debian.org/o/openblas.html)
Also two MacPorts, one for the latest release and one for a very recent snapshot:
[https://www.macports.org/ports.php?by=name&substr=openblas](https://www.macports.org/ports.php?by=name&substr=openblas)
I think if you mention these 3 options and add a general statement like "Check the package manager for your system", most people will get the idea and avoid a lot of wasted time.  Should also save you quite a few problem reports.

I'm also working on a pkgsrc package, which we will use on CentOS, but can also be used on Mac, NetBSD, Solaris, and pretty much any other POSIX platform.

Cheers,
     Jason

**Comment by brada4** [comment]
You can get all possible math packages for CentOS from Fedora EPEL
pkgsrc is nice in cases you dont have native packages (e.g. Solaris)
Of the debian-indeed package: https://github.com/xianyi/OpenBLAS/wiki/faq#debianlts
(i.e it is not latest as distributed)

@martin-frbg  - yes, link collection would be nice to have - at least distributions which re-distribute OpenBLAS - I was thinking - if we just add to Centos and Debian FAQentry that there is native package to try before building ?

**Comment by outpaddling** [comment]
Thanks, we're aware of EPEL, but don't use it much.  Anything built on top of the RHEL/CentOS Yum repo is going to be a bit outdated.  Pkgsrc provides easy access to a bigger and more recent set of  packages, including things like GCC 4.8, 4.9, 5, 6, and 7, clang/llvm 4.  It eliminates duplicated effort and ensures consistency when installing on multiple platforms (mostly CentOS 6 & 7 and OS X for us).  It also allows the end user to easily build and install from source using different build options than the binary packages provided.

Here's more info:

[https://pkgsrc.joyent.com/](https://pkgsrc.joyent.com/)
[http://uwm.edu/hpc/software-management/](http://uwm.edu/hpc/software-management/)
[http://unixdev.ceas.uwm.edu:8084/pkgsrc/packages/sharedapps/pkg-2017Q1/RHEL6/All/](http://unixdev.ceas.uwm.edu:8084/pkgsrc/packages/sharedapps/pkg-2017Q2/RHEL6/All/)

Thanks for the tip on the Debian package.  FYI, the FreeBSD port tends to be up-to-date:

```
# $FreeBSD: head/math/openblas/Makefile 449591 2017-09-10 20:55:38Z gerald $

PORTNAME=       openblas
PORTVERSION=    0.2.20
```

Same is usually true for pkgsrc.

Thanks for the lightning-fast replies!

**Comment by brada4** [comment]
What exactly do you want us to do?
Distribution-specific package installation is sort of generic for each system and documented for ages like [here](http://bhami.com/rosetta.html)
FreeBSD ports and NetBSD pkgsrc are not products of OpenBLAS, but derivatives made by other party. Probably you should seek that party if you are looking to improve their packaging.

**Comment by martin-frbg** [comment]
How about this for a start ?
https://github.com/xianyi/OpenBLAS/wiki/Precompiled-installation-packages
(and something like `__Precompiled_packages__ have recently become available for a number of platforms, so the instructions below are mostly relevant when you want to try the most recent development snapshot from git` added at the beginning of the Installation Guide page)

**Comment by brada4** [comment]
s/recently become/are/1

**Comment by outpaddling** [comment]
Currently [http://www.openblas.net/](http://www.openblas.net/) only mentions Windows binaries and installing from source.
If I were a researcher (especially a new grad student tasked with installing software by my adviser) I'd probably end up doing an ad-hoc install from source on my Ubuntu system based on this info.
My suggestion is to make it clear to new users that they can probably install using a package manager unless they need the very latest features.  Guiding them to
[https://github.com/xianyi/OpenBLAS/wiki/Precompiled-installation-packages](https://github.com/xianyi/OpenBLAS/wiki/Precompiled-installation-packages) would do very well in my opinion.  This is exactly what new users should see first.  Maybe add a link to this page under "Binary Packages" at [http://www.openblas.net/](http://www.openblas.net/)?
This will save them a lot of time, expedite scientific research, and save you some NOOB questions from people unnecessarily trying to do a manual install.
Thanks!

**Comment by brada4** [comment]
Front page editing is up to project leader. We can just make nice wiki page for consideration.

**Comment by brada4** [comment]
Does this server part of your purpose?
https://github.com/xianyi/OpenBLAS/wiki/Precompiled-installation-packages#debianubuntumint
It takes time to do research around distribution.

**Comment by outpaddling** [comment]
Yep.  And it doesn't need to be detailed, comprehensive or even up-to-date.  As long as it makes users aware that there's an easy and reliable way to install the software, mission accomplished.

BTW, I also wanted to send our deepest gratitude for the work you all do on openblas.  Having a portable, open source BLAS implementation that rivals MKL's performance in our package managers saves us a lot of man-hours on caveman installations with ICC.  We can use that time for more creative work, so we accomplish more thanks to you...

**Comment by brada4** [comment]
You could make some prose in the wiki page.

**Comment by brada4** [comment]
@outpaddling Can you add paragraph in wiki regarding Solaris x86_64 via pkgsrc (if it works at all)
Current state of prebuilt packages for Solaris could wish better....

**Comment by outpaddling** [comment]
Sorry, I don't have access to a Solaris system at the moment.  The package is not finished anyway.  So far I've only tested on CentOS 6 & 7.  I'll ping the pkgsrc community and see if someone else might be willing to test on Solaris.

**Comment by brada4** [comment]
I have just various linux in various places and a little windows here and there. If you manage just add where now placeholder is. I think guides here should not grow past that : try distributors version , if that is to old DIY...

**Comment by martin-frbg** [comment]
I'm thinking we might as well close this, as the lack of FreeBSD package info has been resolved ? The wiki page can be amended anytime someone has solid information for one of the supported platforms.

**Comment by outpaddling** [comment]
Agreed.
