### ISSUE TITLE
OSX with ifort 18 linking or/and threading problem

### ISSUE THREAD

**Issue by dimpase** [xianyi/OpenBLAS#1312]
with the latest Xcode 9 and ifort the default install of `develop` branch (just typing `make`)
ends up with 
```
...
ifort -O2 -fPIC -c -o tstiee.o tstiee.f
ifort -O2 -fPIC -c -o ilaver.o ilaver.f
ifort -O2 -fPIC -c -o LAPACK_version.o LAPACK_version.f
ifort -O2 -fPIC -lpthread -o testlsame lsame.o lsametst.o
ifort -O2 -fPIC -lpthread -o testslamch slamch.o lsame.o slamchtst.o
ld: targeted OS version does not support use of thread local variables in _for__set_signal_ops_during_vm for architecture x86_64
make[2]: *** [testlsame] Error 1
```

```
$ ifort -V
Intel(R) Fortran Intel(R) 64 Compiler for applications running on Intel(R) 64, Version 18.0.0.104 Build 20170811

$ clang -v
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin16.7.0
Thread model: posix

```

**Comment by brada4** [comment]
Is 'ld' from ifort or from xcode?

**Comment by brada4** [comment]
Somewhere in ifort release notes xcode6 sneaks through. Can you check in local documentation?

**Comment by dimpase** [comment]
`which ld` says it's `/usr/bin/ld`. Could it be something to do with `MACOSX_DEPLOYMENT_TARGET` ?

**Comment by dimpase** [comment]
I don't seem to have local docs (only "getting started"), perhaps due to a restricted academic license I have for `ifort`.

**Comment by brada4** [comment]
As minimum they got version numbers wrong, even for paying customers:
https://software.intel.com/en-us/articles/intel-compiler-and-composer-update-version-numbers-to-compiler-version-number-mapping

And ifort 2018 does not support Xcode 9:
https://software.intel.com/en-us/articles/get-started-installing-parallel-studio-xe-2018-macos

All after all - get your compilers right.

**Comment by dimpase** [comment]
Oops, sorry for noise then. I somehow expected a bit more maturity from them. :-(
