### ISSUE TITLE
No longer linking with fortran.  

### ISSUE THREAD

**Issue by KellenSunderland** [xianyi/OpenBLAS#1313]
As of [this commit](https://github.com/xianyi/OpenBLAS/commit/3a245a376f94609ec48ce736b8cba892cc97cd90) I can no long compile OpenBLAS without explicitly defining NO_FORTRAN.

Here's some example output:
```bash
make -j$(nproc) TARGET=ARMV6
...
/usr/bin/arm-linux-gnueabihf-gcc -O2 -DMAX_STACK_ALLOC=2048 -marm -Wall -DF_INTERFACE_G77 -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=36 -mfpu=vfp -march=armv6 -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  -shared -o ../libopenblas_armv6p-r0.3.0.dev.so \
-Wl,--whole-archive ../libopenblas_armv6p-r0.3.0.dev.a -Wl,--no-whole-archive \
-Wl,-soname,libopenblas.so.0 -lm -lpthread -lm -lpthread
/usr/bin/arm-linux-gnueabihf-gcc -O2 -DMAX_STACK_ALLOC=2048 -marm -Wall -DF_INTERFACE_G77 -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=36 -mfpu=vfp -march=armv6 -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  -w -o linktest linktest.c ../libopenblas_armv6p-r0.3.0.dev.so  && echo OK.
../libopenblas_armv6p-r0.3.0.dev.so: undefined reference to `_gfortran_concat_string'
../libopenblas_armv6p-r0.3.0.dev.so: undefined reference to `_gfortran_pow_i4_i4'
../libopenblas_armv6p-r0.3.0.dev.so: undefined reference to `_gfortran_compare_string'
collect2: error: ld returned 1 exit status
```

```bash
make -j$(nproc) TARGET=ARMV6 NOFORTRAN=0
...
/usr/bin/arm-linux-gnueabihf-gcc -O2 -DMAX_STACK_ALLOC=2048 -marm -Wall -DF_INTERFACE_G77 -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=36 -mfpu=vfp -march=armv6 -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  -shared -o ../libopenblas_armv6p-r0.3.0.dev.so \
-Wl,--whole-archive ../libopenblas_armv6p-r0.3.0.dev.a -Wl,--no-whole-archive \
-Wl,-soname,libopenblas.so.0 -lm -lpthread -lm -lpthread
/usr/bin/arm-linux-gnueabihf-gcc -O2 -DMAX_STACK_ALLOC=2048 -marm -Wall -DF_INTERFACE_G77 -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=36 -mfpu=vfp -march=armv6 -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  -w -o linktest linktest.c ../libopenblas_armv6p-r0.3.0.dev.so -L/usr/bin/../lib/gcc/arm-linux-gnueabihf/4.8.3 -L/usr/bin/../lib/gcc/arm-linux-gnueabihf -L/usr/bin/../lib/gcc -L/usr/bin/../lib/gcc/arm-linux-gnueabihf -L/usr/bin/../lib/gcc/arm-linux-gnueabihf/4.8.3/../../../../arm-linux-gnueabihf/lib -L/usr/bin/../arm-linux-gnueabihf/libc/lib/arm-linux-gnueabihf -L/usr/bin/../arm-linux-gnueabihf/libc/lib -L/usr/bin/../arm-linux-gnueabihf/libc/lib/arm-linux-gnueabihf -L/usr/bin/../arm-linux-gnueabihf/libc/usr/lib/arm-linux-gnueabihf -L/usr/bin/../arm-linux-gnueabihf/libc/usr/lib -L/usr/bin/../arm-linux-gnueabihf/libc/usr/lib/arm-linux-gnueabihf  -lgfortran -lm -lm -lc   && echo OK.
OK.
rm -f linktest
make[1]: Leaving directory '/work/OpenBLAS/exports'

 OpenBLAS build complete. (BLAS CBLAS LAPACK LAPACKE)

  OS               ... Linux
  Architecture     ... arm
  BINARY           ... 32bit
  C compiler       ... GCC  (command line : /usr/bin/arm-linux-gnueabihf-gcc)
  Library Name     ... libopenblas_armv6p-r0.3.0.dev.a (Multi threaded; Max num-threads is 36)

To install the library, you can run "make PREFIX=/path/to/your/installation install".
```

**Comment by martin-frbg** [comment]
Hmm. NOFORTRAN should be set automatically (by f_check) when no fortran compiler is found, and I think it would make sense not to try to link against a fortran runtime library that may not even be installed in that case. Do you see any references to fortran code being compiled in the full log of the default build ?

**Comment by KellenSunderland** [comment]
Yes, totally agree with that.  For some reason my CI server (which has been building openblas correctly for a few months) and which does have fortran installed doesn't link with -lgfortran.  That is unless yes explicitly set NOFORTRAN to 0.  This should be reproducible simply by running 
```bash
make -j$(nproc) TARGET=ARMV6
```
on a machine with all required pre-requisites (including fortran).

You can also reproduce by building this dockerfile: https://gist.github.com/KellenSunderland/2dcd5be1dbbe54df694e13abe8f0f6f3

**Comment by brada4** [comment]
You can try 
FC=Fake-Nothing
And/or
NOLAPACK=1
To disable fortran other ways.
btw to enable `make -j` you need to set `MAKE_NB_JOBS=-99`, otherwise it uses 1 process per cpu

Much more of build log is needed to diagnose problem. It is too time consuming to to get ARM and/or docker to test.
You set FC and NOFORTRAN option is not documented, it is set internally when FC is not valid.

**Comment by KellenSunderland** [comment]
Thanks for the info brada.  Just to be clear I'm not trying to disable fortran, I'm trying to enable it.  Let me know if you're unable to reproduce the problem, and if you are I can post some more of the build logs.

**Comment by brada4** [comment]
I dont have ARM with 2 cores (I have in mobile, but i dont think it can dockr container)

FC & Co should be parameters to make, not env variables.

**Comment by KellenSunderland** [comment]
The Dockerfile attached should work on an x86 box.  The only thing you'll need is docker installed and then run:
```bash
docker build -f Dockerfile .
```
The env vars are there because this is just the first part of a longer script which reuses the values.

**Comment by martin-frbg** [comment]
Probably the ifeq misfires if/when NOFORTRAN is not even defined ? (My excuse is that I copied that syntax from an OSX build line further down in exports/Makefile, assuming that one to be correct - the "filter" is involved as a CBLAS-only build sets NOFORTRAN=2 for whatever reason)

**Comment by martin-frbg** [comment]
Indeed wisdom of the 'net suggests the `ifeq ($NOFORTRAN, $(filter $NOFORTRAN), 1 2))` should be rewritten as `ifneq (,$(filter(1 2, $NOFORTRAN)))` as "filter" returns an empty string for "no match" (which would match the undefined/empty NOFORTRAN in the present code).

**Comment by KellenSunderland** [comment]
Just ran with the latests commit and can verify everything's working.  Thanks a ton for the quick fix Martin.
