### ISSUE TITLE
android armv8 compile failure: unrecognised emulation mode: aarch64linux

### ISSUE THREAD

**Issue by springishere** [xianyi/OpenBLAS#1315]
Ubuntu 16.04
Followed the instruction (Build ARMV8 with clang section):
export NDK_BUNDLE_DIR=~/android-ndk-r15c
export PATH=${NDK_BUNDLE_DIR}/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin:${NDK_BUNDLE_DIR}/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
export LDFLAGS="-L${NDK_BUNDLE_DIR}/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x -lm"
export CLANG_FLAGS="-target aarch64-linux-android --sysroot ${NDK_BUNDLE_DIR}/platforms/android-23/arch-arm64 -gcc-toolchain ${NDK_BUNDLE_DIR}/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/"
make TARGET=ARMV8 ONLY_CBLAS=1 AR=ar CC="clang ${CLANG_FLAGS}" HOSTCC=gcc -j4

Compile is ok, ld fails
/usr/bin/ld: unrecognised emulation mode: aarch64linux
Supported emulations: elf_x86_64 elf32_x86_64 elf_i386 elf_iamcu i386linux elf_l1om elf_k1om i386pep i386pe
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by springishere** [comment]
If I do these I can build:
sudo ln /home/local/ANT/fengy/android-ndk-r15c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/aarch64-linux-android/bin/ld /usr/bin/ld
sudo ln /home/local/ANT/fengy/android-ndk-r15c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/aarch64-linux-android/bin/ar /usr/bin/ar

**Comment by martin-frbg** [comment]
Looks as if you copied the instructions for setting the PATH from the "ARMv7 with clang" section of the wiki page by mistake (note use of "arm-linux-androideabi" instead of aarch64-linux-android-4.9) so it could not access the ld and ar provided by the toolchain ?

**Comment by springishere** [comment]
Ah, good catch! I did compile for armv7 first and then modified.
