### ISSUE TITLE
libopenblas.dll - No such file or directory

### ISSUE THREAD

**Issue by fuentert** [xianyi/OpenBLAS#1321]
I'm currently on 64bit Windows 10. and having some issues linking OpenBLAS to some code I have written. I have compiled and installed OpenBLAS-0.2.20 with MinGW. However, whenever I try to actually compile my code with OpenBLAS using the command "gcc -o test tests.c /OpenBLAS-0.2.20/libopenblas.dll", it returns "libopenblas.dll: No such file or directory"

Note that tests.c is my own code that calls cblas_sgemm as a test, and I do include cblas.h. OpenBLAS-0.2.20 is the folder that has the OpenBLAS code and where I called the make command. libopenblas.dll is inside that folder. When I just open up the OpenBLAS-0.2.20 folder and open libopenblas.dll through the command terminal, it throws an error message saying it can't open the file since I have no software able to open it, so my computer knows libopenblas.dll is there when I call it seperately.

I'm sure I'm missing something completley basic or simple, but I've been exhausting many of solutions I could think of from making the folder clean before making all, to ensuring I have the latest version of MinGW, Fortran, etc. but nothing seems to be working. Any hints would be appreciated.

**Comment by martin-frbg** [comment]
Are you sure about the leading slash on the folder name ? In Unix lingo that puts it at the top of the folder hierarchy, maybe you want a relative path (no leading slash if "OpenBLAS-0.2.20" is a folder under your current level, or something like ../OpenBLAS-0.2.20 if it is in another folder on the same level)

**Comment by fuentert** [comment]
Whoops, you're right, too much Unix and not enough Windows led me to add that extra slash on accident. However running "gcc -o test tests.c OpenBLAS-0.2.20/libopenblas.dll" returns an error saying that it can't find libopenblas.dll and I should reinstall. Even using the full path of "C:/folder/folder/folder/OpenBLAS-0.2.20/libopenblas.dll" returns this same error.

Maybe I'm just bad at Windows and I should just stick with Unix.

**Comment by martin-frbg** [comment]
Not sure how windows-like the behaviour of gcc on windows is supposed to be - have you tried a Unix-like dynamic link command like "-L/path/to/openBLAS-0.2.20 -lopenblas" ? (Or alternatively, use the libopenblas.lib in place of libopenblas.dll in your present command if you have such a (static library) file)

**Comment by fuentert** [comment]
I do not have a libopenblas.lib, only a libopenblas.dll, libopenblas.dll.a, and libopenblas.def. If I use a dynamic link command, I get an error that says that it can't find -lopenblas (which is the name I used when I did the make install).

**Comment by brada4** [comment]
Normally you can put .dll in current build directory and -lopenblas, then keep it in same place as your program.

**Comment by martin-frbg** [comment]
Can you post the directory layout (relative position of your tests.c file and the OpenBLAS-0.2.20 folder) and the exact commands and error messages ? (And I guess you could try static linking against the .dll.a )
Also, from the discussion in #1293 and depending on the flavor of mingw you are using, it may actually be looking for a "cygopenblas.dll" when you enter -lopenblas.

**Comment by fuentert** [comment]
First of all, thank you everyone for all of your suggestions. I'm still doing research on what could possibly be the problem, but at this point I think it is something silly with my commands or how I compiled OpenBLAS.

For tests.c, the path goes C:/folder1/folder2/Desktop
For my OpenBLAS-0.2.20 folder, its located in the same Desktop, and the contents would then be located in C:/folder1/folder2/Desktop/OpenBlas-0.2.20

First, I navigate to my Desktop and can view the files in my desktop (both the OpenBLAS folder and the c file can be found). I use the command gcc -o test tests.c  /OpenBLAS-0.2.29/libopenblas.dll, where I get the error:
gcc: error: /OpenBLAS-0.2.20/libopenblas.dll: No such file or directory

If I use the command gcc test tests.c -L/OpenBLAS-0.2.20/libopenblas.dll, it does compile. However, I then receive a system error pop up saying that the program can't start because libopenblas.dll is missing from my computer.

Using the command gcc -o test tests.c -L OpenBLAS-0.2.20 -lopenblas returns the error:
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lopenblas
collect2.exe: error: ld returned 1 exit status

**Comment by brada4** [comment]
To my understanding and experience Windows still uses slashes leaning other way than you type.
Can you provide full output of any gcc?
Any successes with clang or msvc? Any info on GCC version?

**Comment by fuentert** [comment]
I just tried using the other slashes with the same result, so its possible Windows recognizes both. The post above has a copy/paste of everything the gcc has spit out at me when I received an error.

I haven't tried clang or msvc, but I'll look into it shortly. I'll also try to find the gcc version in a few minutes as well to post.

**Comment by martin-frbg** [comment]
From what you posted above, gcc version appears to be 5.1. (I seem to remember somebody having problems with the tdm version of gcc earlier, but that was probably an unrelated issue). 
The system popup on program start after the successful compilation is probably because the openblas dll is not in any of the places that the system normally searches for dlls - as a quick workaround you could try copying it to the same folder where the test program is. 
One other quick thing to try is leaving out the space between "-L" and "OpenBLAS-0.2.20"

**Comment by brada4** [comment]
> gcc: error: /OpenBLAS-o.2.20/libopenblas.dll: No such file or directory

I see letter "small OU" where "number zero" should be. Clipboard sometimes does better than keyboard.

**Comment by fuentert** [comment]
Thanks Martin - I moved the dll file to the same location as tests.c, and when running the command 
"gcc -o test tests.c -L/OpenBLAS-0.2.20/libopenblas.dll", I get the below error message:

/tmp/ccbNRNxw.o:tests.c:(.text+0x188): undefined reference to 'cblas_sgemm'
/tmp/ccbNRNxw.o:tests.c:(.text+0x188): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `cblas_sgemm'
collect2: error: ld returned 1 exit status

To be fair, I do call cblas_sgemm from my tests.c. I use the below line of code to import it:
#include "C:\folder1\folder2\Desktop\OpenBLAS-0.2.20\cblas.h"

The actual line of code I use that uses cblas_sgemm is below:
cblas_sgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans, numRows, numCols, numCols, 1.0f, a[0], numRows, b[0], numRows, 0.0f, matrix[0], numRows;

While I understand the above might not make sense without the rest of the code, it matches the data types required for cblas_sgemm. It all seems to be pointing to the idea that my tests.c and the OpenBLAS files aren't really talking to each other and I'm unsure why.

**Comment by brada4** [comment]
-L PATH \ 
-l libname

**Comment by fuentert** [comment]
-l libname will not work; I've tried various times with different names and remaking the library under a new name a few times. Every time gcc will spit out:
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -llibname

**Comment by martin-frbg** [comment]
I do not see how your favorite "-L/OpenBLAS-0.2.20/openblas.dll" is expected to work either - all it does is define a nonexistent folder with that name, but never even try to link anything.

**Comment by martin-frbg** [comment]
Did you get this sorted ? Normally I'd expect
`gcc -o test tests.c -LOpenBLAS-0.2.20 -lopenblas.dll`
to work - note use of capital and lowercase L and no leading slash as it is a relative path. (You will need to add the OpenBLAS-0.2.20 folder path to the windows PATH variable, or to copy the libopenblas.dll to the same folder as the test program so that it gets found when your program is run).

**Comment by fuentert** [comment]
Unfortunately, none of the above worked. To (somewhat) remedy this, I copied the methods/variables I needed from OpenBLAS, then pasted them into my code. It's not recommended, but after almost a week of trying to get this to work to no avail and exhausting nearly almost all of my options, this was the only way to get this to compile and run. I'll close this issue since it's resolved.

**Comment by brada4** [comment]
about anything can load a DLL, like java jni, or excel addon, strange that it does not work here.

**Comment by martin-frbg** [comment]
A LoadLibrary() call within the program would also have been a possibility - maybe something went wrong with the building of OpenBLAS to begin with.
