### ISSUE TITLE
build OpenBLAS on hisi3519

### ISSUE THREAD

**Issue by bluekey2020** [xianyi/OpenBLAS#1324]
root@ubuntu:/opt/OpenBLAS-0.2.20# make TARGET=ARMV7 HOSTCC=gcc CC=arm-hisiv500-linux-gcc CROSS=1 CROSS_SUFFIX=arm-hisiv500-linux- BINARY=32 NOFORTRAN=1 libs
In file included from /usr/include/stdio.h:74:0,
                 from getarch.c:80:
/usr/include/libio.h:49:20: fatal error: stdarg.h: No such file or directory
 #include <stdarg.h>
                    ^
compilation terminated.
make: *** [getarch] Error 1
OpenBLAS: Detecting fortran compiler failed. Cannot compile LAPACK. Only compile BLAS.
make[1]: Entering directory `/opt/OpenBLAS-0.2.20/interface'
arm-hisiv500-linux-gcc -O2 -DMAX_STACK_ALLOC=2048 -marm -Wall -DF_INTERFACE_GFORT -fPIC -DNO_LAPACK -DNO_LAPACKE -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER= -DASMNAME=saxpy -DASMFNAME=saxpy_ -DNAME=saxpy_ -DCNAME=saxpy -DCHAR_NAME=\"saxpy_\" -DCHAR_CNAME=\"saxpy\" -DNO_AFFINITY -I.. -I. -UDOUBLE  -UCOMPLEX -c axpy.c -o saxpy.o
In file included from ../common.h:416:0,
                 from axpy.c:40:
../common_arm.h:134:2: error: #error "you must define ARMV5, ARMV6, ARMV7 or ARMV8"
 #error "you must define ARMV5, ARMV6, ARMV7 or ARMV8"
  ^
make[1]: *** [saxpy.o] Error 1
make[1]: Leaving directory `/opt/OpenBLAS-0.2.20/interface'
make: *** [libs] Error 1

**Comment by martin-frbg** [comment]
Which version of Ubuntu is this ? stdarg.h should normally come with the gcc compiler (and live somewhere under /usr/lib/gcc or /usr/lib64/gcc - the command `gcc -print-file-name=include` should tell you where exactly). The second error message is probably just a consequence of the failure to compile the getarch tool.

**Comment by bluekey2020** [comment]
At first ,thanks!   ubuntu version is 14.04!  It's gcc's version problem,I modify it before. Now it compile ok！
Thanks！
