### ISSUE TITLE
OpenBLAS crash with VS2010 Release

### ISSUE THREAD

**Issue by n2n2** [xianyi/OpenBLAS#1328]
Hello everyone, I compile an project on VS2010, finding out OpenBLAS crash in Release mode, any good advice?
IDE: MS VS2010; 
OS: Windows XP sp3 on VirtualBox. 
OpenBLAS version: v0.2.20, compiled using MSYS2 + gcc & gfortran 4.9.2. 
Project runs in Debug mode is ok, but crash in  Release mode, calling cblas_sgemv or cblas_sgemm will crash, code jump to crtexe.c the 552 line: mainret = wmain (argc, argv, envp);.
Both modes use default configuration, except for the dll library config.
The test code is as follows:

#include "StdAfx.h"
#include "cblas.h"
#include <stdio.h>

void main()
{
  int i=0;
  double A[6] = {1.0,2.0,1.0,-3.0,4.0,-1.0};         
  double B[6] = {1.0,2.0,1.0,-3.0,4.0,-1.0};  
  double C[9] = {.5,.5,.5,.5,.5,.5,.5,.5,.5}; 
  cblas_dgemm(CblasColMajor, CblasNoTrans, CblasTrans,3,3,2,1,A, 3, B, 3,2,C,3);

  for(i=0; i<9; i++)
    printf("%lf ", C[i]);
  printf("\n");
}
In addition, the downloaded OpenBLAS v0.2.15 and v0.2.14 Win32 prebuilt have the same problem.
Thank you.

**Comment by martin-frbg** [comment]
What build options did you use (multithreading, number fo threads in particular) ?
Also make sure that you got the arguments right in the cblas_dgemm call, at a glance it seems to me it should be ...,A,2, B... ?

**Comment by n2n2** [comment]
I use the default options of debug and release mode of VS2010, no multithreading. 
For release mode, compile commandline is  `/Zi /nologo /W3 /WX- /O2 /Oi /Oy- /GL /D "WIN32" /D "NDEBUG" /D "_CONSOLE" /D "_UNICODE" /D "UNICODE" /Gm- /EHsc /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Yu"StdAfx.h" /Fp"Release\blas_simple.pch" /Fa"Release\" /Fo"Release\" /Fd"Release\vc100.pdb" /Gd /analyze- /errorReport:queue `
Link commandline is `/OUT:"C:\project\blas_simple\Release\blas_simple.exe" /INCREMENTAL:NO /NOLOGO /LIBPATH:"C:\project\blas_simple\blas_simple" "libopenblas.dll.a" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "comdlg32.lib" "advapi32.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "odbc32.lib" "odbccp32.lib" /MANIFEST /ManifestFile:"Release\blas_simple.exe.intermediate.manifest" /ALLOWISOLATION /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /DEBUG /PDB:"C:\project\blas_simple\Release\blas_simple.pdb" /SUBSYSTEM:CONSOLE /OPT:REF /OPT:ICF /PGD:"C:\project\blas_simple\Release\blas_simple.pgd" /LTCG /TLBID:1 /DYNAMICBASE /NXCOMPAT /MACHINE:X86 /ERRORREPORT:QUEUE `

The test code was directly copied from  the sample code here:https://gist.github.com/xianyi/6930656#file-test_cblas_dgemm-c, so I think it can't be wrong.

When I use ...,A,2, B... arguments, the output printed in debug mode:
` ** On entry to DGEMM  parameter number  8 had an illegal value
0.500000 0.500000 0.500000 0.500000 0.500000 0.500000 0.500000 0.500000 0.500000`
Thank you for reply.

**Comment by brada4** [comment]
Array parameters must be pointers (see cblas.h for detail)

**Comment by martin-frbg** [comment]
@brada4 the code is correct (and runs on linux), guess we'd need to know the build options used for OpenBLAS (though it is a bit suspicious that xianyi's prebuilt binaries fail in the same way).

**Comment by n2n2** [comment]
I tried to replace the cblas_dgemm line into 
`cblas_dgemm(CblasColMajor, CblasNoTrans, CblasTrans,3,3,2,1,&A[0], 3, &B[0], 3,2,&C[0],3);`
and nothing improved.

**Comment by shoshia** [comment]
Try this:
msvc project properties : Linker:Advanced: Randomize base adress--it is set to 'YES'.
set it "NO" ---No (/DYNAMICBASE:NO)---

**Comment by n2n2** [comment]
Thank you for reply, but that dosn't work.

**Comment by n2n2** [comment]
I change my project to VS 2015, and every thing works fine.
Thanks guys!
