### ISSUE TITLE
Error while Linking libopenblas.a to another so

### ISSUE THREAD

**Issue by yws528** [xianyi/OpenBLAS#1330]
I'm using OpenBLAS to build my android lib of caffe, but some issue happened about OpenBLAS, could you help? Thanks.
*********************************************************************************************
OS: OS: ubuntu14.04_64bit_server
NDK: android-ndk-r15c
*********************************************************************************************
I have already build android_lib\openblas\lib\libopenblas.a, android_lib\openblas\lib\libopenblas_armv8p-r0.2.18.a
And libopenblas.a was built as follows:
 72 make clean
 73 make -j${N_JOBS} \
 74      CC="${CROSS_SUFFIX}gcc --sysroot=$SYSROOT" \
 75      FC="${CROSS_SUFFIX}gfortran --sysroot=$SYSROOT" \
 76      CROSS_SUFFIX=$CROSS_SUFFIX \
 77      HOSTCC=gcc USE_THREAD=1 NUM_THREADS=8 USE_OPENMP=1 \
 78      NO_LAPACK=$NO_LAPACK TARGET=$TARGET BINARY=$BINARY
 79 
 80 rm -rf "$INSTALL_DIR/openblas"
 81 make PREFIX="$INSTALL_DIR/openblas" install
*********************************************************************************************
And then, I start to build caffe using OpenBLAS:

ANDROID_ABI=${ANDROID_ABI:-"armeabi-v7a with NEON"}
WD=$(readlink -f "`dirname $0`/..")
N_JOBS=${N_JOBS:-4}
CAFFE_ROOT=${WD}/caffe
BUILD_DIR=${CAFFE_ROOT}/build

ANDROID_LIB_ROOT=${WD}/android_lib
BOOST_HOME=${ANDROID_LIB_ROOT}/boost
GFLAGS_HOME=${ANDROID_LIB_ROOT}/gflags
GLOG_ROOT=${ANDROID_LIB_ROOT}/glog
OPENCV_ROOT=${ANDROID_LIB_ROOT}/opencv/sdk/native/jni
PROTOBUF_ROOT=${ANDROID_LIB_ROOT}/protobuf
export LMDB_DIR=${ANDROID_LIB_ROOT}/lmdb
export OpenBLAS_HOME="${ANDROID_LIB_ROOT}/openblas"

rm -rf "${BUILD_DIR}"
mkdir -p "${BUILD_DIR}"
cd "${BUILD_DIR}"

cmake -DCMAKE_TOOLCHAIN_FILE="${WD}/android-cmake/android.toolchain.cmake" \
      -DANDROID_NDK="${NDK_ROOT}" \
      -DCMAKE_BUILD_TYPE=Release \
      -DANDROID_ABI="${ANDROID_ABI}" \
      -DANDROID_NATIVE_API_LEVEL=21 \
      -DANDROID_USE_OPENMP=ON \
      -DADDITIONAL_FIND_PATH="${ANDROID_LIB_ROOT}" \
      -DBUILD_python=OFF \
      -DBUILD_docs=OFF \
      -DCPU_ONLY=ON \
      -DUSE_LMDB=ON \
      -DUSE_LEVELDB=OFF \
      -DUSE_HDF5=OFF \
      -DBLAS=open \
      -DBOOST_ROOT="${BOOST_HOME}" \
      -DGFLAGS_INCLUDE_DIR="${GFLAGS_HOME}/include" \
      -DGFLAGS_LIBRARY="${GFLAGS_HOME}/lib/libgflags.a" \
      -DGLOG_INCLUDE_DIR="${GLOG_ROOT}/include" \
      -DGLOG_LIBRARY="${GLOG_ROOT}/lib/libglog.a" \
      -DOpenCV_DIR="${OPENCV_ROOT}" \
      -DPROTOBUF_PROTOC_EXECUTABLE="${ANDROID_LIB_ROOT}/protobuf_host/bin/protoc" \
      -DPROTOBUF_INCLUDE_DIR="${PROTOBUF_ROOT}/include" \
      -DPROTOBUF_LIBRARY="${PROTOBUF_ROOT}/lib/libprotobuf.a" \
      -DCMAKE_INSTALL_PREFIX="${ANDROID_LIB_ROOT}/caffe" \
      ..

make -j${N_JOBS} \
     HOSTCC=gcc USE_THREAD=1 NUM_THREADS=8 USE_OPENMP=1
rm -rf "${ANDROID_LIB_ROOT}/caffe"
make install/strip

cd "${WD}"
*********************************************************************************************
The Error shows as follow:
[ 75%] Linking CXX shared library ../../lib/libcaffe.so
~/workspace/caffe-android-lib-master/android_lib/openblas/lib/libopenblas.a(cblas_saxpy.o): In function `cblas_saxpy':
axpy.c:(.text+0x60): undefined reference to `omp_in_parallel'
axpy.c:(.text+0xd4): undefined reference to `omp_get_max_threads'
~/workspace/caffe-android-lib-master/android_lib/openblas/lib/libopenblas.a(cblas_sscal.o): In function `cblas_sscal':
scal.c:(.text+0x70): undefined reference to `omp_in_parallel'
scal.c:(.text+0xb0): undefined reference to `omp_get_max_threads'
~/workspace/caffe-android-lib-master/android_lib/openblas/lib/libopenblas.a(cblas_sgemv.o): In function `cblas_sgemv':
gemv.c:(.text+0x36c): undefined reference to `omp_in_parallel'
gemv.c:(.text+0x378): undefined reference to `omp_get_max_threads'
~/workspace/caffe-android-lib-master/android_lib/openblas/lib/libopenblas.a(cblas_sgemm.o): In function `cblas_sgemm':
gemm.c:(.text+0x240): undefined reference to `omp_in_parallel'
gemm.c:(.text+0x450): undefined reference to `omp_get_max_threads'
~/workspace/caffe-android-lib-master/android_lib/openblas/lib/libopenblas.a(cblas_daxpy.o): In function `cblas_daxpy':
axpy.c:(.text+0x60): undefined reference to `omp_in_parallel'
axpy.c:(.text+0xd4): undefined reference to `omp_get_max_threads'
~/workspace/caffe-android-lib-master/android_lib/openblas/lib/libopenblas.a(cblas_dscal.o): In function `cblas_dscal':
scal.c:(.text+0x70): undefined reference to `omp_in_parallel'
scal.c:(.text+0xb0): undefined reference to `omp_get_max_threads'
~/workspace/caffe-android-lib-master/android_lib/openblas/lib/libopenblas.a(cblas_dgemv.o): In function `cblas_dgemv':
gemv.c:(.text+0x36c): undefined reference to `omp_in_parallel'
gemv.c:(.text+0x378): undefined reference to `omp_get_max_threads'
~/workspace/caffe-android-lib-master/android_lib/openblas/lib/libopenblas.a(cblas_dgemm.o): In function `cblas_dgemm':
gemm.c:(.text+0x240): undefined reference to `omp_in_parallel'
gemm.c:(.text+0x450): undefined reference to `omp_get_max_threads'
~/workspace/caffe-android-lib-master/android_lib/openblas/lib/libopenblas.a(blas_server.o): In function `exec_blas._omp_fn.0':
blas_server_omp.c:(.text+0x20): undefined reference to `omp_get_num_threads'
blas_server_omp.c:(.text+0x28): undefined reference to `omp_get_thread_num'
blas_server_omp.c:(.text+0x168): undefined reference to `omp_get_thread_num'
~/workspace/caffe-android-lib-master/android_lib/openblas/lib/libopenblas.a(blas_server.o): In function `goto_set_num_threads':
blas_server_omp.c:(.text+0x2d0): undefined reference to `omp_set_num_threads'
~/workspace/caffe-android-lib-master/android_lib/openblas/lib/libopenblas.a(blas_server.o): In function `exec_blas':
blas_server_omp.c:(.text+0x678): undefined reference to `GOMP_parallel'
collect2: error: ld returned 1 exit status
src/caffe/CMakeFiles/caffe.dir/build.make:2720: recipe for target 'lib/libcaffe.so' failed
make[2]: *** [lib/libcaffe.so] Error 1
CMakeFiles/Makefile2:240: recipe for target 'src/caffe/CMakeFiles/caffe.dir/all' failed
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
*********************************************************************************************
I search some other Issues, and I think the issue is about USE_OPENMP=1, I have already set USE_OPENMP=1 in build script, but something went wrong.
Could you help me ? Thanks.

**Comment by martin-frbg** [comment]
These are linker errors. When you build OpenBLAS to use OpenMP, you need to link your code to that library as well - either add -fopenmp to your compiler flags, or add -lgomp to the link libraries.

**Comment by yws528** [comment]
@martin-frbg 
Thanks for your answer.
I'm a newer of it. Could you tell me how should I add -fopenmp flags or add -lgomp ? 
I just run https://github.com/sh1r0/caffe-android-lib/blob/master/build.sh
And I think it use https://github.com/sh1r0/caffe-android-lib/blob/master/scripts/build_openblas.sh to make openBLAS's libopenblas.a.      How should I modify the script ?  Thanks.

**Comment by martin-frbg** [comment]
Actually I am not sure - I see now that the caffe build script already sets -DANDROID_USE_OPENMP=ON as if it was expecting to use OpenMP. Did you change any of the build options for OpenBLAS or Caffe between build attempts by any chance ? (In that case, doing a `make clean` before retrying the build may help). Perhaps you could try redoing the build after setting CFLAGS in your environment, `export CFLAGS=-fopenmp`. 
(I see now that much the same topic came up in #975 some time ago, but unfortunately there never was a conclusion beyond suspecting some general problem with the system or ndk setup)

**Comment by martin-frbg** [comment]
Did you get any further with this ?

**Comment by yws528** [comment]
Maybe it's also caused by environment issue, someone can build it success with same code.
But I don't know why.
