### ISSUE TITLE
NO support for MIPS ingenic x1000

### ISSUE THREAD

**Issue by lucwan** [xianyi/OpenBLAS#1336]
openbals does not suppot ingenic x1000 MIPS processor

**Comment by martin-frbg** [comment]
I guess you could try building for the P5600 target (the only mips32 target currently available as far as I know). The xburst-specific simd extensions appear to be documented in ftp://ftp.ingenic.com/SOC/M200/X1000_M200_XBurst_ISA_MXU_PM.pdf if anyone wants to work on specific support for this hardware.

**Comment by xsacha** [comment]
I have a Creator CI20 / Ingneic JZ4780 (with XBurst). The generic mips32 target will work fine.

Did you want the XBurst stuff specifically?

**Comment by lucwan** [comment]
@xsacha i did the following changes

Change Makefile.systems

ifeq ($(CORE), P5600)
CCOMMON_OPT += -mips32r2 -mtune=mips32r2 -mhard-float $(MSA_FLAGS)
FCOMMON_OPT += -mips32r2 -mtune=mips32r2 -mhard-float $(MSA_FLAGS)
Endif


Change Makefile.prebuild

ifeq ($(TARGET), P5600)
TARGET_FLAGS = -mips32r2
endif


make BINARY=32 BINARY32=1 CC=mips-linux-gnu-gcc FC="mips-linux-gnu-gfortran -EL" RANLIB=mips-linux-gnu-ranlib AR=mips-linux-gnu-ar  HOSTCC=gcc CFLAGS="-EL" FFLAGS=$CFLAGS LDFLAGS=$CFLAGS TARGET=P5600 ONLY_CBLAS=1 USE_THREAD=0


i compiled openblas like above, it runs very slow (10x slower) on x1000e board, though it has a 1GHZ processor 16kb L1 cahce 64 mb ram.

also the same compiled binary crashes on  x1000 board with 32 mb ram but my program is not taking more than 2 mb ram and free ram on device is 24 mb. 

what should i do ?

**Comment by prasannatsm** [comment]
Off Topic - Apologies in advance.
@lucwan I am trying to port latest Linux kernel to X1000 board (patch at https://lkml.org/lkml/2017/9/27/472). I need help in testing it. I could not find your email so I posted here. Can we discuss further via email or in irc? Appreciate your help and time.
