### ISSUE TITLE
Does OpenBLAS 0.2.20 conflit with mxnet?

### ISSUE THREAD

**Issue by ghost** [xianyi/OpenBLAS#1339]
I compiled mxnet with OpenBLAS 0.2.20,  mxnet can use only **one** thread for decoding image data,  while with OpenBLAS 0.2.19,  mxnet use multithread for decoding data. I checked  multiple  compile options and finally roll back to OpenBLAS 0.2.19 so that mxnet multithread works well. Does OpenBLAS 0.2.20 conflit with mxnet?

**Comment by brada4** [comment]
While mxnet makes single BLAS call there is no problem that OpenBLAS spins multiple threads, though might be desirable to use development version past 0.2.20 to gain from small sample threading optimisations. You can adjust openblas threading levels with external environment variables. Start with disabling threading in mxnet (they have documentation), and compare with mxnet threading and single-threaded openblas (OPENBLAS_NUM_THREADS=1 will reduce multithreaded builds to single-thread)
Obvioulsy if both attempt to fill all cores present you get cores^2 threads and it goes between very slow and nowhere.
Please share timings - what you get by default, then what you get in each restricted case. Best is yours to keep.
