### ISSUE TITLE
Support Flang on Windows

### ISSUE THREAD

**Issue by isuruf** [xianyi/OpenBLAS#1342]
TODO list
 - Revert https://github.com/xianyi/OpenBLAS/commit/a1b87eac6bbe140aceb28d50e585979df471a460 because Flang requires symbols like `SGEMM_`
 - Use `CFortranInterface` like Netlib does. https://github.com/xianyi/OpenBLAS/blob/develop/lapack-netlib/LAPACKE/CMakeLists.txt#L7-L17.

cc @xoviat

**Comment by ghost** [comment]
Why was this closed?
