### ISSUE TITLE
cmake install only builds static libraries

### ISSUE THREAD

**Issue by cbcoutinho** [xianyi/OpenBLAS#1362]
I'm not sure if there was a cmake option anywhere to create shared libraries, but I seemed to have missed it. Building OpenBLAS normally creates both static and dynamic/shared libraries

Also, why does the cmake output generate libraries in PREFIX/lib64 whereas the regular make build places all the libraries into PREFIX/lib?

**Comment by martin-frbg** [comment]
This was changed only recently through PR #1279 (issue #1278), stating this was the way to do it with cmake. You can always change the lib path with ccmake, but I notice now that it could be we are missing a default BUILD_SHARED_LIBS option since the change that would make it more obvious that both types of libraries are available. Unfortunately cmake experience among the current set of developers is still quite limited.

**Comment by cbcoutinho** [comment]
Thanks for the reply. I think you're right, if there's no default value for BUILD_SHARED_LIBS then it probably won't show up as an option... I'll try forcing it that as an option from the command line.

If I wanted to hack on the CmakeLists, from which branch should I be working from to make a PR? Is that just the develop branch?

**Comment by martin-frbg** [comment]
Yes, the develop branch is where the action is.

**Comment by cbcoutinho** [comment]
I've been able to determine that the line `include(GNUInstallDirs)` is what sets up the include/lib64 install tree. Apparently cmake determines that OpenBLAS is a 64-bit library and puts it in the lib64 directory as such. Is there a reason the original `make` method places the library into `lib`? I'm assuming it's historical? I guess the question could also be phrased as: do you want the cmake build to be identical to the original `make` styled output?

Overriding this `LIBDIR` behavior is possible using the flag `CMAKE_INSTALL_LIBDIR=lib`, but I'm not sure if that's something OpenBLAS users would be expecting. What's the guiding principle for these decisions?

Also, regarding the static/shared library, setting `BUILD_SHARED_LIBS=ON` means that _only_ a shared library is built - not in addition to a static lib. I wrote a small project using cmake, and I was able to get around it like this:

```cmake
add_library(core-static STATIC ${LIB_SRCS}) # Static library
add_library(core-shared SHARED ${LIB_SRCS}) # Shared library

foreach( mylib core-shared core-static )
    target_link_libraries( ${mylib}
        ${LAPACK_LIBRARIES}
        ${BLAS_LIBRARIES}
    )

    set_target_properties( ${mylib}
        PROPERTIES
        OUTPUT_NAME     ${LIB_NAME}
        COMPILE_FLAGS   "${CMAKE_Fortran_FLAGS}"
        LINK_FLAGS      "${CMAKE_Fortran_LINK_FLAGS}"
        Fortran_MODULE_DIRECTORY ${mylib}
    )
endforeach()
```

The reason I had to do this was because the `add_library` call was essentially the one that compiled all the sources into object files, and all the `target_`-related calls were the ones that linked those object files into libraries. If you want to create both types, it would be beneficial to reuse the object files for both libraries instead of unnecessarily re-compiling them a second time.

**Comment by martin-frbg** [comment]
Quoting @xsacha the author of the aforementioned PR, in the issue I linked to above

> For instance, you would be hard-pressed to find any CMake project that builds both static and shared in the same configuration as that is not how it is intended to be used.

so there appear to be different expectations of how cmake and its autoconfiguration abilities are to be used for best effect. "Historically" there have only been Makefiles distributed with the project.

**Comment by brada4** [comment]
According to FHS 3.0  lib64 is 'alternate format library'
POSIX does not have that.
Why would one say anything linux-only and non-portable is 'modern' ?

**Comment by martin-frbg** [comment]
@brada4 not sure what your point is, the lib64 path here appears to be what cmake chooses by default when it encounters a 64bit Linux host. While lib is probably more portable, I believe it is still used (mostly?) for storing 32bit libraries on a host that has both.

**Comment by cbcoutinho** [comment]
My original question was if it was desired to make the cmake output directory structure identical (or at least close to) the autoconf setup. The fact that cmake has an opinionated default install directory structure is a non-sequitur - that can be changed based on the contents of the `CMakeLists.txt` file and the will of the OpenBLAS authors.

Building either static or shared (or both) is also possible, although a little kludge-y. I'm just curious what the OpenBLAS authors want. And by historical I meant historical w.r.t the OpenBLAS/GotoBLAS projects.

**Comment by martin-frbg** [comment]
Speaking only for myself, I want something that users can work with. The original intention for the added cmake support was to provide a functionality that is as close as possible to what the Makefile setup delivers, but according to the linked issue this may clash with the expectations of cmake users. Some of this is probably unavoidable due to fundamentally different approaches taken by the two build systems.

**Comment by xsacha** [comment]
To reproduce the autoconf static + shared currently in OpenBLAS CMake:
```bash
cmake -DBUILD_SHARED_LIBS .. && cmake --build .
cmake .. && cmake --build .
```

To reproduce static + shared inside the CMakeLists.txt with single build:
```CMake
foreach (TYPE IN ITEMS STATIC SHARED)
  if (BUILD_${TYPE}_LIBS)
    string (TOLOWER "${TYPE}" type)
    add_library(openblas-${type} ${TYPE} ... )
    target_include_directories(openblas-${type} ... )
    target_link_libraries(openblas-${type} ... )
  endif()
endforeach()
```

```bash
cmake -DBUILD_SHARED_LIBS -DBUILD_STATIC_LIBS .. && cmake --build .
```

Both of these would be fine, as long as you respect BUILD_SHARED_LIBS

**Comment by cbcoutinho** [comment]
I like this a lot - it's really succinct. Thanks for teaching me more about CMake

**Comment by brada4** [comment]
I think lib64 is dug from some templates shipped with cmake, probably it is vendor's bug if cmake default native arch uses other convention than (mostly-Makefiles) system packages.
i have seen lib/lib32 too, i think mandriva, now maybe mageia

**Comment by cbcoutinho** [comment]
The decision to override `lib` with `lib64` is made in the [Modules/GNUInstallDirs.cmake](https://github.com/Kitware/CMake/blob/baa19f658f947047dddac0228bcd52591829983d/Modules/GNUInstallDirs.cmake#L203-L212) module:

```cmake
...
  set(_LIBDIR_DEFAULT "lib")
  # Override this default 'lib' with 'lib64' iff:
  #  - we are on Linux system but NOT cross-compiling
  #  - we are NOT on debian
  #  - we are on a 64 bits system
  # reason is: amd64 ABI: http://www.x86-64.org/documentation/abi.pdf
  # For Debian with multiarch, use 'lib/${CMAKE_LIBRARY_ARCHITECTURE}' if
  # CMAKE_LIBRARY_ARCHITECTURE is set (which contains e.g. "i386-linux-gnu"
  # and CMAKE_INSTALL_PREFIX is "/usr"
  # See http://wiki.debian.org/Multiarch
...
```

The actual overriding of the `_LIBDIR_DEFAULT` variable is done later on down in the module...

Unfortunately, the amd64 ABI link is dead, I think this is an adequate replacement: [link](https://github.com/hjl-tools/x86-psABI/wiki/x86-64-psABI-r252.pdf)

**Comment by ghost** [comment]
I don't think it's a good idea to customize the library directory structure. We want all cmake projects to have a standard directory structure that's common and easy to automate.

**Comment by brada4** [comment]
Your OS distributor chose that way for you. if that does not match mulltilib config in /usr then it is best to report mistake to them. Cmake site configuration is way out of scope of any library upstream.

**Comment by martin-frbg** [comment]
So is anybody still in favor of changing the current cmake behaviour, or can this be closed ?

**Comment by ghost** [comment]
FWIW, I'm -1 on changing the existing CMake behavior.

**Comment by brada4** [comment]
https://github.com/xianyi/OpenBLAS/issues/1362#issuecomment-346200629 omits essential part of CMake module - script that distributor most likely customized to reflect their library layout. It differs radically on 3 linux systems I checked moment ago. Really nothing OpenBLAS can fix. 2nd party's package customized by 3rd party....

Putting a 64bit .so in /usr/lib is very likely to kill any strain of 32bit openblas around same place on almost all RPM distributions.

**Comment by cbcoutinho** [comment]
I don't think OpenBLAS has to fix anything - but just to be clear: the original automake setup already places a 64bit .so into $(prefix)/lib. Also, it creates static and dynamic libraries using the same name (`libopenblas.a` and `libopenblas.so`, which are softlinks to `libopeblas_hawsellp-r0.2.20.dev.a` and `libopenblas_haswellp-r0.2.20.dev.so`, respectively)

Since these are things cmake doesn't do by default, they would need to be hard-coded in to reflect the automake build. Or, as an alternative, have two forms of build output.

I think users of cmake would be expecting cmake output, and users of the automake builds would expect the older output. Is the fact that they are different a big deal?

**Comment by brada4** [comment]
It is documented that CMake and (posix) make build results are different. If they were same there was never a need for cmake/m4/automake/autoconf etc makefile generators.
There is no problem, one or other way you can dlopen() resulting library and call included BLAS calls.

**Comment by cbcoutinho** [comment]
I'm closing this because my original problem was solved, and I can overwrite the defaults in ways that doesn't require OpenBLAS to change upstream.

Thanks everyone for the help clearing up my original misunderstanding.

**Comment by bjodah** [comment]
For posterity:
Ended up here googling why cmake was putting the static library in lib64 on CentOS.
Turns out cmake takes an option to override this:
`-DCMAKE_INSTALL_LIBDIR="lib"`

hopefully it will help someone ending up here googling as well...
