### ISSUE TITLE
the result which calculate in  blas.dgemm  are inconsistent

### ISSUE THREAD

**Issue by wangyixiaohuihui** [xianyi/OpenBLAS#1370]
When I use spark mllib multi-layer-perceptron model to predict a vector, I found that the same vector gives different result sometimes in multithreading. I read the source code and found it is based on the BLAS lib. I made some test code for BLAS in multithreading.

I use BLAS dgemm utils to compute a matrix, the same matrix data gives different results when using multithreading.

My test code can be found on  https://github.com/wangyixiaohuihui/blas.git. In the test code, I make some artificial test data. To test it using Windows 10, add blas dll file in java class path.

When I use only one thread to run:

blas.dgemm(transa, transb, m, n, k,alpha, a, _a_offset, lda, b, _b_offset, ldb,beta, c, _c_offset, ldc)

the result is the same when running repeatedly. But using 5 or more threads to run the same data, blas.dgemm gives different results. This is confusing, why does the same data in blas.dgemm give different results?

Using Windows 10, add netlib-native_system-win-x86_64.dll to java class path.

**Comment by martin-frbg** [comment]
Are you actually using OpenBLAS, or the netlib reference implementation  (as suggested by your use of "netlib" in the dll name) ? If it is the netlib BLAS, which as far as I know does not do multihreading by itself, your own code is probably using the same array for storing (intermediate) results from several threads.

**Comment by brada4** [comment]
Google says it is 2mb sized dll, accelerated blas (any of them) starts at 10mb or so.
Your code concurrently writes some output to same memory that causes adverse effects in your [mmu](https://en.wikipedia.org/wiki/Memory_management_unit). You can fix it by using any sort of thread locking to prevent concurrent writes to same memory region (effectively turning your code in single-threaded serial calls)

**Comment by wangyixiaohuihui** [comment]
yes.  i have found the mistake.  if make  double[] cc=c.clone();  the result is right.
thanks.
