### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by zamazan4ik** [xianyi/OpenBLAS#1374]
Hello,
Do you know about [Conan](https://github.com/conan-io/conan)?
[Conan](http://docs.conan.io/en/latest/) is modern dependency manager for C++. And will be great if your library will be available via package manager for other developers.

[Here](https://github.com/bincrafters/conan-templates) you can find example, how you can create package for the library. 

If you have any questions, just ask :-)

**Comment by brada4** [comment]
OpenBLAS supports very generic LAPACK API, just like reference BLAS, ATLAS or MKL.
Does not look like your package manager does any of that.
Please close the issue and stop spamming people.

**Comment by martin-frbg** [comment]
I guess we would possibly accept a PR that adds the required conanfile.py (or whatever it is that your packager requires, as long as it is nonintrusive), but supporting any or all package managers out there does look to me to be beyond the scope of the OpenBLAS project. Note there is no rpm .spec or similar either, although a variety of packages are provided e.g. by Linux distributions. If conan.io relies on project developers alone to create their own packages, I doubt it will gain much traction.

**Comment by zamazan4ik** [comment]
Ok, thank you :-)
