### ISSUE TITLE
liblapacke.a

### ISSUE THREAD

**Issue by timjim333** [xianyi/OpenBLAS#1383]
I'm trying to install the opensource fluid solver SU2. During the install process, it errors when searching for the c lapack library (liblapacke.a), which I thought would be included in the OpenBLAS build. At least, I think it is the c lapack library but I'm not too familiar with this. I want to link to LAPACKE libraries (such as liblapacke.a) but they are not in the PREFIX/lib directory after compiling. I have made sure that NO_LAPACKE is commented out in Makefile.rule. Is there something I have missed? Thanks.

**Comment by brada4** [comment]
Lapacke+lapack+blas (i.e whole dependency chain, sometimes you need to add -lpthread too) are included in produced libopenblas*.a, you can rename it to your liking (or put symlink where liblapacke.a is expected)
Given age of your code make sure default build option BUILD_LAPACK_DEPRECATED=1 is not removed.
If you employ some threading - you might want to build single-threaded OpenBLAS to avoind N^2 core oversubscription, build defaults are fantastic for single-core caller on multi-core machine.

**Comment by brada4** [comment]
> --with-LAPACK-lib=ARG   LAPACK library directory, ARG = path to liblapacke.a
> --with-LAPACK-include=ARG   LAPACK include directory, ARG = path to lapacke.h

For permanent effect probably you need to change SU2 configure script to allow other name than liblapacke.a to accomodate OpenBLAS (Or ATLAS or MKL)

**Comment by timjim333** [comment]
Hi, thanks for the information - understood! One more question regarding the built libraries; when I look in my lib directory, I see some broken symlinks for `libopenblas.so` and `libopenblas.so.0` - is this supposed to be the case? Thanks.
```bash
FIa164@afispb07:~/programs/openblas/OpenBLAS-0.2.20$ ll *
bin:
total 0
drwxr-xr-x 2 FIa164 FIa  6 Nov 17 16:08 ./
drwxr-xr-x 5 FIa164 FIa 40 Nov 17 16:08 ../

include:
total 1372
drwxr-xr-x 2 FIa164 FIa     146 Dec  5 16:08 ./
drwxr-xr-x 5 FIa164 FIa      40 Nov 17 16:08 ../
-rw-r--r-- 1 FIa164 FIa   45648 Nov 17 16:08 cblas.h
-rw-r--r-- 1 FIa164 FIa   47356 Nov 17 16:08 f77blas.h
-rw-r--r-- 1 FIa164 FIa    4236 Nov 11 06:16 lapacke_config.h
-rw-r--r-- 1 FIa164 FIa 1245655 Nov 11 06:16 lapacke.h
-rw-r--r-- 1 FIa164 FIa     474 Nov 11 06:16 lapacke_mangling.h
-rw-r--r-- 1 FIa164 FIa   33161 Nov 11 06:16 lapacke_utils.h
-rw-r--r-- 1 FIa164 FIa    4949 Nov 17 16:08 openblas_config.h

lib:
total 27288
drwxr-xr-x 4 FIa164 FIa     4096 Dec  5 16:12 ./
drwxr-xr-x 5 FIa164 FIa       40 Nov 17 16:08 ../
drwxr-xr-x 3 FIa164 FIa       21 Nov 17 16:08 cmake/
lrwxrwxrwx 1 FIa164 FIa       37 Dec  5 16:12 liblapacke.a -> libopenblas_sandybridgep-r0.3.0.dev.a
lrwxrwxrwx 1 FIa164 FIa       37 Nov 17 16:08 libopenblas.a -> libopenblas_sandybridgep-r0.3.0.dev.a
-rw-r--r-- 1 FIa164 FIa 27938068 Nov 17 15:18 libopenblas_sandybridgep-r0.3.0.dev.a
lrwxrwxrwx 1 FIa164 FIa       38 Nov 17 16:08 libopenblas.so -> libopenblas_sandybridgep-r0.3.0.dev.so
lrwxrwxrwx 1 FIa164 FIa       38 Nov 17 16:08 libopenblas.so.0 -> libopenblas_sandybridgep-r0.3.0.dev.so
```

**Comment by martin-frbg** [comment]
If you build using cmake now, you need to give the option -DBUILD_SHARED_LIBS to cmake if you want the shared library as well. (See #1362). If the symlinks still get created even if there is no shared library, this is certainly a bug in the new cmake files...

**Comment by brada4** [comment]
Static linkage only:
https://github.com/su2code/SU2/blob/ec551e427f20373511432e6cd87402304cc46baa/configure#L1524
Dynamic linkage is of no use, i.e BLAS library will be included in final executable module

Looking at SU2 code following parameters will be need to override reference LAPACK with OpenBLAS:
--with-LAPACK-lib= directory where you made liblapack**e**.a symlink
--with-LAPACK-include= directory where lapacke.h is located i.e include

**Comment by timjim333** [comment]
I didn't explicitly call cmake, only GNU make (I believe).

**Comment by timjim333** [comment]
@brada4 So I shouldn't need to do anything else on the OpenBLAS side, is that correct?

**Comment by brada4** [comment]
scan resulting SU2 module with "strings" or "nm" for symbol(s) characteristic to openblas, like openblas_get_config etc, if you have any note of openblas in resulting output - congratulations, your module is linked to include OpenBLAS.

**Comment by brada4** [comment]
@timjim333 can you confirm symlink hack works? I proposed SU2 to permit other than reference lapacke. If that goes through this issue immediately disappears.

**Comment by timjim333** [comment]
I'll let you know as soon as it finishes building. When you say resulting output, do you mean in the build logs, or somewhere else?

**Comment by brada4** [comment]
su2 binary module.

**Comment by timjim333** [comment]
If I grep my install `bin` for `strings` and `nm`, I get matches but I don't know if they are related to Openblas - Is there any way I can check? Sorry, you might have to walk me through it!

```
FIa164@afispb07:~/programs/su2/SU2-5.0.0/bin$ grep nm *
Binary file _pysu2.so matches
Binary file SU2_CFD matches
Binary file SU2_DEF matches
Binary file SU2_DOT matches
Binary file SU2_GEO matches
Binary file SU2_MSH matches
Binary file SU2_SOL matches
FIa164@afispb07:~/programs/su2/SU2-5.0.0/bin$ grep strings *
Binary file _pysu2.so matches
Binary file SU2_CFD matches
Binary file SU2_DEF matches
Binary file SU2_DOT matches
Binary file SU2_GEO matches
Binary file SU2_MSH matches
Binary file SU2_SOL matches
```

**Comment by martin-frbg** [comment]
Please try either `nm _pysu2.so | grep openblas` or `strings _pysu2.so|grep openblas` (assuming that _pysu2.so is the su2 module, else try it on libSU2Core.a, libSU2.a)

**Comment by timjim333** [comment]
I tried `nm` and `strings` on all the modules but they all came up blank, except libSU2.a, which gave:
```
FIa164@afispb07:~/programs/su2/SU2-5.0.0_src/SU2_BASE/Common/lib$ nm libSU2.a  | grep openblas
nm: libcgns.a: File format not recognized
nm: libparmetis.a: File format not recognized
nm: libmetis.a: File format not recognized
nm: libtecio.a: File format not recognized
nm: libhdf5.a: File format not recognized
nm: libsz.a: File format not recognized
nm: libz.a: File format not recognized
```

**Comment by brada4** [comment]
I have built SU2 and it did not attempt to link Netlib BLAS or OpenBLAS, even validation of library in configure script passed in both cases.
I think we can leave this issue for consideration at upstream SU2, as it looks their build system's "LAPACK" parameter pair is essentially no-op for now (v5.0.0).

**Comment by martin-frbg** [comment]
Looking in the SU2 issue tracker, it seems there is nothing in the current SU2 codebase that actually calls any LAPACK function at the moment, just the configure hooks are there for any user code that may need them: https://github.com/su2code/SU2/issues/478  OK to close here ?
