### ISSUE TITLE
Patch for failing Cmake Android link

### ISSUE THREAD

**Issue by ayounes-nviso** [xianyi/OpenBLAS#1384]
Hello,

We have successfully cross-built and used OpenBLAS thanks to its cmake support using attached patch below. The program was complaining about missing sqrt symbol at startup, not at linking statge.

Please tell me if you need a pull request for it or if you can just integrate it.

Thanks,
Abdel

```patch
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -151,6 +151,11 @@ endif()
 # add objects to the openblas lib
 add_library(${OpenBLAS_LIBNAME} ${LA_SOURCES} ${LAPACKE_SOURCES} ${RELA_SOURCES} ${TARGET_OBJS} ${OpenBLAS_DEF_FILE})
 
+# NVISO PATCH
+if(ANDROID)
+  target_link_libraries(${OpenBLAS_LIBNAME} m)
+endif()
+
 # Handle MSVC exports
 if(MSVC AND BUILD_SHARED_LIBS)
   if (${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION} LESS 3.4)

```

**Comment by brada4** [comment]
Compilers tend to inline simple libm functions. Strange that this pops out just now (but logical, sqrt is used in code)

**Comment by ayounes-nviso** [comment]
Well, the issue is also present and fixed with plain make it seems:

https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android

``` bash
# Setup LDFLAGS so that loader can find libgcc and pass -lm for sqrt
export LDFLAGS="-L${NDK_BUNDLE_DIR}/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x -lm"
```

But I agree with you that this is quite weird that you need to pass the "-lm" option at all.
BTW we also noticed a number of linking issues if you reference libopenblas too many times (missing dsdot_k and the likes). So at the end we decided to just link statically, much less headache.

**Comment by brada4** [comment]
Formally based on code you must pass the option, but with optimising compilers of today those few fabs() and sqrt() calls could be all inlined.

**Comment by martin-frbg** [comment]
Patch committed, thanks
