### ISSUE TITLE
who can provide cross-compiler share library for AARCH64?

### ISSUE THREAD

**Issue by nosqlcoco** [xianyi/OpenBLAS#1385]
Include libcblas.so,liblapack_atlas.so and  libatlas.so
 libcblas.a, liblapack_atlas.a and  libatlas.a

**Comment by brada4** [comment]
Usually system vendors provide compilers. Atlas library is sort of competing product of OpenBLAS, and, unlike OpenBLAS, requires to be compiled (which includes few days of runtime calibration) on the target device.
As much as OpenBLAS is concerned:
If your target device is Android, head for Android NDK
If your target device is Linux - most likely your x86_64 release of same distribution has reasonable cross-compiler.
Unlikely any cross-compiler kit contains Fortran compiler to provide you LAPACK on top of BLAS.

**Comment by nosqlcoco** [comment]
how to install OpenBLAS ARM64 in ubuntu?

**Comment by martin-frbg** [comment]
See "how to build OpenBLAS for Android" in the wiki

**Comment by nosqlcoco** [comment]
@martin-frbg Of course, I build OpenBLAS for Android successfully,using
`
make USE_THREAD=0 TARGET=ARMV8 HOSTCC=gcc CC=arm-linux-androideabi-gcc AR=arm-linux-androideabi-ar NOFORTRAN=1 NO_LAPACKE=0 NO_SHARED=0 ARM_SOFTFP_ABI=1 libs
`
but I not found  share library(.so)

**Comment by martin-frbg** [comment]
Leave off the "libs" at the end of the line to get a full build, the instruction to stop at (static) "libs" is for older version that did not yet support shared libs on Android.

**Comment by brada4** [comment]
Also NO_LAPACKE=0 has no effect since it wraps fortran code called LAPACK into more C-like prototypes.
Androideabi+softfp is not AARCH64, it is 32bit emulation under 64bit system (think i386 EXE on win64)

**Comment by nosqlcoco** [comment]
OpenBLAS  support  AARCH64 by cross-compiler `aarmch64-linux-gnu-gcc`?

**Comment by brada4** [comment]
yes, thats the included vendor stuff you can use.
