### ISSUE TITLE
Building for UWP and 32-Bit

### ISSUE THREAD

**Issue by bobafat** [xianyi/OpenBLAS#1391]
Hello,

I'm trying to build OpenBlas with Lapack for UWP and 32-Bit. I use the Intel Fortran Compiler and generate the VS Files with Visual Studio 14 2015 - Generator. I am using Windows 10.

When building in VS Studio I get the following errors:

For project **gencblas**:
-  sed: -e expression #1, char 1: unknown command: `''

For project **genf77blas**:
- awk: 'BEGIN{print
- awk: ^ invalid char ''' in expression

And when building the fortran project libopenblas:
...
- openblas.def : error LNK2001: unresolved external symbol clanhp_
- openblas.def : error LNK2001: unresolved external symbol clanhs_
- openblas.def : error LNK2001: unresolved external symbol clanht_
- openblas.def : error LNK2001: unresolved external symbol clanhb_
...

Eventually Visual Studio crashes. Are the Linker errors due to gencblas and genf77blas not building? The errors of gencblas and genf77blas seem straightforward, but where do I fix them.

**Comment by brada4** [comment]
Latest intel fortran compiler does not support win32. Unresolved symbols posted are expected to be compiled by fortran compiler.

**Comment by bobafat** [comment]
@brada4 Thank you. I will try earlier versions of the compiler. Do you know how to fix the first two errors in gencblas and genf77blas. Are they required for Openblas to run correctly?

**Comment by brada4** [comment]
You need sed and awk in the path, adding just ifort ot just vcvarsall will not help, you need msys2 commands too. And you are walking unknown places already with fortran. So far best path is described here:
https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-in-Microsoft-Visual-Studio#build-openblas-for-universal-windows-platform

**Comment by martin-frbg** [comment]
Please try compiling the current git snapshot (available via the green "clone or download" button in the table heading under the "Code" tab). Among other improvements, this has the gencblas and genf77blas sections in CMakelists.txt rewritten to remove reliance on awk and sed.
