### ISSUE TITLE
conflicts of cblas APIs definition between OpenBLAS and Eigen 3.3.4

### ISSUE THREAD

**Issue by yang0773** [xianyi/OpenBLAS#1392]
Hi guys,

I hope to use OpenBLAS as a backend of Eigen 3.3.4 on Android/ARMv7. Compiling environment is ubuntu 16.04 + Android NDK r15c. When trying to compile the project, I encountered errors as follow(I picked one to paste here),

In file included from ././gemm.cpp:4:
In file included from /home/yangfan/workspace/study/openBLAS/cblas.h:5:
In file included from /home/yangfan/workspace/study/openBLAS/common.h:751:
/home/yangfan/workspace/study/openBLAS/common_interface.h:105:9: error: functions that differ only in their return type cannot be overloaded
void    BLASFUNC(dcopy) (blasint *, double *, blasint *, double *, blasint *);
~~~~    ^
/home/yangfan/workspace/study/openBLAS/common.h:185:24: note: expanded from macro 'BLASFUNC'
#define BLASFUNC(FUNC) FUNC##_
                       ^
<scratch space>:83:1: note: expanded from here
dcopy_
^
/home/yangfan/workspace/study/eigen-3.3.4/Eigen/src/Core/util/../../misc/blas.h:44:8: note: previous declaration is here
int    BLASFUNC(dcopy) (int *, double *, int *, double *, int *);
~~~    ^
/home/yangfan/workspace/study/eigen-3.3.4/Eigen/src/Core/util/../../misc/blas.h:9:24: note: expanded from macro 'BLASFUNC'
#define BLASFUNC(FUNC) FUNC##_
                       ^
<scratch space>:37:1: note: expanded from here
dcopy_

in common_interface.h of OpenBLAS,
void    BLASFUNC(scopy) (blasint *, float  *, blasint *, float  *, blasint *);
void    BLASFUNC(dcopy) (blasint *, double *, blasint *, double *, blasint *);
void    BLASFUNC(qcopy) (blasint *, xdouble *, blasint *, xdouble *, blasint *);
void    BLASFUNC(ccopy) (blasint *, float  *, blasint *, float  *, blasint *);
void    BLASFUNC(zcopy) (blasint *, double *, blasint *, double *, blasint *);
void    BLASFUNC(xcopy) (blasint *, xdouble *, blasint *, xdouble *, blasint *);

in misc/blas.h of Eigen,
int    BLASFUNC(scopy) (int *, float  *, int *, float  *, int *);
int    BLASFUNC(dcopy) (int *, double *, int *, double *, int *);
int    BLASFUNC(qcopy) (int *, double *, int *, double *, int *);
int    BLASFUNC(ccopy) (int *, float  *, int *, float  *, int *);
int    BLASFUNC(zcopy) (int *, double *, int *, double *, int *);
int    BLASFUNC(xcopy) (int *, double *, int *, double *, int *);

My Android.mk looks like this,
----------------------------------------------------------------------------------------------------
LOCAL_PATH := $(call my-dir)

#build a test executable
include $(CLEAR_VARS)

LOCAL_MODULE := gemm 
LOCAL_C_INCLUDES := /home/yangfan/workspace/study/eigen-3.3.4
LOCAL_C_INCLUDES += /home/yangfan/workspace/study/openBLAS
LOCAL_SRC_FILES := $(LOCAL_PATH)/gemm.cpp
LOCAL_CFLAGS += -DEIGEN_USE_BLAS

LOCAL_CFLAGS += -fPIC -frtti -fexceptions -lz -O3
LOCAL_LDLIBS += -lm -llog -lz
LOCAL_LDLIBS += $(LOCAL_PATH)/openblas-libs/libopenblas.a


Can somebody give some guides for using openblas in Eigen?

Cheers,
yangfan

**Comment by brada4** [comment]
Eigen [has documentation on usage of blas backends](https://eigen.tuxfamily.org/dox/TopicUsingBlasLapack.html).
-l -L should suffice as that document does not state to add any header files to compilation flags.

**Comment by yang0773** [comment]
Thanks @brada4 for your quick feedback.

**Comment by brada4** [comment]
i.e you have to provide location of F77 BLAS library, enable macro variable to use it and then use (include) eigen-provided cblas.h if at all, because BLAS backend will be called by functions mentioned in addition to provide own cblas over fortran blas wrapper (not a recommendation but few megabytes of cblas built by default into openblas library thus become completely unused)

**Comment by yang0773** [comment]
Got it.
Normally, two interface styles are supported in openblas (fortran-style and cblas-style). But Eigen seems to only support fortran-style function calls, i.e. dgemm_( ). In the case we don't need to provide header file.

**Comment by yang0773** [comment]
compilation based on android-ndk-r15b only generates cblas-style function calls without built-in fortran compiler. But I still puzzle the issue. Why does Eigen define different return types?

in common_interface.h of OpenBLAS,
```
void BLASFUNC(sgemm)(char *, char *, blasint *, blasint *, blasint *, float *,
	   float  *, blasint *, float  *, blasint *, float  *, float  *, blasint *);
void BLASFUNC(dgemm)(char *, char *, blasint *, blasint *, blasint *, double *,
	   double *, blasint *, double *, blasint *, double *, double *, blasint *);
```
in misc/blas.h of Eigen,
```
int BLASFUNC(sgemm)(const char *, const char *, const int *, const int *, const int *, const float  *, const 
          float  *, const int *, const float  *, const int *, const float  *, float  *, const int *);
int BLASFUNC(dgemm)(const char *, const char *, const int *, const int *, const int *, const double *, 
          const double *, const int *, const double *, const int *, const double *, double *, const int *);
```

Something missing for me? May I get my answer on Eigen forum.

**Comment by brada4** [comment]
openblas offers int32 and int64 calling convention on x86_64, apparently eigen does not allow to switch right away.
blas.h is not official netlib blas api header. you have to use one of cblas.h files.

**Comment by yang0773** [comment]
Thanks. It makes sense.
The issue can be closed if needed.

**Comment by martin-frbg** [comment]
Thanks for the feedback, closing now.

**Comment by flankechen** [comment]
@yang0773 I am having GeneralMatrixMatrix_BLAS.h:106: error: undefined reference to 'dgemm_' problem when using openblas in eigen for android armv7. 
android.mk

`#build a test executable
include $(CLEAR_VARS)
LOCAL_MODULE := test_qsml
LOCAL_C_INCLUDES += $(LOCAL_PATH)/Eigen/
LOCAL_C_INCLUDES += $(LOCAL_PATH)/openblas/install/include
LOCAL_SRC_FILES := $(LOCAL_PATH)/test_qsml.cpp
#LOCAL_SHARED_LIBRARIES := qsml

LOCAL_CFLAGS += -DEIGEN_USE_BLAS
LOCAL_CFLAGS += -fPIC -frtti -fexceptions -lz -O3 -std=c++11
LOCAL_LDLIBS += -lm -llog -lz

LOCAL_LDLIBS += $(LOCAL_PATH)/openblas/install/lib/libopenblas.a

include $(BUILD_EXECUTABLE)`


my cpp

`#include <iostream>
#include <chrono>
#include <Eigen/Dense>
using namespace Eigen;
using namespace std;

int main()
{


MatrixXd m = MatrixXd::Random(300,300);
MatrixXd n = MatrixXd::Random(300,300);
MatrixXd k;
std::chrono::steady_clock::time_point t1 = std::chrono::steady_clock::now();

//for(int i=0; i<10;i++){
k = m*n;
//}
std::chrono::steady_clock::time_point t2 = std::chrono::steady_clock::now();


double timeSpent =std::chrono::duration_cast<std::chrono::duration<double>>(t2-t1).count();
std::cout << "time used: " << timeSpent <<", " << k(0,0) << endl;

return 0;
}`

could you share your android.mk and how you setting eigen to use openblas
