### ISSUE TITLE
dnrm2 not exported

### ISSUE THREAD

**Issue by mnar53** [xianyi/OpenBLAS#1396]
I think that, when compiled for windows, function dnrm2 (and similars) is not exported in the dll.
I'm using binaries as in OpenBLAS-v0.2.19-Win64-int32, and no symbol related to nrm2 is present.

**Comment by brada4** [comment]
How do you check if symbol is present? Linux 'strings' shows 5 spellings of your function in that DLL.

**Comment by mnar53** [comment]
Sorry my mistake, i was loading an old version (probably 0.2.14), 0.2.19 is correct.

Normally i just link a function in vba ("Declare function dasum ........") and use it, if i have

problems then i load the dll into Notepad++ and check for the function.

Thx


________________________________
Da: Andrew <notifications@github.com>
Inviato: domenica 17 dicembre 2017 09:04
A: xianyi/OpenBLAS
Cc: mnar53; Author
Oggetto: Re: [xianyi/OpenBLAS] dnrm2 not exported (#1396)


How do you check if symbol is present? Linux 'strings' shows 5 spellings of your function in that DLL.

**Comment by martin-frbg** [comment]
Good to know the problem existed only in outdated versions.
