### ISSUE TITLE
clapack routines

### ISSUE THREAD

**Issue by marinejamoulle** [xianyi/OpenBLAS#1397]
Hey 
I'm using clapack for a project and I get this error : 
warning: implicit declaration of function ‘dgeev_’ is invalid in
C99 [-Wimplicit-function-declaration]
dgeev_(&not,&not,&dim,A,&dim,WR,WI,VL,&dim,VR,&dim,WORK,&dim,&INFO) 

Do you know where it comes from ?

**Comment by martin-frbg** [comment]
Not sure why you are asking here ? Also the compiler wii surely have provided some context including line numbers where it "thinks" the function dgeev_ is called without having been declared

**Comment by marinejamoulle** [comment]
In fact I really don't know how it works, I downloaded and installed BLAS and Lapack and placed the "cblas.h" and "f2c.h" files in the same folder as my program so I thought it would naturally take the function in the right file but it doesn't ?? I'm not experimented at all in this field.

**Comment by martin-frbg** [comment]
If you are using the old clapack package from netlib, there should also be a file named "clapack.h" I think. Does your code #include it somewhere ?

**Comment by brada4** [comment]
clapack is gone for 20 years. if it comes to rewrite you must adapt to official C interface of LAPACK called LAPACKE
