### ISSUE TITLE
Build issue on macOS 10.13.2 - develop branch

### ISSUE THREAD

**Issue by kthohr** [xianyi/OpenBLAS#1398]
Dear All,

I am trying to build the OpenBLAS development branch on a Mac system, but there appears to be an extraneous (or incomplete) archive call when compiling the Lapack routines:

```bash
ar -ru ../../../libopenblas_haswellp-r0.3.0.dev.a lapacke_cggsvp.o lapacke_cggsvp_work.o lapacke_dggsvp.o lapacke_dggsvp_work.o lapacke_sggsvp.o lapacke_sggsvp_work.o lapacke_zggsvp.o lapacke_zggsvp_work.o lapacke_cggsvd.o lapacke_cggsvd_work.o lapacke_dggsvd.o lapacke_dggsvd_work.o lapacke_sggsvd.o lapacke_sggsvd_work.o lapacke_zggsvd.o lapacke_zggsvd_work.o lapacke_cgeqpf.o lapacke_cgeqpf_work.o lapacke_dgeqpf.o lapacke_dgeqpf_work.o lapacke_sgeqpf.o lapacke_sgeqpf_work.o lapacke_zgeqpf.o lapacke_zgeqpf_work.o
ar -ru ../../../libopenblas_haswellp-r0.3.0.dev.a 
ar: no archive members specified
usage:  ar -d [-TLsv] archive file ...
	ar -m [-TLsv] archive file ...
	ar -m [-abiTLsv] position archive file ...
	ar -p [-TLsv] archive [file ...]
	ar -q [-cTLsv] archive file ...
	ar -r [-cuTLsv] archive file ...
	ar -r [-abciuTLsv] position archive file ...
	ar -t [-TLsv] archive [file ...]
	ar -x [-ouTLsv] archive [file ...]
make[3]: *** [../../../libopenblas_haswellp-r0.3.0.dev.a] Error 1
make[2]: *** [lapacke] Error 2
make[1]: *** [lapackelib] Error 2
make: *** [netlib] Error 2
```
I am using clang and gfortran v7 ('make CC=clang FC=gfortran-mp-7'), which has worked fine for versions 0.2.x, including the current release branch (0.2.21).

**Comment by martin-frbg** [comment]
This seems to be some sort of conflict between the lapacke.cmake file provided by OpenBLAS/cmake (which apparently lacks entries for the deprecated lapacke functions) and the original CMakeLists.txt in the lapack-netlib lapacke source directory. So the root cause is probably an oversight (by me) in the recent update to lapack 3.8.0. What I do not understand yet is (a) why it did not come up in my tests, nor in the automated builds and (b) why the CMakeLists.txt is even seen, when my understanding of
the reason for "our" lapacke.cmake is that these are precisely to avoid using the netlib-provided files.
(And perhaps (c) if the deprecation is a recent feature of 3.8.0, or if "our" lapacke.cmake has been incomplete for some versions already)

**Comment by martin-frbg** [comment]
Hmm. The lapacke_zgeqpf(_work) seem to have been dropped inadvertently in my update of lapacke.cmake for 3.7.0 back in february (so before 0.2.20). I realize now that the cmake build seems to always assume BUILD_LAPACK_DEPRECATED is set - it does not use the variable, but lists the deprecated functions among the regular ones, which may be a bug in itself although it has no bearing on the current issue (other than possibly explaining my mistake).
The lapacke functions "lost" through the bug appear to be Xgeqpf, Xggsvd and Xggsvp - I will prepare a PR. 
(Still this does not explain the error you see - are you building in a separate build directory, or directly in the source ?)

**Comment by kthohr** [comment]
Directly in the source after a fresh clone of the develop branch:

```bash
git clone -b develop --single-branch https://github.com/xianyi/OpenBLAS ~/Desktop/OBLAS
cd ~/Desktop/OBLAS
make CC=clang FC=gfortran-mp-7
```

**Comment by martin-frbg** [comment]
Ah, I see I had somehow assumed cmake so my PR is actually unrelated to your problem (although it does fix a bug).  Weird issue as I use make all the time myself - I assume you did not change anything in
Makefile.rule (?) Any suspicious warnings or error messages preceding the ar failure ?

**Comment by kthohr** [comment]
Nothing sticks out to me, no errors, but if it helps I put the full build output [here](http://www.kthohr.com/files/openblas_build.txt).

Edit: No changes (by me) to any files.

**Comment by martin-frbg** [comment]
Thanks, I just found the same empty ar call in my own build log, only with the GNU ar it is not fatal. This seems to be a feature of the Makefile provided by netlib - if you look in lapack-netlib/LAPACKE/src/Makefile at the end it has several calls to $(ARCH) which is actually "ar". Each tells it to collect a list of modules, which can be empty as I suspect $(EXTENDED) is when USEXBLAS is not set. I expect these calls all need an appropriate ifdef...endif around them to work as intended on macOS (and the PR needs to go to LAPACK-Reference as well).

**Comment by martin-frbg** [comment]
Looking at https://github.com/Reference-LAPACK/lapack/commit/38e8b31 this used to be a single "ar" call with both default and optional object groups until shortly after 3.7.0 (and among other things the object list was in danger of exceeding the maximum command line length on some systems). This would explain why the problem appears only on the develop branch, which has 3.8.0 as stated.

**Comment by kthohr** [comment]
Ah, great catch. Changing to
```
ifdef USEXBLAS
../../$(LAPACKELIB): $(OBJ_A) $(OBJ_B) $(DEPRECATED) $(EXTENDED) $(MATGEN)
	$(ARCH) $(ARCHFLAGS) $@ $(OBJ_A)
	$(ARCH) $(ARCHFLAGS) $@ $(OBJ_B)
	$(ARCH) $(ARCHFLAGS) $@ $(DEPRECATED)
	$(ARCH) $(ARCHFLAGS) $@ $(EXTENDED)
	$(ARCH) $(ARCHFLAGS) $@ $(MATGEN)
	$(RANLIB) $@
else
../../$(LAPACKELIB): $(OBJ_A) $(OBJ_B) $(DEPRECATED) $(MATGEN)
	$(ARCH) $(ARCHFLAGS) $@ $(OBJ_A)
	$(ARCH) $(ARCHFLAGS) $@ $(OBJ_B)
	$(ARCH) $(ARCHFLAGS) $@ $(DEPRECATED)
	$(ARCH) $(ARCHFLAGS) $@ $(MATGEN)
	$(RANLIB) $@
endif
```
or
```
../../$(LAPACKELIB): $(OBJ_A) $(OBJ_B) $(DEPRECATED) $(EXTENDED) $(MATGEN)
	$(ARCH) $(ARCHFLAGS) $@ $(OBJ_A)
	$(ARCH) $(ARCHFLAGS) $@ $(OBJ_B)
	$(ARCH) $(ARCHFLAGS) $@ $(DEPRECATED) $(EXTENDED)
	$(ARCH) $(ARCHFLAGS) $@ $(MATGEN)
	$(RANLIB) $@
```
fixed the error for me.

Thanks, Martin!

**Comment by martin-frbg** [comment]
Thanks for bringing it up. (I have opted for separate ifdefs for all three optional packages, will merge my own PR here as soon as the automated tests complete. The fix is also in the PR queue of Reference-LAPACK now, so this problem should not reappear when we synchronize with their next release.)

**Comment by kthohr** [comment]
Great! Thanks again.
