### ISSUE TITLE
Dynamic Link in VS2017 Failed

### ISSUE THREAD

**Issue by unanan** [xianyi/OpenBLAS#1402]
Following the instructions on the page:

> https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-in-Microsoft-Visual-Studio

I have dynamically linked the .dll and .dll.a into my project via the function "LoadLibrary"
But, the translater can't load the library "libopenblas.dll"
Can you help me to handle the problem? Thx in advance.

**Comment by martin-frbg** [comment]
Can you post the exact error message and/or code you get please ?

**Comment by unanan** [comment]
@martin-frbg OK
I use GetLastError() to see what's wrong
here is my codes ：

`	//dynamic quotation
	typedef double(*ptest)(OPENBLAS_CONST enum CBLAS_ORDER Order, OPENBLAS_CONST enum CBLAS_TRANSPOSE TransA, OPENBLAS_CONST enum CBLAS_TRANSPOSE TransB, OPENBLAS_CONST blasint M, OPENBLAS_CONST blasint N, OPENBLAS_CONST blasint K,
		OPENBLAS_CONST float alpha, OPENBLAS_CONST float *A, OPENBLAS_CONST blasint lda, OPENBLAS_CONST float *B, OPENBLAS_CONST blasint ldb, OPENBLAS_CONST float beta, float *C, OPENBLAS_CONST blasint ldc);

	HMODULE hDLL = LoadLibrary("E:/Projects/_C++/mtcnnlight_demo1/ConsoleApplication3/bin/libopenblas.dll");
	DWORD errorCode = GetLastError();
	cout << errorCode << endl;
	
	if (hDLL == NULL) cout << "Fail!" << endl;
	ptest cblas_sgemm = ptest(GetProcAddress(hDLL, "cblas_sgemm"));
	if (cblas_sgemm != NULL) cout << "Success!" << endl;
	else cout << "Fail!" << endl;`

and the No. of the error is 193
I check the official site of MSDN: 

> https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx

it says:

> ERROR_BAD_EXE_FORMAT

> 193(0xC1)

> %1 is not a valid Win32 application.
I use the x86 platform, and downloaded the Openblas library from the site:
https://sourceforge.net/projects/openblas/files/v0.2.14/
and I tried both x86 & x64 version. They both don't work on my computer...

**Comment by unanan** [comment]
I guess it may be caused by my computer's OS and environment...
When I run the project on a laptop, it is everything OK....

**Comment by martin-frbg** [comment]
So you did not build it yourself, but downloaded the prebuilt dlls ? In that case could you try the one from 
the v0.2.19 folder on sourceforge, which is at least not quite as ancient as 0.2.14 ? (Could be different Windows versions on desktop and laptop perhaps ?)
