### ISSUE TITLE
BLAS dotproduct slower than normal one

### ISSUE THREAD

**Issue by ghost** [xianyi/OpenBLAS#1405]
Hey guys, 
I'm developing an application on the ARM Cortex-A53 where the dotproduct needs to get calculated very often. To optimize timting I thought about using OpenBLAS. 
I changed this: 

		for(unsigned int i = 0; i < NUMBER_OF_INPUTS; i++)
		{
			tmp = source[i] * weights[i];
			output += tmp;	
		}	`
to this: 
`		output = cblas_sdot(NUMBER_OF_INPUTS, source, 1, weights, 1);`

But now the time for my program changes from about 30sec to like 60sec. 
I used: `openblas_set_num_threads(4);` but it takes the same time as with one thread. So I think the array is to small to take adavantage of threading and always uses just one thread, it has only about 100 elements.
But why is it so much slower than the other dotproduct implementation?

**Comment by brada4** [comment]
_dot depends on memory throughput, not CPU compute power. You can check interface/dot.c that it is always single-threaded.
Which also means that it is thread safe and you can parallelize your loop.
Probably it is worth inlining particular sdot kernel into your code to avoid library call which touches extra page while 400 bytes is practically needed.

**Comment by martin-frbg** [comment]
Did you provide a cpu target when you built OpenBLAS ? The generic Armv8 kernel uses a plain C function for sdot, while CortexA57 (which i believe is compatible with your a53) has an optimized assembly implementation.

**Comment by brada4** [comment]
@martin-frbg sample added per cycle in generic function half of aarch64 memory fetch. I think it would not hurt x86 to double the fat part of loop.
EDIT: I actually see (both) cc -O making unrolled chunks of loop. 
I wonder if just splitting loop with step 2**? (?double? cache line) hints that effect in controllable manner.
EDIT2: automatic stride prefetcher kicks in much later here than on amd64

**Comment by brada4** [comment]
@JonasNey do you observe same doubling time effect with 1000-sized inputs (at the point hardware prefetcher is certainly active)?

**Comment by martin-frbg** [comment]
Any updates on this ?

**Comment by brada4** [comment]
I had intent to double naive chunk in sdot.c ...
