### ISSUE TITLE
why change mnk to nmk for rowmajor  in gemm.c CNAME?

### ISSUE THREAD

**Issue by wl3b10s** [xianyi/OpenBLAS#1418]
why change mnk to nmk for rowmajor  in gemm.c CNAME?

in gemm.c line 337

  if (order == CblasRowMajor) {
    args.m = n;
    args.n = m;
    args.k = k;

**Comment by brada4** [comment]
Can you state a problem and provide a sample code?

**Comment by wl3b10s** [comment]
i haven't face problem. i just study the code and don't know for a A[M*K] B[K*N] input in rowmajor. before passing to the kernel operation, why they are exchanged in to  m<->n.  thanks.

**Comment by brada4** [comment]
Sometimes transforming matrix takes just swapping it's dimensions.

**Comment by brada4** [comment]
Could you close this issue as it is not 1) issue 2) related to OpenBLAS
