### ISSUE TITLE
can not run programm with openblas.dll build without DYNAMIC_ARCH option

### ISSUE THREAD

**Issue by shoshia** [xianyi/OpenBLAS#1421]
Hello
When I compile with
 `make BINARY=64 TARGET=HASWELL DYNAMIC_ARCH=1 HOSTCC=g++ NUM_THREADS=64 CC=gcc FC=x86_64-w64-mingw32-gfortran USE_THREAD=1 USE_OPENMP=1 OPENBLAS_COMPLEX_STRUCT=1 -j8`
 everything is fine, but when i compile without `DYNAMIC_ARCH=1` library compiles but during
execution i get 'error writing location' run time error

Environment:
Win 10 64 bit
msys2 64bit
gcc.exe (Rev1, Built by MSYS2 project) 7.2.0

Processor (CpuZ output):
Number of cores		4 (max 4)
	Number of threads	8 (max 8)
	Name			Intel Core i7 4790
	Codename		Haswell
	Specification		Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
	Package (platform ID)	Socket 1150 LGA (0x1)
	CPUID			6.C.3
	Extended CPUID		6.3C
	Core Stepping		C0
	Technology		22 nm
	TDP Limit		84.0 Watts
	Tjmax			100.0 °C
	Core Speed		998.7 MHz
	Multiplier x Bus Speed	10.0 x 99.9 MHz
	Stock frequency		3600 MHz
	Instructions sets	MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, EM64T, VT-x, AES, AVX, AVX2,

**Comment by martin-frbg** [comment]
Are gcc and gfortran the same version ? I suspect the only magic of using DYNAMIC_ARCH=1 here is that it suppresses running the "make tests" step as part of the build.

**Comment by shoshia** [comment]
yes they are from same distribution
$ gfortran --version
GNU Fortran (Rev1, Built by MSYS2 project) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.

**Comment by shoshia** [comment]
dows it make sense to try  `make BINARY=64 TARGET=HASWELL DYNAMIC_ARCH=1 HOSTCC=g++ NUM_THREADS=64 CC=gcc FC=x86_64-w64-mingw32-gfortran USE_THREAD=1 USE_OPENMP=1 OPENBLAS_COMPLEX_STRUCT=1 -j8 tests`? I'll check out

**Comment by shoshia** [comment]
it did tests without error. Now I cleaned and recompiling without   `DYNAMIC_ARCH`

**Comment by martin-frbg** [comment]
Unfortunately I cannot check the Windows build procedure myself. Is there any particular reason why you pass OPENBLAS_COMPLEX_STRUCT=1 as a build option ? I believe this is an internal setting, you may want to try FORCE_OPENBLAS_COMPLEX_STRUCT=1 instead if you really need it ?

**Comment by shoshia** [comment]
yes . I'm using visual studio 2013 with armadillo.
If I dont define LAPACK_COMPLEX_STRUCTURE I get errors. I thought they were related

**Comment by shoshia** [comment]
Will check again

**Comment by shoshia** [comment]
and one more question...will -O3 option give more speed up?

**Comment by shoshia** [comment]
test passed without 'DYNAMIC_ARCH=1'...i'l doing now without OPENBLAS_COMPLEX_STRUCT=1

**Comment by shoshia** [comment]
when try to run program it loads libgomp-1.dll is that normal?

**Comment by martin-frbg** [comment]
You told it to USE_OPENMP, so loading the GNU OMP implementation is correct.

**Comment by shoshia** [comment]
will try to build using gcc not msvc tomorrow

**Comment by shoshia** [comment]
i mean program(using mingw builds with ms visual studio right now)

**Comment by brada4** [comment]
should be `HOSTCC=gcc CC=x86_64-w64-mingw32-gcc`

**Comment by shoshia** [comment]
I can not put CC=x86_64-w64-mingw32-gcc becouse of this
https://github.com/xianyi/OpenBLAS/issues/339
compiler tries to execute  x86_64-w64-mingw32-ar but there is no such file.
 output 
 ```
$ which ar
/mingw64/bin/ar
```
So I did
`make BINARY=64 TARGET=HASWELL  HOSTCC=gcc NUM_THREADS=64 CC=gcc FC=x86_64-w64-mingw32-gfortran USE_THREAD=1 USE_OPENMP=1  FORCE_OPENBLAS_COMPLEX_STRUCT=1   -j8
`
Same thing --execution stops. May be another mingw64 build is needed? using msys2 mingw64

**Comment by shoshia** [comment]
from mingw64 whic one to choose posix-seh or win32-seh?
I plan to link use library with msvc 2013

**Comment by shoshia** [comment]
In mingw64 environmet program compiles links to openblas and runs Ok.
but now with mscv

**Comment by brada4** [comment]
If you don't have correct binutils it will never work.

**Comment by brada4** [comment]
Fedora and Debian mingw cross compilers work like charm. I don't think original could be as broken as you tell.

**Comment by shoshia** [comment]
what you mean in "correct binutils"?
mingw64 (msys2) openblas is building fine. programm is linking and working.
with DYNAMIC_ARCH option also everything is ok... it links in visual studio and
program works
Did you mean that visual studio 2013 is not enough good for dll linking DYNAMIC_ARCH=0 option?

and one more question. I tryed msys2 with mingw64 and separate mingw64 builds.
There is no  x86_64-w64-mingw32-ar.exe in archives, but there are:
 x86_64-w64-mingw32-gcc-ar.exe
and
ar.exe
Size of executables are different (x86_64-w64-mingw32-gcc-ar.exe and ar.exe)
also where is no
x86_64-w64-mingw32-ranlib.exe
but
x86_64-w64-mingw32-gcc-ranlib.exe
and 
ranlib.exe
all in mingw64 /bin folder. Size of executables are different (x86_64-w64-mingw32-gcc-ranlib.exe and ranlib.exe)

So which one to choose? and what is difference?(both are in 64bit toolchain)

**Comment by martin-frbg** [comment]
Can you tell exactly where "execution stops" when you do not specify DYNAMIC_ARCH ? Is it during the build of OpenBLAS, or when you try to run your own program that is linked against OpenBLAS ?
From my limited understanding of the mingw setup, the ar.exe and x86_64-w64-mingw32-gcc-ar.exe are basically the same thing, one probably a wrapper for the other just to satisfy different tool naming conventions for native or cross-compiling. I wonder if you really need the HOSTCC=gcc statement if you are compiling directly on Windows and not cross-compiling for Windows on a Linux system. Maybe at least the wrong names for ar.exe etc. come from the build system thinking you must be cross-compiling when you are not. Unfortunately I do not have a Windows system available for testing at the moment.

**Comment by shoshia** [comment]
When I run program linked against OpenBlas using msvc 2013 as soon as program tries to call LAPACKE_zgesv or arma::solve (for complex. use std::complex<double>), but I can LAPACKE_zgetri, arma::det for real matrix works


 BINARY=64 make  dll is produced but same problem....Don't understand magic :) ...
will use built with DYNAMIC_ARCH=1 option

**Comment by brada4** [comment]
Can you describe 'same problem's you are referring to from the point of view of a debugger or at least some linker or runtime error message or the code affected?
MSVC std::complex uses same binary representation as GCC.
Can you supplement your builds with exact options passed to build and the final report of the build when complete?
You don't need openmp on windows, default windows threads should be just fine.

**Comment by shoshia** [comment]
I removed msys2 and did fresh install+ only mingw64 64bit toolchain.
(till now i was using msys2 with sourceforge mingw-32 64 bit builds...Don't remember what mess i did :) )

Now things are little bit better some calls from OpenBlas work: LAPACKE_zgetri, arma::det for real matrix works...but calling armadillo's solve gives  'exception writing location'..
I'll post outputs tomorrow....

Just found this https://groups.google.com/forum/#!msg/openblas-users/lRzmnA8X1FU/gIi71oZABgAJ
will check tomorrow it is my openblas side or arma's side misconfiguration...

About openmp... You mean without openmp and setting max numtheds during compilation will enable
winpthread in mingw build?

**Comment by brada4** [comment]
I think winapi CreateThread is independent from POSIX APIs

**Comment by shoshia** [comment]
openmp disabled it still requires libwinpthead-1.dll... It is no mater what parameters i choose on openblas
side and on armadillo side (ARMA_BLAS_UNDERSCORE or ARMA_BLAS_CAPITALS or neither)
execution is halted calling 'zgesv' or 'getrf' (it's armadillos solve() and det() functions). see png left side call hierarchy.  MaxrixXvector multiplication works. cblas_dgemm call works
![image](https://user-images.githubusercontent.com/4439323/35048645-20b34d38-fbb7-11e7-9d1a-6880e3808a6e.png)

**Comment by martin-frbg** [comment]
The dependency on libwinpthread probably comes from a posix-seh or pthread-seh toolchain, from what I could find on the net it should go away if you use a win32-seh mingw. Do I understand correctly that it is now crashing even if you call the LAPACKE_zgesv function directly, with no Armadillo function involved ?
(Perhaps we would need a backtrace from an OpenBLAS that was built with DEBUG=1 )

**Comment by brada4** [comment]
Binary from sf.net could work too

**Comment by shoshia** [comment]
here is a buid info:
make BINARY=64  CC=x86_64-w64-mingw32-gcc FC=x86_64-w64-mingw32-gfortran USE_THREAD=1 USE_OPENMP=0 INTERFACE64=1 FORCE_OPENBLAS_COMPLEX_STRUCT=1  NUM_THREADS=8 -j8

programm defines:
#define HAVE_LAPACK_CONFIG_H
//#define ARMA_DONT_USE_LAPACK
//#define LAPACK_COMPLEX_CUSTOM
//#define LAPACK_COMPLEX_STRUCTURE
//#define LAPACK_COMPLEX_CPP
#define  LAPACK_COMPLEX_STRUCTURE
#define ARMA_DONT_USE_WRAPPER
#define ARMA_DONT_USE_CXX11
//#define ARMA_32BIT_WORD


#define ARMA_BLAS_LONG
#define ARMA_BLAS_LONG_LONG
#define NOMINMAX
calls:
	info = LAPACKE_zgesv(LAPACK_COL_MAJOR, (lapack_int)(Nm), 1, (lapack_complex_double*)(Aa.memptr()), (lapack_int)(Nm), (lapack_int*)(ipiva.memptr()), (lapack_complex_double*)(b.memptr()),Nm);
/*
LAPACKE_zgesv  error
 ** On entry to ZGESV   parameter number  4 had an illegal value
LAPACKE_zgetri  error
 ** On entry to ZGETRI parameter number  6 had an illegal value

**Comment by martin-frbg** [comment]
ZGESV parameter number 4 illegal would mean LDA is smaller than N although you gave Nm for both, so possibly something wrong with the passing of the Aa.memptr argument. (Unless Nm happens to be zero at this point, which it probably should not be.)

**Comment by shoshia** [comment]
yes , but same code works (info=0) with downloaded openblas binary with dynamic_arch On...
giving it up :) for now....

**Comment by brada4** [comment]
Can you run failing sample in x64dbg and show call stack and disasembly around EIP when crashed?

It is possible that single-CPU version was largely irrelevant for last 10 years and nobody tried it.
Here the workarounds (until bug & solution is found):
You can still have single threaded OpenBLAS by setting OPENBLAS_NUM_THREADS=1 before running your program, or setting thread number at runtime (you can find it in cblas.h, once you use the function your EXE essentially depends on OpenBLAS alone (Think ATLAS, MKL as replacements)

**Comment by shoshia** [comment]
Will try again tomorow.
Running openblas built with dynamic_arch On,can i check which architecture is used on runtime

**Comment by shoshia** [comment]
Ok..here it is...
Compile option:
make BINARY=64 DYNAMIC_ARCH=0 CC=x86_64-w64-mingw32-gcc FC=x86_64-w64-mingw32-gfortran USE_THREAD=1 USE_OPENMP=0 CONSISTENT_FPCSR=1  NUM_THREADS=32   -j8

exception at  LAPACKE_zgetrf
Same code with DYNAMIC_ARCH=1 works fine

![image](https://user-images.githubusercontent.com/4439323/35162901-4e7aa290-fd5e-11e7-9c84-aaf38f5481a0.png)

**Comment by shoshia** [comment]
One interesting thing..In debug version of program i changed some project property settings and it
works... :) 
But release version still crashes...

**Comment by shoshia** [comment]
OK I found it
One needs to set:
msvc project properties : Linker:Advanced: Randomize base adress--it is set to 'YES'.
You need to set it "NO" ---No (/DYNAMICBASE:NO)---
and everything works like a charm :) 

I also found one thing .
As you see I have not build with FORCE_OPENBLAS_COMPLEX_STRUCT=1  option and when i set
#define LAPACK_COMPLEX_CPP 
I get warnings 
`e\lapacke_config.h(102): warning C4190: 'lapack_make_complex_float' has C-linkage specified, but returns UDT 'std::complex<float>' which is incompatible with C
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\complex(714) : see declaration of 'std::complex<float>'
1>d:\ctwxs\testopenbpas\openblas\include\lapacke_config.h(103): warning C4190: 'lapack_make_complex_double' has C-linkage specified, but returns UDT 'std::complex<double>' which is incompatible with C
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\complex(846) : see declaration of 'std::complex<double>'`

I looked in lapacke_config.h and i see 2 lines without ifdef/undef/endif staff
`lapack_complex_float lapack_make_complex_float( float re, float im );
lapack_complex_double lapack_make_complex_double( double re, double im );`
and I put it in ifdef's like this

`#ifdef LAPACK_COMPLEX_STRUCTURE

lapack_complex_float lapack_make_complex_float( float re, float im );
lapack_complex_double lapack_make_complex_double( double re, double im );

#endif`

because if we have complex available no structures are needed, right?

Issue is solved....

Can I close it?

Thanks for a great soft :) ... openblas zgesv is faster then mkl's (tested 10 000x10 000 matrix)...few seconds but faster :)

**Comment by shoshia** [comment]
but have no idea why base adress randomization affects build with dynamic_arch_on=0 option :)

openblas was build with this options:
 make BINARY=64 DYNAMIC_ARCH=0 CC=x86_64-w64-mingw32-gcc FC=x86_64-w64-mingw32-gfortran USE_THREAD=1 USE_OPENMP=0 CONSISTENT_FPCSR=1  NUM_THREADS=32   -j8

**Comment by brada4** [comment]
Can you prime up ubuntu or debian virtual machine (vm player or virtualbox) and try cross-build same single-microarchitecture DLL:
```
make TARGET=HASWELL HOSTCC=gcc CC=x86_64-w64-mingw32-gcc \
FC=x86_64-w64-mingw32-gfortran CONSISTENT_FPCSR=1 \
MAKE_NB_JOBS=-1 NUM_THREADS=32 -j`nproc` -s
```
Sure you need to try all 3 involved compilers to get "command-not-found" telling which package is needed to install them.
I can do it in a week or so, maybe you manage first.

**Comment by shoshia** [comment]
I use slackware, but there is no mingw for slack...Will try ubuntu in virtualbox next week...

**Comment by martin-frbg** [comment]
Maybe your program is/was trying to load two different and incompatible instances of the CRT library, and disabling address space randomization makes it clearer that a libcrt is already loaded ? Or it is the address space layout randomization playing with the function pointers itself - in DYNAMIC_ARCH builds, there is an additional table of entry points for all the cpu-specific alternatives of each function generated that may have worked around the problem.
However, this linker setting appears to be the default since at least VS2012 so I wonder why this has not come up before.

**Comment by shoshia** [comment]
there is no need of mingw32-64 crt dll library for build (I have not added mnigw64 in PATH, just copying ddl's what are needed in program's exe folder)...May be it is linked statically...I did native mingw build..
Log:
```
x86_64-w64-mingw32-g++.exe -L..\openblas\lib -o bin\Release\testarmamingw.exe obj\Release\main.o obj\Release\Timer.o  -m64 -static-libgcc -static-libstdc++   -lm  ..\openblas\lib\libopenblas_haswellp-r0.3.0.dev.a C:\msys64\mingw64\lib\gcc\x86_64-w64-mingw32\7.2.0\libgomp.dll.a C:\msys64\mingw64\lib\gcc\x86_64-w64-mingw32\7.2.0\libquadmath.dll.a C:\msys64\mingw64\lib\gcc\x86_64-w64-mingw32\7.2.0\libgfortran.dll.a
Output file is bin\Release\testarmamingw.exe with size 4.30 MB
Process terminated with status 0 (0 minute(s), 0 second(s))
```
But crt library is included some where right? and this 'somewhere' can be openblas dll?

**Comment by shoshia** [comment]
Hello brada4 
I did that build.
Notes:
1.If DINAMICBASE is OFF in msvc project settings program runs on windows. If no--- crashes..same as mingw build on windows case.
2.It is slow(2x)(lapacke zgesv on 10000x10000 matrix) compare to build with same options(and openmp is OFF) done on windows mingw-64
3.When  ubuntu cross platform build is used in msvc, compiler does not complain about 
 `warning C4190: 'lapack_make_complex_float' has C-linkage specified, but returns UDT 'std::complex<float>' which is incompatible with C`
4. During ubuntu build there is a warning from ar.exe 'option 'u' is ignored'

p.s.

It seems we need at least (dllimport) part in header files to make dll work with msvc without 'dynamicbase magic'

**Comment by brada4** [comment]
it has to work with dynamicbase:on aka ASLR

**Comment by shoshia** [comment]
I did some search on the net and it seems it was binutils issue in 2016...
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=836365

**Comment by brada4** [comment]
Deficiency is in OpenBLAS, semantically similar ASLR mechanism is present in all linux where no problems are seen. Typically it is some wrong assumption that subsequent malloc() are allocated in order, so you can try to address next data chunk from previous base adding size of first allocation. 
If you cannot use dynamic_arch build let me suggest to patch (in principle buggy) DLL taking out ASLR options (dynamicbase and highentropyva) while problem is found:
https://docs.microsoft.com/cpp/build/reference/editbin-options

**Comment by martin-frbg** [comment]
Do you see these errors also with functions that do not take complex arguments, or is it "only" happening when the various make_complex_float functions get involved ?

**Comment by shoshia** [comment]
@brada4   build with dynamic_arch=1 is fine. No need to disable dynamicbase.
Tryed binedit /dynamicbase libopenblas.dll but same thing.

@martin-frbg  
No it happens with lapacke calls, for example  `LAPACKE_dgetrf` and solver calls from armadillo or eigen--in general level 3 calls

Here is 

`dumpbin.exe /headers libopenblas.dll `output
[dumpbin.txt](https://github.com/xianyi/OpenBLAS/files/1659987/dumpbin.txt)

and as you see there is no aslr in OPTIONAL HEADER VALUES:

                ```
  Dynamic base                    <==  this
                   NX compatible    <==  nor this
```

**Comment by brada4** [comment]
I mean you wanted to find a bug in debian or something. You can edit PE file attributes on Windows.

**Comment by martin-frbg** [comment]
Weird. No idea why LAPACKE in particular would suffer from ASLR, or why DYNAMIC_ARCH would work around it when (I believe) it "only" adds a table of entry points for the cpu-specific functions.

**Comment by brada4** [comment]
Yes, you can clear 2 ASLR flags in DLL to make it work, but still to determine why more code is less prone to a bug than 10x more....

**Comment by shoshia** [comment]
Interesting thing  I added
` -Wl,--dynamicbase -Wl,--nxcompat -Wl,--high-entropy-va` in exports/Makefile.
now dumpbin shows :
` 160 DLL characteristics
                   High Entropy Virtual Addresses
                   Dynamic base
                   NX compatible`
but when dynamicbase is enable in msvc options dll  crashes again, when it is disable in mscv works fine :)

so this options can be added

**Comment by shoshia** [comment]
Ok ..i made mscv to tell something more usefull:
`Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at LAPACKE_dgetrf(Int32 , Int32 , Int32 , Double* , Int32 , Int32* )
   at matInv(Double* A, UInt32 n)
   at main(Int32 argc, SByte** argv)
   at mainCRTStartup()
`
this was my mistake for purpose to make some debug.... not related to openblas...

**Comment by brada4** [comment]
High Entropy VA space is extreme edition of dynamicbase.

**Comment by shoshia** [comment]
@brada4  without entropy setting it is a same
@martin-frbg  will try build without lapack...
....
blas functions work fine in both cases..

**Comment by brada4** [comment]
Can you try cross-compiled DLL from here https://github.com/xianyi/OpenBLAS/issues/1437#issuecomment-361856808
In that issue it became apparent that some Windows MinGW toolsets build bad DLLs
