### ISSUE TITLE
How to review C language implementing BLAS?

### ISSUE THREAD

**Issue by aqsc** [xianyi/OpenBLAS#1423]
**How to review C language implementing BLAS?
Is OpenBLAS implemented by  Fortran language and compiled to alternative C language? Or is OpenBLAS also  coded in C language?**

**Comment by martin-frbg** [comment]
Not sure what you mean by "how to review" ? The BLAS part of OpenBLAS is implemented in C with cpu-specific assembler code for speed, the LAPACK part is copied from the "netlib" reference implementation which is written in FORTRAN but provides C bindings (the LAPACKE functions) as well.

**Comment by brada4** [comment]
Is it some sort of academic assignment task?

**Comment by aqsc** [comment]
yes， just  the academic task...  I want to analysis the Matrix and vector operations in C language, but it seems that  the code is written in Fortran  and compiled to C, so  I do not know how to analysis...

**Comment by brada4** [comment]
OpenBLAS is written in C. Not sure where you got idea about it being written in Fortran.

**Comment by martin-frbg** [comment]
The github language tag says "Fortran" as that comes from automatic analysis of the code - and the lapack code in lapack-netlib contains the most source lines (although only parts of it are used in OpenBLAS).
You will want to look at the code under /driver, which calls into machine-specific assembler routines from the appropriate subdirectory of /kernel. A _very_ short outline is provided in https://github.com/xianyi/OpenBLAS/wiki/Developer-manual

**Comment by aqsc** [comment]
Throught the path : OpenBLAS-0.2.20\source\lapack-netlib\CBLAS\src , we can find the source files in C language, and the interface of all the functions, such as cblas_dgemm(), cblas_dgemv() , and so on. But research into the cblas_dgemm(),  I find it uses the F77_dgemm() and other function interfaces , which are written in Fortran language...

**Comment by martin-frbg** [comment]
The BLAS and CBLAS under lapack-netlib are not used in OpenBLAS, it is just more convenient to include the whole "netlib" LAPACK source tree which happens to include this reference implementation of BLAS as well. 
The "real" cblas_dgemm() etc. are created from the C sources in `interface` - note you will only find generic files like gemm.c there, the Makefile will invoke the compiler with appropriate definitions of DOUBLE, CBLAS etc to generate sgemm.o, dgemm.o, cblas_sgemm.o, cblas_dgemm.o etc from them in turn.

**Comment by brada4** [comment]
OpenBLAS is written in C provides fortran77 and cblas API. It is binary compatible with BLAS part of netlib reference LAPACK, just faster in most cases. Also it includes LAPACk and lapacke API built from reference code, but using accelerated functions behind the scenes. You can find API documentation around netlib lapack pages, or (more expanded but less applicable to reference API )docs for intel mkl.
