### ISSUE TITLE
Building with VS2017 fails

### ISSUE THREAD

**Issue by joa-quim** [xianyi/OpenBLAS#1424]
First error was that it insisted in requiring gfortran so I tricked it my making a symlink with flang.exe.
Next error, which I could not solve is this:

```
(C:\programs\Miniconda3) V:\openblas\build>cmake --build . --config Release
ninja: error: 'openblas.def', needed by 'lib/liblibopenblas.dll', missing and no known rule to make it
```

apparently openblas.def should have been generated in previous step, but it wasn't

**Comment by isuruf** [comment]
Are you using latest master of OpenBLAS? What is the cmake generator and the options you used?

**Comment by joa-quim** [comment]
Yes, 0.2.20 and I'm following the instructions of point 1 of

https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-in-Microsoft-Visual-Studio

**Comment by isuruf** [comment]
You need to use openblas git version for that.

**Comment by joa-quim** [comment]
Well, then perhaps change the entry sentence. 
```
As of OpenBLAS v0.2.15, we support MinGW and Visual Studio (using CMake to generate visual studio solution files) to build OpenBLAS on Windows.
```

**Comment by joa-quim** [comment]
Hmm, not better

```
-- The Fortran compiler identification is unknown
flang.exe: warning: argument unused during compilation: '-E' [-Wunused-command-line-argument]
flang.exe: error: linker command failed with exit code 1120 (use -v to see invocation)
-- Check for working Fortran compiler: C:/programs/Miniconda3/Library/bin/flang.exe
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_Fortran_PREPROCESS_SOURCE
CMake Error at C:/programs/CMake/share/cmake-3.8/Modules/CMakeTestFortranCompiler.cmake:30 (try_compile):
  Failed to generate test project build system.
Call Stack (most recent call first):
  cmake/f_check.cmake:24 (enable_language)
  cmake/prebuild.cmake:84 (include)
  cmake/system.cmake:118 (include)
  CMakeLists.txt:44 (include)
```

**Comment by brada4** [comment]
flang detection is only with development version

**Comment by joa-quim** [comment]
This was with development version.

**Comment by martin-frbg** [comment]
Your version of CMAKE is too old to recognize flang - it seems that the relevant definitions were added to cmake in August as https://gitlab.kitware.com/cmake/cmake/commit/2f3a07a9 so you would need at least CMAKE 3.10.0

**Comment by isuruf** [comment]
Actually for recognizing flang on windows, you need the development version of cmake. (Or use the cmake from conda)

**Comment by joa-quim** [comment]
Thanks, updated cmake and advanced quite a bit ... but it stops with hundreds of errors like

```
flang.exe: error: no such file or directory: 'CMakeFileslibopenblas.dirlapack-netlibLAPACKEutilslapacke_z_nancheck.c.obj'
flang.exe: error: no such file or directory: 'CMakeFileslibopenblas.dirlapack-netlibLAPACKEutilslapacke_ztr_trans.c.obj'
flang.exe: error: no input files
ninja: build stopped: subcommand failed.
```

A missing slash separator apparently because, for example, the ``lapacke_ztr_trans.c.obj`` file exists in

``V:\openblas\build\CMakeFiles\libopenblas.dir\lapack-netlib\LAPACKE\utils``

**Comment by joa-quim** [comment]
One more try. I hand edited the ``build.ninja`` file and changed all ``\`` by ``/`` and the above errors went way, but now

```
[2/3] Linking Fortran shared library lib/libopenblas.dll
FAILED: lib/libopenblas.dll lib/libopenblas.lib
cmd.exe /C "cd . && C:\programs\Miniconda3\Library\bin\flang.exe  -Wall  /machine:x64 /debug /INCREMENTAL /DEF:V:/openblas/build/openblas.def  /DEF:openblas.def -shared  -o lib/libopenblas.dll @CMakeFiles/libopenblas.rsp  && cd ."
flang.exe: error: no such file or directory: '/machine:x64'
flang.exe: error: no such file or directory: '/debug'
flang.exe: error: no such file or directory: '/INCREMENTAL'
flang.exe: error: no such file or directory: '/DEF:V:/openblas/build/openblas.def'
flang.exe: error: no such file or directory: '/DEF:openblas.def'
ninja: build stopped: subcommand failed.
```

**Comment by isuruf** [comment]
Did you clean the build directory after changing cmake version?

**Comment by joa-quim** [comment]
No, I hadn't but it makes no difference. Same errors.

**Comment by joa-quim** [comment]
Sorry, cleaned the ``build`` dir of another project. Redoing it now.

**Comment by joa-quim** [comment]
but again, no difference. Still errors.

**Comment by vakonovalov** [comment]
I was able to build OpenBLAS (recent commit c7b55b6082c472dce0acc6c91016318328bebe62 from `develop` branch) on Windows. I used VS2015, i don't know if it would work with VS2017.
The problem with `CMAKE_Fortran_PREPROCESS_SOURCE` is indeed solved by installing a new version of CMake. I used 3.10.2.

Then, however, there were errors with linking:
```
[2/3] Linking Fortran shared library lib\openblas.dll
FAILED: lib/openblas.dll lib/Release/openblas.lib
cmd.exe /C "cd . && <PATH_TO_CONDA>\Library\bin\flang.exe    /machine:x64 /INCREMENTAL:NO /DEBUG /OPT:REF /OPT:ICF /DEF:<PATH_TO_OPENBLAS>\OpenBLAS-develop\build\openblas.def  /DEF:openblas.def -shared  -o lib\openblas.dll @CMakeFiles/openblas.rsp  && cd ."
ninja: build stopped: subcommand failed.
```
Using `build.ninja` i determined that `Fortran_SHARED_LIBRARY_LINKER__openblas` is responsible for incorrect formation of this command.
In `rules.ninja` i changed
```
rule Fortran_SHARED_LIBRARY_LINKER__openblas
  command = cmd.exe /C "$PRE_LINK && <PATH_TO_CONDA>\Library\bin\flang.exe  $LANGUAGE_COMPILE_FLAGS $ARCH_FLAGS $LINK_FLAGS -shared $SONAME_FLAG$SONAME -o $TARGET_FILE @$RSP_FILE  && $POST_BUILD"
```
to
```
rule Fortran_SHARED_LIBRARY_LINKER__openblas
  command = cmd.exe /C "$PRE_LINK && link  $LANGUAGE_COMPILE_FLAGS $ARCH_FLAGS $LINK_FLAGS /DLL /OUT:$TARGET_FILE @$RSP_FILE  && $POST_BUILD"
```

But that was not all. There was another small bug:
```
[3/3] Linking C executable utest\openblas_utest.exe
FAILED: utest/openblas_utest.exe
.....
LINK : fatal error LNK1181: cannot open input file "lib\Release\openblas.lib"
ninja: build stopped: subcommand failed.
```

This problem was solved by manually copying `openblas.lib` from `lib` to `lib\Release`
After these fixes, the build was finally completed.

**Comment by isuruf** [comment]
@vakonovalov, can you remove your changes and try with cmake-3.11.0 and see if it succeeds or not?

**Comment by vakonovalov** [comment]
I tried to build OpenBLAS using CMake 3.11.0. The build was successful, there was no need for my intervention in the process. 

I noticed that the rule `Fortran_SHARED_LIBRARY_LINKER__openblas` have changed to
```
rule Fortran_SHARED_LIBRARY_LINKER__openblas
  command = cmd.exe /C "$PRE_LINK && D:\Programs\CMake\bin\cmake.exe -E vs_link_dll --intdir=$OBJECT_DIR --manifests $MANIFESTS -- D:\Programs\MICROS~1.0\VC\bin\amd64\link.exe /nologo @$RSP_FILE  /out:$TARGET_FILE /implib:$TARGET_IMPLIB /pdb:$TARGET_PDB /dll /version:0.3 $LINK_FLAGS   && $POST_BUILD"
```
Now it works correctly. Also, there was no need to manually copy `openblas.lib` from `lib` to `lib\Release`.

So, with CMake 3.11.0 it seems that everything works fine.

**Comment by martin-frbg** [comment]
According to #1521, building with VS2017 should work as well with current conda/cmake/ninja/flang
