### ISSUE TITLE
How to build openblas on eclipse atd&ndk environment?

### ISSUE THREAD

**Issue by jiangfan2** [xianyi/OpenBLAS#1427]
I developed android ndk program using win7  eclipse  adt&ndk environment. But openblas Makefile can not be used directly or transfer to android.mk. How to build openblas on eclipse atd environment?

**Comment by brada4** [comment]
Something like 
include ${LOCAL_PATH}/OpenBLAS-0.3.0/Makefile

**Comment by martin-frbg** [comment]
Did that suggestion work, or is this issue still unresolved ?
