### ISSUE TITLE
-march=native breaks cross-compilation

### ISSUE THREAD

**Issue by andrew-wja** [xianyi/OpenBLAS#1430]
Hello,

When cross-compiling OpenBLAS, in lapack-netlib/make.inc, the statement `override CFLAGS      = -march=native -mtune=generic ...` breaks the build, because a cross compiler (for example aarch64-linux-gnu-gcc) does not understand the `-march=native` option.

This is the only file in the repository containing the string `-march=native` according to fgrep.

Can the `-march=native` option be removed from this file? Doing so appears to fix the problem for me.

For reference my build line is as follows:
`make -j2 HOSTCC=gcc CC=aarch64-linux-gnu-gcc BINARY=64 CROSS=1 NOFORTRAN=1 NOSHARED=1 TARGET=CORTEXA57`

**Comment by martin-frbg** [comment]
Which repository are you pulling from that contains this statement ? Normally the make.inc is generated by the build, if it has `-march=native` in it then it must have picked that up from someone's default CFLAGS setting.

**Comment by andrew-wja** [comment]
Hi,
You're absolutely right, it seems that the CMake build system in lapack-netlib automatically picks up any CFLAGS that are set in the environment, and sets them as override CFLAGS in the generated make.inc file. Unsetting CFLAGS in the environment before running the top-level `make` command works.
