### ISSUE TITLE
Finding a faster way to do parallel QR factorization with pivoting (DGEQP3)

### ISSUE THREAD

**Issue by Diazonium** [xianyi/OpenBLAS#1431]
The current implementation of DGEQP3 kinda sucks. For any non-small matrix it spends most of the time in DGEMV, which is extremely memory bandwidth limited when parallelized. The slowness of DGEQP3 is especially an issue for me, because DGELSY spends a large fraction of time doing DGEQP3. (I use DGELSY on MxN matrices where M and N is >3000 and may go up to 10-20 thousand, so parallel performance is really important for me)
AFAIK the current DGEQP3 implementation in OpenBLAS just takes the existing LAPACK code, and uses parallel BLAS where applicable. However this is suboptimal, and large performance improvements may be possible by explicitly parallelizing at the LAPACK level via OpenMP, instead of the BLAS level.
One example for this is the Column Cyclic Distribution method, as described in Algorithm 2, in this paper: [http://web.cs.ucdavis.edu/~bai/publications/tomasbaihernandez13.pdf](http://web.cs.ucdavis.edu/~bai/publications/tomasbaihernandez13.pdf)
The authors reported up to 60% performance improvement (!) in DGEQP3, compared to MKL 10.3.
It would be great if such an improved DGEQP3 algorithm could be implemented in OpenBLAS.

**Comment by brada4** [comment]
Unless it is threading threshold criticism for OpenBLAS (one of BLAS implementations). it should go to as suggestion for algorithmic improvement to reference LAPACK:
https://github.com/Reference-LAPACK/lapack
Also while you are at it - development version is much better tuned for CV applications, i.e. very small to small-medium _gemm, and if it is possible to compare to single-threaded OpenBLAS in both positions.

**Comment by Diazonium** [comment]
Yeah, I might just do that, this probably better handled upstream. 
When you are talking about the development version, do you mean the dev version of OpenBLAS or LAPACK? I already use the dev version of OpenBLAS.

**Comment by martin-frbg** [comment]
Have you tried to implement the proposed algorithm in your own code ? From his publication list it occurs to me that Prof. Bai appears to be well familiar with LAPACK and its principal maintainers.

**Comment by brada4** [comment]
@Diazonium  thus suggestion is to try if single-threaded version performs any better than default one.

**Comment by Diazonium** [comment]
@brada4 I am not sure if I understand your suggestion correctly. Multi-threading certainly works, so compiling OpenBLAS to be single-threaded would make no sense. It's just that scaling is not really that great, due to hitting the memory bandwidth wall.

@martin-frbg I might try to implement it, but there are some...discouraging factors. I am actually using a Fortran 90/95 library that calls DGELSY, which in turn calls DGEQP3, so this makes things a bit more complicated. Also I am not really comfortable with Fortran code, and I am not even sure if OpenMP parallel/barrier is available in the old style of Fortran that LAPACK seems to be using (F77?)
Still, I might try it if I find time to do it.

**Comment by brada4** [comment]
You will easily oversubscribe cpu cores if you multi-thread at multiple levels.
_GEMV is limited to memory bandwidth, and current multuthreading caibrarion takes in account only presumed processing power to be consumed.
_scal is ONLY memory bandwdth limited, with insignificant processing per memory access (should be tens of float operations per memory access to keep CPU busy)

**Comment by Diazonium** [comment]
@brada4 Ah, ok, you were talking about the hypothetical scenario where threading happens at the LAPACK level. Of course then it would be bad to also have BLAS threading.

**Comment by brada4** [comment]
Since you opened https://github.com/Reference-LAPACK/lapack/issues/226 it should be handled correctly without any continued discussion right here

**Comment by martin-frbg** [comment]
OpenMP PARALLEL is used in only a handful of recent files in LAPACK, guarded by an `#if defined _OPENMP` (and accordingly these files have a capital .F suffix as they need preprocessing, see e.g. dsytrd_sb2st.F ). I see no current uses of BARRIER but it is "probably" safe to assume that an implementation that supports one will also support the other.

**Comment by Diazonium** [comment]
Alright, closing this, thanks for the advice guys.
