### ISSUE TITLE
Test failed for dblas3

### ISSUE THREAD

**Issue by xkszltl** [xianyi/OpenBLAS#1432]
CentOS 7
Xeon Gold 6140 (Purley)
CMake 3.10
gcc-7.2.1

Following error found when compile with both Release and RelWithDebInfo:

```
TESTS OF THE DOUBLE PRECISION LEVEL 3 BLAS

 THE FOLLOWING PARAMETER VALUES WILL BE USED:
   FOR N                   0     1     2     3     7    31
   FOR ALPHA             0.0   1.0   0.7
   FOR BETA              0.0   1.0   1.3

 ROUTINES PASS COMPUTATIONAL TESTS IF TEST RATIO IS LESS THAN   16.00

 RELATIVE MACHINE PRECISION IS TAKEN TO BE  2.2D-16

 DGEMM  PASSED THE TESTS OF ERROR-EXITS

 DGEMM  PASSED THE COMPUTATIONAL TESTS ( 17496 CALLS)

 DSYMM  PASSED THE TESTS OF ERROR-EXITS

 DSYMM  PASSED THE COMPUTATIONAL TESTS (  1296 CALLS)

 DTRMM  PASSED THE TESTS OF ERROR-EXITS

 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
           EXPECTED RESULT   COMPUTED RESULT
       1     -0.142857         -0.292707    
      THESE ARE THE RESULTS FOR COLUMN   5
 ******* DTRMM  FAILED ON CALL NUMBER:
    794: DTRMM ('L','U','N','U',  1, 31, 1.0, A,  2, B,  2)        .

 DTRSM  PASSED THE TESTS OF ERROR-EXITS

 DTRSM  PASSED THE COMPUTATIONAL TESTS (  2592 CALLS)

 DSYRK  PASSED THE TESTS OF ERROR-EXITS

 DSYRK  PASSED THE COMPUTATIONAL TESTS (  1944 CALLS)

 DSYR2K PASSED THE TESTS OF ERROR-EXITS

 DSYR2K PASSED THE COMPUTATIONAL TESTS (  1944 CALLS)

 END OF TESTS
```

It passed the test with Makefile.

**Comment by brada4** [comment]
You need to upgrade HT skylake microcode (UEFI) or disable HT and re-test.
https://lists.debian.org/debian-devel/2017/06/msg00308.html
What is purley?

**Comment by xkszltl** [comment]
They seem to use this name for Skylake platform?
Anyway I just mean SKL...

**Comment by xkszltl** [comment]
I've updated to the latest BIOS which includes SKL bugfix.
The error remains and the numeric result is still -0.292707 for cmake build.

**Comment by martin-frbg** [comment]
Which version are you building, is this 0.2.20 (or earlier), or the current git "develop" branch ?
If it is already the develop branch (which has a number of fixes over 0.2.20), you can try building with -DUSE_SIMPLE_THREADED_LEVEL3=1 to see if that helps.

**Comment by xkszltl** [comment]
It's 0.2.20.
In fact I use `git checkout $(git tag | sed -n '/^v[0-9\.]*$/p' | sort -V | tail -n1)` for automated build in my system.

**Comment by brada4** [comment]
Can you try development version? 0.2.20 cannot be changed anymore.

**Comment by xkszltl** [comment]
I've just done the test on commit 5f998efd7b

Nothing changes, with or without `-DUSE_SIMPLE_THREADED_LEVEL3=1`.

Here's the cmake command:
```
    cmake                                   \
        -DCMAKE_BUILD_TYPE=Release          \
        -DCMAKE_C_COMPILER=gcc              \
        -DCMAKE_CXX_COMPILER=g++            \
        -DCMAKE_INSTALL_PREFIX=/usr/local   \
        -DCMAKE_VERBOSE_MAKEFILE=ON         \
        -DUSE_SIMPLE_THREADED_LEVEL3=1      \
        ..
```

**Comment by martin-frbg** [comment]
Skylake uses the same optimized routines as Haswell, so the error is somewhat unexpected. However I seem to have overlooked the final sentence of your original message -  "It passed the test with Makefile".
Do I take it that only the CMAKE build shows this problem, while building with plain make runs OK ? (Guessing cmake may pick other default CFLAGS, or not fully support some setting - I seem to remember we had something similar a while back, where the USE_TRMM=1 setting for Haswell et al.
from kernel/Makefile.L3 was not mirrored in the cmake counterpart. Probably no coincidence that it is the DTRMM test that breaks)

**Comment by xkszltl** [comment]
Yes only cmake build failed.
It passed both lapack-test and blas-test from Makefile.

CMake uses `-O2 -Wall -m64 -fPIC -O3 -DNDEBUG -O3` for compiling and `gfortran -O2 -Wall -m64 -fPIC -O3 -DNDEBUG -O3 CMakeFiles/dblat3.dir/dblat3.f.o -o dblat3 ../lib/libopenblas.a -lpthread` for linking.

**Comment by martin-frbg** [comment]
Thanks. It seems unlikely that -O3 would be the culprit (and plain make probably picks up the same CFLAGS from your environment anyway). At first glance, the code responsible for setting USE_TRMM in kernel/CMakelists.txt appears to be essentially unchanged from earlier versions.

**Comment by xkszltl** [comment]
FYI our env doesn't set any *FLAGS and these arguments are picked from the log printed by -DCMAKE_VERBOSE_MAKEFILE=ON.

**Comment by martin-frbg** [comment]
Reproducible on Kaby Lake, and a quick look at the definitions in $BUILDDIR/kernel/CMakefiles/dtrmm_kernel_LN.c shows that it indeed includes a gemm kernel file for haswell rather than the trmm one, just as if USE_TRMM was not in effect. Forcing set(USE_TRMM true) in kernel/CMakeList.txt leads to the correct behaviour, so something in the lengthy if statement that matches TARGET and CORE types against a list is (again) broken.

**Comment by martin-frbg** [comment]
${TARGET} in that lengthy `if (ARM OR ARM64 OR...` needs to be ${TARGET_CORE} throughout, patch incoming.
