### ISSUE TITLE
Build OpenBlas for Android on Mac

### ISSUE THREAD

**Issue by waynehong666** [xianyi/OpenBLAS#1435]
Here is my script to build on Mac

# Set path to ndk-bundle
export NDK_BUNDLE_DIR=../Library/Android/sdk/ndk-bundle

# Set the PATH to contain paths to clang and arm-linux-androideabi-* utilities
export PATH=${NDK_BUNDLE_DIR}/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin:${NDK_BUNDLE_DIR}/toolchains/llvm/prebuilt/darwin-x86_64/bin:$PATH

# Set LDFLAGS so that the linker finds the appropriate libgcc
export LDFLAGS="-L${NDK_BUNDLE_DIR}/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x"

# Set the clang cross compile flags
export CLANG_FLAGS="-target arm-linux-androideabi -marm -mfpu=vfp -mfloat-abi=softfp --sysroot ${NDK_BUNDLE_DIR}/platforms/android-23/arch-arm -gcc-toolchain ${NDK_BUNDLE_DIR}/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/"

#OpenBLAS Compile
make TARGET=ARMV7 ONLY_CBLAS=1 AR=ar CC="clang ${CLANG_FLAGS}" HOSTCC=gcc ARM_SOFTFP_ABI=1 -j4

But I got the following error at the end:
../Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: ../libopenblas_armv7p-r0.3.0.dev.a: malformed archive header name at 8
../Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: ../libopenblas_armv7p-r0.3.0.dev.a: malformed archive header name at 8
../Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: fatal error: ../libopenblas_armv7p-r0.3.0.dev.a: attempt to map 60 bytes at offset 3862436 exceeds size of file; the file may be corrupt
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [../libopenblas_armv7p-r0.3.0.dev.so] Error 1
make: *** [shared] Error 2

**Comment by brada4** [comment]
CC should be target compiler, android-eabi-something
Probably worth setting FC=NONE to avoid accidentally catching x86_64 gfortran or ifort that will generate certainly broken module.

**Comment by brada4** [comment]
,,, -49 is GCC NDK toolset based on GCC 4.9

**Comment by martin-frbg** [comment]
From https://github.com/tensorflow/tensorflow/issues/14186 (found by googling the curious "malformed archive header name at 8" message) the problem could be that the local `ar` tool gets picked up rather than its ARM counterpart from the NDK. Can you try with AR=${NDK_BUNDLE_DIR}/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/ar 
(or whatever path to the ndk ar is appropriate) please (after a "make clean")?

**Comment by abhishek-sehgal** [comment]
Hi @martin-frbg, I was facing the same error and I followed your advice and OpenBLAS built properly. The proper path for AR was
`AR=${NDK_BUNDLE_DIR}/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc-ar`

Thank you!

**Comment by martin-frbg** [comment]
Hi @a-sehgal, thanks for the feedback - I have added this to the wiki page now. (@waynehong666, I hope this actually solved the problem for you as well ?)

**Comment by LukeChow** [comment]
unknown argument: '-ru'
