### ISSUE TITLE
openblas performance on 8xA53

### ISSUE THREAD

**Issue by wl3b10s** [xianyi/OpenBLAS#1439]
test gemm on 8 core  A53.
Setting 
 omp_set_num_threads(4);
 openblas_set_num_threads(4);
is much faster than:
 omp_set_num_threads(8);
 openblas_set_num_threads(8);

i think this may because of multithread doesn't work well on more cores.

my build config : all default  and build native on arm a53 and ubuntu.

my test config : gemm  float, both no transpose
M = 16, N = 76800, K = 98
M = 32, N = 19481, K = 144
M = 128, N = 1271, K = 1728

**Comment by brada4** [comment]
is it aarch32 or aarch64?
... check NUMA layout detected by ubuntu. Traversing NUMA borders is slow and happens in 64MB (intel64) or so blocks being dragged via system bus between CPUs.
Probably there is something in ARM datasheets about stride sizes, unless you make inputs 10x NUMA stride it will not gain for extra multicore  CPU.
You can still issue two _GEMM in parallel.

**Comment by ashwinyes** [comment]
M = 16, N = 76800, K = 98
M = 32, N = 19481, K = 144
M = 128, N = 1271, K = 1728

Can you try with proper square matrices? Like 1024x1024 or 2048x2048 etc. For skewed matrices like "M = 32, N = 19481, K = 144" , the partitioning may not be good at 8 cores.

**Comment by martin-frbg** [comment]
@ashwinyes I wonder what target gets used here - I guess the A53 is compatible with the A57 (?), but does it get autodetected as such or would users end up with the generic C ARMV8 kernels ? (Same for the A72)

**Comment by wl3b10s** [comment]
@martin-frbg i guess it detect as generic armv8 asm kernel.

**Comment by ashwinyes** [comment]
@martin-frbg Thanks for pointing this. Yes it would use the ARMV8 C kernels. I think its time we make the generic ARMV8 target to use the assembly kernels. All ARMV8 machines will support the assembly kernels .

@wl3b10s For the time being, you may also try building with "make TARGET=CORTEXA57". You will see some performance improvement.

**Comment by martin-frbg** [comment]
The quick and dirty alternative would be to treat A53 and A72 as A57 in cpuid_arm64. Am I right in thinking that the hardfp/softfp issue that lead to a re-introduction of C kernels for ARM affects that 32bit platform only ?

**Comment by ashwinyes** [comment]
>>  Am I right in thinking that the hardfp/softfp issue that lead to a re-introduction of C kernels for ARM affects that 32bit platform only ?

Yes. hardfp/softfp issue is only for arm 32bit.

>> The quick and dirty alternative would be to treat A53 and A72 as A57 in cpuid_arm64.

Making ARMV8 target to use the assembly kernels is the best thing to do in my opinion.

**Comment by martin-frbg** [comment]
Needs some rearranging of the KERNEL files though, as they all include KERNEL.ARMV8 either directly or indirectly before adding their own definitions on top of it. Or just rename KERNEL.ARMV8 to KERNEL.ARMV8C or something (which could even serve as a fallback target for troubleshooting), adjust the includes accordingly and make KERNEL.ARMV8 a copy of KERNEL.CORTEXA57 ?

**Comment by martin-frbg** [comment]
Perhaps more to the point, CORTEXA57 has the xGEMM and xTRMMKERNELs defined as xx_kernel_$(xGEMM_UNROLL_M)x$(xGEMM_UNROLL_N).S , where the xGEMM_UNROLL_M, xGEMM_UNROLL_N are 16x4, 8x4 or 4x4 respectively. 
Generic ARMV8 has 2x2 for DGEMM,CGEMM and ZGEMM unroll factor which are not currently implemented in assembly. So it seems cpu detection would still need to map the Cortex A53, A72 to the A57 target to make full use of available implementations.
