### ISSUE TITLE
Fails to compile on SPARC due to missing CHAR_CORENAME

### ISSUE THREAD

**Issue by jdemeyer** [xianyi/OpenBLAS#1446]
After fixing #1442, compiling on SPARC still fails:
```
openblas_get_config.c:58:3: error: expected ',' or ';' before 'CHAR_CORENAME'
   CHAR_CORENAME
   ^
openblas_get_config.c: In function 'openblas_get_corename':
openblas_get_config.c:81:10: error: 'CHAR_CORENAME' undeclared (first use in this function)
   return CHAR_CORENAME;
          ^
openblas_get_config.c:81:10: note: each undeclared identifier is reported only once for each function it appears in
openblas_get_config.c:85:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[3]: *** [Makefile:113: openblas_get_config.o] Error 1
```

The problem is that the autogenerated `config.h` does not define `CHAR_CORENAME`:
```
#define OS_SUNOS        1
#define ARCH_SPARC      1
#define C_GCC   1
#define __64BIT__       1
#define PTHREAD_CREATE_FUNC     pthread_create
#define BUNDERSCORE     _
#define NEEDBUNDERSCORE 1
#define SPARC
#define V9
#define DTB_DEFAULT_ENTRIES 32
#define GEMM_MULTITHREAD_THRESHOLD      4
```

When passing `TARGET=SPARC`, everything works because a line `#define CHAR_CORENAME "sparc"` is added.

This should be easy to fix analogous to #1443 but I don't know what the right fix is. Should `CHAR_CORENAME` be defined or not?

**Comment by brada4** [comment]
Please take some inspiration from here, namely add variables until it compiles:
https://github.com/xianyi/OpenBLAS/pull/1443/files
It is not very productive asking one line a time

**Comment by martin-frbg** [comment]
I suspect the cpuid_sparc.c should grow a get_corename() function that returns "sparc", and getarch.c needs a corresponding expansion of the "if defined..." that invokes it. 
But I have to agree that it is not easy to see how (if) this was originally intended to work. :-(
The chance of breaking something seems minimal however, and the relevant files seem to have a history of "improved sparc detection" fixes

**Comment by brada4** [comment]
Maybe SPARC64? Old is sort of forgotten. Also I read in other places that Oracle dropped Sun Performance Library, LAPACK in other words from developer studio with solaris 11
