### ISSUE TITLE
Improve documentation on relationship between # of cores and # of memory buffers

### ISSUE THREAD

**Issue by augray** [xianyi/OpenBLAS#1451]
From the [USAGE.md](https://github.com/xianyi/OpenBLAS/blob/develop/USAGE.md):

> In OpenBLAS, we mange a pool of memory buffers and allocate the number of buffers as the following.
> `#define NUM_BUFFERS (MAX_CPU_NUMBER * 2)`
> This error indicates that the program exceeded the number of buffers.
> Please build OpenBLAS with larger NUM_THREADS. For example, make NUM_THREADS=32 or make NUM_THREADS=64. In Makefile.system, we will set MAX_CPU_NUMBER=NUM_THREADS.

This leaves me with several questions:

1) It appears that this means I can safely and reliably call into OpenBLAS to do N computations with N = NUM_THREADS (or is it 2 * NUM_THREADS?) at once. Is this correct?
2) If the physical machine only has 2 cores, but I built OpenBLAS with NUM_THREADS=10, am I still able to safely do N computations at once with N = NUM_THREADS?
3) If the answer to (2) is yes, is there a reason I would want to limit NUM_THREADS? Presumably the overhead of hundreds of threads is going to not be worth the parallelization if I have only a few cores, but would it be reasonable to set NUM_THREADS=64 if my code will be running on various machines, with anywhere from 2 to 64 cores?

Perhaps I just need to dig in more, but it seems that the [USAGE.md](https://github.com/xianyi/OpenBLAS/blob/develop/USAGE.md) could benefit from some more detail that would help elucidate the answers to these.

FWIW, in my actual use case for BLAS, I only use it through scipy, but I've been hitting the "you tried to allocate too many memory regions." error and am trying to figure out the best route forward.

**Comment by martin-frbg** [comment]
1. N computations with N=NUM_THREADS is correct (I believe the factor of two in the default assignment comes from assuming hyperthreading capability of the physical cores, but the relation between NUM_CORES,MAX_CPU_NUMBER,NUM_THREADS and NUM_BUFFERS in the build system _is_ confusing at best.)
2. Yes, but it will probably be far less efficient than running with fewer threads. You can limit the number of threads at runtime through environment variabls (OPENBLAS_NUM_THREADS or OMP_NUM_THREADS)
3. Correct.

Actually the current behaviour of the code with respect to memory buffer allocation could be called a bug (and has been on occasion) for all the reasons you touched on, but so far nobody has come up with a convincing alternative.

**Comment by augray** [comment]
@martin-frbg: So it sounds like the most flexible option is to build with NUM_THREADS at some reasonable number for the max number of cores you ever expect to have available (such as 64) so that the number of memory regions allocated is sufficiently high. Then at runtime, set OPENBLAS_NUM_THREADS to be the actual number of cores on the machine so you end up with an optimal match between what the CPUs provide and what you request. Are there any downsides to this approach?

**Comment by martin-frbg** [comment]
None that I can think of, except perhaps a small overhead on startup and some unnecessary memory use.

**Comment by augray** [comment]
Great! Is there any form in which you think some of this discussion could be added to the documentation? Perhaps change:


> **Program is Terminated. Because you tried to allocate too many memory regions**
>
> In OpenBLAS, we mange a pool of memory buffers and allocate the number of buffers as the following.
>
> `#define NUM_BUFFERS (MAX_CPU_NUMBER * 2)`
>
> This error indicates that the program exceeded the number of buffers.
>
> Please build OpenBLAS with larger `NUM_THREADS`. For example, `make NUM_THREADS=32` or `make NUM_THREADS=64`. In `Makefile.system`, we will set `MAX_CPU_NUMBER=NUM_THREADS`.
> 
> _Note that the number of threads used at runtime can be altered to differ from the value `NUM_THREADS` was set to at build time. At runtime, the actual number of threads can be set anywhere from 1 to the build's `NUM_THREADS` (note however, that this does not change the number of memory buffers that will be allocated, which is set at build time). The number of threads for a process can be set by using the mechanisms described below._

The italicized text is a suggested addition. I can open a PR if you think this modification would be useful.

**Comment by brada4** [comment]
There are some nearly forgotten allocators that may get past issue. One that seems viable to me would be invoked by
`HUGETLBFILE_ALLOCATION=/dev/hugepages/openblas`
Build parameter (note that it will not work for 2nd parallel invocation as it stands at present)

**Comment by augray** [comment]
@brada4 Sorry, but I'm not sure I quite follow your suggestion. Are you saying that using `HUGETLBFILE_ALLOCATION` at build time in some way can increase the number of memory buffers without using a high `NUM_THREADS` at build time? And could you clarify what you mean by _"note that it will not work for 2nd parallel invocation as it stands at present"_ ? Thanks!

**Comment by martin-frbg** [comment]
Frankly I do not think that this Linux-specific support for "huge page tables" has anything at all to do with the thread buffer allocation ?
