### ISSUE TITLE
openBLAS FIXEDPOINT IMPLEMENTATION

### ISSUE THREAD

**Issue by ali7569392725** [xianyi/OpenBLAS#1458]
HI,
Is there any Fixed Point Implementation for OPEN-BLAS ?

**Comment by martin-frbg** [comment]
OpenBLAS, no. There appears to be a fixed point implementation of the GEMM functions in https://github.com/google/gemmlowp

**Comment by ali7569392725** [comment]
Since I'm Using openBLAS as a supportive Library For a Speech Recognition (KALDI) Project, And I'm using few Functions in cblas.h like cblas_sgemm, cblas_dgemm, cblas_daxpy, cblas_saxpy , cblas_dger & cblas_sger only.
Is there any Possibility to Take a respective C source files from Openblas and detach the supportive Openblas Library for KALDI Project?

**Comment by martin-frbg** [comment]
Possible but probably a bit tedious. Some functions have their implementation directly in `interface`, 
where some Makefile magic sees to it that one source file gets transformed into all permutations of 
blas/cblas interface and float/double/complex variable type.
For others this pulls in the respective code from `driver/level2` or `driver/level3` which in turn calls the cpu-specific implementation from `kernel` - you will probably want to use their generic C fallback implementations from `kernel/generic`.

**Comment by brada4** [comment]
[cblas.h](http://kaldi-asr.org/doc/matrixwrap.html) is used as backend for kaldi api that manipulates abstract FLOAT matrices. I.e. You are NOT expected to call BLAS directly and call it KALDI
While integers are good for FPU-less DSP, they will certainly overflow with more complex computations.

**Comment by ali7569392725** [comment]
Hii...Actually If i want to implement the Function for example cblas_saxpy() , But the function definition **calls** internally some FORTRAN based function such as F77_saxpy() , But In the Visual Studio2017 Community Version I found that there is NO fortran Compiler available, So I think I can't Implement the Function since there is no Fortran Compiler support for VS2017, Please give me your valuable Suggestions So that I can implement that functions and Finally detach the Library.

**Comment by brada4** [comment]
You are looking in reference implementation. OpenBLAS saxpy saxpy_ and cblas_saxpy is built from interface/axpy.c

**Comment by ali7569392725** [comment]
Actually I'm looking exactly in "OpenBLAS-develop\lapack-netlib\CBLAS\src" where i can see cblas_saxpy "C" file is present, So Can u Tell me , If i want to redefine cblas_saxpy() function Independently in VS2017 what function exactly i have to replace??? 
Thanks In advance 👍

**Comment by martin-frbg** [comment]
Actually the code from lapack-netlib\CBLAS is not used by OpenBLAS, it is only included since it is included with the sources of the LAPACK reference implementation. 
The OpenBLAS versions of saxpy() and cblas_saxpy() are both built from interface\axpy.c with appropriate options in the Makefile. The AXPYU_K you will see in axpy.c is declared in common_d.h to be daxpy_k, which gets built by kernel\Makefile.L1 from the cpu-specific assembly file that matches the cpu OpenBLAS was built for, e.g. kernel\x86_64\axpy.S  (with a fallback implementation in C that you can find in kernel\arm\axpy.c - for most functions, these are in kernel\generic).
This is why I wrote above that it is "possible but tedious" to extract individual functions from OpenBLAS...

**Comment by ali7569392725** [comment]
what about the benchmark codes for BLAS?? I can see "axpy.c" file in benchmark folder, So....Can it help out?? Actually i want to know how benchmark codes for BLAS usefull for user?

**Comment by martin-frbg** [comment]
Benchmark codes are programs that call some function and report how fast it runs on your computer. Nothing more, nothing less - if you do not want to compare the speed of OpenBLAS on different computers, or try to improve the implementation of some function for a specific cpu they will be useless to you.
