### ISSUE TITLE
daxpy 10x slower on macOS (Haswell)

### ISSUE THREAD

**Issue by simonbyrne** [xianyi/OpenBLAS#1470]
Calls to `daxpy` seem to be about 10x slower on macOS than when run inside a Linux VM on the same machine (both give the config as "USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell").

This affects a lot of code which depends on it (e.g. `dgebrd`).

downstream: https://github.com/JuliaLang/LinearAlgebra.jl/issues/501

**Comment by martin-frbg** [comment]
Nobody here currently has a Mac I fear. From anecdotal evidence in previous issues (#730, JuliaLang/julia#901) you could try removing the `.align 16` in kernel/x86_64/daxpy_microk_haswell-2.c, or try with the current "develop" tree as that happens to have that microkernel replaced with the non-AVX2 Sandybridge one for unrelated reasons (the respective microkernel is #included at the top of kernel/x86_64/daxpy.c)

**Comment by brada4** [comment]
Can you check if virtual machine has AVX2 inside in /proc/cpuinfo (i.e haswell or sandybridge is used)

**Comment by simonbyrne** [comment]
> Can you check if virtual machine has AVX2 inside in /proc/cpuinfo (i.e haswell or sandybridge is used)

Yes, it does.

**Comment by simonbyrne** [comment]
Using the current `develop` branch (e3a80e6aa8a289228de9ff1c97364bcb7340f7e9) doesn't fix it either.

**Comment by martin-frbg** [comment]
Does killing any and all .align16 in the daxpy microkernel file change anything ?

**Comment by simonbyrne** [comment]
Yes, commenting that out in `daxpy_microk_sandy-2.c` seems to fix it.

**Comment by ViralBShah** [comment]
Is it possible to perhaps have a new release once we fix this, given that we haven't had one for a long time? We're happy (in the Julia community) to try out an RC and give feedback before release.

**Comment by simonbyrne** [comment]
Ah, does it have anything to do with [this commit comment](https://github.com/xianyi/OpenBLAS/commit/6e7be06e072cddc5d34617f28f60a32484b9e910)?

According to [the Mac developer docs](https://developer.apple.com/library/content/documentation/DeveloperTools/Reference/Assembler/040-Assembler_Directives/asm_directives.html#//apple_ref/doc/uid/TP30000823-TPXREF146):

> align_expression is a power of 2 between 0 and 15 (for example, the argument of .align 3 means 2 ^ 3 (8)–byte alignment)

As I understand, `p2align` should be consistent across platforms.

**Comment by martin-frbg** [comment]
@simonbyrne yes, sorry for not digging down to the original source earlier. And thanks for the pointer to p2align, certainly looks cleaner than adding ifdefs around each and every .align (though the underlying issue seems to be an Apple flaw, if their align is identical to p2align).
@ViralBShah I hope so, but xianyi has not been seen here for quite some time, and I still believe only he can do releases

**Comment by simonbyrne** [comment]
No worries. Thanks for all your effort maintaining OpenBLAS.

**Comment by ViralBShah** [comment]
Thank you. We might just apply the patch for now in that case.

**Comment by ViralBShah** [comment]
I have emailed @xianyi about adding more people as admin and perhaps even moving the project to an OpenBLAS organization to help maintain it better.

**Comment by martin-frbg** [comment]
PR merged for Haswell and Sandybridge, from wikipedia I suspect Nehalem may also be needed for 2010-12 models of Mac Pro and iMac ?

**Comment by simonbyrne** [comment]
I believe so: I think we build macOS Julia for Nehalem, perhaps @staticfloat can confirm?

**Comment by staticfloat** [comment]
We build with `DYNAMIC_ARCH=1` on OSX, so we build everything and architecture is chosen at runtime.

**Comment by martin-frbg** [comment]
PR incoming. I now understand that in the early assembly kernels from libGoto this issue was already catered for by using ALIGN_ macros from common_x86_64.h

**Comment by martin-frbg** [comment]
Actually according to the Github documentation I should have sufficient rights for creating a release. As that was never discussed as a possible "duty", I would still prefer to do this only if contact with xianyi cannot be established. Also I do not have access to the sourceforge repository used for providing precompiled windows version, or the openblas.net project page that links to it.

**Comment by simonbyrne** [comment]
The current website seems to be built from @xianyi's personal GitHub page:
https://github.com/xianyi/xianyi.github.com/tree/master/OpenBLAS

**Comment by martin-frbg** [comment]
Tagging for 0.3.0 as xianyi created that milestone recently, hopefully the release will happen soon.
