### ISSUE TITLE
errors in compute the peak performance in benchark/gemm.c

### ISSUE THREAD

**Issue by xingjinglu** [xianyi/OpenBLAS#1474]
Is here a type error in compute the peak performance of gemm in benchmark/gemm.c

```
Line 240      

 timeg = time1/loops;
    fprintf(stderr,
      " %10.2f MFlops %10.6f sec\n",
      COMPSIZE * COMPSIZE * 2. * (double)m * (double)m * (double)n / timeg * 1.e-6, time1);
```

I think here it should be 2. * (double)m * (double)n * (double) k, so one of the 'm' should be k.

**Comment by martin-frbg** [comment]
It does look like a small oversight from #1316, where variable 'k' was added. @timmoon10

**Comment by brada4** [comment]
Should not change much as the benchmark itself operates on square matrices and result from incorrect formula is still correct...

**Comment by martin-frbg** [comment]
Methinks the point of #1316 was to extend it to non-square matrices ? (Though I do not think timmoon10 based his gemm threading rework solely on the numbers from this benchmark)

**Comment by timmoon10** [comment]
Oops, my bad. @brada4 is right that the bug wouldn't affect the benchmark when used in a vanilla configuration. However, it's possible my experiments on non-square matrices were incorrect.

**Comment by brada4** [comment]
new formula is completely correct for scalar case
i have some doubts regarding which is FLOP in complex case

**Comment by brada4** [comment]
I will look around benchmark/ correcting formulas if any and add Bps. I think bandwidth is only thing relevant for L1 and sometimes plays L2
