### ISSUE TITLE
LNK1107	invalid or corrupt file: cannot read at 0x480 when link libopenblas.dll in visual studio express 2017

### ISSUE THREAD

**Issue by liwei46** [xianyi/OpenBLAS#1478]
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1107	invalid or corrupt file: cannot read at 0x480	test-oblas	D:\program\OpenBLAS-v0.2.19-Win64-int32\bin\libopenblas.dll	1	

Hi all,

I encounter a link error (error message above) when using pre-build windows version. the sample code is below. Any idea what can I do? Thanks.

regards,
liwei

-------------------------------
{
	int th_model = openblas_get_parallel();
	switch (th_model) {
	case OPENBLAS_SEQUENTIAL:
		printf("OpenBLAS is compiled sequentially.\n");
		break;
	case OPENBLAS_THREAD:
		printf("OpenBLAS is compiled using the normal threading model\n");
		break;
	case OPENBLAS_OPENMP:
		printf("OpenBLAS is compiled using OpenMP\n");
		break;
	}

	int n = 2;
	double* x = (double*)malloc(n * sizeof(double));
	double* upperTriangleResult = (double*)malloc(n*(n + 1) * sizeof(double) / 2);

	for (int j = 0; j<n*(n + 1) / 2; j++)
		upperTriangleResult[j] = 0;

	x[0] = 1; x[1] = 3;

	cblas_dspr(CblasRowMajor, CblasUpper, n, 1, x, 1, upperTriangleResult);
	double*& A = upperTriangleResult;
	std::cout << A[0] << "\t" << A[1] << std::endl << "*\t" << A[2] << std::endl;

	free(upperTriangleResult);
	free(x);

	return 0;
}
-----------------------------

**Comment by brada4** [comment]
You need to use .lib or .a file supplied in place of a dll, you can also use `lib.exe` to generate one.
clang does not have this problem.

**Comment by liwei46** [comment]
Hi Brada4,

Thanks for the reply.  I use 
D:\program\OpenBLAS-v0.2.19-Win64-int32\lib\libopenblas.a
It have the following errors.  :(

btw: under ubuntu and gcc, it works for me. But I have to use visual studio in windows for now. 

Regards,
liwei


-----------------------------------------------------
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol ___chkstk_ms referenced in function dspr_thread_U	test-oblas	d:\Users\wei.li1\source\repos\test-oblas\test-oblas\libopenblas.a(dspr_thread_U.obj)	1	
Error	LNK2001	unresolved external symbol ___chkstk_ms	test-oblas	d:\Users\wei.li1\source\repos\test-oblas\test-oblas\libopenblas.a(dspr_thread_L.obj)	1	
Error	LNK2019	unresolved external symbol __ms_vsnprintf referenced in function snprintf.constprop.1	test-oblas	d:\Users\wei.li1\source\repos\test-oblas\test-oblas\libopenblas.a(dynamic.obj)	1	
Error	LNK2019	unresolved external symbol __imp___iob_func referenced in function openblas_warning	test-oblas	d:\Users\wei.li1\source\repos\test-oblas\test-oblas\libopenblas.a(openblas_error_handle.obj)	1	
Error	LNK2019	unresolved external symbol __imp__cprintf referenced in function xerbla_	test-oblas	d:\Users\wei.li1\source\repos\test-oblas\test-oblas\libopenblas.a(xerbla.obj)	1	
Error	LNK2001	unresolved external symbol __imp__cprintf	test-oblas	d:\Users\wei.li1\source\repos\test-oblas\test-oblas\libopenblas.a(memory.obj)	1	
Error	LNK2019	unresolved external symbol sprintf referenced in function gotoblas_dynamic_init	test-oblas	d:\Users\wei.li1\source\repos\test-oblas\test-oblas\libopenblas.a(dynamic.obj)	1	
Error	LNK1120	5 unresolved externals	test-oblas	d:\Users\wei.li1\source\repos\test-oblas\x64\Debug\test-oblas.exe	1

**Comment by brada4** [comment]
You are missing #include <stdio.h> for those printf() used in your code.
Gory details here (nothing to do with OpenBLAS):
https://msdn.microsoft.com/en-us/library/bb531344.aspx

**Comment by liwei46** [comment]
Hi Brada4,
Thanks for the help. 
I find when I use D:\program\OpenBLAS-v0.2.19-Win64-int32\lib\libopenblas.dll.a

And add the 3 missing dlls (libgcc_s_seh-1.dll  libgfortran-3.dll  libquadmath-0.dll) in the exe folder, it works. 

Regards,
liwei

**Comment by martin-frbg** [comment]
Guess we may need a "how to use" section for the Windows files in the Wiki page for prebuilt binaries 
(or better documentation included with the zip)
