### ISSUE TITLE
xhpl: error while loaded shared libraries libopenblas.so.0

### ISSUE THREAD

**Issue by shafayetrahat** [xianyi/OpenBLAS#1479]
I build hpl with openmpi and openblas (Nehalem). When I run(mpirun -np 4 xhpl) it on single node it works fine. But when I use (mpirun -np 8 -machinefile node xhpl) on 2 node it gives me :
Primary job terminated normally......
xhpl: error while loaded shared libraries libopenblas.so.0 .No such file or directory.
I have checked my library path. They are ok.

**Comment by martin-frbg** [comment]
Perhaps it is a dependency of libopenblas.so that is missing on the other node, like gfortran's libquadmath or libgfortran itself ?

**Comment by shafayetrahat** [comment]
I have solved it. It's the I have to write in ldconfig configuration file(ld.so.conf/openblas.conf).
