### ISSUE TITLE
does openblas on armv7 support neon simd extension speedup?

### ISSUE THREAD

**Issue by wl3b10s** [xianyi/OpenBLAS#1483]
does openblas on armv7 support neon simd extension speedup?

will it support future?

or is there similar blas library support neon on armv7 ?

thanks.

**Comment by martin-frbg** [comment]
As far as I know, the ARMv7 implementation (mainly) uses vfp in the inline assembly due to fundamental limitations in the ARMv7 implementation of neon. ARMv8 uses neon/asimd.

**Comment by wl3b10s** [comment]
@martin-frbg  you mean neon on v7 is not high performance or most armv7 processor does not support neon extension?

**Comment by martin-frbg** [comment]
See comments by wernsaar in #562 (the softfp support was added recently, but nothing else changed since then as far as I know)

**Comment by martin-frbg** [comment]
So while I cannot seem to find anything supporting the original claim that neon was deprecated on ARMv7, it still seems to be limited to single precision (allowing to process four float values in parallel).
So a more general improvement would probably be achieved by utilizing the FMA functions provided by vfp4 (as suggested earlier in #1127)

**Comment by sandwichmaker** [comment]
My understanding is that NEON is an option for ARMV7. 

https://community.arm.com/tools/b/blog/posts/arm-cortex-a-processors-and-gcc-command-lines
