### ISSUE TITLE
how to compile for new version of ndk

### ISSUE THREAD

**Issue by flankechen** [xianyi/OpenBLAS#1484]
trying to compile OpenBLAS for android, flowing [wiki](https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android) , and got error like  `"fatal error: stdio.h` 

checking my ndk 16.1, stdio.h is located in ${NDK}/sysroot/. if I set --sysroot to this, I got asm/types.h not find error. I find a way like `--sysroot ${NDK_BUNDLE_DIR}/sysroot -isystem ${NDK_BUNDLE_DIR}/sysroot/usr/include/arm-linux-androideabi `, but getting cannot open crtbegin_so.o error. 

NDK change folder structure, and how to set the CLANG_FLAGS ?

my command:

export NDK_BUNDLE_DIR=/path/to/ndk-bundle

export PATH=${NDK_BUNDLE_DIR}/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin:${NDK_BUNDLE_DIR}/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH

export LDFLAGS="-L${NDK_BUNDLE_DIR}/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x"

 export CLANG_FLAGS="-target arm-linux-androideabi -marm -mfpu=vfp -mfloat-abi=softfp --sysroot ${NDK_BUNDLE_DIR}/sysroot -isystem ${NDK_BUNDLE_DIR}/sysroot/usr/include/arm-linux-androideabi -gcc-toolchain ${NDK_BUNDLE_DIR}/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/"

make TARGET=ARMV7 ONLY_CBLAS=1 AR=ar CC="clang ${CLANG_FLAGS}" HOSTCC=gcc ARM_SOFTFP_ABI=1 -j4

**Comment by martin-frbg** [comment]
Has this version of the NDK dropped the ${NDK_BUNDLE_DIR}/platforms/android-23/arch-arm folder for sysroot (that is named in the clang build instructions at the end of the wiki page) ?

**Comment by flankechen** [comment]
@martin-frbg  no, I think they split out things, I install NDK from android studio.  ${NDK_BUNDLE_DIR}/sysroot holds the headers. and others lays /platforms.

**Comment by martin-frbg** [comment]
But when you set sysroot according to the instructions in the wiki, you get other errors ? (I see nothing special mentioned in the release notes or changelog of the new NDK.)

**Comment by flankechen** [comment]
@martin-frbg I got fatal error: stdio.h not found. And I find that this stdio.h is not anywhere in ${NDK_BUNDLE_DIR}/platforms/android-23/arch-arm64. instead, it's in ${NDK_BUNDLE_DIR}/sysroot/

**Comment by flankechen** [comment]
Well, I find the solution, I have to make a standalone toolchain from ndk like: [link](http://jcsilva.github.io/2017/03/18/compile-kaldi-android/)

I think that's interesting, ndk really split out things, so they make a python script to make a standalone toolchain

Thanks for you help!

**Comment by martin-frbg** [comment]
Ah, I see the note about having to do this at the top of the wiki page is easy to miss now that most users will jump directly to the clang section. I have copied that information now, maybe it is even time already to
rearrange the wiki page and make the clang builds the normal procedure.

**Comment by flankechen** [comment]
yeah, I just jump to clang part and miss the begining.
