### ISSUE TITLE
how to set eigen to use openblas in android

### ISSUE THREAD

**Issue by flankechen** [xianyi/OpenBLAS#1485]
Environment set up: android armv7, ndk-build
OpenBlas: make for armv7 like:  make TARGET=ARMV7 ONLY_CBLAS=1 AR=ar CC="clang ${CLANG_FLAGS}" HOSTCC=gcc ARM_SOFTFP_ABI=1 USE_THREAD=0 NUM_THREADS=32 -j4
make install NO_SHARED=1 PREFIX=`pwd`/install
OpenBLAS/install/include/
OpenBLAS/install/lib/libopenblas.a

android.mk

#build a test executable
include $(CLEAR_VARS)
LOCAL_MODULE := test_qsml
LOCAL_C_INCLUDES += $(LOCAL_PATH)/Eigen/
LOCAL_C_INCLUDES += $(LOCAL_PATH)/openblas/install/include
LOCAL_SRC_FILES := $(LOCAL_PATH)/test_qsml.cpp
LOCAL_CFLAGS += -DEIGEN_USE_BLAS
LOCAL_CFLAGS += -fPIC -frtti -fexceptions -lz -O3 -std=c++11
LOCAL_LDLIBS += -lm -llog -lz
LOCAL_STATIC_LIBRARIES += $(LOCAL_PATH)/openblas/install/lib/libopenblas.a
include $(BUILD_EXECUTABLE)

cpp

#include <iostream>
#include <chrono>
#include <Eigen/Dense>
using namespace Eigen;
using namespace std;

int main()
{

MatrixXd m = MatrixXd::Random(300,300);
MatrixXd n = MatrixXd::Random(300,300);
MatrixXd k;
std::chrono::steady_clock::time_point t1 = std::chrono::steady_clock::now();

//for(int i=0; i<10;i++){
k = m*n;
//}
std::chrono::steady_clock::time_point t2 = std::chrono::steady_clock::now();

double timeSpent =std::chrono::duration_cast<std::chrono::duration<double>>(t2-t1).count();
std::cout << "time used: " << timeSpent <<", " << k(0,0) << endl;

return 0;
}

ndk-build
ERROR:

[armeabi-v7a] Compile++ thumb: test_qsml <= test_qsml.cpp
[armeabi-v7a] Executable     : test_qsml
/home/flanke/space/mobilerelight/Android/jni/Eigen/src/Core/products/GeneralMatrixMatrix_BLAS.h:106: error: undefined reference to 'dgemm_'
collect2: error: ld returned 1 exit status

I think it's not linking to correct things for eigen, Am I missing something? Thanks?

**Comment by martin-frbg** [comment]
Case sensitivity ? Your LOCAL_STATIC_LIBRARIES line has the library path "openblas/install/lib" all in lowercase while the output a few lines above calls it "OpenBLAS/install/lib"

**Comment by flankechen** [comment]
@martin-frbg thanks for your reply, it's just another folder in which I clone and make openblas. Then I copy the /install/ folder to Android jni folder.

**Comment by martin-frbg** [comment]
So it really is in "openblas/install/lib", not "OpenBLAS/install/lib" ?

**Comment by martin-frbg** [comment]
If this problem is still unsolved, can you do a `nm` on your `$(LOCAL_PATH)/openblas/install/lib/libopenblas.a` to see if it has dgemm_ ? (As a side effect this would also clear up any doubts about path settings or upper/lowercase names in your context)

**Comment by flankechen** [comment]
@martin-frbg thanks for your help, problem solved. Eigen use blas in a fortran way, I have to compile openblas with fortran.
