### ISSUE TITLE
no such instruction when compiled with gcc 4.5.1 on linux

### ISSUE THREAD

**Issue by wlike** [xianyi/OpenBLAS#1488]
![image](https://user-images.githubusercontent.com/6084282/37462747-f8999772-288d-11e8-821d-e403f52a28c3.png)

**Comment by martin-frbg** [comment]
gcc as such is not the problem, but your assembler is too old to understand AVX instructions. Either upgrade the binutils package or build with `make NO_AVX=1` (which will cost some performance).

**Comment by wlike** [comment]
cat /proc/cpuinfo | grep avx

![image](https://user-images.githubusercontent.com/6084282/37463177-5e4bde4e-288f-11e8-8ae4-4c0c578b0b0e.png)

**Comment by martin-frbg** [comment]
That tells you what your cpu understands, you still need an assembler that transforms the (somewhat) human-readable instructions like "vaddps" into streams of bits that the cpu can process.

**Comment by wlike** [comment]
Ok, thanks very much!
