### ISSUE TITLE
error while loading shared libraries: libopenblas.so.0

### ISSUE THREAD

**Issue by xzy256** [xianyi/OpenBLAS#1489]
hello xianyi,
I build OpenBLAS and install successfully and set the path to installation in `~/.bashrc`. When i run a example, i get the error. How should i do for running the example.c correctly?
>  error while loading shared libraries: libopenblas.so.0: cannot open shared object file: No such file or directory

[example.c]
```
#include <cblas.h>
#include <stdio.h>

int main(void) {
    int i = 0;
    double A[6] = {1.0,2.0,1.0,-3.0,4.0,-1.0};
    double B[6] = {1.0,2.0,1.0,-3.0,4.0,-1.0};
    double C[9] = {.5,.5,.5,.5,.5,.5,.5,.5,.5};
    int M = 3; // row of A and C
    int N = 3; // col of B and C
    int K = 2; // col of A and row of B
    double alpha = 1.0;
    double beta = 0.0;
    cblas_dgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans, M, N, K, alpha, A, K, B, N, beta, C, N);
    for (i = 0; i < 9; i++) {
        printf("%lf ", C[i]);
    }
    printf("\n");
    return 0;
}
```

the trace log:

> $gcc -o example example.c -I /usr/lib/OpenBLAS/include -L /usr/lib/OpenBLAS/lib -lopenblas -lpthread
> $./example
> ./example: error while loading shared libraries: libopenblas.so.0: cannot open shared object file: No such file or directory

**Comment by martin-frbg** [comment]
You need to add this non-standard library path to your /etc/ld.so.conf (and run `ldconfig` once), or add
`export LD_LIBRARY_PATH=/usr/lib/OpenBLAS/lib` to your .bashrc (and make sure this file is actually read by your system, and alternative would be to put such settings in .profile)

**Comment by xzy256** [comment]
Thanks for your attention. I add 'LD_LIBRARY_PATH', it works.

**Comment by Sauron-Annatar** [comment]
cool ! I encounter this problem as well , we should add **'LD_LIBRARY_PATH'**
