### ISSUE TITLE
SVD hangs for some arrays, on Ubuntu 16.04.

### ISSUE THREAD

**Issue by matthew-brett** [xianyi/OpenBLAS#1490]
Sorry not to have (yet) built a C test case, but over at [Numpy](https://github.com/numpy/numpy/issues/10742), we've hit an odd case where it is possible to lock the process with a call to SVD, when linked with OpenBLAS.

You can replicate it thus:

```
docker pull ubuntu:16.04
docker run -ti --rm ubuntu:16.04 /bin/bash
```

then (in the container):

```
# Get Python / OpenBLAS library
apt-get update
apt-get install -y python3 curl libopenblas-dev
# Get Pip to install Numpy
curl -LO https://bootstrap.pypa.io/get-pip.py
python3 get-pip.py
# Install Numpy from source, linking to OpenBLAS
pip install --no-binary numpy numpy
# Warning - this will lock the process!
python3 -c 'import numpy as np; R = np.array([[1. , 0. , np.nan], [0. , 0 , np.nan], [ 0. , 0, np.nan]]) ;np.linalg.svd(R)'
```

We get the same hang for all settings of OPENBLAS_CORETYPE - see: https://github.com/nipy/nibabel/issues/609#issuecomment-373052723

Have you seen anything like this?

**Comment by martin-frbg** [comment]
There was #1343 recently, also known as https://github.com/numpy/numpy/issues/9949 or https://github.com/Reference-LAPACK/lapack/issues/196 (some LAPACK functions entering an endless loop trying to rescale an invalid argument). The np.nan in your test case would probably fit the bill (not all parts of OpenBLAS or LAPACK are NaN-safe), as would the fact that all cpu types are affected. Is this with (unpatched) 0.2.20, or current develop branch ?

**Comment by matthew-brett** [comment]
This is with 0.2.18 (the version in the Ubuntu 16.04 package).   Those bugs do look plausible - I'll try a build with the latest master commit.

**Comment by matthew-brett** [comment]
Unfortunately it does not appear to be fixed - it still hangs when linking against the latest OpenBLAS commit.

Builds of latest commit at:

https://3f23b170c54c2533c070-1c8a9b3114517dc5fe17b7c3f8c63a43.ssl.cf2.rackcdn.com

Builds from:

https://travis-ci.org/MacPython/openblas-libs/builds/354382616

Builds of numpy against this OpenBLAS, starting with `numpy-1.15.0.dev0+20180316170204`

https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com

Builds from:

https://travis-ci.org/MacPython/numpy-wheels/builds/354401544

Replicating hang:

```
docker pull ubuntu:16.04
docker run -ti --rm ubuntu:16.04 /bin/bash
```

```
# Get Python / OpenBLAS library
apt-get update
apt-get install -y python3 curl
# Get Pip to install Numpy
curl -LO https://bootstrap.pypa.io/get-pip.py
python3 get-pip.py
# Install Numpy from new wheel that links to latest OpenBLAS
CDN_URL=https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com
pip install --pre -f $CDN_URL numpy
# Warning - this will still lock the process!
python3 -c 'import numpy as np; R = np.array([[1. , 0. , np.nan], [0. , 0 , np.nan], [ 0. , 0, np.nan]]) ;np.linalg.svd(R)'
```

**Comment by matthew-brett** [comment]
That was with master - testing now with latest develop branch.

**Comment by matthew-brett** [comment]
OK - as you predicted, fixed with develop branch - thanks.
