### ISSUE TITLE
Test failures for 32-bit macOS compile

### ISSUE THREAD

**Issue by matthew-brett** [xianyi/OpenBLAS#1492]
I have just noticed that, when updating to latest `develop` branch, I am getting test failures when compiling for 32-bit macOS only.  `make test` seems to fail (but runs to completion on 64-bit):

https://travis-ci.org/MacPython/openblas-libs/jobs/354493385

```
Note: The following floating-point exceptions are signalling: IEEE_DIVIDE_BY_ZERO
Note: The following floating-point exceptions are signalling: IEEE_DIVIDE_BY_ZERO
Note: The following floating-point exceptions are signalling: IEEE_DIVIDE_BY_ZERO
Note: The following floating-point exceptions are signalling: IEEE_DIVIDE_BY_ZERO
Note: The following floating-point exceptions are signalling: IEEE_DENORMAL
Note: The following floating-point exceptions are signalling: IEEE_DENORMAL
make[1]: *** [run_test] Error 1
make: *** [tests] Error 2
```

**Comment by martin-frbg** [comment]
Which (emulated) hardware is this trying to build on ? (I think I see you are using the current develop branch, which should be good, but I cannot figure out much more. From the long list of what seem to be mobile devices at the start, could it be armv7 which received patches for softfp support relatively recently ?) Any chance to find out _which_ of the tests are failing ? And which if any version used to pass these tests before ?

**Comment by matthew-brett** [comment]
The building machinery is here:

https://github.com/MacPython/openblas-libs

The build that is failing is the 32-bit build of OpenBLAS, on 64-bit macOS - so no emulation, just a 32-bit build.  This just corresponds to:

```
make DYNAMIC_ARCH=1 USE_OPENMP=0 NUM_THREADS=64 BINARY=32
```

I don't know what test is failing - but I am running the same thing now on my desktop.

**Comment by matthew-brett** [comment]
Ok - here is the test output on my desktop:

```
./openblas_utest
TEST 1/22 amax:samax [OK]
TEST 2/22 drotmg:rotmg [OK]
TEST 3/22 drotmg:rotmg_issue1452 [OK]
TEST 4/22 drotmg:rotmg_D1eqD2_X1eqX2 [OK]
TEST 5/22 drotmg:drotmg_D1_big_D2_big_flag_zero [OK]
TEST 6/22 axpy:daxpy_inc_0 [OK]
TEST 7/22 axpy:zaxpy_inc_0 [OK]
TEST 8/22 axpy:saxpy_inc_0 [OK]
TEST 9/22 axpy:caxpy_inc_0 [OK]
TEST 10/22 zdotu:zdotu_n_1 [OK]
TEST 11/22 zdotu:zdotu_offset_1 [OK]
TEST 12/22 dsdot:dsdot_n_1 [FAIL]
  ERR: test_dsdot.c:47  expected -2.393e-03, got -2.393e-03 (diff -1.035e-10, tol 1.000e-13)
TEST 13/22 swap:dswap_inc_0 [OK]
TEST 14/22 swap:zswap_inc_0 [OK]
TEST 15/22 swap:sswap_inc_0 [OK]
TEST 16/22 swap:cswap_inc_0 [OK]
TEST 17/22 rot:drot_inc_0 [OK]
TEST 18/22 rot:zdrot_inc_0 [OK]
TEST 19/22 rot:srot_inc_0 [OK]
TEST 20/22 rot:csrot_inc_0 [OK]
TEST 21/22 potrf:bug_695 [OK]
TEST 22/22 potrf:smoketest_trivial [OK]
RESULTS: 22 tests (21 ok, 1 failed, 0 skipped) ran in 2 ms
```

**Comment by matthew-brett** [comment]
Sorry - I should say - it passes (on Travis-CI) on master.

**Comment by martin-frbg** [comment]
So x86_64 hardware ? 32bit on Haswell or newer is falling back to nehalem kernel I think, and dsdot optimization is new. So no failure in `tests` but in the recently revived `utests` (and the divsion by zero signals all coming from that failed test) ?

**Comment by martin-frbg** [comment]
And I recognize the failure now - this is the limited precision of the older of the two C fallback kernels for (ds)dot. (From #1469, and kernel/x86/KERNEL still sets DSDOT to the inferior arm/dot.c - interestingly this does not cause problems for my local BINARY=32 test builds on Kaby Lake i.e. Haswell)

**Comment by matthew-brett** [comment]
Yes, right, x86_64 hardware.  I can't see the signalling reports on my desktop, that came up on the travis logs.

**Comment by martin-frbg** [comment]
PR incoming, I'll commit as obvious once travis and appveyor tests are through.

**Comment by matthew-brett** [comment]
Is there a travis test entry for the 32-bit build on Mac?

**Comment by martin-frbg** [comment]
I don't think so, but it would certainly be a welcome addition (64bit Mac as well)

**Comment by matthew-brett** [comment]
I found your travis.yml file a bit intimidating ...

**Comment by martin-frbg** [comment]
I found that yours looks completely different, which intimidated _me_ ... no idea if the OpenBLAS one was originally written for an earlier version of travis, or by people with as little knowledge of travis as me

**Comment by matthew-brett** [comment]
Yes, sorry, mine is a sort of sketch based on my "multibuild" framework, so it's more opaque than it needs to be.  I threw it together rather quickly ...  For yours, I didn't understand the YAML stuff like "&common-before" and "<<: *test-ubuntu"  and how `TARGET_BOX` worked.

**Comment by martin-frbg** [comment]
Well, don't ask me, I'm just a user turned project janitor...
I see now that travis has an online validator for yml files, so maybe I can test there without risking to break the OpenBLAS build system first.

**Comment by martin-frbg** [comment]
At least the original topic should hopefully be fixed now... will be interesting to see if the "exceptions are signalling" stuff is gone as well or if travis still reports a failure. (Even with the low-precision dsdot there should not have been a chance for divide-by-zero errors, so maybe something else is still amiss at least with the cpu environment provided by travis)

**Comment by matthew-brett** [comment]
Tests now passing on 32-bit: https://travis-ci.org/MacPython/openblas-libs/builds/354863798

**Comment by martin-frbg** [comment]
Thanks. I am giving up on adding osx to the travis.yml file for now.
