### ISSUE TITLE
Is generic gemmkernel_2x2.c known to be correct?

### ISSUE THREAD

**Issue by honnibal** [xianyi/OpenBLAS#1498]
Hi all,

I've been trying to include OpenBLAS's sgemm function in a Python library, and I had trouble convincing Visual Studio to compile the .S files. So I decided to just get the single-threaded generic kernel working as an intermediate step.

I'm able to compile, but I'm getting incorrect sgemm results (on both Linux and Windows). Are there any config variables that would affect the calculations that I might not have set? For instance, do the config variables like `SGEMM_UNROLL_M` and `SGEMM_UNROLL_N` only affect efficiency, or could setting one of these incorrectly change the calculations?

I see the `gemm_kernel_2x2.c file hasn't changed in a long time, but I'm also not sure it's regularly used. Is it known to be correct, or could the incorrect calculations be due to a bug?

Edit: Hmm all the tests do pass when building with `TARGET=GENERIC`. So I must have some configuration wrong. Any ideas what I might be missing?

The results aren't just a little off -- they're completely wrong, e.g.

```
E       AssertionError: 
E       Not equal to tolerance rtol=1e-07, atol=0
E       
E       (mismatch 100.0%)
E        x: array([[0.677028, 0.818103, 0.965756],
E              [0.838492, 1.073991, 0.902315],
E              [0.086371, 0.108784, 0.101864],
E              [0.54635 , 0.751355, 0.338745]], dtype=float32)
E        y: array([[0.3813  , 0.409797, 0.790194],
E              [0.253714, 0.266599, 0.555156],
E              [0.280345, 0.309137, 0.543085],
E              [0.929918, 1.147537, 1.211224]], dtype=float32)
```

**Comment by martin-frbg** [comment]
At least it is not currently known to be incorrect. Not knowing exactly what you tried, perhaps you got the input wrong ? Also, a regular build with MSVC should default to the generic kernels (as MSVC does not handle the AT&T idiom used in the assembly files) so no need to cherry-pick isolated functions. As an alternative you could also install the clang compiler, which is able to use all the optimized assembly kernels (and with flang, allow building the LAPACK part as well, although that procedure is still a bit experimental).

**Comment by honnibal** [comment]
@martin-frbg I've now gotten this working with LLVM. Thanks for the confirmation that getting the kernels to compile under MSVC can't work, that's useful. I still don't know why I got the wrong results for the generic kernel, but I'll close this as it seems very unlikely it's the code --- I must have gotten part of the compilation process wrong.

> no need to cherry-pick isolated functions.

I'm shipping this as part of a Python library, so I want to cherry-pick to reduce compilation times.

For anyone's future reference, the Python setup.py file is here: https://github.com/explosion/thinc/blob/099aabcfd88970d1fdb23b8906dddc48f744b416/setup.py . Note that this doesn't currently handle architecture detection --- it just blindly builds the Haswell kernel.
