### ISSUE TITLE
how to build for armv7 on ubuntu64bit?

### ISSUE THREAD

**Issue by wl3b10s** [xianyi/OpenBLAS#1514]
i use command make TARGET=ARMV7

but got message:
"
ar  -ru ../../libopenblas_armv7p-r0.3.0.dev.a memory.o xerbla.o c_abs.o z_abs.o openblas_set_num_threads.o openblas_get_num_threads.o openblas_get_num_procs.o openblas_get_config.o openblas_get_parallel.o openblas_error_handle.o openblas_env.o blas_server.o divtable.o blasL1thread.o parameter.o
ar: `u' modifier ignored since `D' is the default (see `U')
make[1]: Leaving directory '/mnt/SD/GitData/OpenBLAS-develop20180410/driver/others'
make[1]: Entering directory '/mnt/SD/GitData/OpenBLAS-develop20180410/kernel'
cc -c -O2 -DMAX_STACK_ALLOC=2048 -Wall -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=8 -DASMNAME=samax_k -DASMFNAME=samax_k_ -DNAME=samax_k_ -DCNAME=samax_k -DCHAR_NAME=\"samax_k_\" -DCHAR_CNAME=\"samax_k\" -DNO_AFFINITY -I.. -UDOUBLE  -UCOMPLEX -UCOMPLEX -UDOUBLE  -DUSE_ABS -UUSE_MIN ../kernel/arm64/amax.S -o samax_k.o
make[1]: *** No rule to make target '../kernel/arm64/amin.S', needed by 'samin_k.o'.  Stop.
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/mnt/SD/GitData/OpenBLAS-develop20180410/kernel'
Makefile:134: recipe for target 'libs' failed
make: *** [libs] Error 1
"

why? seems make some file using arm64 dir?

**Comment by martin-frbg** [comment]
Did you follow https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android ?

**Comment by wl3b10s** [comment]
ok，  finally this command works:

"make TARGET=ARMV7 HOSTCC=gcc BINARY=32 CC=arm-linux-gnueabihf-gcc NOFORTRAN=1 libs"
