### ISSUE TITLE
member at 357266 is not an ELF object

### ISSUE THREAD

**Issue by cs123951** [xianyi/OpenBLAS#1517]
I successfully make a libopenblas_core2p-r0.2.20.a file in windows, and use it in android studio through CMakelist.txt, but it goes wrong.

D:/Softwares/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: ../../../../src/main/jniLibs/armeabi-v7a/libopenblas_soft.a: member at 297598 is not an ELF object
D:/Softwares/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: ../../../../src/main/jniLibs/armeabi-v7a/libopenblas_soft.a: member at 357266 is not an ELF object
E:\Projects\Android\app\src\main\cpp\mtcnn/network.cpp:166: error: undefined reference to 'cblas_sgemm'
E:\Projects\Android\app\src\main\cpp\mtcnn/network.cpp:173: error: undefined reference to 'cblas_sgemm'
E:\Projects\Android\app\src\main\cpp\mtcnn/network.cpp:311: error: undefined reference to 'cblas_sgemv'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by martin-frbg** [comment]
The "core2" in the filename suggests that it was built for Intel processors (probably what your Windows system runs on), not for Arm. Did you follow https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android ?

**Comment by cs123951** [comment]
hello， @martin-frbg 
i have tired using target=armv7 to build openblas, but it could not compile successfully, 
error information shown below:

ar: sgemm_kernel.o: No such file or directory

**Comment by martin-frbg** [comment]
Can you attach the complete build log please ? Problems with the gemm kernels usually happen when the build system does not manage to identifiy the cpu, but I think this should not happen on armv7.

**Comment by cs123951** [comment]
@martin-frbg I don't know how to save complete build log, so I attach the last several outputs in the command line .

```
gcc -c -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=2 -DASMNAME=scabs1 -DASMFNAME=scabs1_ -DNAME=scabs1_ -DCNAME=scabs1 -DCHAR_NAME=\"scabs1_\" -DCHAR_CNAME=\"scabs1\" -DNO_AFFINITY -I.. -DCOMPLEX -UDOUBLE -DF_INTERFACE ../kernel/x86_64/cabs.S -o scabs1.o
generic/zlaswp_ncopy_2.c: 在函数‘zlaswp_ncopy’中:
generic/zlaswp_ncopy_2.c:133:4: 警告：this ‘else’ clause does not guard... [-Wmisleading-indentation]
  } else
    ^~~~
generic/zlaswp_ncopy_2.c:209:4: 附注：...this statement, but the latter is misleadingly indented as if it is guarded by the ‘else’
    buffer += 8;
    ^~~~~~
In file included from ../kernel/x86_64/cabs.S:40:0:
../common.h:326:0: 警告：“YIELDING”重定义
 #define YIELDING        asm volatile ("nop;nop;nop;nop;nop;nop;nop;nop; \n");

../common.h:321:0: 附注：这是先前定义的位置
 #define YIELDING SwitchToThread()

gcc -c -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=2 -DASMNAME=dcabs1 -DASMFNAME=dcabs1_ -DNAME=dcabs1_ -DCNAME=dcabs1 -DCHAR_NAME=\"dcabs1_\" -DCHAR_CNAME=\"dcabs1\" -DNO_AFFINITY -I.. -DCOMPLEX -DDOUBLE -DF_INTERFACE ../kernel/x86_64/cabs.S -o dcabs1.o
In file included from ../kernel/x86_64/cabs.S:40:0:
../common.h:326:0: 警告：“YIELDING”重定义
 #define YIELDING        asm volatile ("nop;nop;nop;nop;nop;nop;nop;nop; \n");

../common.h:321:0: 附注：这是先前定义的位置
 #define YIELDING SwitchToThread()

ar  -ru ../libopenblas_armv7p-r0.2.20.a samax_k.o samin_k.o smax_k.o smin_k.o isamax_k.o isamin_k.o ismax_k.o ismin_k.o sasum_k.o saxpy_k.o scopy_k.o sdot_k.o sdsdot_k.o dsdot_k.o snrm2_k.o srot_k.o sscal_k.o sswap_k.o saxpby_k.o sgemv_n.o sgemv_t.o ssymv_U.o ssymv_L.o sger_k.o sgemm_kernel.o sgemm_beta.o strmm_kernel_LN.o strmm_kernel_LT.o strmm_kernel_RN.o strmm_kernel_RT.o strsm_kernel_LN.o strsm_kernel_LT.o strsm_kernel_RN.o strsm_kernel_RT.o strmm_iunucopy.o strmm_iunncopy.o strmm_ilnucopy.o strmm_ilnncopy.o strmm_iutucopy.o strmm_iutncopy.o strmm_iltucopy.o strmm_iltncopy.o strmm_ounucopy.o strmm_ounncopy.o strmm_olnucopy.o strmm_olnncopy.o strmm_outucopy.o strmm_outncopy.o strmm_oltucopy.o strmm_oltncopy.o strsm_iunucopy.o strsm_iunncopy.o strsm_ilnucopy.o strsm_ilnncopy.o strsm_iutucopy.o strsm_iutncopy.o strsm_iltucopy.o strsm_iltncopy.o strsm_ounucopy.o strsm_ounncopy.o strsm_olnucopy.o strsm_olnncopy.o strsm_outucopy.o strsm_outncopy.o strsm_oltucopy.o strsm_oltncopy.o ssymm_iutcopy.o ssymm_iltcopy.o ssymm_outcopy.o ssymm_oltcopy.o somatcopy_k_cn.o somatcopy_k_rn.o somatcopy_k_ct.o somatcopy_k_rt.o simatcopy_k_cn.o simatcopy_k_rn.o simatcopy_k_ct.o simatcopy_k_rt.o sgeadd_k.o sneg_tcopy.o slaswp_ncopy.o damax_k.o damin_k.o dmax_k.o dmin_k.o idamax_k.o idamin_k.o idmax_k.o idmin_k.o dasum_k.o daxpy_k.o dcopy_k.o ddot_k.o dnrm2_k.o drot_k.o dscal_k.o dswap_k.o daxpby_k.o dgemv_n.o dgemv_t.o dsymv_U.o dsymv_L.o dger_k.o dgemm_kernel.o dgemm_beta.o dtrmm_kernel_LN.o dtrmm_kernel_LT.o dtrmm_kernel_RN.o dtrmm_kernel_RT.o dtrsm_kernel_LN.o dtrsm_kernel_LT.o dtrsm_kernel_RN.o dtrsm_kernel_RT.o dtrmm_iunucopy.o dtrmm_iunncopy.o dtrmm_ilnucopy.o dtrmm_ilnncopy.o dtrmm_iutucopy.o dtrmm_iutncopy.o dtrmm_iltucopy.o dtrmm_iltncopy.o dtrmm_ounucopy.o dtrmm_ounncopy.o dtrmm_olnucopy.o dtrmm_olnncopy.o dtrmm_outucopy.o dtrmm_outncopy.o dtrmm_oltucopy.o dtrmm_oltncopy.o dtrsm_iunucopy.o dtrsm_iunncopy.o dtrsm_ilnucopy.o dtrsm_ilnncopy.o dtrsm_iutucopy.o dtrsm_iutncopy.o dtrsm_iltucopy.o dtrsm_iltncopy.o dtrsm_ounucopy.o dtrsm_ounncopy.o dtrsm_olnucopy.o dtrsm_olnncopy.o dtrsm_outucopy.o dtrsm_outncopy.o dtrsm_oltucopy.o dtrsm_oltncopy.o dsymm_iutcopy.o dsymm_iltcopy.o dsymm_outcopy.o dsymm_oltcopy.o domatcopy_k_cn.o domatcopy_k_rn.o domatcopy_k_ct.o domatcopy_k_rt.o dimatcopy_k_cn.o dimatcopy_k_rn.o dimatcopy_k_ct.o dimatcopy_k_rt.o dgeadd_k.o dneg_tcopy.o dlaswp_ncopy.o camax_k.o camin_k.o icamax_k.o icamin_k.o casum_k.o caxpy_k.o caxpyc_k.o ccopy_k.o cdotc_k.o cdotu_k.o cnrm2_k.o csrot_k.o cscal_k.o cswap_k.o caxpby_k.o cgemv_n.o cgemv_t.o cgemv_r.o cgemv_c.o cgemv_o.o cgemv_u.o cgemv_s.o cgemv_d.o csymv_U.o csymv_L.o chemv_U.o chemv_L.o chemv_V.o chemv_M.o cgeru_k.o cgerc_k.o cgerv_k.o cgerd_k.o cgemm_kernel_n.o cgemm_kernel_r.o cgemm_kernel_l.o cgemm_kernel_b.o cgemm_beta.o ctrmm_kernel_LN.o ctrmm_kernel_LT.o ctrmm_kernel_LR.o ctrmm_kernel_LC.o ctrmm_kernel_RN.o ctrmm_kernel_RT.o ctrmm_kernel_RR.o ctrmm_kernel_RC.o ctrsm_kernel_LN.o ctrsm_kernel_LT.o ctrsm_kernel_LR.o ctrsm_kernel_LC.o ctrsm_kernel_RN.o ctrsm_kernel_RT.o ctrsm_kernel_RR.o ctrsm_kernel_RC.o cgemm3m_kernel.o ctrmm_iunucopy.o ctrmm_iunncopy.o ctrmm_ilnucopy.o ctrmm_ilnncopy.o ctrmm_iutucopy.o ctrmm_iutncopy.o ctrmm_iltucopy.o ctrmm_iltncopy.o ctrmm_ounucopy.o ctrmm_ounncopy.o ctrmm_olnucopy.o ctrmm_olnncopy.o ctrmm_outucopy.o ctrmm_outncopy.o ctrmm_oltucopy.o ctrmm_oltncopy.o ctrsm_iunucopy.o ctrsm_iunncopy.o ctrsm_ilnucopy.o ctrsm_ilnncopy.o ctrsm_iutucopy.o ctrsm_iutncopy.o ctrsm_iltucopy.o ctrsm_iltncopy.o ctrsm_ounucopy.o ctrsm_ounncopy.o ctrsm_olnucopy.o ctrsm_olnncopy.o ctrsm_outucopy.o ctrsm_outncopy.o ctrsm_oltucopy.o ctrsm_oltncopy.o csymm_iutcopy.o csymm_iltcopy.o csymm_outcopy.o csymm_oltcopy.o chemm_iutcopy.o chemm_iltcopy.o chemm_outcopy.o chemm_oltcopy.o cgemm3m_incopyb.o cgemm3m_itcopyb.o cgemm3m_incopyr.o cgemm3m_itcopyr.o cgemm3m_incopyi.o cgemm3m_itcopyi.o cgemm3m_oncopyb.o cgemm3m_otcopyb.o cgemm3m_oncopyr.o cgemm3m_otcopyr.o cgemm3m_oncopyi.o cgemm3m_otcopyi.o csymm3m_iucopyb.o csymm3m_oucopyb.o csymm3m_iucopyr.o csymm3m_oucopyr.o csymm3m_iucopyi.o csymm3m_oucopyi.o csymm3m_ilcopyb.o csymm3m_olcopyb.o csymm3m_ilcopyr.o csymm3m_olcopyr.o csymm3m_ilcopyi.o csymm3m_olcopyi.o chemm3m_iucopyb.o chemm3m_oucopyb.o chemm3m_iucopyr.o chemm3m_oucopyr.o chemm3m_iucopyi.o chemm3m_oucopyi.o chemm3m_ilcopyb.o chemm3m_olcopyb.o chemm3m_ilcopyr.o chemm3m_olcopyr.o chemm3m_ilcopyi.o chemm3m_olcopyi.o comatcopy_k_cn.o comatcopy_k_rn.o comatcopy_k_ct.o comatcopy_k_rt.o comatcopy_k_cnc.o comatcopy_k_rnc.o comatcopy_k_ctc.o comatcopy_k_rtc.o cimatcopy_k_cn.o cimatcopy_k_rn.o cimatcopy_k_ct.o cimatcopy_k_rt.o cimatcopy_k_cnc.o cimatcopy_k_rnc.o cimatcopy_k_ctc.o cimatcopy_k_rtc.o cgeadd_k.o cneg_tcopy.o claswp_ncopy.o zamax_k.o zamin_k.o izamax_k.o izamin_k.o zasum_k.o zaxpy_k.o zaxpyc_k.o zcopy_k.o zdotc_k.o zdotu_k.o znrm2_k.o zdrot_k.o zscal_k.o zswap_k.o zaxpby_k.o zgemv_n.o zgemv_t.o zgemv_r.o zgemv_c.o zgemv_o.o zgemv_u.o zgemv_s.o zgemv_d.o zsymv_U.o zsymv_L.o zhemv_U.o zhemv_L.o zhemv_V.o zhemv_M.o zgeru_k.o zgerc_k.o zgerv_k.o zgerd_k.o zgemm_kernel_n.o zgemm_kernel_r.o zgemm_kernel_l.o zgemm_kernel_b.o zgemm_beta.o ztrmm_kernel_LN.o ztrmm_kernel_LT.o ztrmm_kernel_LR.o ztrmm_kernel_LC.o ztrmm_kernel_RN.o ztrmm_kernel_RT.o ztrmm_kernel_RR.o ztrmm_kernel_RC.o ztrsm_kernel_LN.o ztrsm_kernel_LT.o ztrsm_kernel_LR.o ztrsm_kernel_LC.o ztrsm_kernel_RN.o ztrsm_kernel_RT.o ztrsm_kernel_RR.o ztrsm_kernel_RC.o zgemm3m_kernel.o ztrmm_iunucopy.o ztrmm_iunncopy.o ztrmm_ilnucopy.o ztrmm_ilnncopy.o ztrmm_iutucopy.o ztrmm_iutncopy.o ztrmm_iltucopy.o ztrmm_iltncopy.o ztrmm_ounucopy.o ztrmm_ounncopy.o ztrmm_olnucopy.o ztrmm_olnncopy.o ztrmm_outucopy.o ztrmm_outncopy.o ztrmm_oltucopy.o ztrmm_oltncopy.o ztrsm_iunucopy.o ztrsm_iunncopy.o ztrsm_ilnucopy.o ztrsm_ilnncopy.o ztrsm_iutucopy.o ztrsm_iutncopy.o ztrsm_iltucopy.o ztrsm_iltncopy.o ztrsm_ounucopy.o ztrsm_ounncopy.o ztrsm_olnucopy.o ztrsm_olnncopy.o ztrsm_outucopy.o ztrsm_outncopy.o ztrsm_oltucopy.o ztrsm_oltncopy.o zsymm_iutcopy.o zsymm_iltcopy.o zsymm_outcopy.o zsymm_oltcopy.o zhemm_iutcopy.o zhemm_iltcopy.o zhemm_outcopy.o zhemm_oltcopy.o zgemm3m_incopyb.o zgemm3m_itcopyb.o zgemm3m_incopyr.o zgemm3m_itcopyr.o zgemm3m_incopyi.o zgemm3m_itcopyi.o zgemm3m_oncopyb.o zgemm3m_otcopyb.o zgemm3m_oncopyr.o zgemm3m_otcopyr.o zgemm3m_oncopyi.o zgemm3m_otcopyi.o zsymm3m_iucopyb.o zsymm3m_oucopyb.o zsymm3m_iucopyr.o zsymm3m_oucopyr.o zsymm3m_iucopyi.o zsymm3m_oucopyi.o zsymm3m_ilcopyb.o zsymm3m_olcopyb.o zsymm3m_ilcopyr.o zsymm3m_olcopyr.o zsymm3m_ilcopyi.o zsymm3m_olcopyi.o zhemm3m_iucopyb.o zhemm3m_oucopyb.o zhemm3m_iucopyr.o zhemm3m_oucopyr.o zhemm3m_iucopyi.o zhemm3m_oucopyi.o zhemm3m_ilcopyb.o zhemm3m_olcopyb.o zhemm3m_ilcopyr.o zhemm3m_olcopyr.o zhemm3m_ilcopyi.o zhemm3m_olcopyi.o zomatcopy_k_cn.o zomatcopy_k_rn.o zomatcopy_k_ct.o zomatcopy_k_rt.o zomatcopy_k_cnc.o zomatcopy_k_rnc.o zomatcopy_k_ctc.o zomatcopy_k_rtc.o zimatcopy_k_cn.o zimatcopy_k_rn.o zimatcopy_k_ct.o zimatcopy_k_rt.o zimatcopy_k_cnc.o zimatcopy_k_rnc.o zimatcopy_k_ctc.o zimatcopy_k_rtc.o zgeadd_k.o zneg_tcopy.o zlaswp_ncopy.o lsame.o scabs1.o dcabs1.o
ar: sgemm_kernel.o: No such file or directory
make[1]: *** [../Makefile.tail:40：libs] Error 1
make[1]: 离开目录“/cygdrive/d/GoogleDownload/OpenBLAS-0.2.20/kernel”
make: *** [Makefile:139：libs] error 1
```

**Comment by martin-frbg** [comment]
You can append a redirection command to the "make" commandline to write the output to a file,
`make TARGET=ARMV7 (and all the other make options) >makelog.txt` 
By the way the output you posted looks like it is still trying to build at least some parts for Intel, what _is_ your make commandline ?

**Comment by cs123951** [comment]
@martin-frbg
thanks,
my commandline is:  `make TARGET=ARMV7 BINARY=64`

**Comment by martin-frbg** [comment]
Can you please try with setting CC to the cross-compiler from the android studio ndk, and all the other settings as described in the wiki page I linked above ? I think part of your problem is that you are using the system compiler that knows only x86_64, not the one that can build arm binaries.

**Comment by cs123951** [comment]
the log of `TARGET=ARMV7 `is as following: https://github.com/cs123951/Application/blob/master/makelog_armv7.txt

by the way, I tried use CC
`make TARGET=ARMV7 CC=/cygdrive/d/Softwares/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-gcc.exe >makelog.txt`
but error occurs:
```
Admin@Admin-PC /cygdrive/d/GoogleDownload/OpenBLAS-0.2.20
$ make TARGET=ARMV7 CC=/cygdrive/d/Softwares/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-gcc.exe >makelog.txt
getarch.c:80:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminated.
make: *** [Makefile.prebuild:54：getarch] 错误 1
Makefile.system:958: Makefile.: No such file or directory
make: *** 没有规则可制作目标“Makefile.”。 停止。
```

**Comment by martin-frbg** [comment]
That log is definitely using the wrong gcc.
For the error about missing stdio.h, you can try setting `CFLAGS=--sysroot=/cygdrive/d/Softwares/android-ndk-r16b/platforms/android-16/arch-arm` (or whatever is the correct path to arch-arm in your version of the ndk). Did you build a "standalone toolchain" from the ndk as suggested in the wiki (there is a make_standalone_toolchain script included with the ndk for this purpose) ?

**Comment by cs123951** [comment]
@martin-frbg  
I've tried setting CFLAS,but this error still happened.
```
$ make TARGET=ARMV7 CFLAGS=--sysroot=/cygdrive/d/Softwares/android-ndk-r16b/sysroot/usr/include CC=/cygdrive/d/Softwares/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-gcc.exe  >makelog.txt
getarch.c:80:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminated.
make: *** [Makefile.prebuild:54：getarch] 错误 1
Makefile.system:958: Makefile.: No such file or directory
make: *** 没有规则可制作目标“Makefile.”。 停止。
```

I haven't built a standalone toolchain, I used the toolchain downloaded from github.
Maybe I should try to build a standalone toolchain?

**Comment by cs123951** [comment]
I built a standalone toolchain,  and do following make:

`make TARGET=ARMV7 CFLAGS="$CFLAGS -I/cygdrive/d/Softwares/android-ndk-r16b/my-android-toolchain/sysroot/usr/include" AR=ar CC=/cygdrive/d/Softwares/android-ndk-r16b/my-android-toolchain/bin/aarch64-linux-android-gcc.exe HOSTCC=gcc  NOFORTRAN=1 >makelog.txt`

error happens:
```
make[1]: *** No rule to make target '../kernel/arm64/amin.S', needed by 'samin_k.o'. Stop.
make[1]: *** Waiting for unfinished jobs....
make: *** [libs] Error 1
```
logfile is uploaded to
https://github.com/cs123951/Application/blob/master/makelog_o.txt

**Comment by martin-frbg** [comment]
Shouldn't that CC in your toolchain be called something like arm-linux-androideabi-gcc.exe (like you had before) ? With the 64-bit aarch64 compiler it seems to be confused between building (32bit) ARMV7 and (64bit) ARMV8 code apparently.

**Comment by cs123951** [comment]
I use this command to build toolchain:
`python make_standalone_toolchain.py --arch arm64 --api 26 --install-dir D:\\Softwares\\android-ndk-r16b\\my-android-toolchain `
The generated toolchain doesn't have something like arm-linux-androideabi-gcc.exe, but have something like aarch64-linux-android-gcc.exe

**Comment by martin-frbg** [comment]
Are you sure about the `--arch arm64` ? As far as I know, all ARMV7 are 32bit cpus. So I suppose you would either want `--arch arm` here for the toolchain or `TARGET=ARMV8` for the OpenBLAS build.
What is your target hardware ?

**Comment by cs123951** [comment]
my target hardware is 64bit, 
I changed the make command to` TARGET=ARMV8`, and error happened:
` ar: sgemm_kernel.o: No such file or directory`
attached log:https://github.com/cs123951/Application/blob/master/makelog_armv8.txt

**Comment by martin-frbg** [comment]
Unfortunately that latest log has lots of references to the x86_64 parts of OpenBLAS again, so it looks like your make command was incomplete. Did you set up CLANG_CFLAGS and the make command as described in the last section of https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android ?

**Comment by cs123951** [comment]
I make command as described in the last section of https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android . I also tried adding CFLAGS, but it seems not worked.
error occured:
` fatal error: 'stdio.h' file not found`

My command list:
```
export NDK_BUNDLE_DIR=/cygdrive/d/Softwares/android-ndk-r16b
export LDFLAGS="-L${NDK_BUNDLE_DIR}/my-android-toolchain/lib/gcc/aarch64-linux-android/4.9.x -lm" 
export CLANG_FLAGS="-target aarch64-linux-android -marm -mfpu=vfp -mfloat-abi=softfp --sysroot ${NDK_BUNDLE_DIR}/my-android-toolchain/sysroot/usr/include -gcc-toolchain ${NDK_BUNDLE_DIR}/my-android-toolchain"
export PATH=$PATH:/cygdrive/d/Softwares/android-ndk-r16b/my-android-toolchain/bin:
export CFLAGS=--sysroot=${NDK_BUNDLE_DIR}/platforms/android-26/arch-arm64

#OpenBLAS Compile
make TARGET=ARMV8 BINARY=64 HOSTCC=gcc CC="clang ${CLANG_FLAGS}" NOFORTRAN=1 CFLAGS=${CFLAGS} >makelog.txt

```

**Comment by martin-frbg** [comment]
Are the path names in the sysroot and gcc-toolchain options of the CLANG_CFLAGS correct ?  ~~They look quite different from the wiki entry~~. And the "-marm -mfpu=vfp -mfloat-abi=softfp" are relevant for ARMV7 only. 

(Now I remember that I found something wrong with the wiki instructions myself a few days ago, let me see if I can access the system where I did my armv8 build)

**Comment by martin-frbg** [comment]
Try 
`export CLANG_CFLAGS="-target aarch64-linux-android --sysroot ${NDK_BUNDLE_DIR}/my-android-toolchain/sysroot -gcc-toolchain ${NDK_BUNDLE_DIR}/my-android-toolchain/aarch64-linux-android-4.9/prebuilt/linux-x86_64/"`

**Comment by cs123951** [comment]
I tried
`export CLANG_CFLAGS="-target aarch64-linux-android --sysroot ${NDK_BUNDLE_DIR}/my-android-toolchain/sysroot -gcc-toolchain ${NDK_BUNDLE_DIR}/my-android-toolchain/aarch64-linux-android-4.9/prebuilt/linux-x86_64/"`
or
`export CLANG_CFLAGS="-target aarch64-linux-android --sysroot ${NDK_BUNDLE_DIR}/my-android-toolchain/sysroot/usr/include -gcc-toolchain ${NDK_BUNDLE_DIR}/my-android-toolchain/aarch64-linux-android-4.9/prebuilt/linux-x86_64/"`

error happens in the same way:
`fatal error: 'stdio.h' file not found`

**Comment by martin-frbg** [comment]
Do you have stdio.h in ${NDK_BUNDLE_DIR}/my-android-toolchain/sysroot/usr/include ?

**Comment by cs123951** [comment]
yes, I have checked that stdio.h is in ${NDK_BUNDLE_DIR}/my-android-toolchain/sysroot/usr/include.

**Comment by martin-frbg** [comment]
I just redid my build, the -gcc-toolchain I gave above was incorrect, should be just 
`-gcc-toolchain ${NDK_BUNDLE_DIR}/my-android-toolchain/aarch64-linux-android-4.9/` without the "prebuilt" stuff at the end. But this should not affect the sysroot part about finding stdio.h I think, perhaps $NDK_BUNDLE_DIR does not expand to the correct path in your currrent setup ?

**Comment by cs123951** [comment]
yes. 
```
Admin@Admin-PC /cygdrive/d/GoogleDownload/OpenBLAS-0.2.20
$ find ${NDK_BUNDLE_DIR}/my-android-toolchain/sysroot/usr/include -name stdio.h
/cygdrive/d/Softwares/android-ndk-r16b/my-android-toolchain/sysroot/usr/include/bits/fortify/stdio.h
/cygdrive/d/Softwares/android-ndk-r16b/my-android-toolchain/sysroot/usr/include/stdio.h
```
Besides, I found in this directory` ${NDK_BUNDLE_DIR}/my-android-toolchain/aarch64-linux-android-4.9/ `, it has three sub-directories: bin,lib,lib64, Is it normal?

**Comment by martin-frbg** [comment]
Not sure if it is normal, but at least it is the same here. The files directly in lib appear to be related to C++, and are 64bit as well. I also have the second copy of stdio.h in bits/fortify. The only difference is that I am testing this under Linux, but I do not think this matters.

**Comment by martin-frbg** [comment]
Hmm.. Maybe it _does_ matter, as it is the HOSTCC that is trying to find stdio.h for building getarch. Perhaps you need to set up CFLAGS="-I /where/the/cygwin/usr/include/is" so that the cygwin gcc finds its include path - at least I can cause the same error on my system if I move away the stdio.h from the regular Linux /usr/include.

**Comment by cs123951** [comment]
I changed CFLAGS and it works!!!!
But 
```
clang: Unknown command line argument '-aarch64-fix-cortex-a53-835769=1'.  Try: 'clang -help'
clang: Did you mean '-max-counter-promotions=1'?
make[1]: *** [Makefile:723：saxpy.o] Error 1
make[1]: *** Waiting for unfinished jobs....
clang: Unknown command line argument '-aarch64-fix-cortex-a53-835769=1'.  Try: 'clang -help'
clang: Did you mean '-max-counter-promotions=1'?
make[1]: *** [Makefile:795：sswap.o] Error 1
make: *** [Makefile:139：libs] Error 1
```
I didn't set command line argument '-aarch64-fix-cortex-a53-835769=1'. 
Why this happened?

**Comment by martin-frbg** [comment]
Strange, I have no idea where this option comes from, it is not set in any of the files that come with OpenBLAS. If it is from the ndk, one would expect it to be supported by the clang that ships with it. Do you happen to have another copy of clang installed in windows or as part of your cygwin environment perhaps (the only reference google finds me is a confusing chat log where a microsoft fork of clang is
mentioned) ? So that if your path is not set up "in the correct order", the other clang gets found instead of what is in the toolchain

**Comment by cs123951** [comment]
yes, I found I have two clangs, one is in ndk-my-toolchain, one is in cygwin, which one should I use?
No matter which one I use, the same error happened:
```
axpy.c:39:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
swap.c:39:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
```
I think this error
```
clang: Unknown command line argument '-aarch64-fix-cortex-a53-835769=1'.  Try: 'clang -help'
clang: Did you mean '-max-counter-promotions=1'?
```
is caused by the define of `CFLAGS="-I /cygdrive/d/Softwares/Cygwin/usr/include"`

Now my commands are:
```
$ echo $CFLAGS
--sysroot=/cygdrive/d/Softwares/Cygwin/usr/include
$ echo $PATH
/cygdrive/d/Softwares/android-ndk-r16b/my-android-toolchain/bin:/usr/local/bin:/usr/bin:/cygdrive/d/Softwares/android-ndk-r16b:/cygdrive/d/Softwares/Anaconda3:/cygdrive/d/Softwares/Anaconda3/Scripts:/cygdrive/d/Softwares/Anaconda3/Library/bin:/cygdrive/c/Users/Admin/AppData/Roaming/Composer/vendor/bin:/usr/lib/lapack
$ echo $CLANG_FLAGS
-target aarch64-linux-android --sysroot /cygdrive/d/Softwares/android-ndk-r16b/my-android-toolchain/sysroot/usr/include/ -gcc-toolchain /cygdrive/d/Softwares/android-ndk-r16b/my-android-toolchain/bin

#compile 
/cygdrive/d/Softwares/Cygwin/bin/make.exe TARGET=ARMV8 BINARY=64 HOSTCC=gcc CC="clang50.exe ${CLANG_FLAGS}" NOFORTRAN=1 NO_LAPACK=1 ONLY_CBLAS=1 CFLAGS=${CFLAGS} >makelog.txt
```

**Comment by martin-frbg** [comment]
Not sure how to define the CFLAGS so that gcc finds its includes, without clang seeing it as well. Perhaps  unsetting CFLAGS completely, and using  HOSTCC="gcc -I /cygdrive/d/Softwares/Cygwin/usr/include" on the make command line would work ?

**Comment by cs123951** [comment]
It did not work.
I wrote a test.c file, and tested it in command line:
```
$ clang50.exe test.c
test.c:1:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
```
`gcc test.c` works.

**Comment by martin-frbg** [comment]
What happens when you try with HOSTCC=clang ? (Though this will probably bring back the "unknown option" problem)

**Comment by cs123951** [comment]
$ /cygdrive/d/Softwares/Cygwin/bin/make.exe TARGET=ARMV8 BINARY=64 HOSTCC="clang50.exe" CC="clang50.exe ${CLANG_FLAGS}" NOFORTRAN=1 NO_LAPACK=1 ONLY_CBLAS=1 CFLAGS=${CFLAGS} >makelog.txt
getarch.c:80:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
make: *** [Makefile.prebuild:54：getarch] 错误 1
imax.c:39:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
asum.c:39:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.

**Comment by martin-frbg** [comment]
Oh, and which one is the clang50.exe you put in the CC field ? This should be the clang from the ndk toolchain, as only the toolchain compiler knows how to cross-compile for ARM .

**Comment by cs123951** [comment]
clang50.exe is in /cygdrive/d/Softwares/android-ndk-r16b/my-android-toolchain/bin

**Comment by cs123951** [comment]
Finally, I gave up Cygwin and chose Mingw, it worked well.
