### ISSUE TITLE
Compiling for 32-bit on a 64-bit architecture

### ISSUE THREAD

**Issue by staticfloat** [xianyi/OpenBLAS#152]
I'm trying to compile a .deb of OpenBLAS for as many architectures as I can, but I'm having some trouble getting the OpenBLAS build process to make 32-bit libraries.  Is there a Make variable I need to set?  I'm already setting `DYNAMIC_ARCH=1` to force OpenBLAS to compile for all the different cpu models, but I need to generate a 32-bit version as well so it can be linked on a 32-bit operating system.

**Comment by phetdam** [comment]
For x86-64 Linux in particular, besides `BINARY=32` one should also have installed `gcc-multilib` and `gfortran-multilib`. This is something I noted when building OpenBLAS with `BINARY=32` on the Ubuntu 20.04 Github Actions runner. Maybe this is obvious for experienced user but is a helpful note for beginners who never cross-compile before.

**Comment by martin-frbg** [comment]
Depends - some distributions' gcc is multilib by default
