### ISSUE TITLE
Building on Windows 10 procedure

### ISSUE THREAD

**Issue by PetrKryslUCSD** [xianyi/OpenBLAS#1521]
I had to change the process as described in the Readme as follows:

installed Miniconda3 in ~/Miniconda3/
Started git bash:
Ran 
```
~/Miniconda3/Scripts/conda.exe update -n base conda
~/Miniconda3/Scripts/conda config --add channels conda-forge
~/Miniconda3/Scripts/conda install -y cmake flang clangdev perl
~/Miniconda3/Scripts/conda install -y -c isuruf kitware-ninja
```
Ran 
```
/c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/Community/VC/Auxiliary/Build/vcvars64.bat
```
Then
```
export LIB=~/Miniconda3/Library/lib
export CPATH=~/Miniconda3/Library/include
```
Finally
```
cmake ..
cmake --build . --config Release
```

This successfully built libraries in ~/OpenBLAS\build\lib\RELEASE.

The procedure described in the Readme file failed. In particular this command failed:
```
cmake .. -G "Ninja" -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DCMAKE_Fortran_COMPILER=flang -DBUILD_WITHOUT_LAPACK=no -DNOFORTRAN=0 -DDYNAMIC_ARCH=ON -DCMAKE_BUILD_TYPE=Release
```

Ninja was not found.

**Comment by martin-frbg** [comment]
If I understand you correctly, the execution of vcvars64.bat would appear to replace the somewhat unclear step 5. in the wiki ? 

```
Activate the MSVC environment for 64 bits with vcvarsall x64. 
Search on the web for the particular steps for your version of MSVC
```

In view of issue #1424 it is good to know that building with VS2017 can actually work.
@isuruf should the `-G "Ninja" etc. be picked up automatically now ?

**Comment by PetrKryslUCSD** [comment]
Yes. What I described worked.

**Comment by isuruf** [comment]
@PetrKryslUCSD, can you send me the output of the first cmake command?

**Comment by martin-frbg** [comment]
@isuruf, any idea what happened here w.r.t the extremely stealthy ninja ?

**Comment by isuruf** [comment]
ninja.exe might not have been on the PATH.
