### ISSUE TITLE
RISC-V Architecture support

### ISSUE THREAD

**Issue by jerryz123** [xianyi/OpenBLAS#1525]
RISCV is an open source ISA gathering a lot of support in the hardware community. There's a lot of interest in HPC on RISCV, and future extensions to the ISA look to support vectorized operations. 

Would it be possible to add RISC-V to the list of supported architectures? I have a working fork that compiles for RISC-V, and I'm willing to work on integrating the changes.

**Comment by xianyi** [comment]
@jerryz123 Great work!

We like to merge your RISC-V PR.
