### ISSUE TITLE
Can a cmake build system determine what options OpenBLAS was built with?

### ISSUE THREAD

**Issue by brianborchers** [xianyi/OpenBLAS#1529]
I'm interested in setting up cmake for my software package, which makes use of BLAS and LAPACK routines.  My code is written using OpenMP and I would prefer to link with an OpenMP version of OpenBLAS so that I can manage the number of threads explicitly.  I'd like to warn the user about potential problems if the library is built with pthreads, or warn of poor performance if the library is built single threaded.  

I'm not aware of any way to see whether or not the version of OpenBLAS that I'm linking to was compiled with OpenMP support, single threaded, etc.  Is there some way (e.g. by symbols provided or not in the library) that cmake or other build systems could determine these aspects of the OpenBLAS library? 

One very painful option would be to distribute OpenBLAS and build it along with my code- that's obviously not a desirable way to package things.

**Comment by martin-frbg** [comment]
Hmm. That came up in #1416 already, but I am not sure what the best solution would be. Neither the maximum number of threads nor the type of multithreading used are written to openblas_config.h as far as I know (and I am not entirely sure if it would help if they were). Using ldd (or equivalent) on the library should show its dependencies but I am not sure if there is a cmake function for this. If you want to check symbols, it should be a case of either blas_server() or blas_server_omp() being compiled into the library.
There is also openblas_get_num_threads() which could be called from a small test program - though it was changed in #760 to return the number of currently active threads, not the maximum the library was built to handle.

**Comment by brada4** [comment]
Not wildly documented, but you can load/open library file and try:
https://github.com/xianyi/OpenBLAS/wiki/OpenBLAS-Extensions
... helps if you mention platform ....
I would suggest for inspiration to take idea from R - they put generic BLAS/LAPACK libs in a directory and you are absolutely free to replace it with OpenBLAS, cuBLAS or MKL as you see fit.

**Comment by martin-frbg** [comment]
openblas_get_parallel() would return 2 for OpenMP, 1 for non-OpenMP, 0 for single-threaded. Maybe this should be put in the FAQ to make it more visible (although I am not sure if it is more convenient than a standard cmake check_library_exists test for blas_server_omp). And it might make sense to add the NUM_THREADS setting to the output of openblas_get_config()...

**Comment by martin-frbg** [comment]
The output from openblas_get_config() will now also contain the values of USE_OPENMP  and NUM_THREADS. PR #1559 tries to take this further by also adding the build-time settings to the pkg-config file as a private variable openblas_config, which you can query from the CMake FindPkgConfig module with the trick suggested in https://bloerg.net/2015/03/06/pkg-config-variables-in-cmake.html. This should remove the need to build and execute your own test program.
Does any of this seem useful ?

**Comment by brianborchers** [comment]
Yes it does.  Thanks.

**Comment by loriab** [comment]
I find cmake [find_package(... COMPONENTS)](https://cmake.org/cmake/help/v3.0/command/find_package.html) handy for selecting at detection-time build-time choices such as shared/static, build parameter value, alternate directory structure, etc. For example, [this](https://github.com/evaleev/libint/blob/v1/cmake/LibintConfig.cmake.in) finds the value of a build parameter so that the build system detecting this dependency can check that the requested value is met or exceeded by the detected dependency. Regrettably, that is a poor example b/c I made it unnecessarily complicated by having it search files for the value of interest, rather than just having it explicitly written to the `<pkg>Config.cmake` at build time. I'd suggest that `find_package(OpenBLAS COMPONENTS pthread)` (`serial|pthread|openmp`) could be employed. Though I don't know how advanced CMake is as an alternate build system for OpenBLAS, even for x86_64.

**Comment by martin-frbg** [comment]
So in essence cmake has its own implementation of what pkgconfig does, and OpenBLAS would need to create an OpenBLASConfig.cmake file for others to include (?). Another example is given in https://github.com/forexample/package-example

**Comment by loriab** [comment]
Yes, pkgconfig looks like a good analogy. Below is an untested sketch of what you'd need. It goes a step further and exports your main library as a CMake target. It'd be so nice if BLAS/LAPACK distributions supplied `*Config.cmake` to replace the several fractured `FindLAPACK.cmake`-like projects. :-)


OpenBLASConfig.cmake.in
```
# OpenBLASConfig.cmake
# --------------------
#
# OpenBLAS cmake module.
# This module sets the following variables in your project::
#
#   OpenBLAS_FOUND - true if OpenBLAS and all required components found on the system
#   OpenBLAS_VERSION - OpenBLAS version in format Major.Minor.Release
#   OpenBLAS_INCLUDE_DIRS - Directory where OpenBLAS header is located.
#   OpenBLAS_INCLUDE_DIR - same as DIRS
#   OpenBLAS_LIBRARIES - OpenBLAS library to link against.
#   OpenBLAS_LIBRARY - same as LIBRARIES
#
#
# Available components::
#
##   shared - search for only shared library
##   static - search for only static library
#   serial - search for unthreaded library
#   pthread - search for native pthread threaded library
#   openmp - search for OpenMP threaded library
#
#
# Exported targets::
#
# If OpenBLAS is found, this module defines the following :prop_tgt:`IMPORTED`
## target. Target is shared _or_ static, so, for both, use separate, not
## overlapping, installations. ::
#
#   OpenBLAS::OpenBLAS - the main OpenBLAS library #with header & defs attached.
#
#
# Suggested usage::
#
#   find_package(OpenBLAS)
#   find_package(OpenBLAS 0.2.20 EXACT CONFIG REQUIRED COMPONENTS pthread)
#
#
# The following variables can be set to guide the search for this package::
#
#   OpenBLAS_DIR - CMake variable, set to directory containing this Config file
#   CMAKE_PREFIX_PATH - CMake variable, set to root directory of this package
#   PATH - environment variable, set to bin directory of this package
#   CMAKE_DISABLE_FIND_PACKAGE_OpenBLAS - CMake variable, disables
#     find_package(OpenBLAS) when not REQUIRED, perhaps to force internal build

@PACKAGE_INIT@

set(PN OpenBLAS)

# need to check that the @USE_*@ evaluate to something cmake can perform boolean logic upon
if(@USE_OPENMP@)
    set(${PN}_openmp_FOUND 1)
elseif(@USE_THREAD@)
    set(${PN}_pthread_FOUND 1)
else()
    set(${PN}_serial_FOUND 1)
endif()

check_required_components(${PN})

#-----------------------------------------------------------------------------
# Don't include targets if this file is being picked up by another
# project which has already built this as a subproject
#-----------------------------------------------------------------------------
if(NOT TARGET ${PN}::OpenBLAS)
    include("${CMAKE_CURRENT_LIST_DIR}/${PN}Targets.cmake")

    get_property(_loc TARGET ${PN}::OpenBLAS PROPERTY LOCATION)
    set(${PN}_LIBRARY ${_loc})
    get_property(_ill TARGET ${PN}::OpenBLAS PROPERTY INTERFACE_LINK_LIBRARIES)
    set(${PN}_LIBRARIES ${_ill})

    get_property(_id TARGET ${PN}::OpenBLAS PROPERTY INCLUDE_DIRECTORIES)
    set(${PN}_INCLUDE_DIR ${_id})
    get_property(_iid TARGET ${PN}::OpenBLAS PROPERTY INTERFACE_INCLUDE_DIRECTORIES)
    set(${PN}_INCLUDE_DIRS ${_iid})
endif()
```

main CMakeLists.txt
```
include(GNUInstallDirs)
include(CMakePackageConfigHelpers)

set(PN OpenBLAS)


# <<< Install >>>

install(TARGETS ${OpenBLAS_LIBNAME}
        EXPORT "${PN}Targets"
        ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
        LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR})

# <<< Export Config >>>

# GNUInstallDirs "DATADIR" wrong here; CMake search path wants "share".
set(CMAKECONFIG_INSTALL_DIR "share/cmake/${PN}")
configure_package_config_file(cmake/${PN}Config.cmake.in
                              "${CMAKE_CURRENT_BINARY_DIR}/${PN}Config.cmake"
                              INSTALL_DESTINATION ${CMAKECONFIG_INSTALL_DIR})
write_basic_package_version_file(${CMAKE_CURRENT_BINARY_DIR}/${PN}ConfigVersion.cmake
                                 VERSION ${${PN}_VERSION}
                                 COMPATIBILITY AnyNewerVersion)
install(FILES ${CMAKE_CURRENT_BINARY_DIR}/${PN}Config.cmake
              ${CMAKE_CURRENT_BINARY_DIR}/${PN}ConfigVersion.cmake
        DESTINATION ${CMAKECONFIG_INSTALL_DIR})
install(EXPORT "${PN}Targets"
        NAMESPACE "${PN}::"
        DESTINATION ${CMAKECONFIG_INSTALL_DIR})
```

**Comment by martin-frbg** [comment]
@loriab thank you very much for that. While I am not sure I know how to do any serious tests with it, at least it builds fine and looks reasonable.

**Comment by loriab** [comment]
@martin-frbg, you're welcome. If you ever want to pursue using it (or, what's usually harder in CMake, follow the choices), please ping me with any questions.

**Comment by martin-frbg** [comment]
For now I am just trying to assess the risk of merging it into the current develop branch (and possibly a 0.3.1 release). My current understanding is that even in the worst case it can only hurt somebody who is actively looking for it with find_package(OpenBLAS), so there should be no regressions. is that correct ?

**Comment by loriab** [comment]
Yes, this affects `find_package(OpenBLAS CONFIG)` or (see docs quote below) `find_package(OpenBLAS)` in some approximation of `FindOpenBLAS.cmake` not found or `FindOpenBLAS.cmake` found but it fails to detect a suitable OpenBLAS installation.

From https://cmake.org/cmake/help/v3.8/command/find_package.html,
> If no module is found and the MODULE option is not given the command proceeds to Config mode

A few other notes:
* many Target features start arouand CMake 3.0, so if your lowest supported fails, may need a conditional https://github.com/pybind/pybind11/blob/master/CMakeLists.txt#L94
* the GNUInstallDirs (https://cmake.org/cmake/help/v3.4/module/GNUInstallDirs.html) have good pedigree and the OpenBLASConfig/Target will take care of communicating it to users but `CMAKE_INSTALL_LIBDIR=lib64` can surprise people (and that affects a cmake install, not just detection of a cmake install). I confess to re-defaulting that sometimes (https://github.com/psi4/psi4/blob/master/CMakeLists.txt#L138) but probably involves extra code (https://github.com/psi4/psi4/blob/master/cmake/psi4OptionsTools.cmake#L35-L40).

**Comment by martin-frbg** [comment]
Hmm. NetoDevel's comment in #1516 just reminded me that we are already creating a (very minimal) OpenBLASConfig.cmake in the `make`-based builds, it is just the cmake build of all thing that omitted to do this so far.
