### ISSUE TITLE
(Apparently) new errors with OpenBLAS devel, win32, matrix inverse.

### ISSUE THREAD

**Issue by matthew-brett** [xianyi/OpenBLAS#1533]
I am sorry to email without a replication in C for you, but over at Numpy we have found that the latest development branch is giving us errors for a matrix inverse on 32-bit Windows:

https://github.com/scipy/scipy/issues/8759#issuecomment-383147766

The basic issue is that a new 32-bit OpenBLAS library, built from the latest devel branch, with mingw-w64 (mingw-builds), gives a newly incorrect result for a matrix inverse.

I can describe how to replicate this in Python if its helpful (the details are on the thread above), but the basic result is the following:

```Python
import numpy as np  # This uses a previous OpenBLAS library
import scipy.linalg  # This uses the latest OpenBLAS devel

n = 100
alpha = 1 - 1e-6
A = -scipy.linalg.inv(np.identity(n) + alpha*np.eye(n, k=1))
A_np = -np.linalg.inv(np.identity(n) + alpha*np.eye(n, k=1))
print(np.abs(A - A_np).max())
```

This should give some very small number or 0, but it actually prints a value of 0.999999.  We have confirmed that the `A_np` result is correct on a couple of platforms.  So it looks like the current OpenBLAS is giving incorrect results, on Windows 32 bit only (not 64 bit).

Does this ring any bells?  What should we do next to debug?

**Comment by martin-frbg** [comment]
What is the underlying hardware (or TARGET used for OpenBLAS compilation) ? Haswell (and later Intel generations) will use Nehalem kernels or worse in 32bit builds (and I seem to remember fixing(?) a bug in that code "recently" but will have to look up what it was - pretty sure it was something that led to regular tests failing but my usual platform is Linux) .
 As you mention "newly incorrect", can you give an approximate time frame for when "it" (ideally the develop branch) was last known to return the expected result ?

**Comment by martin-frbg** [comment]
Actually the bugfix I remembered was just the DSDOT fix for your #1492 (Mac 32bit), which should be harmless. (But looking at that issue again I notice that there was an unexplained and not locally reproducible test failure on travis, with IEEE floating point exception signals for division by zero, apparently in at least one of the blas3 tests. I cannot figure out from the travis log what TARGET was in use there, except that it was 32bit. Does your scipy code call into any blas3 function ?)

**Comment by martin-frbg** [comment]
Hmm. Another fix (from october 2017) affected TRMM on 32bit Haswell (in response to a compilation failure, issue #1331 and PR #1333, so any earlier version should not even have built on that platform)

**Comment by matthew-brett** [comment]
The commit that worked (and gives no test errors) was 5f998ef . It's a dynamic arch build, but going through the core types by setting OPENBLAS_CORETYPE I get:

Wrong (0.9999) on Nehalem (default), Prescott
Correct (0) on Dunnington, Penryn, Core2
Sandybridge and Haswell reset to the default of Nehalem.

I'm afraid I don't know what functions scipy.linalg.inv calls into - @pv - do you know?

**Comment by brada4** [comment]
Does reordering import and/or inv statements yield zero at least in one combo?

**Comment by matthew-brett** [comment]
Confirmation that Scipy built against the old 5f998ef 32-bit libraries does pass the tests on the same systems: https://ci.appveyor.com/project/matthew-brett/scipy-wheels/build/job/x10hhlok3ex6nxaa

**Comment by martin-frbg** [comment]
Hmm. 5f998ef is very shortly after 0.2.20, so it is one of only 390 commits that happened since then. I am not aware of anything directly affecting Nehalem besides the two I mentioned. Can you try reverting the simple change from #1333 in your tree ? If that does not help, someone needs to do a `git bisect` to track it down.

**Comment by martin-frbg** [comment]
32bit Haswell builds fail the DTRMM test both with and without the change from #1333. Not sure yet if that is a recent regression (or even related to this issue). I did see similar TRMM failures on MIPS32 recently as well, so there may be something wrong with at least some of the generic trmmkernel implementations.
Update: 32bit Haswell is actually using gemm_kernel_2x4_penryn.S for DTRMM (as 32bit Nehalem uses the Penryn kernels except for sswap/dswap).

**Comment by matthew-brett** [comment]
No, no reordering of the imports / invs generates a zero.

**Comment by brada4** [comment]
@matthew-brett in principle both implementations should act identically. Especially if scipy.linalg is present& loaded numpy.lonalg will use that instead of own implementation.
What I suspect is that either uninitialized memory is added to result, or something gets overwritten outside intended arrays.

Please try following:
* calling numpy routine twice, comparing results
* caling scipy same way
* original script with OPENBLAS_NUM_THREADS=1 set in environment
* (if it really writes outside scope) setting input dimension to 64 (or any multiple thereof) is more likely to set some memory protection barrier right after in/out arrays and trigger the crash.

**Comment by matthew-brett** [comment]
Calling the numpy / scipy routines more than once always gives the same results (0.999 max error for scipy, 0 max error for numpy).

OPENBLAS_NUM_THREADS=1 removes the error, making the difference 0, as it should be.

Neither 64 nor 128 for matrix dimension generate the error, but 100 does...

**Comment by matthew-brett** [comment]
All numpy tests pass with a commit to OpenBLAS reverting #1333 : https://ci.appveyor.com/project/matthew-brett/scipy-wheels/build/job/76h70mvd4lnc3f9w

**Comment by martin-frbg** [comment]
Reverted now, sorry.

**Comment by matthew-brett** [comment]
No problem - thanks for the help diagnosing.

**Comment by matthew-brett** [comment]
Sorry to ask - but will reverting the #1333 cause any problems for 32-bit Haswell builds?

**Comment by martin-frbg** [comment]
I have not found any new ones, that's why I was so quick to revert this. (Actually I have not even been able to reproduce the original problem from #1331 yet)
You will however see DTRMM failures in the output of the cblat3 test (both with and without that change).
