### ISSUE TITLE
Android Studio error

### ISSUE THREAD

**Issue by cs123951** [xianyi/OpenBLAS#1537]
I use` make TARGET=ARMV7 AR=ar CC="clang ${CLANG_FLAGS}" HOSTCC=gcc ONLY_CBLAS=1 FC=gfortran libs `
to generate  libopenblas.a file .
Then I use CMakeLists.txt to import  libopenblas.a in Android Studio, but error happened.
```
Build native-lib armeabi-v7a
[1/1] Linking CXX shared
 library ..\..\..\..\build\intermediates\cmake\debug\obj\armeabi-v7a\l
ibnative-lib.so
FAILED: cmd.exe /C "cd . && D:\Softwares\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=armv7-none-linux-androideabi --gcc-toolchain=D:/Softwares/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 --sysroot=D:/Softwares/Android/sdk/ndk-bundle/sysroot -fPIC -isystem D:/Softwares/Android/sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=14 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat -Werror=format-security  -std=c++11 -frtti -fexceptions -std=gnu++11 -fexceptions -frtti -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a --sysroot D:/Softwares/Android/sdk/ndk-bundle/platforms/android-14/arch-arm -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--fix-cortex-a8 -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libnative-lib.so -o ..\..\..\..\build\intermediates\cmake\debug\obj\armeabi-v7a\libnative-lib.so CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o CMakeFiles/native-lib.dir/src/main/cpp/mtcnn/mtcnn.cpp.o CMakeFiles/native-lib.dir/src/main/cpp/mtcnn/network.cpp.o CMakeFiles/native-lib.dir/src/main/cpp/mtcnn/pBox.cpp.o  -landroid -llog ../../../../src/main/jniLibs/armeabi-v7a/libopencv_java3.so ../../../../src/main/jniLibs/armeabi-v7a/libopencv_calib3d.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_core.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_features2d.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_flann.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_highgui.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_imgcodecs.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_imgproc.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_ml.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_objdetect.a ../../../../src/main/jniL
ibs/armeabi-v7a/libopencv_photo.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_shape.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_stitching.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_superres.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_video.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_videoio.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_videostab.a ../../../../src/main/jniLibs/armeabi-v7a/libopenblas_armv7p-r0.2.20.a -llog -latomic -lm "D:/Softwares/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libgnustl_static.a" && cd ."
../../../../src/main/jniLibs/armeabi-v7a/libopenblas_armv7p-r0.2.20.a(blas_server.o):blas_server.c:function blas_thread_init: error: undefined reference to 'stderr'
../../../../src/main/jniLibs/armeabi-v7a/libopenblas_armv7p-r0.2.20.a(blas_server.o):blas_server.c:function blas_thread_init: error: undefined reference to 'stderr'
../../../../src/main/jniLibs/armeabi-v7a/libopenblas_armv7p-r0.2.20.a(blas_server.o):blas_server.c:function blas_thread_init: error: undefined reference to 'stderr'
../../../../src/main/jniLibs/armeabi-v7a/libopenblas_armv7p-r0.2.20.a(blas_server.o):blas_server.c:function exec_blas: error: undefined reference to 'stderr'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
:app:externalNativeBuildDebug FAILED
```

**Comment by martin-frbg** [comment]
stderr should be in libc, can you get around this by adding "-lc" with the "-lm" you already have ?
(If you are statically linking against libc.a, this is probably https://github.com/android-ndk/ndk/issues/272 which is expected to be fixed with r17 of the NDK)

**Comment by cs123951** [comment]
I just linked libopenblas.a in Android Studio, I don't know  the function of libc.a
I used ` ar -x libc.a` to unzip, and found stderr.o is not in libc.a. 
stderr is not in libopenblas.a, too.
By the way, I use r16 of NDK.

**Comment by martin-frbg** [comment]
Sounds like the ndk bug I linked to then. There is only one place in blas_server.c where stderr gets used (when no debugging options are set). This is to print the warning when OpenBLAS is used from an OpenMP program without being built for OpenMP. If you remove this
```

#ifdef __ELF__
  if (omp_in_parallel && (num > 1)) {
    if (omp_in_parallel() > 0) {
      fprintf(stderr,
              "OpenBLAS Warning : Detect OpenMP Loop and this application may hang. "
              "Please rebuild the library with USE_OPENMP=1 option.\n");
    } 
  }   
#endif
```
from around line 800 of driver/others/blas_server.c and rebuild OpenBLAS, perhaps the problem will
go away.

**Comment by cs123951** [comment]
I removed this, and error still happened.
I noticed that STDERR in blas_server.c appears not only once.
For example:
```
#ifdef SMP_DEBUG
      if (queue -> args) {
	fprintf(STDERR, "Server[%2ld] Calculation started.  Mode = 0x%03x M = %3ld N=%3ld K=%3ld\n",
		cpu, queue->mode, queue-> args ->m, queue->args->n, queue->args->k);
      }
#endif
```
in line 370

**Comment by martin-frbg** [comment]
Is it the same error, still mentioning blas_server.o as the source ? The STDERR is defined as "stderr" in common.h for all platforms (except ppc, where common_power.h redirects it to stdout), and it only occurs within `#ifdef SMP_DEBUG` and similar blocks which are not compiled as SMP_DEBUG is normally not defined.

**Comment by cs123951** [comment]
Yes, the same error.
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process D:\Softwares\Android\sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build E:\Projects\Android\app\.externalNativeBuild\cmake\debug\armeabi-v7a --target native-lib}
  [1/5] Building CXX object CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o
  [2/5] Building CXX object CMakeFiles/native-lib.dir/src/main/cpp/mtcnn/mtcnn.cpp.o
  [3/5] Building CXX object CMakeFiles/native-lib.dir/src/main/cpp/mtcnn/network.cpp.o
  [4/5] Building CXX object CMakeFiles/native-lib.dir/src/main/cpp/mtcnn/pBox.cpp.o
  [5/5] Linking CXX shared library ..\..\..\..\build\intermediates\cmake\debug\obj\armeabi-v7a\libnative-lib.so
  FAILED: cmd.exe /C "cd . && D:\Softwares\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=armv7-none-linux-androideabi --gcc-toolchain=D:/Softwares/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 --sysroot=D:/Softwares/Android/sdk/ndk-bundle/sysroot -fPIC -isystem D:/Softwares/Android/sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=14 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat -Werror=format-security  -std=c++11 -frtti -fexceptions -std=gnu++11 -fexceptions -frtti -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a --sysroot D:/Softwares/Android/sdk/ndk-bundle/platforms/android-14/arch-arm -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--fix-cortex-a8 -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libnative-lib.so -o ..\..\..\..\build\intermediates\cmake\debug\obj\armeabi-v7a\libnative-lib.so CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o CMakeFiles/native-lib.dir/src/main/cpp/mtcnn/mtcnn.cpp.o CMakeFiles/native-lib.dir/src/main/cpp/mtcnn/network.cpp.o CMakeFiles/native-lib.dir/src/main/cpp/mtcnn/pBox.cpp.o  -landroid -llog ../../../../src/main/jniLibs/armeabi-v7a/libopencv_java3.so ../../../../src/main/jniLibs/armeabi-v7a/libopencv_calib3d.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_core.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_features2d.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_flann.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_highgui.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_imgcodecs.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_imgproc.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_ml.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_objdetect.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_photo.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_shape.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_stitching.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_superres.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_video.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_videoio.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_videostab.a ../../../../src/main/jniLibs/armeabi-v7a/libopenblas_armv7p_delete.a -llog -latomic -lm "D:/Softwares/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libgnustl_static.a" && cd ."
  ../../../../src/main/jniLibs/armeabi-v7a/libopenblas_armv7p_delete.a(blas_server.o):blas_server.c:function blas_thread_init: error: undefined reference to 'stderr'
  ../../../../src/main/jniLibs/armeabi-v7a/libopenblas_armv7p_delete.a(blas_server.o):blas_server.c:function blas_thread_init: error: undefined reference to 'stderr'
  ../../../../src/main/jniLibs/armeabi-v7a/libopenblas_armv7p_delete.a(blas_server.o):blas_server.c:function blas_thread_init: error: undefined reference to 'stderr'
  clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.
```

**Comment by martin-frbg** [comment]
Ah, somehow I managed to overlook that the two printouts to STDERR in blas_server_init (near line 585) are not within an #ifdef region. You could try commenting out everything from the `if (ret!=0)` up
to (and including) the second of the three closing braces above the `#ifdef MONITOR`.
However what you could also try (from a comment in the ndk issue I linked to above) is add `-D__ANDROID_API__=14 LDFLAGS=-D__ANDROID_API__=14 CXXFLAGS=D__ANDROID_API__=14` to your CLANG_CFLAGS.

**Comment by cs123951** [comment]
I changed android api and build success!
Thank you very much!

**Comment by martin-frbg** [comment]
I have added a note about this to the wiki page now.

**Comment by 467392906** [comment]
Build command failed.
Error while executing process D:\androidInvrionment\sdk\cmake\3.10.2.4988404\bin\cmake.exe with arguments {--build E:\githubLoading\githubFace\mobilefacenet_android-master\mobilefacenet_android-master\app\.externalNativeBuild\cmake\debug\armeabi-v7a --target Face}
[1/4] Building CXX object CMakeFiles/Face.dir/src/main/cpp/recognize.cpp.o
[2/4] Building CXX object CMakeFiles/Face.dir/src/main/cpp/face_jni.cpp.o
[3/4] Building CXX object CMakeFiles/Face.dir/src/main/cpp/detect.cpp.o
[4/4] Linking CXX shared library ..\..\..\..\build\intermediates\cmake\debug\obj\armeabi-v7a\libFace.so
FAILED: ../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libFace.so 
cmd.exe /C "cd . && D:\ndk\android-ndk-r15c-windows-x86_64\android-ndk-r15c\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=armv7-none-linux-androideabi --gcc-toolchain=D:/ndk/android-ndk-r15c-windows-x86_64/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 --sysroot=D:/ndk/android-ndk-r15c-windows-x86_64/android-ndk-r15c/sysroot -fPIC -isystem D:/ndk/android-ndk-r15c-windows-x86_64/android-ndk-r15c/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=15 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -fopenmp -O2 -fvisibility=hidden -fvisibility-inlines-hidden -fomit-frame-pointer -fstrict-aliasing -ffunction-sections -fdata-sections    -std=c++11 -frtti -fexceptions -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a --sysroot D:/ndk/android-ndk-r15c-windows-x86_64/android-ndk-r15c/platforms/android-15/arch-arm -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--fix-cortex-a8 -Wl,--exclude-libs,libunwind.a -LD:/ndk/android-ndk-r15c-windows-x86_64/android-ndk-r15c/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libFace.so -o ..\..\..\..\build\intermediates\cmake\debug\obj\armeabi-v7a\libFace.so CMakeFiles/Face.dir/src/main/cpp/detect.cpp.o CMakeFiles/Face.dir/src/main/cpp/face_jni.cpp.o CMakeFiles/Face.dir/src/main/cpp/recognize.cpp.o  ../../../../src/main/jniLibs/armeabi-v7a/libncnn.a -ljnigraphics -llog -lm "D:/ndk/android-ndk-r15c-windows-x86_64/android-ndk-r15c/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/libc++.so" && cd ."
../../../../src/main/jniLibs/armeabi-v7a/libncnn.a(net.cpp.o):D:/ncnn/src/net.cpp:function ncnn::Net::~Net(): error: undefined reference to 'std::string::_Rep::_M_destroy(std::allocator<char> const&)'
../../../../src/main/jniLibs/armeabi-v7a/libncnn.a(net.cpp.o):D:/ncnn/src/net.cpp:function ncnn::Net::~Net(): error: undefined reference to 'std::string::_Rep::_M_destroy(std::allocator<char> const&)'
../../../../src/main/jniLibs/armeabi-v7a/libncnn.a(net.cpp.o):D:/ncnn/src/net.cpp:function ncnn::Net::~Net(): error: undefined reference to 'std::string::_Rep::_S_empty_rep_storage'
../../../../src/main/jniLibs/armeabi-v7a/libncnn.a(net.cpp.o):D:/ncnn/src/net.cpp:function ncnn::Net::~Net(): error: undefined reference to 'std::string::_Rep::_S_empty_rep_storage'
../../../../src/main/jniLibs/armeabi-v7a/libncnn.a(net.cpp.o):D:/ncnn/src/net.cpp:function ncnn::Net::clear(): error: undefined reference to 'std::string::_Rep::_M_destroy(std::allocator<char> const&)'
../../../../src/main/jniLibs/armeabi-v7a/libncnn.a(net.cpp.o):D:/ncnn/src/net.cpp:function ncnn::Net::clear(): error: undefined reference to 'std::string::_Rep::_S_empty_rep_storage'
../../../../src/main/jniLibs/armeabi-v7a/libncnn.a(net.cpp.o):D:/ncnn/src/net.cpp:function ncnn::Net::load_param(__sFILE*): error: undefined reference to 'std::string::_Rep::_M_destroy(std::allocator<char> const&)'
../../../../src/main/jniLibs/armeabi-v7a/libncnn.a(net.cpp.o):D:/ncnn/src/net.cpp:function ncnn::Net::load_param(__sFILE*): error: undefined reference to 'std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
../../../../src/main/jniLibs/armeabi-v7a/libncnn.a(net.cpp.o):D:/ncnn/src/net.cpp:function ncnn::Net::load_param(__sFILE*): error: undefined reference to 'std::string::assign(std::string const&)'
../../../../src/main/jniLibs/armeabi-v7a/libncnn.a(net.cpp.o):D:/ncnn/src/net.cpp:function ncnn::Net::load_param(__sFILE*): error: undefined reference to 'std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
../../../../src/main/jniLibs/armeabi-v7a/libncnn.a(net.cpp.o):D:/ncnn/src/net.cpp:function ncnn::Net::load_param(__sFILE*): error: undefined reference to 'std::string::assign(std::string const&)'
../../../../src/main/jniLibs/armeabi-v7a/libncnn.a(net.cpp.o):D:/ncnn/src/net.cpp:function ncnn::Net::load_param(__sFILE*): error: undefined reference to 'std::string::compare(char const*) const'
../../../../src/main/jniLibs/armeabi-v7a/libncnn.a(net.cpp.o):D:/ncnn/src/net.cpp:function ncnn::Net::load_param(__sFILE*): error: undefined reference to 'std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
../../../../src/main/jniLibs/armeabi-v7a/libncnn.a(net.cpp.o):D:/ncnn/src/net.cpp:function ncnn::Net::load_param(__sFILE*): error: undefined reference to 'std::string::assign(std::string const&)'
../../../../src/main/jniLibs/armeabi-v7a/libncnn.a(net.cpp.o):D:/ncnn/src/net.cpp:function ncnn::Net::load_param(__sFILE*): error: undefined reference to 'std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
../../../../src/main/jniLibs/armeabi-v7a/libncnn.a(net.cpp.o):D:/ncnn/src/net.cpp:function ncnn::Net::load_param(__sFILE*): error: undefined reference to 'std::string::assign(std::string const&)'
../../../../src/main/jniLibs/armeabi-v7a/libncnn.a(net.cpp.o):D:/ncnn/src/net.cpp:function ncnn::Net::load_param(__sFILE*): error: undefined reference to 'std::string::_Rep::_S_empty_rep_storage'
../../../../src/main/jniLibs/armeabi-v7a/libncnn.a(net.cpp.o):D:/ncnn/src/net.cpp:function ncnn::Net::find_blob_index_by_name(char const*) const: error: undefined reference to 'std::string::compare(char const*) const'
../../../../src/main/jniLibs/armeabi-v7a/libncnn.a(net.cpp.o):D:/ncnn/src/net.cpp:function ncnn::Net::find_layer_index_by_name(char const*) const: error: undefined reference to 'std::string::compare(char const*) const'
../../../../src/main/jniLibs/armeabi-v7a/libncnn.a(net.cpp.o):D:/ncnn/src/net.cpp:function ncnn::Extractor::input(char const*, ncnn::Mat const&): error: undefined reference to 'std::string::compare(char const*) const'
../../../../src/main/jniLibs/armeabi-v7a/libncnn.a(net.cpp.o):D:/ncnn/src/net.cpp:function std::vector<ncnn::layer_registry_entry, std::allocator<ncnn::layer_registry_entry> >::_M_fill_insert(__gnu_cxx::__normal_iterator<ncnn::layer_registry_entry*, std::vector<ncnn::layer_registry_entry, std::allocator<ncnn::layer_registry_entry> > >, unsigned int, ncnn::layer_registry_entry const&): error: undefined reference to 'std::__throw_length_error(char const*)'
../../../../src/main/jniLibs/armeabi-v7a/libncnn.a(net.cpp.o):D:/ncnn/src/net.cpp:function std::vector<ncnn::Layer*, std::allocator<ncnn::Layer*> >::_M_fill_insert(__gnu_cxx::__normal_iterator<ncnn::Layer**, std::vector<ncnn::Layer*, std::allocator<ncnn::Layer*> > >, unsigned int, ncnn::Layer* const&): error: undefined reference to 'std::__throw_length_error(char const*)'
../../../../src/main/jniLibs/armeabi-v7a/libncnn.a(net.cpp.o):D:/ncnn/src/net.cpp:function std::vector<ncnn::Blob, std::allocator<ncnn::Blob> >::_M_fill_insert(__gnu_cxx::__normal_iterator<ncnn::Blob*, std::vector<ncnn::Blob, std::allocator<ncnn::Blob> > >, unsigned int, ncnn::Blob const&): error: undefined reference to 'std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&)'
../../../../src/main/jniLibs/armeabi-v7a/libncnn.a(net.cpp.o):D:/ncnn/src/net.cpp:function std::vector<ncnn::Blob, std::allocator<ncnn::Blob> >::_M_fill_insert(__gnu_cxx::__normal_iterator<ncnn::Blob*, std::vector<ncnn::Blob, std::allocator<ncnn::Blob> > >, unsigned int, ncnn::Blob const&): error: undefined reference to 'std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&)'
../../../../src/main/jniLibs/armeabi-v7a/libncnn.a(net.cpp.o):D:/ncnn/src/net.cpp:function std::vector<ncnn::Blob, std::allocator<ncnn::Blob> >::_M_fill_insert(__gnu_cxx::__normal_iterator<ncnn::Blob*, std::vector<ncnn::Blob, std::allocator<ncnn::Blob> > >, unsigned int, ncnn::Blob const&): error: undefined reference to 'std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&)'
../../../../src/main/jniLibs/armeabi-v7a/libncnn.a(net.cpp.o):D:/ncnn/src/net.cpp:function std::vector<ncnn::Blob, std::allocator<ncnn::Blob> >::_M_fill_insert(__gnu_cxx::__normal_iterator<ncnn::Blob*, std::vector<ncnn::Blob, std::allocator<ncnn::Blob> > >, unsigned int, ncnn::Blob const&): error: undefined reference to 'std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&)'
../../../../src/main/jniLibs/armeabi-v7a/libncnn.a(net.cpp.o):D:/ncnn/src/net.cpp:function std::vector<ncnn::Blob, std::allocator<ncnn::Blob> >::_M_fill_insert(__gnu_cxx::__normal_iterator<ncnn::Blob*, std::vector<ncnn::Blob, std::allocator<ncnn::Blob> > >, unsigned int, ncnn::Blob const&): error: undefined reference to 'std::__throw_length_error(char const*)'
../../../../src/main/jniLibs/armeabi-v7a/libncnn.a(net.cpp.o):D:/ncnn/src/net.cpp:function std::vector<int, std::allocator<int> >::_M_fill_insert(__gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >, unsigned int, int const&): error: undefined reference to 'std::__throw_length_error(char const*)'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

**Comment by 467392906** [comment]
help help,what's wrong
