### ISSUE TITLE
Intel Compiler 2018 no longer supports -openmp

### ISSUE THREAD

**Issue by albandil** [xianyi/OpenBLAS#1546]
The compiler switch `-openmp` has been considered deprecated for a long time by the intel compiler. The supported alternatives are `-qopenmp` and `-fopenmp`. See: https://software.intel.com/en-us/node/682582

Starting with Intel Compiler 2018, `-openmp` is no longer supported. See https://software.intel.com/en-us/articles/intel-c-compiler-180-for-linux-release-notes-for-intel-parallel-studio-xe-2018#new_features (at the bottom of the part, in section "All –o* options replaced by –qo* options").

OpenBLAS should adjust `Makefile.system` accordingly, possibly in favour of `-qopenmp` that is documented in the first link.

**Comment by martin-frbg** [comment]
Seems the -q option was introduced with the 2015 release, so -f might be the safer choice in case anybody is forced to use an older compiler version for whatever reason ?

**Comment by albandil** [comment]
The same fix needs to be done on line 721 of `Makefile.system` for the Intel Fortran compiler.

**Comment by moravveji** [comment]
Reopening this thread.
I'm compiling a software, and I would like to compare the performance using different Intel toolchains on our clusters. Specifically, I can use the 2016a, 2018a, 2018b and 2019b toolchains.
How can I set the OpenMP flag so that it is backward-compatible; I do not want to keep changing my compiler flag depending on compiler version (bogus approach). What do you guys propose?

**Comment by martin-frbg** [comment]
I had chosen `-fopenmp` on the assumption that it would work with all somewhat recent toolchains - is this not the case for one of those on your list ?

**Comment by moravveji** [comment]
@martin-frbg : did you eventually manage to test/compile with `-fopenmp` on different intel versions? 
If so, can you please explicit the oldest and newest version numbers?

**Comment by martin-frbg** [comment]
Back then I probably just relied on the information given, and nobody complained in the three years since. I have only sporadically used trial versions of the intel compiler in the past. Are you telling me that `-fopenmp` does not work at all with the Intel compilers, and should be changed to `-qopenmp` ?

**Comment by moravveji** [comment]
I have to admit that in many occasions, I had to manually change OpenMP flags to `-qopenmp` to comply with the recent Interl versions. 
However, the questions is: from which version onwards is `-qopenmp` the correct compiler flag? 
Is it backward compatible with 2016a toolchains, as well? 
I struggle with such details.

**Comment by albandil** [comment]
As stated above, the newer flag `-qopenmp` was introduced in the 2015 version. Earlier versions don't know about this flag.

The old flag `-openmp` was marked as deprecated in the 2016 version and removed altogether in one of the later version, I am not sure in which.

The GCC-compatible flag `-fopenmp` has been available for a long time, I just checked that already the 2012 suite understands it. And it works still, I just compiled OpenBLAS 0.3.14 with the most recent version*, Intel oneAPI 2021 (which is available for free btw):
```
 OpenBLAS build complete. (BLAS CBLAS LAPACK LAPACKE)

  OS               ... Linux             
  Architecture     ... x86_64               
  BINARY           ... 64bit                 
  Use 64 bits int    (equivalent to "-i8" in Fortran)      
  C compiler       ... INTEL  (cmd & version : icc (ICC) 2021.1.2 20201208)
  Fortran compiler ... INTEL  (cmd & version : ifort (IFORT) 2021.1.2 20201208)
  Library Name     ... libopenblas_ilp64_skylakexp-r0.3.14.a (Multi-threading; Max num-threads is 10)
```

*) Minus a tiny unrelated bug: The subroutine `LLSAME` is referenced in one of the Fortran source files, but never used and never defined. This makes the build process fail at the very end during the shared library link test.

**Comment by moravveji** [comment]
Thanks @albandil for your thorough reply. 
Then, I will opt for staying with `-fopenmp` from now on, since my toolchains of interest are released around the same years where `-openmp` was deprecated.
