### ISSUE TITLE
lapack-netlib/SRC/*.F files not pre-processed

### ISSUE THREAD

**Issue by albandil** [xianyi/OpenBLAS#1547]
When I try to "make" OpenBLAS 0.3.0, I run into problems with `*.F` files in lapack-netlib. It seems as if the make rules were not properly set up for that extension. Here is an excerpt from the compilation log:
```
gfortran -O2 -Wall -m64 -fPIC -c -o ssytrd_sy2sb.o ssytrd_sy2sb.f
gfortran    -F -o ssytrd_sb2st.f ssytrd_sb2st.F
ssytrd_sb2st.f:233:2:

 #if defined(_OPENMP)
  1
Warning: Illegal preprocessor directive

(...)

f951: Warning: command line option ‘-F-o’ is valid for C/C++/ObjC/ObjC++ but not for Fortran
```
In the end the build fails due to undefined references or multiple definitions to routines defined in those `*.F` files.

I was able to build OpenBLAS successfully only after renaming `*.F` to `*.f`, and changing the compiler invocation in `Makefile.rule` from
```
FC = gfortran
```
to
```
FC = gfortran -cpp
```
so that it preprocesses all files using the C preprocessor. My compiler is gfortran 7.3.1, but the same happens with the current experimental gfortran 9.0.0. And I got stuck on the very same point with ifort 2018.

**Comment by martin-frbg** [comment]
Where does the `gfortran -F` come from in your log excerpt ?

**Comment by albandil** [comment]
That's what I ask myself. I suppose that my `make` (GNU Make 4.2.1), when asked to produce a specific `.o`, uses some default `.F -> .f` rule, followed by `.f -> .o`. All this instead of using `.F -> .o` that is provided in the `Makefile`. But that's a speculation; I am not very strong with `make`.

**Comment by martin-frbg** [comment]
Anything in your environment, CFLAGS etc that could cause this ? And/or do you see this -F flag in the make.inc that gets created in lapack-netlib by the toplevel Makefile ?

**Comment by albandil** [comment]
All right, half of the problem (the strange `make` rule) solved itself when I cleaned my working copy of the repository, which got messy due to switching of different compilers. Still, I am not able to make `ifort` correctly pre-process the `*.F` files.

When I use `FC = ifort`, the compilation fails with:

```
ifort -O2 -fPIC -c dsytrd_sb2st.F -o dsytrd_sb2st.o
dsytrd_sb2st.F(484): #error: #if: syntax error.
```

When I use `FC = ifort -fpp`, it ends the same:

```
ifort -fpp -O2 -fPIC -c dsytrd_sb2st.F -o dsytrd_sb2st.o
dsytrd_sb2st.F(484): #error: #if: syntax error.
```

I have ifort 18.0.1 and all I did with respect to the release-0.3.0 branch is the following:
```diff
diff --git a/Makefile.rule b/Makefile.rule
index 62bf63df..8a2481fe 100644
--- a/Makefile.rule
+++ b/Makefile.rule
@@ -19,10 +19,10 @@ VERSION = 0.3.0.dev
 
 # C compiler including binary type(32bit / 64bit). Default is gcc.
 # Don't use Intel Compiler or PGI, it won't generate right codes as I expect.
-# CC = gcc
+CC = icc
 
 # Fortran compiler. Default is g77.
-# FC = gfortran
+FC = ifort
 
 # Even you can specify cross compiler. Meanwhile, please set HOSTCC.
 
diff --git a/Makefile.system b/Makefile.system
index 9720b317..dcd82be3 100644
--- a/Makefile.system
+++ b/Makefile.system
@@ -424,7 +424,7 @@ CCOMMON_OPT    += -fopenmp
 endif
 
 ifeq ($(C_COMPILER), INTEL)
-CCOMMON_OPT    += -openmp
+CCOMMON_OPT    += -fopenmp
 endif
 
 ifeq ($(C_COMPILER), PGI)
@@ -704,7 +704,7 @@ FCOMMON_OPT += -i8
 endif
 endif
 ifeq ($(USE_OPENMP), 1)
-FCOMMON_OPT += -openmp
+FCOMMON_OPT += -fopenmp
 endif
 endif
```

**Comment by martin-frbg** [comment]
Searching for "ifort" and "#if: syntax error" returns a hit on a stackoverflow posting where someone apparently had the same problem a month ago (without telling here...) and managed to solve (or work around) it by changing the `#if defined` on that source line to an `#ifdef`.
To me this seems to be a bug in ifort 18.0.1 ... 
Note that the same `#if defined (_OPENMP) && _OPENMP >= 201307L` also occurs in two other source files there, it is unclear if they also triggered the error

**Comment by albandil** [comment]
Thank you very much for support, I should be able to do this research on my own next time. It turns out that if I drop the trailing `L`, leaving just
```fortran
#if defined (_OPENMP) && _OPENMP >= 201307
```
then these lines compile well. I tried updating to ifort 18.0.2 without any effect, so I will discuss this issue with Intel people.

**Comment by martin-frbg** [comment]
I noticed this was commented on in the stackoverflow thread as well. Arguably the "L" designation on the constant is C/C++ idiom and not valid fortran, so support for it may be implementation dependent (and as it serves no useful purpose, I guess I should just remove it - was probably thinking of the more common __STDC_VERSION__ test when I wrote that)
