### ISSUE TITLE
Can't compile against musl

### ISSUE THREAD

**Issue by staticfloat** [xianyi/OpenBLAS#1552]
I'm trying to cross-compile OpenBLAS for `x86_64-linux-musl`, and I'm getting errors like the following:

```
/opt/x86_64-linux-musl/bin/x86_64-linux-musl-gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT  -fPIC -DDYNAMIC_ARCH -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=16 -DASMNAME=openblas_get_num_threads -DASMFNAME=openblas_get_num_threads_ -DNAME=openblas_get_num_threads_ -DCNAME=openblas_get_num_threads -DCHAR_NAME=\"openblas_get_num_threads_\" -DCHAR_CNAME=\"openblas_get_num_threads\" -DNO_AFFINITY -I../.. -c openblas_get_num_threads.c -o openblas_get_num_threads.o
memory.c: In function ‘get_num_procs’:
memory.c:191:20: error: missing binary operator before token "("
 #if !__GLIBC_PREREQ(2, 3)
```

This looks to me like `__GLIBC_PREREQ(x,y)` isn't defined on `musl` platforms.  Is there some kind of compatibility shim that we need to define?

**Comment by martin-frbg** [comment]
Are you building 0.2.20, or current "develop" branch ? This bug was (supposedly) fixed shortly after 0.2.20 but xianyi has not found the time to do another release yet.

**Comment by staticfloat** [comment]
Ah, no, that's true, I am building 0.2.20.

Is there a gitsha that the active developers have "blessed" as a particularly stable release candidate?

**Comment by martin-frbg** [comment]
Current f5959f2 should do... in fact if nothing serious comes up that one will probably become 0.3.0

**Comment by martin-frbg** [comment]
0.3.0 is out now, so closing here.
