### ISSUE TITLE
Segfault when running tests after compiling 0.2.3 on OSX 10.8.2

### ISSUE THREAD

**Issue by smcallis** [xianyi/OpenBLAS#156]
I'm trying to get Julia compiled, and I've run into a snag with the OpenBLAS 0.2.3 compilation:

(build with make CC="clang -mmacosx-version-min=10.6" FC="gfortran" FFLAGS="-ff2c -O2 -fPIC" USE_THREAD=1)

OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 ./dblat1
 Real BLAS Test Program Results

 Test of subprogram number  1             DDOT 
                                    ----- PASS -----

 Test of subprogram number  2            DAXPY 
                                    ----- PASS -----

 Test of subprogram number  3            DROTG 
                                    ----- PASS -----

 Test of subprogram number  4             DROT 
                                    ----- PASS -----

 Test of subprogram number  5            DCOPY 
                                    ----- PASS -----

 Test of subprogram number  6            DSWAP 
                                    ----- PASS -----

 Test of subprogram number  7            DNRM2 
                                    ----- PASS -----

 Test of subprogram number  8            DASUM 
                                    ----- PASS -----

 Test of subprogram number  9            DSCAL 
                                    ----- PASS -----

 Test of subprogram number 10            IDAMAX
                                    ----- PASS -----
OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 ./cblat1
 Complex BLAS Test Program Results

 Test of subprogram number  1            CDOTC 

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x100019bbe
#1  0x10001a2d4
#2  0x7fff98d598e9

gfortran -ff2c -O2  -o cblat2 cblat2.o ../libopenblas_sandybridgep-r0.2.3.a -lpthread -lgfortran  -lpthread -lgfortran  
gfortran -ff2c -O2  -o zblat2 zblat2.o ../libopenblas_sandybridgep-r0.2.3.a -lpthread -lgfortran  -lpthread -lgfortran  
rm -f ?BLAT2.SUMM
OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 ./sblat2 < ./sblat2.dat
make[1]: **\* [level1] Segmentation fault: 11
make[1]: **\* Waiting for unfinished jobs....
OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 ./dblat2 < ./dblat2.dat
OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 ./cblat2 < ./cblat2.dat
OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 ./zblat2 < ./zblat2.dat
rm -f ?BLAT2.SUMM
OPENBLAS_NUM_THREADS=2 ./sblat2 < ./sblat2.dat
OPENBLAS_NUM_THREADS=2 ./dblat2 < ./dblat2.dat
OPENBLAS_NUM_THREADS=2 ./cblat2 < ./cblat2.dat
OPENBLAS_NUM_THREADS=2 ./zblat2 < ./zblat2.dat
make: **\* [tests] Error 2

It looks like I have to use clang to compile (it fails compiling kernels with gcc), so I'm suspecting an incompatibility between the gfortran I have and clang:

> fortran -v 
> Using built-in specs.
> COLLECT_GCC=gfortran
> COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-apple-darwin11.4.0/4.7.1/lto-wrapper
> Target: x86_64-apple-darwin11.4.0
> Configured with: ../gcc-4.7.1/configure --enable-languages=fortran
> Thread model: posix
> gcc version 4.7.1 (GCC) 
> 
> clang -v 
> Apple clang version 4.1 (tags/Apple/clang-421.11.66) (based on LLVM 3.1svn)
> Target: x86_64-apple-darwin12.2.0
> Thread model: posix

Any guidance would be appreciated!

**Comment by 25th-engineer** [comment]
> Interesting compiling with just make CC=clang FC=gfortran seems to work fine. Optimization/other flags issue? Stay tuned.

I tried to compile with the command:
```shell
sudo make CC=clang FC=gfortran -j 8
```
the error didn't occur and finally successed

**Comment by martin-frbg** [comment]
Well, that error report was nine years ago (and even back then there should have been no reason to tell the compiler to assume unusual calling conventions that make it compatible with the ancient f2c converter)
