### ISSUE TITLE
/mips/sgemv_n_msa.c:426:33: error: incompatible types when initializing type ‘v4f32’ using type ‘double’

### ISSUE THREAD

**Issue by lancezhangsf** [xianyi/OpenBLAS#1561]
HI :
   i compile the openblas , using the doc:
MTI_TOOLCHAIN_DIR={/home/zsf/WorkSpace/Kernel/JunZheng/mips-mti-linux-gnu/2016.05-03/bin}
MTI_GCC_PREFIX=mips-mti-linux-gnu
MTI_TOOLCHAIN=${IMG_TOOLCHAIN_DIR}/${IMG_GCC_PREFIX}

make BINARY=32 BINARY32=1 CC=$MTI_TOOLCHAIN-gcc AR=$MTI_TOOLCHAIN-ar FC="$MTI_TOOLCHAIN-gfortran -EL"    RANLIB=$MTI_TOOLCHAIN-ranlib HOSTCC=gcc CFLAGS="-EL" FFLAGS=$CFLAGS LDFLAGS=$CFLAGS TARGET=P5600

but have the error :+1: 
ITY -I.. -UDOUBLE  -UCOMPLEX -UDOUBLE -UCOMPLEX  -DTRANS  ../kernel/mips/../mips/sgemv_t_msa.c -o sgemv_t.o
../kernel/mips/../mips/sgemv_n_msa.c: In function ‘sgemv_n’:
../kernel/mips/../mips/sgemv_n_msa.c:426:33: error: incompatible types when initializing type ‘v4f32’ using type ‘double’
     v4f32 v_alpha, x0, x1, y0 = 0.0, y1 = 0.0;
                                 ^
../kernel/mips/../mips/sgemv_n_msa.c:426:43: error: incompatible types when initializing type ‘v4f32’ using type ‘double’
     v4f32 v_alpha, x0, x1, y0 = 0.0, y1 = 0.0;
                                           ^
../kernel/mips/../mips/sgemv_n_msa.c:428:17: error: incompatible types when initializing type ‘v4f32’ using type ‘double’
     v4f32 tp0 = 0.0, tp1 = 0.0, tp2 = 0.0, tp3 = 0.0, tp4 = 0.0, tp5 = 0.0, tp6 = 0.0, tp7 = 0.0;
                 ^
../kernel/mips/../mips/sgemv_n_msa.c:428:28: error: incompatible types when initializing type ‘v4f32’ using type ‘double’
     v4f32 tp0 = 0.0, tp1 = 0.0, tp2 = 0.0, tp3 = 0.0, tp4 = 0.0, tp5 = 0.0, tp6 = 0.0, tp7 = 0.0;
                            ^
../kernel/mips/../mips/sgemv_n_msa.c:428:39: error: incompatible types when initializing type ‘v4f32’ using type ‘double’
     v4f32 tp0 = 0.0, tp1 = 0.0, tp2 = 0.0, tp3 = 0.0, tp4 = 0.0, tp5 = 0.0, tp6 = 0.0, tp7 = 0.0;
                                       ^
../kernel/mips/../mips/sgemv_n_msa.c:428:50: error: incompatible types when initializing type ‘v4f32’ using type ‘double’
     v4f32 tp0 = 0.0, tp1 = 0.0, tp2 = 0.0, tp3 = 0.0, tp4 = 0.0, tp5 = 0.0, tp6 = 0.0, tp7 = 0.0;
                                                  ^
../kernel/mips/../mips/sgemv_n_msa.c:428:61: error: incompatible types when initializing type ‘v4f32’ using type ‘double’
     v4f32 tp0 = 0.0, tp1 = 0.0, tp2 = 0.0, tp3 = 0.0, tp4 = 0.0, tp5 = 0.0, tp6 = 0.0, tp7 = 0.0;
                                                             ^
../kernel/mips/../mips/sgemv_n_msa.c:428:72: error: incompatible types when initializing type ‘v4f32’ using type ‘double’
     v4f32 tp0 = 0.0, tp1 = 0.0, tp2 = 0.0, tp3 = 0.0, tp4 = 0.0, tp5 = 0.0, tp6 = 0.0, tp7 = 0.0;
                                                                        ^
../kernel/mips/../mips/sgemv_n_msa.c:428:83: error: incompatible types when initializing type ‘v4f32’ using type ‘double’
     v4f32 tp0 = 0.0, tp1 = 0.0, tp2 = 0.0, tp3 = 0.0, tp4 = 0.0, tp5 = 0.0, tp6 = 0.0, tp7 = 0.0;
                                                                                   ^
../kernel/mips/../mips/sgemv_n_msa.c:428:94: error: incompatible types when initializing type ‘v4f32’ using type ‘double’
     v4f32 tp0 = 0.0, tp1 = 0.0, tp2 = 0.0, tp3 = 0.0, tp4 = 0.0, tp5 = 0.0, tp6 = 0.0, tp7 = 0.0;
                                                                                              ^
make[1]: *** [sgemv_n.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/home/zsf/WorkSpace/Kernel/JunZheng/OpenBLAS/kernel'
make: *** [libs] Error 1

**Comment by martin-frbg** [comment]
Looking at the other _msa.c sources there, this should probably be "{0,0,0,0}" rather than 0.0 for each initializer.

**Comment by martin-frbg** [comment]
Also looks to be fallout from #1419 - these variables used to be uninitialized until somebody tried to do a code cleanup.

**Comment by brada4** [comment]
I did not look in mips doc what data types stand for... after seeing sort-of float uninitialised in cppcheck.
kernel/mips/cgemv_n_msa.c line 514 needs your treatment too.

**Comment by martin-frbg** [comment]
Nope, that one is declared as FLOAT :)

**Comment by brada4** [comment]
:-)

**Comment by martin-frbg** [comment]
Should be fixed on the "develop" branch now, can you confirm please ? (And I also wonder if your build passes all parts of the utest - my mips32 system does not support msa).

**Comment by martin-frbg** [comment]
I had to add a few more fixes for mips32, for my own wrongdoings this time. Best update to the current state of "develop" before trying again.
