### ISSUE TITLE
Can't locate File/Temp.pm in @INC (you may need to install the File::Temp module)

### ISSUE THREAD

**Issue by rayjs** [xianyi/OpenBLAS#1566]
I am using a custom tool chain to compile OpenBLAS for the Target below:
Target is armv7a (32 bit) (EmbeddedOS)
Host is x86_64 Ubuntu 16

Please note that I have previously compiled successfully for armv7a for android.

I get the following error:
```
Can't locate File/Temp.pm in @INC (you may need to install the File::Temp module) (@INC contains: /opt/imx-toolchain/sysroots/x86_64-pokysdk-linux//usr/lib/perl/site_perl/5.22.1 /opt/imx-toolchain/sysroots/x86_64-pokysdk-linux//usr/lib/perl/vendor_perl/5.22.1 /opt/imx-toolchain/sysroots/x86_64-pokysdk-linux//usr/lib/perl/5.22.1 /opt/poky/2.1.3/sysroots/x86_64-pokysdk-linux/usr/lib/perl/site_perl/5.22.1/ /opt/poky/2.1.3/sysroots/x86_64-pokysdk-linux/usr/lib/perl/site_perl/5.22.1 /opt/poky/2.1.3/sysroots/x86_64-pokysdk-linux/usr/lib/perl/vendor_perl/5.22.1/ /opt/poky/2.1.3/sysroots/x86_64-pokysdk-linux/usr/lib/perl/vendor_perl/5.22.1 /opt/poky/2.1.3/sysroots/x86_64-pokysdk-linux/usr/lib/perl/5.22.1/ /opt/poky/2.1.3/sysroots/x86_64-pokysdk-linux/usr/lib/perl/5.22.1 /opt/poky/2.1.3/sysroots/x86_64-pokysdk-linux/usr/lib/perl/5.22.1 .) at ./c_check line 4.
BEGIN failed--compilation aborted at ./c_check line 4.
make: *** [config.h] Error 2
Makefile.system:171: Makefile.conf: No such file or directory
make: *** No rule to make target 'Makefile.conf'.  Stop.
Can't locate File/Temp.pm in @INC (you may need to install the File::Temp module) (@INC contains: /opt/imx-toolchain/sysroots/x86_64-pokysdk-linux//usr/lib/perl/site_perl/5.22.1 /opt/imx-toolchain/sysroots/x86_64-pokysdk-linux//usr/lib/perl/vendor_perl/5.22.1 /opt/imx-toolchain/sysroots/x86_64-pokysdk-linux//usr/lib/perl/5.22.1 /opt/poky/2.1.3/sysroots/x86_64-pokysdk-linux/usr/lib/perl/site_perl/5.22.1/ /opt/poky/2.1.3/sysroots/x86_64-pokysdk-linux/usr/lib/perl/site_perl/5.22.1 /opt/poky/2.1.3/sysroots/x86_64-pokysdk-linux/usr/lib/perl/vendor_perl/5.22.1/ /opt/poky/2.1.3/sysroots/x86_64-pokysdk-linux/usr/lib/perl/vendor_perl/5.22.1 /opt/poky/2.1.3/sysroots/x86_64-pokysdk-linux/usr/lib/perl/5.22.1/ /opt/poky/2.1.3/sysroots/x86_64-pokysdk-linux/usr/lib/perl/5.22.1 /opt/poky/2.1.3/sysroots/x86_64-pokysdk-linux/usr/lib/perl/5.22.1 .) at ./c_check line 4.
BEGIN failed--compilation aborted at ./c_check line 4.
make: *** [config.h] Error 2
Makefile.system:171: Makefile.conf: No such file or directory
make: *** No rule to make target 'Makefile.conf'.  Stop.

```

Commands I used:
```
make clean
source /opt/imx-toolchain/environment-setup-cortexa9hf-neon-poky-linux-gnueabi
make TARGET=ARMV7 BINARY=32 HOSTCC=gcc ONLY_CBLAS=1 NOFORTRAN=1 
make PREFIX=build_arm32v7-a_imx8 install
```

Here is the part of the script that I `source`d in the above command
```
 **cat /opt/imx-toolchain/environment-setup-cortexa9hf-neon-poky-linux-gnueabi**

... <redacted> ...
export SDKTARGETSYSROOT=/opt/imx-toolchain/sysroots/cortexa9hf-neon-poky-linux-gnueabi
export PATH=/opt/imx-toolchain/sysroots/x86_64-pokysdk-linux/usr/bin:/opt/imx-toolchain/sysroots/x86_64-pokysdk-linux/usr/sbin:/opt/imx-toolchain/sysroots/x86_64-pokysdk-linux/bin:/opt/imx-toolchain/sysroots/x86_64-pokysdk-linux/sbin:/opt/imx-toolchain/sysroots/x86_64-pokysdk-linux/usr/bin/../x86_64-pokysdk-linux/bin:/opt/imx-toolchain/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi:/opt/imx-toolchain/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-uclibc:/opt/imx-toolchain/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-musl:$PATH
export CCACHE_PATH=/opt/imx-toolchain/sysroots/x86_64-pokysdk-linux/usr/bin:/opt/imx-toolchain/sysroots/x86_64-pokysdk-linux/usr/bin/../x86_64-pokysdk-linux/bin:/opt/imx-toolchain/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi:/opt/imx-toolchain/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-uclibc:/opt/imx-toolchain/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-musl:$CCACHE_PATH
export PKG_CONFIG_SYSROOT_DIR=$SDKTARGETSYSROOT
export PKG_CONFIG_PATH=$SDKTARGETSYSROOT/usr/lib/pkgconfig
export CONFIG_SITE=/opt/imx-toolchain/site-config-cortexa9hf-neon-poky-linux-gnueabi
export OECORE_NATIVE_SYSROOT="/opt/imx-toolchain/sysroots/x86_64-pokysdk-linux"
export OECORE_TARGET_SYSROOT="$SDKTARGETSYSROOT"
export OECORE_ACLOCAL_OPTS="-I /opt/imx-toolchain/sysroots/x86_64-pokysdk-linux/usr/share/aclocal"
unset command_not_found_handle
export CC="arm-poky-linux-gnueabi-gcc  -march=armv7-a  -marm -mfpu=neon  -mfloat-abi=hard -mcpu=cortex-a9 --sysroot=$SDKTARGETSYSROOT"
export CXX="arm-poky-linux-gnueabi-g++  -march=armv7-a  -marm -mfpu=neon  -mfloat-abi=hard -mcpu=cortex-a9 --sysroot=$SDKTARGETSYSROOT"
export CPP="arm-poky-linux-gnueabi-gcc -E  -march=armv7-a  -marm -mfpu=neon  -mfloat-abi=hard -mcpu=cortex-a9 --sysroot=$SDKTARGETSYSROOT"
.
... <redacted> ...
.
```

**Comment by martin-frbg** [comment]
This looks like the installation of perl in your toolchain is somehow incomplete - the dependency on the File::Temp module was added to the c_check about two years ago, and from what I read on perldoc.perl.org this module has been a standard part of perl since version 5.6.1 (you seem to be using 5.22.1, if your perl `@INC` setting is correct)

**Comment by brada4** [comment]
you can install missing perl module with 'cpan File::temp'

**Comment by rayjs** [comment]
I have no control over the tool chain but thank you all for the feedback.

**Comment by martin-frbg** [comment]
You can try removing the two lines `use File::Temp qw(tempfile);` and
`$tmpf = new File::Temp( UNLINK => 1 );` (lines 4 and 14) from c_check that got added in #941, these should only be needed on MIPS.

**Comment by brada4** [comment]
@martin-frbg 
c_check uses /usr/bin/perl
Could it become /usr/bin/env perl
to accomodate environment redirections?

**Comment by martin-frbg** [comment]
@brada4 are you assuming that the wrong perl binary got called in the OP's case, or is this just a general suggestion ? (Not sure about portability)

**Comment by brada4** [comment]
Script calls /usr/bin/perl, no matter environment redirections (as seen in @@inc )
'env' is very old posix, omnipresent, NO-OP in particular case
REF https://en.wikipedia.org/wiki/List_of_Unix_commands

I dont know if we ask @rayjs to change c_check 1st line instead of
#!/usr/bin/perl
to
#!/usr/bin/env perl
Maybe it magically starts to work

**Comment by rayjs** [comment]
Thank you all for the help. I am getting a different error now. Perhaps some issue with the tool chain.

`c_check` file first 15 lines:
```
#!/usr/bin/env perl

use File::Basename;
#use File::Temp qw(tempfile);

# Checking cross compile
$hostos   = `uname -s | sed -e s/\-.*//`;    chop($hostos);
$hostarch = `uname -m | sed -e s/i.86/x86/`;chop($hostarch);
$hostarch = "x86_64" if ($hostarch eq "amd64");
$hostarch = "arm" if ($hostarch =~ /^arm.*/);
$hostarch = "arm64" if ($hostarch eq "aarch64");
$hostarch = "power" if ($hostarch =~ /^(powerpc|ppc).*/);
$hostarch = "zarch" if ($hostarch eq "s390x");

#$tmpf = new File::Temp( UNLINK => 1 );
$binary = $ENV{"BINARY"};
```

Commands ( I was given an incorrect 32 bit toolchain, now I am using the 64 bit tool chain)
```
make clean
source  /opt/fsl-imx-wayland/4.9.51-mx8-ga/environment-setup-aarch64-poky-linux
make TARGET=ARMV8 BINARY=64 HOSTCC=gcc ONLY_CBLAS=1 NOFORTRAN=1 
make PREFIX=build_arm64v8-a_imx8

```

Error:
```
aarch64-poky-linux-gcc: error: ../libopenblas_armv8p-r0.2.20.a: No such file or directory
aarch64-poky-linux-gcc: error: unrecognized command line option ‘-ru’; did you mean ‘-r’?
../Makefile.tail:40: recipe for target 'libs' failed
make[1]: *** [libs] Error 1
make[1]: Leaving directory '/home/<dir>/Documents/extern_libs/OpenBLAS/interface'
Makefile:131: recipe for target 'libs' failed
make: *** [libs] Error 1
/lib/ld-linux-aarch64.so.1: No such file or directory
make: *** [config.h] Error 255
make -f Makefile.install install
make[1]: Entering directory '/home/<dir>/Documents/extern_libs/OpenBLAS'
Makefile.install:21: *** OpenBLAS: Please run "make" firstly.  Stop.
make[1]: Leaving directory '/home/<dir>/Documents/extern_libs/OpenBLAS'
Makefile:322: recipe for target 'install' failed
make: *** [install] Error 2

```

**Comment by brada4** [comment]
You need to 'make clean' between builds.
env+perl trick was meant to get around unloadable File::Temp function (that /usr/bin/perl tries to load from redirections shown in @@inc and fails for good)

**Comment by rayjs** [comment]
Yeah I do make clean.
The commands I showed is a shell script so it ensures 'make clean' always

**Comment by brada4** [comment]
Q1: does using 'env perl' in place of 'perl' helps perl script to find File::Temp?
Q2: cause (warnings etc) should be well before error in last screen. Just a wild guess: add build parameter:
AR=aarch64-poky-linux-ar

**Comment by brada4** [comment]
@rayjs  which one solved your prob ? Either sort of necessitates small polishing of makefiles.

**Comment by rayjs** [comment]
@brada4  I am not sure, I referred the toolchain provider to this page and then they compiled OpenBLAS for me.

**Comment by mxbsakura** [comment]
did you have solved the issue,  I have the same issue and if you have solved it please share with,thanks a lot

**Comment by brada4** [comment]
Since there was no feedback from OP nothing was changed in code.
Could you try replacing script interpreter first as discussed above?

**Comment by rayjs** [comment]
I am sorry but there is nothing I can do. Its a proprietary tool chain from another party and it was a blackbox for me.

**Comment by martin-frbg** [comment]
@mxbsakura what is your platform and what is the "same issue" you have - the "File/Temp.pm not found" or the missing ld-linux-aarch64.so.1that rayjs encountered later ?

**Comment by brada4** [comment]
gcc is GPL sort of. Including yocto-poky releases....

**Comment by martin-frbg** [comment]
Does not help if there was some issue with the toolchain setup and the proprietary third party did not want (or bother) to tell what needed changing. Still we do not know what the *current* problem is that mxbsakura seeks help with. If it is only the perl File.pm issue, it is probably possible to move all reference to it down into the mips-only section of c_check so that it does not cause unnecessary trouble on other platforms.

**Comment by brada4** [comment]
I will make a PR
It is not MIPS specific, in case of yocto/poky SDK -  perl is in path and P5LIB is set to that private perl, so system perl chokes on (much newer) private modules.
Targets are i586 mips arm and some non-openblas platforms too
Basically:
`#!/usr/bin/env perl`
in place of
`#!/usr/bin/perl`
Which will pick `perl` command instead of static path.
EDIT: env serves as a fixed path because hashbang will not run plain command from path.
I will spend some hours building "full" SDK just to see if something else crosses ways with system/no-compiler tools
