### ISSUE TITLE
OpenBLAS 0.2.20 build problem

### ISSUE THREAD

**Issue by kayakml** [xianyi/OpenBLAS#1569]
I am trying to install OpenBLAS into my win10 computer. Actually I want to use a python package named scikits.odes to solve some DAE problem. [In the installation document](http://scikits-odes.readthedocs.io/en/latest/installation.html#requirements-before-install) they recommend first to install OpenBLAS (at least I understood in this way). After a 7 days of struggle I have "learned!!" and installed cmake 3.11.1 and mingw. After then I downloaded [lapack - 3.8.0](http://www.netlib.org/lapack/). First I finished cmake-gui things and then from the command line I run mingw32-make.exe command and managed to get libblas.a nd liblapack.a files (though I dont know what to do with them). Then I downloaded OpenBLAS-0.2.20. Again finished cmake-gui things. It came to the command line thing. I run C:\openblas-build   mingw32-make.exe command. Everything went ok till this error message 
`[ 18%] Building C object driver/level3/CMakeFiles/driver_level3.dir/CMakeFiles/zgemm3m_thread_tt.c.obj
[ 18%] Built target driver_level3
Scanning dependencies of target genlapacke
process_begin: CreateProcess(NULL, cp C:/OpenBLAS-0.2.20/lapack-netlib/LAPACKE/include/lapacke_mangling_with_flags.h.in C:/openblas-build/lapacke_mangling.h, ...) failed.
make (e=2): Sistem belirtilen dosyayı bulamıyor.
CMakeFiles\genlapacke.dir\build.make:56: recipe for target 'CMakeFiles/genlapacke' failed
mingw32-make.exe[2]: *** [CMakeFiles/genlapacke] Error 2
CMakeFiles\Makefile2:262: recipe for target 'CMakeFiles/genlapacke.dir/all' failed
mingw32-make.exe[1]: *** [CMakeFiles/genlapacke.dir/all] Error 2
Makefile:139: recipe for target 'all' failed
mingw32-make.exe: *** [all] Error 2
(base) C:\openblas-build>`
*Sistem belirtilen dosyayı bulamıyor. = couldn't find the specified file (in turkish)
I checked if the 2 files (lapacke_mangling_with_flags.h.in and lapacke_mangling.h) are missing? But no I have them right in the C:\OpenBLAS-0.2.20\lapack-netlib\LAPACKE\include 
I am really exhausted in this 7 days . I need some help to install OpenBLAS ( or to install sundials or to install scikits.odes) I really appreciate it.

**Comment by brada4** [comment]
You just type 'make' in top level OpenBLAS source directory? 
Lapacke will need fortran compiler down the road, probably cmake files included do not check that. 
Can you show link how scikit, a pure python, would use any library apart ones linked from scipy....

**Comment by brada4** [comment]
In principle you have binary wheel packages reachable by PIP too, some of them with OpenBLAS included.
Also Anaconda is a good python with almost all bits MKL for intel CPUs. Windows building is not the easiest task to start with. e.g. "official" dll releases are cross-compiled on Linux with mingw compilers.

**Comment by kayakml** [comment]
thank you brada4 for the answer. And sorry for late. Yes, I just type "make" in top level OpenBLAS. Actually I found another package named DAETools and installed it in just 2 minutes. I think it is best to switch to linux for scientific computing.

**Comment by brada4** [comment]
i think you can close the issue
Project binaries are here: https://sourceforge.net/projects/openblas/files/v0.2.19/
Takes few seconds to unzip.
