### ISSUE TITLE
sswap/dswap utests fail with kernel/x86/swap.S

### ISSUE THREAD

**Issue by atsampson** [xianyi/OpenBLAS#1575]
With OpenBLAS 0.3.0, building on IA32 with TARGET=PRESCOTT DYNAMIC_ARCH=1, I see two test failures in utest/test_swap.c. WIth some code added to show the array contents:

```
TEST 14/22 swap:sswap_inc_0 before sswap:
x1[0]=1.000000 y1[0]=2.000000
x1[1]=3.000000 y1[1]=4.000000
x1[2]=5.000000 y1[2]=6.000000
x1[3]=7.000000 y1[3]=8.000000
after:
x1[0]=2.000000 y1[0]=1.000000
x1[1]=3.000000 y1[1]=4.000000
x1[2]=5.000000 y1[2]=6.000000
x1[3]=7.000000 y1[3]=8.000000
[FAIL]
  ERR: test_swap.c:105  expected 1.000e+00, got 2.000e+00 (diff -1.000e+00, tol 1.000e-04)
TEST 15/22 swap:zswap_inc_0 [OK]
TEST 16/22 swap:dswap_inc_0 before dswap:
x1[0]=1.000000 y1[0]=2.000000
x1[1]=3.000000 y1[1]=4.000000
x1[2]=5.000000 y1[2]=6.000000
x1[3]=7.000000 y1[3]=8.000000
after:
x1[0]=2.000000 y1[0]=1.000000
x1[1]=3.000000 y1[1]=4.000000
x1[2]=5.000000 y1[2]=6.000000
x1[3]=7.000000 y1[3]=8.000000
[FAIL]          
```

So it's swapping the first element when it shouldn't do anything with incx==incy==0. This looks like another instance of the problem in #1469.

Tracing with gdb reveals it's using the implementation in kernel/x86/swap.S, which has no explicit test in there for this case. Making the following change fixes it (although I imagine someone who's better at x86 assembler than me can probably suggest a nicer approach!):

```
--- tmp/v0.3.0/kernel/x86/swap.S	2017-07-24 09:05:15.000000000 +0100
+++ work/v0.3.0/kernel/x86/swap.S	2018-05-25 17:50:39.551000000 +0100
@@ -138,6 +138,14 @@
 /* INCX != 1 or INCY != 1 */
 
 .L14:
+	cmpl	$0, %ebx
+	jne	.L141
+	cmpl	$0, %ecx
+	jne	.L141
+/* INCX == 0 and INCY == 0 */
+	jmp	.L27
+
+.L141:
 	movl	%edx, %eax
 	sarl	$2,   %eax
 	jle	.L28
```

I haven't checked to see if kernel/x86/swap-sse.S and swap-sse2.S have the same problem.

**Comment by martin-frbg** [comment]
Thank you. I notice this fixes an issue that I had blindly worked around earlier, trying to get the utests to pass for Nehalem and 32-bit Haswell builds. I _think_ I had somehow assumed that these used the sse versions of the s/dswap assembly (which I struggle to read), but these appear to be actually not used on any hardware.
