### ISSUE TITLE
getstackaddr should return size_t

### ISSUE THREAD

**Issue by KindDragon** [xianyi/OpenBLAS#1577]
`unsigned long` for MS Visual C++ is 4 bytes types even when you compile for x64 platform
https://github.com/xianyi/OpenBLAS/blob/88e224f4c03a39c7564117bc2b0306397c9fdaac/common_x86.h#L99

**Comment by martin-frbg** [comment]
Thanks, that function stems from the original GotoBLAS (probably following C89 rules at the time) and as far as I can tell is not used anywhere. (Or did you encounter a caller that my search missed ?)

**Comment by KindDragon** [comment]
Yes you right, and it redefined for x64 https://github.com/xianyi/OpenBLAS/blob/88e224f4c03a39c7564117bc2b0306397c9fdaac/common_x86_64.h#L107
