### ISSUE TITLE
_Atomic definition

### ISSUE THREAD

**Issue by diorcety** [xianyi/OpenBLAS#1593]
Here https://github.com/xianyi/OpenBLAS/blob/develop/common.h#L653
ifndef is used to check if _Atomoc is defined. It doesn't seems to work with clang (6.0 for me).
Removing the 3 lines of this ifndef make the compilation succeed
https://releases.llvm.org/3.1/tools/clang/docs/LanguageExtensions.html#c_atomic

**Comment by martin-frbg** [comment]
Hmm. Somehow that block looks reversed, maybe it would make more sense to write
```
#if (__STDC_VERSION__ >= 201112L)
#include <stdatomic.h>
#else
#ifndef _Atomic
#define _Atomic volatile
#endif
#endif

**Comment by diorcety** [comment]
Indeed :)

**Comment by dzyong** [comment]
Hi @martin-frbg 

The old code can work well with gcc (but the new code couldn't, because of https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65467), if it has some problem with clang, maybe we should distinguish compiler here.

**Comment by martin-frbg** [comment]
Sorry, I had completely forgotten about the gcc issue that made this odd code necessary. As far as I can tell, this should have been fixed with gcc 7, so making it conditional on `#if defined(C_GCC) && (__GNUC__ < 7) ` should be sufficient ?
