### ISSUE TITLE
Large number of micro-architectures in DYNAMIC_ARCH=1

### ISSUE THREAD

**Issue by sandwichmaker** [xianyi/OpenBLAS#1595]
I would like to reduce the number of micro-architectures being built when DYNAMIC_ARCH=1, is there a way to do that? My naive attempts at editing the makefiles led to linking failures.

**Comment by martin-frbg** [comment]
Unless you want to remove the more modern architectures (which could be done by setting NO_AVX2=1
or even NO_AVX=1), there is currently no clean way to do this. You would need to hack driver/others/dynamic.c directly to either remove all traces of the architectures that you removed from the DYNAMIC_CORE list of Makefile.system, or `#define` their gotoblas_KERNEL function pointer to point to one of the remaining architectures.

**Comment by sandwichmaker** [comment]
Thanks @martin-frbg that is what I gathered too, that this would require some kind of dynamic.c hacking. Having a fallback mechanism would be nice.

**Comment by martin-frbg** [comment]
related to #791 - it has been noted before that the number of dynamic targets is getting out of hand (and it is causing trouble for the continuous integration tests as well). Which architectures would you like to remove (or see removed from the default list) ?

**Comment by sandwichmaker** [comment]
@martin-frbg I only care about newer CPUs.

roughly Zen, Nehalem, sandybridge and haswell.

**Comment by martin-frbg** [comment]
Hmmm. #791 had people asking to keep even Prescott, guess you can't please everybody. 

It should be easy to override the DYNAMIC_CORE list in Makefile.system with a user-defined selection from Makefile.rule (or the environment), but I do not see how to parse this list on the preprocessor level and add redirections for all "standard" types _not_ on this list in dynamic.c.
Perhaps creating a handful of predefined subsets would work, say DYNAMIC_NO_ANCIENT (
only nehalem and newer), DYNAMIC_NO_AMD and DYNAMIC_NO_INTEL ? At least that would
make it easy to add blocks of `#define gotoblas_SOMEKERNEL gotoblas_SOMEFALLBACK` to
dynamic.c

**Comment by sandwichmaker** [comment]
@martin-frbg a few extra architectures are not a problem. So if you had a group that had Prescott, I would be okay with it. 

I am displaying my lack of knowledge about these architectures, but could we introduce an ordering of these microarchitectures which could be used for reasoning about fallback?

**Comment by martin-frbg** [comment]
I believe the list in Makefile.system is mostly in that order, although it is basically chronological. There are a few branches in it like Dunnington (Intel Xeon from 10 years ago) vs. Nehalem (early i7, still useful for mobile and  small-form-factor HTPC or NAS systems), or AMD's product line name after heavy construction machinery.

**Comment by sandwichmaker** [comment]
@martin-frbg thanks for addressing this so quickly.

**Comment by sandwichmaker** [comment]
@martin-frbg any chance of an intel/amd split too?

**Comment by martin-frbg** [comment]
Not sure I really want to go there :-)
But I assume you would want a very short list of recent systems in that case, like NEHALEM-SANDYBRIDGE-HASWELL-SKYLAKEX or  BARCELONA-BULLDOZER-EXCAVATOR-ZEN ?

**Comment by sandwichmaker** [comment]
@martin-frbg I totally understand your hesitation in increasing the complexity of the build, but I had to ask :). Actually I should correct myself. I am more interested in things chronologically and newer architectures rather than the intel/amd split. I think your current patch if expanded to include some of the AMD architectures should be good enough. Either ways, your current patch is already a big step in the direction of reducing the size of the build.

**Comment by martin-frbg** [comment]
The selection was mostly guided by #791, I'll wait a bit for comments from others before committing. Perhaps it would make sense to move AMD Bulldozer, Piledriver and/or Steamroller to the "OLDER" list as well.

**Comment by brada4** [comment]
And my piledrivers?
If we substitute overall default of prescott by atom then we get better stuff for average "new small laptop" case.
Probably the only openblas user on a hackintosh will not complain about absent AMD kernels in default build while others will fancy the speed of build.

**Comment by martin-frbg** [comment]
PILEDRIVER is still on the DYNAMIC_ARCH list even with this PR, and ATOM can stay on it if there is sufficient interest. Not sure what your comment about "the only user on a hackintosh" is trying to tell me, do you mean the OPTERON kernels I removed from the default list ?

**Comment by brada4** [comment]
I mean that on OSX there is no purpose whatsoever in having AMD kernels.

Other point is to default to ATOM on unknown x86_64 CPUs, it is more likely to hit the spot today than Prescott, and the difference is minimal (less of jump targets present on ATOM CPU, thus it will be better than vice versa, esp having same instruction set)

**Comment by martin-frbg** [comment]
Initial version merged now, but leaving this open for further discussion and improvement.

**Comment by sandwichmaker** [comment]
@martin-frbg what do you think about moving the older AMD targets to DYNAMIC_OLDER?

**Comment by martin-frbg** [comment]
I am unsure which if any to (re)move, and I do not want to create the impression that OpenBLAS is reducing support for AMD hardware. Barcelona probably needs to stay as least common denominator (and also seems to be be what is used for relatively recent mobile systems, e.g. A8). That would leave Piledriver/Steamroller (or Bulldozer and Steamroller) as candidates, and I have no idea how popular these are.

**Comment by martin-frbg** [comment]
Steamroller cpuid fix was only a year ago (#1159), Bulldozer seems to be at the heart of compute clusters from 2-3 years ago so probably not yet fair to remove from the standard list either.

**Comment by sandwichmaker** [comment]
Thinking out aloud here.

I think having the AMD arches in the default build is fine, as long as there is a way of excluding them if the user so desires. So putting them in DYNAMIC_OLDER is not a great idea since it is off by default.

But perhaps add DYNAMIC_AMD_OLDER which is on by default but can be turned off?

But all of this sounds a bit dirty, and are we just trying to avoid a proper more sophisticated reasoning algorithm as part of the build system that given a set of desired architectures, figures out the right thing to do?

we are already doing this with the single core v/s dynamic_arch, and then within dynamic_arch we are doing the dynamic_older v/s not.

**Comment by martin-frbg** [comment]
Something like `export MY_DYNAMIC_ARCH='GOLEM R2D2 TERMINATOR'` ?

**Comment by sandwichmaker** [comment]
Thanks @martin-frbg for #1639. My apologies for not getting back to you earlier with feedback. It works well. We have been dealing with another issue that I will start a new thread about.

**Comment by martin-frbg** [comment]
Not a new blocker I hope...
