### ISSUE TITLE
share the real floating point performance of the CPU in hand?

### ISSUE THREAD

**Issue by yyy-git** [xianyi/OpenBLAS#1603]
Though we can calculate the peak performance from the referance manual published by CPU vendors. It's only a theoretical upper bound. The information on the web about floating point performance is also misleading. For example, there is one website says 8700K is 138GFLOPS. But my result of i5-7500 is 186GFLOPS. And many users,including me, were not aware of the poor single thread floating performance of ZEN until we run some program...
So I want to collect some information of the floating point performance of CPUs, which is reliable and informative.
Since the whole system takes some time to warm up for floating point operation,  I run cblas_dgemm() repeatedly for 10min or 15min. Considering 4K alasing, the LDC should not be dividend by 4096. In my experiment, the mean value or median value is very close, so either will be OK. For laptop, only the data after 30 seconds or so should be adopted because of turbo boost. 
The real problem of floating operation is heat, so the temperature and power consumption of CPU are also important. 

Here is my result:
TR1950x@3.75GHz SMT OFF,16G DDR4@2666M*quad-chanel,kali linux,16 threads,OpenBLAS-v0.2.20-ZEN,406GFLOPS(double),232Watt(1.225V,EXCAVATOR,windows),70 degrees Celsius(1.225V,EXCAVATOR,windows 10, 240 AIO liquid cooler )

i7-8550U@(2.2G,not sure) HT ON,8G DDR4@2400M*single stick,windows 10,8-threads,OpenBLAS-v0.2.19-HASWELL,113GFLOPS(double)

i5-7500 NO HT,4G DDR4@2400M*dual chanel,windows 10,4 threads,OpenBLAS-v0.2.19-HASWELL,186GFLOPS(double)

**Comment by martin-frbg** [comment]
Not sure if you want to compare the performance of the CPU, or that of the OpenBLAS optimization (versions may differ in machine code efficiency, threading,...) ? 
The current code is not optimized for Zen (still treating is as Haswell, although there are known differences in e.g. AVX2 performance). I just committed a fix that has noticable influence on thermal behaviour.

**Comment by yyy-git** [comment]
@martin-frbg  I'm not going to compare the performance of libraries, that depends on the size of matrix and number of threads. I just want to know the real performance of CPU, no matter you are using MKL or OpenBLAS. 
Results of AIDA64 GPGPU benchmark are also OK, because usually we can achieve >80% of the peak value. btw, GFLOPS of AIDA64 GPGPU benchmark is independent of memory bandwith.
![aida64_tr1950x_3 75g_2666m_fpu_benchmark_cpu_gpu](https://user-images.githubusercontent.com/35886438/41097735-9b2f76d4-6a8b-11e8-91de-ea1613623efa.PNG)

**Comment by martin-frbg** [comment]
"real performance" will be influenced by the choice of machine code instructions, and anything else that may make one cpu spend time waiting for data rather than computing. I am fairly certain you will get quite different GFlops figures from MKL, Atlas, etc., and from different versions of OpenBLAS as well.

**Comment by yyy-git** [comment]
As long as the "real performance" > 80% of  theoretical upper bound( FREQ x NUM_CORES x 16/8), it's acceptable. There should be two extra curves mean=380GFLOPS and mean=390GFLOPS in the figure below(I don't want to make a mess of the figure). But any value in 380-403GFLOPS can tell us it's much powerful than i5-7500.

divide/sqrt/sin operation have much lower GFLOPS, some lapack functions' bottleneck is not CPU. Still you can not say GFLOPS is useless. Too many people don't realize the importance of GFLOPS until they find their matlab/DeepLearning or something else is running much slower than others. 

![tr1950x_dgemm_gflops_oc_cmp](https://user-images.githubusercontent.com/35886438/41100064-f281426c-6a92-11e8-98d4-a58e894f2dfc.png)

**Comment by martin-frbg** [comment]
I still think GFlops values obtained with different versions will not give a fair comparison of CPU power. And even with the same version, it would mostly tell which hardware to choose if you want to run some code with that version of OpenBLAS. Nevertheless, the comparison may be useful even if just to see what needs optimization. Keeping the list up to date would be a major task though - and perhaps using a page in the wiki will be more appropriate for it than an issue ticket ?

**Comment by brada4** [comment]
?Can you compare if OpenBLAS (Haswell vs Zen having previous discussions in mind) gets proportionally comparable CPU GFlops to your benchmark?
https://github.com/xianyi/OpenBLAS/tree/develop/benchmark/scripts

I vote for wiki page too that helps people to detect sub-standard hardware setups

**Comment by brada4** [comment]
PS in your benchmark it is obvious that GPU memory copy is optimized to pointer swap/CoW etc and actually no processing takes place.

**Comment by yyy-git** [comment]
My AIDA64's help is out of date, it says nothing about how  memory copy is done on GPU. 
I think there is another possibility that memory read and memory write is the speed of PCIE rather than GPU, while the memory copy is the real bandwith of GPU memory. 
https://en.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units#GeForce_10_series, the bandwith of GTX1080TI is 484.3GB/s.

it seems that my numpy is not using openblas-0.2.20, and so do octave.
I have run the octave scripts. There is no significant  difference between HASWELL and ZEN. but I think the reason is octave's blas doesn't know ZEN...
My handwritten C code gives the best result of dgemm. Still, no significant gap between HASWELL and ZEN as regard to dgemm.

TR1950x, kali linux. OpenBLAS-v0.2.20.
[result.txt](https://github.com/xianyi/OpenBLAS/files/2093893/result.txt)

**Comment by brada4** [comment]
I dont know if this FAQ entry applies to kali linux too:
https://github.com/xianyi/OpenBLAS/wiki/faq#debianlts
(first check if libblas.so.3 is alternative-enabled, build anything after, add kali name to faq if it is that close to debian/ubuntu)
0.2.20 needs `OPENBLAS_CORETYPE=Haswell` for ZEN. In 0.30.0 and current develop ZEN architecture code is identical to that one of haswell. It is just brought out for future tuning.

**Comment by yyy-git** [comment]
There is no option named "--add" in update-alternatives on my kali. It failed...

**Comment by brada4** [comment]
... thus not worth mentioning in this case ...
