### ISSUE TITLE
OpenBLAS should be resilient to reported zero-size L2 cache lines

### ISSUE THREAD

**Issue by nelhage** [xianyi/OpenBLAS#1610]
On current versions of the "crostini" virtual machine on Google's Pixelbooks, the hypervisor erroneously reports all 0s for CPUID 0x80000006, including a zero-size L2 cache line. This causes openblas to spin forever on most operations:
https://bugs.chromium.org/p/chromium/issues/detail?id=848488

The bug here is clearly in the hypervisor, but I'd like to request that OpenBLAS could still be better-behaved here, and either die with an error or assume a default cacheline size.

**Comment by martin-frbg** [comment]
Not sure what a sensible default would be, perhaps 256k ?. ~Building with an appropriate TARGET option such as TARGET=HASWELL should work around this.~ (Misconfigured hypervisors are known to cause problems, e.g. qemu not reporting a feature set corresponding to any real cpu model)
EDIT: build-time detection already has a fallback case for this (using 1M L2 cache size), it is the runtime detection in a DYNAMIC_ARCH situation, i.e. get_l2_size/get_l2_size_old in kernel/setparam-ref.c that silently returns 0 for any unexpected response. This definitely looks unhealthy.
