### ISSUE TITLE
With threading enabled, small matrix gemm performance gets worse. 

### ISSUE THREAD

**Issue by sandwichmaker** [xianyi/OpenBLAS#1614]
As @oon3m0oo has reported, small matrix gemm < 32x32, which should not be affected by threading get slower with pthreads as well as OpenMP.

**Comment by fenrus75** [comment]
using strace on a small matrix multiply shows that we do

openat(AT_FDCWD, "/sys/devices/system/cpu", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3</sys/devices/system/cpu>
fstat(3</sys/devices/system/cpu>, {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
getdents(3</sys/devices/system/cpu>, /* 38 entries */, 32768) = 1128
getdents(3</sys/devices/system/cpu>, /* 0 entries */, 32768) = 0
close(3</sys/devices/system/cpu>)       = 0
sched_getaffinity(5432, 8, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]) = 8
fstat(0</dev/pts/0>, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
fstat(1</dev/pts/0>, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
fstat(2</dev/pts/0>, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
openat(AT_FDCWD, "/sys/devices/system/cpu", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3</sys/devices/system/cpu>
fstat(3</sys/devices/system/cpu>, {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
getdents(3</sys/devices/system/cpu>, /* 38 entries */, 32768) = 1128
getdents(3</sys/devices/system/cpu>, /* 0 entries */, 32768) = 0
close(3</sys/devices/system/cpu>)       = 0
sched_getaffinity(0, 8, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]) = 8


for each... which is likely part of the extra cost.

**Comment by sandwichmaker** [comment]
@fenrus75  Is this only for when threading is enabled or is this the dynamic dispatch logic in general?

**Comment by sandwichmaker** [comment]
@oon3m0oo

**Comment by martin-frbg** [comment]
Pretty sure this cpu enumeration happens only once on (any) startup. Trying to identify the various callers of YIELDING now - setting a breakpoint on sched_yield() with gdb seems to hit only once per thread, but adding a printf to the macro generates several lines of output - maybe I am using gdb wrong.

**Comment by martin-frbg** [comment]
All calls to sched_yield() (in benchmark/sgemm.goto 30 30 1) appear to originate from https://github.com/xianyi/OpenBLAS/blob/2f957947a6ed0712f13c8ff97a6ff60c60d6e1e0/driver/others/blas_server.c#L319-L320 
in blas_thread_server()  waiting for the thread_status[cpu].queue to change
(This was rewritten by me a year ago in #1052 to fix a race condition, but if I introduced a logic change there I am still unable to see it now. Still might be worthwile to check if 0.2.19 from before this change shows the same bad behaviour)

**Comment by oon3m0oo** [comment]
level3_thread.c also emits many sched_yield calls; I'm seeing many of them come from there.  At least, when I replaced sched_yield with __builtin_ia32_pause suddenly inner_thread was in the top 3 in my profile, since the profiler seems to count the pause as time.

**Comment by martin-frbg** [comment]
level3_thread is not called for small matrices, I am just trying to find what the other, supposedly dormant threads are up to while one is busy with the "single-threaded" gemm for 30x30. Apparently entering YIELDING again and again is not a good idea, but I have no idea how to turn this into something based on pthread_cond_wait() or whatever... It seems libGoto2 was not designed for situations where not all threads are busy, and the various nthreads=1 kludges added much later did not address the scheduling, they only avoid splitting a small problem into even tinier chunks. 
I have tried using openblas_set_num_threads(), but this can only add additional workers to the pool
created on initialization.

**Comment by oon3m0oo** [comment]
I've identified the root cause of the slowdown.  When SMP is defined, blas_memory_alloc does a large amount of locking and unlocking.  Adding:
```
#undef LOCK_COMMAND
#define LOCK_COMMAND(a)
#undef UNLOCK_COMMAND
#define UNLOCK_COMMAND(a)
```
before the definition of blas_memory_alloc in memory.c, and all that extra time goes away for small matrices.  Obviously we don't want to do this when we're actually using threads, but I believe this is the culprit. Each call to gemm (with matrix size 4) is causing 14 lock/unlock pairs (13 in alloc, 1 in free), which seems excessive.

It looks like the reason OpenBLAS doesn't just rely on the existing thread safety of malloc and free is to reuse preallocated pages (though it's admittedly a bit hard to read memory.c).  Is that right?

**Comment by martin-frbg** [comment]
I had already limited the use of locks to the non-OpenMP case in #1468 . Without them OpenBLAS would be back at the racy 0.2.19 stage as mentioned above, but perhaps it would be possible to use fewer locks around larger sections of the code. Not sure if/how blas_memory_alloc could act differently with a knowledge that only a single thread is truely active.
~~BTW I think this does not explain the difference seen between running with and without OPENBLAS_NUM_THREADS=1,~~ (EDIT: well, except that the blas_memory_alloc would be done for the unused extra threads as well) so there are probably two cumulative effects at work here ?

**Comment by oon3m0oo** [comment]
I'm wondering if some things here might be usable as thread-local, such as memory, release_info, etc.  The dynamic initialization still needs to be global, but I think there's a better way to ensure one-time initialization than locking on every allocation.  Have you tried this before?  I'm happy to spend some time seeing if I can make it fast while keeping it safe.

**Comment by martin-frbg** [comment]
I never tried this, and am not aware of anyone who has.

**Comment by fenrus75** [comment]
while mutexes are not cheap, in single threaded mode there shouldn't be any
contention so surprised this shows up at all....

**Comment by martin-frbg** [comment]
Not sure what "single threaded mode" is in this OpenBLAS context - the gemm interface keeps the work all in one thread if the matrix is small, but initialization created a thread pool (with each thread doing its blas_memory_alloc) earlier and the other threads are spinning sched_yield(). Maybe I just got tricked (by helgrind) into adding lots of locks around code that cannot develop races in any case - but if this was the full story, shouldn't 0.2.19 and earlier show much smaller difference between single-threaded _build_ and multihreaded running with OPENBLAS_NUM_THREADS=1 ?

**Comment by martin-frbg** [comment]
Returning to that `while(!tscq) {YIELDING` in blas_server.c , that section of the code seems to want to check if it is time for an idle thread to go to sleep. Is deriving the elapsed time from the TSC the right tool for this job ? Is the compile-time constant THREAD_TIMEOUT of 1 << 28 (not 1<<26 as suggested in Makefile.rule) or 100(?) milliseconds appropriate ? Should the gemm interface itself send the excess threads to sleep when it wants to go single-threaded, and wake them up when it is done ? Clearly reducing the THREAD_TIMEOUT to values below 20 reduces the number of  pointless calls to sched_yield() as the idle threads quickly end up in pthread_cond_wait().

**Comment by fenrus75** [comment]
the sad part is that glibc has a flag you can set on the pthread locks/etc
that makes glibc spin an appropriate amount of time

normally apps then don't have to do their own spinning on top ;-)

100 msec is *forever* for spinning though. The other sad part is that a
sched_yield() is approximately as expensive as just waking up from a
cond_wait()

(at least in terms of order of magnitude and the work they do in the
process scheduler)

**Comment by martin-frbg** [comment]
That flag may not have been available ~10 years ago, and OpenBLAS needs to stay compatible with
other implementations of libc. However both the huge THREAD_TIMEOUT and the loop appear to be unchanged from libGoto2-1.08 (the oldest libGoto2 I still have on my system), even if they were appropriate back then they may not be now.
I should not be working on this today, with paid customer projects waiting...

**Comment by oon3m0oo** [comment]
I've successfully been able to use TLS for memory tracking in memory.c, and that (with #1612), completely removes the difference between threaded and non-threaded builds.  I'll send over a PR in a couple minutes.

**Comment by oon3m0oo** [comment]
Created #1618.

**Comment by martin-frbg** [comment]
Merged #1618. (Worst case we may need to `#ifdef` old vs. new implementation if some currently supported platform does not cope with thread-local storage)

**Comment by sandwichmaker** [comment]
This seems to have caused some regressions on small matrices on ARM64 in single threaded mode. @oon3m0oo and I are investigating.

**Comment by martin-frbg** [comment]
Seems to me you introduced a lock/unlock in single threaded mode around line 1023 (which was previously in an `#ifdef OPENMP` section) ?

**Comment by martin-frbg** [comment]
My late-night blunder with the CannonLake cpuid patch also makes me realize we have grown a build warning on the windows/mingw platform:
```
memory.c:433:15: warning: thread attribute directive ignored
memory.c:434:1: warning: thread attribute directive ignored
memory.c:977:15: warning: thread attribute directive ignored
```
and potentially more seriously with gcc on both Linux and Windows,
```
memory.c: In function blas_memory_free:
memory.c:1149:13: warning: array subscript is above array bounds
```
(and also a "cast to pointer from integer of different size" in blas_server_win32.c:506:30 that could be
related)

**Comment by oon3m0oo** [comment]
I don't think there's a new lock, it's only hit a single time, the first time threads hit this routine.  After that the if will fail and you don't lock.

Also, I've got a patch in the works that will reduce this down to a single TLS index (which should help with Android), and should resolve these two, and makes it easier to emulate for arches which don't support TLS like this.

If you'd rather revert the original patch first, that's ok by me.

**Comment by martin-frbg** [comment]
Depends on the timeframe you envisage for the patch - as the issue does not appear to be catastrophic I guess we can live with a slowdown on one platform for a few days. Not sure about the bounds check warning yet, could be a false positive from gcc.

**Comment by oon3m0oo** [comment]
I've put up #1625 which ought to resolve this, though I'll let the automated builder check a few thing for me.

**Comment by sandwichmaker** [comment]
I can confirm that this has been fixed.
