### ISSUE TITLE
where is the binary DLLs downloading for windows

### ISSUE THREAD

**Issue by yanchao12122** [xianyi/OpenBLAS#1615]
I don't want to build openblas on windows.
Is there any way to download the  prebuilt binary packages .

**Comment by martin-frbg** [comment]
Please see https://github.com/xianyi/OpenBLAS/wiki/Precompiled-installation-packages  - xianyi's "official" binaries on the sourceforge site have not yet been updated, but you can find equivalent files e.g.
in the "Julia-compatible" builds (first link under "Multiple operating systems" on the wiki page)
