### ISSUE TITLE
"*** [cgemm_cr.obj] Error 1" in building on Windows 10

### ISSUE THREAD

**Issue by ShigeruHEMMI** [xianyi/OpenBLAS#1617]
Dear OpenBLAS developer, thank you for providing very excellent library.
I encounteerd a bug in building OpenBLAS-v0.3 on Windows10 pro 64bit.

My PC is Windows 10 Pro 64bit version 1803.
Am using gcc and gfortran of mingw-w64 labelled x86_64-8.1.0-release-posix-seh-rt_v6-rev0:
E:\>gcc --version
gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0

together with the make program of msys. My PATH order is mingw-w64 is first and msys ast.

My encountered output is the followings:

E:\Alibraries\xianyi-OpenBLAS-939452e>make -j 4
ln: creating symbolic link `libopenblas.a' to `libopenblas_haswellp-r0.3.0.dev.a': No such file or directory
Makefile:134: recipe for target `libs' failed
make: [libs] Error 1 (ignored)
make[1]: Entering directory `/e/Alibraries/xianyi-OpenBLAS-939452e/interface'
gcc -O2 -DMS_ABI -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=8 -DMAX_PARALLEL_NUMBER=1 -DASMNAME=saxpy -DASMFNAME=saxpy_ -DNAME=saxpy_ -DCNAME=saxpy -DCHAR_NAME=\"saxpy_\" -DCHAR_CNAME=\"saxpy\" -DNO_AFFINITY -I.. -I. -UDOUBLE  -UCOMPLEX -c axpy.c -o saxpy.obj

(many lines with no error snipped)

gcc -O2 -DMS_ABI -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=8 -DMAX_PARALLEL_NUMBER=1 -DASMNAME=cgemm_tr -DASMFNAME=cgemm_tr_ -DNAME=cgemm_tr_ -DCNAME=cgemm_tr -DCHAR_NAME=\"cgemm_tr_\" -DCHAR_CNAME=\"cgemm_tr\" -DNO_AFFINITY -I../.. -UDOUBLE  -DCOMPLEX  -c -UDOUBLE -DCOMPLEX -DTR gemm.c -o cgemm_tr.obj
gcc -O2 -DMS_ABI -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=8 -DMAX_PARALLEL_NUMBER=1 -DASMNAME=cgemm_cr -DASMFNAME=cgemm_cr_ -DNAME=cgemm_cr_ -DCNAME=cgemm_cr -DCHAR_NAME=\"cgemm_cr_\" -DCHAR_CNAME=\"cgemm_cr\" -DNO_AFFINITY -I../.. -UDOUBLE  -DCOMPLEX  -c -UDOUBLE -DCOMPLEX -DCR gemm.c -o cgemm_cr.obj
<command-line>: error: expected identifier or '(' before numeric constant
gcc -O2 -DMS_ABI -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=8 -DMAX_PARALLEL_NUMBER=1 -DASMNAME=cgemm_rn -DASMFNAME=cgemm_rn_ -DNAME=cgemm_rn_ -DCNAME=cgemm_rn -DCHAR_NAME=\"cgemm_rn_\" -DCHAR_CNAME=\"cgemm_rn\" -DNO_AFFINITY -I../.. -UDOUBLE  -DCOMPLEX  -c -UDOUBLE -DCOMPLEX -DRN gemm.c -o cgemm_rn.obj
gcc -O2 -DMS_ABI -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=8 -DMAX_PARALLEL_NUMBER=1 -DASMNAME=cgemm_rt -DASMFNAME=cgemm_rt_ -DNAME=cgemm_rt_ -DCNAME=cgemm_rt -DCHAR_NAME=\"cgemm_rt_\" -DCHAR_CNAME=\"cgemm_rt\" -DNO_AFFINITY -I../.. -UDOUBLE  -DCOMPLEX  -c -UDOUBLE -DCOMPLEX -DRT gemm.c -o cgemm_rt.obj
Makefile:365: recipe for target `cgemm_cr.obj' failed
make[1]: *** [cgemm_cr.obj] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/e/Alibraries/xianyi-OpenBLAS-939452e/driver/level3'
Makefile:134: recipe for target `libs' failed
make: *** [libs] Error 1

Best regards,

Shigeru Hemmi

**Comment by martin-frbg** [comment]
This is problem #1503, fixed by #1584 - recent Windows (and recent mingw) have added a system variable named "CR" that clashes with the -DCR used in the Makefile for compiling cgemm_cr.obj
You can copy the corrected file driver/level3/Makefile from #1584 by clicking "Files changed", then
the "View" button on the "diff" output that is shown, then right-click on the "Raw" button to save the
plaintext view of the file.
(Or pick a binary release from https://github.com/JuliaLinearAlgebra/OpenBLASBuilder/releases. Or download a zip file of the current development snapshot from the green "Clone or download" button on the "Code" tab.)

**Comment by ShigeruHEMMI** [comment]
Thanks for the immediate response but still problems.

(1) You wrote:
> You can copy the corrected file driver/level3/Makefile from #1584 by clicking "Files changed", then
> the "View" button on the "diff" output that is shown, then right-click on the "Raw" button to save the
> plaintext view of the file.

The new Makefile not working for me. 
There are some differences between original one and new one. For example, the first 2 lines differ:

TOPDIR = .
include ./Makefile.system

TOPDIR	= ../..
include ../../Makefile.system

And simple change for these lines not solves the problems (seems nothing building process starts).



(2) And you wrote:
> (Or pick a binary release from https://github.com/JuliaLinearAlgebra/OpenBLASBuilder/releases.

OpenBLAS.x86_64-w64-mingw32.tar.gz (0.3.0 release, Julia compatibility) downloaded and tested.
I ran into the link problems, small part of my output is
   undefined reference to `dcopy_'
   undefined reference to `dtrsm_'
   undefined reference to `dscal_'
   undefined reference to `dgemm_'
   undefined reference to `dswap_'
   undefined reference to `dtrsm_'
   (snipped)

That is, blas or lapack libraries not included in binary release.

Regards,

**Comment by martin-frbg** [comment]
Could be you overwrote the wrong Makefile ? The one from #1584 should start with TOPDIR set to ../.. and belongs in the driver/level3 folder. The one starting with TOPDIR set to "." (that is "current folder") is the toplevel Makefile (the one in /e/Alibraries/xianyi-OpenBLAS-939452e in your case) and should not change.
~~I did not expect the Julia-provided binary to have only the BLAS part of the library, sorry.~~

**Comment by martin-frbg** [comment]
Actually not sure where the `undefined reference` errors come from, seems more likely that your linker did not find the library ? (OpenBLAS binary release with no BLAS functions in it is simply not possible)

**Comment by ShigeruHEMMI** [comment]
(1)
I replaced the Makefile in xianyi-OpenBLAS-939452e/driver/level3 at your suggestion.
The make command generated 3 files
(libopenblas.dll, libopenblas.dll.a,libopenblas_haswellp-r0.3.0.dev.a),
and everything is OK, my problem completeley solved. Thank you very much.


(2)
My target application is MUMPS 5.1.2 (http://mumps.enseeiht.fr/).
For the combination(libopenblas.dll.a, libopenblas.dll), 
generated in xianyi-OpenBLAS-939452e, linking is OK and no problem.

On the other hand, for the combination(libopenblas64_.dll.a,
libopenblas64_.dll) extracted from OpenBLAS.x86_64-w64-mingw32.tar.gz 
(0.3.0 release, Julia compatibility), linking fails.
Note that I did not change file names provided.

My console output is:

(snip header output)
gfortran -o examples\c_example_SEQ.exe examples\c_example.o -Llibmingw-w64\SEQ -LE:\cygwin64\home\shigeru\ApetamagneticD\libmingw-w64_MUMPS_5.1.2 -LE:\cygwin64\home\shigeru\ApetamagneticD\libmingw-w64_MUMPS_5.1.2 -lzmumps_SEQ -ldmumps_SEQ -lmumps_common_SEQ -lpord -lmetis -lmpiseq -lopenblas64_.dll
libmingw-w64\SEQ/libdmumps_SEQ.a(dtools.o):dtools.F:(.text+0x48fc): undefined reference to `dcopy_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_driver.o):dfac_driver.F:(.text+0x4c5): undefined reference to `dcopy_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_driver.o):dfac_driver.F:(.text+0xa8a): undefined reference to `dcopy_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_driver.o):dfac_driver.F:(.text+0x10d8): undefined reference to `dcopy_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_driver.o):dfac_driver.F:(.text+0x11bd): undefined reference to `dcopy_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_driver.o):dfac_driver.F:(.text+0x1363): more undefined references to `dcopy_' follow
libmingw-w64\SEQ/libdmumps_SEQ.a(dooc_panel_piv.o):dooc_panel_piv.F:(.text+0x377): undefined reference to `dswap_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dmumps_ooc_buffer.o):dmumps_ooc_buffer.F:(.text+0x27be): undefined reference to `dcopy_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dmumps_ooc_buffer.o):dmumps_ooc_buffer.F:(.text+0x2ad7): undefined reference to `dcopy_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dmumps_ooc_buffer.o):dmumps_ooc_buffer.F:(.text+0x2c3e): undefined reference to `dcopy_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_front_aux.o):dfac_front_aux.F:(.text+0x6f7): undefined reference to `dtrsm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_front_aux.o):dfac_front_aux.F:(.text+0x8ef): undefined reference to `dcopy_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_front_aux.o):dfac_front_aux.F:(.text+0x905): undefined reference to `dscal_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_front_aux.o):dfac_front_aux.F:(.text+0xac2): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_front_aux.o):dfac_front_aux.F:(.text+0xcf4): undefined reference to `dcopy_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_front_aux.o):dfac_front_aux.F:(.text+0xd6f): undefined reference to `dcopy_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_front_aux.o):dfac_front_aux.F:(.text+0x101b): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_front_aux.o):dfac_front_aux.F:(.text+0x17a8): undefined reference to `dswap_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_front_aux.o):dfac_front_aux.F:(.text+0x1822): undefined reference to `dswap_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_front_aux.o):dfac_front_aux.F:(.text+0x18f9): undefined reference to `dswap_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_front_aux.o):dfac_front_aux.F:(.text+0x19bb): undefined reference to `dswap_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_front_aux.o):dfac_front_aux.F:(.text+0x2094): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_front_aux.o):dfac_front_aux.F:(.text+0x2278): undefined reference to `dtrsm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_front_aux.o):dfac_front_aux.F:(.text+0x250d): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_front_aux.o):dfac_front_aux.F:(.text+0x2aa0): undefined reference to `dcopy_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_front_aux.o):dfac_front_aux.F:(.text+0x2af9): undefined reference to `dcopy_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_front_aux.o):dfac_front_aux.F:(.text+0x7842): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_front_aux.o):dfac_front_aux.F:(.text+0x7b18): undefined reference to `dtrsm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_front_aux.o):dfac_front_aux.F:(.text+0x7bd0): undefined reference to `dtrsm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_front_aux.o):dfac_front_aux.F:(.text+0x7c8e): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_front_aux.o):dfac_front_aux.F:(.text+0x7f9e): undefined reference to `dtrsm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_front_aux.o):dfac_front_aux.F:(.text+0x8048): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_front_aux.o):dfac_front_aux.F:(.text+0x8249): undefined reference to `dtrsm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_front_aux.o):dfac_front_aux.F:(.text+0x8391): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_front_aux.o):dfac_front_aux.F:(.text+0x8589): undefined reference to `dtrsm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_front_aux.o):dfac_front_aux.F:(.text+0x8646): undefined reference to `dtrsm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_front_aux.o):dfac_front_aux.F:(.text+0x86e6): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_front_aux.o):dfac_front_aux.F:(.text+0x8fe8): undefined reference to `dger_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_front_type2_aux.o):dfac_front_type2_aux.F:(.text+0xeab): undefined reference to `dcopy_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_front_type2_aux.o):dfac_front_type2_aux.F:(.text+0xf01): undefined reference to `dcopy_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_process_blfac_slave.o):dfac_process_blfac_slave.F:(.text+0x254d): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_process_blocfacto_LDLT.o):dfac_process_blocfacto_LDLT.F:(.text+0x14a4): undefined reference to `dswap_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_process_blocfacto_LDLT.o):dfac_process_blocfacto_LDLT.F:(.text+0x166a): undefined reference to `dtrsm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_process_blocfacto_LDLT.o):dfac_process_blocfacto_LDLT.F:(.text+0x2899): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_process_blocfacto_LDLT.o):dfac_process_blocfacto_LDLT.F:(.text+0x465c): undefined reference to `dscal_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_process_blocfacto_LDLT.o):dfac_process_blocfacto_LDLT.F:(.text+0x4d21): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_process_blocfacto_LDLT.o):dfac_process_blocfacto_LDLT.F:(.text+0x4fb3): undefined reference to `dgemv_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_process_blocfacto_LDLT.o):dfac_process_blocfacto_LDLT.F:(.text+0x50be): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_process_blocfacto.o):dfac_process_blocfacto.F:(.text+0x1bcc): undefined reference to `dswap_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_process_blocfacto.o):dfac_process_blocfacto.F:(.text+0x1d4a): undefined reference to `dtrsm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_process_blocfacto.o):dfac_process_blocfacto.F:(.text+0x2780): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_process_blocfacto.o):dfac_process_blocfacto.F:(.text+0x4137): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_type3_symmetrize.o):dfac_type3_symmetrize.F:(.text+0xe6): undefined reference to `dcopy_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dmumps_iXamax.o):dmumps_iXamax.F:(.text+0x19): undefined reference to `idamax_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dsol_bwd.o):dsol_bwd.F:(.text+0x2975): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dsol_bwd.o):dsol_bwd.F:(.text+0x2abb): undefined reference to `dtrsm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dsol_bwd.o):dsol_bwd.F:(.text+0x4265): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dsol_bwd.o):dsol_bwd.F:(.text+0x4358): undefined reference to `dtrsm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dsol_bwd.o):dsol_bwd.F:(.text+0x447d): undefined reference to `dtrsm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dsol_bwd.o):dsol_bwd.F:(.text+0x468c): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dsol_bwd.o):dsol_bwd.F:(.text+0x5f22): undefined reference to `dtrsm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dsol_fwd_aux.o):dsol_fwd_aux.F:(.text+0x702): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dsol_fwd_aux.o):dsol_fwd_aux.F:(.text+0x1550): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dsol_fwd_aux.o):dsol_fwd_aux.F:(.text+0x4bdb): undefined reference to `dtrsm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dsol_fwd_aux.o):dsol_fwd_aux.F:(.text+0x5853): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dsol_fwd_aux.o):dsol_fwd_aux.F:(.text+0x5dea): undefined reference to `dtrsm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dsol_fwd_aux.o):dsol_fwd_aux.F:(.text+0x5ebb): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dsol_fwd_aux.o):dsol_fwd_aux.F:(.text+0x6094): undefined reference to `dtrsm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dsol_fwd_aux.o):dsol_fwd_aux.F:(.text+0x67f2): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dlr_core.o):dlr_core.F:(.text+0x18c0): undefined reference to `xerbla_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dlr_core.o):dlr_core.F:(.text+0x1990): undefined reference to `ilaenv_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dlr_core.o):dlr_core.F:(.text+0x19e3): undefined reference to `dnrm2_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dlr_core.o):dlr_core.F:(.text+0x1a3f): undefined reference to `dlamch_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dlr_core.o):dlr_core.F:(.text+0x1b76): undefined reference to `idamax_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dlr_core.o):dlr_core.F:(.text+0x1c0c): undefined reference to `dswap_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dlr_core.o):dlr_core.F:(.text+0x1ca5): undefined reference to `dswap_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dlr_core.o):dlr_core.F:(.text+0x1e1b): undefined reference to `dgemv_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dlr_core.o):dlr_core.F:(.text+0x1e9e): undefined reference to `dlarfg_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dlr_core.o):dlr_core.F:(.text+0x1fc0): undefined reference to `dgemv_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dlr_core.o):dlr_core.F:(.text+0x2123): undefined reference to `dgemv_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dlr_core.o):dlr_core.F:(.text+0x21e8): undefined reference to `dgemv_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dlr_core.o):dlr_core.F:(.text+0x22e8): undefined reference to `dgemv_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dlr_core.o):dlr_core.F:(.text+0x23cb): undefined reference to `dlarfg_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dlr_core.o):dlr_core.F:(.text+0x2619): undefined reference to `dnrm2_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dlr_core.o):dlr_core.F:(.text+0x281f): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dlr_core.o):dlr_core.F:(.text+0x3148): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dlr_core.o):dlr_core.F:(.text+0x33f4): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dlr_core.o):dlr_core.F:(.text+0x352d): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dlr_core.o):dlr_core.F:(.text+0x3ad6): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dlr_core.o):dlr_core.F:(.text+0x463a): more undefined references to `dgemm_' follow
libmingw-w64\SEQ/libdmumps_SEQ.a(dlr_core.o):dlr_core.F:(.text+0x6b79): undefined reference to `dorgqr_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dlr_core.o):dlr_core.F:(.text+0x6c9c): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_lr.o):dfac_lr.F:(.text+0x1286): undefined reference to `dormqr_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_lr.o):dfac_lr.F:(.text+0x4243): undefined reference to `dorgqr_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_lr.o):dfac_lr.F:(.text+0x4320): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_lr.o):dfac_lr.F:(.text+0x514f): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_lr.o):dfac_lr.F:(.text+0x610d): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_lr.o):dfac_lr.F:(.text+0x61f6): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_lr.o):dfac_lr.F:(.text+0x6498): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dfac_lr.o):dfac_lr.F:(.text+0x73b3): more undefined references to `dgemm_' follow
libmingw-w64\SEQ/libdmumps_SEQ.a(dsol_bwd_aux.o):dsol_bwd_aux.F:(.text+0x409a): undefined reference to `dtrsm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dsol_bwd_aux.o):dsol_bwd_aux.F:(.text+0x5a41): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dsol_bwd_aux.o):dsol_bwd_aux.F:(.text+0x5b22): undefined reference to `dtrsm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dsol_bwd_aux.o):dsol_bwd_aux.F:(.text+0x5ed7): undefined reference to `dgemm_'
libmingw-w64\SEQ/libdmumps_SEQ.a(dsol_bwd_aux.o):dsol_bwd_aux.F:(.text+0x7aab): undefined reference to `dgemv_'
collect2.exe: error: ld returned 1 exit status
scons: *** [c_example_SEQ.exe] Error 1
scons: building terminated because of errors.

Best regards,

**Comment by martin-frbg** [comment]
@andreasnoack @staticfloat any idea why your mingw-w64 binary would not link for him on Win10 ?

**Comment by staticfloat** [comment]
When building for ILP64, [we set `SYMBOLSUFFIX` to be equal to `64_`](https://github.com/JuliaLinearAlgebra/OpenBLASBuilder/blob/master/build_tarballs.jl#L20-L26); this means that the symbols get renamed to things like `dgemm_64_`.

**Comment by martin-frbg** [comment]
Ah, thanks, that would explain it. Guess I should mention this on the OpenBLAS wiki page.
