### ISSUE TITLE
Intel Core i7 rounding issues? 

### ISSUE THREAD

**Issue by ayounes-nviso** [xianyi/OpenBLAS#1627]
Hi there,

We have a C++ implementation of MTCNN (a CNN based Face Detector) which uses GEMM and GEMV functions for some layer. 
On some older Intel platforms or on Android (Arm32), we have the very same results using OpenBlas, BLIS or a pure CPU implementation.

But with a recent enough Intel platform we have slightly different results when using OpenBlas (latest master), about 2 pixels difference out of MTCNN.

The results are correct with:
* Intel Core i7 9xx (Nehalem Class Core i7), gcc-6
* ARM 32 bits (clang 6, Android NDK r17)

The results are slightly different with:
* Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz, gcc-6, 7 or 8
* Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz,  gcc-6

Any idea how we can fix this discrepancy?

Thanks in advance and best regards,
Abdel

**Comment by martin-frbg** [comment]
Latest "master" (stale ~ 0.2.20) or latest "develop" (where the action is) ? Latest stable (0.2.30) was released from its own branch.
Anyway, what you are seeing may also come from the use of FMA instructions on the more recent AVX2 capable CPUs (which may lead to different rounding than from separate multiply and add instructions). If you absolutely need identical results, you can try building with the NO_AVX2=1 option.

**Comment by abdelyounes** [comment]
Latest "develop" indeed, sorry for the confusion.

Yes, 2 pixels difference is important so we need identical results... so thanks, we will try the NO_AVX2=1 option; hope we will not loose some of the recent performance improvement...

Still, I find it disturbing that we get such important differences on different platforms... BLIS also supports AVX2 and doesn't have this effect on the same platform. I am willing to investigate more if you think there is something to fix here.

**Comment by martin-frbg** [comment]
Much of the recent improvement is in the multithreading code, so not cpu-specific. Worst case you could build with TARGET=NEHALEM to force it to use the Nehalem code on the more modern systems (NO_AVX2 will build for Sandybridge I think). It could certainly be that you hit a bug somewhere in the Haswell kernels, I hope tracing this to individual BLAS functions called by your code is not too hard.

**Comment by abdelyounes** [comment]
Thanks, we will try to investigate more.

**Comment by abdelyounes** [comment]
As a first step I can confirm that using NO_AVX2 fixes our issue. We will report back here if we have any outcome from the investigation.

**Comment by martin-frbg** [comment]
You could try reverting https://github.com/xianyi/OpenBLAS/pull/1482 - the Haswell microkernel for DAXPY has been under suspicion before, but the circumstances were a bit too involved to justify retiring it (some discussion in #1332)

**Comment by fenrus75** [comment]
Also note that FMA makes the result more accurate (e.g. closer to what you would get if you had infinite precision) due to less rounding.

**Comment by martin-frbg** [comment]
Probably does not help if one needs identical rather than perfect results across a range of platforms. And unfortunately my assembler skills do not allow me to exclude a more-or-less subtle bug in any of the AVX2-enabled microkernels - a bug that may not even be related to the use of FMA itself. (DAXPY just happens to be one that came up recently, though the test case from #1332 contained an extreme case of error-propagation and feedback)

**Comment by fenrus75** [comment]
it's unfortunate that these kernels are written in ASM for sure;
I tend to develop this stuff now in C (with intrinsics for the vector bits)
and then port the disassembly to openblas ;-)

**Comment by martin-frbg** [comment]
@abdelyounes any news on this ?

**Comment by ayounes-nviso** [comment]
@martin-frbg Sorry about that, I did not manage to find the time to do that.

But the good news is that with latest develop branch (8440a4cb1a) and *without* setting NO_AVX2 the issue is not present anymore!

I guess this is due to the recent porting of some kernels to C intrinsics?

In any case, I think you can close this issue now.

Thanks a lot for your support and this fix!
