### ISSUE TITLE
Is cmake aleady useful on other platforms than MSVC?

### ISSUE THREAD

**Issue by emmenlau** [xianyi/OpenBLAS#1633]
Dear Developers,
please forgive my naiive question: I found that building OpenBLAS on MSYS2 (with MinGW compiler) works, but requires a bit of fiddling to generate the definitions for the shared libraries (see https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-openblas/PKGBUILD). Its great that it works, but it seems a bit fragile right now.

But then I am happily surprised you also provide `cmake` for a simplified MSVC build! Now I am wondering if cmake is limited to MSVC, or can I build OpenBLAS with cmake on MSYS2 (or other MinGW), MacOSX, Linux? Are you planning to extend cmake support to more platforms?

**Comment by martin-frbg** [comment]
It is expected to work on at least Linux since PR #1279 , not sure about OSX.

**Comment by emmenlau** [comment]
Great, thanks a lot for this feedback. Then I will give it a try on MSVC with nmake, MSYS2, Linux and MacOSX, and report back what I find!

**Comment by xsacha** [comment]
I added this support and I am using it for Android (armv7, arm64-v8a), iOS (armv7 + arm64-v8a), Mac OS, Linux (x64) and MSVC.
I have not tested msys2.

It builds, compiles and runs but I have rolled back to 0.2.20 for an unrelated bug (infinite loop happening).

**Comment by martin-frbg** [comment]
@xsacha thanks for the clarification (and tests).  Infinite loop where ?

**Comment by xsacha** [comment]
Not sure exactly. Didn't bother tracking it down. It happens when using dlib to generate a DNN feature.
The CPU just sits there at 100% forever on 0.3.0 so I rolled back to 0.2.20.

Not sure if it's related to the CMake build either because in 0.2.20 I didn't build with CMake.

**Comment by martin-frbg** [comment]
If you suspect it could be related to threading you could try the current develop branch.
