### ISSUE TITLE
cblas_i*amin is not declared in cblas.h

### ISSUE THREAD

**Issue by zhuhaow** [xianyi/OpenBLAS#1637]
This is implemented but not declared in `cblas.h`. `cblas_i*amax` is declared, however.

Is that an error or there is some reason that `cblas_i*amin` is not working?

**Comment by martin-frbg** [comment]
Most probably an error (or oversight) as this is not a standard BLAS function (so comparison to the cblas.h from the netlib reference implementation would not make it obvious that it is missing). But it is 
more than just the header entry that is missing, the `cblas_i*min` interfaces also do not get built by inteface/Makefile although the BLAS `i*min` interfaces do. (Not sure about cmake, seems they are present there). I'll prepare a PR.
