### ISSUE TITLE
Return 0 when call openblas

### ISSUE THREAD

**Issue by TianBinyu** [xianyi/OpenBLAS#1640]
Now we want to porting openblas to Tizen platform.
I have finished to build the libopenblas_armv7-r0.3.1.dev.a in Tizen platform, but when i call the api of blas, it return 0, for example:
	int dim = 2;
	float a[2] = {1.0,2.0};
	float b[2]={1.0,1.0};
	printf ("%f\n",cblas_sdot(dim, a, 1, b, 0));

it return 3.000000 in my linux openblas.
But when i run it in Tizen openblas, it return 0.000000.
I have attached my build log, can you help me to check this issue?Thank you very much~
[openblas-build.txt](https://github.com/xianyi/OpenBLAS/files/2130557/openblas-build.txt)

**Comment by TianBinyu** [comment]
build cmd:
make TARGET=ARMV7

**Comment by TianBinyu** [comment]
the build log is as follow:

cc -O2 -DMAX_STACK_ALLOC=2048 -marm -Wall -DF_INTERFACE_GFORT -fPIC -DNO_WARMUP -DMAX_CPU_NUMBER=1 -DMAX_PARALLEL_NUMBER=1 -mfpu=vfpv3 -march=armv7-a -DASMNAME=cblas_sdot -DASMFNAME=cblas_sdot_ -DNAME=cblas_sdot_ -DCNAME=cblas_sdot -DCHAR_NAME=\"cblas_sdot_\" -DCHAR_CNAME=\"cblas_sdot\" -DNO_AFFINITY -I.. -I. -UDOUBLE  -UCOMPLEX -DCBLAS -c dot.c -o cblas_sdot.o


cc -c -O2 -DMAX_STACK_ALLOC=2048 -marm -Wall -DF_INTERFACE_GFORT -fPIC -DNO_WARMUP -DMAX_CPU_NUMBER=1 -DMAX_PARALLEL_NUMBER=1 -mfpu=vfpv3 -march=armv7-a -DASMNAME=sdot_k -DASMFNAME=sdot_k_ -DNAME=sdot_k_ -DCNAME=sdot_k -DCHAR_NAME=\"sdot_k_\" -DCHAR_CNAME=\"sdot_k\" -DNO_AFFINITY -I.. -UDOUBLE  -UCOMPLEX -UCOMPLEX -UDOUBLE ../kernel/arm/sdot_vfp.S -o sdot_k.o


Tizen is like new platform,it is  arm 32bit

**Comment by martin-frbg** [comment]
Build was done in qemu it seems. Which cpu did you tell it to emulate ? It showed test failures in CHERK and SAMAX that I did not see on real ARMV7 hardware, but not in SDOT. What hardware does your actual Tizen platform run, and - silly question I know - are you sure that your test linked against the libopenblas you just built, and not some other version of BLAS ?

**Comment by TianBinyu** [comment]
for the last question, sure ,i have modified openBLAS code and add logs, to do one simple test.
Only build two .o file and link it as one simple lib like this:
cc -O2 -DMAX_STACK_ALLOC=2048 -marm -Wall -DF_INTERFACE_GFORT -fPIC -DNO_WARMUP -DMAX_CPU_NUMBER=1 -DMAX_PARALLEL_NUMBER=1 -mfpu=vfpv3 -march=armv7-a -DASMNAME=cblas_sdot -DASMFNAME=cblas_sdot_ -DNAME=cblas_sdot_ -DCNAME=cblas_sdot -DCHAR_NAME=\"cblas_sdot_\" -DCHAR_CNAME=\"cblas_sdot\" -DNO_AFFINITY -I.. -I. -UDOUBLE  -UCOMPLEX -DCBLAS -c dot.c -o cblas_sdot.o


cc -c -O2 -DMAX_STACK_ALLOC=2048 -marm -Wall -DF_INTERFACE_GFORT -fPIC -DNO_WARMUP -DMAX_CPU_NUMBER=1 -DMAX_PARALLEL_NUMBER=1 -mfpu=vfpv3 -march=armv7-a -DASMNAME=sdot_k -DASMFNAME=sdot_k_ -DNAME=sdot_k_ -DCNAME=sdot_k -DCHAR_NAME=\"sdot_k_\" -DCHAR_CNAME=\"sdot_k\" -DNO_AFFINITY -I.. -UDOUBLE  -UCOMPLEX -UCOMPLEX -UDOUBLE ../kernel/arm/sdot_vfp.S -o sdot_k.o


ar  -ru libopenblas_haswellp-r0.3.1.dev.a cblas_sdot.o  ../kernel/sdot_k.o

ranlib  libopenblas_haswellp-r0.3.1.dev.a

Now libopenblas_haswellp-r0.3.1.dev.a only include cblas_sdot.o  ../kernel/sdot_k.o
so it can offer this api:  cblas_sdot
after that ,i build one simple test app, when it run in linux, it can print the right answer.
When i run it in tizen, it print 0.0000.

Build in linux :  
cc -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=8 -DMAX_PARALLEL_NUMBER=1 -DASMNAME=cblas_sdot -DASMFNAME=cblas_sdot_ -DNAME=cblas_sdot_ -DCNAME=cblas_sdot -DCHAR_NAME=\"cblas_sdot_\" -DCHAR_CNAME=\"cblas_sdot\" -DNO_AFFINITY -I.. -I. -UDOUBLE  -UCOMPLEX -DCBLAS -c dot.c -o cblas_sdot.o


cc -c -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=8 -DMAX_PARALLEL_NUMBER=1 -DASMNAME=sdot_k -DASMFNAME=sdot_k_ -DNAME=sdot_k_ -DCNAME=sdot_k -DCHAR_NAME=\"sdot_k_\" -DCHAR_CNAME=\"sdot_k\" -DNO_AFFINITY -I.. -UDOUBLE  -UCOMPLEX -UCOMPLEX -UDOUBLE ../kernel/x86_64/sdot.c -o sdot_k.o


ar  -ru libopenblas_haswellp-r0.3.1.dev.a cblas_sdot.o  ../kernel/sdot_k.o

ranlib  libopenblas_haswellp-r0.3.1.dev.a

i think it is same build steps.

One more question, when i build it in Tizen, it looks to make the .o  with this:
../kernel/arm/sdot_vfp.S -o sdot_k.o
and in sdot_vfp.S, there is no API like CNAME, so i think maybe this api "sdot_k"  is missed?
If it select the right file to build sdot_k.o?

**Comment by martin-frbg** [comment]
You could try running `nm` on your libopenblas.a to check that sdot_k is defined, but I guess your minimalistic libopenblas.a should probably work. (At least I am not aware that the build process for ARMV7 is fundamentally different from x86_64). Perhaps try using the generic C implementation from arm/dot.c instead of sdot_vfp.S to build sdot_k.o in case there is something special with the vfp support in your target cpu. (In the normal build process, this is selected in KERNEL.ARMV5 (which is indirectly included in KERNEL.ARMV7 and overriden by the `SDOTKERNEL=sdot_vfp.S` line there).

**Comment by TianBinyu** [comment]
yes
when i do not use .S file, it works well:
-mfpu=vfpv3 ../kernel/arm/sdot_vfp.S
how can i disable this in build config?

**Comment by martin-frbg** [comment]
Change (or just comment out) that line in kernel/arm/KERNEL.ARMV7 (and possibly the lines for DDOTKERNEL etc as well, depending on what further tests with cblas_ddot, cdot, zdot show). Or build for TARGET=ARMV5 if you want to avoid the assembly kernels completely for now.

**Comment by TianBinyu** [comment]
but our platform is armv7, i am not sure it can work if i use target=armv5 ..

**Comment by martin-frbg** [comment]
"ARMV5" for OpenBLAS mostly means "use the generic C kernels everywhere", which may still be reasonably fast if your compiler is good. But you are right that there are also some differences in the block sizes chosen for loop unrolling in param.h. So for now just set SDOTKERNEL=dot.c in KERNEL.ARMV7 (or comment out the line that sets it to dot_vfp.S in KERNEL.ARMV6). If you find other problems you can always look up in KERNEL.ARMV5 what the non-assembly version is named.

(Maybe there is a bug in the current dot_vfp.S that just happens to be harmless on the Cortex processors, or the cpu in your Tizen box needs an additional register save/restore around vfp calls 
that is not necessary on other hardware)

**Comment by TianBinyu** [comment]
Dear martin-frbg 
Thank you very much~
i will have a try and tell your the result~

**Comment by martin-frbg** [comment]
Is there any hardware info available for what you are targeting ? All I seem to find are the artik boards that appear to have regular CortexA7 or A9 cpus.

**Comment by TianBinyu** [comment]
now the LUX device is locked in our company, i will tell you in 6/26, because tomorrow i need to go to hospital~
Thank you

**Comment by TianBinyu** [comment]
@martin-frbg 
This is our device info:
bash-3.2#  cat /proc/cpuinfo
processor       : 0
BogoMIPS        : 52.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 1
BogoMIPS        : 52.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 2
BogoMIPS        : 52.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 3
BogoMIPS        : 52.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 4
BogoMIPS        : 52.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 5
BogoMIPS        : 52.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 6
BogoMIPS        : 52.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd09
CPU revision    : 2

processor       : 7
BogoMIPS        : 52.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd09
CPU revision    : 2

Hardware        : Lux
Revision        : 0003
Serial          : 52006d9bb267a43f

...
 OpenBLAS build complete. (BLAS CBLAS LAPACK LAPACKE)

  OS               ... Linux
  Architecture     ... arm
  BINARY           ... 32bit
  C compiler       ... GCC  (command line : cc)
  Fortran compiler ... GFORTRAN  (command line : gfortran)
  Library Name     ... libopenblas_armv7-r0.3.1.dev.a (Single threaded)


if you want to know other information?

**Comment by martin-frbg** [comment]
Seems your cpu does not offer vfp support (at least as far as the linux kernel is concerned) ? The "CPU architecture: 8" on the other hand makes me wonder if this is actually a 64bit, ARMV8 architecture.

**Comment by TianBinyu** [comment]
No, it is a 32bit, ARMV7 architecture i think~  :)

**Comment by martin-frbg** [comment]
Seems the sdot_vfp.S is broken, I see the same wrong result now on a Cortex-A17. @ashwinyes, can you help here ? Perhaps it is simply not returning the result in the expected register(s) since the addition of softfp support.

**Comment by ashwinyes** [comment]
CPU part : 0xd09   --> This is Cortex-A73 which is ARMv8
http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.100048_0002_04_en/jfa1406793219596.html

You can also look at features which contains asimd which is a ARMv8 feature and architecture is 8 which indicates Aarch64.

But having said that, Cortex A73 can run 32-bit ARM code. 

Can you try building. Do a clean build.
make TARGET=ARMV7 ARM_SOFTFP_ABI=1

**Comment by ashwinyes** [comment]
Also can you check whether "__ARM_PCS_VFP" is present in the default defines in your compiler.

$CC -dM -E - < /dev/null  | grep __ARM_PCS_VFP

**Comment by martin-frbg** [comment]
Just as an aside, on my A17 that also shows the problem,  __ARM_PCS_VFP is defined, and building with ARM_SOFTFP_ABI=1 is not possible with the linaro default gcc (missing stubs-soft.h). Seems I still have not grasped the various fp modes (this is an asus tinkerboard, so compilation runs locally in linux)

**Comment by ashwinyes** [comment]
If __ARM_PCS_VFP is defined, it means it is using hard fp ABI. You should not use ARM_SOFTFP_ABI=1 in this case. 

In **hardfp ABI**, floating point arguments and floating point returns are done via **floating point registers/stack**.
In **softfp/soft ABI,** floating point arguments and floating point returns are done via **integer registers/stack.**

OpenBLAS implementations were originally written for hard float ABI.

In the support added for softfp, we check whether it is using softfp or hardfp ABI using the __ARM_PCS_VFP define. If it is using softfp (__ARM_PCS_VFP is not defined), then the arguments from integer registers/stack are moved to the appropriate floating point registers as expected by the implementation. Also some adjustments are done to the positions of the arguments on the stack as it will change between hard and softfp.  For example:  In rot_vfp.S, float arguments (from stack) are moved to floating point registers.
```
#if !defined(__ARM_PCS_VFP)
#if !defined(DOUBLE)
	vldr	s0, OLD_C
	vldr	s1, OLD_S
#else
	vldr	d0, OLD_C
	vldr	d1, OLD_S
#endif
#endif
```


While returning the results are moved back to integer registers. Example: In sdot_vfp.S, return value is moved to integer register.
```
#if !defined(__ARM_PCS_VFP)
#if defined(DSDOT)
	vmov	r0, r1, d0
#else
	vmov	r0, s0
#endif
#endif
```

For hardfp case, ideally there is nothing that should change with the commits for softfp. So, if there is any problem, it should have been there before the commits. But I may have overlooked something while implementing. I dont have a hardware to test this unfortunately.

**Comment by martin-frbg** [comment]
Thanks for the detailed explanation. The problem does indeed appear to be much older, maybe even original libGoto. And it is probably "only" about lacking proper support for the special case of INCY being zero (or actually taking a too early exit in that case probably - there were a few similar cases  that got exposed recently by the re-introduction of the utests).

**Comment by martin-frbg** [comment]
Indeed it appears to be the early exit to `sdot_kernel_L999` after the `cmp INC_Y, #0` that is causing this (same over-optimization in ddot, and almost certainly c/zdot as well). And exiting on INC_X==0 is probably just as wrong.
Seems to have gone unnoticed for years (but is not from original libGoto2, as it did not yet support ARM).
