### ISSUE TITLE
OpenPower nonvolatile registers not saved/restored in zdot kernel (OpenBLAS 0.2.19)

### ISSUE THREAD

**Issue by schweitzpgi** [xianyi/OpenBLAS#1649]
Unfortunately, it appears like the OpenPower assembly code in zdot_microk_power8.c is also using the nonvolatile vector-scalar registers without saving and restoring them properly.

This is a similar issue to the one found here: https://github.com/xianyi/OpenBLAS/issues/1263.

Here is a snippet selection that shows the problem.

0000000000000240 <zdot_kernel_8>:
 240:   78 1b 67 7c     mr      r7,r3
 244:   10 00 00 39     li      r8,16
 248:   20 00 20 39     li      r9,32
...
 28c:   99 26 49 7d     lxvd2x  vs42,r9,r4
 290:   99 2e 49 7e     lxvd2x  vs50,r9,r5
 294:   99 26 6a 7d     lxvd2x  vs43,r10,r4
 298:   99 2e 6a 7e     lxvd2x  vs51,r10,r5 
 29c:   57 82 90 f2     xxswapd vs52,vs48  <-- writes to nonvolatile register, but not saved
 2a0:   57 8a b1 f2     xxswapd vs53,vs49  <-- "
 2a4:   57 92 d2 f2     xxswapd vs54,vs50  <-- "
 2a8:   57 9a f3 f2     xxswapd vs55,vs51  <-- ... clobbers up to and including vs63
...

**Comment by quickwritereader** [comment]
thanks I will check that

**Comment by quickwritereader** [comment]
strange that code fixed by Alan Modra himself. I checked source code 

```
       "xxswapd		0, 48		\n\t"	// y0_i, y0_r
       "xxswapd		1, 49		\n\t"	// y1_i, y1_r
       "xxswapd		2, 50		\n\t"	// y2_i, y2_r
       "xxswapd		3, 51		\n\t"	// y3_i, y3_r
```
it is explicitly provided and clobbered later.

**Comment by quickwritereader** [comment]
please check if you are using latest. because neither on source code nor on machine I could find.
thanks. still I will recheck whenever I am  free

**Comment by martin-frbg** [comment]
Are you really still at 0.2.19 as suggested by the title of this issue ? These bugs were fixed in 0.2.20 almost a year ago, please update to current 0.3.0 (or hopefully 0.3.1 next week).

**Comment by schweitzpgi** [comment]
I buried the version info in the title. We're using 0.2.19. We'll check the latest code though. Thank you.

**Comment by martin-frbg** [comment]
Please do. While the latest code is certainly not bug-free, at least those bugs will be fresher than any you have now. Please reopen if this problem resurfaces with 0.3, or create a new issue for any new catches.
