### ISSUE TITLE
gotoblas_init and static linking

### ISSUE THREAD

**Issue by sandwichmaker** [xianyi/OpenBLAS#1652]
I would like to understand the correct behaviour/use of gotoblas_init(). 

My understanding is  that gotoblas_init is annotated with __attribute__((constructor)). So

1. When one builds openblas as a shared library, it gets called at the time the shared library is loaded, so the user has no need to call gotoblas_init() explicitly. 

2. But this mechanism does not work when one builds a static version of the library and links to it, and in this case the user is expected to call gotoblas_init() explicit before calling any other function in OpenBLAS.

Is this correct? or is there a way of using the static library without calling gotoblas_init() explicitly.

**Comment by martin-frbg** [comment]
There is no need to call gotoblas_init() explicitly even when linking to the static version (see for example the executables in the "test" and "ctest" directories). As to why, I can only offer the naive assumption that this must be a fundamental difference between static and dynamic libraries, the constructor function being required only for the latter.

**Comment by sandwichmaker** [comment]
@martin-frbg that does not line up with my experience. Calling dscal_ leads to a crash (with a dynamic build) because the function table pointer gotoblas* is NULL. But things work fine when calling xGEMM.

I am not entirely clear as to what is going on, which is why I am asking (it is possible something is broken in the way we are building, we use bazel).  But I will work on creating a reproduction which works the existing build.

**Comment by martin-frbg** [comment]
Maybe the issue is not gotoblas_init as such, but gotoblas_dynamic_init ?

**Comment by sandwichmaker** [comment]
Well, gotoblas_init() is supposed to call gotoblas_dynamic_init(), and it seems to be the case that gotoblas_init() is not getting called in the statically linked case in my build.

Let me investigate further and come back to this thread.

**Comment by martin-frbg** [comment]
I cannot reproduce your issue so far (with a trivial fortran program that calls dscal, statically linked against libgotoblas.a from a DYNAMIC_ARCH=1 build) ?

**Comment by sandwichmaker** [comment]
@martin-frbg looks like like it is an instance of 
https://isocpp.org/wiki/faq/ctors#static-init-order on our end. Still investigating, will report back.

**Comment by oon3m0oo** [comment]
#1661 should resolve this by checking gotoblas before every call.

**Comment by sandwichmaker** [comment]
I am going to close this, as this appears to be an issue with our build and not openblas.
