### ISSUE TITLE
LAPACK and iOS compilation issues

### ISSUE THREAD

**Issue by glacius3000** [xianyi/OpenBLAS#1658]
Hi,

I'm able to follow the instructions [here](https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-iPhone-iOS-(ARMv8)) and can get OpenBLAS to compile. However, the LAPACK portion fails with the following error.

>OpenBLAS: Detecting fortran compiler failed. Cannot compile LAPACK. Only compile BLAS.

Is this expected behavior when compiling for iOS?
If it isn't expected behavior does anyone know how I can get around this?

thanks

**Comment by martin-frbg** [comment]
The `NOFORTRAN=1` on the `make` command line (last line of the command file that the instruction tells you to create) should suppress the search for a fortran compiler. (It seems XCODE has only the C/C++ compiler, clang). Our Travis checks use `brew install gcc` to install the GNU compiler collection from "homebrew" for building on OSX, not sure if this would also work for iOS.

**Comment by brada4** [comment]
You can try walking unknown paths and build flang compiler for xcode llvm code generator... But as it stands presently - there is no fortran compiler targeting iOS (there is intel C compiler targeting OSX)

**Comment by glacius3000** [comment]
I think I'm gonna try replacing the LAPACK libraries with the Apple LAPACK libraries. I was able to get the project to build this way now lets see if it works.

**Comment by brada4** [comment]
Yes, you can use apple accelerate framework on iOS, once there is good fortran compiler you can try OpenBLAS again. For now there is no easy chance.

**Comment by martin-frbg** [comment]
Almost all of OpenBLAS' LAPACK is identical to the non-optimized reference implementation from netlib anyway. So it could be that the combination with Apple LAPACK is even faster than a pure OpenBLAS BLAS+LAPACK.
