### ISSUE TITLE
Linking problem on RHEL 6

### ISSUE THREAD

**Issue by susilehtola** [xianyi/OpenBLAS#1659]
I'm updating the OpenBLAS package in Fedora and Fedora EPEL from 0.3.0 to 0.3.1. The packages are built with ```TARGET=CORE2 NO_AVX2=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER=1```. The link phase fails with
```
dynamic.c: In function 'get_coretype':
dynamic.c:513: error: 'gotblas_SANDYBRIDGE' undeclared (first use in this function)
dynamic.c:513: error: (Each undeclared identifier is reported only once
dynamic.c:513: error: for each function it appears in.)
make[1]: *** [dynamic.o] Error 1
```
Full x86_64 build log at
https://kojipkgs.fedoraproject.org//work/tasks/8058/27978058/build.log

**Comment by martin-frbg** [comment]
Meh. Looks like a "nice" typo in the fallback section of the CannonLake detection code, triggered by your setting NO_AVX2=1. (Line 513 of driver/others/dynamic.c). So my second release seems to end as a blunder as well.

**Comment by susilehtola** [comment]
Thanks, #1660 fixes issue and packages have been built.
