### ISSUE TITLE
DGESVD gives incorrect result

### ISSUE THREAD

**Issue by vladimir-ch** [xianyi/OpenBLAS#1666]
Our Gonum test for Dgesvd has recently started to fail when using OpenBLAS as the underlying implementation. I've bisected it to 01440685379f11f158c5f612cf15fc279eb16c88. As a data point, out of the various test cases that we have it seems to fail only for the matrix sizes 300x600 and 600x300.

**Comment by martin-frbg** [comment]
Oh great. :-(
Could you check if this can be repaired by restoring the two instances of `&= 0` (lines 428 and 472) that supposedly were no better than the plain `=0` that replaced them in the PR ?

**Comment by sandwichmaker** [comment]
@oon3m0oo

**Comment by vladimir-ch** [comment]
Reverting that commit fixes it but just restoring the `&= 0` does not.

**Comment by martin-frbg** [comment]
Reverted now, thanks again for testing.

**Comment by oon3m0oo** [comment]
Interesting.  I wonder if it was the movement of the top block of code.  There didn't seem to be a dependency there, but I guess there was!

**Comment by ViralBShah** [comment]
Will there be a quick 0.3.2 with this hotfix?

**Comment by martin-frbg** [comment]
Depends on how quick you would want it to be - I am very busy this week, and I would also like to see at least #1673 resolved so that we do not end up with a new single-fix release every two weeks.

**Comment by ViralBShah** [comment]
Something in a couple of weeks would be great to line up with Julia 0.7. But otherwise we can always pick up the patches too.

**Comment by timokau** [comment]
I personally think there is nothing wrong with a patch release every two weeks. Better than having a lot of people re-discover the issue and spend time fixing it.

**Comment by martin-frbg** [comment]
Closing as 0.3.2 is released now.
