### ISSUE TITLE
Can't build openblas with the face-recognition.js node package on windows

### ISSUE THREAD

**Issue by thexiroy** [xianyi/OpenBLAS#1670]
Before anyone mentions, yes I have contacted the package creator: https://github.com/justadudewhohacks/face-recognition.js/issues/104#issuecomment-402958859 but I think my issue is related to openblas.

I have compiled openblas source (latest release) on windows using section 1 from the wiki: https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-in-Microsoft-Visual-Studio and added the openblas (lib & dll) to my system path. 

After I build the package with openblas I get a runtime error that a module could not be found. So I used dependency walker to see which dependencies are missing.
![openblas_flang](https://user-images.githubusercontent.com/12149840/42376734-8f4a4aaa-8120-11e8-86d8-7b551cc76dd9.png)
It seems that the FLANG.DLL is missing, I have no idea what this means or how to fix this.

Any insight would be welcome.

**Comment by thexiroy** [comment]
I have also tried building with the stable openblas version and the Windows binary but they give the same results.

**Comment by martin-frbg** [comment]
flang is the fortran compiler that you used to build the LAPACK part of OpenBLAS. I suspect FLANG.DLL is its runtime library, and you need to add its location to the system path as well. (If you are only ever going to use BLAS functions and no LAPACK, you can also build OpenBLAS with NOFORTRAN=1 to get rid of the fortran dependency)

**Comment by thexiroy** [comment]
Which configuration commands do I have to use to build it without LAPACK?
I just tried:
> cmake .. -G "Ninja" -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DCMAKE_Fortran_COMPILER=flang -DBUILD_WITHOUT_LAPACK=no -DNOFORTRAN=1 -DDYNAMIC_ARCH=ON -DCMAKE_BUILD_TYPE=Release

However this gave me errors: 
![openblas_linkerror](https://user-images.githubusercontent.com/12149840/42383778-91d7f05c-8138-11e8-99c6-04c303750057.png)
I also found LAPACK in the Anaconda prompt:
![openblas_linkerror_lapack](https://user-images.githubusercontent.com/12149840/42383868-dd93142c-8138-11e8-9413-10930b0f2210.png)

**Comment by brada4** [comment]
You can add just FC=FAKE parameter istead of dozen lapack & fortran parameters. btw real ones are in Makefile.rule.
And you need to clean build directory befor build with new parameters.

**Comment by martin-frbg** [comment]
I expect setting "BUILD_WITHOUT_LAPACK" to yes would be the cmake equivalent of NO_LAPACK=1 (or NOFORTRAN=1) in the GNU make context

**Comment by thexiroy** [comment]
I am not sure what I should specifically do, I am not used to compiling with cmake.  I tried this as well:
> cmake .. -G "Ninja" -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DFC=FAKE -DDYNAMIC_ARCH=ON -DCMAKE_BUILD_TYPE=Release

**Comment by martin-frbg** [comment]
That is probably another way of dealing with it, by forcing it to use a non-existing fortran compiler like brada4 suggested it should automatically disable the LAPACK part. Just make sure to start with a clean build directory so the linker does not pick up any fortran object files from your first attempt.

**Comment by thexiroy** [comment]
I have I got it working.

**Comment by brada4** [comment]
It was first choice against cross-build picking native gfortran. Sort of shorter to type too...
