### ISSUE TITLE
OpenBLAS does not properly support FreeBSD on POWER

### ISSUE THREAD

**Issue by chmeeedalf** [xianyi/OpenBLAS#1671]
The cpuid_power.c config generator only supports Linux, OS X, and AIX.  It does not support FreeBSD.  A simple addition would be to either return CPUTYPE_POWER4 for powerpc64 as the lowest common powerpc64 architecture for FreeBSD, or to use the mfpvr instruction (mfspr SPR_PVR) and check that result.

Currently it does end up defining, by happenstance, POWER4 for CPU type, but in one run it defines "CORE_\xf8!\xff\xd1|^H^B\xa6\xf8^A", as there is no valid core type.

**Comment by martin-frbg** [comment]
Pretty sure that file grew from what happened to work for whoever needed it. Do I take it that `mfpvr(SPR_PVR)` would work across all the currently supported platforms (and thus would be preferable to digging through /proc/cpuinfo even where that is available) ?

**Comment by chmeeedalf** [comment]
The mfpvr() function is in <machine/cpufunc.h>, but it can be done with inline asm of:

__asm __volatile("mfpvr %0" : "=r"(reg));

with 'reg' being the output value.  FreeBSD and Linux both emulate the mfpvr function, since the PVR is a privileged register.  I don't know if OS X or AIX emulate the instruction, so it may need to be guarded with #if defined(linux) || defined(__FreeBSD__).

**Comment by brada4** [comment]
Anything in `sysctl hw` like on x86_64 ?

**Comment by chmeeedalf** [comment]
FreeBSD does have "hw.model" sysctl.  On my POWER9 system hw.model is "IBM POWER9".  Currently valid values can be found at https://svnweb.freebsd.org/base/head/sys/powerpc/powerpc/cpu.c?revision=334260&view=markup#l109 (the strings in the model[] array).

**Comment by martin-frbg** [comment]
Would this work ?
```
#if defined(__FreeBSD__) || defined(__OpenBSD__) || defined(__DragonFly__)
int id;
id = __asm __volatile("mfpvr %0" : "=r"(id));
if (id == 0x4e) return CPUTYPE_POWER8; //POWER9
if (id == 0x4d || id == 0x4b) return CPUTYPE_POWER8;
if (id == 0x4a || id == 0x3f) return CPUTYPE_POWER6; // POWER7 
if (id == 0x3e) return CPUTYPE_POWER6;
if (id == 0x3a) return CPUTYPE_POWER5;
if (id == 0x35 || id == 0x38) return CPUTYPE_POWER4;
if (id == 0x40 || id == 0x41) return CPUTYPE_POWER3;
if (id == 0x39 || id == 0x3c || id == 0x44 || id == 0x45) return CPUTYPE_PPC970;
if (id == 0x70) return CPUTYPE_CELL;
if (id == 0x8003) return CPUTYPE_PPCG4;

return  CPUTYPE_UNKNOWN;
#endif
}
```

**Comment by chmeeedalf** [comment]
martin, thanks for creating that patch so quickly.  It would work with one minor change:  Need to right-shift 'id' by 16 bits.  The processor identifier is the upper 16 bits, the major/minor rev are the lower 16 bits.
