### ISSUE TITLE
openblas.net site still has download links to old 0.2.20 release

### ISSUE THREAD

**Issue by conradsnicta** [xianyi/OpenBLAS#1675]
The [OpenBLAS.net](http://www.openblas.net/) site still has links to the old release.

The .tar.gz and .zip download buttons are pointing to the outdated 0.2.20 release.

Many people use the OpenBLAS site as the canonical site, instead of the GitHub repo. It's easier to click on a download link instead of doing a git clone.

It might be an idea to remove the download buttons and instead point people directly to https://sourceforge.net/projects/openblas/files/

@xianyi @martin-frbg

**Comment by martin-frbg** [comment]
Known problem, but xianyi is the only one who has write access to the website (and the sourceforge repository - fortunately the release process is set up to upload source packages there automatically, but there is no way to update the windows binaries).
BTW the release page on github will also let you download a tar or zip archive (same as the "clone or download" button will provide a zip archive along with the URL for cloning), sourceforge is just nice to have as a backup.

**Comment by conradsnicta** [comment]
@martin-frbg - So what happened to @xianyi ?  From the commit logs, you appear to be the main OpenBLAS developer these days, with Xianyi pretty much absent. It looks like he should officially hand over all the reins to you.

**Comment by martin-frbg** [comment]
I have now received commit access to the repository that holds the web pages, and updated the site accordingly.
