### ISSUE TITLE
Openblas becomes single-thread when compiled with MPI

### ISSUE THREAD

**Issue by ZhangJunQCC** [xianyi/OpenBLAS#1676]
Hi everyone,

I am using Eigen with OpenBLAS as backend in my project. OpenBLAS was compiled in multi-thread mode. When using `g++ -fopenmp -O3` to link the program with OpenBLAS, everything is correct: a matrix is diagonalized using **8 CPU cores**. 

When I use `mpic++ -fopenmp -O3` to link the program with OpenBLAS, and run the program like `mpirun -np 8 foo.x`, each process does the diagonalization using only **1 CPU core**. Even using `mpirun -np 1 foo.x`,  the program will use only **1 CPU core**. 

Thus my question is, 

+ How to use multi-thread OpenBlas in a MPI program ? (Put aside the reasonability and efficiency of hybrid OpenMP/MPI)

Thanks! 
Jun

**Comment by martin-frbg** [comment]
Did you try setting OMP_NUM_THREADS ? I have never tried this combination myself, searching the entire github for "mpirun OpenMP" I found what looks to be very useful tips in https://github.com/SmileiPIC/Smilei/issues/36

**Comment by ZhangJunQCC** [comment]
Setting `OMP_NUM_THREADS ` or `OPENBLAS_NUM_THREADS`  does not work. Maybe `mpirun` overwrote some variables? I am not sure.

**Comment by brada4** [comment]
mpirun -np 100 -x OMP_NUM_THREADS=4

**Comment by ZhangJunQCC** [comment]
Neither `mpirun -np 100 -x OMP_NUM_THREADS=4` nor `mpirun -np 100 -x OPENBLAS_NUM_THREADS=4` works, unfortunately.

**Comment by martin-frbg** [comment]
Could be you also need to specify a -npernode value. How do you know it uses only one core ?
(This google hit : http://lammps.sandia.gov/threads/msg26152.html could be relevant)

**Comment by albandil** [comment]
Some MPI implementations automatically bind the launched processes (i.e. restrict the cores on which these can run, including their child processes/threads). I remember that I needed to use `--bind-to none` with Open MPI at some point when using OpenMP.
