### ISSUE TITLE
build OpenBLAS in Microsoft Visual Studio

### ISSUE THREAD

**Issue by rafaP** [xianyi/OpenBLAS#1679]
Hello,

I'm trying to build the OpenBlas to use with face-recognition.js, i'm doing all that is in the https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-in-Microsoft-Visual-Studio

but i get an error in this command:
cmake .. -G "Ninja" -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DCMAKE_Fortran_COMPILER=flang -DBUILD_WITHOUT_LAPACK=no -DNOFORTRAN=0 -DDYNAMIC_ARCH=ON -DCMAKE_BUILD_TYPE=Release

error output:
Run Build Command:"C:/Users/......./Miniconda2/Library/bin/ninja.exe" "cmTC_ec765"
    [1/2] Building C object CMakeFiles\cmTC_ec765.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_ec765.exe
    FAILED: cmTC_ec765.exe
    cmd.exe /C "cd . && C:\Users\......\Miniconda2\Library\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_ec765.dir --manifests  -- C:\Strawberry\c\bin\ld.exe /nologo CMakeFiles\cmTC_ec765.dir\testCCompiler.c.obj  /out:cmTC_ec765.exe /implib:cmTC_ec765.lib /pdb:cmTC_ec765.pdb /version:0.0  /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /foCMakeFiles\cmTC_ec765.dir/manifest.res CMakeFiles\cmTC_ec765.dir/manifest.rc" failed (exit code 0) with the following output:
    The system cannot find the file specified
    ninja: build stopped: subcommand failed.

  CMake will not be able to correctly generate this project.

**Comment by martin-frbg** [comment]
That looks like a problem with your installation of cmake or ninja - building testCCompiler.c.obj is not part of the OpenBLAS build process itself, so I assume it comes from the CMAKE macro to identify the C compiler. Is `clang-cl` in your search path for executables ?

**Comment by rafaP** [comment]
i'm using Miniconda2 it makes diference?

**Comment by martin-frbg** [comment]
Actually I have no idea, but I doubt it. Perhaps try setting -DCMAKE_C_COMPILER to the full path leading to clang-cl.exe ?

**Comment by martin-frbg** [comment]
Oh, and make sure that rc.exe is in your path as well - that seems to have been the problem in this old forum thread here https://cmake.org/pipermail/cmake/2016-March/063028.html

**Comment by rafaP** [comment]
It's working with the version 3

and the release from here: https://github.com/xianyi/OpenBLAS/releases
now the last line of the build: cmake --build . --config Release

**Comment by martin-frbg** [comment]
So it is working now, and you had the trouble only with 0.2.20 or some other old version ? (I know the openblas.net webpage needs updating, but I cannot change it.)

**Comment by rafaP** [comment]
yes it compile. but i only got the openblas.dll and i need the libopenblas.dll too

**Comment by martin-frbg** [comment]
If I understand your question correctly (not a windows user normally), you may need to re-run the cmake with -DBUILD_SHARED_LIBS (see discussion in #1362)

**Comment by rafaP** [comment]
When i try to do the build with shared libs it give me this error:


cmake -DBUILD_SHARED_LIBS .. && cmake --build . --config Release
Parse error in command line argument: -DBUILD_SHARED_LIBS
Should be: VAR:type=value
CMake Error: No cmake script provided.
CMake Error: Problem processing arguments. Aborting.

-----------------------------
I need to do a cmake file? i never used cmake files or do one.

**Comment by martin-frbg** [comment]
Try -DBUILD_SHARED_LIBS=ON

**Comment by rafaP** [comment]
I got the same result: 

![image](https://user-images.githubusercontent.com/3018248/42645463-fd35512a-85f5-11e8-83c6-05bc03174fed.png)

**Comment by brada4** [comment]
You can rename openblas.dll into libopenblas.dll
Actually few versions ago it was named like that

**Comment by rafaP** [comment]
Yes. But now i get a error of dependecy of Flang.dll and Flangrti.dll
When i try to run the face-recognition js with the Openblas

![image](https://user-images.githubusercontent.com/3018248/42930973-5a36b27a-8b36-11e8-9cb2-ab2607a95e89.png)

**Comment by martin-frbg** [comment]
These are probably the runtime libraries for fortran (most of the LAPACK part of OpenBLAS is written in FORTRAN, as it is just a copy of the "netlib" reference implementation).

**Comment by rafaP** [comment]
So i can i fix it?

**Comment by martin-frbg** [comment]
I guess it should work if you copy these two dlls from your clang/flang installation to where you put the openblas dll. (If you know that the face recognition code only uses BLAS and never needs any of the LAPACK functions, you can also build OpenBLAS without the parts written in fortran. Either specify -DNOFORTRAN=1 or define FC to some non-existing program so that cmake does not find the flang
fortran compiler anymore.)

**Comment by rafaP** [comment]
I think it need the LAPACK as well.

**Comment by martin-frbg** [comment]
OK, so building without fortran is out of the question. Does your code work if you copy flang.dll and flangrti.dll ?

**Comment by rafaP** [comment]
where i can get those?

**Comment by brada4** [comment]
Somewhere in lib directory near to flang.exe
It is sort of msvcrt2018, but flang+fortran way.

**Comment by rafaP** [comment]
It doesn't work, it keep asking for more files if i use the dependency walker on the .node file

**Comment by martin-frbg** [comment]
What other files does it need ? Possibly flang.dll depends on something else (libomp.dll from openmp perhaps ?)

**Comment by rafaP** [comment]
It works if i add all the files in the folder
![image](https://user-images.githubusercontent.com/3018248/42945805-3b8843f4-8b61-11e8-9164-e14ba73cb975.png)
