### ISSUE TITLE
Creating new layer Caffe，*** Aborted at 1531846768 (unix time) try "date -d @1531846768" if you are using GNU date ***

### ISSUE THREAD

**Issue by ineslyl** [xianyi/OpenBLAS#1685]
Hello, i got the problem when i creat the new layer Caffe: 

I0717 16:59:28.236726 12947 layer_factory.hpp:77] Creating layer input-data
*** Aborted at 1531846768 (unix time) try "date -d @1531846768" if you are using GNU date ***
PC: @     0x7f8e06acbfaf dgetrf_
*** SIGSEGV (@0x280) received by PID 12947 (TID 0x7f8e8ebc4a40) from PID 640; stack trace: ***
    @     0x7f8e75dab6d0 (unknown)
    @     0x7f8e06acbfaf dgetrf_
    @     0x7f8e69ec6b45 f2py_rout__flapack_dgetrf
    @     0x7f8e76b37a63 (unknown)
    @     0x7f8e76bcc236 (unknown)
    @     0x7f8e76bd303d (unknown)
    @     0x7f8e76bd053c (unknown)

The problem might be dgetrf of OpenBLAS, i'm not sure....
Someone can help? :)

Thx

**Comment by martin-frbg** [comment]
Can you provide more details of what you are trying to do, and which version of OpenBLAS you are using ?

**Comment by ineslyl** [comment]
I don't know the exact version of OpenBLAS. I just download OpenBLAS by the command:  git clone https://github.com/xianyi/OpenBLAS.git
And follow README.md step by step

**Comment by martin-frbg** [comment]
Alright, that would be a snapshot of the current "develop" branch. (Which should be good.) 
What is your CPU and operating system ? (Unfortunately I do not know caffe, so I have no idea what "creating a new layer" involves there)

**Comment by brada4** [comment]
Since 'creating layers' involves C++ coding, could you, please, make backtrace with module names and function names, and a short snipplet of your code to repeat the issue?

**Comment by ineslyl** [comment]
I think that the module name and the function name are corresponding with the information of layer.
For creating a layer, i wrote <inputdata.py>, like :

class InputData(caffe.Layer): 
   def setup:
       ......

And i add this in "NET" :

layer {
  name: "input-data"
  type: "Python"
  top: "data"
  top: "label"
  python_param {
    module: "inputdata"
    layer: "InputData"
    param_str: ""
  }
}

**Comment by brada4** [comment]
You need to run your code in gdb and generate backtrace yielding library where dgetrf_ is loaded from, and by chance arguments passed to it.
Usually it involves installing something like numpy-dbg or numpy-debug package

Sorting current backtrace by offsets yields that getrf and unresolved function called by it (should be getrf_single or getrf_parallel if OpenBLAS is used) are from different library files.
``
@ 0x7f8e75dab6d0 (unknown)
@ 0x7f8e06acbfaf dgetrf_
``

**Comment by brada4** [comment]
Please check blas version:
```
>>> import numpy
>>> numpy.__config__.show()
```
My ubuntu (native dstribution packages) says:
```
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/lib64']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/lib64']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/lib64']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
blis_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/lib64']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
lapack_mkl_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
```

**Comment by brada4** [comment]
Did you get gdb showing symbols?
Present backtrace is not convincing, next call out from dgetrf is any of DGEMM, DGETF2, DLASWP, DTRSM, XERBLA and you must implicate one of them somehow
