### ISSUE TITLE
Does NO_WARMUP do anything?

### ISSUE THREAD

**Issue by TiborGY** [xianyi/OpenBLAS#1686]
I did a quick search in the repo, and found no actual code where NO_WARMUP does anything at all.
It seems to be a vestigial option in Makefile.rule.

Am I missing something?

**Comment by martin-frbg** [comment]
The memory allocation code in driver/others/memory.c is where it is used (mostly in conjunction with Linux)

**Comment by TiborGY** [comment]
Ah, OK, found it. Turns out the github search only shows a couple matches per file.
Thanks.
