### ISSUE TITLE
zsbmv & csbmv

### ISSUE THREAD

**Issue by sandwichmaker** [xianyi/OpenBLAS#1689]
I am using the full fortran LAPACK distribution and not the LAPACK distribution that ships with OpenBLAS.

So when  trying to build the LAPACK test suite (3.5.0) and linking it to OpenBLAS, there is a linking error because zsbmv and csbmv which are defined in TESTING/LIN and TESTING/EIG and that conflicts with the implementation of these functions in OpenBLAS. 

As far as I can tell these are not standard BLAS functions.

http://www.netlib.org/lapack/explore-html/d6/dee/group__complex__blas__level2.html

Is there a reason they are included in the main library?

**Comment by martin-frbg** [comment]
Not sure why this would be OpenBLAS' fault rather than netlib unconditionally building their own function.  Anyway c/zsbmv have been included ever since GotoBLAS2, and as far as I know the documented procedure for building OpenBLAS+LAPACK has always been to build the netlib LAPACK within the OpenBLAS source tree (in the past, the netlib source was not bundled like it is now). BTW the LAPACK distribution that ships with OpenBLAS is the current 3.8.0...

**Comment by sandwichmaker** [comment]
I do not think this is netlib/lapack's fault, since a standard BLAS implementation is not expected to have these functions (though to be fair, LAPACK is not a paragon of code cleanliness either, it comes with two identical copies of this function - one for the linear solver tests and another for the eigensolver tests).

**Comment by martin-frbg** [comment]
I am not sure if OpenBLAS is supposed to be a "standard" BLAS implementation in the sense of providing only what was historically present in a 1990s BLAS. There are numerous extensions in MKL and others as well, which you are probably just as likely to hit eventually. (And I still do not get why you want to build an outdated version of something that comes with OpenBLAS out-of-tree)

**Comment by sandwichmaker** [comment]
There are two different issues. Version and out of tree.

The version thing is not really relevant, because the same thing is true for the latest version of LAPACK. 

Why I am building out of tree is because thats how our LAPACK and BLAS build is structured right now,  LAPACK build is independent of the BLAS implementation which can vary from platform to platform. So I am in the process of trying to replace our BLAS build with OpenBLAS, and in the process I need to make sure that LAPACK tests pass on top of whatever BLAS we are using. 

At a future date, I'd like to use the LAPACK build from OpenBLAS too, but its just BLAS for now.

**Comment by martin-frbg** [comment]
I do not yet see a convincing case to remove the OpenBLAS implementations of c/zsbmv after about 10 years (they were present in GotoBLAS2-1.08, but probably not yet in GotoBLAS1), in particular if it is just about getting the LAPACK test code working. IMHO Reference-LAPACK should change the name of their private implementations in EIG and LIN (though that would not work retroactively for your 3.5.0)

**Comment by sandwichmaker** [comment]
Oh I am not asking you to remove it, I was mostly just curious about the reasoning.  I can work around this. Thanks for the background.
