### ISSUE TITLE
Tag a new release for Ryzen 2 support?

### ISSUE THREAD

**Issue by tlnagy** [xianyi/OpenBLAS#1691]
I see that #1665 adds support for Ryzen 2, what's the schedule for releasing a patch with that commit included? 

Thanks!

**Comment by brada4** [comment]
It is a three-line change.
If desperately in need you can extract patch file with git diff, or set OPENBLAS_CORETYPE=ZEN while it makes into packaged release.

**Comment by martin-frbg** [comment]
0.3.2 should be out either this weekend or the next, primarily to fix the problems encountered with the new code from 0.3.1. (But as brada4 wrote, the Ryzen2 support is actually just its autodetection at build time, there are still no specific performance patches for the Zen architecture compared to Intel Haswell.)

**Comment by martin-frbg** [comment]
Closing as 0.3.2 is released now.
