### ISSUE TITLE
OpenBLAS 0.3.1 Compile Fails with IBM XL 16.1.0 Compiler on POWER8

### ISSUE THREAD

**Issue by nmhamster** [xianyi/OpenBLAS#1699]
Bug when trying to compile OpenBLAS 0.3.1 download using IBM XL 16.1 (C/C++ and Fortran compilers) on POWER8. It appears inline assembly does not compile correctly.

```
[ 26%] Building C object kernel/CMakeFiles/kernel.dir/CMakeFiles/sasum_k.c.o
In file included from /ascldap/users/sdhammo/openblas/OpenBLAS-0.3.1/build-power8/kernel/CMakeFiles/sasum_k.c:7:
In file included from /ascldap/users/sdhammo/openblas/OpenBLAS-0.3.1/kernel/power/sasum.c:50:
/ascldap/users/sdhammo/openblas/OpenBLAS-0.3.1/kernel/power/sasum_microk_power8.c:172:8: error: unknown register name 'vs32' in asm
       "vs32","vs33","vs34","vs35","vs36","vs37","vs38","vs39",
```

**Comment by martin-frbg** [comment]
Known problem, see #1248 - according to https://github.com/xianyi/OpenBLAS/issues/1078#issuecomment-332984211 this is a limitation of the XL compiler.

**Comment by trudeaun** [comment]
IBM XL 16.1 uses clang technology, and so far, "vs" register names are [unsupported by clang](https://bugs.llvm.org/show_bug.cgi?id=31837). As a workaround, you can use v0, …, v7, instead of "vs32", …, "vs39".

**Comment by martin-frbg** [comment]
Good to know - was this already the case with xlc 13, which was the subject of the earlier issues ? (I note another problem back then was lack of support for constraints like "=wa" (t0)"  in this same file, sasum_mikrok_power.c , which kept me from doing the vs mass rename - https://github.com/xianyi/OpenBLAS/issues/1078#issuecomment-332925325 )

**Comment by trudeaun** [comment]
For "vs" register names, my comment applies to xlc 13 as well. For the second problem related to constraints like "wa", unfortunately even the latest version of XL (16.1) does not support it yet. This feature request is in XL's backlog and hopefully it can be implemented soon.

**Comment by martin-frbg** [comment]
So are there equivalent constraints that xlc supports ? So far it looks like David Edelsohn's comment is still valid ...

**Comment by trudeaun** [comment]
Unfortunately, no. The currently supported constraints are listed on [Knowledge Center](https://www.ibm.com/support/knowledgecenter/en/SSXVZZ_16.1.0/com.ibm.xlcpp161.lelinux.doc/language_ref/asm.html). Sorry about that.

**Comment by martin-frbg** [comment]
I have added an entry to the faq in the wiki (thought I had done that already earlier).
