### ISSUE TITLE
OpenBLAS fails at build in MacPorts

### ISSUE THREAD

**Issue by shaonghosh** [xianyi/OpenBLAS#1716]
Hi, 

MacPorts upgrading is failing for OpenBLAS with the following error message:

`:info:build  FATAL:/opt/local/bin/../libexec/as/x86_64/as: I don't understand 'm' flag!`
... 
`:info:build Command failed:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_math_OpenBLAS/OpenBLAS/work/OpenBLAS-0.3.2" && /usr/bin/make -j8 -w all AR=/usr/bin/ar RANLIB=/usr/bin/ranlib`

I am not sure if this is a MacPorts issue or if something to with new changes in OpenBLAS itself. Thought it will be better to run it by you before reporting to MacPorts. Sorry if this is already reported, but I did not find any myself.

**Comment by martin-frbg** [comment]
If you do a search for the error message it seems to be a problem in MacPorts, where it puts /opt/local/bin in the PATH before /usr/bin and other stock OS directories, so some wrong version of as gets called.

**Comment by shaonghosh** [comment]
Thank you for pointing me to it. I am notifying MacPorts regarding it.

**Comment by shaonghosh** [comment]
This is now resolved. Here is the link to the MacPorts ticket that solved this issue:

https://trac.macports.org/ticket/56919

Cheers
