### ISSUE TITLE
Build On Windows with VS2013 Failed

### ISSUE THREAD

**Issue by BEMfreshman** [xianyi/OpenBLAS#1719]
Hi,
I want to build Openblas 0.3.2 on Windows with VS2013.
I successfully build OpenBLAS project in VS and get .lib and .dll file in DEBUG folder. But I notice that the size of openblas.lib is only 2KB while openblas.dll is about 5MB. So I suspect perhaps the installation of library is failed. As expected, all tests code in utest folder terminate with errors as following:

`error LNK2019: unresolved external symbol caxpy_，referenced in function __ctest_axpy_caxpy_inc_0_run
error LNK2019: unresolved external symbol csrot_，referenced in function __ctest_rot_csrot_inc_0_run 
error LNK2019: unresolved external symbol cswap_，referenced in function __ctest_swap_cswap_inc_0_run
error LNK2019: unresolved external symbol daxpy_，referenced in function __ctest_axpy_daxpy_inc_0_run
error LNK2019: unresolved external symbol drot_，referenced in function __ctest_rot_drot_inc_0_run
error LNK2019: unresolved external symbol drotmg_，referenced in function __ctest_drotmg_rotmg_run
error LNK2019: unresolved external symbol dsdot_，referenced in function __ctest_dsdot_dsdot_n_1_run 
error LNK2019: unresolved external symbol dswap_，referenced in function __ctest_swap_dswap_inc_0_run 
error LNK2019: unresolved external symbol samax_，referenced in function __ctest_amax_samax_run 
error LNK2019: unresolved external symbol saxpy_，referenced in function __ctest_axpy_saxpy_inc_0_run
error LNK2019: unresolved external symbol srot_，referenced in function __ctest_rot_srot_inc_0_run 
error LNK2019: unresolved external symbol sswap_，referenced in function __ctest_swap_sswap_inc_0_run 
error LNK2019: unresolved external symbol zaxpy_，referenced in function __ctest_axpy_zaxpy_inc_0_run 
error LNK2019: unresolved external symbol zdrot_，referenced in function __ctest_rot_zdrot_inc_0_run 
error LNK2019: unresolved external symbol zswap_，referenced in function __ctest_swap_zswap_inc_0_run
`

Anyone can help me with it?

PS:
My platform is Windows 10 Family 64bits

**Comment by brada4** [comment]
Can you record all output of build? There should be some errors before regarding failure to compile particular files.
Formally vs2013 cannot target w10, just 8.1 and less, bit it should not be a problem failing build completely

**Comment by BEMfreshman** [comment]
Do you mean all output in VS when I build OpenBLAS solution?
I left my personal computer home so I can't post information printed by VS immediately.
The record will be post after returning home in next 6 hours.

By then way, I have succeed in installing OpenBLAS in another Windows 10 with VS2013 but
failed in my Archlinux due to some segment faults in test.

**Comment by brada4** [comment]
No such rush, good that you return to report once in a while.
Always issue 'make clean' before build. 
0.3.1 is known to be with some threading defects not present before or after. 
You can record arch or any liniux output with 'script' command.
If you get coredumps it is certainly worth examining.

**Comment by BEMfreshman** [comment]
I have compiled this library twice in the last two days and read the record given by VS in output window. 16 errors and 480+ warnings. All the errors I have post yesterday and I will check whether something has been missed.

I will open a new issue about errors that I meet in archlinux.

**Comment by brada4** [comment]
Clean or use fresh build directory. It should err at failing to build missing symbols before they get found being missing.

**Comment by BEMfreshman** [comment]
OK, I make it and let me tell the way.
(1) Clean the build directory
(2) Install newest CMake (3.12)
(3) start VS2013 as administrator

Compile.

I don't know which step takes effect but I think if you meet same problem, you'd better do as I do.

**Comment by brada4** [comment]
The third step would not be necessary since vista or so
Try w8.1 compat mode instead?

**Comment by martin-frbg** [comment]
I have now added a version recommendation for cmake to the wiki page - this seems to be the most likely culprit, and I now remember that we saw similar recommendations (for 3.11 at the time) in recent issues involving building with VS2017.
