### ISSUE TITLE
More Debug Information

### ISSUE THREAD

**Issue by BEMfreshman** [xianyi/OpenBLAS#1722]
Hi,
I am debugging this library on windows in VS2013 and I have scanned blas_server_win32.c.
I find there are some code just like:
`
#ifdef SMP_DEBUG

fprintf(STDERR,....);

#endif
`
That is to say, if I define macro SMP_DEBUG, I can get some information printed on console.
I have tried to use preprocessor in VS or define SMP_DEBUG directly in my main.c file but none of them works.

How can I get it works?
Thanks.

**Comment by martin-frbg** [comment]
Add -DSMP_DEBUG=1 to the cmake command line (or if all else fails, define SMP_DEBUG in common.h so that it gets included in all source files) (The definition must be seen at compile - or rather, preprocessor time, so it does not help to put it in your main.c file)

**Comment by BEMfreshman** [comment]
Thanks for reply.
I have read common.h and found SMP_DEBUG had been defined by default.
So, what I should do is to add SMP_DEBUG to prerocessor?
Let me have a try and report lately

**Comment by martin-frbg** [comment]
There is an `#undef SMP_DEBUG` hiding in common_thread.h that disables it again, try to remove it.

**Comment by martin-frbg** [comment]
BTW it seems that -DSMP_DEBUG=1 is not currently recognized by the cmake scripts. Probably need to edit the affected header(s) for these old developer options to work even with gmake.

**Comment by BEMfreshman** [comment]
Done.
Disable this code and it works well.
Thanks
