### ISSUE TITLE
Changelog not up-to-date

### ISSUE THREAD

**Issue by pbregener** [xianyi/OpenBLAS#1727]
The changelog (https://github.com/xianyi/OpenBLAS/blob/develop/Changelog.txt) has not been updated since v0.2.20. Is that information (changes between 0.2.20 and 0.3.2) available somewhere else?

**Comment by martin-frbg** [comment]
Unfortunately I missed that when I started doing the releases. Please see https://github.com/xianyi/OpenBLAS/releases for now, I will update Changelog.txt as soon as possible.

**Comment by pbregener** [comment]
Wow, that was fast! Thanks a lot!
