### ISSUE TITLE
Dynamic runtime CPU detection for non-x86 architectures

### ISSUE THREAD

**Issue by susilehtola** [xianyi/OpenBLAS#1737]
Hi,

what are your plans for dynamic CPU detection on non-x86 architectures? It would be great to have it, as it would enable efficient versions on linux distributions...

**Comment by martin-frbg** [comment]
No concrete plans as far as I am aware, but patches welcome of course. Which architecture(s) do you have in mind ? A suggestion for implementing the runtime detection on ARM was posted quite non-recently in #989

**Comment by susilehtola** [comment]
All of them? :laughing:

**Comment by sharkcz** [comment]
/me agrees ;-) I'm looking into it, but no promises.

**Comment by RashmicaG** [comment]
I was thinking of doing this for the POWER architecture.

Do you think its reasonable to assume that the glibc version on the system OpenBLAS is running on will be the same or higher than the system it was built on?

I was thinking of something like this:

```
int cpu_is_power8() 
{
#ifdef __BUILTIN_CPU_SUPPORTS__
        return __builtin_cpu_is("power8");
#elif ((__GLIBC__ > 2) || (__GLIBC__ == 2 && __GLIBC_MINOR__ >= 16))
        unsigned long v = getauxval( AT_PLATFORM );
        return !strcmp("power8", (char *)v);
#else
        return detect();
#endif
}

static FLOAT ddot_kernel_8(....)
{
        if (cpu_is_power9())
                //do power9 optimised code
        elif (cpu_is_power8())
                //do power8 optimised code
        else
                // default implementation
}

```
What are your thoughts @sharkcz? I'm not sure if there's a better way to determine the existence of getauxval()...

**Comment by dnabanita7** [comment]
Hello! I am very new to this community. I want to learn and work on creating a dynamic cpu on s390x in OpenBLAS. Can I know where to get started? 
Thank you.

**Comment by martin-frbg** [comment]
Hi, the corresponding work for PowerPC (#2084) can probably be used as a guideline. Basically, you would need to create driver/others/dynamic_zarch.c with some reliable runtime detection of the cpu (can be what is used in cpuid_zarch.c at build time, can be something else) and a little code to translate between the generic names of functions (sgemm) and their cpu-specific implementations (like sgemm_kernel_Z13). Do you have access to s390x hardware for testing ?

**Comment by dnabanita7** [comment]
I am not familiar to the jargons you have used. I am sorry for this. Can I know where to get started to learn about another architecture implementing OpenBLAS, then try this project? I will check for PowerPC right now.
Currently, I do not have access to s390x but I will set it up and let you know.
Thanks.

**Comment by martin-frbg** [comment]
https://github.com/xianyi/OpenBLAS/pull/2084/files (the "Files changed" tab on the github page I linked to with #2084) shows what was written to make it work for PowerPC - just writing "Z13" and "Z14" where that has POWER8 and POWER9 would probably get most of the work done. But that code uses a function _builtin_cpu_is() for cpu identification that is probably not available on s390x - you could copy from the cpu identification code that is run as part of the build (cpuid_zarch.c) which reads /proc/sysinfo instead, perhaps there are even better ways.

**Comment by aggmoulik** [comment]
Hi @martin-frbg, I don't know much about the s390x architecture and I want to set up the s390x so can you please recommend something.

**Comment by nk521** [comment]
@martin-frbg can you please take a look at #2349 and point out the changes that I should make.

**Comment by dipu989** [comment]
@martin-frbg @jmertic Is s390x runtime detection implemented now with this PR #2349 ?
Is https://github.com/openmainframeproject-internship/resources/blob/master/proposed_projects/Dynamic%20CPU%20support%20for%20s390x%20in%20OpenBLAS.md complete now?

**Comment by martin-frbg** [comment]
I believe so (though I do not have a convenient collection of z-series to actually test it in the wild)
BTW I was not even aware of that proposal...

**Comment by jmertic** [comment]
Hi! @sharkcz has put together this proposal, but I don't think a mentee picked this project.

**Comment by dipu989** [comment]
@jmertic @sharkcz Can I submit my proposal of OMP regarding this project or any other project will be added in its place, given that the project was completed?

**Comment by jmertic** [comment]
@dipu989 I'd confirm the work is done first.

**Comment by dipu989** [comment]
@jmertic That would be great!

**Comment by martin-frbg** [comment]
Closing as I believe the major architectures are covered now (if there is demand for armv7 or a revival of the MIPS ecosystem these could still be added of course).

**Comment by susilehtola** [comment]
Would it be possible to get dynamic runtime detection for armv7 as well? It is still a supported architecture for linux distributions.

**Comment by martin-frbg** [comment]
I believe the two CORTEX targets are just clones of the generic ARMV7 one with a bigger L2 size **assumed** for the hardware (1M vs 512k). (Nothing seems to have changed since xianyi originally committed 229ce2cc) So unless there is renewed interest in this architecture leading somebody to add individual optimizations or entirely new cpu models I see little point in adding runtime detection.

**Comment by Gautime** [comment]
@jmertic Is this project closed for OMP mentees? Please confirm.

**Comment by sharkcz** [comment]
Yes, it's not available for mentees any more. I'm going to retract it from the OMP web.

**Comment by Dhiraj240** [comment]
@sharkcz @jmertic I had applied for this project in this year OMP.
Please look at it as I have listed some documentations in my proposal.

I applied as it is still present on main page as https://github.com/openmainframeproject-internship/resources/blob/master/proposed_projects/Dynamic%20CPU%20support%20for%20s390x%20in%20OpenBLAS.md
so, please check as my work will become trash.

**Comment by martin-frbg** [comment]
@sharkcz @jmertic can you **please** look into getting that project proposal taken down ? I'm inclined to think there needs to be some advance coordination on potential topics. (In particular for would-be mentees with little or no prior coding experience - I am sure there are many bright minds out there but if no experienced contributor has spare time to work on a topic, chances are there will be even less capacity for teaching someone new how to do it). In the current style it is only going to reflect poorly on either project. (And I will probably lock this ticket later this week)

**Comment by Dhiraj240** [comment]
@martin-frbg But then it will provide no space for me to get into OMP this year as it was a prior project for me.
I will work on this project and will finish it up properly. If I am not good enough during my coding phase just take down my stipends and remove me at that time but please don't make judgements as of now.
Is there any alternative for me as the application phase is already over?
Can we work together if there are no alternatives for me now?

**Comment by jmertic** [comment]
@martin-frbg I've moved it to the inactive list for now. When you think timing is better to tackle this, let us know - we likely will have some mentees looking for projects for class credit throughout the year that could get engaged.

**Comment by Dhiraj240** [comment]
@jmertic Is there any slot left or should I apply next year?
