### ISSUE TITLE
pkgconfig filles for cblas, blas and lapack

### ISSUE THREAD

**Issue by timokau** [xianyi/OpenBLAS#1740]
When pkgconfig files were added, there used to be pkgconfig files for clbas, blas and lapack in addition to the openblas one. They were removed in #1096 by @martin-frbg. Discussion about it is in #598, though I don't really see any arguments against inclusion.

Currently at least sage relies on these pkgconfig files. Because of that distributions have to include them if they want to package sage. I'm the packager for nix and we just wondered (https://github.com/NixOS/nixpkgs/pull/45257) why openblas doesn't provide these pc files by default.

So is there any reason not to include them? It seems useful to me to be able to abstract over blas libraries.

**Comment by martin-frbg** [comment]
As I remember it, there were no arguments _for_ inclusion of separate pkgconfig files, and my concern was that these would all end up adding the same link line to any build process that would use them. Then there was the question of parallel installations of OpenBLAS and e.g. netlib or atlas, which
might provide conflicting cblas.pc etc.

**Comment by timokau** [comment]
> As I remember it, there were no arguments for inclusion of separate pkgconfig files

What about the use case "link some blas library"?

> adding the same link line to any build process that would use them

That shouldn't make a difference right?

> Then there was the question of parallel installations of OpenBLAS and e.g. netlib or atlas, which
might provide conflicting cblas.pc etc

That would be remedied by prefixing the filenames like suggested in #598.

**Comment by brada4** [comment]
BLAS is like 20 years older than pkgconfig, and in those 20 years of pkgconfig nobody found it practical to have such .pc file
Indeed you can have synthetic openblas.pc and atlas.pc and mkl.pc files in sagemath if that is your preferred way.
in most linux distributions it is either -lblas alternatives or easily replaceable thunk to distributor's prefered blas implementation, that you can symlink to replacement of users' choice.

**Comment by timokau** [comment]
Why would it not be practical? And what disadvantages would there be?

**Comment by brada4** [comment]
You can make 'ld -lblas -osageblas.so' thunk library that one can replace with openblas , or in case of ubuntu, it is already obedient to alternatives. Or in case of windows just plant openblas there?
Sort of leave easy choice to users instead of implying one implementation on them?
pkgconfig is not very good at understanding that blas.pc atlas.pc openblas.pc and mkl.pc all would provide same API in the end. Lets take ubuntu alternatives as an example where netlib blas is used for compiler linking but alternatives can be used for runtime loading.

**Comment by timokau** [comment]
I'm sorry I still don't understand you. What is a thunk library? What is ubuntu obedient to? What do you mean with windows?

**Comment by brada4** [comment]
You just link your executables to a library which imports blas, lapack and cblas
One can replace that with blas implementation of their choice, by relinking, or rewriting library file...
In turn in ubuntu or debian you can redirect -lblas that i suggest to link from your fake blas library with a blas implementation of your choice. I.e far outside sagemath. Or replace fake blas library with mkl etc

**Comment by timokau** [comment]
Yes, that is a possibility. However are there any reasons against just providing the pkgconfig files for cblas, blas and lapack? If you are opposed against this, is there any reason against us providing them as a distribution?

**Comment by brada4** [comment]
They are not part of Netlib LAPACK API?
cmake and autoconf has on their own blas implementation finders for example.

**Comment by martin-frbg** [comment]
I am not opposed to reinstating the additional pkgconfig files, as long as they do not cause any new and interesting problems. Getting the recent thread memory allocating mess fixed is much higher on my list of priorities however.

**Comment by timokau** [comment]
Why would an implementation detail like pkgconfig-files be a part of the api? That other implementation finders exist shouldn't be an issue.

Okay, glad to hear that you are open to it. I understand that it is not high priority. I'll then add the files to our distro package for now. Let me know if I can do anything to help.

**Comment by isuruf** [comment]
@timokau, I added them initially when I was packaging sagemath for conda and I agree with the decision that the `cblas, blas, lapack` files should be left to the distributions to add them. Reason is that the system-wide blas or cblas or lapack should be chosen by the distribution and openblas should not assert itself as the blas implementation for the distribution.

**Comment by timokau** [comment]
@isuruf my understanding of pkgconfig is incomplete, but shouldn't it be able to deal with multiple declarations of "blas" and "cblas"?

**Comment by timokau** [comment]
Okay apparently it is not. So in that case I agree that adding those files to `lib/pkgconfig` would be a bad idea. Thanks for the explanations!
