### ISSUE TITLE
cblas_sgemm gives incorrect results in heavily multi-threaded programs

### ISSUE THREAD

**Issue by btiplitz** [xianyi/OpenBLAS#1755]
When making a call to cblas_sgemm, sometimes I get a completely different result (though not often).  When I run this on a high core count system with 12+ processors per core, it happens more often though I have reproduced this on my CoreI7 processor.  I have also tried to disable hyperthreading as well as to lock the thread onto a non-paired core and nothing changes this.  On the high count systems, I can only produce this error when linked statically but on the CoreI7, I see this with dynamic linking.  The identical behaviour happens with ATLAS though not with the intel MKL 

The OpenBLAS library is compiled with 
make -j 10 USE_THREAD=0 NUM_THREADS=60 DYNAMIC_ARCH=1

The code to produce this computes a single answer and then uses that for the expected result.  When I get this error on the I7, I'm running this as ./process-matrix 20 500.  Sometimes it gets an error and sometimes its fine.  When the error happens, the LMS was 8210.902343750000 so it's not a slight error.  On my I7, the value is always the same but on the Xevon E5-2660v3, I get many different values. 

Code:
/*
  g++ -o matrix-test matrix-test.cc -Wall -IOpenBLAS/release/include -lm -lpthread -LOpenBLAS/release/lib -lopenblas
 *
 * */
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <unistd.h>
#include <sys/syscall.h>
#include <math.h>
#include <pthread.h>
#include <stdlib.h>
#ifdef HAVE_MKL
#include "mkl.h"
#else
extern "C" {
#include "cblas.h"
}
#endif

int loop_max=10000;
float *Adata, *Bdata, *Mdata_ans, *Mdata_prime;
float alpha=1.0, beta=1.0;
int a_num_rows=1;
int a_num_cols=3000;
int a_stride=3000;
int b_num_rows=128;
int b_num_cols=3000;
int b_stride=3000;
int num_rows=1;
int num_cols=128;
int stride=128;

CBLAS_TRANSPOSE transA=CblasNoTrans, transB=CblasTrans;
int threads_ready=0;
pthread_mutex_t locker=PTHREAD_MUTEX_INITIALIZER;
bool go=false;

int main(int argc, char *argv[])
{
#ifdef HAVE_MKL
  mkl_set_num_threads(1);
#else
  openblas_set_num_threads(1);
#endif
  int thread_count=8;
  if (argc > 1) {
    int n=atoi(argv[1]);
    if (n >= 0) thread_count=n;
    if (argc > 2) {
      n=atoi(argv[2]);
      if (n >= 1) loop_max=n;
    }
  }
  printf("Max thread=%d cycles=%d\n", thread_count, loop_max);

  Adata=(float *)malloc(a_num_rows*a_num_cols*sizeof(float));
  Mdata_prime=(float *)malloc(num_rows*num_cols*sizeof(float));
  Bdata=(float *)malloc(b_num_rows*b_num_cols*sizeof(float));
  Mdata_ans=(float *)malloc(num_rows*num_cols*sizeof(float));
  for (int i=0; i<a_num_rows*a_num_cols; i++) Adata[i]=drand48();
  for (int i=0; i<num_rows*num_cols; i++) Mdata_prime[i]=drand48();
  for (int i=0; i<b_num_rows*b_num_cols; i++) Bdata[i]=drand48();
  memcpy(Mdata_ans, Mdata_prime, sizeof(float)*num_rows*num_cols);
  cblas_sgemm(CblasRowMajor,  transA, transB, num_rows, num_cols,
              transA==CblasNoTrans ? a_num_cols : a_num_rows,
              alpha, Adata, a_stride, Bdata, b_stride, beta, Mdata_ans, stride);

  pthread_attr_t attr;
  pthread_attr_init(&attr);
 pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_JOINABLE);

  pthread_t pyr[thread_count];
  struct timespec clock_start, clock_end;
  clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &clock_start);
  for (long i=0; i < thread_count; i++) {
    void *matrixrunner(void *thrdata);
    int r=pthread_create(&pyr[i], &attr, matrixrunner, (void *)(i+1));
    if (r != 0) {
      printf("Thread create failed %ld %d/%s\n", i, errno, strerror(errno));
    }
  }
  while (thread_count > threads_ready) {}
  go=true;
  for (int i=0; i < thread_count; i++) {
    void *status;
    pthread_join(pyr[i], &status);
  }
  clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &clock_end);
  printf("Duration %f seconds\n", clock_end.tv_sec-clock_start.tv_sec+((float)(clock_end.tv_nsec-clock_start.tv_nsec)/1e9));
  return(0);
}

void *matrixrunner(void *thrdata)
{
  printf("%ld ", (long)thrdata);fflush(stdout);
  int count=0;
  float *Mdata=(float *)malloc(num_rows*num_cols*sizeof(float));
  pthread_mutex_lock(&locker);
  threads_ready++;
  pthread_mutex_unlock(&locker);
  while (!go) {}
  while (count < loop_max) {
    memcpy(Mdata, Mdata_prime, sizeof(float)*num_rows*num_cols);
    cblas_sgemm(CblasRowMajor,  transA, transB, num_rows, num_cols,
                transA==CblasNoTrans ? a_num_cols : a_num_rows,
                alpha, Adata, a_stride, Bdata, b_stride, beta, Mdata, stride);
    float lms=0;
    for (int i=0; i < num_rows*num_cols; i++) {
      lms+=pow(fabs(Mdata_ans[i]-Mdata[i]), 2);
    }
    if (lms > .0000001) {
      printf("BAD %.12f %ld (%d)\n", lms, syscall(SYS_gettid), count);
      _exit(0);
    }
    printf(".");fflush(stdout);
    count++;
  }
  free(Mdata);
  pthread_exit(NULL);
  return(NULL);
}

**Comment by martin-frbg** [comment]
Which version of OpenBLAS are you seeing this with ? (I suspect using OpenMP or compiling with USE_SIMPLE_THREADED_LEVEL3 may fix it - there are some suspected races in the multithreaded
level 3 BLAS implementation.)

**Comment by brada4** [comment]
Could you fill the cpu model number for corei7 , this trade name covers at least 4 generations, including haswell matching the xeon you fully describe.
Also backtrace of crash would be nice.

**Comment by btiplitz** [comment]
0.3.2.  and I did try that option both before and today.  It does not seem to effect the behaviour.  I updated the bug as I missed that on the high count, I've only reproduced this when linking statically but on the I7, I see this with dynamic linking.  Thus as with many issues like this, the bug only occurs occasionally

**Comment by btiplitz** [comment]
There is no crash.  Just bad results.  The I7 is i7-6700 CPU @ 3.40GHz

**Comment by brada4** [comment]
Skylake HT processors need microcode/ bios update past this https://lists.debian.org/debian-devel/2017/06/msg00308.html for float accuracy....
Also worth disabling HT altogether for recent security discoveries.

**Comment by btiplitz** [comment]
I saw the Skylake bug which is why I tried to disabling HT to eliminate that as a cause.  The Zeon processor is 2 generations earlier.  Since the MKL does not have the bug, I don't think it's related to the CPU though it is also possible I have just not managed to create the bug on the MKL.

**Comment by martin-frbg** [comment]
You could try 0.3.3 to exclude potential issues with the new thread-local storage allocation code (that is disabled by default again in 0.3.3), unless you already saw the same problems with 0.3.0 or earlier.
ATLAS showing the same problems does point towards firmware, MKL may already know what to avoid.

**Comment by brada4** [comment]
The microcode bug is skylake-only, I think it has to go to FAQ, I see it suspected like 3rd time.
Since it is along same lines, would be most practical to address L1TF at same microcode update and HT disablement spree.... There is no perfromance impact on i7 or Xeon as they run 1st HT core while other stopped at full performance.

@btiplitz if you told OS it would be easier to propose os-based firmware package, typically linux-firmware intel-ucode kernel-microcode cpumcupdate etc.

**Comment by btiplitz** [comment]
I updated to 0.3.3 and so far it's not happening.  I assume this indicates a compiler bug.  I'm using gcc 4.8.5.  Perhaps I should try a new compiler with 0.3.2 ?

**Comment by brada4** [comment]
You should not try 0.3.2, it has the bug with threading, addressed in 0.3.3
Still ATLAS problem rises some eyebrow. Can you check ATLAS with HT off and/or new microcode, so that skylake microcode bug lands in FAQ?

**Comment by btiplitz** [comment]
@brada4 I don't have a skylake processor.  I do have other code using thread local storage so if it does not work for OpenBLAS, then I'm worried about my code.  As the 0.3.3 appears fixed I guess I don't have a current bug with OpenBLAS

**Comment by brada4** [comment]
Dont blame your code or atlas without confirming CPU microcode.
/proc/cpuinfo on Linux shows microcode version, just google for it and it will tell how good it is....

**Comment by btiplitz** [comment]
for the I7 microcode       : 0xc2
the zeon says 0x38

**Comment by btiplitz** [comment]
Ah, my desktop is a skylake

**Comment by btiplitz** [comment]
microcode_ctl-2.1-29.10.el7_5.x86_64 on the i7 skylake

**Comment by brada4** [comment]
That's the latest microcode, far past your CPU bug.
I think this issue is resolved "silently" with 0.3.3 and can be closed.
The Fedora EPEL package is still 0.3.0 , so also "official" option for you should be working fine.

Probably worth drilling around ATLAS a bit and reporting issue IF it is theirs to where due.

**Comment by btiplitz** [comment]
I tried gcc 8.2 figuring perhaps if it's some thread_local thing which is done by the compiler, then perhaps it's fixed but it still fails.  I would not expect openblas to use thread local storage.  Seems unexpected

**Comment by martin-frbg** [comment]
Using thread local storage was implemented recently to remove significant overhead at thread startup. Unfortunately that implementation had - and unfortunately still has - a few shortcomings that did not show up immediately, and trying to get those fixed seemed to lead to new problems as evident in #1739. As that unlucky episode also uncovered just how many projects silently depend on OpenBLAS nowadays, the offending code was disabled for now in 0.3.3 to provide a stable basis again.
Why would you not expect OpenBLAS to use TLS in general ?

**Comment by martin-frbg** [comment]
reopening due to #2126

**Comment by martin-frbg** [comment]
This test case is now fixed by adding a new build option USE_LOCKING to be used in conjunction with USE_THREAD=0, where it will activate the locking code that is normally included only in multithreaded builds.
