### ISSUE TITLE
Compile for iOS ARMV7

### ISSUE THREAD

**Issue by bitianchi** [xianyi/OpenBLAS#1758]
When I build openblas for ios armv7, some errors coming up. 
I use the following commands to build openblas.

**TOOLCHAIN_PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
SYSROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk
make clean
make TARGET=ARMV7 BINARY=64 HOSTCC=clang CC="$TOOLCHAIN_PATH/clang -isysroot $SYSROOT_PATH -arch armv7 -miphoneos-version-min=8.0 -O2" NOFORTRAN=1 libs**

The following file is the log.
[err.log](https://github.com/xianyi/OpenBLAS/files/2366555/err.log)

**Comment by bitianchi** [comment]
@martin-frbg Could you please take a look at this?

**Comment by martin-frbg** [comment]
Indeed looks a lot like #1531 - my patch there was for ARMV8 only, and it could be that ARMV7 needs more and different changes besides replacing the nrm2 functions with their C equivalents. Could you try how much further you get when you replace the four NRM2 entries like we did in #1531 ?

**Comment by bitianchi** [comment]
The question is I have no idea about the replacement of nrm2_vfpv3.S

**Comment by martin-frbg** [comment]
If you just comment out the four lines in KERNEL.ARMV7, it should pick up nrm2.c (for SNRM2 and DNRM2) and znrm2.c (for C/ZNRM2) from the basic KERNEL file in kernel/arm.

**Comment by brada4** [comment]
IphoneOS 11.0 does not run on armv7 processors. It is safe to make it armv8

**Comment by xsacha** [comment]
Looks like he is targeting iOS 8.0 though:
`miphoneos-version-min=8.0 `

**Comment by bitianchi** [comment]
Yes, we need to support IOS 8.0

**Comment by bitianchi** [comment]
One more question:
`make TARGET=ARMV7 BINARY=64 HOSTCC=clang CC="$TOOLCHAIN_PATH/clang -isysroot $SYSROOT_PATH -arch armv7 -miphoneos-version-min=8.0 -O2" NOFORTRAN=1 libs
`
TARGET=ARMV7 is this right?

**Comment by martin-frbg** [comment]
Yes, that is correct for general ARMv7 cpu support. (Cortex A9 and A15 targets use the same KERNEL.ARMV7 file but have individual settings for cache sizes etc.)

**Comment by martin-frbg** [comment]
"BINARY=64" probably does not makes sense with the ARMV7 target though (aren't they 32bit cpus, while ARMV8 can support both 32/64 ?)

**Comment by bitianchi** [comment]
I got it. Thanks

**Comment by brada4** [comment]
@martin-frbg [32bit support](https://www.wired.com/story/the-ios-11-32-bit-appocalypse-isnt-actually-that-bad/) goes away [in iOS11](https://support.apple.com/en-us/HT208067)
iOS8 supports 64bit apps too.

**Comment by martin-frbg** [comment]
Should not affect building for earlier versions as seems to be intended here, or does it ? (Not sure what having 64bit support in IOS8 has to do with it)

**Comment by brada4** [comment]
All phones targeted are ARMv8, just that. Latest ones will not run 32bit binary if they get connected to wifi sometimes....

**Comment by xsacha** [comment]
To be honest I never target iOS because that platform has a built in BLAS implementation called Accelerate. Saves a lot of headache.

**Comment by bitianchi** [comment]
It seems in armv8, there is no definition of _scopy_k

### armv7:
![image](https://user-images.githubusercontent.com/29396595/45398258-12a50180-b676-11e8-8187-9a14e76b3aeb.png)

### armv8
![image](https://user-images.githubusercontent.com/29396595/45398272-19cc0f80-b676-11e8-9661-b4aea3ccd9c3.png)

### error:
![image](https://user-images.githubusercontent.com/29396595/45398441-babaca80-b676-11e8-97dd-b9f69102f23d.png)

Is there any solutions? Thanks

**Comment by martin-frbg** [comment]
Did you see any errors in the build log ? If the IOS compiler did not like the assembly implementation in copy.S, you will need to replace the xCOPYKERNEL entries in KERNEL.ARMV8 with the corresponding C functions from ../arm like we did with NRM2. (And it looks as if this continues with xAXPY and xGER)

**Comment by martin-frbg** [comment]
Did you make any progress ? (I notice the problems you saw with scopy_k etc. never came up in #1531, which makes me wonder if something else got broken in your build)

**Comment by bitianchi** [comment]
I had changed OpenBlas to Accelerate.

**Comment by martin-frbg** [comment]
I see. So this can be closed if you are not going to continue with OpenBLAS on IOS ?
