### ISSUE TITLE
Check for USE_TLS=0

### ISSUE THREAD

**Issue by jakirkham** [xianyi/OpenBLAS#1766]
Looks like the `USE_TLS` checks only verify that it is defined. Would it be possible to check that it is defined with a non-zero value?

**Comment by brada4** [comment]
@martin-frbg i could take care of ths class of issues starting here, +/- equaling -DXXX=0 to -UXXX

**Comment by brada4** [comment]
@jakirkham if you use `make` as opposed to `cmake` you can just comment out offending line from Makefile.rule, in cmake I think whole sections need to be patched out until corrected.

**Comment by martin-frbg** [comment]
`cmake` builds of 0.3.3 _do_ compile the "old" non-TLS version of memory.c by default, it is only plain `make` builds that are affected by the unintended presetting of USE_TLS=1 in Makefile.rule.

**Comment by brada4** [comment]
thus it is just to take one line away in Makefile.rule to get intended default?

**Comment by martin-frbg** [comment]
Updated PR #1765 just now to address both these issues.

**Comment by martin-frbg** [comment]
Merged #1765, so should be fixed on the develop branch.

**Comment by jakirkham** [comment]
Great, thanks Martin. 😄
