### ISSUE TITLE
OpenBlas issue with NDK18 and clang 7.0

### ISSUE THREAD

**Issue by wolfviking0** [xianyi/OpenBLAS#1774]
Hi,

I am using openblas with android arm and arm64, in order to build I used GCC.
But since the last update of the NDK(18), it seems not possible to use GCC. I decide to use Clang.

It's ok for arm64, but trying arm32 I have many issue like:
error: instruction 'fstmia' can not set flags, but 's' suffix specified
 fstmias r6, { s23 }

Any suggestion 

Thanks

**Comment by martin-frbg** [comment]
This looks like it is similar to #1226 , makes me wonder if the clang assembler is slowly shedding support for these "pre-UAL" memonics with every new version ? 
The UAL spelling of fstmias seems to be VSTMIA.32
but I guess it would make sense to review the entire error log unless it is only the fstmias instruction
that clang7 objects to...

**Comment by wolfviking0** [comment]
So I try quickly and we can use the VSTMIA.32, it seems to be fixing this error,
but after that other instructions failed but I suppose those can be fix using the UAL equivalent.

**Comment by brada4** [comment]
Could you try `make -i`
It will produce full compile errors in log (and garbage binary until errors are fixed)
Sure you can go one by one, but all at once seems quicker. 
There is assembly-free 32 bit version called ARMV5 if you need something to test without performance claims in 10 minutes.

**Comment by martin-frbg** [comment]
The corresponding "load" instruction, fldmias should be replacable by VLDMIA.32, and I suspect the "double" variants fldmiad,fstmiad would be the same just with a .64 postfix. These are the only `*mia*` instructions in the code I think, does it complain about other mnemonics as well ?

**Comment by wolfviking0** [comment]
@martin-frbg you are correct all the variant MIA also failed.

**Comment by martin-frbg** [comment]
Is it only the MIA instructions that fail, or is there more ? 
http://www.keil.com/support/man/docs/armasm/armasm_dom1359731199385.htm has a table of equivalent names that also includes instructions like fadds (used in the cgemm_kernel file), I wonder if these need changing as well.

**Comment by wolfviking0** [comment]
@martin-frbg it's only the MIA instructions.

**Comment by wolfviking0** [comment]
Hi @martin-frbg 

I just test your develop branch but I still have some few errors regarding fstmias

`
<instantiation>:26:2: error: instruction 'fstmia' can not set flags, but 's' suffix specified
 fstmias r5!, { s0 - s3 }
 ^
../kernel/arm/sgemm_ncopy_4_vfp.S:225:2: note: while in macro instantiation
 COPY4x4
 ^
<instantiation>:28:2: error: instruction 'fstmia' can not set flags, but 's' suffix specified
 fstmias r5!, { s4 - s7 }
 ^
../kernel/arm/sgemm_ncopy_4_vfp.S:225:2: note: while in macro instantiation
 COPY4x4
 ^
<instantiation>:29:2: error: instruction 'fstmia' can not set flags, but 's' suffix specified
 fstmias r5!, { s8 - s15 }
 ^
../kernel/arm/sgemm_ncopy_4_vfp.S:225:2: note: while in macro instantiation
 COPY4x4
 ^
<instantiation>:26:2: error: instruction 'fstmia' can not set flags, but 's' suffix specified
 fstmias r5!, { s0 - s3 }
 ^
../kernel/arm/sgemm_ncopy_4_vfp.S:230:2: note: while in macro instantiation
 COPY4x4
 ^
<instantiation>:28:2: error: instruction 'fstmia' can not set flags, but 's' suffix specified
 fstmias r5!, { s4 - s7 }
 ^
../kernel/arm/sgemm_ncopy_4_vfp.S:230:2: note: while in macro instantiation
 COPY4x4
 ^
<instantiation>:29:2: error: instruction 'fstmia' can not set flags, but 's' suffix specified
 fstmias r5!, { s8 - s15 }
 ^
../kernel/arm/sgemm_ncopy_4_vfp.S:230:2: note: while in macro instantiation
 COPY4x4
 ^
<instantiation>:10:2: error: instruction 'fstmia' can not set flags, but 's' suffix specified
 fstmias r5!, { s0 - s3 }
 ^
../kernel/arm/sgemm_ncopy_4_vfp.S:243:2: note: while in macro instantiation
 COPY1x4
 ^
<instantiation>:13:2: error: instruction 'fstmia' can not set flags, but 's' suffix specified
 fstmias r5!, { s0 - s7 }
 ^
../kernel/arm/sgemm_ncopy_4_vfp.S:278:2: note: while in macro instantiation
 COPY4x2
 ^
<instantiation>:6:2: error: instruction 'fstmia' can not set flags, but 's' suffix specified
 fstmias r5!, { s0 - s1 }
 ^
../kernel/arm/sgemm_ncopy_4_vfp.S:291:2: note: while in macro instantiation
 COPY1x2
 ^
<instantiation>:7:2: error: instruction 'fstmia' can not set flags, but 's' suffix specified
 fstmias r5!, { s0 - s3 }
 ^
../kernel/arm/sgemm_ncopy_4_vfp.S:319:2: note: while in macro instantiation
 COPY4x1
 ^
<instantiation>:4:2: error: instruction 'fstmia' can not set flags, but 's' suffix specified
 fstmias r5!, { s0 }
 ^
../kernel/arm/sgemm_ncopy_4_vfp.S:332:2: note: while in macro instantiation
 COPY1x1
 ^
`

**Comment by wolfviking0** [comment]
Here the list of files missing: 

	modified:   kernel/arm/cgemm_ncopy_2_vfp.S
	modified:   kernel/arm/dgemm_ncopy_2_vfp.S
	modified:   kernel/arm/dgemm_ncopy_4_vfp.S
	modified:   kernel/arm/sgemm_ncopy_2_vfp.S
	modified:   kernel/arm/sgemm_ncopy_4_vfp.S
	modified:   kernel/arm/zgemm_ncopy_2_vfp.S
	modified:   kernel/arm/ztrmm_kernel_2x2_vfp.S
	modified:   kernel/arm/ztrmm_kernel_2x2_vfpv3.S

**Comment by martin-frbg** [comment]
Ah, sorry, I did change them locally (by running `sed` on all assembly files in kernel/arm) but this was not in a regular git fork. Probably something went wrong when I uploaded the changes to github. Thanks for
catching this.
