### ISSUE TITLE
test_axpy work error on LOONGSON3A platform

### ISSUE THREAD

**Issue by fengrl** [xianyi/OpenBLAS#1777]
Compile Openblas with:
make CC=gcc FC=gfortran HOSTCC=gcc TARGET=LOONGSON3A CROSS=1 NO_LAPACKE=1 BINARY=64

And run utest
./openblas_utest 
TEST 1/23 amax:samax [OK]
TEST 2/23 drotmg:drotmg_D1_big_D2_big_flag_zero [OK]
TEST 3/23 drotmg:rotmg_D1eqD2_X1eqX2 [OK]
TEST 4/23 drotmg:rotmg_issue1452 [OK]
TEST 5/23 drotmg:rotmg [OK]
TEST 6/23 axpy:caxpy_inc_0 [OK]
TEST 7/23 axpy:saxpy_inc_0 [FAIL]
  ERR: test_axpy.c:90  expected 4.000e+00, got 2.250e+00 (diff 1.750e+00, tol 1.000e-13)
TEST 8/23 axpy:zaxpy_inc_0 [OK]
TEST 9/23 axpy:daxpy_inc_0 [FAIL]
  ERR: test_axpy.c:52  expected 4.000e+00, got 2.250e+00 (diff 1.750e+00, tol 1.000e-13)
TEST 10/23 zdotu:zdotu_offset_1 [OK]
TEST 11/23 zdotu:zdotu_n_1 [OK]
TEST 12/23 dsdot:dsdot_n_1 [OK]
TEST 13/23 swap:cswap_inc_0 [OK]
TEST 14/23 swap:sswap_inc_0 [OK]
TEST 15/23 swap:zswap_inc_0 [OK]
TEST 16/23 swap:dswap_inc_0 [OK]
TEST 17/23 rot:csrot_inc_0 [OK]
TEST 18/23 rot:srot_inc_0 [OK]
TEST 19/23 rot:zdrot_inc_0 [OK]
TEST 20/23 rot:drot_inc_0 [OK]
TEST 21/23 potrf:smoketest_trivial [OK]
TEST 22/23 potrf:bug_695 [OK]
TEST 23/23 fork:safety [OK]

**Comment by fengrl** [comment]
It seems that while incX=0, incY=0, the assembler code work error.
Test with:
SAXPYKERNEL=../x86_64/daxpy.c
DAXPYKERNEL=../x86_64/daxpy.c
CAXPYKERNEL  = ../mips/zaxpy.c
ZAXPYKERNEL  = ../mips/zaxpy.c

Result can be ok.

**Comment by martin-frbg** [comment]
The generic MIPS64 fix was probably https://github.com/xianyi/OpenBLAS/commit/fca6626 , not sure if it would also work on LOONGSON3A but at least the SAXPY file axpy_loongson3a.S looks similar enough. 
(Switching to the generic C code is probably safer, as I know just barely enough MIPS assembly to be dangerous...)

**Comment by fengrl** [comment]
merge the fix you provided to axpy_loongson3a.S and daxpy_loongson3a_simd.S, this problem can be fixed.

**Comment by martin-frbg** [comment]
Great. Thanks for testing and for preparing a PR (which I will merge now).
