### ISSUE TITLE
[question] Should DYNAMIC_ARCH and DYNAMIC_OLDER be enabled in the port?

### ISSUE THREAD

**Issue by yurivict** [xianyi/OpenBLAS#1779]
I am trying to decide should the port enable them by default. I can't find a definition, description what they do.

```DYNAMIC_ARCH``` seems to build several kernels for various processor types, and allows to select them at run-time? Therefore, it seems like it should be enabled by default?

What about ```DYNAMIC_OLDER```?

Could you also update descriptions of these cmake options to explain what they do?

**Comment by martin-frbg** [comment]
Your interpretation of DYNAMIC_ARCH is correct. (This option is available for x86 and x86_64 only at the moment). DYNAMIC_OLDER was split off from it in an effort to shorten the list, reducing library size and compile time. When it is not set, the library will still run on older hardware but will use kernels optimized for even less powerful cpus there. 
In general you will find the description of the available options in Makefile.rule - perhaps not ideal, but
a practice that was inherited from OpenBLAS' predecessor GotoBLAS.

**Comment by brada4** [comment]
@yurivict do you intend to target other architectures than x86 and x86_64?

Both should be enabled, especially for binary packages.
Between the lines of Martin's text - users' build of port could default to their current CPU. You may want to tweak CPU detection failure message to direct new CPUs encountered to this tracker.

**Comment by martin-frbg** [comment]
I assume the help texts would be for `cmake -LH` output, or is there a more elegant way to display them that I am missing ?
How about something like
`Include support for multiple CPU targets, with automatic selection at runtime (x86/x86_64 only)`
for DYNAMIC_ARCH, and
`Include specific support for older cpu models (Penryn,Dunnington,Atom,Nano,Opteron) with DYNAMIC_ARCH`
for DYNAMIC_OLDER ?

**Comment by yurivict** [comment]
Since ```DYNAMIC_ARCH``` is only for amd64/i386, there will be the port option ```DYNAMIC_ARCH``` only on amd64/i386 architectures that will be "ON" by default.

I guess, the same should be done for ```DYNAMIC_OLDER```.

**Comment by brada4** [comment]
For other architectures you need to allow to select core type

**Comment by yurivict** [comment]
How do I do this?

**Comment by brada4** [comment]
TARGET=ARMv8 for aarch64 for example

**Comment by yurivict** [comment]
Is this during build or during run?

**Comment by martin-frbg** [comment]
During build. Similarly 32bit ARM has TARGET=ARMV7 (and ARMV6,...) other architectures support TARGET=GENERIC.

**Comment by yurivict** [comment]
Why don't you set ```TARGET=xx``` during build yourself if it always has to be set?

What would happen if ```TARGET=xx``` isn't set?

**Comment by martin-frbg** [comment]
If TARGET is not set, the library will be built optimized for the CPU of the build system (which also means that it will only run on systems that are at least as poweful). If the build system cannot autodetect the CPU (which sometimes happens with very new CPU models, until their CPUID is added to the detection code), the build will fail with an error message.

**Comment by brada4** [comment]
I am proposing default user build to be "with target not set", while binary packages with DYNAMIC_ARCH(both), 64 cores , that serves two purposes - always working binary, and short build time for end-user.

**Comment by yurivict** [comment]
What is the benefit of the build with ```DYNAMIC_ARCH=OFF```? I mean, should there even be such option, or it should be always ```ON```?

**Comment by martin-frbg** [comment]
Shorter compile time and more importantly smaller library size as it will then contain only the optimized codes for one particular cpu type. 
If you are planning to distribute the library, you will probably want it to be able to run on as many systems as possible - if you are only going to use it on your own system(s) it would be pointless to include support for any (ancient or expensive) hardware you do not have.

**Comment by brada4** [comment]
Those options are implemented in a strange way that their presence is checked via `ifdef` historically, so they should be omitted to disable.
So only place it should not be mentioned is when user types "make" in port directory, so by default they build just code pertaining their current CPU. In all redistribution cases you might want to support all CPUs out there.

**Comment by martin-frbg** [comment]
> Those options are implemented in a strange way that their presence is checked via `ifdef` historically, so they should be omitted to disable.

Valid advice for a pure `make` build, but not an issue for the cmake build system I think.

**Comment by yurivict** [comment]
I think, in the port these options should just be permanently set to ```ON```. If they are ```OFF```, then the CPU type should be selectable and there's really no place for the CPU type in the port.

**Comment by brada4** [comment]
As you prefer, current port has place to build for current cpu too.
