### ISSUE TITLE
can't use multiple threads on Android

### ISSUE THREAD

**Issue by herbakamil** [xianyi/OpenBLAS#1783]
I'm doing some benchmarks and can't run multithread version on Android ARM64.

On x86 when I increase threads I see that more cores are busy.
`openblas_set_num_threads(threads);`
`cblas_sgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans, N, N, M, 1, A, N, B, N, 0, C, N);`

On Android only 1 core is used.
I followed first part of https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android
I'm using Android toolchain for arm64 api 24.
building lib
`make TARGET=ARMV8 BINARY=64 HOSTCC=gcc CC=aarch64-linux-android-gcc NOFORTRAN=1 -j7`

building benchmark
`$CXX -o benchmark_blas_arm64 benchmark_blas.cpp -I /home/kamil/tools/OpenBLAS_android/include/ -L/home/kamil/tools/OpenBLAS_android/lib -lopenblas -std=c++11 -pie`

**Comment by brada4** [comment]
Please check here, for very small inputs extra threads will not be employed.
https://github.com/xianyi/OpenBLAS/blob/544b069e85254d41699afde16e2e81c123cb5f28/interface/gemm.c#L413
Still attached debugger will show that threads are started.

**Comment by herbakamil** [comment]
Can it be that threads are used on x86 for matrices of certain size and Android version waits for bigger data? I will check for matrices of size 5k x 5k

**Comment by brada4** [comment]
~~What was the build command exactly?~~ it is incomplete. 
Did you specify target core numbers e.g. NUM_THREADS=4 when building? Or at least had at least that many cores in build system.
What thread number is returned from openblas_get_num_threads()?

Threshold is same for all architectures. You can disable it by commenting few lines for tests.

**Comment by brada4** [comment]
Your recent tengine post says you are oversubscribing cores if you use multi-processor openblas.
I think there is nothing to fix unless you get short representative code of your problem, or at least backtraces (t a a bt)

**Comment by martin-frbg** [comment]
Actually not sure what value of NUM_THREADS the build system will pick by itself when cross-compiling via the NDK. Does building with NUM_THREADS=4 (as brada4 suggested) help, and do you see any indication at all that your current libopenblas.so is built with threads support ?

**Comment by herbakamil** [comment]
**I haven't set NUM_THREADS=4 when building.**
In case of x86 `openblas_set_num_threads(threads);` was enough.
**Tomorrow I will try recompiling with NUM_THREADS set to something.**

Regarding code the essential part in main() is
`openblas_set_num_threads(threads);`
`cblas_sgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans, N, N, M, 1, A, N, B, N, 0, C, N);`
Rest is just variable creation and printing.

and building of the code is:

`PATH=~/tools/android-arm64-api-24-1/bin:$PATH`
`CXX=aarch64-linux-android-g++`
`$CXX -o benchmark_blas_arm64 benchmark_blas.cpp -I /home/kamil/tools/OpenBLAS_android/include/ -L/home/kamil/tools/OpenBLAS_android/lib -lopenblas -std=c++11 -pie`

**In Tengine I had problem that (de)convolution in cblas_sgemm haven't been using multiple cores. So I've decided to learn how to use multiple cores in cblas_sgemm on small benchmark application and I'm able to use many cores in x86 but not in arm64.**

Tomorrow I will try to compile it on arm32 and will see what will be the results.
Anyway if anyone has some examples of correct linking of C++ applications to run on arm64 or library build which for sure is able to use multiple cores on arm64 I'd be grateful if I could use it :)

I will run my tests and later let you know what are results

**Comment by brada4** [comment]
x86_64 is native build, i.e tailored for CPUs in current system.
as said - hard to tell how many CPUs get detected cross-building , especially if you use build robot, it may have just one virtual CPU.

to make any effect of -j parameter of make you need to set MAKE_NB_JOBS=-1

**Comment by herbakamil** [comment]
I'm not sure what has helped but now multiplication on multiple cores works :)
Thanks for the consultation!

**Comment by martin-frbg** [comment]
Great (though it would have been good to know if there is something missing in the wiki instructions, or if there are any hidden pitfalls in the approach detailed there).
