### ISSUE TITLE
Build error on Cray machines

### ISSUE THREAD

**Issue by jczhang07** [xianyi/OpenBLAS#1790]
On a Cray machine, I built OpenBLAS 0.3.3 with
  
make CC=cc CXX=CC FC=ftn
  
and finally got an error as follows. I do need static libraries as this is Cray's default.

perl ./gensymbol linktest  x86_64 _ 0 0 0 0 0 0 "" "" 1 > linktest.c
...
/usr/bin/ld: attempted static link of dynamic object `../libopenblas_haswellp-r0.3.4.dev.so'
Makefile:145: recipe for target '../libopenblas_haswellp-r0.3.4.dev.so' failed
make[1]: *** [../libopenblas_haswellp-r0.3.4.dev.so] Error 1
make[1]: Leaving directory '/global/u1/j/jczhang/OpenBLAS/exports'
Makefile:101: recipe for target 'shared' failed
make: *** [shared] Error 2

**Comment by martin-frbg** [comment]
Don't you have the libopenblas_haswellp-r0.3.4.dev.a ? The `make` builds will (try to) create both shared and dynamic libraries by default, and the static one is built first. (You can try `make NO_SHARED=1` to avoid hitting the error at the end - see Makefile.rule for a description of all options)

**Comment by martin-frbg** [comment]
A quick search brought up https://github.com/LLNL/GOTCHA/issues/41 with a suggested fix (by setting two environment variables), not sure if it is appropriate for your case though.

**Comment by jczhang07** [comment]
Yes, I saw both libopenblas_haswellp-r0.3.4.dev.a and libopenblas_haswellp-r0.3.4.dev.so
I was wondering if the build system can select the right library to link, or ignore the wrong one and proceed, so that when OpenBLAS is included and built by another library, it won't block that library's build.

**Comment by martin-frbg** [comment]
Sounds like using `make NO_SHARED=1` (or in your case `make CC=cc CXX=CC FC=ftn NO_SHARED=1`) to build only the static OpenBLAS library is the right solution for you then ?

**Comment by jczhang07** [comment]
Yes, "make CC=cc CXX=CC FC=ftn NO_SHARED=1" works for me.
I also tried "make CC=cc CXX=CC FC=ftn NO_STATIC=1".  Both the static and dynamic libraries were built and the same link error showed up.
It would be nice if OpenBLAS could auto-detect the build type and do the right linking.

**Comment by martin-frbg** [comment]
I think the static library is built in any case, and is used in generating the shared library. The NO_STATIC option is only about _installing_ that version of the library. We could probably make NO_SHARED the default on Cray if there is some way to autodetect this platform (but from the ticket I linked to it is not clear what "do the right linking" would be in general). There is no way for the OpenBLAS build system to "know" that it is called in the context of building another, static library - perhaps if OpenBLAS is "included and built" by another library the build system of that library should
be changed to pass `NO_DYNAMIC=1` to its make command for OpenBLAS .
