### ISSUE TITLE
disable avx512 on msys2 mingw64

### ISSUE THREAD

**Issue by hjbreg** [xianyi/OpenBLAS#1801]
workaround #1717 for avx512 on cygwin in #1708 does not work for msys2 mingw64
building OpenBLAS on 64-bit windows with msys2 failed with the same error message
Error: invalid register for .seh_savexmm

**Comment by martin-frbg** [comment]
Does it work when you add the ` -fno-asynchronous-unwind-tables` option to CFLAGS ? (The CYGWIN_NT condition may not trigger for msys2, though I have not checked this yet - probably needs to be something like `ifeq ($(OS), WINNT)...ifeq($(C_COMPILER),GCC)` to match msys2/mingw64)

**Comment by hjbreg** [comment]
Building successfully with CFLAGS=-fno-asynchronous-unwind-tables.
In MSYS2 MinGW 64-bit launcher, uname output MINGW64_NT-10.0, for your reference.
There is also another workaround in JuliaLang/julia@651a727a201e08aa1e2aa8d9007a7088cbbdc997
