### ISSUE TITLE
cross-compile OpenBLAS with lapack error

### ISSUE THREAD

**Issue by kimparksama** [xianyi/OpenBLAS#1811]
error as follows:

In file included from ../include/lapacke.h:41:0,
                 from ../include/lapacke_utils.h:37,
                 from lapacke_cbdsqr_work.c:34:
../include/lapacke_config.h:92:21: fatal error: complex.h: No such file or directory
 #include <complex.h>
                     ^
In file included from ../include/lapacke.h:41:0,
                 from ../include/lapacke_utils.h:37,
                 from lapacke_cbdsqr.c:34:
../include/lapacke_config.h:92:21: fatal error: complex.h: No such file or directory
 #include <complex.h>
                     ^
compilation terminated.
compilation terminated.
In file included from ../include/lapacke.h:41:0,
                 from ../include/lapacke_utils.h:37,
                 from lapacke_cgbcon.c:34:
../include/lapacke_config.h:92:21: fatal error: complex.h: No such file or directory
 #include <complex.h>
                     ^
compilation terminated.
In file included from ../include/lapacke.h:41:0,
                 from ../include/lapacke_utils.h:37,
                 from lapacke_cbbcsd.c:34:
../include/lapacke_config.h:92:21: fatal error: complex.h: No such file or directory
 #include <complex.h>
                     ^
compilation terminated.
In file included from ../include/lapacke.h:41:0,
                 from ../include/lapacke_utils.h:37,
                 from lapacke_cbbcsd_work.c:34:
../include/lapacke_config.h:92:21: fatal error: complex.h: No such file or directory
 #include <complex.h>
                     ^
compilation terminated.
Makefile:2476: recipe for target 'lapacke_cgbcon.o' failed
make[3]: *** [lapacke_cgbcon.o] Error 1
make[3]: *** Waiting for unfinished jobs....
Makefile:2476: recipe for target 'lapacke_cbdsqr_work.o' failed
make[3]: *** [lapacke_cbdsqr_work.o] Error 1
Makefile:2476: recipe for target 'lapacke_cbdsqr.o' failed
make[3]: *** [lapacke_cbdsqr.o] Error 1
Makefile:2476: recipe for target 'lapacke_cbbcsd.o' failed
make[3]: *** [lapacke_cbbcsd.o] Error 1
In file included from ../include/lapacke.h:41:0,
                 from ../include/lapacke_utils.h:37,
                 from lapacke_cgbbrd.c:34:
../include/lapacke_config.h:92:21: fatal error: complex.h: No such file or directory
 #include <complex.h>
                     ^
compilation terminated.
Makefile:2476: recipe for target 'lapacke_cbbcsd_work.o' failed
make[3]: *** [lapacke_cbbcsd_work.o] Error 1
Makefile:2476: recipe for target 'lapacke_cgbbrd.o' failed
make[3]: *** [lapacke_cgbbrd.o] Error 1
In file included from ../include/lapacke.h:41:0,
                 from ../include/lapacke_utils.h:37,
                 from lapacke_cgbbrd_work.c:34:
../include/lapacke_config.h:92:21: fatal error: complex.h: No such file or directory
 #include <complex.h>
                     ^
compilation terminated.
In file included from ../include/lapacke.h:41:0,
                 from ../include/lapacke_utils.h:37,
                 from lapacke_cgbequb.c:34:
../include/lapacke_config.h:92:21: fatal error: complex.h: No such file or directory
 #include <complex.h>
                     ^
compilation terminated.
In file included from ../include/lapacke.h:41:0,
                 from ../include/lapacke_utils.h:37,
                 from lapacke_cgbcon_work.c:34:
../include/lapacke_config.h:92:21: fatal error: complex.h: No such file or directory
 #include <complex.h>
                     ^
compilation terminated.
In file included from ../include/lapacke.h:41:0,
                 from ../include/lapacke_utils.h:37,
                 from lapacke_cgbequb_work.c:34:
../include/lapacke_config.h:92:21: fatal error: complex.h: No such file or directory
 #include <complex.h>
                     ^
compilation terminated.
Makefile:2476: recipe for target 'lapacke_cgbequb.o' failed
make[3]: *** [lapacke_cgbequb.o] Error 1
Makefile:2476: recipe for target 'lapacke_cgbbrd_work.o' failed
make[3]: *** [lapacke_cgbbrd_work.o] Error 1
Makefile:2476: recipe for target 'lapacke_cgbcon_work.o' failed
make[3]: *** [lapacke_cgbcon_work.o] Error 1
Makefile:2476: recipe for target 'lapacke_cgbequb_work.o' failed
make[3]: *** [lapacke_cgbequb_work.o] Error 1
In file included from ../include/lapacke.h:41:0,
                 from ../include/lapacke_utils.h:37,
                 from lapacke_cgbequ_work.c:34:
../include/lapacke_config.h:92:21: fatal error: complex.h: No such file or directory
 #include <complex.h>
                     ^
compilation terminated.
In file included from ../include/lapacke.h:41:0,
                 from ../include/lapacke_utils.h:37,
                 from lapacke_cgbequ.c:34:
../include/lapacke_config.h:92:21: fatal error: complex.h: No such file or directory
 #include <complex.h>
                     ^
compilation terminated.
Makefile:2476: recipe for target 'lapacke_cgbequ_work.o' failed
make[3]: *** [lapacke_cgbequ_work.o] Error 1
Makefile:2476: recipe for target 'lapacke_cgbequ.o' failed
make[3]: *** [lapacke_cgbequ.o] Error 1
make[3]: Leaving directory '/home/ubuntu/Downloads/OpenBLAS-0.3.3/lapack-netlib/LAPACKE/src'
Makefile:48: recipe for target 'lapacke' failed
make[2]: *** [lapacke] Error 2
make[2]: Leaving directory '/home/ubuntu/Downloads/OpenBLAS-0.3.3/lapack-netlib/LAPACKE'
Makefile:24: recipe for target 'lapackelib' failed
make[1]: *** [lapackelib] Error 2
make[1]: Leaving directory '/home/ubuntu/Downloads/OpenBLAS-0.3.3/lapack-netlib'
Makefile:225: recipe for target 'netlib' failed
make: *** [netlib] Error 2

i use command line:

make ARM_SOFTFP_ABI=1 TARGET=ARMV7 CFLAGS=--sysroot=$NDK/platforms/android-19/arch-arm HOSTCC=gcc CC=arm-linux-androideabi-gcc FC=arm-linux-androideabi-gfortran USE_THREAD=1 USE_OPENMP=1 USE_LAPACK=1 

- 

-

**Comment by brada4** [comment]
complex.h is in posix for 10 years, and in visual studio since 2015
As a quick fix you may disable LAPACKE but leave rest intact (see Makefile.rule for tips)
But normally search for complex.h on your file system, usually it is in libc/libm development headers, not part of compiler.

**Comment by martin-frbg** [comment]
Did you use a standalone toolchain as suggested in the wiki ? That should make it easier to access all the required header files etc automatically.

**Comment by ronyuzhang** [comment]
lapack's static package(.a) be included in linOpenBlas.a ? @martin-frbg

**Comment by ronyuzhang** [comment]
i found only a libopenblas.a in install dir,

**Comment by martin-frbg** [comment]
Yes. (You can do `ar -t libopenblas.a` to see the modules it contains)

**Comment by ronyuzhang** [comment]
but， when i build android native app， i encounter a problem， as follows：

../../../../libs/armeabi-v7a/libopenblas.a(dormlq.o):dormlq.f:function dormlq_: error: undefined reference to '_gfortran_concat_string'
../../../../libs/armeabi-v7a/libopenblas.a(dormlq.o):dormlq.f:function dormlq_: error: undefined reference to '_gfortran_concat_string'
../../../../libs/armeabi-v7a/libopenblas.a(dormqr.o):dormqr.f:function dormqr_: error: undefined reference to '_gfortran_concat_string'
../../../../libs/armeabi-v7a/libopenblas.a(dormqr.o):dormqr.f:function dormqr_: error: undefined reference to '_gfortran_concat_string'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

i use a static libs named  "libopenblas.a " , why static libs lost fortran libs? @martin-frbg

**Comment by martin-frbg** [comment]
static lib does not contain the fortran runtime library, your app needs to link to that as well.

**Comment by ronyuzhang** [comment]
thank you,  openblas and lapack can work well.

**Comment by martin-frbg** [comment]
Great. Now back to kimparksama's original issue...

**Comment by brada4** [comment]
@kimparksama could you attach full build log?
Android NDK does not provide OpenMP for example

**Comment by christoph-conrads** [comment]
> error as follows:
> 
> In file included from ../include/lapacke.h:41:0,
> from ../include/lapacke_utils.h:37,
> from lapacke_cbdsqr_work.c:34:
> ../include/lapacke_config.h:92:21: fatal error: complex.h: No such file or directory
> #include <complex.h>
> ^
> [snip]

@kimparksama I think you hit OpenBLAS issue #682. Try this (note the modified `CFLAGS`):
```
make \
  ARM_SOFTFP_ABI=1 TARGET=ARMV7 \
  CFLAGS="-DFORCE_OPENBLAS_COMPLEX_STRUCT -DLAPACK_COMPLEX_STRUCTURE -DHAVE_LAPACK_CONFIG_H --sysroot='$NDK/platforms/android-19/arch-arm'" \
  HOSTCC=gcc \
  CC=arm-linux-androideabi-gcc \
  FC=arm-linux-androideabi-gfortran \
  USE_THREAD=1 USE_OPENMP=1 USE_LAPACK=1
```

**Comment by martin-frbg** [comment]
Good catch, it seems the fix to LAPACKE/include/lapacke_config.h from #778 got nuked (again) with the update of lapack-netlib to 3.7.0 two years ago (and would probably have been hit by my subsequent 3.8 updates if there had been any changes)
