### ISSUE TITLE
compile error win-x64

### ISSUE THREAD

**Issue by nyon-one** [xianyi/OpenBLAS#1818]
I don't know what went wrong or how to fix this please help
here is the error log

[errrr.log](https://github.com/xianyi/OpenBLAS/files/2478055/errrr.log)

**Comment by brada4** [comment]
The build log attached is partial without any error in it. 
`make clean`
Then (with some select parameters added to make resulting dll usable on other CPU types)
`make DYNAMIC_ARCH=1 NUM_TREADS=64 2>&1 1>..\build_output.txt`

**Comment by martin-frbg** [comment]
I do not see that anything went wrong, from your log the dll appears to have been created just fine ?
