### ISSUE TITLE
how to set OMP_NUM_THREADS? Use lapack dgels in multi-thread env.

### ISSUE THREAD

**Issue by ronyuzhang** [xianyi/OpenBLAS#1819]
W/linker: /data/app/com.example.mm.ss-2/lib/arm/libjniopenblas_nolapack.so: unused DT entry: type 0xf arg 0x9f29
I/System.out: Unable to tune runtime. Please set OMP_NUM_THREADS manually.

**Comment by martin-frbg** [comment]
According to the Android API documentation it seems to be possible to call os.setenv from java code.
(But the "unable to tune runtime" message is not created by OpenBLAS, perhaps ask the people who maintain the "other" code - I am guessing it is deeplearning4j as a google search for the message returned hits from their support chat ?)

**Comment by brada4** [comment]
I see this in my android log without using any OpenBLAS, if you read 'man 5 elf' on any linux system you see dozen types of descriptor table entries. Namely 0xf is DT_RPATH, which is not usable for any effect under android. The error is with format of your jni so file, not openblas itself. You can erase parameter with some elf editor to get rid of essentially harmless warning.

**Comment by brada4** [comment]
Second line message may have nothing to do with openblas. 
https://github.com/bytedeco/javacpp-presets/commit/d6c14b20ed48b1ec2490e16d2f7569d324bea0c0

**Comment by brada4** [comment]
I am afraid you posted in wrong forum. This is one that supplies your error message:
https://github.com/bytedeco/javacpp-presets/tree/master/openblas

**Comment by martin-frbg** [comment]
At a quick glance, that project appears to generate the error message when it does not find an entry point for openblas_set_num_threads in the openblas library. As this function should be present even in single-threaded builds, probably something went fundamentally wrong (like libopenblas.so.0 not being a link to the actual library).

**Comment by ronyuzhang** [comment]
this issue I use nd4j with openblas ， but now， I  use directly openblas without nd4j 3rd libs
