### ISSUE TITLE
Static libraries running in parallel but shared libraries not (USE_OPENMP=1)

### ISSUE THREAD

**Issue by rfkspada** [xianyi/OpenBLAS#1822]
Hi everybody,

I am linking openblas to my own code. I got the version from git today (17 Oct 2018) and compiled it with 

make USE_OPENMP=1

and I am setting:

export OMP_NUM_THREADS=4

My code use LAPACK routines (e.g. DSYEVX). It compiles fine for both libraries (static and shared). However the static ones run in parallel as expected (i.e. %CPU = 400 in top), but not the shared ones (i.e. %CPU = 100). The compile lines are as follows:

$ make shared:
gfortran -O2 -mavx2 -fopenmp src/eter-module.f90 src/spline.f90 src/eter-internal.f90 src/eter-files.f90 src/FDM.f90 src/Eter-Inten.f90 -o di-eter -I /opt/OpenBLAS/include -L/opt/OpenBLAS/lib -lopenblas

$ make static
 gfortran -O2 -mavx2 -fopenmp src/eter-module.f90 src/spline.f90 src/eter-internal.f90 src/eter-files.f90 src/FDM.f90 src/Eter-Inten.f90 -o di-eter -I /opt/OpenBLAS/include /opt/OpenBLAS/lib/libopenblas.a

I am using gfortran, so there is no need for -lgfortran and since I am using OpenMP there is no need for -lpthread. Is this right?

What am I missing?

Thanks

**Comment by martin-frbg** [comment]
One possible explanation for the misbehaviour of the "shared" build is that you have another libopenblas.so somewhere on the system, in a path that takes precedence over the one you put in /opt/OpenBLAS/lib. `ldd ./di-eter` should reveal what the loader does at runtime.

**Comment by brada4** [comment]
You can override "other" library with LD_PRELOAD=/opt/OpenBLAS/lib/libopenblas.so
You can run LD_DEBUG=all ./di-ether to see at least if all symbols come from same .so file (deviation could explain spectacular crashes, but not incidental single-threadness)
Another is if you use something of RPM breeds, than /usr/lib/libopenblas.so is single-threaded RPM, while pthread will be libopenblasp.so and OMP will be libopenblaso.so , and first taking over your explicit linking which actually just adds extra lib path, that is used if system finds no viable .so bu default (quick hit - `rpm -e libopenblas-single` )

**Comment by rfkspada** [comment]
From the ldd ./di-eter, the program was linking to a libopenblas.so in /usr/lib64. To link to the new compiled library in /opt/OpenBlas/lib, I just adjusted the Makefile to:

gfortran -O2 -mavx2 -fopenmp src/eter-module.f90 src/spline.f90 src/eter-internal.f90 src/eter-files.f90 src/FDM.f90 src/Eter-Inten.f90 -o di-eter -I /opt/OpenBLAS/include -L/opt/OpenBLAS/lib -Wl,-rpath=/opt/OpenBLAS/lib -lopenblas

Thank you very much.

**Comment by brada4** [comment]
Does this qualify for FAQ ?

**Comment by rfkspada** [comment]
> Does this qualify for FAQ ?

Actually I think it is a great idea. In my system, I can not uninstall the lib in /usr/lib64 since a lot of system packages relly on it. I think it is an Issue for other users also.

**Comment by brada4** [comment]
@rfkspada Do you want to try to add a new paragraph (no fine in doing wrong, it is always reversible):
https://github.com/xianyi/OpenBLAS/wiki/faq
@martin-frbg ;-)

**Comment by martin-frbg** [comment]
Added to FAQ.
