### ISSUE TITLE
Where is the implementation of cblas_sgemm() function? 

### ISSUE THREAD

**Issue by light82** [xianyi/OpenBLAS#1824]
I found that cblas_sgemm() was declared in cblas.h file,but I cannot find the implementation of it.Which file contains the implementation of this function? Thanks very much

**Comment by martin-frbg** [comment]
`interface/gemm.c` (with CBLAS and CNAME set from the Makefile), which then calls the appropriate function from `driver/level3` that in turn uses optimized GEMM kernels for the target CPU which are in `kernel/<architecture>/`. (With a `KERNEL.<cpuname>` file in each directory controlling how functions map to C or assembly implementations at build time). See "Developer manual" in the wiki (which should probably have a less impressive title as it is just a collection of short notes and references).

**Comment by tejainece** [comment]
Who managed to write it insuch an unfollowable retarded way? Whats all this CNAME gibberish all over the codebase?
