### ISSUE TITLE
so slowly, I excute lapack "dgels" spent 40-60 ms. how to excute faster?

### ISSUE THREAD

**Issue by ronyuzhang** [xianyi/OpenBLAS#1826]

**Comment by ronyuzhang** [comment]
cross-compiling openblas with lapack for android armeabi-v7a， and calling dgels by jni。

**Comment by martin-frbg** [comment]
So did you get #1819 solved ? Try to get some profiling data (by running perf or similar) from your code. 
With very few exceptions, OpenBLAS uses the unmodified, unoptimized (and non-parallelized) LAPACK routines from the netlib reference implementation. So the only speedup can be where the LAPACK functions make calls to BLAS, and matrix size will be important in this as for small sizes the
overhead from multithreading may exceed the computational advantage.

**Comment by brada4** [comment]
Android version of linux perf is called `simpleperf`
Doc is here:
https://developer.android.com/ndk/guides/simpleperf
Text that comes out of record/report pair is most interesting.
Also please post build parameters you used.

**Comment by brada4** [comment]
@ronyuzhang I assume you somehow passed build parameter NUM_THREADS=16 or something >= your actual target cores? It is hard to systematize, but cross-compilation sometimes takes builder core number, and some other times 1, but never ever target numbers.

**Comment by brada4** [comment]
... and let me doubt necessity of double precision on a mobile ... It can hardly get any natural measurement with range not covered by single precision, even less visualize or play back the result ...
Is casting to sgels of help?

**Comment by brada4** [comment]
@ronyuzhang we dont have crystal ball to guess how 60ms are mapped to BLAS functions that may have to be improved considering your LAPACK call...
