### ISSUE TITLE
compile error getarch_2nd.c w AMD 2950X

### ISSUE THREAD

**Issue by biohegedus** [xianyi/OpenBLAS#1835]
Hi,
I have the following error with AMD Ryzen Threadripper 2950X 16-Core Processor.
First, I used TARGET=ZEN, but reading [issue 1664](https://github.com/xianyi/OpenBLAS/issues/1664) I also tried TARGET=HASWELL.
What to do?
Thanks, Tamas

make -j16 TARGET=HASWELL
...
sudo make PREFIX=/opt/OpenBLAS-0.2.20 install

getarch_2nd.c: In function ‘main’:
getarch_2nd.c:12:35: error: ‘SGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function)
     printf("SGEMM_UNROLL_M=%d\n", SGEMM_DEFAULT_UNROLL_M);
...
getarch_2nd.c:69:50: error: ‘SGEMM_DEFAULT_Q’ undeclared (first use in this function)
     printf("#define SLOCAL_BUFFER_SIZE\t%ld\n", (SGEMM_DEFAULT_Q * SGEMM_DEFAULT_UNROLL_N * 4 * 1 *  sizeof(float)));
...

make: *** [getarch_2nd] Error 1
make -j 32 -f Makefile.install install
make[1]: Entering directory '/home/hegedus/src/OpenBLAS-0.2.20'
Generating openblas_config.h in /opt/OpenBLAS-0.2.20/include
Generating f77blas.h in /opt/OpenBLAS-0.2.20/include
Generating cblas.h in /opt/OpenBLAS-0.2.20/include
Copying the static library to /opt/OpenBLAS-0.2.20/lib
Copying the shared library to /opt/OpenBLAS-0.2.20/lib
Generating openblas.pc in /opt/OpenBLAS-0.2.20/lib/pkgconfig
Generating OpenBLASConfig.cmake in /opt/OpenBLAS-0.2.20/lib/cmake/openblas
Generating OpenBLASConfigVersion.cmake in /opt/OpenBLAS-0.2.20/lib/cmake/openblas
Install OK!

**Comment by martin-frbg** [comment]
Please try with current version 0.3.3 from https://github.com/xianyi/OpenBLAS/releases

**Comment by biohegedus** [comment]
Thanks, the compilation works if I define ZEN (I do not find any issue).
I use Debian for a decade, thus I became pretty conservative... :-)

**Comment by martin-frbg** [comment]
Did you have to define ZEN (that is, did autodetection fail for your TR2950) ?

**Comment by biohegedus** [comment]
I had to define ZEN.
Autodetection failed for RT2950X.

**Comment by martin-frbg** [comment]
Could you please post your /proc/cpuinfo then, so that its cpuid can be added to cpuid_x86.c ?

**Comment by biohegedus** [comment]
Sure.

processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 23
model           : 8
model name      : AMD Ryzen Threadripper 2950X 16-Core Processor
stepping        : 2
microcode       : 0x800820b
cpu MHz         : 2200.000
cache size      : 512 KB
physical id     : 0
siblings        : 32
core id         : 0
cpu cores       : 16
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc extd_apicid amd_dcm aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_l2 mwaitx cpb hw_pstate ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf amd_ibpb arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic overflow_recov succor smca
bugs            : fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass
bogomips        : 6986.50
TLB size        : 2560 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate cpb eff_freq_ro [13] [14]

**Comment by martin-frbg** [comment]
Strange - this (family 15 + extended family 8 == 23, model 8) should already be detected since 0.3.2.

**Comment by biohegedus** [comment]
I got openblas as:
git clone https://github.com/xianyi/OpenBLAS.git
I do not see the version of the cloned openblas, but I guess it is the most recent.

make
Makefile:135: *** OpenBLAS: Detecting CPU failed. Please set TARGET explicitly, e.g. make TARGET=your_cpu_target. Please read README for the detail..  Stop.

**Comment by biohegedus** [comment]
Yes, it is 0.3.4
libopenblas_zenp-r0.3.4.dev.so

**Comment by martin-frbg** [comment]
Sorry, #1665 was incomplete - it does detect the cputype correctly, but fails to set CORE in Makefile.conf
