### ISSUE TITLE
stdlib.h not found

### ISSUE THREAD

**Issue by gigadeplex** [xianyi/OpenBLAS#1838]
/include/lapacke_config.h:44:20: fatal error: stdlib.h: No such file or directory
 #include <stdlib.h>

Been trying to solve this for some time now.. full command is: 
"mingw32-make TARGET=ARMV7 HOSTCC=gcc CC=arm-linux-androideabi-gcc FC=arm-linux-androideabi-gfortran ARM_SOFTFP_ABI=1 CFLAGS=--sysroot=%NDK%/sysroot" I tried changing ndk to r13 to use android-16. I'm very new to this so please excuse me if this has a simple fix.

**Comment by brada4** [comment]
If you google for particular error you find the way to provide extra flags for android C compiler to work.
Most likely your sysroot setting is wrong, it has to be a directory with ./usr/include/stdlib.h file present.
https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android

**Comment by gigadeplex** [comment]
Thanks, I had a few other things wrong as well but I got it working.. just my lack of knowledge compiling haha
