### ISSUE TITLE
Compilation errors: bad register name

### ISSUE THREAD

**Issue by manavbhatia** [xianyi/OpenBLAS#1841]
Hi, 
   I am attempting to build openblas with [spack](https://github.com/spack/spack). I have tried two different compilers gcc8.2 and gcc7.3 and each time have ended up with errors concerning ```bad register name``` . For example, 
```
../kernel/x86_64/sgemm_kernel_16x4_skylakex.S: Assembler messages:
../kernel/x86_64/sgemm_kernel_16x4_skylakex.S:1311: Error: bad register name `%zmm0'
../kernel/x86_64/sgemm_kernel_16x4_skylakex.S:1311: Error: bad register name `%zmm2'
../kernel/x86_64/sgemm_kernel_16x4_skylakex.S:1311: Error: bad register name `%zmm3'
../kernel/x86_64/sgemm_kernel_16x4_skylakex.S:1311: Error: bad register name `%zmm2'
../kernel/x86_64/sgemm_kernel_16x4_skylakex.S:1311: Error: bad register name `%zmm3'
../kernel/x86_64/sgemm_kernel_16x4_skylakex.S:1311: Error: bad register name `%zmm7'
../kernel/x86_64/sgemm_kernel_16x4_skylakex.S:1311: Error: bad register name `%zmm9'
../kernel/x86_64/sgemm_kernel_16x4_skylakex.S:1311: Error: bad register name `%zmm7'
../kernel/x86_64/sgemm_kernel_16x4_skylakex.S:1311: Error: bad register name `%zmm9'
```

The detailed errors are in [error.txt](https://github.com/xianyi/OpenBLAS/files/2530621/error.txt). 

I would greatly appreciate advice on how to deal with them. 

Thanks,
Manav

**Comment by martin-frbg** [comment]
To me this looks as if your assembler may be too old, or perhaps you need to set up AS to point to the spack version of `gas` like you did with CC ?

**Comment by brada4** [comment]
You need binutils 2.25 or better and gcc 5 or better
```
$ as --version
GNU assembler (GNU Binutils; openSUSE Leap 15.0) *2.31*.1.20180828-lp150.5.3
$ gcc -march=skylake-avx512 --version
gcc (SUSE Linux) *7*.3.1 20180323 [gcc-7-branch revision 258812]
```
As Martin already noted - gas or as included in binutils gets called by gcc and chokes on modern registers that compiler emits with `-march` flag noted above

@martin-frbg is it worth c_ceck-ing also with short assembly like `and zmm32` ?

**Comment by brada4** [comment]
@manavbhatia probably it is worth bringing this issue to spack developers that gcc is not functional with archaic host binutils.
@martin-frbg i think I adressed at least popular part of particular problem (Ubuntu14 has old compiler but fresh binutils):
https://github.com/xianyi/OpenBLAS/wiki/Faq#binutils

**Comment by martin-frbg** [comment]
@brada4 I do not think this is a problem with spack in particular - just that sometimes updating one package is not sufficient to receive some particular new functionality. I think this assembler problem came up before, probably when the Haswell kernels brought AVX2 mnemonics (and one could not say that rpm or apt-get were at fault back then either)

**Comment by brada4** [comment]
Old systems do not have right tools to do the job. I wonder how this slipped past initial AVX512 compiler detection which invokes `as` before proceeding.

**Comment by martin-frbg** [comment]
@manavbhatia did you manage to solve this ?
@brada4 I suspect he specified TARGET=SKYLAKEX, which overrides the fallback to HASWELL. And the later safeguards in the SkylakeX microkernels (where available) are based on compiler version only.
