### ISSUE TITLE
OpenBLAS Cross compile error

### ISSUE THREAD

**Issue by icandoithj** [xianyi/OpenBLAS#1842]
I use ARM architecture on Embedded Linux platform.
The Embedded Linux kernel version used in my device is 3.4.39.
Processor is Cortex-A9 Quad Core CPU @ 1.4GHz

I downloaded OpenBLAS v0.3.3 and built the following error.
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#make CC=arm-cortex_a9-linux-gnueabi-gcc FC=arm-cortex_a9-linux-gnueabi-gfortran HOSTCC=gcc TARGET=CORTEXA9
.......................
(omission)
......................
cblat2.f: In function ‘cchk1’:
cblat2.f:398:0: warning: ‘nargs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
sblat2.f: In function ‘schk1’:
sblat2.f:391:0: warning: ‘nargs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
zblat2.f: In function ‘zchk1’:
zblat2.f:399:0: warning: ‘nargs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
dblat2.f: In function ‘dchk2’:
dblat2.f:732:0: warning: ‘nargs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
cblat2.f: In function ‘cchk2’:
cblat2.f:743:0: warning: ‘nargs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
zblat2.f: In function ‘zchk2’:
zblat2.f:745:0: warning: ‘nargs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
sblat2.f: In function ‘schk2’:
sblat2.f:732:0: warning: ‘nargs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
dblat2.f: In function ‘dchk3’:
dblat2.f:1075:0: warning: ‘nargs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
zblat2.f: In function ‘zchk3’:
zblat2.f:1094:0: warning: ‘nargs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
cblat2.f: In function ‘cchk3’:
cblat2.f:1091:0: warning: ‘nargs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
sblat2.f: In function ‘schk3’:
sblat2.f:1075:0: warning: ‘nargs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
dblat2.f: In function ‘dchk5’:
dblat2.f:1864:0: warning: ‘nargs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
zblat2.f: In function ‘zchk5’:
zblat2.f:1912:0: warning: ‘nargs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
dblat2.f: In function ‘dchk6’:
dblat2.f:2166:0: warning: ‘nargs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
cblat2.f: In function ‘cchk5’:
cblat2.f:1906:0: warning: ‘nargs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
sblat2.f: In function ‘schk5’:
sblat2.f:1864:0: warning: ‘nargs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
zblat2.f: In function ‘zchk6’:
zblat2.f:2220:0: warning: ‘nargs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
cblat2.f: In function ‘cchk6’:
cblat2.f:2213:0: warning: ‘nargs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
sblat2.f: In function ‘schk6’:
sblat2.f:2166:0: warning: ‘nargs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/opt/arm-cortex_a9-eabi-4.7-eglibc-2.18/bin/arm-cortex_a9-linux-gnueabi-gfortran -O2 -marm -Wall  -mfpu=vfpv3 -march=armv7-a  -o sblat1 sblat1.o ../libopenblas_armv7p-r0.3.3.a -lm -lpthread -lm -lpthread -L/home/pjsin/devel/tools/crosstools/ct/linaro-1.13.1-4.8-2013.11/.build/arm-cortex_a9-linux-gnueabi/build/static/lib -L/opt/arm-cortex_a9-eabi-4.7-eglibc-2.18/bin/../lib/gcc/arm-cortex_a9-linux-gnueabi/4.7.4 -L/opt/arm-cortex_a9-eabi-4.7-eglibc-2.18/bin/../lib/gcc -L/opt/arm-cortex_a9-eabi-4.7-eglibc-2.18/bin/../lib/gcc/arm-cortex_a9-linux-gnueabi/4.7.4/../../../../arm-cortex_a9-linux-gnueabi/lib -L/opt/arm-cortex_a9-eabi-4.7-eglibc-2.18/bin/../arm-cortex_a9-linux-gnueabi/sysroot/lib -L/opt/arm-cortex_a9-eabi-4.7-eglibc-2.18/bin/../arm-cortex_a9-linux-gnueabi/sysroot/usr/lib  -lstdc++ -lm -lpwl -lc  
/opt/arm-cortex_a9-eabi-4.7-eglibc-2.18/bin/../lib/gcc/arm-cortex_a9-linux-gnueabi/4.7.4/../../../../arm-cortex_a9-linux-gnueabi/bin/ld.bfd: cannot find -lpwl
collect2: error: ld returned 1 exit status
Makefile:134: recipe for target 'sblat1' failed
make[1]: *** [sblat1] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/go/download/xianyi-OpenBLAS-fd8d186/test'
Makefile:123: recipe for target 'tests' failed
make: *** [tests] Error 2
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

Does anyone know about this?
Please reply.

**Comment by brada4** [comment]
given you made first mention of libpwl.so used with openblas - maybe take care to explain what it is and what it does on your target system.

**Comment by martin-frbg** [comment]
Haven't seen this before, this libpwl could be a requirement of your specific platform. (Search results point to a "Parma Watchdog Library", you probably need to install a package named pwl-dev or similar)

**Comment by brada4** [comment]
.... and tests need the static library thereof - most likely called libpwl.a

**Comment by icandoithj** [comment]
Thank you, everyone.
I solved problem that libpwl by making dummy library.
