### ISSUE TITLE
dgelss vs sgelss

### ISSUE THREAD

**Issue by mattharrigan** [xianyi/OpenBLAS#1859]
I think that [sgelss](https://github.com/xianyi/OpenBLAS/blob/develop/lapack-netlib/SRC/sgelss.f#L410) should be similar to [dgelss](https://github.com/xianyi/OpenBLAS/blob/develop/lapack-netlib/SRC/dgelss.f#L414).  However the last parameter is different, 1 vs MINMN.  Although not certain, I think this may be a bug.  Thank you

**Comment by martin-frbg** [comment]
I think you are correct, I'll raise the issue with the netlib a.k.a https://github.com/Reference-LAPACK/lapack project from which OpenBLAS imports LAPACK. Looks like it has been that way for ten years at least, but then it "only" affects zeroing of a result array in an error path (where older FORTRAN would probably initialize it to zero anyway).
