### ISSUE TITLE
Build broken on OS X Mojave

### ISSUE THREAD

**Issue by dlfivefifty** [xianyi/OpenBLAS#1862]
```julia
Warning: 'nargs' may be used uninitialized in this function [-Wmaybe-uninitialized]
cblat2.f:435:0:

      $                   LDAS, LX, LY, M, ML, MS, N, NARGS, NC, ND, NK,
 
Warning: 'nargs' may be used uninitialized in this function [-Wmaybe-uninitialized]
gfortran -O2 -m128bit-long-double -Wall -frecursive -m64   -o sblat1 sblat1.o ../libopenblas_haswellp-r0.3.4.dev.a -lpthread -lgfortran -lpthread -lgfortran -lto_library -lSystem  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/lib/darwin/libclang_rt.osx.a 
ld: library not found for -lSystem
collect2: error: ld returned 1 exit status
make[1]: *** [sblat1] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [tests] Error 2
```

**Comment by dlfivefifty** [comment]
I think this is the key, from the XCode 10 [release notes](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes) (still need to see if I can get it working):
> The Command Line Tools package installs the macOS system headers inside the macOS SDK. Software that compiles with the installed tools will search for headers within the macOS SDK provided by either Xcode at:
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk
```
> or the Command Line Tools at:
```
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
```
> depending on which is selected using xcode-select.
The command line tools will search the SDK for system headers by default. However, some software may fail to build correctly against the SDK and require macOS headers to be installed in the base system under /usr/include. If you are the maintainer of such software, we encourage you to update your project to work with the SDK or file a bug report for issues that are preventing you from doing so. As a workaround, an extra package is provided which will install the headers to the base system. In a future release, this package will no longer be provided. You can find this package at:
```
/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
```
>  To make sure that you're using the intended version of the command line tools, run xcode-select -s <path to Xcode> or xcode select -s /Library/Developer/CommandLineTools after installing.

**Comment by brada4** [comment]
`export MACOSX_DEPLOYMENT_TARGET=10.8`
Either install sdk matching oldest practically supportable osx or change above line in Makefile.system acknowledging it will not work on other compiters.

**Comment by brada4** [comment]
According to same release notes Xcode 10 supports OSX 10.6 or better but only 64bit applications.
You have to use command line tools to download old SDK-s and you need Xcode9 to make 32bit applications.

**Comment by martin-frbg** [comment]
@brada4 I do not see him trying to build for 32bit ?
@dlfivefifty  isn't that essentially the same problem you had in https://github.com/JuliaLang/julia/issues/23962 a year ago (where a `brew rebuild gcc` was the solution apparently) ?

**Comment by dlfivefifty** [comment]
Ah, thanks for the tip. This time I deleted my /usr/local and started Homebrew from scratch and works now.

**Comment by brada4** [comment]
Probably OSX SDK version should be brought to Makefile.rule, because GUI offers only one previous version though can support much older ones (-lSystem)

**Comment by ChaiBapchya** [comment]
Above mentioned steps didn't work for me.
Firstly - 
`brew rebuild` is not a valid command (atleast for `openblas` which was my usecase)
I had to do - `brew list | xargs brew reinstall --build-from-source` to recompile all brew installed packages.

What worked for me was header installer for Mac OS SDK 10.14 Mojave - 
https://silvae86.github.io/sysadmin/mac/osx/mojave/beta/libxml2/2018/07/05/fixing-missing-headers-for-homebrew-in-mac-osx-mojave/

**Comment by brada4** [comment]
brew binaries were built for older OSX, and you refused to install old -lSystem , but instead upgraded everything to your system. On the other side of wire brew creates packages that are universally useful.

**Comment by ChaiBapchya** [comment]
Sequence of events
Mac recommended upgrading OS from HighSierra to Mojave. I did it. And that's about it.
Didn't quite get your point about "refusing to install old -ISystem" Where was this option asked? Just curious.

**Comment by brada4** [comment]
You could install older OSX headers to complement your brand new Xcode matching those used for brew and build just happy. It is not specific to OpenBLAS, brew rebuilds for same version as rest of their packages unless you do local build of brew itself and its configuration against current -lSystem.
