### ISSUE TITLE
Typo `iUNSAFE` ?

### ISSUE THREAD

**Issue by zerothi** [xianyi/OpenBLAS#1872]
https://github.com/xianyi/OpenBLAS/blob/ecbeb802a0d3b3f32430e618bd0a882320f41015/driver/level2/gemv_thread.c#L168

I believe there is a typo here?

**Comment by zerothi** [comment]
@martin-frbg

**Comment by martin-frbg** [comment]
Hehe. Sponsored by Apple probably. At least it landed in a totally harmless spot where it would only create an unused variable (and possibly a compiler warning about same).

**Comment by zerothi** [comment]
hehe.. ;-)

**Comment by brada4** [comment]
Probably not so shiny, and true sponsor is vim editor...
It is actually an unused diagnostic parameter and could be wiped out of file.

**Comment by martin-frbg** [comment]
Not unused. It is a flag that is set when the splitting code did not "goto Outer" due to the size of the matrix. I'll clean it up later today or tomorrow.

**Comment by martin-frbg** [comment]
Actually fixed right away by a direct edit rather than going through all the PR stuff. Thanks for spotting this.

**Comment by zerothi** [comment]
@martin-frbg this was why I didn't do a PR (much easier I suspected ;))

**Comment by zerothi** [comment]
Thanks!
