### ISSUE TITLE
ThunderX build broken

### ISSUE THREAD

**Issue by rengolin** [xianyi/OpenBLAS#1873]
It seems the build for ThunderX is broken, with undefined symbol errors:
```
undefined reference to `sgemm_incopy'
```
Tracing back to `KERNEL.THUNDERX`, it doesn't define such symbol, while other ARM arches do. But it seems that this is only defined when:
```
ifneq ($(CGEMM_UNROLL_M), $(CGEMM_UNROLL_N))
```
which is not the case for ThunderX, so it should not be defined anyway. But the test tries to link against it.

It's possible that the previous ThunderX change added something else that needed/used it and the symbol is being called but not defined:
```
# objdump -t libopenblas_thunderx-r0.3.4.dev.a | grep sgemm_incopy
0000000000000000         *UND*	0000000000000000 sgemm_incopy
0000000000000000         *UND*	0000000000000000 sgemm_incopy
```
My knowledge of the intricate include system is still not on par to solve this issue.

**Comment by martin-frbg** [comment]
Make sure that you did a `make clean` before that build to get rid of any artifacts from any previous builds for different targets. I do not see any problems when building the current develop branch with TARGET=THUNDERX (though on lowly A57 hardware)

**Comment by rengolin** [comment]
I always do make clean. I'll try to reproduce it on different machines and will try your example code and come back to you, thanks.

**Comment by rengolin** [comment]
Apologies, my `develop` branch wasn't clean. That was after hundreds of builds on multiple machines and it was Friday night, but still, I'm a little embarrassed. :)
