### ISSUE TITLE
How to check number of threads at runtime? Some function like openblas_get_num_threads

### ISSUE THREAD

**Issue by SuperFluffy** [xianyi/OpenBLAS#1874]
For setting the number of threads dynamically/at runtime, we have `openblas_set_num_threads`. I would also like to be able to inspect how many threads openblas is set to use. Is there a way to do that?

`openblas_get_parallel` only returns if openblas is compiled with the ability to run in parallel, `openblas_get_config` only gives me compile time information.

It would be nice if we had a sibling to `openblas_set_num_threads` called `openblas_get_num_threads`.

**Comment by martin-frbg** [comment]
Does the existing `openblas_get_num_threads` not do what you need ? It was added by PR #497 in  2015, so must have been around since about version 0.2.15.

**Comment by SuperFluffy** [comment]
My bad, I overlooked it. Probably fat-fingered the name when I searched. Thank you for pointing it out. This is exactly what I need!
