### ISSUE TITLE
compile failing make[1]: *** [../libopenblas_sandybridgep-r0.3.4.dev.so] Error 1

### ISSUE THREAD

**Issue by shivam05011996** [xianyi/OpenBLAS#1879]
I am trying to compile OpenBLAS, but I getting error as - 
```
make[1]: Leaving directory `/tmp/OpenBLAS/ctest'
make[1]: Entering directory `/tmp/OpenBLAS/exports'
perl ./gensymbol linktest  x86_64 _ 0 0 0 0 0 0 "" "" 1 > linktest.c
cc -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DNO_AVX512 -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=8 -DMAX_PARALLEL_NUMBER=1 -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  -shared -o ../libopenblas_sandybridgep-r0.3.4.dev.so \
        -Wl,--whole-archive ../libopenblas_sandybridgep-r0.3.4.dev.a -Wl,--no-whole-archive \
        -Wl,-soname,libopenblas.so.0 -lm -lpthread -lgfortran -lm -lpthread -lgfortran
/usr/bin/ld: cannot find -lgfortran
collect2: error: ld returned 1 exit status
make[1]: *** [../libopenblas_sandybridgep-r0.3.4.dev.so] Error 1
make[1]: Leaving directory `/tmp/OpenBLAS/exports'
make: *** [shared] Error 2
```

I tried with make and make FC=gfortran, in both of them I am getting same error.
Unable to figure out whats going bad.

Thanks

**Comment by brada4** [comment]
What distribution are you using?
Are gcc and gfortran same versions (e.g. from distribution packages)?

**Comment by martin-frbg** [comment]
It seems the linker cannot find the fortran runtime library, it could be that you need to install it from a separate package named something like libgfortran or libgfortran-dev

**Comment by brada4** [comment]
-lgfortran would be looking for a file named libgfortran.so in directories set in /etc/ld.so.conf(.d/\*.conf) files.
Note that it is (typically) just a symbolic link to libgfortran.so.[0-9]\*$ library installed by gfortran compiler package.

**Comment by shivam05011996** [comment]
@brada4 I am on Ubuntu 14.04. I uninstalled gfortran4.8 and removed the ld.cache. And tried make it got successfully compiled and installed. But I dont understand why with fortran its not compiling
The fortran version was 4.8 and gcc 5.4, is this a problem?

**Comment by brada4** [comment]
The best tested combination is 2 compilers shipped with distro and used to build whole package collection. It is not a hard requirement, say redhat-scl would permit mixing in one system compiler with latest version of other, but not finding some library that is there in plain sight probably is a good sign at least to make them match.

My ubuntu 14 shows following:
```
$ uname -a
Linux ubuntu 3.13.0-162-generic #212-Ubuntu SMP Mon Oct 29 12:08:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4
LIC-CUT
$ gfortran --version
GNU Fortran (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4
LIC-CUT
```

**Comment by martin-frbg** [comment]
Different version numbers may imply more or less subtle differences in the library format or interface, making the "old" library unsuitable for linking with a "newer" gcc project.

**Comment by brada4** [comment]
Just spotted that it is cc shortcut involved
`update-alternatives --config cc`
Should permit to use gcc 4.8 instead in presence of newer versions.

**Comment by shivam05011996** [comment]
Yes, the problem was gcc i had 5.4 when install 4.8 it was successful also, fortan also should be of same version.

closing this.

**Comment by brada4** [comment]
Normally you can have multiple compilers, build system will default to `cc` before trying others and resort to `gfortran` not finding others. If you `cc` is not same `gcc` as `gfortran` you might need to force its hand setting FC and CC variables.
