### ISSUE TITLE
Errors Built in Visual Studio 2015 

### ISSUE THREAD

**Issue by MateuszSoftcream** [xianyi/OpenBLAS#1880]
I would like to create .wxs file with file tree using heat.exe WIX. Any ideas whats wrong with it and why im getting 9009 error code all the time ? 
This a Pre-build comand thar im using: 
“$(WIX)bin\heat.exe” dir “$(N_Published)” -cg N_Published -gg -scom -sreg -sfrag -srd 
-out “$(ProjectDir)\FilesFragment.wxs”

N_Published directory is fine.

**Comment by martin-frbg** [comment]
Probably better to ask this whereever the WIX heat.exe community lives... from a quick google, error 9009 with heat.exe seems to be "command not found" so your "$(WIX)bin\heat.exe" path may be incorrect. See https://stackoverflow.com/questions/22730003/msb3073-command-exited-with-code-9009
