### ISSUE TITLE
How to support a new cpu arch?

### ISSUE THREAD

**Issue by chen2366** [xianyi/OpenBLAS#1888]
I clone OpenBlas to a alpha(Shenwei CPU) machine. How to support for alpha type cpu(sw_64)

**Comment by martin-frbg** [comment]
Probably best to look at pull request #1526 to see what needs to be done to add a new arch (RISC-V in that case, not yet merged into mainline). Once you get your port working with the generic C kernels you can look into replacing the most important ones with optimized code for your CPU.  (As noted by the RISCV port's author in #1528, the optimization strategy used in OpenBLAS - originally x86-only GotoBLAS - may not be useful on radically different hardware architectures)

**Comment by brada4** [comment]
Actually there is old little maintained alpha axp port, probably we are talking about new cpu type in that architecture.

**Comment by chen2366** [comment]
@martin-frbg  Yeah, I have seen that branch, and add some code to support sw_64 cpu. Now I find that there isn't add the check code in `c_check`, I will try it later. Thanks

**Comment by windofbarcelona** [comment]
sorry,could tou please teach me how to support sw_64

**Comment by brada4** [comment]
That CPU is only rumoured to be Alpha-like.
Best chance is to use compilers in your system, only publicly visible (attempt at port of) gcc 4.8.4 should be valid.
Start with target armv5, names are misleading, that is actually assembly-free.

**Comment by martin-frbg** [comment]
As noted earlier, you could start from a copy of all the C-only codes ("GENERIC" or "ARMV5" target) which is what is done to start the RISCV support as described in #1526 (the file list in that pull request describes quite well which files would need to be copied and/or modified). 
For developing actual cpu-specific code you would need a good knowledge of the sw64 cpu architecture and its instruction set, or perhaps just a compiler that provides cpu-specific intrinsic functions (like we have seen recently with the AVX512 code added to OpenBLAS).
Unfortunately very little information about sw_64 seems to be available outside China, at least I did not find any links to cpu or compiler documentation.
