### ISSUE TITLE
`flang.dll` `flangrti.dll` not found when using openblas.dll in MSVC

### ISSUE THREAD

**Issue by russellfei** [xianyi/OpenBLAS#1901]
According to build instructions on MSVC 2017 via `CMake` and `conda`, the output `openblas.dll` requires `flang.dll` and `flangrti.dll`. However, both of them CANNOT be found in conda library directory. Other compilations via `MSYS2` report same problem. Maybe we should stay on the old version of OpenBLAS?

Please update the installation instructions after careful compilation tests, related problems found among open issues but none of them have effective solutions.

**Comment by isuruf** [comment]
They should be in `<CONDA_INSTALL_LOCN>\Library\lib`

**Comment by russellfei** [comment]
@isuruf  only `*.lib` not `*.dll`, lib is used in compilation, while dll is missing when debugging.

**Comment by isuruf** [comment]
Can you check `<CONDA_INSTALL_LOCN>\Library\bin` ?

**Comment by russellfei** [comment]
@isuruf  only `flang.exe` `flang1.exe` `flang2.exe`, nothing else. I've tried various compilation instructions for the last few days, still not working.

**Comment by isuruf** [comment]
Can you do `conda install libflang`? It should download the package https://anaconda.org/conda-forge/libflang/5.0.0/download/win-64/libflang-5.0.0-vc14_20180208.tar.bz2 which has flang.dll, flangrti.dll and libomp.dll

**Comment by russellfei** [comment]
@isuruf  It works. Please add this in MSVC compile instructions.

**Comment by martin-frbg** [comment]
@isuruf thanks for taking care of this.

**Comment by jschroedl** [comment]
I ran into this as well except I needed flang.dll, flangrti.dll, pgmath.dll and libomp.dll
