### ISSUE TITLE
v0.3.4 build failure in osx

### ISSUE THREAD

**Issue by isuruf** [xianyi/OpenBLAS#1902]
Building for DYNAMIC_ARCH fails with,

```
../kernel/x86_64/dgemm_kernel_4x8_skylakex.c:872:5: error: invalid alignment value
                        ".align 32\n"
                         ^
<inline asm>:26:8: note: instantiated into assembly here
.align 32
       ^
../kernel/x86_64/dgemm_kernel_4x8_skylakex.c:1040:5: error: invalid alignment value
                        ".align 32\n"
                         ^
<inline asm>:18:8: note: instantiated into assembly here
.align 32
       ^
../kernel/x86_64/dgemm_kernel_4x8_skylakex.c:1168:5: error: invalid alignment value
                        ".align 32\n"
                         ^
<inline asm>:11:8: note: instantiated into assembly here
.align 32
```

Let me know if you need more info on the build environment.

**Comment by martin-frbg** [comment]
Looks like a return of the OSX ".align vs .p2align" issue of #1470 (i.e. these should probably be converted to ".p2align 5")

**Comment by matthew-brett** [comment]
We (Numpy) just hit this too:

https://travis-ci.org/MacPython/openblas-libs/jobs/462712673#L1323

xref: https://github.com/numpy/numpy/issues/12478

**Comment by brada4** [comment]
You can quickly avoid building the implicated code by setting NO_AVX512=1 and mapping skylakex to haswell.

**Comment by martin-frbg** [comment]
>We (Numpy) just hit this too:

Yeah that is the beauty of this project - any small oversight at release time is going to hit a lot of projects.  Fix in place now.

**Comment by matthew-brett** [comment]
Thanks for fixing so quickly.

**Comment by isuruf** [comment]
Thanks for fixing this.
