### ISSUE TITLE
Build fails for TARGET=ATHLON

### ISSUE THREAD

**Issue by nikudyshko** [xianyi/OpenBLAS#1906]
I need to compile OpenBLAS for old processor AMD Athlon X2 5600+, but when I set TARGET=ATHLON 
build process fails after some time. The last error, that appears in the build log is following: 
`C:\mingw-w64\mingw64\bin\ar.exe: sgemm_kernel.obj: No such file or directory` 
Few times before it appears the following warning: 
`gcc.exe: warning: ../kernel/x86_64/: linker input file unused because linking not done` 

I use msys2+mingw64(v7.3.0) and OpenBLAS sources v3.3.0. 
With them I'm able to build lib for HASWELL and EXCAVATOR arcs. 

Full build log here: 
[build.log](https://github.com/xianyi/OpenBLAS/files/2654243/build.log)

**Comment by martin-frbg** [comment]
I suspect the old "ATHLON" target may have been implemented for the original 32bit models only, could you try TARGET=OPTERON please ? (Alternatively "BINARY=32" would work for TARGET=ATHLON if my interpretation is correct)

**Comment by brada4** [comment]
It should be auto-detected as OPTERON_SSE3 by typing `make`
It is also correctly detected by setting `DYNAMIC_ARCH=1 DYNAMIC_OLDER=1` to make (otherwise even older CPU code will be used)

**Comment by nikudyshko** [comment]
Thanks for replies 

@brada4 I'm running build process on another PC. 

@martin-frbg Running a.t.m.

**Comment by brada4** [comment]
Yes, DYNAMIC_ARCH parameters are exactly to make runtime CPU detection instead of quick build for build host only.
You can switch to sources 0.3.4 for last few days.
EDIT: ref: ./Makefile.rule
EDIT2: for old architectures you might want to disable denormal processing via CONSISTENT_FPCSR=1 option REF: http://research.ihost.com/osihpa/osihpa-hensbergen.pdf

**Comment by nikudyshko** [comment]
It took some time to make some experiments, but after all - when I switched to sources v0.3.4 and changed target to 'opteron' I was able to built the library.

**Comment by brada4** [comment]
Your mentioned CPU is OPTERON_SSE3

**Comment by martin-frbg** [comment]
Performance difference between OPTERON and OPTERON_SSE3 targets is probably not that big...
