### ISSUE TITLE
Provide means to add distribution compiler flags

### ISSUE THREAD

**Issue by brada4** [xianyi/OpenBLAS#1917]
Seen in #1915
Either guidance or parameter to do it consistently properly

**Comment by martin-frbg** [comment]
Not sure this is really needed, or how to implement it without overriding any intention that may be valid for a particular case.

**Comment by brada4** [comment]
Something like (telling people how to go about) querying rpm or dpkg for defaults 
https://wiki.debian.org/Hardening
https://developers.redhat.com/blog/2018/03/21/compiler-and-linker-flags-gcc/

**Comment by brada4** [comment]
I will add it to faq some day
