### ISSUE TITLE
Next stable release

### ISSUE THREAD

**Issue by mhsmith** [xianyi/OpenBLAS#1920]
I see it's been nearly 18 months since the last stable release, and a lot has happened on the 0.3 branch. Can you give any idea of what's left to be done before 0.3 is declared stable, and when that's expected to happen?

**Comment by martin-frbg** [comment]
There have been five releases from the 0.3 branch already - see https://github.com/xianyi/OpenBLAS/releases - with the next tentatively scheduled for end of december. Unfortunately only the original maintainer has write access to the project page on openblas.net so the project is shown as if it was still stuck at 0.2.20 there.

**Comment by mhsmith** [comment]
Thanks, and I'll add a link here to #1675.

**Comment by mhsmith** [comment]
By the way, https://github.com/xianyi/OpenBLAS/wiki/Download also identifies 0.2.20 as the "latest stable version": I guess you probably do have access to change that.

**Comment by brada4** [comment]
I just changed that page.
