### ISSUE TITLE
configure the project:  CMAKE_LINKER-NOTFOUND

### ISSUE THREAD

**Issue by wdear** [xianyi/OpenBLAS#1922]
when configuring the project with CMake following the [Wiki](https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-in-Microsoft-Visual-Studio), I got the error:

F:\devlib\OpenBLAS-0.3.4\build> cmake .. -G "Ninja" -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DCMAKE
_Fortran_COMPILER=flang -DBUILD_WITHOUT_LAPACK=no -DNOFORTRAN=0 -DDYNAMIC_ARCH=ON -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is Clang 5.0.0
-- The ASM compiler identification is MSVC
-- Found assembler: H:/Anaconda3/Library/bin/clang-cl.exe
-- Check for working C compiler: H:/Anaconda3/Library/bin/clang-cl.exe
-- Check for working C compiler: H:/Anaconda3/Library/bin/clang-cl.exe -- broken
CMake Error at H:/Anaconda3/Library/share/cmake-3.13/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "H:/Anaconda3/Library/bin/clang-cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: F:/devlib/OpenBLAS-0.3.4/build/CMakeFiles/CMakeTmp

    Run Build Command:"H:/Anaconda3/Library/bin/ninja.exe" "cmTC_10796"
    [1/2] Building C object CMakeFiles\cmTC_10796.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_10796.exe
    FAILED: cmTC_10796.exe
    cmd.exe /C "cd . && H:\Anaconda3\Library\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_10796.dir --manifests  -- CMAKE_LINKER-NOTFOUND /nologo CMakeFiles\cmTC_10796.dir\testCCompiler.c.obj  /out:cmTC_10796.exe /implib:cmTC_10796.lib /pdb:cmTC_10796.pdb /version:0.0  /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /foCMakeFiles\cmTC_10796.dir/manifest.res CMakeFiles\cmTC_10796.dir/manifest.rc" failed (exit code 0) with the following output:
    系统找不到指定的文件。
    ninja: build stopped: subcommand failed.

I've been trapped here for several days. The main clue for CMAKE_LINKER-NOTFOUND is about Activating the MSVC environment. But I already have done this:

 C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build> .\vcvarsall x64
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0.26730.10
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

**Comment by brada4** [comment]
Try anaconda binutils maybe

**Comment by martin-frbg** [comment]
Various sources on the net seem to suggest that CMAKE_LINKER is actually not used (and not set) in a Visual Studio environment. Actually the last command that was executed in your log snippet appears to have been `rc` - is "rc.exe" in your path ?

**Comment by wdear** [comment]
Thanks @martin-frbg， "rc.exe" in path solved the CMAKE_LINKER problem.
However，new error popped up and I give up MSVC build，switch to MinGW and work it out. o(╯□╰)o
