### ISSUE TITLE
Floating point warning set during syrk call

### ISSUE THREAD

**Issue by seberg** [xianyi/OpenBLAS#1924]
Calling syrk on arrays larger then (32, 32), seems to cause the floating point error flag `FE_INVALID` to be set (as checked by `fetestexcept` as far as I can see).

This was tested on OpenBLAS ~master~ develop branch, unfortunately, I only have a numpy reproducer (**EDIT:** Do to changes in numpy, this will currently only work on master – NumPy 1.17+):
```python
i = 33
arr = np.zeros((i, i))
res = np.matmul(arr, arr.T)  # will call syrk since it is transpose

# RuntimeWarning: invalid value encoutnered in matmul
```
For `i < 33` the warning is not given. The actual values or transpose flag seems irrelevant.

I am not quite sure whether this is an error in OpenBLAS, but if it is not we will have to silence floating point warnings here I think.

**Comment by seberg** [comment]
Silencing `FE_INVALID` for matrix multiplication seems an OK workaround to me in any case, only overflow/underflow should be relevant for matrix multiplication I guess.

**Comment by martin-frbg** [comment]
Could you rerun your check on OpenBLAS develop branch or the recent 0.3.4 release please ? master is unfortunately stale at 0.2.20 (the last release made by xianyi 18 months ago)

**Comment by seberg** [comment]
@martin-frbg oops, sorry, I use `develop` since I was on it. Am too used to having master as the development branch from numpy.

**Comment by seberg** [comment]
To be more exact:
```
    version info: OpenBLAS 0.3.5.dev NO_AFFINITY HASWELL MAX_THREADS=4
```
EDIT: On arch linux.

**Comment by martin-frbg** [comment]
Thanks. If I am not entirely mistaken, FE_INVALID signals a domain error, so probably "should not happen" with sane code and data (except perhaps as the result of an earlier overflow, which would not be that healthy either).

**Comment by martin-frbg** [comment]
Who or what is "c" in your example - should this be "arr" or are there lines missing in your code snippet ?

**Comment by seberg** [comment]
Sorry :(, that is what you get when you edit code only in one place after pasting...

EDI: Yes, should be `arr`, fixed it in the example.

**Comment by martin-frbg** [comment]
Not immediately reproducible on my Haswell (i8700K), perhaps python or glibc version plays a role ?

**Comment by seberg** [comment]
Hmmm, possibly, have a Haswell `i7-7500U`. Python is 3.7.1, glibc is 2.28 unless I am confused.

But if you can't easily reproduce, that probably explains why nobody else ever complained about it. Maybe my setup is somehow weird.

**Comment by seberg** [comment]
Hmm, I can reproduce it on my Debian with python3:
```
OpenBLAS version info: NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=64
```
(not sure which OpenBLAS version right now, it is debian testing). With Python 3.6.7.

Man... I forgot a major information. To reproduce it with numpy, you need to use numpy master :(.

**Comment by martin-frbg** [comment]
Is it possible that the relevant `fetestexcept` call was added only in current numpy master ? (I am not too keen on installing numpy master right now, but https://github.com/ContinuumIO/anaconda-issues/issues/9129#issuecomment-380284038 could be describing a similar situation where an originally benign signal triggers the numpy warning )

**Comment by seberg** [comment]
Yes, it definitely is new on master. Sorry, forgot to mention that crucial thing. The old one did not  even call syrk in my example. (EDIT: for poor phone typing)

**Comment by brada4** [comment]
Dows it magically work with 64?

**Comment by seberg** [comment]
@brada4 yes, indeed it does!

**Comment by brada4** [comment]
I see old fish in driver/*/level3_syrk_threaded.c
>  BLASLONG range[MAX_CPU_NUMBER + 100];

Can you check if any avoids the issue:
Using USE_SIMPLE_THREADED_LEVEL3=1 build opt.
Using env var OPENBLAS_NUM_THREADS=1

**Comment by martin-frbg** [comment]
That does look like some less than creative coding by grandmaster Goto, but I do not immediately see its connection to the FE_INVALID ?

**Comment by brada4** [comment]
One-off INT calculation or something....

**Comment by seberg** [comment]
OK, so setting threads to 1 indeed fixes it. Not quite sure about the `USE_SIMPLE_THREADED_LEVEL3=1`, I think I screwed up the recompile the first try, so will update the comment in a bit. EDIT: I somewhat think the simple threaded level 3 did not help, but can't say I am 100% sure I got it right.

**Comment by brada4** [comment]
it is in interface/syrk.c the strange poorly understood work dividers (but easy to take out if it is implicated)

**Comment by seberg** [comment]
well there is a `... / (double) nthreads` that would add up as the cause of this if `nthreads` can reach 0 when it is an exact multiple or so.

**Comment by brada4** [comment]
with (double) it could reach 0+theta > 0 ....

**Comment by martin-frbg** [comment]
Err, nthreads is not expected to become zero. If the explanation was that simple, OpenBLAS would be blowing up all over the place. FWIW valgrind does not find anything wrong with either the wonderful
+100 or a more common MAX_CPU_NUMBER+1, so this may have been papering over a long-gone bug.

**Comment by seberg** [comment]
Yeah, that made no sense. That `sqrt` might be a suspect, but I will tune down the guesses until they are more educated :)

**Comment by martin-frbg** [comment]
Seems I cannot even get it to raise FE_INVALID when I add the `feenableexcept(FE_INVALID)` to OpenBLAS itself.

**Comment by seberg** [comment]
Sorry, I have problems myself right now with reproducing it after recompiling OpenBLAS a few time. I am wondering if it had to do with a slightly older version or not. Will post more later probably, right now I am confused :/.

**Comment by seberg** [comment]
Yeah, maybe I did not clean up correctly, and it disappeared in the not too far back past?

**Comment by brada4** [comment]
It is sort of OK if it was just some mistake building, but try again few times just in case.

**Comment by seberg** [comment]
@brada4 it still happens with the OpenBLAS shipped with debian testing as far as I can see (I did not mess with OpenBLAS myself on that machine). Just a bit sorry if I am wasting everyone's time because it is not in master anymore.

**Comment by seberg** [comment]
So I may have forgotten a `git clean -xdf` and/or `make clean`. Cannot reproduce right now, not even with open mp enabled.

Since the last time I had compiled OpenBLAS develop was when we discussed the thread safety issues (probably about ~2 months ago), it sounds like it got fixed in the mean time.

Will close this for now. Will also quickly try with version from 2 months ago and post the result. If anyone is curious (and I can repro with an older version) I can bisect just for the kicks.

**Comment by brada4** [comment]
Please quickly snap package version as installed on your system
`dpkg --list | grep openblas`
And report to debian too so they do not release broken package to masses.
Can you try options from dpkg-buildflags one by one or half by half?
Like quickest way:
`make CC='cc --fsomething' FC='gfortran -fsomething'`

**Comment by seberg** [comment]
The debian info:
```
ii  libopenblas-base:amd64                        0.3.3+ds-1                            amd64        Optimized BLAS (linear algebra) library (shared library)
ii  libopenblas-dev:amd64                         0.3.3+ds-1                            amd64        Optimized BLAS (linear algebra) library (development files)
```

I never used many flags in my own (arch) compilations, just enabling OMP/SIMPLE threaded level 3 or `THREADS=4`, that is about it.

**Comment by seberg** [comment]
Hmmm, right now seems it maybe only happens with `USE_SIMPLE_THREADED_LEVEL3=1`.

**Comment by seberg** [comment]
OK got it, it seems at least with ~master~ develop it only shows up with `USE_SIMPLE_THREADED_LEVEL3=1` (for comparison debian uses `USE_OPENMP=0` but it is an old version of course, I also set THREADS manually) and my ingenious patch:
```diff
diff --git a/driver/level3/syrk_thread.c b/driver/level3/syrk_thread.c
index 5f40853d..e6c54bf5 100644
--- a/driver/level3/syrk_thread.c
+++ b/driver/level3/syrk_thread.c
@@ -133,6 +133,7 @@ int CNAME(int mode, blas_arg_t *arg, BLASLONG *range_m, BLASLONG *range_n, int (
     }
 
   } else {
+    double sqrt_di;
 
     nf = (double)(arg -> n - n_from);
     nt = (double)(arg -> n - n_to);
@@ -149,6 +150,14 @@ int CNAME(int mode, blas_arg_t *arg, BLASLONG *range_m, BLASLONG *range_n, int (
       if (nthreads - num_cpu > 1) {
 
        di = (double)(arg -> n - i);
+       if (di * di + dnum < 0) {
+           sqrt_di = 0;  /* or does this have to be NaN rather? */
+           printf("WHAHAHAHAHA bad SQRT %f, %f!\n", di, dnum);
+       }
+       else {
+           sqrt_di = sqrt(di * di + dnum);
+       }
+       printf("SQRT DI: %f\n", sqrt_di);
        width = ((BLASLONG)((-sqrt(di * di + dnum) + di) + mask)/(mask+1)) * (mask+1);
 
        if ((width <= 0) || (width > n_to - i)) width = n_to - i;
```
Actually prints out:
```
In [1]: i = 33; arr = np.zeros((i, i)); res = np.matmul(arr.T, arr)
SQRT DI: 28.578838
WHAHAHAHAHA bad SQRT 1.000000, -272.250000!
SQRT DI: 0.000000
runtests.py:1: RuntimeWarning: invalid value encountered in matmul
  #!/usr/bin/env python
```

Which means that:
```
    nf = (double)(arg -> n - n_from);
    nt = (double)(arg -> n - n_to);

    dnum = (nt * nt - nf * nf) / (double)nthreads;
```
is negative. That seems strange, but I guess it might be just harmless, because in the end everything is already finished or so and the only left over from the whole thing is the error flag.

**Comment by brada4** [comment]
Testing is 0.3.4 - can you repeat with that?
https://packages.debian.org/source/testing/openblas

**Comment by martin-frbg** [comment]
Thanks for tracking this down. So in the end this is the (main or only) reason for the subsequent "if width <=0" check, also inherited from the original GotoBLAS. Ugly but (mostly) harmless, I guess I will patch this along the lines of your "ingenious patch" over the weekend.

**Comment by seberg** [comment]
@brada4 I guess I had not upgraded in a while on that computer. The 3.4 version actually shipped with up to date Debian does **not** show the issue.

I do think it is a pretty mild bug:
  1.It is not a regressions (and likely a bit more hidden by recent changes)
  2. Numpy master test suit trips over it, but in release mode it probably only prints a warning, in a path that is rarely used in actual code.
  3. Few people will use an older debian openblas with numpy master (most of those would end up using Anaconda/pip which installs a custom OpenBLAS). When debian upgrades numpy, they may also have to upgrade OpenBLAS, but that seems about it.
  4. No wrong results are returned as far as I can see, only a wrong floating point error flag.

**Comment by brada4** [comment]
It is solved. There was a genuine mistake in 0.3.3 packaging, solved as in first line of 3.4 release notes, but broken version managed to land about everywhere.
3/ there is no problem whatsoever for older than v0.3.3
3debian/ current release with 0.2.20 is not affected (as opposed to mid-testing mistakes)
3pip/ yes, they contain non-releases of openblas, some frankensteins from openblas and atlas, that cannot be solved here, but keep crashing and filling bug trackers.

**Comment by martin-frbg** [comment]
That part of the code did not change in 0.3.4 (and I notice you reproduced the problem with current `develop` already), perhaps the python message is generated somewhat randomly depending on which thread came in last.

**Comment by brada4** [comment]
@martin-frbg debian 0.3.3 did not patch out USE_TLS from Makefile.rule
If it happens with other versions without this primary suspect it is necessary to investigate deeper

**Comment by martin-frbg** [comment]
@brada4 I am not convinced that USE_TLS has any bearing on this syrk oddity (and note he has been cross-checking with current `develop` from the start). You may be thinking of the haskell-opencv segfault bug discussed yesterday ?

**Comment by seberg** [comment]
My guess is that checking if `dnum` is negative and setting width explicitly would band-aid everything that I see away, there is a similar branch in the same file, where I think negative numbers are not possible. The only thing I wonder is if something went wrong elsewhere to produce negative numbers in the first place.

But I do not have a clear enough idea about what this code does to judge the correctness.

**Comment by brada4** [comment]
@martin-frbg only common thing is that it fails with 0.3.3, difference is that this does not go fixed.
The problem with +100 is that +1 might have been insufficient long ago.

**Comment by seberg** [comment]
Thanks @martin-frbg!
