### ISSUE TITLE
single-thread multi-threading 

### ISSUE THREAD

**Issue by ghost** [xianyi/OpenBLAS#1927]
Hi All,
The issue I am going to report possibly popped up on several occasions already.
I was running parallel test inside TBB's "parallel_for" loop using Armadillo matrix library linked against OpenBlas backend. The test itself run correctly except all the threads were bounded to a single CPU, that is, all but one cores were free and 1 was 100% busy. It took quite a lot of time to figure out what was going wrong. Eventually, I recompiled Armadillo/Arpack without OpenBlas and for now the multi-threading operates as expected. My impression is that nested parallelism causes a problem. TBB runs a function body inside thread context where Armadillo vector/matrices are manipulated with OpenBlas parallelisation. Ideally, OpenBlas should follow sequential execution branch if its function was invoked from the parent thread context, although I am not sure how to do this automatically. Maybe OpenBlas can expose both the parallel and sequential APIs and let front-end libraries to switch between them upon user request. 
P.S. My system is Redhat 7.6, 64-bits, g++ 6.3. Interesting, exactly the same code runs without issues on Mac OS, where everything was installed via Homebrew.

**Comment by martin-frbg** [comment]
I think we have an older ticket already open for TBB support. Not sure if your problem comes from TBB itself or if something in Armadillo (or whatever else is involved) forces thread affinity to a single cpu. 
It may be possible to work around this by setting  OPENBLAS_NUM_THREADS=1 in the environment or calling openblas_set_num_threads(1) early in your code.

**Comment by martin-frbg** [comment]
Regarding your PS, which version of OpenBLAS are you using on the two systems ? (Besides MacOS may handle affinity differently)

**Comment by ghost** [comment]
Hi Martin,
1) Besides TBB, I wrote two parallel_for implementations based on pure pthreads and std::thread - the same behavior.
2) On Mac OS (Mojave):  openblas 0.3.4 (strange version, the official one is 0.2.20).
     On Linux: openblas 0.2.20

**Comment by martin-frbg** [comment]
Looks like you're the ideal person to debug this :smile:
Version 0.3.4 is not that strange, actually that _is_ the latest version. 0.2.20 on the other hand is 18 months old, it was the last version produced by xianyi before he (apparently) concentrated on his newly founded business. Unfortunately I do not have write access anywhere outside the repository, so openblas.net still provides outdated information.

**Comment by brada4** [comment]
Only OpenMP parallel section detection AND (&&) in OpenMP build of OpenBLAS are implemented. In all other cases OpenBLAS functions will not detect being in parallel section. There is some code preventing extreme (n^2) core oversubscription.

Regarding CPU affinity mask - it is possible that under OSX OpenBLAS and TBB uses different affinity masks API, so openblas can occupy more threads, under Linux once mask is set to smaller than wildcard - sub-threads or child processes cannot escape it in user context, that is possible from root user (or subject to renice ulimit)

**Comment by martin-frbg** [comment]
Hmm. 0.2.20 may actually have been one of those older releases where cpu affinity had accidentally been made the default on linux as well. I'd wait for results with 0.3.4 before trying to explain away why it might behave differently on linux...

**Comment by brada4** [comment]
There is 0.3.3 (_TLS patched, AFIINITY off) all flavours available via Fedora EPEL.

**Comment by martin-frbg** [comment]
Confirmed now - 0.2.20 was the exact version where I had inadvertently changed the default setting in Makefile.rule to enable CPU affinity on Linux - luckily this was spotted and corrected in time for the subsequent 0.3.0 release. The effect of having cpu affinity enabled would be exactly as you describe, 
any threads started by the program after initialization of OpenBLAS would be bundled on that one cpu.
