### ISSUE TITLE
float to long?

### ISSUE THREAD

**Issue by kenshin92** [xianyi/OpenBLAS#1928]
https://github.com/xianyi/OpenBLAS/blob/e23366e860c9afc53608287040ee550623fefe49/kernel/x86_64/sgemm_beta_skylakex.c#L53

**Comment by martin-frbg** [comment]
Looks like a slightly creative way around the classical problem of "comparison of floating point values to exact zero", with "long" being used as beta is declared as FLOAT (meaning either "float" or "double" depending on a compile-time definition provided by the Makefile).

**Comment by fenrus75** [comment]
the test is for "exact zero", and is performance critical.
Unfortunately many compilers generate pretty dire code for this test.

in hindsight I could have used memcmp() I suppose

**Comment by martin-frbg** [comment]
Fixed by #1934
