### ISSUE TITLE
Build target is not validated

### ISSUE THREAD

**Issue by TiborGY** [xianyi/OpenBLAS#1938]
When the target is manually set in Makefile.rule, no validation is done to check if the requested target is actually supported/implemented. The build proceeds as normal, but the target seems to be silently ignored and the build machine will be targeted.

This could be a problem both if the user requests an unsupported target, a target that has no specific support (i.e. IVYBRIDGE) or if there is a typo in the target string.

The build system should error out if the requested target cannot be found.
Might try to fix this issue myself.

**Comment by martin-frbg** [comment]
The target is supplied as a build-time define for the getarch program (in/by Makefile.prebuild or prebuild.cmake) where it is expected to match one of the possible targets. The way this is written, it is not easily possible to detect that a non-existent target was specified - if no match occured, the code simply behaves as if no target was set. (And as the result of the build is normally named after the actual target, I guess it should become apparent if the build did not go as desired - no matter if the builder misspelled or neglected to read the Targetlist.txt)

**Comment by TiborGY** [comment]
I am thinking about implementing a check in Makefile.system, right after Makefile.rule is included.

**Comment by martin-frbg** [comment]
Given the number of "legal" targets I expect that is bound to get messy. Perhaps try to add something like -DUSER_TARGET to GETARCH_FLAGS to mark that some TARGET was given and use it to print a message in getarch.c when FORCE is not defined after passing through the cascade of ifdefs ?

**Comment by martin-frbg** [comment]
This would work, but I am still unsure if it would be desirable:
```
--- a/Makefile.system
+++ b/Makefile.system
@@ -64,7 +64,7 @@ HOSTCC         = $(CC)
 endif
 
 ifdef TARGET
-GETARCH_FLAGS := -DFORCE_$(TARGET)
+GETARCH_FLAGS := -DFORCE_$(TARGET) -DFORCED
 endif
--- a/getarch.c
+++ b/getarch.c
@@ -1068,6 +1068,10 @@ USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 #ifndef FORCE
 
+#ifdef FORCED
+#error "An unknown TARGET was specified - see TargetList.txt for the list of supported targets."
+#endif
+
 #if defined(__powerpc__) || defined(__powerpc) || defined(powerpc) || \
     defined(__PPC__) || defined(PPC) || defined(_POWER) || defined(__POWERPC__)
 #ifndef POWER
```

**Comment by brada4** [comment]
> see TargetList.txt for the list of supported targets

... or use DYNAMIC_ARCH

**Comment by martin-frbg** [comment]
> > see TargetList.txt for the list of supported targets
> 
> ... or use DYNAMIC_ARCH

not available on all architectures, not useful when autodetection failed for some reason and probably not the desired solution when somebody expressly wanted to build for a specific cpu in the first place.
