### ISSUE TITLE
Where are official binary packages? 

### ISSUE THREAD

**Issue by chenjiechun** [xianyi/OpenBLAS#1948]
The files stored on sourceforge.net are also source code files. Where are official binary packages stored?

**Comment by chenjiechun** [comment]
I have solved the problem using NuGet.

**Comment by martin-frbg** [comment]
This is indeed the preferred solution currently - https://github.com/xianyi/OpenBLAS/wiki/Precompiled-installation-packages - for the reasons given in #1675

**Comment by martin-frbg** [comment]
...though it seems that packages on nuget are not much newer than what xianyi last put on sourceforge :frowning_face:
