### ISSUE TITLE
OpenBlas static library on windows 

### ISSUE THREAD

**Issue by wolfviking0** [xianyi/OpenBLAS#1950]
Hi I am currently facing some issue when I link my openblas.a library with openface.
I build openblas using cmake but I create a static lib, not shared.

When I try to link my lib I have some undefined reference for _sgemm.

I am not sure why, is it possible to build openblas as a static library ?

Thanks

**Comment by martin-frbg** [comment]
Can you check with `nm` or some windows equivalent like `dumpbin` what symbols are present in your lib ? (I am assuming the build went without any error messages, also which version are you using ?)

**Comment by wolfviking0** [comment]
[symbols.txt](https://github.com/xianyi/OpenBLAS/files/2730775/symbols.txt)
Hi,
I attached the symbols of the static library; I think the symbols sgemm_ do not exist inside
The build succeed and I am using the openblas library with openface on all other platform
I am currently using your latest release 0.3.5

Here the exact error I have in openface :

LandmarkDetector.lib(CEN_patch_expert.cpp.obj) : error LNK2001: unresolved external symbol sgemm_
LandmarkDetector.lib(LandmarkDetectorModel.cpp.obj) : error LNK2001: unresolved external symbol sgemm_
LandmarkDetector.lib(PDM.cpp.obj) : error LNK2001: unresolved external symbol sgemm_
LandmarkDetector.lib(CNN_utils.cpp.obj) : error LNK2001: unresolved external symbol sgemm_
LandmarkDetector.lib(CCNF_patch_expert.cpp.obj) : error LNK2001: unresolved external symbol sgemm_
bin\openfaceengine.dll : fatal error LNK1120: 1 unresolved externals

Here the command arguments I am using to build on windows :

            -DDYNAMIC_ARCH=OFF
            -DBUILD_RELAPACK=OFF
            -DNOFORTRAN=ON
            -DUSE_THREAD=ON
            -DNUM_THREADS=16

**Comment by martin-frbg** [comment]
I may be reading this wrong, but I do not see a trailing underline on any of the symbols, so perhaps this is a matter of calling convention.

**Comment by wolfviking0** [comment]
Not sure to understand what you mean by calling convention. Do you mean an issue how openface is calling openblas ?

OpenFace is calling openblas like that :
          https://github.com/TadasBaltrusaitis/OpenFace/blob/be9b57703c2d7194f3d6354b46d22fe3a240141b/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp#L454

**Comment by martin-frbg** [comment]
Does it work when you modify it to call sgemm(...) instead of sgemm_(...) ?

**Comment by wolfviking0** [comment]
I need to do a patch let me try it, i will let you know.

Thanks

**Comment by martin-frbg** [comment]
If it is not easy, perhaps wait a bit in case somebody comes up with a better suggestion, Windows is not my usual environment...

**Comment by wolfviking0** [comment]
I made the patch you suggest on openface but The build failed because the sgemm_ do not have the same signature of sgemm.

Here the code I found in openface headers:
https://github.com/TadasBaltrusaitis/OpenFace/blob/master/lib/local/LandmarkDetector/include/stdafx.h

 // OpenBLAS stuff

      #include <openblas_config.h>
      // Instead of including cblas.h and f77blas.h (the definitions from OpenBLAS and other           BLAS libraries differ, declare the required OpenBLAS functionality here)
      #ifdef __cplusplus
       extern "C" {
	/* Assume C declarations for C++ */
      #endif  /* __cplusplus */

	/*Set the number of threads on runtime.*/
	void openblas_set_num_threads(int num_threads);

	void sgemm_(char *, char *, blasint *, blasint *, blasint *, float *,
		float  *, blasint *, float  *, blasint *, float  *, float  *, blasint *);
}

**Comment by wolfviking0** [comment]
Hi check inside my libopenblas.a for OSX and I can find the sgemm_

        $ nm -just-symbol-name libopenblas.a | grep sgemm
        libopenblas.a(sgemm.o):
        _sgemm_
        _sgemm_nn
        _sgemm_nt
        _sgemm_tn
        _sgemm_tt

**Comment by wolfviking0** [comment]
@martin-frbg I think I maybe find the trouble, in fact on OSX the openblas_config define the macro OPENBLAS_NEEDUNDERSCODE to 1 but not on windows.
So I need to modify OpenFace to use sgemm without underscore only on windows.

**Comment by brada4** [comment]
> The build failed because the sgemm_ do not have the same signature of sgemm.

You mean compiler expects "decorated" names? https://docs.microsoft.com/en-us/cpp/build/reference/decorated-names?view=vs-2017

**Comment by martin-frbg** [comment]
Not sure who is the culprit here - the NEEDBUNDERSCORE is (I think) a fortran/LAPACK only setting so perhaps we need to look into if/why it is needed for the C (BLAS) part as well on Windows ?
 In the meantime I managed to cross-compile a dynamic_arch binary of 0.3.5 on Linux using MXE, and running nm on the .a shows `_sgemm_` as it should be. (This was with plain `make`, the cmake build ran into unrelated problems with DYNAMIC:_ARCH=ON but I see you were building with DYNAMIC_ARCH=OFF which should work fine.)
[win035.zip.txt](https://github.com/xianyi/OpenBLAS/files/2733175/win035.zip.txt)

**Comment by wolfviking0** [comment]
Ok so after testing a window replacing the sgemm_ by sgemm. The issue seems to be fixed, I was able to build everything.

Thanks for you help

**Comment by brada4** [comment]
Formally it should be replaced with cblas_sgemm()
