### ISSUE TITLE
OpenBLAS fails on OS X with new -mavx2 flag

### ISSUE THREAD

**Issue by NicosPavlov** [xianyi/OpenBLAS#1951]
The flag -mavx2 was added on commit 43c2b0eb, which makes the building process fail on Mac OS X in Lapack code, with gcc8 as a fortran compiler:

make[2]: Entering directory `/opt/local/var/macports/build/_Users_nicos_ports_local_math_OpenBLAS/OpenBLAS/work/OpenBLAS-0.3.5/lapack-netlib/SRC'
/opt/local/bin/gfortran-mp-8 -O3 -m128bit-long-double -Wall -frecursive -m64 -fPIC -mavx2 -c -o sbdsvdx.o sbdsvdx.f
/opt/local/bin/gfortran-mp-8 -O3 -m128bit-long-double -Wall -frecursive -m64 -fPIC -mavx2 -c -o spotrf2.o spotrf2.f
/opt/local/bin/gfortran-mp-8 -O3 -m128bit-long-double -Wall -frecursive -m64 -fPIC -mavx2 -c -o sgetrf2.o sgetrf2.f
/opt/local/bin/gfortran-mp-8 -O3 -m128bit-long-double -Wall -frecursive -m64 -fPIC -mavx2 -c -o sgbbrd.o sgbbrd.f
/opt/local/bin/gfortran-mp-8 -O3 -m128bit-long-double -Wall -frecursive -m64 -fPIC -mavx2 -c -o sgbcon.o sgbcon.f
/opt/local/bin/gfortran-mp-8 -O3 -m128bit-long-double -Wall -frecursive -m64 -fPIC -mavx2 -c -o sgbequ.o sgbequ.f
/opt/local/bin/gfortran-mp-8 -O3 -m128bit-long-double -Wall -frecursive -m64 -fPIC -mavx2 -c -o sgbrfs.o sgbrfs.f
/opt/local/bin/gfortran-mp-8 -O3 -m128bit-long-double -Wall -frecursive -m64 -fPIC -mavx2 -c -o sgbsv.o sgbsv.f
/opt/local/var/macports/build/_Users_nicos_ports_local_math_OpenBLAS/OpenBLAS/work/.tmp/ccyLD1vQ.s:103:no such instruction: `vxorps %xmm0, %xmm0,%xmm0'
/opt/local/var/macports/build/_Users_nicos_ports_local_math_OpenBLAS/OpenBLAS/work/.tmp/ccyLD1vQ.s:104:no such instruction: `vcomiss (%r14), %xmm0'
/opt/local/var/macports/build/_Users_nicos_ports_local_math_OpenBLAS/OpenBLAS/work/.tmp/ccyLD1vQ.s:111:no such instruction: `vsqrtss (%r14), %xmm0,%xmm0'
/opt/local/var/macports/build/_Users_nicos_ports_local_math_OpenBLAS/OpenBLAS/work/.tmp/ccyLD1vQ.s:112:no such instruction: `vmovss %xmm0, (%r14)'
make[2]: *** [spotrf2.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/opt/local/var/macports/build/_Users_nicos_ports_local_math_OpenBLAS/OpenBLAS/work/.tmp/cc2HvPr7.s:249:no such instruction: `vmovd %esi, %xmm1'
/opt/local/var/macports/build/_Users_nicos_ports_local_math_OpenBLAS/OpenBLAS/work/.tmp/cc2HvPr7.s:252:no such instruction: `vpbroadcastd %xmm1, %ymm1'
/opt/local/var/macports/build/_Users_nicos_ports_local_math_OpenBLAS/OpenBLAS/work/.tmp/cc2HvPr7.s:257:no such instruction: `vpaddd (%rcx,%rax), %ymm1,%ymm0'
/opt/local/var/macports/build/_Users_nicos_ports_local_math_OpenBLAS/OpenBLAS/work/.tmp/cc2HvPr7.s:258:no such instruction: `vmovdqu %ymm0, (%rcx,%rax)'
/opt/local/var/macports/build/_Users_nicos_ports_local_math_OpenBLAS/OpenBLAS/work/.tmp/cc2HvPr7.s:267:no such instruction: `vzeroupper'
[snip]

Removing the flag enables the build to proceed correctly.

**Comment by martin-frbg** [comment]
To me this looks as if your assembler (from macports version of GNU binutils package probably ?) is significantly older than your gcc. -mavx2 is supported since at least gcc/gfortran version 4.something, and it seems that your gfortran8 happily creates avx2-specific code that your assembler  does not understand. Not sure how to handle this, perhaps I should add a compile test like for skylake-avx512 ?

**Comment by brada4** [comment]
Mind to share `as --version`
Something at 2.25 starts to work wiyh AVX2
That includes binutils 2.30 shipped with macports.
The port actually includes self-help option to disable AVX with broken compilers like yours, so that peiple with proper build environment on good CPU get 20% bettet lapack

**Comment by NicosPavlov** [comment]
Thanks for the input. Looking at other errors reported, this seems indeed quite similar.

I have been using OS X assembler up to this point:
- /usr/bin/as: Apple LLVM version 10.0.0 (clang-1000.11.45.5)
I also then tried a version provided in cctools (binutils-like tools provided by Apple), but it seems also too old:
- /opt/local/bin/as: Apple Inc version cctools-921, GNU assembler version 1.38

Interestingly, Macports' binutils port does not contain as, so that this approach does not provide a more recent version. I'll look more, but at least the problem seems to be pinpointed.

**Comment by brada4** [comment]
It may be called gas or gcc-as on some systems.
If OSX has POSIX accounting option it will show which got called.
Common linux produces something like follows:
```
$ as --version
GNU assembler (GNU Binutils) 2.31.1
```

**Comment by NicosPavlov** [comment]
No, I think it is more general. as/gas from binutils is not supported on OS X and is disabled. See for instance this discussion: https://github.com/Homebrew/homebrew-core/issues/29177

**Comment by brada4** [comment]
But clang used to accept same flag and supposedly same assembler was fine with it.
Does it work if setting `-march=haswell`?
`vcomiss` is avx1 instruction, maybe `-mavx` helps?

**Comment by NicosPavlov** [comment]
So to try to get a better grasp of the problem, I went back to the initial configuration that was working (OpenBLAS 0.3.4, compiled with cc=clang, fc=gfortran from gcc8), and tried some things. 

1. gcc8 is partly broken in this case, and cannot handle AVX (fails with similar errors are reported above), so that cc=gcc8 and fc=gfortran8 fails.
2. clang/gfortran works and can compile the AVX code (cc=clang, fc=gfortran8). This should Imply that clang's assembler can handle avx instructions. 
3. however, adding the suggested flags (-mavx or -march=haswell) breaks the build with again the same errors.

**Comment by martin-frbg** [comment]
Does it work with `-march=core-avx2` in place of `-mavx2` ?

**Comment by NicosPavlov** [comment]
Sorry no. Any of these flags added to the fortran compiler leads to failure in the build.

**Comment by martin-frbg** [comment]
Thanks. I wonder if this is only a problem for the fortran compiler, so just stopping the build from adding -mavx2 to FCOMMON_OPT might work - in which case we would still get the benefit of the recent avx2 BLAS kernels ?

**Comment by brada4** [comment]
Does -march=native work? (it is of no universal usage, but if it is broken than you need to unconfigure all broken options from compiler interface)
hmmm....

Do competing fortran compilers work?
https://github.com/fxcoudert/gfortran-for-macOS/releases ?
ifort ? 
i am not sure if you can fit flang on top of xcode llvm?

**Comment by NicosPavlov** [comment]
Good point. I tried with the gfortran you pointed to, and it works in that case with the -mavx2 flag in version 0.3.5.
This shows that this is in the end an issue with MacPorts' compiler. The question is then if removing the flag to allow compilation on MacPorts indeed disables some AVX instructions or not. Thanks for all the pointers.

**Comment by brada4** [comment]
Probably you can port patches from that gfortran while keeping temporary -mavx2 revert in place.

**Comment by martin-frbg** [comment]
@NicosPavlov do you know if this gfortran issue can/will be addressed on the MacPorts side ? 
Otherwise this can probably be worked around by an additional condition in Makefile.x86_64
```
ifneq ($(OSNAME)$(F_COMPILER), DarwinGFORTRAN)
FCOMMON_OPT += -mavx2
endif
```
as the `-mavx2` is not as important for compilation of the fortran (LAPACK) part as it is for the BLAS
microkernels.

**Comment by NicosPavlov** [comment]
Thanks for the pointer. This more or less what I have been doing since reporting the problem. 

I think the issue has been addressed in Macports a few days ago. The problem is at least solved for me, and I have been waiting a little bit since the fix to see if there were reports of problems from other people, and there weren't. 

As far as I am concerned, this ticket can be closed, as it has been a problem quite specific to Macports, which is now fixed.

**Comment by brada4** [comment]
@NicosPavlov best that you close when you got working macport going (tests and dependent tests included)

**Comment by ludwigschwardt** [comment]
For folks attempting builds of new OpenBLAS on ancient Mac OS X systems, that may have washed up on this shore like me:

I added `-Wa,-q` to `CFLAGS` and `FFLAGS` on OS X 10.10.5 to switch the assembler from the prehistoric default Apple cctools one to the improved clang / LLVM one.

(At some point the default assembler switched to clang / LLVM :tada:, while the cctools version can still be selected these days by passing `-Q` to `as` instead.)

**Comment by martin-frbg** [comment]
Any idea if this can be done unconditionally on any version of OS X ?

**Comment by brada4** [comment]
AVX512 MACs are supported from OSX 10.11, maybe it can be conditionalized based on target SDK?
