### ISSUE TITLE
aarch64 flags for GCC 4.8.5 (Red Hat Enterprise Linux 7)

### ISSUE THREAD

**Issue by susilehtola** [xianyi/OpenBLAS#1952]
I'm trying to update the Fedora packages of OpenBLAS to 0.3.5, with runtime CPU detection on the aarch64 architecture.

However, there's a problem on Red Hat Enterprise Linux 7, which only has gcc 4.8.5: none of the mtune flags (cortex-a{53,57,72,73}, thunderx, falkor, thunderx2t99) are supported; also -march=armv8.1-a is not available.

Removing all the mtune flags, and replacing -march=armv8.1-a with -march=armv8-a gets the compilation farther, but I get a link error
```
BUILDSTDERR: ../libRblas-r0.3.5.a(ddot_k_THUNDERX.o): In function `ddot_k_THUNDERX':
BUILDSTDERR: /builddir/build/BUILD/openblas-0.3.5/Rblas/kernel/../kernel/arm64/ddot_thunderx.c:92: undefined reference to `vaddvq_f64'
```

Which flags should I use for Red Hat Enterprise 7? I'm restricted to using the system compiler, so suboptimal performance is okay as long as the code still compiles and works.

**Comment by martin-frbg** [comment]
The `vaddvq_f64` appears verbatim in kernel/arm64/ddot_thunderx.c so I am afraid flags are not likely to help. gcc 4.9 defines it in its arm_neon.h as
```
__extension__ static __inline float64_t __attribute__ ((__always_inline__))
vaddvq_f64 (float64x2_t __a)
{
  float64x2_t __t = __builtin_aarch64_reduc_splus_v2df (__a);
  return vgetq_lane_f64 (__t, 0);
}
```

but I do not know if this would work with an older gcc. On the other hand, the ThunderX DDOT kernel
appears to be unchanged from its 2015 original, so the best option for you is probably to comment or remove the DDOTKERNEL line in KERNEL.THUNDERX

**Comment by susilehtola** [comment]
Thanks! Compiled at
https://koji.fedoraproject.org/koji/watchlogs?taskID=31892642
