### ISSUE TITLE
Homepage is very outdated

### ISSUE THREAD

**Issue by PallHaraldsson** [xianyi/OpenBLAS#1953]
I assume https://www.openblas.net is for the same project, and that you do not want to have it too misleading.

The changelog linked from there also states at the same old version. And the wiki also linked there with OpenBLAS 0.2.0.

Possibly you want to link to github and just not have version numers and dates in the other places?

**Comment by martin-frbg** [comment]
See #1675 please

**Comment by martin-frbg** [comment]
Homepage updated now that xianyi has kindly given me write access to it.
