### ISSUE TITLE
Core2 is not a Microarchitecture, but Core is

### ISSUE THREAD

**Issue by dichn** [xianyi/OpenBLAS#1959]
I think there is a little mistake in **TargetList.txt**
> YONAH
CORE2
PENRYN
DUNNINGTON

**Core 2** is a microprocessor based on the **Core** microarchitecture.

**Comment by dichn** [comment]
actually I am confused if my cpu is Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
then how to choose the target while this cpu's microarchitecture is Kaby Lake

**Comment by brada4** [comment]
Core micro-architecture name is re-used as marketing trade name later, thus CORE2 signifies the early generation desktop CPUs microarchitecture (including Xeons) as opposed to i3-i9 that follow later.

I think you should be looking into Makefile.rule instead, namely along lines of DYNAMIC_ARCH, sort of all sorts of auto-detection work fine, either at build time, or at run time if above parameter is used.

Auto-detected TARGET name for your processor is HASWELL

**Comment by dichn** [comment]
thanks for your quick reply
