### ISSUE TITLE
Error:selected processor does not support 'dmb ish' in ARM mode

### ISSUE THREAD

**Issue by ghost** [xianyi/OpenBLAS#1961]
Excuse me! 
When i compiled OpenBLAS-0.2.20,saw as this problem:
/tmp/ccgB9J2n.s: Assembler messages:
/tmp/ccgB9J2n.s:330: Error: selected processor does not support `dmb ishst' in ARM mode
/tmp/ccgB9J2n.s:536: Error: selected processor does not support `dmb ishst' in ARM mode
make[1]: *** [sgemm_thread_tn.o] 错误 1
make[1]: *** 正在等待未完成的任务....
/tmp/ccAp6XOk.s: Assembler messages:
/tmp/ccAp6XOk.s:324: Error: selected processor does not support `dmb ishst' in ARM mode
/tmp/ccAp6XOk.s:529: Error: selected processor does not support `dmb ishst' in ARM mode
make[1]: *** [sgemm_thread_nt.o] 错误 1
/tmp/ccYzBsVk.s: Assembler messages:
/tmp/ccYzBsVk.s:330: Error: selected processor does not support `dmb ishst' in ARM mode
/tmp/ccYzBsVk.s:535: Error: selected processor does not support `dmb ishst' in ARM mode
/tmp/ccQXgEzn.s: Assembler messages:
/tmp/ccQXgEzn.s:324: Error: selected processor does not support `dmb ishst' in ARM mode
/tmp/ccQXgEzn.s:530: Error: selected processor does not support `dmb ishst' in ARM mode
make[1]: *** [sgemm_thread_nn.o] 错误 1
make[1]: *** [sgemm_thread_tt.o] 错误 1

My processor is ARM Cortex A53,and mechine is Hi3519AV100.here is my make command:
make TARGET=ARMV8 HOSTCC=gcc CC=arm-himix200-linux-gcc CROSS=1 NO_LAPACKE=1  BINARY=32 NOFORTRAN=1.

 When TARGET=ARMV7,this problem does not accur.But my processor(ARM Cortex A53) base on ARMV8 .Could you help me ? Thanks in advance.

**Comment by martin-frbg** [comment]
Could you please try with 0.3.5 from https://github.com/xianyi/OpenBLAS/releases ? Unfortunately the openblas.net site has not been updated for more than a year.

**Comment by ghost** [comment]
> Could you please try with 0.3.5 from https://github.com/xianyi/OpenBLAS/releases ? Unfortunately the openblas.net site has not been updated for more than a year.

Thank you for your reply.But version 0.3.5 causes the same problem.

**Comment by brada4** [comment]
There is no ARMv8 target for 32bit, you need 64bit system and libraries to use all execution resources of your CPU (or use ARMv7 cores)
You can greatly reduce redundant make parameters:
`make TARGET=ARMV7 HOSTCC=cc CC=arm-himix200-linux-gcc NOFORTRAN=1`

**Comment by ghost** [comment]
> There is no ARMv8 target for 32bit, you need 64bit system and libraries to use all execution resources of your CPU (or use ARMv7 cores)
> You can greatly reduce redundant make parameters:
> `make TARGET=ARMV7 HOSTCC=cc CC=arm-himix200-linux-gcc NOFORTRAN=1`

Thanks.
