### ISSUE TITLE
Cannot compile 32-bit version (BINARY=32)

### ISSUE THREAD

**Issue by TiborGY** [xianyi/OpenBLAS#1974]
Trying to compile a 32-bit version of the library on a 64-bit OS (Ubuntu 18.04, GCC 7.3) fails with the following log. Something related to avx512 detection does not work on 32-bit. NO_AVX=1 and NO_AVX2=1 have no effect on this issue.

> In file included from getarch.c:1090:0:
cpuid_x86.c: In function ‘support_avx512’:
cpuid_x86.c:242:5: warning: implicit declaration of function ‘xgetbv’; did you mean ‘getwd’? [-Wimplicit-function-declaration]
     xgetbv(0, &eax, &edx);
     ^~~~~~
     getwd
/tmp/ccA8ambP.o: In function `support_avx512':
getarch.c:(.text+0x23c): undefined reference to `xgetbv'
collect2: error: ld returned 1 exit status
make: *** [getarch] Error 1

**Comment by brada4** [comment]
Do you use 32bit gcc or clang with multilib?
There is no AVX possible in 32bit mode at all
What is your CPU?

**Comment by martin-frbg** [comment]
Can you provide the complete build log please ? The avx512 detection is allowed to fail and should set NO_AVX512=1 in that case.

**Comment by TiborGY** [comment]
This *is* the complete build log. The build system fails very early, because it cannot compile getarch.c .

**Comment by martin-frbg** [comment]
Ah, I see. You have set NO_AVX=1 which removes the definition of xgetbv(). Line 231 of cpuid_x86.c should read `if !defined(NO_AVX) && !defined(NO_AVX512)` rather than just `ifndef NO_AVX512`.
