### ISSUE TITLE
Static libs for MSVC prevented in cmakelists?

### ISSUE THREAD

**Issue by danielgindi** [xianyi/OpenBLAS#1975]
Hi!

I'm trying to understand why this line exists:
https://github.com/xianyi/OpenBLAS/blob/develop/CMakeLists.txt#L154

And can't figure it out. Why prevent static lib compilation on MSVC specifically?

**Comment by martin-frbg** [comment]
I suspect this may be a holdover from an observed inability to use the static library in MSVC around 2015. Most people active here do not develop on Windows so the build files and instructions for that platform tend to get updated from sporadic user reports mostly.

**Comment by danielgindi** [comment]
Okay. I'm doing some testing, may send you a PR soon if this works.

**Comment by danielgindi** [comment]
So yes I got it to work, and even cooperate nicely with conan.

**Comment by martin-frbg** [comment]
Great, thanks. (Not sure if I read correctly that this will stop building of tests and ctests though ?)

**Comment by danielgindi** [comment]
Nope, it was not building those to begin with. The indentation sucked, but that's how it was. Those cannot build on MSVC as they require a fortran compiler.

**Comment by martin-frbg** [comment]
Ah yes you are right of course. (Need to create some ctests that are actually C-only some day)

**Comment by danielgindi** [comment]
Btw I think that those changes should be propagated to the 0.3.x branch (`develop`?) too. These are not a lot of changes, and will make all the change in the world for those trying to compile for windows/MSVC.

**Comment by martin-frbg** [comment]
0.3.x gets updated from develop whenever a new release is prepared. (master is stuck at 0.2.20 where xianyi left off). (And ctests are tests for CBLAS that are taken from the netlib reference implementation - as that was (and still is) mostly written in fortran, its tests are fortran-heavy as well)

**Comment by danielgindi** [comment]
So do you want a PR for `develop` too or will you propagate the changes directly? As this PR is for the 0.2.x which most people still use

**Comment by martin-frbg** [comment]
Actually the PR needs to be against `develop`(I can look into copying the changes). master/0.2.20 is about 18 months old and close to a thousand commits out of date. (The CMAKE support files got a complete overhaul in that timeframe and CMakeLists.txt went through a few changes as well, just this particular issue did not get adressed)

**Comment by danielgindi** [comment]
The reason I did it against 0.2.2 is that other frameworks are still point to this version, and it doesn't hurt to finally give proper support for that.
I can create another one for 0.3

**Comment by martin-frbg** [comment]
Out of interest (recent issue #1950) what do the symbols in the library look like in your Windows build - do they have a trailing underscore or not ? (Not sure if this is actually a clang vs. MSVC issue though)

**Comment by danielgindi** [comment]
@martin-frbg 
Well both forms exist in the lib files. 
I see `openblas_get_num_threads`, `openblas_get_num_threads_`.

For the `sgemm` symbol - it differs between the static lib and the shared lib:
In the static I don't see an `sgemm` but only a `sgemm_` - with other variants like `sgemm_nt`, `sgemm_kernel` etc.
In the shared - both exist.

I'm guessing the underscored ones are aliases for some kind of compatibility.

Hope it helps...
