### ISSUE TITLE
ARM ismin/idmin kernels yield index of maximum instead

### ISSUE THREAD

**Issue by aarnez** [xianyi/OpenBLAS#1990]
The kernels defined by arm/imin.c behave exactly like arm/imax.c. They yield the index of the largest instead of the smallest element. This doesn't seem to be covered by any existing test case.

The fix is trivial -- see attached [patch](https://github.com/xianyi/OpenBLAS/files/2817194/0001-Fix-arm-imin.c-yield-index-of-smallest-not-largest-e.txt).

**Comment by martin-frbg** [comment]
Eeek. That bug appears to have gone unnoticed for more than five years, although it affects ARMV8 targets as well (which are probably a bit more popular, affordable and portable than zarch). (mips32 and armv5 probably play no major role anymore, nor do the "generic" x86 and x86_64 targets I think)

**Comment by martin-frbg** [comment]
Fixed on the develop branch, thanks.
