### ISSUE TITLE
Problem compiling lapacke and boost together

### ISSUE THREAD

**Issue by aprokop** [xianyi/OpenBLAS#1992]
The following test example:
```c++
#include "lapacke.h"
#include "boost/property_tree/ptree.hpp"

int main() {
    return 0;
}
```
does not compile, with errors like this:
```
In file included from /usr/include/c++/7/complex.h:36:0,                                                                                                                                       
                 from /home/xap/local/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/openblas-0.3.3-xlt4harsqysny4q4qw53g34s6jfz5wtx/include/lapacke.h:73,                             
                 from ./main.cc:1:                                                                                                                                                             
/home/xap/local/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/boost-1.68.0-j2mqoxflxrkb5c27hqgzp3yer5aepbtp/include/boost/type_traits/integral_constant.hpp:34:20: error: expected identifier before ‘(’ token                                                                                                                                                                       
    template <class I, I val> struct integral_c;                                                                                                                                               
                    ^                                                                                                                                                                          
/home/xap/local/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/boost-1.68.0-j2mqoxflxrkb5c27hqgzp3yer5aepbtp/include/boost/type_traits/integral_constant.hpp:34:20: error: expected ‘)’ before ‘__extension__’                                                                                                                                                                        
    template <class I, I val> struct integral_c;                                                                                                                                               
                    ^                                                                                                                                                                          
/home/xap/local/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/boost-1.68.0-j2mqoxflxrkb5c27hqgzp3yer5aepbtp/include/boost/type_traits/integral_constant.hpp:34:20: error: expected ‘>’ before ‘__extension__’                                                                                                                                                                        
/home/xap/local/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/boost-1.68.0-j2mqoxflxrkb5c27hqgzp3yer5aepbtp/include/boost/type_traits/integral_constant.hpp:34:20: error: expected unqualified-id before ‘)’ token                                                                                                                                                                   
    template <class I, I val> struct integral_c;
```
This is also a problem with many other boost headers as well.

The only known workaround is to change the order so that `lapacke.h` goes *after* boost header. It sounds like a bug somewhere, but I have trouble understanding why that is the case. It always go through `complex.h` header, but unclear how and why it ends with boost.

**Comment by aprokop** [comment]
Just found another workaround: add
```c++
#include <complex>
#define lapack_complex_float std::complex<float>
#define lapack_complex_double std::complex<double>
```
before including `lapacke.h`.

**Comment by martin-frbg** [comment]
Could be that something in the boost header triggers multiple inclusion of complex.h. The only remotely similar topic I managed to find is https://svn.boost.org/trac10/ticket/12781 but that apparently went away with a rebuild of boost. The OpenBLAS lapacke.h is unchanged from the one in the netlib reference implementation of LAPACK.

**Comment by aprokop** [comment]
Also, once I reordered with boost in my project, it got triggered on Kokkos library too:
```
In file included from /usr/include/c++/7/complex.h:36:0,                                                                                                                                       
                 from /home/xap/local/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/openblas-0.3.3-xlt4harsqysny4q4qw53g34s6jfz5wtx/include/lapacke.h:73,                             
                 from ../../include/mfmg/dealii/lanczos_lanczos.templates.hpp:22,                                                                                                              
                 from ../../include/mfmg/dealii/lanczos_deflatedlanczos.templates.hpp:23,                                                                                                      
                 from ../../tests/test_lanczos.cc:14:                                                                                                                                          
/home/xap/local/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/trilinos-master-wahhgsi2mnozyjqlhbgn6wyynupjs2q3/include/impl/Kokkos_Utilities.hpp: At global scope:                   
/home/xap/local/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/trilinos-master-wahhgsi2mnozyjqlhbgn6wyynupjs2q3/include/impl/Kokkos_Utilities.hpp:160:20: error: expected ‘)’ before ‘_
_extension__’                                                                                                                                                                                  
 template <unsigned I, typename IntegerSequence>          
```
Both boost and Kokkos seem to be triggered when using `I` in a template. So I'm no longer certain that's just boost. But it is almost certain have something to do with complex.

**Comment by martin-frbg** [comment]
Probably the `#define I _Complex_I` from the glibc-provided complex.h ?

**Comment by martin-frbg** [comment]
Exact same thing here: https://svn.boost.org/trac10/ticket/10948 seems they only fix this bug on a case-by-case basis. Guess you should really take this up with the Boost team at https://github.com/boostorg  (https://github.com/boostorg/type_traits subproject for the original problem, though it is safe to assume that each of the gazillion subprojects they created has this in some way or other)

**Comment by aprokop** [comment]
Oh, boy... in my boost installation:
```
$ grep -rl \<I\> | wc -l
97
```

**Comment by brada4** [comment]
complex.h defines imaginary number as constant I (capital) while in c++ it is i(small)
Including complex.h along with any of those 97 occurences will break the code. How it breaks depends on order of inclusion.

As a workaround you can make your own minilapacke.h including just prototypes of D- and S- functions you use without the need for complex.h, over time with good luck that could be reduced to just including lapacke.h

**Comment by martin-frbg** [comment]
At least in the past, the Boost project appears to have accepted that this is a bug that needs to be fixed in their code. On the other hand, LAPACKE does neither claim nor aspire to provide a C++ API as far as I know. There is an ongoing project to produce such an API at https://bitbucket.org/icl/lapackpp that _may_ be included in the netlib reference lapack in the future (see recent PR
https://github.com/Reference-LAPACK/lapack/pull/297 )

**Comment by aprokop** [comment]
OK, great discussion so far. One other thing I found is that the following patch seems to also work:
```diff
--- lapacke.h.orig      2019-02-01 08:12:29.852341011 -0500
+++ lapacke.h   2019-02-01 08:09:02.296335500 -0500
@@ -70,7 +70,11 @@
 
 /* Complex type (single precision) */
 #ifndef lapack_complex_float
+#ifdef __cplusplus
+#include <complex>
+#else
 #include <complex.h>
+#endif
 #define lapack_complex_float    float _Complex
 #endif
 
@@ -86,7 +90,11 @@
 
 /* Complex type (double precision) */
 #ifndef lapack_complex_double
+#ifdef __cplusplus
+#include <complex>
+#else
 #include <complex.h>
+#endif
 #define lapack_complex_double   double _Complex
 #endif
 
```
Judging from [C++ complex](https://en.cppreference.com/w/cpp/numeric/complex) page, C++ complex and C complex are guaranteed to be binary compatible from C++11. As I never really worked with complex, I'm not 100% sure if it does the right thing. But if it is, would it be acceptable?

**Comment by brada4** [comment]
The code (lapacke.h) originates over there:
https://github.com/Reference-LAPACK/lapack/issues

**Comment by aprokop** [comment]
> The code (lapacke.h) originates over there:
> [Reference-LAPACK/lapack/issues](https://github.com/Reference-LAPACK/lapack/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)

The `lapacke.h` in that repo looks a bit different, and does not include complex.

**Comment by martin-frbg** [comment]
The two are identical if you compare Reference-LAPACK at release 3.8.0 rather than their current master branch. (Apparently it was recently split into two files, lapacke.h and lapack.h with the `#include complex.h` moving to the latter)

**Comment by martin-frbg** [comment]
BTW your patch looks good to me, but the Reference-LAPACK folks should still be informed about the problem and likely solution.

**Comment by aprokop** [comment]
> The two are identical if you compare Reference-LAPACK at release 3.8.0 rather than their current master branch.

Oh, you are right, my bad.

> BTW your patch looks good to me, but the Reference-LAPACK folks should still be informed about the problem and likely solution.

The only thing I'm not sure about is whether it should be further protected by C++11 requirement, something like
```
#if defined(__cplusplus) && (__cplusplus >= 201103L)
...
```

> Reference-LAPACK folks should still be informed about the problem and likely solution.

I'm not sure about OpenBLAS and Reference-LAPACK relationship. Is it as simple as creating an issue there and just pointing to this one?

**Comment by brada4** [comment]
Relationship is such that openblas includes almost verbatim fortran lapack and its c wrapper from reference implementation. So you actually are interacting with their code. 
Regarding how elaborate fix should be - no idea, we will copy what will come out as a result. Probably worth re-basing to their new 2-file schema.

**Comment by martin-frbg** [comment]
I have now found that there is some precedent in that lapacke_config.h already does `#include <complex>` (without also checking for C++11) - but only when C++ complex types are configured, the default is C99 complex types (see lapacke/README). 
Pointing the lapack folks to this issue should be sufficient.
