### ISSUE TITLE
segfault in sgemm_beta() on POWER9

### ISSUE THREAD

**Issue by davemq** [xianyi/OpenBLAS#2011]
One of our recent builds of PyTorch for POWER 8 and 9 tickled a segfault bug in `sgemm_beta()`. `sgemm_beta()` crashed on

        dcbst	PRE, CO1

This instruction will write the data block at `PRE(CO1)` to main memory.  In the crashing case, `CO1` was `PRE` bytes before the end of a page, so `PRE(CO1)` points to the beginning of the next page. That page is not mapped, e.g. we're at the end of our stack, and we get a segmentation fault.

I suspect this is actually supposed to be a prefetch, ala

        dcbtst	PRE, CO1

which shows up in another loop. This is in line with assembly implementations of `gemm_beta()` on other platforms. Making this change causes the segfault to no longer hit.

Alternatively, if there's some reason to write data cache blocks to main memory (why in one loop but not the other?) then we likely want

        dcbst	0, CO1

**Comment by martin-frbg** [comment]
From your description the prefetch does seem a bit more likely - the same situation exists in zgemm_beta.S as well but one is probably a modified copy of the other. In any case this appears to be a "historic" bug inherited from GotoBLAS2, so the prime suspect is not available for questioning.
