### ISSUE TITLE
Compile fails on 32-bit

### ISSUE THREAD

**Issue by opoplawski** [xianyi/OpenBLAS#2033]
See https://kojipkgs.fedoraproject.org//work/tasks/5955/33095955/build.log 
```
gfortran -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m32 -march=i686 -mtune=generic -msse2 -mfpmath=sse -mstackrealign -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m32 -march=i686 -mtune=generic -msse2 -mfpmath=sse -mstackrealign -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -frecursive -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -o dblat2 dblat2.o ../libRblas-r0.3.6.dev.a -lm -lgfortran -lm -lgfortran -L/usr/lib/gcc/i686-redhat-linux/9 -L/usr/lib/gcc/i686-redhat-linux/9/../../..  -lc  
BUILDSTDERR: /usr/bin/ld: ../libRblas-r0.3.6.dev.a(dynamic.o): in function `support_avx512':
BUILDSTDERR: /builddir/build/BUILD/openblas-0.3.6/Rblas/driver/others/dynamic.c:336: undefined reference to `xgetbv'
BUILDSTDERR: collect2: error: ld returned 1 exit status
BUILDSTDERR: make[1]: *** [Makefile:137: dblat1] Error 1
BUILDSTDERR: make[1]: *** Waiting for unfinished jobs....
BUILDSTDERR: /usr/bin/ld: ../libRblas-r0.3.6.dev.a(dynamic.o): in function `support_avx512':
BUILDSTDERR: /builddir/build/BUILD/openblas-0.3.6/Rblas/driver/others/dynamic.c:336: undefined reference to `xgetbv'
BUILDSTDERR: collect2: error: ld returned 1 exit status
BUILDSTDERR: make[1]: *** [Makefile:134: sblat1] Error 1
BUILDSTDERR: /usr/bin/ld: ../libRblas-r0.3.6.dev.a(dynamic.o): in function `support_avx512':
BUILDSTDERR: /builddir/build/BUILD/openblas-0.3.6/Rblas/driver/others/dynamic.c:336: undefined reference to `xgetbv'
BUILDSTDERR: collect2: error: ld returned 1 exit status
BUILDSTDERR: make[1]: *** [Makefile:143: cblat1] Error 1
BUILDSTDERR: /usr/bin/ld: ../libRblas-r0.3.6.dev.a(dynamic.o): in function `support_avx512':
BUILDSTDERR: /builddir/build/BUILD/openblas-0.3.6/Rblas/driver/others/dynamic.c:336: undefined reference to `xgetbv'
BUILDSTDERR: collect2: error: ld returned 1 exit status
BUILDSTDERR: make[1]: *** [Makefile:146: zblat1] Error 1
BUILDSTDERR: /usr/bin/ld: ../libRblas-r0.3.6.dev.a(dynamic.o): in function `support_avx512':
BUILDSTDERR: /builddir/build/BUILD/openblas-0.3.6/Rblas/driver/others/dynamic.c:336: undefined reference to `xgetbv'
BUILDSTDERR: collect2: error: ld returned 1 exit status
BUILDSTDERR: make[1]: *** [Makefile:149: sblat2] Error 1
BUILDSTDERR: /usr/bin/ld: ../libRblas-r0.3.6.dev.a(dynamic.o): in function `support_avx512':
BUILDSTDERR: /builddir/build/BUILD/openblas-0.3.6/Rblas/driver/others/dynamic.c:336: undefined reference to `xgetbv'
BUILDSTDERR: collect2: error: ld returned 1 exit status
BUILDSTDERR: make[1]: *** [Makefile:152: dblat2] Error 1
```

This is with latest develop branch

**Comment by brada4** [comment]
Does it help adding NO_AVX512=1? I think it is not implied by NO_AVX2 already present in i386 build, thus something from around 0.3.3 is broke same way.

**Comment by brada4** [comment]
@martin-frbg this issue probably deserves 036 tag
I have plan to clean warnings , bug-like before cosmetic for x86

**Comment by martin-frbg** [comment]
~~I wonder how it gets there - somehow it must have passed the checks for AVX and AVX2 to do this.~~
This problem was probably masked by the earlier mistake in the compiler capability check until very recently.

**Comment by opoplawski** [comment]
This doesn't appear to be sufficient, still getting the same error.  I added BINARY=32 to make args without any effect either.  See https://kojipkgs.fedoraproject.org//work/tasks/1001/33111001/build.log

**Comment by brada4** [comment]
If you examine code in dynamic.c -> add NO_AVX=1 next to NO_AVX512 line Martin added.

**Comment by martin-frbg** [comment]
I just merged another commit that should fix this.

**Comment by brada4** [comment]
Still dynamic.c does not get freshly added no_avx512 and tries to emit xsave class instruction. 
I have hard time understanding the interactions of avx512 being overridden in so many places, like knowing which one is in force in particular case

**Comment by martin-frbg** [comment]
@brada4 the build worked for me ?

**Comment by brada4** [comment]
did not work for me 
opensuse tumbleweed of yesterday, last commit --afa4
make DYNAMIC_ARCH=1 DYNAMIC_OLDER=1
same build log as in initial report - xgetbv missing
NO_AVX512=1 addressed thing for me
I willl get the build log.

**Comment by martin-frbg** [comment]
Did a fresh checkout of `develop`, definitely builds fine here with BINARY=32 DYNAMIC_ARCH=1 (with and without DYNAMIC_OLDER).

**Comment by brada4** [comment]
not for me. both builds make -s CC={cc} DYNAMIC_ARCH=1
gcc fails clang succeeds.
```
$ rpm -q make perl gcc gcc-fortran clang
make-4.2.1-7.5.i586
perl-5.28.1-2.2.i586
gcc-8-2.4.i586
gcc-fortran-8-2.4.i586
clang-7.0.1-2.1.i586
```

[gcc821.log](https://github.com/xianyi/OpenBLAS/files/2922422/gcc821.log)
[clang7.log](https://github.com/xianyi/OpenBLAS/files/2922423/clang7.log)

**Comment by brada4** [comment]
Outside scope of current issue - Wuninitialized screams bug, is it worth cleaning dead codes from setparam\* along the walk through?

**Comment by martin-frbg** [comment]
Definitely cannot reproduce your gcc821 issue (with gcc9 snapshot from a week ago), are you certain this was from a clean and current checkout ? The -Wunitialized warning from setparam has been there "forever", it is just amplified by the DYNAMIC_ARCH build as it gets repeated for each target. Little point in cleaning this one up when there are much more serious issues in need of attention.

**Comment by brada4** [comment]
Build is absolutely clean, no dirty tricks involved. Installed clean tumbleweed 32bit system in a VM without any customization at all.

What raised eyebrow uninitialized var in runtime library, like 1char change to silence (outside purely cosmetic setparam build system noise)
```
memory.c: In function ‘blas_memory_alloc’:
memory.c:2783:56: warning: ‘mypos’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   if (memory[position].pos == -1) memory[position].pos = mypos;
                                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~
```

**Comment by brada4** [comment]
dynamic.c
xgetbf definition is ifndef NO_AVX
while the section where it is called is ifndef NO_AVX512 (which should have been passed esp after your fixes)

**Comment by martin-frbg** [comment]
Got it now - my earlier PRs addressed BINARY32=1 builds on 64bit, and the failure mode happens to be different in an actual 32bit environment.
