### ISSUE TITLE
ctest din3

### ISSUE THREAD

**Issue by quickwritereader** [xianyi/OpenBLAS#2036]
din3 file differs form test/dblat3.dat and on both values of N does not handle all cases

I believe N value should be changed at least to 7 for din3 and dblat3

```
'DBLAT3.SNAP'     NAME OF SNAPSHOT OUTPUT FILE
-1                UNIT NUMBER OF SNAPSHOT FILE (NOT USED IF .LT. 0)
F        LOGICAL FLAG, T TO REWIND SNAPSHOT FILE AFTER EACH RECORD.
T        LOGICAL FLAG, T TO STOP ON FAILURES.
T        LOGICAL FLAG, T TO TEST ERROR EXITS.
2        0 TO TEST COLUMN-MAJOR, 1 TO TEST ROW-MAJOR, 2 TO TEST BOTH
16.0     THRESHOLD VALUE OF TEST RATIO
6                 NUMBER OF VALUES OF N
1 2 3 5 7 9 35    VALUES OF N
3                 NUMBER OF VALUES OF ALPHA
0.0 1.0 0.7       VALUES OF ALPHA
3                 NUMBER OF VALUES OF BETA
0.0 1.0 1.3       VALUES OF BETA
```
Plus dblat3.dat cases are different than din3
0 1 2 3 7 31 63   VALUES OF N

 Other files should be checked too

**Comment by martin-frbg** [comment]
The din3 file matches its (original) counterpart in lapack-netlib/CBLAS/testing except for the (unused) extraneous entry 35 for N. dblat3.dat (apparently unchanged from GotoBLAS2) matches the dblat3.in from netlib BLAS/TESTING except for the choice of higher values of N (and again an unused seventh entry that is likely leftover from earlier testing of behaviour at larger N).
Even comparing din3 and dblat3.in in the netlib reference shows small differences in the choice of N, and it is not clear to me why they would need to match ? (A case could be made that differences could even be beneficial as a wider range of options would be tested by the two tests combined, but
anyway this is just a relatively quick sanity check for compilation and not an in-depth examination like
BLAS-Tester or the ATLAS tests would provide.)

**Comment by quickwritereader** [comment]
( Afaik it is limited by 64) It does not suit for 16x4 kernel correctness check. I'm currently working on power9 trying to improve performance. My wrong changes were detected by test but not by ctest. Looking at it I saw that value 35 was not tested.

**Comment by martin-frbg** [comment]
Probably best to adapt them for your local needs while developing (which is most probably where the seventh entry comes from) but I really do not see a need to modify what gets distributed with the project.
BTW there is #458 still open for what happens at large N - the limit at 64 or 65 is just an arbitrary value set in the fortran sources)

**Comment by quickwritereader** [comment]
Ok then I'll close as it is related to #458 .
I just wanted to inform.
