### ISSUE TITLE
using -DBUILD_SHARED_LIBS=ON results in build error

### ISSUE THREAD

**Issue by amwink** [xianyi/OpenBLAS#2043]
After cloning the repository and successful
   make && make install PREFIX=$HOME/usr/local
I have been trying to build a shared library for openblas using the cmake option  -DBUILD_SHARED_LIBS=ON

Starting with cmake and the options files generated in the first build --successful after specifying the fortran compiler, I enabled the options for building RELAPACK and DYNAMIC_ARCH: still building successfully. But the when I ran 
   `cmake -DBUILD_SHARED_LIBS=ON ..`
from the build directory, the make exited with this error:
```
relapack/src/CMakeFiles/relapack_src.dir/lapack_wrappers.c.o: In function `stgsyl_':
lapack_wrappers.c:(.text+0xd70): multiple definition of `stgsyl_'
CMakeFiles/openblas.dir/lapack-netlib/SRC/stgsyl.f.o:stgsyl.f:(.text+0x0): first defined here
relapack/src/CMakeFiles/relapack_src.dir/lapack_wrappers.c.o: In function `dtgsyl_':
lapack_wrappers.c:(.text+0xdf3): multiple definition of `dtgsyl_'
CMakeFiles/openblas.dir/lapack-netlib/SRC/dtgsyl.f.o:dtgsyl.f:(.text+0x0): first defined here
relapack/src/CMakeFiles/relapack_src.dir/lapack_wrappers.c.o: In function `ctgsyl_':
lapack_wrappers.c:(.text+0xe76): multiple definition of `ctgsyl_'
CMakeFiles/openblas.dir/lapack-netlib/SRC/ctgsyl.f.o:ctgsyl.f:(.text+0x0): first defined here
relapack/src/CMakeFiles/relapack_src.dir/lapack_wrappers.c.o: In function `ztgsyl_':
lapack_wrappers.c:(.text+0xef9): multiple definition of `ztgsyl_'
CMakeFiles/openblas.dir/lapack-netlib/SRC/ztgsyl.f.o:ztgsyl.f:(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
CMakeFiles/openblas.dir/build.make:129643: recipe for target 'lib/libopenblas.so.0.3' failed
make[2]: *** [lib/libopenblas.so.0.3] Error 1
CMakeFiles/Makefile2:116: recipe for target 'CMakeFiles/openblas.dir/all' failed
make[1]: *** [CMakeFiles/openblas.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```
Am I right in thinking that this has to do with the 'dynamic architecture' option and that the shared libs and dynamic architecture options cannot be used at the same time?

EDIT -- it seems to be the other way round. switching on RELAPACK breaks the build when building shared libraries. with DYNAMIC_ARCH on it does build. The question remains: is there a reason why some options clash with building shared libraries?

**Comment by martin-frbg** [comment]
Shared libs and dynamic architecture should definitely be able to coexist, in particular as dynamic_arch "only" adds individual sets of blas microkernels for the various supported cpus but uses a common lapack. This looks more like a conflict between RELAPACK and the generic LAPACK, perhaps the linking tricks used there do not (or no longer) work with cmake or your compiler/linker version.

**Comment by martin-frbg** [comment]
Seems the ReLAPACK build currently works only with plain make, not cmake. The difference is that the plain Makefiles use `ar` to build the library (where it is possible to tell it to override earlier symbols) while cmake invokes the linker on all object files directly. Still need to find if/when/why this changed - at least I am fairly certain that this combination of options used to work with cmake in the past.

**Comment by martin-frbg** [comment]
Actually it appears that this never worked for building the shared library - should be solved by the addition of the appropriate linker option in #2044 unless I overiooked something (again)...

**Comment by amwink** [comment]
It does work now. Thanks!
