### ISSUE TITLE
building dynamic arch package fails if CPU is not recognized

### ISSUE THREAD

**Issue by svillemot** [xianyi/OpenBLAS#2048]
Hi,

This is [Debian bug #923607](https://bugs.debian.org/923607).

The compilation of OpenBLAS with dynamic arch on x86 fails when the CPU of the build machine is not recognized (in this case the problem happens on a virtualized host). One gets:
```
Makefile:135: *** OpenBLAS: Detecting CPU failed. Please set TARGET explicitly, e.g. make TARGET=your_cpu_target. Please read README for the detail..  Stop.
```

This seems wrong. The dynamic arch package is precisely supposed to be independent of the building machine, so the result of CPU detection should not be taken into account.

As a workaround, I have tried to set `TARGET=GENERIC`, but it still fails to build (at a later point though, after compiling the Prescott kernel).

Debian packages are supposed to be buildable on any machine, so I would be glad if you could point me to a solution.

Thanks for your work,

**Comment by martin-frbg** [comment]
Not sure why TARGET=GENERIC would not work (do you have a build log from this ?), but please try TARGET=NEHALEM (or even a really old one like PRESCOTT). The problem with virtualized hosts is that they present a weird subset of the host cpu features by default, so their cpuinfo does not match any actual hardware known to OpenBLAS.

**Comment by martin-frbg** [comment]
Reproduced the build problem with `DYNAMIC_ARCH=1 TARGET=GENERIC` locally now - for some weird reason the generic target makes the build tools "forget" which source files to use for compiling the PRESCOTT strmm_kernel_XY objects...

**Comment by brada4** [comment]
@svillemot what is actual /proc/cpuinfo in a VM? Maybe it is from a genuine real CPU that openblas does not recognize.
TARGET=? or autodetected one is used to select compile options for some common (not cpu-specific) code, so one has to set something archaic to make resulting lib universally usable, like prescott. Probably the "generic" name is more straightforward choice for your packaging needs.

**Comment by svillemot** [comment]
Thanks for your feedback. I am going to apply your patch and build with `TARGET=GENERIC` (on x86, x86_64 and arm64).

**Comment by brada4** [comment]
Can you get /proc/cpuinfo from in and out of virtual machine? There could be real cpu in hiding (or less likely a new way of breaking VCPU)

**Comment by svillemot** [comment]
@brada4 Even if we fix the problem for the specific VM on which I got the failure, this would not really solve the problem I raised in this issue. My point is that the dynamic arch build should succeed on *any* machine (even the weirdest VM we can think of), so the `TARGET=GENERIC` road looks much more promising.

**Comment by brada4** [comment]
The correct detection of that CPU would have masked the issue you spotted, that's clear. 
With that spotted, would you be so kind and help out with particular unrecognized CPU?

**Comment by svillemot** [comment]
Here is the contents of `/proc/cpuinfo` on the VM guest:
```
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 95
model name      : Intel(R) Atom(TM) CPU C3955 @ 2.10GHz
stepping        : 1
microcode       : 0x1
cpu MHz         : 2100.000
cache size      : 4096 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl pni pclmulqdq vmx ssse3 cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave rdrand hypervisor lahf_lm 3dnowprefetch ibrs ibpb kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust smep erms mpx rdseedsmap clflushopt xsaveopt xsavec xgetbv1 xsaves arat
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass
bogomips        : 4200.00
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:
```

Note that I don't have access to the host (and I am not the owner of the VM, I was only kindly given access to it by the person who reported the bug in Debian).

**Comment by martin-frbg** [comment]
Thanks. CPUID appears to be that of a genuine Goldmont/Denverton Atom core, I'll check ASAP if this is missing in the builtin table.

**Comment by sanvila** [comment]
Hi. Just for the record: Those CPUs are the ones from Scaleway instances of type 1-XS or 1-S.

**Comment by martin-frbg** [comment]
Genuinely missing, will fix this later today (and use the opportunity to check if wikichip has any other "new" entries that OpenBLAS might be missing)
