### ISSUE TITLE
Android CMake compile: Unable to find dgemm_kernel_2x2.s

### ISSUE THREAD

**Issue by xsacha** [xianyi/OpenBLAS#2053]
I have this issue since moving to 0.3.5

See log here: https://travis-ci.org/xsacha/hunter/jobs/504456660

`/home/travis/build/xsacha/hunter/_testing/Hunter/_Base/42b7747/9040522/9bbf8fe/Build/OpenBLAS/Build/OpenBLAS-Release-prefix/src/OpenBLAS-Release-build/kernel/CMakeFiles/dgemm_kernel.S:8:10: fatal error: '/home/travis/build/xsacha/hunter/_testing/Hunter/_Base/42b7747/9040522/9bbf8fe/Build/OpenBLAS/Source/kernel/arm64/dgemm_kernel_2x2.S' file not found
#include "/home/travis/build/xsacha/hunter/_testing/Hunter/_Base/42b7747/9040522/9bbf8fe/Build/OpenBLAS/Source/kernel/arm64/dgemm_kernel_2x2.S"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[5]: *** [kernel/CMakeFiles/kernel.dir/CMakeFiles/dgemm_kernel.S.o] Error 1
make[4]: *** [kernel/CMakeFiles/kernel.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....`

**Comment by martin-frbg** [comment]
I do not see a TARGET argument among you CMAKE options, are you sure this was not necessary for the cross-compilation earlier ?

**Comment by martin-frbg** [comment]
Possibly related to #1908 (or my related PR #1946) though...

**Comment by xsacha** [comment]
TARGET is autodetected as ARMV8. Last working version was 0.3.3.
0.3.4 had some other issues I think so I decided to test out 0.3.5.

It looks like the #1908 you linked to. So it should be fixed in #1946 for 0.3.6. Sorry for the duplicate.
