### ISSUE TITLE
[cmake][android][clang] Assembly compilation fails with clang/NDK-r19b

### ISSUE THREAD

**Issue by ayounes-nviso** [xianyi/OpenBLAS#2054]
Latest develop branch (#f18ab6c17b262f617b5bbad87555bca3b490b079)

Cross-compiling from ubuntu-18.04 for Android-ARMv7 (32bit), using NDK r19b and the new lld loader:

`
cmake -DDYNAMIC_ARCH=OFF -DUSE_THREAD=OFF -DNUM_THREADS=64 -DBUILD_WITHOUT_LAPACK=ON -DBUILD_RELAPACK=OFF -DNOFORTRAN=ON -DBUILD_SHARED_LIBS=OFF  -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_TOOLCHAIN_FILE:STRING=/opt/android-ndk/build/cmake/android.toolchain.cmake -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=true -DANDROID_ABI:STRING=armeabi-v7a -DANDROID_STL:STRING=c++_shared -DANDROID_TOOLCHAIN:STRING=clang -DANDROID_PLATFORM:STRING=android-21 -DCMAKE_EXE_LINKER_FLAGS:STRING=-fuse-ld=lld
`

Here is just the first error message, I will upload the full log in a comment.
[1/3] cd /out/src/openblas_project-build && /build/cmake-3.12.3-Linux-x86_64/bin/cmake --build . && /build/cmake-3.12.3-Linux-x86_64/bin/cmake -E touch /out/src/openblas_project-stamp/openblas_project-build
FAILED: src/openblas_project-stamp/openblas_project-build 
cd /out/src/openblas_project-build && /build/cmake-3.12.3-Linux-x86_64/bin/cmake --build . && /build/cmake-3.12.3-Linux-x86_64/bin/cmake -E touch /out/src/openblas_project-stamp/openblas_project-build
[1/252] Building ASM object kernel/CMakeFiles/kernel.dir/CMakeFiles/dgemv_n.S.o
FAILED: kernel/CMakeFiles/kernel.dir/CMakeFiles/dgemv_n.S.o 
/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target armv7-none-linux-androideabi21 -gcc-toolchain /opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot  -I/sources/deps-base/pkg-openblas/src -I. -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mfpu=vfpv3-d16 -fno-addrsig -march=armv7-a -mthumb -Wa,--noexecstack -Wformat -Werror=format-security   -fPIC -DNO_LAPACK -DNO_LAPACKE -DNO_AVX -DMAX_CPU_NUMBER=64 -DMAX_PARALLEL_NUMBER=1 -DNO_AFFINITY -DVERSION="\"0.3.6.dev\"" -Oz -DNDEBUG  -fPIC -MD -MT kernel/CMakeFiles/kernel.dir/CMakeFiles/dgemv_n.S.o -MF kernel/CMakeFiles/kernel.dir/CMakeFiles/dgemv_n.S.o.d -o kernel/CMakeFiles/kernel.dir/CMakeFiles/dgemv_n.S.o -c kernel/CMakeFiles/dgemv_n.S
<instantiation>:5:2: error: invalid instruction, any one of the following would fix this:
 fldd d24 , [fp, #-228]
 ^
/sources/deps-base/pkg-openblas/src/kernel/arm/gemv_n_vfpv3.S:634:2: note: while in macro instantiation
 INIT_F8
 ^
<instantiation>:5:7: note: operand must be a register in range [s0, s31]
 fldd d24 , [fp, #-228]
      ^
/sources/deps-base/pkg-openblas/src/kernel/arm/gemv_n_vfpv3.S:634:2: note: while in macro instantiation
 INIT_F8
 ^
<instantiation>:5:7: note: operand must be a register in range [d0, d15]
 fldd d24 , [fp, #-228]
      ^
/sources/deps-base/pkg-openblas/src/kernel/arm/gemv_n_vfpv3.S:634:2: note: while in macro instantiation
 INIT_F8
 ^
<instantiation>:6:2: error: invalid instruction
 vmov.f64 d25 , d24
 ^
/sources/deps-base/pkg-openblas/src/kernel/arm/gemv_n_vfpv3.S:634:2: note: while in macro instantiation
 INIT_F8
 ^
<instantiation>:7:2: error: invalid instruction
 vmov.f64 d26 , d24
 ^
/sources/deps-base/pkg-openblas/src/kernel/arm/gemv_n_vfpv3.S:634:2: note: while in macro instantiation
 INIT_F8
 ^
<instantiation>:8:2: error: invalid instruction
 vmov.f64 d27 , d24
 ^
/sources/deps-base/pkg-openblas/src/kernel/arm/gemv_n_vfpv3.S:634:2: note: while in macro instantiation
 INIT_F8
 ^
<instantiation>:9:2: error: invalid instruction
 vmov.f64 d28 , d24
 ^
/sources/deps-base/pkg-openblas/src/kernel/arm/gemv_n_vfpv3.S:634:2: note: while in macro instantiation
 INIT_F8
 ^
<instantiation>:10:2: error: invalid instruction
 vmov.f64 d29 , d24
 ^
/sources/deps-base/pkg-openblas/src/kernel/arm/gemv_n_vfpv3.S:634:2: note: while in macro instantiation
 INIT_F8
 ^
<instantiation>:11:2: error: invalid instruction
 vmov.f64 d30 , d24
 ^
/sources/deps-base/pkg-openblas/src/kernel/arm/gemv_n_vfpv3.S:634:2: note: while in macro instantiation
 INIT_F8
 ^
<instantiation>:12:2: error: invalid instruction
 vmov.f64 d31 , d24
 ^
/sources/deps-base/pkg-openblas/src/kernel/arm/gemv_n_vfpv3.S:634:2: note: while in macro instantiation
 INIT_F8
 ^
<instantiation>:5:11: error: operand must be a register in range [d0, d15]
 vmla.f64 d24 , d4 , d8
          ^
<instantiation>:3:2: note: while in macro instantiation
 KERNEL_F8X1
 ^

**Comment by ayounes-nviso** [comment]
[android-compilation-fails.txt](https://github.com/xianyi/OpenBLAS/files/2956473/android-compilation-fails.txt)

**Comment by martin-frbg** [comment]
Where does the `-mfpu=vfpv3-d16` come from ? Judging from http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0472h/CJADDCIF.html and the OpenBLAS README.md you would need `-mfpu=vfpv3` to compile the ARMV7 kernels, or set `TARGET=ARMV6` if you are really restricted to 16 registers.

**Comment by ayounes-nviso** [comment]
I am affraid it comes from the new NDL cmake toolchain:

grep -C4 -n vfpv3-d16 /home/ayounes/ndk/android-ndk-r19b/build/cmake/android.toolchain.cmake
```
468-endif()
469-
470-# Toolchain and ABI specific flags.
471-if(ANDROID_ABI STREQUAL armeabi-v7a)
472:  list(APPEND ANDROID_COMPILER_FLAGS -mfpu=vfpv3-d16)
473-endif()
474-if(ANDROID_ABI STREQUAL x86 AND ANDROID_PLATFORM_LEVEL LESS 24)
475-  # http://b.android.com/222239
476-  # http://b.android.com/220159 (internal http://b/31809417)

```

**Comment by martin-frbg** [comment]
According to the `cmake` documentation one can apparently define CMAKE_ANDROID_ARM_NEON to ON to enable vfpv3-d32 and the neon extensions instead of the default vfpv3-d16. (Not sure if this helps here, and why this problem would come up only now)

**Comment by ayounes-nviso** [comment]
You are right, I had those in my toolchain files before I switched to NDK toolchain!

So I added `-DANDROID_ARM_MODE:STRING=arm -DANDROID_ARM_NEON:BOOL=ON` and now it works!

Terribly sorry about the noise and wasting your time with this!
