### ISSUE TITLE
cmake system assumes relies on CMAKE_SYSTEM_PROCESSOR to determine 32 vs 64bit

### ISSUE THREAD

**Issue by gdevenyi** [xianyi/OpenBLAS#2056]
Currently CMAKE_SYSTEM_PROCESSOR is used to determine x86 or x86_64:
https://github.com/xianyi/OpenBLAS/blob/develop/cmake/system_check.cmake#L41

Unfortunately, it is possible for CMAKE_SYSTEM_PROCESSOR to be x86_64 on a 32bit userspace, resulting in BINARY being set to 64, and breaking things.

It appears the proper way to check this is via something like this:
https://dilawarnotes.wordpress.com/2016/01/13/detect-architecture-of-your-system-using-cmake/

**Comment by gdevenyi** [comment]
The suggested check works for me if hackily patched into system_check.cmake

**Comment by brada4** [comment]
Could you assist in setting up a broken system?
It is default that CMAKE is detecting. You can "correct" it if you need to.

**Comment by xsacha** [comment]
```CMake
...
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "amd64.*|x86_64.*|AMD64.*")
  if("${CMAKE_SIZEOF_VOID_P}" EQUAL "8")
    set(X86_64 1)
  else()
    set(X86 1)
  endif()
...
```

See #2058 for a PR

**Comment by martin-frbg** [comment]
Thanks (to both of you). I wonder if this situation could occur on ARM64 as well ?

**Comment by gdevenyi** [comment]
My guess would be yes but I have no ARM systems to check that.
