### ISSUE TITLE
OpenBLAS with LAPACK on Android Clang Toolchain?

### ISSUE THREAD

**Issue by jgavris** [xianyi/OpenBLAS#2059]
Has anyone been able to build OpenBLAS with LAPACK using the recent NDK's with Clang? If so, could you perhaps just share an arm64 and x86_64 binary?

**Comment by brada4** [comment]
You have variety of options, 
* You can examine relapack for parts of LAPACK in C.
* You can find earlier well working attempt at fortran here: https://github.com/buffer51/android-gfortran , it might be a bit outdated, but if you rebuild entire GCC alongside clang you get gfortran too.
* Another try is to get flang on top of llvm in android SDK
Be warned that neither is tried recently

**Comment by martin-frbg** [comment]
ReLAPACK calls LAPACK itself so is not a replacement.
Also, open tickets like https://github.com/flang-compiler/flang/issues/81 suggest that flang is not yet capable of cross-compiling. Perhaps you can use the termux environment for direct compilation on the target.

**Comment by brada4** [comment]
relapack implements dozen of lapack functions without any fortran needs, if that is enough.... No cigar, but might be useful

**Comment by jgavris** [comment]
@martin-frbg Termux environment is pretty interesting, just build it on the phone and copy it off I guess? I'm just a bit surprised there's no standard LAPACK on Android yet. iOS / macOS has Apple's very generous [Accelerate.framework](https://developer.apple.com/documentation/accelerate).

**Comment by martin-frbg** [comment]
Yep. See https://github.com/its-pointless/gcc_termux for compiler packages. (And I suspect Apple already had Accelerate for OSX so it meant little effort for them to rebuild it for iOS, while Google had no in-house implementation of LAPACK and little incentive to pick and bundle any of the free ones available in the Linux ecosystem. Note that until the recent deprecation of gcc in the NDK, building fortran code with it was fairly straightforward - perhaps it still is, if one manages to set up a mixed clang/gfortran build.)

**Comment by djacobs010** [comment]
Wanted to comment on this and see if there's any update on the easiest way to use OpenBLAS for Android?

**Comment by brada4** [comment]
You can build it without fortran (LAPACK) with normal clang NDK. Rest is as tough as described, no fortran in normal NDK.

**Comment by djacobs010** [comment]
Can build r23b easily without fortran (without lapack) with just these 2 commands:
```sh
export PATH=/opt/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/:$PATH
make HOSTCC=gcc CC=/opt/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android31-clang ONLY_CBLAS=1 TARGET=ARMV8
```

**Comment by brada4** [comment]
You can reed that in wiki:
https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android

**Comment by martin-frbg** [comment]
@brada4 I assume he copied the information here at about the same time as I updated the wiki page with it. Nothing wrong with that...

**Comment by djacobs010** [comment]
Is it possible to build OpenBLAS with CLAPACK?

**EDIT**: oh, I see #1284 talks about this

**Comment by danielcjacobs** [comment]
I'm trying right now to just bring in a single file ([dgesv.c](https://github.com/NIRALUser/CLAPACK/blob/master/SRC/dgesv.c)) from `CLAPACK` to build with the rest of `CBLAS`. I copied this file to `OpenBLAS/lapack-netlib/CBLAS/src`, and the 2 header files it includes to `OpenBLAS/lapack-netlib/CBLAS/include`, but when I build and install without fortran using the same commands as before, the symbols from this file aren't found anywhere in `libopenblas.so`

**Comment by brada4** [comment]
Such aged projects (and f2c in general) could serve as a base for porting one function you need to C, but usually more advanced functions includes like dozen of others and that's no longer fun or easy.
It is best to assume you dont have LAPACK on Android. Well you can have it with very old NDK based on GCC, or via termux app, but thats not easy either.

**Comment by jianshu93** [comment]
Hi All, 

Just want to catch up, in the home-brew version of OpenBLAS for MacOS, is that possible to use the android NDK toolchain clang to compile it? I was not successful it seems. Tons of errors. 

Thanks,

Jianshu

**Comment by martin-frbg** [comment]
one of our CI jobs does this (on Intel Mac cross-compiling to ARMV7, but I think it should be adaptable to your situation)
https://github.com/OpenMathLib/OpenBLAS/blob/753c7ebe17786a1c8cbfa18542c257b3affb0ff2/azure-pipelines.yml#L243-L252
also see https://github.com/OpenMathLib/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android (though that page could use another overhaul I guess)
