### ISSUE TITLE
CMake not finding VS 2017

### ISSUE THREAD

**Issue by Ry7en** [xianyi/OpenBLAS#2062]
I've been having trouble getting OpenBLAS to build properly using the MSVC compiler; after cloning https://github.com/xianyi/OpenBLAS, then running:
```
mkdir build
cd build
cmake -G "Visual Studio 15 2017 Win64" ..
cmake --build . --config Release
```
I am left only with openblas.lib in my build\lib\RELEASE folder, and not libopenblas.dll as expected. My laptop runs Windows 10 on a Ryzen 2500u processor; for my previous attempts at solving the issue see https://github.com/Microsoft/ELL/issues/201

**Comment by martin-frbg** [comment]
Have you tried adding `-DBUILD_SHARED_LIBS=1` to the cmake command line ?

**Comment by Ry7en** [comment]
After running 
`cmake -DBUILD_SHARED_LIBS=ON ..`
from the VS developer prompt, and then 
`cmake --build . --config Release`
the build completes with 130 warnings, 25 fewer than before, and I noticed that the folder called "RELEASE" in my previous build is now named "Release", if this is relevant. That folder is now empty, whereas before it contained "openblas.lib".

**Comment by martin-frbg** [comment]
Any sign of a dll anywhere in the build tree ? Just counting warnings is probably not a useful metric, can you provide a build log ?

**Comment by Ry7en** [comment]
There are, and I erred when I stated that there wasn't a "RELEASE" folder; it resides within the "OpenBLAS\build\lib" folder as before, the only change being that there is now a "Release" folder in "OpenBLAS\build". A search for dll's showed that there are two called "openblas.dll", one in "RELEASE" and one in "build\utest", both 1.53MB (RELEASE also contains openblas.lib, openblas.exp and openblas.pdb ).

I can upload the CMakeError and CMakeOutput files, but otherwise should I copy and paste the entire output of the developer prompt into a text file and upload that instead?

**Comment by martin-frbg** [comment]
So essentially the build worked, and the only issue is whether the dll should be named openblas or libopenblas ?

**Comment by Ry7en** [comment]
If the developer confirms that's the only issue, is it the case, as I recall reading here, that I can simply rename the file to libopenblas?

**Comment by martin-frbg** [comment]
Yes, you can simply rename it if the other program expects it to be named libopenblas.dll. (Would need to search the commit history to find when it was renamed, but I expect somebody stated that the "lib" prefix was not standard on Windows. Similarly it used to be the case that the cmake build created both .lib and .dll by default in the past until it was pointed out that this was not what cmake builds usually do.) Probably the build instructions for the other project were written a year or more ago and not updated to reflect these changes in the OpenBLAS build process.)

**Comment by isuruf** [comment]
There are two types of `.lib` files. When the DLL is created there's a small import library called `openblas.lib` created as well. When linking you usually don't directly link to the DLL, but to this import library `openblas.lib`. This import library knows that the application should link to `openblas.dll`. If you rename the DLL, you'll have to regenerate `openblas.lib` unless you are doing something like LoadLibrary (dlopen equivalent on windows) or you are using MinGW (MinGW can direcly link to the DLL if I remember correctly)

A static library also has the extension `.lib` which adds to the confusion.

**Comment by Ry7en** [comment]
Thank you both very much for your help. After installing the OpenBLAS build in Program Files, and renaming the .dll and .lib files to "libopenblas.dll", and "libopenblas.lib", the program now detects OpenBLAS, but reports that `-- BLAS library not found`. If the solution is to regenerate openblas.lib,   would the following CLI be useful?
https://github.com/emilbayes/rename-dll

**Comment by martin-frbg** [comment]
From last week's comments in your ELL issue it seems to me that "finding" (Open)BLAS in that project is done by searching for specific file locations, not actual contents of the files it sees. So I do not think that regenerating the .lib will help, perhaps review the ELL setup script  again to see why it detects OpenBLAS and (apparently) still does not set BLAS_FOUND to TRUE.

**Comment by Ry7en** [comment]
I should also note that the output:
```
C:\Users\HP\ELL\build>dir /s /b "c:\Program Files"\openblas
c:\Program Files\openblas\bin
c:\Program Files\openblas\include
c:\Program Files\openblas\lib
c:\Program Files\openblas\share
c:\Program Files\openblas\bin\libopenblas.dll
c:\Program Files\openblas\include\openblas
c:\Program Files\openblas\include\openblas\cblas.h
c:\Program Files\openblas\include\openblas\f77blas.h
c:\Program Files\openblas\include\openblas\openblas_config.h
c:\Program Files\openblas\lib\libopenblas.lib
c:\Program Files\openblas\share\cmake
c:\Program Files\openblas\share\cmake\OpenBLAS
c:\Program Files\openblas\share\cmake\OpenBLAS\OpenBLASConfig.cmake
c:\Program Files\openblas\share\cmake\OpenBLAS\OpenBLASConfigVersion.cmake
c:\Program Files\openblas\share\cmake\OpenBLAS\OpenBLASTargets-release.cmake
c:\Program Files\openblas\share\cmake\OpenBLAS\OpenBLASTargets.cmake
```
includes 

```
c:\Program Files\openblas\share\cmake
c:\Program Files\openblas\share\cmake\OpenBLAS
c:\Program Files\openblas\share\cmake\OpenBLAS\OpenBLASConfig.cmake
c:\Program Files\openblas\share\cmake\OpenBLAS\OpenBLASConfigVersion.cmake
c:\Program Files\openblas\share\cmake\OpenBLAS\OpenBLASTargets-release.cmake
c:\Program Files\openblas\share\cmake\OpenBLAS\OpenBLASTargets.cmake
```
which do not appear in the developers OpenBLAS folder. Are these usually found when OpenBLAS is installed?

**Comment by martin-frbg** [comment]
Yes, some files are generated during the install (and it could also be that the developer has an earlier version installed)

**Comment by Ry7en** [comment]
Upon closer inspection, I noticed that the files `cblas.h`, `f77blas.h` and `openblas_config.h` resided in the developer's "openblas\include" folder. In my installation however, they were located within "openblas\include\openblas", which seems to have prevented the setup script from finding them; after copying the three files to "openblas\include", the ELL build completed successfully.
