### ISSUE TITLE
NUM_THREADS=512 cause OPENBLAS_NUM_THREADS=2 ./sblat3 < ./sblat3.dat segmentation fault

### ISSUE THREAD

**Issue by hjbreg** [xianyi/OpenBLAS#207]
Building OpenBLAS latest develop version using 

make NO_CBLAS=1 NO_LAPACK=1 BINARY=64 USE_THREAD=1 NUM_THREADS=512

gives the following output (part of)

OPENBLAS_NUM_THREADS=2 ./sblat3 < ./sblat3.dat
/bin/sh: line 1: 26659 Segmentation fault      OPENBLAS_NUM_THREADS=2 ./sblat3 < ./sblat3.dat
make[1]: **\* [level3] Error 139
make[1]: **\* Waiting for unfinished jobs....
OPENBLAS_NUM_THREADS=2 ./dblat2 < ./dblat2.dat
OPENBLAS_NUM_THREADS=2 ./cblat2 < ./cblat2.dat
OPENBLAS_NUM_THREADS=2 ./zblat2 < ./zblat2.dat
make[1]: Leaving directory `OpenBLAS-develop/test'
make: **\* [tests] Error 2

while building with NUM_THREADS 32, 64, 128, 256 are all ok
make NO_CBLAS=1 NO_LAPACK=1 BINARY=64 USE_THREAD=1
make NO_CBLAS=1 NO_LAPACK=1 BINARY=64 USE_THREAD=1 NUM_THREADS=32
make NO_CBLAS=1 NO_LAPACK=1 BINARY=64 USE_THREAD=1 NUM_THREADS=64
make NO_CBLAS=1 NO_LAPACK=1 BINARY=64 USE_THREAD=1 NUM_THREADS=128
make NO_CBLAS=1 NO_LAPACK=1 BINARY=64 USE_THREAD=1 NUM_THREADS=256

cpu: Intel Xeon E5-2609
os: rocks 6.1 x86_64 based on centos 6.3
gcc version 4.4.6 20120305 (Red Hat 4.4.6-4) (GCC)

**Comment by yilunzhao** [comment]
This also works for me, thanks!
