### ISSUE TITLE
DYNAMIC_ARCH=ON fails in cmake: many "undefined reference" errors

### ISSUE THREAD

**Issue by yurivict** [xianyi/OpenBLAS#2076]
```
[ 99%] Building Fortran object test/CMakeFiles/cblat3.dir/cblat3.f.o
cd /usr/ports/math/openblas/work/.build/test && /usr/local/bin/gfortran8  -I/usr/ports/math/openblas/work/OpenBLAS-0.3.5/lapack-netlib/LAPACKE/include -I/usr/ports/math/openblas/work/OpenBLAS-0.3.5 -I/usr/ports/math/openblas/work/.build -O -Wl,-rpath=/usr/local/lib/gcc8  -m128bit-long-double -fPIC -O3 -DNDEBUG -O3   -pthread -c /usr/ports/math/openblas/work/OpenBLAS-0.3.5/test/cblat3.f -o CMakeFiles/cblat3.dir/cblat3.f.o
--- test/CMakeFiles/zblat1.dir/all ---
/usr/local/bin/ld: ../lib/libopenblas.so.0.3: undefined reference to `xhemm_outcopy_PRESCOTT'
/usr/local/bin/ld: ../lib/libopenblas.so.0.3: undefined reference to `xdotc_k_CORE2'
/usr/local/bin/ld: ../lib/libopenblas.so.0.3: undefined reference to `xhemv_V_SKYLAKEX'
/usr/local/bin/ld: ../lib/libopenblas.so.0.3: undefined reference to `qgemm_otcopy_BARCELONA'
/usr/local/bin/ld: ../lib/libopenblas.so.0.3: undefined reference to `xgemm_oncopy_CORE2'
/usr/local/bin/ld: ../lib/libopenblas.so.0.3: undefined reference to `xtrmm_ounucopy_BARCELONA'
/usr/local/bin/ld: ../lib/libopenblas.so.0.3: undefined reference to `xtrmm_kernel_LR_PRESCOTT'
/usr/local/bin/ld: ../lib/libopenblas.so.0.3: undefined reference to `xgemm_otcopy_BARCELONA'
/usr/local/bin/ld: ../lib/libopenblas.so.0.3: undefined reference to `xtrsm_kernel_RT_CORE2'
/usr/local/bin/ld: ../lib/libopenblas.so.0.3: undefined reference to `iqamax_k_NEHALEM'
/usr/local/bin/ld: ../lib/libopenblas.so.0.3: undefined reference to `xtrmm_kernel_LC_CORE2'
```

**Comment by brada4** [comment]
If you follow longer build log:
https://github.com/xianyi/OpenBLAS/blob/651ab01d2b552dd979120edd44cf0ccb0031bed1/CMakeLists.txt#L59

Namely it may happen that the warning above means that extended precision - probably 80bit long floats - really are not built with cmake. Those are not built on Linux or Windows, thus probably you are one of first to test if thei get through cmake.
Would be nice that you report shortcomings with cmake files including comparison with normal makefiles.

**Comment by yurivict** [comment]
Thanks, I didn't realize that cmake support isn't mature yet.

**Comment by brada4** [comment]
There probably should be option to disable ext precision , it was cool before double precision was omnipresent, and that no caller remembers it nowadays. (including own tests ;-) )
It is not present in NetLib BLAS, so it is an (OpenBLAS) extension. Let hear from martin if it is worth tackling in some way.

**Comment by martin-frbg** [comment]
This is **not** an expected failure. cmake builds may not support all the more esoteric options from Makefile.rule but a straightforward DYNAMIC_ARCH=ON should work. Can you make sure that this is not again caused by some incompatible patch from the BSD port, and then upload your build log please ?

**Comment by yurivict** [comment]
Other patches seem unrelated.

Here is the log: https://people.freebsd.org/~yuri/openblas-DYNAMIC_ARCH=ON.log

**Comment by isuruf** [comment]
Both CMake and Makefiles don't disable extended precision for *BSDs, https://github.com/xianyi/OpenBLAS/blob/develop/cmake/os.cmake#L6 and https://github.com/xianyi/OpenBLAS/blob/develop/Makefile.system#L280

**Comment by brada4** [comment]
> don't disable extended 

Just that cmake does not build the files.
