### ISSUE TITLE
OpenBLAS is setup properly but not using multicores

### ISSUE THREAD

**Issue by bharathk005** [xianyi/OpenBLAS#2079]
ubuntu 18.04
python 3.6 
env: conda
Setup OpenBLAS by following this thread: https://stackoverflow.com/questions/11443302/compiling-numpy-with-openblas-integration
********************** np.__config__.show()**********************
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/OpenBLAS/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/OpenBLAS/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/OpenBLAS/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/OpenBLAS/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
**************************************************************

After the setup I don't see any improvement in the speed. I also tried setting OPENBLAS_NUM_THREADS and OMP_NUM_THREADS but it did not work. Please help..

**Comment by bharathk005** [comment]
numpy: 1.17.0.dev0+e8bd864

**Comment by martin-frbg** [comment]
What is your typical matrix size ? Many functions in OpenBLAS have been changed in recent years to run single-threaded when the multithreading overhead would outweigh any gains from parallelisation.

**Comment by bharathk005** [comment]
I have a deque of size 4 which has 4 matrices of 500x500. 
I am performing np.stack on this. Not sure if this is big enough for multithreading. Can you please share a sample operation with big enough size so that it is multithreaded and I can test if OpenBLAS is really working on my system?

**Comment by martin-frbg** [comment]
From the description of np.stack I am not even convinced it uses any BLAS calls at all. There are a few test cases provided with OpenBLAS in benchmark/scripts/NUMPY that use functions like np.dot or np.linalg.eig to exercise GEMM and related functions.

**Comment by bharathk005** [comment]
Thanks for the response. I will test that out and update.

**Comment by bharathk005** [comment]
It was setup correctly. As you said, looks like stack operation doesn't use blas calls. Thanks for the help :)
