### ISSUE TITLE
install r language make error

### ISSUE THREAD

**Issue by march3032** [xianyi/OpenBLAS#2082]
when i make r in my centos linux ,it comes an error like: 
/usr/bin/ld:cannot find -lRblas 
collect2:ld returned 1 exit status 
what should i do know...

**Comment by march3032** [comment]
In addition my linux cannot access to internet

**Comment by martin-frbg** [comment]
Can you be more specific about what you did, and what makes you think this problem is caused by OpenBLAS ? Did you follow the directions in https://cran.r-project.org/doc/manuals/R-admin.html#BLAS

**Comment by brada4** [comment]
This is certainly not "your linux internet helpdesk"

If you follow breadcrumb tail from R homepage it leads you to Fedora EPEL that includes quality builds of R and OpenBLAS.

I fail to see how your question has anything to do with OpenBLAS
