### ISSUE TITLE
i can generate the openblas.lib ,but how to generate the openblasd.lib file?

### ISSUE THREAD

**Issue by mengpengfei** [xianyi/OpenBLAS#2085]
i can generate the openblas.lib ,but how to generate the openblasd.lib file?what is the diffrent bettwen the two file

**Comment by isuruf** [comment]
> i can generate the openblas.lib ,but how to generate the openblasd.lib file?

There's no openblasd.lib file. What do you mean by openblasd.lib file?

**Comment by mengpengfei** [comment]
the old version has the file name "libopenblasd.lib"

**Comment by mengpengfei** [comment]
the version is openblas0.2.14.1

**Comment by isuruf** [comment]
@mengpengfei, where did you get openblas0.2.14.1 ?

**Comment by mengpengfei** [comment]
http://www.zifuture.com/fs/3.build/3rd.rar
the file contains the compiled lib file of that version

**Comment by mengpengfei** [comment]
that has a file libopenblas.dll.a,how can i replace the file

**Comment by mengpengfei** [comment]
thanks very much

**Comment by isuruf** [comment]
`libopenblas.dll.a` is an import library created when you build with MinGW and `openblas.lib` is when you build with MSVC. Both files should be interchangeable with a recent binutils version. If you want to generate libopenblas.dll.a, build OpenBLAS with MinGW.

**Comment by mengpengfei** [comment]
thank you very much

**Comment by mengpengfei** [comment]
you already have the binary package,oh!! i compile it step by step ,,,,,consume me one day

**Comment by brada4** [comment]
Old OpenBLAS versions on Windows build using only one CPU core, you might want to try cross-building DLL on Linux if you cannot get newer ones (like 0.3.5)

**Comment by mengpengfei** [comment]
how money cores the version 0.2.19 uses

**Comment by brada4** [comment]
This is just limitation of Windows build process in old versions, no problem with resultant library.
If you look in Makefile.rule, it hints NUM_THREADS=256 should work without any risks, in practice it will use detected CPU count if it is less.

**Comment by brada4** [comment]
Let me make 2 guesses regarding openblasD.lib
If it is *D*ouble precision (half-)library - API is included in full version
If it is with .pdb *D*ebug symbols - you will have more luck with clang-cl etc.

**Comment by mengpengfei** [comment]
thank you,just use openblas.lib is suitable
