### ISSUE TITLE
when i compile it use MinGW,how can i solve it

### ISSUE THREAD

**Issue by mengpengfei** [xianyi/OpenBLAS#2086]
D:\code\CCDL-Branch_6ea824e806c793ad609fd4f7ce8c836274660b6c\xianyi-OpenBLAS-eebc189>mingw32-make BINARY=32
The system cannot find the path specified.
process_begin: CreateProcess(NULL, uname -s, ...) failed.
'uname' is not recognized as an internal or external command,
operable program or batch file.
'uname' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
'grep' is not recognized as an internal or external command,
operable program or batch file.
'rm' is not recognized as an internal or external command,
operable program or batch file.
'uname' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
'.' is not recognized as an internal or external command,
operable program or batch file.
mingw32-make: *** [config.h] Error 1
'expr' is not recognized as an internal or external command,
operable program or batch file.
'expr' is not recognized as an internal or external command,
operable program or batch file.
'expr' is not recognized as an internal or external command,
operable program or batch file.
OpenBLAS: Detecting fortran compiler failed. Cannot compile LAPACK. Only compile BLAS.
process_begin: CreateProcess(NULL, ln -fs libopenblas_p-r0.3.5.a libopenblas.a, ...) failed.
make (e=2): ÏµÍ³ÕÒ²»µ½Ö¸¶¨µÄÎÄ¼þ¡£
Makefile:138: recipe for target 'libs' failed
mingw32-make: [libs] Error 2 (ignored)
d was unexpected at this time.
Makefile:138: recipe for target 'libs' failed
mingw32-make: *** [libs] Error 255

when i compile it use MinGW,how can i solve it

**Comment by isuruf** [comment]
you need to use a msys2 shell or use mingw with cmake

**Comment by mengpengfei** [comment]
thanks very much

**Comment by mengpengfei** [comment]
how can i get the openblas.dll.a file?

**Comment by isuruf** [comment]
See https://github.com/xianyi/OpenBLAS/issues/2086#issuecomment-481255427

**Comment by isuruf** [comment]
If you don't want to compile it yourself, you can download it at http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-openblas-0.3.5-1-any.pkg.tar.xz

**Comment by mengpengfei** [comment]
thank you very much.
but  when i compile the version "OpenBLAS 0.3.5 version"
some errors ：
D:\code\CCDL-Branch_6ea824e806c793ad609fd4f7ce8c836274660b6c\xianyi-OpenBLAS-eebc189>make BINARY=64 CC=gcc FC=gfortran USE_OPENMP=1 NUM_THREADS=32 NUM_PARALLEL=32
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
ln: creating symbolic link `libopenblas.a' to `libopenblas_haswellp-r0.3.5.a': No such file or directory
make: [libs] Error 1 (ignored)
make[1]: Entering directory `/d/code/CCDL-Branch_6ea824e806c793ad609fd4f7ce8c836274660b6c/xianyi-OpenBLAS-eebc189/interface'

**Comment by mengpengfei** [comment]
thank you for your binary package very much,,but if i use you binary package ,how can i set it to use all cpu cores?

**Comment by isuruf** [comment]
It's compiled with threading enabled. See https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-openblas/PKGBUILD#L45

**Comment by mengpengfei** [comment]
thank you very very much,god bless you!!!!

**Comment by mengpengfei** [comment]
can you give me the openblas.lib file that match the binary package?

**Comment by isuruf** [comment]
I don't understand what you are doing. You either need `libopenblas.dll.a` or `openblas.lib`. Why would you need both?

**Comment by mengpengfei** [comment]
i am compiling a wrapped caffe and that need the two files

**Comment by isuruf** [comment]
Please open an issue with them. `libopenblas.dll.a` is the import library when compiled with MinGW and `openblas.lib` is the import library when compiled with MSVC. There's no reason to require both as both do the same thing.

**Comment by brada4** [comment]
@mengpengfei did you just add some text to #2087 to close this issue?

**Comment by mengpengfei** [comment]
yes

**Comment by brada4** [comment]
You can do it yourself.
