### ISSUE TITLE
i use the compiled binary,but why the cpu only be used 30%

### ISSUE THREAD

**Issue by mengpengfei** [xianyi/OpenBLAS#2087]
i use the compiled binary,but why the cpu only be used 30%

**Comment by mengpengfei** [comment]
how to let it use more cpu

**Comment by mengpengfei** [comment]
i set this parameter,but it do not work,  
OPENBLAS_NUM_THREADS=10
 GOTO_NUM_THREADS=10
OMP_NUM_THREADS=10

**Comment by mengpengfei** [comment]
i want to compile by myself,but accour some errors when i execute the command: 
make BINARY=64 CC=gcc FC=gfortran USE_OPENMP=1 NUM_THREADS=32 NUM_PARALLEL=32

errors:
C:\MinGW\bin\ar.exe: strmm_kernel_LN.obj: No such file or directory
make[1]: *** [libs] Error 1
make[1]: Leaving directory `/d/code/CCDL-Branch_6ea824e806c793ad609fd4f7ce8c836274660b6c/xianyi-OpenBLAS-eebc189/kernel'
make: *** [libs] Error 1

**Comment by brada4** [comment]
which BLAS function are you calling and with what parameters, and on what CPU?
see interface/\*.c , most functions will process small samples with one thread, it is how fast you get the result, not how you warm CPU.

**Comment by mengpengfei** [comment]
i compile openblas with mingw,but why some errors accour,how to solve it?
the command: 
make BINARY=64 CC=gcc FC=gfortran USE_THREAD=1 USE_OPENMP=1 NUM_THREADS=32 NUM_PARALLEL=32

errors:
.obj zimatcopy_k_ctc.obj zimatcopy_k_rtc.obj zgeadd_k.obj zneg_tcopy.obj zlaswp_ncopy.obj lsame.obj scabs1.obj dcabs1.obj cpuid.obj
C:\MinGW\bin\ar.exe: strmm_kernel_LN.obj: No such file or directory
make[1]: *** [libs] Error 1
make[1]: Leaving directory `/d/code/CCDL-Branch_6ea824e806c793ad609fd4f7ce8c836274660b6c/xianyi-OpenBLAS-eebc189/kernel'
make: *** [libs] Error 1

**Comment by mengpengfei** [comment]
i have compile it successfully,the problem is solved,thanks for you help very much,

**Comment by brada4** [comment]
Issue tracker is not pastebin. Do you have something to add regarding what BLAS calls your code makes to OpenBLAS?

**Comment by brada4** [comment]
Regarding 30% - is it 30% of one core or 30% of 80 cores?

**Comment by mengpengfei** [comment]
30% of all cores

**Comment by mengpengfei** [comment]
when i set  OMP_NUM_THREADS=80   or  <80  the program can run perfectly,,,,,but  if  80+,  some errors accours,     why?

**Comment by isuruf** [comment]
the binaries were compiled with max 64 threads. you need to compile them with a higher number

**Comment by mengpengfei** [comment]
yes ,  i have compiled it with max 256 thread yestoday

**Comment by mengpengfei** [comment]
but when i set  OMP_NUM_THREADS=128,,some errors accoured,

**Comment by mengpengfei** [comment]
but when i set OMP_NUM_THREADS=80 or <80 the program can run perfectly

**Comment by isuruf** [comment]
> some errors accoured,

This is not going to help anybody. you need to be more detailed about the error you are getting and what you were running.

**Comment by mengpengfei** [comment]
what is the diffrent betwen libopenblas.lb and libopenblasp.lib?

**Comment by mengpengfei** [comment]
what is the diffrent betwen libopenblas.lib and libopenblasp.lib?

**Comment by brada4** [comment]
The difference is just in the name, one with p might be linux pthreds, while without p either default output of openblas build, or something default of distribution, could be pthreads, omp, of no threads.

**Comment by mengpengfei** [comment]
if i set OMP_NUM_THREADS=128, the error accoured,
the error:
 Process finished with exit code -1073740940 (0xC0000374)

the os is windows 10 ,
cpu:i7-4800mq
memory:16gb

**Comment by brada4** [comment]
It is a 4-core processor, running wildly more threads than 4 will just slow aggregate things down (but it is of value to eliminate crashes also for 128-core case)

Error 0xC0000374 is "heap corruption", which is indeed interesting and may be pointing to a bug in your or openblas code. Could you install [x64dbg](https://x64dbg.com/) as a JIT debugger and catch the crash. Try to get some screenshot image with as much as possible: thread backtraces, including one crashed, modules loaded, disassembly around at least crash, better backtrace plus whatever you fel is relevant.

**Comment by mengpengfei** [comment]
but the cpu has 8 logic processor

**Comment by brada4** [comment]
Yes, half-speed with half-caches logical processors, you get more or less same completion time using or not using them. Also disabling them is good for security.
But keep crashing it, we will find the problem and fix it.

**Comment by mengpengfei** [comment]
so the cpu  i7-4800mq  only can be used  50%?

**Comment by brada4** [comment]
30% usage might be one core working in turbo mode, with other 3 cores and 4 hyperthreads parked. "task manager" counts GHz as usage, you have it at 100% with only one hyperthread at 100% and other stopped, while more than 1/n if just one core works at turbo speed.
What is important is completion time to get the result, not how 100% CPU looks.

**Comment by mengpengfei** [comment]
i have the source code，can i give you and you compiled it，then you run it with bigger threads，the error will accour

**Comment by brada4** [comment]
Very short code fragment triggering bug could help, or a pointer to generally public code - YES
Something privately done -NO
The smaller it is the better.
You can also run program from inside debugger if you are afraid to operate JIT debugger. We just need last call into OpenBLAS DLL from others' code -  parameters passed, probably down the publicly available library chain.
Also whicl you are at it - Netlib BLAS and MKL not crashing in same conditions will point to sure problem in OpenBLAS.

**Comment by mengpengfei** [comment]
source code：
 https://github.com/phy0292/CCDL

**Comment by mengpengfei** [comment]
if you need some help ,please contract me anytime

**Comment by brada4** [comment]
It has caffe framework, where is the entry point that makes things crash?

**Comment by mengpengfei** [comment]
i execute the command:
set OMP_NUM_THREADS=100
"caffe.exe" train --solver=solver.prototxt 

and the source code is caffe-easy/tools/caffe.cpp

**Comment by mengpengfei** [comment]
you can also compile it :
Requirement tool Visual Studio 2013
1. Download the dependency library 3rd (158MB) and extract it into this directory
2. Open windows-cpu/windows-cpu.sln
3. Compile, and the result will be in the corresponding location in the Build directory.

if you compile it , you can replace the openblas in 3rd directory with your compiled openblas version

**Comment by brada4** [comment]
What options you use to compile OpenBLAS?

**Comment by mengpengfei** [comment]
i use the command :
make BINARY=64 CC=gcc FC=gfortran USE_OPENMP=1 NUM_THREADS=224 NUM_PARALLEL=16

**Comment by mengpengfei** [comment]
thank you very much，can you slove it？

**Comment by brada4** [comment]
Probably caffe (visual studio) and openblas use different kinds of "OpenMP"
OpenBLAs is built to hold 224\*16\*2=7168 threads, but you are calling 100x100=10000
It is fairly common mistake. You can build OpenBLAS without OMP, then you can control threads made by openblas independently from Caffe and OMP.

It is platform-neutral "known issue". Moderate your thread usage, especially avoid N\*\*2 thread expansions.

**Comment by mengpengfei** [comment]
thanks very much，i will try it today

**Comment by brada4** [comment]
If outer wrapper (cafe) paralellizes - use OpenBLAS with one thread.
Try various combinations of fitting them - whichever is fastest for you is the best.
You lose all perfromance possibly gained at 10 threads/core, and system gets slow to no usable around hundreds threads per core....

**Comment by mengpengfei** [comment]
thanks very much,do you mean i should use OpenBLAS with one thread?

**Comment by mengpengfei** [comment]
sorry,my english is bad

**Comment by mengpengfei** [comment]
why one thread is more faster than four threads?

**Comment by mengpengfei** [comment]
do you mean i should use OpenBLAS with one thread?

**Comment by mengpengfei** [comment]
i use the command to compile it:
 make BINARY=64 CC=gcc FC=gfortran USE_OPENMP=1 NUM_THREADS=2560 NUM_PARALLEL=16
but why one thread is the fastest

**Comment by mengpengfei** [comment]
“OpenBLAs is built to hold 224*16*2=7168 threads, but you are calling 100x100=10000
It is fairly common mistake.”

but now is i cant set OMP_NUM_THREADS=80+

**Comment by mengpengfei** [comment]
funck caffe，i will use tensorflow!!

**Comment by Diazonium** [comment]
What do you mean by "i cant set OMP_NUM_THREADS=80+" ?
Just do `export OMP_NUM_THREADS=whatever`

**Comment by Diazonium** [comment]
Also, why on Earth are you trying to run 80+ threads on 4 cores?

**Comment by mengpengfei** [comment]
the cpu has 8 logic cores,and the os is windows 10
"set OMP_NUM_THREADS=1"  is more faster than  "set OMP_NUM_THREADS=4"

**Comment by Diazonium** [comment]
I would advise you to stop using Windows, especially Windows 10, if you want to do serious computation.
BLAS does not care about logic cores, you can forget they exist.

**Comment by brada4** [comment]
@mengpengfei you need to make sure you do not exceed cores(real or psedo - does not matter for Desktop/Server CPUs). You use 2 different OpenMP implementations - MS-OMP from visual studio and GOMP from MinGW the parameter is applied square. I am suggesting you use native threads in OpenBLAS so that you can control them with OPENBLAS_NUM_THREADS inside each OMP_NUM_THREADS, there is some sweet spot in between you get most out of your CPU. 4 means 16 BLAS threads and CPU busy switching between them and re-fetching caches from 10x slower RAM. Try OMP_N.._T..=2 that should be better fit for your hardware.

**Comment by brada4** [comment]
You can rebuild openblas with native threads (take away USE_OPENMP=1 build parameter)
Then you can use OMP_NUM_THREADS to control caffe thread count
Each caffe thread will spawn OPENBLAS_NUM_THREADS openblas native threads
At present it is same parameter for both, so you get 1^2 2^2 3^2 4^2 real threads working, not good, easily exceeds 4/8 hardware/hyper- cores.
Then you can try:
cafe:openblas
8:1
4:2
...
1:8
...
4:1
2:2
1:4

**Comment by mengpengfei** [comment]
thanks you，i have implement multi threads with other method

**Comment by brada4** [comment]
In this case single-threaded openblas fits your puropose, note that there is still a limit of 50 malloc handles limiting single-threaded version to that many threads.
