### ISSUE TITLE
FAQ on update-alternatives in Ubuntu 16.04 and 18.04

### ISSUE THREAD

**Issue by amigalemming** [xianyi/OpenBLAS#2089]
The FAQ may be outdated for Ubuntu 16.04 and 18.04. The command for registration of an alternative is `--install` not `--add` and `liblapack.so.3` is not a slave of `libblas.so.3`. Thus you need two `--install` invocations.

**Comment by brada4** [comment]
It is slave configuration still after those years. OpenBLAS Lapack part calls OpenBLAS BLAS internals, thus it will not work with other libblas.so.3
I edited the other part and updated title from distrowatch.

**Comment by brada4** [comment]
Actually on modern ubuntu there is cblas.so.3 without wrapper that we could replace but cannot, on some others liblapacke.so.3 again same.... I wrote it just to make instant win in common case as for F.A.Q.

**Comment by amigalemming** [comment]
On Tue, 16 Apr 2019, Andrew wrote:

> It is slave configuration still after those years. OpenBLAS Lapack part calls OpenBLAS BLAS internals, thus it
> will not work with other libblas.so.3

$ sudo update-alternatives --install /usr/lib/libblas.so.3 libblas.so.3 /usr/local/openblas-0.3.5/lib/libopenblas.so.0 41 --slave /usr/lib/liblapack.so.3 liblapack.so.3 /usr/local/openblas-0.3.5/lib/libopenblas.so.0
update-alternatives: Fehler: Alternative liblapack.so.3 kann kein Slave 
von libblas.so.3 sein: Sie ist eine Master-Alternative

Translated:
Error: Alternative liblapack.so.3 cannot be slave of libblas.so.3: It is a master alternative.

**Comment by brada4** [comment]
It is a shortcoming of update to update-alternatives.
You can take out that second line from FAQ yourself. Probably worth editing that only netlib lapack will be usable from then on.

**Comment by amigalemming** [comment]
On Tue, 16 Apr 2019, Andrew wrote:

> It is a shortcoming of update to update-alternatives.

???

> You can take out that second line from FAQ yourself. Probably worth 
> editing that only netlib lapack will be usable from then on.

???


Btw. blas.pc seems to be a slave of libblas.so group and lapack.pc a slave 
of liblapack.so. What is the recommended way to generate the pkg-config 
files?

**Comment by brada4** [comment]
Best is to take .so and .pc files from reference netlib blas, then you can still swap runtime library with anything of choosing. 
i.e. you change only `*.so.3` libraries for ld.so, while gcc and pkgconfig picks `*.so` and defailt `*.pc` file.

**Comment by brada4** [comment]
I have looked at 18.04, library names are weird as to say softly. If you have a good idea how to make it work on ubuntu-debian-mint-mxlinux and opensuse, and not make too long you are welcome, I have no easy idea how to plant openblas manua  build in Ubuntu 18LTS :-(

**Comment by martin-frbg** [comment]
A search for the error message leads to old bugs like https://bugs.launchpad.net/ubuntu/+source/ri/+bug/876097 where it is suggested that running `update-alternatives --remove` on the affected component first may be used to work around this problem. Not sure if this applies to the problem at hand here, but this blog entry from 2015 https://aweirdimagination.net/2015/03/27/fixing-broken-alternatives/ - which actually concerns setting up alternatives entries for liblapack - seems to concur. Furthermore it suggests that the problem is caused by dangling links to files that have already
been removed on disk but not deleted from the alternatives file (also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=776634).

**Comment by brada4** [comment]
I have spotted same back when adding faq entry. Basically I install libblas-dev so that one set of valid links is present. Now it is not libblas.so.3, but libblas.so.3-some-architecture-string phew.
Probably one can set master/slave confs in an empty place but it is longer than faq expects and nothing like 1-minute fix

**Comment by martin-frbg** [comment]
With the architecture-dependent part worse than the usual x86_64-llinux-gnu ? That would seem very impractical...

**Comment by brada4** [comment]
It is just the usual one, but same copypasta will not work for 16.04 nor for aarch64

**Comment by martin-frbg** [comment]
Wouldn't that be enough to give those (relatively few?) on aarch64 an idea what to do ? I assume they would be used to mentally replacing x86_64 with aarch64 in many other hints and instructions. Certainly better than just stating "it has become much too complicated to explain here"... (What is different on 16.04 ? Something simple like a version number, or is there more to it ? I am not familiar with Ubuntu)

**Comment by brada4** [comment]
in 16.04 alternative is called (/usr/lib/)libblas.so.3, in 18.04 t is called libblas.so.3.host-triplet and the target symlink is /usr/lib/host-triplet/libblas.so.3
Probably one paragraph on how to detect if it is one or another naming scheme

**Comment by martin-frbg** [comment]
"In recent versions of the distributions, the installation path for the libraries has been changed to include the name of the host architecture, like /usr/lib/x86_64-linux-gnu/blas/libblas.so.3 . Use `update-alternatives --display libblas.so.3` to find out what layout your system has." Would this do ?

**Comment by brada4** [comment]
`bash-completion` is needed to complete the line into libblas.so.3-tr-ip-le
but yes, it has all keys inside.
I see also they make massive link group with blas.pc libblas.so libblas.a cblas.h which could be atlas or old openblas, yielding semi-broken dynamic executables.

**Comment by martin-frbg** [comment]
@amigalemming any update on the master-slave dilemma ? (Is it possible that the alternatives links on your system are outdated or dangling symlinks due to earlier changes, or is this a fresh, unmodified installation of Ubuntu ?)

**Comment by brada4** [comment]
It is if you install (Ubuntu) libblas and liblapack they are "independent" , in this case we cannot safely use openblas as source of lapack, as this needs it to be BLAS too bat that cannot be assured/enforced. Same applies to atlas and mkl, I dunno if it is good to just give one libblas (probaby even building without lapacks)
