### ISSUE TITLE
[Question]What is the parallelization threshold value for Caxpy benchmark?

### ISSUE THREAD

**Issue by tianyizhangcs** [xianyi/OpenBLAS#2090]
Hello, I am writing a paper using caxpy benchmark, could someone tell me what is the parallelization threshold value for Caxpy benchmark or somewhere I can find the info?
I feel that OpenMP is really called when the size of the vector is really small.

**Comment by brada4** [comment]
Any considerate improvements are more than welcome, especially if they help your research...
I measured just once and it sort of pointed to something bigger than 10000
interface/axpy.c
```
#define MULTI_THREAD_MINIMAL  10000
```

```
  //Temporarily work-around the low performance issue with small imput size &
  //multithreads.
  if (incx == 0 || incy == 0 || n <= MULTI_THREAD_MINIMAL)
          nthreads = 1;
```

**Comment by brada4** [comment]
Also see #1886 for other things help is needed.

**Comment by tianyizhangcs** [comment]
Very helpful! Thank you so much

**Comment by brada4** [comment]
add your research result as a pull request later if possible.

**Comment by tianyizhangcs** [comment]
Sure, my research is mainly comparing hpxMP
```
 https://github.com/STEllAR-GROUP/hpxMP
```
with llvm-OpenMP and GOMP.

As the benchmark is using OpenMP, so I employed as a performance comparison.
