### ISSUE TITLE
Issue about releaseing new version

### ISSUE THREAD

**Issue by Hao-HUST** [xianyi/OpenBLAS#2091]
Will you release a new version recently?

The released version 0.3.5 cannot compile in VisualStudio 2017 x64, while the develop branch works well.  So, would you please release a new version soon (not a develop version)?

Best

**Comment by brada4** [comment]
Can you detail your setup a bit?
What C compiler, which build scripting system, what kind of fortran compiler you are using in particular case . There is nothing major changed targetting vs2017 vs older or newer versions

**Comment by martin-frbg** [comment]
@brada4 probably #1978 (which I had forgotten to tag for 0.3.6 until now)
@Hao-HUST I had hoped to fix some rather major bugs that had come up in the meantime, but unfortunately got overwhelmed by other work. Will try to get a release out either this weekend or the next.

**Comment by martin-frbg** [comment]
0.3.6 is released now.
