### ISSUE TITLE
Use HTTPS URL in GitHub description

### ISSUE THREAD

**Issue by paulmenzel** [xianyi/OpenBLAS#2109]
Please use https://www.openblas.net/ in the GitHub description.

**Comment by martin-frbg** [comment]
A) why ? I do not think there is any potentially compromising information there that would warrant secure transmission
B) see #1675

**Comment by paulmenzel** [comment]
A) Why not? Browsers will warn about it in the future, and it’s also preventing certain DNS attacks.
B) I know, but it’s unrelated as the URL is only there.

**Comment by paulmenzel** [comment]
I actually meant the GitHub description at the very top.

> OpenBLAS is an optimized BLAS library based on GotoBLAS2 1.13 BSD version. http://www.openblas.net

**Comment by martin-frbg** [comment]
That is in the project description that only xianyi himself can edit
