### ISSUE TITLE
getrf_parallel.c strange code

### ISSUE THREAD

**Issue by brada4** [xianyi/OpenBLAS#2113]
Here the first "check" actually never checks if it is free
https://github.com/xianyi/OpenBLAS/blob/6a8b4269b522a8e1383e27e0ffef6111993a7264/lapack/getrf/getrf_parallel.c#L284
Id like to make a PR with either removing first no-check leaving just loop, or enclosing loop in if()?

**Comment by martin-frbg** [comment]
Guess I had this as a while-do originally so needed to pull the initial value out of the loop, or I was just confused... Or maybe I was worried that optimization might change the order of execution ? Anyway there appear to be a few more in this style - _probably_ harmless but certainly pointless. In each case, the original (non-locking) code was just a one-liner while() with a dummy do() block

**Comment by brada4** [comment]
I think not much space to make mistakes in PR.
