### ISSUE TITLE
cblas_isamin on a dataset containing 0.0 and a non-1 incX returns 7

### ISSUE THREAD

**Issue by RossBrunton** [xianyi/OpenBLAS#2116]
The following example shows the problem:

```CPP
int a = 30;
std::vector<float> x(a * 5);
for (int i = 0; i < a * 5; i ++) {
  x[i] = i + 1;
}
x[10 * 5] = 0;
std::cout << cblas_isamin(a, x.data(), 5) << "\n";
```

This prints out `7`, rather than `10` as I would expect. Changing the `10` to any value larger than `7` also prints `7`. Changing `incX` to `1`, or removing the `x[10 * 5] = 0` line causes this to output `0` as expected.

I'm using commit 6a8b42 .

**Comment by martin-frbg** [comment]
Oh joy, this is probably a historical bug from GotoBLAS... I assume you are running this on x86_64 hardware ?

**Comment by RossBrunton** [comment]
This is x86_64, yes.

**Comment by martin-frbg** [comment]
Quick solution seems to be to change the ISAMINKERNEL entry in kernel/x86_64/KERNEL from iamax_sse.S to iamax.S - have not checked yet if related functions are similarly affected.

**Comment by martin-frbg** [comment]
Seems both isamin and ismin give wrong results for non-1 incX,  although they use the same code as their (working) -max counterparts with only the comparison inverted.
