### ISSUE TITLE
Lapacke problem

### ISSUE THREAD

**Issue by Yasminem6** [xianyi/OpenBLAS#2128]
Hi, 
I have just installed OpenBlas and I can't find examples of code to test if it works. 
I found 2 pieces of code: one that uses "cblas.h" and another one to invert a matrix that uses "Lapacke.h". Unfortunately, the one using Lapacke doesn't work, it returns thousands of errors. It seems as though it can't find lapacke functions like "lapack_make_complex_double".
Here is the code I used :
 `
#include <stdio.h>
#include "cblas.h"
#include "lapacke.h"

// inplace inverse n x n matrix A.
// matrix A is Column Major (i.e. firts line, second line ... *not* C[][] order)
// returns:
//   ret = 0 on success
//   ret < 0 illegal argument value
//   ret > 0 singular matrix

lapack_int matInv(double *A, unsigned n)
{
    int ipiv[n+1];
    lapack_int ret;

    ret =  LAPACKE_dgetrf(LAPACK_COL_MAJOR,
                          n,
                          n,
                          A,
                          n,
                          ipiv);

    if (ret !=0)
        return ret;

    ret = LAPACKE_dgetri(LAPACK_COL_MAJOR,
                       n,
                       A,
                       n,
                       ipiv);
    return ret;
}

int main()
{
    double A[] = {
        0.378589,   0.971711,   0.016087,   0.037668,   0.312398,
        0.756377,   0.345708,   0.922947,   0.846671,   0.856103,
        0.732510,   0.108942,   0.476969,   0.398254,   0.507045,
        0.162608,   0.227770,   0.533074,   0.807075,   0.180335,
        0.517006,   0.315992,   0.914848,   0.460825,   0.731980
    };

    for (int i=0; i<25; i++) {
        if ((i%5) == 0) putchar('\n');
        printf("%+12.8f ",A[i]);
    }
    putchar('\n');

    matInv(A,5);

    for (int i=0; i<25; i++) {
        if ((i%5) == 0) putchar('\n');
        printf("%+12.8f ",A[i]);
    }
    putchar('\n');
}
`

Is it a problem with the way I built the library or I'm not using it correctly ?
Thank you in advance.

Ps: Im using it on Visual Studio 2019.

**Comment by martin-frbg** [comment]
Do you have a Fortran compiler installed ? While LAPACKE itself is C, it only provides the bindings for calling the LAPACK functions which require a Fortran compiler to get built. If no Fortran compiler is available, your library will only contain the BLAS (and CBLAS) functions.
