### ISSUE TITLE
OpenBlas - Numpy  setup -Library_dirs Path issue- RHEL7.4

### ISSUE THREAD

**Issue by krishm228** [xianyi/OpenBLAS#2131]
Using the following link tried to setup OpenBlas
https://stackoverflow.com/questions/11443302/compiling-numpy-with-openblas-integration

Numpy  config shows as follows

>>> import numpy as np;
>>> np.__config__.show()
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]

but  library_dirs is not pointing to /opt/OpenBlas/lib ...How to resolve this ??

**Comment by isuruf** [comment]
You need to open this issue in numpy issue tracker, not openblas.

**Comment by krishm228** [comment]
@isuruf ...Thanks for your suggestion . I had already raised an issue in numpy issue tracker . I would like to know if any specific settings at bashrc / bash_profile require to link to library_dirs to point  to /opt/OpenBlas/lib ?

**Comment by isuruf** [comment]
@krishm228, anything related to `library_dirs` is related to numpy, not openblas.

**Comment by brada4** [comment]
Most likely place is /etc/ld.so.conf.d/openblas.conf
Also make sure you get rid of vendor-provided atlas-based numpy.

**Comment by krishm228** [comment]
@brada4, Thank you for your response. I already had place file and output as follows
 cat /etc/ld.so.conf.d/openblas.conf
/opt/OpenBLAS/lib
Could you please help in any of the paths need to be set ?

**Comment by brada4** [comment]
numpy.config.show shows build-time configuration of numpy.
Do you get any dependency errors?

**Comment by krishm228** [comment]
@ brada4 ,Thanks for your quick response 
 I could see the following warning before building  the numpy 
**Command: python setup.py config**
O/P:
setup.py:417: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
  run_build = parse_setuppy_commands()
Running from numpy source directory.
Cythonizing sources
numpy/random/mtrand/randint_helpers.pxi.in has not changed
numpy/random/mtrand/mtrand.pyx has not changed
blas_opt_info:
blas_mkl_info:
customize UnixCCompiler
  FOUND:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/include', '/usr/include', '/opt/anaconda3/include']

  FOUND:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/include', '/usr/include', '/opt/anaconda3/include']

/bin/sh: svnversion: command not found
lapack_opt_info:
lapack_mkl_info:
customize UnixCCompiler
  FOUND:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/include', '/usr/include', '/opt/anaconda3/include']

  FOUND:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/include', '/usr/include', '/opt/anaconda3/include']

/opt/anaconda3/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
  warnings.warn(msg)
running config


Though OpenBlas is Installed. we couldn't see  libraries ,library_dirs paths as expected ..
.Please let me know if any config information is require for analysis and I will provide you the details

**Comment by brada4** [comment]
Please read guidance around anaconda nomkl package. That is their name for OpenBLAS. It would not be a good idea to try your build where you have choice of 2 nearly perfect bundles from same storefront.
