### ISSUE TITLE
make -j $(nproc --all)$(nproc --all) $(nproc --all)$(nproc --all)

### ISSUE THREAD

**Issue by gabygga** [xianyi/OpenBLAS#2132]
Hi, I'm trying to install with the following instructions:
`make -j $(nproc --all)$(nproc --all) $(nproc --all)$(nproc --all) && make PREFIX=/usr/local install
`
But it doesn't do nothing. I'm not sure what is the difference with `make -j $(nproc --all)$(nproc --all)&& make PREFIX=/usr/local install ` because this compiles fine.

**Comment by isuruf** [comment]
Where did you find these instructions?

**Comment by gabygga** [comment]
I'm installing cosmosis which uses OpenBLAS, https://bitbucket.org/joezuntz/cosmosis-docker/src/master/Dockerfile , and my computer doesn't the step where it installs OpenBLAS. Then I tried to do it manually with the same instructions, but when I do `make -j $(nproc --all)$(nproc --all) $(nproc --all)$(nproc --all)`  it stops.

**Comment by isuruf** [comment]
Don't use that line. Just use `make -j $(nproc --all)` or simply `make -j`

**Comment by gabygga** [comment]
So many thanks, it seems to work. Do you know what line(s) in the Makefile I should see to understand what is the difference of using only `make -j` or `make -j $(nproc --all)` ?

**Comment by isuruf** [comment]
It's a make command `make -j` means use all processors. `make -j <num>` means use the specificied number of processors and `nproc --all` gives the number of processors.

**Comment by brada4** [comment]
`nproc --all` shows all processors in the system
`nproc` without parameter considers cgroup restrictions from docker and may show less 
4 times `nproc --all` will prime up nnnn processes - exactly useless heaps of them, like 2 CPUs already getting over typical 1k nofile limit.
