### ISSUE TITLE
Using Openblas in tensorflow

### ISSUE THREAD

**Issue by knjwhn** [xianyi/OpenBLAS#2133]
Could change the eigen to openblas in tensorflow for matrix operation? 
Anyone who knows whether this could work?
Thanks a lot!

**Comment by brada4** [comment]
Eigen, a completely fidfferent product,  has own documentation on how to interface OpenBLAS.
No need to post in a bug tracker, it is not a support chat.

**Comment by martin-frbg** [comment]
https://github.com/tensorflow/tensorflow/issues/18457 suggests the developers of tensorflow are not particularly interested in providing support for other BLAS implementations, although the topic seems to come up occasionally. As I understand it, what is usually done is to configure Eigen to use OpenBLAS as a backend.

**Comment by brada4** [comment]
It is well documented, sort of:
https://eigen.tuxfamily.org/dox/TopicUsingBlasLapack.html
There is nothing at all specific to OpenBLAS, same guide works for Netlib, Atlas, MKL.

**Comment by jcftang** [comment]
I guess you would need to define EIGEN_USE_BLAS conditionally if the user needs this. This would be particularly useful for embedded devices where the vendor might provide their own accelerated blas libraries e.g. c66x on the am5728 chip have their own accelerated libraries.
