### ISSUE TITLE
error installing openblas for torch7 on ubuntu 18.04

### ISSUE THREAD

**Issue by Ruminum** [xianyi/OpenBLAS#2135]
Hello, I have a problem with installing for installing torch7 which I manage to narrow down to error when installing OpenBlas. I tried to install OpenBlas separately and got the same error. I follow the [Torch 7](https://www.kadamwhite.com/archives/2018/install-torch-7-and-cuda-9-1-on-ubuntu-18-04-lts?unapproved=2422&moderation-hash=5265ae372d0185f702b59cd8ba5de945#comment-2422) installation, and I am using a freshly installed ubuntu 18.04 with cuda 9.0. This are the error I got but it usually has different everytime I compile bash install-deps. 
This is generally the error I got 
> cc -c -O2 -DMAX_STACK_ALLOC=2048 -fopenmp -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=8 -DMAX_PARALLEL_NUMBER=1 -DVERSION=\"0.3.7.dev\" -DASMNAME=dtbmv_TLU -DASMFNAME=dtbmv_TLU_ -DNAME=dtbmv_TLU_ -DCNAME=dtbmv_TLU -DCHAR_NAME=\"dtbmv_TLU_\" -DCHAR_CNAME=\"dtbmv_TLU\" -DNO_AFFINITY -I../.. -DDOUBLE  -UCOMPLEX -UCOMPLEX -DDOUBLE -DTRANSA -DUNIT tbmv_U.c -o dtbmv_TLU.o
cc: internal compiler error: Segmentation fault (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
Makefile:1464: recipe for target 'dspr_U.o' failed
make[1]: *** [dspr_U.o] Error 4
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/tmp/tmp.qQRj0hXVsU/OpenBLAS/driver/level2'
Makefile:145: recipe for target 'libs' failed
make: *** [libs] Error 1
Error. OpenBLAS could not be compiled

more or less same error when I install OpenBlas seperately. Please help me

**Comment by martin-frbg** [comment]
This is almost certainly a hardware problem, the compiler is crashing as it is receiving random data instead of the program code to work on. Try replacing the memory in your computer.

**Comment by brada4** [comment]
Typically such problems do come from unstable memory because of overclocking. 
It sort of does not crash until you start to use the computer. OpenBLAS will employ all execution resources of all cores, thus stress hardware setup to the top of thermal envelope often.
There is a builtin memory test when you boot ubuntu installer. Given error above - I thing "verify install media" option also will point to hardware broken.

**Comment by Ruminum** [comment]
Hello, Thank you for the quick reply guys, I really appreciate it. So now I just run memory test using Ubuntu pen drive and will see the result tomorrow morning. So if it really is a memory problem, is there any workaround besides replacing the memory? I don't think I will be able to request it quickly to my advisor

**Comment by martin-frbg** [comment]
You can try lowering the clock frequency and/or increasing the voltage for the memory (if the BIOS provides settings for these), but if the memory is defective you cannot really trust any results obtained with this computer.

**Comment by Ruminum** [comment]
I see, I will give more feedback tomorrow after the check is finished

**Comment by brada4** [comment]
We did not sell you hardware... Probably you should seek DoA warranty return .

**Comment by Ruminum** [comment]
weirdly enough I don't find any error during memtest (around 15 hours). So I will try to reinstall my Ubuntu

**Comment by martin-frbg** [comment]
Other possibilities are overheating (especially on older hardware, recent cpus usually throttle down instead of failing) or a weak power supply. You could also try the NO_PARALLEL_MAKE or MAKE_NB_JOBS options (see Makefile.rule) to limit the number of parallel compile jobs in order to put less strain on your computer.

**Comment by brada4** [comment]
Try to verify usb stick with installer , one bad block matters

**Comment by Diazonium** [comment]
What sort of CPU do you have in this computer?

**Comment by Ruminum** [comment]
sorry for the late reply, I am using i7 3770 and GTX 1080Ti with 16 gb ram. Since the problem persist, I tried to use repository provided in [link](https://github.com/nagadomi/distro) and it works so I will close this thread. Thank you for all your help.
