### ISSUE TITLE
document building with cmake

### ISSUE THREAD

**Issue by dimpase** [xianyi/OpenBLAS#2138]
Trying to figure out how it can be done leads to various Windows-only issues and wikis, but there are no general instructions available. 

Our interest in part is the apparent ability of the cmake build to generate pkg-config .pc file.

**Comment by martin-frbg** [comment]
pkg-config files are generated by both cmake and gmake builds. There are no generic instructions for cmake builds as it is no different from standard cmake usage - create a build directory somewhere (e.g. a folder named "build" underneath the toplevel OpenBLAS one), cd to it and call cmake with the path to the toplevel OpenBLAS directory (e.g. "cmake ..") and then run "make". Options are basically the same as listed in Makefile.rule, you would use something like "-Doptionname=ON" on the cmake command line where Makefile.rule has "optionname=1".
