### ISSUE TITLE
PGI 19.4 failed to compile OpenBLAS 0.3.6 

### ISSUE THREAD

**Issue by jmbeuken** [xianyi/OpenBLAS#2139]
CentOS 7.6 ( E5-2623 v4 )
tar xzf v0.3.6.tar.gz
```
make CC=pgcc FC=pgfortran DEBUG=1 DYNAMIC_ARCH=1
...
make[1]: Entering directory `/data/TOOLS/OpenBLAS-0.3.6_pgi19.4/driver/others'
pgcc -g -DMAX_STACK_ALLOC=2048 -tp p7-64 -DF_INTERFACE_PGI -fPIC -DDYNAMIC_ARCH -DNO_AVX512 -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=16 -DMAX_PARALLEL_NUMBER=1 -DVERSION=\"0.3.6\" -DASMNAME=memory -DASMFNAME=memory_ -DNAME=memory_ -DCNAME=memory -DCHAR_NAME=\"memory_\" -DCHAR_CNAME=\"memory\" -DNO_AFFINITY -I../.. -c memory.c -o memory.o
/backup/opt/pgi/linux86-64-llvm/19.4/share/llvm/bin/llc: error: /backup/opt/pgi/linux86-64-llvm/19.4/share/llvm/bin/llc: /tmp/pgccPOlg70ojvfFR.ll:1387:44: error: expected comma in inline asm expression
        call void asm sideeffect ".section .init,"ax"; call gotoblas_init@PLT; .section .text", "" (), !dbg !1422
                                                  ^
```

**Comment by martin-frbg** [comment]
Funnily this `.section .init, "ax"` stuff is in a dummy routine specifically provided for (some version of) PGI at the very end of memory.c (or around line 1620 if you build the USE_TLS=1 branch of this file). This code appears to date back to GotoBLAS2, over 10 years ago. Guess you could try just deleting the entire `gotoblas_dummy_for_PGI{}` that appears to be just dead code added to work around some weird compiler logic. (Or try adding a comma after the "ax", if that is what it seems to be asking for ?)
