### ISSUE TITLE
Disabling AVX-512 during compilation

### ISSUE THREAD

**Issue by ahmetaa** [xianyi/OpenBLAS#2151]
Hello, I looked around source files but could not find a way to disable AVX-512 support during compilation. My system supports AVX-512 but I do not want to use it by default.

**Comment by martin-frbg** [comment]
Set NO_AVX512=1 on the `make` command line, or if you use CMAKE specify `-DNO_AVX512=1`.
(It seems that this option still needs to be added to Makefile.rule)

**Comment by martin-frbg** [comment]
Documented in Makefile.rule now. BTW an alternative solution is to build with TARGET=HASWELL

**Comment by ahmetaa** [comment]
Thanks. I actually did try with TARGET=HASWELL but it still generated a lib with name `skylake' I did not dig deeper though.
