### ISSUE TITLE
OpenBLAS v0.3.6 detection error for TARGET=SKYLAKEX

### ISSUE THREAD

**Issue by ghost** [xianyi/OpenBLAS#2152]
When specify TARGET=SKYLAKEX to build openblas v0.3.6 on a SKYLAKE machine, the build will still go with haswell as target. The cause is at getarch.c:94 --
94: #if (( defined(\_\_GNUC\_\_)  && \_\_GNUC\_\_   > 6 && defined(\_\_AVX2\_\_)) || (defined(\_\_clang\_\_) && \_\_clang\_major\_\_ >= 6))
95: #else
96: #define NO_AVX512
97: #endif

It will go with AVX512 only when __GNUC__ defined and newer than 6, and __AVX2__ defined. However, __AVX2__ can be obtained only when -march=haswell/skylake/skylake-avx512 or -mavx2 or -mavx512???? to be specified during building getarch.c. Unfortunately the CFLAGS in Makefile.prebuild is passed by Makefile.system:203 that CFLAGS is overwriten by GETARCH_FLAGS -- which will never include those options (-march or -m ... etc.). 

I learned from git log that getarch.c:94 is newly added to make the build more smart when building on a non-avx512 machine, but this seems not a good way. To me, it is even worse than just told me that I cannot build SKYLAKEX target instead of going with haswell as a fall-back. At least the user know that what he get is what he want, but not another one.

**Comment by GuobingChen** [comment]
BTW, don't know why this github system omit the '__' before and after those macros (GNUC, AVX2 ...) automatically. But let's pretend these '__' are still there...

**Comment by martin-frbg** [comment]
There is a proposed solution in #2110 but it is still not perfect (I think)

**Comment by brada4** [comment]
You can slip past that (wrong) detection with:
`make CC='cc -mavx2'`

**Comment by martin-frbg** [comment]
Hopefully fixed now by #2110

**Comment by ghost** [comment]
Thanks, seems good.
