### ISSUE TITLE
Hidden ABI problems in calls from C to FORTRAN

### ISSUE THREAD

**Issue by martin-frbg** [xianyi/OpenBLAS#2154]
As noted (by a gfortran developer) in https://github.com/Reference-LAPACK/lapack/issues/339, the de facto ABI for calling FORTRAN code from C requires the lengths of any string arguments to be passed as additional, hidden arguments at the end of the argument list. Changes in gcc from about gcc8 onwards (higher patchlevels of gcc7 might be equally affected) have apparently enforced this for single-character arguments as well, which affects most LAPACK(E) functions through their use of flags like N/T for (non)transpose or U/L for upper/lower triangular matrix. This has already led to misbehaviour in LAPACK calls from codes like Armadillo https://github.com/RcppCore/RcppArmadillo/issues/254 - as noted there, a workaround is to compile the FORTRAN code with -fno-optimize-sibling-calls and upcoming releases of gcc will incorporate a similar workaround for the time being.
This still leaves existing installations with unpatched gcc 7.x, 8.x, 9.x vulnerable to the problem, so while (most of) an eventual "proper" fix would have to happen upstream in the netlib LAPACKE we need to fix this locally as well. (It appears to be still unclear how compilers other than gfortran handle the length requirement for single-character strings, but it has been argued that current code is at best relying on undefined behaviour.)

**Comment by brada4** [comment]
i think `cmake/fc.cmake` is mising and probably `-frecursive` for power.

**Comment by martin-frbg** [comment]
Yes that particular PR was only for the gmake side of things. (And I have not touched, and certainly not removed -frecursive)

**Comment by brada4** [comment]
In no case I blame you, its just place I walked by once ago.
