### ISSUE TITLE
GEMM packing with conversion. single->double double->single inside

### ISSUE THREAD

**Issue by quickwritereader** [xianyi/OpenBLAS#2160]
It is different than #1092
I would like to know if we can make the packing code with the conversion.
for z13 this way I could use blas3 double codes for single. (vector single precision on z13 hardware is not supported)
Benefits of this:
one could concentrate on improving blas3 double.
As I am thinking of working on the improvement of z13  initial blas3 especially single precision.

**Comment by brada4** [comment]
There is no cast+copy(+scale) in the codebase. Once there was idea about accelerated Half-to-Single fro AI DSP and such things that did not materialize.

**Comment by brada4** [comment]
Say you can size up with vector bitops, but down you need to consider all subnormals/under-/over-flows and itmight nor be that fast.

**Comment by quickwritereader** [comment]
Thx @brada4 for advice.
Practically I need single to double.
for z13 I am doing single to double conversion. but its  done inside loop which I want to separate and tune loop for pipeline.
I could write small packing/conversion inside gemm microkernel.But considering that packing is already done for A B matrices I opened this issue.
So I want to know if I can  add that functionality and will it be welcomed.   
If yes what will be the cleanest way to add that.

**Comment by quickwritereader** [comment]
closed for now as it is not so important. probably I will reopen if I start to work on it

**Comment by brada4** [comment]
Certainly problems arise casting down in IEEE754 conforming manner.
Actually given hardware limitations you can win tons of precision by pushing whole lapack call into doubles... In my dreams that it could be global ifdef or something.....
