### ISSUE TITLE
thread safety of dgemv in 0.3.6

### ISSUE THREAD

**Issue by simonnwood** [xianyi/OpenBLAS#2164]
This may be related to #1761. I am calling the dgemv supplied by a single threaded OpenBLAS 0.3.6 from OpenMP threads, and intermittently obtaining incorrect results. A stripped down version of the problem is provided by the following code (modified from #1761). The code multiples 2 matrices by repeatedly calling dgemv, first from a single thread, and then in parallel using OpenMP. The results are compared to see if they are identical, as expected. In this code the  experiment is repeated 1000 times or until the results differ substantially. 

```
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <omp.h>
#include <cblas.h>


void mult(double *A,double *B,double *C,int m,int n,int nt) {
/* pointless C=A'B code using openmp. A and B are m by n. C is n by n. */
  int i,j;
#pragma omp parallel for private(i) num_threads(nt)
  for (i=0;i<n;i++) {
    cblas_dgemv(CblasColMajor, CblasTrans,m,n,1,A,m,B+i*m,1,0,C+i*n,1);
  }
  /* NOTE: in original code producing problem replacing dgemv with dgemm 
     did not fix the problem */
}


void main() {
  double *A,*B,*C,*D,*c,*d,diff=0.0,x,max=0.0;
  int n = 200,m=300,i,j;
  A = (double *)calloc((size_t)n*m,sizeof(double));
  B = (double *)calloc((size_t)n*m,sizeof(double));
  C = (double *)calloc((size_t)n*n,sizeof(double));
  D = (double *)calloc((size_t)n*n,sizeof(double));
  for (i=0;i<n*m;i++) {A[i] = i*0.01;B[i]= n*m/(i*.04+.1);}
  mult(A,B,D,m,n,1);
  for (j=0;j<1000;j++) { /* repeat multi-threaded call until a failure encountered */
    mult(A,B,C,m,n,4);        
    for (d=D,c=C,i=0;i<n*n;i++,c++,d++) { /* compare C & D which should be identical */
      x = fabs(*d-*c); if (x>diff) diff=x;
      if (*d>max) max = *d;
    }
    if (diff>max*1e-2) break;
    printf(".");fflush(stdout);
  }
  printf("\nMax |D| = %g\nMax abs diff = %g\n",max,diff);
}
```
Compiling and running this as follows:
```
gcc problem.c -I /opt/OpenBLAS/include/ -L /opt/OpenBLAS/lib/ -lopenblas -fopenmp
LD_LIBRARY_PATH=/opt/OpenBLAS/lib ./a.out
```
gives (after a variable number of iterations) a result like
```
Max |D| = 4.48832e+09
Max abs diff = 3.48985e+09
```
under 0.3.6. In contrast, using 0.2.20 it always runs for the full 1000 iterations before returning 
```
Max |D| = 4.48832e+09
Max abs diff = 0
```
as it should. Note that the only substantive change to the code relative to #1761 is the loop to repeat the experiment, so I don't think that the problem can lie in the test code.

My (64bit) test set up is an Intel i5-6300U CPU, Ubuntu 16.04, gcc 5.4.0. OpenBLAS was compiled with `USE_THREAD=0` (and I also tried `FCOMMON_OPT=-frecursive` and `NUM_THREADS=8` after looking at #1690). 

My real application of this is the R package [https://cran.r-project.org/web/packages/mgcv/index.html](url) which offers some `big data' methods that need this functionality and are currently intermittently failing their tests.

**Comment by martin-frbg** [comment]
Probably related to #2126

**Comment by TiborGY** [comment]
The latest dev version with `USE_LOCKING=1 ` might fix this.
Also, we now have a thread safety tester integrated into the project. Could you try compiling with `CPP_THREAD_SAFETY_TEST = 1`? This runs a test after the build, and should catch most thread safety issues.

**Comment by simonnwood** [comment]
Thanks, the latest dev with `make USE_THREAD=0 USE_LOCKING=1` indeed fixes the problem, both for the test code (above) and the original application. Will  `USE_LOCKING=1` be the default with `USE_THREAD=0` in future stable releases? I need to update my package documentation to make sure users of openblas have a suitable one.

**Comment by martin-frbg** [comment]
Not decided yet as I am not sure what the "default" context for a USE_THREAD=0 build of OpenBLAS is supposed to be - a truely single-threaded program, where the locking would only incur unnecessary overhead and an unwanted dependency on libpthread, or a heavily multithreaded program whose use of OpenMP  is (contrary to earlier assumptions) not sufficient to keep things in order.

**Comment by TiborGY** [comment]
I might be a good idea to print a big fat warning at the end of the build,
if someone builds with a configuration that is decidedly not thread safe.
(such as USE_THREAD=0 USE_LOCKING=0)
Something like this:

WARNING: This build was not configured to be thread safe. Please make sure
that programs using this build never call any BLAS/LAPACK subroutine from
more than one thread at the same time. Otherwise, you may get INCORRECT
RESULTS.

Hopefully people would notice something like this appearing at the end of
the build.


Martin Kroeker <notifications@github.com> ezt írta (időpont: 2019. jún.
17., H, 12:50):

**Comment by simonnwood** [comment]
My example above only ever uses 4 threads (and also failed with only 2 threads), and all it is doing is calling dgemv from these threads, with no overlap of memory that is supposed to be modified between the threads. Does that really count as heavily multi-threaded, and is there a way I could have used openMP to keep things in order? 

Or am I missing something about how to build a single threaded BLAS, and there is another way to do it than USE_THREAD=0 that avoids these problems (I'm very much in recipe following mode with this, and may well be missing things)?

My problem is that my users are often working on a machine where the BLAS is managed by someone else, especially in the cases in which some multi-threading may help (they are statistically modelling in R and selecting a number of threads to use), and usually have only the vaguest idea of what the BLAS is actually doing, let alone how to configure it. If I have to tell them to check that OpenBLAS has been compiled using USE_LOCKING=1 they are  liable to read this as telling them not to use OpenBLAS (or not to multithread).

**Comment by TiborGY** [comment]
OpenBLAS has some internal state that is shared between all concurrently
running BLAS calls. So, unless OpenBLAS is compiled with locking enabled
(BTW setting USE_THREAD=1 also enables locking), even two concurrent BLAS
calls can mess up the internal shared state of the library. As far as I
know, if OpenBLAS is compiled without locking enabled there is nothing the
user can do to make it thread safe, but maybe Martin could confirm this.

In other words, I think if USE_THREAD=0 is set, then without USE_LOCKING=1
OpenBLAS is not thread safe at all, not even while operating on different
memory regions.
I think the library was never designed to be thread safe when it was first
written. To really solve all of these issues one would probably have to
rewrite a lot of very complicated code. (take a look at memory.c if you
dare...)


simonnwood <notifications@github.com> ezt írta (időpont: 2019. jún. 17., H,
19:12):

**Comment by simonnwood** [comment]
Thanks, that's helpful. Oddly I can't ever generate a problem in 0.2.20, only in 0.3.x. The problem from my perspective is that single threaded OpenBLAS is the default on e.g. Fedora: the default BLAS not being thread safe on some platforms is quite difficult to handle. I guess all I'm really saying is that it would be great if OpenBLAS could be safe by default, allowing experienced users wanting absolute bleeding edge performance on purely single threaded applications to turn off thread safety.

**Comment by martin-frbg** [comment]
Yes, original GotoBLAS (and accordingly OpenBLAS until about 0.2.18) was totally not thread-safe. My theory is that this simply did not become apparent on the slower x86 cpus of the time. Around 0.2.20 locks had got put around practically everything so people started to complain about decreased performance in supposedly safe OpenMP contexts so the locks were put into `#ifdef`'s (Mind you I do not consider myself an expert on thread safety, I only happened to be one of the first people who ran
valgrind's helgrind on OpenBLAS and tried to do something about the surprisingly alarming reports.)

**Comment by TiborGY** [comment]
> 
> 
> The problem from my perspective is that single threaded OpenBLAS is the default on e.g. Fedora: the default BLAS not being thread safe on some platforms is quite difficult to handle. I guess all I'm really saying is that it would be great if OpenBLAS could be safe by default

I guess that could be done. But it might also be worthwhile to reach out to package maintainers, to see if they are receptive towards the idea of releasing multiple builds with different build configs and package names.

**Comment by courage17340** [comment]
I also met up with this problem, and "USE_THREAD=0 USE_LOCKING=1" solved it. Since 0.3.7 has been released, I think that it's a good idea to update the wiki page on "How can I use OpenBLAS in multi-threaded applications?" to inform users of thread safety.

**Comment by martin-frbg** [comment]
Wiki updated now, thanks for the reminder.
