### ISSUE TITLE
DYNAMIC_ARC does't not work for me

### ISSUE THREAD

**Issue by gxkevin** [xianyi/OpenBLAS#2173]
I compile the openblas on the brodware cpu， but I make the DYNAMIC_ARC=1， the whole command is：

    make USE_OPENMP=1 NUM_THREADS=64 NO_AFFINITY=0 DYNAMIC_ARC=1
    make PREFIX=./openblas install

but when I move the binary compiled by the openblas on brodware to the skylake machine， it can't recognize the skylake cpu

    [W] [kernel/src/life_cycle_filter/conf_filter.cpp::22::proc_init] load    predictor_conf[./conf/predictor.yaml] successfully!
    [N] [kernel/src/util/predictor_env.cpp::46::predictor_proc_env] [INIT]: OpenBLAS num_procs:32 parallel_type:2 blas_conf:OpenBL
    AS 0.3.7.dev NO_AFFINITY USE_OPENMP HASWELL MAX_THREADS=64 cpu_core:HASWELL

**Comment by gxkevin** [comment]
sorry, I compile on the HASWELL cpu, not brodware

**Comment by martin-frbg** [comment]
The option is named DYNAMIC_ARCH

**Comment by gxkevin** [comment]
sorry, my mistick, but I accturally set the DYNAMIC_ARCH=1, not DYNAMIC_ARC=1

It dones't work as well

**Comment by martin-frbg** [comment]
Is this a Skylake X (Intel Xeon, with AVX512) or a desktop Skylake (i7-6xxx) ? The desktop Skylake models are identified as Haswell by OpenBLAS (no important difference in cpu instructions).

**Comment by gxkevin** [comment]
The CPU is Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz，

**Comment by gxkevin** [comment]
So If I want to use the Avx512 on skylake,  I must compile the openblas on the skylake machine as well?

the DYNAMIC_ARCH dones't work?

**Comment by martin-frbg** [comment]
Possibly your compiler on the Haswell machine was not identified correctly (issue #2152), or it really is too old to support AVX512.

**Comment by gxkevin** [comment]
my gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11) 

 ldd --version
ldd (Ubuntu GLIBC 2.23-0ubuntu10) 2.23
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

**Comment by gxkevin** [comment]
glibc2-23 does't surpport the detect?

**Comment by gxkevin** [comment]
also, when I compile , I add the TARGET=SKYLAKEX to build the openblas, It can't recognize the command

**Comment by brada4** [comment]
You need later (6 or better) compiler from ubuntu PPA to get AVX-512 support:
https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test?field.series_filter=xenial
Then use `CC=gcc-6 FC=gfortran-6` flags to select it.

**Comment by gxkevin** [comment]
ok， I'll try.
I wonder that I compile the openblas on the HASWELL, and then build my own program， then move it to the SKYLAKEX。

In this condition， both the HASWELL and SKYLAKEX need g++/gcc 6?

**Comment by brada4** [comment]
You need gcc 6 or better to generate AVX512 code path in dynamic arch binary. There are no huge optimisations included yet in assembly (BLAS) for SkylakeX over running Haswell fallback. But few percent sometimes do matter.

Forced more modern architecture build e.g SkylakeX, will not work on older CPUs e.g. Sandybridge, generating SIGILL when encountering unsupported instructions (also applies to build on old CPUs for single more modern arch)

You need dynamic arch to use same module on multiple machines (And DYNAMIC_OLDER for old and rare CPUs)

I think Makefile.rule is your best source for now. You might want to bump up thread count over building desktop to better utilize multi-socket xeon server.

**Comment by brada4** [comment]
NO_AFFINITY=0 does not work as intended, you have to comment it out from Makefile.rule to enable CPU affinity settings. Note they dont work if other code uses any kind of threading as the main() and all threads started from it is affined to single CPU core. 
Better idea is to fine tune Linux kernel to avoid moving processes between cores and preserve cache contexts , e.g. https://www.postgresql.org/message-id/50E4AAB1.9040902@optionshouse.com

**Comment by brada4** [comment]
If this Q repeats pgsql link should go to faq....
