### ISSUE TITLE
when I build the mxnet with openblas, how specipy the openblas path 

### ISSUE THREAD

**Issue by gxkevin** [xianyi/OpenBLAS#2174]
acturally, I want to disable the openmp in openblas, I used :

     sudo make USE_OPENMP=0 NUM_THREADS=64 NO_AFFINITY=0 DYNAMIC_ARCH=1 CC=gcc-6 FC=gfortran-6

then I compile the mxnet with openblas, my command is 

    sudo make -j4 USE_OPENCV=0 USE_MKLDNN=0 USE_BLAS=openblas

but it can't work, the output is 

     OpenBLAS num_procs:32 parallel_type:2 blas_conf:OpenBLAS 0.3.7.
dev DYNAMIC_ARCH NO_AFFINITY USE_OPENMP SkylakeX MAX_THREADS=64 cpu_core:SkylakeX

the system install the openblas before with USE_OPENMP=1, and should I specipy the openblas path ?

**Comment by martin-frbg** [comment]
That is actually more a question for the mxnet folks - as far as I can tell there is no option like USE_OPENBLAS_PATH in their config.mk although there is USE_LAPACK_PATH and USE_INTEL_PATH.  If you do not need the system-installed openblas, you could uninstall it or copy your own version in its place. Or if you want to keep both versions, try setting  LD_LIBRARY_PATH=/path/to/your/openblas before running mxnet

**Comment by brada4** [comment]
Build parameter , according to documentation is
`BLAS=Open`
