### ISSUE TITLE
ar: sgemm_kernel.o: No such file or directory

### ISSUE THREAD

**Issue by vbraun** [xianyi/OpenBLAS#2176]
OpenBLAS 0.3.6 fails to build on a QEMU vm (/proc/cpuinfo model name: QEMU Virtual CPU version 2.5+). The generated Makefile.conf has 
````
CORE=P6
LIBCORE=p6
````
and the compile does not specify a sgemm kernel (which is a gcc warning only, but then fails at the linking stage):
````
$ make
[...]
gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DNO_AVX512 -DNO_WARMUP -DMAX_CPU_NUMBER=1 -DMAX_PARALLEL_NUMBER=1 -DUSE_TLS -DVERSION=\"0.3.6\" -DASMNAME=sgemm_kernel -DASMFNAME=sgemm_kernel_ -DNAME=sgemm_kernel_ -DCNAME=sgemm_kernel -DCHAR_NAME=\"sgemm_kernel_\" -DCHAR_CNAME=\"sgemm_kernel\" -DNO_AFFINITY -I.. -UDOUBLE  -UCOMPLEX -c -UDOUBLE -UCOMPLEX ../kernel/x86_64/ -o sgemm_kernel.o
gcc: warning: ../kernel/x86_64/: linker input file unused because linking not done
[...]
ar: sgemm_kernel.o: No such file or directory
````
Manually specifying a valid `make TARGET=...` works. 

The way I understand it, `P6` is not a valid target (and its not in TargetList.txt) so it shouldn't be emitted during auto detection. Though there are a few differences between cpuid_x86.c  cpuname and TargetList.txt, so I don't really understand how this compiles in all cases. Shouldn't the CORE variable be constrained to valid TARGETs?

**Comment by vbraun** [comment]
Makefile.conf:
````
OSNAME=Linux
ARCH=x86_64
C_COMPILER=GCC
BINARY32=
BINARY64=1
CEXTRALIB=-L/usr/lib/gcc/x86_64-linux-gnu/6 -L/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/6/../../..  -lc  
F_COMPILER=GFORTRAN
FC=gfortran
BU=_
FEXTRALIB=-L/usr/lib/gcc/x86_64-linux-gnu/6 -L/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/6/../../..  -lgfortran -lm -lquadmath -lm -lc  
CORE=P6
LIBCORE=p6
NUM_CORES=2
HAVE_MMX=1
HAVE_SSE=1
HAVE_SSE2=1
HAVE_SSE3=1
MAKE += -j 2
SGEMM_UNROLL_M=8
SGEMM_UNROLL_N=2
DGEMM_UNROLL_M=2
DGEMM_UNROLL_N=2
QGEMM_UNROLL_M=2
QGEMM_UNROLL_N=2
CGEMM_UNROLL_M=4
CGEMM_UNROLL_N=1
ZGEMM_UNROLL_M=1
ZGEMM_UNROLL_N=1
XGEMM_UNROLL_M=1
XGEMM_UNROLL_N=1
CGEMM3M_UNROLL_M=8
CGEMM3M_UNROLL_N=2
ZGEMM3M_UNROLL_M=2
ZGEMM3M_UNROLL_N=2
XGEMM3M_UNROLL_M=2
XGEMM3M_UNROLL_N=2
````
config.h:
````
#define OS_LINUX	1
#define ARCH_X86_64	1
#define C_GCC	1
#define __64BIT__	1
#define PTHREAD_CREATE_FUNC	pthread_create
#define BUNDERSCORE	_
#define NEEDBUNDERSCORE	1
#define PENTIUM2
#define L1_CODE_SIZE 32768
#define L1_CODE_ASSOCIATIVE 8
#define L1_CODE_LINESIZE 64
#define L1_DATA_SIZE 32768
#define L1_DATA_ASSOCIATIVE 8
#define L1_DATA_LINESIZE 64
#define L2_SIZE 2097152
#define L2_ASSOCIATIVE 8
#define L2_LINESIZE 64
#define L3_SIZE 16777216
#define L3_ASSOCIATIVE 16
#define L3_LINESIZE 64
#define DTB_DEFAULT_ENTRIES 32
#define HAVE_CMOV
#define HAVE_MMX
#define HAVE_SSE
#define HAVE_SSE2
#define HAVE_SSE3
#define HAVE_CFLUSH
#define NUM_SHAREDCACHE 1
#define NUM_CORES 1
#define CORE_P6
#define CHAR_CORENAME "P6"
#define SLOCAL_BUFFER_SIZE	8192
#define DLOCAL_BUFFER_SIZE	8192
#define CLOCAL_BUFFER_SIZE	8192
#define ZLOCAL_BUFFER_SIZE	8192
#define GEMM_MULTITHREAD_THRESHOLD	4
````

**Comment by martin-frbg** [comment]
P6 is a valid (if somewhat historic) x86 target, the problem is most likely "just" that getarch returns it as a 64bit platform (and the appropriate match for what Qemu simulates is probably something more modern anyway - just that it does not correspond to any actual hardware model)

**Comment by vbraun** [comment]
For the record, this is a 64-bit system so that part is correct. Of course I'm not looking for optimum performance, just don't want to support cryptic build errors (this was reported to sagemath.org)

**Comment by brada4** [comment]
P6 is/was a 32bit CPU
`qemu-system-x86_64 -cpu help`
should tell available CPU types.
You should use any 64bit emulated CPU
`-cpu qemu64`
`-cpu kvm64`
Should be lowest functional 64bit "fake" cpus 
Or `n270` or `core2duo` or `athlone` for more "real" ones
It was written down long ago, though does not mention 64bit openblas needs 64bit CPUID:
https://github.com/xianyi/OpenBLAS/wiki/faq#qemu

**Comment by martin-frbg** [comment]
The problem with emulators/VMs is that they often default to some weird subset of the host cpu features (and/or an Intel cpuid that does not officially exist).

**Comment by brada4** [comment]
Those I mentioned worked fro me before I posted, their 32bit close siblings did not.
@vbraun - can you post `cat /proc/cpuinfo` section regarding last COU core. 
If it is not any CPU ever made it might be possible to make it work as `TARGET=CORE2`

**Comment by vbraun** [comment]
I haven't set up the vm myself but I'm pretty sure this is the `qemu64` cpu (a.k.a "hypervisor default")
````
$cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 6
model name	: QEMU Virtual CPU version 2.5+
stepping	: 3
microcode	: 0x1
cpu MHz		: 3192.754
cache size	: 16384 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm rep_good nopl xtopology pni cx16 x2apic hypervisor lahf_lm kaiser
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds
bogomips	: 6385.50
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:
````

**Comment by brada4** [comment]
It matches Pentium2 celeron, old 32bit cpu, so it is a no-go, you have to use other cpuid.
CORE2 target should work with cpu feature bits shown

**Comment by vbraun** [comment]
I see. I looked through the qemu sources for the reason behind the cpu family choice, and it is intentionally conflicting with an existing cpu. They initially used a non-existing cpu model/family but that just exposed OS kernel bugs: https://git.qemu.org/?p=qemu.git;a=commit;f=target/i386/cpu.c;h=f8e6a11aecc96e9d8a84f17d7c07019471714e20

I'd argue that cpu family = model = 6 is always going to be qemu32/qemu64 nowadays, nobody is going to compile openblas on a 20-year old 32-bit only cpu...

**Comment by martin-frbg** [comment]
Maybe, but then why would one go to the trouble of installing an optimized BLAS, yet run the software on the least performant, "least common denominator" default cpu configuration the emulator has to offer ?

**Comment by vbraun** [comment]
Because you might be using the vm but not be in charge of setting it up. E.g. your school sets up a vm (with default values) for a project, that is where we ran into the issue.

The other reason for using the lowest-common denominator cpu is live migration, but at least thats not our use case.

**Comment by brada4** [comment]
No need to appeal to weakest. They will use any KVM GUI and get a copy of host CPUID, unlike those hardass typists that out of principle will not write 5 characters after finishing 2x80 command line to start a VM.
