### ISSUE TITLE
Fast avx2 dgemm subroutine for large matrices

### ISSUE THREAD

**Issue by wjc404** [xianyi/OpenBLAS#2178]
[handcoded_DGEMM_subroutine.tar.gz](https://github.com/xianyi/OpenBLAS/files/3365904/handcoded_DGEMM_subroutine.tar.gz)
Dear OpenBLAS developers,
   I tested the avx2 dgemm subroutine of OpenBLAS(target=haswell) on an i9-9900K(avx-offset=6) and found it ~5% slower to Intel MKL(2018). I wrote a dgemm code myself for fun and optimized it to 98-99% MKL single thread performance for large matrices. The code may look unprofessional since i'm not an expert programmer. I wonder if some experts can further optimize it and put it into OpenBLAS.

Thanks,
wjc404

**Comment by brada4** [comment]
Can you make it a PR so that it drills through CI?

**Comment by brada4** [comment]
Is it as fast with -O2 ? Numeric accuracy is absolute paramount here.

**Comment by martin-frbg** [comment]
No need for CI as I can test Haswell locally (and CI only runs the regular build tests anyway, rather than e. g. BLAS-tester).
Haswell improvements are definitely welcome as the key developer for that architecture dropped out unexpectedly about two years ago, possibly for medical reasons

**Comment by brada4** [comment]
It will take some time do dissect the code, it looks as good as static checkers dont barf out on the spot
it is -O3 (waiting for feedback w -O2), hope no problem there
It has FMA+AVX2 intrinsics inner loops
Some assembly
Some provate functions, not sure if they do well unaligned with spectres' workarounds on lower CPUs
And -fopenmp (-only) own work piece distribution.
But I think porting is doable, worth even if it is half of promised benefit.

**Comment by brada4** [comment]
I think `-mfma` can be added to haswell already

**Comment by wjc404** [comment]
[performance_1thread_9900k_-O2.txt](https://github.com/xianyi/OpenBLAS/files/3368225/performance_1thread_9900k_-O2.txt)
@brada4 Thanks for your advice. I tested -O2 option and found the performance losses were less than 0.5% in most cases.

**Comment by wjc404** [comment]
[test_results_1thread_r5-1600_m=n=k=5000.txt](https://github.com/xianyi/OpenBLAS/files/3368373/test_results_1thread_r5-1600_m.n.k.5000.txt)
I also tested the newly wrote subroutine on a ryzen r5-1600 processor (OpenBLAS (target=zen) as reference), the results were also promising.

**Comment by wjc404** [comment]
[test_results_1thread_r5-1600_m=n=k=5000.txt](https://github.com/xianyi/OpenBLAS/files/3368383/test_results_1thread_r5-1600_m.n.k.5000.txt)
 I also tested the newly written subroutine on a ryzen r5-1600 processor (OpenBLAS (target=zen) as reference), the results were also promising.

**Comment by brada4** [comment]
Are you sure about 7000.7000 gemm speed?
i5-4690 turns up 3x faster?
```
R> xx<-matrix(rnorm(7000*7000),7000)
R> xy<-matrix(rnorm(7000*7000),7000)
R> system.time(xz<-crossprod(xx,xy))
 14.872   0.280   3.887 
```

**Comment by wjc404** [comment]
Sorry I may not have expressed myself clearly. The previous test (66 GFLOPS) ran on a single thread.

**Comment by wjc404** [comment]
[asm_dgemm.S.txt](https://github.com/xianyi/OpenBLAS/files/3373708/asm_dgemm.S.txt)

I managed to transfer the function "dgemmblkregccc_ac" to pure assembly form, just like the codes in /OpenBLAS/kernel/x86_64 folder:)

**Comment by wjc404** [comment]
[asm_dgemmreg.S.txt](https://github.com/xianyi/OpenBLAS/files/3374135/asm_dgemmreg.S.txt)
also transfer the function "dgemmblkregccc_ar"

**Comment by brada4** [comment]
I think call it something haswell12x4 rhyming with files in that directory and stuff in a PR. Then with other PR activate it , for eay removal if something goes wrong. I am wondering if this or C intrinsics fits ZEN and skylakex better...

**Comment by wjc404** [comment]
[asm_dgemmreg.S.txt](https://github.com/xianyi/OpenBLAS/files/3377414/asm_dgemmreg.S.txt)
add function "dgemmblktailccc"

**Comment by wjc404** [comment]
add optimized function "load_reg_a_r"
