### ISSUE TITLE
optimized_for_deeplearning branch cross build for Android armv8 error

### ISSUE THREAD

**Issue by weirongGA** [xianyi/OpenBLAS#2183]
Hello,
  When cross-compiling OpenBLAS, build for armv8 for android platform，I met following errors.

branch:
`optimized_for_deeplearning`  

For reference my build line is as follows:

`make TARGET=ARMV8 BINARY=64 HOSTCC=gcc CC=aarch64-linux-android-gcc NOFORTRAN=1
` 
output error:
>  -DNAME=sger_k_ -DCNAME=sger_k -DCHAR_NAME=\"sger_k_\" -DCHAR_CNAME=\"sger_k\" -DNO_AFFINITY -I.. -UDOUBLE  -UCOMPLEX -UDOUBLE ../kernel/arm64/../generic/ger.c -o sger_k.o
aarch64-linux-android-gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -DF_INTERFACE_GFORT -fPIC -DNO_LAPACK -DNO_LAPACKE -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DUSE_SIMPLE_THREADED_LEVEL3 -march=armv8-a -DASMNAME=sgemm_kernel -DASMFNAME=sgemm_kernel_ -DNAME=sgemm_kernel_ -DCNAME=sgemm_kernel -DCHAR_NAME=\"sgemm_kernel_\" -DCHAR_CNAME=\"sgemm_kernel\" -DNO_AFFINITY -I.. -UDOUBLE  -UCOMPLEX -c -UDOUBLE -UCOMPLEX ../kernel/arm64/sgemm_kernel_4x4.S -o sgemm_kernel.o
<instantiation>:7:27: error: invalid operand for instruction
 fmul v16.4s, v0.4s, v8.4s[0]
                          ^
../kernel/arm64/sgemm_kernel_4x4.S:923:2: note: while in macro instantiation
 KERNEL16x4_I
 ^
<instantiation>:8:27: error: invalid operand for instruction
 fmul v20.4s, v0.4s, v8.4s[1]
                          ^
../kernel/arm64/sgemm_kernel_4x4.S:923:2: note: while in macro instantiation
 KERNEL16x4_I
 ^
<instantiation>:13:27: error: invalid operand for instruction
 fmul v24.4s, v0.4s, v8.4s[2]
                          ^
../kernel/arm64/sgemm_kernel_4x4.S:923:2: note: while in macro instantiation
 KERNEL16x4_I
 ^
<instantiation>:14:27: error: invalid operand for instruction
 fmul v28.4s, v0.4s, v8.4s[3]
                          ^
../kernel/arm64/sgemm_kernel_4x4.S:923:2: note: while in macro instantiation
 KERNEL16x4_I
 ^
<instantiation>:19:27: error: invalid operand for instruction
 fmul v17.4s, v2.4s, v8.4s[0]
                          ^

> 
Is there any solutions?

**Comment by martin-frbg** [comment]
That branch has been dead for several years, and it had only a single change over the (then) mainline, https://github.com/xianyi/OpenBLAS/commit/92058a75e2cc1e46e73e2784f691a2bcb2f9aef9 so you are probably much better off if you use the current develop branch. (The actual assembly error you encountered here appears to have been fixed by PR #819 over three years ago)

**Comment by weirongGA** [comment]
Thank you for your reply.
