### ISSUE TITLE
LAPACKE_degesv gives incorrect result with LAPACK_ROW_MAJOR order

### ISSUE THREAD

**Issue by physcrf** [xianyi/OpenBLAS#2188]
I tried a simple code for test to solve a linear equation using LAPACKE_dgesv. When using column major order, it gives the correct answer. The code is

`
#include <stdio.h>
#include <lapacke.h>

int main ()
{
        double A[4] = {1,2,3,4};
        double x[2] = {1,2};
        int ipiv[2];
        int info = LAPACKE_dgesv (LAPACK_COL_MAJOR, 2, 1, A, 2, ipiv, x, 2);
        printf ("info = %d\n", info);
        printf ("x[0] = %g, x[1] = %g\n", x[0], x[1]);
        return 0;
}
`

And the output is

`
info = 0
x[0] = 1, x[1] = 0
`

However, if row major ordering is used, the code is

`
#include <stdio.h>
#include <lapacke.h>

int main ()
{
        double A[4] = {1,2,3,4};
        double x[2] = {1,2};
        int ipiv[2];
        int info = LAPACKE_dgesv (LAPACK_ROW_MAJOR, 2, 1, A, 2, ipiv, x, 2);
        printf ("info = %d\n", info);
        printf ("x[0] = %g, x[1] = %g\n", x[0], x[1]);
        return 0;
}
`

The output is

`
info = 0
x[0] = -1, x[1] = 2
`

The right answers should be x[0] = 0, x[1] = 0.5. I don't know if I misunderstand row major ordering in LAPACKE or I misuse the routine.

**Comment by vladimir-ch** [comment]
The stride of `x` (the `ldb` parameter) is 1 in your case, not 2.

**Comment by physcrf** [comment]
In Netlib's manual http://www.netlib.org/lapack/explore-html/d7/d3b/group__double_g_esolve_ga5ee879032a8365897c3ba91e3dc8d512.html it states that LDB >= max(1,N). It seems that I misunderstand this parameter.

Thanks very much.

**Comment by vladimir-ch** [comment]
> LDB >= max(1,N)

That applies in column major ordering. In row major the condition is `ldb >= max(1,nrhs)`.
