### ISSUE TITLE
sgemm_kernel.o: No such file or directory

### ISSUE THREAD

**Issue by jiamuluo** [xianyi/OpenBLAS#2192]
i want to cross compile openblas by arm-himix200-linux-gcc.My cmdline is 
```
make TARGET=ARMV7 HOSTCC=gcc CROSS=1 BINARY=32 CROSS_SUFFIX=arm-himix200-linux- BINARY=32 NOFORTRAN=1 libs -j8
```
But  i get error arm-himix200-linux-ar: sgemm_kernel.o: No such file or directory.Could you give some advice?Thanks

**Comment by antoscha** [comment]
Just remove `BINARY=32`.

**Comment by jiamuluo** [comment]
sorry,I have tried it,but just get a  same err message.

**Comment by martin-frbg** [comment]
CROSS=1 and CROSS_SUFFIX are used internally in the makefiles, but the build system does not expect to have to handle them in the early stages of cpu/host detection. Please try 
`make TARGET=ARMV7 HOSTCC=gcc CC=arm-himix-200-linux-gcc NOFORTRAN=1 -j8` instead (also limiting the build to the "libs" stage should no longer be necessary if you build a recent version of OpenBLAS)

**Comment by jiamuluo** [comment]
That's it.Thanks a lot
