### ISSUE TITLE
OpenBLAS on docker hub

### ISSUE THREAD

**Issue by dpraul** [xianyi/OpenBLAS#2195]
Hi there! I was browsing docker hub and saw that there is an [`openblas/alpine`](https://hub.docker.com/r/openblas/alpine) image published by the `openblas` org that has not been updated in a while. Is this maintained by you? If so, are you seeking to build it out at all? It would be nice to have official & automated builds of OpenBLAS images for different OSs

**Comment by martin-frbg** [comment]
I suspect you are looking at the base build environment image (prepared by @aytekinar for issue #1861/PR #1864) that was used in the Travis Ci tests for the (emulated) ARM architecture until we moved them to native builds on Drone. The idea of providing images has some merit but I am not sure if there is both sufficient demand and capacity.

**Comment by dpraul** [comment]
I suppose that's what it could be? I did not delve too deeply because it appeared to be out of maintenance.

The reason I ask is not because of alpine - they get regular enough releases that I imagine most people can get away with just installing via apk. We use debian images though, and have need of recent version of OpenBLAS on those images. We've been working on a minimum OpenBLAS `Dockerfile` that should work with the automated docker hub builds - would there be any interest in integrating that here?

**Comment by aytekinar** [comment]
Hi @dpraul. As @martin-frbg has already pointed out, `openblas/alpine` is a multi-architecture `alpine` image that only contains the toolchain needed to build OpenBLAS from source, and is only used in the unit testing of OpenBLAS in (emulated) ARM architectures.

The reason why I cannot have automated Docker builds is that I need some sort of CI environment (such as Travis) to build the multi-architecture images. That is the very reason why the images are old --- I cannot bind hookups from Docker's `alpine` repository to my Travis account.

You can check what exactly I am doing under my [repository](https://github.com/aytekinar/openblas-alpine), if you want.

PS: I am the owner of `openblas` Docker Hub group, and if you would like to integrate your solution there, I am happy to add you as a member there, too.

**Comment by dpraul** [comment]
I see what you mean now, thanks for clarifying. 

It seems I moved too quickly on opening this issue, as our priorities have changed and we no longer need to build our own version of OpenBLAS in Docker, so there's no use in integrating our solution if we won't be able to maintain it. Thanks again for taking the time to respond, though.
