### ISSUE TITLE
compile failed of v0.3.5 in Centos 7.4 with Xeon Platinum 8163

### ISSUE THREAD

**Issue by annpeter** [xianyi/OpenBLAS#2200]
`
cc -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DNO_AVX512 -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DMAX_PARALLEL_NUMBER=1 -DVERSION=\"0.3.5\" -DASMNAME=sgemm_kernel -DASMFNAME=sgemm_kernel_ -DNAME=sgemm_kernel_ -DCNAME=sgemm_kernel -DCHAR_NAME=\"sgemm_kernel_\" -DCHAR_CNAME=\"sgemm_kernel\" -DNO_AFFINITY -I.. -UDOUBLE  -UCOMPLEX -c -UDOUBLE -UCOMPLEX ../kernel/x86_64/sgemm_kernel_16x4_skylakex.c -o sgemm_kernel.o
cc -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DNO_AVX512 -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DMAX_PARALLEL_NUMBER=1 -DVERSION=\"0.3.5\" -DASMNAME=sgemm_incopy -DASMFNAME=sgemm_incopy_ -DNAME=sgemm_incopy_ -DCNAME=sgemm_incopy -DCHAR_NAME=\"sgemm_incopy_\" -DCHAR_CNAME=\"sgemm_incopy\" -DNO_AFFINITY -I.. -UDOUBLE  -UCOMPLEX -c -UDOUBLE -UCOMPLEX ../kernel/x86_64/../generic/gemm_ncopy_16.c -o sgemm_incopy.o
../kernel/x86_64/sgemm_kernel_16x4_skylakex.c: In function 'sgemm_kernel':
../kernel/x86_64/sgemm_kernel_16x4_skylakex.c:789:4: error: unknown type name '__m512'
    __m512 zmm0, zmm1, zmm2, zmm3, row0, zmm5, row1, zmm7, row2, row3, row0b, row1b, row2b, row3b, row0c, row1c, row2c, row3c, row0d, row1d, row2d, row3d;
    ^
../kernel/x86_64/sgemm_kernel_16x4_skylakex.c:797:4: warning: implicit declaration of function '_mm512_setzero_ps' [-Wimplicit-function-declaration]
    INIT64x4()
    ^
../kernel/x86_64/sgemm_kernel_16x4_skylakex.c:801:5: warning: implicit declaration of function '_mm512_loadu_ps' [-Wimplicit-function-declaration]
     KERNEL64x4_SUB()
     ^
../kernel/x86_64/sgemm_kernel_16x4_skylakex.c:801:5: warning: implicit declaration of function '_mm512_broadcastss_ps' [-Wimplicit-function-declaration]
../kernel/x86_64/sgemm_kernel_16x4_skylakex.c:805:4: warning: implicit declaration of function '_mm512_set1_ps' [-Wimplicit-function-declaration]
    SAVE64x4(alpha)
    ^
../kernel/x86_64/sgemm_kernel_16x4_skylakex.c:805:4: warning: implicit declaration of function '_mm512_storeu_ps' [-Wimplicit-function-declaration]
../kernel/x86_64/sgemm_kernel_16x4_skylakex.c:815:4: error: unknown type name '__m512'
    __m512 zmm0, zmm1, zmm2, zmm3, row0, row1, row2, row3, row0b, row1b, row2b, row3b;
`

**Comment by brada4** [comment]
Your system compiler does not support AVX-512.
Maneuvers around softwarecollections.org binutils are described in OpenBLAS FAQ.

**Comment by annpeter** [comment]
@brada4  i use gcc version 6.5.0, which should support AVX-512.

**Comment by martin-frbg** [comment]
Can you try version 0.3.6 (or the current "develop" branch here on github) please ? The problem is probably that your compilation does not pick up one of the `*immintrin.h` headers for he AVX512 intrinsics. (Though what is strange is that (a) these should be present in 6.5.0, and (b) the build system appears to have detected a problem with AVX512 support already and defined "NO_AVX512" accordingly, yet still tries to compile the SkylakeX codes rather than their non-AVX512 Haswell fallbacks)

**Comment by annpeter** [comment]
@martin-frbg  I used 0.3.6, it compile succeed. but 0.3.6 seems not support by kaldi(which depends on openblas).

**Comment by martin-frbg** [comment]
I do not think there should be a reason for them to avoid 0.3.6, perhaps they just did not update the version number in kaldi/tools/Makefile ? Anyway if you want to use 0.3.5, you can add TARGET=HASWELL to their `make` commandline (last line of kaldi/tools/Makefile) so that it avoids the AVX512 codes completely. (Unfortunately the AVX512 DGEMM in OpenBLAS is currently broken anyway, even in 0.3.6 - if Kaldi only uses single precision, i.e. SGEMM you should be alright with 0.3.6)

**Comment by annpeter** [comment]
I use TARGET=HASWELL to compile 0.3.5, it compile succeed. What's the difference between  TARGET=HASWELL AND TARGET= SkylakeX ？


I change the version number in kaldi/tools/Makefile to 0.3.6，openblas compile succeed，but kaldi build got some errors.
one error is because, in 0.3.6 openblas OpenBLAS/install/include/(build out) dir only got two .h files, lapacke.h、 lapacke_xx.h  is missing.

**Comment by martin-frbg** [comment]
The key difference between TARGET=HASWELL and TARGET=SKYLAKEX is that SKYLAKEX target will use the new AVX512 instructions (and registers) of the current generation Xeon cpu for SGEMM, DGEMM and related functions like STRMM/DTRMM. (This was contributed by someone who works for Intel - unfortunately none of the more regular contributors to OpenBLAS has AVX512 coding experience or actual hardware)
Not sure why your 0.3.6 build would not install all header files (Some of them are generated in the `make install` step, so if the kaldi build does its own copying after the build it may miss them - but
I think the same mistake would then have happened with 0.3.5 already)

**Comment by brada4** [comment]
https://github.com/xianyi/OpenBLAS/wiki/faq#binutils
You need to install binutils from devtools in addition to the compiler.
EDIT: 0.3.6 has the detection routing that hopefully applies NO_AVX512=1 flag if compiler toolkit is too old. Please tell if something is amiss there (or in develop version). It is intended to build well out of the box.
