### ISSUE TITLE
Tag 0.3.7?

### ISSUE THREAD

**Issue by TiborGY** [xianyi/OpenBLAS#2201]
Are there any issues left that need to be resolved before tagging 0.3.7?
The big one was AVX-512, and that has been resolved by disabling those parts, right?
I think we should not drag this on too much longer, as 0.3.7 already has a number of fixes and enhancements and many people grab whatever the latest release is.

**Comment by martin-frbg** [comment]
I agree completely, except that I do not have time to do a release in the next few days, and I have now given in and ordered an AVX512 system which should arrive by tuesday. (The old ARMV7 softfp issues from the current milestone will need to be pushed back again anyway as I have not managed to find any usable armeabi image that would either run in qemu or on my asus tinkerboard)

**Comment by martin-frbg** [comment]
released 0.3.7 just now.

**Comment by TiborGY** [comment]
Thanks Martin!
