### ISSUE TITLE
Make error: bits/c++config.h: No such file or directory

### ISSUE THREAD

**Issue by gerwang** [xianyi/OpenBLAS#2202]
I am using anaconda's gcc_linux-64 with no multilib support. When I execute `make` I get

`.../include/c++/7.3.0/complex.h:29:10: fatal error: bits/c++config.h: No such file or directory
 #include <bits/c++config.h>`

which is invoked in file common.h:
```cpp
520       (__GNUC__ >= 3 && !defined(__cplusplus))) && !(defined(FORCE_OPENBLAS_COMPLEX_STRUCT))) && !defined(_MSC_VER)
521   #define OPENBLAS_COMPLEX_C99
522   #ifndef __cplusplus
523     #include <complex.h> // here
524   #endif
```

Yes, there is no `c++config.h` in `.../include/c++/7.3.0/`. But when I compile a small test program:

```cpp
#include <complex>
#include <iostream>
using namespace std;

complex<double> nmb;

int main() {
        std::cout<<nmb.real()<<" "<<nmb.imag()<<std::endl;
}
```
It compiles and works.

**Comment by isuruf** [comment]
You need to post a more detailed error log

**Comment by gerwang** [comment]
Thanks for reply.

Here is the stderr of my make: https://gist.github.com/gerwang/0ecd264cff529588b769883aa0fe6ba2

By the way, I am using Intel(R) Xeon(R) CPU E5-2660 v3, a haswell cpu.

**Comment by isuruf** [comment]
Need the stdout too

**Comment by martin-frbg** [comment]
On my (SuSE) system, this is part of the libstdc++-devel package

**Comment by gerwang** [comment]
Updated https://gist.github.com/gerwang/0ecd264cff529588b769883aa0fe6ba2

**Comment by isuruf** [comment]
See https://github.com/xianyi/OpenBLAS/issues/818#issuecomment-207365134

You might need to unset CFLAGS and set them using `make`. See https://github.com/conda-forge/openblas-feedstock/blob/master/recipe/build.sh

**Comment by martin-frbg** [comment]
I do not believe the macro redefinition warning (issue #818) is anything more than a harmless nuisance caused by the somewhat recursive Makefile structure. Note that it is one of the gcc headers itself (complex.h) that is failing to find c++config.h - what does this file contain on your system ? (On mine, both the complex.h and plain "complex" there expect to include the c++config.h) Are you perhaps trying to cross-compile OpenBLAS on that system without having the appropriate multilib package installed (e.g. https://stackoverflow.com/questions/34437483/bits-cconfig-h-no-such-file-or-directory/36556287#36556287 ) ?

**Comment by isuruf** [comment]
conda compiler has a custom sysroot and doesn't look at the files in the system. @gerwang, do you have `CPLUS_INCLUDE_PATH` or similar env variable set?

**Comment by gerwang** [comment]
Thanks, solved my problem.

**Comment by martin-frbg** [comment]
@gerwang could you please tell what the solution was ?

**Comment by gerwang** [comment]
Yes, by changing my gcc to the one supports multilib.
Since I don't have sudo privilege, I use linuxbrew's gcc, which I can find c++config.h from ~/.linuxbrew/include/c++/5.5.0/x86_64-unknown-linux-gnu/bits.

I searched through conda's repo can didn't find conda's multilib gcc, so I gave up using conda's gcc.

So I wonder, does OpenBLAS requires multilib gcc to build? I am not going to cross compiling OpenBLAS, just want to use it on the build machine.

**Comment by isuruf** [comment]
@gerwang, did you have `CPLUS_INCLUDE_PATH` set?

**Comment by gerwang** [comment]
I think a simple solution to use on gcc with no multilib is to disable C99's complex support, reverts to using OpenBLAS's custom complex structure. Once I tried to refactor common.h to stop using C99's complex.h, but I found out there are many direct includes to complex.h, so finally I gave up. Maybe there can be an option to disable complex.h on compiler that is not multilib.

**Comment by martin-frbg** [comment]
I do not think you would need multilib if you are not cross-compiling for the "other" architecture (32bit on 64bit host, or vice versa) - there should always be the c++config.h appropriate for the build host installed with your gcc. Most likely your include path was set to point away from the conda default locations somehow. (There are ways to get around a missing or unusable complex.h, by defining FORCE_OPENBLAS_COMPLEX_STRUCT, but you will not normally want to do this on a modern system)
