### ISSUE TITLE
undefined reference file cblas_dgemm

### ISSUE THREAD

**Issue by ChrisNabold** [xianyi/OpenBLAS#2204]
I try to create a simple test using the OpenBLAS library. (Call CBLAS Interface).
I previously created the following directories
c;/openblas/lib/bin (libopenblass.dll)
c:/Openblas/lib/include (cblas.h.f77blas.h,lapacke.h,,lapacke_config.h,lapacke_mangling.h,lapacke_utils.h,openblas_config.h)
c::/Openblas/lib/lib (cmake(dir),pkgconfig(dir),libopenblas.a,libopenblas.dll.a,libopenblas_haswellp-r0.3.6.a)
I tried to use the following CMake.Lists.txt file:
cmake_minimum_required(VERSION 3.14)
project(EX7)

SET( OPENBLAS_INCLUDE_DIR "C:/Openblas/lib/include " )
IF( NOT OPENBLAS_INCLUDE_DIR )
    MESSAGE( FATAL_ERROR "Please point the environment variable EIGEN3_INCLUDE_DIR to the include directory of your Eigen3 installation.")
ENDIF()
INCLUDE_DIRECTORIES ( "${OPENBLAS_INCLUDE_DIR}"  )
SET( OPENBLAS_LIB_BIN "C:/Openblas/lib" )
LINK_DIRECTORIES( "${OPENBLAS_LIB_BIN}" )

add_executable(EX7 main.c)
------------
But I always receive the following error messages:
"C:\Program Files\JetBrains\CLion 2019.2\bin\cmake\win\bin\cmake.exe" --build C:\Users\Chris\CLionProjects\EX7\cmake-build-debug --target all -- -j 4
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/Chris/CLionProjects/EX7/cmake-build-debug
[ 50%] Linking C executable EX7.exe
CMakeFiles\EX7.dir/objects.a(main.c.obj): In function `main':
C:/Users/Chris/CLionProjects/EX7/main.c:10: undefined reference to `cblas_dgemm'
collect2.exe: error: ld returned 1 exit status
mingw32-make.exe[2]: *** [CMakeFiles\EX7.dir\build.make:86: EX7.exe] Error 1
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:72: CMakeFiles/EX7.dir/all] Error 2

Can anyone please help me

**Comment by martin-frbg** [comment]
Can you check what your library contains (`dumpbin` if you have VS installed, `nm` or `objdump` if you have mingw/msys tools) ? Possibly your build is either missing the CBLAS parts, or the function names have leading or trailing underscores like "cblas_sgemm_"

**Comment by ChrisNabold** [comment]
I almost gave up trying, but i found the solution - the correct CMakeLists.txt file should read;
cmake_minimum_required(VERSION 3.14)
project(EX7)

SET( OPENBLAS_INCLUDE_DIR "C:/Openblas/lib/include " )
IF( NOT OPENBLAS_INCLUDE_DIR )
    MESSAGE( FATAL_ERROR "Please point the environment variable EIGEN3_INCLUDE_DIR to the include directory of your Eigen3 installation.")
ENDIF()
INCLUDE_DIRECTORIES ( "${OPENBLAS_INCLUDE_DIR}"  )
SET( OPENBLAS_LIB_BIN "C:/Openblas/lib/lib" )

add_executable(EX7 main.c)
TARGET_LINK_LIBRARIES(EX7 ${OPENBLAS_LIB_BIN}/libopenblas.a )

**Comment by martin-frbg** [comment]
Ah, okay, that would make it more of a cmake usage question. I must admit I know next to nothing about using OpenBLAS or CMAKE on Windows...

**Comment by brada4** [comment]
Actually eigen provides own cblas.h that inlines blas level 1 with fixed input sizes and passes rest to f77 blas. It should not call cblas_\* in your context as eigen sort of does stub/thunk/wrap/offload already.

**Comment by martin-frbg** [comment]
@brada4 it is probably safe to assume  ChrisNabold just started from a known working CMakeLists.txt that happened to come with Eigen (or some code that uses Eigen)...
