### ISSUE TITLE
Unable to run on ARM (aarch64)

### ISSUE THREAD

**Issue by ammarik** [xianyi/OpenBLAS#2207]
Hello, 
I'm trying to run OpenBLAS on aarch64 machine with CentOS 7. I tried to run basic example provided by you: https://github.com/xianyi/OpenBLAS/wiki/User-Manual#call-cblas-interface . I've run:
```
export LD_LIBRARY_PATH=/.../blas/0.3.5.openblas/aarch64-centos7-gcc8-opt/lib64/ 
gcc -o test_cblas_open test_cblas_dgemm.c -I   /.../blas/0.3.5.openblas/aarch64-centos7-gcc8-opt/include/openblas -L /.../blas/0.3.5.openblas/aarch64-centos7-gcc8-opt/lib64/ -lopenblas  -lpthread  
./test_cblas_open
```
I've got output like this:
```
11.000000 -9.000000 5.000000 -9.000000 21.000000 -1.000000 5.000000 -1.000000 3.000000
OpenBLAS : munmap failed
OpenBLAS : munmap failed
OpenBLAS : munmap failed
OpenBLAS : munmap failed
OpenBLAS : munmap failed
OpenBLAS : munmap failed
OpenBLAS : munmap failed
OpenBLAS : munmap failed
OpenBLAS : munmap failed
OpenBLAS : munmap failed
OpenBLAS : munmap failed
OpenBLAS : munmap failed
OpenBLAS : munmap failed
OpenBLAS : munmap failed
```
Thank you for your help.

**Comment by martin-frbg** [comment]
Interesting, what kind of hardware is this ? The result as such looks correct, I suspect what happened is that OpenBLAS (in driver/others/memory.c) tried to use `mmap` for allocation initially, failed - silently - and used `malloc` instead. Later when it tried to deallocate, it may have blindly called munmap(-1) first - and error handling in that part of the code looks to be poor if it does not even return the error code from munmap...

**Comment by ammarik** [comment]
Here is output of lscpu:
```
Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                96
On-line CPU(s) list:   0-95
Thread(s) per core:    1
Core(s) per socket:    48
Socket(s):             2
NUMA node(s):          2
Model:                 0
BogoMIPS:              200.00
L1d cache:             32K
L1i cache:             78K
L2 cache:              16384K
NUMA node0 CPU(s):     0-47
NUMA node1 CPU(s):     48-95
Flags:                 fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics
```
Part of lshw output:
```
computer                    
    description: System
    product: Cavium ThunderX CN88XX board
    vendor: GIGABYTE
    version: 0100
    serial: [REMOVED]
    width: 64 bits
    capabilities: smbios-3.0.0 dmi-3.0.0 smp
    configuration: chassis=server family=Server sku=01234567890123456789AB uuid=[REMOVED]
  *-core
       description: Motherboard
       product: MT60-SC0
       vendor: GIGABYTE
       physical id: 0
       version: 01234567
       serial: [REMOVED]
       slot: Default string
     *-firmware
          description: BIOS
          vendor: GIGABYTE
          physical id: 0
          version: T08
          date: 06/06/2016
          size: 64KiB
          capacity: 8MiB
          capabilities: pci upgrade shadowing cdboot bootselect socketedrom edd int13floppy1200 int13floppy720 int13floppy2880 int5printscreen int14serial int17printer acpi usb biosbootspecification uefi
     *-cpu:0
          description: CPU
          product: ARM (CN88xx)
          vendor: www.cavium.com
          physical id: 2d
          bus info: cpu@0
          version: 2.0
          serial: [REMOVED]
          slot: Socket
          size: 2GHz
          capacity: 2GHz
          clock: 156MHz
          capabilities: lm
          configuration: cores=48 enabledcores=48
        *-cache:0
             description: L1 cache
             physical id: 2e
             slot: Intelnal L1D Cache
             size: 1536KiB
             capacity: 1536KiB
             capabilities: internal write-back data
             configuration: level=1
        *-cache:1
             description: L2 cache
             physical id: 30
             slot: Internal L2 Cache
             size: 16MiB
             capacity: 16MiB
             capabilities: internal write-back unified
             configuration: level=2
     *-cache:0
          description: L1 cache
          physical id: 2f
          slot: Internal L1I Cache
          size: 3744KiB
          capacity: 3744KiB
          capabilities: internal write-back instruction
          configuration: level=1
     *-memory
          description: System Memory
          physical id: 31
          slot: System board or motherboard
          size: 256GiB
          capacity: 1TiB
        *-bank:0
             description: DIMM DDR4 2133 MHz (0.5 ns)
             product: M393A4K40BB0-CPB
             vendor: Samsung
             physical id: 0
             serial: [REMOVED]
             slot: DIMM_P0_A0
             size: 32GiB
             width: 64 bits
             clock: 2133MHz (0.5ns)
        *-bank:1
             description: DDR4 [empty]
             product: NO DIMM
             vendor: NO DIMM
             physical id: 1
             serial: [REMOVED]
             slot: DIMM_P0_A1
             width: 64 bits
        *-bank:2
             description: DIMM DDR4 2133 MHz (0.5 ns)
             product: M393A4K40BB0-CPB
             vendor: Samsung
             physical id: 2
             serial: [REMOVED]
             slot: DIMM_P0_B0
             size: 32GiB
             width: 64 bits
             clock: 2133MHz (0.5ns)
        *-bank:3
             description: DDR4 [empty]
             product: NO DIMM
             vendor: NO DIMM
             physical id: 3
             serial: [REMOVED]
             slot: DIMM_P0_B1
             width: 64 bits
             ...
     *-cpu:1
          description: CPU
          product: ARM (CN88xx)
          vendor: www.cavium.com
          physical id: 3f
          bus info: cpu@1
          version: 2.0
          serial: [REMOVED]
          slot: Socket
          size: 2GHz
          capacity: 2GHz
          clock: 156MHz
          capabilities: lm
          configuration: cores=48 enabledcores=48
          ...
```

**Comment by martin-frbg** [comment]
So some quite big and special hardware - I'll see if I can add some more verbose error output to the develop branch tonight. (If one looks around line 2100 of memory.c , there is only minimal perror output to track a mbind failure, and that is not even in the default NO_WARMUP=0 branch of the rather involved code there. The alloc_mmap_free at line 2042 could certainly do with a bit
more feedback but I suspect the error code here is going to be EINVAL, not much use on its own
(though perhaps release->address is NULL there).

**Comment by brada4** [comment]
There is another place.
https://github.com/xianyi/OpenBLAS/blob/ce3651516f12079f3ca2418aa85b9ad571c3a391/common_arm64.h#L127

**Comment by martin-frbg** [comment]
That "other place" just defines BUFFER_SIZE - in the unlikely case that this is set to a wrong value, we can play with it once we know if and why either mmap or munmap is unhappy.

**Comment by brada4** [comment]
It is hard to understand constants there, aarch64 supports same page sizes as amd64 in default kernels, but one can try 16k or 64k basic pages, then all assumptions in that file are blown away. 4MB pages assumed there do not exist in real hardware , checking qemu will not relate to real performance either

**Comment by martin-frbg** [comment]
At least that kind of error message was not observed on consumer hardware (lots of phones with ARMV8 hardware), and I do not think ashwinyes developed the thunderx support without access to actual hardware. Anyway without detailed error reporting from the relevant functions we can imagine possible causes forever without getting anywhere.

**Comment by martin-frbg** [comment]
The patch to provide more information in the error case is now merged, but you need to check out the current develop branch to get it. One possible cause of mmap/unmap errors seems to be running out of available mappings (/proc/sys/vm/max_map_count or the vm.max_map_count sysctl), which I guess would depend on what else is running on your server.

**Comment by ammarik** [comment]
Hello. I tried to run it with your patch and here is the output:
```
11.000000 -9.000000 5.000000 -9.000000 21.000000 -1.000000 5.000000 -1.000000 3.000000 
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff86c68000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff7faf3000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff7a50b000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff77c3a000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff75dcc000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff70984000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff6b831000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff685e1000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff6dac1000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff60ef4000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff5e63d000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff66103000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff5981c000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff570c6000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff527f2000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff4f678000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff4cfe5000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff4a522000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff43589000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff47e64000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff460c3000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff3ef17000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff40576000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff36025000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff391c3000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff30eba000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff2e509000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff33fba000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff2c36c000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff27f66000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff2a0bd000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff23e19000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff26053000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff214b5000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff1ca32000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff00594000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff1045d000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff13253000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff07401000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff09401000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3ff0bea1000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3fed4be3000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3fef8dcf000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3fed2321000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3fecbb11000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3fefdbd1000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3feedeb3000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3feef3bc000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3fee1513000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3feeb381000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3fedccc3000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3fefbe03000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3fee2d3e000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3fef1a5e000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3fee7e2b000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3fee5788000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3fed9f7f000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3fec9b74000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3fec037c000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3fec5d69000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3fec7b11000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3feba4eb000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3feb7b55000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3feb6403000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3feb4434000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3feb22f8000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3feb026b000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3feae1aa000
OpenBLAS : munmap failed:: Invalid argument
error code=22,	release->address=3febddca000
```

**Comment by martin-frbg** [comment]
Thank you. Unfortunately EINVAL just tells that there is "something wrong" with the arguments passed to munmap, which are just the address and the length (the BUFFER_SIZE brada4 pointed to, but that value must have been used successfully in the preceding mmap as there was no corresponding error from mmap). As release->address stores the memory pointer returned by
the corresponding mmap, I do not see how anything could have gone wrong there either (unless
the code manages to call the munmap twice for the same address, which obviously should not happen). (And the manpage even states that "it is not an error if the indicated range does not contain any mapped pages", suggesting that a double munmap should be harmless).
So I still think these messages are harmless, but I still have no idea what causes them (and why only at munmap time, and only on your system)... would probably need to print out successful mmap/munmap invocations  as well to make sense of this.

**Comment by brada4** [comment]
if @ammarik could try to play with those parameters, like make it 2MB etc to see if it starts working. I have just android, which does not get respective error.

**Comment by martin-frbg** [comment]
If the value of the BUFFER_SIZE constant was unacceptable, the original mmap should have failed with EINVAL already. And as unmap gets called with the actual start address of the region as returned by mmap rather than the one we asked for, any realignment done by mmap or the kernel should be accounted for as well. (And running out of mappings would have raised ENOMEM, so we can also exclude that possibility.)
Edited to add: even if divisibility by page size was only important on unmap, I believe the 16MB BUFFER_SIZE declared in common_arm64.h should be perfectly compatible with page sizes of 4k, 16k and even 64k - as should be the 20MB choosen for CortexA57. And at least on x86_64 the map/unmap still works with BUFFER_SIZES that are not multiples of its 4k pagesize.

**Comment by ammarik** [comment]
Hello. Thank you for trying to help me. I tried to run the example with various values of BUFFER_SIZE and PAGESIZE, but it resulting either by same output as above or by Segmentation fault. Any other suggestions how to solve this issue?

**Comment by martin-frbg** [comment]
If you happen to have valgrind on that box, you could try and see if that generates any more verbose complaints. Unfortunately I do not have access to a Cavium server, and know very little about ThunderX (except to try and keep my hands off the kernels that @ashwinyes maintains :-) )

**Comment by ashwinyes** [comment]
This is a Cavium ThunderX board. There is nothing special in OpenBLAS that should cause this error.

@ammarik Are you using any special Linux Kernel on this device? 

Does map/unmap work outside of OpenBLAS ?

**Comment by brada4** [comment]
> Does map/unmap work outside of OpenBLAS ?

Its like mmap, memset, munmap , print ret code

Actually centos default aarch64 says supporting thunderx as one of four boards...

**Comment by jfikar** [comment]
I'm just playing with Raspberry Pi 4 in aarch64 mode using latest Debian Buster and I can run test_cblas_dgemm.c without problem. I'm using libopenblas-dev:arm64 version 0.3.5+ds-3.

**Comment by brada4** [comment]
Also worth a try with CentOS aarch64:
https://fedoraproject.org/wiki/EPEL

**Comment by iarspider** [comment]
Hi! We can't use EPEL due to a strict policy of "no 3rd party repositories" - OpenBLAS will be used by code that runs on LCG (LHC Computring Grid).

**Comment by brada4** [comment]
Question is if it works, since we dont get your build logs, at least those are public, and if they do you can build off their RPM spec ans keep in your repo.
Not sure what is first and second party there, centos and fedora are on redhats payroll often.

**Comment by ammarik** [comment]
I tried whether map/unmap works outside of OpenBLAS and it works without any issues, I tried example from [mmap wikipedia page](https://en.wikipedia.org/wiki/Mmap).  Here are build logs:

[blas-0.3.6.openblas-configure.log](https://github.com/xianyi/OpenBLAS/files/3533787/blas-0.3.6.openblas-configure.log)
[blas-0.3.6.openblas-build.log](https://github.com/xianyi/OpenBLAS/files/3533783/blas-0.3.6.openblas-build.log)
[blas-0.3.6.openblas-install.log](https://github.com/xianyi/OpenBLAS/files/3533789/blas-0.3.6.openblas-install.log)

**Comment by brada4** [comment]
Please build with `make` like fedora epel rpmbuild does. It is better at logging. Thanks. 
Really reuse their spec file, there is some porting and repeatability work put in there, no need to reinvent it all.

**Comment by ammarik** [comment]
I've built it as you said, as fedora epel rpmbuild does and it works now without errors. Thank you!

**Comment by brada4** [comment]
Did you try 0.3.7 or their default 0.3.3?

**Comment by ammarik** [comment]
I tried 0.3.7.

**Comment by brada4** [comment]
Good to know. Could you find anything different in their spec vs your build?
https://src.fedoraproject.org/rpms/openblas/blob/master/f/openblas.spec
(That 0.3.7 patch looks worth integrating btw)
