### ISSUE TITLE
Building OpenBLAS with desired lapack implementation

### ISSUE THREAD

**Issue by notoriou1pig** [xianyi/OpenBLAS#2209]
Hi,

I wondering if I can build OpenBLAS with another lapack implementation.
Is there an option in the Makefile for that. I saw OpenBLAS package for fedora doing something like that but by tweaking the Makefile.

Thanks in advance,
notoriou1pig

**Comment by isuruf** [comment]
You can build just the `BLAS` and `CBLAS` parts of `OpenBLAS` and let your desired lapack implementation use it. For eg: reference lapack implementation can use any BLAS library.

**Comment by martin-frbg** [comment]
This would be `NO_LAPACK=1` and/or `ONLY_CBLAS=1` (see Makefile.rule, the apparent redundancy in the options probably comes from the early GotoBLAS days)

**Comment by martin-frbg** [comment]
Just out of curiosity, which LAPACK implementation do you have in mind ?

**Comment by notoriou1pig** [comment]
Hi isuruf and martin-frbg,
thanks for the quick replies.

Do you think the best choice is to build OpenBLAS with no LAPACK support and then build LAPACK with the desired BLAS implementation ?
Then, should I add libblas.so and libcblas.so manually ?
```
$ ln -s libopenblas.so libblas.so
$ ln -s libopenblas.so libcblas.so
```

For your information, I am working on the buildroot project (https://buildroot.org/).
The user is free to choose between LAPACK and CLAPACK implementation. I wish I can also add BLAS implementation like OpenBLAS. I will add ATLAS also if I can.

Regars,
notoriou1pig

**Comment by martin-frbg** [comment]
Sounds vaguely similar to what the Debian folks do with their "alternatives" concept, perhaps you can  borrow some tricks from their patches to the stock OpenBLAS Makefiles ?
