### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by andrewshyichuk** [xianyi/OpenBLAS#2220]
OpenBLAS make apparantly uses many kewords, which are poorly documented. 
For instance, make NUM_THREADS=64 USE_OPENMP=1 USE_THREAD=1 PREFIX=...

Is there a full list of what make can accept?

Thank you. 
Andrew

**Comment by martin-frbg** [comment]
Please see Makefile.rule

**Comment by andrewshyichuk** [comment]
Many thanks. Today I learned.

**Comment by martin-frbg** [comment]
It may be a bit unusual to document it this way, but this is how it was already done in the original GotoBLAS - and it is even mentioned in the "GotoBLAS_02QuickInstall.txt" document that is retained from that time.
