### ISSUE TITLE
Multithread complex dot product

### ISSUE THREAD

**Issue by antoine-levitt** [xianyi/OpenBLAS#2221]
On my machine (linux x86_64), `zdotc` is not multithreaded. `ddot` is, though.

**Comment by martin-frbg** [comment]
The dot functions are a bit special as they are not multithreaded at the interface level like most everything else - if I remember correctly, the opinion of the earlier developers was that these were bound by the system I/O bandwidth limit already. A select few machines do have multithreaded ddot kernels - for x86_64, I stole the idea and implementation from the arm64 ThunderX kernels in #1491 to satisfy another Julia request. Not sure if zdot(c) would be just as easy...

**Comment by antoine-levitt** [comment]
> if I remember correctly, the opinion of the earlier developers was that these were bound by the system I/O bandwidth limit already

At least on my laptop that is not the case - I see a definite speedup in ddot.

**Comment by martin-frbg** [comment]
PR #2222 now but may need some tuning - for now it is just a copypasta of the ARM server cpu code including its n=10000 threshold.

**Comment by brada4** [comment]
Can you give some numbers, like CPU trade name? How big is input? Is it cache-line aligned (like starts on fresh malloc)? Does it help to double processing block in source file?
One cache line size, 4 values, should get fetched from memory to CPU, then 8 FLOPS done on them (that fits in 1-2 FMA instrs), then hopefully next batch is pre-fetched at once. It is certainly not FPU speed at fault, but something else micro-architectural on the way.

**Comment by antoine-levitt** [comment]
I'm confused by most of your post, but here are some numbers. This is with julia 1.1, on Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz

```
julia> BLAS.openblas_get_config()
"USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=16"
```

```julia
using BenchmarkTools

for N in (5_000, 20_000, 100_000)
    for i in (1,2,4)
        BLAS.set_num_threads(i)

        aa = randn(N)
        bb = randn(N)
        @btime dot($aa,$bb)
    end
end
```
```
  815.453 ns (0 allocations: 0 bytes)
  816.198 ns (0 allocations: 0 bytes)
  810.475 ns (0 allocations: 0 bytes)
  4.070 μs (0 allocations: 0 bytes)
  2.408 μs (0 allocations: 0 bytes)
  2.349 μs (0 allocations: 0 bytes)
  24.012 μs (0 allocations: 0 bytes)
  13.054 μs (0 allocations: 0 bytes)
  8.458 μs (0 allocations: 0 bytes)
```

**Comment by brada4** [comment]
Thanks, so it is pretty standard desktop CPU. I was a bit afraid of those high-end with numa in the cartridge and many memory controllers.

**Comment by martin-frbg** [comment]
Multithreading (at the kernel level, as already done on ARM server cpus) was added in #2222
