### ISSUE TITLE
OPENBLAS COMPILING

### ISSUE THREAD

**Issue by wesjane8** [xianyi/OpenBLAS#2259]
Hello!
I am trying to install the KALDI toolkit. I must install the OpenBLAS.

While compiling the OpenBLAS i get this error : 

matcopy_k_cnc.o zomatcopy_k_rnc.o zomatcopy_k_ctc.o zomatcopy_k_rtc.o zimatcopy_k_cn.o
zimatcopy_k_rn.o zimatcopy_k_ct.o zimatcopy_k_rt.o zimatcopy_k_cnc.o zimatcopy_k_rnc.o
zimatcopy_k_ctc.o zimatcopy_k_rtc.o zgeadd_k.o zneg_tcopy.o zlaswp_ncopy.o lsame.o scabs1.o
dcabs1.o cpuid.o
ar:  the modifier "u" is ignored since "D" is the default (consult "U")
ar: strmm_kernel_LN.o: No such file or directory
../Makefile.tail:40: recipe for target 'libs' failed
make[1]: *** [libs] Error 1
make[1]: Leaving directory '/home/user/Bureau/kaldi/tools/OpenBLAS/kernel'
Makefile:145: recipe for target 'libs' failed
make: *** [libs] Error 1
make[1]: Leaving directory '/home/user/Bureau/kaldi/tools/OpenBLAS'

I see that to solve this problem I should run: make clean , make TARGET=Haswell and make BINARY=32 next build. I do these steps, and also with make BINARY=64. But in all cases, i cannot install the OpenBLAS. I get the same error.

MAY YOU PLEASE HELP ME TO SOLVE THIS PROBLEM. THANK YOU

**Comment by martin-frbg** [comment]
Which version of OpenBLAS, what cpu ? Did you try with target "HASWELL" (all capital letters) ?

**Comment by wesjane8** [comment]
I tried with capital letters i get the same error
** version  of OpenBLAS
libopenblas_haswell-r0.3.5.a
** lscpu (cpu info)
Architecture:          i686
Mode(s) opératoire(s) des processeurs :32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) par cœur : 2
Cœur(s) par socket : 2
Socket(s):             1
Identifiant constructeur :GenuineIntel
Famille de processeur :6
Modèle :             142
Model name:            Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
Révision :           9
Vitesse du processeur en MHz :400.000
CPU max MHz:           2601.0000
CPU min MHz:           400.0000
BogoMIPS:              5424.49
Virtualisation :      VT-x
Cache L1d :           32K
Cache L1i :           32K
Cache L2 :            256K
Cache L3 :            3072K

**Comment by martin-frbg** [comment]
Strange, 0.3.5 should compile without problems on 7200U (Kaby Lake should be automatically detected as Haswell) in either 32 or 64 bit mode. (Using either just `make` or `make BINARY=32` - I tried it on my i7-7200U just now to be sure it works. The only difference is that I am running a 64bit Linux, but this should not matter).

**Comment by brada4** [comment]
You must run `make clean` between build attempts. Probably worth trying 0.3.7, though haswell was not broken with 0.3.5
For 32bit system on your CPU - highest possible TARGET will be NEHALEM as AVX and better extensions are not reachable from 32bit OS
Please record the build log with `script` command, the error of missing file is preceded long ago (by means of log) with some error building that file.

**Comment by brada4** [comment]
I want to see your build log
```

[build@localhost openblas]$ make TARGET=SANDYBRIDGE BINARY=64
....
cc -O2 -DMAX_STACK_ALLOC=2048 -Wall -m32 -DF_INTERFACE_GFORT -fPIC -DNO_AVX -DNO_AVX512 -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DMAX_PARALLEL_NUMBER=1 -DVERSION=\"0.3.8.dev\" -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  -shared -o ../libopenblas_sandybridgep-r0.3.8.dev.so \
	-Wl,--whole-archive ../libopenblas_sandybridgep-r0.3.8.dev.a -Wl,--no-whole-archive \
	-Wl,-soname,libopenblas.so.0 -lm -lpthread -lgfortran -lm -lpthread -lgfortran
cc -O2 -DMAX_STACK_ALLOC=2048 -Wall -m32 -DF_INTERFACE_GFORT -fPIC -DNO_AVX -DNO_AVX512 -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DMAX_PARALLEL_NUMBER=1 -DVERSION=\"0.3.8.dev\" -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  -w -o linktest linktest.c ../libopenblas_sandybridgep-r0.3.8.dev.so -L/usr/lib/gcc/i686-redhat-linux/4.4.7 -L/usr/lib/gcc/i686-redhat-linux/4.4.7 -L/usr/lib/gcc/i686-redhat-linux/4.4.7/../../..  -lgfortran -lm -lgfortran -lm -lc   && echo OK.
OK.
rm -f linktest
make[1]: Leaving directory `/home/build/openblas/exports'

 OpenBLAS build complete. (BLAS CBLAS LAPACK LAPACKE)

  OS               ... Linux             
  Architecture     ... x86               
  BINARY           ... 32bit                 
  C compiler       ... GCC  (command line : cc)
  Fortran compiler ... GFORTRAN  (command line : gfortran)
  Library Name     ... libopenblas_sandybridgep-r0.3.8.dev.a (Multi threaded; Max num-threads is 4)

[build@localhost openblas]$ lscpu
Architecture:          i686
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             4
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 42
Model name:            Intel Xeon E312xx (Sandy Bridge)
Stepping:              1
CPU MHz:               2495.360
BogoMIPS:              4990.72
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             64K
L1i cache:             64K
L2 cache:              512K
L3 cache:              16384K

```

Note that excess flags are striped out - AVX and 64bit code is not generated.

**Comment by martin-frbg** [comment]
Yes, can you please first run `make clean`, and then run `make >logfile.txt 2>&1` (which should redirect all compiler messages to a file), and upload the logfile.txt here ?
