### ISSUE TITLE
Compilation error with GCC 10

### ISSUE THREAD

**Issue by marxin** [xianyi/OpenBLAS#2262]
Hi.

Using latest GCC snapstot, I see the following error:
```
gfortran sgbsvx.f -c 
sgbsvx.f:585:48:

  563 |      $                       AFB( MAX( 1, KL+KU+2-INFO ), 1 ), LDAFB,
      |                             2                   
......
  585 |       RPVGRW = SLANTB( 'M', 'U', 'N', N, KL+KU, AFB, LDAFB, WORK )
      |                                                1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-2)
```

It comes from `netlib` and one needs to use `-std=legacy` to compile the file:
```
marxin@marxinbox:/tmp> gfortran sgbsvx.f -c  -std=legacy
sgbsvx.f:585:48:

  563 |      $                       AFB( MAX( 1, KL+KU+2-INFO ), 1 ), LDAFB,
      |                             2                   
......
  585 |       RPVGRW = SLANTB( 'M', 'U', 'N', N, KL+KU, AFB, LDAFB, WORK )
      |                                                1
Warning: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-2)
```

**Comment by martin-frbg** [comment]
As this is "netlib" it should probably be reported to https://github.com/Reference-LAPACK/lapack (and I wonder how many other old codes this will break by default - would not surprise me if they had to relent on that before the official release). From http://gcc.gnu.org/gcc-10/changes.html this change appears to be deliberate, and they even created a new option -fallow-argument-mismatch to restore the previous behaviour.

**Comment by marxin** [comment]
> As this is "netlib" it should probably be reported to https://github.com/Reference-LAPACK/lapack (and I wonder how many other old codes this will break by default - would not surprise me if they had to relent on that before the official release).

I'll do it.

> From http://gcc.gnu.org/gcc-10/changes.html this change appears to be deliberate, and they even created a new option -fallow-argument-mismatch to restore the previous behaviour.

Ok, we have a new option. I bet we can optimize better when not using the legacy option.

**Comment by marxin** [comment]
Move to: https://github.com/Reference-LAPACK/lapack/issues/353
