### ISSUE TITLE
Potential issue in single precision subroutine(s)

### ISSUE THREAD

**Issue by Ionizing** [xianyi/OpenBLAS#2264]
I just found that there is precision issue when using OpenBLAS with fortran, here is the reproducing procedure:

```fortran
program main
  implicit none
  integer, parameter :: M = 1000
  real(4) :: A(M, M), B(M, M), C1(M, M)

  integer :: i, j

  call srand(0)
  do i=1,M
    do j=1,M
      A(j, i) = rand()
    enddo
  enddo

  call srand(100)
  do i=1,M
    do j=1,M
      B(j, i) = rand()
    enddo
  enddo

  C1 = matmul(A, B)

  do i=1,M
    do j=1,M
      print *, C1(j, i)
    enddo
  enddo
end program main
```

and use the `Makefile`
```makefile
FC=gfortran

all: blas.out native.out
	time ./blas.out > blas.log
	time ./native.out > native.log
	diff native.log blas.log > diff

blas.out: main.F90
	$(FC) -o $@ $< $(HOME)/usr/lib64/libopenblas.a -fexternal-blas

native.out: main.F90
	$(FC) -o $@ $<

clean:
	rm -f *.log *.out
```

When I use small size of matrix such as `M=100` and ended up with an empty `diff` file. However, when `M` is larger, for example, `M=500`, there are differences between `native.log` and `blas.log` .

<img width="237" alt="image" src="https://user-images.githubusercontent.com/17506747/65370861-1196af00-dc90-11e9-8ae9-8d9022bc445d.png">

When I changed the matrix type from `real(4)` into `real(8)`, `diff` shows nothing.
I am still not sure whether this issue is associated with `gfortran` or `OpenBLAS`.

Here is my environment:
> Linux node100 3.10.0-693.el7.x86_64
> Processor name    : Intel(R) Xeon(R)  E5-2620 v2
> gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)
> OpenBLAS version: libopenblas-r0.3.3

**Comment by Ionizing** [comment]
Issue reproduced on my Mac.

> macOS 10.13 High Sierra
> openblas: 0.3.6_1
> gcc version 9.1.0 (Homebrew GCC 9.1.0)
> cpu: intel i5 8259u

**Comment by brada4** [comment]
Precision of single float is about 7 decimal digits. So you get one last bit lost because of order of computation. Id bet gcc will fluctuate between O2 and O0 too
Question regarding measurements - is GCC algorithm result ever different from NetLib BLAS result?

**Comment by brada4** [comment]
I answer my own question - results differ at the same degree between gcc and reference LAPACK 3.8.0, you are reporting on range of single precision float. You know that 0.3 and 07 do not represent correctly?

**Comment by martin-frbg** [comment]
Differences in error accumulation from different order of individual summations and multiplications would be my guess as well. (Results vary between OpenBLAS' SGEMM kernels for different CPUs as well, some hardware provides FMA instructions while others do not and none of the implementations is "bad" in the context of the tests from the netlib reference implementation of LAPACK). If you need more digits of precision, use doubles (real*8 in the fortran context), if you want to loose faith in common BLAS read https://sinews.siam.org/Details-Page/reproducible-blas-make-addition-associative-again

**Comment by brada4** [comment]
You get like log2(flops) bits lost when operating with floating point. Different order of computation will yield different results. There is sympy to get exact ones... not blas, nor GCC....
NetLib BLAS with -O0 is sort of reference, but even GCC has different algo there....

**Comment by Ionizing** [comment]
So this is not the issue of `OpenBLAS`, but the issue of how precise the single precision can be. The float number precision error will accumulate as the scale of data grows, and this explains why those two results do not vary when `M` is small. If more precision digits is needed, just choose double precision, and this **may** cause less error accumulation, right ?

**Comment by martin-frbg** [comment]
Yes. There will almost always be rounding or truncation, as few decimal numbers have a finite representation in binary at all,  so what looks like a nice exact number like 123.4 in decimal will
already be much less exact when constrained to the 24 bits of mantissa a "single precision" float
provides - even before it gets involved in any addition or multiplication. By choosing double precision, you get a much bigger range of representable numbers so the inaccuracy will "usually"
be much smaller (although there are some pathological cases). See the classic [Perils of Floating Point](http://www.lahey.com/float.htm) or the collection of [Pathological floating point problems](https://rosettacode.org/wiki/Pathological_floating_point_problems).
 There were plans to implement quadruple-precision support in the original GotoBLAS that OpenBLAS is based on, but unfortunately this never went beyond creating a basic framework of conditionals in the headers and makefiles.

**Comment by Ionizing** [comment]
I got your point, thank you very much.
