### ISSUE TITLE
POWER9 Build failure on AT12 (GCC 8.3)

### ISSUE THREAD

**Issue by pmur** [xianyi/OpenBLAS#2268]
When building from 6b830793686c06fed3f517ca1e95854891bbed6f on the develop branch, I encounter the following:

##### System information (version)
POWER9 on Ubuntu 18.04.3 LTS with IBM AT 12 (GCC 8.3)
 
make CC=/opt/at12.0/bin/gcc FC=/opt/at12.0/bin/gfortran -j20

##### Detailed description
A number of errors of the form:
```
/home/murp/src/OpenBLAS/interface/zdot.c:135: undefined reference to `cdotc_k'
/opt/at12.0/lib/gcc/powerpc64le-linux-gnu/8.3.1/../../../../powerpc64le-linux-gnu/bin/ld: /home/murp/src/OpenBLAS/interface/zdot.c:135: undefined reference to `cdotc_k'
/opt/at12.0/lib/gcc/powerpc64le-linux-gnu/8.3.1/../../../../powerpc64le-linux-gnu/bin/ld: ../libopenblas_power9p-r0.3.8.dev.a(cdotu.o): in function `cdotu_':
/home/murp/src/OpenBLAS/interface/zdot.c:133: undefined reference to `cdotu_k'
/opt/at12.0/lib/gcc/powerpc64le-linux-gnu/8.3.1/../../../../powerpc64le-linux-gnu/bin/ld: /home/murp/src/OpenBLAS/interface/zdot.c:133: undefined reference to `cdotu_k'
```

##### Steps to reproduce

1. Install AT 12, run make command above.

The following hack seemed to move the build along:

```
diff --git a/kernel/power/cdot_power9.S b/kernel/power/cdot_power9.S
index 01d194c0..c4c08ce1 100644
--- a/kernel/power/cdot_power9.S
+++ b/kernel/power/cdot_power9.S
@@ -1,8 +1,11 @@
+#define ASSEMBLER
+#include "common.h"
        .file   "cdot.c"
        .abiversion 2
        .section        ".text"
        .align 2
        .p2align 4,,15
+#define cdot_k REALNAME
        .globl cdot_k
        .type   cdot_k, @function
 cdot_k:
```

**Comment by martin-frbg** [comment]
Indeed. Sorry, i must have forgotten to edit that section when I rejoined the gcc intermediates for cdotc and cdot (cdotu). In the related edits from  #2263 I simply replaced that section with the PROLOGUE macro (from common_power.h, pulled in by common.h)
