### ISSUE TITLE
Win32 binary version for windows

### ISSUE THREAD

**Issue by Nelson-numerical-software** [xianyi/OpenBLAS#2278]
On main page, 
```
Binary Packages
We provide official binary packages for the following platform:

Windows x86/x86_64
You can download them from file hosting on sourceforge.net.
```

Where is the x86 version ?
Only x64 version is available

Please provide it

Thanks

**Comment by martin-frbg** [comment]
Could you check if the binary I put in https://github.com/xianyi/OpenBLAS/issues/805#issuecomment-515214152 works ? (It is not the latest version, but I will see if I can update it later)

**Comment by Nelson-numerical-software** [comment]
Hi, I would prefer to have latest version.
The easier could be to expose artefact in appveyor

**Comment by brada4** [comment]
Very basic build command for a linux VM (you dont need FPCSR parameter)
https://github.com/xianyi/OpenBLAS/issues/1237#issuecomment-315371243
PS you need fedora or ubuntu or rhel/centos for rady to use mingw32 cross-compiler
PPS probably play with autocomplete like bash-completion to get exact x86- gcc, gfortran and binutils
PPPS would be worth adding to faq, how those "binary releases" get built....

**Comment by martin-frbg** [comment]
@Nelson-numerical-software So does this one work for you ?
[OpenBLAS-0.3.7-32bit.zip](https://github.com/xianyi/OpenBLAS/files/3699619/OpenBLAS-0.3.7-32bit.zip)

**Comment by brada4** [comment]
Gfort deps?

**Comment by martin-frbg** [comment]
One of the reasons why I am asking. I believe I did everything the same as for the 64bit build where there were no complaints. I think there is also an old issue ticket about requiring ~~cdecl~~ stdcall on 32bit.

**Comment by Nelson-numerical-software** [comment]
> @Nelson-numerical-software So does this one work for you ?
> [OpenBLAS-0.3.7-32bit.zip](https://github.com/xianyi/OpenBLAS/files/3699619/OpenBLAS-0.3.7-32bit.zip)

Thanks, it works without some others dependencies
![image](https://user-images.githubusercontent.com/23081266/66424323-b5f94f00-ea0d-11e9-8664-9f7587df5908.png)
But x64 version requires some dependencies about gfortran.
![image](https://user-images.githubusercontent.com/23081266/66425139-3ec4ba80-ea0f-11e9-9364-74ac96dda73c.png)

It will be great to have same dependencies on win32 & x64 platforms (for packaging)

**Comment by brada4** [comment]
which functions you do import from BLAS? 
Fortran part (LAPACK and LAPACKE depending on it) needs fortran redist. BLAS (like GEMM,SCAL etc) can do without.

**Comment by brada4** [comment]
(or point the finger at respective source file that does linear algebra)
