### ISSUE TITLE
make: *** [netlib] Error 2

### ISSUE THREAD

**Issue by rickwierenga** [xianyi/OpenBLAS#2284]
I'm trying to install OpenBLAS like so:

```sh
git clone https://github.com/xianyi/OpenBLAS
cd OpenBLAS
make BINARY=64 CC=mips64el-unknown-linux-gnu-gcc FC=mips64el-unknown-linux-gnu-gfortran HOSTCC=gcc TARGET=LOONGSON3A
```

or:
```sh
make FC=gfortran -j4
```

Both yield the following error:
```
Makefile:229: recipe for target 'netlib' failed
make: *** [netlib] Error 2
```

I'm on Ubuntu 18.04.3 LTS.

I'm installing this software as a dependency and I'm not sure about what the error means. Please let me know if you need additional information. Thanks in advance.

**Comment by rickwierenga** [comment]
Apparently simply using `make` fixed it for me.

**Comment by martin-frbg** [comment]
Depends on what you are trying to do - the full set of options (CC=... FC=... HOSTCC=...) is used when you are building on a different hardware and cross-compiling for the actual system you want to use OpenBLAS on. Just using `make` will let the build system figure out what computer it is running on and which compilers to use for building on and for that same system.
So now you will have built OpenBLAS for the system that runs Ubuntu - is that the MIPS system with the Loongson processor ?

**Comment by rickwierenga** [comment]
I'm sorry but I am not entirely sure what you mean by "the MIPS system with the Loongson processor". I have never used this software before.

**Comment by martin-frbg** [comment]
The question is simply if you are speaking (writing) of one single system on which you build and use OpenBLAS, or if there are two - one of which we only know it runs Ubuntu, and another that is MIPS64 architecture and has a Loongson3A processor. (Or was the `make` command line from your first build attempt simply copied from somewhere, and all you actually want to do is build and
run OpenBLAS on a "normal" Intel or AMD desktop/laptop  ?)

**Comment by martin-frbg** [comment]
To word it differently - the `make CC=mips64el-unknown-linux-gnu-gcc ... TARGET=LOONGSON3A` 
that you used at first says you want to use a special compiler that produces binaries for MIPS64, and you want OpenBLAS to include optimized code for a Loongson3A cpu. MIPS64 is a special type of processor architecture (kind of like ARM for smartphones) that is now mostly seen in network routers and embedded systems. The Loongson3A in particular is a fairly exotic (from a European standpoint) Chinese cpu. So either you want to do something unusual, or you stumbled on very specific instructions for an unusual case.

**Comment by rickwierenga** [comment]
I see. I am installing OpenBLAS as a dependency for another project. I just copied that line from the README of this project but I did not know the specifics of it. Thank you for clarifying it.

As for the platform, I am using a GCP Compute Engine VPS.

**Comment by martin-frbg** [comment]
The underlying hardware of the Google Cloud is most likely some Intel x86_64, so you should be fine with the successful build. I guess the cross-compilation example in the README could be updated to reflect a more recent mainstream scenario like cross-building for ARMV8 - but I do note that the preceding section labeled "normal compile" must have been too boring for you somehow :smile:

**Comment by rickwierenga** [comment]
Yes you are completely right. I tried the 'install dependency' section of the main project first and since that gave me the error I tried to copy installation code from the README of this project. That gave me the exact same error so I was sure there would be something weird going on and I couldn't figure out what is was. Guess I should read more carefully in the future...
