### ISSUE TITLE
Whether OpenBLAS supports 鲲鹏920

### ISSUE THREAD

**Issue by mmx110** [xianyi/OpenBLAS#2285]
hi， I compilered OpenBlas using soure code in TaiShan 200 service. I get some error as follow:
copy.c:1:0: error: unknown value ‘armv8.2-a’ for -march
 /*********************************************************************/
 ^
scal.c:1:0: error: unknown value ‘tsv110’ for -mtune
copy.c:1:0: error: unknown value ‘tsv110’ for -mtune
make[1]: *** [saxpy.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [sswap.o] Error 1
dot.c:1:0: error: unknown value ‘armv8.2-a’ for -march
 /*********************************************************************/
 ^
dot.c:1:0: error: unknown value ‘tsv110’ for -mtune
make[1]: *** [sscal.o] Error 1
sdsdot.c:1:0: error: unknown value ‘armv8.2-a’ for -march
 /*********************************************************************/
 ^
make[1]: sdsdot.c:1:0: error: unknown value ‘tsv110’ for -mtune
seem not support armv8.2 architecture?

**Comment by martin-frbg** [comment]
The "unknown value" are error messages from your compiler, apparently it is too old to support these options. (Or if you are cross-compiling, you called the wrong compiler). If you cannot install a newer
gcc (I think you need gcc 9.1 for tsv110 support), you can edit the options in Makefile.arm64

**Comment by brada4** [comment]
Your compiler does not support optimisations for particular CPU.
You can choose some from `kernel/arm64/KERNEL.*`, like A72/A73

**Comment by mmx110** [comment]
thanks for your reply ! I get some information from your reply, I will try.

**Comment by mmx110** [comment]
thanks for your reply ! I get some information from your reply, I will try.

**Comment by brada4** [comment]
Also clang from 2019 can help, just that no fortran compiler there and no lapack will be built, but you can wrap it with less optimized gfortran build too.
