### ISSUE TITLE
ubuntu openblas-0.3.6 make error

### ISSUE THREAD

**Issue by ghost** [xianyi/OpenBLAS#2287]
tar -xvf OpenBLAS-0.3.6.tar.gz
cd OpenBLAS-0.3.6
make

then
`./sblat1: error while loading shared libraries: libgfortran.so.3: cannot open shared object file: No such file or directory
Makefile:8: recipe for target 'level1' failed
make[1]: *** [level1] Error 127
make[1]: *** 正在等待未完成的任务....`

`make[1]: Leaving directory '/path/OpenBLAS-0.3.6/test'
Makefile:123: recipe for target 'tests' failed
make: *** [tests] Error 2
`

**Comment by martin-frbg** [comment]
You will probably need to provide the path to the fortran runtime library (the libgfortran.so.3),e.g. by
setting LD_LIBRARY_PATH so that the test programs can find it.

**Comment by ghost** [comment]
> You will probably need to provide the path to the fortran runtime library (the libgfortran.so.3),e.g. by
> setting LD_LIBRARY_PATH so that the test programs can find it.

`/usr/bin/ld: 找不到 -lgfortran`
but my gcc/lib/gcc/x86_64-unknown-linux-gnu/5.4.0  don't have lgfortran.a

**Comment by ghost** [comment]
> LD_LIBRARY_PATH

I had set just

**Comment by martin-frbg** [comment]
Actually you would need a file libgfortran.so (usually a link to libgfortran.so.3). You will probably need to install the "libgfortran3" package from Ubuntu (`sudo apt-get install libgfortran3`)

**Comment by ghost** [comment]
`libgfortran.so -> libgfortran.so.3.0.0`
has in my install_path/gcc/lib64 

 I don't have root

**Comment by martin-frbg** [comment]
Do you have libgfortran.so.3.0.0 (and `libgfortran.so.3 -> libgfortran.so.3.0.0`)  as well ?

**Comment by ghost** [comment]
> Do you have libgfortran.so.3.0.0 (and `libgfortran.so.3 -> libgfortran.so.3.0.0`) as well ?

yes

**Comment by martin-frbg** [comment]
Strange. Do you also have libquadmath.so.0 (that is needed by libgfortran.so.3) ?

**Comment by ghost** [comment]
yes,
 do you know how to 
`An alternative solution is to replace -lgfortran with /usr/lib/libgfortran.so.3` ?
https://stackoverflow.com/questions/10881002/lgfortran-not-found

**Comment by martin-frbg** [comment]
The -lgfortran is in Makefile.system (EXTRALIB += -lgfortran) you could try replacing it there and recompiling.
Are you sure that gcc and gfortran are the same versions ? (gcc --version, gfortran --version)

**Comment by ghost** [comment]
my gfortran is a part of gcc ,5.4.0

> The -lgfortran is in Makefile.system (EXTRALIB += -lgfortran) you could try replacing it there and recompiling.
> Are you sure that gcc and gfortran are the same versions ? (gcc --version, gfortran --version)

my gfortran is a part of gcc ,5.4.0

**Comment by brada4** [comment]
There is no Ubuntu version ever shipped with gcc 5.4.0

Please use gcc+gfortran shipped with your Ubuntu distribution.

**Comment by martin-frbg** [comment]
One of the earlier postings mentioned not having root access on that Ubuntu system, my guess is this is a compiler installed under tianlanli's home directory.

**Comment by brada4** [comment]
Title blames ubuntu, at least unpacked default .deb expected.

**Comment by ghost** [comment]
> Title blames ubuntu, at least unpacked default .deb expected.

I do not blame ubuntu ...

**Comment by ghost** [comment]
> There is no Ubuntu version ever shipped with gcc 5.4.0
> 
> Please use gcc+gfortran shipped with your Ubuntu distribution.



> There is no Ubuntu version ever shipped with gcc 5.4.0
> 
> Please use gcc+gfortran shipped with your Ubuntu distribution.

I install gcc
then
gfortran -V
`使用内建 specs。
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/home/lxr/software/gcc/libexec/gcc/x86_64-unknown-linux-gnu/5.4.0/lto-wrapper
目标：x86_64-unknown-linux-gnu
配置为：../configure --disable-checking --enable-languages=c,c++,fortran --disable-multilib --prefix=/home/lxr/software/gcc --enable-threads=posix
`

**Comment by isuruf** [comment]
If you have set `LD_LIBRARY_PATH` and `LIBRARY_PATH` to where your `libgfortran.so.3` and `libgfortran.so` is, then you won't have this problem.

**Comment by ghost** [comment]
> One of the earlier postings mentioned not having root access on that Ubuntu system, my guess is this is a compiler installed under tianlanli's home directory.

thank you for your reply , my openblas is ok.
I have try much times ,such as copy lib64 to lib ,rewrite Makefile.system and set more PATH to my .bashrc .I am not clear which one makes openblas ok, I will try again in another server.

**Comment by ghost** [comment]
> If you have set `LD_LIBRARY_PATH` and `LIBRARY_PATH` to where your `libgfortran.so.3` and `libgfortran.so` is, then you won't have this problem.

I have set it and I do other works . Maybe you are right

**Comment by brada4** [comment]
If you have gcc libs in system (you usually do) it will be quite hard to get around them.

**Comment by brada4** [comment]
In short:
`dpkg -l | grep gcc`
Now you have version, download respective missing deb files , then treat them with `ar x`, then included content with `tar xf`, it is well known that even minor version differences between gcc and gfortran and their redistributable components cause link time errors.
It would be much easier to bring up similar desktop virtual machine and copy over compiled results for computation...

**Comment by martin-frbg** [comment]
The linker problem with gfortran probably comes from installing the compiler in the home directory, while the default configuration has /usr/local as the install prefix. So gfortran will probably use
rpath=/usr/local/lib  (you can check by running "gfortran -v ftest2.f" in the toplevel OpenBLAS directory - this is what the f_check script uses to determine the compiler and linker options).
Setting LD_LIBRARY_PATH (somewhere in your .profile so you do not have to type it each time you log in) to the directory with the libgfortran.so should be sufficient to solve this, or rebuild gcc
with the "--prefix=" option in the configure command set to the desired location under the home directory.
