### ISSUE TITLE
creating a logo for OpenBLAS

### ISSUE THREAD

**Issue by rgommers** [xianyi/OpenBLAS#2298]
Hi, after quite a bit of searching I failed to find an OpenBLAS logo. Is is correct that that doesn't exist? If so, would you be interested in getting one? I may be able to point a few people who enjoy designing logos this way.

**Comment by martin-frbg** [comment]
Correct as far as I know - there is "only" the mixed-case word mark. Not sure this would be an important asset to have ? (_If_ there is to be one, I guess it would have to be more original than just the name with some pointless green or blue brush stroke attached. I do like the simplicity of the LAPACK logo but do not see how to achieve something similar... maybe a cross of the gonum gopher and hypnotoad would be more appropriate to show what OpenBLAS can do to other projects when we get something wrong...)

**Comment by quickwritereader** [comment]
I would suggest this one done by me.  Still blue brushes but with some meaning.  
P.s Im not good at design.  

![20191031_035943](https://user-images.githubusercontent.com/4885088/67907928-1a35ab80-fb93-11e9-8e3d-3a2831112718.png)

**Comment by quickwritereader** [comment]
About Go mascot I would suggest things related to processors. 

Mr. Proc|fessor. 

![sketch1572483951089](https://user-images.githubusercontent.com/4885088/67910616-d5af0d80-fb9c-11e9-87d4-85858612f346.png)  
On the black background  it shows this way:  
![20191031_051244](https://user-images.githubusercontent.com/4885088/67910679-1b6bd600-fb9d-11e9-8839-478e4f5636e8.jpg)

**Comment by jmertic** [comment]
Hi!

Just checking which logo the community settled on - looking to add OpenBLAS to the Open Mainframe Landscape ( l.openmainframeproject.org ). We will need the logo in an SVG format, which we can help create if needed.

**Comment by quickwritereader** [comment]
mathjax for Proposed Logo 
`
$$
    {\begin{bmatrix}
    Op \\
    \hline
    BL
    \end{bmatrix}}^{\top}\times 
     {\begin{bmatrix}
    en \\
    \hline
    AS
    \end{bmatrix}}
$$`

 

> For converting mathjax to svg use this site [latex to svg](https://viereck.ch/latex-to-svg/)

One could work on colours and unnecessary spaces  of svg output which looks like this in png.  
![eq](https://user-images.githubusercontent.com/4885088/68163554-34e19900-ff74-11e9-9eda-ac8631775818.png)

**Comment by jmertic** [comment]
Thank you @quickwritereader ! Will let you know once this goes live.

**Comment by martin-frbg** [comment]
@jmertic you will probably want to leave off the dollar signs if you want to run it through the mathjax converter (though it seems market capitalization features rather prominently on your Landscape page) - this is just the LaTeX typesetting command for "start/end of mathematical formula".
This is a bit closer to the PNG posted above 
`{\color[rgb]{0.01,0.63,0.78}\begin{bmatrix} \color[rgb]{0.27,0.66,0.99}Op \\ \hline \color{violet}BL \end{bmatrix}}^{\color[rgb]{0.01,0.63,0.78}\top}\hspace{-1ex}\color[rgb]{0.01,0.63,0.78}\times {\begin{bmatrix} \color[rgb]{0.27,0.66,0.99}en \\ \hline \color{violet}AS \end{bmatrix}}`

[openblas.svg.txt](https://github.com/xianyi/OpenBLAS/files/3824084/openblas.svg.txt) which renders as 
![openblas](https://user-images.githubusercontent.com/6192365/68469086-b9a11100-0219-11ea-9e0e-60ea5cc417c8.png)

(cue potentially endless discussion if we want the characters italicized - the LaTeX default for the math environment - or straight...)

**Comment by jmertic** [comment]
Thanks!

I've added it to the landscape now - check it out at https://landscape.openmainframeproject.org/selected=open-blas

**Comment by quickwritereader** [comment]
I tried to modify with InkSpace. Anyway, I think the logo which is in use is good enough till we get new shiny and professional logo with better concept.
[open-blas_svg.txt](https://github.com/xianyi/OpenBLAS/files/3827331/open-blas_svg.txt)
![open-blas](https://user-images.githubusercontent.com/4885088/68529317-d96a2f00-0316-11ea-9ae2-980e1722e430.png)

**Comment by martin-frbg** [comment]
I've put yesterday's version on the openblas.net page, certainly good enough for the time being.

**Comment by rgommers** [comment]
> I've put yesterday's version on the openblas.net page, certainly good enough for the time being.

great, thanks! 

> I've added it to the landscape now - check it out at https://landscape.openmainframeproject.org/selected=open-blas

Looks interesting. Out of interest, what does that mean? Found the PR that added OpenBLAS and  https://github.com/openmainframeproject/tac/blob/master/process/proposal_process.md#project-acceptance-process, but it doesn't really explain all the good things that will hopefully follow from being an OpenMainframe project:)

**Comment by jmertic** [comment]
> Looks interesting. Out of interest, what does that mean? Found the PR that added OpenBLAS and https://github.com/openmainframeproject/tac/blob/master/process/proposal_process.md#project-acceptance-process, but it doesn't really explain all the good things that will hopefully follow from being an OpenMainframe project:)

Check out this link for more details...

https://www.openmainframeproject.org/projects/supported-projects

Happy to chat about this more if there is of interest.
