### ISSUE TITLE
using large NUM_THREADS for single-threaded openblas

### ISSUE THREAD

**Issue by courage17340** [xianyi/OpenBLAS#2304]
Hi,

I am using single-threaded openblas on armv8 (built with "make TARGET=ARMV8 USE_THREAD=0 USE_LOCKING=1 CC=aarch64-linux-gnu-gcc FC=aarch64-linux-gnu-gfortran HOSTCC=gcc"). In my program, sgemm is called in parallel, and when number of threads exceeds NUM_BUFFERS, error "BLAS : Program is Terminated. Because you tried to allocate too many memory regions." will occur.

Then I'm wondering if I could set NUM_THREADS to a large value (like 10,000) so that NUM_BUFFERS is definitely greater than number of threads. I want to know how much memory is needed per buffer, and is it safe to set a large NUM_THREADS.

**Comment by martin-frbg** [comment]
The permanent cost should be something like 64 bytes per NUM_THREADS (the size of struct memory[] in driver/others/memory.c that keeps track of actual buffer allocations). I imagine making it unnecessarily huge (your 10000) could impact performance through cpu cache trashing so it might make sense to choose something in the same order of magnitude as the number of concurrent threads you actually expect to use (which is probably only a small multiple of the number of cores available)

**Comment by courage17340** [comment]
OK, I will try some different values and then choose a reasonable one. Thank you for your help.

**Comment by brada4** [comment]
Check #1858 for formula. You can put any number you like, but have in mind 80 bytes structures will stretch across pages and consume TLB entries, normally used for data you process. You can patch any value in that file, even single-threaded version does some IPC there.

**Comment by courage17340** [comment]
By the way, is there any method (like catch exceptions or return non-zero error codes) to avoid crashes in the case that buffer is not enough? I found that it would segfault directly.

**Comment by martin-frbg** [comment]
Frankly I am not sure how the library could/should react here, in particular if there is a way to return some meaningful information to the caller. The segfault as such is probably caused by returning NULL for the buffer in blas_memory_alloc shortly after printing the termination message. (The caller - gotoblas_memory_init() - does not check the returned address before trying to use it, as it currently has no other option anyway.) This is old code from the original GotoBLAS that probably never expected to encounter more than about four threads on the hardware available at the time.

**Comment by brada4** [comment]
You can overload XERBLA with your handler and identify caller that failed, you can look at numpy, R and octave for hints. As such BLAS APIs do not have failure return codes. Citing same old codes - sometimes exit() is done in confusing situations, probably it should not, but there are no strict return codes (well, XERBLA parameter set) past identifying bad input values.

**Comment by martin-frbg** [comment]
I do not expect that using a private xerbla would help when the failure happens on entrance to the library initialization code. If exit() from libopenblas creates a sufficiently less undefined state for the calling program than the segfault it would be trivial to implement a NULL check in gotoblas_memory_init - alas I am not convinced that it does.

**Comment by brada4** [comment]
There is no xerbla code past showing first arg that is wrong. But there is no other place for feedback either.

**Comment by martin-frbg** [comment]
Which is exactly why I wrote the above. Basically this takes us back to the currently oldest open ticket, #295, which proposed a BLAS extension function for registering a custom error handler. Apparently MKL has it as mkl_set_exit_handler, and Apple's implementation of BLAS provides it under the name SetBLASParamErrrorProc. I am still not entirely sure this would have a chance to 
work in this particular case here.

**Comment by brada4** [comment]
My idea was to corrupt XERBLA "API" to the degree that we feed it with out-of-band exit code (or two , depending if RW structures were written), or a new function that gives those codes  Sure it will confuse some prehistorical callers etc. 
Intel's examples actually show the handler just overriding fortran runitime's error message and exitting in a controlled manner.

**Comment by martin-frbg** [comment]
Googling turned up an older blog post (or rant if you will) at http://erlingdandersen.blogspot.com/2016/04/error-handling-in-blas-libraries.html with some links to forum discussions. One bit of potentially useful information from this is that MKL apparently uses non-standard error numbers in xerbla to signal out-of-memory or other internal failures. This should be trivial to implement, but I am not sure if it would actually help in the multithreading scenario outlined here. (Adding support for a custom exit handler on the other hand would probably require some form of thread-local storage for the function pointer, or locks around a global one - I am still unsure if that is going to work for handling an error that occurs right after invoking the library.)

**Comment by brada4** [comment]
XERBLA https://software.intel.com/en-us/mkl-developer-reference-c-xerbla extra codes would help single-threaded programs, the set_xerbla_overload() (i am wondering if intel's cblas.h exports any under generic-looking name) is needed for posted scenario. 
Sure 99% is gruntwork looking for alloc calls and adding error handler, but some sophisticated cases may pop up "right after release"
