### ISSUE TITLE
Bugs in paralleled GEMM3M

### ISSUE THREAD

**Issue by wjc404** [xianyi/OpenBLAS#2319]
I tested CGEMM3M and ZGEMM3M functions of OpenBLAS(TARGET=SKYLAKEX) on an Intel i5-1035G1 CPU with 1 or 4 threads. 
When using 1 thread, the results were correct.
![Screenshot from 2019-11-22 15-06-33](https://user-images.githubusercontent.com/52632443/69405443-a8d4bd00-0d3a-11ea-8f50-fb7f6f097207.png)
![Screenshot from 2019-11-22 15-07-20](https://user-images.githubusercontent.com/52632443/69405449-af633480-0d3a-11ea-9a20-1e5a8fe5e083.png)
However, after setting OMP_NUM_THREADS to 4, some errors appeared.
![Screenshot from 2019-11-22 15-08-41](https://user-images.githubusercontent.com/52632443/69405480-c73ab880-0d3a-11ea-8331-d6f42f131303.png)
![Screenshot from 2019-11-22 15-09-32](https://user-images.githubusercontent.com/52632443/69405491-cc980300-0d3a-11ea-8a54-edaeade7d481.png)
I suggest the parallel gemm3m codes in the "driver" folder to be checked.

**Comment by martin-frbg** [comment]
This has not been touched in a while, probably needs at least some barriers added in level3_gemm3m_thread.c  corresponding to https://github.com/xianyi/OpenBLAS/commit/73de17664dfdf2934a2fdc6dd9442107e6c85035#diff-05879208978a19073d36ba6d09ffdab8

**Comment by brada4** [comment]
Is it v0.3.7 or development? some before had problems with AVX-512 extension too.

**Comment by martin-frbg** [comment]
@brada4 wjc404 **wrote** all the fast and correct AVX512 implementations in the current develop branch

**Comment by wjc404** [comment]
@brada4 It's 0.3.7, sorry I forgot to mention that. The development version has the same problem.

**Comment by brada4** [comment]
Keep development until 0.3.8 for having AVX512 processor as Martin mentioned.
No quick workarounds are viable

**Comment by martin-frbg** [comment]
I notice that the gemm_3m tests (and ctests) are not build by default, but even if I build them separately I do not get any complaints from valgrind/helgrind (except some "lock order violations" within libgfortran) at least on Kaby Lake. Same for your test codes from #2305. Does it work for you when you build with TARGET=HASWELL ?

**Comment by wjc404** [comment]
I'm going to test this in detail after I come to my workplace tomorrow~

**Comment by brada4** [comment]
No need to rush, bug has been in same place for a while. Minimized neutralized sample would be nice for tests collection and to validate fixes.

**Comment by martin-frbg** [comment]
With the test code from your repository I now see this on Kaby Lake as well. helgrind reports several races between the gemm3m kernel and its otcopy routine. Copying the barriers from level3_thread as I suggested earlier does not appear to help, but the level3_thread.c has quite a history of using barriers, locks and _Atomic declarations to stop races whlle level3_gemm3m_thread has remained unchanged (if not to say neglected).

**Comment by wjc404** [comment]
I have just tested zgemm3m and cgemm3m of the newest OpenBLAS version (set TARGET=HASWELL), on ryzen 7 3700x with OMP_NUM_THREADS=2. The bug appears only when m>=64 && n>=64, for both functions.

**Comment by brada4** [comment]
TARGET=ZEN avoids some pipe blocking instruction sequences on top of HASWELL and is faster on native Ryzen.
Was RYZEN detected by build? Is it eqally affected?
64*64=4096 aka PAGESIZE
What happens if you seek around points doubling one and halving other - is it `area size > page size` or one of params at fault?

**Comment by martin-frbg** [comment]
I now believe this can be fixed with #2321 by  the same approach as already used for regular GEMM (level3_thread.c). It is certainly possible that there are more elegant ways to solve this.
