### ISSUE TITLE
Update LAPACK to 3.9.0

### ISSUE THREAD

**Issue by martin-frbg** [xianyi/OpenBLAS#2320]
This is just to note that reference LAPACK 3.9.0 was released two days ago.
As usual, this is not simply a drop-in replacement here as OpenBLAS uses modified Makefiles (and own CMakelists) to replace some functions with optimized implementations. There are also some platform-specific changes and header rearrangements that need to be merged during an update.
And I see svillemot has already found some small bugs in the release.

**Comment by brada4** [comment]
Do you intend to block waiting for bugs to be addressed or let it go as is?

**Comment by martin-frbg** [comment]
I primarily wanted to acknowledge the release and preempt any well-meaning million lines "delete 3.8.0, insert 3.9.0" PRs that do not address the OpenBLAS-specific adaptions. :)
If I recall correctly, any major bugfixes since 3.8.0 should already have been tracked here so the primary motivation for upgrading would probably be the added functions for QR SVD and Householder reconstruction.
