### ISSUE TITLE
DYNAMIC_ARCH differences on cmake vs make

### ISSUE THREAD

**Issue by isuruf** [xianyi/OpenBLAS#2330]
ARM64 on cmake
https://github.com/xianyi/OpenBLAS/blob/eb2eddf241dd5e46e0064cd311b6a63229897d21/cmake/arch.cmake#L48
while on make
https://github.com/xianyi/OpenBLAS/blob/69b16a894dedda06b62fba763aa964f973d6808b/Makefile.system#L549-L552

POWER on cmake is not supported.
make has https://github.com/xianyi/OpenBLAS/blob/69b16a894dedda06b62fba763aa964f973d6808b/Makefile.system#L555-L568

**Comment by martin-frbg** [comment]
Right, my mistake from #1908 (ARM64) where I added the cmake version of the cpu list after rengolin's rearrangement of the cpu model support, but both the list in the Makefile and the runtime checks still reflect ashwinyes' original, shorter list. I will create a PR for this later today.
