### ISSUE TITLE
0xC0000005 error when running cblas_sgemm

### ISSUE THREAD

**Issue by lujq96** [xianyi/OpenBLAS#2335]
I used cmake + VS2017 and 2019 to compile and run the following code with OpenBlas:
```
        float* A = new float[256 * 256];
	float* B = new float[256 * 256];
	float* C = new float[256 * 256 *10];

	{
		int M = 50;
		int N = 50;
		int K = 50;
		cblas_sgemm(CblasRowMajor, CblasNoTrans, CblasTrans, M, N, K,
			-2.0f, A, K, B, K, 0.0f, C, N);

		std::cout << "ok" << std::endl;
	}

	{
		int M = 10;
		int N = 10;
		int K = 10;
		cblas_sgemm(CblasRowMajor, CblasNoTrans, CblasTrans, M, N, K,
			-2.0f, A, K, B, K, 0.0f, C, N);

		std::cout << "ok" << std::endl;
	}

	{
		int M = 256;
		int N = 256;
		int K = 256;
		cblas_sgemm(CblasRowMajor, CblasNoTrans, CblasTrans, M, N, K,
			-2.0f, A, K, B, K, 0.0f, C, N);

		std::cout << "ok" << std::endl;
	}
```
The program prints 2 "ok" and get a 0xC0000005 error for access violation. Several experiments show that this always happens when M and N are greater than 100. I believe this should be a bug.

**Comment by martin-frbg** [comment]
Which version of OpenBLAS and what cpu is this ? (And I assume you left out the initialisation of A and B in your code snippet, or are you actually running this with random memory contents ?)

**Comment by lujq96** [comment]
I used OpenBLAS 0.3.7 and the cpu is intel i7-7700. A and B are initialized as matrix of small float numbers in [-1, 1].

**Comment by brada4** [comment]
Can you attach (or jit) x64dbg to crashing process to show call chain to cblas_sgemm? Picture is fine.

Or event log entry https://answers.microsoft.com/en-us/windows/forum/all/application-error-0xc0000005-and-applications-not/4eefcc5c-ddfc-4146-9545-8cc730f2a5d6 (text from, not xml)

**Comment by martin-frbg** [comment]
Could you check if your code works with the precompiled dll from https://github.com/xianyi/OpenBLAS/releases/download/v0.3.7/OpenBLAS-0.3.7-x64.zip that was cross-compiled on Linux ? I think there was another case recently where a VS2019 build did not appear to work correctly.
