### ISSUE TITLE
OpenBLAS fails when compiled with gcc-10

### ISSUE THREAD

**Issue by JeffreyALaw** [xianyi/OpenBLAS#2336]
Openblas will segfault in its testsuite when compiled with gcc-10.

The root of the problem is openblas does not recognize gcc-10 as gcc and thus selects a different ABI for return values, particularly complex return values.  The difference in ABIs causes parameters to not be in their expected registers.

This was tracked down the the f_check script which tries to determine what compiler is being used.  That script assumes the major, minor and patchlevel are all single integers, which isn't true for gcc-10.

Something like this is sufficient to fix the problem and restore openblas's proper behavior with gcc-10.

[f_check.patch.txt](https://github.com/xianyi/OpenBLAS/files/3929618/f_check.patch.txt)

**Comment by brada4** [comment]
just first `+` is needed to accommodate next 90 gcc releases.

**Comment by martin-frbg** [comment]
@brada4 until one day a gcc with a two-digit minor or patchlevel number gets released, so why not fix this in advance ?
