### ISSUE TITLE
use of openblas.lib in Visual C++

### ISSUE THREAD

**Issue by Adingo** [xianyi/OpenBLAS#2347]
Hi,

I have flowed https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-in-Microsoft-Visual-Studio#1-native-msvc-abi and build openBLAS on Windows x86_64. It generates a directory "Release" which include openblas.lib.

My question is how to use it in Visual C++. 

In a simple VC ++ project, 

step 1) Unfold the C/C++ list and select General → Additional Include Directories
   which directory should be used? The install procedure created a directory "generated" which includes two .h files: cblas.h, and f77blas.h. Is "generated" the only one that should be included?

step 2) click on Linker → General → Additional Import Library
    Directory "Release" was selected

step 3) click Linker → Input → Additional Dependencies
     input openblas.lib

However, I got an error:

LNK1104	cannot open file 'flangmain.lib'

**Comment by brada4** [comment]
That file is included with gfortran used to build openblas.

**Comment by Adingo** [comment]
thanks, brada4. I found this file and added it in the linker as in steps. Then works.

**Comment by brada4** [comment]
If you call only (c)blas you can build mini library without fortran (NO_LAPACK=1)
