### ISSUE TITLE
"FATAL ERROR" when testing "./xdcblat3 < din3"

### ISSUE THREAD

**Issue by njutcz** [xianyi/OpenBLAS#2363]
"FATAL ERROR" when testing "./xdcblat3 < din3"
![error](https://user-images.githubusercontent.com/55725787/71945134-e4e7b280-3200-11ea-8932-c628a8cc2f3e.PNG)
Environment: ARMV8 CentOS 7.6, OpenBLAS-0.3.7
compile: make TARGET=ARMV8 -j

cd ctest
mycount=0; while (( $mycount < 100 )); do ./xdcblat3 < din3;sleep 1; ((mycount=$mycount+1)); done;

The error will occur about every 7 or 8 times! And when "export OMP_NUM_THREADS=1", the error doesn't occur! I'm not sure if this is a precision issue or a calculation error!

**Comment by wjc404** [comment]
What about the test results of cblas_dgemm? It should have appeared above the results of cblas_dsymm.

**Comment by njutcz** [comment]
Only cblas_dsymm has the error. Cblas_dgemm never occurs the same error!

**Comment by martin-frbg** [comment]
What kind of hardware is this, how many cores and which compiler version ? I cannot reproduce this problem so far.

**Comment by brada4** [comment]
There was something similar, solution that worked was to rpmbuild Fedora's SRPM/SPEC that likely has some compiler quirks included.
You can start here (or seek SRPM in rawhide repos)
https://src.fedoraproject.org/rpms/openblas/blob/HEAD/f/openblas.spec

**Comment by njutcz** [comment]
> What kind of hardware is this, how many cores and which compiler version ? I cannot reproduce this problem so far.

kunpeng920 96cores gcc 4.8.5

**Comment by njutcz** [comment]
> What kind of hardware is this, how many cores and which compiler version ? I cannot reproduce this problem so far.

When I build with “USE_SIMPLE_THREADED_LEVEL3=1”， the ERROR doesn't occur. But i don't know why.

**Comment by martin-frbg** [comment]
Thanks for the additional information. Building with USE_SIMPLE_THREADED_LEVEL3=1 disables some additional splitting of the workload that could still contain race conditions - though I do not get any error messages from running valgrind/helgrind on the xdcblat3 test. 
Historically OpenBLAS - like GotoBLAS before it - has not been thread safe until well into the 0.2.x series - with the slow cpu speeds and low core counts available ten years ago the probability of an actual failure seems to have been very low. Even now that most bugs have hopefully been fixed, there is unfortunately still very limited experience with core counts beyond about 32.
I guess there is still some chance that it could be a compiler bug "working around" a lock or barrier though.

**Comment by martin-frbg** [comment]
I have now managed to obtain related helgrind warnings for this on a different system. Apparently the current set of memory barriers in level3_thread.c is insufficient to sequence accesses to the segments of the common gemm buffer.
The attached working version of level3_thread.c addresses these by riddling the code with mutex locks, hopefully (a) this actually solves the problem you encountered and (b) it can be stripped down to a less intrusive solution
[level3_thread.txt](https://github.com/xianyi/OpenBLAS/files/4050825/level3_thread.txt)

**Comment by martin-frbg** [comment]
@njutcz did you test if my proposed version of level3_thread.c fixes the problem for you ? With my limited range of hardware, I never saw the actual miscalculation.

**Comment by njutcz** [comment]
Yes, it can solve my problem but the performance drops a lot when too many threads.
Thanks a lot anyway!

**Comment by martin-frbg** [comment]
Well, it was just a first stab at the problem, with lots of overhead from individual lock/unlock calls. (Compiling with OpenMP would probably provide similar protection, not sure if you tried that as well ?)

**Comment by brada4** [comment]
> Yes, it can solve my problem but the performance drops a lot when too many threads.

You should not try more threads than actual cores. What happens is cache spill that you actually access main memory and everything gets disproportionally 10-20x slower.

**Comment by njutcz** [comment]
> > Yes, it can solve my problem but the performance drops a lot when too many threads.
> 
> You should not try more threads than actual cores. What happens is cache spill that you actually access main memory and everything gets disproportionally 10-20x slower.

Well, I tested on Kunpeng920. It has 96 or 128 cores.

**Comment by brada4** [comment]
OpenBLAS might get per-cpu task sizing wrong too especially with that many CPUs....

**Comment by njutcz** [comment]
> Well, it was just a first stab at the problem, with lots of overhead from individual lock/unlock calls. (Compiling with OpenMP would probably provide similar protection, not sure if you tried that as well ?)

I tried to build with "make USE_OPENMP=1 TARGET=ARMV8", but this can't solve the problem.

**Comment by martin-frbg** [comment]
Too bad. So far I have failed to come up with a solution that uses less locking, satisfies helgrind _and_ does not deadlock immediately. :(

**Comment by marxin** [comment]
I'm a noobie to the project, but I can't reproduce the failure on an Intel system with 160 cores:
```
$ cat /proc/cpuinfo
...
processor	: 159
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU E7-8891 v4 @ 2.80GHz
stepping	: 1
microcode	: 0xb000038
cpu MHz		: 2800.224
cache size	: 61440 KB
physical id	: 7
siblings	: 20
core id		: 29
cpu cores	: 10
apicid		: 507
initial apicid	: 507
fpu		: yes
fpu_exception	: yes
cpuid level	: 20
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm arat pln pts md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit
bogomips	: 5604.89
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:
```

I compiled the current `develop` branch with:
```
$ make -j160 USE_THREAD=1 USE_OPENMP=0
```

From the performance perspective I see the following numbers:
```
$ OPENBLAS_NUM_THREADS=160 time -p ./xdcblat3 < din3
...
real 0.65
$ OPENBLAS_NUM_THREADS=1 time -p ./xdcblat3 < din3
...
real 0.36
$ OPENBLAS_NUM_THREADS=4 time -p ./xdcblat3 < din3
...
real 0.39
```

And there's a `perf report` for the 160 cores usage:
```
$ perf report --stdio
# Overhead  Command   Shared Object         Symbol                              
# ........  ........  ....................  ....................................
#
    49.07%  xdcblat3  libpthread-2.26.so    [.] __lll_unlock_elision
    13.89%  xdcblat3  libc-2.26.so          [.] __sched_yield
    12.04%  xdcblat3  libpthread-2.26.so    [.] __pthread_mutex_lock
    10.19%  xdcblat3  libpthread-2.26.so    [.] __lll_lock_elision
     8.33%  xdcblat3  [kernel]              [k] 0xffffffff9b80018a
     6.48%  xdcblat3  xdcblat3              [.] pthread_mutex_unlock@plt
     0.00%  xdcblat3  xdcblat3              [.] dmmch_
     0.00%  xdcblat3  xdcblat3              [.] blas_thread_server
     0.00%  xdcblat3  libpthread-2.26.so    [.] __pthread_mutex_unlock_usercnt
```

**Comment by brada4** [comment]
Could you make same perf report from command prepended with:
`OMP_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1`
It looks like locking goes awful as minimum.

**Comment by marxin** [comment]
> `OMP_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1`

I see this:
```
    96.13%  xdcblat3  xdcblat3              [.] pthread_mutex_unlock@plt
     3.87%  xdcblat3  xdcblat3              [.] dmake_
     0.00%  xdcblat3  xdcblat3              [.] dmmch_
     0.00%  xdcblat3  ld-2.26.so            [.] _dl_lookup_symbol_x
     0.00%  xdcblat3  ld-2.26.so            [.] do_lookup_x
     0.00%  xdcblat3  xdcblat3              [.] dchk1_
     0.00%  xdcblat3  libc-2.26.so          [.] __GI_____strtoull_l_internal
     0.00%  xdcblat3  libc-2.26.so          [.] _dl_addr
     0.00%  xdcblat3  libgfortran.so.4.0.0  [.] 0x0000000000190ba2
     0.00%  xdcblat3  ld-2.26.so            [.] _dl_cache_libcmp
     0.00%  xdcblat3  ld-2.26.so            [.] dl_main
     0.00%  xdcblat3  ld-2.26.so            [.] _dl_setup_hash
     0.00%  xdcblat3  [kernel]              [k] 0xffffffff9b800a40
```

**Comment by martin-frbg** [comment]
Is that with or without the proposed patch ? As this particular problem appears to be irreproducible on x86_64, I believe it could also be that (1) the helgrind warnings are a false positive, with the memory barriers already in place theoretically sufficient to prevent a race and (2) the implementation of "MB" and "WMB" as a `dmb ish(st)` (in common_arm64.h) is insufficient either in general or specifically in the Kunpeng implementation.

**Comment by brada4** [comment]
Helluva locks in there

**Comment by njutcz** [comment]
The ERROR is caused by weak memory order, so it can't be reproduced on Intel.

**Comment by marxin** [comment]
> Is that with or without the proposed patch ?

It's without the suggested patch.

**Comment by martin-frbg** [comment]
Well, with that patch there would have been even more cycles spent in lock/unlock - the code as originally written was totally not threadsafe and my sprinkling of pthread_mutex_lock on each problem spot was certainly not ideal for performance. (Not sure why the unlock would feature disproportionally in the perf report, but with a tiny problem like default xdcblat3 about 158 of your threads would be doing nothing. Perhaps a topic for another issue, if you have a suggestion how to improve performance without reintroducing races).
Not sure yet what to replace the "dmb ish" fences with to  restore order on arn64...

**Comment by brada4** [comment]
pthread locks sort of do some synchronisation, should not have different memory access semantics on different arches.

**Comment by martin-frbg** [comment]
@brada4 the (original) problem is that critical parts are only protected by barriers. Replacing them with locks is what my proposed patch did, but obviously at a performance penalty.
@njutcz I wonder if you could retest with the original code, but with the `#define WMB...` in common_arm64.h set to "dmb ish" rather than "dmb ishst" (same as the definition for MB in the line above it) ? But that is just another stab in the dark...

**Comment by brada4** [comment]
@martin-frbg yup, pthread lock makes a syscall, that is quite heavy and does not ease in last years....

**Comment by njutcz** [comment]
> @brada4 the (original) problem is that critical parts are only protected by barriers. Replacing them with locks is what my proposed patch did, but obviously at a performance penalty.
> @njutcz I wonder if you could retest with the original code, but with the `#define WMB...` in common_arm64.h set to "dmb ish" rather than "dmb ishst" (same as the definition for MB in the line above it) ? But that is just another stab in the dark...

I tried it, but it still failed.

**Comment by AGSaidi** [comment]
I can make this fail with on an Graviton2 CPU as well. Taking a quick look at this, the barriers are in the wrong places. I'll need to look more carefully at the code,  before I'm comfortable with the solution. However, quickly moving some things around, but it went from failing after a couple of iterations to passing 100s.  #2471  @njutcz @martin-frbg can you please try?

I'd like to also briefly talk about why these are in the wrong place.  Arm systems are weakly ordered. Writes and reads don't have to occur in the memory system in program order. When work is being passed from one thread to another, the barriers are needed to ensure the data written before the flag that says the data can be read is set on the producer side and conversely on the consumer side the flag must be written before the data can be consumed. 

Wrapping everything in pthread_lock/unlock effectively does this because both part of the lock and unlock contain barriers.
