### ISSUE TITLE
OpenBLAS only runs three CPU cores when running cblas_segmm 

### ISSUE THREAD

**Issue by zzl2410** [xianyi/OpenBLAS#2364]
Hi
When running cblas_segmm ,my computer CPU only can run 3 cores even though it has 8 cores.
I tried to modify threads number,but it also cannot run all eight cores.
![9b07eab60aa87a12305002125b7cb8e](https://user-images.githubusercontent.com/59674578/72032276-da452000-32c9-11ea-99ad-57457b5f22e0.jpg)

Envirnment: CPU:intel core i7-9700  win10
I want to know how to run  all CPU cores.

**Comment by brada4** [comment]
How big is the sample you are running? Who calls it? Maybe the calling part is on a single CPU and you dont get those 4 CPUs on average.

**Comment by zzl2410** [comment]
> How big is the sample you are running? Who calls it? Maybe the calling part is on a single CPU and you dont get those 4 CPUs on average.

I am running a cascaded network by running cblas_sgemm and each network includes four convolution calculations.I  find the number of process is eight when running sample, but i dont know how to set 4 CPUs on average when running cblas_sgemm.

Envirnment: CPU:intel core i7-9700 win10

**Comment by martin-frbg** [comment]
OpenBLAS will not distribute the GEMM workload onto multiple threads when it is so small that the overhead would outweigh the gains, perhaps this is why you are not seeing all (or even just 4) cores busy all the time.

**Comment by brada4** [comment]
Once the last part of cascade is less than system page, or hugepage, it cannot efficiently be processed on diffetent cores
.

**Comment by brada4** [comment]
check number of openblas threads with process explorer (that task manager from microsoft sysinternals) 
OpenBLAS is intended to return result ASAP, not to stress-test your CPU at all times, you have other tools for that.
