### ISSUE TITLE
Skylake target

### ISSUE THREAD

**Issue by jbaron42** [xianyi/OpenBLAS#2374]
I'm a little confused about the state of Skylake support in v0.3.7.  Is it entirely disabled, or a just limited set of functionality that is disabled?  When I try to build for a Skylake target on a Cascade Lake processor, it appears the Haswell target is getting built regardless of what options I pass to make.  E.g.,

 make USE_THREAD=0 USE_LOCKING=1 TARGET=SKYLAKEX FC=ifort DYNAMIC_ARCH=0

yields

 OpenBLAS build complete. (BLAS CBLAS LAPACK LAPACKE)

  OS               ... Linux
  Architecture     ... x86_64
  BINARY           ... 64bit
  C compiler       ... GCC  (command line : cc)
  Fortran compiler ... INTEL  (command line : ifort)
  Library Name     ... libopenblas_haswell-r0.3.7.a (Single threaded)

It looks like c_check is causing NO_AVX512=1 to be set (I don't know why it would fail on a Cascade Lake node), but even if I hack it to force NO_AVX512=0, the Haswell version is built (and the resulting DGEMM performance of that library is consistent with an AVX2 build).

Thanks for any pointers.

**Comment by martin-frbg** [comment]
Probably either your gcc or binutils (assembler) is too old to support avx512 vector instructions - the c_check script tries to compile a few lines of code to test this (around line 230 in this file). 
With 0.3.7, AVX512 GEMM support is limited to SGEMM, you need to build the current develop branch to get DGEMM (as well as CGEMM, ZGEMM and further performance improvements for SGEMM)

**Comment by martin-frbg** [comment]
BTW forcing NO_AVX512=0 is not going to work, you'd need to `undef NO_AVX512` instead (or simply make sure that it does not get set).

**Comment by jbaron42** [comment]
OK, thanks for the tips.  I had tried a relatively recent gcc, but you are right that my binutils is probably old as well.  I will give the development branch a try.

**Comment by brada4** [comment]
The gcc invoked from cc command usually is the old one used to compile your system.
As long as you dont tell versions in absolute numbers we cannot help much. You also need a kernel with AVX512 state support.

**Comment by brada4** [comment]
You mention "node" as to refering to a computer, a virtual machine, or some container? Whats in /proc/cpuinfo ?
