### ISSUE TITLE
openblas 0.3.7 fails to build with MSVC when linking libs

### ISSUE THREAD

**Issue by scirocc** [xianyi/OpenBLAS#2385]
I use MSVC toolchain in clion，the environment is vs2019 （version16.4）  architecture：amd64.

And I download openblas binary library for windows64.

In cmakelist I wrote this:

add_executable(MYtoolTest
E:/CLionProjects/MYtoolTest/src/main.cpp
E:/CLionProjects/MYtoolTest/include/openBLAS/cblas.h
E:/CLionProjects/MYtoolTest/include/openBLAS/f77blas.h
E:/CLionProjects/MYtoolTest/include/openBLAS/lapacke.h
E:/CLionProjects/MYtoolTest/include/openBLAS/lapacke_config.h
E:/CLionProjects/MYtoolTest/include/openBLAS/lapacke_mangling.h
E:/CLionProjects/MYtoolTest/include/openBLAS/lapacke_utils.h
E:/CLionProjects/MYtoolTest/include/openBLAS/openblas_config.h
D:/ProgramData/Anaconda3/include/Python.h
)

TARGET_LINK_LIBRARIES(MYtoolTest 
E:/CLionProjects/MYtoolTest/bin/libgcc.a
E:/CLionProjects/MYtoolTest/bin/libstdc++.a
E:/CLionProjects/MYtoolTest/bin/openBLAS/libopenblas.a
python36.lib
imagehlp.lib
legacy_stdio_definitions.lib
)

```#include <armadillo>
int main(){
    arma::mat A = arma::randn<arma::mat>(3,2);
    arma::mat B = cov(A);
    return 0;
}```

and then there is the error:
libopenblas.a(dgemv_thread_n.obj) : error LNK2019: Unresolved external symbol **__emutls_get_address**，referenced in function **dgemv_thread_n** 
libopenblas.a(dynamic.obj) : error LNK2019: Unresolved external symbol  **__ms_vsnprintf**，referenced in function **snprintf.constprop.2** 

What should I do now？Any  suggestion is `appreciated！

**Comment by brada4** [comment]
Both symbols are in msvcrt.dll
libgcc.a forced link means the outer builder stuff is not aware of visual studio and thinks mingw gcc.

**Comment by scirocc** [comment]
> Both symbols are in msvcrt.dll
> libgcc.a forced link means the outer builder stuff is not aware of visual studio and thinks mingw gcc.

Thank you very much for you advice！It really hepls.I follow your suggestion:get rid of those two lib(libgcc.a,libstdc++.a),put msvcrt.dll in the path of the executable file（E:\CLionProjects\MYtoolTest\cmake-build-debug）
and my cmakelists it's now like this:
```

cmake_minimum_required(VERSION 3.14)
project(MYtoolTest)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_FLAGS_DEBUG "/O2")   
include_directories(include)
include_directories(E:/CLionProjects/MYtoolTest/MyTool/include)
include_directories(D:/ProgramData/Anaconda3/include)
include_directories(E:/CLionProjects/MYtoolTest/MyTool/include)
include_directories(E:/CLionProjects/MYtoolTest/include)
include_directories(E:/CLionProjects/MYtoolTest/include/armadillo_9.800.3)
include_directories(E:/CLionProjects/MYtoolTest/include/armadillo_9.800.3/armadillo_bits)
include_directories(E:/CLionProjects/MYtoolTest/include/openBLAS)
link_directories(bin)
link_directories(D:/ProgramData/Anaconda3/libs)
include_directories(E:/CLionProjects/MYtoolTest/bin)
include_directories(E:/CLionProjects/MYtoolTest/bin/bin)
include_directories(E:/CLionProjects/MYtoolTest/bin/include)
include_directories(E:/CLionProjects/MYtoolTest/bin/lib)
include_directories(E:/CLionProjects/MYtoolTest/bin/lib/cmake)
include_directories(E:/CLionProjects/MYtoolTest/bin/lib/cmake/openblas)
include_directories(E:/CLionProjects/MYtoolTest/bin/lib/pkgconfig)
include_directories(E:/CLionProjects/MYtoolTest/bin/openBLAS)
add_executable(MYtoolTest
E:/CLionProjects/MYtoolTest/src/main.cpp
E:/CLionProjects/MYtoolTest/include/openBLAS/cblas.h
E:/CLionProjects/MYtoolTest/include/openBLAS/f77blas.h
E:/CLionProjects/MYtoolTest/include/openBLAS/lapacke.h
E:/CLionProjects/MYtoolTest/include/openBLAS/lapacke_config.h
E:/CLionProjects/MYtoolTest/include/openBLAS/lapacke_mangling.h
E:/CLionProjects/MYtoolTest/include/openBLAS/lapacke_utils.h
E:/CLionProjects/MYtoolTest/include/openBLAS/openblas_config.h
D:/ProgramData/Anaconda3/include/Python.h
)
TARGET_LINK_LIBRARIES(MYtoolTest 
E:/CLionProjects/MYtoolTest/bin/lib/libopenblas.a
python36.lib
imagehlp.lib
legacy_stdio_definitions.lib
)
```

and I got this：
1.error LNK2019: Unresolved external symbol **___chkstk_ms**（link libgcc.a only to fix this ）
2.error LNK2019: Unresolved external symbol **__emutls_get_address**
3error LNK2019:  Unresolved external symbol  **__ms_vsnprintf**

 Am I did it in a wrong way?

**Comment by brada4** [comment]
You should refer to documentation of
` MSVC toolchain in clion，the environment is vs2019 （version16.4） architecture：amd64.`

OpenBLAS builds with visual studio after vcvarsall.bat

**Comment by scirocc** [comment]
you mean this?
“step5:Activate the MSVC environment for 64 bits with vcvarsall x64. Search on the web for the particular steps for your version of MSVC. On Windows 10 with Visual Studio 2017, this would be...”

So the binary library just won't work in my environment and I should compile it follow the instructions ?

Thank you so much!! I'll try!

**Comment by brada4** [comment]
OpenBLAS alone builds with visual studio compilers, but without assembly kernels. Better off with clang-cl.
The problem lies in other project wrapping it. If you can use independently built (Open)BLAS, give it a go and ignore their in-tree version.

**Comment by Diazonium** [comment]
Personally I would recommend using GCC even on Windows, last time I checked OpenBLAS compiled and worked fine with GCC+MinGW64. You can grab a reasonably recent toolchain build with this installer:
https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/mingw-w64-install.exe

**Comment by brada4** [comment]
clang-cl is clang wrapper with visual studio parameters, even visual studio permits it....

**Comment by scirocc** [comment]
@Diazonium GCC+MinGW64 works just fine,but my project has to use cuda,it looks like MinGW64 can't work with cuda?So I was forced to use msvc instead

**Comment by scirocc** [comment]
@brada4 thanks again bro，I‘ll try clang-cl.

> clang-cl is clang wrapper with visual studio parameters, even visual studio permits it....

**Comment by scirocc** [comment]
> clang-cl is clang wrapper with visual studio parameters, even visual studio permits it....

Maybe I gonna use libtorch and cuda in future,but seems like they only work with msvc?So I  thought maybe I should try msvc last time.If it wont work,I made up my mind to use vs2019 as my ide,then all of those problems will gone.

**Comment by brada4** [comment]
Python 3.6 requires absolutely one exact msvc version. Please dig relevant documentation before saying anything more.
This is not a support forum for dozen of products you mention

**Comment by martin-frbg** [comment]
I believe combining mingw and VS like you intended should work, and used to work - perhaps recent versions of mingw and/or VS introduced some incompatibility between the two as I believe we have a few open tickets about build and runtime problems in that combination.

**Comment by brada4** [comment]
there is Python 3.6 involved that mandates older CL.EXE, and I suspect already imports older msvcrt....

**Comment by martin-frbg** [comment]
@brada4 can you point to a reference for this ? From https://wiki.python.org/moin/WindowsCompilers
I am led to believe 3.6 would work with VS2019

**Comment by brada4** [comment]
@martin-frbg there is a mention of "version 16.4" in initial post, not CL.EXE 14.x used to build python.

**Comment by martin-frbg** [comment]
that's the current build/version number of VS2019 professional/enterprise I believe, not directly related to the version of cl.exe it contains as far as I know. (What used to be just VS _year_ Update X years ago)

**Comment by brada4** [comment]
The question is if mentioned toolchain builds sole OpenBLAS with cmake.
That tells if it is problem here or somewhere else. Link line with python is not a constitute of openblas build.

**Comment by scirocc** [comment]
> I believe combining mingw and VS like you intended should work, and used to work - perhaps recent versions of mingw and/or VS introduced some incompatibility between the two as I believe we have a few open tickets about build and runtime problems in that combination.

Thanks man,I thought that combination should work too,maybe my visual studio version is too high.
It just freak me out ,cant waste time in environment anymore.Use msbuild now.
