### ISSUE TITLE
OpenBLAS 0.3.8: Goldmont Plus not automatically detected on Teclast F7 plus

### ISSUE THREAD

**Issue by Iceman9** [xianyi/OpenBLAS#2400]
I was trying to compile OpenBLAS 0.3.8 on Debian 10, Teclast F7 plus. Before, I manually stated the CPU as ATOM, but since I saw from the changelog that the Goldmont Plus is auto detected, why not give it a shot. The Teclast F7 plus has a Intel Celeron N4100 processor.

The message I get is:
```
➜  OpenBLAS-GIT git:(fb5eb475) make
Makefile:139: *** OpenBLAS: Detecting CPU failed. Please set TARGET explicitly, e.g. make TARGET=your_cpu_target. Please read README for the detail..  Stop.
```

I have read only the changelog, so I apologize if I missed any additional info.

Attached is cpu_info and the `Makefile.conf` file, if it helps.

[cpu_info.txt](https://github.com/xianyi/OpenBLAS/files/4179921/cpu_info.txt)
[Makefile.conf.txt](https://github.com/xianyi/OpenBLAS/files/4179926/Makefile.conf.txt)

**Comment by brada4** [comment]
TARGET=WESTMERE should do, as CPU(ID) has no AVX, though given age difference could be sub-optimal.

**Comment by martin-frbg** [comment]
Strange - family 6, exmodel 7, model 10 (122 decimal == 7A hex) should be recognized. (And I believe NEHALEM is the most appropriate cpu generation)
https://github.com/xianyi/OpenBLAS/blob/3bec250cf995c8f96e0849e582227589234effcd/cpuid_x86.c#L1384-L1388

**Comment by Iceman9** [comment]
I have done as @brada4 wrote. And it compiled (and also works of course). Then I ran make without any arguments again and found out that `config.h` **defines** `#define NEHALEM` but it also defines `#define CHAR_CORENAME "UNKNOWN"`

**Comment by martin-frbg** [comment]
Thank you, that provided the missing clue - there is a separate function that was indeed missing the definitions for extended model code 7 (and code 6 as well, meaning this oversight will have affected high-end Cannon Lake and Ice Lake systems too)
