### ISSUE TITLE
Test blas-test fails with -ftree-vectorize

### ISSUE THREAD

**Issue by lexming** [xianyi/OpenBLAS#2412]
The `develop` branch builds successfully (`make all`) using GCC 9.2 in a Skylake CPU with AVX512 using `-ftree-vectorize`. However, running `blas-test` afterwards shows several loss of accuracy errors.

All failed tests are complex BLAS tests: CTRMV, CTPMV, CTRSV, CTPSV, ZTRMV, ZTBMV, ZTPMV, ZTRSV, ZTBSV, ZTPSV

Example of error:
```
 TESTS OF THE COMPLEX*16       LEVEL 2 BLAS
   
THE FOLLOWING PARAMETER VALUES WILL BE USED:
    FOR N                   0     1     2     3     5     9
    FOR K                   0     1     2     4
    FOR INCX AND INCY       1     2    -1    -2
    FOR ALPHA          ( 0.0, 0.0)  ( 1.0, 0.0)  ( 0.7,-0.9) 
    FOR BETA           ( 0.0, 0.0)  ( 1.0, 0.0)  ( 1.3,-1.1)    
 
ROUTINES PASS COMPUTATIONAL TESTS IF TEST RATIO IS LESS THAN   16.00 
  
RELATIVE MACHINE PRECISION IS TAKEN TO BE  2.2D-16 
  
ZGEMV  PASSED THE TESTS OF ERROR-EXITS  
 
ZGEMV  PASSED THE COMPUTATIONAL TESTS (  3460 CALLS)
[...]
ZTRMV  PASSED THE TESTS OF ERROR-EXITS 
 
******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
                        EXPECTED RESULT                    COMPUTED RESULT
        1  (   0.686813    ,  -0.156843    )  (   0.686813    ,  -0.156843    )
        2  (  -0.101935    ,   0.100522    )  (  -0.101935    ,   0.100522    )
        3  (  -0.365189E-01,   0.520084E-01)  (  -0.365189E-01,   0.520084E-01)
        4  (   0.305346    ,   0.135281    )  (  -0.529970E+10,   0.843656E+10)
        5  (   0.884216    ,   0.264764    )  (   0.884216    ,   0.264764    )
  ******* ZTRMV  FAILED ON CALL NUMBER:     171: ZTRMV ('L','N','U',  5, A,  6, X, 2)
```

Commands to reproduce the error with GCC 9.2:
1. `FFLAGS='-ftree-vectorize' make all  BINARY='64'  CC='gcc'  FC='gfortran'  USE_OPENMP='1'  USE_THREAD='1'  CFLAGS='-ftree-vectorize'`
2. `make blas-test`

Could you clarify if `blas-test` is prepared to be run with `-ftree-vectorize` and if those errors can be fixed? Moreover, reducing the optimization level of the tests built by `blas-test` seems to fix the issue. Should we use any particular compilation flags to build and run those tests?

**Comment by bartoldeman** [comment]
`make blas-test` replaces the library with the reference blas: ```ar -ru ../../../libopenblas_skylakexp-r0.3.9.dev.a isamax.o sasum.o saxpy.o scopy.o sdot.o snrm2.o srot.o srotg.o sscal.o sswa
p.o sdsdot.o srotmg.o srotm.o sgemv.o sgbmv.o ssymv.o ssbmv.o sspmv.o strmv.o stbmv.o stpmv.o strsv.o stbsv.o stpsv.o sger.o s
syr.o sspr.o ssyr2.o sspr2.o sgemm.o ssymm.o ssyrk.o ssyr2k.o strmm.o strsm.o idamax.o dasum.o daxpy.o dcopy.o ddot.o dnrm2.o 
drot.o drotg.o dscal.o dsdot.o dswap.o drotmg.o drotm.o dgemv.o dgbmv.o dsymv.o dsbmv.o dspmv.o dtrmv.o dtbmv.o dtpmv.o dtrsv.
o dtbsv.o dtpsv.o dger.o dsyr.o dspr.o dsyr2.o dspr2.o dgemm.o dsymm.o dsyrk.o dsyr2k.o dtrmm.o dtrsm.o scabs1.o scasum.o scnr
m2.o icamax.o caxpy.o ccopy.o cdotc.o cdotu.o csscal.o crotg.o cscal.o cswap.o csrot.o cgemv.o cgbmv.o chemv.o chbmv.o chpmv.o ctrmv.o ctbmv.o ctpmv.o ctrsv.o ctbsv.o ctpsv.o cgerc.o cgeru.o cher.o chpr.o cher2.o chpr2.o cgemm.o csymm.o csyrk.o csyr2k.o ctrmm.o ctrsm.o chemm.o cherk.o cher2k.o dcabs1.o dzasum.o dznrm2.o izamax.o zaxpy.o zcopy.o zdotc.o zdotu.o zdscal.o zrotg.o zscal.o zswap.o zdrot.o zgemv.o zgbmv.o zhemv.o zhbmv.o zhpmv.o ztrmv.o ztbmv.o ztpmv.o ztrsv.o ztbsv.o ztpsv.o zgerc.o zgeru.o zher.o zhpr.o zher2.o zhpr2.o zgemm.o zsymm.o zsyrk.o zsyr2k.o ztrmm.o ztrsm.o zhemm.o zherk.o zher2k.o lsame.o xerbla.o xerbla_array.o
``` after compiling all those from `lapack-netlib/BLAS/SRC` so blas-test doesn't test openblas but netlib blas.

It's still an issue though because this behaviour is somewhat surprising!

**Comment by brada4** [comment]
All options on -O3 that are added over -O2 guarantee numeric accuracy deviation. That is well documented.

**Comment by lexming** [comment]
I just realized that `blas-test` is part of the special target `.NOTPARALLEL` that runs those test **after** install. That explains the findings of @bartoldeman regarding the replacement with the reference blas. So we might have been misguided by the name of `blas-test` and are misusing them.
Could somebody clarify the purpose and use of `blas-test`?

**Comment by martin-frbg** [comment]
In theory the `blas-test` should be redundant as the same test cases from netlib BLAS are in test.
(From the commit history the Makefile entry crept in as "some minor changes" accompanying a   
Sandybridge cgemm kernel - quite possible that the contributor did not realize that the tests were
already available) 
In practice the inputs are almost completely identical (some of the "OpenBLAS" ones test bigger matrix sizes in addition to what the "netlib" tests have) but there appear to be some differences in the fortran codes. (Codes in "test" are probably unchanged from GotoBLAS, which will have borrowed them from a netlib BLAS of ten to fifteen years ago, codes in "blas-test" received a few updates in the LAPACK 3.5/3.6 timeframe but at first glance most appear to be purely cosmetic )

**Comment by martin-frbg** [comment]
Main functional difference (particularly for zblat2.f which performs the tests you quoted)  appears to be a change in the calculation of the machine precision - maybe this moved goalposts a bit.

**Comment by lexming** [comment]
@martin-frbg thank you very much for taking the time to look into this. The combination of a change in machine precision and the lower numeric precision introduced by `-ftree-vectorize` might indeed explain the failed tests. Since the tests in `blas-test` do not test anything fundamentally different from `make tests`, we will stick to the default ones then.

**Comment by bartoldeman** [comment]
The tests actually failed because of a bug in GCC, which caused it to miscompile some complex and double complex functions (going far beyond numerical rounding errors) in the reference BLAS with -ftree-vectorize enabled. I've reduced it to a small test case and it's now with the GCC developers: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=93734
