### ISSUE TITLE
shuts down and restarts when using all cores

### ISSUE THREAD

**Issue by MiXaiLL76** [xianyi/OpenBLAS#2413]
I compiled the latest library version for raspberry pi 3 b + and compiled a ready-made deb package.
Installed it on a rasbian system and try to run

```
pi@raspberrypi:~ $ gcc time_dgemm.c -lopenblas
```

TEST 1 CORE OK
```
pi@raspberrypi:~ $ OPENBLAS_NUM_THREADS=1 ./a.out
openblas_get_num_threads =  1
m=1000,n=1000,k=1000,alpha=1.200000,beta=0.001000,sizeofc=1000000
1000x1000x1000  1.007118 s      1985.864616 MFLOPS
```

TEST 2 CORE OK
```
pi@raspberrypi:~ $ OPENBLAS_NUM_THREADS=2 ./a.out
openblas_get_num_threads =  2
m=1000,n=1000,k=1000,alpha=1.200000,beta=0.001000,sizeofc=1000000
1000x1000x1000  0.519102 s      3852.807348 MFLOPS
```

TEST 3 CORE OK
```
pi@raspberrypi:~ $ OPENBLAS_NUM_THREADS=3 ./a.out
openblas_get_num_threads =  3
m=1000,n=1000,k=1000,alpha=1.200000,beta=0.001000,sizeofc=1000000
1000x1000x1000  0.371171 s      5388.351999 MFLOPS
```

but...  TEST 4 CORES

```
pi@raspberrypi:~ $ OPENBLAS_NUM_THREADS=4 ./a.out
openblas_get_num_threads =  4
m=1000,n=1000,k=1000,alpha=1.200000,beta=0.001000,sizeofc=1000000
```
crash and reboot.

What could it be? 

Compilation:
```
make CC=arm-linux-gnueabihf-gcc       \
    RANLIB=arm-linux-gnueabihf-ranlib \
    AR=arm-linux-gnueabihf-gcc-ar     \
    FC=arm-linux-gnueabihf-gfortran   \
    HOSTCC=gcc                        \
    TARGET=ARMV7 NUM_THREADS=4
```

GCC
```
HOME-PC:~$ arm-linux-gnueabihf-gcc --version
arm-linux-gnueabihf-gcc (Debian 8.3.0-2) 8.3.0
```
```
pi@raspberrypi:~ $ arm-linux-gnueabihf-gcc --version
arm-linux-gnueabihf-gcc (Raspbian 8.3.0-6+rpi1) 8.3.0
```

RPI

```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.19.97-v8+ #1294 SMP PREEMPT Thu Jan 30 13:27:08 GMT 2020 aarch64 GNU/Linux
```

**Comment by martin-frbg** [comment]
Bad power supply or overheating cpu would be my guesses.

**Comment by Diazonium** [comment]
If you are powering the raspi via USB, your µUSB cable might also be faulty, or low quality. Many µUSB cables have very thin conductors and cause a significant voltage drop if the device draws a lot of current.

**Comment by MiXaiLL76** [comment]
> 
> 
> If you are powering the raspi via USB, your µUSB cable might also be faulty, or low quality. Many µUSB cables have very thin conductors and cause a significant voltage drop if the device draws a lot of current.

I specifically bought a thick usb cable through which the phone charges under 3A 5V
I'll check for overheating of the processor. I'll write later.

**Comment by MiXaiLL76** [comment]
it's voltage drop
