### ISSUE TITLE
Building with native Apple Clang fails if NO_AVX512 not set

### ISSUE THREAD

**Issue by zbeekman** [xianyi/OpenBLAS#2428]
It seems that a build with GFortran 9 and Apple clang version 11.0.0 (clang-1100.0.33.17) fails unless `NO_AVX512` is set in the environment.

This was discovered while updating the Homebrew formula. I suspect something similar may happen when using GCC 9 for C and Fortran too.

Here is what the build & environment look like:

```
DYNAMIC_ARCH=1
USE_OPENMP=1
make CC=clang FC=gfortran libs netlib shared
make PREFIX=/usr/local/Cellar/openblas/0.3.8 install
```

And here are the errors we see [during CI](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/57076/version=catalina/console):

```
15:22:04 ==> make CC=clang FC=gfortran libs netlib shared
15:22:04 make[1]: warning: -jN forced in submake: disabling jobserver mode.
15:22:04 clang -O2 -DMAX_STACK_ALLOC=2048 -DEXPRECISION -fopenmp -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=6 -DMAX_PARALLEL_NUMBER=1 -DVERSION=\"0.3.8\" -DASMNAME=_saxpy -DASMFNAME=_saxpy_ -DNAME=saxpy_ -DCNAME=saxpy -DCHAR_NAME=\"saxpy_\" -DCHAR_CNAME=\"saxpy\" -DNO_AFFINITY -I.. -I. -UDOUBLE  -UCOMPLEX -c axpy.c -o saxpy.o
15:22:04 clang -O2 -DMAX_STACK_ALLOC=2048 -DEXPRECISION -fopenmp -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=6 -DMAX_PARALLEL_NUMBER=1 -DVERSION=\"0.3.8\" -DASMNAME=_sswap -DASMFNAME=_sswap_ -DNAME=sswap_ -DCNAME=sswap -DCHAR_NAME=\"sswap_\" -DCHAR_CNAME=\"sswap\" -DNO_AFFINITY -I.. -I. -UDOUBLE  -UCOMPLEX -c swap.c -o sswap.o

...

[snip]

...

15:53:55 clang -c -O2 -DMAX_STACK_ALLOC=2048 -DEXPRECISION -fopenmp -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=6 -DMAX_PARALLEL_NUMBER=1 -DVERSION=\"0.3.8\" -DASMNAME=_sgemv_t_SKYLAKEX -DASMFNAME=_sgemv_t_SKYLAKEX_ -DNAME=sgemv_t_SKYLAKEX_ -DCNAME=sgemv_t_SKYLAKEX -DCHAR_NAME=\"sgemv_t_SKYLAKEX_\" -DCHAR_CNAME=\"sgemv_t_SKYLAKEX\" -DNO_AFFINITY -DTS=_SKYLAKEX -I.. -DBUILD_KERNEL -DTABLE_NAME=gotoblas_SKYLAKEX -march=skylake-avx512 -UDOUBLE  -UCOMPLEX -UDOUBLE -UCOMPLEX  -DTRANS  ../kernel/x86_64/sgemv_t_4.c -o sgemv_t_SKYLAKEX.o
15:53:55 In file included from ../kernel/x86_64/saxpy.c:37:
15:53:55 ../kernel/x86_64/saxpy_microk_skylakex-2.c:41:13: error: always_inline function '_mm256_broadcastss_ps' requires target feature 'avx2', but would be inlined into function 'saxpy_kernel_16' that is compiled without support for 'avx2'
15:53:55         __alpha =  _mm256_broadcastss_ps(_mm_load_ss(alpha));
15:53:55                    ^
15:53:55 ../kernel/x86_64/saxpy_microk_skylakex-2.c:60:3: error: always_inline function '_mm256_storeu_ps' requires target feature 'avx', but would be inlined into function 'saxpy_kernel_16' that is compiled without support for 'avx'
15:53:55                 _mm256_storeu_ps(&y[i +  0], _mm256_loadu_ps(&y[i +  0]) + __alpha * _mm256_loadu_ps(&x[i +  0]));
15:53:55                 ^
15:53:55 ../kernel/x86_64/saxpy_microk_skylakex-2.c:60:32: error: always_inline function '_mm256_loadu_ps' requires target feature 'avx', but would be inlined into function 'saxpy_kernel_16' that is compiled without support for 'avx'
15:53:55                 _mm256_storeu_ps(&y[i +  0], _mm256_loadu_ps(&y[i +  0]) + __alpha * _mm256_loadu_ps(&x[i +  0]));
```

**Comment by isuruf** [comment]
Can you run `clang --version`?

**Comment by martin-frbg** [comment]
~~That looks more like an AVX2 problem, though perhaps NO_AVX512 would mask it somehow.~~
For gcc (and gfortran, if used), Makefile.x86_64 already adds either `-march=skylake-avx512` or `-mavx2` automatically as required, I did not observe that this is also required for clang (now ?)
EDIT: the -march=skylake-avx512 gets added for any compiler, only the -mavx2 on Haswell is limited to gcc

**Comment by zbeekman** [comment]
@isuruf 
> Can you run `clang --version`?

Included in my original post:
> Apple clang version 11.0.0 (clang-1100.0.33.17)

**Comment by isuruf** [comment]
@zbeekman, does Apple clang support `-fopenmp` now?

**Comment by zbeekman** [comment]
Yes, looks like it:

```
$ clang --help

# ...

  -fobjc-weak             Enable ARC-style weak references in Objective-C
  -fopenmp-simd           Emit OpenMP code only for SIMD-based constructs.
  -fopenmp-targets=<value>
                          Specify comma-separated list of triples OpenMP offloading targets to be supported
  -fopenmp                Parse OpenMP pragmas and generate parallel code.
  -foptimization-record-file=<value>
                          Specify the file name of any generated YAML optimization record
  -foptimization-record-passes=<value>
                          Only include passes which match a specified regular expression in the generated optimization record (by default, include all passes)
  -fpack-struct=<value>   Specify the default maximum struct packing alignment
  -fpascal-strings        Recognize and construct Pascal-style string literals
```

**Comment by isuruf** [comment]
Weird. Here's what I get,

```
osx:~ isuru$ clang --version
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin19.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
osx:~ isuru$ clang -fopenmp test.c
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
```

**Comment by zbeekman** [comment]
I think you need to do something like what is described here: https://iscinumpy.gitlab.io/post/omp-on-high-sierra/

**Comment by zbeekman** [comment]
Also, didn't realize you wanted the full output of `--version`:
```
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by isuruf** [comment]
> I think you need to do something like what is described here: https://iscinumpy.gitlab.io/post/omp-on-high-sierra/

Yes, but the logs you gave doesn't use the `-Xcompiler` trick which made me think that you are using a different clang.

**Comment by zbeekman** [comment]
The following homebrew packages have a dependency on `libomp` which indicates that they use OpenMP with Apple Clang:

- cryfs
- faiss
- imagemagick
- libraw
- libtorch
- lightgbm
- ngt
- rpm
- siril

These are good candidates to look at to see how other build systems do this.

Looking at `cryfs` it appears that they are explicitly setting these compiler flags:
```
-Xpreprocessor -fopenmp -I/usr/local/opt/libomp/include
```
and explicitly telling their build system to link against `/usr/local/opt/libomp/lib/libomp.dylib`. 

@isuruf 
> Yes, but the logs you gave doesn't use the `-Xcompiler` trick which made me think that you are using a different clang.

Forgive me, but I am a bit confused here. We are definitely building with AppleClang. The flags passed to the compiler are determined by and encoded in OpenBLAS' build system, unless we need to patch/override them. The only "special" things homebrew is doing in the OpenBLAS with Clang formula to enable OpenMP are:

1. Creating a dependency on `libomp` so that it is present
2. Setting `USE_OPENMP=1` in the environment before calling OpenBLAS' make

I just double checked, and I'm a bit surprised that the OpenBLAS I just built with clang does not appear to link `libomp` at all:
```
$  brew linkage openblas
System libraries:
  /usr/lib/libSystem.B.dylib
Homebrew libraries:
  /usr/local/lib/gcc/9/libgcc_s.1.dylib (gcc)
  /usr/local/opt/gcc/lib/gcc/9/libgfortran.5.dylib (gcc)
  /usr/local/opt/gcc/lib/gcc/9/libgomp.1.dylib (gcc)
  /usr/local/opt/gcc/lib/gcc/9/libquadmath.0.dylib (gcc)
Dependencies with no linkage:
  libomp
```

So while this discussion of OpenMP seems orthogonal to the AVX512/ARM issue, it may still be important since I see linkage against `libgomp` and not `libomp`.

Should I open a new issue to track this? Or is there an environment variable we should be setting to get Make to pass the required OpenMP flags to clang?

**Comment by isuruf** [comment]
Can you run,
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -c -O2 -DMAX_STACK_ALLOC=2048 -DEXPRECISION -fopenmp -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=6 -DMAX_PARALLEL_NUMBER=1 -DVERSION=\"0.3.8\" -DASMNAME=_saxpy_k_SKYLAKEX -DASMFNAME=_saxpy_k_SKYLAKEX_ -DNAME=saxpy_k_SKYLAKEX_ -DCNAME=saxpy_k_SKYLAKEX -DCHAR_NAME=\"saxpy_k_SKYLAKEX_\" -DCHAR_CNAME=\"saxpy_k_SKYLAKEX\" -DNO_AFFINITY -DTS=_SKYLAKEX -I. -DBUILD_KERNEL -DTABLE_NAME=gotoblas_SKYLAKEX -march=skylake-avx512 -UDOUBLE  -UCOMPLEX -UCOMPLEX -UDOUBLE kernel/x86_64/saxpy.c -o saxpy_k_SKYLAKEX.o -v
```
and send the output?

**Comment by zbeekman** [comment]
@isuruf no, because the skylake machine is our CI bot/infra in MacStadium. My local machine is Haswell, and I could remove the NO_AVX512 variable and build locally, but I won't have time for a bit to get to this. I've spent more of my day on this already than I should. But if it would be useful to you I can rebuild locally to trigger the same failure, send you the logs and you can then give me the command you want me to test drive.

**Comment by isuruf** [comment]
> But if it would be useful to you I can rebuild locally to trigger the same failure, send you the logs and you can then give me the command you want me to test drive.

Sure. Let me know if you can reproduce locally and send me the logs.

**Comment by zbeekman** [comment]
I have reproduced locally before, but isn't the issue reported here unrelated to OpenMP? I want to verify OpenMP is working in the clang based build for sure, but I also want to make sure the ARM/AVX512 problem is addressed, if possible.

Honestly, the OpenMP issue is probably a bigger problem if the code is not compiling with threading properly enabled, so I'll try to improve the Homebrew formula test to verify OpenMP functionality too, and if that's broken I'll check in here about whether you want a new separate issue for OpenMP with clang in addition to this issue about ARM instructions being generated unless the NO_AVX512 variable is set.

Is there a small example code you could point me to, or copy/paste that exercises multithreaded OpenBLAS?

**Comment by isuruf** [comment]
> I'll check in here about whether you want a new separate issue for OpenMP with clang in addition to this issue about ARM instructions being generated unless the NO_AVX512 variable is set.

This issue is not about ARM instructions. This is about a compiler issue with clang as @martin-frbg mentioned. I'd like to see the error again with verbose to see what the issue of the compiler is. I can't reproduce this issue without homebrew, so if you can run the failing command line with `-v`, then that'll be helpful.

**Comment by zbeekman** [comment]
> This issue is not about ARM instructions.

Derp, you're right. I was conflating this issue with GCC-9 failing with OpenBLAS 0.3.8... I'll get the output with the verbose flag added as soon as I can.

It would still be good to have a small example code that tests OpenMP functionality. I'll hunt through the test sweet to see if I can find anything short and sweet.

**Comment by martin-frbg** [comment]
Err, why are you two going off on a tangent about OpenMP now ? The only issue that I can see is that the Apple clang either does not like -march=skylakex-avx512, or wants to see -march=avx2 as well (which could be hacked into Makefile.x86_64 or Makefile.rule or CFLAGS or whatever for a quick test)

**Comment by isuruf** [comment]
Sorry, that was my fault. I was confused by the `-fopenmp` flag being present in Apple clang.

**Comment by zbeekman** [comment]
@martin-frbg 
That was my initial thought...

As an aside I have developed concerns about the changes I'm proposing to how Homebrew builds OpenBLAS and not seeing it link libomp... but I can test that on my own.

**Comment by martin-frbg** [comment]
With -fopenmp it should link libomp in the end automatically - let's see if/when we get that far. (If it starts missing omp functions at that point, I may have broken it with my recent PGI-related fixes..)

**Comment by zbeekman** [comment]
Just FYI, after some discussion with other maintainers, we have concluded that it does not make sense to switch away from GCC for OpenBLAS. The GCC dependency is needed already for Fortran and there are serious concerns about mixing OpenMP libraries that using native Clang with GFortran would cause. I suspect that this issue is present with GCC-9 in addition to clang, and will try to confirm shortly that this is the case.

**Comment by zbeekman** [comment]
@isuruf @martin-frbg I can confirm similar problems if I remove `NO_AVX512=1` and build on macOS 10.14.6 (Mojave) with GCC 9. Here is a sample log output where I see the failure:

```
gcc-9 -O2 -DMAX_STACK_ALLOC=2048 -DEXPRECISION -m128bit-long-double -fopenmp -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DMAX_PARALLEL_NUMBER=1 -DVERSION=\"0.3.9.dev\" -DASMNAME=_sgemm_otcopy_SKYLAKEX -DASMFNAME=_sgemm_otcopy_SKYLAKEX_ -DNAME=sgemm_otcopy_SKYLAKEX_ -DCNAME=sgemm_otcopy_SKYLAKEX -DCHAR_NAME=\"sgemm_otcopy_SKYLAKEX_\" -DCHAR_CNAME=\"sgemm_otcopy_SKYLAKEX\" -DNO_AFFINITY -DTS=_SKYLAKEX -I.. -DBUILD_KERNEL -DTABLE_NAME=gotoblas_SKYLAKEX -march=skylake-avx512 -UDOUBLE  -UCOMPLEX -c -UDOUBLE -UCOMPLEX ../kernel/x86_64/../generic/gemm_tcopy_4.c -o sgemm_otcopy_SKYLAKEX.o
gcc-9 -O2 -DMAX_STACK_ALLOC=2048 -DEXPRECISION -m128bit-long-double -fopenmp -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DMAX_PARALLEL_NUMBER=1 -DVERSION=\"0.3.9.dev\" -DASMNAME=_sgemm_beta_SKYLAKEX -DASMFNAME=_sgemm_beta_SKYLAKEX_ -DNAME=sgemm_beta_SKYLAKEX_ -DCNAME=sgemm_beta_SKYLAKEX -DCHAR_NAME=\"sgemm_beta_SKYLAKEX_\" -DCHAR_CNAME=\"sgemm_beta_SKYLAKEX\" -DNO_AFFINITY -DTS=_SKYLAKEX -I.. -DBUILD_KERNEL -DTABLE_NAME=gotoblas_SKYLAKEX -march=skylake-avx512 -UDOUBLE  -UCOMPLEX -c -UDOUBLE -UCOMPLEX ../kernel/x86_64/sgemm_beta_skylakex.c -o sgemm_beta_SKYLAKEX.o
In file included from /usr/local/Cellar/gcc/9.2.0_3/lib/gcc/9/gcc/x86_64-apple-darwin18/9.2.0/include/immintrin.h:55,
                 from ../kernel/x86_64/sgemm_kernel_16x4_skylakex_2.c:379:
../kernel/x86_64/sgemm_direct_skylakex.c: In function 'sgemm_kernel_direct':
/usr/local/Cellar/gcc/9.2.0_3/lib/gcc/9/gcc/x86_64-apple-darwin18/9.2.0/include/avx512fintrin.h:310:1: error: inlining failed in call to always_inline '_mm512_setzero_ps': target specific option mismatch
  310 | _mm512_setzero_ps (void)
      | ^~~~~~~~~~~~~~~~~
In file included from ../kernel/x86_64/sgemm_kernel_16x4_skylakex_2.c:380:
../kernel/x86_64/sgemm_direct_skylakex.c:16:55: note: called from here
   16 | #define DECLARE_RESULT_512(N,M) __m512 result##N##M = _mm512_setzero_ps()
      |                                                       ^~~~~~~~~~~~~~~~~~~
../kernel/x86_64/sgemm_direct_skylakex.c:89:94: note: in expansion of macro 'DECLARE_RESULT_512'
   89 |    DECLARE_RESULT_512(0, 3);    DECLARE_RESULT_512(1, 3);       DECLARE_RESULT_512(2, 3);    DECLARE_RESULT_512(3, 3);
      |                                                                                              ^~~~~~~~~~~~~~~~~~
In file included from /usr/local/Cellar/gcc/9.2.0_3/lib/gcc/9/gcc/x86_64-apple-darwin18/9.2.0/include/immintrin.h:55,
                 from ../kernel/x86_64/sgemm_kernel_16x4_skylakex_2.c:379:
/usr/local/Cellar/gcc/9.2.0_3/lib/gcc/9/gcc/x86_64-apple-darwin18/9.2.0/include/avx512fintrin.h:310:1: error: inlining failed in call to always_inline '_mm512_setzero_ps': target specific option mismatch
  310 | _mm512_setzero_ps (void)
      | ^~~~~~~~~~~~~~~~~
In file included from ../kernel/x86_64/sgemm_kernel_16x4_skylakex_2.c:380:
../kernel/x86_64/sgemm_direct_skylakex.c:16:55: note: called from here
   16 | #define DECLARE_RESULT_512(N,M) __m512 result##N##M = _mm512_setzero_ps()
      |                                                       ^~~~~~~~~~~~~~~~~~~
../kernel/x86_64/sgemm_direct_skylakex.c:89:65: note: in expansion of macro 'DECLARE_RESULT_512'
   89 |    DECLARE_RESULT_512(0, 3);    DECLARE_RESULT_512(1, 3);       DECLARE_RESULT_512(2, 3);    DECLARE_RESULT_512(3, 3);
      |                                                                 ^~~~~~~~~~~~~~~~~~
In file included from /usr/local/Cellar/gcc/9.2.0_3/lib/gcc/9/gcc/x86_64-apple-darwin18/9.2.0/include/immintrin.h:55,
                 from ../kernel/x86_64/sgemm_kernel_16x4_skylakex_2.c:379:
/usr/local/Cellar/gcc/9.2.0_3/lib/gcc/9/gcc/x86_64-apple-darwin18/9.2.0/include/avx512fintrin.h:310:1: error: inlining failed in call to always_inline '_mm512_setzero_ps': target specific option mismatch
  310 | _mm512_setzero_ps (void)
      | ^~~~~~~~~~~~~~~~~
In file included from ../kernel/x86_64/sgemm_kernel_16x4_skylakex_2.c:380:
../kernel/x86_64/sgemm_direct_skylakex.c:16:55: note: called from here
   16 | #define DECLARE_RESULT_512(N,M) __m512 result##N##M = _mm512_setzero_ps()
      |                                                       ^~~~~~~~~~~~~~~~~~~
../kernel/x86_64/sgemm_direct_skylakex.c:89:33: note: in expansion of macro 'DECLARE_RESULT_512'
   89 |    DECLARE_RESULT_512(0, 3);    DECLARE_RESULT_512(1, 3);       DECLARE_RESULT_512(2, 3);    DECLARE_RESULT_512(3, 3);
      |                                 ^~~~~~~~~~~~~~~~~~
```

I see `-march=skylake-avx512` being passed in some places, and defines being set for skylake and zen on a Haswell iMac.

**Comment by zbeekman** [comment]
(FYI, the previous build was using the latest commit on develop, c5bbfd8fee066e9fc68aa84e71afbb67b2dcb4f3)

**Comment by martin-frbg** [comment]
"defines being set for skylake and zen on a haswell" would be normal for a DYNAMIC_ARCH build, where the march=skylake-avx512 option would only be passed when building the kernel files for SkylakeX. 
The error message is what one would expect if -march=skylake-avx512 had been omitted (#2377 when it was not getting set in the cmake build) but your log clearly shows it.

The problem does not appear to be reproducible on Linux.

**Comment by martin-frbg** [comment]
@zbeekman if this is still a problem with 0.3.9, could you please upload a build log along with the config.h and Makefile.conf generated at the start of the build ?
