### ISSUE TITLE
Recognize X-Gene arm64 processors

### ISSUE THREAD

**Issue by isuruf** [xianyi/OpenBLAS#2434]
Some info,
```
processor       : 31
BogoMIPS        : 80.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer : 0x50
CPU architecture: 8
CPU variant     : 0x3
CPU part        : 0x000
CPU revision    : 2
```

@vielmetti or I can give a SSH access to a server https://en.wikichip.org/wiki/ampere_computing/emag/8180 if needed.

**Comment by martin-frbg** [comment]
I assume this (sort of) works as TARGET=ARMV8 already?

**Comment by isuruf** [comment]
Yes. I was using a DYNAMIC_ARCH=1 TARGET=ARMV8 and it gives a warning in verbose mode that the processor is not recognized.

**Comment by martin-frbg** [comment]
Quick first stab at supporting it (without the DYNAMIC_ARCH and cmake bits so far) is in #2437 but it is not even compile-tested of course.

**Comment by vielmetti** [comment]
For reference, see also

https://amperecomputing.com/wp-content/uploads/2019/01/Lenovo_ThinkSystem_HR330A_20190118.pdf -- OEM system by Lenovo with this part

https://amperecomputing.com/wp-content/uploads/2019/01/eMAG8180_PB_v0.5_20180914.pdf - eMAG 8180 product brief with details of cache sizes etc.

**Comment by martin-frbg** [comment]
It occured to me that it might be interesting to see if/how it behaves as TARGET=THUNDERX2T99, at least the general hardware specs look superficially similar ?

**Comment by isuruf** [comment]
@martin-frbg, what benchmark should I run?

**Comment by martin-frbg** [comment]
benchmark/dgemm.goto or the mt-dgemm from https://gitlab.com/arm-hpc/packages/-/wikis/packages/dgemm - however on rereading the earlier discussions in #1854 it is probably not half as good an idea as I first thought.
