### ISSUE TITLE
0.3.8 doesn't compile for NumPy; the next best known commit deserves a tag

### ISSUE THREAD

**Issue by mattip** [xianyi/OpenBLAS#2445]
I was all set to [update NumPy to 0.3.8](https://github.com/MacPython/openblas-libs/pull/22#issuecomment-590945917), but gh-2405 and gh-2407 mean 0.3.8 fails to build on s380x. Is there a known-good-commit I can use instead? It would be enough to just tag it 0.3.8a or, a little less desirable, tell me what hash to use. I am getting [a segfault](MacPython/numpy-wheels#73) (the last commit there) with avx512 and 32-bit linux, but maybe one of the commits leading up to 0.3.8 fixed it.

**Comment by martin-frbg** [comment]
Can you try with current develop (ddcbed6) ? Hopefully 0.3.9 will be out in a week

**Comment by mattip** [comment]
> Hopefully 0.3.9 will be out in a week

Cool, that would be the best. Closing. I will try ddcbed6 and if there are problems open a new issue.
