### ISSUE TITLE
Some problem about build for armv7

### ISSUE THREAD

**Issue by KobayashiLiu** [xianyi/OpenBLAS#2470]
ur readme file is a fucking shit.

**Comment by martin-frbg** [comment]
Are you seriously expecting any help with that attitude ?

**Comment by brada4** [comment]
@KobayashiLiu I think your request was already answered here: https://github.com/kaldi-asr/kaldi/issues/3965

**Comment by KobayashiLiu** [comment]
> 
> 
> Are you seriously expecting any help with that attitude ?

No any help to ask for, Just KICK YOUR ASS because of YOUR FUCKING README FILE

**Comment by martin-frbg** [comment]
That README has been like this for some f....ing fifteen years. Please create a pull request if you have any improvements to contribute
