### ISSUE TITLE
how to build a dll with CMAKE GUI and MS Visual Studio

### ISSUE THREAD

**Issue by jbensabat** [xianyi/OpenBLAS#2473]
Hi 
I have managed to build openblas with CMake GUI and MS Visual studio 
the resulting workspace creates a static library 
how could it build a dll ?

best
jac

**Comment by martin-frbg** [comment]
Add BUILD_SHARED_LIBS=ON to your options in the Cmake GUI

**Comment by jbensabat** [comment]
Thanks

Sent from my iPhone

On 1 Mar 2020, at 19:22, Martin Kroeker <notifications@github.com> wrote:

﻿

Add BUILD_SHARED_LIBS=ON to your options in the Cmake GUI
