### ISSUE TITLE
unresolved external symbol dpotrf_ on Windows

### ISSUE THREAD

**Issue by thamht4190** [xianyi/OpenBLAS#2492]
Hi,
I can build OpenBLAS on Windows with conda following your guide: https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-in-Microsoft-Visual-Studio. But when linking with Blaze (https://bitbucket.org/blaze-lib/blaze) and use `blaze::llh()` and `blaze::eigen()` methods, I got the linking issue:
```
error: LNK2019: unresolved external symbol dpotrf_ referenced in function "void __cdecl blaze::llh<class blaze::DynamicMatrix<double,0>,0,class blaze::DynamicMatrix<double,0>,0>(class blaze::DenseMatrix<class blaze::DynamicMatrix<double,0>,0> const &,class blaze::DenseMatrix<class blaze::DynamicMatrix<double,0>,0> &)" (??$llh@V?$DynamicMatrix@N$0A@@blaze@@$0A@V12@$0A@@blaze@@YAXAEBV?$DenseMatrix@V?$DynamicMatrix@N$0A@@blaze@@$0A@@0@AEAV10@@Z)
error: LNK2019: unresolved external symbol dgeev_ referenced in function "void __cdecl blaze::geev_backend<class blaze::DynamicMatrix<double,0>,0,class blaze::DynamicVector<class std::complex<double>,0>,0>(class blaze::DenseMatrix<class blaze::DynamicMatrix<double,0>,0> &,class blaze::DenseVector<class blaze::DynamicVector<class std::complex<double>,0>,0> &)" (??$geev_backend@V?$DynamicMatrix@N$0A@@blaze@@$0A@V?$DynamicVector@V?$complex@N@std@@$0A@@2@$0A@@blaze@@YAXAEAV?$DenseMatrix@V?$DynamicMatrix@N$0A@@blaze@@$0A@@0@AEAV?$DenseVector@V?$DynamicVector@V?$complex@N@std@@$0A@@blaze@@$0A@@0@@Z)
```
It seems these functions are implemented in fortran and not counted in cmake scripts while building openblas lib. Sorry I don't have any experience of fortran, just cpp. I'm using Windows 10, MSVC 2017 Win64.

Can you please help? Thanks in advance!

**Comment by martin-frbg** [comment]
Do you have a fortran compiler installed on your system ? Without it you will only get the BLAS functions, and what you are currently missing is technically LAPACK (which we import from its reference implementation that happens to be written in fortran).

**Comment by martin-frbg** [comment]
If you followed the steps for installing with conda, it should have installed the fortran compiler named `flang` (third command under item 4. there). Did you receive any error messages at that point ?
 Then in step 6 the last line (running cmake to configure the project) contains the parameter `-DCMAKE_Fortran_COMPILER=flang` to tell cmake to use this for the fortran parts of the code. Perhaps you mistyped there - I think the mixed case "Fortran" among all the capital letters can be a source of mistakes, but as this is a builtin cmake option we probably cannot change its naming.

**Comment by thamht4190** [comment]
@martin-frbg Thanks for response very quickly. For your doubt about mistyping: I've copied exactly what the command in the guide, I didn't type them. I will rebuild again on Monday and send you the commands I use and the build log as well, so we can see clearly. I'm very happy that there is an issue somewhere, not unsupported one ;)

**Comment by thamht4190** [comment]
@martin-frbg Here is my build log: https://gist.github.com/thamht4190/2e8f5630640ac61807825f46e077c33a. Because the step "cmake --build . --config Release" produces a lot of logs, I separate it into a file "openblas_cmake_build.txt". Can you please check it out?
I'm building openblas at this commit:
```
commit 33f76a6c378681ac2af76b20e55ff682191a1937 (HEAD, tag: v0.3.9, origin/release-0.3.0)
Author: Martin Kroeker <martin@ruby.chemie.uni-freiburg.de>
Date:   Mon Mar 2 00:10:20 2020 +0100
```

**Comment by thamht4190** [comment]
@martin-frbg I found the problem in my project config. I didn't link openblas.lib in executable file, only for some libs. Sorry! Thanks for your time!
