### ISSUE TITLE
OpenBLAS 0.3.9 build segfault on ARM64 + 64-bit integer support

### ISSUE THREAD

**Issue by tylerjereddy** [xianyi/OpenBLAS#2497]
We've been observing this segfault for a while now, so it is not specific to `0.3.9`.

Invocation line: 
`make DYNAMIC_ARCH=1 USE_OPENMP=0 NUM_THREADS=64 BINARY=64 INTERFACE64=1 SYMBOLSUFFIX=64_ OBJCONV=/io/objconv/objconv`

Link to build/failure log: https://travis-ci.org/MacPython/openblas-libs/jobs/659863204?utm_medium=notification&utm_source=github_status

Summary of failure:

```
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0xffff9b1509ab
#1  0xffff9b14fa1f
#2  0xffff9b2c65b7
#3  0xbe80d4
make[1]: *** [level1] Segmentation fault (core dumped)
make[1]: *** Waiting for unfinished jobs....
make: *** [tests] Error 2
```

Example PR exhibiting the segfault: https://github.com/MacPython/openblas-libs/pull/26

If you'd like me to try some things let me know. Thanks!

**Comment by tylerjereddy** [comment]
To be clear, I have no evidence that this build **ever** worked, since the scientific Python ecosystem is preparing to support a much wider array of platforms & this is one of the new ones. So just looking for suggestions :)

**Comment by isuruf** [comment]
Can you run a verbose build?

**Comment by brada4** [comment]
`make` should emit crashing commands. At the point it crashes it is not any of openblas code, it is at the end of lapack build, it could be `ar` or `gcc`

**Comment by martin-frbg** [comment]
Crash is in the sdot section of the sblat2 test.

**Comment by martin-frbg** [comment]
Turns out INTERFACE64=1 was never translated into the appropriate fortran compiler option. Should be fixed now for arm64, but the same problem is likely to exist on other non-x86 architectures as well. ISTR this used to be handled in a common Makefile section where it interfered with some compilers so got thrown out - I still need to look into this.

**Comment by tylerjereddy** [comment]
Cool, thanks for the work here!
