### ISSUE TITLE
Problem installing OpenBLAS

### ISSUE THREAD

**Issue by UfrancoU** [xianyi/OpenBLAS#2499]
Hi all,

 My name is Felipe. I am installing software (Trilinos among others) that builds and depends on OpenBLAS.
  It is failing when building Trilinos, with this message:
      
    Processing enabled TPL: MPI (enabled explicitly, disable with -DTPL_ENABLE_MPI=OFF)
Processing enabled TPL: BLAS (enabled by TeuchosNumerics, disable with -DTPL_ENABLE_BLAS=OFF)
-- Searching for libs in BLAS_LIBRARY_DIRS='/home/Felipe/BIGSOFTWARE/candi/OpenBLAS-0.2.20/lib'
-- Searching for a lib in the set "blas blas_win32":
--   Searching for lib 'blas' ...
--   Searching for lib 'blas_win32' ...
-- ERROR: Did not find a lib in the lib set "blas blas_win32" for the TPL 'BLAS'!
-- ERROR: Could not find the libraries for the TPL 'BLAS'!

Nevertheless, my installation script orders the installation of OpenBLAS beforehand. But I am not sure whether that installation succeeded. If I go into the logfile, I see this:

   make[1]: Leaving directory `/home/Felipe/BIGSOFTWARE/candi/tmp/build/OpenBLAS-0.2.20/exports'
 OpenBLAS build complete. (BLAS CBLAS LAPACK LAPACKE)

  OS               ... Linux
  Architecture     ... x86_64
  BINARY           ... 64bit
  C compiler       ... GCC  (command line : mpicc)
  Fortran compiler ... GFORTRAN  (command line : mpif90)
  Library Name     ... libopenblas_sandybridgep-r0.2.20.a (Multi threaded; Max num-threads is 24)

To install the library, you can run "make PREFIX=/path/to/your/installation install".

make -j 24 -f Makefile.install install
make[1]: Entering directory `/home/Felipe/BIGSOFTWARE/candi/tmp/build/OpenBLAS-0.2.20'
make[1]: warning: -jN forced in submake: disabling jobserver mode.
Generating openblas_config.h in /home/Felipe/BIGSOFTWARE/candi/OpenBLAS-0.2.20/include
Generating f77blas.h in /home/Felipe/BIGSOFTWARE/candi/OpenBLAS-0.2.20/include
Generating cblas.h in /home/Felipe/BIGSOFTWARE/candi/OpenBLAS-0.2.20/include
Copying LAPACKE header files to /home/Felipe/BIGSOFTWARE/candi/OpenBLAS-0.2.20/include
Copying the static library to /home/Felipe/BIGSOFTWARE/candi/OpenBLAS-0.2.20/lib
Copying the shared library to /home/Felipe/BIGSOFTWARE/candi/OpenBLAS-0.2.20/lib
Generating openblas.pc in /home/Felipe/BIGSOFTWARE/candi/OpenBLAS-0.2.20/lib/pkgconfig
Generating OpenBLASConfig.cmake in /home/Felipe/BIGSOFTWARE/candi/OpenBLAS-0.2.20/lib/cmake/openblas
Generating OpenBLASConfigVersion.cmake in /home/Felipe/BIGSOFTWARE/candi/OpenBLAS-0.2.20/lib/cmake/openblas
Install OK!
make[1]: Leaving directory `/home/Felipe/BIGSOFTWARE/candi/tmp/build/OpenBLAS-0.2.20'

So, it seems to have installed.

Nevertheless, if I go into the directory /candi/OpenBLAS-0.2.20 , I see 3 subdirs:
1. bin : which is empty !
2. include :
[Felipe@mu01 include]$ ls
cblas.h  f77blas.h  lapacke_config.h  lapacke.h  lapacke_mangling.h  lapacke_utils.h  openblas_config.h
3. lib
[Felipe@mu01 lib]$ ls
cmake          libopenblas_sandybridgep-r0.2.20.a   libopenblas.so    pkgconfig
libopenblas.a  libopenblas_sandybridgep-r0.2.20.so  libopenblas.so.0
..Where cmake and pkgconfig are subdirs.

It does not seem that the created directories are OK. I do not see a ‘long’ collection of libraries.

I am right? What should I do?

cheers many,
Felipe

**Comment by martin-frbg** [comment]
1. OpenBLAS is a library, so nothing getting installed in bin is correct.
2. The other parts of the installation look correct as well (except that 0.2.20 is two years out of date, current is 0.3.9). Probably your problem is that the dependent software is expecting to link against a libblas.so while OpenBLAS calls itself libopenblas.so. (Not sure what you meant with "long collection of libraries"). Try creating a symlink from libopenblas_sandybridge.so to libblas.so, and make sure that /opt/OpenBLAS is actually among the paths searched by the linker.

**Comment by brada4** [comment]
You will need lapack too. Createe liblapack.so just like libblas.so 
Best is to approach trilinos and fix their blas and lapack detection templates.

**Comment by UfrancoU** [comment]
Hi Martin and Andrew,

      Thank you sooooo much for your response.

      I am just learning all of this. My experience in CS is programming my own stuff and using codes whose installation was not too hard. These days, I am stuck trying to install Trilinos and Dealii.. on a deprived cluster.

      Should I just create a file that links the libopenblas to libblas?  Sort of giving an alternative name to libopenblas for Trilinos to recognize?  am i correct?

      What about a text file that contains the following?

      ln -s libopenblas.so libblas.so

In my lib directory I have several files and two directories, so I am not sure which one I should link, maybe all of them?:

[Felipe@mu01 lib]$ pwd
/home/Felipe/BIGSOFTWARE/candi/OpenBLAS-0.2.20/lib
[Felipe@mu01 lib]$ ls
cmake          libopenblas_sandybridgep-r0.2.20.a   libopenblas.so    pkgconfig
libopenblas.a  libopenblas_sandybridgep-r0.2.20.so  libopenblas.so.0

Also, should I write the link in a file? or should I add it in the installation shell script?
 
I appreciate your help,
cheers,
Felipe

**Comment by brada4** [comment]
```
cd lib
ln -s libopenblas.so libblas.so
ln -s libopenblas.so liblapack.so
```
not for this case but also one may need cblas and lapacke, and do same ritual araound .a static library file

**Comment by UfrancoU** [comment]
Hello Andrew, Martin and whom this may concern,

 

       Thanks a lot for your reply.

 

        Awesome ! it worked !

 

        I created the two symlinks from libopenblas to libblas and liblapack.. Then I rerun the installation from that point (which simply resumed from the last completed stage), and it started progressing .. it installed Trilinos ! then it installed petsc. It is now installing dealii, there are some warning issues, but I am 100% confident that the blas & lapack linking worked as expected.

 

        So good. Thank you veryveryvery much for your support.

 

cheers many,

Felipe

 

 

 
 

Sent: Wednesday, March 11, 2020 at 1:49 PM

**Comment by brada4** [comment]
Hi, could you open issue with trillinos, linking to this discussion? Probably you will get OpenBLAS update down the road too.

https://github.com/trilinos/Trilinos/issues/new/choose

Correct fix is adding openblas next to blas and blas-win32 lib names (adding amcl, atlas and mkl would not hurt either)

@martin-frbg please clean this note from post and the post above ;-)

**Comment by UfrancoU** [comment]
Hi Andrew,

 

         Thanks for folowing up, and thanks for contributing to a broader understanding of these issues. This is all helpful.

 

         I am thinking on how to explain the issue..

 

         It happens that I finally installed Trilinos and Openblas, and I did this using a script named candi , which is a dealii installer.. but deal ii needs Trilinos..and so on..it's a chain.

 

         My point is that if someone installs OpenBLAS in a different way (as I have installed blas and lapack as standalone in past times), and then install Trilinos using a conventional linking to OPenBLAS, maybe, maybe the problem does not arise.

 

         So, I am not sure if this is  problem of Trilinos.. or is a problem in the way candi is written. I thnk it is the latter. I emailed one of candi developers but he was a bit puzzled with my problem, partly cause I was not explaining it well. After that I restudied my problem and I emailed you guys. Happily your advices worked perfectly. I have finished installing all my softwares.

 

what do you think?

 

cheers man,

Felipe


Sent: Thursday, March 12, 2020 at 5:44 PM

**Comment by brada4** [comment]
Easy - trilinos build builds (old) openblas, then other components dont find it....

**Comment by UfrancoU** [comment]
Done !
Million thanks !

**Comment by brada4** [comment]
You can fix the link in trilinos issue, here one question - would it have been helpful if this info (symlink trick) was in OpenBLAS FAQ, it is like 3rd time we write same for abother bug report.
I think as much as your initial problem it is solved here ok.

**Comment by martin-frbg** [comment]
Added to our FAQ now.
