### ISSUE TITLE
linktest.c:(.text.startup+0x6e47): undefined reference to `LAPACKE_csyr'

### ISSUE THREAD

**Issue by 0mid** [xianyi/OpenBLAS#250]
At the link stage of compilation using make, I get undefined reference errors to all `LAPACKE_` functions. Should linking be done against a particular library not mentioned in `GotoBLAS_02QuickInstall.txt`?

**Comment by physkets** [comment]
I too am seeing the same error message. I'm building using the following:

`make CC=/home/user/bin/gcc FC=/home/user/bin/gfortran NO_STATIC=1 NO_AFFINITY=1 USE_OPENMP=1 DYNAMIC_ARCH=0 TARGET=HASWELL NUM_THREADS=20 MAJOR_VERSION=3 libs shared`

I'm using a gcc 8.2.0 that I compiled in my home directory, and not the one that came with the system.

**Comment by physkets** [comment]
The issue does not occur when I do a static build:

`make CC=/home/user/bin/gcc FC=/home/user/bin/gfortran NO_STATIC=0 NO_AFFINITY=1 USE_OPENMP=1 DYNAMIC_ARCH=0 TARGET=HASWELL NUM_THREADS=20`

**Comment by martin-frbg** [comment]
@physkets I suspect the actual difference is in if you tell `make` to execute specific targets (`libs shared`) or if you do a complete build. (But linktest is only run to make sure that the dynamic library was built correctly, so you would not see it when building just the static library by setting NO_SHARED=1)
