### ISSUE TITLE
lapack.h move LAPACK_COMPLEX_CUSTOM section

### ISSUE THREAD

**Issue by XL64** [xianyi/OpenBLAS#2510]
Hello,

TO be able to build my C++ code with openblas 0.3.9 I needed to move the LAPACK_COMPLEX_CUSTOM section from lapack.h outstide the extern "C" { part of the header.

Regards,

XL.

**Comment by martin-frbg** [comment]
Ah, sorry. I probably trashed the earlier fix for this when I imported LAPACK 3.9.0 which introduced the separate lapack.h. Will push a PR later

**Comment by XL64** [comment]
Thanks

**Comment by martin-frbg** [comment]
Interestingly, this appears to be a different problem than what was addressed in #1992 earlier.
