### ISSUE TITLE
Q: Problems with replicating binary package perfomance

### ISSUE THREAD

**Issue by banderlog** [xianyi/OpenBLAS#2528]
Hi, I have found some strange things while tried to compile custom opencv+dldt build with OpenBLASS GEMM.

I used precompiled `libopenblas-0.2.20` that comes with Ubuntu 18.04 LTS and achieved very good results. Then I tried to repeat this result with newest OpenBLAS version (0.3.9) and even with original 0.2.20. 

I tried to compile it as suggested in in User Guide (with single `make`) with and without `gfortran`. Also I tried to compile it with `cmake` using different flags:

First version: `cmake --D BUILD_SHARED_LIBS=ON `

Last version:
```cmake
cmake -D BUILD_RELAPACK=ON \
            -D CMAKE_BUILD_TYPE=Release \
            -D NO_AFFINITY=ON \
            -D BUILD_SHARED_LIBS=ON \
            -D CMAKE_INSTALL_PREFIX=./OUT/ \
            -D CMAKE_INSTALL_FULL_INCLUDEDIR=./OUT/include/ \
            -D USE_THREAD=ON ..
```

But result `libopenblas.so.0` always was like 1\2 of original binary lib size and it's speed was 2 times slower (at best):

| OpenBLAS                   | Inference time (ms) | Lib size (MB) |
|------------------------|---------------------|---------------|
| 0.2.20 (src)        | 520                 | 13.7          |
| 0.3.9 (src)         | 160                 | 16.4          |
| 0.3.9 (src, RELAPACK)         | 140                 | 16.1          |
| 0.3.9 (src, without gfortran) | 160     | 3.9 |
| 0.2.20 (binary)| 60                  | 32            |

All experiments I made on Ubuntu 18.04 LTS multipass instance with ` Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz` (4 physical cores and Hyper-Threading, but I gave only 6 possible threads to ubuntu multipass  instance, it looks like 3 cores + HT ),  `gcc-7.5.0`, `gfortran-7.5.0`

What am I doing wrong?  
What are optimal parameters for maximum performance on Intel haswell x86_64 CPU?
What cmake flags were set for lib from Ubuntu repository?

Please help

**Comment by martin-frbg** [comment]
Size difference probably comes from the Ubuntu binary being a `DYNAMIC_ARCH=ON` build that contains optimized code for several cpu models with runtime selection, while your build includes only the code relevant for the particular cpu you built on. Speed difference could be related to different compiler options or different compiler version, or perhaps to the Ubuntu build using OpenMP (`USE_OPENMP=ON`) instead of plain pthreads with mutex locks for thread safety.
ReLAPACK and gfortran should be irrelevant if you really only use GEMM

**Comment by brada4** [comment]
Your CPU specs says you have 4 cores,

**Comment by banderlog** [comment]
@martin-frbg thx, I'll try to build it with OpenMP. How did you find out that they use that flag?

@brada4 sorry, 4 physical cores and Hyper-Threading

**Comment by brada4** [comment]
Answering for Martin:
https://packages.ubuntu.com/source/bionic/openblas
Get +debian+ tarball, there inside something named rules or so has the parameters they use, note that they add default lapack and dont use latest as included in OpenBLAS build. 

30+MB is DYNAMIC_ARCH 20-MB s for single arch 40+ is DUNAMIC_ARCH and DYNAMIC_OLDER together.

From me:
Try using exactly 8 or 4 cores or less. 2x regression rises both eyebrows.

I dont know if this applies - build with -lblas, then use openblas at runtime:
https://github.com/xianyi/OpenBLAS/wiki/faq#debianlts

**Comment by martin-frbg** [comment]
Actually svillemot mentioned it recently in another ticket, and OpenMP would require less of the quite heavy-handed locking that goes on in the code. (@brada4 I do not believe that the distribution package would have such a small value for NUM_THREADS that it would utilize less than the available number of (hyper)threads.)

**Comment by banderlog** [comment]
Hmm, from `rules` in `openblas_0.2.20+ds-4.debian.tar.xz`:

```cmake
MAKE_OPTIONS := NO_LAPACKE=1 NO_AFFINITY=1 USE_OPENMP=0 NO_WARMUP=1 CFLAGS="$(CPPFLAGS) $(CFLAGS)" FFLAGS="$(FFLAGS)"

# Avoid having -O2 automatically added (especially for DEB_BUILD_OPTIONS=noopt)
MAKE_OPTIONS += COMMON_OPT= FCOMMON_OPT=-frecursive

# Build generic package with hardcoded max number of threads of 64
GENERIC_OPTIONS := NUM_THREADS=64

# On x86 archs, enable dynamic arch selection
ENABLE_DYNAMIC_ARCHS := amd64 i386 kfreebsd-amd64 kfreebsd-i386
ifneq (,$(findstring $(DEB_HOST_ARCH),$(ENABLE_DYNAMIC_ARCHS)))
	GENERIC_OPTIONS += DYNAMIC_ARCH=1
endif
```

They did not use OpenMP and hardcoded NUM_THREADS

**Comment by brada4** [comment]
Any luck with their options?

**Comment by banderlog** [comment]
@brada4 yes, but only for 0.2.20
With this:
```
cmake -D NO_LAPACKE=1 \
      -D FCOMMON_OPT=-frecursive \
      -D NO_AFFINITY=1 \
      -D USE_OPENMP=0 \
      -D NO_WARMUP=1 \
      -D NUM_THREADS=64 \
      -D BUILD_SHARED_LIBS=ON \
      -D CMAKE_INSTALL_PREFIX=./OUT/ \
      -D CMAKE_INSTALL_FULL_INCLUDEDIR=./OUT/include/ ..
```
I achieved a 10.8MB lib with ~60ms inference speed (gfortran dependant):

```python
In [3]:  %timeit -n10 -r10 _ = net.forward()
59.3 ms ± 4.11 ms per loop (mean ± std. dev. of 10 runs, 10 loops each)

In [4]:  %timeit -n10 -r10 _ = net.forward()
60.6 ms ± 4.46 ms per loop (mean ± std. dev. of 10 runs, 10 loops each)

In [5]:  %timeit -n10 -r10 _ = net.forward()
65.1 ms ± 8.3 ms per loop (mean ± std. dev. of 10 runs, 10 loops each)

In [6]:  %timeit -n10 -r10 _ = net.forward()
71.1 ms ± 4.24 ms per loop (mean ± std. dev. of 10 runs, 10 loops each)

In [7]:  %timeit -n10 -r10 _ = net.forward()
67.8 ms ± 7.02 ms per loop (mean ± std. dev. of 10 runs, 10 loops each)

In [8]:  %timeit -n10 -r10 _ = net.forward()
71.3 ms ± 5.08 ms per loop (mean ± std. dev. of 10 runs, 10 loops each)

```

With OpenBLAS-0.3.9 a got 14.3MB lib with ~100ms Inference speed. But it has _huge_ variance:
```python
In [3]:  %timeit -n10 -r10 _ = net.forward()
158 ms ± 70.1 ms per loop (mean ± std. dev. of 10 runs, 10 loops each)

In [4]:  %timeit -n10 -r10 _ = net.forward()
190 ms ± 53.3 ms per loop (mean ± std. dev. of 10 runs, 10 loops each)

In [5]:  %timeit -n10 -r10 _ = net.forward()
The slowest run took 4.54 times longer than the fastest. This could mean that an intermediate result is being cached.
228 ms ± 87.5 ms per loop (mean ± std. dev. of 10 runs, 10 loops each)

In [6]:  %timeit -n10 -r10 _ = net.forward()
95.4 ms ± 5.98 ms per loop (mean ± std. dev. of 10 runs, 10 loops each)

In [7]:  %timeit -n10 -r10 _ = net.forward()
125 ms ± 40.8 ms per loop (mean ± std. dev. of 10 runs, 10 loops each)

In [8]:  %timeit -n10 -r10 _ = net.forward()
198 ms ± 55.5 ms per loop (mean ± std. dev. of 10 runs, 10 loops each)
```

Any thoughts why 0.3.9 is "slower" than 0.2.20 and why it has so high variance?

**UPD:**

I've compiled 0.3.9 with config as above, but added `-D GEMM_MULTITHREAD_THRESHOLD=64`, now it looks somewhat relevant (still 14.3MB):
```python
In [3]:  %timeit -n10 -r10 _ = net.forward()
57.1 ms ± 1.46 ms per loop (mean ± std. dev. of 10 runs, 10 loops each)

In [4]:  %timeit -n10 -r10 _ = net.forward()
61.1 ms ± 7.24 ms per loop (mean ± std. dev. of 10 runs, 10 loops each)

In [5]:  %timeit -n10 -r10 _ = net.forward()
74 ms ± 5.09 ms per loop (mean ± std. dev. of 10 runs, 10 loops each)

In [6]:  %timeit -n10 -r10 _ = net.forward()
73.7 ms ± 4.57 ms per loop (mean ± std. dev. of 10 runs, 10 loops each)

In [7]:  %timeit -n10 -r10 _ = net.forward()
78.2 ms ± 7.15 ms per loop (mean ± std. dev. of 10 runs, 10 loops each)

In [8]:  %timeit -n10 -r10 _ = net.forward()
74.8 ms ± 6.29 ms per loop (mean ± std. dev. of 10 runs, 10 loops each)
```

**Comment by brada4** [comment]
Thermal issues? I think there is slight code change towards more AVX2 in in/out copy routines around gemm.

If you set cpu governor to powersave (cpupower --set-frequency -g powersave) to rule those out, yes it will be slow, but lets see how it compares 0.2.20 vs 0.3.9
Thats laptop CPU, maybe AVX2 usage fixes frequency at (remarkably) lowest frequency.

**Comment by martin-frbg** [comment]
0.3.x has more of the (somewhat clumsy) locking to take care of various race conditions. Current develop branch should be better due to #2466

**Comment by brada4** [comment]
@banderlog if you compare `perf record` `perf report` - do you see that heavy locking load? Most locks yield syscalls that should grow in fresher version.

**Comment by banderlog** [comment]
Thank you for your help, guys :)

Using https://github.com/xianyi/OpenBLAS/commit/9f67d03d3b63a73af02a27c6cfe78b73acf16fd9 I was able to compile 4.18MB lib using this cmake:
```cmake
cmake -D NO_LAPACKE=1 \
      -D CMAKE_BUILD_TYPE=Release \
      -D NOFORTRAN=ON \
      -D BUILD_RELAPACK=OFF \
      -D NO_AFFINITY=1 \
      -D USE_OPENMP=0 \
      -D NO_WARMUP=1 \
      -D NUM_THREADS=64 \
      -D GEMM_MULTITHREAD_THRESHOLD=64 \
      -D BUILD_SHARED_LIBS=ON \
      -D CMAKE_INSTALL_PREFIX=./OUT/ ..
```

With best inference speed so far:
```python
In [3]:  %timeit -n10 -r10 _ = net.forward()
53.4 ms ± 1.35 ms per loop (mean ± std. dev. of 10 runs, 10 loops each)

In [4]:  %timeit -n10 -r10 _ = net.forward()
54 ms ± 2.27 ms per loop (mean ± std. dev. of 10 runs, 10 loops each)

In [5]:  %timeit -n10 -r10 _ = net.forward()
67.8 ms ± 5.48 ms per loop (mean ± std. dev. of 10 runs, 10 loops each)

In [6]:  %timeit -n10 -r10 _ = net.forward()
69.5 ms ± 4.8 ms per loop (mean ± std. dev. of 10 runs, 10 loops each)

In [7]:  %timeit -n10 -r10 _ = net.forward()
68.7 ms ± 4.54 ms per loop (mean ± std. dev. of 10 runs, 10 loops each)

In [8]:  %timeit -n10 -r10 _ = net.forward()
65.1 ms ± 7.51 ms per loop (mean ± std. dev. of 10 runs, 10 loops each)
```

And I think that you were right and I have some thermal issues as well.

**PS:** ` -D NOFORTRAN=ON` also shrinks size of 0.3.9 to 4.14MB without inference speed loss.

**Comment by martin-frbg** [comment]
> PS: -D NOFORTRAN=ON also shrinks size of 0.3.9 to 4.14MB without inference speed loss.

understandable as your code only uses the BLAS part of OpenBLAS, which is written in C and assembler. Fortran is required only for building the much larger set of linear algebra functions named LAPACK that sits on top of BLAS (and which OpenBLAS largely imports from the reference implementation that had its roots in the late 1980s).

**Comment by brada4** [comment]
Are you on some embedded system that 10MB of unused overload code really matters? 
If you want 3MB library with no performance, just compile netlib reference library.

**Comment by banderlog** [comment]
Just like keeping things rational.
