### ISSUE TITLE
cblas_somatcopy performance issues on Sandy Bridge

### ISSUE THREAD

**Issue by JoaoAlves95** [xianyi/OpenBLAS#2532]
Good Afternoon,

While comparing `cblas_somatcopy` against other approaches to compute an out-of-place matrix transpose I've noticed that its performance as serious issues. This approach is more than 10x slower than a SSE2 blocked implementation( https://stackoverflow.com/a/16743203/11486760) for large matrices, e.g. 2048x2048.

My main questions are: 
Does this function uses older vector libraries, like SSE2, when the CPU does not support AVX/AVX2? 
Does this function support multithreading? There is no performance difference when calling this function with `openblas_set_num_threads(1)` or `openblas_set_num_threads(4)`.

Thanks in advance for any useful insight!

My cpu: Intel Xeon E312xx (Sandy Bridge, IBRS update)

Code used:
```
openblas_set_num_threads(4);
/*init float matrix A and B*/
...
cblas_somatcopy(CblasRowMajor, CblasTrans, n, n, 1.0f, A, n, B, n);
```

Compiled with:
`gcc -static -Ioblas/include -Loblas/lib -o somatcopy somatcopy.c -lopenblas -lpthread
`

**Comment by martin-frbg** [comment]
This has already been noticed in #2232, but I have no idea yet why its fairly trivial implementation
would be particularly slow on Sandybridge (except that on newer systems, `-mavx2` gets added to the compiler flags automatically while on SB the compiler is on its own - just `-O2` by default).

**Comment by JoaoAlves95** [comment]
Sorry, failed to notice that issue while searching the similar list...

From previous testing with naive transpose operations I've never seen the compiler auto-vectorizing the trasnpose loop with operations like `sse_transpose4x4()`. I guess with `-O2` the compiler might vectorize some auxiliary loops but not the transpose itself.

Do you have any insight reggarding the multi-threading aspect?

Edit: Currently I can not test this operation with Intel-MKL, any idea on how does `cblas_somatcopy` performs in comparison to `mkl_somatcopy`?

**Comment by martin-frbg** [comment]
Not multithreaded - interface/omatcopy.c calling into kernel/arm/omatcopy_xx.c (omatcopy_rt.c in your case) without attempting to split the workload. And omatcopy_rt.c itself is a trivially simple implementation, just a nested loop without even an attempt to optimize for alpha == 1 or alpha == 0. This has all signs of a quick-and-dirty convenience function that nobody saw as a bottleneck.

**Comment by martin-frbg** [comment]
Also #1243 is relevant - somehow I lost track of that issue (and I even wrote to look into it "in the near future" at some point)

**Comment by martin-frbg** [comment]
The immediate problem on Sandybridge may be just (non-)use of AVX, all the other issues with the code nonwithstanding. On Haswell and newer, `-mavx2` is automatically added to the CFLAGS by Makefile.x86_64 around line 35, but there is no equivalent for Sandybridge. Could you try if adding something like
```
ifeq ($(CORE), SANDYBRIDGE)
ifeq ($(C_COMPILER), GCC)  
CCOMMON_OPT += -mavx
endif
endif
```
to Makefile.x86_64 leads to any noticeable improvement ?

**Comment by JoaoAlves95** [comment]
Just tested it. It shows no significant improvement in performance. I'm quite new to the AVX/SSE world, but if you take a look at `_MM_TRANSPOSE4_PS` (https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=transpo&expand=5948) it is easy to understand that matrices with side length different than a multiple of 4 requires padding. This operation is probably not auto-vectorized due to the extra amount of memory required.

**Comment by martin-frbg** [comment]
Thanks. That was just a quick stab in the dark, based on the earlier claims that performance of the exact same code on Haswell was markedly better. You are quite right that behaviour will largely depend on matrix dimensions.

**Comment by wjc404** [comment]
I tried to write an AVX-vectorized kernel of SOMATCOPY_RT. Here's the code. 
[somatcopy_rt_sandy.txt](https://github.com/xianyi/OpenBLAS/files/4391826/somatcopy_rt_sandy.txt)

I compiled it with -O2 flag by gcc-5.4.0 and tested it on a KVM (SKX CPU). Here's the result.
![Screenshot from 2020-03-27 13-37-13](https://user-images.githubusercontent.com/52632443/77727709-deb1e700-7035-11ea-8294-4331f3088c64.png)

I'll make it a PR, if this kernel performs better in most cases. Currently I cannot access avx-compatible computers without KVM, I would be grateful if someone can help test it.

**Comment by martin-frbg** [comment]
Actual Sandybridge HW has
```
Test omatcopy_rt with rows = 1978 and cols = 1961.
Reference C  implementation: 4.31e+02 M elements per second.
AVX-enhanced implementation: 7.23e+02 M elements per second.
Maxdiff between output matrices: 0.00e+00
Maxdiff between output matrices after subsequent alpha=zero runs: 0.00e+00

Test omatcopy_rt with rows = 3979 and cols = 3975.
Reference C  implementation: 3.97e+02 M elements per second.
AVX-enhanced implementation: 7.23e+02 M elements per second.
Maxdiff between output matrices: 0.00e+00
Maxdiff between output matrices after subsequent alpha=zero runs: 0.00e+00

Test omatcopy_rt with rows = 5980 and cols = 5989.
Reference C  implementation: 3.55e+02 M elements per second.
AVX-enhanced implementation: 7.24e+02 M elements per second.
Maxdiff between output matrices: 0.00e+00
Maxdiff between output matrices after subsequent alpha=zero runs: 0.00e+00

Test omatcopy_rt with rows = 7981 and cols = 7950.
Reference C  implementation: 3.34e+02 M elements per second.
AVX-enhanced implementation: 7.25e+02 M elements per second.
Maxdiff between output matrices: 0.00e+00
Maxdiff between output matrices after subsequent alpha=zero runs: 0.00e+00

Test omatcopy_rt with rows = 9982 and cols = 9964.
Reference C  implementation: 3.33e+02 M elements per second.
AVX-enhanced implementation: 7.26e+02 M elements per second.
Maxdiff between output matrices: 0.00e+00
Maxdiff between output matrices after subsequent alpha=zero runs: 0.00e+00
```

with gcc-4.7.2. Thanks.

**Comment by brada4** [comment]
Piledriver gcc-7.5.0
```
Test omatcopy_rt with rows = 1978 and cols = 1961.
Reference C  implementation: 1.02e+02 M elements per second.
AVX-enhanced implementation: 5.37e+02 M elements per second.
Maxdiff between output matrices: 0.00e+00
Maxdiff between output matrices after subsequent alpha=zero runs: 0.00e+00

Test omatcopy_rt with rows = 3979 and cols = 3975.
Reference C  implementation: 1.12e+02 M elements per second.
AVX-enhanced implementation: 5.38e+02 M elements per second.
Maxdiff between output matrices: 0.00e+00
Maxdiff between output matrices after subsequent alpha=zero runs: 0.00e+00

Test omatcopy_rt with rows = 5980 and cols = 5989.
Reference C  implementation: 1.06e+02 M elements per second.
AVX-enhanced implementation: 5.57e+02 M elements per second.
Maxdiff between output matrices: 0.00e+00
Maxdiff between output matrices after subsequent alpha=zero runs: 0.00e+00

Test omatcopy_rt with rows = 7981 and cols = 7950.
Reference C  implementation: 1.03e+02 M elements per second.
AVX-enhanced implementation: 5.62e+02 M elements per second.
Maxdiff between output matrices: 0.00e+00
Maxdiff between output matrices after subsequent alpha=zero runs: 0.00e+00

Test omatcopy_rt with rows = 9982 and cols = 9964.
Reference C  implementation: 7.94e+01 M elements per second.
AVX-enhanced implementation: 5.69e+02 M elements per second.
Maxdiff between output matrices: 0.00e+00
Maxdiff between output matrices after subsequent alpha=zero runs: 0.00e+00
```

EDIT `-march=native` turns "Reference C" case 4x slower than displayed.
EDIT2 in a VM on same cpu difference is a bit more dramatic than that and does not get influenced by C flags

**Comment by martin-frbg** [comment]
Not sure how/if it would be possible to get to the purported tenfold speed increase from there...

**Comment by brada4** [comment]
With forced telework everything is possible, like unrolling innermost loop etc.
Yes, makes no sense that virtualisation and march.native is so much worse

**Comment by MigMuc** [comment]
I have written a pure C version of the routine with 4x4 blocking. On Haswell systems it is ~4 times faster than the reference implementation. On a Sandybridge system using MingW64 compilers I observed only a factor of 2 with -O2 optimization (-mavx did not work, it segfaulted). I could not verify the AVX version of @wjc404 since it segfaulted on that system, too.
Here is the file:
[somatcopy_rt_4x4.txt](https://github.com/xianyi/OpenBLAS/files/4542090/somatcopy_rt_4x4.txt)

**Comment by MigMuc** [comment]
The stackoverflow link given above points to a 4x4 blocking implementation which is parallelized with OpenMP. Assuming a 4 core processor we get a factor of 8 on a SB system close to 10. Maybe proper alignement on that hardware is critical.

**Comment by brada4** [comment]
Not sure how do you implement SSE on current ARM processors.

**Comment by brada4** [comment]
Just spotted that you are running in a VM, SandyBridge has AVX, E3120 do not, go figure. Your /proc/cpuinfo can tell. Yes, compiler will be invoked with almost march=native for either CPU type and make alternative (compiler-)optimized code paths in case of DYNAMIC_ARCH compilation.

What hurts VM-s a lot is bad alignment, it is cool to say 2048x2048, that will align well, 2045x2049 wont, and misalignment hurts VM badly.

_matcopy does no computation, it is just beefed-up memcpy() from compute perspective, it should not get threaded.

Try this in patch to make your needed function better optimizeable:
```
diff --git a/kernel/arm/omatcopy_rt.c b/kernel/arm/omatcopy_rt.c
index 9d58350d..66796e6b 100644
--- a/kernel/arm/omatcopy_rt.c
+++ b/kernel/arm/omatcopy_rt.c
@@ -45,6 +45,19 @@ int CNAME(BLASLONG rows, BLASLONG cols, FLOAT alpha, FLOAT *a, BLASLONG lda, FLO
 
        aptr = a;
 
+       if (ldb==1) {
+                       for ( i=0; i<rows ; i++ )
+        {
+                bptr = &b[i];
+                for(j=0; j<cols; j++)
+                {
+                        bptr[j] = alpha * aptr[j];
+                }
+                aptr += lda;
+        }
+
+       } else {
+
        for ( i=0; i<rows ; i++ )
        {
                bptr = &b[i];
@@ -54,6 +67,7 @@ int CNAME(BLASLONG rows, BLASLONG cols, FLOAT alpha, FLOAT *a, BLASLONG lda, FLO
                }
                aptr += lda;
        }
+       }
 
        return(0);
```

What it does is to make inner loop vectorizeable for case where increment is 1, which means it is not one-cacheline prefetch + X cache reads, then X writes at compiler-unknown offset calculated at runtime.

It is not complete solution, complete one would need to pad start to cl alignment, but this works for 16xfload or 8xdouble sized rows.

**Comment by brada4** [comment]
Resulting file attached, should work fine with any openblas version you might have, then just rebuild with last parameters used, or do make clean, then build new one.
[kernel-arm-omatcopy_rt-c.txt](https://github.com/xianyi/OpenBLAS/files/4547852/kernel-arm-omatcopy_rt-c.txt)

**Comment by RajalakshmiSR** [comment]
@brada4 @MigMuc Do you have any plans to submit PR for your attached patches? Just trying to understand the reason why this was paused for a while.

**Comment by MigMuc** [comment]
I am not really used to the github workflow. I would suggest someone more familiarized with it, could make the PR.
Don't know though, what the actual state is.

**Comment by martin-frbg** [comment]
I'll make this into a PR, no problem, sorry for letting this slide. ISTR I did not observe the expected speedup but my setup may have been flawed.

**Comment by martin-frbg** [comment]
wjc404's AVX version and MigMuc's 4x4 blocked C built into wjc404's benchmark (rename .txt to .c)
[omatcopy_rt_bench.txt](https://github.com/xianyi/OpenBLAS/files/6029941/omatcopy_rt_bench.txt)
on i7_7500U MigMuc's code is twice as fast, while wjc404's is three times as fast - both codes currently lack special code paths for alpha=0.0 or alpha=1.0 .
on ARM64 (CortexA53/A72 locally, and I suspect Neoverse at drone.io), the speedup from MigMuc's code is about a factor of 4.
on EPYC (drone.io), speedup from MigMuc's code is "only" about a factor of 2, but wjc404's is six to eight times faster.
And I get about 5-fold  (4x4) and 7-fold (AVX) speedup on Sandybridge now, not sure why the first tests had much lower numbers. Merging the current version now, apologies to all involved and thanks to RajalakshmiSR for bringing this up again.
