### ISSUE TITLE
Compiled with no errors but the .out file cannot run

### ISSUE THREAD

**Issue by shujian1997** [xianyi/OpenBLAS#2535]
Hi, everyone,:
   I have met some problems when I use the OpenBLAS-dev in my ubuntu(version:12.04 LTS) . 
   I compiled the openblas as the manual said, and I succeed. The instruction I used to compile the OpenBLAS is that "`make CC=arm-linux-gnueabihf-gcc FC=arm-linux-gnueabihf-gfortran HOSTCC=gcc TARGET=CORTEXA9`"

But when I tried to use the openblas to compile the test.c which is offered by the manual, I met a problem. The instructions I used to compile the test.c is "`arm-linux-gnueabihf-gcc  -o test test.c -I /usr/local/openblas_a9/include -L /usr/local/openblas_a9/lib -lopenblas -lpthread -lgfortran`"   The result is it output a 7.9kb named "test" executable file and no errors is showed, but when i run it on my 4412 development board, the result is it cannot be found.

The reason I changed the compile instruction from "`gcc`" to "`arm-linux-gnueabihf-gcc`" is that when I use the "gcc", It will comeout errros like cannot find libopenblas.

I would very appreciate it if you can tell me where the problem is or inspire me. Thank you.

**Comment by shujian1997** [comment]
![image](https://user-images.githubusercontent.com/58925429/78121353-deeb2180-743d-11ea-9de7-3fb09d0ea884.png)
This is the resulting that when I run the output file in 4412 ARM development board.



![image](https://user-images.githubusercontent.com/58925429/78121704-4a34f380-743e-11ea-9dcf-c054fd0da045.png)

This is the instruction that I compile the test.c(that is just the same code with different name, I tried it in many version to avoid some mistakes)
And I have tried to -rpath  the ld-linux.so.3 to eliminate the warning, but the compiled file didn't change, so I think it's not the key of the problem.

![image](https://user-images.githubusercontent.com/58925429/78121661-3be6d780-743e-11ea-8ed6-a53b3c77f637.png)

This is the test.c


![image](https://user-images.githubusercontent.com/58925429/78122284-245c1e80-743f-11ea-9ec3-bd4344683c31.png)
This is something about the output file.

**Comment by martin-frbg** [comment]
The instructions you used to compile the test.c look correct (assuming you installed the arm openblas into /usr/local/openblas_a9) but they link the program dynamically. So the libopenblas.so you built needs to be available on your development system as well. (You can probably run `ldd test`on your development system to see what is missing. Unfortunately it could also be that the cross-compiling toolkit you installed on ubuntu does not match the software installed on your development board so that it does not even have the loader (the ld-linux.so) needed to start the test executable)

**Comment by shujian1997** [comment]
> The instructions you used to compile the test.c look correct (assuming you installed the arm openblas into /usr/local/openblas_a9) but they link the program dynamically. So the libopenblas.so you built needs to be available on your development system as well. (You can probably run `ldd test`on your development system to see what is missing. Unfortunately it could also be that the cross-compiling toolkit you installed on ubuntu does not match the software installed on your development board so that it does not even have the loader (the ld-linux.so) needed to start the test executable)

Thank you very much for the replying. I am so Sorry that I forget to mention a situation that  once I have compiled the OpenBLAS and compiled the test.c and the size of the output file is about 790KB, and it can actually run in the development system, but I am so pity and self-accusation that I forget the concrete instruction I used that time. What I remember is that I used the arm-linux-gnueabihf-gcc.   So the reason why occurs the different size of the output file is that  the way I link the file to program, maybe I should try to link it staticly?   Thanks again.

**Comment by shujian1997** [comment]
![image](https://user-images.githubusercontent.com/58925429/78124241-fd531c00-7441-11ea-9876-c612e0da9e0c.png)
When I choose to link the static library, it comes out some errors.

**Comment by martin-frbg** [comment]
Yes that would suggest that you linked it statically before, so something like `arm-linux-gnueabihf-gcc -o test test.c -I /usr/local/openblas_a9/include /usr/local/openblas_a9/libopenblas.a -lpthread -lgfortran` would probably work. (You will still need to link to libpthread and libgfortran, so these should hopefully be installed on your developer board already)

**Comment by shujian1997** [comment]
> Yes that would suggest that you linked it statically before, so something like `arm-linux-gnueabihf-gcc -o test test.c -I /usr/local/openblas_a9/include /usr/local/openblas_a9/libopenblas.a -lpthread -lgfortran` would probably work. (You will still need to link to libpthread and libgfortran, so these should hopefully be installed on your developer board already)

Thank you very much for your patient. I tried that instruction, and the output file still cannot run in my developer board, and the 4412 developer board tips the error that the output file cannot be found, although the file size has increased to around 57kb, so is this size correct when it link to a static library?  What should I check to find out the potential issues?   Thanks a lot for your patient again.

![image](https://user-images.githubusercontent.com/58925429/78132851-064aea00-7450-11ea-8338-4f2c0bcb3613.png)

**Comment by martin-frbg** [comment]
Make that `./test1` (the current directory may not be in your PATH where executables are looked up), if that does not work try if `ldd test1` gives any output. (Should look similar to this here from an arm64 system - a list of the things it is looking for on startup, with "not found" for any of them that are missing):
```
        linux-vdso.so.1 (0x0000007f8d8dd000)
        libgfortran.so.5 => /lib/aarch64-linux-gnu/libgfortran.so.5 (0x0000007f8d743000)
        libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000007f8d686000)
        libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000007f8d657000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000007f8d4e5000)
        libgcc_s.so.1 => /lib/aarch64-linux-gnu/libgcc_s.so.1 (0x0000007f8d4c1000)
        libz.so.1 => /lib/aarch64-linux-gnu/libz.so.1 (0x0000007f8d494000)
        /lib/ld-linux-aarch64.so.1 (0x0000007f8d8af000)
```

**Comment by shujian1997** [comment]
Thanks for your inspiration! I solved this problem by adding `-static` in my instruction, and it worked!  Thank you all the time!
