### ISSUE TITLE
Multi-Thread & Speed Problem

### ISSUE THREAD

**Issue by shujian1997** [xianyi/OpenBLAS#2540]
Hi, everyone
      I am not sure that if the speed I got is the quickest result, so I wanna make for sure here, and in my opinion, It can be faster. 
     I ran a `test.c`  like this:

```
#include <stdio.h>
#include "/usr/local/openblas_a9/include/cblas.h"
#include <time.h>
#include <stdlib.h>
#define random(x)(rand()%x)

void main()
{
   int M=160*160,K=32*9,N=64;
   int i;
   float* A=(float*)malloc(sizeof(float)*M*K);
   for(i=0;i<M*K;i++)
   {
      A[K]=(float)random(10);
    }

   float* B=(float*)malloc(sizeof(float)*N*K);
   for(i=0;i<N*K;i++)
   {
      B[K]=(float)random(10);
    }
   float* C=(float*)malloc(sizeof(float)*N*M);
   
   float alpha=1;
   float beta=0;
   int lda=K;
   int ldb=N;
   int ldc=N;
   
   clock_t start1,end1;
   start1=clock();
   cblas_sgemm(CblasRowMajor,CblasNoTrans,CblasNoTrans,M,N,K,alpha,A,lda,B,ldb,beta,C,ldc);
   end1=clock();
   printf("timeusing:%lf",((double)end1 - (double)start1)/ CLOCKS_PER_SEC);
   printf("\n");
}
```

Before I compiled it I tried to use the multi-threads, I inputed this in my ubuntu teminal
`export OPENBLAS_NUM_THREADS=4`
  Then I compiled this test.c by using this instruction  :
`arm-linux-gnueabihf-gcc -static -o test test.c -I /usr/local/openblas_a9/include/ -L /usr/local/openblas_a9/lib  /usr/local/openblas_a9/lib/libopenblas.a   -lpthread  -lgfortran  -std=c99 -mcpu=cortex-a9  -mfpu=neon-fp16  -mfloat-abi=hard  -O3 -ffast-math`

The CPU that run the executable file is exynos4412  cortex-a9 

the time that cblas_sgemm used is around 0.48s.  If I didn't input `export OPENBLAS_NUM_THREADS=4`  the time is 0.68s

I wanna know that if I did something wrong when I use openblas to caculate the matrix and if the speed is reasonable, if not , how can I speed up?

Thanks for your attention!

**Comment by brada4** [comment]
You need to set the variable at run time only, it has no effect at compile time.
What openblas version?
What compiler flags you added to build it?
PS Timing wrapper compile flags does not change timing result usually.

**Comment by shujian1997** [comment]
> You need to set the variable at run time only, it has no effect at compile time.
> What openblas version?
> What compiler flags you added to build it?
> PS Timing wrapper compile flags does not change timing result usually.

Thanks for your reply, the openblas version is OpenBLAS-develop(download in March),  I compiled the openblas with the instruction `make CC=arm-linux-gnueabihf-gcc FC=arm-linux-gnueabihf-gfortran HOSTCC=gcc TARGET=CORTEXA9`

**Comment by shujian1997** [comment]
> You need to set the variable at run time only, it has no effect at compile time.
> What openblas version?
> What compiler flags you added to build it?
> PS Timing wrapper compile flags does not change timing result usually.

And when my 4412 developer board calculate it ,it only use one cpu.  I compile it staticly, should I copy the the result of compiled openblas to the board?

**Comment by martin-frbg** [comment]
With the static compilation of your binary, you should not need to copy the libopenblas, just the executable you built with it. Strange that it would only use one core - perhaps you could try rebuilding OpenBLAS with the additional option NUM_THREADS=4 to make sure that it will support up to four cores. (There are internal limits to make sure that it does not multithread for
very small problem sizes where the overhead would be too large, but I think at  160*64*32 there should be more than one core active)

**Comment by martin-frbg** [comment]
Preliminary tests on Asus Tinkerboard (quad-core A17) suggest that OpenBLAS is using all four cores in your example - but it is at least twice as fast when limited to a single core by setting NUM_THREADS=1. Not sure what exactly is wrong here.

**Comment by shujian1997** [comment]
> Preliminary tests on Asus Tinkerboard (quad-core A17) suggest that OpenBLAS is using all four cores in your example - but it is at least twice as fast when limited to a single core by setting NUM_THREADS=1. Not sure what exactly is wrong here.

I rebuilt the OpenBLAS and added the option that   NUM_THREADS=4;
So the complete instrutction of compiling the openblas is
`make CC=arm-linux-gnueabihf-gcc  FC=arm-linux-gnueabihf-gfortran  HOSTCC=gcc TARGET=CORTEXA9  NUM_THREADS=4
`
The result seems reasonable, 
![compiled result](https://user-images.githubusercontent.com/58925429/78316937-888ff700-7593-11ea-877e-73a0d4ea258b.jpg)

Then I used the `make PREFIX=/usr/local/openblas_a9/ install`  to install it.
The result is shown at followed pictures.
![image](https://user-images.githubusercontent.com/58925429/78317072-e0c6f900-7593-11ea-96e9-ce70cd87ebef.png)
![image](https://user-images.githubusercontent.com/58925429/78317086-e6bcda00-7593-11ea-9afc-cb2fcc53aac9.png)
![image](https://user-images.githubusercontent.com/58925429/78317092-ee7c7e80-7593-11ea-9b1e-c3769f2c0eaf.png)
![image](https://user-images.githubusercontent.com/58925429/78317104-f63c2300-7593-11ea-8b55-6712d9de345d.png)


Then I compiled the test.c example by using the instruction
` arm-linux-gnueabihf-gcc -static -o test test.c -I /usr/local/openblas_a9/include/ -L /usr/local/openblas_a9/lib /usr/local/openblas_a9/lib/libopenblas.a -lpthread -lgfortran -std=c99 -mcpu=cortex-a9 -mfpu=neon-fp16 -mfloat-abi=hard -O3 -ffast-math
`

And I got a executable binary file(around 700kb).
I copied it to my developer board(quad-core  A9),  before I ran it through "super terminal" in my computer, I inputed the instruction --'export OPENBLAS_NUM_THREADS=4' .   PS I didn't copy the openblas library to my board.
But the result is still the same.

![V}Q_40 P_9{QI)(A86D$NVF](https://user-images.githubusercontent.com/58925429/78317395-c04b6e80-7594-11ea-8bb0-ac9feab951c3.jpg)

So which step was wrong?  And I am carious about that when I link the library staticly,  dose it work when I export environment variable on my developer board? 
Besides, dose the option ` -mcpu=cortex-a9 -mfpu=neon-fp16 -mfloat-abi=hard -O3 -ffast-math`  help to improve the speed?


Thanks for your attention!!!! Thank you very much!

**Comment by brada4** [comment]
I think it should be -lopenblas after -Lfullpath.
700kb looks way smaller than static libraries involved.

**Comment by shujian1997** [comment]
> I think it should be -lopenblas after -Lfullpath.
> 700kb looks way smaller than static libraries involved.

Thanks for your reply, I tried your advice and add -lopenblas after -Lfullpath, and now the instruction becomes
`arm-linux-gnueabihf-gcc -static -o mainv5 main.c -I /usr/local/openblas_a9/include/ -L /usr/local/openblas_a9/lib/  -lopenblas -lpthread -lgfortran -std=c99 -mcpu=cortex-a9 -mfpu=neon-fp16 -mfloat-abi=hard -O3 -j4`

Unfortunately, the result doesn't change, and the size of the file is still around 700kb, actually 748kb.

PS It's wired that the size of libopenblas.a is 18.6MB

**Comment by martin-frbg** [comment]
libopenblas.a is 18MB on my system as well, but the linker seems to be smart enough to pick only the object modules from it that are actually needed - a .a is basically just a collection of .o fles anyway. (The test executable is 70kb when it is dynamically linked against libpthread and libc/libm). @brada4 your suggestion seems to be for dynamic linking against OpenBLAS while the intention here is to link statically. Compiler options will probably not help much, as the most important function, the sgemm_kernel_4x4_vfpv3.S, is already written in assembler.
According to comments in the code, it was probably optimized for matrix sizes around 3000x3000 - unfortunately the person who wrote it is no longer around. "perf" shows no obvious hotspot in the code (one of many fmul instructions is shown at 9 percent, but that is about all)

**Comment by shujian1997** [comment]
> libopenblas.a is 18MB on my system as well, but the linker seems to be smart enough to pick only the object modules from it that are actually needed - a .a is basically just a collection of .o fles anyway. (The test executable is 70kb when it is dynamically linked against libpthread and libc/libm). @brada4 your suggestion seems to be for dynamic linking against OpenBLAS while the intention here is to link statically. Compiler options will probably not help much, as the most important function, the sgemm_kernel_4x4_vfpv3.S, is already written in assembler.
> According to comments in the code, it was probably optimized for matrix sizes around 3000x3000 - unfortunately the person who wrote it is no longer around. "perf" shows no obvious hotspot in the code (one of many fmul instructions is shown at 9 percent, but that is about all)

Thanks for your explanation about the linker. I got another three questions followed, 
1.Would you like tell me how do you set the multi-threads on your Asus Tinkborder?  Maybe I could get some inspiration from it.

2.As it doesn't work that I compile the OpenBLAS with option  NUM_THREADS=4, and the way I exported OPENBLAS_NUM_THREADS=4 also doesn't work, so what other settings should I set to solve this problem and let it use more than 1 core(Now I saw only one core was running).

PS: the system on my developer board is QT

3.I found that the cpu would start another core when the worked core is used more than 70% of it's ability, so can I consider the test code I wrote before didn't make full use of the developer board's performance?

Thanks for your patience and reply.

**Comment by martin-frbg** [comment]
1. Nothing special. I was only trying to make sure that your library was built correctly as you are cross-compiling. On the tinkerboard I can compile directly, so the Makefiles will always see the correct number of cores.
2. The runtime of the test is too short to get output from a debugger, so I edited OpenBLAS and made it print out how many threads it configured in interface/gemm.c - it does appear to use all 
four but for me the test runs faster with OPENBLAS_NUM_THREADS=1
3. It could be that the matrix in the test code is too small to make (sensible) use of more than one core, but my tinkerboard has not enough memory to test with large sizes. There could also be something wrong in the sgemm kernel, or in the values of various constants in OpenBLAS. I tried
replacing the sgemm kernel with the older vfp version used for ARMV6 but that only made it even slower. (What is clear is that the sgemm is only using vfpv3 instructions, not the FMA available in vfpv4. EDIT: not quite correct, it has lots of fmacs that according to `perf` get translated to `vmla.f32` - just no vector instructions from NEON, which might be supported for single precision)

**Comment by martin-frbg** [comment]
Whatever the core issue is, it goes all the way back to 0.2.9 and probably earlier, all showing 0.29 seconds single-threaded and 0.40 for all four cores active. (I have not been able to pinpoint it so far - it is not OpenMP vs locking, and does not appear to be a simple parameter error either. Maybe it is just the cpu overheating on the passively cooled board, but I do not see anything in the logs)

**Comment by shujian1997** [comment]
> Whatever the core issue is, it goes all the way back to 0.2.9 and probably earlier, all showing 0.29 seconds single-threaded and 0.40 for all four cores active. (I have not been able to pinpoint it so far - it is not OpenMP vs locking, and does not appear to be a simple parameter error either. Maybe it is just the cpu overheating on the passively cooled board, but I do not see anything in the logs)

I have tried some ways to figure it out these days, including edit my flags, use pthread way, it seems do not work anyway. My openblas version is 0.3.9, I will try 0.2.9-version today.  
In fact we are trying to finish a densenet to recoginize faces, this matrix multiplication operation is the biggest matrix in our neural network. As we all know, openblas is one of the quickest way to achieve the matrix multiplication, so I think the speed now is not that right. I will tell you if there is any progress.
Thanks for your patience, it feels so warm to consult you these problems!

**Comment by shujian1997** [comment]
> Whatever the core issue is, it goes all the way back to 0.2.9 and probably earlier, all showing 0.29 seconds single-threaded and 0.40 for all four cores active. (I have not been able to pinpoint it so far - it is not OpenMP vs locking, and does not appear to be a simple parameter error either. Maybe it is just the cpu overheating on the passively cooled board, but I do not see anything in the logs)

It seems like the Openblas-armv7 version and Openblas-0.2.9 don't support cross-compile with the TARGET=CORTEXA9 😥

**Comment by brada4** [comment]
A9 was introduced in 0.2.14

**Comment by martin-frbg** [comment]
I think TARGET=ARMV7 should work in 0.2.9 (and be practically identical), but as I wrote 0.2.9 gave the same timings and it has lots of bugs that were fixed since then.

**Comment by martin-frbg** [comment]
Possibly the fundamental problem is just that M is so much bigger than N in your case. There once was an "optimized for deep learning" branch that Xianyi started, which is basically only a single commit to change the rules for distributing a GEMM task onto separate threads. I'll see if that offers any improvement.
EDIT: well, that manages to make the multithreaded version a little less slow, but at 0.37 vs. 0.29 seconds for the single-threaded run it still seems slower rather than faster. (And no sweet spot at two or three threads either, just a gradual slowdown. Perhaps I should take another look at the
time calculation - if it happened to sum up the cputime of cores working in parallel it would make multithreading always look worse)

**Comment by shujian1997** [comment]
> Possibly the fundamental problem is just that M is so much bigger than N in your case. There once was an "optimized for deep learning" branch that Xianyi started, which is basically only a single commit to change the rules for distributing a GEMM task onto separate threads. I'll see if that offers any improvement.
> EDIT: well, that manages to make the multithreaded version a little less slow, but at 0.37 vs. 0.29 seconds for the single-threaded run it still seems slower rather than faster. (And no sweet spot at two or three threads either, just a gradual slowdown. Perhaps I should take another look at the
> time calculation - if it happened to sum up the cputime of cores working in parallel it would make multithreading always look worse)

I ran the test code with my openblas built with single threat mode,  the runing time varies between 0.5s~1.8s.  Without the single-thread restriction, the running time is aroud 0.48s or 0.49s.

**Comment by martin-frbg** [comment]
Pretty sure now that by using clock() you are measuring the sum of processor time across all threads. When I rewrite it to calculate elapsed time rather than cpu time, single thread is still at 0.29s but with four threads it completes in 0.09s (0.16 for two threads, 0.12 with three threads). This is with the small changes from the old "optimized for deep learning" branch, i.e. https://github.com/xianyi/OpenBLAS/commit/92058a75e2cc1e46e73e2784f691a2bcb2f9aef9
(I believe I can only test with softfp on my Tinkerboard running Linaro, but I see no reason why hardfp would be different).

**Comment by shujian1997** [comment]
> Pretty sure now that by using clock() you are measuring the sum of processor time across all threads. When I rewrite it to calculate elapsed time rather than cpu time, single thread is still at 0.29s but with four threads it completes in 0.09s (0.16 for two threads, 0.12 with three threads). This is with the small changes from the old "optimized for deep learning" branch, i.e. [92058a7](https://github.com/xianyi/OpenBLAS/commit/92058a75e2cc1e46e73e2784f691a2bcb2f9aef9)
> (I believe I can only test with softfp on my Tinkerboard running Linaro, but I see no reason why hardfp would be different).

You hit the point!  Could you please tell me how to edit my code to calculate elapsed time? I will try it before your answer! Thank you very much!

**Comment by martin-frbg** [comment]
this is what i changed in your code, there may be more elegant ways
```
   struct timespec start1,end1;
   double elapsed;
 
   clock_gettime(CLOCK_MONOTONIC,&start1);
 cblas_sgemm(CblasRowMajor,CblasNoTrans,CblasNoTrans,M,N,K,alpha,A,lda,B,ldb,beta,C,ldc);
   clock_gettime(CLOCK_MONOTONIC,&end1);
   elapsed = (end1.tv_sec - start1.tv_sec);
   elapsed += (end1.tv_nsec - start1.tv_nsec) / 1000000000.0;
   printf("timeusing:%lf",elapsed);
```

**Comment by shujian1997** [comment]
> this is what i changed in your code, there may be more elegant ways
> 
> ```
>    struct timespec start1,end1;
>    double elapsed;
>  
>    clock_gettime(CLOCK_MONOTONIC,&start1);
>  cblas_sgemm(CblasRowMajor,CblasNoTrans,CblasNoTrans,M,N,K,alpha,A,lda,B,ldb,beta,C,ldc);
>    clock_gettime(CLOCK_MONOTONIC,&end1);
>    elapsed = (end1.tv_sec - start1.tv_sec);
>    elapsed += (end1.tv_nsec - start1.tv_nsec) / 1000000000.0;
>    printf("timeusing:%lf",elapsed);
> ```

What about your compile instruction? I wanna check it and be the same with you to get a better result.
I have tried another way to calculate the time, it seems still wired that if I ran it quickly by my hand, it will start another core and the speed become faster! So wired, maybe it means the code run on my board is still single thread?
![image](https://user-images.githubusercontent.com/58925429/78665485-78b44200-7908-11ea-8b5b-ec873cc6d238.png)

**Comment by shujian1997** [comment]
> this is what i changed in your code, there may be more elegant ways
> 
> ```
>    struct timespec start1,end1;
>    double elapsed;
>  
>    clock_gettime(CLOCK_MONOTONIC,&start1);
>  cblas_sgemm(CblasRowMajor,CblasNoTrans,CblasNoTrans,M,N,K,alpha,A,lda,B,ldb,beta,C,ldc);
>    clock_gettime(CLOCK_MONOTONIC,&end1);
>    elapsed = (end1.tv_sec - start1.tv_sec);
>    elapsed += (end1.tv_nsec - start1.tv_nsec) / 1000000000.0;
>    printf("timeusing:%lf",elapsed);
> ```


![TIM图片20200407195528](https://user-images.githubusercontent.com/58925429/78666342-cda48800-7909-11ea-8626-265cc49520bc.png)

**Comment by martin-frbg** [comment]
Maybe your board's firmware only wakes up cpu cores as needed to save energy ? OpenBLAS should detect how many cores (threads) are available when it starts up, this may not work so well if some cores are actually offline at that time. You could try having interface/gemm.c print out how many threads it is going to use (args.nthreads as used in the GEMM_THREAD call at the end of that file)

**Comment by shujian1997** [comment]
> Maybe your board's firmware only wakes up cpu cores as needed to save energy ? OpenBLAS should detect how many cores (threads) are available when it starts up, this may not work so well if some cores are actually offline at that time. You could try having interface/gemm.c print out how many threads it is going to use (args.nthreads as used in the GEMM_THREAD call at the end of that file)

I think you are right, the most important for me is trying to wake all the cores at the start time. I'll try it. 
I will try to add it, but actually I don't know how to operate it.... It may take some time.  So appreciate for your advice!

**Comment by shujian1997** [comment]
> Maybe your board's firmware only wakes up cpu cores as needed to save energy ? OpenBLAS should detect how many cores (threads) are available when it starts up, this may not work so well if some cores are actually offline at that time. You could try having interface/gemm.c print out how many threads it is going to use (args.nthreads as used in the GEMM_THREAD call at the end of that file)

THANKS FOR YOUR HELP!  I use the 'echo' instruction to open the other cpu, and now the openblas can run it aroud 0.2s, Thanks to your help! Thank you again!

**Comment by martin-frbg** [comment]
Thanks for the feedback, I have added an entry to the FAQ in the wiki
