### ISSUE TITLE
Specifying thread affinity at runtime

### ISSUE THREAD

**Issue by sharvil** [xianyi/OpenBLAS#2545]
It's important to specify the thread affinity at runtime for my application. I've locally modified OpenBLAS to expose a function to set the thread affinity (Linux-only) and I'd love to see it upstreamed. In `drivers/others/blas_server.c`:

```c
void openblas_setaffinity(const cpu_set_t* cpu_set) {
    for (int i = 0; i < blas_num_threads - 1; ++i) {
        pthread_setaffinity_np(blas_threads[i], sizeof(cpu_set_t), cpu_set);
    }
}
```

I'm happy to submit a PR. Is it sufficient to hide this function behind `#if __linux__`? Any other comments / suggestions about adding this function?

**Comment by martin-frbg** [comment]
`#if defined(OS_LINUX) && !defined(NO_AFFINITY)` I would think... and expose it in cblas.h
ISTR there is a gotoblas_set_affinity already in the code but that is probably just an internal helper to apply the initial affinity mask to a thread.

**Comment by sharvil** [comment]
Thanks for the quick response! Yes, there is a `gotoblas_set_affinity` and it is internal as you said.

I'm not sure gating on `!defined(NO_AFFINITY)` is right here. A caller explicitly specifying thread affinity seems independent of whether OpenBLAS sets thread affinities automatically or not (which, AFAICT, is the purpose of `NO_AFFINITY`).

**Comment by brada4** [comment]
There are ways to prevent OS scheduler to migrate running processes off the caches. If something is badly sub-optimal there are ways with system tuning that benefits other software outside openblas alike.

**Comment by martin-frbg** [comment]
Was not sure offhand if all the required code would be compiled with NO_AFFINITY set, but I guess if it already compiled and worked for you, you will be right. (And probably no reason not to provide an entirely optional interface in the library - not everybody will be able to make system-wide changes on their hardware, and not all OS may provide a working, scheduler-based solution.)
