### ISSUE TITLE
LAPACK test failures

### ISSUE THREAD

**Issue by mikecroucher** [xianyi/OpenBLAS#2552]
Hi 

Building OpenBLAS with Intel version 19.0.5.281 results in a bunch of LAPACK test errors.

Here's the make call
```
make CC=icc FC=ifort DYNAMIC_ARCH=1 USE_OPENMP=1 MAKE_NB_JOBS=$numcores NUM_THREADS=256
```

Here's the result of `make lapack-test`

```
                        -->   LAPACK TESTING SUMMARY  <--
SUMMARY                 nb test run     numerical error         other error
================        ===========     =================       ================
REAL                    561270          176     (0.031%)        150     (0.027%)
DOUBLE PRECISION        724206          547     (0.076%)        140     (0.019%)
COMPLEX                 582618          74      (0.013%)        13      (0.002%)
COMPLEX16               591638          168     (0.028%)        8       (0.001%)

--> ALL PRECISIONS      2459732         965     (0.039%)        311     (0.013%)
```

I later `make CC=icc FC=ifort DYNAMIC_ARCH=1` and got 

```
                        -->   LAPACK TESTING SUMMARY  <--
SUMMARY                 nb test run     numerical error         other error
================        ===========     =================       ================
REAL                    561270          176     (0.031%)        146     (0.026%)
DOUBLE PRECISION        713815          1191    (0.167%)        150     (0.021%)
COMPLEX                 582618          74      (0.013%)        2280    (0.391%)
COMPLEX16               591638          168     (0.028%)        0       (0.000%)

--> ALL PRECISIONS      2449341         1609    (0.066%)        2576    (0.105%)
```

finally, `make CC=icc FC=ifort`

```
                        -->   LAPACK TESTING SUMMARY  <--
SUMMARY                 nb test run     numerical error         other error
================        ===========     =================       ================
REAL                    564808          158     (0.028%)        146     (0.026%)
DOUBLE PRECISION        730536          310     (0.042%)        136     (0.019%)
COMPLEX                 582618          74      (0.013%)        2280    (0.391%)
COMPLEX16               591638          168     (0.028%)        0       (0.000%)

--> ALL PRECISIONS      2469600         710     (0.029%)        2562    (0.104%)
```

CPU is Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz

**Comment by Diazonium** [comment]
Hmm, does this also happen with gcc/gfortran? I am not sure if icc/ifort is even supported, probably not that well tested, given that most people just use MKL if they have ifort.

**Comment by martin-frbg** [comment]
Supported but certainly less well tested. Which version did you build ? Some LAPACK functions in netlib need to be built with -recursive which was not done until very recently (#2536)

**Comment by mikecroucher** [comment]
gcc/gfortran builds perfectly. 

I built OpenBLAS 0.3.9.  If there is anything else you need from me for this, let me know.

**Comment by martin-frbg** [comment]
Can you try with the changes from #2536 , or just build the current `develop` branch instead of 0.3.9 ?

**Comment by ningli** [comment]
Tested. Change in #2536 is irrelevant.

**Comment by martin-frbg** [comment]
Thanks. No other immediate suggestion unfortunately.  (And I need to check if my temporary trial license of ifort is still valid)

**Comment by martin-frbg** [comment]
Testing now. Reducing the optimization level actually makes the number of failures increase, -recursive and -fpe options have no effect. No change with NO_AVX512=1 or building a single-threaded library either, tiny reduction in number of failures for REAL when building for Sandybridge (without AVX2), small increase when building for Nehalem (w/o even AVX). 
No errors in BLAS-Tester.

**Comment by martin-frbg** [comment]
CC=icc FC=gfortran looks almost perfect, suggesting the problem is on the fortran (or fortran-c interface) side.

**Comment by martin-frbg** [comment]
Reference-LAPACK build with the same compiler (current 19.1 build) turns out to have no issues, copying the extra options (`-fp-model strict -assume protect-parens`) at least brings the number of tests run closer to the gcc/gfortran data but still more numerical errors.
Even `TARGET=GENERIC` which is pretty much all plain C without vector intrinsics on the BLAS side shows lots of errors in the LAPACK tests with icc+ifort.

**Comment by martin-frbg** [comment]
Looks like things got bad at some point after 0.3.7 - but `git bisect` strangely puts the blame on PR #2327 which is a change in one of the CI configuration files. (Redoing the bisect now)
Actually it is #2353, which happens to be the big update of LAPACK to 3.9.0. As it is "only" broken for the Intel compilers, hopefully it is something simple like the changes I made in make.inc
