### ISSUE TITLE
Clarification on feature availability

### ISSUE THREAD

**Issue by THoferSchmitz** [xianyi/OpenBLAS#2558]
Hi

Since I didn't find a clear answer so far I decided to just ask here:

When I build OpenBLAS without a Fortran compiler, what features will not be available in OpenBLAS? Will all BLAS/LAPACK functions be unusable or does OpenBLAS provide a C/C++ fallback to provide (part of) these features even without a working Fortran compiler?

I'm interested because compiling Fortran for Android is problematic to set up and I would like to avoid this if possible.

**Comment by martin-frbg** [comment]
Without Fortran, OpenBLAS will be reduced to just the BLAS functions. (The LAPACK component is imported from the "netlib" reference implementation - which is still in Fortran - and only a handful of LAPACK functions are replaced by optimized C equivalents)
