### ISSUE TITLE
Support for bfloat16 in OpenBLAS 

### ISSUE THREAD

**Issue by RajalakshmiSR** [xianyi/OpenBLAS#2560]

**Comment by RajalakshmiSR** [comment]
To discuss about PR
https://github.com/xianyi/OpenBLAS/pull/2559

**Comment by martin-frbg** [comment]
Merged the PR after the last issues seen on Appveyor were confirmed fixed after moving the "Windows/CL" build to Azure CI. (Appveyor jobs are still shown as queued, these should provide final confirmation eventually -- EDIT: all complete now).
It is important to note that any bfloat16 BLAS functions outside SHGEMM - even trivial functions like MIN/MAX or SUM are almost guaranteed to be wrong right now, as they are simply mapped to the corresponding single-precision implementations without even a proper cast.

**Comment by xianyi** [comment]
Hi @martin-frbg ,

Is it possible add something like `BFLOAT16` makefile flag? If the user wants `BFLOAT16`,  `make BFLOAT16=1`. By default, it is disabled.

**Comment by martin-frbg** [comment]
This should certainly be possible, if one is concerned about library size. I must admit I did not see an immediate need as there should be no other cause of problems when the bfloat16 code is present but not called by user code.

**Comment by RajalakshmiSR** [comment]
Just to clarify, shgemm() is enabled by default now.

**Comment by martin-frbg** [comment]
The CMAKE build already has a concept of `BUILD_*` options for the various data types (but I am not sure if this was ever actually tested or just seemed like a good idea - EDIT: it was probably taken from the LAPACK CMakeLists.txt and applies only there), but the Makefiles do not.
My presumption was that storage-limited platforms would likely be wanting bfloat16 support for AI applications all the same (but this is not an area I am familiar with)

**Comment by martin-frbg** [comment]
Option added in #2590 - this could also be expanded to support BUILD_SINGLE etc. like netlib LAPACK does for both BLAS and LAPACK
