### ISSUE TITLE
OpenBLAS not using LIBRARY_PATH

### ISSUE THREAD

**Issue by dlqqq** [xianyi/OpenBLAS#2561]
I'm having issues specifying library paths to search for during compilation. The system I am using has outdated versions of GCC and its corresponding libraries, and the latest libraries are located under the `/share/apps/gcc/gcc-9.2.0/lib[64]` directories. Thus, I need to specify the LIBRARY_PATH for GCC to use manually. I've done this by exporting the following environmental variables prior to compilation:

```
export LIBRARY_PATH=/share/apps/gcc/gcc-9.2.0/lib:/share/apps/gcc/gcc-9.2.0/lib64
export LD_LIBRARY_PATH=$LIBRARY_PATH
```

However, OpenBLAS is still linking the outdated libraries in `/lib` and `/lib64`. This is shown when I run `ldd` on the compiled library. 

```
$ ldd libopenblas_barcelonap-r0.3.9.dev.so
        linux-vdso.so.1 =>  (0x00007fff2c9ff000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f5d71615000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f5d713f7000)
        libgfortran.so.3 => /usr/lib64/libgfortran.so.3 (0x00007f5d71105000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f5d70d71000)
```

I expected that the Makefile would read from the LIBRARY_PATH and LD_LIBRARY_PATH environmental variables, as it as done so for all the other libraries I've compiled on this machine. Am I forgetting something blindingly obvious? Do I need to edit the Makefiles manually to resolve this?

I'm happy to provide more information on the system if necessary. Thank you for spending your time to help me with this issue!

**Comment by martin-frbg** [comment]
This should definitely work - perhaps something is unsetting LD_LIBRARY_PATH between the compilation and your `ldd` call (or you are doing the two tasks in different shells perhaps) ?

**Comment by dlqqq** [comment]
Thank you for your advice @martin-frbg! I've made sure to re-examine the environmental variables I was exporting, and realized I accidentally commented the environmental variables specifying my compiler! After exporting the following environmental variables:

```
export FC=/share/apps/gcc/gcc-9.2.0/bin/gfortran
export CC=/share/apps/gcc/gcc-9.2.0/bin/gcc
export CXX=/share/apps/gcc/gcc-9.2.0/bin/g++
export HOSTCC=$CC
```

everything worked perfectly as expected. `ldd` then showed the OpenBLAS library linking to the proper libraries.

```
 $ ldd libopenblas_barcelonap-r0.3.9.dev.so
        linux-vdso.so.1 =>  (0x00007ffffddff000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fdebcaee000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fdebc8d0000)
        libgfortran.so.5 => /share/apps/gcc/gcc-9.2.0/lib64/libgfortran.so.5 (0x00007fdebc4ab000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fdebc117000)
```

I'll close this issue. However, how is the HOSTCC any different from CC? Is the HOSTCC the compiler of the system I am currently compiling the library on, and CC is the compiler of the system I wish to use the library?

**Comment by martin-frbg** [comment]
HOSTCC is only relevant when you are cross-compiling for a different architecture, e.g using the Android NDK to create ARM binaries for your phone or tablet on an x86_64 computer. In that case, CC points to the "foreign" compiler and HOSTCC is the native compiler on the build host that is needed to create a few helper programs (like `getarch`) that generate configuration files.
