### ISSUE TITLE
MIPS32 24K / 24KE TARGET

### ISSUE THREAD

**Issue by bhack** [xianyi/OpenBLAS#2564]
Is there a target for MIPS32 24K / 24KE? 
http://en.techinfodepot.shoutwiki.com/wiki/MIPS32#MIPS32_24K_.2F_24KE

**Comment by martin-frbg** [comment]
Not specifically - you could try TARGET=P5600

**Comment by bhack** [comment]
Mhh I got this with `P5600` on compilation.

```
{standard input}:207: Error: opcode not supported on this processor: mips32r5 (mips32r5) `rdhwr $2,$30'
{standard input}:289: Error: opcode not supported on this processor: mips32r5 (mips32r5) `rdhwr $2,$30'
{standard input}:330: Error: opcode not supported on this processor: mips32r5 (mips32r5) `rdhwr $2,$30'
```

**Comment by bhack** [comment]
It is a Mediatek MT7688 https://docs.onion.io/omega2-docs/omega2.html#omega2

**Comment by bhack** [comment]
I think that chip is a `mips32r2`. `P5600` set `mips32r5`

**Comment by bhack** [comment]
Setting the TARGET=1004K that is `-mips32r2` I got:

`
getarch.c:1164:2: error: #error "The TARGET specified on the command line or in Makefile.rule is not supported. Please choose a target from TargetList.txt"
 #error "The TARGET specified on the command line or in Makefile.rule is not supported. Please choose a target from TargetList.txt"
`

**Comment by martin-frbg** [comment]
Sorry, that seems to be an omission in getarch.c (the 1004K target is basically the same as P5600 but with the compiler options set to -mips32r2 . Back when I added it getarch.c did not yet have the code to catch invalid target names, and it seems I need to dig out that little ubiqiti router again and confirm everything still builds).

**Comment by martin-frbg** [comment]
Can you try what happens when you hack the Makefile.prebuild and Makefile.system to change mips32r5 to mips32r2 (and perhaps remove the mtune=P5600 where you encounter it) and then
build for TARGET=P5600 ?

**Comment by martin-frbg** [comment]
BTW what does /proc/cpuinfo contain on your system (assuming that it is some flavor of Linux or Unixoid that has /proc) ? The current check in cpuid_mips.c just tries to read the plaintext name rather than the numeric cpuid

**Comment by bhack** [comment]
Do you mean on the target machine? Cause I am cross-compiling from a x86 host.

**Comment by brada4** [comment]
EDIT: an exampe from modern mips linux - isa/ase/opt are text fields.

`Linux OpenWrt 4.14.171 #0 Thu Feb 27 21:05:12 2020 mips GNU/Linux`

```
system type             : Qualcomm Atheros QCA956X ver 1 rev 0
machine                 : TP-Link Archer C7 v5
processor               : 0
cpu model               : MIPS 74Kc V5.0
BogoMIPS                : 385.84
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa                     : mips1 mips2 mips32r1 mips32r2
ASEs implemented        : mips16 dsp dsp2
Options implemented     : tlb 4kex 4k_cache prefetch mcheck ejtag llsc dc_aliases perf_cntr_intr_bit cdmm nan_legacy nan_2008 contextconfig perf
shadow register sets    : 1
kscratch registers      : 0
package                 : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available
```

**Comment by bhack** [comment]
@brada4 I see you are on openwrt. I am trying exactly to prepare a package feed for openblas. Do you have already a recepit?
```
system type        : MediaTek MT7688 ver:1 eco:2
machine            : Onion Omega2+
processor        : 0
cpu model        : MIPS 24KEc V5.5
BogoMIPS        : 385.84
wait instruction    : yes
microsecond timers    : yes
tlb_entries        : 32
extra interrupt vector    : yes
hardware watchpoint    : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa            : mips1 mips2 mips32r1 mips32r2
ASEs implemented    : mips16 dsp
shadow register sets    : 1
kscratch registers    : 0
package            : 0
core            : 0
VCED exceptions        : not available
VCEI exceptions        : not available
```

**Comment by brada4** [comment]
@bhack no yet, but I will try. You try too.
Start with 'make' see if builtin tests dont fail, etc, btw there is no fortran which implies no reference blas either.

**Comment by bhack** [comment]
@brada4 It is a WIP if you want to try https://gist.github.com/bhack/60f61083d3264f4c1e11fbd7ff1225fd

**Comment by bhack** [comment]
@martin-frbg with` -mips32r2 -mtune=24kc` i got.
```
blas_server.c: In function 'blas_thread_init':
blas_server.c:585:95: warning: format '%ld' expects argument of type 'long int', but argument 4 has type 'int' [-Wformat=]
         fprintf(STDERR, "OpenBLAS blas_thread_init: pthread_create failed for thread %ld of %ld: %s\n", i+1,blas_num_threads,msg);
                                                                                             ~~^

{standard input}: Assembler messages:
{standard input}:207: Error: opcode not supported on this processor: mips32r2 (mips32r2) `rdhwr $2,$30'
{standard input}:289: Error: opcode not supported on this processor: mips32r2 (mips32r2) `rdhwr $2,$30'
{standard input}:330: Error: opcode not supported on this processor: mips32r2 (mips32r2) `rdhwr $2,$30'
Makefile:125: recipe for target 'blas_server.o' failed
```

**Comment by martin-frbg** [comment]
That error looks strange, are you sure that the assembler gets picked up from the cross-compile toolchain ? (I believe the rdhwr $2,$30 is generated by the toolchain compiler - though the definition of the "rpcc" macro in common_mips.h also contains a similar rdhwr instruction with a value of 30)

**Comment by bhack** [comment]
@martin-frbg It is quite easy to test
From https://github.com/OnionIoT/source#using-the-docker-image

To prepare the toolchain and minimal build in Docker

```
docker run -it onion/omega2-source /bin/bash
./scripts/feeds update onion
sh scripts/onion-minimal-build.sh
make -j
```
When it is ready put your branch/PR commit hash in your `Makefile` like this `scripts/package/libs/openblas/Makefile`
```
include $(TOPDIR)/rules.mk

PKG_NAME:=OpenBLAS
PKG_VERSION:=0.3.9
PKG_RELEASE:=1
PKG_BUILD_DIR:=$(BUILD_DIR)/OpenBLAS-$(PKG_VERSION)
#PKG_SOURCE:=v$(PKG_VERSION).tar.gz
#PKG_SOURCE_URL:=https://github.com/xianyi/OpenBLAS/archive/
PKG_SOURCE_PROTO:=git
PKG_SOURCE_URL:=https://github.com/martin-frbg/OpenBLAS.git
#PKG_HASH:=28cc19a6acbf636f5aab5f10b9a0dfe1
PKG_SOURCE_VERSION:=00172d440bfc7dedc8523a4cdad58b685801bb76
include $(INCLUDE_DIR)/package.mk

define Package/openblas
  SECTION:=libs
  CATEGORY:=Libraries
  TITLE:=An optimized BLAS library
  URL:=https://www.openblas.net/
endef

define Package/bridge/description
  OpenBLAS is an optimized BLAS library based on GotoBLAS2 1.13 BSD version
endef
# Package build instructions; invoke the GNU make tool to build our package
define Build/Compile
        $(MAKE) -C $(PKG_BUILD_DIR) \
           NOFORTRAN=1 \
           TARGET='1004K' \
           HOSTCC=gcc \
               CC="$(TARGET_CC)" \
           CFLAGS="$(TARGET_CFLAGS)" \
          LDFLAGS="$(TARGET_LDFLAGS)" 
endef
define Build/InstallDev
        $(INSTALL_DIR) $(1)/usr/lib/pkgconfig
        $(CP) $(PKG_INSTALL_DIR)/usr/lib/* $(1)/usr/lib/
        $(INSTALL_DIR) $(1)/usr/include
        $(CP) $(PKG_INSTALL_DIR)/usr/include/* $(1)/usr/include/
        $(CP) $(PKG_INSTALL_DIR)/usr/lib/pkgconfig/* $(1)/usr/lib/pkgconfig/
endef

define Package/openblas/install
        $(INSTALL_DIR) $(1)/usr/lib
        $(CP) $(INSTALL_BIN) $(PKG_BUILD_DIR)/usr/lib/libOpenblas.so* $(1)/usr/lib/
endef
$(eval $(call BuildPackage,openblas))
```

And then compile you could compile OpenBLAS with
`make package/libs/openblas/compile -j1 V=s`

**Comment by brada4** [comment]
native build on usb chroot did not complain about invalid opcodes yet.
rdhwr and 32 registers are mips1, fpu2008 is mips4, so mips5 should cover both
I think something missing in a cross-compiler vs native compiler that assembler under the hood rejects valid instruction for architecture.
Once the build is over (does not look like soon) I will report back with log.

More or less what I did:
* mount usb stick, but with f2fs, somehow ext4 peaked router CPU
* zram-swap - apparntly 128MB RAM is insufficient for git-http clone, nor svn supports http(s)
* clone (copy) libc installation - /usr/lib/opkg - 3 files from there plus edited list to leave single package, and 3 libs from other places to chroot (a new directory on USB)
* bind-mount /dev and /proc to chroot
* opkg -o /dev/sda/chroot install ash busybox opkg usign
* chroot /mnt/sda/chroot /bin/ash
* now you should be able to install git-http make gcc perl perlbase-file, maybe you need to mkdir -p some stuff to make opkg happy.
* git clone
* make target=P5600
* .... still waiting

Though not sure what is practical consumer that is C-only on 128MB RAM.

Since we are facing compiler ?bug? I think we cannot proceed much further. From the compiler output it looks like `cc1` generated proper armv1 instruction while `as` says it does not get it.
You get same if you want avx512 on ubuntu16 or rhel7

**Comment by bhack** [comment]
@brada4 The cross-compile openwrt docker has `gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0`

**Comment by martin-frbg** [comment]
From what I could find it is more likely a binutils bug in the toolchain - "read hardware register" should be a legal MIPS32R2 instruction, perhaps the assembler does not know the 24K cpu ?

**Comment by brada4** [comment]
> @brada4 The cross-compile openwrt docker has `gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0`

Ubuntu ships no mips compiler.
```
@OpenWrt:/openblas# gcc --version
gcc (OpenWrt GCC 7.4.0) 7.4.0
@OpenWrt:/openblas# opkg list | grep ^gcc
gcc - 7.4.0-5 - Build a native toolchain for compiling on target device.
```

**Comment by brada4** [comment]
> From what I could find it is more likely a binutils bug in the toolchain - "read hardware register" should be a legal MIPS32R2 instruction, perhaps the assembler does not know the 24K cpu ?

In addition fpu=2008 fails to link together with fpu=generic libc/libm.

**Comment by martin-frbg** [comment]
you mean -mnan=2008 ? Could be that requires mips32r5, I do not think our Makefiles use this in conjuction with 32r2 hosts anyway

**Comment by bhack** [comment]
The toolchain in the docker is build in "./staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/lib/gcc"

**Comment by brada4** [comment]
So problem is with that toolchain, please try official OpenWRT mips SDK toolchain, that should contain gcc 7.4 or 7.0 and matching working assembler (binutils) package.

**Comment by martin-frbg** [comment]
Just for testing, could you try deleting the line with the "rwhdr" instruction in common_mips.h and/or the "#define RPCC_DEFINED" that accompanies it ?  (Oh, and make that function "return 0" instead of "return ret" so that it does not read from uninitialized memory)

I believe this is only meant to read the cycle counter for profiling purposes so should not matter in normal operation. Perhaps this can even be a priviledged instruction not available to userspace in some circumstances ? At the very least, this would tell us if it is actually something the compiler generated itself (as I originally assumed due to the register number mismatch, but the %0 in the macro may be a gcc alias for the same thing) or code imported from this macro

**Comment by martin-frbg** [comment]
```
Read Hardware Register
RDHWR                       -  page 208
MIPS32® Architecture For Programmers Volume II: The MIPS32® Instruction Set, Revision 2.62
Copyright © 2001-2003,2005,2008-2009 MIPS Technologies Inc. All rights reserved.
Restrictions:
In implementations of Release 1 of the Architecture, this instruction resulted in a Reserved Instruction Exception.
Access to the specified hardware register is enabled if Coprocessor 0 is enabled, or if the 
corresponding bit is set in the HWREna register. If access is not allowed or the register is not implemented, a Reserved Instruction Exception is signaled.
```
So perhaps binutils assumes coprocessor not present/not available ? (the document does not spell it out whether this `coprocessor` is the fpu, but perhaps adding `-mhard-float` (if applicable)
would help to make sure the fpu is online)
Does it help when you add  `-march=24kc` in addition to `-mips32r2` ?

**Comment by bhack** [comment]
@martin-frbg I am on https://github.com/xianyi/OpenBLAS/pull/2565. What TARGET i need to set?

**Comment by bhack** [comment]
`-mtune=24kc` was already inherited but then setting TARGET with your PR I have `-mtune was already specified, is now p5600.`

**Comment by martin-frbg** [comment]
Can you try TARGET=24K please (this does not set any `-mtune` at the moment, so if mtune=24kc is inherited this should be best)

**Comment by bhack** [comment]
@martin-frbg Yes see my comment in your PR

**Comment by martin-frbg** [comment]
OK, so back to using TARGET=P5600 for now, can you hack Makefile.system to fix the mtune in addition to the mips revision number in the `ifeq $(CORE), P5600` block ?

**Comment by brada4** [comment]
After taking out `-mnan=2008` it links right, no tests ran though
```
 OpenBLAS build complete. (BLAS CBLAS)

  OS               ... Linux             
  Architecture     ... mips               
  BINARY           ... 32bit                 
  C compiler       ... GCC  (cmd & version : gcc (OpenWrt GCC 7.4.0) 7.4.0)
  Library Name     ... libopenblas_p5600-r0.3.9.dev.a (Single-threading)  
```
Ill try R2, to answer question inregard gcc vs assembly. But that comes with time.

**Comment by bhack** [comment]
@martin-frbg With that
```
mipsel-openwrt-linux-musl-gcc -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -iremap/root/source/build_dir/target-mipsel_24kc_musl/OpenBLAS-0.3.9:OpenBLAS-0.3.9 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -O2 -DMAX_STACK_ALLOC=2048 -Wall -mabi=32 -mips32r2  -DF_INTERFACE_GFORT -fPIC -DNO_LAPACK -DNO_LAPACKE -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DMAX_PARALLEL_NUMBER=1 -DVERSION=\"0.3.9.dev\" -DASMNAME=parameter -DASMFNAME=parameter_ -DNAME=parameter_ -DCNAME=parameter -DCHAR_NAME=\"parameter_\" -DCHAR_CNAME=\"parameter\" -DNO_AFFINITY -I../..
```
But same `rdhwr $2,$30` issue.

**Comment by martin-frbg** [comment]
OK so the -mtune does not help in this regard. So what happens when you change the RPCC macro in common_mips.h, does the rdhwr issue go away then ?

**Comment by martin-frbg** [comment]
@brada4 I am losing track now - was this with the "official" mips toolchain and/or with any changes to the rpcc macro ?

**Comment by brada4** [comment]
@martin-frbg 
https://downloads.openwrt.org/releases/19.07.2/targets/ath79/generic/ by the end of page , file with SDK in the name, its to run on normal linux.

I am building without any change in code. I never saw rdhwr issue with native compiler on openwrt router, and would speculate openwrt cross-compiler is working better.

**Comment by bhack** [comment]
@martin-frbg With that change it works fine. But had many linking fails like

`/mipsel-openwrt-linux-musl/bin/ld: failed to merge target specific data of file ../libopenblas_p5600p-r0.3.9.dev.a(saxpy.o)`

**Comment by brada4** [comment]
Comparing processors mine is Kc , his is KEc, mine has dsp2, theirs 4x DSP1 but no DSP2

**Comment by brada4** [comment]
> @martin-frbg With that change it works fine. But had many linking fails like
> 
> `/mipsel-openwrt-linux-musl/bin/ld: failed to merge target specific data of file ../libopenblas_p5600p-r0.3.9.dev.a(saxpy.o)`

You have to remove nan=2008 to link with openwrt musl libc, e.g. like my experimantation goes.
```
ifeq ($(CORE), P5600)                      
# CCOMMON_OPT += -mnan=2008 -mips32r5 -mtune=p5600  $(MSA_FLAGS)
# CCOMMON_OPT += -mips32r5 -mtune=p5600  $(MSA_FLAGS)
CCOMMON_OPT += -mips32r2 -mtune=p5600  $(MSA_FLAGS)                                 
FCOMMON_OPT += -mips32r5 -mtune=p5600  $(MSA_FLAGS)                    
endif                                                                  
```

**Comment by bhack** [comment]
@brada4 Ok sorry I missed your previous comment now it is ok without the `rdhwr`
```
 OpenBLAS build complete. (BLAS CBLAS)

  OS               ... Linux             
  Architecture     ... mips               
  BINARY           ... 32bit                 
  C compiler       ... GCC  (cmd & version : mipsel-openwrt-linux-musl-gcc (OpenWrt GCC 7.3.0 r7456-ddd04310cb) 7.3.0)
  Library Name     ... libopenblas_p5600p-r0.3.9.dev.a (Multi-threading; Max num-threads is 4)
```

**Comment by bhack** [comment]
That one was `-mips32r2 -mtune=24kc`

**Comment by martin-frbg** [comment]
@brada4 thanks. I doubt the version level of the DSP extensions plays a role here (though DSP2 seems to come with a few vector instructions?).
So the primary result of this thread is that we might want to add an entry to the faq, something like "if you encounter compiler errors about RDHWR when compiling for mips, throw away your compiler and get an officially supported toolchain for your architecture instead" ?

**Comment by brada4** [comment]
`Onion Omega2+` is sort real hardware, just that they did something bad to upstream toolchain when stuffing it into docker..... 
Technically adequate statement, but something that goes easier with exploring first-time user would be better. Actually half of issues are of that kind all the time.

**Comment by bhack** [comment]
I've notfied them at https://github.com/OnionIoT/source/issues/22

**Comment by brada4** [comment]
Please try this SDK in the meantime:
https://downloads.openwrt.org/snapshots/targets/ramips/mt76x8/
Thats what I see in docker menuconfig part if you intend to do full build
![image](https://user-images.githubusercontent.com/16061801/79673127-40521500-81e0-11ea-823a-91e356937155.png)

**Comment by brada4** [comment]
@martin-frbg built with mips32r2 very well
I dont know if it is too much fro test to make simple libm formula and try linking to it for initial test?

**Comment by martin-frbg** [comment]
Sorry I do not understand, simple libm formula for doing what ?

**Comment by brada4** [comment]
Just link an object that certainly uses libm and gets marked with nan=2008 ABI, then would not link in the end.

**Comment by bhack** [comment]
@brada4 I am trying to compile with an updated openwrt (19.07.2) official toolkit. In the main time what do you suggest to use in the Openwrt openblas Makefile WIP. 
For cross-compilation how we could handle OpenBLAS TARGET inside Openwrt?

**Comment by bhack** [comment]
Same problem with Openwrt (19.07.2):
```
{standard input}:209: Error: opcode not supported on this processor: mips32r2 (mips32r2) `rdhwr $2,$30'
{standard input}:233: Error: opcode not supported on this processor: mips32r2 (mips32r2) `rdhwr $2,$30'
{standard input}:319: Error: opcode not supported on this processor: mips32r2 (mips32r2) `rdhwr $2,$30'
```

**Comment by bhack** [comment]
It seems to compile only with `USE_THREAD=0` when we have the unmodified "rpcc" macro in `common_mips.h`

**Comment by brada4** [comment]
Could you post any kind of boot log? We need to know command(s) that led to particualr output.

**Comment by bhack** [comment]
I don't have the card available now. All the things I am testing now are just crosscompilation for that target with fresh Ubuntu 18.04 Docker with a fresh Openwrt 19.0.2 toolkit.
I've tried with USE_THREAD=0 cause I saw that your native test was a single thread build at https://github.com/xianyi/OpenBLAS/issues/2564#issuecomment-615961972

**Comment by bhack** [comment]
Sorry the link to your build was at  https://github.com/xianyi/OpenBLAS/issues/2564#issuecomment-615957300

**Comment by brada4** [comment]
Trying for multiple CPUs for openwrt. I think pthread lib is libc for musl, at least that has symbols.
```
\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  -shared -o ../libopenblas_p5600p-r0.3.9.dev.so \
-Wl,--whole-archive ../libopenblas_p5600p-r0.3.9.dev.a -Wl,--no-whole-archive \
-Wl,-soname,libopenblas.so.0 -lm -lpthread -lm -lpthread
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lpthread
collect2: error: ld returned 1 exit status
```
ath79 cross-compilers had no problems building single-threaded, same link error for multi, could be something particular with ramips, which in particular has less isa extensions than ath79, even though claims MIPS V5.5 where mine says just V5.0

**Comment by martin-frbg** [comment]
-lpthread is currently added unconditionally on MIPS (Makefile.system, exceptions there just for Android and Windows). Not sure how to find out we are going to link against musl eventually.

**Comment by brada4** [comment]
My build command that works after removing fpu=2008, there is no invalid assembly with 2 CPUs, just that -lpthread is not found @bhack - you should patch that out for OpenWRT package, also have in mind arm arches have dynamic arch, and probably everyone tests on x86 where it is a lot more of them.
`make TARGET=P5600 CC=mipsel-openwrt-linux-gcc FC=ERROR HOSTCC=cc NUM_CPUS=1`
I did set up "SDK" as follows. 
```
export PATH=~/openwrt/openwrt-sdk-ramips-mt76x8_gcc-8.4.0_musl.Linux-x86_64/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/bin:$PATH
export STAGING_DIR=~/openwrt/openwrt-sdk-ramips-mt76x8_gcc-8.4.0_musl.Linux-x86_64/staging_dir
```
@martin-frbg musl does not define anything specific, it works with ln -s libc.so libpthread.so (idea taken from xcode/android), does not leave libpthread in imports (not much debug symbols in files, I just deleted the link), Alpine has no such symlink.

**Comment by bhack** [comment]
@brada4 `NUM_CPUS=1` works without `USE_THREAD=0`

**Comment by bhack** [comment]
@brada4 Ops sorry I was on https://github.com/xianyi/OpenBLAS/pull/2565

**Comment by brada4** [comment]
@bhack you can work around the thread issue with symlink as above (ln -s /lib/libc.so /lib/libpthread.so)
I think not mine nor your SoC has 2-processor thing in extant series. But threre are lots of OpenWRT ARM routers, and OpenWRT x86 test machines, where pthreads are of use.

Actually it is written in FAQ that most of the times if no CPU count is specified , the core count is detected from build system, not from target.

I tried with USE_THREAD=0, still no wrong instructions, it turns out `cc` was clang, switching it to gcc, also no bad instructions.
What is so different in the way we approach the compilers? I dont use any special tricks, it just works as I type?

**Comment by bhack** [comment]
I supposed that the Macro removed the assembly but it is not case cause it is working now on https://github.com/xianyi/OpenBLAS/pull/2565

**Comment by brada4** [comment]
@bhack thinking of file naming - best if you call resulting library libblas.so and libcblas.so , so it is replacable at no pain with reference netlib blas (requires fortran) or atlas (needs native compilation that involves hours to days of target calibration at least once)

**Comment by brada4** [comment]
I did not change any macros, just addressed obvious problem striping out fpu=2008 because of `ld`complaining about ABI compatibility, and then added libpthr symlink because of another complaint.

**Comment by bhack** [comment]
I was working on #2565 branch and there is a new `#if !defined(MIPS24K)` for the assembly. But seems that it is not working cause I still have the assembly after postprocessing the Macro and now it compiles without special flags.

**Comment by brada4** [comment]
What command you use for build? I never needed assembly fixups , even with ramips openwrt sdk, actually the resulting library came same size with ramips and ath79 toolchains and ath79 native.

**Comment by bhack** [comment]
The Makefile stub of Openblas is at https://github.com/openwrt/packages/pull/11894.
I cross compile in OpenWRT  `make package/libs/openblas/compile V=s -j`

**Comment by martin-frbg** [comment]
@brada4 I think you are not actually building for TARGET=MIPS24K, which would explain the differences ? @bhack the new `#if defined(MIPS24K)` only removes the RPCC call  with its unsupported hwrdr instruction, but certainly not all assembly. (The error you saw earlier about amax.S was just because the build was not picking up the correct files for the MIPS24K as the name of the KERNEL file did not match)

**Comment by bhack** [comment]
@martin-frbg What i mean is that:
```
cat ./build_dir/target-mipsel_24kc_musl/OpenBLAS-0.3.9/common_mips.h
static inline unsigned int rpcc(void){
  unsigned long ret;

  __asm__ __volatile__(".set   push    \n"
          "rdhwr %0, $30  \n"
          ".set pop" : "=r"(ret) : : "memory");

  return ret;
}
#define RPCC_DEFINED
```

**Comment by martin-frbg** [comment]
Yes, that section should be removed by the preprocessor (and I expect that does happen during the build, if the compiler no longer complains about that instruction).

**Comment by bhack** [comment]
I think this is the one already relsoved or not:

```
#ifndef ASSEMBLER

static inline unsigned int rpcc(void){
  unsigned long ret;

  __asm__ __volatile__(".set   push    \n"
          "rdhwr %0, $30  \n"
          ".set pop" : "=r"(ret) : : "memory");

  return ret;
}
#define RPCC_DEFINED
```

**Comment by bhack** [comment]
Cause the macro was:
```
#ifndef ASSEMBLER

#if !defined(MIPS24K)
static inline unsigned int rpcc(void){
  unsigned long ret;

  __asm__ __volatile__(".set   push    \n"
          "rdhwr %0, $30  \n"
          ".set pop" : "=r"(ret) : : "memory");

  return ret;
}
#define RPCC_DEFINED
#endif
```

**Comment by brada4** [comment]
I built with same openwrt sdk you said does not accept this instruction, what command you use to build, and what gcc gets used? I see no reason for particular change.

**Comment by bhack** [comment]
@brada4 I think we are not using that instruction @martin-frbg explained the behavior  see https://github.com/xianyi/OpenBLAS/pull/2565#discussion_r410948822

**Comment by brada4** [comment]
I am under belief that target machine evenly irradiates my build system and your build system, so behaviour of `as` and `cc1` interactions should be identical. Absence of particular co-processor should give SIGILL or similar at runtime if at all.

**Comment by bhack** [comment]
So on an ubuntu host can you cross-compile with `make package/libs/openblas/compile V=s -j` on master hash?

**Comment by brada4** [comment]
I know nothing about packaging system, I am just telling that particular SDK compiles OpenBLAS with minimal changes, no idea what is missing.

**Comment by bhack** [comment]
@brada4 How we can reproduce the same execution? Can you share a Dockerfile?

**Comment by bhack** [comment]
The official openwrt image where you can compile for that arch is ` docker run --rm  -it openwrtorg/sdk:ramips-mt76x8-19.07.2`

**Comment by bhack** [comment]
Basic commands are at https://hub.docker.com/r/openwrtorg/sdk

**Comment by brada4** [comment]
in include/toplevel.mk
```
# make sure that a predefined CFLAGS variable does not dist
export CFLAGS=
export LDFLAGS=
```
zap both lines and replace with
```
unexport CFLAGS LDFLAGS
```
Thats a bug in openwrt SDK that makes it different from plain make with SDK compiler.
You can probably unexport those in package file, if that succeeds plese review validity and need of all changes here.
PS I am against using multi-gigabyte docker 'microservices'

**Comment by commodo** [comment]
> /cc @commodo if you are interested for the openwrt part of the thread.

[we had easter this weekend :) so a bit slow on the reply]
openblas is a bit far from my current interest;
i am bit interested in numpy atm;
maybe later; after i get to take a look at numpy + openwrt;
