### ISSUE TITLE
TARGET for cross-compililng

### ISSUE THREAD

**Issue by bhack** [xianyi/OpenBLAS#2570]
Hi I am trying to create an official OpenBlAS package for openwrt at https://github.com/openwrt/packages/pull/11894.
As it cross-compile for many target archs it already set `-march` and `-mtune`  correctly but it is hard to find an elegant way to set the required `TARGET` from https://github.com/xianyi/OpenBLAS/blob/develop/TargetList.txt.
Is there a more automatic that Openblas can retrieve the `TARGET` in cross-compilation from `-march` `-mtune` directly?

**Comment by martin-frbg** [comment]
Normally it would more likely be the other way around - setting -march/-mtune for the selected TARGET. For most architectures (except mips and armv7, but they are both essentially one set of codes for all "supported" cpus) it is now possible to build one big library with optimized code for a number of cpu types (DYNAMIC_ARCH), where you would set TARGET to the oldest cpu you are expecting to encounter (this determines what all the common code is compiled for).

**Comment by bhack** [comment]
Yes but there for all the packages of the distro the process Is inverted. It Is not so good TARGET cause also we are talking about an embedded distro with many mips, arm, etc.. that are dinamically handled by mtune and march flags.

Also the target size It Is imporant for embedded image so we cannot build a big lib with all the targets as in not armi, mips dynamic approach that you have.

**Comment by brada4** [comment]
You can only append C flags. i.e no -Os.
You can still apply distro patches and use least common denominator of flags or even build generic C codes only. I assume your current intent is to provide (C)BLAS API as such. 
x86_64 single target arch will be 5-6MB, all together 30-some stripped, thats quite over the roof of idea of embedded.

**Comment by bhack** [comment]
@brada4 Thanks. I know that the "universe" is patchable or that I could bulid generic C. 
I am just asking why `-march/-mtune` cannot be reverse mapped to TargetLists.txt to satisfy your mandatory `TARGET` when cross-compiling.

Cause I see also other distros need to try to [reverse mapping arch](https://github.com/CogentEmbedded/meta-opencl/blob/master/meta-ocl-common/recipes-graphics/openblas/openblas_git.bb#L15) to satisfy `TARGET`.

**Comment by brada4** [comment]
Here are package arches, you just reverse map them to respective OpenBLAS arch once.
https://downloads.openwrt.org/snapshots/packages/
If you find any regressions, you are more than welcome to show up with them before resorting to distro patches.
PS That ARM matching example is already obsolete, there is DYNAMIC_ARCH on arm, just like on x86, but that is outside scope of your effort.

**Comment by bhack** [comment]
Ok I will wait @commodo on the Openwrt Openblas PR to see how we could organize this rosetta stone between openwrt arches and  `TargetLists.txt`.
On many arches we don't have the same atomic semantics (i.e. X86) but probably there we could use `DYNAMIC_ARCH` there.

**Comment by brada4** [comment]
Lets first focus on getting least-common-denominator  CPU codes to provide viable working API first.

Current MIPS24K is that thing, real 24K would need `r5 -mdsp` , then real 74k some more.

32bit PPC is largely abandoned, and arc is non-existent, but probably generic C codes could be provided to have better coverage.

**Comment by martin-frbg** [comment]
Where do your CFLAGS get set ? Assuming that you already have some kind of "matrix" of build targets for the compiler, that might be the place to add a corresponding TARGET for each -march/-mtune combination, rather than try to to figure out a reverse mapping onto a cpu model
from within the OpenBLAS build system. (Also how many cpu/architecture builds do you expect to
cross-compile rather than compile on native hardware where the TARGET can get autodetected ? I suspect with OpenWRT you will mainly be interested in small, low-power setups, so probably not the entire range of x86_64 but just Atom and/or Nehalem, and certainly no powerpc or zarch)
(@brada4 I am still not convinced that a 24K would be r5 rather than r2 - and DSP support would
probably be irrelevant to building OpenBLAS)

**Comment by brada4** [comment]
DSP is floating point SIMD, with good wind it would vectorize explicit unrolls like for SSE.
Indeed there is no additional mandatory floating point ISA in R5 over R2 (but DSP in 24K) to put any hopes on. DSP1 is smaller than SSE1, but still some beef.
74K has mandatory DSP2 and FPU, that would need the precise flags, with measurements.

**Comment by martin-frbg** [comment]
From https://gcc.gnu.org/onlinedocs/gcc/MIPS-DSP-Built-in-Functions.html#MIPS-DSP-Built-in-Functions it looks to me as if the DSP/DSP2 instruction set is only for special packed float formats, so probably not usable just by letting the compiler/optimizer do its thing.

**Comment by bhack** [comment]
@martin-frbg 
https://s3-eu-west-1.amazonaws.com/downloads-mips/documents/24ke.pdf

https://s3-eu-west-1.amazonaws.com/downloads-mips/mips-documentation/login-required/five_methods_of_utilizing_the_mips_dsp_ase.pdf

**Comment by bhack** [comment]
> Where do your CFLAGS get set ? Assuming that you already have some kind of "matrix" of build targets for the compiler, that might be the place to add a corresponding TARGET for each -march/-mtune combination, rather than try to to figure out a reverse mapping onto a cpu model
from within the OpenBLAS build system.

https://github.com/openwrt/openwrt/blob/master/include/target.mk

Here instead the `ARCH` list:
https://github.com/openwrt/openwrt/blob/master/target/Config.in

**Comment by martin-frbg** [comment]
Thanks. First is where I got the information from that the 24K family is mips32r2 not r5 as brada4 seems to assume. Might be interesting to see what compiling with `-ftree-vectorize -mdsp  -fdump-tree-vect-stats` results in (but I still have not dug out my 1004K, nor had time to build the docker image you linked to).

**Comment by bhack** [comment]
OK but you don't need to build the docker image cause the image is ready to download. You need only to run the command the toolchain is already compiled.

**Comment by brada4** [comment]
MIPS docs are public, no need to deep-link to clouds
https://www.mips.com/products/classic/

**Comment by bhack** [comment]
But seems are not so well inexed for search engines :smile: 
So the official download for "Five Methods of Utilizing the MIPS® DSP ASE" is at https://www.mips.com/downloads/five-methods-of-utilizing-the-mips-dsp-ase/

**Comment by brada4** [comment]
Yes, the auto-vectorizer report welcome.
https://github.com/xianyi/OpenBLAS/issues/2570#issuecomment-617678986

**Comment by bhack** [comment]
In the Openwrt sdk docker for the 24K target you can find the log at https://gist.github.com/bhack/631aa01dc1506a3054f1e1273fa49c89

**Comment by brada4** [comment]
`-ftree-vectorize -mdsp -mdspr2 -fopt-info-vec-optimized`
... nothing got optimized ... EDIT: in all 4 combinations.
if `s/otimized/missed/` you get following all round
```
note: not vectorized: not enough data-refs in basic block.
```

I hit this weird stuff - not sure it tells you something
```
memory.c:96:2: warning: #warning BUFFER_SIZE is too small for P, Q, and R of SGEMM - large calculations may crash ! [-Wcpp]
 #warning BUFFER_SIZE is too small for P, Q, and R of SGEMM - large calculations may crash !
  ^~~~~~~
```

**Comment by martin-frbg** [comment]
Confirms my suspicion that code would need to be actively rewritten to make use of what limited DSP/vector capability is available. (The weird stuff is from issue 2538, PR 2551 - MIPS/MIPS64 has not been checked for this yet)

**Comment by brada4** [comment]
Also DSP is on-demand processor part, which means never seen thermal output.

I tried a "rewrite" with godbolt.org (mips compilers dont work from list, default haswell gcc was ok), making special case for inc?==1 on copy.c - optimizes, at least says so.

**Comment by brada4** [comment]
x86(_64) reverse dictionary:
In context of OpenWRT - all new intel Lantiq SoCs are ATOM-based, thats fine for x86_64 and "pentium4" x86
For x86 "pentium" - let it be P5
