### ISSUE TITLE
how to enable cblas_cgemm3m in windows

### ISSUE THREAD

**Issue by insar-dev** [xianyi/OpenBLAS#2572]
when i use cblas_cgemm3m in vs2019,  it occurs compile error:error LNK2019: unresolved external symbol cblas_cgemm3m referenced in function,how to solve it?

**Comment by martin-frbg** [comment]
Do you see anything about cgemm3m or cblas_cgemm3m in the build log ? The GEMM3M functions in OpenBLAS should be available on x86, x86_64, mips (and ia64 if that still exists).

**Comment by insar-dev** [comment]
i can see cgemm3m_(not cgemm3m ) in the openblas.lib file,but when i use it ,the app crashes。@martin-frbg

**Comment by martin-frbg** [comment]
What is your hardware ? It is possible that the recently rewritten cgemm3m kernels for Haswell and SkylakeX were not tested on windows, but as they use intel intrinsics I'd think the compiler should be able to handle any os-specific differences.  (cgemm3m kernels for older cpus use assembly directly, but in a syntax that VS does not understand, so you would get generic C kernels - again these should work)

**Comment by insar-dev** [comment]
my hardware is "intel core i9 Coffe lake" read  from CPU-Z ,openblas compile info is "OpenBLAS 0.3.9 DYNAMIC_ARCH NO_AFFINITY Haswell"。how can i direct use the api cblas_cgemm3m in the cblas.h?

**Comment by martin-frbg** [comment]
It does look as if there is an error in our cmake support files (which are used on Windows) and the CBLAS interfaces to the GEMM3M functions are not getting built by VS2019. Could you try changing the line in interface/CMakeLists.txt that reads
`GenerateNamedObjects("gemm.c" "GEMM3M" "gemm3m" false "" "" false ${float_type})`
to 
`GenerateNamedObjects("gemm.c" "GEMM3M" "gemm3m" ${CBLAS_FLAG} "" "" false ${float_type})` (change the first "false" to "${CBLAS_FLAG}") and rebuild OpenBLAS ?
