### ISSUE TITLE
Problems with Android

### ISSUE THREAD

**Issue by UO258198** [xianyi/OpenBLAS#2574]
Hi, I'm trying to use OpenBLAS on Android but I have some problems.

First, I use this code to compile.
`export TOOLCHAIN=/Users/alberto/Library/Android/sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/darwin-x86_64/

make CC=$TOOLCHAIN/bin/armv7a-linux-androideabi21-clang AR=$TOOLCHAIN/bin/arm-linux-androideabi-ar RANLIB=$TOOLCHAIN/bin/arm-linux-androideabi-ranlib TARGET=ARMV7 BYNARY=32 HOSTCC=gcc USE_OPENMP=1 ARM_SOFTFP_ABI=1 NOFORTRAN=1 -j4

make PREFIX=/Users/alberto/Downloads/OpenBLASCompilado/armeabi-v7a install

make CC=$TOOLCHAIN/bin/aarch64-linux-android21-clang AR=$TOOLCHAIN/bin/aarch64-linux-android-ar RANLIB=$TOOLCHAIN/bin/aarch64-linux-android-ranlib TARGET=CORTEXA57 BYNARY=64 HOSTCC=gcc USE_OPENMP=1 NOFORTRAN=1 -j4

make PREFIX=/Users/alberto/Downloads/OpenBlasCompilado/arm64-v8a install`

After that I get some .so files that I use on my Android project.
![image](https://user-images.githubusercontent.com/55456543/79972274-fc883580-8495-11ea-934a-e77e153db7be.png)

Then, in the CMakeLists.txt I use the following lines to be able to use the library

`add_library(OpenBLASCompilado SHARED IMPORTED)
set_target_properties(OpenBLASCompilado PROPERTIES IMPORTED_LOCATION OpenBLASCompilado/${ANDROID_ABI}/lib/libopenblas.so)
include_directories(OpenBLASCompilado/${ANDROID_ABI}/include)
link_directories(OpenBLASCompilado/${ANDROID_ABI}/lib)`

But when I have to build the Android project I always get the same error:
`Build command failed.
Error while executing process /Users/alberto/Library/Android/sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C /Users/alberto/AndroidStudioProjects/PruebaC4/app/.cxx/cmake/debug/armeabi-v7a CardioPulmon fftw3 fftw3_omp}
ninja: Entering directory `/Users/alberto/AndroidStudioProjects/PruebaC4/app/.cxx/cmake/debug/armeabi-v7a'

ninja: error: 'OpenBLASCompilado/armeabi-v7a/lib/libopenblas.so', needed by '/Users/alberto/AndroidStudioProjects/PruebaC4/app/build/intermediates/cmake/debug/obj/armeabi-v7a/libCardioPulmon.so', missing and no known rule to make it

`

Does anyone know what the problem might be?

**Comment by martin-frbg** [comment]
perhaps try specifiying the full path to the library (/Users/Alberto/Downloads/... ?)  instead of starting it at "OpenBLASCompilado/..." . Also (unless that is just a typo here)  you seem to have OpenBLASCompilado4 in the PREFIX you installed to, but only OpenBLASCompilado without the number in the add_library ?

**Comment by UO258198** [comment]
> perhaps try specifiying the full path to the library (/Users/Alberto/Downloads/... ?) instead of starting it at "OpenBLASCompilado/..." . Also (unless that is just a typo here) you seem to have OpenBLASCompilado4 in the PREFIX you installed to, but only OpenBLASCompilado without the number in the add_library ?

I tried specifiying the full path but I got the same problem. The second problem you mention is not important because those files were copied to another folder inside the Android project

**Comment by martin-frbg** [comment]
Well I can only comment on what you have shown, not on what I do not see. But if you are certain there is nothing wrong with the path names you used, perhaps the error message is misleading and it is not missing libopenblas.so itself but one of its dependencies - this could be libpthread.so

**Comment by UO258198** [comment]
I believe there's nothing wrong with the paths. How do I know if one of its dependencies are missing?

**Comment by martin-frbg** [comment]
If you have `ldd` available on that platform you could do `ldd libopenblas.so`. (The "p" in the full name of the library suggests that it was built for pthreads-based multithreading, so if your environment has pthreads as a separate library  libpthreads.so it is most likely needed).

**Comment by UO258198** [comment]
> If you have `ldd` available on that platform you could do `ldd libopenblas.so`. (The "p" in the full name of the library suggests that it was built for pthreads-based multithreading, so if your environment has pthreads as a separate library libpthreads.so it is most likely needed).

As far as I know, there shouldn't be problems with dependencies using the Android ndk

**Comment by martin-frbg** [comment]
As far as I know, there shouldn't be problems with linking OpenBLAS, so ?
Probably there are ways to make ninja be more verbose about what it tries to do, or cmake flags that make it enumerate the paths it is actually searching for libraries.

**Comment by martin-frbg** [comment]
Perhaps `make VERBOSE=1` or setting `CMAKE_EXE_LINKER_FLAGS  "-L/path/to/openblas/"
can help to debug this ? Or attach your entire CMakeLists.txt (for someone with more cmake experience than me). Still pretty sure this is not an OpenBLAS problem as such.

**Comment by UO258198** [comment]
I think the problem was that it's not compatible with the latest version of the Android ndk. 
Now the problem I have is that I can't compile Lapack's functions with Android's ndk. Do you know if there is any already compiled version of this Android library with the Lapack functions?

**Comment by martin-frbg** [comment]
Unfortunately I am not aware whether it is already possible to add a fortran compiler (flang) to the current ndk now that it switched to using clang instead of gcc. All the old instructions in our wiki point to a special build of NDK revision 13 from a time when gcc was still supported. The test builds I do locally are created on native (non-Android) Linux systems without the NDK, and I am not familiar enough with the Android ecosystem to know if they would be compatible.

**Comment by brada4** [comment]
@UO258198 you can install gfortran in Android Termux
https://github.com/its-pointless/gcc_termux
It builds usable library linked with recent NDK
File juggling I leave to you (hint: sftp), there is really no solution involving cross-compilers from where Android Studio runs.

**Comment by martin-frbg** [comment]
Yes termux would appear to be the best option right now, as flang still does not appear to be configurable for cross-compiling. I just have never used OpenBLAS builds from it outside the termux environment - if they can be used in building native Android programs, this information certainly needs to be put on the wiki page.

**Comment by martin-frbg** [comment]
There is also dockcross https://github.com/dockcross/dockcross - various cross-compiler toolchains wrapped in Docker images - which has arm and arm64 androideabi variants with gcc/gfortran at NDK rev. 16.
(Google found me a nice writeup on running these in an Azure CI environment, thinking about borrowing ideas from there to set up build&utest checks for MIPS - https://ariya.io/2019/07/continuous-integration-of-vanilla-c-programs-for-intel-arm-and-mips-architecture)
