### ISSUE TITLE
blas_memory_alloc very slow when in omp region

### ISSUE THREAD

**Issue by insar-dev** [xianyi/OpenBLAS#2575]
my program have lots of small matrix, and i put blas_cgemm in omp region,vtune profilter reports that it spend lost of time on blas_memory_alloc, my code look likes follow:

openblas_set_num_threads(1);
#pragma omp parallel for
for(int i = 0; i < count; ++i)
{
       while(condition)
      {
            //small matrix, [1 100] * [100 100] or [1 32] * [32 32]
            blas_cgemm();
      }
}
i also have use mkl to run, openblas slows than mkl (about 10%).
how can blas_cgemm avoid using blas_memory_alloc?

**Comment by brada4** [comment]
How big is the CPU? What operating system? What OpenBLAS version?
Do you use OpenMP enabled OpenBLAS? In this case setting threadis is not necessary, it will detect parallel sesction.

> how can blas_cgemm avoid using blas_memory_alloc?

Same as asking why do computers have memory at all.

**Comment by martin-frbg** [comment]
You could try building OpenBLAS with USE_TLS=1 to make it use thread-local storage instead of the big common buffer. This option is less well tested however. @brada4 from yesterday's ticket this is on Intel Coffee Lake running Windows.

**Comment by insar-dev** [comment]
@brada4 
operating system: win10
OpenBlas Version:0.3.9
OpenMP:disable

this is my cpu info:
![cpu](https://user-images.githubusercontent.com/1676595/80075644-9d055500-857d-11ea-9393-b89d45e7a9f0.png)

@martin-frbg if i building with USE_TLS=1, will it  effect large matrix?
thanks for reply!

**Comment by martin-frbg** [comment]
It should work for large matrix cases as well, but as I wrote this option is less well tested - the code was contributed by some guys from google who dropped out of the discussion before all bugs got fixed, so I am not entirely sure I did things right.

**Comment by insar-dev** [comment]
i will try it later, thank you!@martin-frgb
