### ISSUE TITLE
Build fails when build directory contians spaces

### ISSUE THREAD

**Issue by menkaur** [xianyi/OpenBLAS#2576]
I downloaded the source into directory that contained a space and tried to compile it. The compilation failed with following error:

c1 : fatal error C1083: Cannot open source file:
'source/OpenBLAS/build/getarch_build': No such file or directory [G:\c++
source\OpenBLAS\build\getarch_build\CMakeFiles\CMakeTmp\cmTC_8aa90.vcxproj]

The error disappeared when I removed the space from "c++ source" directory name

**Comment by martin-frbg** [comment]
Thanks, this appears to be entirely due to two unquoted include paths in the compilation of a tool.
