### ISSUE TITLE
Memory usage on startup

### ISSUE THREAD

**Issue by ViralBShah** [xianyi/OpenBLAS#258]
In general I have noticed that openblas tends to take up a lot of memory on startup. This typically increases when compiled with a large number of max threads, such as 128, which is what we do in the julia distribution.

I believe this was largely due to allocation on the stack, but with the new heap allocation code, is it possible that the memory footprint of openblas can be brought down, and memory is only allocated for the number of threads that are launched? In most cases, people only end up using 2 or 4 cores.

**Comment by caojiaqi** [comment]
HI, xianyi, I'm using sgemm on arm cortex a9, openblas was compiled without multi-thread support, the deploy environment is quite memory constrained, is it possible to manage the internal workspace outside even if some performance drop may be incurred? Or in this kind of scenario, any suggestions from you? Thanks.

**Comment by ViralBShah** [comment]
I must say that we have received a fair number of complaints about this memory consumption over time, and perhaps it would be better to allocate at runtime based on number of cores.

**Comment by caojiaqi** [comment]
@xianyi
