### ISSUE TITLE
Sometimes very bad performance of cblas_sgemm on Samsung S7 (and other Exynos phones?) with OMP_NUM_THREADS=4

### ISSUE THREAD

**Issue by alexeyr** [xianyi/OpenBLAS#2589]
The following code
```
#include "cblas.h"
#include <chrono>
#include <random>
#include <algorithm>
#include <limits>
#include <iostream>

int main(int argc, char** argv) {
    constexpr int m = 128, n = 64, k = 768, attempts = 100;
    float a[k * m], b[n * k], c[n * m];
    std::minstd_rand gen;
    std::fill_n(c, n * m, 0);

    int min = std::numeric_limits<int>::max(), max = std::numeric_limits<int>::min();
    double sum = 0;
    for (int i = 0; i < attempts; i++) {
        std::generate_n(a, k * m, gen);
        std::generate_n(b, n * k, gen);
        auto start = std::chrono::steady_clock::now();
        cblas_sgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans, m, n, k, 1.0,
                    a, k, b, n, 1.0, c, n);
        int diff = std::chrono::duration_cast<std::chrono::microseconds>(
            std::chrono::steady_clock::now() - start).count();
        sum += diff;
        min = std::min(min, diff);
        max = std::max(max, diff);
    }
    std::cerr << "Min: " << min << ", max: " << max << ", mean: " << sum / attempts << "\n";

    return 0;
}
```
gives consistent results on my Samsung S7 Edge (the Exynos version) when run with `OMP_NUM_THREADS=2`:
```
hero2lte:/ $ for i in 1 2 3 4 5 6 7 8 9 10; do OMP_NUM_THREADS=2 /data/local/tmp/encoder_sample; done 
Min: 1206, max: 5058, mean: 1270.65
Min: 1200, max: 4829, mean: 1259.47
Min: 1207, max: 4751, mean: 1262.73
Min: 1212, max: 5921, mean: 1295.69
Min: 1205, max: 4738, mean: 1270
Min: 1212, max: 4637, mean: 1267.83
Min: 1203, max: 5318, mean: 1266.7
Min: 1218, max: 4621, mean: 1274.14
Min: 1214, max: 4861, mean: 1287.41
Min: 1205, max: 4965, mean: 1277.11
```
But `OMP_NUM_THREADS=4` gives something like
```
130|hero2lte:/ $ for i in 1 2 3 4 5 6 7 8 9 10; do OMP_NUM_THREADS=4 /data/local/tmp/encoder_sample; done                              
Min: 1050, max: 14507, mean: 1291.4
Min: 1400, max: 13520, mean: 1599.03
Min: 1381, max: 13113, mean: 1571.65
Min: 1393, max: 9575, mean: 1580.16
Min: 55965, max: 98585, mean: 65195
Min: 945, max: 43219, mean: 2431.44
Min: 1275, max: 68717, mean: 2700.56
Min: 55915, max: 103316, mean: 64446.7
Min: 926, max: 80020, mean: 9143.66
Min: 1265, max: 6865, mean: 1479.05
```
As you can see, most runs are fine but there are not just bad outliers but runs where the _miminum_ result is awful. We've also seen similar problems with our actual code on S9, but some other phones work fine, so my guess is that the problem might be Exynos CPUs (haven't tried a non-Exynos Samsung).

Built according to https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android#build-armv8-with-clang. I tried compiling `develop` branch and the 0.3.9 release, using `TARGET=ARMV8` and `TARGET=CORTEXA57`.

**Comment by martin-frbg** [comment]
Seeing that the S7 has an Exynos with four fast and four slow cores, a possibility could be that OpenMP tasks get scheduled onto some or all of the slower ones sometimes.  Can you try to bind processes to specific cores with OMP_PLACES ?

**Comment by alexeyr** [comment]
I thought I'd have to figure out which cores are which, but just `OMP_PLACES=cores` appears to solve the problem. The strange thing is that one of the phones which _doesn't_ have the problem is also 4+4 (Honor 8, 4x2.3 GHz Cortex-A72 & 4x1.8 GHz Cortex A53). Thank you!

**Comment by martin-frbg** [comment]
Thanks for the feedback, I have amended the FAQ in the wiki accordingly.

**Comment by alexeyr** [comment]
Fun addition: for `OMP_NUM_THREADS=2`, `OMP_PLACES=cores` halves the performance (I've tried to find another value which doesn't, but unsuccessfully). Maybe also change the title in the FAQ from "on my ARMV7 board" to "ARM" or "ARMV7/ARMV8"?

**Comment by alexeyr** [comment]
Fun addition: for `OMP_NUM_THREADS=2`, `OMP_PLACES=cores` halves the performance on this phone (`cores(2)` instead maintains the default). 

Maybe also change the title in the FAQ from "on my ARMV7 board" to "ARM" or "ARMV7/ARMV8"?

**Comment by martin-frbg** [comment]
Guess that deserves its own FAQ entry rather than being tacked onto the ARMV7 topic. The num=2 result is "interesting" - wonder if specifying just "cores" makes a thread wander about and lose its cache, and/or if that is intended behaviour or a bug in libgomp...
