### ISSUE TITLE
Does OpenBLAS support csrmm?

### ISSUE THREAD

**Issue by chenxuhao** [xianyi/OpenBLAS#2592]
Hi,
I wonder if OpenBLAS supports csrmm? Thank you.

csrmm in MKL:
https://software.intel.com/en-us/mkl-developer-reference-c-mkl-csrmm

csrmm in cuda:
https://docs.nvidia.com/cuda/cusparse/index.html#csrmm

**Comment by martin-frbg** [comment]
OpenBLAS does not currently have this extension (nor sparse matrix codes in general).

**Comment by chenxuhao** [comment]
> OpenBLAS does not currently have this extension (nor sparse matrix codes in general).

Thank you so much
