### ISSUE TITLE
Failed to compile example

### ISSUE THREAD

**Issue by CharlesHua** [xianyi/OpenBLAS#2593]
Failed to compile example with report:
./common.h: In function 'blas_unlock':
./common.h:693:3: error: 'MB' undeclared (first use in this function)

common.h 文件中的static __inline void blas_unlock() 中有一个 “MB”，没有被定义或展开。是不是我少安装了什么包或者库？

**Comment by martin-frbg** [comment]
Which version of OpenBLAS is this please, which example, and compiled on what platform ? The declaration of "MB" is internal to OpenBLAS (to be found in the individual `common_<architecture>.h` files included from common.h).
Most importantly no user code outside OpenBLAS should normally include common.h (or any of the other headers in the source directory), only the cblas.h (and/or f77blas.h, lapacke.h) that get installed by a `make install`.

**Comment by CharlesHua** [comment]
Thanks. The example in https://gist.github.com/xianyi/6930656.
OpenBLAS-0.3.9, on Unbuntu with gcc 4.8.5

**Comment by CharlesHua** [comment]
Actually I find no file named common_.h, but only to find common_d.h, common_c.h, and others.

**Comment by martin-frbg** [comment]
Fixed the formatting of my reply... these are common_arm.h,  common_x86_64.h and the like. Still I do not see why the example you linked to would try to include common.h, unless you tried to include the preliminary template version of cblas.h that is in the source tree - among other things, `make install` will replace the "common.h" in this file with "openblas_config.h" when creating the actual cblas.h in the installation directory.
