### ISSUE TITLE
How to generate OpenBLASConfig.cmake in Linux

### ISSUE THREAD

**Issue by zchrissirhcz** [xianyi/OpenBLAS#2595]
With the lastest version of OpenBLAS source code.

I've tried in build openblas with cmake in Windows:
```bash
cd build/vs2017-x64
cmake ../.. -G "Visual Studio 15 2017 Win64"
```
This will generate 'OpenBLASConfig.cmake' in `/path/to/install/share/cmake/OpenBLAS` folder.

However, `OpenBLASConfig.cmake` file is not generated in Linux. Is there any trick that can generate it? Is there any plan that this file be generated on default in the future?

Btw, in Windows the `OpenBLAS_LIBRARIES` cmake variable is just empty, while `OpenBLAS_LIBRARY` is with correct value. This is not as what `OpenBLASConfig.cmake`'s comment says:
```cmake
#   OpenBLAS_LIBRARIES - OpenBLAS library to link against.
#   OpenBLAS_LIBRARY - same as LIBRARIES
```

**Comment by martin-frbg** [comment]
The OpenBLASConfig.cmake does get generated on Linux, but only in the `make install` step. If your build does not install it, could you please upload a complete build log ?
I cannot really comment on the OpenBLAS_LIBRARY vs OpenBLAS_LIBRARIES topic, but as the
cmake config file is mainly using basic CMAKE commands it could be that it depends on CMAKE version and environment which of the two gets set ?

**Comment by zchrissirhcz** [comment]
@martin-frbg  Thanks for reply. 

I notice that in Linux I was using the lastest code of master branch instead of develop branch, sorry for the miss-understanding. Actually I just import this repo into a proxy website (https://gitee.com) for fast clone in P.R. China and that mirror on default gives master branch. Now I switched to develop branch and see OpenBLASConfig.cmake as you said.
