### ISSUE TITLE
Please add SONAME to shared libraries

### ISSUE THREAD

**Issue by yurivict** [xianyi/OpenBLAS#2599]
https://en.wikipedia.org/wiki/Soname

Otherwise it's unclear if all ports depending on openblas should be rebuilt or not.

**Comment by martin-frbg** [comment]
This appears to have been removed by PR #301 seven years ago - probably inadvertently, as its description only mentions a change immediately adjacent to the deleted soname directive.

**Comment by yurivict** [comment]
You also install versioned library names, like ```/usr/local/lib/libopenblasp-r0.3.9.so``` where the version is in the name: ```r0.3.9```.  This should be handled through SONAME.

**Comment by martin-frbg** [comment]
True, but the versioned library names also come with a softlink to the generic name. If a distribution wants to handle this differently I think this is best changed on the distribution packaging side.

**Comment by yurivict** [comment]
Some (or all) packages are linked to libopenblas-rN.N.N.so versions forcing to rebuild such dependencies.

The ```-rN.N.N``` suffix duplicates what SONAME should have done. This is why it is relevant here, and ```-rN.N.N``` should be removed as part of (re)adding of SONAME.

**Comment by martin-frbg** [comment]
I am not convinced the rN.N.N names should be removed, they have been there throughout the development starting from GotoBLAS and IMHO they complement the internal SONAME information as a trivially human-readable counterpart. If other packages in FreeBSD happen to be linked against the versioned names this is not necessarily the fault of OpenBLAS.

**Comment by yurivict** [comment]
> they complement the internal SONAME information as a trivially human-readable counterpart.

The problem is that they force to upgrade all depending packages, regardless of SONAME, so they defeat the purpose of SONAME.

**Comment by martin-frbg** [comment]
I may be missing something obvious, but I do not get why you cannot link against libopenblas.so (or libopenblasp.so) and have the actual version be determined by an appropriate link at runtime ? (We could certainly treat FreeBSD as a special case as far as library _file_ naming is concerned, but I'd like to understand what makes it special.) The SONAME entry will return soon, unless somebody comes up stating that it was indeed removed on purpose (which does not seem likely)

**Comment by brada4** [comment]
blas and lapack stand still at v3 for 20-some years. And it is just that API being provided.

**Comment by yurivict** [comment]
> I may be missing something obvious, but I do not get why you cannot link against libopenblas.so (or libopenblasp.so

Several or all depending projects de-facto link to ```libopenblas-rN.N.N.so```. They follow the symbolic links. I think toolchains to this for SONAMEed libraries, because SONAME is implemented through symlinks.

**Comment by isuruf** [comment]
AFAIK, SONAME has been `libopenblas.so.0` on Linux for a long time and `install_name` on OSX has been `libopenblas.0.dylib` for a couple of releases. Is this not true?

**Comment by martin-frbg** [comment]
Yes, it is just the `*BSDs` that had their SONAME entry get lost in what looks like an editing mishap on an unrelated change.

**Comment by martin-frbg** [comment]
This was actually fixed by #2541 four weeks ago, leaving only a few other BSD variants without SONAME

**Comment by brada4** [comment]
> Several or all depending projects de-facto link to libopenblas-rN.N.N.so

It is not necessary to rebuild all dependent libraries when you update blas, API is stable for 20-some years. You could build everything against libblas.so(.3) then use libmap to supplant it with OpenBLAS, Atlas, or if it works - MKL.

**Comment by yurivict** [comment]
This symlink makes rebuilding dependencies necessary just because of the shared libary name change.

**Comment by brada4** [comment]
Dynamic libraries are meant to prevent that...

**Comment by isuruf** [comment]
@brada4, you can't build everything against libblas.so.3 because there are packages using openblas specific functions and extensions.

> Dynamic libraries are meant to prevent that...

That's not true. Dynamic libraries + SONAME prevents that. Having a SONAME that updates every version requires a rebuild every version.

Anyway as @martin-frbg said, this issue is fixed in develop branch.

**Comment by brada4** [comment]
> packages using openblas specific

It is just few of them, and such use is likely optional. Lets outweight what is our target - make maximum rebuilds, or trust stable API as it is?
