### ISSUE TITLE
"#include <lapacke.h>" causes "error: templates must have C++ linkage"

### ISSUE THREAD

**Issue by yurivict** [xianyi/OpenBLAS#2600]
This code:
```
#include <lapacke.h>

void f() {
}
```

worked with openblas-0.3.7,
nit now it fails with openblas-0.3.9:
```
$ c++ -c testcase-openblas.cpp -I /usr/local/include/
In file included from testcase-openblas.cpp:6:
In file included from /usr/local/include/lapacke.h:37:
In file included from /usr/local/include/lapack.h:58:
In file included from /usr/include/c++/v1/complex:244:
In file included from /usr/include/c++/v1/stdexcept:45:
/usr/include/c++/v1/exception:165:1: error: templates must have C++ linkage
template<class _Ep>
^~~~~~~~~~~~~~~~~~~
```

FreeBSD 12.1
clang-9

**Comment by martin-frbg** [comment]
Should already be fixed in develop branch by #2512

**Comment by yurivict** [comment]
IMO you should make a release with this fix, because this problem broke some user code.

**Comment by martin-frbg** [comment]
At a guess at least half the commits on average are fixes for problems that broke something for someone, but creating a new release every other week makes little sense either
