### ISSUE TITLE
cmake error on POWER9 due to recent  utils.cmake check

### ISSUE THREAD

**Issue by RajalakshmiSR** [xianyi/OpenBLAS#2604]
-- Reading vars from /home/r/code/tmp/ORG/OpenBLAS/kernel/power/KERNEL.POWER9...
CMake Error at cmake/utils.cmake:66 (if):
  if given arguments:

    "STREQUAL" "__ORDER_BIG_ENDIAN__"

  Unknown arguments specified
Call Stack (most recent call first):
  kernel/CMakeLists.txt:16 (ParseMakefileVars)
  kernel/CMakeLists.txt:572 (build_core)

-- Configuring incomplete, errors occurred!
See also "/home/r/code/tmp/ORG/OpenBLAS/CMakeFiles/CMakeOutput.log".

**Comment by RajalakshmiSR** [comment]
@martin-frbg  Looks like there are new checks added in commit e7bbdfdf84419254743d2f4e7c09d1333e5b38ba.  Can this help?
diff --git a/getarch.c b/getarch.c
index c173d58b..c986e43b 100644
--- a/getarch.c
+++ b/getarch.c
@@ -1364,6 +1364,8 @@ int main(int argc, char *argv[]){
 printf("__BYTE_ORDER__=__ORDER_BIG_ENDIAN__\n");
 #elif defined(__BIG_ENDIAN__) && __BIG_ENDIAN__ > 0
 printf("__BYTE_ORDER__=__ORDER_BIG_ENDIAN__\n");
+#else
+printf("__BYTE_ORDER__=__ORDER_LITTLE_ENDIAN__\n");
 #endif
 #if defined(_CALL_ELF) && (_CALL_ELF == 2)
 printf("ELF_VERSION=2\n");

**Comment by martin-frbg** [comment]
Ah sorry, looks like I committed another half-baked solution there. While your suggestion will certainly fix the issue at hand, I guess I should look into making the cmake function more robust against missing arguments in comparisons. (At least I _think_ I checked that the conditionals in KERNEL.POWER9 are handled correctly by gmake even when BYTE_ORDER is undefined)

**Comment by RajalakshmiSR** [comment]
Also with the above workaround ..  noticed sgemm_otcopy is not compiled...(ONLY with cmake)
[ 28%] Building ASM object kernel/CMakeFiles/kernel.dir/CMakeFiles/dgemm_kernel.S.o
[ 28%] Building C object kernel/CMakeFiles/kernel.dir/CMakeFiles/sgemm_incopy.c.o
[ 28%] Building ASM object kernel/CMakeFiles/kernel.dir/CMakeFiles/sgemm_itcopy.S.o
[ 28%] Building C object kernel/CMakeFiles/kernel.dir/CMakeFiles/sgemm_oncopy.c.o
[ 28%] Building C object kernel/CMakeFiles/kernel.dir/CMakeFiles/sgemm_beta.c.o
[ 28%] Building ASM object kernel/CMakeFiles/kernel.dir/CMakeFiles/strmm_kernel_RN.S.o

which resulted in
[ 98%] Linking C executable openblas_utest
../lib/libopenblas.a(sgemm_nt.c.o): In function `sgemm_nt':
sgemm_nt.c:(.text+0x42c): undefined reference to `sgemm_otcopy'
../lib/libopenblas.a(sgemm_thread_nt.c.o): In function `inner_thread':
sgemm_thread_nt.c:(.text+0x658): undefined reference to `sgemm_otcopy'
../lib/libopenblas.a(sgemm_tt.c.o): In function `sgemm_tt':
sgemm_tt.c:(.text+0x42c): undefined reference to `sgemm_otcopy'
../lib/libopenblas.a(sgemm_thread_tt.c.o): In function `inner_thread':
sgemm_thread_tt.c:(.text+0x658): undefined reference to `sgemm_otcopy'
../lib/libopenblas.a(spotrf_L_single.c.o): In function `spotrf_L_single':
spotrf_L_single.c:(.text+0x3c8): undefined reference to `sgemm_otcopy'
../lib/libopenblas.a(spotrf_L_single.c.o):spotrf_L_single.c:(.text+0x4d0): more undefined references to `sgemm_otcopy' follow
collect2: error: ld returned 1 exit status
make[2]: *** [utest/openblas_utest] Error 1
make[1]: *** [utest/CMakeFiles/openblas_utest.dir/all] Error 2

Checking where sgemm_otcopy  entry is missing...

**Comment by martin-frbg** [comment]
Hm, weird as there are no further gmake-style conditionals in KERNEL.POWER9 once it gets past the endianness check. Also the ncopy/tcopy stuff is common across all architectures so a fundamental breakage in that area (e.g. as a missing entry in kernel/CMakeLists.txt) should have been picked up much earlier.
Haven't experimented with cmake on POWER as much as on ARMV8 (where conditionals in the KERNEL files are much more prevalent as well)

**Comment by RajalakshmiSR** [comment]
Figured out it is due to extra space at the end of line (SGEMMOTCOPY) in KERNEL.POWER8 and KERNEL.POWER9.. I will open a separate PR for that...It could be due to GenerateNamedObjects() in utils.cmake not allowing filename with space at the end.
