### ISSUE TITLE
deprecate Fortran files ? (Visual Studio)

### ISSUE THREAD

**Issue by skn123** [xianyi/OpenBLAS#2607]
I tried building OpenBlas for Visual studio using CMake (not using Ninja). The problem arises as we have a bunch of Fortran files (pertaining the LAPACK). Is there a way to deprecate this by using a pre-build command to convert all .f to .c files using f2c ?

I even tried building g95 using Visual studio. While the executable built correctly, it could not compile any FORTRAN file !

**Comment by martin-frbg** [comment]
You could try with either mingw/gfortran or clang/flang (as described in the wiki, there are pre-packaged binaries available for both), or just build OpenBLAS without the fortran parts (meaning without LAPACK). This should happen automatically when the build system does not detect a fortran compiler (or else run cmake with `-DNOFORTRAN=1`). If you absolutely need a non-fortran LAPACK for your projects, there is a (very old) version of the LAPACK reference implementation already converted with f2c at http://www.netlib.org/clapack/

**Comment by skn123** [comment]
Thanks @martin-frbg. I am aware of clapack. I was specifically asking if such a "pre-build" option can be made available in OpenBlas (CMake Version)  for Visual Studio? All other generators like MinGW/Cygwin etc can remain the same.

**Comment by martin-frbg** [comment]
I'm not even sure if any recent version of LAPACK could still be converted with f2c (and I am pretty sure that it was never supported in their build system).  With all the other options available (there is also the PGI compiler suite - with a free community edition - and Intel parallel studio) I am not convinced there would be much demand (though there already is #1284) 
An actual performant re-implementation in C would be a different matter - at one point a reference to the LAPACK++ project got  added to the LAPACK documentation, but it looks as if that never reached feature compatibility before getting superseded by another research project that does not appear to provide a compatible API.

**Comment by skn123** [comment]
@martin-frbg LAPACK is F90. Maybe this can be of some help ?
http://www.ncsa.illinois.edu/People/mdewing/f90toC/

**Comment by martin-frbg** [comment]
Well ...

> This is a development version. It is not ready for general use as a Fortran compiler. 
> Major To Do Items
> Last updated: 6/3/98

does not really look that attractive. I do not get what is so bad about installing a fortran compiler,
or cross-compiling from a Linux box (that could even be a WSL instance on the same computer)

**Comment by brada4** [comment]
@skn123 - 
f2c produces unreadable C files, which depends on a support library written in - make a guess in which language...
I would not bet on automatic translation of this "bunch" correctly:
http://www.icl.utk.edu/~mgates3/docs/lapack.html

**Comment by martin-frbg** [comment]
@brada4 I libf2c (or the original two libs, libf77 and libI77 I believe they were called) was written in C last time I looked at it, and it most definitely does not depend on a fortran runtime. Whether a fortran77-era tool is sufficient to convert a current lapack source to compilable form is anybody's guess but I do not see how your link would help ?

**Comment by brada4** [comment]
My link just illustrates the "bunch" one wishes to "deprecate".
Export entry/exit in f2c lib is like fortran - just pointers even in first registers. One cannot debug that.

Probably F2C can assist porting few needed functions, it errors 435 times over current lapack (minus BLAS) source, so that many changes are needed to make first suggestion viable.

**Comment by skn123** [comment]
@martin-frbg I guess you make a valid point. So, I downloaded PGI community edition. There is a 'pgfortran.exe' in the binary folder. I could compile a file  from command line and it generates a ".obj" file. Hence, we may we have a "workaround" for MSVC and only MSVC if we also are willing to download PGI:
Compile All .f files as a Pre-Build option and then link them using Visual studio / PGI ?

**Comment by martin-frbg** [comment]
I am fairly certain that the PGI compiler integrates with Visual Studio, so I do not understand why you insist on a separate pre-build step that would probably be lots of work to implement for no actual benefit.

**Comment by brada4** [comment]
I think the most practical approach is to take binary lapack library, interfeace it from MSVC, then later consider to build/f2c/port those few functions actually in use in final project. 
Whole LAPACK does not f2c, but there is a chance you use small parts of whole API that do f2c, and that f2c easily converts to maintainable C.

**Comment by skn123** [comment]
@brada4 That would also be fine. Can this be enabled?

**Comment by brada4** [comment]
Yes, build binary library with fortran, use it from C, figure out functions you use (dependency walker comes in mind), then f2c respective fortran files.

It is a tip for you on what to do - f2c small subset of fortran that you actually need, there is some chance you do not hit 400 of 2500 files in LAPACK that do not F2C at all.
