### ISSUE TITLE
LAPACKE `strict-prototypes` compiler warning for `LAPACKE_get_nancheck` prototype

### ISSUE THREAD

**Issue by Reobos** [xianyi/OpenBLAS#2619]
https://github.com/xianyi/OpenBLAS/blob/cf46c9f84e5cfa848c8062040cd1f833dd3b9862/lapack-netlib/LAPACKE/include/lapacke.h#L12578

If compiler warning `-Werror=strict-prototypes` is set, the following message appears:

    include/lapacke.h:12578:1: error: function declaration isn’t a prototype [-Werror=strict-prototypes]

A simple fix: 

`int LAPACKE_get_nancheck(void);`

**Comment by martin-frbg** [comment]
Interesting, thanks. This is actually a problem imported from https://github.com/Reference-LAPACK/lapack

**Comment by Reobos** [comment]
I can put in an issue there as well. How often do you update lapack-netlib from reference lapack? It seems some changes are made, like the check to include c++ <complex> instead of <complex.h> in lapack.h (I had to fix the 0.3.9 release lapack.h as well as this issue to get my build to work).

**Comment by martin-frbg** [comment]
Thanks for notifying the LAPACK project as well. Updates from there are routinely imported when a new LAPACK version is released, and I try to keep abreast of non-trivial code changes in their development branch as well.

**Comment by Reobos** [comment]
That’s great! Thanks Martin for making openblas easy to build a full lapacke+cblas library. Much appreciated 🙂
