### ISSUE TITLE
MIPS64 MADPS instruction illegal instruction

### ISSUE THREAD

**Issue by yaoguangchao** [xianyi/OpenBLAS#2621]
Hi All,
   Today, I tried to compile openblas on linux system with loongson3a cpu. The compilation didn't get any problem, but when i ran cblas_sgemm, I got an illegal instruction failure. After then, I recompiled openblas with DEBUG=1, and got more detailed core information like below:

> Program terminated with signal SIGILL, Illegal instruction.
#0  sgemm_kernel () at ../kernel/mips64/sgemm_kernel_8x4_ps.S:624
624             MADPS   C11, C11, A5, B5
[Current thread is 1 (LWP 3368)]
(gdb) bt
#0  sgemm_kernel () at ../kernel/mips64/sgemm_kernel_8x4_ps.S:624
#1  0x000000fff5da62f0 in sgemm_nn (args=0xffffab9700, range_m=0x0, range_n=0x0, sa=0xffedae0000, sb=0xffedaec000, dummy=0) at level3.c:358
#2  0x000000fff5c73ab0 in cblas_sgemm (order=CblasRowMajor, TransA=CblasNoTrans, TransB=CblasNoTrans, m=10, n=512, k=1286, alpha=1, a=0xffd403def0, lda=1286, b=0xffe3158010, ldb=512, beta=1, c=0xffd4052080, ldc=512) at gemm.c:433

I checked the file in kernel/mips64/sgemm_kernel_8x4_ps.S, and found that it does use MADPS instruction! But why did I get an illegal instruction failure?
Could anyone give me a correct compile options?
Thanks a lot.

**Comment by martin-frbg** [comment]
Unfortunately there has not been any significant work on the Loongson kernels in recent years, and I am not really familiar with the architecture. 
From what I could find, apparently an illegal instruction error can be raised when the madd instruction ("MADPS" is expanded to "madd.ps" in common_mips64.h) is called with arguments that are denormalized or NaN, so perhaps it depends on what input values you have in your matrix. (But it could also be a problem in the code. Which version of OpenBLAS did you build ?

**Comment by yaoguangchao** [comment]
I use the latest develop branch cloned from git. It's really possible that my input is not very good, because my colleague compiled openblas on the same machine and used it on other project but didn't get my problem. I want to ask whether the code for loongson will be well mantained in the future?



发自我的小米手机
在 Martin Kroeker <notifications@github.com>，2020年5月19日 下午10:44写道：

Unfortunately there has not been any significant work on the Loongson kernels in recent years, and I am not really familiar with the architecture.
From what I could find, apparently an illegal instruction error can be raised when the madd instruction ("MADPS" is expanded to "madd.ps" in common_mips64.h) is called with arguments that are denormalized or NaN, so perhaps it depends on what input values you have in your matrix. (But it could also be a problem in the code. Which version of OpenBLAS did you build ?

**Comment by martin-frbg** [comment]
I certainly hope so, as Loongson Ltd. has already expressed their intention to help with development in  #2368 - unfortunately the ongoing health crisis has delayed everything.

**Comment by yaoguangchao** [comment]
Thank you very much for your reply. I get in touch with the software engineer worked for loongson. 
I will reply in time if there is a progress.

**Comment by martin-frbg** [comment]
It would probably help to know the register contents for the failing instruction, or to have a minimal testcase that reproduces the fault. You could also try to revert the changes from https://github.com/xianyi/OpenBLAS/commit/cb0214787b361a6e1f8ac0d1a423d4a95b474832 (param.h and KERNEL.LOONGSON3A) to go back to the earlier 4x4 SGEMM kernel. (Or compile for TARGET=GENERIC to get a less performant OpenBLAS without all the hand-coded assembler routines)

**Comment by yaoguangchao** [comment]
I test the easier way: compile on 

> TARGET=GENERIC

and it works! Thank you martin~

I also test another way based on the advice from loongson engineer: 

> modify KERNEL.LOONGSON3A in kernel/mips64, change SGEMMKERNEL = sgemm_kernel_8x4_ps.S to SGEMMKERNEL =sgemm_kernel_loongson3a_4_4.S

code can be ran using this way,but the result is totally wrong. So I decide to use the first way temporarily.

**Comment by martin-frbg** [comment]
If you take the advice of the Loongson engineer, you also need to make the other changes related to the commit I linked to (change param.h and change also the sgemm ncopy/tcopy entries in KERNEL.LOONGSON3A)

**Comment by XiWeiGu** [comment]
@yaoguangchao. Thank you for your feedback. Could you show me more details about your problems like toolchain, compile command?
