### ISSUE TITLE
how to run the benchmark of OpenBLAS??

### ISSUE THREAD

**Issue by anlongfei** [xianyi/OpenBLAS#2624]
how to run the benchmark of OpenBLAS??

**Comment by brada4** [comment]
run `make` with some parameters to build OpenBLAS
then change directory to benchmak and run `make` with same parameters
Then run \*.goto files made there, see source for parameters.
There is scripts directory under, that you need to run after integrating OpenBLAS with the respective scripting environment.

**Comment by anlongfei** [comment]
thanks!

**Comment by brada4** [comment]
Typical speedup is 10-20 times multiplied by CPU count over NetLib reference LAPACK (and BLAS), no speedup or worse qualifies as a bug report here.
