### ISSUE TITLE
Tests failing on FreeBSD/powerpc

### ISSUE THREAD

**Issue by pkubaj** [xianyi/OpenBLAS#2628]
I'm building OpenBLAS 0.3.9 for PPCG4 on FreeBSD 12.1-RELEASE:
```
gmake[2]: Entering directory '/wrkdirs/usr/ports/math/openblas/work/OpenBLAS-0.3.9/utest'
./openblas_utest
TEST 1/27 amax:samax [OK]
TEST 2/27 ismax:negative_step_2 [OK]
TEST 3/27 ismax:positive_step_2 [OK]
TEST 4/27 ismin:negative_step_2 [OK]
TEST 5/27 ismin:positive_step_2 [OK]
TEST 6/27 drotmg:drotmg_D1_big_D2_big_flag_zero [OK]
TEST 7/27 drotmg:rotmg_D1eqD2_X1eqX2 [OK]
TEST 8/27 drotmg:rotmg_issue1452 [OK]
TEST 9/27 drotmg:rotmg [OK]
TEST 10/27 axpy:caxpy_inc_0 [OK]
TEST 11/27 axpy:saxpy_inc_0 [OK]
TEST 12/27 axpy:zaxpy_inc_0 [OK]
TEST 13/27 axpy:daxpy_inc_0 [OK]
TEST 14/27 zdotu:zdotu_offset_1 [FAIL]
  ERR: test_dotu.c:78  expected -9.000e+00, got 4.244e-314 (diff -9.000e+00, tol 1.000e-13)
TEST 15/27 zdotu:zdotu_n_1 [FAIL]
  ERR: test_dotu.c:54  expected -1.000e+00, got 4.244e-314 (diff -1.000e+00, tol 1.000e-13)
TEST 16/27 dsdot:dsdot_n_1 [OK]
TEST 17/27 swap:cswap_inc_0 [OK]
TEST 18/27 swap:sswap_inc_0 [OK]
TEST 19/27 swap:zswap_inc_0 [OK]
TEST 20/27 swap:dswap_inc_0 [OK]
TEST 21/27 rot:csrot_inc_0 [FAIL]
  ERR: test_rot.c:109  expected -2.148e-01, got 3.125e-01 (diff -5.273e-01, tol 1.000e-04)
TEST 22/27 rot:srot_inc_0 [OK]
TEST 23/27 rot:zdrot_inc_0 [FAIL]
  ERR: test_rot.c:71  expected -2.148e-01, got 3.125e-01 (diff -5.273e-01, tol 1.000e-13)
TEST 24/27 rot:drot_inc_0 [OK]
TEST 25/27 potrf:smoketest_trivial [FAIL]
  ERR: test_potrs.c:528  L c(1,1) difference: 0.0500002
TEST 26/27 potrf:bug_695 [OK]
TEST 27/27 kernel_regress:skx_avx [OK]
RESULTS: 27 tests (22 ok, 5 failed, 0 skipped) ran in 530 ms
```

GCC 9.3.0 is used to build.

**Comment by martin-frbg** [comment]
which endianness/ELF version is that ? Unfortunately I can only run power8be/fsd13 on the unicamp cloud right now, a TARGET=PPCG4 build there gave segfaults in CAXPY/ZAXPY and the CROT/ZROT utest failure you see but no zdotu badness. (Also, do the tests for TRMM etc run correctly, i.e. without the "LESS THAN HALF ACCURATE" warning that will not abort the build ?)

**Comment by pkubaj** [comment]
It's big-endian. There's no ELF version for that, this is for 32 bit powerpc. There was no ABI change there and the 32 bit powerpc still uses the original PPC ABI. There's no ELFv2 for 32 bits at all.

If you want to try building for 32 bits, you can run 32 bit chroot on 64 bit system just fine. It works just like x86 chroot on x86_64 system. With FreeBSD, you can just download https://download.freebsd.org/ftp/releases/powerpc/powerpc/12.1-RELEASE/base.txz, untar and chroot. But I don't think this is FreeBSD-specific bug, so if you prefer Linux, you could probably reproduce it there too (Void Linux and Adelie support 32 bit PPC).

**Comment by martin-frbg** [comment]
Ah right, I had the feeling that G4 was quite ancient but did not immediately think 32bit-ancient. Pretty sure the kernels are original K.Goto code (which predates the utests...).
Probably sufficient to revert the ZDOT and CROT/ZROT kernels to their plain-C counterparts from ../arm at least temporarily to "fix" the mishandling of various special cases ?

**Comment by martin-frbg** [comment]
>like x86 chroot on x86_64 system. With FreeBSD, you can just download 

unfortunately I did not manage to install git/gmake (or even pkg itself) inside the chroot on unicamp POWER8 - seems none of the download mirrors advertised carrying powerpc images at all (?) Will try with Linux and/or local qemu setup when I have time.

**Comment by pkubaj** [comment]
Right, there are no official binary packages for 32-bit PPC. I built the whole repo here https://poudriere.rtk0.net/packages/powerpc-head-pkubaj/ You can use it, but it's unofficial.

**Comment by martin-frbg** [comment]
Thanks. Unfortunately getting coredumps with these in the chroot on unicamp, either I am missing something or it is caused by their current FreeBSD image being 13-head.
