### ISSUE TITLE
Problem with make in Fedora on RPI 3B

### ISSUE THREAD

**Issue by swepettax** [xianyi/OpenBLAS#2629]
Hi!

I'm doing work where i see if the OS is affecting a clusters performance. Doing so i need to tryout diffrent OS with the same setup. I had gotten everything to work smoothfully on raspbian with a RPI 3B (not the plus model) where i used this (OpenBLAS). Now i'm trying to do the same on Fedora, but i get errors when i try to use make. I've attached the log and i hope everything is correct, otherwise i will upload it again. Hope i haven't forgotten to submit something important.

My RPI model have 4× ARM Cortex-A53, 1.2GHz CPU (it's a homogenous cluster so all RPI:s is of the same model)

[logg.txt](https://github.com/xianyi/OpenBLAS/files/4677177/logg.txt)

**Comment by martin-frbg** [comment]
The log appears to be incomplete (or you accidentally ran "make" in the interface subdirectory rather than the toplevel), but can you please retry with the current 0.3.9 version rather than the 0.2.20 from almost three years ago ?

**Comment by swepettax** [comment]
thx, that solved it. I missed that there was newer version available, sorry for any inconvenience
