### ISSUE TITLE
[WIP]Optimize GEMM for TSV110

### ISSUE THREAD

**Issue by craft-zhang** [xianyi/OpenBLAS#2630]
Hi, fellows!
I benchmarked sgemm performance on kunpeng920@2.6GHz x 24Cores (square matrix from 128 to 4096 ). There seems to be a gap between the best case (28.3 GFLOPS) and the theoretical peak of the chip (41.6 GFLOPS), still have room for optimization.

**Comment by xianyi** [comment]
@craft-zhang , Thank you for the work.

I think you need use `ldp` instruction.

**Comment by craft-zhang** [comment]
> @craft-zhang , Thank you for the work.
> 
> I think you need use `ldp` instruction.

Thx for the advice.

**Comment by martin-frbg** [comment]
going by recent experience, just matching the GEMM P and Q factors in param.h to per-core L2 cache size would probably help. but it needs someone with the hardware to test
