### ISSUE TITLE
Android Unit test failed with special condition

### ISSUE THREAD

**Issue by nguoithichkhampha** [xianyi/OpenBLAS#2631]
Openblass version: 0.3.9
Testing platform: android arm64-v8a, android x86

I built openblas library for Android follow this [guide](https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android#building-openblas-with-fortran)

here is command to build for android x86
` make TARGET=ATOM HOSTCC=gcc CC=i686-linux-android-gcc FC=i686-linux-android-gfortran -j5`

Then I run unit test from file /utest/test_ports.c
my purpose is test function **dpotrf**

when run test with data from openblas, it pass for both android arm64 and android x86.
But when I try with my data, it failed when run test on android x86
Here is my data test
double test[64] = {3.359683,  0.933888, 7.856728, 1.553534, 1.612851, 1.308500, 1.614919, 1.014111, 
                     0.933888,  5.929266, 14.483585,  0.169785, 1.907630, 2.492657, 0.745386, 1.984591,
                     7.856728,  14.483585,  821.453095, 11.475373,  8.011218, 119.410446, 13.913216,  47.113103,
                     1.553534,  0.169785, 11.475373,  5.160770, 0.773038, 1.725675, 1.490839, 0.963136,
                     1.612851,  1.907630, 8.011218, 0.773038, 3.892801, 1.388328, 1.021856, 1.143961,
                     1.308500,  2.492657, 119.410446, 1.725675, 1.388328, 20.735549,  2.165295, 7.631787,
                     1.614919,  0.745386, 13.913216,  1.490839, 1.021856, 2.165295, 1.526666, 1.106760,
                     1.014111,  1.984591, 47.113103,  0.963136, 1.143961, 7.631787, 1.106760, 4.529768};

char layout = 'U';
  blasint size = 8;
  BLASFUNC(dpotrf)(&layout, &size, test, &size, &info);
  __android_log_print(ANDROID_LOG_DEBUG, "openblas", "run test dpotrf %d",info);

with android x86, it print "run test dpotrf 3"

seems unit test from openblas does not cover all the cases or something I'm missing.
Note: android x86 from android emulator, android arm64 from physical device.

**Comment by martin-frbg** [comment]
The tests in utest are mainly small regression tests for known earlier problems, so will not be able to catch all problems. Atom x86 is still using the old GotoBLAS kernels from ten years ago, it could be that the more aggressive optimization in current compilers uncovered some previously hidden flaw. (Though imperfect emulation of actual floating point hardware behaviour could theoretically also cause this - I wonder how a non-Android TARGET=ATOM build on x86 would behave)

**Comment by nguoithichkhampha** [comment]
@martin-frbg , thanks for your answer. as my testing, test failed even with Matrix 3x3, but in openblas unit test only use Matrix 2x2. So, I suggest use matrix with bigger size will help detect the issue early.

**Comment by nguoithichkhampha** [comment]
one more thing, actually we have to run unit test from CI/CD system. only one way is run with android emulator. But our unit test relates to openblas will failed by this issue. you have any suggestion ? build android x86 with another target ?

**Comment by martin-frbg** [comment]
You could try TARGET=GENERIC or TARGET=PENRYN. Quick test with your 8x8 matrix flagged a maximum deviation of 6e-5  but no LAPACK INFO printout (on Haswell, running Linux, with TARGET=ATOM)

**Comment by martin-frbg** [comment]
Now seeing the same deviation _in the single precision 8x8 test_ with both targets I suggested, which makes it very likely that this is actually a general optimization or fma vs. non-use of fma problem (note the default limit for the 2x2 matrix is 1e-5, also TARGET=GENERIC uses plain C kernels rather than model-specific assembly, so optimization compared to the reference BLAS is mostly through loop unrolling). 
Perhaps you could show your entire modified test_potrs.c in case there is a problem with your edit that is not apparent from what you posted above ? Ignoring the complex/double complex tests for now, essentially you would only need to change (or copy & rename) the "smoketest_trivial" section, set nv and dimensions of A1s, As,Bs to 64 and n=8 and plug in your own array for A1s and A1d.

**Comment by nguoithichkhampha** [comment]
[main.cpp.zip](https://github.com/xianyi/OpenBLAS/files/4689765/main.cpp.zip)
Here is my testing file.

> you would only need to change (or copy & rename) the "smoketest_trivial" section, set nv and dimensions of A1s, As,Bs to 64 and n=8 and plug in your own array for A1s and A1d

Thanks, I will try this option.
