### ISSUE TITLE
How to set MAX_CPU_NUMBER using CMake build system

### ISSUE THREAD

**Issue by dkonst13** [xianyi/OpenBLAS#2632]
Hello, we have a quite simple question. How to set MAX_CPU_NUMBER using CMake?

Kind Reagrds, Dmitri

**Comment by martin-frbg** [comment]
use `cmake -DNUM_THREADS=` with the desired number please

**Comment by dkonst13** [comment]
Hello, thank you. I am wondering if setting NUM_THREADS to 256 I will be able to run with lesser number of threads. "MAX" in MAX_CPU_NUMBER sounds differently.

**Comment by martin-frbg** [comment]
The actual maximum at runtime is always limited to the number of (pseudo)cores detected, and there are environment variables that can be set to reduce this further if necessary.

**Comment by dkonst13** [comment]
Thank you. Clarified. I am closing it.
