### ISSUE TITLE
Possibility of an early fix for ZHEEQUB.f

### ISSUE THREAD

**Issue by ilayn** [xianyi/OpenBLAS#2633]
Due to some SciPy test hiccups, we found out that reference implemantation 3.9.0 came out with a bug in ZHEEQUB.f file. I already opened a PR in https://github.com/Reference-LAPACK/lapack/pull/408 however I was wondering if we can fix this already upstream. 

Please feel free to reject & close, I am also trying to learn how reference implementation arrives here and release machinery of OpenBLAS.

**Comment by h-vetinari** [comment]
Here's an example of carrying an upstream patch: https://github.com/xianyi/OpenBLAS/pull/2442. Your PR should be simple enough to treat in the same way IMO, so you could just create a PR. Not sure if @martin-frbg requires this to be merged upstream first, but since it's a correctness issue, I think there's a good argument to be made to include it.

**Comment by martin-frbg** [comment]
Sure - I would prefer the Reference-LAPACK folks to give such patches their blessing first, but it would not be the first time either that a bugfix gets merged here before appearing "upstream".
(OpenBLAS releases are not synchronised with Reference-LAPACK, but OpenBLAS always tries to carry the latest LAPACK release (there are a few changes in Makefiles and a few patches not applied upstream, so updating LAPACK in OpenBLAS is not completely trivial) and I try to keep OpenBLAS updated with functional improvements (i.e., non-documentation, non-codingstyle patches) in between LAPACK versions.

**Comment by ilayn** [comment]
Thanks @h-vetinari and @martin-frbg . Indeed since the fix is quite trivial (and the bug is very annoying for our test suite), I think we are safe this time. I'll open a PR shortly.

Regarding the release cycle, thanks a lot for the clarifications.
