### ISSUE TITLE
trouble making armv71-linux-gnu-gcc

### ISSUE THREAD

**Issue by woreom** [xianyi/OpenBLAS#2649]
Hi, 
I'm trying to cross compile [mxnet](https://mxnet.apache.org/get_started/?platform=devices&iot=raspberry-pi&)
and I need armv71-linux-gnu-gcc. I used these commands and got these errors
command
```
make NOFORTRAN=1 NO_SHARED=1 CC=arm-linux-gnueabihf-gcc

```
error
```
make: arm-linux-gnueabihf-gcc: Command not found
make: *** [Makefile.prebuild:66: getarch] Error 127
Makefile.system:1184: Makefile.: No such file or directory
make: *** No rule to make target 'Makefile.'.  Stop.
```
command
```
make: aarch64-linux-gnu-gcc: Command not found
make: *** [Makefile.prebuild:66: getarch] Error 127
Makefile.system:1184: Makefile.: No such file or directory
make: *** No rule to make target 'Makefile.'.  Stop.

```
error:
```
make: arm-linux-gnu-gcc: Command not found
make: *** [Makefile.prebuild:66: getarch] Error 127
Makefile.system:1184: Makefile.: No such file or directory
make: *** No rule to make target 'Makefile.'.  Stop.

```

**Comment by martin-frbg** [comment]
I guess these are the results of three separate `make` attempts with varying values for `CC` ? It would help to know which compiler you have actually installed and what system you are cross-compiling on, but in any case you need to make sure that the operating system can find it (add the directory where you installed it to your PATH variable)

**Comment by brada4** [comment]
What follows after CC should be executable command, like with full path if not in PATH
Also you need something like HOSTCC=cc if you are cross-compiling.

**Comment by Yenofer** [comment]
You can try to enter the following code:
sudo apt-get install gcc
then rewrite your code
