### ISSUE TITLE
Allow AR to be set in the environment

### ISSUE THREAD

**Issue by orlitzky** [xianyi/OpenBLAS#2654]
The `AR` variable (like `CC` or `LD`) may be set by the user in her environment. In https://github.com/xianyi/OpenBLAS/blob/develop/Makefile.system#L266 however, it is set unconditionally, making the value in the Makefile difficult to override. I would suggest using the conditional assignment operator `?=` instead of `=`. That way the Makefile only sets it if it's not already set.

I'm able to work around this another way but it may be nice for everyone else =)

It was reported to us at https://bugs.gentoo.org/725608

**Comment by martin-frbg** [comment]
Interesting, guess there have not been that many alternate implementations of ar in the past ~15 years that did not also hijack the name "ar" system-wide. Guess the same applies to AS, LD and RANLIB there (and I believe nothing actually uses NM)

**Comment by orlitzky** [comment]
Yes, the others should probably be conditionally defined as well. I know `AS` is a standard name, that `RANLIB` is used by automake, and that and `LD` is used by e.g. the linux kernel, so people may try to override those. Even if no one is going to complain about them I don't see the harm in conditionally defining them, just in case.

**Comment by orlitzky** [comment]
It looks like meson has also added support for `LD` in the environment: https://github.com/mesonbuild/meson/pull/6207

That grants a bit more validity to the expectation that setting `LD` in the environment will override the linker used.

**Comment by brada4** [comment]
Also `AR=${{C|F}C}` could work.

**Comment by orlitzky** [comment]
Thank you!
