### ISSUE TITLE
Local cblas symbols in dynamic library

### ISSUE THREAD

**Issue by ACSimon33** [xianyi/OpenBLAS#2659]
There are a few cblas interfaces that are not exported in the dynamic library:
**cblas_i?amin, cblas_i?min, cblas_i?max, cblas_?sum, cblas_?gemm3m**

I added the missing routines to the export/gensymbol script myself for my purposes, but i was wondering if there is any reason for those routines to be excluded or if I made some mistake building the library?

**Comment by martin-frbg** [comment]
nm does list them (on Linux at least), what is your platform and which version are you building ?

**Comment by ACSimon33** [comment]
I'm building the develop branch on MacOS 10.15.5 using clang and gfortran. You're right, I tried it on my Linux machine and it worked without the changes.

**Comment by martin-frbg** [comment]
But OSX (xcode linker probably) did not export them ?

**Comment by ACSimon33** [comment]
They are only local to the library making them not linkable to my programs. Here is a part of the output that **nm libopenblas.dylib | grep cblas** gives me:

....
00000000000213d0 T _cblas_dzasum
0000000000021920 T _cblas_dznrm2
0000000000021a30 t _cblas_dzsum
0000000000015b70 T _cblas_icamax
0000000000015bb0 t _cblas_icamin
0000000000016210 t _cblas_icmax
00000000000161d0 t _cblas_icmin
000000000000cc80 T _cblas_idamax
000000000000ccc0 t _cblas_idamin
000000000000daa0 t _cblas_idmax
000000000000da60 t _cblas_idmin
0000000000003790 T _cblas_isamax
00000000000037d0 t _cblas_isamin
0000000000004630 t _cblas_ismax
00000000000045f0 t _cblas_ismin
0000000000021350 T _cblas_izamax
0000000000021390 t _cblas_izamin
00000000000219f0 t _cblas_izmax
00000000000219b0 t _cblas_izmin
0000000000003810 T _cblas_sasum
0000000000004590 T _cblas_saxpby
0000000000003830 T _cblas_saxpy
0000000000015bf0 T _cblas_scasum
0000000000016140 T _cblas_scnrm2
0000000000003940 T _cblas_scopy
0000000000016250 t _cblas_scsum
00000000000039a0 T _cblas_sdot
0000000000003a00 T _cblas_sdsdot
....

So they are present in the library but not externally accessible (**t** instead of **T**).
I get the same result if I use the homebrew formula instead of the source build.

**Comment by martin-frbg** [comment]
Interesting to see that the behaviour is so different. Most users will have GNU `ld` in some form or other, otherwise this bug should have been noticed much earlier. Would you like to submit a PR ?

**Comment by ACSimon33** [comment]
I think the reason why this isn't a problem under linux is that the linux build doesn't use an exported symbols list like the OSX build. Under linux it seems that all symbols are exported. 
The exports/gensymbols script is only used to generate the link test under linux which is therefore missing the routines I mentioned above as well.

Adding those routines to the script would solve all those issues I think. I'll do that and test if the osx and linux builds work as expected. I'll submit a PR if it's working.

**Comment by martin-frbg** [comment]
Merged, thanks
