### ISSUE TITLE
gotoblas_corename() showing apparently incorrect cpu identification

### ISSUE THREAD

**Issue by danielwe** [xianyi/OpenBLAS#2660]
My machine has Xeon E7 4870 processors, which use the Nehalem-based Westmere microarchitecture. However, OpenBLAS built with `DYNAMIC_ARCH` appears to identify them as Atom cores. The output of `openblas_get_config()` is:
```
OpenBLAS 0.3.5  USE64BITINT DYNAMIC_ARCH NO_AFFINITY Atom MAX_THREADS=32
```
`export OPENBLAS_CORETYPE=Nehalem` makes no difference

I think the actual problem is that with `DYNAMIC_ARCH` but not `DYNAMIC_OLDER`, `gotoblas_ATOM` is aliased to `gotoblas_NEHALEM`, and `gotoblas_coretype()` checks for `gotoblas == &gotoblas_ATOM` before `gotoblas == &gotoblas_NEHALEM`:
https://github.com/xianyi/OpenBLAS/blob/9d5079008f964d0be08708dc3785ebcf5b7bf68b/driver/others/dynamic.c#L767-L771

Seems like the solution would be one of the following:

* Make sure that the `gotoblas_<ARCH>` identifiers that could be aliases are checked last in `gotoblas_corename()`, or
* Disable some of the checks in `gotoblas_corename()` depending on compiler flags

**Comment by martin-frbg** [comment]
Option #2 looks cleaner to me (though neither will solve the "problem" with a custom DYNAMIC_LIST - which would require a nasty cascade of ifdefs that is _probably_ not worthwile to implement)
