### ISSUE TITLE
Build with MAKEFLAGS='-j4 -l4'

### ISSUE THREAD

**Issue by slel** [xianyi/OpenBLAS#2673]
Paul Zimmermann reports:

> OpenBLAS-0.3.6 fails to build when MAKEFLAGS is defined as '-j4 -l4'

See report at [Sage Trac ticket 28768](https://trac.sagemath.org/ticket/28768), in particular [comment 7](https://trac.sagemath.org/ticket/28768#comment:7).

Paul reported this by email in Jan 2020 and was advised to open an issue.
I am opening this issue on Paul's behalf to track this.

**Comment by martin-frbg** [comment]
Does this persist with the current release ? It looks a lot like #2616 , believed fixed by #2617

**Comment by slel** [comment]
Indeed, it is no longer the case with OpenBLAS 0.3.10.
