### ISSUE TITLE
Multithreaded openblas

### ISSUE THREAD

**Issue by AnonymousYWL** [xianyi/OpenBLAS#2678]
My processor has 64 cores. Although the program uses openblas_ set_ num_ Threads() sets the number of threads = 64, but uses openblas_ get_ num_ Threads() gets only 16 threads.

**Comment by martin-frbg** [comment]
Did you build OpenBLAS on the same hardware (or if you built on a smaller machine, did you build with NUM_THREADS=64 or more) ?

**Comment by AnonymousYWL** [comment]
I compile on a login node with 16 cores and compute on a compute node with 64 cores。

**Comment by martin-frbg** [comment]
Ah, there is the snag - OpenBLAS will get the maximum possible number of threads from the number of cores in the hardware it is built on, unless you specify this at compilation time. (`make NUM_THREADS=64` or `cmake -DNUM_THREADS=64`)

**Comment by Diazonium** [comment]
I would also recommend opening Makefile.rule and reading the comments in it.

**Comment by martin-frbg** [comment]
Added to the FAQ as https://github.com/xianyi/OpenBLAS/wiki/Faq#numthreads
