### ISSUE TITLE
DLL License

### ISSUE THREAD

**Issue by Rashaine-Johnson** [xianyi/OpenBLAS#2685]
I have a question about OpenBLAS' BSD-3-Clause License. Given that OpenBLAS requires libquadmath-0.dll which seems to have a GPL license, is OpenBLAS therefore required to be GPL? I'm working on a commercial product that uses OpenBLAS but because libquadmath-0.dll is a dependency that seems to limit our licensing options.

Somewhat related to the dependency discussion in #1112 but from a licensing perspective.

**Comment by isuruf** [comment]
libquadmath is LGPL.

**Comment by Rashaine-Johnson** [comment]
@isuruf Can you please provide a reference for that? Everything I've seen says GPL

**Comment by martin-frbg** [comment]
libquadmath is LGPL, see e.g. here : https://fossies.org/linux/gcc/libquadmath/COPYING.LIB
Also the dependency is only incurred if OpenBLAS is compiled with gcc (or mingw and the like), you may be able to recompile it with a commercial compiler that brings its own libraries (and legalese).

**Comment by Rashaine-Johnson** [comment]
Oh, that makes sense. Thanks for the information and the reference. Much appreciated!
