### ISSUE TITLE
Is those extended blas APIs available for both CBLAS and fortran?

### ISSUE THREAD

**Issue by Guobing-Chen** [xianyi/OpenBLAS#2689]
There are several BLAS extensions as listed in cblas.h. Are these extension cblas APIs only available as cblas_XXX or also available as Fortran API?
I don't find any Fortran related code supporting these APIs so suppose not support Fortran API, but want to have your confirmation in case I am wrong.

e.x.: 
void cblas_saxpby(OPENBLAS_CONST blasint n, OPENBLAS_CONST float alpha, OPENBLAS_CONST float *x, OPENBLAS_CONST blasint incx,OPENBLAS_CONST float beta, float *y, OPENBLAS_CONST blasint incy);

void cblas_daxpby(OPENBLAS_CONST blasint n, OPENBLAS_CONST double alpha, OPENBLAS_CONST double *x, OPENBLAS_CONST blasint incx,OPENBLAS_CONST double beta, double *y, OPENBLAS_CONST blasint incy);

void cblas_caxpby(OPENBLAS_CONST blasint n, OPENBLAS_CONST void *alpha, OPENBLAS_CONST void *x, OPENBLAS_CONST blasint incx,OPENBLAS_CONST void *beta, void *y, OPENBLAS_CONST blasint incy);

void cblas_zaxpby(OPENBLAS_CONST blasint n, OPENBLAS_CONST void *alpha, OPENBLAS_CONST void *x, OPENBLAS_CONST blasint incx,OPENBLAS_CONST void *beta, void *y, OPENBLAS_CONST blasint incy);

**Comment by martin-frbg** [comment]
All the BLAS functions in OpenBLAS are implemented in C (the BLAS subtree of lapack-netlib is unused) so you will not find a Fortran source for saxpby etc.These fiunctions should still be callable from Fortran however.

**Comment by Guobing-Chen** [comment]
Thanks for the information. How this mechanism works? Let's say I added a new extension API like cblas_xdot in cblas.h, together with all the implementation under drivers/kernels. What else I need to do to make this new API can be invoked by Fortran?

**Comment by martin-frbg** [comment]
See the files in `interface` please
