### ISSUE TITLE
Multithreading performance

### ISSUE THREAD

**Issue by AnonymousYWL** [xianyi/OpenBLAS#2690]
My processor has 64 threads. If I want each thread to run a GEMM, what should I do?

**Comment by brada4** [comment]
You need to supply large enough input matrix to utilize 16 cores, then you paralellize using other framework like python parallel.
Or take your CPU as 4 PCs glued together.
http://developer.amd.com/wp-content/resources/56420.pdf Ch 6 on p 15
What OS you are running?
