### ISSUE TITLE
compiling and linking openblas with MSVC

### ISSUE THREAD

**Issue by thomassligon** [xianyi/OpenBLAS#2691]
I want to use `openblas` in AMICI ([https://github.com/ICB-DCM/AMICI](https://github.com/ICB-DCM/AMICI)) on Windows using Visual Studio. When I downloaded the binaries, I got an openblas.dll that depended on mingw dlls, including a Fortran library. In order to be sure I have a consistent final version, I decided to compile and link `openblas` using MSVC, and I need a command-line version of that so it can run as part of `Travis CI`. I have tried the following commands
```
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
cmake -S "C:\BLAS\OpenBLAS-v0.3.10\OpenBLAS-0.3.10" -B "C:\BLAS\OpenBLAS-v0.3.10\OpenBLAS-0.3.10\out"
cmake --build "C:\BLAS\OpenBLAS-v0.3.10\OpenBLAS-0.3.10"
copy "C:\BLAS\OpenBLAS-v0.3.10\OpenBLAS-0.3.10\lib\openblas.lib" "C:\BLAS\lib"
link /DLL /NOLOGO /INCREMENTAL:NO /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO "/LIBPATH:C:\BLAS\lib" openblas.lib "/OUT:C:\BLAS\bin\openblas.dll" /INCLUDE:DllMain
```
The results look pretty good, except that I think that my linking of the dll is probably wrong.
Should the dll also be created by the cmake? (I didn't find that in `CMakeLists.txt`.)
Is there something missing in my link command, such as an object file that needs to be linked in?
PS: This is the first time I have used cmake, so I might be doing some things wrong.

**Comment by brada4** [comment]
The target needs only CBLAS api. It would help if you post any output you got from last 3 steps, compiling silently for first time  is usually overconfident.

**Comment by martin-frbg** [comment]
You could try adding `-DBUILD_SHARED_LIBS=ON` to that first `cmake` call
(see https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-in-Microsoft-Visual-Studio in the Wiki section for other options - unfortunately MS Windows build expertise is a bit sparse here)

**Comment by thomassligon** [comment]
Thanks! I added the -D and reran everything except for the copy and link statements. Interesting, now I didn't see any compilation, maybe the objects are being treated as up-to-date. Here is the output:
```
C:\BLAS\bin>"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.6.2
** Copyright (c) 2020 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\BLAS\bin>
C:\BLAS\bin>cmake -S "C:\BLAS\OpenBLAS-v0.3.10\OpenBLAS-0.3.10" -B "C:\BLAS\OpenBLAS-v0.3.10\OpenBLAS-0.3.10\out" -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release
CMake Warning at CMakeLists.txt:66 (message):
  CMake support is experimental.  It does not yet support all build options
  and may not produce the same Makefiles that OpenBLAS ships with.


-- GEMM multithread threshold set to 4.
-- Multi-threading enabled with 4 threads.
CMake Deprecation Warning at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.17/Modules/CMakeForceCompiler.cmake:103 (message):
  The CMAKE_FORCE_Fortran_COMPILER macro is deprecated.  Instead just set
  CMAKE_Fortran_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  cmake/f_check.cmake:27 (CMAKE_FORCE_Fortran_COMPILER)
  cmake/prebuild.cmake:89 (include)
  cmake/system.cmake:157 (include)
  CMakeLists.txt:69 (include)


CMake Warning (dev) at cmake/prebuild.cmake:472 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  cmake/system.cmake:157 (include)
  CMakeLists.txt:69 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

MSVC
-- Running getarch
-- GETARCH results:
CORE=generic
LIBCORE=generic
NUM_CORES=4
GENERIC=1
L1_DATA_SIZE=32768
L1_DATA_LINESIZE=128
L2_SIZE=512488
L2_LINESIZE=128
DTB_DEFAULT_ENTRIES=128
DTB_SIZE=4096
L2_ASSOCIATIVE=8
MAKE += -j 4

-- Compiling a 64-bit binary.
-- Building Single Precision
-- Building Double Precision
-- Building Complex Precision
-- Building Double Complex Precision
-- Reading vars from C:/BLAS/OpenBLAS-v0.3.10/OpenBLAS-0.3.10/kernel/x86_64/KERNEL...
-- Reading vars from C:/BLAS/OpenBLAS-v0.3.10/OpenBLAS-0.3.10/kernel/x86_64/KERNEL.generic...
CMake Warning (dev) at utest/CMakeLists.txt:4 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating openblas_config.h in include/openblas
-- Generating f77blas.h in include/openblas
-- Generating cblas.h in include/openblas
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Configuring done
-- Generating done
-- Build files have been written to: C:/BLAS/OpenBLAS-v0.3.10/OpenBLAS-0.3.10/out

C:\BLAS\bin>cmake --build "C:\BLAS\OpenBLAS-v0.3.10\OpenBLAS-0.3.10"
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  driver_level2.vcxproj -> C:\BLAS\OpenBLAS-v0.3.10\OpenBLAS-0.3.10\driver\level2\driver_level2.dir\Debug\driver_level2.lib
  driver_level3.vcxproj -> C:\BLAS\OpenBLAS-v0.3.10\OpenBLAS-0.3.10\driver\level3\driver_level3.dir\Debug\driver_level3.lib
  driver_others.vcxproj -> C:\BLAS\OpenBLAS-v0.3.10\OpenBLAS-0.3.10\driver\others\driver_others.dir\Debug\driver_others.lib
  interface.vcxproj -> C:\BLAS\OpenBLAS-v0.3.10\OpenBLAS-0.3.10\interface\interface.dir\Debug\interface.lib
  kernel.vcxproj -> C:\BLAS\OpenBLAS-v0.3.10\OpenBLAS-0.3.10\kernel\kernel.dir\Debug\kernel.lib
  openblas.vcxproj -> C:\BLAS\OpenBLAS-v0.3.10\OpenBLAS-0.3.10\lib\DEBUG\openblas.lib
  openblas_utest.vcxproj -> C:\BLAS\OpenBLAS-v0.3.10\OpenBLAS-0.3.10\utest\openblas_utest.exe

C:\BLAS\bin>
```

**Comment by martin-frbg** [comment]
Hmm. Treating the object files as up-to-date should be correct, but I see no indication that either of the two -D was actually processed (given that the build still talks of puttng things in "Debug", and there is no dll to be seen). Possibly you need a `-G` option with an appropriate generator (like -G "Visual Studio 16 2019") to get the options passed to the right tools but I am out of my depth here.

**Comment by isuruf** [comment]
To use the Release build with Visual Studio, you need to do `cmake --build "C:\BLAS\OpenBLAS-v0.3.10\OpenBLAS-0.3.10" --config Release` as the Visual Studio generator is a multi config build.

**Comment by thomassligon** [comment]
This looks like a very interesting exercise, but I am happy that I don't have to do it on a fixed time schedule. I'll write a summary first, then a few more details, then paste in a number of log files.
The first big thing: I found a Microsoft web site that says I can get the full `cmake` command used by the integrated GUI and all of its output. However, when I try running that on the command line, I get `file not found` errors for the files `LIBCMT.lib` and `cmTC_78fd6.lib` (if I understood that last one correctly). With that, the Microsoft developer site might be the better place to find a solution.
The web site 
[https://docs.microsoft.com/de-de/cpp/build/cmake-projects-in-visual-studio?view=vs-2019](https://docs.microsoft.com/de-de/cpp/build/cmake-projects-in-visual-studio?view=vs-2019)
IDE Integration
“Visual Studio runs cmake.exe and generates the `CMake` cache file (`CMakeCache.txt`) for the default (x64 Debug) configuration. **The CMake command line is displayed in the Output Window, along with additional output from CMake**.”
In order to get that, I made a fresh copy of the openblas sources, started Visual Studio, and opened the folder containing CMakeLists.txt, then copied the output to this file:
[OpenFolderOut.txt](https://github.com/xianyi/OpenBLAS/files/4853155/OpenFolderOut.txt)
The next step was to make sure that all programs are in my PATH and create and run my own call to cmake, resulting in the following:
[cmakeStdOut-1.txt](https://github.com/xianyi/OpenBLAS/files/4853157/cmakeStdOut-1.txt)
[cmakeOut-1.txt](https://github.com/xianyi/OpenBLAS/files/4853158/cmakeOut-1.txt)
[CMakeError-1.log](https://github.com/xianyi/OpenBLAS/files/4853161/CMakeError-1.log)

**Comment by martin-frbg** [comment]
Googling the libcmt error leads to suggestions that it could be related to having "Spectre Mitigation" turned on by default in VS but the spectre-aware versions of the libraries not available.https://stackoverflow.com/questions/9356135/link-fatal-error-lnk-1104-cannot-open-file-libcmt-lib/56119187
The "cmTC78fd6" is most likely just the temporary name of the throw-away executable used for testing if the compiler works,
I think that test failed for the same reason - not finding the libcmt.lib (unless rc.exe itself was not in your path at the time - higly unlikely if you executed vcvarsall)

**Comment by brada4** [comment]
> happy that I don't have to do it on a fixed time schedule

Probably worth finding a compiler that produces executables before taking up such a gig.

**Comment by thomassligon** [comment]
Ouch! I forgot the `vcvars`. With it, everything compiles without error and links `openblas.lib` and `openblas_utest.exe`. There are only warnings, such as
`C:/BLAS/OpenBLAS-v0.3.10/OpenBLAS-0.3.10/kernel/x86_64/../generic/trsm_kernel_LN.c(140): warning C4244: '=': conversion from 'BLASLONG' to 'int', possible loss of data`
Now, my commands reduce to:
```
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
cmake -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH="C:\BLAS\OpenBLAS-v0.3.10\OpenBLAS-0.3.10\out\install\x64-Release" -DCMAKE_C_COMPILER:FILEPATH=cl -DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PROGRAM=ninja "C:\BLAS\OpenBLAS-v0.3.10\OpenBLAS-0.3.10" >cmakeOut.txt
cmake --build "C:\BLAS\OpenBLAS-v0.3.10\OpenBLAS-0.3.10"
copy "C:\BLAS\OpenBLAS-v0.3.10\OpenBLAS-0.3.10\lib\release\openblas.lib" "C:\BLAS\lib"
link /DLL /NOLOGO /INCREMENTAL:NO /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO "/LIBPATH:C:\BLAS\lib" openblas.lib "/OUT:C:\BLAS\bin\openblas.dll" /INCLUDE:DllMain
```
My next step will be to recreate AMICI with this version of openblas.dll and see if I forgot anything there.
[cmakeBuildOut-3.txt](https://github.com/xianyi/OpenBLAS/files/4854159/cmakeBuildOut-3.txt)

**Comment by brada4** [comment]
If it is just a (c)blas dll (as opposed to static .lib) you can build with generic netlib BLAS DLL, then just rename (cross-built) (on Linux) openblas dll in its place. MSVC build omits all CPU-specific kernels, and is noticeably slow, though still by number of cores faster than reference implementation.

**Comment by martin-frbg** [comment]
Could always recompile with clang, mingw, pgi or intel later, I guess. (The issue with VS is that it does not support the specific dialect of assembly used, nor does it support inline assembly on x86_64)

**Comment by thomassligon** [comment]
Now I have added -DBUILD_SHARED_LIBS=ON resulting in the following calls:
```
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
cmake -G "Ninja" -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX:PATH="C:\BLAS\OpenBLAS-v0.3.10\OpenBLAS-0.3.10\out\install\x64-Release" -DCMAKE_C_COMPILER:FILEPATH=cl -DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PROGRAM=ninja "C:\BLAS\OpenBLAS-v0.3.10\OpenBLAS-0.3.10" >cmakeOut.txt
cmake --build "C:\BLAS\OpenBLAS-v0.3.10\OpenBLAS-0.3.10" >cmakeBuildOut.txt
```
That means that the `dll` is created based on the `cmake` files included in the `openblas` sources. This dll has the following dependencies, all of which are found in the Windows PATH variable:
```
C:\BLAS\bin>dumpbin /DEPENDENTS openblas.dll
Microsoft (R) COFF/PE Dumper Version 14.26.28806.0
Copyright (C) Microsoft Corporation.  All rights reserved.
Dump of file openblas.dll
File Type: DLL
  Image has the following dependencies:
    KERNEL32.dll
    VCRUNTIME140.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-convert-l1-1-0.dll
```
In contrast, the dll supplied as part of the v0.3.6-x64 binaries has the following dep0endencies:
```
C:\BLAS\OpenBLAS-0.3.6-x64\bin>dumpbin /DEPENDENTS libopenblas.dll.save
Microsoft (R) COFF/PE Dumper Version 14.26.28806.0
Copyright (C) Microsoft Corporation.  All rights reserved.
Dump of file libopenblas.dll.save
File Type: DLL
  Image has the following dependencies:
    KERNEL32.dll
    msvcrt.dll
    USER32.dll
    libgcc_s_seh-1.dll
    libgfortran-3.dll
```
My previous understanding was that dlls are loaded on demand, when called, but it looks like the `Python import` statement loads all of them immediately and fails if one is not available.

**Comment by martin-frbg** [comment]
The current Windows binaries are created by cross-compiling with MXE (mingw) on Linux, which is where the added dependencies come from. (On the plus side, your VS build is probably BLAS only and no LAPACK) The 0.3.10 packages currently on github (but not yet sf.net) should depend only on KERNEL32, USER32 and msvcrt though.

**Comment by brada4** [comment]
> dlls are loaded on demand

It depends, try "dependency walker" aka depends.exe to see all import flags, those fortran dependencies are mandatory at load time.

**Comment by thomassligon** [comment]
Sorry I didn't close this myself. The changes are working for us.
