### ISSUE TITLE
Batch GEMM

### ISSUE THREAD

**Issue by AnonymousYWL** [xianyi/OpenBLAS#2695]
How does openblas run batch GEMM?

**Comment by martin-frbg** [comment]
https://github.com/xianyi/OpenBLAS/wiki/Developer-manual contains a pointer to the algorithm as published by Kazushige Goto years ago. What is your interest ? (Please do not open new issue tickets for any random question, this project has few resources)

**Comment by HPC4AI** [comment]
> https://github.com/xianyi/OpenBLAS/wiki/Developer-manual contains a pointer to the algorithm as published by Kazushige Goto years ago. What is your interest ? (Please do not open new issue tickets for any random question, this project has few resources)

Hi, does the current OpenBLAS library support matrix batch operations `cblas_xgemm_batch`?

**Comment by martin-frbg** [comment]
Unfortunately not yet - I remember xianyi started an implementation in a separate branch a few years ago, but I _think_ he ran out of free time to complete it. Not sure how easy it would be to resurrect now.
