### ISSUE TITLE
dot.S and zdot.S at kernel/arm64 who do better ?

### ISSUE THREAD

**Issue by miaozhuojun** [xianyi/OpenBLAS#2698]
I'm looking for the best implementation of ddot for vector with 20 elements in AARCH64. Anybady test these two implementations ?

**Comment by martin-frbg** [comment]
Not sure I understand the question - dot.S is used for single and double precision real, zdot.S is the implementation for complex values.

**Comment by brada4** [comment]
Probably best implementation is to write inline sum of 20 array values as.
More universal approach is to make cache-line sized block sums in a loop where same offset counter serves as loop counter.

Then you examine assembly - it may need to hint temporary variables as intrinsic FPU registers, or some prefetch of next block interleaved with previous summation.

The biggest concern is memory fetch at full speed, modern CPUs do dozens of FPU ops or more during RAM access.
