### ISSUE TITLE
Is this statement redundant?

### ISSUE THREAD

**Issue by miaozhuojun** [xianyi/OpenBLAS#2700]
https://github.com/xianyi/OpenBLAS/blob/c3aa036e99de5a5e3fb57698c634c194764b8a58/kernel/arm64/dot.S#L157

**Comment by martin-frbg** [comment]
Cannot look in detail now, but suspect this may be needed for transporting (part of) the return value in the double precision case (same source code used for single and double precision dot with appropriate `ifdef`s as you will have noticed)

**Comment by brada4** [comment]
Probably it is a FPU warmup code without due comment. As for having no effect logicaly your observation is correct. 
ARM has partial logic block shutdowns to save power since ARMv5/v6

**Comment by miaozhuojun** [comment]
> 
> 
> Probably it is a FPU warmup code without due comment. As for having no effect logicaly your observation is correct.
> ARM has partial logic block shutdowns to save power since ARMv5/v6

OK, I know, Thank you
