### ISSUE TITLE
 CC1: error: unrecognized command line option "- mavx2"

### ISSUE THREAD

**Issue by chenwuchen** [xianyi/OpenBLAS#2702]
centos 6.3 install  fail OpenBLAS-0.3.7
make error

CC1: error: unrecognized command line option "- mavx2"

**Comment by martin-frbg** [comment]
With the extra space between the `-` and the `mavx2` ? I do not see this in any of the 0.3.7 makefiles, so perhaps this is in your CFLAGS or some similar environment variable ? (In any case, do you need 0.3.7 specifically, or can you update to 0.3.10 ?)

**Comment by chenwuchen** [comment]
There are no spaces
Openblas-0.3.10 has the same error

Here is the compiled  error information：

```
cc -O2 -DMAX_STACK_ALLOC=2048 -DUSE_LOCKING -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DNO_AVX512 -DNO_WARMUP -DMAX_CPU_NUMBER=24 -DMAX_PARALLEL_NUMBER=1 -DVERSION=\"0.3.10\" -mavx2 -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME=ssum -DASMFNAME=ssum_ -DNAME=ssum_ -DCNAME=ssum -DCHAR_NAME=\"ssum_\" -DCHAR_CNAME=\"ssum\" -DNO_AFFINITY -I.. -I. -UDOUBLE  -UCOMPLEX -c sum.c -o ssum.o
CC1: error: unrecognized command line option "-mavx2"
```

**Comment by chenwuchen** [comment]
> With the extra space between the `-` and the `mavx2` ? I do not see this in any of the 0.3.7 makefiles, so perhaps this is in your CFLAGS or some similar environment variable ? (In any case, do you need 0.3.7 specifically, or can you update to 0.3.10 ?)

There are no spaces
Openblas-0.3.10 has the same error

Here is the compiled error information：

```
cc -O2 -DMAX_STACK_ALLOC=2048 -DUSE_LOCKING -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DNO_AVX512 -DNO_WARMUP -DMAX_CPU_NUMBER=24 -DMAX_PARALLEL_NUMBER=1 -DVERSION=\"0.3.10\" -mavx2 -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME=ssum -DASMFNAME=ssum_ -DNAME=ssum_ -DCNAME=ssum -DCHAR_NAME=\"ssum_\" -DCHAR_CNAME=\"ssum\" -DNO_AFFINITY -I.. -I. -UDOUBLE  -UCOMPLEX -c sum.c -o ssum.o
CC1: error: unrecognized command line option "-mavx2"
```

**Comment by wjc404** [comment]
https://www.tuicool.com/articles/JBZz6b7
This might help.

**Comment by martin-frbg** [comment]
I guess we could add another version test in Makefile.x86_64 - the other spots in kernel/Makefile and cmake/system.cmake already check for gcc >= 4.7 before adding the option.
