### ISSUE TITLE
Single Threaded USE_LOCKING Question

### ISSUE THREAD

**Issue by johnduffymsc** [xianyi/OpenBLAS#2711]
Hi

In Makfile.rule there is a comment about using USE_LOCKING=1 in single threaded OpenBLAS if your program is multi-threaded. I sort of understand this, but would it be possible to clarify this is the following situation:

I'm using OpenMPI to run Linpack on a 4-core CPU. Each core will be running it's own copy of the Linpack 'xhpl' executable, and there is no core hyper-threading. My thinking is that since each core has it's own executable (linked to shared library single-threaded OpenBLAS), then it would be safe to use USE_LOCKING=0, since this is no different from multiple different programs using OpenBLAS at the same time. But I'm not entirely sure my thinking is correct.

Any help/suggestions would be much appreciated.

Best wishes

**Comment by brada4** [comment]
Yes, in your situation locking is not necessary because two blas threads dont meet in same process.

hyperthreading is lower level concept in CPU design, completely abstracted by operating system kernel. I assume you mean threading.

**Comment by martin-frbg** [comment]
Yes as long it is separate processes this option is not needed, only two (or more) threads of the same program calling into the serial libopenblas would run a risk of encountering a race condition.

**Comment by johnduffymsc** [comment]
Thank you. I understand this now. And yes, I meant threading.
