### ISSUE TITLE
make fail in installing openblas

### ISSUE THREAD

**Issue by aliabavi** [xianyi/OpenBLAS#2714]
Hi,

I am trying to install openblas-0.3.10 on my centos linux machine, but keep getting the following errors while trying to run `make`:

```
cc: error: unrecognized argument in option ‘-mcpu=power9’
cc: error: unrecognized argument in option ‘-mtune=power9’

```

Any suggestion on how I could fix this?

Thank you,

**Comment by brada4** [comment]
Could you show /proc/cpuinfo ? Which Centos version?
Are you running just `make` ?
In principle fedora epel repository contains fairly recent openblas for CentOS.

**Comment by martin-frbg** [comment]
What does `gcc -v` tell about the version ? Perhaps you have several installed with an old one the default, and running with 
`make CC=gcc-7` (or `gcc-9` or whatever) would get you one that understands the power9 options.

**Comment by aliabavi** [comment]
Here is the output of `$ cat /etc/os-release` :

```
NAME="CentOS Linux"
VERSION="7 (AltArch)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (AltArch)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7:server"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

Would you please provide me the link for the recent openblas?

Thank you.

> Could you show /proc/cpuinfo ? Which Centos version?
> Are you running just `make` ?
> In principle fedora epel repository contains fairly recent openblas for CentOS.

**Comment by aliabavi** [comment]
Here is the output of `$gcc -v` :

```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/ppc64le-redhat-linux/4.8.5/lto-wrapper
Target: ppc64le-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-ppc64le-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-ppc64le-redhat-linux/cloog-install --enable-gnu-indirect-function --enable-secureplt --with-long-double-128 --enable-targets=powerpcle-linux --disable-multilib --with-cpu-64=power8 --with-tune-64=power8 --build=ppc64le-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) 
```

> What does `gcc -v` tell about the version ? Perhaps you have several installed with an old one the default, and running with
> `make CC=gcc-7` (or `gcc-9` or whatever) would get you one that understands the power9 options.

**Comment by martin-frbg** [comment]
`make TARGET=POWER8` would probably work with that old gcc

**Comment by brada4** [comment]
You need later gcc known as devtoolset from softwarecollections.org
Rough guidance (for older versions regarding haswell, but with latest tools suits CentOS7 and POWER9 as well):
https://github.com/xianyi/OpenBLAS/wiki/faq#binutils
Short check 
`scl enable devtoolset-8 -- $SHELL`
`which as`
`which gcc`
`which gfortran`

**Comment by martin-frbg** [comment]
`sudo yum install devtoolset-8-gcc-8.2.1 devtoolset-8-gcc-fortran-8.2.1` followed by `source /opt/rh/devtoolset-8/enable` before the compilation was what I used when I last tested building on centos7

**Comment by brada4** [comment]
It is at versions 8.3.1-3.2 or 9.3.1-2 if not forcing old version...

**Comment by abavisani** [comment]
I used your suggestion, now I get this error:

```
ake[1]: <command-line>:0:0: note: this is the location of the previous definition
*** Waiting for unfinished jobs....
<command-line>:0:0: warning: "CNAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
make[1]: *** [isamin_k.o] Error 1
<command-line>:0:0: warning: "CHAR_NAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
```

> `make TARGET=POWER8` would probably work with that old gcc

**Comment by abavisani** [comment]
Problem is I don't have root privilege and `sudo` ability on this system. Is there any work around that I can install OpebBLAS on it? ATLAS will be fine as well.

> `sudo yum install devtoolset-8-gcc-8.2.1 devtoolset-8-gcc-fortran-8.2.1` followed by `source /opt/rh/devtoolset-8/enable` before the compilation was what I used when I last tested building on centos7

**Comment by isuruf** [comment]
Here's a package manager you can install without `sudo`. https://github.com/conda-forge/miniforge#miniforge3
You can install gcc 8.3 by doing `conda install compilers` and you can also install a pre-built openblas 0.3.10 by doing `conda install openblas`

**Comment by martin-frbg** [comment]
Could you add a few more lines before what you posted - that snippet only shows that something went wrong when trying to compile isamin_k.o, but lacks the actual error message from the compiler ?  (The "CNAME redefined" messages should be harmless - I thought I had managed to suppress them, but probably only on x86 platforms)

**Comment by brada4** [comment]
`my centos linux machine`
vs
`don't have root`

Just acquire root in single-user mode?

**Comment by martin-frbg** [comment]
With #2714 the makefile will now use `-mcpu=power8` when your gcc is too old to support power9

**Comment by abavisani** [comment]
> With #2714 the makefile will now use `-mcpu=power8` when your gcc is too old to support power9

Hi,

Thanks for the response. Would you please let me know what is correct syntax to use this `-mcpu=power8` while installing openblas? The line I am using for installation is as following:

`make PREFIX=$(pwd)/OpenBLAS/install USE_LOCKING=1 USE_THREAD=0 -C OpenBLAS all install`

The actual script I am using for openblas installation is here:
https://github.com/kaldi-asr/kaldi/blob/master/tools/extras/install_openblas.sh

**Comment by martin-frbg** [comment]
The -mpu  option is set automatically inside the OpenBLAS makefiles, there should be no need to change anything in your install script. Is installation still failing for you despite the change ?

**Comment by abavisani** [comment]
> The -mpu option is set automatically inside the OpenBLAS makefiles, there should be no need to change anything in your install script. Is installation still failing for you despite the change ?

Where should I change? The `Makefile.conf` inside OpenBLAS directory?

And yes, I still cannot install Openblas on that system.

**Comment by martin-frbg** [comment]
If you are still trying with 0.3.10, the change needs to be made in  Makefile.power - should be sufficient to change any -mcpu=power9 that you see in that file to -mpcu=power8

**Comment by abavisani** [comment]
> If you are still trying with 0.3.10, the change needs to be made in Makefile.power - should be sufficient to change any -mcpu=power9 that you see in that file to -mpcu=power8

Thank you for the note. I replaced all instances of `-mpcu=power9 `and `-mtune=power9` with `-mpcu=power8` and `-mtune=power8`. Now I have the following error when tried to install OpenBlas:


```
Preprocessed source stored into /tmp/cc4VrMFS.out file, please attach this to your bugreport.
<command-line>:0:0: warning: "ASMNAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "ASMFNAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "NAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "CNAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "CHAR_NAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "CHAR_CNAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
make[1]: *** [isamax_k.o] Error 1
make[1]: *** Waiting for unfinished jobs....
Preprocessed source stored into /tmp/ccWWtaHS.out file, please attach this to your bugreport.
make[1]: *** [isamin_k.o] Error 1
<command-line>:0:0: warning: "ASMNAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "ASMFNAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "NAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "CNAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "CHAR_NAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "CHAR_CNAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
Preprocessed source stored into /tmp/ccSvQgQh.out file, please attach this to your bugreport.
make[1]: *** [icamax_k.o] Error 1
Preprocessed source stored into /tmp/ccRGaYak.out file, please attach this to your bugreport.
make[1]: *** [icamin_k.o] Error 1
make[1]: Leaving directory `/home/aliabavi/discophone/kaldi/tools/OpenBLAS/kernel'
make: *** [libs] Error 1
make: Leaving directory `/home/aliabavi/discophone/kaldi/tools/OpenBLAS'
```

**Comment by martin-frbg** [comment]
Strange, that problem looks like what I fixed with #2601, but 0.3.10 should already contain that fix.

**Comment by abavisani** [comment]
> Strange, that problem looks like what I fixed with #2601, but 0.3.10 should already contain that fix.

Thanks for the reply. So what is the solution?

**Comment by abavisani** [comment]
run the installation script again, and have the following error now:

```
<command-line>:0:0: warning: "ASMNAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "ASMFNAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "NAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "CNAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "CHAR_NAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "CHAR_CNAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "ASMNAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "ASMFNAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "NAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "CNAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "CHAR_NAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "CHAR_CNAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "ASMNAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "ASMFNAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "NAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "CNAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "CHAR_NAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "CHAR_CNAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "ASMNAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "ASMFNAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "NAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "CNAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "CHAR_NAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "CHAR_CNAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
../kernel/power/isamax.c: In function ‘siamax_kernel_64’:
../kernel/power/isamax.c:288:1: internal compiler error: in build_int_cst_wide, at tree.c:1210
 }
 ^
../kernel/power/isamin.c: In function ‘siamin_kernel_64’:
../kernel/power/isamin.c:288:1: internal compiler error: in build_int_cst_wide, at tree.c:1210
 }
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
../kernel/power/icamax.c: In function ‘ciamax_kernel_32’:
../kernel/power/icamax.c:326:1: internal compiler error: in build_int_cst_wide, at tree.c:1210
 }
 ^
../kernel/power/icamin.c: In function ‘ciamin_kernel_32’:
../kernel/power/icamin.c:264:1: internal compiler error: in build_int_cst_wide, at tree.c:1210
 }
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
Preprocessed source stored into /tmp/ccQccX8S.out file, please attach this to your bugreport.
Preprocessed source stored into /tmp/ccHwaOaT.out file, please attach this to your bugreport.
make[1]: *** [isamin_k.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [isamax_k.o] Error 1
Preprocessed source stored into /tmp/ccWhcPPT.out file, please attach this to your bugreport.
make[1]: *** [icamax_k.o] Error 1
Preprocessed source stored into /tmp/cc7m4CNT.out file, please attach this to your bugreport.
make[1]: *** [icamin_k.o] Error 1
make[1]: Leaving directory `/home/aliabavi/discophone/kaldi/tools/OpenBLAS/kernel'
make: *** [libs] Error 1
make: Leaving directory `/home/aliabavi/discophone/kaldi/tools/OpenBLAS'
```

**Comment by martin-frbg** [comment]
I had been wondering why the warnings alone should be fatal. But again this problem is confusing - is this really 0.3.10 that you are trying to build ? These internal compiler errors came up almost a year ago and 0.3.10 should already be using a precompiled assembler (.S) file instead of isamax.c (and the others) when the compiler is found to be older than gcc9.

**Comment by abavisani** [comment]
Is there a version of Openblas or similar package that supports ppc64le machine?

**Comment by martin-frbg** [comment]
You could get a snapshot of the current `develop` branch and compile that - use https://github.com/xianyi/OpenBLAS/archive/develop.zip if you cannot do a `git clone https://github.com/xianyi/OpenBLAS` on your ppc64le host. And I think Fedora has ppc64le binary rpms of 0.3.10

**Comment by abavisani** [comment]
> You could get a snapshot of the current `develop` branch and compile that - use https://github.com/xianyi/OpenBLAS/archive/develop.zip if you cannot do a `git clone https://github.com/xianyi/OpenBLAS` on your ppc64le host. And I think Fedora has ppc64le binary rpms of 0.3.10

did not work.

**Comment by martin-frbg** [comment]
Care to be more specific about what "did not work" - the fedora binary or building the develop branch ?

**Comment by brada4** [comment]
You can rebuild fedora RPM (or get slightly older one via EOEL)
https://src.fedoraproject.org/rpms/openblas/blob/HEAD/f/openblas.spec
Or at least find some build flags that enabled their build.
