### ISSUE TITLE
int64 version of openBLAS

### ISSUE THREAD

**Issue by access2rohit** [xianyi/OpenBLAS#2717]
Hi,
    I am trying to build MXNet with int64 version of openBLAS. I wanted to know that apart from INTERFACE64=1 and BINARY=64 flags. Is there a binary version of openBLAS available that supports int64 ? 
So I can install it like `sudo apt install libopenblas64-dev` sth like this ?

**Comment by martin-frbg** [comment]
As far as I know there is a libopenblas64-dev package provided by debian-science, though it may not yet be at the very latest (0.3.10) release

**Comment by access2rohit** [comment]
@martin-frbg Does it support int64_t API signatures ? Or is just for 64-bit architecture platforms?

**Comment by martin-frbg** [comment]
I doubt they would add a "64" suffix just for the architecture, but as I said I am not directly involved in providing that package.

**Comment by brada4** [comment]
It is rarity, you might need to do similar tricks outside julia:
https://github.com/apache/incubator-mxnet/pull/16125#issuecomment-568167647

**Comment by access2rohit** [comment]
@brada4 
https://packages.debian.org/sid/metapackages/libopenblas64-dev

Here it says: "This metapackage provides a 64-bit indexing version" which means this is good for inputs with sizes > (2^31-1)

**Comment by brada4** [comment]
internal dimensions math is not uint64 perfect in int32 build, probably matrix dimensions over int16 (32k pessimistically)  would flop inexplicably. ideally single dimension of 2^31-1 should be working if anyone had time to review through all dimension math inside.

**Comment by access2rohit** [comment]
@brada4 i didn't understand this part "internal dimensions math is not uint64 perfect in int32 build, probably matrix dimensions over int16 (32k pessimistically) would flop inexplicably"

**Comment by martin-frbg** [comment]
Seems he was still referring to what happens when one does _not_ use the INTERFACE64=1 version for large problems.

**Comment by access2rohit** [comment]
@martin-frbg quick question: If i build openBLAS with make flags `DYNAMIC_ARCH=1 DYNAMIC_OLDER=1 USE_OPENMP=1 INTERFACE64=1 BINARY=64 NO_SHARED=0 NO_LAPACK=0` is it correct way to build openBLAS with int64 support ? Because i cannot see any `64` or `_64` being appended or prefixed in library names or share object file names.

**Comment by access2rohit** [comment]
I need lapack interface so I added `NO_LAPACK=0`

**Comment by martin-frbg** [comment]
The suffix is a separate option (SYMBOLSUFFIX=64 , or LIBNAMESUFFIX=64 if you want only the library name but not the symbols to have a suffix)

**Comment by access2rohit** [comment]
So my build flags are correct ? But when I investigate the installation folder the `lapacke_utils.h` it shows `int` parameters in signatures and not `lapack_int`. Also, cblas.h shows `blasint` will `INTERFACE64=1 BINARY=64` we sufficient to set that as `int64_t` as well ?

**Comment by access2rohit** [comment]
@martin-frbg i also saw the following code in file openblas_config.h
```
#ifdef OPENBLAS_USE64BITINT
typedef BLASLONG blasint;
#else
typedef int blasint;
#endif
```
I don't set OPENBLAS_USE64BITINT anywhere in my makefile or build commands

**Comment by martin-frbg** [comment]
The lapacke headers and their concept of "INTERFACE64" (there called LAPACK_ILP64) are copied verbatim from the "netlib"
reference implementation of LAPACK. While it is true that there are some `int` parameters left among the `lapack_int`, these are essentially flags like matrix_layout that are not expected to assume a wide range of values.
Regarding your other question, INTERFACE64=1 is converted to USE64BITINT internally (by a strangely complicated route - Makefile.system instructs the getarch tool to return that value), which gets OPENBLAS prepended in the installed version of the OpenBLAS headers.
