### ISSUE TITLE
Out-of-source build instructions

### ISSUE THREAD

**Issue by alexeyr** [xianyi/OpenBLAS#2730]
Is it documented how to build OpenBLAS out-of-source? I'd really like to have two separate build directories for Android (ARM) and Linux (x86) without having to `make clean` to switch.

**Comment by martin-frbg** [comment]
This is pretty much standard with cmake (create your build directory somewhere and invoke `cmake ...options... /path/to/the/source` in it, like `cmake -DUSE_OPENMP=1 -DNUM_THREADS=128 ../OpenBLAS`) but not currently possible with plain `make`.

**Comment by alexeyr** [comment]
Ok, thank you!
