### ISSUE TITLE
BUG: Possible bug with dot product on Azure

### ISSUE THREAD

**Issue by larsoner** [xianyi/OpenBLAS#2732]
Using a fairly simple line with latest Python 3.8 NumPy built with OpenBLAS 3.10:
```
>>> import numpy as np, glob
>>> data = np.load(glob.glob('bad/*.npz')[0])
>>> a, b = data['a'], data['b']
>>> print(np.dot(a, b).shape)"
Cmd.exe exited with code '-1073741819'
```
The `.npz` is available as a build artifact [on Azure](https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=8349&view=logs&j=a846d25a-e32c-5640-1b53-e815fab94407&t=c40cce3b-0d9d-58ac-d4ba-617876a7e096).

It's possible that this has to do with CPU architecture detection being broken:

- If I [OPENBLAS_VERBOSE=2](https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=8348&view=logs&j=a846d25a-e32c-5640-1b53-e815fab94407&t=c40cce3b-0d9d-58ac-d4ba-617876a7e096) and run the line it outputs "Core: Haswell" (and oddly enough it seems not segfault?! but I didn't check to see if the result is actually valid).
- If I [OPENBLAS_CORETYPE='nehalem'](https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=8347&view=logs&j=a846d25a-e32c-5640-1b53-e815fab94407&t=c40cce3b-0d9d-58ac-d4ba-617876a7e096) it seems not to segfault

Not 100% sure about this because I can't 100% replicate the issue. I did a bit of searching and didn't know how to get the information from Azure (e.g., via some command-line utility).

Cross-ref with https://github.com/numpy/numpy/issues/16913

**Comment by isuruf** [comment]
Can you check with openblas develop branch? Looks like https://github.com/xianyi/OpenBLAS/issues/2728

**Comment by larsoner** [comment]
I'll close as a duplicate and re-open if need be, thanks!
