### ISSUE TITLE
ARM64 DTB_DEFAULT_ENTRIES

### ISSUE THREAD

**Issue by johnduffymsc** [xianyi/OpenBLAS#2733]
Hi

Please can you confirm that for a CPU such as the Arm Cortex-A72 the DTB_DEFAULT_ENTRIES refers to the L1 Data TLB?

In the Arm Cortex-A72 Technical Reference Manual (TRM) it refers to:

L1 Instruction TLB
L1 Data TLB
L2 TLB

The reason I ask it that cpuid_arm64.c has the DTB_DEFAULT_ENTRIES as 64 for the for the COrtex-A57, A72 and A73 CPUs, but the Arm Cortex-A72 TRM says the L1 Data TLB is 32 entry.

Many thanks

**Comment by martin-frbg** [comment]
That is my understanding - however this oversight should have no practical consequences as the DTB_DEFAULT_ENTRIES is currently not used in any of the ARM or ARM64 microkernels (in fact it only features in a few GEMV kernels for 32bit x86 that date back to the original GotoBLAS). It should certainly be corrected if/when/before anybody is tempted to use it, so thanks for the hint.

**Comment by johnduffymsc** [comment]
Thank you!
