### ISSUE TITLE
Need support for Renoir CPUs

### ISSUE THREAD

**Issue by huaiyuli** [xianyi/OpenBLAS#2738]
Nothing worth mentioning, it just does not recognize Renoir and uses Prescott binaries. I am able to get the performance acceptable by re-compiling with TARGET=ZEN yet it should be officially fixed since otherwise things like Julia will not work well out of box while the user might be suffering from the legacy binaries' slowness and still think them to be normal.

**Comment by martin-frbg** [comment]
Could you post the first few lines of your /proc/cpuinfo please ? I would have thought it would be covered by the Zen2 family/model numbers already in cpuid_x86.c (if you are using a somewhat recent release e.g. 0.3.9/0.3.10 or the 
development branch)

**Comment by brada4** [comment]
https://www.notebookcheck.nl/Kort-testrapport-AMD-Ryzen-3-3100-en-Ryzen-3-3300X-met-4-cores-en-8-threads.466306.0.html has 2 cpu-z pictures with extfamily 17 thats not in the ZEN list.

@huaiyuli you dont have to recompile everything, probably distributed binaries are compiled for dynamic architecture detection and you can set OPENBLAS_CORETYPE=ZEN or =HASWELL to get the right code running waiting for next version.

**Comment by martin-frbg** [comment]
Indeed looks like we are currently missing extfamilies 17h and 19h (though I was fairly certain that we already detected the extfamily 17h Threadrippers ?)

**Comment by huaiyuli** [comment]
> Could you post the first few lines of your /proc/cpuinfo please ? I would have thought it would be covered by the Zen2 family/model numbers already in cpuid_x86.c (if you are using a somewhat recent release e.g. 0.3.9/0.3.10 or the
> development branch)

I have them here:

```
Processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 96
model name	: AMD Ryzen 5 4600HS with Radeon Graphics
stepping	: 1
microcode	: 0xffffffff
cpu MHz		: 2994.371
cache size	: 512 KB
physical id	: 0
siblings	: 12
core id		: 0
cpu cores	: 6
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes

```
It is not 17h or 19h. I will read more later about the codes for detection yet for the moment the CPU family is worth mentioning before this issue closes. (BTW, is there a reason why parsing the model name is not an alternative for the detection?)

**Comment by martin-frbg** [comment]
23 decimal is 17 in hexadecimal. OpenBLAS already recognizes this family, but only models 1 (Zen1 desktop) and 8 (Zen2 desktop) so far. Right now it probably does not even make sense to add individual family members on a per-model basis when it is only the fundamental architecture that we are interested in so I'll just add a default case for "any model" zen2.
Parsing the model name would be even messier than the current approach that uses documented, unique model numbers (which only has its drawbacks when a new cpuid needs to be added to the code, maybe I should look again at outputting "unknown" ID data in a form that would be easier to report and add to the code)

**Comment by jebej** [comment]
I can also confirm this on 0.3.9, and that setting `OPENBLAS_CORETYPE=ZEN` helps performance.

I have uploaded the full CPUID info here, if it is useful: http://www.cpu-world.com/cgi-bin/CPUID.pl?CPUID=71632
