### ISSUE TITLE
Can't install correctly on Intel platform

### ISSUE THREAD

**Issue by cppfred** [xianyi/OpenBLAS#2742]
After clone the files form github, the next step is use shell command "make". But I get stuck on this step now. Error tips told me one error "Detecing CPU failed" has been found. Now my **platfrom's CPU is Intel Core i9-9900K**, and I try to set the parameter "TARGET" but still get the same error. Is there any solution to solve the problem? Or just OpenBLAS can't support this CPU?
![image](https://user-images.githubusercontent.com/47978719/88618317-66cef880-d0cb-11ea-925e-8e91600851dd.png)

**Comment by Iceman9** [comment]
Hello. 

On which branch are you?

`git status`

When you cloned the repository, did you checkout develop? master branch is quite behind from develop.

`git checkout develop`

**Comment by martin-frbg** [comment]
Yes you need the `develop` branch (or the 0.3.10 release) which should both recognize the i9-9900K (I think). If you got the `master` branch this is three years out of date now (but would probably still compile if you make the target all caps - TARGET=NEHALEM or actually TARGET=HASWELL for best performance)

**Comment by cppfred** [comment]
> Yes you need the `develop` branch (or the 0.3.10 release) which should both recognize the i9-9900K (I think). If you got the `master` branch this is three years out of date now (but would probably still compile if you make the target all caps - TARGET=NEHALEM or actually TARGET=HASWELL for best performance)

![image](https://user-images.githubusercontent.com/47978719/88674633-9fe38900-d11c-11ea-8a3e-743a2768ee02.png)
Is that means the BLAS is install correctly? The parameter TARGET=HASWELL is really useful, thanks!

**Comment by cppfred** [comment]
> Hello.
> 
> On which branch are you?
> 
> `git status`
> 
> When you cloned the repository, did you checkout develop? master branch is quite behind from develop.
> 
> `git checkout develop`

I remove the directory which clone earlier, and switch to "developer" branch to clone again. Then add the parameter TARGET=HASWELL and problem is solved, thank you for your advise!

**Comment by martin-frbg** [comment]
Was it necessary to add TARGET=HASWELL to build the `develop` branch as well ? (BTW that screenshot looks a bit weird with the "/path/to/your/installation" that is just a placeholder in the documentation for /opt/OpenBLAS or whereever you want to install it. But it should work.)

**Comment by cppfred** [comment]
Well, "/path/to.your/installaion" is programme tips for me to install when command "make TARGET=HASWELL" is done. So I just type it in and run (lol). But I don't know is there any necessary to build develop barnch, I just do it for safe.

**Comment by cppfred** [comment]
> Was it necessary to add TARGET=HASWELL to build the `develop` branch as well ? (BTW that screenshot looks a bit weird with the "/path/to/your/installation" that is just a placeholder in the documentation for /opt/OpenBLAS or whereever you want to install it. But it should work.)

Well, "/path/to.your/installaion" is programme tips for me to install when command "make TARGET=HASWELL" is done. So I just type it in and run (lol). But I don't know is there any necessary to build develop barnch, I just do it for safe.

**Comment by cppfred** [comment]
> Was it necessary to add TARGET=HASWELL to build the `develop` branch as well ? (BTW that screenshot looks a bit weird with the "/path/to/your/installation" that is just a placeholder in the documentation for /opt/OpenBLAS or whereever you want to install it. But it should work.)

Well, "/path/to.your/installaion" is programme tips for me to install when command "make TARGET=HASWELL" is done. So I just type it in and run (lol). But I don't know is there any necessary to build develop branch, I just do it for safe.

**Comment by brada4** [comment]
@cppfred  the question is if it builds without TARGET=HASWELL, i.e if your CPU is detected by OpenBLAS.

**Comment by martin-frbg** [comment]
According to wikichip, i9-9900K is family 6, model 158 (= 9E in hexadecimal, i.e. extended model 9, model 14) which is definitely
handled in cpuid_x86.c as "just another Haswell refresh".

**Comment by cppfred** [comment]
> @cppfred the question is if it builds without TARGET=HASWELL, i.e if your CPU is detected by OpenBLAS.

No, with default settings I can't build it correctly, and the tip is "Detecing CPU failed". It only build sucess after I add parameter "TARGET=HASWELL"
I have solve this problem now, and I will close this issue.
