### ISSUE TITLE
openBLAS build with int64 support fails on valid input for ssyevd

### ISSUE THREAD

**Issue by access2rohit** [xianyi/OpenBLAS#2745]
From GDB
```
ssyevd (jobz='V', uplo=76 'L', n=80000, a=0x7fea6c1ee010, lda=80000, w=0x7ffcd0006450, work=0x7fde7ffed010, lwork=12800480256, iwork=0x7fea6bde2010,
    liwork=400003, info=0x7fea6c90f01c
```
when passing the above parameters the error occurs with parameter 'lwork' since `info` returned is (-8). But as per the documentation: http://www.netlib.org/lapack/explore-html/d3/d88/group__real_s_yeigen_ga6b4d01c8952350ea557b90302ef9de4d.html#ga6b4d01c8952350ea557b90302ef9de4d values passed seem correct 

Am I doing something wrong here ?

**Comment by martin-frbg** [comment]
What value for lwork does ssyevd suggest when you run a workspace query (lwork = -1) ?

**Comment by access2rohit** [comment]
> What value for lwork does ssyevd suggest when you run a workspace query (lwork = -1) ?

12800480256

after calling like this
```
ssyevd (jobz='V', uplo=76 'L', n=80000, a=0x7fea6c1ee010, lda=80000, w=0x7ffcd0006450, work=0x7fde7ffed010, lwork=-1, iwork=0x7ffce6078cc0, liwork=-1, info=0x7ffac9c0f00c
```

**Comment by martin-frbg** [comment]
Strange. As I read the code, the INFO=-8 is returned when the actual lwork is smaller than 1+6*N+2*N*N (which should evaluate to 12800480001 in your case so the error should not be raised). If the LAPACk ssyevd had inadvertently been built without int64 support I would expect worse things to happen however - probably need to step into ssyevd and have gdb print the lwork and lwmin (or add WRITE statements to the fortran code) to see what is actually happening.

**Comment by access2rohit** [comment]
I think it is a problem with int64 build because after building with symbolsuffix=_64 flag and adding that declaration manually to cblas.h it operators that weren't earlier working started working

**Comment by martin-frbg** [comment]
Hm, what exactly did you need to change in the build ? (The symbolsuffix alone should not matter unless you have existing code that expects to call function names that end in _64. Good point that these suffixes probably need to be propagated to cblas.h so that the correct prototypes are available - maybe it was picking up those from another header not belonging to OpenBLAS ?)

**Comment by access2rohit** [comment]
Hi,
    upon inspection it seems like an issue with Amazon's Deep Learning AMI that causes issues with linking to libopenvlas.so (even after installing via update alternatives). Will investigate further and update. An easier way for users to build int64 version(IMO) would be to generate a shared object and header files with `_64` suffix so we can clearly add them to PATH and LD_LIBRARY_PATH along with update alternatives.

**Comment by martin-frbg** [comment]
INTERFACE64=1 SYMBOLSUFFIX=_64 should do this (after #2753), or did I misunderstand your remark ?

**Comment by access2rohit** [comment]
@Zha0q1 Can you confirm whether #2753 solves the issue? @martin-frbg Thanks for quickly providing a fix !

**Comment by Zha0q1** [comment]
> @Zha0q1 Can you confirm whether #2753 solves the issue? @martin-frbg Thanks for quickly providing a fix !

Sure, I replied to the PR last week and have not been able to test the new version. Will find time to do so and reply to the PR directly. @martin-frbg  Thanks for the update!

**Comment by martin-frbg** [comment]
@Zha0q1 any update on this ?

**Comment by Zha0q1** [comment]
> @Zha0q1 any update on this ?

Sorry for the delayed response. Yeah I was able to build my program with the suffixed declarations. I haven't tried all functions but the cblas_ ones all ran fine. Thanks!

**Comment by martin-frbg** [comment]
Ok thanks.
