### ISSUE TITLE
ARM64 L2_SIZE Tweaks Strange Behaviour

### ISSUE THREAD

**Issue by johnduffymsc** [xianyi/OpenBLAS#2747]
Hi

Whilst changing the L2_SIZE to 1MB to reflect the 1MB L2 cache on my Raspberry Pi 4, I've noticed some strange behaviour running HPL Linpack benchmarks (NB = 128, N = the closest integer multiple of NB to 80% memory), 

```
L2_SIZE 0.5 MB - 13.2 Gflops
L2_SIZE 1.0 MB - 13.2 Gflops
L2_SIZE 0.0 MB - 13.2 Gflops!!!
```
It would appear the L2_SIZE is being ignored.

A quick ```grep -r L2_SIZE``` reveals L2_SIZE is only used in ```driver/memory.c```.

And I've noticed their is a FIXME in ```params.h``` relating to cache sizes.

I'm happy to try to help out and fix this, if this is not the expected behaviour?

Best wishes

**Comment by johnduffymsc** [comment]
As an aside, BLIS running the same benchmarks is 1 - 2 Gflops faster (Ubuntu 20.04 ARM64)

I would like to help to get OpenBLAS running as fast. But I will need some pointers as to where to look...

**Comment by martin-frbg** [comment]
Most of the power in Goto's method comes from fitting things into L1, and unfortunately he must have taken some pre-existing code for identifying cpu features so there are numerous parameters getting defined that no part of the code actually uses. It is debatable if paying more attention to a (probably shared) L2 is where performance could be gained - the A72 of the Pi4 is currently treated mostly the same as an A57, and the locking I had to introduce to make the code thread-safe in the first place may still be more expensive than absolutely necessary.

**Comment by johnduffymsc** [comment]
Thanks martin. I will have a further look around the source code. I would like to understand it better anyway...
