### ISSUE TITLE
Strange Performance When Using OpenBLAS with Eigen API

### ISSUE THREAD

**Issue by albertchang1989** [xianyi/OpenBLAS#2748]
Thanks for this great project!

In my program, QR decomposition is calculated with Eigen function HouseholderQR. After linking to OpenBLAS with Eigen API "EIGEN_USE_BLAS", the decomposition cost less time. However, the other part of my program (1000 * 1000 matrix calculation without Eigen matrix) cost much more time in some specific epoch. This phenomena repeat every time when I run the program. If I don't use BLAS, this phenomena wont appear.

The compile options of OpenBLAS are all default settings. Is there any options that can be edit to solve this problem?

**Comment by martin-frbg** [comment]
What kind of computer are you using ? (And I assume you are using BLAS calls in "the other part" of your program ?) One trivial possibillty could be that your computer reduces its cpu frequency due to overheating, another that you are observing the sum of your cpu times spent in parallel rather than the reduction in "wallclock time" from processing a problem in parallel.

**Comment by brada4** [comment]
You need to set EIGEN_USE_LAPACKE(_STRICT) to offload HouseholderQR offload as per documentation, it could be that it uses GEMM under the hood anyway but less than with lapack call.
https://eigen.tuxfamily.org/dox/TopicUsingBlasLapack.html
You can set breakpoint on `_(S/D)GEMM` to see where actual matrix multiplication lands.

**Comment by albertchang1989** [comment]
> What kind of computer are you using ? (And I assume you are using BLAS calls in "the other part" of your program ?) One trivial possibillty could be that your computer reduces its cpu frequency due to overheating, another that you are observing the sum of your cpu times spent in parallel rather than the reduction in "wallclock time" from processing a problem in parallel.

1. the program is running on a cloud service, centOS, 2.5GHz cpu.
2. the "specific epoch" are the same every time when I restart the program with same data.  
![image](https://user-images.githubusercontent.com/42538196/88872475-d4566280-d24c-11ea-83a9-d6910ae121d1.png)
3. "the other part" is "obsupdate" shown in the above picture. I don‘t use any Eigen matrix or OpenBLAS API in this part.
4. the program is single thread, time consumption equals cpu time after "obsupdate" minus cpu time before entering "obsupdate" .
@martin-frbg

**Comment by albertchang1989** [comment]
> You need to set EIGEN_USE_LAPACKE(_STRICT) to offload HouseholderQR offload as per documentation, it could be that it uses GEMM under the hood anyway but less than with lapack call.
> https://eigen.tuxfamily.org/dox/TopicUsingBlasLapack.html
> You can set breakpoint on `_(S/D)GEMM` to see where actual matrix multiplication lands.

Do you mean use "EIGEN_USE_LAPACKE" instead of "EIGEN_USE_BLAS"? I try this, the phenomena of increase of time consumption still exist but appear in other epoch.
![image](https://user-images.githubusercontent.com/42538196/88873612-9f97da80-d24f-11ea-895b-d61e4aa9e53f.png)

@brada4

**Comment by brada4** [comment]
I just pointed to Eigen docs telling particular function is not completely offloaded to BLAS.
Are you counting total wall time or CPU used? 2.5 or 0.8 seconds are 10-50x slow for 1000 by 1000 GEMM on a 2.5GHz CPU. Do you have an idea (like /proc/cpuinfo) on what actual CPU is?
Are you able to repeat same thing (fixed input, just repeat) on your own hardware? If cloud provider does not guarantee any performance, it is quite logical they overcommit system in places you dont see.

**Comment by martin-frbg** [comment]
Cache eviction ? But that still wouldn't explain why it happens that deterministically on a few cycles only.(Is it really exactly repeatable, or does the slow phase move around a bit ?) Most likely explanation to me is that the cloud service is playing tricks on you, moving your task to a different cpu, reclaiming memory or slowing down data reads at times.

**Comment by albertchang1989** [comment]
> I just pointed to Eigen docs telling particular function is not completely offloaded to BLAS.
> Are you counting total wall time or CPU used? 2.5 or 0.8 seconds are 10-50x slow for 1000 by 1000 GEMM on a 2.5GHz CPU. Do you have an idea (like /proc/cpuinfo) on what actual CPU is?
> Are you able to repeat same thing (fixed input, just repeat) on your own hardware? If cloud provider does not guarantee any performance, it is quite logical they overcommit system in places you dont see.

This is my cpu info
![image](https://user-images.githubusercontent.com/42538196/88896774-eb14ad80-d27c-11ea-89ad-248d95fb1909.png)

I am counting total wall time, but in "obsupdate" there are no other I/O process. the calculation of 1000*1000 matrix is implemented by ourself, that is the reason why it is slow.

Because of some policy, I cant download the program from the cloud now, but I will try.
@brada4

**Comment by albertchang1989** [comment]
> Cache eviction ? But that still wouldn't explain why it happens that deterministically on a few cycles only.(Is it really exactly repeatable, or does the slow phase move around a bit ?) Most likely explanation to me is that the cloud service is playing tricks on you, moving your task to a different cpu, reclaiming memory or slowing down data reads at times.

I am pretty sure it is deterministic when using the same input. As @brada4 suggested, I will try to run the program on my hardware the check if it is related to the environment.

**Comment by albertchang1989** [comment]
By the way, if i just remove "EIGEN_USE_BLAS" in my code which means use Eigen itself to do the calculation, the phenomena disappear. @brada4 @martin-frbg

**Comment by albertchang1989** [comment]
I use another cloud service with a better configuration, see below.
![image](https://user-images.githubusercontent.com/42538196/88900959-befc2b00-d282-11ea-9a92-0a29adbf14d3.png)
The phenomena still exist.
![image](https://user-images.githubusercontent.com/42538196/88901018-d3d8be80-d282-11ea-8725-b12d848f1fd4.png)

**Comment by martin-frbg** [comment]
Just for completeness, which version of OpenBLAS are you currently using ?

**Comment by albertchang1989** [comment]
> Just for completeness, which version of OpenBLAS are you currently using ?

V0.3.10

**Comment by martin-frbg** [comment]
You mentioned that your program is single-threaded, does this apply to your build of OpenBLAS as well ? (Thinking it might be OpenBLAS threads occasionally lingering on and getting in the way, as your VMs appear to have multiple cores)

**Comment by albertchang1989** [comment]
> You mentioned that your program is single-threaded, does this apply to your build of OpenBLAS as well ? (Thinking it might be OpenBLAS threads occasionally lingering on and getting in the way, as your VMs appear to have multiple cores)

I build OpenBLAS in a single thread version with the setting USE_THREADING = 0 in MakeFile.rule

**Comment by brada4** [comment]
Do you experience same slowdowns when using OPENBLAS_CORETYPE=HASWELL ?
Just a speculation that employing AVX-512 heats CPU into thermal throttling, thugh unlikely knowing following:

Both CPUs are order-built, i.e think google cloud/amazon/azure and not sold to consumers, so bad they dont even appear in intel ark lists, just blurred mentions in wikipedias.

**Comment by brada4** [comment]
.. microcode 0x1 means you are running inside KVM, you will not see when your CPU thread shares a CPU with strangers' VM..
somebody consumes 3/4 of same core while you get painful measurable slowdown while TSC goes ahead as if they never came by.
Probably you can run same measurement continuously while idle, and you see them coming once in a while. We cannot add a strong elbow to your VM to get to the real CPU.

**Comment by albertchang1989** [comment]
> Do you experience same slowdowns when using OPENBLAS_CORETYPE=HASWELL ?
> Just a speculation that employing AVX-512 heats CPU into thermal throttling, thugh unlikely knowing following:
> 
> Both CPUs are order-built, i.e think google cloud/amazon/azure and not sold to consumers, so bad they dont even appear in intel ark lists, just blurred mentions in wikipedias.

Although the performance of the function which use OpenBLAS become a little bit worse, the slowdown has gone when I built the OpenBLAS with NO_AVX2 = 1 in MakeFile.rule! I guess NO_AVX2 = 1 equals the HASWELL branch?
@brada4

**Comment by albertchang1989** [comment]
> .. microcode 0x1 means you are running inside KVM, you will not see when your CPU thread shares a CPU with strangers' VM..
> somebody consumes 3/4 of same core while you get painful measurable slowdown while TSC goes ahead as if they never came by.
> Probably you can run same measurement continuously while idle, and you see them coming once in a while. We cannot add a strong elbow to your VM to get to the real CPU.

sorry, I can't understand.

**Comment by brada4** [comment]
You are running inside the virtual machine. Not that I completely deny any chance of such performance regression possible with OpenBLAS, just that measurements you make pretty much fall within typical damage of overcommitment of resources coming as natural part of any virtualisation.

More appropriate setting is (undocumented) `NO_AVX512=1`, that would keep AVX-512 units inside CPU untouched and keep "normal" case slightly better than AVX-1 only.

You could retrofit the sample (or more with varied build options) as monitoring probe into smokeping or similar monitoring system to better characterize your cloud system. Maybe there is a pattern every hour or 5min something scheduled oppresses everybody on the same piece of cloud you are on or so.

**Comment by martin-frbg** [comment]
NO_AVX2=1 equals Sandybridge, probably not necessary to go that far back in time and performance. (I _think_ I saw it mentioned in some talks when AVX512 was new that using this unit could/would lead to a momentary drop in cpu frequency but I do not understand how this could show up as a delayed effect)

**Comment by albertchang1989** [comment]
> You are running inside the virtual machine. Not that I completely deny any chance of such performance regression possible with OpenBLAS, just that measurements you make pretty much fall within typical damage of overcommitment of resources coming as natural part of any virtualisation.
> 
> More appropriate setting is (undocumented) `NO_AVX512=1`, that would keep AVX-512 units inside CPU untouched and keep "normal" case slightly better than AVX-1 only.
> 
> You could retrofit the sample (or more with varied build options) as monitoring probe into smokeping or similar monitoring system to better characterize your cloud system. Maybe there is a pattern every hour or 5min something scheduled oppresses everybody on the same piece of cloud you are on or so.

I tried NO_AVX512=1, the slowdown still exist. I guess the best configuration with my system is NO_AVX2=1.

**Comment by brada4** [comment]
It is not explainable within OpenBLAS.

There are many speculative execution vulnerabilities not addressed in your kernel.
Basically you need to fully power off/on a virtual machine to get host+qemu new CPUID bits through, then update kernel, or all at once. Some of vulnerabilities need cooperation between guest and host to regain performance, having only host side is bad.
Tool to check progress: https://github.com/speed47/spectre-meltdown-checker

**Comment by martin-frbg** [comment]
@brada4 it is not clear to me what spectre&meltdown vulnerabilities would have to do with AVX2 performance in particular ? To me this is looking more like the cloud hoster is discouraging compute-intensive tasks, or just using a hardware setup that really suffers from AVX2 workloads. Google found me a blog post that addresses this (although the Intel erratum SKX24 it refers to is about AVX512 specifically, as mentioned previously)
https://movingfulcrum.com/neighboring-avx-workloads-can-impact-your-vms-and-kubernetes-clusters/

**Comment by brada4** [comment]
What you say means @albertchang1989 guessed right :+1: 
Mine just fixes few percent loss of having double cache housekeeping around vm exit/enter.

**Comment by albertchang1989** [comment]
Thanks for all these explanations!  I will close this issue
