### ISSUE TITLE
Error installing OpenBLAS on ubuntu 12.04 precise.

### ISSUE THREAD

**Issue by curioustolearn** [xianyi/OpenBLAS#275]
I am trying to install OpenBLAS using the instructions and the download file given here:
http://xianyi.github.io/OpenBLAS/

I get the following error:

../common.h:579:27: fatal error: cblas_noconst.h: No such file or directory
compilation terminated.
make[1]: **\* [cblas_isamax.o] Error 1
make[1]: Leaving directory `/home/admin/downloads/xianyi-OpenBLAS-9c51cdf/interface'
make: **\* [libs] Error 1

I was having trouble installing Julia and then thought I will install OpenBLAS first but am having the same trouble. Can someone please help?

Thanks.

**Comment by rcgn** [comment]
Same problem .
My CPU is CORE i5 6300HQ, which TARGET should I Select?

**Comment by martin-frbg** [comment]
TARGET=HASWELL should work - which version of OpenBLAS are you trying to build ? ("SkyLake" type CPUs should be autodetected since about version 0.2.15, released more than a year ago)
