### ISSUE TITLE
suffix and prefix in cblas.c?

### ISSUE THREAD

**Issue by Zha0q1** [xianyi/OpenBLAS#2751]
Hi,

I am trying to build openblas with int 64 indexing and prefix = something. Is there a way to automatically generate the suffixed function declaration in cblas.h? 

Thanks

**Comment by martin-frbg** [comment]
This just came up in #2745, I need to add it.
What would probably work (manually for now) is
`sed -i -e "s/cblas/someprefixcblas/g" cblas.h`
(and similarly `sed -i -e "s/(OPENBLAS/somesuffix(OPENBLAS/g"` if needed)

EDIT: same method should (currently) work for replacing "openblas" by "someprefixopenblas" and "(void)" by "somesuffix(void)" though in the long run it may be safer to have placeholders for pre- and suffix in the cblas.h template
that get replaced or removed as necessary on installation.
Another topic for discussion is that SYMBOLPREFIX and SYMBOLSUFFIX appear to be silently ignored when INTERFACE64 is not set. This obviously stems from the context in which they were originally implemented, but
there might well be other reasons why one would want to "personalize" the library ?

**Comment by Zha0q1** [comment]
Thanks for the PR! In my use case I actually need both the int 32 and 64 version of the functions. Would you also add a flag to control whether to have them coexist in cblas.h?

**Comment by martin-frbg** [comment]
That is probably not so easy to implement, why would you need this to coexist ?

**Comment by Zha0q1** [comment]
There are multiple sections that use blas in the code base I am working on. I am only trying to extend support to large tensors in one place. Plus adding prefix to all function declarations will affect all other programs that use blas on the same system.
