### ISSUE TITLE
Adding POWER9 to travis CI

### ISSUE THREAD

**Issue by RajalakshmiSR** [xianyi/OpenBLAS#2754]
It would be nice to add a P9 system in our travis CI.
There are POWER9 systems at OSU. We can  request for VM here:
https://osuosl.org/services/powerdev/

**Comment by RajalakshmiSR** [comment]
cc @ceseo

**Comment by martin-frbg** [comment]
I must admit it is unclear to me how this meshes with travis CI - as far as I know their P8 offering (still a semi-official beta ?) is using osuosl but no idea if they would be easily convinced to expand it to P9. Or are you suggesting setting up a generic CI of our own using a github workflow or whatever?

**Comment by ceseo** [comment]
@martin-frbg I think that, as a community, submitting a request for adding P9 to Travis CI wouldn't hurt. I understand that may take a while to happen.

Meanwhile, adding a way to test on P9 in the workflow sounds like a very good idea. Is it something that you would consider?

**Comment by martin-frbg** [comment]
@ceseo certainly - I "only" need to read up on how to do it with an external "self-hosted" site.

**Comment by ceseo** [comment]
@martin-frbg cool! If you need help setting up a P9 at OSU, please let me know.

**Comment by martin-frbg** [comment]
Access request submitted, still a bit sketchy about setup but found their powerci wiki documentation already

**Comment by martin-frbg** [comment]
Request got approved and both xianyi's and my github username added to powerci. No idea yet how to match the "freestyle setup" described in the wiki to what is actually available on the Jenkins dashboard.

**Comment by martin-frbg** [comment]
@ceseo if you could point me to some documentation for setting up jobs with the osuosl Jenkins specifically that would be great - right now I do not even see anything in their interface that would allow me to do anything except add a bio to my username.
BTW I have also asked about P9 support in the travis community forum but judging from their blog they seem to be focused on expanding their aarch64 portfolio.

**Comment by martin-frbg** [comment]
Just received a reply from travis - with their recent move to the POWERVS cloud all their POWER  backend is actually P9 now apparently.

**Comment by ceseo** [comment]
@martin-frbg which request form did you submit? The POWER CI form, or the OpenStack one?

Regarding Travis, it seems the problem is that the build script is passing `-mcpu=power8`, as you can see [here](https://travis-ci.org/github/xianyi/OpenBLAS/jobs/716881083)

**Comment by martin-frbg** [comment]
POWERCI as I did not know any better... regarding Travis the `-mcpu=power8` is a direct consequence of having `TARGET=POWER8` in the build options (to define minimum requirement for the shared parts of the DYNAMIC_ARCH build).
I have created a PR that adds a separate `TARGET=POWER9` run (where we could also add a benchmark step if that makes sense).

**Comment by ceseo** [comment]
@martin-frbg excellent, thanks!

So, you can't do anything in the Jenkins dashboard [here](https://powerci.osuosl.org)? If not, I can ask someone there to walk you through this.

**Comment by martin-frbg** [comment]
Well; I can log in and edit the description of my user, and see other project's build history but that is about it. Clicking on "New item" on the main Jenkins page or "Configure" on my user page gets me flaming Mr.Jenkins with no explanation what I did wrong. Maybe I am just to dense to realize where and how I need to start defining my own builds, or maybe the UI does not work in firefox ? In any case I have not found any howto that matches what I see, least of all in the osl wiki. osuosl folks were
like "there you have it, hope it is what you wanted". IFF travis already does what you/we need I'm inclined to give Jenkins a rest.

**Comment by martin-frbg** [comment]
Hmmm. P9 build bombs out with an ICE due to the old gcc version (thought I had added workarounds for that while testing in the unicamp minicloud, but probably not for 5.x) . Preceding, unchanged P8 build completes as usual but on closer inspection I do not actually see it compiling P9 as per DYNAMIC_ARCH, probably because of compiler guards in the Makefile.

**Comment by ceseo** [comment]
@martin-frbg I think for the purposes of a functional CI, Travis is enough for now. I'm trying to contact someone at OSU to look at your Jenkins as well.

**Comment by martin-frbg** [comment]
Haven't quite gotten Travis to work but this is mostly due to me not realizing I cannot use their usual addon to update (gcc) packages on ppc64le. OSUOSL folks including support people in India are already looking into what seems to be a permissions problem. Will update here as soon as either CI setup is sorted...

**Comment by martin-frbg** [comment]
Power9 build (using gcc/gfortran-9) now integrated into our Travis configuration.
Jenkins permissions issue solved by OSUOSL, test build works at least when manually invoked (and without fortran, as network access to `dnf install gcc-gfortran` into the provided docker image appears to be flaky right now)

**Comment by martin-frbg** [comment]
Jenkins now using an Ubuntu image with gfortran. Haven't figured out how triggering builds by PR is supposed to work

**Comment by ceseo** [comment]
I think you have to configure a github-webhook in the repository settings pointing to the Jenkins server.

**Comment by martin-frbg** [comment]
Yes, but I do not have full admin control over the repo - need to try this in my fork and then ask xianyi to do it.
Do we/you actually need both travis and jenkins in parallel ?

**Comment by ceseo** [comment]
No, Travis would suffice for me. And if they are in PowerVS, they will eventually get POWER10 in the future.
