### ISSUE TITLE
What does this error message mean?No rule to make target `cuda_init.c', needed by `cuda_init.o'

### ISSUE THREAD

**Issue by Codingrunningman** [xianyi/OpenBLAS#2755]
Today when I want to compile the source code, I met this problem:
```
No rule to make target `cuda_init.c', needed by `cuda_init.o'
```
And my configuration just like this:
machine:arrch64
gcc:9.2.0
cmake:3.16.4

My machine does not have GPUs, does it cause this problem?And how can I solve it without GPUs?

**Comment by martin-frbg** [comment]
Whatever it is, it does not come from OpenBLAS. What code is it that you want to compile ?

**Comment by Codingrunningman** [comment]
I just want compile the OpenBLAS source code.
First, I run this command
```
git clone https://github.com/xianyi/OpenBLAS.git
```
I run `make` then I get this error. If it is not caused by OpenBLAS, where it may come from?

**Comment by martin-frbg** [comment]
Hm. There is some (probably very old) entry in driver/others/Makefile that wants to build a (nonexistent) cuda_init module whne USE_CUDA is defined. Perhaps you have this in your CFLAGS or elsewhere in your environment from some other project ?

**Comment by Codingrunningman** [comment]
Yeah, I export this variable `export USE_CUDA=0` before I compile the source code

**Comment by Codingrunningman** [comment]
Maybe it is the reason, I will delete this variable, thank you martin

**Comment by martin-frbg** [comment]
With these old variables there was often the problem that setting them to 0 was the same as setting them to 1, as the makefiles would only check for "if defined". I'll look at this later and probably just delete those lines.
