### ISSUE TITLE
Is there an option so that libgfortran.a and libquadmath.a can be staticly archived into libopenblas.a when running make? 

### ISSUE THREAD

**Issue by atesop** [xianyi/OpenBLAS#2759]
Hi all, is there an option so that libgfortran.a and libquadmath.a can be staticly archived into libopenblas.a when running `make`? 
 
 when I run `make`, I find `gfortran` is miss.  And after run `yum install libgfortran`, `make`  runs perfert.

But, I try to find out `gfortran_concat_string`, I get that
```bash
# nm libopenblas.a | grep fortran
                 U _gfortran_concat_string
```
That means gfortran has to been preinstalled when `libopenblas.a` is needed.

Any suggestion is appreciated. Thanks.

**Comment by martin-frbg** [comment]
You could try adding `-static-libgfortran` to your compile flags, but there is no clean way to do the same for libquadmath. (You'd probably need to hack the makefiles to add libquadmath.a directly - there have been proposals and patches for gfortran to add a -static-libquadmath option but libquadmath appears to be under a less permissive license for historical reasons.) 
If you can be sure that you will only ever use BLAS functions and no LAPACK, the easiest solution is to build with NOFORTRAN=1 or NO_LAPACK=1 as Fortran is only used in the LAPACK parts (which are mostly a direct copy of the "netlib"
reference implementation).
