### ISSUE TITLE
Cross-compiling for ARMV8 on Ubuntu 18

### ISSUE THREAD

**Issue by mshadian** [xianyi/OpenBLAS#2762]
I'm having trouble cross-compiling the library for ARMV8 on Ubuntu 18. Any specific toolchain I need to use? I've been able to make the library for 32-bit ARMV7 using:

`make CC=arm-linux-gnueabihf-gcc HOSTCC=gcc TARGET=ARMV7 BINARY=32`

but for ARMV8 I'm using:

`make CC=arm-none-eabi-gcc HOSTCC=gcc TARGET=ARMV8 BINARY=64`

and I get the following error:

`make[1]: *** No rule to make target '../kernel/arm/amax.S', needed by 'samax_k.o'.  Stop.`

Do I need to use a different toolchain, or anything else I'm doing wrong?

Thanks in advance!

**Comment by martin-frbg** [comment]
Is your arm-none-eabi-gcc a 64bit toolchain ? The error message certainly suggests that the compiler could only compile the testcode for 32bit armv7.

**Comment by martin-frbg** [comment]
You would need a toolchain with a name starting with aarch64, which for Ubuntu18 is probably the gcc-8-aarch64-linux-gnu package (providing aarch64-linux-gnu-gcc-8)

**Comment by brada4** [comment]
Another way is using `clang-12 -target=aarch64-..-...` , the 'standard; libraries from cross-compiler or extracted from target platform are still relevant. PS There is better clang in llvm apt repo
