### ISSUE TITLE
Library working in Xilinx SDK on Ubuntu but gives syntax error on Windows

### ISSUE THREAD

**Issue by mshadian** [xianyi/OpenBLAS#2766]
When cross-compiling the library, I used the gcc in my ‘host” Ubuntu to build the library for the “target” armv8, using the cross toolchain aarch64-linux-gnu-gcc. And the resulted library worked in my 2018.3 Xilinx SDK in my Ubuntu. I used the same library on the same version of Xilinx SDK on Windows, and it failed with “syntax error” on the libopenblas.so file in the library. It does not give any other information on where the actually error happens! Any ideas on this? Here is the error copied from the SDK and a snapshot is attached!

Description	Resource	Path	Location	Type
syntax error	TestBLAS		line 0, external location: h:\xilinx\sdk\2018.3\gnu\aarch64\nt\aarch64-none\aarch64-none-elf\bin\ld.exe:D:\multipleTarget\multipleTarget\lib\libopenblas.so	C/C++ Problem
![Screen Shot 2020-08-10 at 12 14 59 PM](https://user-images.githubusercontent.com/15149235/89821462-6f7bf180-db03-11ea-9af2-b7bca85def7f.png)

**Comment by martin-frbg** [comment]
Not sure about that, could well be that the linker in the Windows version of the SDK expects some kind of Windows-style library build ? Anyway not much to go by (as you noted yourself), the only visible warning seems to be for initializing your array of doubles with integer values. Can we assume your other issue tickets to be resolved now BTW ?

**Comment by mshadian** [comment]
What do you exactly mean by Widnows-style? Like dlls?

**Comment by martin-frbg** [comment]
Actually I have no idea, perhaps there is something in the Xilinx documentation about this ?

**Comment by brada4** [comment]
Aparently Windows is unable to execute TestBLAS.elf , somehow you need to convince that build system to produce .exe if you want to test something.

**Comment by martin-frbg** [comment]
@brada4 that is a cross-compilation, .elf is probably the correct executable extension for the target platform. As I read it, the linker is unable to build TestBLAS.elf from the helloworld code by linking with libopenblas.

**Comment by brada4** [comment]
What cross-compilation? Error next to Makefile in bottom right box in Eclipse screenshot says it executes that file natively and cannot do so.
Since it got through with OpenBLAS - what do you expect from here? We cannot fix commercial 3rd party SDK. Maybe they already did during last 2 years.

**Comment by martin-frbg** [comment]
Xilinx build for aarch64 was the idea, but maybe you are right and the project is just misconfigured to actually run the executable after it is created.

**Comment by martin-frbg** [comment]
@mshadian did that build attempt create the file "TestBLAS.elf" that is the subject of the error message, and if so, can you run it on the Xilinx board ?

**Comment by brada4** [comment]
@martin-frbg I suspect that is the case. One has to check if produced `file.elf` actually exists, or is named `file.elf.exe` and if it is linux elf format, and basically prepend `-` in front of makefile line to let it proceed after error. It would be a bit harder if some framework generates that makefile.
