### ISSUE TITLE
Can build to x86 or x86_64 with NDK?

### ISSUE THREAD

**Issue by diamondcm** [xianyi/OpenBLAS#2768]
I found target is only armv7 and arm64

Thanks a lot

**Comment by martin-frbg** [comment]
The wiki only describes building for arm and arm64 as these are the most often requested cases, but as far as I know there are
NDK toolchains targeting x86 and x86_64 that can be used in the same way, just with a TARGET like NEHALEM and/or setting DYNAMIC_ARCH=1 to get optimized support for a range of x86 cpus.

**Comment by martin-frbg** [comment]
Rearranged the wiki page to move all the dust and cobwebs to the bottom. Have not yet tried if an x86 NDK build actually works the way I think it should though.

**Comment by martin-frbg** [comment]
Tested an x86 build with the current NDK (r21d) - compile-tested only as I have no Android tablet or similar to run this on.
```
export PATH=/opt/android-ndk-r21d/toolchains/x86-4.9/prebuilt/linux-x86_64/bin:/opt/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
export LDFLAGS="-L/opt/android-ndk-r21d/toolchains/x86-4.9/prebuilt/linux-x86_64/i686-linux-android/lib/"
make TARGET=NEHALEM NOFORTRAN=1 CC=clang HOSTCC=gcc
```

**Comment by martin-frbg** [comment]
Thanks to @lemberh the wiki page just got updated with a new section detailing compilation for ARM and X86
