### ISSUE TITLE
ILP64 SGETRI Parameter Error

### ISSUE THREAD

**Issue by Zha0q1** [xianyi/OpenBLAS#2776]
I have built openblas with these options 
```
CXX="g++ -fPIC" CC="gcc -fPIC" make -j DYNAMIC_ARCH=1 DYNAMIC_OLDER=1 USE_OPENMP=1 INTERFACE64=1 BINARY=64 NO_SHARED=0 NO_LAPACK=0 
```

When I called `sgetri_` I ran into this error
```
** On entry to SGETRI parameter number  3 had an illegal value
```
I then inspected the parameters using GDB:
```
#0  0x00007fff4254a980 in sgetri_ () from /usr/local/lib/libopenblas.so.0
#1  0x00007fff47705e7f in MY_sgetri (matrix_layout=102, n=2, a=0x7ffca4011e80, 
    lda=2, ipiv=0x0, work=0x7fffe267de2c, lwork=-1)
```
```C++
  inline int MY_sgetri(int matrix_layout, int n, dtype *a, int lda, 
                                          int *ipiv, dtype *work, int lwork) { 
    if (matrix_layout == MY_LAPACK_ROW_MAJOR) { 
      CHECK(false) << "MY_sgetri implemented for col-major layout only"; 
      return 1; 
    } else { 
      int info(0); 
      sgetri_(&n, a, &lda, ipiv, work, &lwork, &info); 
      return info; 
    } 
  }
```

I am trying to migrate to using ILP64 OpenBLAS. My program used to work no problem with 32-bit OpenBLAS with the same input. 

This is my own hard-coded function declaration:
```C++
void sgetri_(int *m, int *n, dtype *a, int *lda, int *ipiv, int *info);
```

Any suggestions on what to change? Since I am using ILP64 now should I modify the function declaration?
In `sgetri.c` there is this:
``` C
 /* Subroutine */ int sgetri_(integer *n, real *a, integer *lda, integer *ipiv,
	 real *work, integer *lwork, integer *info)
```
Is `integer` even controlled by these flags `INTERFACE64=1 BINARY=64`? 

Thanks!

**Comment by martin-frbg** [comment]
Waitaminute where does sgetri.c come from ? I do not think this is OpenBLAS or Reference-LAPACK code (unless mangled by something like f2c) Perhaps you could try the LAPACKE interface to sgetri instead of creating your own makeshift interface to the library function, this would let you include lapacke.h in your code (which should take care of the split persona of lapack_int)

**Comment by Zha0q1** [comment]
> Waitaminute where does sgetri.c come from ? I do not think this is OpenBLAS or Reference-LAPACK code (unless mangled by something like f2c) Perhaps you could try the LAPACKE interface to sgetri instead of creating your own makeshift interface to the library function, this would let you include lapacke.h in your code (which should take care of the split persona of lapack_int)

I just googled it. 

<img width="1393" alt="Screen Shot 2020-08-13 at 12 54 09 AM" src="https://user-images.githubusercontent.com/16669457/90108707-9141c800-dcff-11ea-88b3-ed90b7870121.png">

For backward compatibility I sort of need to use this hard-coded interface. I wonder how is `sgetri_` compiled. Knowing that might help getting those parameters properly aligned..

**Comment by martin-frbg** [comment]
Ah ok, the old CLAPACK  - LAPACK from many years ago when it was still old-style fortran77, mangled by the f2c converter. Not sure if it even had the 64bit integer option back then, but the C declaration of the fortran  "integer" should certainly be in one of the accompanying headers - change it to lapack_int (or blasint for that matter) if you want the typedefs from the OpenBLAS headers to work.
