### ISSUE TITLE
f77blas.h: unknown type name `bfloat16`

### ISSUE THREAD

**Issue by siko1056** [xianyi/OpenBLAS#2783]
When compiling OpenBLAS 0.3.10 and include the `f77blas.h` header in my program, I receive the following error.

```
/usr/include/f77blas.h:476:5: error: unknown type name 'bfloat16'
```

This seems related to the change

https://github.com/xianyi/OpenBLAS/commit/7eb55504b1727eebcb0f451fa5b148dbea303b69#diff-7a719af21b4ed2f340e10df2dc8da843R40-R476

followed by this change

https://github.com/xianyi/OpenBLAS/commit/67cc4b9e16d2e8c017731d2b9eabb5c6b45a9ad5#diff-7a719af21b4ed2f340e10df2dc8da843L40-L42

`f77blas.h` is generated from `common_interface.h` and the symbol `bfloat16` is not defined.

Thank you for your time and help.

**Comment by martin-frbg** [comment]
Can you try if adding 
```
#ifndef BFLOAT16
typedef unsigned short bfloat16;
#define HALFCONVERSION 1
#endif
```
to openblas_config.h (which gets included by f77blas.h et al.) solves the problem ?

**Comment by siko1056** [comment]
Yes, thanks, this solves my problem.  I don't know if `#define HALFCONVERSION 1` was necessary.  For my case it is not.

**Comment by martin-frbg** [comment]
Probably not, I just copypasted it from common.h (internal to OpenBLAS), but the other part needs to be added to openblas_config_template.h - I'll do a PR for this later today.

**Comment by siko1056** [comment]
Thanks a lot :+1:
