### ISSUE TITLE
Segfault in zdotc on Windows

### ISSUE THREAD

**Issue by masuday** [xianyi/OpenBLAS#2787]
### Issue
On Windows, OpenBLAS `zdotc` fails with a vector with more than 10000. A detailed condition shows below. This issue was originally reported in Julia (https://github.com/JuliaLang/LinearAlgebra.jl/issues/754).

### Environment

- OpenBLAS v0.3.9 and v0.3.10 (not tried v0.3.8 or earlier)
- MSYS64 on Windows 10
- `GNU Fortran (Rev2, Built by MSYS2 project) 9.2.0`
- `gcc.exe (Rev2, Built by MSYS2 project) 9.2.0`

EDIT: forgot to add the test platform (output of Julia; see above for compiler versions)
```
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-8600 CPU @ 3.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

Build:
```
# env
$ uname
MINGW64_NT-10.0-18363

# quick build on Windows
$ make BINARY=64 CC=gcc FC=gfortran
```

#### Fortran code
```Fortran
program test_zdot
   implicit none
   integer :: n,inc
   complex*16 :: val
   complex*16,allocatable :: zx(:)

   interface
      COMPLEX*16 FUNCTION zdotc(N,ZX,INCX,ZY,INCY)
         INTEGER incx,incy,n
         COMPLEX*16 zx(*),zy(*)
      END FUNCTION zdotc
   end interface

   read(*,*) n
   allocate(zx(n))
   zx(:) = 0.0
   inc = 1
   val = zdotc(n,zx,inc,zx,inc)
   print *,val
end program test_zdot
```

#### Compilation & execution:
```
# compilation
gfortran test_zdot.f90 libopenblas.dll.a
```

#### Tests
```
# okay case
$ ./a.out
10000
               (0.0000000000000000,0.0000000000000000)

# current issue
10001

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0xffffffff
Segmentation fault
```

### Condition

- No segfault with a single thread (`OPENBLAS_NUM_THREADS=1`).
- In Julia (with v0.3.9), `OPENBLAS_CORETYPE=Penryn` worked with any number of threads. In my test, it always failed (I'm not sure whether my build really looks at this option to chooses the Penryn kernel).

**Comment by martin-frbg** [comment]
from the linked issue of the linked issue... this problem does/did not appear with 0.3.5 ? The internal parallelization of the zdot kernel was introduced shortly ~~before~~ *after* the 0.3.7 release, and 10000 happens to be the magic number at which the code switches to parallelization. It is not clear to me why this would fail on Windows specifically, unless num_cpu_avail() returns a bogus value (or the number of cores in your machine is substantially greater than what libopenblas.dll.a was compiled with).
Pity the backtrace is so useless

**Comment by martin-frbg** [comment]
BTW Nehalem kernel should be old enough to not use this apparently problematic code, yet not quite as ancient as Penryn. You would get the chance to select a coretype at runtime only if your libopenblas was compiled with DYNAMIC_ARCH of course - without that option, the library would contain support for the cpu of the system you built on only.

**Comment by masuday** [comment]
thank you for your comment! I have just tested the previous versions:

- v0.3.8: failed
- v0.3.7: ok

```
Backtrace for this error:
#0  0xffffffff
JuliaLang/julia#1  0xffffffff
JuliaLang/julia#2  0xffffffff
JuliaLang/julia#3  0xffffffff
JuliaLang/julia#4  0xffffffff
JuliaLang/julia#5  0xffffffff
JuliaLang/julia#6  0xffffffff
JuliaLang/julia#7  0xffffffff
JuliaLang/julia#8  0xffffffff
JuliaLang/julia#9  0xffffffff
```

Seems like something happened after the 0.3.7 release.

**Comment by martin-frbg** [comment]
Interesting that 0.3.7 would still work - the only change (at least in kernel/x86_64/zdot.c itself) after that was the addition of `#ifdef`'d code for PGI and Sun compilers that did not cope with the CREAL, CIMAG macros.
EDIT: 0.3.7 released on August 11, 2019, zdot.c changed August 15, 2019 so 0.3.7 would be the last "good" version if that change is bad

**Comment by masuday** [comment]
I found the commit: https://github.com/xianyi/OpenBLAS/commit/9ef96b32a6cc9a41908e832f2f713462bb94f40f

git bisect:
```
$ git bisect bad
9ef96b32a6cc9a41908e832f2f713462bb94f40f is the first bad commit
commit 9ef96b32a6cc9a41908e832f2f713462bb94f40f
Author: Martin Kroeker <martin@ruby.chemie.uni-freiburg.de>
Date:   Thu Aug 15 22:09:12 2019 +0200

    Add multithreading support to the x86_64 zdot kernel (#2222)

    * Add multithreading support

    copied from the ThunderX2T99 kernel. For JuliaLang/julia#2221

 kernel/x86_64/zdot.c | 86 +++++++++++++++++++++++++++++++++++++++++++---------
 1 file changed, 72 insertions(+), 14 deletions(-)
```

<del>EDIT: seems like `nthreads = num_cpu_avail(1)` is not working on Windows.</del> I removed it because it is not the point.

**Comment by martin-frbg** [comment]
While the obvious stopgap solution is to disable that code on Windows, I do not think the num_cpu_avail() is the culprit - that call is used throughout the multithreading setup code in `interface/*`. More likely something in the handling of the results pointer is incorrect for Windows. Can you make DDOT crash in the same way (uses much the same code) ?

**Comment by brada4** [comment]
Does it "fix" if N is multiple of cores, or thet multiplied by 2^N

**Comment by martin-frbg** [comment]
Possibly the explanation is simply that 
https://github.com/xianyi/OpenBLAS/blob/75eeb265d7c5715f05b63e8706593ef6d8485627/kernel/x86_64/zdot.c#L172
should have `*result` declared as an OPENBLAS_COMPLEX_FLOAT

**Comment by masuday** [comment]
I just changed `FLOAT *result` to `OPENBLAS_COMPLEX_FLOAT *result`, but it still failed. Perhaps more changes needed?

By the way, `DDOT` works with a big vector.

EDIT:  `OPENBLAS_CORETYPE=Nehalem` works as expected.

**Comment by martin-frbg** [comment]
For some - probably very silly - reason, argument passing is going completely wrong here, and the x and y increments of 1 end up as some absurdly huge number.

**Comment by masuday** [comment]
Thank you for keeping your eyes on this issue. I investigated the code and found a bug particularly in win32. The following function will be called in each thread in `legacy_exec` in `blas_server_win32.c`.

https://github.com/xianyi/OpenBLAS/blob/9ee21a0a39fe5e0ba178b6dce2ba8b71e4dc2dc6/kernel/x86_64/zdot.c#L170-L172

The `legacy_exec` function has the following code.

https://github.com/xianyi/OpenBLAS/blob/9ee21a0a39fe5e0ba178b6dce2ba8b71e4dc2dc6/driver/others/blas_server_win32.c#L133-L143

You can see the mismatch in the number of arguments and their types! As a test, when I added one more FLOAT argument to `zdot_thread_function`, the segfault didn't occur. Probably the above is enough to describe the issue. Could you fix this problem? Just because I don't have much knowledge about the internal of OpenBLAS to make sure it works in any OS. But, of course, I am willing to test the modified code.

**Comment by martin-frbg** [comment]
Yes, thanks, it was basically missing the imaginary part of the scale factor alpha - I was too tired yesterday to complete the bug hunt. Not entirely sure why this did not cause crashes on Linux as well though..

**Comment by masuday** [comment]
I confirmed that it no longer gives segfault on WIndows. Thank you for your help!
