### ISSUE TITLE
undefined reference to `__printf_chk'

### ISSUE THREAD

**Issue by mshadian** [xianyi/OpenBLAS#2793]
I'm having issues linking a project using cross-compiled blas and lapacke libraries. blas works, but when I use lapacke function, I get multiple errors while linking the project. There are many undefined reference errors, some as following. Any ideas to how to fix it? The machine I use for compile/lining is an Ubuntu 18. Thanks!

/home/dev/Desktop/NoThreadNew/lib/libopenblas.a(lapacke_xerbla.o): In function `LAPACKE_xerbla':
lapacke_xerbla.c:(.text+0x28): undefined reference to `__printf_chk' 
/home/dev/Desktop/NoThreadNew/lib/libopenblas.a(iparmq.o): In function `iparmq_':
iparmq.f:(.text+0x68): undefined reference to `logf'
/home/dev/Desktop/NoThreadNew/lib/libopenblas.a(dgemv.o): In function `dgemv_':
gemv.c:(.text+0x370): undefined reference to `__assert_fail'
/home/dev/Desktop/NoThreadNew/lib/libopenblas.a(dtrmv_thread_NUU.o): In function `dtrmv_thread_NUU':
trmv_thread.c:(.text+0x4d4): undefined reference to `sqrt'
/home/dev/Desktop/NoThreadNew/lib/libopenblas.a(dtrmv_thread_NUN.o): In function `dtrmv_thread_NUN':
trmv_thread.c:(.text+0x51c): undefined reference to `sqrt'
/home/dev/Desktop/NoThreadNew/lib/libopenblas.a(dtrmv_thread_NLU.o): In function `dtrmv_thread_NLU':
trmv_thread.c:(.text+0x530): undefined reference to `sqrt'
/home/dev/Desktop/NoThreadNew/lib/libopenblas.a(dtrmv_thread_NLN.o): In function `dtrmv_thread_NLN':
trmv_thread.c:(.text+0x558): undefined reference to `sqrt'
/home/dev/Desktop/NoThreadNew/lib/libopenblas.a(dtrmv_thread_TUU.o): In function `dtrmv_thread_TUU':
trmv_thread.c:(.text+0x440): undefined reference to `sqrt'
/home/dev/Desktop/NoThreadNew/lib/libopenblas.a(dtrmv_thread_TUN.o):trmv_thread.c:(.text+0x4b8): more undefined references to `sqrt' follow
/home/dev/Desktop/NoThreadNew/lib/libopenblas.a(dgemm_thread_nn.o): In function `gemm_driver':
gemm.c:(.text+0x60): undefined reference to `pthread_mutex_lock'
gemm.c:(.text+0x338): undefined reference to `pthread_mutex_unlock'
/home/dev/Desktop/NoThreadNew/lib/libopenblas.a(dgemm_thread_nt.o): In function `gemm_driver':
gemm.c:(.text+0x60): undefined reference to `pthread_mutex_lock'
gemm.c:(.text+0x338): undefined reference to `pthread_mutex_unlock'
/home/dev/Desktop/NoThreadNew/lib/libopenblas.a(dgemm_thread_tn.o): In function `gemm_driver':
gemm.c:(.text+0x60): undefined reference to `pthread_mutex_lock'
gemm.c:(.text+0x338): undefined reference to `pthread_mutex_unlock'
/home/dev/Desktop/NoThreadNew/lib/libopenblas.a(dgemm_thread_tt.o): In function `gemm_driver':
gemm.c:(.text+0x60): undefined reference to `pthread_mutex_lock'
gemm.c:(.text+0x338): undefined reference to `pthread_mutex_unlock'
/home/dev/Desktop/NoThreadNew/lib/libopenblas.a(memory.o): In function `alloc_mmap':
memory.c:(.text+0x94): undefined reference to `mmap'
memory.c:(.text+0xc0): undefined reference to `pthread_mutex_lock'
memory.c:(.text+0xf4): undefined reference to `pthread_mutex_unlock'
memory.c:(.text+0x11c): undefined reference to `syscall'
memory.c:(.text+0x13c): undefined reference to `mmap'
/home/dev/Desktop/NoThreadNew/lib/libopenblas.a(memory.o): In function `alloc_mmap_free':
memory.c:(.text+0x168): undefined reference to `munmap'
memory.c:(.text+0x180): undefined reference to `__errno_location'
memory.c:(.text+0x1b4): undefined reference to `__printf_chk'
/home/dev/Desktop/NoThreadNew/lib/libopenblas.a(memory.o): In function `get_num_procs':
memory.c:(.text+0x208): undefined reference to `__sched_cpualloc'
memory.c:(.text+0x22c): undefined reference to `sched_getaffinity'
memory.c:(.text+0x23c): undefined reference to `__sched_cpucount'
memory.c:(.text+0x25c): undefined reference to `__sched_cpufree'
memory.c:(.text+0x29c): undefined reference to `sched_getaffinity'
memory.c:(.text+0x2ac): undefined reference to `__sched_cpucount'
memory.c:(.text+0x2d8): undefined reference to `sysconf'
/home/dev/Desktop/NoThreadNew/lib/libopenblas.a(memory.o): In function `openblas_fork_handler':
memory.c:(.text+0x318): undefined reference to `pthread_atfork'
/home/dev/Desktop/NoThreadNew/lib/libopenblas.a(memory.o): In function `blas_memory_alloc':
memory.c:(.text+0x4a8): undefined reference to `pthread_mutex_lock'
memory.c:(.text+0x4e0): undefined reference to `pthread_mutex_unlock'
memory.c:(.text+0x4e8): undefined reference to `pthread_mutex_lock'
memory.c:(.text+0x528): undefined reference to `pthread_mutex_unlock'
memory.c:(.text+0x5c8): undefined reference to `pthread_mutex_lock'
memory.c:(.text+0x5d4): undefined reference to `pthread_mutex_unlock'
memory.c:(.text+0x5fc): undefined reference to `pthread_mutex_unlock'
/home/dev/Desktop/NoThreadNew/lib/libopenblas.a(memory.o): In function `blas_memory_free':
memory.c:(.text+0x640): undefined reference to `pthread_mutex_lock'
memory.c:(.text+0x698): undefined reference to `__printf_chk'
memory.c:(.text+0x6ac): undefined reference to `pthread_mutex_unlock'
memory.c:(.text+0x6c8): undefined reference to `pthread_mutex_unlock'
/home/dev/Desktop/NoThreadNew/lib/libopenblas.a(memory.o): In function `blas_shutdown':
memory.c:(.text+0x710): undefined reference to `pthread_mutex_lock'
memory.c:(.text+0x798): undefined reference to `pthread_mutex_unlock'
/home/dev/Desktop/NoThreadNew/lib/libopenblas.a(xerbla.o): In function `xerbla_':
xerbla.c:(.text+0x1c): undefined reference to `__printf_chk'
/home/dev/Desktop/NoThreadNew/lib/libopenblas.a(openblas_error_handle.o): In function `openblas_warning':
openblas_error_handle.c:(.text+0x2c): undefined reference to `stderr'
openblas_error_handle.c:(.text+0x38): undefined reference to `stderr'
/home/dev/Desktop/NoThreadNew/lib/libopenblas.a(blas_server.o): In function `blas_thread_server':
blas_server.c:(.text+0x204): undefined reference to `pthread_mutex_lock'
blas_server.c:(.text+0x21c): undefined reference to `pthread_cond_wait'
blas_server.c:(.text+0x240): undefined reference to `pthread_mutex_unlock'

**Comment by martin-frbg** [comment]
The sqrt and logf are libm, anything with pthread in it is libpthread (which may be a bit suspicious given the "NoThreadNew" in your path name, maybe you mis-spelled an option ?) , stderr, malloc, printf_chk and assert sound like libc. No idea why this would happen only with LAPACKE and not BLAS functions as well,given that both are written in C. Maybe this was not actually cross-compiled, or you have a mismatch between 32 and 64 bit libraries ?

**Comment by mshadian** [comment]
I cross-compiled again using 
make CC=aarch64-linux-gnu-gcc FC=aarch64-linux-gnu-gfortran HOSTCC=gcc TARGET=ARMV8 BINARY=64 NUM_THREADS=1

and the pthread errors seems to be gone for now. Can you please tell me where do I get the libm and libc that works for aarch64? I'm using Ubuntu 18.

About not having issues with blas and not working with lapacke, I initially compiled with NOFORTRAN key, and only used the cblas functions. For lapacke I needed to compile again with the fortran option enabled, so all these errors started to show up.

**Comment by martin-frbg** [comment]
What OS is your aarch64 target using ? "Normally" I'd expect it to have a libc and libm if it is anything linux-like - if it does not, perhaps you are using the wrong cross-compiler ? (Or perhaps your cross-compiler is newer than the OS on your aarch64 system, so that library versions do not match - even with your LAPACKE problem, I would understand if you met problems with  missing fortran functions from libgfortran, but all the C functions needed should be the same as for your BLAS-only build)

**Comment by mshadian** [comment]
I included the libm and libc from "/usr/aarch64-linux-gnu/lib", and now I'm getting these new errors, any ideas?

./../BLAStest_bsp/psu_cortexa53_0/lib/libxil.a(xil-crt0.o): In function `_startup':
/home/dev/workspace/XSDK/BLAStest_bsp/psu_cortexa53_0/libsrc/standalone_v6_8/src/xil-crt0.S:114: undefined reference to `__libc_init_array'
/home/dev/workspace/XSDK/BLAStest_bsp/psu_cortexa53_0/libsrc/standalone_v6_8/src/xil-crt0.S:132: undefined reference to `__libc_fini_array'

**Comment by mshadian** [comment]
Here is the full command line:

make all 
Building target: BLAStest.elf
Invoking: ARM v8 gcc linker
aarch64-none-elf-gcc -L/home/dev/Desktop/NumThread1/lib -L/usr/aarch64-linux-gnu/lib -N -fstack-protector -Wl,-T -Wl,../src/lscript.ld -L../../BLAStest_bsp/psu_cortexa53_0/lib -o "BLAStest.elf"  ./src/helloworld.o ./src/platform.o   -lopenblas -lc -lm -Wl,--start-group,-lxil,-lgcc,-lc,--end-group -Wl,--start-group,-lxil,-lmetal,-lgcc,-lc,--end-group
/home/dev/XDK/SDK/2018.3/gnu/aarch64/lin/aarch64-none/bin/../aarch64-none-elf/libc/usr/lib/crt0.o: In function `_start':
/proj/esdt_sdk/gnu_abe/ABE/builds/lin/arm/arm-linux/snapshots/newlib-newlib-2_4_0/libgloss/aarch64/crt0.S:156: undefined reference to `__libc_init_array'
makefile:36: recipe for target 'BLAStest.elf' failed
/home/dev/XDK/SDK/2018.3/gnu/aarch64/lin/aarch64-none/bin/../aarch64-none-elf/libc/usr/lib/crt0.o: In function `_cpu_init_hook':
/proj/esdt_sdk/gnu_abe/ABE/builds/lin/arm/arm-linux/snapshots/newlib-newlib-2_4_0/libgloss/aarch64/crt0.S:228: undefined reference to `__libc_fini_array'
../../BLAStest_bsp/psu_cortexa53_0/lib/libxil.a(xil-crt0.o): In function `_startup':
/home/dev/workspace/XSDK/BLAStest_bsp/psu_cortexa53_0/libsrc/standalone_v6_8/src/xil-crt0.S:114: undefined reference to `__libc_init_array'
/home/dev/workspace/XSDK/BLAStest_bsp/psu_cortexa53_0/libsrc/standalone_v6_8/src/xil-crt0.S:132: undefined reference to `__libc_fini_array'
collect2: error: ld returned 1 exit status
make: *** [BLAStest.elf] Error 1

**Comment by martin-frbg** [comment]
No clear idea, sorry. Could it be that your cross-compiler is newer than the operating system (and libraries) on your target ?

**Comment by brada4** [comment]
You need library files from target SDK/BSP. Sometimes, like bionic on android or iOS libc, libpthread and libm are integrated in libc, so you might need to put empty files or symlinks to libc.so in lib directory.
`crt0.S:228: undefined reference to __libc_fini_array'` - probably means that you need to run some SDK start script. crt0 aka C runtime header cannot be linked to libc aka C library.
