### ISSUE TITLE
dsysv slower than dgesv?

### ISSUE THREAD

**Issue by theinlinaung2010** [xianyi/OpenBLAS#2800]
I was trying to benchmark netlib Lapack and OpenBlas for `dgesv` and `dsysv` routines. I found that dsysv in OpenBlas was slower than dgesv although common sense tells me the opposite.

Here are the test results for my machine (Intel Core i7-8750H 12 logical cores, 16GB ram).

 ### Computation time (seconds)
n |  | Lapack  |  |  | OpenBlas |  |
-- | -- | -- | -- | -- | -- | -- |
**n**  | **matmul** | **dgesv** | **dsysv** | **matmul** | **dgesv** | **dsysv**
1000 | 0 | 0.188 | 0.094 | 0 | 0.05 | 0.11
5000 | 0.045 | 22.5 | 11.453 | 0.047 | 0.657 | 2.609
10000 | 0.203 | 183.344 | 90.844 | 0.218 | 4.75 | 10.469
15000 | 0.469 | 654.25 | 310.781 | 0.203 | 4.61 | 11.781
20000 | 0.953 | 1723.906 | 745.906 | 0.875 | 39.094 | 55.954

Fortran code used in the test 
https://drive.google.com/file/d/1osjyTTt6Wq0QJ2qtJPIiMY7WI_GcS_1G/view?usp=sharing

### Versions
Lapack 3.9.0, compiled from http://www.netlib.org/lapack/#_lapack_version_3_9_0_2
OpenBlas 0.3.10, compiled with default parameters from https://sourceforge.net/projects/openblas/files/v0.3.10/
Compiler - GNU  Fortran (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0

I could see both dgesv and dsysv were using multiple cores.

**Comment by martin-frbg** [comment]
Without having run perf on the code in question, this could simply be due to getrf/getf2 being replaced by an optimized, multithreaded reimplementation in OpenBLAS while dsysv goes through standard netlib ssytrf/ssysv.

**Comment by theinlinaung2010** [comment]
That is strange because I could see CPU usage was almost 100% during dsysv call.

**Comment by martin-frbg** [comment]
Closing as my initial assessment appears to be correct - when running single-threaded, dsysv wins, but in multithreaded builds dgesv is faster due to the parallelized getrf
