### ISSUE TITLE
link error when use blas arm64-v8a

### ISSUE THREAD

**Issue by crazy0126** [xianyi/OpenBLAS#2810]
use the following commands to compile OpenBLas:

export PATH=/home/stone/codes/Changba/thirdparty/tools/aarch64-linux-android-4.9/bin:$PATH
make TARGET=ARMV8 BINARY=64 HOSTCC=gcc CC=aarch64-linux-android-gcc FC=aarch64-linux-android-gfortran  CFLAGS=--sysroot=/home/stone/codes/Changba/thirdparty/tools/aarch64-linux-android-4.9/r13b_sysroot libs

Error:
cblas-wrappers.h:493: undefined reference to `sgetri_'
cblas-wrappers.h:506: undefined reference to `sgesvd_'

**Comment by martin-frbg** [comment]
Not sure what cblas_wrappers.h belongs to, but the two "missing" LAPACK functions should be in libopenblas if you did not get any errors during its compilation. Probably you got only a partial compile as you specified the "libs" target instead of doing a full build.

**Comment by crazy0126** [comment]
@martin-frbg    cblas_wrapper.h is just a function  to invoke blas api, yes I used  libs target. I just tried to specified the "all" target, and it worked enven though there was an compile error at the end .

r: `u' modifier ignored since `D' is the default (see `U')
aarch64-linux-android-ranlib ../../../libopenblas_armv8p-r0.3.10.dev.a
make[3]: Leaving directory '/home/stone/codes/Changba/thirdparty/OpenBLAS/lapack-netlib/LAPACKE/utils'
make[2]: Leaving directory '/home/stone/codes/Changba/thirdparty/OpenBLAS/lapack-netlib/LAPACKE'
make[1]: Leaving directory '/home/stone/codes/Changba/thirdparty/OpenBLAS/lapack-netlib'
touch libopenblas_armv8p-r0.3.10.dev.a
make -j 4 -C test all
make[1]: *** test: No such file or directory.  Stop.
Makefile:139: recipe for target 'tests' failed
make: *** [tests] Error 2


@martin-frbg  I really apprreciate it.

**Comment by martin-frbg** [comment]
Strange that the build system apparently tried to execute the tests on the build host although it should have detected you were cross-compiling - guess I need to check that this did not get broken by recent additions. But the static libopenblas.a should be complete at that point, and you will probably not need the dynamic .so (that would be created after successful tests) on Android
