### ISSUE TITLE
Installing from pre-compiled packages: Where to find libopenblas.dll?

### ISSUE THREAD

**Issue by ekdnam** [xianyi/OpenBLAS#2827]
Hallo. I am trying to installing OpenBLAS from [here](https://sourceforge.net/projects/openblas/files/). Referring [this](https://github.com/apache/incubator-mxnet/issues/19048), how to get `libopenblas.dll`? Earlier (https://github.com/xianyi/OpenBLAS/issues/2806), after what seemed like a successful build of OpenBLAS,`libopenblas.dll` was not generated. Was the prior build incomplete?

**Comment by ekdnam** [comment]
Probably the solution to this is: 
> If you would rather have a DLL, add -DBUILD_SHARED_LIBS=ON above.

from [here](https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-in-Microsoft-Visual-Studio)

**Comment by martin-frbg** [comment]
Yes. And the prebuilt zips on sf.net have the dll in "bin" (actually no idea why it is placed there rather than in "lib", I am just following the layout that xianyi used for the packages he built in earlier years). You can find the prebuilt 0.3.10 on github in the "releases" link for now.

**Comment by ekdnam** [comment]
I cannot find the .dll in "bin" in the prebuilt zips, after unzipping them. (There is no bin directory as a matter of fact) Are you using this link? [sourceforge.net](https://sourceforge.net/projects/openblas/)

**Comment by martin-frbg** [comment]
Hmm, guess you are looking at the recent source zips on sf.net ? Pretty sure I pushed binary packages for 0.3.7...0.3.9 as well, but indeed the latest I see there is in/of 0.3.6. (I do not have direct write access to the sf.net account). Anyway you can find the
x86_64 windows build here https://github.com/xianyi/OpenBLAS/releases/download/v0.3.10/OpenBLAS-0.3.10-x64.zip

**Comment by ekdnam** [comment]
Okay I got it from the link! Danke Martin!

**Comment by isuruf** [comment]
> actually no idea why it is placed there rather than in "lib"

That's because DLLs in windows are found in `PATH` environment variable just like executables and `PATH` usually has the `bin` directories instead of `lib`.

**Comment by arypramudito** [comment]
Waiting for binary  OpenBLAS-0.3.11-x64.zip

**Comment by martin-frbg** [comment]
Have a life, sometimes even need to sleep

**Comment by arypramudito** [comment]
Thank you Martin for supporting openblas. The newest sf has binary 0.2.19. Thank you for mentioning precompiled 0.3.10 above. 
Is there any precompiled with msvc abi. The precompiled  mingw64 version is ran well with Intel Fortran windows.
I have difficulties linking the my own msvc abi library version (external symbol dgtri not found) , and build the mingw64 library version on msys64 windows for a year.

**Comment by martin-frbg** [comment]
Windows 64bit binary package now on the github release page at https://github.com/xianyi/OpenBLAS/releases/download/v0.3.11/OpenBLAS-0.3.11-x64.zip
Will create the 32bit package later and regenerate the missing binaries for xianyi to upload to sf.net later (though pretty sure sf should have something like 0.3.5 at least)

**Comment by martin-frbg** [comment]
Unfortunately the 0.3.11 release had a number of stupid bugs, e.g. the Windows binary is missing all double precision complex functions in the dll. Will update this tomorrow
