### ISSUE TITLE
openBLAS with MSVC - utest\openblas_utest.exe failing to link

### ISSUE THREAD

**Issue by thomassligon** [xianyi/OpenBLAS#2830]
I am now able to download and compile openBLAS using MSVC and cmake, and the result is doing what is needed. However, one  small thing is left: utest\openblas_utest.exe failing to link. Since I don't need utest, I could ignore the error, but I would prefer to fix it.

[out-2020-09-11.txt](https://github.com/xianyi/OpenBLAS/files/5207512/out-2020-09-11.txt)
[installOpenBLAS.ps1.txt](https://github.com/xianyi/OpenBLAS/files/5207517/installOpenBLAS.ps1.txt)
[compileBLAS.cmd.txt](https://github.com/xianyi/OpenBLAS/files/5207518/compileBLAS.cmd.txt)

**Comment by martin-frbg** [comment]
Do the executables in `test` and `ctest` get built ? (Same `target_link_libraries` line in their CMakeFile)

**Comment by thomassligon** [comment]
If I understand correctly, the answer is no. On searching the directory, I can see 3 `*.exe`:
```
getarch.exe
etarch_2nd.exe
CMakeCCompilerId.exe
```
and one `*.dll`:
`openblas.dll.`
Checking to see if sources were compiled, the first `.c` in `utest` is `test_amax.c` and I can find `test_amax.c.obj` in `utest/CMakeFiles/openblas_utest.dir`. But `ctest` contains e.g. `c_sblas1.c` and I can't find a `.obj` for it. `utest` contains a subdirectory `CMakeFiles`, but `ctest` and `test` have no subdirectories.

**Comment by martin-frbg** [comment]
Ah, silly me, you won't get a build of test and ctest with MSVC anyway as both would require a Fortran compiler. So these cannot be taken as a reference for the utest CMakefile. (I see it has lib/Release/~~lib~~openblas.lib on the linker commandline, so at least it is trying to do the right thing - wonder if that should have been specified relative to the current path)

**Comment by thomassligon** [comment]
I see openblas.lib in the link command, but not libopenblas.lib. There is a file lib/Release/openblas.lib. Getting the wrong path sounds like a plausible explanation, but where does that need to be changed?

**Comment by martin-frbg** [comment]
in utest/CMakeLists.txt, something like 
`target_link_libraries(${OpenBLAS_utest_bin}  ${CMAKE_BINARY_DIR}/${OpenBLAS_LIBNAME})`
where it currently has
`target_link_libraries(${OpenBLAS_utest_bin} ${OpenBLAS_LIBNAME})`

**Comment by martin-frbg** [comment]
Hm, when I just use `cmake` without the `-G "Ninja"`, it builds and links openblas_utest.exe just fine, no matter if I have BUILD_SHARED_LIBS set or not. (With Ninja, my build breaks early due to a missing rc.exe, seems I may need to repair my installation of VS). Not sure what should be the recommended method, but presumably the conda/ninja route is primarily required for using flang (?)

**Comment by martin-frbg** [comment]
It appears to be the `-DBUILD_DOUBLE=1` that is causing the failure (which kind of makes sense as it is only "non-double" fuctions that are missed). Did you actually intend to build an OpenBLAS that has only the double precision functions ? (Not actually supported right now - the individual BUILD_ options are there from Reference-LAPACK but not guaranteed to be handled in the other parts - #2588. A `dumpbin /exports libopenblas.dll` suggests it is "mostly" correct with a few stray real and complex16 functions added to the mix but I did not check in detail for anything missing)

**Comment by thomassligon** [comment]
Oh, I should have mentioned that. Originally, I got an installation of OpenBLAS (which compiled over 2000 C files) working, and submitted it to [https://github.com/AMICI-dev/AMICI](https://github.com/AMICI-dev/AMICI). After accepting the push request, Daniel made some improvements. Since AMICI only uses double precision, he added the `-DBUILD_DOUBLE=1` piece, greatly reducing the number of compilations required, but overlooked the failure to link utest. That was actually working and looked fine in Travis. Then in order to run `pip install amici` locally, I needed to install OpenBLAS locally, and that's when I found the failure to link utest.
So yes, we actually intend to build OpenBLAS that has only the double precision features.
Is there any way we can suppress the creation/linking of utest, in order to avoid the failure? Something like "noTest"?

**Comment by martin-frbg** [comment]
No such option unfortunately, tests are only suppressed when cross-compiling. Will try to look into ifdef'ing the various parts of utest.

**Comment by thomassligon** [comment]
I can confirm that the path was not the cause. As you said afterwards, it is the "non-double" functions.
In case it helps, my installation documentation is here [http://amici-dev.github.io/AMICI/md__i_n_s_t_a_l_l.html](http://amici-dev.github.io/AMICI/md__i_n_s_t_a_l_l.html). I need to update it to say that line 3 of `compileBLAS.cmd` may need changing to match your version of Visual Studio, and also change the environment variables to use double backslashes. You can see that I already used dumpbin to check all dependencies, and listed them in the instructions. I personally think that the `api-ms-win....dll` files (Windows Universal C Runtime) should not be necessary in a pure Windows 10 environment and are an artifact of python setuptools, but that's OK.
