### ISSUE TITLE
Issues with gfortran on Mac OSX Mojave 10.14.5

### ISSUE THREAD

**Issue by stefanozampini** [xianyi/OpenBLAS#2831]
I have tried with `v0.3.10` and `develop` and `gfortran` (as built via HomeBrew) is not recognized properly on my Mac OSX Mojave 10.14.5 . I use MPI compiler wrappers, since this is automatic compilation from PETSc https://gitlab.com/petsc/petsc.

```
kl-18448:git.openblas szampini$ make CC=mpicc FC=mpif90  TARGET=GENERIC MAKE_NB_JOBS=10  USE_OPENMP=0  USE_THREAD=0  NO_EXPRECISION=1
OpenBLAS: Detecting fortran compiler failed. Cannot compile LAPACK. Only compile BLAS
```
This is the output of f_test.s. 

```
        .text
        .p2align 4
        .globl _zhoge_
_zhoge_:
LFB0:
        pxor    %xmm1, %xmm1
        movapd  %xmm1, %xmm0
        ret
LFE0:
        .section __TEXT,__eh_frame,coalesced,no_toc+strip_static_syms+live_support
EH_frame1:
        .set L$set$0,LECIE1-LSCIE1
        .long L$set$0
LSCIE1:
        .long   0
        .byte   0x1
        .ascii "zR\0"
        .byte   0x1
        .byte   0x78
        .byte   0x10
        .byte   0x1
        .byte   0x10
        .byte   0xc
        .byte   0x7
        .byte   0x8
        .byte   0x90
        .byte   0x1
        .align 3
LECIE1:
LSFDE1:
        .set L$set$1,LEFDE1-LASFDE1
        .long L$set$1
LASFDE1:
        .long   LASFDE1-EH_frame1
        .quad   LFB0-.
        .set L$set$2,LFE0-LFB0
        .quad L$set$2
        .byte   0
        .align 3
LEFDE1:
        .ident  "GCC: (Homebrew GCC 10.2.0) 10.2.0"
        .subsections_via_symbols
```

I have fixed it with the patch below. Clearly it is not perfect, can you please fix OpenBLAS properly?

```
kl-18448:git.openblas szampini$ git diff
diff --git a/f_check b/f_check
index dd4d3475..7069b393 100644
--- a/f_check
+++ b/f_check
@@ -69,7 +69,7 @@ if ($compiler eq "") {
            $bu       = "_";
        }
 
-       if ($data =~ /GNU/) {
+       if ($data =~ /GCC/) {
 
            $data =~ /(\d+)\.(\d+).(\d+)/;
            $major = $1;
```

**Comment by martin-frbg** [comment]
Proper fix is probably to accept both, wonder when/why Homebrew made this change though (my guess would be "recent" and perhaps because theirs is based on a pre-release snapshot and/or heavily patched ?)

**Comment by stefanozampini** [comment]
Not sure if this is homebrew related or it is a "feature" of the latest GCC. Accepting both is a fix. On a linux machine with GCC 9.1.1

```
.LFE0:
        .size   zhoge_, .-zhoge_
        .ident  "GCC: (GNU) 9.1.1 20190503 (Red Hat 9.1.1-1)"
        .section        .note.GNU-stack,"",@progbits
```

**Comment by martin-frbg** [comment]
Yes, this looks to be a (recent - at least not reported earlier) Homebrew specialty.

**Comment by brada4** [comment]
Not just homebrew (but somehow it builds everywhere)
```
.ident "GCC: (GNU) 4.4.7 20120313 (Red Hat 4.4.7-23)" // CentOS 6
.ident "GCC: (GNU) 9.1.1 20190605 (Red Hat 9.1.1-2)" // CentOS6 + Devtoolset9
.ident "GCC: (GNU) 8.3.1 20191121 (Red Hat 8.3.1-5)" // CentOS8 Stream
.ident "GCC: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609"
.ident "GCC: (SUSE Linux) 7.5.0"
```

**Comment by martin-frbg** [comment]
Think I understand what happened - there is a fallback in place that gets triggered when none of the "vendor" checks scored a hit, but it tries to match the compiler name against a list that does have `gfortran` but not `mpif90` (or any other mpi driver variant)

**Comment by brada4** [comment]
But those are not guaranteed to wrap gfortran in any way, `s/GNU/GCC:/1` looks like correct approach to support mpif90 outside redhat.

**Comment by martin-frbg** [comment]
Certainly. I was only adding the explanation for why the current code "mostly" kept doing the right thing despite the name change.
