### ISSUE TITLE
Unrelated merge broke DYNAMIC_ARCH on ZARCH

### ISSUE THREAD

**Issue by ghost** [xianyi/OpenBLAS#2842]
The merge of unrelated commit ba644378dce7 ("Copy BUILD_ options available to the compiler flags") inadvertently reverted a subset of my PR #2829. As a result, DYNAMIC_ARCH is broken on ZARCH: the code always defers to the "generic", non-vectorized code paths, no matter the architecture generation it is running on.

Since our current test suite does not cover the detection mechanisms in DYNAMIC_ARCH, this problem slipped through the CI, and could have manifested undetected for any other architecture as well.

I believe we should have tests that cover these mechanisms in our regular test suite and CI. Ideally, these tests will eventually cover all architectures.

**Comment by martin-frbg** [comment]
Ouch, sorry about that. The Travis job for s390x already has DYNAMIC_ARCH set, it is unfortunate that in this case the build still succeeded with a less than satisfactory artifact.
