### ISSUE TITLE
Flag about -DNO_AVX512

### ISSUE THREAD

**Issue by nervermore2** [xianyi/OpenBLAS#2848]
I'm wondering what does DNO_AVX512 means? In my AMD machine, grepping cpuinfo, I can only see avxfp16 and avx2, didn't see AVX512. However, while compiling, this option shows up.
```
cc -O2 -DMAX_STACK_ALLOC=2048 -DUSE_LOCKING -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DNO_LAPACK -DNO_LAPACKE -DNO_AVX512 -DNO_WARMUP -DMAX_CPU_NUMBER=120 -DMAX_PARALLEL_NUMBER=1 -DVERSION=\"0.3.10\" -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  -w -o linktest linktest.c ../libopenblas_zen-r0.3.10.so  && echo OK.
...
 OpenBLAS build complete. (BLAS CBLAS)

  OS               ... Linux             

  Architecture     ... x86_64               

  BINARY           ... 64bit                 

  C compiler       ... GCC  (cmd & version : cc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609)

  Library Name     ... libopenblas_zen-r0.3.10.a (Single-threading)  
```
My interpretation about this flag means we don't know about AVX512, I just wanna confirm.
Thanks

**Comment by nervermore2** [comment]
In my other Ubuntu machines with gcc 5.4, since gcc version below 6 will make OpenBLAS doesn't recognize AVX512, I'm wondering what's the default avx for OpenBLAS.

**Comment by martin-frbg** [comment]
AVX512 is a set of vector registers and instructions that are only available in newer Intel processors. When the NO_AVX512 flag gets set automatically in the build system, it means that your compiler is too old to support these instructions no matter what cpu you have. If you are building for Ryzen, you can ignore this.

**Comment by brada4** [comment]
NO_AVX512 flag works just like smaller brothers, but it is not documented in Makefile.rule, as Martin said, it is (well believed) to be handled automatically based on compiler. 
This flag just means if SKYLAKEX cordes are ever built in case of modern compiler or explicitly replaced by AVX2 haswell code in case compiler works well.
Would be much easier to migrate to Ubuntu 18 or 20 (Or Debian 10) if you have any skylake with avx512 in sight. I can tell for certain experience  you need HWE-1604 kernel to have KVM working on real AVX-512 CPU.... Did not test OpenBLAS on pure hardware with 4.4 kernel.
