### ISSUE TITLE
install openBLAS by vcpkg is not complete

### ISSUE THREAD

**Issue by LiuPeiqiCN** [xianyi/OpenBLAS#2855]
I can't find LAPACK if I use vcpkg to install OpenBLAS.

**Comment by martin-frbg** [comment]
This is a problem of vcpkg not OpenBLAS - as far as I know, vcpkg still uses plain Visual Studio for compiling, which does not have a Fortran compiler for building LAPACK. (Also plain VS builds are not optimized, as Visual Studio does not support the assembly functions used in most cpu-specific implementations of the BLAS functions)

**Comment by martin-frbg** [comment]
See also #2256 please
