### ISSUE TITLE
'make clean' cannot clean up some stuff created by 'make NOFORTRAN=1'

### ISSUE THREAD

**Issue by docularxu** [xianyi/OpenBLAS#2856]
Hi, 

I am posting for suggestions / clues for a weird issue I met when building with NOFORTRAN=1. What I found is:

1. run 'make TARGET=<my.customized> NOFORTRAN=1', it can succeed.
2. run 'make clean', it can succeed.
3. run 'make TARGET=<my.customized>', here I run into a make error saying " No rule to make target 'generic/laswp_ncopy_12.c". See Reference below for complete make failure logs.

But, if I 'git clone' all my code again, start fresh, never run 'make NOFORTRAN=1', then my  'make TARGET=<my.customized>' can succeed, and BLAS APIs tests can pass. So you see the weirdness. It leads to me to believe that 'make clean' doesn't do his job. Some stuff was left there somewhere.

Do you have any suggestion about where I should look into to find the possible cause? Who is using API 'laswp_ncopy_...'? why it relates to NOFORTRAN? I know the number _12 comes from the DGEMM_DEFAULT_UNROLL_M ( = 12) which I set for my customized TARGET.

Reference:

make[1]: *** No rule to make target 'generic/laswp_ncopy_12.c', needed by 'slaswp_ncopy.o'.  Stop.
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/docularxu/OpenBLAS/kernel'
Makefile:149: recipe for target 'libs' failed
make: *** [libs] Error 1

**Comment by martin-frbg** [comment]
LASWP is a LAPACK function (that OpenBLAS reimplements), this is why it is only built when FORTRAN is available as the majority of the LAPACK code in OpenBLAS is a direct copy of the "netlib" reference implementation (which is written in FORTRAN).
This looks like a flaw in the Makefiles, probably the `make clean` will work if you run it as `make NOFORTRAN=1 clean` but this is certainly not ideal (or intended).

**Comment by martin-frbg** [comment]
BTW I cannot reproduce this problem with the limited information you provided, what TARGET did you specify and did you use any other options ? (If there was to be "complete make failure logs" attached to your message they unfortunately did not make it to the site.

**Comment by martin-frbg** [comment]
If you are _adding_ your own TARGET, the relevant Makefile for your problem would be kernel/Makefile.LA (which gets included by kernel/Makefile). The NO_LAPACK conditional used in that file is set automatically when NOFORTRAN was defined (or no suitable compiler was found). Does your addition contain the file kernel/generic/laswp_ncopy_12.c - I do not think we carry a version for this unroll value yet ? This could be a genuine failure in the `make` step, rather than the `make clean` (though I cannot guess why you would not get the same error message when building a fresh checkout) ?

**Comment by docularxu** [comment]
Thanks @martin-frbg . You reminded me of the fact that I installed 'gfortran' in between. And after a second testing, I noticed my original description is not accurate. Sorry about that. With 'gfortran' in mind, here is how the problem can be reproduced. 

The customized TARGET I am using is based on ARM64. Source code is [here](https://github.com/docularxu/OpenBLAS/commits/working_sve256_16x4).

1. In the beginning, there is no gfortran in my Arm64 ubuntu box. I 'git clone' & 'checkout', then I run this make command, and it can succeed:
 `make clean; make TARGET=TSV110SVE USE_THREAD=0 V=1 -j8`
2. Then, I installed gfortran:
`sudo apt-get install gfortran`
3. Then, if I run the same make command again, it fails.
`make clean; make TARGET=TSV110SVE USE_THREAD=0 V=1 -j8`
Failure log:
`make[1]: *** No rule to make target 'generic/laswp_ncopy_12.c', needed by 'slaswp_ncopy.o'.  Stop.
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/docularxu/2OpenBLAS.git/kernel'
Makefile:149: recipe for target 'libs' failed
make: *** [libs] Error 1
`

**Comment by docularxu** [comment]
> The NO_LAPACK conditional used in that file is set automatically when NOFORTRAN was defined (or no suitable compiler was found).

Now that makes complete sense. Thank you @martin-frbg . You saved my day.
The unroll number 12 is a new one which I implemented for GEMM/TRMM (and related kernels like ncopy etc.). But clearly, now I know we are still missing these kernels in kernel/Makefile.LA if (and only if) I want LAPACK support.

**Comment by martin-frbg** [comment]
I guess this should be fairly easy to implement, as it is just a copy/swap operation and there are already examples for unroll values of 1/2/4/8 ( I am a bit intrigued by the non-power-of-2 number but that only shows my ignorance I guess)

**Comment by docularxu** [comment]
Not at all. You are welcome. It will be my pleasure if you can give us any comments for our premature design.

We chose 12 because we want to achieve higher 'flops/memops' performance on arm64 SVE-256 machines. Arm SVE [1] provides 32 vector registers (named z0~z31), and with SVE-256 (one implementation of SVE) each register has 256 bits in length, and can hold 4 doubles.

[In DGEMM/DTRMM](https://github.com/docularxu/OpenBLAS/commit/326ffea871c1fcbc2ba65f90b39433894a978a7e), we compared micro-kernel `(mr*nr) 8*8, 16*4, and 12*8`. `12*8` gives the highest 'flops/memops' score. With mr=12, nr=8, 24 vector registers is allocated for matrix C [2], 4 vectors for matrix B (only half space of these 4 vectors is used, due to assembly instruction efficiency reasons [3]), 3 vectors for matrix A, and 1 vector is free and used in loop unrolling.

I know this is a static comparison, and actual performance will be impacted greatly by other factors, such as L1/L2 cache sizes, pipelines, prefetch, etc. But anyway, so far, based on what we know, we want to give 12 a try and let the future tests tell us whether this is sane.

[In SGEMM/STRMM](https://github.com/docularxu/OpenBLAS/commit/2bcfc38c4d50c61ef15d3ebf3d80d60a6ce90f29), micro-kernel size 16*12 is the highest.

[1] Arm SVE [Introduction](https://developer.arm.com/tools-and-software/server-and-hpc/compile/arm-instruction-emulator/resources/tutorials/sve). 

[2] Vector Registers allocation for DGEMM/DTRMM
- z8 ~ z31  : c
- z0 ~ z2   : a
- z4 ~ z7   : b
- z3        : free, used in loop unrolling

[3] [arm64 sve: ld1rqd and fmul 'indexed' instructions are used.](https://github.com/docularxu/OpenBLAS/blob/326ffea871c1fcbc2ba65f90b39433894a978a7e/kernel/arm64/dtrmm_kernel_sve256_12x8.S#L160)
