### ISSUE TITLE
Multiple build systems

### ISSUE THREAD

**Issue by twmr** [xianyi/OpenBLAS#2858]
Why are there both CMake files as well as Makefiles in the top-level
directory? Will the cmake build system replace the pure-Makefile based
system in the future?

Which one is preferred?

The README.md should contain instructions on how the project can be built using cmake

When can we expect cmake support to be production-ready, because currently

```
 CMake support is experimental.  It does not yet support all build options
 and may not produce the same Makefiles that OpenBLAS ships with.
```

is output when cmake is run.

I noticed that there are instructions for building the software both in the
README.md as well as in the wiki
(https://github.com/xianyi/OpenBLAS/wiki/Installation-Guide). IMO they
should be merged.

**Comment by brada4** [comment]
It is hard to understand what is the issue - we target old cmake versions that cannot in effect prevent in-source builds.
Common sense says to not do them.

**Comment by martin-frbg** [comment]
Makefiles for GNU make were the original build system and are still considered the primary or "normative" one, cmake support is a later addition - it is supposed to be "production ready" for normal use by now but one or the other of the more exotic build flags could still be unsupported. I do not expect the gmake support to be removed in favor of cmake - there will certainly be platform and user preferences for either.
Further build systems may be supported in the future if there is sufficient interest and contribution of expertise.

**Comment by twmr** [comment]
I have one more question, since I want to document this in the README:

Is it correct that the build options for cmake builds are not the ones that are defined in Makefile.rule, but only in CMakeLists.txt?

**Comment by martin-frbg** [comment]
Some build options are handled in the scripts under `cmake/` - please do not document anything without observing and understanding its actual behaviour first, or you will only create additional work for everybody. 
As I wrote earlier, the intention is that the same options from Makefile.rule should be available to cmake builds, the only exception is where cmake provides standard options (e.g. CMAKE_C_COMPILER or CMAKE_BUILD_TYPE) for a given purpose already.
