### ISSUE TITLE
Why are LAPACK/RELAPACK bundled?

### ISSUE THREAD

**Issue by twmr** [xianyi/OpenBLAS#2860]
Please mention it in the README.md.
FYI there are newer versions of lapack available than the one that is
bundled.

If a OpenBLAS is built with NOLAPACK=0, should liblapack.so be built and
installed? Currently I can't find a liblapack.so file in the

**Comment by brada4** [comment]
No, lapack.dll should not be built, same as MKL or ATLAS - some LAPACK functions get replaced by optimized versions and all is in one library. You can build without LAPACK, then link netlib LAPACK to the BLAS-only library provided, especially if you are informed there are versions newer than netlib LAPACK 3.9.0 with cherry-picked updates present in this repository.

**Comment by martin-frbg** [comment]
LAPACK is bundled as parts of it are superseded by reimplementations, and there will also be occasional bugfixes
and perhaps even enhancements that have not yet made their way into the "netlib" reference implementation. (One of the reasons being that OpenBLAS release cycles are shorter than Reference-LAPACKs). If by "newer versions of LAPACK available" you refer to Reference-LAPACK, I can assure you that you are wrong, if you think of SCALAPACK et al., to my knowledge there is still no complete, license-compatible, cross-platform, production-quality one that is a drop-in replacement with the traditional API. Of course you are free to build without LAPACK and substitute any implementation of your choice.
RELAPACK is bundled mostly for convenience, the original project is basically unmaintained right now (though I intend to feed back my local fixes there eventually if possible)
