### ISSUE TITLE
Merge Usage section in README.md with the USAGE.md file

### ISSUE THREAD

**Issue by twmr** [xianyi/OpenBLAS#2862]
Since the Usage section in README.md and the USAGE.md file contains similar
information, they should be merged. IMO USAGE.md should be integrated into
README.md.

Note that there is also a Usage section in the FAQ 
https://github.com/xianyi/OpenBLAS/wiki/Faq

**Comment by martin-frbg** [comment]
The structure of the (arguably scarce) documentation is still that of the original GotoBLAS2 of Kazushige Goto. Obviously the contents of the github wiki are more recent, some of it could/should probably be integrated into what gets distributed by packagers. But I see no immediate benefit from just shuffling around the data in the existing files.
