### ISSUE TITLE
CMake switches for Float type

### ISSUE THREAD

**Issue by cpviolator** [xianyi/OpenBLAS#2868]
I added the following lines to my local CMakeLists.txt:
```CMake
# Accessible from CMake GUI, command line, or parent build                                                                                                                        
option(BUILD_FLOAT_TYPE_HALF "Build Half " OFF)
option(BUILD_FLOAT_TYPE_SINGLE "Build Single " ON)
option(BUILD_FLOAT_TYPE_DOUBLE "Build Double " ON)
option(BUILD_FLOAT_TYPE_COMPLEX "Build Complex " ON)
option(BUILD_FLOAT_TYPE_COMPLEX16 "Build Complex16 " ON)

set(FLOAT_TYPES "")
if (BUILD_FLOAT_TYPE_SINGLE)
  message(STATUS "Building Single Precision")
  list(APPEND FLOAT_TYPES "SINGLE") # defines nothing                                                                                                                             
endif ()

if (BUILD_FLOAT_TYPE_DOUBLE)
  message(STATUS "Building Double Precision")
  list(APPEND FLOAT_TYPES "DOUBLE") # defines DOUBLE                                                                                                                              
endif ()

if (BUILD_FLOAT_TYPE_COMPLEX)
  message(STATUS "Building Complex Precision")
  list(APPEND FLOAT_TYPES "COMPLEX") # defines COMPLEX                                                                                                                            
endif ()

if (BUILD_FLOAT_TYPE_COMPLEX16)
  message(STATUS "Building Double Complex Precision")
  list(APPEND FLOAT_TYPES "ZCOMPLEX") # defines COMPLEX and DOUBLE                                                                                                                
endif ()

if (BUILD_FLOAT_TYPE_HALF)
  message(STATUS "Building Half Precision")
  list(APPEND FLOAT_TYPES "HALF") # defines nothing                                                                                                                               
endif ()
```

and removed:

```CMake
if (NOT DEFINED BUILD_HALF)
 set (BUILD_HALF false)
endif ()
# set which float types we want to build for
if (NOT DEFINED BUILD_SINGLE AND NOT DEFINED BUILD_DOUBLE AND NOT DEFINED BUILD_COMPLEX AND NOT DEFINED BUILD_COMPLEX16)
  # if none are defined, build for all
#  set(BUILD_HALF true)
  set(BUILD_SINGLE true)
  set(BUILD_DOUBLE true)
  set(BUILD_COMPLEX true)
  set(BUILD_COMPLEX16 true)
endif ()

set(FLOAT_TYPES "")
if (BUILD_SINGLE)
  message(STATUS "Building Single Precision")
  list(APPEND FLOAT_TYPES "SINGLE") # defines nothing
endif ()

if (BUILD_DOUBLE)
  message(STATUS "Building Double Precision")
  list(APPEND FLOAT_TYPES "DOUBLE") # defines DOUBLE
endif ()

if (BUILD_COMPLEX)
  message(STATUS "Building Complex Precision")
  list(APPEND FLOAT_TYPES "COMPLEX") # defines COMPLEX
endif ()

if (BUILD_COMPLEX16)
  message(STATUS "Building Double Complex Precision")
  list(APPEND FLOAT_TYPES "ZCOMPLEX") # defines COMPLEX and DOUBLE
endif ()

if (BUILD_HALF)
  message(STATUS "Building Half Precision")
  list(APPEND FLOAT_TYPES "HALF") # defines nothing
endif ()

```
so that my parent project can compile only `COMPLEX16`. Is there some contribution model I can use to push this to mainline?

**Comment by martin-frbg** [comment]
Compiling only the parts for a particular floating point type is very much a work in progress right now - #2588 and related temporary PR #2852 - that these BUILD_ options were there at all was mostly an artefact of including Reference-LAPACK. Possibly your build still contains all of BLAS, and just the COMPLEX16 subset of LAPACK, and building with DYNAMIC_ARCH support is not possible in that configuration without #2588 .
 
If I read your change correctly, it "only" makes the options visible in the cmake GUI, while using them on a cmake commandline  "sort-of" worked already ? (Not sure I understand your question about a contribution model, but if no employer (or similar) has any rights to your work and you are comfortable with the BSD-style
licensing you can just submit a pull request (or outline your changes if you are not familiar with git)

**Comment by cpviolator** [comment]
Hi, Thanks for the reply. Indeed, I found that by only passing `DOUBLE COMPLEX` flags for compilation, there were several link errors from lower prec routines.

I ask about contributing because when I tried to push my branch to git, I did not have permissions. Not sure how I can make a PR without being able to push a branch to this repo. Use a fork?

**Comment by martin-frbg** [comment]
Yes, use a fork of the repo and create PRs from there. 

Your problem with `COMPLEX` probably comes from complex functions calling single-precision BLAS, and similarly COMPLEX16 using DOUBLE routines. Patching #2852 into the `develop` branch will probably work (though that PR contains a hackish workaround for a parameter not getting set by normal means - still need to track that one down. And eventually this needs to work with plain gmake as well, where even Reference-LAPACK does not support these options - currently have that "almost" working in my local branch as of late last night)
