### ISSUE TITLE
Wrong defines checked when compiling with -std=c11

### ISSUE THREAD

**Issue by Flamefire** [xianyi/OpenBLAS#2871]
There is some code which checks for C11 features, such as atomics. Usually C11 is enabled by passing `-std=c11`

However there are many checks like `#ifdef linux` which will then fail due to `linux` not being defined. In general (IIRC) the symbols from the compiler all are of the form `__foo__`, especially starting with a double underscore

I think it would be a good idea to check and replace such macros and add CI for using standard C11

**Comment by martin-frbg** [comment]
Thanks, at first glance the old-style symbol checks are limited to the benchmarks and to the cpuid detection code of a few platforms - which would explain why this has not bitten anybody yet.

**Comment by Flamefire** [comment]
At least for `#ifdef linux` I can confirm this. I noticed that because the build in CMake failed after `getarch` outputs bogus values which is actually a bug in that code: https://github.com/xianyi/OpenBLAS/blob/0d98ce202cd504f6f591ba0d1d6d67c0cf08af75/cpuid_power.c#L105 misses a return statement for the "default" case when none of the defines matches. Maybe a style using `#if-elif-else error` would be better so this is caught at compiletime?

**Comment by brada4** [comment]
Why not c18 right away?

**Comment by brada4** [comment]
Would be nice to back original statement with a report from static checker being used.
Once c11 is enabled also asm sections stop working, while gnu11 would permit them.

**Comment by martin-frbg** [comment]
@brada4 there is nothing that would mandate use of -std=c11 in the related PR. The only C11-ish feature we are _optionally_ interested in is Atomics (and I am not aware that std=c11 breaks inline assembly with gcc ?)
And I do not get your comment about using a "static checker" - with `gcc -std=c11 -dM ctest.c` it is fairly obvious that the `define linux` gets dropped compared to non-c11 behaviour, and it is not rocket science to conclude that the entire `ifdef linux` section of the cpuid code will be skipped because of this.

**Comment by Flamefire** [comment]
> Why not c18 right away?

I wasn't suggesting to raise any required standard but just wanted to point out that when compiling in standard compliant C the define `linux` does not exist. This can be verified by running `gcc -dM -E -std=c11 - < /dev/null | grep linux`

I hope that helps

**Comment by brada4** [comment]
`asm` is not defined with c11 , the build actually stops step later.
gnu11/ gnu18 work just fine and define `linux`

**Comment by martin-frbg** [comment]
seriously what compiler is that ? Does not happen with gcc7/gcc9  on either x86_64 or power. In any case there was nothing here about forcing people to use -std=c11

**Comment by brada4** [comment]
clang 10.0.1 present in termux app on android compiling aarch64 cannot expand macro yielding which is asm nopnopnop
basically git pull/apt install make gcc perl/make 'CC="cc -std=c18" ' nothing done to damage anything

**Comment by brada4** [comment]
I think something if !def asm && def __asm -> define asm __asm

**Comment by martin-frbg** [comment]
clang 8 in termux still has/had __linux , think you uncovered another bug: the YIELDING macro in common.h has an "asm" that should be `__asm__` (like all the others)

**Comment by brada4** [comment]
Will make a PR

**Comment by brada4** [comment]
There is a bunch of those in zarch and alpha - do they deserve blanket editing?
I can split in pieces too.

**Comment by martin-frbg** [comment]
Not sure we want to touch zarch, and alpha is very probably dead anyway
