### ISSUE TITLE
Superflous statements in CMake code

### ISSUE THREAD

**Issue by Flamefire** [xianyi/OpenBLAS#2872]
I noticed that this line is not required: https://github.com/xianyi/OpenBLAS/blob/68b1713c300ac152d1efcb3c02f0c59fafcd39e1/cmake/system_check.cmake#L125 CMake already outputs:

> -- Looking for stdatomic.h
> -- Looking for stdatomic.h - found

And `if (HAVE_C11 EQUAL 1)` can be shortened to `if (HAVE_C11)`, similar for others

**Comment by martin-frbg** [comment]
Thanks, the first is a leftover from debugging - I noticed the duplicate output but did not get around to cleaning it up. (There are probably other things that can be improved in the script-generated output). I have grown a bit wary of shortening conditional code - with "if" the extra verbosity does not hurt (I think) and it makes it less easy for any "ifdef(FOO)" to hide in the neighborhood, waiting to trap somebody who sets FOO to zero for good measure. :)

**Comment by Flamefire** [comment]
> "if" the extra verbosity does not hurt (I think) and it makes it less easy for any "ifdef(FOO)" to hide in the neighborhood, 

Well this is CMake code so that does not apply. An `if(FOO)` is shorter and allows different values besides "1" like "ON", "TRUE" and similar. I'm not sure if it is specified that a header check sets to variable to "1" and not e.g. "ON". From the top of my head I can only say that it sets it to a value that is true according to CMake rules. And `ifdef(FOO)` doesn't exist in CMake (well `if(DEFINED FOO)` exists, but is clearly different)

**Comment by martin-frbg** [comment]
Of course you are right.Don't think there are any others where shortening makes sense though - the NO_AVX512 is the return code from executing a test, so unlikely to be anything other than 0/1, and the other instances of EQUAL are not in the context of simple true/false tests

**Comment by Flamefire** [comment]
I see.

However I've also seen a common mistake: Using `if(${var} <op> <value>)` Those should be converted to NOT evaluating the variable manually:  `if(var <op> <value>)`
Reason: CMake will evaluate the variable if it is found. For example `if (${CMAKE_C_COMPILER_ID} STREQUAL "GNU"` could be a problem, I think there might be a predefined CMake variable "GNU" which gets defined to 1 if GCC is detected so what CMake will ultimately do is `1 == "GNU"` which then erroneously fails

**Comment by martin-frbg** [comment]
Thanks for the hint - I guess many things in the cmake code are still more of the "observed to work" variety, which is why the big warning is still there although the functionality _should_ be equivalent to gmake builds by now. (Though I think that particular example is a bit contrived ?)

**Comment by Flamefire** [comment]
> Though I think that particular example is a bit contrived ?

Not fully, there are many variables defined by CMake which could conflict like this example: https://cmake.org/cmake/help/latest/manual/cmake-variables.7.html#variables-that-describe-the-system From a quick check I haven't seen a conflict yet, but maybe if some changes are introduced there might be. E.g there is a variable `X86_64` and if `ARCH` is set to `X86_64` then there would be a conflict. Or if a variable named `ia64` is introduced there would be an actual bug (I think currently there is none)

So this is more to avoid problems and it even makes the code shorter.
