### ISSUE TITLE
[Regression?] OpenBLAS failed to compile with "DYNAMIC_ARCH=0 make", but works with make

### ISSUE THREAD

**Issue by Iceman9** [xianyi/OpenBLAS#2875]
OS: CentOS8
GCC: 8.3.0
OpenBLAS: 0.3.10
CPU: Intel(R) Xeon(R) Gold 5217 CPU

Compiling OpenBLAS fails with the following command:

DYNAMIC_ARCH=0 make

But compiling with the following commands work:
- make
- DYNAMIC_ARCH=1 make

In config.h SKYLAKEX is defined.

The problem is the same as in the referenced issue #1797, missing ``-march=skylakex-avx512`` flag when compiling kernels.

It is not an issue, but the way my build scripts are organized, dynamic arch is always provided and for my work machine, I do not need the dynamic library, so I simply turn it of by setting it to 0. Maybe I misunderstood the use of DYNAMIC_ARCH. So for example if I do not want a dynamic library, I simply do not define the variable at all?

**Comment by martin-frbg** [comment]
Yes, in general you should leave the respective variable undefined (though I fixed many/most of the cases where using `ifdef FOO` instead of `ifeq FOO,1` created such traps - certainly looks like I missed at least one, or the code grew a new one)

**Comment by Iceman9** [comment]
Noted. I will close the issue, unless you wish more data on where does it goes wrong.

But I think, like you wrote, it's best that this switch should be used only as an ON switch and not an explicit off. There is no sense in saying DYNAMIC_ARCH=0, but like I said, that was the way my build script was organized.
