### ISSUE TITLE
Optimal TARGET when building on AMD Naples

### ISSUE THREAD

**Issue by moravveji** [xianyi/OpenBLAS#2877]
Hey

I would like to build OpenBLAS for our AMD Naples nodes (two socket, 32 cores per socket, CentOS 7.8), but would like to know the optimal choice of TARGET from the available list.
Would you please help me choose?

Regards
Ehsan

**Comment by martin-frbg** [comment]
That would be "TARGET=ZEN". Does autodetection of the cpu not work ?
