### ISSUE TITLE
Compilation terminates with: ieee_inexact is signaling

### ISSUE THREAD

**Issue by moravveji** [xianyi/OpenBLAS#2901]
Dear all

I am trying to build OpenBLAS v. 0.3.10 on an AMD naples node using the AOCC/2.2.0 prebuilt compilers (clang and flang). Each node has two sockets with 32 cores per socket, and running CentOS 7.8 as OS.

At the end of the build, I get the following error message and the build terminates:

``` bash 
END OF TESTS
Warning: ieee_inexact is signaling
FORTRAN STOP
make[1]: Leaving directory `/work/OpenBLAS/OpenBLAS-0.3.10/ctest'
make: *** [tests] Error 2 
```

Here is the full ``make`` command that I execute:

``` bash
make TARGET=ZEN CC=clang FC=flang BINARY=64 USE_THREAD=1 USE_OPENMP=1 NUM_THREADS=64 NUM_PARALLEL=64 BIGNUMA=0 NO_AVX=1 NO_AVX2=0 NO_AVX512=1 MAX_STACK_ALLOC=2048
```

In the ``Makefile.rule`` I see no relevant variable/control over the IEEE precision tolerance for tests, hence, my hands are short here. 
Do you have an idea how to circumvent the fail, and help it pass?

Thanks in advance.
Ehsan

**Comment by martin-frbg** [comment]
Can you upload the full build log please ? I do not think the IEEE_INEXACT is the actual cause, probably some critical error was reported earlier

**Comment by moravveji** [comment]
Thanks @martin-frbg for your swift reply.
I see a lot of `expr: syntax error` in the build log, which I cannot easily associate to the `make` arguments.
Please find the log file attached.
[log.tar.gz](https://github.com/xianyi/OpenBLAS/files/5390984/log.tar.gz)

**Comment by martin-frbg** [comment]
Not sure what the expr errors are about, but the actual problem appears to be this:
```
OMP_NUM_THREADS=2 ./xccblat2 < cin2
FIO-F-217/list-directed read/unit=5/attempt to read past end of file.
 File name = 'stdin ',    formatted, sequential access   record = 1
 In source file c_cblat2.f, at line number 129
make[1]: *** [all2] Error 127
make[1]: *** Waiting for unfinished jobs....
TESTS OF THE COMPLEX*16        LEVEL 3 BLAS
```
which is either a corrupt/truncated input file or a bug in the test. (ISTR fixing something like this in the `develop` branch, so the
quickest solution would probably be to cherrypick the current c_cblat2.f from there. (Or wait a few hours for me to either lose my mind or release 0.3.11 - possibly both)

The various IEEE errors are most probably generated by functions in the LAPACK code that actively check for IEEE-conformant behaviour of the host.

**Comment by moravveji** [comment]
@martin-frbg: if the release of 0.3.11 is an option, I am patient enough to wait ;-)

**Comment by moravveji** [comment]
Thanks @martin-frbg for the fix. The new release (0.3.11) indeed compiles flawlessly.

**Comment by martin-frbg** [comment]
Unfortunately 0.3.11 has some other problems, like not including all double-precision complex functions in the library - there will be another release soon

**Comment by moravveji** [comment]
I was not aware of that, so, thanks for the heads-up.
Don't you mind notifying me here to fetch the new release once it is fired?

**Comment by martin-frbg** [comment]
Reopening as a reminder to let you know as soon as all known bugs are replaced by new ones.

**Comment by martin-frbg** [comment]
Released 0.3.12 now, hope this clears up all the fallout from 0.3.11
BTW the "expr: syntax error" were probably caused by a broken check for the gcc version, please let me know if you still see them
with 0.3.12

**Comment by moravveji** [comment]
Thanks for the last release. I also easily compiled it; however, I still see the "expr: syntax error" message everywhere. 
What worries me is that you do not see this, and hence cannot reproduce it on your platform. I am using AOCC v.2.2.0 compilers on an AMD Naples machine with CentOS 7.8.

**Comment by martin-frbg** [comment]
Found a spurious "expr" in a shell call to query the flang version now (Makefile.system near line 860) - this should be harmless as the call only served to identify an earlier version of AOCC flang that required a workaround for a complier bug)
