### ISSUE TITLE
build with RHEL7 gcc fails on ppc64le

### ISSUE THREAD

**Issue by loveshack** [xianyi/OpenBLAS#2902]
If you try a simple make with RHEL7's system compiler on a POWER9 system, it fails with

cc: error: unrecognized argument in option ‘-mcpu=power9’

despite the check I see in Makefile.system.  Sorry I don't have time to debug it immediately.

**Comment by martin-frbg** [comment]
That's with current develop ?

**Comment by loveshack** [comment]
Sorry, I'd just realized I didn't say it's with 0.3.10, which you'd think I'd know to do.  No worries if it's been fixed since.

**Comment by martin-frbg** [comment]
#2749 is/was supposed to fix it but that came after 0.3.10

**Comment by brada4** [comment]
You can get newer compiler to actually optimize for POWER9  here: https://www.softwarecollections.org/en/scls/rhscl/devtoolset-8/
