### ISSUE TITLE
0.3.11: cblas_sgemm test case fails on skylake for k=0, beta=0.0

### ISSUE THREAD

**Issue by bartoldeman** [xianyi/OpenBLAS#2914]
`make tests` reports this on SkyLakeX (but not on Haswell and Ryzen):
```
 cblas_sgemm  PASSED THE COLUMN-MAJOR COMPUTATIONAL TESTS ( 27783 CALLS)
 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
           EXPECTED RESULT   COMPUTED RESULT
       1       0.00000          0.266733    
 ******* cblas_sgemm  FAILED ON CALL NUMBER:
   4540: cblas_sgemm ( CblasRowMajor,  CblasNoTrans,  CblasNoTrans,
                      1,  1,  0, 1.0, A,  2, B,  1, 0.0, C,  2).

 ******* FATAL ERROR - TESTS ABANDONED *******
```
#2782 may have something to do with this (to be confirmed)

**Comment by bartoldeman** [comment]
Confirmed: 75eeb26 is the culprit.

**Comment by martin-frbg** [comment]
Thx. I do not see what is causing this, have marked the ill-fated release as beta for now and added a fat warning :(

**Comment by bartoldeman** [comment]
Looking a little further I see `sgemm_direct.o` contains only a `retq` so does nothing. That's why it returns garbage.

**Comment by bartoldeman** [comment]
```
diff --git a/kernel/x86_64/sgemm_direct_skylakex.c b/kernel/x86_64/sgemm_direct_skylakex.c
index a7cddbb3..aaadcf15 100644
--- a/kernel/x86_64/sgemm_direct_skylakex.c
+++ b/kernel/x86_64/sgemm_direct_skylakex.c
@@ -1,7 +1,8 @@
-#if defined(SKYLAKEX) || defined (COOPERLAKE)
 /* the direct sgemm code written by Arjan van der Ven */
 #include <immintrin.h>
 #include "common.h"
+
+#if defined(SKYLAKEX) || defined (COOPERLAKE)
 /*
  * "Direct sgemm" code. This code operates directly on the inputs and outputs
  * of the sgemm call, avoiding the copies, memory realignments and threading,
```
fixes it. I'll file a PR

**Comment by martin-frbg** [comment]
The ancient art of shooting oneself in the foot. Wish I had let the self-imposed deadline slip for another week of testing but by then even more  work would have piled up. Thanks for tracking down and fixing this

**Comment by boegel** [comment]
> Thx. I do not see what is causing this, have marked the ill-fated release as beta for now and added a fat warning :(

Just for the record: thanks a lot for taking this approach, rather than pulling the release or doing an in-place re-release under the same version (which is a big no-no).

Tagged "broken" releases is not fun, but sweeping it under the rug doesn't help anyone either.

If there's something we can do to help out with pushing out a quick new release, do let us know!

cc @bartoldeman, @Flamefire

**Comment by isuruf** [comment]
> Just for the record: thanks a lot for taking this approach, rather than pulling the release or doing an in-place re-release under the same version (which is a big no-no).

:smile: Reminded me of the "How to make package managers cry" video and realized it was you in that video.

**Comment by boegel** [comment]
@isuruf :+1:
