### ISSUE TITLE
How to modify compiler flags when building

### ISSUE THREAD

**Issue by moravveji** [xianyi/OpenBLAS#2921]
Hi

I would like to know how to add e.g. `-march=native` (and few other ones) to the compiler flags, in order to have different builds? 

Thanks
Ehsan

**Comment by martin-frbg** [comment]
The official way is to uncomment the COMMON_OPT line in Makefile.rule and add your flags there. (Providing your own COMMON_OPT variable on the `make` command line would appear to do the same thing, but it creates a hierarchical problem where the makefiles cannot change COMMON_OPT anymore to add further required options)

**Comment by moravveji** [comment]
Thanks @martin-frbg for your verdict. 
For the record, I just installed OpenBLAS/0.3.11 with the following options and `make` arguments:

```bash
COMMON_OPT = -O3 -march=native -fvectorize -mfma -mavx2 -m3dnow -floop-unswitch-aggressive -fuse-ld=lld
FCOMMON_OPT = -frecursive -O3 -mavx
``` 
and
```bash
make TARGET=ZEN CC=clang FC=flang BINARY=64 USE_THREAD=1 USE_OPENMP=1 NUM_THREADS=64 NUM_PARALLEL=64 BIGNUMA=0 NO_AVX=1 NO_AVX2=0 NO_AVX512=1 MAX_STACK_ALLOC=2048
```
I will test it soon for performance comparison with another build we have using GCC.

Thanks for the help.
