### ISSUE TITLE
GEMM_... undeclared

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [xianyi/OpenBLAS#2927]
I am using CentOS 8 on A64FX. On make I get lots of similar errors like 
- trsm.c:365:19: error: ‘GEMM_MULTITHREAD_THRESHOLD’ undeclared (first use in this function) 
- ../common_param.h:972:25: error: ‘GEMM_DEFAULT_OFFSET_B’ undeclared (first use in this function); did you mean ‘GEMM_DEFAULT_UNROLL_M’?

**Comment by martin-frbg** [comment]
This kind of error usually means that the cpu model was not autodetected, so model-dependent parameters could not be defined. If A64FX is what I think it is, please try building with `make TARGET=ARMV8` (after a `make clean`).  
(BTW which version are you trying to build - a snapshot of the current `develop` branch or a release ?
In theory the code in cpuid_arm64.c should fall back to ARMV8 when it does not find a more specific match, but maybe something got broken there. Could you please provide /proc/cpuinfo output for this beast ?

**Comment by LutzWeischerFujitsu** [comment]
Martin, I forget to mention it is regarding tinyBLAS. I am going for the master, not a specific release. /proc/cpuinfo looks for each core like this: cat /proc/cpuinfo
processor       : 0
BogoMIPS        : 200.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm fcma dcpop sve
CPU implementer : 0x46
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0x001
CPU revision    : 0
Did make clean and make TARGET=ARMV8, which works much better, but get error in directory test with: 
sblat1.f:215:44:

  215 |                CALL STEST1(SNRM2(N,SX,INCX),STEMP,STEMP,SFAC)
      |                                            1
Error: Rank mismatch in argument ‘strue1’ at (1) (scalar and rank-1) 
...

**Comment by martin-frbg** [comment]
Beware that the `master` branch here is stale (and getting close to three years out of date), you'll want `develop`. The files in `test` are copied from Reference-LAPACK ("netlib LAPACK") which sometimes used quite the rustic approach for argument passing - if you happen to use a recent gfortran10 and you are actually building from the old `master` (which has the `test` from an even older lapack)  you could try adding -fallow-argument-mismatch to the compiler flags - but using the current OpenBLAS `develop` will make more sense.

**Comment by LutzWeischerFujitsu** [comment]
Thanks, adding 'git checkout develop' solved it, it compiles.

**Comment by martin-frbg** [comment]
Great. Performance will probably not be stellar out of the box as nothing will make use of SVE right now. (You could try if forcing TARGET=NEOVERSEN1 works (which should at least get you a mix of ThunderX2 microkernels and automatic addition of -march=armv8.2-a to the compiler flags, though the -mtune will also be for the neoverse).

**Comment by LutzWeischerFujitsu** [comment]
Auto-vectorisation for SVE by compilers like GCC and LLVM has already started. Fujitsu supplies with its compiler a BLAS library with hundreds of SVE'ed routines.

**Comment by martin-frbg** [comment]
In that case using the handwritten assembler kernels for another ARM cpu may not be advantageous of course.
