### ISSUE TITLE
Fails to build on recent targets with -mtune=generic

### ISSUE THREAD

**Issue by thrasibule** [xianyi/OpenBLAS#2933]
I package openblas for Arch AUR, and I'm getting reports from multiple users that it fails to build with the following error. 

```
cc -c -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -O2 -DMAX_STACK_ALLOC=2048 -fopenmp -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=12 -DMAX_PARALLEL_NUMBER=1 -DUSE_TLS -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.11\" -msse3 -mssse3 -msse4.1 -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME=strmm_iutncopy -DASMFNAME=strmm_iutncopy_ -DNAME=strmm_iutncopy_ -DCNAME=strmm_iutncopy -DCHAR_NAME=\"strmm_iutncopy_\" -DCHAR_CNAME=\"strmm_iutncopy\" -DNO_AFFINITY -I.. -UDOUBLE  -UCOMPLEX -Wno-uninitialized -UDOUBLE -UCOMPLEX -UOUTER -ULOWER -UUNIT generic/trmm_utcopy_8.c -o strmm_iutncopy.o
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/immintrin.h:51,
                 from ../kernel/x86_64/../arm/../simd/intrin.h:51,
                 from ../kernel/x86_64/../arm/sum.c:33:
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/avxintrin.h:517:1: error: inlining failed in call to ‘always_inline’ ‘_mm256_extractf128_ps’: target specific option mismatch
  517 | _mm256_extractf128_ps (__m256 __X, const int __N)
      | ^~~~~~~~~~~~~~~~~~~~~
In file included from ../kernel/x86_64/../arm/../simd/intrin.h:63,
                 from ../kernel/x86_64/../arm/sum.c:33:
../kernel/x86_64/../arm/../simd/intrin_avx.h:36:17: note: called from here
   36 |     __m128 hi = _mm256_extractf128_ps(sum_halves, 1);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/immintrin.h:51,
                 from ../kernel/x86_64/../arm/../simd/intrin.h:51,
                 from ../kernel/x86_64/../arm/sum.c:33:
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/avxintrin.h:1454:1: error: inlining failed in call to ‘always_inline’ ‘_mm256_castps256_ps128’: target specific option mismatch
 1454 | _mm256_castps256_ps128 (__m256 __A)
      | ^~~~~~~~~~~~~~~~~~~~~~
In file included from ../kernel/x86_64/../arm/../simd/intrin.h:63,
                 from ../kernel/x86_64/../arm/sum.c:33:
../kernel/x86_64/../arm/../simd/intrin_avx.h:35:17: note: called from here
   35 |     __m128 lo = _mm256_castps256_ps128(sum_halves);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/immintrin.h:51,
                 from ../kernel/x86_64/../arm/../simd/intrin.h:51,
                 from ../kernel/x86_64/../arm/sum.c:33:
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/avxintrin.h:270:1: error: inlining failed in call to ‘always_inline’ ‘_mm256_hadd_ps’: target specific option mismatch
  270 | _mm256_hadd_ps (__m256 __X, __m256 __Y)
      | ^~~~~~~~~~~~~~
In file included from ../kernel/x86_64/../arm/../simd/intrin.h:63,
                 from ../kernel/x86_64/../arm/sum.c:33:
../kernel/x86_64/../arm/../simd/intrin_avx.h:34:18: note: called from here
   34 |     sum_halves = _mm256_hadd_ps(sum_halves, sum_halves);
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/immintrin.h:51,
                 from ../kernel/x86_64/../arm/../simd/intrin.h:51,
                 from ../kernel/x86_64/../arm/sum.c:33:
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/avxintrin.h:270:1: error: inlining failed in call to ‘always_inline’ ‘_mm256_hadd_ps’: target specific option mismatch
  270 | _mm256_hadd_ps (__m256 __X, __m256 __Y)
      | ^~~~~~~~~~~~~~
In file included from ../kernel/x86_64/../arm/../simd/intrin.h:63,
                 from ../kernel/x86_64/../arm/sum.c:33:
../kernel/x86_64/../arm/../simd/intrin_avx.h:33:25: note: called from here
   33 |     __m256 sum_halves = _mm256_hadd_ps(a, a);
      |                         ^~~~~~~~~~~~~~~~~~~~
make[1]: *** [Makefile.L1:691: ssum_k.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/var/tmp/pamac-build-username/openblas-lapack/src/OpenBLAS-0.3.11/kernel'
make: *** [Makefile:165: libs] Error 1
```

One fix is to pass "-march=native" to the CFLAGS and it builds fine, this is for a zen2 cpu. I don't observe the issue on my machine with a zen1 cpu so it must be target dependent. By looking at the recent changelog, it doesn't look like it's been fixed since the 0.3.11 release.

**Comment by brada4** [comment]
-march=x86_64  does not provide any of three AVX generations, you need to disable those (see Makefile.rule) to compile with your strange options.
OpenBLAS uses different `-march` and `-mtune` flags for different CPU generation-specific code. Then they are called on specific CPUs when those are detected at runtime.

**Comment by martin-frbg** [comment]
The problem appears to be that getarch found your build host capable of AVX and/or AVX2, but gcc requires to be expressly told to allow the corresponding intrinsics (`-mavx`) while `mtune=generic` and the x86_64 gcc target are probably too generic to include it.

**Comment by thrasibule** [comment]
This makes sense. I found a machine where I can reproduce. getarch indeed shows HAVE_AVX2=1, and then it fails to compile. Now my question is why doesn't `-mavx2` get added to the compilation? It compiles fine if I add it manually (even with `-march=x86-64 and mtune=generic`), and it seems like ``-msse3 -mssse3 -msse4.1`` already get added, so it seems it's missing. Also it seems to be caused by the universal intrinsics PR, cause 3.10 was compiling fine before.

**Comment by thrasibule** [comment]
So I think I found the issue. This code doesn't look right: https://github.com/xianyi/OpenBLAS/blob/develop/Makefile.x86_64#L78. With recent gcc versions, the minor version can be less then 7, say 10.2 so the test always fails, and -mavx2 never gets added.

**Comment by martin-frbg** [comment]
You are right that this conditional is deceptive nonsense, but OTOH it is not involved when TARGET, and from that CORE, is set to GENERIC.

**Comment by thrasibule** [comment]
But TARGET is correctly determined (in my case HASWELL). `-march=x86-64 -mtune=generic` get passed because these are the default CFLAGS for all packages build on arch linux and we try to respect user CFLAGS when possible when building packages. So with a recent cpu (which supports avx2) and building openblas with `make CFLAGS=-march=x86-64 -mtune=generic` would always trigger it I think. I agree it's a weird scenario, and if you recompile a package from source, using `-march=native` makes a lot more sense, but this could be fixed by improving the test. I can try to come up with something better.

**Comment by martin-frbg** [comment]
Ah, you are not setting TARGET=GENERIC, but -mtune=generic for whatever got autodetected ? Then indeed I need to find out where the `-mavx2` does (not) come from in some cases.

**Comment by martin-frbg** [comment]
Eh... this was simply generating false positives for (some) older gcc releases where `gcc -dumpversion` returned the major only.
So e.g. a gcc 7.5 would report "7" two times and pass the check, while you'd probably be out of luck with 10.2 - and this did not
really matter until the intrinsics crept up on more than just SkylakeX

**Comment by martin-frbg** [comment]
Looks like I broke this in early July in response to #2702 (either my checks were sloppy or it depends on the build of gcc how much it prints in response to a `dumpversion`). I wonder if it wouldn't make much more sense to have c_check get the compiler version once from the __VERSION macro and store it in Makefile.conf rather than let several Makefiles run their own `gcc -dumpversion`

**Comment by martin-frbg** [comment]
`gcc -dumpfullversion` appears to be consistent, always reporting major.minor.patch, while the behaviour of `gcc -dumpversion` is build-time configurable to `--with-gcc-major-version-only` . Now I need to find out if  e.g. gcc4 already understood `-dumpfullversion`(it does not, printing the "no input files" error instead)

**Comment by thrasibule** [comment]
regarding testing for -mavx2 or the like we could use something like:
```
gcc -Q --help=target|grep -q "\-mavx2 "&&echo "1"
```
Not sure how robust that is.

**Comment by martin-frbg** [comment]
Just had a `deja vue` - this volatility of dumpversion was already pointed out some time ago, and a conditional setting of a DUMPVERSIONPARAM introduced in Makefile.system that could/should simply substitute the `-dumpversion` here

**Comment by brada4** [comment]
The problem's source is here:
https://github.com/archlinux/svntogit-community/blob/0a93bacf4206de7dd26b24cb6d3cbe7622f31c62/trunk/PKGBUILD#L23
It should be "COMMON_OPT" or "CCOMMON_OPT" instead to append your flags to those generated by OpenBLAS.
