### ISSUE TITLE
OpenBLAS 0.3.12 ARMv7 build fail

### ISSUE THREAD

**Issue by h6197627** [xianyi/OpenBLAS#2947]
Newly released OpenBLAS 0.3.12 fails build for ARMv7 architecture

> make TARGET=CORTEXA9 USE_OPENMP=1

```
...
cc -c -O2 -DMAX_STACK_ALLOC=2048 -fopenmp -marm -Wall -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DMAX_PARALLEL_NUMBER=1 -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.12\" -mfpu=vfpv3 -march=armv7-a -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME=sswap_k -DASMFNAME=sswap_k_ -DNAME=sswap_k_ -DCNAME=sswap_k -DCHAR_NAME=\"sswap_k_\" -DCHAR_CNAME=\"sswap_k\" -DNO_AFFINITY -I.. -UDOUBLE  -UCOMPLEX -UCOMPLEX -UDOUBLE ../kernel/arm/swap_vfp.S -o sswap_k.o
In file included from ../kernel/arm/../generic/../simd/intrin.h:56:0,
                 from ../kernel/arm/../generic/dot.c:30:
/usr/lib/gcc/arm-linux-gnueabihf/5/include/arm_neon.h:31:2: error: #error You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) to use arm_neon.h
 #error You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) to use arm_neon.h
  ^
In file included from ../kernel/arm/../generic/../simd/intrin.h:56:0,
                 from ../kernel/arm/../generic/dot.c:30:
/usr/lib/gcc/arm-linux-gnueabihf/5/include/arm_neon.h:31:2: error: #error You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) to use arm_neon.h
 #error You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) to use arm_neon.h
  ^
In file included from ../kernel/arm/../generic/../simd/intrin.h:69:0,
                 from ../kernel/arm/../generic/dot.c:30:
../kernel/arm/../generic/../simd/intrin_neon.h:10:9: error: unknown type name ‘float32x4_t’
 typedef float32x4_t v_f32;
         ^
../kernel/arm/../generic/../simd/intrin_neon.h: In function ‘v_muladd_f32’:
../kernel/arm/../generic/../simd/intrin_neon.h:32:14: warning: implicit declaration of function ‘vmlaq_f32’ [-Wimplicit-function-declaration]
     { return vmlaq_f32(c, a, b); }
              ^
../kernel/arm/../generic/../simd/intrin_neon.h: At top level:
../kernel/arm/../generic/../simd/intrin_neon.h:42:30: error: unknown type name ‘float32x4_t’
 BLAS_FINLINE float v_sum_f32(float32x4_t a)
                              ^
In file included from ../kernel/arm/../generic/../simd/intrin.h:69:0,
                 from ../kernel/arm/../generic/dot.c:30:
../kernel/arm/../generic/../simd/intrin_neon.h:10:9: error: unknown type name ‘float32x4_t’
 typedef float32x4_t v_f32;
         ^
../kernel/arm/../generic/../simd/intrin_neon.h: In function ‘v_muladd_f32’:
../kernel/arm/../generic/../simd/intrin_neon.h:32:14: warning: implicit declaration of function ‘vmlaq_f32’ [-Wimplicit-function-declaration]
     { return vmlaq_f32(c, a, b); }
              ^
../kernel/arm/../generic/../simd/intrin_neon.h: At top level:
../kernel/arm/../generic/../simd/intrin_neon.h:42:30: error: unknown type name ‘float32x4_t’
 BLAS_FINLINE float v_sum_f32(float32x4_t a)
                              ^
Makefile.L1:782: recipe for target 'sdsdot_k.o' failed
make[1]: *** [sdsdot_k.o] Error 1
make[1]: *** Waiting for unfinished jobs....
Makefile.L1:779: recipe for target 'dsdot_k.o' failed
make[1]: *** [dsdot_k.o] Error 1
make[1]: Leaving directory '/home/user/Downloads/OpenBLAS-0.3.12/kernel'
Makefile:164: recipe for target 'libs' failed
make: *** [libs] Error 1
```

**Comment by martin-frbg** [comment]
Ouch, more fallout from using intrinsics... fix will probably be to add
```
ifdef HAVE_NEON
CCOMMON_OPT += -mfpu=neon
FCOMMON_OPT += -mfpu=neon
endif
```
at the end of Makefile.arm

**Comment by h6197627** [comment]
@martin-frbg, unfortunately it does not work.
I tried to add:
```
$(info before)
ifdef HAVE_NEON
$(info inside)
CCOMMON_OPT += -mfpu=neon
FCOMMON_OPT += -mfpu=neon
endif
$(info after)
```
and while running:
> make TARGET=CORTEXA9 USE_OPENMP=1

It prints only:

> before
> after

However, while running:

> make clean

it prints:

> before
> inside
> after

Right now I just additionally hardcoded neon into  these lines:
```
CCOMMON_OPT += -mfpu=vfpv3 -march=armv7-a -mfpu=neon
FCOMMON_OPT += -mfpu=vfpv3 -march=armv7-a -mfpu=neon
```

Just for reference:

> cat /proc/cpuinfo

outputs:

> Features                : swp half thumb fastmul vfp edsp thumbee neon vfpv3 tls

**Comment by martin-frbg** [comment]
Hm. With the "neon" in /proc/cpuinfo you should see HAVE_NEON=1 in Makefiie.conf - maybe this is a detection problem for the A9 (our CI did not report a build failure, but compiler version may also play a role with the intrinsics apparently).

**Comment by h6197627** [comment]
Yes, I have HAVE_NEON=1 in Makefiie.conf

**Comment by martin-frbg** [comment]
I cannot explain why the addition would not work in your case, unless there is a mis-spelling in the HAVE_NEON line - it definitely does on my Asus Tinkerboard. The actual behaviour seems to depend on compiler version or float ABI as well - in my case, with
gcc 6.3 running natively on the board (using Linaro Linux), compilation is successful even without the added `-mfpu=neon`

**Comment by Qiyu8** [comment]
@h6197627  I suspect your compiler don't support the Neon intrinsics(maybe a cross-compiler), can you running the following code with `gcc test.c -o main && ./main`.

```
// test.c
#include<arm_neon.h>
#include<stdio.h>
float32x4_t vsqrt(float32x4_t a)
{
    float32x4_t rsqrte = vrsqrteq_f32(a);
    rsqrte = vmulq_f32(rsqrte, vrsqrtsq_f32(a, vmulq_f32(rsqrte, rsqrte)));
    rsqrte = vmulq_f32(rsqrte, vrsqrtsq_f32(a, vmulq_f32(rsqrte, rsqrte)));
    return vmulq_f32(a, rsqrte);
}

int main() {
    float arr[4];
    float32x4_t a = vdupq_n_f32(100.0);
    float32x4_t res = vsqrt(a);
    vst1q_f32(arr, res);
    for(int i=0;i<4;i++) {
        printf("%f ", arr[i]);
    }
    printf("\n");
}
```

**Comment by martin-frbg** [comment]
@Qiyu8 from what I could find, this compiler (Debian/Raspbian gcc5 ?) should support Neon. If I read the above correctly, @h6197627 did not even see the `-mfpu=neon` added by the updated Makefile at first, and with that added to an existing CCOMMON_OPT line it worked ?
(Still I wonder why gcc does not behave as documented, autodetecting the neon capability - but this could be a consequence of
our -mfpu=vfp3 overriding the default -mfpu=auto. In general it would be quite a drawback of the intrinsics if the makefiles now have to provide cpu-specific options for each supported target - the previous approach of mostly just using `-O2`and inline assembly may habe been simplistic but at least it got everything compiled.)

**Comment by h6197627** [comment]
Sorry, I tried one more time and I think I have made mistake:
There is no HAVE_NEON=1 in Makefile.conf
But there is #define HAVE_NEON in config.h
The compiler is gcc 5.4.0 (from Ubuntu 16.04)
@martin-frbg, when used as proposed fix - same error. When added -mfpu=neon to the end of https://github.com/xianyi/OpenBLAS/blob/develop/Makefile.arm#L6-L7 lines, compilation succeed.

**Comment by martin-frbg** [comment]
very strange as the HAVE_NEON entry in both files is generated by the same program. (`getarch 0` writes the part for Makefile.conf, `getarch 1` produces the output that gets into config.h)

**Comment by martin-frbg** [comment]
Indeed this can happen in cross-compilations - for writing to config.h there is an additional loop that writes out static defines for the
desired cpu, but for Makefile.conf it is either query the host cpu or do nothing. Not good, and must have been this way for years.
I'll try to come up with a fix.

**Comment by h6197627** [comment]
Actually I am building directly on a Odroid board, so it is not a cross-compilation.
Before that I had manually built OpenBLAS 3.10 without errors, though not sure was it using NEON or not.

**Comment by martin-frbg** [comment]
Sorry cross-compilation was a bit of a misnomer, specifiying the TARGET instead of letting it get autodetected will lead into the same codepath in getarch.c. 0.3.10 did not yet have the new code that uses the NEON intrinsics (which apparently require that the compiler gets told that NEON is safe to use).

**Comment by h6197627** [comment]
I see. That explains why running
> make clean

was satisfying 
```
ifdef HAVE_NEON
CCOMMON_OPT += -mfpu=neon
FCOMMON_OPT += -mfpu=neon
endif
```
and
> make TARGET=CORTEXA9 USE_OPENMP=1

wasn't

**Comment by martin-frbg** [comment]
Should be fixed on the develop branch now. By the way do you specify TARGET=CORTEXA9 on your Odroid board because autodetection does not work there (cpu type not know to OpenBLAS) or to get consistent builds on a big.LITTLE system ?

**Comment by h6197627** [comment]
Yes, current develop correctly detects:
`-mfpu=vfpv3 -march=armv7-a -mfpu=neon`
I specified TARGET=CORTEXA9 just to be sure that it is building for my particular architecture. Right now I tried to build without this flag and it correctly autodetects my CPU capabilities, so actually this flag is not necessary for me.
