### ISSUE TITLE
binaries to output as libblas.dll and liblapack.dll

### ISSUE THREAD

**Issue by fommil** [xianyi/OpenBLAS#296]
Can you please output separate dynamic libraries for your project:
- libblas3.dll containing BLAS and CBLAS
- liblapack3.dll containing LAPACK (and _no_ LAPACKE, in keeping with industry norms)

instead of bundling it all into a single DLL. This allows upstream developers to swap the BLAS/LAPACK implementation at runtime to OpenBLAS (if compiled against the reference implementation, for example) or to change to another implementation for performance reasons (e.g. to cuBLAS for the BLAS portion).

This is directly impacting me in https://github.com/fommil/netlib-java/issues/27 on Windows, but it would appear that Linux distribution managers already take care of this.

**Comment by jakirkham** [comment]
So, I create symbolic links for libblas.so and liblapack.so on Linux (or dylib on Mac) and libblas.a and liblapack.a and this works fine. It would be nice if OpenBLAS did this by default for these platforms. However, I have not explored this on Windows.

**Comment by opoplawski** [comment]
Has any more work been done on this?

**Comment by sjjpo2002** [comment]
There is only `libgfortran-3.dll` in mingw. Unless by `libgfortran-1-3.dll` you mean `libgfortran-1.dll` or `libgfortran-2.dll`or `libgfortran-3.dll`
