### ISSUE TITLE
Build 0.3.12 with skylakex

### ISSUE THREAD

**Issue by minchaoyue** [xianyi/OpenBLAS#2968]
I build 3.12 version (make TARGET=SKYLAKEX NUM_THREADS=1) and test  performance(use sgemm function). But I found it was not better than MKL in my project. 

And found below comment
  
_*** 2014/07/28 Saar
* Performance at 9216x9216x9216:
*       1 thread:      102 GFLOPS       (SANDYBRIDGE:  59)      (MKL:   83)**_

 in the sgemm_kernel_16x4_skylakex.S file. From build log ,it (sgemm_kernel_16x4_skylakex.S )was not compile by gcc.

gcc build files:

 ../kernel/x86_64/sgemm_kernel_16x4_skylakex_3.c -o sgemm_kernel.o

 ../kernel/x86_64/sgemm_kernel_16x4_skylakex_2.c -o strmm_kernel_LN.o

 ../kernel/x86_64/sgemm_kernel_16x4_skylakex_2.c -o strmm_kernel_LT.o

 ../kernel/x86_64/sgemm_kernel_16x4_skylakex_2.c -o strmm_kernel_RN.o

 ../kernel/x86_64/sgemm_kernel_16x4_skylakex_2.c -o strmm_kernel_RT.o

Would you help me confirm that which  file performance is better ? sgemm_kernel_16x4_skylakex.S sgemm_kernel_16x4_skylakex_2.c sgemm_kernel_16x4_skylakex_3.c . And how to use th file of sgemm_kernel_16x4_skylakex.S build ?

thanks for your help.

**Comment by brada4** [comment]
What is your gcc version? It builds haswell with older compilers.

**Comment by minchaoyue** [comment]
> What is your gcc version? It builds haswell with older compilers.

  OS               ... Linux             
  Architecture     ... x86_64               
  BINARY           ... 64bit                 
  C compiler       ... GCC  (cmd & version : cc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2))
  Fortran compiler ... GFORTRAN  (cmd & version : GNU Fortran (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2))
  Library Name     ... libopenblas_skylakex-r0.3.12.a (Single-threading)

**Comment by brada4** [comment]
Compiler looks fine.
Those files differ in matrix transforms performed by kernel (there is no transform, it just loads input in transformed order), they are all equally good.
You should measure yourself, with virtualisation bugs sometimes haswell or sandybridge are better (build DYNAMIC_ARCH=1, then set OPENBLAS_CORETYPE before benchmark)

**Comment by minchaoyue** [comment]
> Compiler looks fine.
> Those files differ in matrix transforms performed by kernel (there is no transform, it just loads input in transformed order), they are all equally good.
> You should measure yourself, with virtualisation bugs sometimes haswell or sandybridge are better (build DYNAMIC_ARCH=1, then set OPENBLAS_CORETYPE before benchmark)

you mean build : make DYNAMIC_ARCH=1  NUM_THREADS=1
then set OPENBLAS_CORETYPE= SKYLAKEX   before benchmark, right?

**Comment by brada4** [comment]
If you have SkylakeX CPU then it is auto-detected.
You have to measure if code meant for older architecture works better with virtualisation if such is used. i.e set `OPENBLAS_CORETYPE=Sandybridge ./benchmark` 
Or use python/R/octave scripts in benchmark directory if fed up with recompilations.

**Comment by martin-frbg** [comment]
The comment from wernsaar is several years older than the first addition of an sgemm kernel for SkylakeX  by "fenrus75", who retained the comments of the (Haswell?) file he started from. That file is now outdated, the SGEMMKERNEL actually in use (as seen from KERNEL.SKYLAKEX) is sgemm_kernel_16x4_skylakex_3.c ( by "wjc404", see #2520 ). It is quite likely that the performance varies with matrix size, you could change the entry in KERNEL.SKYLAKEX and recompile to test

**Comment by minchaoyue** [comment]
> It is quite likely that the performance varies with matrix size, you could change the entry in KERNEL.SKYLAKEX and recompile to test

For "change the entry in KERNEL.SKYLAKEX and recompile to test", could you please input more info about it ?  
change SGEMM_DEFAULT_Q to suitable size ?

**#define SGEMM_DEFAULT_Q 448**


thanks again.

**Comment by brada4** [comment]
Specific kernels can be changed here:
`kernel/x86_64/KERNEL.SKYLAKEX`

**Comment by martin-frbg** [comment]
Yes you may need to modify the GEMM parameters as well, depending on what you are changing in the algorithm. The entry in kernel/x86_64/KERNEL.SKYLAKEX defines which of the various sgemm_kernel... files you noticed in kernel/x86_64 gets compiled into the library.

**Comment by martin-frbg** [comment]
FYI, other relevant commits are #2300 and #2367 (the pull request comments by wjc404 explain the background of the changes).
Not sure if it is realistic to expect to achieve a _major_ speedup compared to Intel's own MKL on one of their processors though.
