### ISSUE TITLE
non-paywalled Goto and van de Geijn reference 

### ISSUE THREAD

**Issue by loveshack** [xianyi/OpenBLAS#2969]
The link for a non-paywalled version of the "Anatomy" paper at https://github.com/xianyi/OpenBLAS/wiki/Developer-manual is broken, but it's available from CiteSeerX, for instance: https://github.com/xianyi/OpenBLAS/wiki/Developer-manual

**Comment by martin-frbg** [comment]
Thanks - I am not sure about the legality of the CiteSeerX link so would rather not provide it directly. (Seem to remember Prof. van de Geijn had a pdf linked from his bibliography at one point, but now it seems that even if his page was not broken it would point to the ACM paywall only.)

**Comment by loveshack** [comment]
I'd have thought the ACM permissions notice would cover such use, but 
http://www.cs.utexas.edu/users/flame/pubs/GotoTOMS_final.pdf is
accessible, along with, for instance, 
https://www.cs.utexas.edu/users/flame/pubs/GotoTOMS2.pdf.  (A utexas
link is actually top of a duckduckgo search for the paper.)  Presumably
https://www.cs.utexas.edu/~flame/web/FLAMEPublications.html would be
worth referencing anyhow.

**Comment by martin-frbg** [comment]
Hm, weird. The wiki page already has a link to `~flame/web/Publications` which appears to be the same as `FLAMEPublications` just with a fancy FLAME header (and non-working links). The pdfs appear to be hidden from normal browser view, perhaps a side effect of the Flame group now apparently calling itself the "Science of High-Performance Computing" group ?

**Comment by martin-frbg** [comment]
Archive.org does not find me a version of either the FLAME or vdGeijn pages that openly links to the pdf, so assuming the deep link is either accidental or meant to be a hidden gem. Have updated the "Publications" link to point to its "FLAMEPublications" counterpart.
