### ISSUE TITLE
version 0.3.12 compile error on Debian Stable (gcc 8.3.0)

### ISSUE THREAD

**Issue by strimmerlab** [xianyi/OpenBLAS#2971]
OpenBLAS 0.3.10 compiles just fine under Debian Stable with gcc 8.3.0

OpenBLAS 0.3.12 throws the following error messages:

In file included from /usr/lib/gcc/x86_64-linux-gnu/8/include/immintrin.h:41,
                 from ../kernel/x86_64/../arm/../simd/intrin.h:51,
                 from ../kernel/x86_64/../arm/sum.c:33:
/usr/lib/gcc/x86_64-linux-gnu/8/include/avxintrin.h:516:1: error: inlining failed in call to always_inline ‘_mm256_extractf128_ps’: target specific option mismatch
 _mm256_extractf128_ps (__m256 __X, const int __N)
 ^~~~~~~~~~~~~~~~~~~~~
In file included from ../kernel/x86_64/../arm/../simd/intrin.h:63,
                 from ../kernel/x86_64/../arm/sum.c:33:
../kernel/x86_64/../arm/../simd/intrin_avx.h:36:17: note: called from here
     __m128 hi = _mm256_extractf128_ps(sum_halves, 1);
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/lib/gcc/x86_64-linux-gnu/8/include/immintrin.h:41,
                 from ../kernel/x86_64/../arm/../simd/intrin.h:51,
                 from ../kernel/x86_64/../arm/sum.c:33:
/usr/lib/gcc/x86_64-linux-gnu/8/include/avxintrin.h:1453:1: error: inlining failed in call to always_inline ‘_mm256_castps256_ps128’: target specific option mismatch
 _mm256_castps256_ps128 (__m256 __A)
 ^~~~~~~~~~~~~~~~~~~~~~
In file included from ../kernel/x86_64/../arm/../simd/intrin.h:63,
                 from ../kernel/x86_64/../arm/sum.c:33:
../kernel/x86_64/../arm/../simd/intrin_avx.h:35:17: note: called from here
     __m128 lo = _mm256_castps256_ps128(sum_halves);
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/lib/gcc/x86_64-linux-gnu/8/include/immintrin.h:41,
                 from ../kernel/x86_64/../arm/../simd/intrin.h:51,
                 from ../kernel/x86_64/../arm/sum.c:33:
/usr/lib/gcc/x86_64-linux-gnu/8/include/avxintrin.h:269:1: error: inlining failed in call to always_inline ‘_mm256_hadd_ps’: target specific option mismatch
 _mm256_hadd_ps (__m256 __X, __m256 __Y)
 ^~~~~~~~~~~~~~
cc -c -O2 -DMAX_STACK_ALLOC=2048 -fopenmp -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=12 -DMAX_PARALLEL_NUMBER=1 -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.12\" -msse3 -mssse3 -msse4.1 -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME=ssymm_outcopy -DASMFNAME=ssymm_outcopy_ -DNAME=ssymm_outcopy_ -DCNAME=ssymm_outcopy -DCHAR_NAME=\"ssymm_outcopy_\" -DCHAR_CNAME=\"ssymm_outcopy\" -DNO_AFFINITY -I.. -UDOUBLE  -UCOMPLEX -Wno-uninitialized -UDOUBLE -UCOMPLEX -DOUTER -ULOWER generic/symm_ucopy_4.c -o ssymm_outcopy.o
In file included from ../kernel/x86_64/../arm/../simd/intrin.h:63,
                 from ../kernel/x86_64/../arm/sum.c:33:
../kernel/x86_64/../arm/../simd/intrin_avx.h:34:18: note: called from here
     sum_halves = _mm256_hadd_ps(sum_halves, sum_halves);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/lib/gcc/x86_64-linux-gnu/8/include/immintrin.h:41,
                 from ../kernel/x86_64/../arm/../simd/intrin.h:51,
                 from ../kernel/x86_64/../arm/sum.c:33:
/usr/lib/gcc/x86_64-linux-gnu/8/include/avxintrin.h:269:1: error: inlining failed in call to always_inline ‘_mm256_hadd_ps’: target specific option mismatch
 _mm256_hadd_ps (__m256 __X, __m256 __Y)
 ^~~~~~~~~~~~~~

etc.
Compile with make USE_OPENMP=1

**Comment by strimmerlab** [comment]
Processor:
 Xeon E5-1660 v2 @ 3.70GHz   Ivy Bridge EP, Intel Xeon Processor E5 v2 Family
Version 0.3.10 compiles to 
libopenblas_sandybridgep-r0.3.10.a (Multi threaded; Max num-threads is 12)

**Comment by strimmerlab** [comment]
In contrast, I can confirm that compiling 0.3.12 under the same system (Debian Stable with gcc 8.3.0) *does* work perfectly for the following three CPUs:

Core i5 4200U  Haswell, 4th Generation Intel Core i5 Processor
Core i5-8250U  Kaby Lake R, 8th Generation Intel Core i5 Processor
---> compiles into libopenblas_haswellp-r0.3.12.a

Xeon Silver 4114   Skylake, Intel® Xeon® Scalable Processors
---> compiles into libopenblas_skylakexp-r0.3.12.a

**Comment by martin-frbg** [comment]
Needs adding `-mavx` to the CFLAGS to enable the AVX intrinsics header (believed to be already fixed in current `develop` branch).

**Comment by strimmerlab** [comment]
Many thanks!  Just tried to compile OpenBLAS 0.3.12 with 

make USE_OPENMP=1 CFLAGS+='-mavx'

and I can confirm that there are no errors and that the output is (as it should)

libopenblas_sandybridgep-r0.3.12.a   (Multi-threading; Max num-threads is 12)

**Comment by martin-frbg** [comment]
Thanks for the confirmation
