### ISSUE TITLE
fail in building OpenBLAS

### ISSUE THREAD

**Issue by honoreeronoh** [xianyi/OpenBLAS#2975]
I want to use it in Window with the MinGW.
at first I installed the MinGW, then gcc and gfortran. I also download the code(https://sourceforge.net/projects/openblas/) , unzip it to D:/ and rename the folder as OpenBLAS .
then i open the msys (C:\MinGW\msys\1.0\msys.bat), enter the file directory (cd d:/OpenBLAS) and then build it(make)
here are the code given later in the shell:

> ln: creating symbolic link `libopenblas.a' to `libopenblas_haswellp-r0.3.12.a': No such file or directory
> make: [libs] Error 1 (ignored)
> FUNCOBJS = {[ ...]}
> gcc...
> ...
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> ...
> gcc...
> gcc...
> ...
> gcc...
> ar ...
> C:\MinGW\bin\ar.exe: strmm_kernel_LN.obj: No such file or directory
> make[1]: *** [libs] Error 1
> make[1]: Leaving directory `/d/OpenBLAS/kernel'
> make: *** [libs] Error 1
> 

after that I can only find ''libopenblas_haswellp-r0.3.12.a'' in the folder but not ''libopenblas.a" and the shared dll library "libopenblas.dll''. So how to do with it? 
(it is the first time i try to install a library for C language so maybe I made some basic mistakes ... )

**Comment by martin-frbg** [comment]
Can you upload the full build log please ? Probably the build failed before it created the libopenblas_haswellp-r0.3.12.a, and that file was only produced as a side effect of trying to symlink it to its short name. Would need to see why strmm_kernel_LN did not compile... A 64bit Windows binary package of 0.3.12 (cross-compiled on Linux with the MXE version of mingw) can be found on the github Releases page. (A 32bit package should follow once I figure out what I broke in my reinstallation of MXE after a disk failure)

**Comment by honoreeronoh** [comment]
[build log.txt](https://github.com/xianyi/OpenBLAS/files/5501459/build.log.txt)
Is this the build log?  
I will try download and use the 64bit Windows binary package of 0.3.12

**Comment by martin-frbg** [comment]
Yes, this is what I meant - unfortunately the part about compiling strmm_kernel_LN seems to have been in the section of "so many lines similar" that you left out. (And I wonder why it tries to do the "ln" first before the library has even been compiled, but I guess this does not matter)

**Comment by honoreeronoh** [comment]
It is hard to get the full build log...
And I can't figure out how to use the 64bit Windows binary package of 0.3.12. Should I upzip it to a folder and directly use it like this?
> gcc -o test test.c -I /your_path/OpenBLAS/include/ -L/your_path/OpenBLAS/lib -lopenblas

**Comment by honoreeronoh** [comment]
get the full build log! 
[build.txt](https://github.com/xianyi/OpenBLAS/files/5502122/build.txt)

> $ make>build.txt
> ln: creating symbolic link `libopenblas.a' to `libopenblas_haswellp-r0.3.12.a': No such file or directory
> make: [libs] Error 1 (ignored)
> C:\MinGW\bin\ar.exe: creating ../libopenblas_haswellp-r0.3.12.a
> parameter.c: In function 'blas_set_parameter':
> parameter.c:273:7: warning: unused variable 'size' [-Wunused-variable]
>    int size = 16;
>        ^~~~
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> C:\MinGW\bin\ar.exe: strmm_kernel_LN.obj: No such file or directory
> make[1]: *** [libs] Error 1
> make: *** [libs] Error 1
>

**Comment by brada4** [comment]
Could you run `make clean` before running the build again?
 That start with a failed symlink does not seem right.
Is it intentionally 32-bit?
Normally you can collect unix terminal text within `script` command (just exit the script shell after build command and it will say about file named typescript)

**Comment by honoreeronoh** [comment]
My computer is window 64bit system and I download the code from the site (https://sourceforge.net/projects/openblas/). It occur to me that the MinGW in me computer has installed for a long time so maybe the MinGW is not something 64bit ?
What's more, since the build always failed so I have deleted the folder OpenBLAS and unzipped the code for many times, maybe it remains something during this process.

I deleted the whole folder and unzip the code again, and get the following result:

> honore@DESKTOP-3LP8A9H ~
> $ cd d:/OpenBLAS
> 
> honore@DESKTOP-3LP8A9H /d/OpenBLAS
> $ make clean>makecleanlog.txt
> 
> honore@DESKTOP-3LP8A9H /d/OpenBLAS
> $ make>makelog.txt
> ln: creating symbolic link `libopenblas.a' to `libopenblas_haswellp-r0.3.12.a': No such file or directory
> make: [libs] Error 1 (ignored)
> C:\MinGW\bin\ar.exe: creating ../libopenblas_haswellp-r0.3.12.a
> parameter.c: In function 'blas_set_parameter':
> parameter.c:273:7: warning: unused variable 'size' [-Wunused-variable]
>    int size = 16;
>        ^~~~
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> gcc.exe: warning: ../kernel/x86/: linker input file unused because linking not done
> C:\MinGW\bin\ar.exe: strmm_kernel_LN.obj: No such file or directory
> make[1]: *** [libs] Error 1
> make: *** [libs] Error 1

[makecleanlog.txt](https://github.com/xianyi/OpenBLAS/files/5504365/makecleanlog.txt)
[makelog.txt](https://github.com/xianyi/OpenBLAS/files/5504366/makelog.txt)

The `script` command don't work on window msys shell...

In the end I decide not to use OpenBLAS for now, I will retry it when I want to accelerate my program. Maybe at that time i will try Linux which seems more stable and easier for the installation.

Thanks you for help me a lot

**Comment by brada4** [comment]
I dont find source file in compile command?
`gcc -O2 -DMS_ABI -mincoming-stack-boundary=2 -DMAX_STACK_ALLOC=2048 -Wall -m32 -DF_INTERFACE_GFORT -DNO_AVX -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DMAX_PARALLEL_NUMBER=1 -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.12\" -msse3 -mssse3 -msse4.1 -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME=_strmm_kernel_LN -DASMFNAME=_strmm_kernel_LN_ -DNAME=strmm_kernel_LN_ -DCNAME=strmm_kernel_LN -DCHAR_NAME=\"strmm_kernel_LN_\" -DCHAR_CNAME=\"strmm_kernel_LN\" -DNO_AFFINITY -I.. -UDOUBLE  -UCOMPLEX -c -DTRMMKERNEL -UDOUBLE -UCOMPLEX -DLEFT -UTRANSA ../kernel/x86/ -o strmm_kernel_LN.obj`

**Comment by martin-frbg** [comment]
Yes, looks like the automatic fallback to (IIRC) Nehalem for 32bit "Haswell" is now leaving STRMMKERNEL empty. Possibly a side effect of the recent GEMM/TRMM improvements.
honoreeronoh would probably have wanted mingw-w64 rather than mingw, but the 32bit builds are supposed to work too. Will try to reproduce this later

**Comment by brada4** [comment]
I wonder if it is possible to re-open a genuine issue without disturbing OP
