### ISSUE TITLE
Illegal lvalue with PGI compiler 19.9

### ISSUE THREAD

**Issue by sheltongeosx** [xianyi/OpenBLAS#2976]
Hi Dear Developers:

I am using PGI compiler 19.9 to built OpenBLAS on IBM Power8(commit 60ab9c7, 2020-11-04) and it failed with the error mesages:
    
    ... ...
    PGC-S-0058-Illegal lvalue (../kernel/power/../arm/zdot.c: 77)
    PGC-S-0058-Illegal lvalue (../kernel/power/../arm/zdot.c: 78)
    PGC/power Linux 19.9-0: compilation completed with severe errors

Any idea to fix it?

Best,
Shelton

**Comment by brada4** [comment]
You need to produce output from preprocessed file, `CREAL` is either C `creal` or by mistake struct() based emulation of it, somewhere in includes - hard to guess.
With gcc that would be running `cpp` sitting next to `gcc` with same params and picking the output, then compiling that output with gcc and same params, probably PGI has guide somewhere how to "output preprocessed C ffile"
```
76: #if !defined(__POWER__) 
77:        CREAL(result) = dot[0];
78:        CIMAG(result) = dot[1];
79: #else
```

**Comment by martin-frbg** [comment]
These two lines are not supposed to be used on ppc, perhaps PGI does not define `__POWER__`?
Try changing the ifdef to `__PPC__` (like it is a few lines above - both instances were from same commit #2731, probably got distracted in between and it did not matter with the compiler I had used at the time)

**Comment by sheltongeosx** [comment]
@brada4 @martin-frbg 
Andrew, Martin,
Thank you very much for pointing me to the right point. By adding "#define  __POWER__1" to common.h it is successfully built now!

Thanks,
Shelton
