### ISSUE TITLE
Different handling of non-set CROSS and CROSS=0 in Makefiles

### ISSUE THREAD

**Issue by Flamefire** [xianyi/OpenBLAS#2996]
At 1 place `ifneq ($(CROSS), 1)` is used, in others` ifndef CROSS`

This causes tests to not be run, whenn `CROSS=0` is given.

There have been fixes for similar inconsistencies before. I'd suggest to check the makefiles for `ifndef` and `ifdef` and make sure they are handled as booleans where booleans are used.

**Comment by brada4** [comment]
Parameters that are unset in Makefile.rule behave that way, that is long standing misfeature, present empty string or zero change build behaviour, mostly to failure.
