### ISSUE TITLE
segfault in zgemm_oncopy_POWER8 during sagemath test on ppc64el

### ISSUE THREAD

**Issue by tobihan** [xianyi/OpenBLAS#3000]
Hi,

a sagemath test segfaulted in openblas 0.3.12, libopenblas.so.0 / zgemm_oncopy_POWER8 when building on ppc64el, see https://buildd.debian.org/status/fetch.php?pkg=sagemath&arch=ppc64el&ver=9.2-2&stamp=1606048431&raw=0

openblas was called by numpy and the issue looks similar to #2728 where the segfault occurred in dgemm_oncopy_HASWELL and especially #2959 where the segfaut was in zgemm_oncopy_EMAG8180 on arm64. #2959 was reported by me and your patch fixed the issue on arm64 for me. Thanks for that!

Extract from the stack backtrace:

    #5  <signal handler called>
    #6  0x00007fff8250a2b8 in zgemm_oncopy_POWER8 ()
       from /usr/lib/powerpc64le-linux-gnu/libopenblas.so.0
    #7  0x00007fff82203574 in zgetrf_single ()
       from /usr/lib/powerpc64le-linux-gnu/libopenblas.so.0
    #8  0x00007fff815150ac in zgesv_ ()
       from /usr/lib/powerpc64le-linux-gnu/liblapack.so.3
    #9  0x00007fff8149f708 in ?? ()
       from /usr/lib/python3/dist-packages/numpy/linalg/_umath_linalg.cpython-39-powerpc64le-linux-gnu.so

Best,
Tobias

**Comment by martin-frbg** [comment]
0.3.12 should already be using the same buffersize value for all cpu models in the DYNAMIC_ARCH build, but a default TARGET of "GENERIC" or "PPC440" would break it. (Did not want to impose the memory requirement on smaller/older hardware, but crashing is certainly the worse option)
