### ISSUE TITLE
Compile failure on Apple M1 with cmake: cpu type issue?

### ISSUE THREAD

**Issue by TonyWu20** [xianyi/OpenBLAS#3009]
I previously compiled and installed the gcc ported by [iains](https://github.com/iains/gcc-darwin-arm64).
The cmake configuration outputs:
```
CMake Deprecation Warning at CMakeLists.txt:5 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Warning at CMakeLists.txt:67 (message):
  CMake support is experimental.  It does not yet support all build options
  and may not produce the same Makefiles that OpenBLAS ships with.


-- GEMM multithread threshold set to 4.
-- Multi-threading enabled with 8 threads.
-- Running getarch
-- GETARCH results:
CORE=ARMV8
LIBCORE=armv8
NUM_CORES=8
MAKE += -j 8

-- Compiling a 64-bit binary.
-- Building Single Precision
-- Building Double Precision
-- Building Complex Precision
-- Building Double Complex Precision
-- Reading vars from /Users/tonywu/Downloads/openblas/kernel/arm64/KERNEL...
-- Reading vars from /Users/tonywu/Downloads/openblas/kernel/arm64/KERNEL.ARMV8...
-- Building deprecated routines
-- Building Single Precision
-- Building Double Precision
-- Building Single Precision Complex
-- Building Double Precision Complex
-- Generating openblas_config.h in include/openblas
-- Generating f77blas.h in include/openblas
-- Generating cblas.h in include/openblas
-- Copying LAPACKE header files to include/openblas
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/tonywu/Downloads/openblas/build
```
The `cmake --bulid` or `make` shows the progress to 100% but no openblas binary was found after completion of build. When I run `sudo cmake --install` or `sudo make install`, it only shows lib and include information.

**Comment by TonyWu20** [comment]
It turns out that I specify a wrong gfortran (x86_64). After fixing the gfortran path, cmake compiled successfully.

**Comment by martin-frbg** [comment]
There is no "openblas binary" as such, as OpenBLAS is a library. The only binaries created during the build are for the verification tests - these are not installed as they do not serve any other purpose, if you want you can copy them from the test/ctest/openblas_utest folders manually.

**Comment by TonyWu20** [comment]
Thank you. I got this question since I want to compile scipy and I found that the config has the option to specify binary of openblas. I will try the solution.

**Comment by martin-frbg** [comment]
Pretty sure that by "binary of openblas" they mean the compiled library, libopenblas.so or libopenblas.a (only the static library is built by default with cmake, if you want the dynamic one you need to add -DBUILD_SHARED_LIBS=ON to the cmake options)
