### ISSUE TITLE
nm: '/lib/libpthread.so*': No such file

### ISSUE THREAD

**Issue by cbkadhk** [xianyi/OpenBLAS#3028]
Hi
when I try to type "make install"
it returns error that "nm: '/lib/libpthread.so*': No such file"

**Comment by martin-frbg** [comment]
What system are you trying to install on ? (And did you build OpenBLAS by running `make` on that same computer ?) It is looking for the "pthreads" library for multithreading support, perhaps you need to install it on your system.

**Comment by brada4** [comment]
That typically happens when you mix up glibc and musl, the later provides libm and libpthread inside main libc.

**Comment by cbkadhk** [comment]
> 
> 
> What system are you trying to install on ? (And did you build OpenBLAS by running `make` on that same computer ?) It is looking for the "pthreads" library for multithreading support, perhaps you need to install it on your system.

Ubuntu 18.04
And I'm sure that I've run 'make' successfully
--------------------------------------------------------
GotoBLAS build complete.
  OS                         ... Linux
  Architecture          ... x86_64
  BINARY                  ... 64bit
  C compiler             ... GCC
  Fortran compiler    ... libgoto2_nehalemp-r1.13.a

**Comment by cbkadhk** [comment]
> 
> 
> That typically happens when you mix up glibc and musl, the later provides libm and libpthread inside main libc.

sorry sir, i still don't understand what should i install to fix it

**Comment by martin-frbg** [comment]
GotoBLAS and libgoto2_nehalem... ??
Which source package are you building from, this looks like original GotoBLAS from 10 years ago

**Comment by cbkadhk** [comment]
> 
> 
> GotoBLAS and libgoto2_nehalem... ??
> Which source package are you building from, this looks like original GotoBLAS from 10 years ago

GotoBLAS2-1.13……

**Comment by brada4** [comment]
You should try this instead:
https://github.com/xianyi/OpenBLAS/releases/tag/v0.3.13
In principle there is slightly older still usable openblas package via apt (openblas-dev) available from Ubuntu.
