### ISSUE TITLE
Update openblas.net with the latest releases

### ISSUE THREAD

**Issue by mattip** [xianyi/OpenBLAS#3041]
http://www.openblas.net/ is showing 0.3.10 as the latest version, and the [changelog[(http://www.openblas.net/Changelog.txt) is a text file. It should show off 0.3.13, and it would be nice to render that text file as an html file.

**Comment by martin-frbg** [comment]
Updated the website today, may convert the changelog to html later as time permits

**Comment by mattip** [comment]
Thanks.
