### ISSUE TITLE
Error DSYTRF in openblas 0.3.12 and 0.3.13

### ISSUE THREAD

**Issue by carlonervi** [xianyi/OpenBLAS#3054]
I'm Gentoo user and I recently upgraded from openblas 0.3.9-r1 to openblas 0.3.12-r1.
When I upgrade my system from openblas 0.3.9-r1 to the version 0.3.12-r1 (marked as stable by Gentoo), openblas gives some problems. On Ryzen 3800X and Threadripper 3990X the zenp version of openblas is correctly compiled.

I compiled Quantum Espresso (a chemical program in fortran) with dynamic libraries, including openblas. 
I'm running in parallel with mpirun (no openmp, OMP_NUM_THREADS=1). Under openblas 0.3.9-r1 all was working.
After the Gentoo update to 0.3.12-r1 (only openblas was updated) the program runs, but a certain point it stops with the following error:

** On entry to DSYTRF parameter number  7 had an illegal value

 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     Error in routine broyden (7):
     factorization
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

     stopping ...

I also tried to use the version 0.3.13, but with the same results. Returning to the 0.3.9-r1 solved the problem.
The problem is reproducible, at least on my machines.

**Comment by martin-frbg** [comment]
Is this reproducible with some standard example or test case that comes with QE, or only with some particular input from your current research project ? Error code 7 from DSYTRF would mean "the provided work array is too small", which suggests something went wrong earlier.

**Comment by carlonervi** [comment]
Hi Martin, from my limited computer knowledge (I'm chemist) I can report that the same identical input and the same Quantum Espresso executable (pw.x version from qe6.5 to be more precise, which load openblas dynamic library) it is perfectly working with 0.3.9-r1, but it crashes with 0.3.13. No recompilation of pw.x has been done. Recompiling openblas with Gentoo results into  pw.x working with 0.3.9-r1, but crashing with 0.3.13. Perfectly reproducible and switchable.
To my understanding it is a library-related problem. I'm using gcc 9.3.0-r2 p4 with Gentoo up-to-date.
I can send you the QE executable (it is compiled with -march=native switch), the input file (which is an input molecule from my research) and the output files. I am running the executable with the command "mpirun -np 8 pw.x" (the QE6.5 executable). It takes about 3 min on a 8-core Ryzen 3800X).

**Comment by martin-frbg** [comment]
The input in particular would be appreciated - I guess I could compile QE myself if necessary, though I am more familiar with Wien2k. There is no obvious (to me at least) candidate in the changes between 0.3.9 and 0.3.12, so I will need to build and test
several snapshots in between to track this down. (Happily git already provides a tool - the `git bisect` command - to facilitate this)

**Comment by carlonervi** [comment]
Thank you for your time.
Below attache the input file, and the two outputs (correct and with crash).
[calc.zip](https://github.com/xianyi/OpenBLAS/files/5771713/calc.zip)
To run QE you will need also to download the pseudopotentials from http://www.quantum-espresso.org/pseudopotentials and place them in a suitable directory. you will have to modify also the directory name in the input file (.in)
We need to download C H, N and O pseudos. In particular these:
C.pbe-n-kjpaw_psl.1.0.0.UPF
H.pbe-kjpaw_psl.1.0.0.UPF
N.pbe-n-kjpaw_psl.1.0.0.UPF
O.pbe-n-kjpaw_psl.1.0.0.UPF

I can attach them , but compressed is 800 Kb....
Thank you,
Carlo

**Comment by brada4** [comment]
Some things to try to bisect the problematic change:
Since their build is dynamic try setting for running tests:
OPENBLAS_CORETYPE=Haswell
OPENBLAS_COERTYPE=Sandybridge

Does 0.3.10 (unstable by their measure) work? Gentoo changed lots of build parameters between .9 and .10.

**Comment by carlonervi** [comment]
brada4,
Is the OPENBLAS_CORETYPE=Haswell compatible with Ryzen 3800X processor or TR 3990X?
I have no idea of possible OPENBLAS_CORETYPE values...
Anyway, I tested with openblas 0.3.9-r1 and both Haswell and Sandybridge are working with Ryzen 3800X.
With openblas 0.3.13 Sandybridge  and Haswell are crashing at the same point with identical error.

**Comment by brada4** [comment]
Yes, Haswell is AVX2 and ZEN was based largely on it, they still run on eachother with some performance penalty.
Sandybridge is AVX1, also compatible, only older AMD codes may not be compatible because of FMA4 and 3DNOW missing in newer AMD CPUs
I will try to reproduce problem in a VM, I think while around uncommon software you decribed that pretty clearly.

**Comment by martin-frbg** [comment]
A first test with the current `develop` branch did not encounter any problems on Ryzen5-4600H. (But I built with default options, from reading the .ebuild I am not entirely sure if gentoo uses the same setup)

**Comment by carlonervi** [comment]
Which version of QE were you compiling? and mpirun?
I start to have doubts that the problem could be inside one of these...

**Comment by martin-frbg** [comment]
6.5 like you said. mpirun from the "lam" package (lam-mpi.org) as per the defaults of this (opensuse 15.2) installation

**Comment by carlonervi** [comment]
Thank you, I have some machines to test around (Ryzen, TR, an old 4-socket 48-cores Opteron 6168 and perhaps Haswell, but the latter generally uses Intel MKL with docker because the nodes are on our academic supercomputer).
On the Opteron actually I'm using openmpi 4.0.5. I will try to download the OpenBlas 0.3.13.dev (git develop) and recompile.
Sometimes Gentoo mess up the libraries (or because I'm not too much skilled).
I will report the results here... Thank you

**Comment by martin-frbg** [comment]
Oh. I just realized that current  openSUSE 15.2 still installs the ancient openmpi 1.10.7 when one naively asks for "openmpi" rather than "openmpi4". Guess I need to redo my litte experiment ...

**Comment by carlonervi** [comment]
A little update. I recompiled from the scratch QE and manually compiling 0.3.13.dev in separate directory (without using emerge) resulted in a QE working program. Good.
So I decided to upgrade again openblas to the stable 0.3.12-r1 by using the emerge Gentoo utility.
**Again the same error appears!!!!** This time the following extra error appears:
 PMIX ERROR: UNREACHABLE in file /var/tmp/portage/sys-cluster/openmpi-4.0.5/work/openmpi-4.0.5/opal/mca/pmix/pmix3x/pmix/src/server/pmix_server.c at line 2193

I'm confused. Apparently there is something weird happening to my system when I use emerge for openblas. 
and now switching back to the openblas 0.3.13.dev with the LD_LIBRARY_PATH gives the same error! I'm not particular familiar with Gentoo's ebuilds, but now it seems that my problems arises from there.

**Comment by brada4** [comment]
It will take some time to get full gentoo on to repeat. Probably plugging 0.3.13 tarball in 0.3.9 ebuild files will work too.

**Comment by carlonervi** [comment]
re-emerging 0.3.9-r1 downgrading from 0.3.12-r1, but using the same compiled program and library it works again.
Good point. brada4, you mean simply to copy the source tarball to ... which exact place? Thankx.

**Comment by brada4** [comment]
In ebuild file there is download link constructed from version number and checksum of that file, likely bumping up both shall do the trick. I remember gentoo from long ago when it was approx LFS that you compile all system installing.

**Comment by martin-frbg** [comment]
Confirmed 0.3.13 with openmpi 4.0.5 works for me here, cannot really comment on what gentoo's emerge might be doing.

**Comment by brada4** [comment]
Ill try to repeat in full gentoo, but hopefully quick fixes proposed around fill the time till that

**Comment by brada4** [comment]
@carlonervi plese try disabling ReLAPACK, not present in your "simple" build or 0.3.9 file
```
echo 'sci-libs/openblas -relapack' >> /etc/portage/package.use
```
It has no influence on getting back to 0.3.9, though at some point you want to try cleaner than clean build and edit particular line out from the file.
I'll try to find some script wrapper to DSYTRF to eventually test in environments with less compilation. It is tough work watching terabyte scroll across a VM console.

EDIT: it struck out all avx parameters for a ivy bridge even cpuid says they are there and dmesg confirms are XSAVE-d right, best performance in "simple" build. Please record ebuild output wiht `script` command, and `grep -i avx typescript` if you get same.

**Comment by martin-frbg** [comment]
Uh, are gentoo building with ReLAPACK enabled _by default_ now ? Perhaps it needs to be made clearer that this does not yet pass all LAPACK tests (even after my somewhat recent attempts to fix the most obvious problems)

**Comment by brada4** [comment]
DSYTRF is here (see sample) http://search.r-project.org/library/Matrix/html/BunchKaufman-methods.html
Striking out AVX is no go too, should dig a bit further if it overrides fortran flags where it should not as a side impact.

**Comment by brada4** [comment]
> default now

yuck - stable and kicking https://gitweb.gentoo.org/repo/gentoo.git/tree/sci-libs/openblas/openblas-0.3.12-r1.ebuild#n16

I will get  somewhat cleaner build system and grep-able build logs, it is gcc9 , -O2 -pipe, maybe -march=native if user other than I chooses to, nothing that gives broke first impression.

**Comment by martin-frbg** [comment]
The plus sign before the "relapack" in the IUSE line ? (and I see they appear to apply some patch for remedying their override of fflags - but have not looked closer at what exactly they are patching in there). Unfortunately I am not sure I understand what you are writing about your finds - is relapack not the (only) issue, and what's the problem with AVX ?

**Comment by brada4** [comment]
Problem is that ebuild never passes any -mavx or -DAVX flag to gcc where just typing `make` does that right away as designed.
Yes, that + means option is enabled by default, while all other options are optional, equal to zero further in the build script.
Did not read through it - they just push their C flags through after striping out COMMON flags.

**Comment by martin-frbg** [comment]
Thanks. Still any required `-mavx` should get added by the build system (or the build would fail if/when it encounters any of the recent kernels that use Intel intrinsics) (?) And I do not quite get why you try to find or build an isolated DSYTRF example when - as I read it - it is some earlier BLAS or LAPACK function call in QE that generates the (wrong) size for the work array that DSYTRF complains about ?

**Comment by brada4** [comment]
im used to installable linux at least to the spot it boots with ssh on indicated ip... hours of building to get there left some mental scars. The test case is relapack and few reported fortran files w data . No need to search as long as I did.

**Comment by martin-frbg** [comment]
Confirmed that adding BUILD_RELAPACK is sufficient to cause the problem. Now to see if the ReLAPACK DSYTRF itself is confused about what workspace it needs, or if perhaps the workspace requirement calculated for/by standard DSYTRF get applied to the ReLAPACK one or vice versa. Update: seems a "bad" value of 4 was given where ReLAPACK expects at least 8, and the wrong value was not calculated by the ReLAPACK DSYTRF itself.

**Comment by brada4** [comment]
Maybe we can branch relapack option, like 1 - build what is working at least past lapack test suites =2 force building known broken things

**Comment by brada4** [comment]
>  required -mavx should get added

It does not. I think CFLAGS get inheritrd from emerge config after they blank out OPT flags. Thats not cause of a crash or error just a pessimality on modern CPUs. Maybe it is worth writing to some wiki section how to feed manual build to eselect.

**Comment by martin-frbg** [comment]
Unfortunately I do not think this (splitting ReLAPACK into perfectly good and perfectly broken routines) is possible (but I need to review what I noted in one of the related PRs). And in this particular case, the "wrong" workspace appears to come from some other function, not (either implementation of) DSYTRF itself - have not yet determined from where, but code making assumptions on workspace requirements based purely on the reference implementation could be in for a surprise with ReLAPACK

**Comment by brada4** [comment]
Either way gentoo should flip distribution default to stay out of experimental code for unsuspecting consumers. They have debian maintainer written there but package flags are different, really no idea whom to ask.

**Comment by brada4** [comment]
@carlonervi that was fast, thanks. You can keep this open if you wish to see when any improvement is made in ReLAPACK part.

**Comment by brada4** [comment]
@martin-frbg I messed up something with compiling libvirt and it got wrong set of CPU XMLs, AVX kernels are used/compiled correctly, just that base compiler flags are propagated across, no problem whatsoever in that part. Ones using `march=native` probably should not try dynamic build anyway.

**Comment by carlonervi** [comment]
Thanks a lot, the  bug is solved!
I'm actually trying 0.3.13 and works perfectly under Gentoo.

**Comment by carlonervi** [comment]
Quick and nice job. Thanks!
