### ISSUE TITLE
Bad memory unallocation & wrong results with OpenMP

### ISSUE THREAD

**Issue by mgates3** [xianyi/OpenBLAS#3057]
For OpenBLAS version >= 0.3.6, verified through 0.3.13, when we call BLAS routines from within an OpenMP parallel section, we get `BLAS : Bad memory unallocation!` errors and the results are wrong. It works fine with 0.3.5.

This seems similar to #2760 "BLAS: Bad memory unallocation!" errors on Power, but we see this on Intel (Haswell). The tester is compiled with g++, clang++, or Intel icpc, all with OpenMP. I installed OpenBLAS using Spack, and it is compiled with either gcc@7.3.0 or gcc@8.3.0:
```
> spack find openblas
==> 16 installed packages
-- linux-scientific7-haswell / gcc@7.3.0 ------------------------
openblas@0.3.1  openblas@0.3.5  openblas@0.3.7  openblas@0.3.9
openblas@0.3.4  openblas@0.3.6  openblas@0.3.8  openblas@0.3.10

-- linux-scientific7-haswell / gcc@8.3.0 ------------------------
openblas@0.3.11  openblas@0.3.12  openblas@0.3.13
```

A simple tester is below. Here is correct output with 0.3.5.
```
> ./test_gemm 
batch_size 1000, n 50
init
test
test OpenMP
compare
max error 0.00e+00
delete
done
```

Here is erroneous output with 0.3.7. The exact output varies, typical of race conditions.
```
> ./test_gemm 
batch_size 1000, n 50
init
test
test OpenMP
BLAS : Bad memory unallocation! :  128  0x7fffcb070000
BLAS : Bad memory unallocation! :  128  0x7fffc5070000
BLAS : Bad memory unallocation! :  128  0x7fffc7070000
BLAS : Bad memory unallocation! :  128  0x7fffe1070000
BLAS : Bad memory unallocation! :  128  0x7fffc9070000
compare
max error 4.02e+02
delete
done
```

This tester says "batch", but it isn't calling a batched routine, it is just looping over regular gemm. We see the same issue with all other BLAS routines tested (hemm, herk, her2k, trmm, trsm, etc.) and all 4 precisions (s, d, c, z).

Tester (test_gemm.cc)
```
#include <cblas.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

#include <vector>

//------------------------------------------------------------------------------
void fill_rand( int m, int n, double* A, int ld )
{
    for (int j = 0; j < n; ++j) {
        for (int i = 0; i < m; ++i) {
            A[ i + j*ld ] = rand() / double(RAND_MAX);
        }
    }
}

//------------------------------------------------------------------------------
inline double max_nan( double x, double y )
{
    return (isnan(y) || (y) >= (x) ? (y) : (x));
}

//------------------------------------------------------------------------------
int main( int argc, char** argv )
{
    int batch_size = 1000;
    int n = 50;
    if (argc > 1)
        batch_size = atoi( argv[1] );
    if (argc > 2)
        n = atoi( argv[2] );
    printf( "batch_size %d, n %d\n", batch_size, n );

    int ld = n;
    double alpha = 3.1416;
    double beta  = 2.7183;

    printf( "init\n" );
    std::vector<double*> A_array( batch_size ),
                         B_array( batch_size ),
                         C_array( batch_size ),
                         D_array( batch_size );
    for (int i = 0; i < batch_size; ++i) {
        A_array[ i ] = new double[ ld*n ];
        B_array[ i ] = new double[ ld*n ];
        C_array[ i ] = new double[ ld*n ];
        D_array[ i ] = new double[ ld*n ];
        fill_rand( n, n, A_array[ i ], ld );
        fill_rand( n, n, B_array[ i ], ld );
        fill_rand( n, n, C_array[ i ], ld );
        std::copy( C_array[ i ], C_array[ i ] + ld*n, D_array[ i ] );
    }

    printf( "test\n" );
    for (int i = 0; i < batch_size; ++i) {
        cblas_dgemm( CblasColMajor, CblasNoTrans, CblasNoTrans, n, n, n,
                     alpha, A_array[ i ], ld, B_array[ i ], ld,
                     beta,  C_array[ i ], ld );
    }

    printf( "test OpenMP\n" );
    #pragma omp parallel for
    for (int i = 0; i < batch_size; ++i) {
        cblas_dgemm( CblasColMajor, CblasNoTrans, CblasNoTrans, n, n, n,
                     alpha, A_array[ i ], ld, B_array[ i ], ld,
                     beta,  D_array[ i ], ld );
    }

    printf( "compare\n" );
    double max_error = 0;
    for (int i = 0; i < batch_size; ++i) {
        // norm( D - C )
        cblas_daxpy( ld*n, -1.0, C_array[ i ], 1, D_array[ i ], 1 );
        double error = cblas_dnrm2( ld*n, D_array[ i ], 1 );
        max_error = max_nan( error, max_error );
    }
    printf( "max error %.2e\n", max_error );

    printf( "delete\n" );
    for (int i = 0; i < batch_size; ++i) {
        delete [] A_array[ i ];
        delete [] B_array[ i ];
        delete [] C_array[ i ];
    }

    printf( "done\n" );
    return 0;
}
```

Makefile
```
CXXFLAGS = -fPIC -fopenmp -Wall
LDFLAGS  = -fPIC -fopenmp
LIBS     = -lopenblas

src = test_gemm.cc
obj = test_gemm.o
exe = test_gemm

$(exe): $(obj)
	$(CXX) $(LDFLAGS) -o $@ $^ $(LIBS)

%.o: %.cc
	$(CXX) $(CXXFLAGS) -c -o $@ $<

clean:
	-rm -f $(exe) $(obj)
```

**Comment by martin-frbg** [comment]
Not reproducible so far (with 0.3.13 and current `develop` at least). Any special build options for the spack openblas, or does it need a certain number of cores/threads (greater than my current 12) for the error to appear ?

**Comment by mgates3** [comment]
I just did `spack install openblas@0.3.6`, etc. I switched from gcc 7.3.0 to 8.3.0 because of Spack dependencies.
```
spack find -f -l -v openblas 
==> 16 installed packages
-- linux-scientific7-haswell / gcc@7.3.0 ------------------------
mhoy5nx openblas@0.3.4%gcc ~consistent_fpcsr~ilp64+pic+shared threads=none
uuucrux openblas@0.3.5%gcc ~consistent_fpcsr~ilp64+pic+shared threads=none
mej4qpc openblas@0.3.6%gcc ~consistent_fpcsr~ilp64+pic+shared threads=none
nxuv6tp openblas@0.3.7%gcc ~consistent_fpcsr~ilp64+pic+shared threads=none
rtuzy5k openblas@0.3.8%gcc ~consistent_fpcsr~ilp64+pic+shared threads=none
ghrgxvi openblas@0.3.9%gcc ~consistent_fpcsr~ilp64+pic+shared threads=none
6yneoqc openblas@0.3.10%gcc ~consistent_fpcsr~ilp64+pic+shared threads=none

-- linux-scientific7-haswell / gcc@8.3.0 ------------------------
sqhjy67 openblas@0.3.11%gcc ~consistent_fpcsr~ilp64+pic+shared threads=none
zh3fv47 openblas@0.3.12%gcc ~consistent_fpcsr~ilp64+pic+shared threads=none
hekhb2d openblas@0.3.13%gcc ~consistent_fpcsr~ilp64+pic+shared threads=none
```

The errors definitely increase in frequency with more threads, as one might expect. Repeating the test 20 times with this script:
```
#!/bin/sh
for nt in 1 2 4 6 8 10 12 14 16 18 20; do
    export OMP_NUM_THREADS=${nt}
    echo "OMP_NUM_THREADS ${OMP_NUM_THREADS}"
    for i in {1..20}; do
        ./test_gemm >> out-${OMP_NUM_THREADS}
    done
done
```
errors happen 1 time for 8 threads, and more times with more threads, below. The max error (admittedly a basic check) was bad (non-zero) occasionally for even 2 threads, and always for ≥ 8 threads.
```
>> grep -c Bad out-*
out-01:0
out-02:0
out-04:0
out-06:0
out-08:1
out-10:0
out-12:4
out-14:3
out-16:19
out-18:50
out-20:89

>> grep -c 'max error [1-9]' out-*
out-01:0
out-02:2
out-04:15
out-06:16
out-08:20
out-10:20
out-12:20
out-14:20
out-16:20
out-18:20
out-20:20

>> grep 'max error [1-9]' out-02 
max error 2.69e+02
max error 3.13e+02
```
Setting `export OPENBLAS_NUM_THREADS=1` didn't change these results substantively.

**Comment by mgates3** [comment]
This is on 2 socket x 10 cores each, Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz. I can try on some other systems if you can't reproduce.

**Comment by brada4** [comment]
SPACK build options (nothing suspicious)
https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/openblas/package.py

mgates3: can you check with fedora's builtin openblas and toolchain as opposed to spack? even unproductive yum installation that makes end product run somehow is nice to have, at least to narrow search space of all package combinations of fedora and spack.
Also note that old versions cannot be changed anymore, it is about 2 screens of fixes since ones you see problem with.
https://github.com/xianyi/OpenBLAS/commits/fd7da56965a5af99f7ec2af161f0057f8b9d6bdb/driver/others/memory.c

The requirement between gcc7 or gcc8 is not from here, <=5 will not build skylakex code, and various 4.x that cannot do away with AVX are no longer distributed with production Linux.

**Comment by mgates3** [comment]
If I change to `spack install openblas@0.3.13 threads=openmp` or `threads=pthreads`, the problem appears to go away, whereas it exists with the default `threads=none`. That suggests the non-threaded version is not thread safe.

I also confirmed that I see the issue with `openblas@develop threads=none`, and not with `threads=openmp` or `threads=pthreads`.

I could compile OpenBLAS from source with the system's gcc 4.8.5, if that's what you're looking for. I'm not admin, so can't install system packages. The system's OpenBLAS appears to be 0.3.3, which works fine.

**Comment by martin-frbg** [comment]
Problem has not surfaced so far on  48-thread EPYC, nor on ARMV8 where the CI job gets scheduled on either 44 or 96 core hardware. If you are actually using a single-threaded build rather than one made with USE_OPENMP=1, chances are that using the build option USE_LOCKING will make it safe(r). Early 0.3.x may have been safe as it made heavy use of locking in all situations, leading to complaints about poor performance in genuine single-threaded applications...
