### ISSUE TITLE
cblas_csrot cblas_zdrot frontends missing; request implementation.

### ISSUE THREAD

**Issue by mu578** [xianyi/OpenBLAS#3063]
Just noticed while making bindings to native-openblas target within my project that `cblas_csrot` and `cblas_zdrot` are missing; would it be possible to add placeholders even if not fully optimized yet? as it requires a specific target treatment. Thank you.

references:

https://github.com/moe123/macadam/blob/master/macadam/lapack/blas/native/mc_blas_native_rot.h
https://github.com/moe123/macadam/blob/master/macadam/lapack/blas/mc_blas_rot.h
https://github.com/moe123/macadam/blob/master/macadam/lapack/mc_blas.h

```
/opt/local/bin/clang-mp-9.0 -x c -std=c99  \
-DMC_TARGET_BUILTIN_COMPLEX=1 blas_all_load.c \
-I/Users/moe/Projects/macadam -pedantic -Wno-newline-eof  \
-DMC_TARGET_BLAS_USE_NATIVE=1 \
-DMC_TARGET_BLAS_USE_OPENBLAS=1 \
-I /opt/local/include -L /opt/local/lib \
-lopenblas -Xclang -fopenmp -fopenmp-simd \
-DMC_TARGET_USE_OPENMP=1 \
-DMC_TARGET_OPENMP_FOR_SIMD=1 \
-L /opt/local/lib/libomp -lomp

nm /opt/local/lib/libopenblas.dylib | grep rot
000000000000d540 T _cblas_drot
000000000000d590 T _cblas_drotg
000000000000d670 T _cblas_drotm
000000000000db20 T _cblas_drotmg
0000000000003f60 T _cblas_srot
0000000000003fb0 T _cblas_srotg
0000000000004080 T _cblas_srotm
0000000000004520 T _cblas_srotmg
0000000000b70560 T _clarot_
000000000089fa80 T _crot_
0000000000016200 T _crotg_
00000000000161a0 T _csrot_
00000000003c86a0 t _csrot_k
0000000000b85e30 T _dlarot_
000000000000c850 T _drot_
000000000038d980 t _drot_k
000000000000c8b0 T _drotg_
000000000000c990 T _drotm_
000000000000ce40 T _drotmg_
                 U _mprotect
000000000002d6a0 t _qrot_
0000000000465160 t _qrot_k
000000000002d720 t _qrotg_
000000000002d7e0 t _qrotm_
000000000002db40 t _qrotmg_
0000000000b57910 T _slarot_
0000000000003200 T _srot_
0000000000355840 t _srot_k
0000000000003260 T _srotg_
0000000000003330 T _srotm_
00000000000037d0 T _srotmg_
0000000000031310 t _xqrot_
0000000000473820 t _xqrot_k
0000000000031390 t _xrotg_
0000000000021c80 T _zdrot_
000000000041eec0 t _zdrot_k
0000000000b9d750 T _zlarot_
0000000000a50c70 T _zrot_
0000000000021ce0 T _zrotg_

```

**Comment by martin-frbg** [comment]
Looks like an oversight, this being non-standard CBLAS functions (as far as the reference implementation is concerned - though it could be a "historical" oversight there as well, given that reference BLAS appears to have had CSROT and ZDROT since at least version 3.2.1, well before CBLAS was added)

**Comment by mu578** [comment]
Yes, you are right, it regards ATLAS introduction [historically speaking ] (1) and are not mandatory by standard, however, any over third-party major vendors are implementing them: Apple, IBM, Intel; i.e I guess to ensure `catlas_` compatibility.

\- 1 ATLAS extension: `cblas_csrot`, `cblas_zdrot`, `cblas_crotg`, `cblas_zrotg`.

```
void cblas_csrot(const int N, void * X, const int incX, void * Y, const int incY, const float c, const float s);
void cblas_zdrot(const int N, void * X, const int incX, void * Y, const int incY,  const double c, const double s);
void cblas_crotg(void * a, void * b, void * c, void * s); -> I don't know what they do here as cosine is real not complex.
void cblas_zrotg(void * a, void * b, void * c, void * s); -> ? some sizeof runtime check? Apple states it must be real;
need further investigations to confirm everyone understood the same; because here the intent would seem to be 
that `c` can be complex represented; else no need of a var passed by void reference i.e:

void cblas_crotg(void * a, void * b, float * c, void * s);
void cblas_zrotg(void * a, void * b, double * c, void * s);

```

**Comment by martin-frbg** [comment]
Right, we appear to be missing the cblas_(c/z)rotg from cblas.h and gmake-built libraries as well (and they, too, have been in the reference BLAS for ages but are missing from its CBLAS).

**Comment by martin-frbg** [comment]
Guess the strange `void` in the ATLAS(?) cblas.h are just harmless copypasta (IIRC what I read a few moments ago in the Atlas mailing list archive, all four functions were added following the same suggestion/patch in 2008)

**Comment by mu578** [comment]
maybe should upstream discussion to reference, to see what people have to say.
