### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by alexander-reeves** [xianyi/OpenBLAS#3065]
Hello. I am trying to build OpenBLAS0.3.13 and having navigated to the right directory and running: 

$ make clean 
$ gmake CC=gcc FC=gfortran

I get presented with an error: 
make[2]: *** No rule to make target `slaruv.f', needed by `slaruv.o'.  Stop.
make[1]: Leaving directory `/home/ar901/CLASS_PT/OpenBLAS0.3.13/lapack-netlib'
make: *** [netlib] Error 2

What am I doing wrong or is there some other conflicting library?

**Comment by martin-frbg** [comment]
Strange, looks like a download or filesystem problem - "slaruv.f" should be a regular file in lapack-netlib/SRC (size 18573 bytes)

**Comment by alexander-reeves** [comment]
Okay- I had a look in that file and I can't find slaruv.f so I'm going to try redownloading the library. Thanks!

**Comment by alexander-reeves** [comment]
All fixed now- this was a simple download issue. Cheers!
