### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by hlyj1995** [xianyi/OpenBLAS#3077]
hi,
   I'm using  Cortex-A53 in Xilinx ZCU102. When I set TARGET=CORTEXA53,I will meet some errors, but TARGET=ARMV8 is OK. However when I execute the second step "make PREFIX=./build install", the same error will appear again. I hope your help.
   ylh
`
error: 'SGEMM_DEFAULT_UNROLL_M' undeclared (first use in this function); did you mean 'QGEMM_DEFAULT_UNROLL_M'?
     printf("SGEMM_UNROLL_M=%d\n", SGEMM_DEFAULT_UNROLL_M);
                                   ^~~~~~~~~~~~~~~~~~~~~~
                                   QGEMM_DEFAULT_UNROLL_M
getarch_2nd.c:12:35: note: each undeclared identifier is reported only once for each function it appears in
getarch_2nd.c:13:35: error: 'SGEMM_DEFAULT_UNROLL_N' undeclared (first use in this function); did you mean 'XGEMM_DEFAULT_UNROLL_N'?
     printf("SGEMM_UNROLL_N=%d\n", SGEMM_DEFAULT_UNROLL_N);
                                   ^~~~~~~~~~~~~~~~~~~~~~
                                   XGEMM_DEFAULT_UNROLL_N
getarch_2nd.c:14:35: error: 'DGEMM_DEFAULT_UNROLL_M' undeclared (first use in this function); did you mean 'QGEMM_DEFAULT_UNROLL_M'?
     printf("DGEMM_UNROLL_M=%d\n", DGEMM_DEFAULT_UNROLL_M);
                                   ^~~~~~~~~~~~~~~~~~~~~~
                                   QGEMM_DEFAULT_UNROLL_M
getarch_2nd.c:15:35: error: 'DGEMM_DEFAULT_UNROLL_N' undeclared (first use in this function); did you mean 'XGEMM_DEFAULT_UNROLL_N'?
     printf("DGEMM_UNROLL_N=%d\n", DGEMM_DEFAULT_UNROLL_N);
                                   ^~~~~~~~~~~~~~~~~~~~~~
                                   XGEMM_DEFAULT_UNROLL_N
getarch_2nd.c:19:35: error: 'CGEMM_DEFAULT_UNROLL_M' undeclared (first use in this function); did you mean 'QGEMM_DEFAULT_UNROLL_M'?
     printf("CGEMM_UNROLL_M=%d\n", CGEMM_DEFAULT_UNROLL_M);
                                   ^~~~~~~~~~~~~~~~~~~~~~
                                   QGEMM_DEFAULT_UNROLL_M
getarch_2nd.c:20:35: error: 'CGEMM_DEFAULT_UNROLL_N' undeclared (first use in this function); did you mean 'XGEMM_DEFAULT_UNROLL_N'?
     printf("CGEMM_UNROLL_N=%d\n", CGEMM_DEFAULT_UNROLL_N);
                                   ^~~~~~~~~~~~~~~~~~~~~~
                                   XGEMM_DEFAULT_UNROLL_N
getarch_2nd.c:21:35: error: 'ZGEMM_DEFAULT_UNROLL_M' undeclared (first use in this function); did you mean 'QGEMM_DEFAULT_UNROLL_M'?
     printf("ZGEMM_UNROLL_M=%d\n", ZGEMM_DEFAULT_UNROLL_M);

`

**Comment by martin-frbg** [comment]
Try `make TARGET=ARMV8 PREFIX=./build install` . But the error is very strange - which version of OpenBLAS is this, that it does not recognize the A53 cpu ?

**Comment by hlyj1995** [comment]
> Try `make TARGET=ARMV8 PREFIX=./build install` . But the error is very strange - which version of OpenBLAS is this, that it does not recognize the A53 cpu ?

@martin-frbg 
Hi, thank you. The solution is useful. And the version  of OpenBLAS is latest. Maybe it's due to Yotco Linux. In addition, do you have any suggestions for linking Numpy to OpenBLAS , I am doing this for the first time.
 ylh

**Comment by martin-frbg** [comment]
I cannot reproduce this with 0.3.13 or current `develop`.
For NumPy, if you are building it yourself there is a file `site.cfg` in the sources where you can enter the location of your OpenBLAS installation. If you have a precompiled numpy and want to make sure that it uses your own build of OpenBLAS, you can use the NumPy "show_config()" command to find the location of the BLAS library that it uses. (Or run `ldd` on one of the libraries installed to your python site-packages as part of numpy, e.g. multiarray.so)

**Comment by hlyj1995** [comment]
> I cannot reproduce this with 0.3.13 or current `develop`.
> For NumPy, if you are building it yourself there is a file `site.cfg` in the sources where you can enter the location of your OpenBLAS installation. If you have a precompiled numpy and want to make sure that it uses your own build of OpenBLAS, you can use the NumPy "show_config()" command to find the location of the BLAS library that it uses. (Or run `ldd` on one of the libraries installed to your python site-packages as part of numpy, e.g. multiarray.so)

hi @martin-frbg 
Thanks for your advice, I will try it.
I guess my mistake is a few cases, because the Linux I built with xilinx's petalinux may be a little different.
ylh

**Comment by martin-frbg** [comment]
Just for your information, the SGEMM_DEFAULT_UNROLL_M and other parameters that it could not find are read from the file param.h, based on the cpu name that the `getarch` program wrote into config.h. And when you call `make` with a TARGET name, the getarch tool does not even have to read any system files or make system calls to identify the cpu. So I do not understand what could have gone wrong with the `make TARGET=CORTEXA53`

**Comment by martin-frbg** [comment]
BTW, as you wrote "the version of OpenBLAS is latest" - if you pulled from the `master` branch, that would explain the problem as that branch is severely outdated (and did not yet have a CortexA53 target). Development happens on the `develop` branch since 4 years ago, and releases are made from the 0.3.0 branch.
