### ISSUE TITLE
Limiting the number of ARM cortex targets with DYNAMIC is set to 1

### ISSUE THREAD

**Issue by Feakster** [xianyi/OpenBLAS#3081]
Is there a way of limiting the number of ARM cortex targets to just two when setting DYNAMIC to 1? I only want to build openblas for cortex A53 & A72.

**Comment by Feakster** [comment]
I guess you just comment out or remove the lines from Makefile.arm64 that are irrelevant?

**Comment by isuruf** [comment]
Yes, see note at https://github.com/xianyi/OpenBLAS#support-for-multiple-targets-in-a-single-library about `DYNAMIC_LIST`

**Comment by isuruf** [comment]
nvm, `DYNAMIC_LIST` doesn't work for ARM targets.

**Comment by martin-frbg** [comment]
Probably sufficient to copy the x86-centric DYNAMIC_LIST handling in Makefile.system around line 607 into the end of the `ifeq ($(ARCH), arm64)` section a few lines below, like 
```
ifdef DYNAMIC_LIST
override DYNAMIC_CORE = ARMV8 $(DYNAMIC_LIST)
endif
```
(or just cut down the list there to the types you actually need)

**Comment by Feakster** [comment]
Thanks for your help. I note the open pull request. Should I close this issue, or leave it open for now?

**Comment by martin-frbg** [comment]
Thanks for bringing this issue up. It will be closed automatically when I merge the pull request, but I need to add the corresponding changes for cmake-based builds first.
