### ISSUE TITLE
MSVS build recipe for CLAPACK

### ISSUE THREAD

**Issue by LuggerMan** [xianyi/OpenBLAS#3086]
Asking help for a recipe for building OpenBLAS without fortran, using CLAPACK and f2c. What keys do i need to specify to do this?

**Comment by martin-frbg** [comment]
When building OpenBLAS without a fortran compiler, the build files should detect that automatically and build only the BLAS parts. I assume you could then specify the libopenblas as the BLAS library to link to when building CLAPACK, but I have not tried it and CLAPACK is very old. Is there a specific reason why you want to avoid installing a fortran compiler ? (As far as I know, even the Intel compilers have recently become free to use)

**Comment by LuggerMan** [comment]
@martin-frbg, trying to reproduce this https://github.com/alphacep/vosk-api/commit/02b7312a006b7dc4daa75a1c865b19928c92d73c on windows msvs, it can use standart openblas but my app tells me it needs gfortran-3.dll, and i cant find it for msvs, supplying one from mingw gets me 0xc0000007b error

**Comment by martin-frbg** [comment]
Yes, you would probably need the libgfortran-3.dll that matches the mingw version that libopenblas.a was built with. You could try if it happens to be what we used quite some time ago for the prebuilt images provided on sourceforge.net (and linked from www.openblas.net)  at https://sourceforge.net/projects/openblas/files/v0.2.14 
libgfortran-3 does sound a bit old though ~~, so I wonder what version the OpenBLAS in that vosk-api commit is~~ 
EDIT: I misread that commit, the build options in the Dockerfile look correct for what you want to achieve, and should not create a dependency on a gfortran dll.To be extra sure you could add NOFORTRAN=1

**Comment by LuggerMan** [comment]
@martin-frbg LMAO, i used this https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-in-Microsoft-Visual-Studio, supplied fortran libs from miniconda and it started working! For the wiki part: for unexperienced users, please specify that u need to cd to vcvars64 and call it more verbose, it was not obvious for my stupid head. And add the thing that u need to supply some flang ddls to linker for openblas.lib to work. dlls were all found in c:\programdata\miniconda3. Issue solved, problem solved for now, but a handy illustration how to build with clapack and no fortran would be good, too.

i`m not using docker or python, just the c implementation, all with vs2019 =)

Thank you for help
