### ISSUE TITLE
OpenBLAS adds the build target to the name of the shared object output when "TARGET=ARMV8" is passed to make

### ISSUE THREAD

**Issue by Feakster** [xianyi/OpenBLAS#3089]
When using the following make command, the resulting shared object is incorrectly named as _"libopenblas_armv8p-r0.3.13.so"_:

```bash
make NO_STATIC=1 NO_LAPACK=1 NO_LAPACKE=1 NO_CBLAS=1 NO_AFFINITY=1 USE_OPENMP=1 \
       CFLAGS="$CPPFLAGS $CFLAGS" TARGET=ARMV8 \
       NUM_THREADS=64 MAJOR_VERSION=3 libs shared
```
The resulting shared object should be named _"libopenblasp-r0.3.13.so"_.

**Comment by martin-frbg** [comment]
This is a feature, and not specific to ARMV8 - when a TARGET is specified for compilation, its name gets appended to the library name. The internal SONAME remains as libopenblas.so.0, and appropriate symlinks are created.

**Comment by Feakster** [comment]
Is there a way to specify the name of the output?

**Comment by brada4** [comment]
Just rename the file to your liking?

**Comment by Feakster** [comment]
Happy to close this issue. But before I do, is adding the build target arch to the library name useful in some way?

**Comment by martin-frbg** [comment]
Probably as a way of distinguishing between builds for specific machines. I believe this behaviour has been in the Makefiles since the original GotoBLAS of ~15 years ago.

**Comment by Feakster** [comment]
Fair enough.
