### ISSUE TITLE
how can openblas supprt andoid x86_64

### ISSUE THREAD

**Issue by ghost** [xianyi/OpenBLAS#3097]

**Comment by martin-frbg** [comment]
The script near the middle of the wiki page on building for Android has a section with the settings for x86_64, please see 
https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android#alternative-script-which-was-tested-on-osx-with-ndk2136528147

**Comment by ghost** [comment]
> The script near the middle of the wiki page on building for Android has a section with the settings for x86_64, please see
> https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android#alternative-script-which-was-tested-on-osx-with-ndk2136528147

thank you , I will try it.
