### ISSUE TITLE
Incorrect detection of crosstool-ng-built compiler version after support for gcc 10 was added

### ISSUE THREAD

**Issue by patrickdepinguin** [xianyi/OpenBLAS#3099]
Commit b28db31429d9b3b6a57a182d79e63aafdd2843f1 made a fix in `f_check` to support GCC 10, by allowing multi-digit version numbers.

However, this causes incorrect detection in my case: I have a cross-compiler built with crosstool-ng, and the input used by f_check turns out to be:

```
	.cpu cortex-a53
	.eabi_attribute 28, 1
	.eabi_attribute 20, 1
	.eabi_attribute 21, 1
	.eabi_attribute 23, 3
	.eabi_attribute 24, 1
	.eabi_attribute 25, 1
	.eabi_attribute 26, 2
	.eabi_attribute 30, 2
	.eabi_attribute 34, 1
	.file	"ftest.f"
	.text
	.align	2
	.global	zhoge_
	.syntax unified
	.arm
	.fpu neon-fp-armv8
	.type	zhoge_, %function
zhoge_:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	vmov.i64	d16, #0	@ float
	vmov.f64	d0, d16
	vmov.f64	d1, d16
	bx	lr
	.size	zhoge_, .-zhoge_
	.ident	"GCC: (crosstool-NG 1.24.0) 7.4.0"
	.section	.note.GNU-stack,"",%progbits
```

Before mentioned commit, the crosstool-ng version would not be considered because it had a multi-digit element 24, but after the change it is now not detecting 7.4.0 but 1.24.0.

As a result of that, the variable `F_COMPILER` is no longer `GFORTRAN`, but `G77`.
This in turn causes `libopenblas.so` no longer to be linked with `libgfortran.so`, which causes an 'undefined reference' to `_gfortran_concat_string` when compiling an application linked to libopenblas.

When I revert the commit, I get correct behavior. Of course, it will break again when I update to gcc 10.

I don't know all the different possibilities you need to support, but the safest way to get the version of gfortran seems to me:
```
$ .../arm-cortex_a53-linux-gnueabi-gfortran -dumpversion
7.4.0
```
Is there a reason such check cannot be used?

**Comment by patrickdepinguin** [comment]
Looking at a possible solution, following works for me:
```
diff --git a/f_check b/f_check
index 79b24e2d..f3ca4e90 100644
--- a/f_check
+++ b/f_check
@@ -71,11 +71,9 @@ if ($compiler eq "") {
 
 	if ($data =~ /GNU/) {
 
-	    $data =~ /(\d+)\.(\d+).(\d+)/;
-	    $major = $1;
-	    $minor = $2;
-
-	    if ($major >= 4) {
+	    # gfortran supports -dumpversion while g77 does not
+	    $version = `$compiler -dumpversion 2> /dev/null`;
+	    if (!$?) {
 		$vendor = GFORTRAN;
 		$openmp = "-fopenmp";
 	    } else {
```

So instead of distinguishing gfortran from g77 based on the version itself, do it with the assumption that '-dumpversion' only exists in gfortran.

This change should still support gcc 10.

Would you accept this? Do you have another proposal?

**Comment by martin-frbg** [comment]
I suspect gfortran earlier than 7.x will not recognize that option either, perhaps it would be better to come up with something that eliminates everything between parentheses before the matching ? 
(An added `$data =~ s/\(+.*?\)+//g;` seems to do the trick for me)

**Comment by patrickdepinguin** [comment]
`-dumpversion` was already supported in gfortran 4.8.5 (tested on CentOS 7):
```
$ gfortran -dumpversion
4.8.5
```
But it seems that e.g. in gfortran versions like 4.0.3 and others, there was a '-dumpversion' which gave more verbose output, similar to --version.
Do we have to support older compilers?

Matching based on parentheses would also work. The string in parentheses is the 'pkgversion' passed at ./configure time of gcc, and will be placed in parentheses, since its introduction in gcc 4.3.0 (gcc commit 2f41c1d60b2435f9feb5105632eacd0b4ec57c28) .
