### ISSUE TITLE
Add optimized codepath to ZEN

### ISSUE THREAD

**Issue by MigMuc** [xianyi/OpenBLAS#3103]
Please add ZEN to the following  to the optimzed code path of the routines:

1. dasum.c
2. drot.c
3. sasum.c
4. srot.c

**Comment by martin-frbg** [comment]
right - I have this in a local fork but forgot to create a PR, will do so tomorrow. Also need to look into refining the cpu detection to allow passing `-march=znver2` (or `znver3`) to gcc.

**Comment by martin-frbg** [comment]
Just checked that adding `-march=znver...` does not appear to make a significant difference overall.
