### ISSUE TITLE
unknown type name 'cpu_set_t'  on SPARC Solaris 11 and gcc 10

### ISSUE THREAD

**Issue by dimpase** [xianyi/OpenBLAS#3108]
building OpenBlas 0.3.13, the first error is 
```
memory.c: In function 'get_num_procs':
memory.c:225:3: error: unknown type name 'cpu_set_t'
  225 |   cpu_set_t cpuset,*cpusetp;
      |   ^~~~~~~~~
```
indeed, there is no `cpu_set_t`, there is `cpuset_t` only (in `sys/cpuvars.h`)

**Comment by martin-frbg** [comment]
Strange, this must have been wrong for something like 3 years at least then.(Unless it is specific to gcc10 -but wouldn't that be OS headers ? Confused as I got a successful build on solaris11 in the gcc compile farm last autumn.) Quickest workaround is probably to build with NO_AFFINITY=1

**Comment by dimpase** [comment]
I would be surprised if it worked - perhaps you included a header with workaround...
Several places point to the need to do something like
```#!c
#include <sys/cpuvar.h>
typedef cpuset_t cpu_set_t;
```
including [cpuvar.h](http://web.mit.edu/freebsd/head/sys/cddl/contrib/opensolaris/uts/common/sys/cpuvar.h). I have too little understanding of all these flags around there to come with a good patch

**Comment by martin-frbg** [comment]
Hmm. I see the gccfarm machine has a gcc configured with includedir=/opt/csw/include, maybe they put compatibility headers there. OTOH it seems you were compiling with USE_TLS=1 (as you encountered errors near the top of memory.c), which is a bit less well tested ?

**Comment by martin-frbg** [comment]
Yes, USE_TLS is key here - I forgot to apply a fix to that branch of memory.c (which has two implementations of the memory management code under a fat ugly ifdef), the cpu_set_t stuff should be moved under the `#if defined(__GLIBC_PREREQ)`
as seen from line 1770 onwards. I'll upload a fix tomorrow.
