### ISSUE TITLE
Issues with flang detection

### ISSUE THREAD

**Issue by dnoan** [xianyi/OpenBLAS#3123]
Recently I tried building OpenBLAS with Classic Flang 11. I got error messages like this:
```
clang-11: error: no such file or directory: 'version'
clang-11: error: no such file or directory: '11'
clang-11: error: no input files
```
I figured out that the error comes from `Makefile.system` where it tries to detect if Flang is provided by AMD AOCC so that it can add the `-fno-unroll-loops` flag. I installed AMD AOCC and interestingly, it never added the flag. More over, during compilation I got a lot of errors like this:

`/bin/sh: AMD: command not found`

AMD AOCC Flang behaves like this:
```
flang --version | head -1
AMD clang version 11.0.0 (CLANG: AOCC_2.3.0-Build#85 2020_11_10) (based on LLVM Mirror.Version.11.0.0)
```

Classic Flang behaves like this:
```
flang --version | head -1
clang version 11.1.0
```

LLVM Flang behaves like this:
```
flang --version | head -1

f18 compiler (under development), version 11.0.1
```

**Comment by martin-frbg** [comment]
Which version are you trying to build?

**Comment by dnoan** [comment]
I've tried with both 0.3.13 and git. In addition, when building the test programs with Flang, I get a lot of warnings:

```
clang-11: warning: argument unused during compilation: '-Mrecursive' [-Wunused-command-line-argument]
clang-11: warning: argument unused during compilation: '-Kieee' [-Wunused-command-line-argument]
```

I guess that `-Mrecursive` and `-Kieee` are only relevant when compiling the code and not when linking it.

**Comment by dnoan** [comment]
Thanks! It works now with both AOCC and Classic Flang.

**Comment by martin-frbg** [comment]
Yes, sorry - not sure what happened there - seems I mis-copied the original solution from a non-networked box and only made it worse with later changes.
