### ISSUE TITLE
how do I determine if I need LAPACK in openblas

### ISSUE THREAD

**Issue by chinyu0704** [xianyi/OpenBLAS#3124]
hi,
I want to speed up the building process. I found that if I set NO_LAPACK = 1, the building time is significantly reduced. 

I use Numpy which depends on openblas.  Could anybody tell me whether can I set NO_LAPACK = 1; if not, can I set NO_LAPACKE = 1 (C interfaface support? ). 

FYI, I have a separate rpm "lapack" in my env.

**Comment by martin-frbg** [comment]
You're probably better off asking in the numpy project rather than here, but I suspect you will need both LAPACK and its C interface. Also I am not sure I understand why the time needed for building OpenBLAS is important - surely you would not
need to do this every time you use (or even modify) NumPy ?

**Comment by chinyu0704** [comment]
@martin-frbg thanks for your kind reply.  I will also open an issue in the numpy proj.

**Comment by brada4** [comment]
Statement from numpy documentation:
> NumPy does not require any external linear algebra libraries to be installed. However, if these are available, NumPy’s setup script can detect them and use them for building. A number of different LAPACK library setups can be used, including optimized LAPACK libraries such as ATLAS, MKL or the Accelerate/vecLib framework on OS X.

From scipy documentation:
> BLAS and LAPACK libraries (optional but strongly recommended for NumPy, required for SciPy): typically ATLAS + OpenBLAS, or MKL.

I dont think "opening issue" will help in any way. It is clearly written long ago.

**Comment by chinyu0704** [comment]
@brada4 thanks for your kind reply. But still, your relpy doesn't make it clear that  "do I must build lapack routiines in openblas lib" or ”do I need C interfaces for LAPACK in openblas lib” when using Numpy.

thanks anyway!

**Comment by Qiyu8** [comment]
you can use the pre-built binary wheels from [PyPI](https://pypi.org/project/numpy/#files), both numpy and openblas can be used directly.

**Comment by chinyu0704** [comment]
> you can use the pre-built binary wheels from [PyPI](https://pypi.org/project/numpy/#files), both numpy and openblas can be used directly.

**Comment by chinyu0704** [comment]
@Qiyu8 thanks for your reply, SAITAMA. 
I was told there is no ARM version of this PyPi and my main use situation is on ARM. 

thanks anyway.

**Comment by Qiyu8** [comment]
The ARMV8/AArch64 version has released in PyPI, try search keyword 'AArch64' in that page.

**Comment by chinyu0704** [comment]
@Qiyu8 okay, thank you. Nevertheless, I still wonder if I use openblas for Numpy, could I cut lapack off from openblas.

**Comment by martin-frbg** [comment]
Look, you will need LAPACK for anything but the most simple matrix operations. And I expect you will only need to compile OpenBLAS once, so what is the point of reducing its build time ?
