### ISSUE TITLE
Compiled issue on Macos

### ISSUE THREAD

**Issue by crazyi** [xianyi/OpenBLAS#3127]
`cmake .. -DUSE_OPENMP=1 -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 -DBUILD_SHARED_LIBS=1 -DUSE_THREAD=1 -DCMAKE_MACOSX_RPATH=1`

Above is my setup for openblas, and the output is:

```
[ 83%] Linking Fortran shared library lib/libopenblas.dylib
collect2: fatal error: execvp: Argument list too long
compilation terminated.
make[2]: *** [lib/libopenblas.0.3.dylib] Error 1
make[1]: *** [CMakeFiles/openblas.dir/all] Error 2
make: *** [all] Error 2
```

Any idea for the issue?

**Comment by martin-frbg** [comment]
This has come up before (#855) and appears to be an OSX or CMAKE limitation. You can try if adding
`-DCMAKE_Fortran_USE_RESPONSE_FILE_FOR_OBJECTS=1` helps.

**Comment by crazyi** [comment]
@martin-frbg Thanks, your suggestion fixes my issue, I think it is should be added to the FAQ

**Comment by martin-frbg** [comment]
Done, thanks for confirming.
