### ISSUE TITLE
Using FMA intrinsics without HAVE_FMA3 

### ISSUE THREAD

**Issue by xandox** [xianyi/OpenBLAS#3128]
Hi All.

I try to upgrade openblas port in vcpkg to 0.3.13. 
And faced problem with building for x64-osx. 
I attach build logs
[openblas-x64-odx-build-failure.zip](https://github.com/xianyi/OpenBLAS/files/6084718/openblas-x64-odx-build-failure.zip)

The problem is that `getarch` does not detect FMA instruction set and as result `-mfma` switch did not append to compiler arguments. But some code still use `FMA` instructions without check HAVE_FMA3

**Comment by martin-frbg** [comment]
I believe this is already fixed in the current `develop` branch, soon to become 0.3.14

**Comment by martin-frbg** [comment]
Actually on reviewing your logs I am no longer sure this is already fixed (a distantly related issue was fixed by #3042, but the more general fma option handling was revised already before 0.3.13). I do find it a bit strange that the cpu would report AVX/AVX2 capability but not FMA3 though - is this a VM config problem ?

**Comment by xandox** [comment]
>is this a VM config problem ?

Very probably

**Comment by martin-frbg** [comment]
Probably safe to assume FMA3 capability in getarch when AVX2 is present (though not with AVX alone) - unless your VM actually lacks FMA for whatever reason (?)

**Comment by xandox** [comment]
Probably. I thought about it myself. I really do not know what is reason FMA3 absents. 
I will ask guys from vcpkg for reasons and may be they can fix it.

But this is still reasonable to assume FAM3 or wrap code with checks HAVE_FMA3. How you think?

**Comment by martin-frbg** [comment]
Not sure how messy this would get. For srot, it is fairly simple as it just needs an additional `#if defined(HAVE_FMA3)...#endif` around the `#include` of the microkernel at the top of kernel/x86_64/srot.c

**Comment by brada4** [comment]
Please ask first in place where you got these parches from:
```
Checking patch cmake/prebuild.cmake...
Hunk #1 succeeded at 39 (offset 2 lines).
Hunk #2 succeeded at 577 (offset 264 lines).
Hunk #3 succeeded at 604 (offset 264 lines).
Checking patch cmake/system.cmake...
Applied patch cmake/prebuild.cmake cleanly.
Applied patch cmake/system.cmake cleanly.
```
200 lines off is most likely a mistake no matter what initial intent of patches is.

**Comment by martin-frbg** [comment]
@brada4 completely unrelated I think - one can check the patches in the ports/openblas section of the vcpkg project

**Comment by brada4** [comment]
NO_AVX2=1 should avoid FMA3 on Haswell, FMA3 is present and assumed to be present in all haswell CPUs based on CPUID generation numbers, it is not detected separately at build time, nor at run time.
What kind of virtualisation is that? AVX1 xsave should handle FMA3-reachable registers, no need to mask CPUID or instruction in a VM.

**Comment by martin-frbg** [comment]
@brada4 it _is_ deteczed separately at  build time, and directs the addition of `-fma` to the gcc options (which has become necessary through the recent use of intrinsics)

**Comment by martin-frbg** [comment]
(reproduced by commenting out the HAVE_FMA3 output in getarch's cpuid_x86.c, so there should be no similar bugs left)
