### ISSUE TITLE
I believe this is a misuse of USE_OPENMP

### ISSUE THREAD

**Issue by chinyu0704** [xianyi/OpenBLAS#3131]
hi,
I believe openmp is a different threading program comparing to pthread. Each time we choose one of them if we want threaded openblas. But, I found that the openblas.spec in centos 8 has following compiling option:
`COMMON="%{optflags} **_-fPIC -fopenmp -pthread_**"                                     
FCOMMON="$COMMON -frecursive -fdefault-integer-8"
                          
make -C openmp64   $TARGET USE_THREAD=1 USE_OPENMP=1 FC=gfortran CC=gcc COMMON_OPT="$COMMON" FCOMMON_OPT="$F    COMMON" $NMAX LIBPREFIX="libopenblaso64"   $AVX $LAPACKE INTERFACE64=1 CPP_THREAD_SAFETY_TEST=1`

I believe USE_THREAD defaults to using pthread and USE_OPENMP use threads too but openmp overides pthread. So the quoted code is a misuse: that is, _**Centos compile openblas with both "-fopenmp" and "-pthread".**_ 

Correct me if I am wrong. Appreciate for your help. thanks!
the spec file: https://git.centos.org/rpms/openblas/blob/c8-beta/f/SPECS/openblas.spec
line:430

**Comment by brada4** [comment]
Here [Upstream without BETA tags etc](https://src.fedoraproject.org/rpms/openblas/blob/rawhide/f/openblas.spec)
Most likely fedora's openmp is same wrapper around pthreads, so that compiler flag is deemed necessary over there.

**Comment by chinyu0704** [comment]
@brada4 thanks brada. I got your point. That somehow explained why those flags are needed here.

**Comment by martin-frbg** [comment]
GNU OpenMP (libgomp) is implemented on top of pthreads - and I think that is the case for both LLVM's and Intel's implementation as well.
