### ISSUE TITLE
OpenBLAS on MacOSX

### ISSUE THREAD

**Issue by vickysharma0812** [xianyi/OpenBLAS#3132]
Hello everyone,
I need a small help.

I tried to build OpenBLAS from source using CMake with following option:

```
cmake -S ./ -B build -DCMAKE_INSTALL_PREFIX=${EASIFEM_EXTPKGS} -DBUILD_WITHOUT_LAPACK=OFF -DBUILD_WITHOUT_CBLAS=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DNOFORTRAN=OFF
```

I my project when I try following:

```
find_package( OpenBLAS 0.3 CONFIG REQUIRED )
#possible COMPONENTS are: pthread, static, shared, serial, openmp
if(OpenBLAS_FOUND)
  message(STATUS "OpenBLAS_LIBRARIES found")
  include(CMakePrintHelpers)
  cmake_print_properties(
    TARGETS
      OpenBLAS::OpenBLAS
    PROPERTIES
      INTERFACE_INCLUDE_DIRECTORIES
      INTERFACE_LINK_LIBRARIES
 )
```

then I get nothing.

```
-- OpenBLAS_LIBRARIES found
   OpenBLAS::OpenBLAS.INTERFACE_INCLUDE_DIRECTORIES = "/Users/vikassharma/.easifem/extpkgs/include/openblas"
   OpenBLAS::OpenBLAS.INTERFACE_LINK_LIBRARIES = <NOTFOUND>
   OpenBLAS::OpenBLAS.INTERFACE_COMPILE_OPTIONS = <NOTFOUND>
```

It seems I am not able to find the libraries.

Any help in this matter would be great.

Regards
Vikas

**Comment by martin-frbg** [comment]
Have you checked that the library (and ~~the pkgconfig file openblas.pc~~ cmake support file OpenBLASConfig.cmake) actually got installed to where you wanted them to be ? (Not sure if the compile options would get written to the file currently)

**Comment by brada4** [comment]
Did the library build after cmake?

**Comment by vickysharma0812** [comment]
> Have you checked that the library (and ~~the pkgconfig file openblas.pc~~ cmake support file OpenBLASConfig.cmake) actually got installed to where you wanted them to be ? (Not sure if the compile options would get written to the file currently)

@martin-frbg 
The lib installs at right place outside the build directory (I use CMAKE_INSTALL_PREFIX.

what I have noticed is the following.

- If I add 'find_package(LAPACK REQUIRED)' just after 'find_package(OpenBLAS ...' then it correctly sets 'BLAS_LIBRARIES' and 'LAPACK_LIBRARIES' to 'libOpenBlas'. However, 'OpenBLAS_LIBRARIES' still empty.

Regards
Vikas

**Comment by vickysharma0812** [comment]
> Did the library build after cmake?

@brada4 library builds correctly at the right place. however, the 'OpenBLAS_LIBRARY' variable is not set.

**Comment by brada4** [comment]
Variables should be named OpenBLAS xor OpenBLAS_NOTFOUND
If you use FindLAPACK built into cmake you get BLA_vendor set to OpenBLAS.

**Comment by martin-frbg** [comment]
Possibly related to https://gitlab.kitware.com/cmake/cmake/-/issues/21779
(But it may well be that the generated OpenBLASConfig.cmake is not sufficient for your needs - this was created following suggestions in #1529 but I am by no means an expert in cmake and find some of the official documentation rather confusing.)

**Comment by vickysharma0812** [comment]
> Variables should be named OpenBLAS xor OpenBLAS_NOTFOUND
> If you use FindLAPACK built into cmake you get BLA_vendor set to OpenBLAS.

@brada4 

In my case FindLAPACK is not setting `BLA_VENDOR`  to `OpenBLAS` but  to `All` (which is strange).

**Comment by vickysharma0812** [comment]
> Possibly related to https://gitlab.kitware.com/cmake/cmake/-/issues/21779
> (But it may well be that the generated OpenBLASConfig.cmake is not sufficient for your needs - this was created following suggestions in #1529 but I am by no means an expert in cmake and find some of the official documentation rather confusing.)

I can understand what your are saying @martin-frbg . That is why now I am using the following to use OpenBLAS.

- First I have set the environment variable `$EASIFEM_EXTPKGS` where OpenBLAS is located on my system.

Then I use following snippet in my CMakeLists.txt

```cmake
set(CMAKE_PREFIX_PATH "$ENV{EASIFEM_EXTPKGS}")
set(BLA_VENDOR "OpenBLAS")
find_package( LAPACK REQUIRED )
if( LAPACK_FOUND )
  message(STATUS "LAPACK_LIBRARIES found")
  message("LAPACK_LIBRARIES: ${LAPACK_LIBRARIES}")
  message("BLAS_LIBRARIES: ${BLAS_LIBRARIES}")
  message("BLA_vendor: ${BLA_VENDOR}")
endif() 
```

This works as desired, and I get following output.

```
-- Found LAPACK: /Users/vikassharma/.easifem/extpkgs/lib/libopenblas.dylib;/Users/vikassharma/.easifem/extpkgs/lib/libopenblas.dylib  
-- LAPACK_LIBRARIES found
LAPACK_LIBRARIES: /Users/vikassharma/.easifem/extpkgs/lib/libopenblas.dylib;/Users/vikassharma/.easifem/extpkgs/lib/libopenblas.dylib
BLAS_LIBRARIES: /Users/vikassharma/.easifem/extpkgs/lib/libopenblas.dylib
BLA_vendor: OpenBLAS
-- BLA_VENDOR : OpenBLAS
```

I am closing this issue.

**Comment by brada4** [comment]
Great to hear, hopefully we integrate this in wiki if someone looks for same thing again.
