### ISSUE TITLE
Wrong Result (all 0s) for Blas32 on Skylake

### ISSUE THREAD

**Issue by tdmtrader** [xianyi/OpenBLAS#3152]
I have had no issues until I rebuilt the library from source yesterday morning. I am using the same dockerfile and code as before, and I now get an empty result (all 0s) from Blas32 Gemm. I am using OpenBLAS from within Go, via the gonum netlib implementation. My previous build, which worked without issues, was from late February.

I can only reproduce this on Skylake (which I'm using via GCP's n2-... machines). On my colleague's and my personal PC's all is working well.  The code also works fine with no blas implementation. I had been compiling with Dynamic Arch=1 (and threading=0, locking=1), but I dropped all of those option and compiled it directly on the server with no luck. The problem goes away if I switch to blas64 (which unfortunately does not work for my application).

I've attached a zip containing the minimum reproducible example I could come up with, which contains a few lines of Go, the corresponding go.mod/go.sum files, as well as a dockerfile (since I must run it on GCP) and script to setup blas. I appreciate any guidance anyone can offer.

[Matrix32Empty.zip](https://github.com/xianyi/OpenBLAS/files/6159996/Matrix32Empty.zip)

**Comment by martin-frbg** [comment]
Which compiler (and version), and can you narrow down the "late February" date of your last working build please ? I do not see any test failures on my local SkylakeX system, and there (should not) have not been any major code changes for that platform lately.

**Comment by tdmtrader** [comment]
Both builds (last working and current) were done with gcc/g++ v 8.3. Unfortunately I did not try anything between then and yesterday. That was commit d12a2 on Feb 26. I will attempt to pull that commit and confirm that I can still build and run it successfully.

I should clarify when I say "I can only reproduce this on Skylake"- I have reproduced it consistently on GCP's n2- machines, and I do not have the issue on my or my colleagues personal PCs. I have not tried other cloud hardware, so I cannot confirm that it does not happen on other servers with different architectures, only that I have not seen it on personal hardware.

Edit: I can confirm that d12a2 is working. I'm going to try to pinpoint when it stopped.

**Comment by martin-frbg** [comment]
Very strange - most of the changes since Feb 26 were in completely unrelated areas like IBM POWER10 support or the LAPACK testsuite. Unfortunately I do not really know Go so I cannot use your docker example to do the `git bisect` myself. All the SGEMM tests I have run did not turn up anything bad on my SkylakeX (but that is only a low-end machine with very few cores).
Just to confirm - by "your or your colleagues personal PCs" you refer to hardware other than SkylakeX (which would most likely be "Haswell" as far as OpenBLAS is concerned), that is, without AVX512 instruction support ?

**Comment by tdmtrader** [comment]
I'm going through a bisect now. I should have a specific commit for you shortly. 

I am running on Haswell; I do not know what specific hardware my colleagues are on, but they mostly use laptops, so unlikely that anyone has AVX512.

EDIT: I had a problem with bisect. ef0238b seems ok. I should know more soon.

**Comment by martin-frbg** [comment]
Thanks. ef0238b itself should not affect SkylakeX , and I (still) see no likely candidates between it and the Feb 24 version. Probably bloody obvious once you point it out though..

**Comment by tdmtrader** [comment]
> Thanks. [ef0238b](https://github.com/xianyi/OpenBLAS/commit/ef0238ba2bad6f065f36240dae6fdc00a49b37c5) itself should not affect SkylakeX , and I (still) see no likely candidates between it and the Feb 24 version. Probably bloody obvious once you point it out though..

Got it. It was commit 093456. [After ef00238b- sorry for the confusion, I had made a mistake with bisect]. 

The change is specific to SkylakeX and Cooperlake, so this definitely makes sense as the source of the error, although I'm not familiar enough with OpenBLAS to understand why this was a problem and how to fix it. Thanks, and please let me know what I can do to help out.

**Comment by martin-frbg** [comment]
Augh.  Took me a while to realize what is happening here. I have looked at 0934568 several times before and thought there should be no functional difference for SkylakeX between the "before" and "after" - the `include <immintrin.h>` is only needed for the code inside the `#if defined(SKYLAKEX)...` and its presence when compiling only the dummy function in the `#else` branch broke compilation with fairly ancient versions of gcc. There is "nothing" in common.h itself - except that it includes config.h where the `#define SKYLAKEX` sits. Now if you had a time machine that I could borrow for a minute...

**Comment by tdmtrader** [comment]
Thanks so much- I can confirm that this fixed the issue on my end.  Thanks again for all of your great work on this project.
