### ISSUE TITLE
int32 multiplication overflow at a fat side of 32bit input

### ISSUE THREAD

**Issue by brada4** [xianyi/OpenBLAS#3160]
I think both inputs should be cast to native pointer prior to multiplication (they are checked unsigned already at that red point)
https://lgtm.com/projects/g/xianyi/OpenBLAS/latest/files/interface/imatcopy.c?sort=name&dir=ASC&mode=heatmap
https://lgtm.com/projects/g/xianyi/OpenBLAS/latest/files/interface/zimatcopy.c?sort=name&dir=ASC&mode=heatmap

**Comment by martin-frbg** [comment]
Would you mind proposing a patch ? (Though I suspect any lda or ldb large enough to cause an overflow here would fail elsewhere a bit later when not building with INTERFACE64=1)

**Comment by brada4** [comment]
This would get one bit more before failing, will do tomorrow, like in 10h
