### ISSUE TITLE
Makefile:139: * OpenBLAS: Detecting CPU failed. Please set TARGET explicitly, e.g. make TARGET=your_cpu_target. Please read README for the detail.. Stop.

### ISSUE THREAD

**Issue by tianshuo78520a** [xianyi/OpenBLAS#3162]
I bought a MAC machine of a M1 chip, I have reported an error in compile, OpenBLAS has not supported M1? I am using version 0.3.7

**Comment by brada4** [comment]
OpenBLAS did not support M1 years before its release. Please use version 0.3.13 at least.

**Comment by tianshuo78520a** [comment]
Thank you for your reply, I will try 0.3.13

**Comment by brada4** [comment]
`TARGET=ARMV8` should work with old versions, That is not tuned for anything, just aarch64 basic ISA.

**Comment by tianshuo78520a** [comment]
Thank you very much for your help, let me succeed.
