### ISSUE TITLE
AVX512 sgemm kernel compilation failed with "inline assembly requires more registers than available" on ClangCL

### ISSUE THREAD

**Issue by LYP951018** [xianyi/OpenBLAS#3176]
I don't know why the project could be successfully compiled in CI...

> 8>  In file included from C:\Users\liuyu\Documents\Code\OpenBLAS\build\kernel\CMakeFiles\sgemm_kernel_COOPERLAKE.c:7:
8>  C:/Users/liuyu/Documents/Code/OpenBLAS/kernel/x86_64/sgemm_kernel_16x4_skylakex_3.c(504,34): error : inline assembly requires more registers than available
8>  C:/Users/liuyu/Documents/Code/OpenBLAS/kernel/x86_64/sgemm_kernel_16x4_skylakex_3.c(454,5): message : expanded from macro 'COMPUTE_n24'

My CMake arguments:

> cmake .. -G "Visual Studio 16 2019" -T ClangCL -DCMAKE_Fortran_COMPILER=flang -DBUILD_WITHOUT_LAPACK=no -DNOFORTRAN=0 -DDYNAMIC_ARCH=ON -DCMAKE_BUILD_TYPE=Release -DNO_LAPACK=1 -DNOFORTRAN=1

**Comment by martin-frbg** [comment]
So far I have only encountered this clang error when using CMAKE_BUILD_TYPE=Debug (or correspondingly low optimize setting), maybe it depends on the version of LLVM how severe the register pressure is ?

**Comment by martin-frbg** [comment]
Can you get it to compile when you change line 504 in sgemm_kernel_16x4_skylakex_3.c from calling `COMPUTE_n24` back to `COMPUTE(24)` like it was done in revision _2 of that kernel file ? (If so, we could add another ugly `ifdef` to work around this)

**Comment by LYP951018** [comment]
Thanks for the reply. `COMPUTE(24)` works.

**Comment by j-horner-c4x** [comment]
I encountered this with when compiling with clang (14 and 15) on Ubuntu 22.04 (WSL 2) with vcpkg:
```
.../external/vcpkg/buildtrees/openblas/src/v0.3.25-dc6d649124.clean/kernel/x86_64/sgemm_kernel_16x4_skylakex_3.c:505:34: error: inline assembly requires more registers than available
    for(;n_count>23;n_count-=24) COMPUTE(24)
```
It's the debug version which fails. GCC seems fine:
```
[cmake] Building openblas[core,dynamic-arch]:x64-linux...
[cmake] -- Installing port from location: .../external/vcpkg/buildtrees/versioning_/versions/openblas/4c2a355bc21475a2a4a69f6a3c227f54efc5c425
[cmake] -- Using cached xianyi-OpenBLAS-v0.3.25.tar.gz.
[cmake] -- Cleaning sources at .../external/vcpkg/buildtrees/openblas/src/v0.3.25-dc6d649124.clean. Use --editable to skip cleaning for the packages you specify.
[cmake] -- Extracting source .../external/vcpkg/downloads/xianyi-OpenBLAS-v0.3.25.tar.gz
[cmake] -- Applying patch uwp.patch
[cmake] -- Applying patch fix-redefinition-function.patch
[cmake] -- Applying patch install-tools.patch
[cmake] -- Using source at .../external/vcpkg/buildtrees/openblas/src/v0.3.25-dc6d649124.clean
[cmake] -- Configuring x64-linux
[cmake] -- Building x64-linux-dbg
[cmake] CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
[cmake]     Command failed: .../cmake/cmake-3.28.3-linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j21
[cmake]     Working Directory:.../external/vcpkg/buildtrees/openblas/x64-linux-dbg
[cmake]     See logs for more information:
[cmake]       .../external/vcpkg/buildtrees/openblas/install-x64-linux-dbg-out.log
```
There are several other similar error messages about `COMPUTE(1), COMPUTE(2),COMPUTE(4),...,COMPUTE(20)`
