### ISSUE TITLE
OpenBLAS on KVM

### ISSUE THREAD

**Issue by cganterh** [xianyi/OpenBLAS#318]
I am trying to use numpy in a KVM machine. And I'm getting this error:

```
>>> import numpy
GotoBLAS : Architecture Initialization failed. No initialization function found.
```

Which I think may be a problem of OpenBLAS.
Anyone have an idea of what may be causing it?

You can find more details of my question in [stackoverflow](http://stackoverflow.com/questions/20058653/gotoblas-error-when-installing-matplotlib-with-pip-in-a-virtualenv-on-debian-whe).

**Comment by oncletom** [comment]
I confirm that I had to compile OpenBLAS manually from source with the `DYNAMIC_ARCH=1`.

My docker instructions are the following:

```
RUN apt-get install gfortran -y
RUN wget -qO- https://github.com/xianyi/OpenBLAS/archive/v0.2.14.tar.gz \
        | tar xz \
        && cd ./OpenBLAS-0.2.14 \
        && make DYNAMIC_ARCH=1 USE_THREAD=1 FC=gfortran \
        && make install PREFIX=/usr/local \
        && rm -rf /tmp/OpenBLAS-0.2.14
```

But at least it works on my KVM based host, and it is predictable at build time which is great.

PS: as a side note, if I did `make TARGET=NEHALEM USE_THREAD=1 FC=gfortran`, I encountered compilation errors. Maybe worth a separate issue?

PS2: awaiting for the sysadmin to change the KVM CPU configuration – will keep this topic updated.

**Comment by knedlsepp** [comment]
I'm trying to compile openblas inside a QEMU VM. I get an error:
```
getarch_2nd.c:12:35: error: ‘SGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function)
     printf("SGEMM_UNROLL_M=%d\n", SGEMM_DEFAULT_UNROLL_M);
```
It seems the CPU does not get detected, but I was hoping that it should still work as I added `DYNAMIC_ARCH=1` to the build env:
I'm using `DYNAMIC_ARCH=1 NUM_THREADS=64 FC=gfortran CC=gcc BINARY=64 USE_OPENMP=1 INTERFACE64=1
It seems to compile if I add `TARGET=NEHALEM`. Is this a good idea?

**Comment by xianyi** [comment]
@knedlsepp , I think it may choose a slow kernel when detecting failed on QEMU VM.

**Comment by knedlsepp** [comment]
@xianyi: Thanks for your quick reply. I'd mostly be interested in building inside the VM, but then using the resulting binary on a different architecture. Would this be possible using `DYNAMIC_ARCH`?
