### ISSUE TITLE
Segmentation fault with openblas >0.3.10 and numpy

### ISSUE THREAD

**Issue by Vringe** [xianyi/OpenBLAS#3180]
I'm using `numpy-1.16.6` with `openblas-0.3.13` which causes a segmentation fault while importing.
Not sure if it is `numpy` or `openblas` related. But what I found out is that with `openblas-0.3.13`, much more virtual memory is required.

Here is how I tested it:

```
$ ulimit -v
2097152
$ python -c "import numpy as np"
Segmentation fault
$ ulimit -v 3670016
$ python -c "import numpy as np"
$
```

Downgrading to `openblas-0.3.10` also fixes this issue.

Also mentioned here: https://github.com/numpy/numpy/issues/18631

**Comment by martin-frbg** [comment]
OpenBLAS versions after 0.3.10 default to using a larger buffer for multihreaded GEMM to accomodate larger problem sizes. This can be adjusted at build time via the BUFFERSIZE parameter - recent numpy releases make use of this (setting BUFFERSIZE=20 to restore the pre-0.3.10 behaviour), which is probably why you were asked to upgrade to 1.20.x in the numpy ticket
(i.e. basically a duplicate of #2970 and https://github.com/numpy/numpy/issues/18141)

**Comment by Vringe** [comment]
Thank you. Can confirm that setting BUFFERSIZE to 20 fixes the issue.
