### ISSUE TITLE
Different results between ARM compiled version and x86_64 compiled version

### ISSUE THREAD

**Issue by FanGao0526** [xianyi/OpenBLAS#3182]
Hi, there

I'm calling the cblas_sgemm function on both ARM and X86_64 platforms, and I found the difference of output result.

OpenBLAS 0.3.9
ARM platform info:
arm64, using gcc (version 7.3.0), tsv110p
x86_64 platform info:
x86_64, using gcc (version 7.3.0), sandybridgep

The compile command：
`cmake -DNOFORTRAN=1 NO_LAPACKE=1 -DCMAKE_BUILD_TYPE=Release`
Then
`make -j8`
It's not totally different, seems like accuracy issues.
![image](https://user-images.githubusercontent.com/35786404/114810637-188b9200-9ddf-11eb-906f-8dd252faaac8.png)

But as you guys can see from the pic, 8.9728e+12 and 8.97279e+12 do vary a lot.
Any suggestions?
THX

**Comment by martin-frbg** [comment]
Which version, which cpus, which compilers, are the input data exactly the same (or are they generated in your program) ?
Consider using cblas_dgemm if you need higher precision.

**Comment by FanGao0526** [comment]
> Which version, which cpus, which compilers, are the input data exactly the same (or are they generated in your program) ?
> Consider using cblas_dgemm if you need higher precision.

Hi, thanks for the suggestion. The data are the same, so the only diff is the cpus, since the gcc 7.3.0 is used to compile for both platforms. I may not be able to use cblas_dgemm limited by the project, but I will have a try first.

**Comment by brada4** [comment]
Different architectures yield different compiler optimisations, of 23 bits of significand precision you lose one bit in log(slightly less than)2(n) float operations, i.e take log2(biggest if M and K) ,you get double of that calculations, half add, half mul, normally 7th decimal place would nibble, because effects cancel out, but it gets radical when you calculate sum of an array, and compare to sum of same array sorted one way and other way.
Normally NetLIB BLAS will perform equally, but if you apply compiler optimisations like -O2 by default, math is re-ordered and vectorized into e.g. FMA, and the rounding effect accumulates to different sides on AARCH vs x86. 
Why do I even mention FMA - it does multiply and add in a single step avoiding interim rounding, result will be more accurate numerically, but certainly different from where interim rounding was employed.

Shortest illustration of rounding trims:
```
> 0.07*100-7
[1] 8.881784e-16
```

**Comment by FanGao0526** [comment]
> Different architectures yield different compiler optimisations, of 23 bits of significand precision you lose one bit in log(slightly less than)2(n) float operations, i.e take log2(biggest if M and K) ,you get double of that calculations, half add, half mul, normally 7th decimal place would nibble, because effects cancel out, but it gets radical when you calculate sum of an array, and compare to sum of same array sorted one way and other way.
> Normally NetLIB BLAS will perform equally, but if you apply compiler optimisations like -O2 by default, math is re-ordered and vectorized into e.g. FMA, and the rounding effect accumulates to different sides on AARCH vs x86.
> Why do I even mention FMA - it does multiply and add in a single step avoiding interim rounding, result will be more accurate numerically, but certainly different from where interim rounding was employed.
> 
> Shortest illustration of rounding trims:
> 
> ```
> > 0.07*100-7
> [1] 8.881784e-16
> ```

Thanks, brada! I still want to ask, if I have to stick on sgemm, and I need to support several cpus (let's take it as arm64 and x86 for this case), any tricks to avoid the diff? Like a compile flag or some other settings?

**Comment by brada4** [comment]
What you compare is single bit significand precision difference. Just make comparisons to accomodate (those numbers are equal - `abs(a-b)<precision` that and printouts to hide it( just 5 decimal digits - dont you see it after rounding to precision) . Thats how floating point works. No stress.
To get repeatable results you should use unoptimized NetLIB BLAS, at least check new platform against pre-computed values.
To get 20 extra bits to round or so you should use double in all calculations, i.e cast up, then back down
Bias of this kind will certainly show itself between FMA and no-FMA x86_64 processors. There is nothing that can be changed. It has to be accomodated in calling problem.

**Comment by martin-frbg** [comment]
Different number of threads on the two systems will probably affect associativity already (different rounding of intermediate results), apart from and in addition to any differences in floating point hardware and the instructions used in the respective SGEMM kernels.
