### ISSUE TITLE
Error compilling OpenBLAS 0.3.14

### ISSUE THREAD

**Issue by jpsalada** [xianyi/OpenBLAS#3186]
Dear all,

I have configured OpenBlas with the following cmake command: 
cmake .. -G "Ninja"  -DCMAKE_MT=mt -DBUILD_SHARED_LIBS=ON  -DDYNAMIC_ARCH=ON -DCMAKE_BUILD_TYPE=Release

When building I am getting the following error:

Building C object driver\level3\CMakeFiles\driver_level3.dir\CMakeFiles\dsyrk_kernel_U.c.obj
FAILED: driver/level3/CMakeFiles/driver_level3.dir/CMakeFiles/dsyrk_kernel_U.c.obj
C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x64\cl.exe  /nologo  -I..\ -I. /DWIN32 /D_WINDOWS /W3  -DDYNAMIC_ARCH -DNO_LAPACK -DNO_LAPACKE -DSMP_SERVER -DMAX_CPU_NUMBER=8 -DMAX_PARALLEL_NUMBER=1 -DNO_AFFINITY -DVERSION="\"0.3.14\"" -DBUILD_SINGLE -DBUILD_DOUBLE -DBUILD_COMPLEX -DBUILD_COMPLEX16 /MD /O2 /Ob2 /DNDEBUG /showIncludes /Fodriver\level3\CMakeFiles\driver_level3.dir\CMakeFiles\dsyrk_kernel_U.c.obj /Fddriver\level3\CMakeFiles\driver_level3.dir\ /FS -c driver\level3\CMakeFiles\dsyrk_kernel_U.c
C:/dev/openblas2/OpenBLAS-0.3.14/driver/level3/syrk_kernel.c(65): error C2057: expected constant expression
C:/dev/openblas2/OpenBLAS-0.3.14/driver/level3/syrk_kernel.c(65): error C2466: cannot allocate an array of constant size 0
C:/dev/openblas2/OpenBLAS-0.3.14/driver/level3/syrk_kernel.c(65): error C2133: 'subbuffer': unknown size

Can you please help?

Thank you

**Comment by martin-frbg** [comment]
Unfortunately the MSVC compiler is unsuitable for building the optimized BLAS kernels, many of which contain assembly in a form that MSVC does not support.
Please build with TARGET=GENERIC instead of DYNAMIC_ARCH, or use a different compiler (mingw,icc,clang,...)

(the actual error seems to be the result of the parameter GEMM_UNROLL_MN not being defined, which "should not happen" unless something went wrong much earlier)

**Comment by jpsalada** [comment]
If I configure clang compiler I get the following error during the configuration:

>cmake .. -G "Ninja"   -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DCMAKE_Fortran_COMPILER=flang -DNOFORTRAN=0  -DDYNAMIC_ARCH=ON -DCMAKE_BUILD_TYPE=Release


```  

CMake Error at C:/dev/miniconda3/Library/share/cmake-3.20/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "C:/dev/miniconda3/Library/bin/clang-cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

Make Error at C:/dev/miniconda3/Library/share/cmake-3.20/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "C:/dev/miniconda3/Library/bin/clang-cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/dev/openblas2/OpenBLAS-0.3.14/build/CMakeFiles/CMakeTmp

    Run Build Command(s):C:/dev/miniconda3/Library/bin/ninja.exe cmTC_6186d && [1/2] Building C object CMakeFiles\cmTC_6186d.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_6186d.exe
    FAILED: cmTC_6186d.exe
    cmd.exe /C "cd . && C:\dev\miniconda3\Library\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_6186d.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x64\link.exe /nologo CMakeFiles\cmTC_6186d.dir\testCCompiler.c.obj  /out:cmTC_6186d.exe /implib:cmTC_6186d.lib /pdb:cmTC_6186d.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    LINK Pass 1: command "C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x64\link.exe /nologo CMakeFiles\cmTC_6186d.dir\testCCompiler.c.obj /out:cmTC_6186d.exe /implib:cmTC_6186d.lib /pdb:cmTC_6186d.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\cmTC_6186d.dir/intermediate.manifest CMakeFiles\cmTC_6186d.dir/manifest.res" failed (exit code 1104) with the following output:
    LINK : fatal error LNK1104: cannot open file 'kernel32.lib'

`` 
    ninja: build stopped: subcommand failed.

**Comment by martin-frbg** [comment]
That looks like a pretty generic error with the library path configuration, perhaps you just need to run vcvars64.bat (or work from a VS command prompt) despite using clang now (which still integrates with the msvc environment)

**Comment by brada4** [comment]
You need windows SDK installed in addition to MSVC tools to get kernel32.lib etc linker information files.

**Comment by jpsalada** [comment]
I deleted everything, ran the steps in the wiki and compiled everythin with success. thanks for the support guys!
