### ISSUE TITLE
build android falied on mac.

### ISSUE THREAD

**Issue by bugmany** [xianyi/OpenBLAS#3194]
version:
release-0.3.0

build command:
make TARGET=ARMV7 ONLY_CBLAS=1 AR=ar CC="clang ${CLANG_FLAGS}" HOSTCC=gcc ARM_SOFTFP_ABI=1 USE_THREAD=0 NUM_THREADS=64 -j4

error log:
make[1]: *** No rule to make target `generic/trmm_uncopy_.c', needed by `strmm_iunucopy.o'.  Stop.
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/Users/bm/dev/OpenBLAS/kernel'
make: *** [libs] Error 1
can anyone help me?

**Comment by martin-frbg** [comment]
Please try with a more recent version, and with the suggestions from the wiki page
https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android

**Comment by brada4** [comment]
I dont think there are any 64-core 32bit ARM processors around, even less running Android.

**Comment by martin-frbg** [comment]
> I dont think there are any 64-core 32bit ARM processors around, even less running Android.

That should not really matter - at worst it will waste a bit of memory for threads that will never be used at runtime.
The actual issue boils down to SGEMM_UNROLL_M not being defined for the ARMV7 target, which simply should not happen. This _may_ have been a bug in the 0.3.0 release which was created almost exactly three years ago.

**Comment by martin-frbg** [comment]
@bugmany did you try with 0.3.15 yet ?

**Comment by bugmany** [comment]
hello @martin-frbg,
i've tried 0.3.14, the issue exist yet, but i can not see 0.3.15, so can not try it.
thanks

**Comment by brada4** [comment]
It is right here:
https://github.com/xianyi/OpenBLAS/releases/

**Comment by martin-frbg** [comment]
Sorry for the confusion - I do not own a Mac, and the information in the top part of the (user-contributed) wiki page appears to be outdated again, at least as far as the OSX version of the NDK is concerned. 
The following line (copied from the "alternative script" on the wiki page) works on the CI host:
```
make TARGET=ARMV7 ONLY_CBLAS=1 CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi21-clang AR=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-ar HOSTCC=gcc ARM_SOFTFP_ABI=1 -j4
```
where ANDROID_NDK_HOME would obviously need to be tailored to the install location - in my test on Azure, I got it from homebrew (with `brew install --cask android-ndk`) which put it in /usr/local/share/android-ndk

**Comment by bugmany** [comment]
hello @brada4,
i 've tried build 0.3.15 passed, thanks.
