### ISSUE TITLE
Compiling OpenBLAS using the Nvidia compiler

### ISSUE THREAD

**Issue by tomoppe** [xianyi/OpenBLAS#3200]
Dear Sir:
I am having trouble compiling OpenBLAS using the Nvidia compiler, formerly the PGI compiler.  It does not like "-march=native".  In the file "Makefile.system", there is code to exclude "pgcc" from using this flag:

# On x86_64 build getarch with march=native unless the compiler is PGI. This is required to detect AVX512 support in getarch.
ifeq ($(HOSTARCH), x86_64)
ifeq ($(findstring pgcc,$(HOSTCC)),)
GETARCH_FLAGS += -march=native
endif
endif

Does anyone know the syntax for excluding both "pgcc" and "nvc" from adding the "-march=native" flag.  Please excuse me if this issue has already been addressed.    I am using 

Version 0.3.13
 12-Dec-2020

**Comment by martin-frbg** [comment]
nvc support was added shortly after the 0.3.13 release. Probably best to fetch a snapshot of the current `develop` branch or wait a (hopefully) few days for 0.3.15.

**Comment by tomoppe** [comment]
Dr. Kroeker,

Thank you for your helpful response.  I will wait for 0.3.15 to be released.

Tom Oppe

-----------------------------------------------------------------------------
Thomas Oppe | SAIC
Benchmarking Team Computational Scientist | ERDC DSRC
601-642-4516

________________________________________

**Comment by martin-frbg** [comment]
0.3.15 released now
