### ISSUE TITLE
A bug in zrotg for Mac arm64

### ISSUE THREAD

**Issue by ghost** [xianyi/OpenBLAS#3201]
Running a simple C code for testing zrotg, I found out that the implementation of this function on Mac arm64 is incorrect.
Here is the code:
```
#include <stdio.h>
void  zrotg_ (double *, double *, double *, double *);
int main() {
  double a[2] = {4.0, 0.0};
  double x[2] = {0.0, 0.0};
  double c = 0.0;
  double s[2] = {0.0, 0.0};

  zrotg_(a, x, &c, s);
  printf("a = (%lf, %lf)\nx = (%lf, %lf)\n", a[0], a[1], x[0], x[1]);
  printf("c = %lf\ns = (%lf, %lf)\n", c, s[0], s[1]);
  return 0;
}
```
It should return this result:
```
a = (4.000000, 0.000000)
x = (0.000000, 0.000000)
c = 1.000000
s = (0.000000, 0.000000)
```
but instead it returns
```
a = (nan, nan)
x = (0.000000, 0.000000)
c = nan
s = (nan, nan)
```
The bug is in the file `interface/zrotg.c` line 93:
```
    scale = (bb_i / bb_r);
```
because `bb_i` and `bb_r` are zero. Therefore, `scale` becomes `nan`.

**Comment by martin-frbg** [comment]
Curious - the interface code is shared among all architectures, and zrotg.c has not changed much from the original GotoBLAS. So this bug must have been present for something like 15 years (zrotg.c has a special codepath for x86/x86_64 that is not affected though).
