### ISSUE TITLE
DYNAMIC_ARCH for ARMV8 fails

### ISSUE THREAD

**Issue by dnoan** [xianyi/OpenBLAS#3218]
I am building a DYNAMIC_ARCH version of OpenBLAS on ARMv8.0-a. All archs build except for THUNDERX3T110. It gives me the following type of errors:

```
Assembler messages:
Error: unknown architecture `armv8.3-a'
Error: unrecognized option -march=armv8.3-a
```
I tried with different compilers, the latest being GCC 11.1, and it always fails.

When I remove THUNDERX3T110 from `Makefile.system` and from `driver/others/dynamic_arm64.c`, the build works.

**Comment by martin-frbg** [comment]
Makefile.arm64 already checks that the GCC version is at least 10.x before it applies the `-march=armv8.3-a` option. It is probably your `binutils` package installation that is too old then.

**Comment by dnoan** [comment]
I guess it could be due to too old version of binutils. I compile on Red Hat Enterprise Linux 7.9. Is there some nice way to exclude THUNDERX3T110 support?

**Comment by martin-frbg** [comment]
Depends on your definition of "nice" - you could add a DYNAMIC_LIST argument like so:
`-DYNAMIC_ARCH=1 DYNAMIC_LIST='ARMV8 CORTEXA53 CORTEXA57 CORTEXA72 CORTEXA73 NEOVERSEN1 EMAG8180 FALKOR THUNDERX THUNDERX2T99 TSV110'`

**Comment by dnoan** [comment]
Thanks! I upgraded from binutils 2.27 to 2.28 and it solved the problem.
