### ISSUE TITLE
f18 non-compiler called flang.

### ISSUE THREAD

**Issue by brada4** [xianyi/OpenBLAS#3221]
Seen present on fedora rawhide.
Is it worth adding some poisonous flang parameter at f_check to assure it is really working really flang?

Probably this: https://github.com/flang-compiler/f18/issues/290

Version ID (first line is BLANK, second is like version, both written to stderr)
```
[blasb@fedora OpenBLAS]$ flang --version

f18 compiler (under development), version 12.0.0
[blasb@fedora OpenBLAS]$
```
And the repeated barf building:
```
gfortran: error: unrecognized command-line option ‘-Mrecursive’; did you mean ‘-frecursive’?
gfortran: error: unrecognized command-line option ‘-Kieee’
execvp(gfortran) failed: 
flang: in /home/blasb/OpenBLAS/lapack-netlib/SRC, f18 failed with exit status 0: /usr/bin/f18 -module-suffix .f18.mod -intrinsic-module-directory /usr/include/flang -O2 -Mrecursive -Kieee -Wall -fPIC -msse3 -mssse3 -msse4.1 -mavx -c -o DEPRECATED/ztzrqf.o DEPRECATED/ztzrqf.f
```

**Comment by martin-frbg** [comment]
Not sure if f_check needs to deal with this - an unstable/unfinished distribution installing an unstable/unfinished compiler, unless everybody thinks it is a great idea to alias one compiler name to a completely different project with incompatible option syntax. (I assume compiling with FC=gfortran will still work, and probably provide a more reliable result than mangling the source to f18's internal representation and back)

**Comment by brada4** [comment]
I was happy to see almost production-like flang, turned out just a superfluous dream....

**Comment by martin-frbg** [comment]
Probably as much the LLVM project's fault to include it under the name of a known-working compiler before it is actually ready, as it is the fedora maintainer's dubious decision to provide it in rawhide. The problem I see with adding another test in f_check is that it would provide only limited improvement - an error message about an unusable compiler - over the observed build failure unless we also try to figure out what it is configured to use. 
On the other hand it appears that this f18-flang may be provided by fedora34 already, so may be noticed by a wider audience

**Comment by brada4** [comment]
Lets permit somebody to report it. It is already coming of age there.
https://koji.fedoraproject.org/koji/packageinfo?packageID=32294

**Comment by martin-frbg** [comment]
Did a quick test - in Fedora 34, flang (i.e. f18) can be installed without gfortran being present, but unsurprisingly it fails to compile anything. With gfortran available, the build system picks up gcc and gfortran as the defautl compilers.Onlywhen flang is forced as FC will things get messy

**Comment by brada4** [comment]
When you have no gfortran (or any other fortran compiler I presume) it is detected even though early in the build things fail (that is invoking `$FC` without any parameters)
```
cat: ftest.s: No such file or directory
cat: ftest.c: No such file or directory
cat: ftest3.s: No such file or directory
cat: ftest3.c: No such file or directory
```

**Comment by martin-frbg** [comment]
Yes, I noticed that too - the f_check picks up that there is a thing called `flang` but that thing does not produce any output.  I wonder if there is a sane way to map from the f18 wrapper to the actual compiler it will be calling, but getting that information to override the FC named on the commandline leads down the well-known rabbit hole of recursive inclusion (or not) of the OpenBLAS Makefiles.

**Comment by brada4** [comment]
>  The external compiler is specified by the F18_FC environment variable. The default is 'gfortran'.

The problem is it returns zero no matter what fails under the hood, thats very make-unfriendly.

I could not find a way to make it characterize backend (gfortran).

Best I can think of would be to break it setting F18_FC to say `false` or something cross-platform (? find?) and check if flang still produces output module, but again thats not future-proof as one day it might attempt compilation on its own.

**Comment by martin-frbg** [comment]
Seems it already has its own quirks - when I hack the makefiles to assume gfortran, the lapack build fails as the ETIME intrinsic is not recognized by the f18 frontend (wanting CPU_TIME instead, like PGI and NAG).

**Comment by brada4** [comment]
Scary, I dont see any documentation on it past conference presentations, none of them strictly says it works or not or how.
