### ISSUE TITLE
Question about OpenBLAS dependents.

### ISSUE THREAD

**Issue by gkarpa** [xianyi/OpenBLAS#3248]
Hi all, and congratulations on your tremendous work.

As a developer of an application that uses OpenBLAS heavily (dynamically linked), I'm having a hard time determining whether I should rebuild all of its dependencies (executables, or other dlls that I use like scalapack, hypre, etc) every time I want to use a newer version of OpenBLAS, or just replacing with a new OpenBLAS dll will be good to go without any additional concerns. Is there any way to determine this except from thorough testing? Maybe any compatibility tables or general information that I have missed?

If it matters, I maintain two different builds, one for Linux and one for Windows via MinGW64 with MSYS2. Thanks a lot in advance!

Regards,
George

**Comment by martin-frbg** [comment]
Normally just replacing the dynamic library should be sufficient.

**Comment by brada4** [comment]
All the testing should be checking that there is only single BLAS DLL in same process (MKL, ATLAS, BLIS, NetLIB, NVBLAS), and that no other DLL (or EXE) includes own rebuild of BLAS and LAPACK functions. That causes "undefined behaviour" indpendently of BLAS implementation(s) involved. Usually visual tools like proexp.exe or depends.exe are sufficient to figure it out.

For the rest - yes, it is just one DLL to replace, you can even use generic DLL name and let users alternate if they find it useful.

**Comment by gkarpa** [comment]
Thank you both, great help!
