### ISSUE TITLE
Core dumps when executing TRSM call with latest GCC (gcc12)

### ISSUE THREAD

**Issue by austinpagan** [xianyi/OpenBLAS#3256]
While doing some regression testing on the _new_ GCC12 compiler (built from trunk), we discovered core dumps when executing TRSM calls.

These core dumps occur both in our power-optimized TRSM code and in the generic TRSM code.

We determined that they are caused by array address offsets being computed incorrectly as negative values.

We found that if we modify the code to ensure that all computations of pointer addresses into the A array are done using exclusively "long int" variables (no mixing "int" and "long int"), and if we also slow down the computations with an if-test containing a conditional print statement, then the problem goes away.

We do NOT advocate such a modification as a patch or a workaround.
We view it as evidence that there _might_ be a compiler bug involved, particularly because it only happens with this new, not-yet-released compiler.
We solicit your thoughts on the matter.

**Comment by austinpagan** [comment]
For completeness, here's a "git diff" showing the changes we made to eight files
(the LN, LT, RN and RT files for generic TRSM and for power-optimized TRSM):
[diff_file.txt](https://github.com/xianyi/OpenBLAS/files/6600963/diff_file.txt)

**Comment by brada4** [comment]
So you just changed one type to BLASLONG and added some casts? Similar code is about everywhere, though BLASLONG style in most places.
Does it fails same way with release trains i.e 11.1 and/or 10.3 ?

**Comment by martin-frbg** [comment]
I'd think the conditional printf is preventing some over-zealous optimization - but if this only happens with a development snapshot that must be early stage1 at best, I would prefer to ignore it at this time (i.e. defer to the gcc team).

**Comment by austinpagan** [comment]
@brada4, gcc11 and gc10.3 are working fine. No failures of this nature have been noted.

**Comment by brada4** [comment]
This should wait until mis-compilation gets into stable branches, or hopefully not.

**Comment by martin-frbg** [comment]
Err, "gets into stable branches" may be a bit late for this, but there will surely be a stage3 in about five months where it might make more sense to check for this again. At least I see nothing obviously wrong with the current TRSM code (and nor did any of the other compilers in use on various platforms) - going from int to long may be sensible in the future but I do not think this is directly related to the miscalculation or overflow of the offsets.

**Comment by brada4** [comment]
Maybe it is a 32/64 confusion in some other place, that it gets unitialized upper half somehow by means of wild optimisations and chokes. It has to be checked if at all against same gcc with lower optimisation levels, not here.

**Comment by austinpagan** [comment]
We have NEWS:
After opening a GCC Bugzilla issue, we were quickly notified of a suspicious commit that might have been the problem in GCC12.  My colleague Peter Bergner quickly created a compile with that commit removed, and the problem indeed goes away entirely.  Definitely a GCC problem, and definitely identified to be part of a bad commit.  

We will leave this issue OPEN until we have a GCC12 which runs OpenBLAS cleanly, and then we will close this issue.

**Comment by austinpagan** [comment]
And, even better NEWS:

We had a fix for this problem that has already been uploaded to GCC12, but Peter Bergner was unaware of it!
This problem no longer occurs in GCC12, and I'm closing this issue now.
