### ISSUE TITLE
Openblas version 3.15_1 packaged with Brew on M1 apple silicon target does not include lapacke functions

### ISSUE THREAD

**Issue by Nelson-numerical-software** [xianyi/OpenBLAS#3257]
Maybe more a trouble for brew mainteners but it is blocking.
Eigen3 uses lapacke.
Boring Workaround build lapacke on local machine...

**Comment by martin-frbg** [comment]
This should probably be reported to https://github.com/Homebrew/homebrew-core/issues - packaging is out of the scope here and I do not know if/why they would want to build without LAPACKE support.
