### ISSUE TITLE
Add OpenBLAS to Chocolatey for Windows installations

### ISSUE THREAD

**Issue by j-c-cook** [xianyi/OpenBLAS#3262]
[Chocolatey](https://community.chocolatey.org/) is the Windows implementation of `apt-get` (Linux) or `brew-install` (Darwin). 

Could we add the ability to `choco install OpenBLAS`?

**Comment by martin-frbg** [comment]
OpenBLAS is BSD-licensed, as long as Chocolatey does not conflict with that it should be alright (but out of scope here). Note that pure MSVC builds of OpenBLAS will mostly consist of generic C code rather than hand-optimized assembly kernels, so using mingw for the build should be preferable.
