### ISSUE TITLE
Default architecture settings

### ISSUE THREAD

**Issue by tly000** [xianyi/OpenBLAS#3267]
I am a bit confused by the default architecture selected by OpenBLAS. I built a static version of the library with MinGW and one with Visual Studio. The one built with MinGW crashed (illegal instruction) on an old notebook while the other one works. Is there a difference in the default architecture settings when using GCC vs. MSVC?

**Comment by martin-frbg** [comment]
MSVC does not support the style of assembly (inline assembly statements, AT&T syntax) used in many of the optimized BLAS kernels, so a MSVC build defaults to TARGET=GENERIC with plain C sources (which has the side effect to make it portable, but also much less performant).
If you want your MinGW build to be portable, compile with DYNAMIC_ARCH=1 (and DYNAMIC_OLDER=1 if you plan to support really old pc hardware) which will include optimized code for several targets with automatic selection at runtime.

**Comment by tly000** [comment]
Thanks! is this fact documented somewhere?

**Comment by martin-frbg** [comment]
The README.md describes the DYNAMIC_ARCH option and links to the wiki for building with MSVC and its limitations.
Note that you will want to combine DYNAMIC_ARCH=1 with a TARGET (for all the common code) set to the oldest cpu you expect to encounter, e.g. `DYNAMIC_ARCH=1 TARGET=NEHALEM` or `DYNAMIC_ARCH=1 TARGET=GENERIC`, else the common code may again contain instructions that are only supported on the build host cpu.

**Comment by tly000** [comment]
Thank you for the information.
