### ISSUE TITLE
install manifest

### ISSUE THREAD

**Issue by agarza5724** [xianyi/OpenBLAS#3268]
Install Manifest Request:
please leave a list of what files to copy over after successful compilation on windows 10 using TDMGCC (mingw variant).

**Comment by martin-frbg** [comment]
There is a `(c)make install` at the end of the build process, as with many (most ?) other software. Please use it, as some files (headers) are only created in this step. The install location can be set with the `PREFIX=` option, it will contain the usual hierarchy of bin,lib and include folders.

**Comment by agarza5724** [comment]
thank you martin! i'll give that a try
