### ISSUE TITLE
Risc-v Cross compile error

### ISSUE THREAD

**Issue by chen-coco** [xianyi/OpenBLAS#3277]
hi, i'm try make for riscv,but find something error  :(
make HOSTCC=gcc TARGET=RISCV64_GENERIC CC=riscv64-unknown-linux-gnu-gcc FC=riscv64-unknown-linux-gnu-gfortran
cc1: error: '-march=native': ISA string must begin with rv32 or rv64
cc1: error: requested ABI requires '-march' to subsume the 'D' extension
cc1: error: ABI requires '-march=rv64'
cc1: error: '-march=native': ISA string must begin with rv32 or rv64
cc1: error: requested ABI requires '-march' to subsume the 'D' extension
cc1: error: ABI requires '-march=rv64'
make: *** [Makefile.prebuild:70: getarch] Error 1
Makefile.system:1351: Makefile.: No such file or directory
make: *** No rule to make target 'Makefile.'.  Stop.

riscv64-unknown-linux for rv64g

**Comment by brada4** [comment]
You can comment out one line in Makefile.system as a workaround.
```
# On x86_64 build getarch with march=native unless the compiler is PGI. This is required to detect AVX512 support in getarch.
ifeq ($(HOSTARCH), x86_64)
ifeq ($(findstring pgcc,$(HOSTCC))$(findstring nvc,$(HOSTCC)),)
// GETARCH_FLAGS += -march=native
endif
endif
```

**Comment by martin-frbg** [comment]
@brada4 that line is only there for the host compiler, used in building the getarch tool. The problem must be elsewhere.

**Comment by martin-frbg** [comment]
What is your build host, is it x86_64 or something else ? And which release of OpenBLAS are you trying to build here ? (I assume either 0.3.15 or the `develop` branch - do not use the `master` branch as that is no longer updated)

**Comment by chen-coco** [comment]
> What is your build host, is it x86_64 or something else ? And which release of OpenBLAS are you trying to build here ? (I assume either 0.3.15 or the `develop` branch - do not use the `master` branch as that is no longer updated)

build host for x86_64 Ubuntu20.04  ,relrese for 0.3.15 or the develop branch

**Comment by martin-frbg** [comment]
Which cross-compiler do you use on Ubuntu ? (I am not getting the error on openSuSE, but the cross-riscv64-elf toolchain there appears to be broken or incomplete, missing headers later in the build)

**Comment by chen-coco** [comment]
> Which cross-compiler do you use on Ubuntu ? (I am not getting the error on openSuSE, but the cross-riscv64-elf toolchain there appears to be broken or incomplete, missing headers later in the build)

i use riscv64-unknown-linux-gnu -arch=rv64g
```
`https://github.com/riscv/riscv-gnu-toolchain`
./configure --prefix=/opt/riscv --with-arch=rv64g
make linux

```

**Comment by martin-frbg** [comment]
Thanks for the additional information. I still get different errors with a build from source (errors related to the toolchain missing some headers), but I guess it is safe to say that your `gcc` (as used in HOSTCC) probably does not point to the host (x86_64) compiler at the moment but to the toolchain compiler instead.

**Comment by brada4** [comment]
Try `HOSTCC=/usr/bin/gcc` (or clang , or gcc-10 or something like that)

**Comment by martin-frbg** [comment]
Right, that was what I was trying to say (and my build went fine once I noticed I had omitted the `linux` option on the make command to build the crosscompiler - a bit exhausted today)

**Comment by chen-coco** [comment]
I'm sorry to trouble you all， thanks everyone。
i try to use `HOSTCC=/usr/bin/gc`  but it was the same
![image](https://user-images.githubusercontent.com/50285422/122491505-c2251480-d016-11eb-9208-18f83cdd4628.png)
so i change to use CBLAS lib to Cross compile
it‘s work！
But I still can't error this mistake
Thank  again

**Comment by martin-frbg** [comment]
The error message suggests that /usr/bin/gcc on your system is a riscv compiler as well, maybe something went wrong with the installation of riscv64-unknown-linux-gnu-gcc and it put a link `/usr/bin/gcc -> riscv64-unknown-linux-gnu-gcc` ? /usr/bin/gcc should normally be a compiler for your host system (x86_64), and the OpenBLAS Makefile needs to build a few tools on the host system to configure the build even when cross-compiling.

**Comment by chen-coco** [comment]
> The error message suggests that /usr/bin/gcc on your system is a riscv compiler as well, maybe something went wrong with the installation of riscv64-unknown-linux-gnu-gcc and it put a link `/usr/bin/gcc -> riscv64-unknown-linux-gnu-gcc` ? /usr/bin/gcc should normally be a compiler for your host system (x86_64), and the OpenBLAS Makefile needs to build a few tools on the host system to configure the build even when cross-compiling.

yes，gcc->riscv64-unknown-linux-gnu-gcc
change gcc for x86_x64 will different
![image](https://user-images.githubusercontent.com/50285422/122509252-083da080-d036-11eb-9235-afce5062776e.png)

**Comment by martin-frbg** [comment]
No idea where the `-march=tigerlake` and `-mtune=tigerlake` is coming from - this is definitely not set by the OpenBLAS build, all we do is set `-march=native` for building the `getarch` tool. Perhaps you have set CFLAGS in your environment ?
(`-march=tigerlake` is supported by gcc version 10 and newer)

**Comment by chen-coco** [comment]
> No idea where the `-march=tigerlake` and `-mtune=tigerlake` is coming from - this is definitely not set by the OpenBLAS build, all we do is set `-march=native` for building the `getarch` tool. Perhaps you have set CFLAGS in your environment ?
> (`-march=tigerlake` is supported by gcc version 10 and newer)

your are right！
for `echo "" | gcc -v -x c++ -E -`
![image](https://user-images.githubusercontent.com/50285422/122516362-412f4280-d041-11eb-8fa5-330ab7e8b2e0.png)
`COLLECT_GCC_OPTIONS='-v' '-E' '-mtune=generic' '-march=x86-64'`
So how do I set it up?can i use `HOSTCC=gcc -march=.. `

**Comment by martin-frbg** [comment]
You'd need to add quotes around the argument, like `HOSTCC="gcc -march=native"` - but I think it would be easier to find out where the `-march=tigerlake` is getting set. Does `echo $CFLAGS`  show it ?

**Comment by chen-coco** [comment]
> You'd need to add quotes around the argument, like `HOSTCC="gcc -march=native"` - but I think it would be easier to find out where the `-march=tigerlake` is getting set. Does `echo $CFLAGS` show it ?
 
no，nothing。i can‘t find

**Comment by chen-coco** [comment]
I made it！ 
thanks @martin-frbg suggest。
My gcc-9 doesn't support - March = tiger lake
but I can't find this option
This option is not supported until gcc-10, so I apt install gcc-10
And using gcc-10 make, it is successful
：）

**Comment by martin-frbg** [comment]
Glad to know you got it working 🙂
