### ISSUE TITLE
undefined reference to `gotoblas'

### ISSUE THREAD

**Issue by alicezanella** [xianyi/OpenBLAS#3282]
Hello, 

I've installed OpenBLAS-0.3.15 from source on a server where I don't have root privileges. 
Now I'm installing a program which requires OpenBLAS and  in the configuring part it finds my OpenBLAS source code. Then in the make part it ends with this error and I don't know what to do: 

`/usr/lib/liblapack.so.3: undefined reference to gotoblas`

Is it something I am missing from my `.bashrc`? Or do I need to reinstall OpenBLAS? 

I appreciate your help,

_Alice_

**Comment by martin-frbg** [comment]
It seems the linker is still picking up an older library from the default system paths. Have you set the LD_LIBRARY_PATH and LIBRARY_PATH environment variables to point to the location of your OpenBLAS libraries ?

**Comment by alicezanella** [comment]
I set these: 

```
export LD_LIBRARY_PATH=/home/softwares/SU2_RBF/OpenBLAS-develop:$LD_LIBRARY_PATH
export PKG_CONFIG_PATH=/home/softwares/SU2_RBF/OpenBLAS-develop/lib/pkgconfig:$PKG_CONFIG_PATH

```

**Comment by martin-frbg** [comment]
Does setting LIBRARY_PATH help ? (This is what the compiler/linker uses at build time, while LD_LIBRARY_PATH is consulted for dependencies when actually running a program) If not, you could check the configuring options of that other software to see if you can force it to use your OpenBLAS for both LAPACK and BLAS.

**Comment by alicezanella** [comment]
I just tried to add: 
`export LIBRARY_PATH=/home/softwares/SU2_RBF/OpenBLAS-develop:$LIBRARY_PATH`
but I don't know if it's the correct way.. Anyway, it doesn't help. 
To configure the program I run `./meson.py build` but I don't know how to force to use my OpenBLAS.

**Comment by alicezanella** [comment]
Could it help to add LDFLAGS?

**Comment by martin-frbg** [comment]
Which program is it, Is it SU2 ? (Its build documentation mentions running `meson.py build -Denable-openblas` and claims that it expects that library to also contain the LAPACK functions. So I do not understand why it is accessing a separate /usr/lib/liblapack.so at all.) BTW the "undefined reference: gotoblas" suggests that this liblapack.so.3 (whatever it is) expects to work with an OpenBLAS that was built with "DYNAMIC_ARCH=1"

**Comment by alicezanella** [comment]
Yes it is SU2. I don't know if it could be related, but in my `.bashrc` I set `PKG_CONFIG` also for another program, which is needed by this SU2 version and that I specify while building with `meson.py` Does it interfere that liblapack.so.3 is found by that program library? 
I think OpenBLAS was build with "DYNAMIC_ARCH=1" because it has already been used for SU2 (it is in a folder accessible by all the users of the server)

**Comment by alicezanella** [comment]
> BTW the "undefined reference: gotoblas" suggests that this liblapack.so.3 (whatever it is) expects to work with an OpenBLAS that was built with "DYNAMIC_ARCH=1"

Maybe I should try to reinstall OpenBLAS on my local user with this flag. Just to be sure.

**Comment by martin-frbg** [comment]
Yes it could be that the PKG_CONFIG setting for the other program interferes. https://github.com/su2code/SU2/issues/991 appears to be describing similar problems on a Linux distribution that splits its OpenBLAS build into separate liblapack.so and libblas.so, maybe that is what the /usr/lib/iiblapack.so.3 is as well ? Then the pkg_config probably finds the system liblapack and your OpenBLAS - rebuilding your OpenBLAS with DYNAMIC_ARCH=1 should indeed help in that case.

**Comment by alicezanella** [comment]
Thank you for the reference to the su2 issue! I'm reading all the discussion. It is really a tough error... but I appreciate your help! 
I hope to be able to solve it...

**Comment by alicezanella** [comment]
@martin-frbg just to be sure, in order to install OpenBLAS is it correct to do: 

`make DYNAMIC_ARCH=1`

**Comment by martin-frbg** [comment]
Yes, this will build OpenBLAS with optimized kernels for several cpu models, which is where the "gotoblas" symbol is used. (Please do a `make clean` in the source tree first)

**Comment by alicezanella** [comment]
Rebuilding OpenBLAS with the dynamic arch worked! Thank you 🙏🏻
