### ISSUE TITLE
Is there a prebuilt for Windows?

### ISSUE THREAD

**Issue by ghost** [xianyi/OpenBLAS#3283]
Hi,
From the openblas website, the binary Packages link directs to the sourceforge page. In the zip download 0.3.5, I could see the source codes. I am wondering if there are prebuilt library for Windows? Thanks.

**Comment by martin-frbg** [comment]
The current binaries for Windows are under the Releases link here on github : https://github.com/xianyi/OpenBLAS/releases (I still cannot write directly to the sourceforge.net page)

**Comment by brada4** [comment]
@martin-frbg maybe the binary link in openblas/readme.md can be complemented to point to the github releases too? At least fixing one entry to reasonable one. Something like sources mirror there, binary here...
