### ISSUE TITLE
Does OpenBLAS support Int8 operation now?

### ISSUE THREAD

**Issue by umiswing** [xianyi/OpenBLAS#3286]
Hello! I am trying to implement quantization matrix multiplication base on OpenBLAS.
I found the issue #2984, and it's still open. Does OpenBLAS support Int8 operation right now?

**Comment by martin-frbg** [comment]
No it does not, only the "traditional" floating point formats plus bfloat16 are supported.

**Comment by umiswing** [comment]
> 
> 
> No it does not, only the "traditional" floating point formats plus bfloat16 are supported.

Get it! Thanks for your reply!

**Comment by brada4** [comment]
Well, how many multiplications it would take to overflow int8 range of 128 ....
Convrsion to float for such limited range is a vectorizable bitop.
