### ISSUE TITLE
Questions about risc-v vector support

### ISSUE THREAD

**Issue by Dream-math** [xianyi/OpenBLAS#3290]
Hi, I notice that openblas support riscv vector support, if I don't misunderstand, the vector support are only available for C910V,
but my processor is C906 which supports vector instructions 0.71, so can I just replace `C910V` in the file with `C906` to make
it support my processor.

Once, I try to cross compile for C910V, but get the error cross compiler doesn't support flag `lp64v`, it only supports `lp64` , `lp64d` , do I need to recompile my cross compiler to support `lp64v`, Thanks!

**Comment by martin-frbg** [comment]
Yes you would need to compile with `TARGET=C910V` if the processors are similar enough, and you would need a cross-compiler that supports the lp64v ABI (which I suspect may be only in Xuantie's vendor branch of gcc which appears to be available as part of https://github.com/c-sky/xuantie-vector-demos , it does not look like the https://github.com/riscv/riscv-gnu-toolchain has it)
@damonyu1989 is this correct ?

**Comment by Dream-math** [comment]
Thanks, I have tested the cross compiler in demos, it has some errors
```
../kernel/riscv64/amax_vector.c:34:19: error: unknown type name 'vfloat32m8_t'; did you mean 'float32xm8_t'?
 #define FLOAT_V_T vfloat32m8_t
                   ^~~~~~~~~~~~
../kernel/riscv64/amax_vector.c:34:19: note: in definition of macro 'FLOAT_V_T'
 #define FLOAT_V_T vfloat32m8_t
                   ^~~~~~~~~~~~
../kernel/riscv64/amax_vector.c:35:22: error: unknown type name 'vfloat32m1_t'; did you mean 'float32xm1_t'?
 #define FLOAT_V_T_M1 vfloat32m1_t
```
I guess it is because the compiler is too old, I will find a new version C910V compiler to try.

**Comment by Dream-math** [comment]
I have updated to the new C910V compiler, but when run tests, it gets the error:
```
/home/hermanhe/software/riscv64-linux-x86_64/bin/../lib/gcc/riscv64-unknown-linux-gnu/8.4.0/../../../../riscv64-unknown-linux-gnu/bin/ld: (.text._gfortrani_set_fpu_trap_exceptions+0xa6): warning: feenableexcept is not implemented and will always fail
/home/hermanhe/software/riscv64-linux-x86_64/bin/../lib/gcc/riscv64-unknown-linux-gnu/8.4.0/../../../../riscv64-unknown-linux-gnu/bin/ld: /home/hermanhe/software/riscv64-linux-x86_64/bin/../lib/gcc/riscv64-unknown-linux-gnu/8.4.0/../../../../riscv64-unknown-linux-gnu/lib/../lib64vxthead/lp64v/libgfortran.a(fpu.o): in function `_gfortrani_get_fpu_trap_exceptions':
(.text._gfortrani_get_fpu_trap_exceptions+0x12): warning: fegetexcept is not implemented and will always fail
/home/hermanhe/software/riscv64-linux-x86_64/bin/../lib/gcc/riscv64-unknown-linux-gnu/8.4.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../libopenblas_c910vp-r0.3.15.dev.a(memory.o): in function `alloc_mmap':
memory.c:(.text+0x78): undefined reference to `pthread_mutex_lock'
/home/hermanhe/software/riscv64-linux-x86_64/bin/../lib/gcc/riscv64-unknown-linux-gnu/8.4.0/../../../../riscv64-unknown-linux-gnu/bin/ld: memory.c:(.text+0xa2): undefined reference to `pthread_mutex_unlock'
/home/hermanhe/software/riscv64-linux-x86_64/bin/../lib/gcc/riscv64-unknown-linux-gnu/8.4.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../libopenblas_c910vp-r0.3.15.dev.a(memory.o): in function `.L60':
memory.c:(.text+0x33a): undefined reference to `pthread_mutex_lock'
/home/hermanhe/software/riscv64-linux-x86_64/bin/../lib/gcc/riscv64-unknown-linux-gnu/8.4.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../libopenblas_c910vp-r0.3.15.dev.a(memory.o): in function `.L0 ':
memory.c:(.text+0x362): undefined reference to `pthread_mutex_unlock'
```
any advice, thanks!

**Comment by Dream-math** [comment]
I solved the `pthread_mutex_unlock` error by adding `-lpthread`, but the warning can't be eliminated.

**Comment by martin-frbg** [comment]
According to https://github.com/riscv/riscv-gnu-toolchain/issues/417#issuecomment-475128185 the warning is harmless

**Comment by martin-frbg** [comment]
Did you have to add the `-lpthread` to run tests that come with OpenBLAS, or was this for test code of your own ?

**Comment by Dream-math** [comment]
come with OpenBLAS, what I have done is to execute :
``` shell
make HOSTCC=gcc TARGET=C910V CC=riscv64-unknown-linux-gnu-gcc FC=riscv64-unknown-linux-gnu-gfortran
```

**Comment by martin-frbg** [comment]
I assume you had to add the `-lpthread` in test/Makefile then ? Maybe it depends on the compiler version if this is needed or not, I notice the original PR that introduced the C910V support added blank entries for both EXTRALIB and CEXTRALIB there (and these values are normally autodetected by the compiler test scripts, c_check and f_check)

**Comment by Dream-math** [comment]
In fact, I add the `-L/my/pthread/path -lpthread` to `EXTRALIB` to solve the pthread error.

**Comment by martin-frbg** [comment]
Unfortunately I do not have the hardware, so I cannot check if suppressing the `-lpthread` is/was actually needed on the C910V or only a peculiarity of the toolchain used at the time.

**Comment by Dream-math** [comment]
You don't need the hardware, right now I just do the cross compiling, my host is x86_64 fedora 34, and my cross compiler is [riscv64-linux-x86_64-20210618.tar.gz](https://occ.t-head.cn/community/download?id=3927429448189939712). and install command is 
```
make HOSTCC=gcc TARGET=C910V CC=riscv64-unknown-linux-gnu-gcc FC=riscv64-unknown-linux-gnu-gfortran
```

**Comment by martin-frbg** [comment]
Thanks. The site apparently requires registration(?) and I cannot read Chinese (also the site design prevents google translate from working, I cannot even copy+paste the label texts into the google translate form) :flushed:
Deciphered most entries from the site source by now but it requires a telephone number (probably for sending a verification code to enter) and does not accept international numbers...

**Comment by Dream-math** [comment]
OK, if you don't mind, I will email you or give you a public link, so you can download, I don't know if gmail can send a mail with attachment about 533.2MB, so can you give me a email address.

**Comment by martin-frbg** [comment]
Thank you - the email address should be visible on my profile page
