### ISSUE TITLE
Error building on i7-1165G7

### ISSUE THREAD

**Issue by gilcu2** [xianyi/OpenBLAS#3298]
I download the code in develop branch on an Archlinux with i7-1165G7 .
When make I get:
error near unexpected token `(' /bin/sh: -c: line 1: `ar  -ru ../libopenblas_(null)p-r0.3.15.dev.a

I review Makefile.conf and LIBCORE=(null)

What can I do?

**Comment by martin-frbg** [comment]
That's Tiger Lake, which should be supported in the develop branch - maybe there is an extra CPUID for the mobile version that is not yet covered by the checks. Can you please post the contents of /proc/cpuinfo (just for the first core to show family/model number) please ? And building with `make TARGET=SKYLAKEX` should get you around the problem for now.

**Comment by martin-frbg** [comment]
The CPUID data family 6, model 8c (extended model 8, model 12) currently in the autodetection code are correct as such but there is a copy/paste error that leads to LIBCORE not getting set correctly. I'll post a PR shortly.

**Comment by gilcu2** [comment]
Thanks, very fast reaction. Here the CPU info if still interesting:
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 140
model name	: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
stepping	: 1
microcode	: 0x88
cpu MHz		: 2800.000
cache size	: 12288 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 27
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l2 invpcid_single cdp_l2 ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves split_lock_detect dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid movdiri movdir64b fsrm avx512_vp2intersect md_clear flush_l1d arch_capabilities
vmx flags	: vnmi preemption_timer posted_intr invvpid ept_x_only ept_ad ept_1gb flexpriority apicv tsc_offset vtpr mtf vapic ept vpid unrestricted_guest vapic_reg vid ple pml ept_mode_based_exec tsc_scaling
bugs		: spectre_v1 spectre_v2 spec_store_bypass swapgs
bogomips	: 5608.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

**Comment by martin-frbg** [comment]
Thank you - model 140 (decimal) is 8c (hexadecimal), so exactly as expected, just not reported correctly by the code until yesterday.
