### ISSUE TITLE
Segfaults in dependent packages with 0.3.16 on Intel macOS

### ISSUE THREAD

**Issue by carlocab** [xianyi/OpenBLAS#3309]
I don't know where exactly the issue is yet, but I was hoping you could help me figure this out.

I'm trying to update Homebrew's OpenBLAS to 0.3.16 in Homebrew/homebrew-core#81045. However, our tests of dependent packages revealed problems with `arpack`, `dynare`, `nwchem`, and `superlu` on Intel macOS Mojave (10.14), Catalina (10.15), and Big Sur (11).

All four packages report segfaults when trying to run our smoke tests in CI against OpenBLAS 0.3.16. We very recently ran these tests against 0.3.15 (cf. Homebrew/homebrew-core#80747), and CI reported no issues.

CI logs are available at https://github.com/Homebrew/homebrew-core/actions/runs/1020971586. On Big Sur, the errors can be found at

- https://github.com/Homebrew/homebrew-core/runs/3052436753?check_suite_focus=true#step:10:275 (`arpack`)
- https://github.com/Homebrew/homebrew-core/runs/3052436753?check_suite_focus=true#step:10:525 (`dynare`)
- https://github.com/Homebrew/homebrew-core/runs/3052436753?check_suite_focus=true#step:10:797 (`nwchem`)
- https://github.com/Homebrew/homebrew-core/runs/3052436753?check_suite_focus=true#step:10:1790 (`superlu`)

The errors on Catalina and Mojave appear to be identical, but I've only eyeballed them. We have macOS ARM builds of `arpack` and `superlu`. Running the exact same tests for those on ARM did not reveal any problems.

For reference, here are the smoke tests that we run:

1. [`arpack`](https://github.com/Homebrew/homebrew-core/blob/a79ce202051b373568f65357ca6a66aaa6fcb883/Formula/arpack.rb#L54-L61)
2. [`dynare`](https://github.com/Homebrew/homebrew-core/blob/a79ce202051b373568f65357ca6a66aaa6fcb883/Formula/dynare.rb#L101-L119)
3. [`nwchem`](https://github.com/Homebrew/homebrew-core/blob/a79ce202051b373568f65357ca6a66aaa6fcb883/Formula/nwchem.rb#L64-L72)
4. [`superlu`](https://github.com/Homebrew/homebrew-core/blob/a79ce202051b373568f65357ca6a66aaa6fcb883/Formula/superlu.rb#L44-L50)

Happy to answer any questions as best I can. Assistance would be appreciated.

**Comment by carlocab** [comment]
Also for reference, we build OpenBLAS with the following environment variables set:
```
DYNAMIC_ARCH=1
USE_OPENMP=1
NUM_THREADS=56
```
plus `TARGET=VORTEX` on M1 and `TARGET=NEHALEM` on Intel.

We invoke `make` with
```
make CC=gcc-11 FC=gfortran libs netlib shared
make PREFIX=$prefix install
```
where `gcc-11` is Homebrew GCC 11.1.0.

**Comment by martin-frbg** [comment]
Please try reverting #3250 (got a similar report from conda-forge last night, lapack testsuite blowing up on SkylakeX running OSX).
I've just started debugging though, the problem does not appear to be reproducible on Linux and I do not have any Macs.

**Comment by carlocab** [comment]
Yes, I don't think this is reproducible on Linux. In particular, the same tests ran for `arpack` and `superlu` on Linux and revealed no problems.

If generating debug information isn't too involved, I could try to give it a go locally.

In the meantime, I've attempted the fix you suggest in ~~https://github.com/Homebrew/homebrew-core/pull/81045/commits/fb1b1456a2db9a7151dd1a456f7da91f72ca6e9c~~ https://github.com/Homebrew/homebrew-core/pull/81045/commits/7e81803a2fd96657f400d0a6c47c728c7762b937. We should find out if it helped in an hour and a half or so.

**Edit:** Oops, my editor ate a bunch whitespace so my first attempt at reverting it didn't work. Trying again.

**Comment by pkubaj** [comment]
This issue also seems to reproduce on FreeBSD/amd64, although for some reason on i386 and powerpc64 it builds fine. Reverting #3250 fixes it.

**Comment by martin-frbg** [comment]
@pkubaj did it fail for any x86_64 cpu, or "only" those with AVX512 ?

**Comment by pkubaj** [comment]
I don't have a CPU with AVX512, not even AVX2 :)

I use Opteron 6386SE.

**Comment by martin-frbg** [comment]
Too bad as I had hoped it would at least be an AVX512-only bug. (Could not reproduce it - at least not with the LAPACK testsuite - in a VM with OpenBSD, guess I need FreeBSD as well)

**Comment by carlocab** [comment]
Reverting #3250 fixed the four packages I mentioned.

I'm now getting a segfault in [`csound`](/usr/local/Cellar/opencv/4.5.3_1/include/opencv4/opencv2/core/mat.inl.hpp) after the revert, but I think this is not due to any changes in `openblas`. Thanks for the help!

**Comment by brada4** [comment]
https://cirrus-ci.org/features/ looks like it

**Comment by atsampson** [comment]
> I don't think this is reproducible on Linux

With openblas 0.3.16 on Linux (Xeon E5520, GCC 11.1.0, glibc 2.33, built with TARGET=PRESCOTT DYNAMIC_ARCH=1 USE_THREAD=1 USE_OPENMP=1), the patch in #3311 (reverting #3250) fixes a testsuite failure for me:

```
OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 ./sblat2 < ./sblat2.dat

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f24dc8f86ef in ???
	at ../sysdeps/unix/sysv/linux/sigaction.c:10
#1  0x7f24dc963888 in ???
	at ../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S:190  [this and above are in glibc]
#2  0x563fcc279448 in zero_y
	at ../kernel/x86_64/sgemv_n.c:77
#3  0x563fcc279448 in sgemv_n_PRESCOTT
	at ../kernel/x86_64/sgemv_n.c:150
#4  0x563fcb65c052 in sgemv_
	at /src/math/openblas/work/v0.3.16/interface/gemv.c:206  [this is the GEMV_N call]
#5  0x563fcb6568e4 in schk1_
	at /src/math/openblas/work/v0.3.16/test/sblat2.f:621
#6  0x563fcb65b5ec in sblat2
	at /src/math/openblas/work/v0.3.16/test/sblat2.f:344
#7  0x563fcb64d04e in main
	at /src/math/openblas/work/v0.3.16/test/sblat2.f:429
```

(i.e. zero_y is being called with non-zero NB at sgemv_n.c:150, even though buffer was passed in as NULL?)

**Comment by martin-frbg** [comment]
0.3.17 out now with this fix (and another for sgemv_t on SkylakeX...). Still need some time (and quiet) to understand where I went wrong. The most likely explanation is that the stack buffer is used in some assembly kernels even when there is no obvious need to sort or compact the input.

**Comment by carlocab** [comment]
Thanks for the lightning-quick fixes, @martin-frbg!
