### ISSUE TITLE
failed to make openblas  in centos7 of aarch64 

### ISSUE THREAD

**Issue by marchawake** [xianyi/OpenBLAS#3322]
axpy.c:1:0: error: unknown value ‘cortex-a72’ for -mtune
 /*********************************************************************/
 ^
copy.c:1:0: error: unknown value ‘cortex-a72’ for -mtune
 /*********************************************************************/
 ^
swap.c:1:0: error: unknown value ‘cortex-a72’ for -mtune
 /*********************************************************************/
 ^
make[1]: *** [saxpy.o] Error 1
make[1]: *** Waiting for unfinished jobs....
scal.c:1:0: error: unknown value ‘cortex-a72’ for -mtune
 /*********************************************************************/
 ^
make[1]: *** [sswap.o] Error 1
make[1]: *** [scopy.o] Error 1
make[1]: *** [sscal.o] Error 1
make[1]: Leaving directory `/root/OpenBLAS/interface'
make: *** [libs] Error 1

**Comment by martin-frbg** [comment]
What is your C compiler ?
This `-mtune` option is added in Makefile.arm64,it should be safe to remove it if your compiler is too old to support it. (Known to gcc since at least version 5.1,released in 2015)

**Comment by brada4** [comment]
We are dealing with GCC 4.8 there. It is so relevant recently because of EOL flop with CentOS8.
I have been there recently, I could add fallbacks also for sort of mainstream aarch64 CPUs.

**Comment by martin-frbg** [comment]
Are there no gcc updates for CentOS7 ?

**Comment by brada4** [comment]
RedHat discontinued ARM64 with RHEL7U5, leaving only RHEL8, so related softwarecollections and epel are gone too.

**Comment by martin-frbg** [comment]
That's bad. gcc 4.8 had the very beginnings of arm64 support and does not appear to have understood any mtune option for that architecture at all.

**Comment by marchawake** [comment]
Thanks, I have solved, cause I didn't select the TARGET  make TARGET=arm64 HOSTCC=gcc BINARY=64 CC=arm-linux-gnueabihf-gcc FC=arm-linux-gnueabihf-gfortran
