### ISSUE TITLE
error: Makefile.system:1011: *** only one `else' per conditional.  Stop.

### ISSUE THREAD

**Issue by chenQ1114** [xianyi/OpenBLAS#3324]
Hi, 

I try to compile OpenBLAS with the command below:
git clone https://github.com/xianyi/OpenBLAS.git
cd OpenBLAS
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/home/mwp141/Tool/OpenBLAS-build
make
make

I got several errors about makefile.system file. After change the similar code from:
`else ifeq ($(ARCH), powerpc64)`
to 
`else`
`ifeq  ($(ARCH), powerpc64)`

The error: Makefile.system:1011: *** only one `else' per conditional.  Stop. is still unsolved. 

Do you know how to fix it? Thanks!

**Comment by martin-frbg** [comment]
Can you please give more details about your problem, like your hardware and operating system ?  Possibly your standard`make` program is something other than GNU make and you may need to call it as `gmake` to get the right one to understand the Makefile syntax. But the error is a bit strange - If you are using CMAKE, I do not think the toplevel Makefile.system is needed by anything, perhaps you were not in the build directory when you issued `make` ?

**Comment by chenQ1114** [comment]
Thanks! It is fixed now. You are right. There are make and gmake in the linux. Throught change the "make" to "gmake" command. The OpenBLAS is installed successfully.
- GNU Make 3.82 Built for x86_64-redhat-linux-gnu (gmake --version)
- GNU Make 3.80 (when I run the command: make --version)
