### ISSUE TITLE
`make install` on MacOS 10.15 does not copy LAPACK/LAPACKE headers to `$PREFIX/include` + emits `clang`, `expr`  errors

### ISSUE THREAD

**Issue by phetdam** [xianyi/OpenBLAS#3339]
While building the 0.3.17 release on a GitHub Actions `macos-latest` (MacOS 10.15) runner, I noticed that despite OpenBLAS having built LAPACK, LAPACKE when running `make`, on `make install` the LAPACK/LAPACKE headers were not being correctly copied to `$PREFIX/include`. I read through `Makefile.install` and so explicitly passed `NO_LAPACKE=` to the `make install` command, which fixed the problem. However, this is not reasonable behavior, and it is also more worrying that when running `make install` I got errors from `expr` and `clang`. OpenBLAS built using Homebrew GCC 9.4 on the GitHub Actions runner, so why is `clang` being run?

Below is what I used to build and install OpenBLAS on the MacOS 10.15 runner. See [here](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md) for info on the machine.

`make BINARY=64 USE_THREAD=1 CC=gcc-9 FC=gfortran-9 && make PREFIX=/path/to/OpenBLAS install`

Note that `/path/to/OpenBLAS` is just a placeholder path; I used a valid path. Below is the final output from building minus the warning about using and installing the `.dylib` with `make install`.

```text
 OpenBLAS build complete. (BLAS CBLAS LAPACK LAPACKE)

  OS               ... Darwin             
  Architecture     ... x86_64               
  BINARY           ... 64bit                 
  C compiler       ... GCC  (cmd & version : gcc-9 (Homebrew GCC 9.4.0) 9.4.0)
  Fortran compiler ... GFORTRAN  (cmd & version : GNU Fortran (Homebrew GCC 9.4.0) 9.4.0)
  Library Name     ... libopenblas_sandybridgep-r0.3.17.a (Multi-threading; Max num-threads is 3)
```

Here is the erroneous output I got when running the `make install` command:

```text
/Applications/Xcode_12.4.app/Contents/Developer/usr/bin/make -j 3 -f Makefile.install install
clang: error: no input files
expr: syntax error
clang: error: no input files
expr: syntax error
clang: error: no input files
expr: syntax error
```

After this lines are printed, I still get all the other output about generating `openblas_config.h`, `f77blas.h`, `cblas.h`, static and shared libs, `openblas.pc`, `OpenBLASConfig.cmake`, `OpenBLASConfigVersion.cmake` printed to screen and the final `Install OK!` message at the end of the install, but there is no `Copy LAPACKE header files to $(DESTDIR)$(OPENBLAS_INCLUDE_DIR)` that is printed. Furthermore, as I previously noted, I used GCC to build this, so `clang` should not be involved at all. Unfortunately, I don't have the `Makefile` expertise nor familiarity with the OpenBLAS build system to track down where exactly this problem might occur.

Thanks for reading to the end and it would be great if someone can patch this. Otherwise, it may be good to update the MacOS section in the wiki's installation guide with the workaround I used (explicit unset of `NO_LAPACKE` when running `make install`).

**Comment by martin-frbg** [comment]
You need to repeat the `CC=gcc-9` etc. from the initial `make` in the `make install`, otherwise it will just try to use the default compiler while the parts of the build system (Makefile.conf and config.h) that were generated at the start of the build step are set up for gcc.

**Comment by phetdam** [comment]
Ok, just tried and that seems to work. But maybe the install instructions on the wiki should be updated since it doesn't seem obvious to me that `make install` should depend on any choice of compiler.

Thanks!

**Comment by brada4** [comment]
It is not documented anywhere in wikis, even README.md is very short with words on what happens if you play with build flags.
In short - `make install` expects nearly all build flags to be copied over.

**Comment by phetdam** [comment]
Ok, thanks for the explanation. I updated the User Manual install section with a quick note about that.

**Comment by martin-frbg** [comment]
Thank you for the wiki update
