### ISSUE TITLE
GenerateNamedObjects fails when OpenBLAS is compiled as a subproject using cmake FetchContent

### ISSUE THREAD

**Issue by cianciosa** [xianyi/OpenBLAS#3342]
This call to GenerateNamedObjects fails when OpenBLAS is compiled as a subproject of a parent cmake based build system.
https://github.com/xianyi/OpenBLAS/blob/b9e4fb206ddb8b11576d9a2b5d8b87c15ddce196/interface/CMakeLists.txt#L170
Attached is a test case to show the problem. The test results in a link error because the symbol for dgesv was never included in the library.
[Test Case.zip](https://github.com/xianyi/OpenBLAS/files/6971004/Test.Case.zip)

This is caused by ARGV2 containing bogus values.
https://github.com/xianyi/OpenBLAS/blob/b9e4fb206ddb8b11576d9a2b5d8b87c15ddce196/cmake/utils.cmake#L164

From the cmake docs
https://cmake.org/cmake/help/latest/command/function.html
>When the function is invoked, the recorded `<commands>` are first modified by replacing formal parameters (`${arg1},` ...) with the arguments passed, and then invoked as normal commands.
>
>In addition to referencing the formal parameters you can reference the `ARGC` variable which will be set to the number of arguments passed into the function as well as `ARGV0`, `ARGV1`, `ARGV2`, ... which will have the actual values of the arguments passed in. This facilitates creating functions with optional arguments.
>
>Furthermore, `ARGV` holds the list of all arguments given to the function and `ARGN` holds the list of arguments past the last expected argument. Referencing to `ARGV#` arguments beyond `ARGC` have undefined behavior. Checking that `ARGC` is greater than # is the only way to ensure that `ARGV#` was passed to the function as an extra argument.

**Comment by martin-frbg** [comment]
Thanks. It is probably safe to assume/admit that building as a cmake subproject was not even envisaged for the current level of cmake support

**Comment by cianciosa** [comment]
The fix was really simple. I implemented the last line from the cmake docs and everything worked.
https://github.com/xianyi/OpenBLAS/pull/3343

**Comment by martin-frbg** [comment]
Closing as fixed by your PR #3343
