### ISSUE TITLE
TARGET=HASWELL is ignored with NO_AVX2=1 NO_AVX=1 NO_AVX512=1 in 0.3.17

### ISSUE THREAD

**Issue by dkonst13** [xianyi/OpenBLAS#3358]
We were building openblas 0.3.10 with:

TARGET=HASWELL BIGNUMA=1 NO_AFFINITY=1 NO_AVX2=1 NO_AVX=1 NO_AVX512=1

And we had haswell library without AVX:

cmake          libopenblas_haswellp-r0.3.10.a   libopenblas.so    pkgconfig
libopenblas.a  libopenblas_haswellp-r0.3.10.so  libopenblas.so.0

Migrating 0.3.17 we noticed that we don't have haswell anynmore:
cmake          libopenblas_sandybridgep-r0.3.17.a   libopenblas.so    pkgconfig
libopenblas.a  libopenblas_sandybridgep-r0.3.17.so  libopenblas.so.0

Playing with parameters we came to conclusion that addition of NO_AVX2=1 NO_AVX=1 NO_AVX512=1 changes architecture from haswell to sandybridge.

**Comment by martin-frbg** [comment]
"Haswell without AVX2" is automatically mapped to Sandybridge by the build system as it would not be able to use the Haswell-speciic BLAS kernels (due to their use of AVX2 instructions), and if you also defined NO_AVX=1 the resulting library should probably be called libopenblas_nehalem.

**Comment by martin-frbg** [comment]
Also "TARGET=HASWELL NO_AVX512=1" is redundant, as Haswell does not have AVX512 support. Were you trying to build a library that supports several generations of cpu ? If so, you would need to build with  DYNAMIC_ARCH=1 (and TARGET set to
GENERIC; or to the oldest cpu you expect to support, e.g. "make TARGET=NEHALEM DYNAMIC_ARCH=1"). This will generate a (bigger) library with kernels for about a dozen cpu models built in, and automatic selection of the best match at runtime.

**Comment by dkonst13** [comment]
@martin-frbg ,  thanks you! it makes sense. 

"and if you also defined NO_AVX=1 the resulting library should probably be called libopenblas_nehalem"
No, it doesn't...

**Comment by martin-frbg** [comment]
Yes, "TARGET=HASWELL NO_AVX=1" is actually an unhandled situation, and the NO_AVX=1 gets ignored. (But both NO_AVX2 and NO_AVX were originally added as workarounds when the then-new cpu came out but common compilers did not yet support the new instructions. So it was only ever expected to see "NO_AVX=1" with (autodetected) SANDYBRIDGE cpu or "NO_AVX2=1" with HASWELL.
