### ISSUE TITLE
Add an option to set TARGET to the oldest supported when DYNAMIC_ARCH is on

### ISSUE THREAD

**Issue by isuruf** [xianyi/OpenBLAS#3361]
I've seen multiple projects (openblas, sagemath, numpy) building openblas hit by
this issue. All these projects now keep a list of oldest TARGET for each platform
and set TARGET when building with DYNAMIC_ARCH.
This is error prone and duplicates work among several projects.

Would it be possible to add an option to set TARGET to the oldest supported
when DYNAMIC_ARCH is on and TARGET is not set?

**Comment by brada4** [comment]
There is TARGET=GENERIC, do you mean imply it if in DYNAMIC_ARCH?

**Comment by isuruf** [comment]
Ah, didn't realize that we could use `TARGET=GENERIC` with `DYNAMIC_ARCH`. Thanks

**Comment by brada4** [comment]
It is quite recent introduction.... But indeed having it by default would save a lot of duplicate work.

**Comment by martin-frbg** [comment]
been thinking about that but not sure I want to change established behaviour, i.e. "no target named = use host cpu"

**Comment by isuruf** [comment]
Maybe something like `DYNAMIC_ARCH=1` and `TARGET=OLDEST` would set the target to the oldest. I haven't tried @brada4's suggestion yet, but if that works, then this issue can be closed.

**Comment by martin-frbg** [comment]
TARGET=GENERIC (plain C code) is expected to work. This has no influence on the choice of BLAS kernels anyway (you will get CORE2 hardcoded as a worst-case fallback on x86_64, and similar for other architectures), but _used to_ determine the compiler options used when compiliing the shared code parts (e.g code from the interface and  drivers directories). This mainly became a problem after the introduction of intrinsics, which led to the addition of more such options like `-mavx2` or `-msse3`.
I _think_ the current version has limited most if not all such options to the actual, cpu-specific kernel files so this should hopefully be a  problem of the past.

**Comment by isuruf** [comment]
Great. Then let's document `TARGET=GENERIC` in all the places where `DYNAMIC_ARCH=1` is documented.

**Comment by martin-frbg** [comment]
Well, as I wrote this _should_ be a problem of the past.

**Comment by isuruf** [comment]
Ah, sorry about the noise.
