### ISSUE TITLE
Warning: variable may be used uninitialized

### ISSUE THREAD

**Issue by thiagomacieira** [xianyi/OpenBLAS#3371]
Since the OpenBLAS build forces warnings on (at least with CMake), then warnings should be considered errors and should be fixed.

```
/tmp/OpenBLAS/kernel/x86_64/casum_microk_skylakex-2.c:25:29: warning: ‘abs_mask1’ may be used uninitialized [-Wmaybe-uninitialized]
```

**Comment by brada4** [comment]
This is only one that has implications on the result. Would you mind to share gcc version you are using and that gives the warning?

**Comment by thiagomacieira** [comment]
This was found with GCC 11.2.1 from OpenSUSE Tumbleweed. I cannot reproduce it with GCC 10.2.1 from Ghettoforge for CentOS 7.

**Comment by brada4** [comment]
Thanks, there are some more. Could you edit 2 other issues into this one (they are cosmetic by large, this is accuracy/stability where in place of ZERO you get leftovers from memory in long run, but not on 1st run)

**Comment by martin-frbg** [comment]
That code does look a bit strange, almost as if the initial value of abs_mask1 was irrelevant for generation of the mask, but I am not sure I understand that part of the algorithm. I wonder if you get a similar error for zasum_microk_skylakex-2.c,which contains similar code _plus_ a commented-out initializer ?

**Comment by martin-frbg** [comment]
Well duh, the "uninitialized" use of abs_mask1 actually _is_ the initializer (using _mm_cmpeq_epi8 of the arbitrary value with itself to set all its bits to 1). Probably doing it in this hackish fashion is actually faster than _mm_set1_epi8(0xff) (although the only reference to this that I can find is a blog entry from 2011, and a comment on that claims that all reasonable compilers do the substitution automatically...)

**Comment by martin-frbg** [comment]
Gut feeling is to try to silence the warning by initializing abs_mask1 with itself (unless some compiler then throws a warning for self-initialization...)
