### ISSUE TITLE
How does OpenBLAS print log?

### ISSUE THREAD

**Issue by jianlongf** [xianyi/OpenBLAS#3373]
Can OpenBLAS  print log by export XXXX=1, like this.  Then I can debug through it.

**Comment by martin-frbg** [comment]
A trace of which function gets called in turn ? No, this is not supported. In general, the code flow is from the appropriate function in interface (e.g. interface/gemv.c which gets compiled to sgemv,dgemv and their CBLAS variants) to the driver routine in level2 or level3 (which distribute the workload onto several threads) or (for level1 BLAS functions or single-threaded jobs) directly to the BLAS kernel matching the cpu (from kernel/(architecture), individual kernels defined in the KERNEL.(cpuname) files there).

**Comment by jianlongf** [comment]
Oh, Thanks a lot. We had the issue of pytorch. But I am not sure the cause. So if it exist, it maybe help us ensure.
