### ISSUE TITLE
dgemm crash on macOS 12.0 beta arm64

### ISSUE THREAD

**Issue by ilian8** [xianyi/OpenBLAS#3383]
With macOS 12.0 (21A5506j) arm64 and OpenBLAS 0.3.17 (earlier versions as well) there is a crash in the utest target

```
* thread JuliaLang/julia#3, stop reason = EXC_BAD_ACCESS (code=2, address=0x10031c000)
    frame #0: 0x000000010005d394 openblas_utest`.Ldgemm_tcopy_L8_M8_20 + 116
openblas_utest`.Ldgemm_tcopy_L8_M8_20:
->  0x10005d394 <+116>: ldp    q30, q31, [x13], #0x20
    0x10005d398 <+120>: st1.2d { v28, v29, v30, v31 }, [x20]
    0x10005d39c <+124>: add    x20, x20, #0x40           ; =0x40 
    0x10005d3a0 <+128>: add    x14, x14, x5
Target 0: (openblas_utest) stopped.
```
See also https://github.com/JuliaLang/LinearAlgebra.jl/issues/866.

There is no problem on maOS 11.6 (but the library built on macOS 11 also crashes when run on macOS 12).

**Comment by martin-frbg** [comment]
Unfortunately I do not have M1 hardware (beyond what is available in the gcc compile farm). The OpenBLAS dgemm_tcopy kernel is shared among all supported ARMV8 cpus however, so unlikely to be the culprit.

**Comment by ilian8** [comment]
Thanks, it seems a bit mysterious how the same assembly can run differently on the same CPU.

Does the dgemm_tcopy kernel make any use of the x18 register by any chance? 

This is generally available on ARMv8 CPUs, but is reserved on the Apple M1 according to 

https://developer.apple.com/documentation/xcode/writing-arm64-code-for-apple-platforms.

**Comment by martin-frbg** [comment]
Yes it does. Looks like it may be an easy fix as it is `#define`d to a variable I and there is an unused `#define TEMP2 x21` in dgemm_tcopy_8.S as well. Of course there may be additional instances in other kernels (and all have been there for years)

**Comment by martin-frbg** [comment]
Tentative fix in JuliaLang/julia#3384 - have not checked yet if I broke anything with the naive reshuffle...

**Comment by mryodo** [comment]
> Tentative fix in JuliaLang/julia#3384 - have not checked yet if I broke anything with the naive reshuffle...

if you want I can try building it on `m1`, although simple `make` results into undefined symbols for `arm64` architecture

**Comment by martin-frbg** [comment]
Strange. I got a clean build (for TARGET=ARMV8 on CortexA57 hardware, which should touch all the modified kernels), I just need to run the lapack testsuite on that system to make sure it still does the calculations right. What undefined symbols are you getting ?

**Comment by ilian8** [comment]
I can confirm https://github.com/xianyi/OpenBLAS/pull/3384 fixes the crashes on my M1 system (the rest of the test suite also passes).

**Comment by mryodo** [comment]
> Strange. I got a clean build (for TARGET=ARMV8 on CortexA57 hardware, which should touch all the modified kernels), I just need to run the lapack testsuite on that system to make sure it still does the calculations right. What undefined symbols are you getting ?

I've pulled JuliaLang/julia#3384 and it ends up with this:
```
Undefined symbols for architecture arm64:
  "___chkstk_darwin", referenced from:
      _sgemv_ in libopenblas_armv8p-r0.3.17.dev.a(sgemv.o)
      _sger_ in libopenblas_armv8p-r0.3.17.dev.a(sger.o)
      _cblas_sgemv in libopenblas_armv8p-r0.3.17.dev.a(cblas_sgemv.o)
      _cblas_sger in libopenblas_armv8p-r0.3.17.dev.a(cblas_sger.o)
      _dgemv_ in libopenblas_armv8p-r0.3.17.dev.a(dgemv.o)
      _dger_ in libopenblas_armv8p-r0.3.17.dev.a(dger.o)
      _cblas_dgemv in libopenblas_armv8p-r0.3.17.dev.a(cblas_dgemv.o)
      ...
ld: symbol(s) not found for architecture arm64
collect2: error: ld returned 1 exit status
make[1]: *** [libopenblas_armv8p-r0.3.17.dev.dylib] Error 1
make: *** [shared] Error 2
```
everything before passes, I think

Sorry, I guess that's on me

**Comment by martin-frbg** [comment]
@mryodo Googling "__chkstk_darwin" suggests this happens when the base SDK setting or the deployment target is somehow not correct.
