### ISSUE TITLE
running vs2015 exe loading v0.3.5 dll that compiled with mingw64 got violation writting access error

### ISSUE THREAD

**Issue by allenling** [xianyi/OpenBLAS#3391]
for some reasons, i need to compile openblas v0.3.5 with mingw64

i used this build script

```bash
# You may adjust to your preferred output directory
OPENBLAS_ROOT=./

# Adjust to match the MSYS2 version you installed
BUILD_BITS=64

# Print some gcc info that MSYS2 discovered in the path
which x86_64-w64-mingw32-gcc
x86_64-w64-mingw32-gcc --version

# Get into the repository that we cloned
cd OpenBLAS

# The following two lines clean up in case we make a mistake and need
# to run the script again
git clean -fxd
git reset --hard
rm -rf $OPENBLAS_ROOT/$BUILD_BITS

# Set architecture flags
march="x86-64"
extra="-fno-asynchronous-unwind-tables"
vc_arch="X64"
cflags="-O2 -march=$march -mtune=generic $extra -static -static-libgcc"
fflags="$cflags -frecursive -ffpe-summary=invalid,zero"

# Build name for output library from gcc version and OpenBLAS commit.
GCC_TAG="x86_64-w64-mingw32-gcc_$(x86_64-w64-mingw32-gcc -dumpversion | tr .- _)"
OPENBLAS_VERSION=$(git describe --tags)
# Build OpenBLAS
# Variable used in creating output libraries
export LIBNAMESUFFIX=${OPENBLAS_VERSION}-${GCC_TAG}
make -j8 BINARY=$BUILD_BITS DYNAMIC_ARCH=1 USE_THREAD=1 USE_OPENMP=0 \
    NO_WARMUP=1 BUILD_LAPACK_DEPRECATED=1 FC=x86_64-w64-mingw32-gfortran.exe CC=x86_64-w64-mingw32-gcc AR=x86_64-w64-mingw32-gcc-ar RANLIB=x86_64-w64-mingw32-gcc-ranlib.exe\
    COMMON_OPT="$cflags" FCOMMON_OPT="$fflags" BUILD_WITHOUT_LAPACK=0
make install PREFIX=$OPENBLAS_ROOT/$BUILD_BITS
```

and compilation was good, and i got such info in the end

```
 OpenBLAS build complete. (BLAS CBLAS LAPACK LAPACKE)

  OS               ... WINNT
  Architecture     ... x86_64
  BINARY           ... 64bit
  C compiler       ... GCC  (command line : x86_64-w64-mingw32-gcc)
  Fortran compiler ... GFORTRAN  (command line : x86_64-w64-mingw32-gfortran.exe)
  Library Name     ... libopenblas_v0.3.5-x86_64-w64-mingw32-gcc_10_3_0p-r0.3.5.a (Multi threaded; Max num-threads is 12)
```

it seemed that everything is great! 

and i wanted to link that dll in this vs2015 test vs project

```
void zungqr_();
int main(int argc, const char *argv[])
{
	zungqr_();
	return 0;
}

```

compilation was great too. but when i ran exe, i got 

```Exception thrown at 0x00007FFAD27F157D (libopenblas_v0.3.5-x86_64-w64-mingw32-gcc_10_3_0.dll) in Project2.exe: 0xC0000005: Access violation writing location 0x0000000000000000.```

**Comment by martin-frbg** [comment]
Can you check if you get the same problem with the current code ? 0.3.5 is almost three years old now, and while this NULL pointer exception does not look familiar, many bugs have been fixed since then.

**Comment by brada4** [comment]
some args of mentioned function are pointers. the way you call args are taken from unitializeed memory which turns out zeroes on your platform.

**Comment by martin-frbg** [comment]
> some args of mentioned function are pointers. the way you call args are taken from unitializeed memory which turns out zeroes on your platform.

I had automatically assumed that it was a stripped-down example - of course you are right if that was actually just zungqr() without arguments then OpenBLAS did exactly what was asked from it...

**Comment by brada4** [comment]
actual call with all zeroes yields writing optimal workspace size at 0x0, thus openblas works correctly

**Comment by allenling** [comment]
thanks for replies!

actually, i want to build openblas for numpy.

and the code above, which used to check openblas with lapack embeded by calling `zungqr`, was cut from numpy v1.13.3 source code

`actual call with all zeroes yields writing optimal workspace size at 0x0, thus openblas works correctly`

and i searched   `zungqr` /`zungqr_` in openblas v0.3.5 source codes, and yes, it seems that zungqr has more than one args

and it is  weird why numpy call `zungqr` with zero arg, maybe i should choose another version for numpy v1.13.3

**Comment by allenling** [comment]
and in numpy main branch, it still calls `zungqr_` without any arg

here https://github.com/numpy/numpy/blob/main/numpy/distutils/system_info.py#L2266

```python

class openblas_info(blas_info):
    section = 'openblas'
    dir_env_var = 'OPENBLAS'
    _lib_names = ['openblas']
    _require_symbols = []
    notfounderror = BlasNotFoundError

    def check_symbols(self, info):
            prototypes = "\n".join("void %s%s%s();" % (self.symbol_prefix,
                                                       symbol_name,
                                                       self.symbol_suffix)
                                   for symbol_name in self._require_symbols)
            calls = "\n".join("%s%s%s();" % (self.symbol_prefix,
                                             symbol_name,
                                             self.symbol_suffix)
                              for symbol_name in self._require_symbols)
            s = textwrap.dedent("""\
                %(prototypes)s
                int main(int argc, const char *argv[])
                {
                    %(calls)s
                    return 0;
                }""") % dict(prototypes=prototypes, calls=calls


class openblas_lapack_info(openblas_info):
    section = 'openblas'
    dir_env_var = 'OPENBLAS'
    _lib_names = ['openblas']
    _require_symbols = ['zungqr_']
    notfounderror = BlasNotFoundError
```

`self._require_symbols` is equal to `['zungqr_']`

**and another question, why zungqr_, not zungqr?**

i searched zungqr_ in openblas source codes, and got nothing

what did i miss?

**Comment by brada4** [comment]
You can get latest versions of both via pip, no need to dive back in history.

**Comment by allenling** [comment]
alright, it was my "little" mistake!!!

numpy has wrapped function zungqr itself(in numpy/linalg/lapack_lite), so it can call zungqr_

here is the check code in numpy v1.13.3

```python

void zungqr();
int main(int argc, const char *argv[])
{
    zungqr_();
    return 0;
}
```

i thought calling zungqr_ was a miskae atfer i did some searches(google lapack etc) , so i changed zungqr_ to zungqr, then hit this error

changing zungqr to zungqr_, then everything is ok! 

so "clever"!

i should not have tested numpy code out of numpy env

**Comment by martin-frbg** [comment]
Alright. Then the numpy wrapper probably looks to see if anything needs to be calculated, and does a quick return otherwise. While the LAPACK code used in OpenBLAS tries to report back that it needs a workspace size of one when N is <= 0 (there is no "quick return" for both M and N zero, if you like you could propose this as an enhancement PR in https://github.com/Reference-LAPACK/lapack)
