### ISSUE TITLE
eigenvalues require linking with libgfortran

### ISSUE THREAD

**Issue by devcrocod** [xianyi/OpenBLAS#3405]
Hi!
I use `LAPACKE_cgeev` and `LAPACKE_zgeev`. When linking, it turned out that it needed to link with `libgfortran`. It is needed because of this function - `gfortran_concat_string`.
Despite the fact that the documentation says that `lapacke` does not need linking with `libgfortran`.
The problem is that dynamic linking does not suit me, and if I managed to statically link in macos and windows, then `libgfortran` cannot be statically linked in Linux.

**Comment by martin-frbg** [comment]
LAPACKE itself is written in C just like the BLAS part of OpenBLAS, but all it provides is the C bindings for the functions in LAPACK (like cgeev)- which in the "netlib" reference implementation used by OpenBLAS are written in Fortran. It should be possibly to link libgfortran statically in Linux as well, with something like `gcc -static-libgcc -Wl,-Bstatic -lgfortran -lquadmath -lm ` or by specifying `-static-libgfortran` and adding the full path to the libquadmath.a that libgfortran depends on.
