### ISSUE TITLE
make lapack-test does not return error on failed tests

### ISSUE THREAD

**Issue by h-vetinari** [xianyi/OpenBLAS#3406]
I returned to https://github.com/conda-forge/openblas-feedstock/pull/122 after a while, and looking at the CI results, there are still errors in the test suite for `make lapack-test` that do however not propagate the failure.

IOW, results like
```
			-->   LAPACK TESTING SUMMARY  <--
SUMMARY             	nb test run 	numerical error   	other error  
================   	===========	=================	================  
REAL             	1174263		2	(0.000%)	0	(0.000%)	
DOUBLE PRECISION	1227437		0	(0.000%)	0	(0.000%)	
COMPLEX          	694951		1	(0.000%)	0	(0.000%)	
COMPLEX16         	696320		2	(0.000%)	0	(0.000%)	

--> ALL PRECISIONS	3792971		5	(0.000%)	0	(0.000%)	
```
still result in a green CI, which is not intentional.

**Comment by martin-frbg** [comment]
This is actually intentional, as LAPACK testsuite errors (in contrast to BLAS test failures) do not necessarily mean that the build is unsuitable. Please see
http://www.netlib.org/lapack/faq.html#_how_do_i_interpret_lapack_testing_failures
