### ISSUE TITLE
supported target CPU 

### ISSUE THREAD

**Issue by wangzheng00** [xianyi/OpenBLAS#3407]
I check in targetlist.txt, and find now it supported CPU(intel) list as below, now Intel already introduced new CPU (Icelake) . Do you have any plans to support it? If yes, when and in which version?

Supported List:
1.X86/X86_64
a)Intel CPU:
P2
KATMAI
COPPERMINE
NORTHWOOD
PRESCOTT
BANIAS
YONAH
CORE2
PENRYN
DUNNINGTON
NEHALEM
SANDYBRIDGE
HASWELL
SKYLAKEX
ATOM
COOPERLAKE

**Comment by martin-frbg** [comment]
Targetlist only names the cpu models for which dedicated support is available. Intel Ice Lake is supported and autodetected as either SKYLAKEX  or COOPERLAKE depending on availability of AVX512BF16.
(Similarly for older cpus, e.g. every Haswell refresh like Kaby Lake etc. is supported as HASWELL)

**Comment by wangzheng00** [comment]
thank you.
in my two servers, compile failed using these commands:
 ( 2 CPU information: 
Model name:          Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz
Model name:          Intel Xeon Processor (Icelake)
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid fsrm md_clear pconfig flush_l1d arch_capabilities )
make
make TARGET=COOPERLAKE
error:
[root@localhost OpenBLAS]# make TARGET=COOPERLAKE

getarch_2nd.c: In function ‘main’:
getarch_2nd.c:12:35: error: ‘SGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function); did you mean ‘XGEMM_DEFAULT_UNROLL_M’?
     printf("SGEMM_UNROLL_M=%d\n", SGEMM_DEFAULT_UNROLL_M);
                                   ^~~~~~~~~~~~~~~~~~~~~~
                                   XGEMM_DEFAULT_UNROLL_M
getarch_2nd.c:12:35: note: each undeclared identifier is reported only once for each function it appears in
getarch_2nd.c:13:35: error: ‘SGEMM_DEFAULT_UNROLL_N’ undeclared (first use in this function); did you mean ‘XGEMM_DEFAULT_UNROLL_N’?
     printf("SGEMM_UNROLL_N=%d\n", SGEMM_DEFAULT_UNROLL_N);
                                   ^~~~~~~~~~~~~~~~~~~~~~
                                   XGEMM_DEFAULT_UNROLL_N
getarch_2nd.c:14:35: error: ‘DGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function); did you mean ‘XGEMM_DEFAULT_UNROLL_M’?
     printf("DGEMM_UNROLL_M=%d\n", DGEMM_DEFAULT_UNROLL_M);
                                   ^~~~~~~~~~~~~~~~~~~~~~
                                   XGEMM_DEFAULT_UNROLL_M
getarch_2nd.c:15:35: error: ‘DGEMM_DEFAULT_UNROLL_N’ undeclared (first use in this function); did you mean ‘XGEMM_DEFAULT_UNROLL_N’?
     printf("DGEMM_UNROLL_N=%d\n", DGEMM_DEFAULT_UNROLL_N);
                                   ^~~~~~~~~~~~~~~~~~~~~~
                                   XGEMM_DEFAULT_UNROLL_N
getarch_2nd.c:19:35: error: ‘CGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function); did you mean ‘XGEMM_DEFAULT_UNROLL_M’?
     printf("CGEMM_UNROLL_M=%d\n", CGEMM_DEFAULT_UNROLL_M);
                                   ^~~~~~~~~~~~~~~~~~~~~~
                                   XGEMM_DEFAULT_UNROLL_M
getarch_2nd.c:20:35: error: ‘CGEMM_DEFAULT_UNROLL_N’ undeclared (first use in this function); did you mean ‘XGEMM_DEFAULT_UNROLL_N’?
     printf("CGEMM_UNROLL_N=%d\n", CGEMM_DEFAULT_UNROLL_N);
                                   ^~~~~~~~~~~~~~~~~~~~~~
                                   XGEMM_DEFAULT_UNROLL_N
getarch_2nd.c:21:35: error: ‘ZGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function); did you mean ‘XGEMM_DEFAULT_UNROLL_M’?
     printf("ZGEMM_UNROLL_M=%d\n", ZGEMM_DEFAULT_UNROLL_M);
                                   ^~~~~~~~~~~~~~~~~~~~~~
                                   XGEMM_DEFAULT_UNROLL_M
getarch_2nd.c:22:35: error: ‘ZGEMM_DEFAULT_UNROLL_N’ undeclared (first use in this function); did you mean ‘XGEMM_DEFAULT_UNROLL_N’?
     printf("ZGEMM_UNROLL_N=%d\n", ZGEMM_DEFAULT_UNROLL_N);
                                   ^~~~~~~~~~~~~~~~~~~~~~
                                   XGEMM_DEFAULT_UNROLL_N
getarch_2nd.c:69:50: error: ‘SGEMM_DEFAULT_Q’ undeclared (first use in this function); did you mean ‘XGEMM_DEFAULT_UNROLL_M’?
     printf("#define SLOCAL_BUFFER_SIZE\t%ld\n", (SGEMM_DEFAULT_Q * SGEMM_DEFAULT_UNROLL_N * 4 * 1 *  sizeof(float)));
                                                  ^~~~~~~~~~~~~~~
                                                  XGEMM_DEFAULT_UNROLL_M
getarch_2nd.c:70:50: error: ‘DGEMM_DEFAULT_Q’ undeclared (first use in this function); did you mean ‘XGEMM_DEFAULT_UNROLL_M’?
     printf("#define DLOCAL_BUFFER_SIZE\t%ld\n", (DGEMM_DEFAULT_Q * DGEMM_DEFAULT_UNROLL_N * 2 * 1 *  sizeof(double)));
                                                  ^~~~~~~~~~~~~~~
                                                  XGEMM_DEFAULT_UNROLL_M
getarch_2nd.c:71:50: error: ‘CGEMM_DEFAULT_Q’ undeclared (first use in this function); did you mean ‘XGEMM_DEFAULT_UNROLL_M’?
     printf("#define CLOCAL_BUFFER_SIZE\t%ld\n", (CGEMM_DEFAULT_Q * CGEMM_DEFAULT_UNROLL_N * 4 * 2 *  sizeof(float)));
                                                  ^~~~~~~~~~~~~~~
                                                  XGEMM_DEFAULT_UNROLL_M
getarch_2nd.c:72:50: error: ‘ZGEMM_DEFAULT_Q’ undeclared (first use in this function); did you mean ‘XGEMM_DEFAULT_UNROLL_M’?
     printf("#define ZLOCAL_BUFFER_SIZE\t%ld\n", (ZGEMM_DEFAULT_Q * ZGEMM_DEFAULT_UNROLL_N * 2 * 2 *  sizeof(double)));
                                                  ^~~~~~~~~~~~~~~
                                                  XGEMM_DEFAULT_UNROLL_M
make: *** [Makefile.prebuild:66: getarch_2nd] Error 1
Makefile:135: *** OpenBLAS: Detecting CPU failed. Please set TARGET explicitly, e.g. make TARGET=your_cpu_target. Please read README for the detail..  Stop.

there is this information (OpenBLAS: Detecting fortran compiler failed. Cannot compile LAPACK. Only compile BLAS.
) when using command: make  TARGET=SKYLAKEX

**Comment by wangzheng00** [comment]
BTW:
if in my server, there is no AVX512BF16, can I set "TARGET=SKYLAKEX" by manual, it can run successful?

**Comment by martin-frbg** [comment]
Yes, building with "TARGET=SKYLAKEX" should succeed in your case (but as the warning message mentioned, you will need a Fortran compiler if you want the LAPACK component as well (which is mostly just a copy of the "netlib" reference implementation of LAPACK). 
I do wonder why cpu detection did not work, and why you get the missing parameters error when building for Cooperlake. Which version of OpenBLAS are you trying to build ? (Cooperlake support was added in 0.3.11, and Ice Lake should be autodetected since 0.3.17, current release is 0.3.18. If you want the latest from github, be sure to check out the "develop" branch, not "master")

**Comment by wangzheng00** [comment]
sorry, I used OpenBLAS: v0.3.3.
just now I just develop branch, but also "Detecting CPU failed", see CPU information and error:
[root@localhost OpenBLAS]# git branch
* develop

Model name:          Intel Xeon Processor (Icelake)
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat avx512vbmi umip avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq la57 fsrm md_clear arch_capabilities

[root@localhost OpenBLAS]# make
Makefile:160: *** OpenBLAS: Detecting CPU failed. Please set TARGET explicitly, e.g. make TARGET=your_cpu_target. Please read README for the detail..  Stop.

**Comment by brada4** [comment]
can you post one core from /proc/cpuinfo ? it is Q2 21, maybe not yet detected. , namely model stepping codes above cpuid flags

**Comment by martin-frbg** [comment]
yes please post the family/model numbers from /proc/cpuinfo. OpenBLAS should already recognize family 6, model 106 (which I got from a benchmark result posted on spec.org) but maybe there are additional codes for xeon8358 variants (or there is an error in the cpu detection code...)

**Comment by martin-frbg** [comment]
Code in cpuid_x86.c works as expected for family 6, model 106

**Comment by brada4** [comment]
Should be same 106:
https://www.spec.org/cpu2017/results/res2021q2/cpu2017-20210426-25722.html
@wangzheng00 please do "make clean" and then run "make", and also make sure you run develop branch either by fresh git clone or https://github.com/xianyi/OpenBLAS/archive/refs/heads/develop.zip (you get that link from green button above file list, on the right)

**Comment by wangzheng00** [comment]
@brada4 , now it seems OK, do you update the code?
and why couldn't detected before?

**Comment by martin-frbg** [comment]
There wete no relevant code updates in the meantime. Probably you unpacked the current version into the same folder where you had previously built 0.3.3, and the build system picked up some of the outdated tools and objects ?

**Comment by wangzheng00** [comment]
got it, thanks!
