### ISSUE TITLE
OpenBLAS causes "import torch" to crash with segment fault

### ISSUE THREAD

**Issue by zhmlcg** [xianyi/OpenBLAS#3436]
Environment:

- Remote Linux with core version 5.8.0. I am not a super user.
- Python 3.8.6
- CUDA Version: 11.1
- GPU is RTX 3090 with driver version 455.23.05
- CPU: Intel Core i9-10900K
- PyTorch version: 1.8.0+cu111 (I found it at /usr/local/lib/python3.8/dist-packages/torch/version.py)
- System imposed RAM quota: 4GB
- System imposed number of threads: 512198
- System imposed `RLIMIT_NPROC` value: 300

PyTorch uses numpy and numpy uses OpenBLAS. However, a setting of (or more accurately failure to set) `OPENBLAS_NUM_THREADS` causes numpy to crash, which in turn causes PyTorch to crash when running `import torch` in python3 command line.

I have two versions of numpy installed. One is system-wide installed in system folders whose version is 1.19.5. Another is installed in my user space whose version is 1.21.3.

If I run `import torch` with numpy 1.19.5 installed in system, python3 just crashes with error message:

> Segmentation fault (core dumped)

If I run `import torch` with numpy 1.21.3 installed in my user space, python3 crashes with some additional error message:

> OpenBLAS blas_thread_init: pthread_create failed for thread 10 of 20: Resource temporarily unavailable
> OpenBLAS blas_thread_init: RLIMIT_NPROC 300 current, 300 max
> OpenBLAS blas_thread_init: pthread_create failed for thread 11 of 20: Resource temporarily unavailable
> OpenBLAS blas_thread_init: RLIMIT_NPROC 300 current, 300 max
> OpenBLAS blas_thread_init: pthread_create failed for thread 12 of 20: Resource temporarily unavailable
> OpenBLAS blas_thread_init: RLIMIT_NPROC 300 current, 300 max
> OpenBLAS blas_thread_init: pthread_create failed for thread 13 of 20: Resource temporarily unavailable
> OpenBLAS blas_thread_init: RLIMIT_NPROC 300 current, 300 max
> Segmentation fault (core dumped)

The segfault can be solved by setting `OPENBLAS_NUM_THREADS` environment variable properly using the following two lines before `import torch`:
```
import os
os.environ['OPENBLAS_NUM_THREADS'] = '5'

```

5 is used for numpy 1.21.3. If I use numpy 1.19.5, the number should be reduced to only 2. Under numpy 1.21.3, If I increment `OPENBLAS_NUM_THREADS` to 6, numpy will produce the following error:

> Traceback (most recent call last):
>   File "\<stdin\>", line 1, in <module>
>   File "/usr/local/lib/python3.8/dist-packages/torch/__init__.py", line 196, in \<module\>
>     from torch._C import *
> ImportError: numpy.core.multiarray failed to import

Here come my questions:
1) What does `OPENBLAS_NUM_THREADS` environment variable do? I tried to google documentation for it but of no avail.

2) I think the quota for number of threads is large enough (512198), so is `RLIMIT_NPROC` value, why did OpenBLAS still report error "Resource temporarily unavailable" as above?

3) If I did not set `OPENBLAS_NUM_THREADS`, how much quota of number of threads or others should I set so that I can run `import torch` without segfault errors?

Thank you for help.

**Comment by martin-frbg** [comment]
OpenBLAS is "only" quoting the error message it received from the operating system here. So either "something else" in your numpy/torch setup is changing the limits (or eating into the threads quota, or there may be several instances of OpenBLAS getting created, each trying to start as many threads as there are cpu cores (20 apparently on your system). With the environment variable, you limit OpenBLAS to the given number of threads instead.

**Comment by martin-frbg** [comment]
Probably what you are getting here is pytorch starting as many threads as it sees cores in the system, and each of them starts its own instance of OpenBLAS, which again defaults to building a thread pool corresponding to the number of cores. So you would need RLIMIT_NPROC big enough to accomodate 20*20 =400 threads

**Comment by brada4** [comment]
If that is the case it is best to set OPENBLAS_NUM_THREADS=1 , with present setup it starts ncpu x ncpu threads that is very inefficient as all openblas functions will work with RAM instead of cache.

**Comment by UnitedMarsupials** [comment]
I'm seeing something very similar here, on FreeBSD/amd64. Here is the stack extract by gdb from the core-dump:
```
#0  0x000000082e987b11 in idamax_k () at /opt/lib/libopenblas.so.0
#1  0x000000082eaa34e6 in dgetf2_k () at /opt/lib/libopenblas.so.0
#2  0x000000082ea9ee94 in dgetrf_parallel () at /opt/lib/libopenblas.so.0
#3  0x000000082ea9ee94 in dgetrf_parallel () at /opt/lib/libopenblas.so.0
#4  0x000000082ea9ee94 in dgetrf_parallel () at /opt/lib/libopenblas.so.0
#5  0x000000082ea9ee94 in dgetrf_parallel () at /opt/lib/libopenblas.so.0
#6  0x000000082ea9ee94 in dgetrf_parallel () at /opt/lib/libopenblas.so.0
#7  0x000000082e642fc6 in dgetrf_ () at /opt/lib/libopenblas.so.0
#8  0x000000095c51d103 in ??? () at /opt/lib/python3.11/site-packages/scipy/linalg/_flapack.cpython-311.so
#9  0x0000000822911ff9 in _PyObject_MakeTpCall () at /opt/lib/libpython3.11.so.1.0
#10 0x0000000822a1301f in _PyEval_EvalFrameDefault () at /opt/lib/libpython3.11.so.1.0
#11 0x0000000822a045af in PyEval_EvalCode () at /opt/lib/libpython3.11.so.1.0
#12 0x0000000822a00006 in ??? () at /opt/lib/libpython3.11.so.1.0
#13 0x000000082296814e in ??? () at /opt/lib/libpython3.11.so.1.0
#14 0x0000000822a1552c in _PyEval_EvalFrameDefault () at /opt/lib/libpython3.11.so.1.0
#15 0x0000000822a17e65 in ??? () at /opt/lib/libpython3.11.so.1.0
#16 0x00000008229145b1 in ??? () at /opt/lib/libpython3.11.so.1.0
#17 0x0000000822914388 in PyObject_CallMethodObjArgs () at /opt/lib/libpython3.11.so.1.0
#18 0x0000000822a46c74 in PyImport_ImportModuleLevelObject () at /opt/lib/libpython3.11.so.1.0
#19 0x0000000822a0ef5d in _PyEval_EvalFrameDefault () at /opt/lib/libpython3.11.so.1.0
#20 0x0000000822a045af in PyEval_EvalCode () at /opt/lib/libpython3.11.so.1.0
#21 0x0000000822a00006 in ??? () at /opt/lib/libpython3.11.so.1.0
#22 0x000000082296814e in ??? () at /opt/lib/libpython3.11.so.1.0
#23 0x0000000822a1552c in _PyEval_EvalFrameDefault () at /opt/lib/libpython3.11.so.1.0
#24 0x0000000822a17e65 in ??? () at /opt/lib/libpython3.11.so.1.0
#25 0x00000008229145b1 in ??? () at /opt/lib/libpython3.11.so.1.0
#26 0x0000000822914388 in PyObject_CallMethodObjArgs () at /opt/lib/libpython3.11.so.1.0
#27 0x0000000822a46c74 in PyImport_ImportModuleLevelObject () at /opt/lib/libpython3.11.so.1.0
...
```
Setting the `OPENBLAS_NUM_THREADS` to 1 has no obvious effect...

**Comment by martin-frbg** [comment]
not sure from your backtrace what makes this "very similar" to the three years old case - are you getting a message about thread creation failure at all ? and which version of OpenBLAS is this please, anything recent (current is 0.3.28) ?
