### ISSUE TITLE
Invalid when compiling single-threaded Openblas on windows

### ISSUE THREAD

**Issue by Vasline** [xianyi/OpenBLAS#3438]
Compile options on windows : make BINARY=64 USE_THREAD=0;
Using the libopenblas.dll.a library in the lib folder, the number of threads obtained by the openblas_get_num_threads() function is equal to the number of CPU cores 4 instead of 1. Why? Even if I compile multi-threaded openblas and use openblas_set_num_threads(1), but the number of threads obtained by openblas_get_num_threads() is still equal to the number of CPU cores 4 instead of 1.

**Comment by martin-frbg** [comment]
Odd - which version are you building ? openblas_get_num_threads() is hardcoded to return 1 when "SMP" is not defined (which is a consequence of USE_THREAD=0) so this should not happen.

**Comment by Vasline** [comment]
@martin-frbg 0.3.18 version. 
![image](https://user-images.githubusercontent.com/19258558/140022139-3c56eaf3-d65d-4e6a-8dd2-c92d869a2cb8.png)

**Comment by Vasline** [comment]
> Odd - which version are you building ? openblas_get_num_threads() is hardcoded to return 1 when "SMP" is not defined (which is a consequence of USE_THREAD=0) so this should not happen.

**Comment by Vasline** [comment]
> Odd - which version are you building ? openblas_get_num_threads() is hardcoded to return 1 when "SMP" is not defined (which is a consequence of USE_THREAD=0) so this should not happen.

I use the following command to compile under windows: make BINARY=64 USE_THREAD=0 CC=gcc FC=gfortran

**Comment by martin-frbg** [comment]
I have checked both make and cmake builds on Linux and they behave correctly, I do not see how Windows builds could be different.
Is there any chance that you checked out the very old "master" branch instead of 0.3.18 or "develop" ? Or  you might have multiple versions of libopenblas.dll.a on your system and were linking to the wrong one by mistake ? 
(The output from your testcase reports a DYNAMIC_ARCH build, also I would expect any OpenBLAS since version 0.3.4 from 2018 to include its version number in the config message - you should be seeing something like `Config: OpenBLAS 0.3.18 NO_AFFINITY SINGLE_THREADED` in the output of your program)

**Comment by Vasline** [comment]
> I have checked both make and cmake builds on Linux and they behave correctly, I do not see how Windows builds could be different. Is there any chance that you checked out the very old "master" branch instead of 0.3.18 or "develop" ? Or you might have multiple versions of libopenblas.dll.a on your system and were linking to the wrong one by mistake ? (The output from your testcase reports a DYNAMIC_ARCH build, also I would expect any OpenBLAS since version 0.3.4 from 2018 to include its version number in the config message - you should be seeing something like `Config: OpenBLAS 0.3.18 NO_AFFINITY SINGLE_THREADED` in the output of your program)

The openblas I compiled on Linux and Android are also normal, but this happens only on Windows. I tried 0.3.12 and 0.3.14, the result is still incorrect. I tried various compilation options, but they still didn’t work. This problem has bothered me for a long time.

**Comment by Vasline** [comment]
@martin-frbg Can you check it on windows?

**Comment by Vasline** [comment]
@martin-frbg The library in the green box can be set to single thread, but the library in the red box cannot be set to less than 4 . The function symbols in the library in the green box are far less than those in the library in the red box.  I need to link the library in the red box.
![image](https://user-images.githubusercontent.com/19258558/140050314-40ae4e57-8ee8-4726-bd96-952923b54c40.png)

**Comment by Vasline** [comment]
@martin-frbg  The library in the green box can be set to single thread, but the library in the red box cannot be set to less than 4 . The function symbols in the library in the green box are far less than those in the library in the red box. I need to link the library in the red box.

![image](https://user-images.githubusercontent.com/19258558/140050815-5154bc8e-3484-48a6-b941-0bc3eaa398d2.png)

**Comment by martin-frbg** [comment]
Works for me (with the cross-compiled Windows binaries provided under the Releases section of the OpenBLAS github page). But as far as I understand mingw/Windows conventions, the dll.a is just an import library (note its small size) and your program will load "a" libopenblas.dll on startup - maybe that is where it is picking up some very old version elsewhere on your system ? 
Note that you should definitely see "Config: OpenBLAS 0.3.18" at the start of the config string output, and for your latest screenshot (where you have small library sizes and a "libopenblas_haswell", meaning it was built specifically for that cpu) there should be no "DYNAMIC_ARCH" in the string. I bet somewhere in your DLL search path is a libopenblas.dll from about three years ago...

**Comment by brada4** [comment]
In the last powershell screenshot you can see detected architecture being Prescott. That is generic fallback if your CPU is not detected. You certainly need newer version. Screenshot from Cpu-Z will not hurt if you still see prescott with latest version.
