### ISSUE TITLE
benchmark/cgemv.goto and zgemv.goto hit Segmentation fault when initializing inputs (seen on x86-64 and s390x)

### ISSUE THREAD

**Issue by mhillenbrand** [xianyi/OpenBLAS#3439]
Hi,

I observe Segmentation faults when running `benchmark/cgemv.goto` or `benchmark/zgemv.goto` from the current `develop` branch on both x86-64 (on Fedora 34) and s390x (Fedora 31 / Ubuntu 21.04).

On my laptop:
```
$ ./benchmark/cgemv.goto 
From :   1  To : 200 Step =   1 Trans = 'N' Inc_x = 1 Inc_y = 1 Loops = 1
   SIZE       Flops
      1x1 :        7.01 MFlops   0.000001 sec
      2x2 :       46.92 MFlops   0.000001 sec
...
    142x142 :      194.48 MFlops   0.000829 sec
    143x143 : Segmentation fault (core dumped)
```

backtrace:
```
... in main (argc=<optimized out>, argv=<optimized out>) at gemv.c:133
133                                     a[(long)j + (long)i * (long)m * COMPSIZE] = ((FLOAT) rand() / (FLOAT) RAND_MAX) - 0.5;
```

which (after adding some debug output) clearly goes out of range (allocating 80000 elements in A, then accessing element 80938).

_(edit:)_ None of the environment variables that influence gemv.c were set.

**Comment by mhillenbrand** [comment]
... looks like the factor COMPSIZE goes into the index twice
- in the range of i
  https://github.com/xianyi/OpenBLAS/blob/abf45f72354ab9aefb24aa21b20649fc22bba64f/benchmark/gemv.c#L127
- and when calculating the index
  https://github.com/xianyi/OpenBLAS/blob/abf45f72354ab9aefb24aa21b20649fc22bba64f/benchmark/gemv.c#L128

**Comment by mhillenbrand** [comment]
Git bisect points to commit 0b909203cb31f4667bfc9172d475d20d53bbad75

Reverting the first change in that patch prevents the segfaults. That is, I believe the row and column indices were flipped inadvertently at that place.

**Comment by gxw-loongson** [comment]
I think a[(long)i + (long)j * (long)n * COMPSIZE] mybe better.
