### ISSUE TITLE
Possible bug in memory.c

### ISSUE THREAD

**Issue by NdK73** [xianyi/OpenBLAS#3441]
Hello.

I've been directed here from Debian bugtracker ( https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=995450 ) since this should be the most appropriate place to report it.

I've had troubles with octave and cdo that segfaulted when I installed libopenblas0-pthread but worked when replacing -pthread with -serial.

The "TL;DR" from the Debian bugtracker is:
-8<--
Following quite a bit of debugging, I think I've found a wrong check in 
memory.c file, at line 2789 (0.3.13+ds-3):
https://sources.debian.org/src/openblas/0.3.13+ds-3/driver/others/memory.c/

IIUC, it should check *func != NULL instead of func != NULL . func 
should be "guaranteed" to not be NULL since memoryalloc is defined at 
line 2641.

Else, when it reaches the last element of memoryalloc[], func is not 
NULL but *func is, and it's what gets dereferenced.
-8<--

Am I right?

Tks,
 Diego

**Comment by martin-frbg** [comment]
Oops. Yes, you are right of course, and this was supposed to be adressed by @alexhenrie 's PR #3085 for 0.3.14. Unfortunately memory.c is a siamese twin of two implementations and the fix was only applied to the TLS version of the thread buffer management. (Obviously my fault for not noticing, or perhaps forgetting soon after the merge. Sorry.)

**Comment by NdK73** [comment]
The important thing is that it gets corrected.
In the mean time I confirmed that it got triggered by an OOM situation: by default I limit users (including root) to 1G RAM, so it was not easy to spot and others couldn't reproduce it.
Tks!

**Comment by martin-frbg** [comment]
I would hope that this is not easily triggered, given how long the bug has been in the code. On the other hand, given the weird range of hardware and software OpenBLAS gets used for, maybe earlier victims were unable to trace it to OpenBLAS. 
Would you like to submit a PR yourself, or do you prefer me to apply the quick fix?
