### ISSUE TITLE
Error when compiling on a xenserver or xcp-ng based vm

### ISSUE THREAD

**Issue by aaroneg** [xianyi/OpenBLAS#3445]
The build system seems to check the CPU model instead of checking the actual CPU capabilities from the OS when compiling.

I was trying to build several different versions of OpenBLAS for my HPC environment and it kept breaking with feedback I was not able to interpret. Some of the kind folks at easybuild helped me diagnose it down to the build process expecting these instruction sets even though these were not being passed through to the VM. 

I was able to get past the problem by running `/opt/xensource/libexec/xen-cmdline --set-xen cpuid=avx512` on the hypervisor host and rebooting so the CPU features are passed into the VM. 

I'm not sure if this is necessarily a bug worth fixing, as this should be a pretty rare case - but at minimum I wanted to make sure it's here in case anyone else runs into it. 

Thank you.

**Comment by martin-frbg** [comment]
Yes the build system does try to identify the hardware by its CPUID when no build TARGET was supplied, but there are additional checks for AVX512 etc that should ensure that a cpu with unavailable functionality is treated like the appropriate earlier generation e.g Haswell.
Can you provide more context please, like the error messages you got and the cpuinfo produced before setting cpuid in Xen ? (Could be it was supplying some made-up ID that does not correspond to any known hardware)

**Comment by aaroneg** [comment]
So in this case it's version 0.3.7, I'll see if I can find more specific information. It's a little hard for me to parse out the relevant build logs from the easybuild log. 

Here is at least one example that seems to repeat:
```
In file included from /opt/apps/easybuild/software/GCCcore/8.3.0/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/immintrin.h:45,
                 from ../kernel/x86_64/sgemm_kernel_16x4_skylakex.c:57:
/opt/apps/easybuild/software/GCCcore/8.3.0/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/avx512fintrin.h:3918:1: error: inlining failed in call to always_inline _mm512_broadcastss_ps: target specific option mismatch
 _mm512_broadcastss_ps (__m128 __A)
 ^~~~~~~~~~~~~~~~~~~~~
../kernel/x86_64/sgemm_kernel_16x4_skylakex.c:659:12: note: called from here
  zmm2   =  _mm512_broadcastss_ps(_mm_load_ss(BO));  \
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../kernel/x86_64/sgemm_kernel_16x4_skylakex.c:1082:5: note: in expansion of macro KERNEL16x1_SUB
     KERNEL16x1_SUB()
     ^~~~~~~~~~~~~~
```
[easybuild-PJPHuZ.log](https://github.com/xianyi/OpenBLAS/files/7502616/easybuild-PJPHuZ.log)

here's the full log in case there's enough information here to be meaningful to you. It may be that the problem has since been fixed, but a lot of this HPC software depends on specific versions so I don't have a lot of options as far as just using the most recent version goes.

**Comment by martin-frbg** [comment]
A dependency on 0.3.7 from two years ago is a bit unfortunate (and AVX512 support back then was mostly in SGEMM)

**Comment by aaroneg** [comment]
Yep. Like I say, I don't necessarily expect you all to change anything (especially on a release that old) but it may help some other person trying to get it all to compile. Nothing in the error messages made any sense to me as a non-developer, much less someone who can read C code. it took a while and a few people to track down so I wanted it to be a searchable issue since it's a weird combination of a build system's logic and a hypervisor unexpectedly hiding cpu features.

**Comment by martin-frbg** [comment]
Yes the error message is not exactly helpful, in particular as it is usually printed when `-march=skylake-avx512` was not specified (which is not the case here). This could also be your similarly old gcc8.3 misbehaving though. Anyway I have amended the FAQ entry for building on QEMU/KVM to include XEN now.
