### ISSUE TITLE
What is the difference between FUSED_KERNEL_OPERATION and KERNEL_OPERATION?

### ISSUE THREAD

**Issue by AnonymousYWL** [xianyi/OpenBLAS#3463]

**Comment by wjc404** [comment]
FUSED_KERNEL_OPERATION fuses kernel calculation and copy operation. In the multiplication of medium-to large matrices, the data from matrices A and B are copied(or packed) to buffers before doing calculations. The elements are reordered in the copy step to make subsequent calculations more efficient. The cost of copy operations can be neglected comparing to the speedup they bring to the kernel calculations. I guess the purpose of creating FUSED_KERNEL_OPERATION is to overlap copy operation(memory-intensive) with part of calculation task(CPU-intensive) to further improve the performance.

**Comment by AnonymousYWL** [comment]
Has&nbsp;&nbsp;FUSED_KERNEL_OPERATION been&nbsp;implemented?


 
---Original---
From: ***@***.***&gt;
Date: 2021/11/27 19:24:10
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [xianyi/OpenBLAS] What is the difference betweenFUSED_KERNEL_OPERATION and KERNEL_OPERATION? (Issue #3463)




 
FUSED_KERNEL_OPERATION fuses kernel calculation and copy operation. In the multiplication of medium-to large matrices, the data from matrices A and B are copied(or packed) to buffers before doing calculations. The elements are reordered in the copy step to make subsequent calculations more efficient. The cost of copy operations can be neglected comparing to the speedup they bring to the kernel calculations. I guess the purpose of creating FUSED_KERNEL_OPERATION is to further overlap copy operation with part of calculation task, to reduce the standalone cost of copy.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by martin-frbg** [comment]
Unfortunately I do not think any of the fused GEMM kernels are actually implemented - this is probably just one of several empty "hooks" that the creator of the original GotoBLAS added in the design phase.

**Comment by AnonymousYWL** [comment]
thanks for your reply


 
---Original---
From: "Martin ***@***.***&gt;
Date: 2021/11/27 19:41:02
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [xianyi/OpenBLAS] What is the difference betweenFUSED_KERNEL_OPERATION and KERNEL_OPERATION? (Issue #3463)




 
Unfortunately I do not think any of the fused GEMM kernels are actually implemented - this is probably just one of several empty "hooks" that the creator of the original GotoBLAS added in the design phase.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
