### ISSUE TITLE
Intel Xeon appropriate TARGET for make

### ISSUE THREAD

**Issue by carriunix** [xianyi/OpenBLAS#3477]
Greetings,

I'm trying to install OpenBLAS on a IBM SystemX3650 server, and having this error:

`Makefile:160: *** OpenBLAS: Detecting CPU failed. Please set TARGET explicitly, e.g. make TARGET=your_cpu_target.`

What would be the appropriate TARGET for make in a Intel Xeon "Netburst" (also know as "P68") arch?

**Comment by martin-frbg** [comment]
Uh. Try `TARGET=PRESCOTT` if it is really one of the original Netburst Xeons from the early 2000s (seems IBM kept using the X3650 designation for more recent models, so I also find specifications for later cpus with AVX2 that would be SANDYBRIDGE).
What is your operating system ?

**Comment by martin-frbg** [comment]
If 1st generation (and 32 bit), try `TARGET=NORTHWOOD`

**Comment by carriunix** [comment]
@martin-frbg , thank you for reply. Indeed, it is a 2006 server. `TARGET=PRESCOTT` seems to work perfectly. Thanks!
