### ISSUE TITLE
Crash on cblas_sgemm with large array on Windows but not on Linux

### ISSUE THREAD

**Issue by W-Geong** [xianyi/OpenBLAS#3481]
When calling cblas_sgemm on Windows 10 with VS2019
![1 74JUM3UG571Z2W_`}_)9D](https://user-images.githubusercontent.com/38862569/146190700-fadb5324-c0f8-4e60-9c0c-4719ab170008.png)
where M=128 N=206 K=18
output_feature_map = [M*N]

it crashed like this:
![ACC7G717__) J91L`FURO~8](https://user-images.githubusercontent.com/38862569/146190624-3de54eb9-74f0-491d-b092-8b0ac3c65b20.png)
with stack called:
![2)XGGYW`0P2IDGM Y95D9F2](https://user-images.githubusercontent.com/38862569/146190994-8855e626-e89d-4a45-ae59-4acaf8f5b34c.png)

Same code are OK with Linux.
I found it works if N is less than 114, that is it crashs only on large array.
I tested that the memory allocation of the input array is no problem.

Now I can only cut the large matrix into small pieces and then concat them. This is just an expedient measure.
I guess it has something to do with the compiler, but I don't know what the problem is.
I would be very grateful if someone could give me some help.

**Comment by W-Geong** [comment]
![ACC7G717__) J91L`FURO~8](https://user-images.githubusercontent.com/38862569/146195352-e02d697d-0521-4a2d-bd2d-62455e4372fe.png)
It says Access conflict writing to location 0x00...024

**Comment by martin-frbg** [comment]
Looks like this could be a re-run of #2335 (which was closed due to no feedback). The thread handling is different between Linux and Windows and I am not very familiar with the latter (the code in blas_server_win32.c is mostly unchanged from original GotoBLAS around 2010, and I see nothing obviously wrong with it). 
Could you try if the gcc-crosscompiled library from https://github.com/xianyi/OpenBLAS/releases/download/v0.3.18/OpenBLAS-0.3.18-x64.zip gives the same crash ?

**Comment by W-Geong** [comment]
I found the reason. This is because the static library is referenced but the dynamic library is not referenced correctly. Thank you very much @martin-frbg

**Comment by martin-frbg** [comment]
Glad to know you got it working. Though not sure I understand correctly - did you mean there is something wrong in the way the DLL is built in general, or just in your VS2019 environment ?

**Comment by W-Geong** [comment]
I made a stupid mistake.  I built from the source, but did not generate a DLL. After downloading the gcc-crosscompiled library, I realized that there should be DLL in addition to LIB. The gcc-crosscompiled library works well.
Surprisingly, small arrays can be calculated successfully without DLL.
If someone has the same problem, make sure that both static and dynamic libraries are generated and referenced correctly.
Thank you for your help again. @martin-frbg

**Comment by martin-frbg** [comment]
Unfortunately I am not truely familiar with Windows library semantics. But what I think could be happening is that (1) the small arrays did not invoke multithreading (there is a threshold in the interface code to make sure that the thread overhead does not outweigh the performance benefit from multithreading) and (2) when the DLL is loaded, initializer code from its DllMain() function is executed automatically and sets up the thread management, while with static linking (and MSVC specifically) I am not even sure if there is any way to call the initializer function (gotoblas_init) yourself.

**Comment by martin-frbg** [comment]
Hmm. Digging deeper, we have been there before : #2106 And the code where the crash happened even _has_ an emergency mechanism to rectify a missed initialization, only that it is guarded by `#ifdef CYGWIN` as it was meant to be used after a Unix-like fork()...

**Comment by brada4** [comment]
it is pytorch? conv1d?
backtrace shows int64 api blas dll is expected. default dlls are int32.
