### ISSUE TITLE
Remove the extraneous brace in cpuid_mips64.c

### ISSUE THREAD

**Issue by kevlo** [xianyi/OpenBLAS#3482]
[patch-cpuid_mips64.c.txt](https://github.com/xianyi/OpenBLAS/files/7725215/patch-cpuid_mips64.c.txt)
In cpuid_mips64.c, it added an extra '}' in detect().
Attached patch fixes it, thanks.

**Comment by martin-frbg** [comment]
Oops, thanks. However the brace is not extraneous, it "just" belongs before the `#endif`. I'll prepare a PR.

**Comment by kevlo** [comment]
@martin-frbg 

Ah exactly!  Thanks.
