### ISSUE TITLE
Update LAPACK to 3.10

### ISSUE THREAD

**Issue by h-vetinari** [xianyi/OpenBLAS#3495]
Just opening an issue to track since there doesn't seem to be one. Quoting from #2320:
> @martin-frbg: As usual, this is not simply a drop-in replacement here as OpenBLAS uses modified Makefiles (and own CMakelists) to replace some functions with optimized implementations. There are also some platform-specific changes and header rearrangements that need to be merged during an update.

**Comment by martin-frbg** [comment]
As noted elsewhere earlier, most if not all functional changes from 3.10 are already reflected in the OpenBLAS codebase.

**Comment by martin-frbg** [comment]
3.10.1 was released today, this is probably a worthwile opportunity for updating to the most recent fixes (and all the non-functional changes such as inline documentation updates and removal of all dates and version numbers)
