### ISSUE TITLE
是否支持测试飞腾系列cpu

### ISSUE THREAD

**Issue by wanghaifeng-yuntuteng** [xianyi/OpenBLAS#3497]
在下面标出的支持中国国产cpu系列里面有龙芯，但没有飞腾。请问是否能够支持飞腾系列cpu，如FT 2000

Force Target Examples:

make TARGET=NEHALEM
make TARGET=LOONGSON3A BINARY=64
make TARGET=ISTANBUL

Supported List:
1.X86/X86_64
a)Intel CPU:
P2
KATMAI
COPPERMINE
NORTHWOOD
PRESCOTT
BANIAS
YONAH
CORE2
PENRYN
DUNNINGTON
NEHALEM
SANDYBRIDGE
HASWELL
SKYLAKEX
ATOM
COOPERLAKE
SAPPHIRERAPIDS

b)AMD CPU:
ATHLON
OPTERON
OPTERON_SSE3
BARCELONA
SHANGHAI
ISTANBUL
BOBCAT
BULLDOZER
PILEDRIVER
STEAMROLLER
EXCAVATOR
ZEN

c)VIA CPU:
SSE_GENERIC
VIAC3
NANO

2.Power CPU:
POWER4
POWER5
POWER6
POWER7
POWER8
POWER9
POWER10
PPCG4
PPC970
PPC970MP
PPC440
PPC440FP2
CELL

3.MIPS CPU:
P5600
MIPS1004K
MIPS24K

4.MIPS64 CPU:
SICORTEX
LOONGSON3A
LOONGSON3B
I6400
P6600
I6500

5.IA64 CPU:
ITANIUM2

6.SPARC CPU:
SPARC
SPARCV7

7.ARM CPU:
CORTEXA15
CORTEXA9
ARMV7
ARMV6
ARMV5

8.ARM 64-bit CPU:
ARMV8
CORTEXA53
CORTEXA57
CORTEXA72
CORTEXA73
NEOVERSEN1
CORTEXA55
EMAG8180
FALKOR
THUNDERX
THUNDERX2T99
TSV110
THUNDERX3T110
VORTEX

9.System Z:
ZARCH_GENERIC
Z13
Z14

10.RISC-V 64:
RISCV64_GENERIC
C910V

11.LOONGARCH64:
LOONGSON3R5

**Comment by brada4** [comment]
Datasheet says it is TARGET=ARMv8 https://phytium.com.cn/en/article/97

**Comment by brada4** [comment]
You can attach `/proc/cpuinfo` here or try to enable autodetection PR via
driver/others/dynamic_arm64.c
cpuid_arm64.c

**Comment by martin-frbg** [comment]
yes TARGET=ARMV8 should work.
Is it this cpu ?
https://github.com/util-linux/util-linux/issues/1036

**Comment by brada4** [comment]
There is another related: https://www.titanwolf.org/Network/q/74696651-fcaf-470d-b084-1ebf2dba6d98/y
Would be cool to cover whole series at once...

**Comment by brada4** [comment]
partno-s from phytium website:
|partno|name| 
|-|-|
|663|S2500,FT2000|
|662|FT2000+|
|661|FT2000A|
|660|FT1500A,D2000|

**Comment by martin-frbg** [comment]
Returning to this issue, all current Phytium cpus appear to be ARMV8.0A , and OpenBLAS´ cpuid handling code already maps any unknown arm64 vendor hardware to the basic ARMV8 target. So the primary benefit of adding model detection would be to get exact cache details, which are mostly unused in the arm64 codepaths (pretty much the same situation as with the current EMAG8180 "support" ). Any attempt at tuning would likely require access to such hardware.

**Comment by xianyi** [comment]
Could you try Cortex-A72 target？
