### ISSUE TITLE
libopenblas.a not found after installing OpenBLAS package on cluster

### ISSUE THREAD

**Issue by ash2223** [xianyi/OpenBLAS#3499]
Hello,

I successfully installed the OpenBLAS package within an anaconda environment on my university's cluster, but I can't seem to find the libopenblas.a file anywhere within it. I wrote: 

conda activate EFTClass
conda install -c anaconda openblas

However, when I navigate to the lib folder within the environment named EFTClass, the list of files within that folder does not include libopenblas.a, only libopenblas.so (screenshot below). Does anyone know if being on a cluster make a difference? I've done the exact same procedure locally and I end up finding the libopenblas.a file in the correct folder. Is there a way to generate the libopenblas.a file in the lib folder in the cluster? Thank you so much!

-Adam

<img width="1168" alt="Screen Shot 2021-12-25 at 3 31 21 PM" src="https://user-images.githubusercontent.com/61329093/147395133-b845269c-b326-4104-a397-dffa2036762e.png">

**Comment by brada4** [comment]
You certainly do not need to have static libs everywhere. They are needed around the C compiler in the place you build enormous size monolith binaries packing all dependencies. The problem in your image is static python libraries, but no static compiler runtimes, so in fact that environment is incomplete for building those monstrosities.

**Comment by ash2223** [comment]
Ah, got it. Thanks Andrew!
