### ISSUE TITLE
OpenBLAS won't compile

### ISSUE THREAD

**Issue by sbrignone** [xianyi/OpenBLAS#3501]
OpenBLAS fail to compile.
architecture: Intel skylake
os: Windows 10 (Version 20H2)
compiler: gcc  (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0

D:\OpenBLAS>make
process_begin: CreateProcess(NULL, uname -m, ...) failed.
The system cannot find the path specified.
process_begin: CreateProcess(NULL, uname -s, ...) failed.
The system cannot find the path specified.
process_begin: CreateProcess(NULL, perl ./c_check Makefile.conf config.h gcc, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [config.h] Error 2
....

**Comment by martin-frbg** [comment]
You probably do not have the mingw-w64 "bin" folder added to your Path variable, so tools like "uname" or "perl" cannot be found.
(Or you are running this from a regular Windows "cmd" command window rather than the mingw/msys command prompt)

**Comment by sbrignone** [comment]
Thanks Martin. 
You were right. I was not running MINGW64

However, I got now a zillion of warnings and a segmentation fault at the end

$ make clean
/usr/bin/sh: C:/Program: No such file or directory
Makefile.system:283: Makefile.conf: No such file or directory
Makefile.:2: Makefile.system: Too many open files
Makefile.:122: warning: overriding commands for target `shared'
Makefile.:122: warning: ignoring old commands for target `shared
....
Makefile.:370: warning: overriding commands for target `blas-test'
Makefile.:370: warning: ignoring old commands for target `blas-test'
Makefile.:378: warning: overriding commands for target `install'
Makefile.:378: warning: ignoring old commands for target `install'
Segmentation fault

**Comment by martin-frbg** [comment]
> /usr/bin/sh: C:/Program: No such file or directory

that is probably an unquoted "C:\Program Files" somewhere in your Path variable.
What happens when you try to run just `make` again (the previous attempt stopped so early that there is probably nothing for `make clean` to remove) ?
