### ISSUE TITLE
does OpenBLAS support arm-none-eabi-gcc toochain

### ISSUE THREAD

**Issue by guoxiuhao** [xianyi/OpenBLAS#3507]
I use  ‘make TARGET=ARMV7 HOSTCC=gcc BINARY=32 CC=arm-none-eabi-gcc NOFORTRAN=1’  to compile, the Operating system used on armv7 is RTOS，but it shows 
../common.h:126:10: fatal error: sys/mman.h: No such file or directory
  126 | #include <sys/mman.h>, 
how to solve this problem

**Comment by martin-frbg** [comment]
For arm-_none_  toolchain, you will need to add the option "EMBEDDED=1" and also supply your own implementations of `malloc` and `free` (or use something like https://github.com/embeddedartistry/libmemory )

**Comment by guoxiuhao** [comment]
if i use arm-none-eabi-gcc toolchain, whether i have to implement the mmap funtion, which is used by driver/others/memory.c

**Comment by brada4** [comment]
Yes, openblas relies on mentioned functions, probably simplest already linked. You can also extract malloc/free from MUSL, or even use efence during development.
