### ISSUE TITLE
clang64 flang compile failure

### ISSUE THREAD

**Issue by bmiyuan** [xianyi/OpenBLAS#3509]
it works fine when I use mingw64 to compile openblas on windows, but it compiles failure when I use clang64 flang with Ninja generator .

I try to fix the issue, and add the FC environment variable, it can build successfully, but it seems the lapack isn't compiled. the prebuild log also shows the info :
-- Looking for a Fortran compiler - NOTFOUND
-- No Fortran compiler found, can build only BLAS but not LAPACK

Is threre a solution that can build LAPACK successfully on windows with clang64 ? thanks in advance!

**Comment by martin-frbg** [comment]
Not sure why it did not identify the clang64 version of flang - we rely on the standard "CheckLanguage" module of cmake (called in cmake/f_check,cmake as check_language(Fortran)). Perhaps cmake failed to link the small test program it tries to compile, or the flang command itself was not available in the system path ? (There may be some information in the `CMakeFiles\CMakeError.log` and/or `CMakeFiles\CMakeOutput.log` under your build directory)
As an alternative to setting FC, I guess you could try specifiying the `-DCMAKE_Fortran_COMPILER=/path/to/your/flang` option to cmake

**Comment by bmiyuan** [comment]
Hi,Martin
   thanks your advise, but it still failed.
**Build failure Infor:**

-- The ASM compiler identification is Clang
-- Found assembler: C:/msys64/clang64/bin/clang.exe
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/msys64/clang64/bin/clang.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
CMake Warning at CMakeLists.txt:90 (message):
  CMake support is experimental.  It does not yet support all build options
  and may not produce the same Makefiles that OpenBLAS ships with.


-- Looking for stdatomic.h
-- Looking for stdatomic.h - found
-- GEMM multithread threshold set to 4.
-- Multi-threading enabled with 12 threads.
-- The Fortran compiler identification is unknown
error: unknown integrated tool '-cc1'. Valid tools include '-fc1'.
-- Detecting Fortran compiler ABI info
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_Fortran_PREPROCESS_SOURCE
CMake Error at C:/Program Files/JetBrains/CLion 2021.1.1/bin/cmake/win/share/cmake-3.19/Modules/CMakeDetermineCompilerABI.cmake:48 (try_compile):
  Failed to generate test project build system.
Call Stack (most recent call first):
  C:/Program Files/JetBrains/CLion 2021.1.1/bin/cmake/win/share/cmake-3.19/Modules/CMakeTestFortranCompiler.cmake:20 (CMAKE_DETERMINE_COMPILER_ABI)
  cmake/f_check.cmake:27 (enable_language)
  cmake/prebuild.cmake:89 (include)
  cmake/system.cmake:163 (include)
  CMakeLists.txt:93 (include)


**Detailed CMakeError log info:**
Checking whether the ASM compiler is GNU using "--version" did not match "(GNU assembler)|(GCC)|(Free Software Foundation)":
clang version 13.0.0
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: C:/msys64/clang64/bin
Compiling the Fortran compiler identification source file "CMakeFortranCompilerId.F" failed.
Compiler: C:/msys64/clang64/bin/flang-new.exe 
Build flags: 
Id flags: -v 

The output was:
1
flang-new version 13.0.0
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: C:/msys64/clang64/bin
 "C:/msys64/clang64/bin/flang-new" -fc1 -emit-obj -o C:/Users/XT/AppData/Local/Temp/CMakeFortranCompilerId-22f181.o CMakeFortranCompilerId.F
error: code-generation is not available yet


Compiling the Fortran compiler identification source file "CMakeFortranCompilerId.F" failed.
Compiler: C:/msys64/clang64/bin/flang-new.exe 
Build flags: 
Id flags:  

The output was:
1
error: code-generation is not available yet


Compiling the Fortran compiler identification source file "CMakeFortranCompilerId.F" failed.
Compiler: C:/msys64/clang64/bin/flang-new.exe 
Build flags: 
Id flags: -c 

The output was:
1
error: code-generation is not available yet


Compiling the Fortran compiler identification source file "CMakeFortranCompilerId.F" failed.
Compiler: C:/msys64/clang64/bin/flang-new.exe 
Build flags: 
Id flags: -fpp 

The output was:
1
flang-new: error: unknown argument: '-fpp'


Compiling the Fortran compiler identification source file "CMakeFortranCompilerId.F" failed.
Compiler: C:/msys64/clang64/bin/flang-new.exe 
Build flags: 
Id flags: -v 

The output was:
1
flang-new version 13.0.0
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: C:/msys64/clang64/bin
 "C:/msys64/clang64/bin/flang-new" -fc1 -emit-obj -o C:/Users/XT/AppData/Local/Temp/CMakeFortranCompilerId-f417fc.o CMakeFortranCompilerId.F
error: code-generation is not available yet


Compiling the Fortran compiler identification source file "CMakeFortranCompilerId.F" failed.
Compiler: C:/msys64/clang64/bin/flang-new.exe 
Build flags: 
Id flags:  

The output was:
1
error: code-generation is not available yet


Compiling the Fortran compiler identification source file "CMakeFortranCompilerId.F" failed.
Compiler: C:/msys64/clang64/bin/flang-new.exe 
Build flags: 
Id flags: -c 

The output was:
1
error: code-generation is not available yet


Compiling the Fortran compiler identification source file "CMakeFortranCompilerId.F" failed.
Compiler: C:/msys64/clang64/bin/flang-new.exe 
Build flags: 
Id flags: -fpp 

The output was:
1
flang-new: error: unknown argument: '-fpp'


Checking whether the Fortran compiler is Compaq using "-what" did not match "Compaq Visual Fortran":
flang-new: error: unknown argument: '-what'
flang-new: error: no input files
Checking whether the Fortran compiler is NAG using "-V" did not match "NAG Fortran Compiler":
flang-new: error: argument to '-V' is missing (expected 1 value)
flang-new: error: no input files
Checking whether the Fortran compiler is Compaq using "-what" did not match "Compaq Visual Fortran":
flang-new: error: unknown argument: '-what'
flang-new: error: no input files
Checking whether the Fortran compiler is NAG using "-V" did not match "NAG Fortran Compiler":
flang-new: error: argument to '-V' is missing (expected 1 value)
flang-new: error: no input files

**Comment by bmiyuan** [comment]
**it seems flang-new.exe lack cc1 tool, so I use f18,but it still failed** 
C:\msys64\clang64\bin>flang-new.exe -cc1
error: unknown integrated tool '-cc1'. Valid tools include '-fc1'.

C:\msys64\clang64\bin>f18.exe -cc1
Enter Fortran source
Use EOF character (^D) to end file

**OutPut compile info:**
-- The Fortran compiler identification is unknown
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingw32.a(lib64_libmingw32_a-crt0_c.o): in function `main':
C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crt0_c.c:18: undefined reference to `WinMain'
collect2.exe: error: ld returned 1 exit status
execvp(gfortran) failed: 
-- Detecting Fortran compiler ABI info
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_Fortran_PREPROCESS_SOURCE
CMake Error at C:/Program Files/JetBrains/CLion 2021.1.1/bin/cmake/win/share/cmake-3.19/Modules/CMakeDetermineCompilerABI.cmake:48 (try_compile):
  Failed to generate test project build system.
Call Stack (most recent call first):
  C:/Program Files/JetBrains/CLion 2021.1.1/bin/cmake/win/share/cmake-3.19/Modules/CMakeTestFortranCompiler.cmake:20 (CMAKE_DETERMINE_COMPILER_ABI)
  cmake/f_check.cmake:27 (enable_language)
  cmake/prebuild.cmake:89 (include)
  cmake/system.cmake:163 (include)
  CMakeLists.txt:93 (include)

**CMAKE error log:**
Checking whether the ASM compiler is GNU using "--version" did not match "(GNU assembler)|(GCC)|(Free Software Foundation)":
clang version 13.0.0
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: C:/msys64/clang64/bin
Compilation of the Fortran compiler identification source "CMakeFortranCompilerId.F" did not produce an executable in "D:/code/OpenBLAS/cmake-build-debug/CMakeFiles/3.19.2/CompilerIdFortran".

The Fortran compiler identification could not be found in "D:/code/OpenBLAS/cmake-build-debug/CMakeFiles/3.19.2/CompilerIdFortran/a.exe"

The Fortran compiler identification could not be found in "D:/code/OpenBLAS/cmake-build-debug/CMakeFiles/3.19.2/CompilerIdFortran/CMakeFortranCompilerId.o"

Compiling the Fortran compiler identification source file "CMakeFortranCompilerId.F" failed.
Compiler: C:/msys64/clang64/bin/f18.exe 
Build flags: 
Id flags: -fpp 

The output was:
1
gfortran: error: unrecognized command-line option '-fpp'; did you mean '-cpp'?
execvp(gfortran) failed: 


Compilation of the Fortran compiler identification source "CMakeFortranCompilerId.F" did not produce an executable in "D:/code/ OpenBLAS/cmake-build-debug/CMakeFiles/3.19.2/CompilerIdFortran".

The Fortran compiler identification could not be found in "D:/code/OpenBLAS/cmake-build-debug/CMakeFiles/3.19.2/CompilerIdFortran/a.exe"

The Fortran compiler identification could not be found in "D:/code/OpenBLAS/cmake-build-debug/CMakeFiles/3.19.2/CompilerIdFortran/CMakeFortranCompilerId.o"

Compiling the Fortran compiler identification source file "CMakeFortranCompilerId.F" failed.
Compiler: C:/msys64/clang64/bin/f18.exe 
Build flags: 
Id flags: -fpp 

The output was:
1
gfortran: error: unrecognized command-line option '-fpp'; did you mean '-cpp'?
execvp(gfortran) failed: 


Checking whether the Fortran compiler is Compaq using "-what" terminated after 10 s due to timeout.Checking whether the Fortran compiler is NAG using "-V" did not match "NAG Fortran Compiler":

f18 compiler (under development), version 13.0.0
Checking whether the Fortran compiler is Compaq using "-what" terminated after 10 s due to timeout.Checking whether the Fortran compiler is NAG using "-V" did not match "NAG Fortran Compiler":

f18 compiler (under development), version 13.0.0

**Comment by MehdiChinoune** [comment]
There are two different Flang: LLVM/Flang and Classic Flang.
The one packaged on MSYS2/clang64 is the LLVM one. which couldn't generate binary code and is also not supported by CMake.
MSYS2/mingw-w64 doesn't have Classic Flang

**Comment by bmiyuan** [comment]
Thanks a lot MehdiChinoune !  As you said , CMake dosen't support Clang64 Flang ,so we can't compile lapack of openblas on windows by this way. Is there any other solution we can compile lapack of openblas successfully on windows?

**Comment by MehdiChinoune** [comment]
> Thanks a lot MehdiChinoune ! As you said , CMake dosen't support Clang64 Flang ,so we can't compile lapack of openblas on windows by this way. Is there any other solution we can compile lapack of openblas successfully on windows?

Use MINGW64 or UCRT64 they both have openblas built with lapack support.

**Comment by bmiyuan** [comment]
thanks MehdiChinoune ! yes, mingw64 is ok I've already tried before. But our project need use clang64......

**Comment by MehdiChinoune** [comment]
> thanks MehdiChinoune ! yes, mingw64 is ok I've already tried before. But our project need use clang64......

Do you need CLANG64 environment or Clang compiler?

**Comment by bmiyuan** [comment]
Hi,MehdiChinoune 
 actually,we need Clang compiler and Clang64 environment both.
![image](https://user-images.githubusercontent.com/72647751/148686148-82643e72-0160-419e-92e9-bd9dc92fc4c2.png)

**Comment by MehdiChinoune** [comment]
If you need just Clang compiler you could use the clang compiler from MINGW64/UCRT64 + OpenBLAS.
If you just need the LAPACK package on CLANG64 then you could install mingw-w64-clang-x86_64-f2cblaslapack, but It is very slow compared to OpenBLAS.
Out of curiosity, why exactly do you need CLANG64?

**Comment by martin-frbg** [comment]
Building flang (-classic) from source used to be fairly straightforward on Linux, but i have no idea if it would be as easy on Windows. As far as I know, the llvm-related commercial compilers (nvidia hpc, amd aocc) are not available for Windows.

**Comment by bmiyuan** [comment]
> If you need just Clang compiler you could use the clang compiler from MINGW64/UCRT64 + OpenBLAS. If you just need the LAPACK package on CLANG64 then you could install mingw-w64-clang-x86_64-f2cblaslapack, but It is very slow compared to OpenBLAS. Out of curiosity, why exactly do you need CLANG64?

MehdiChinoune, we need compile openblas with LAPACK, bcos we need compile Armadillo,which will calculate data very quickly with openblas, but openblas also depends LAPACK to calculate some data.our project use Clang to compile all the modules and third party libs, and we can't use mingw64 to compile openblas.

**Comment by bmiyuan** [comment]
> Building flang (-classic) from source used to be fairly straightforward on Linux, but i have no idea if it would be as easy on Windows. As far as I know, the llvm-related commercial compilers (nvidia hpc, amd aocc) are not available for Windows.

thanks Martin,  but we don't select commercial compilers ,it's better if we can use opensource compiler. 
so per your advise, maybe we can try build flang/classic from source on windows, and then use it as the flang compiler when compiler LAPACK of openblas.

**Comment by brada4** [comment]
> Flang is not yet able to generate LLVM IR for the source code and thus is unable to compile a running binary

i.e it is a wrapper for gfrotran or a commercial compiler.

SOURCE: https://releases.llvm.org/13.0.0/tools/flang/docs/ReleaseNotes.html

**Comment by carlkl** [comment]
@bmiyuan, if you work with the msys2 clang64 environent you can try to use [mingw-w64-clang-x86_64-f2cblaslapack](https://packages.msys2.org/package/mingw-w64-clang-x86_64-f2cblaslapack?repo=clang64). It provides you with two static libraries: 

1. `/clang64/lib/libblas.a` and
2. `/clang64/lib/liblapack.a`

You can try the latter library (`/clang64/lib/liblapack.a`) in addition to your locally build OpenBLAS.

The reason why f2cblaslapack was added to msys2 is described here: https://github.com/msys2/MINGW-packages/discussions/10386#discussioncomment-1854837

BTW: clang64 provides you with [mingw-w64-clang-x86_64-armadillo](https://packages.msys2.org/package/mingw-w64-clang-x86_64-armadillo?repo=clang64) which depends on [mingw-w64-clang-x86_64-openblas](https://packages.msys2.org/package/mingw-w64-clang-x86_64-openblas).

The clang64 version of OpenBLAS is compiled without LAPACK and LAPACKE support. AFAIK this is not needed for Armadillo anyway.

**Comment by brada4** [comment]
One can use binary cross-built on Linux with Armadillo, or use clang and gfortran, much like the only free option OSX users have. CMake says you dont have fortran compiler - indeed flang without gfortran is no fortran compiler.

**Comment by martin-frbg** [comment]
@carlkl if this is based on `f2c` mangling the netlib Reference-LAPACK sources to C, apart from performance issues it is likely to be a LAPACK version from ten or more years ago (given that f2c does not support fortran95 or later language elements AFAIK).

**Comment by brada4** [comment]
@martin-frbg probably latest version that did away with f2c....

I thing OP thinks he talks with @MehdiChinoune from
https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-f2cblaslapack/PKGBUILD
fame, who could sched some light on that project's state.

**Comment by MehdiChinoune** [comment]
I have used f2cblaslapack used by petsc project, I don't know from which revision did they generate it!

**Comment by carlkl** [comment]
PKGBUILD uses the latest version from PETCS: https://ftp.mcs.anl.gov/pub/petsc/externalpackages/f2cblaslapack-3.4.2.q4.tar.gz (2020). However, Lapack version 3.4.2 is from 2012.
The interesting question is (CLANG64): can we use the accelerated BLAS part from OpenBLAS and Lapack from f2cblaslapack?

**Comment by brada4** [comment]
You never know if you dont try. That tarball is providing fortran API, so OpenBLAs built with DYNAMIC_ARCH=1 NO_CBLAS=1 NO_FORTRAN=1 (please skip experimental cmake part and use gnu make) will make a compatible library.

**Comment by martin-frbg** [comment]
@carlkl should be possible, except obviously your code would not be able to use the (smallish) number of LAPACK functions added since then, and more importantly might suffer from LAPACK bugs that got fixed in the meantime. Also you would miss out on the parallelized/optimized versions of potrf/getrf and friends if you built OpenBLAS without LAPACK.

**Comment by MehdiChinoune** [comment]
Someone doesn't trust our answer!
https://lists.llvm.org/pipermail/flang-dev/2022-January/000958.html

**Comment by martin-frbg** [comment]
I have no problem with that. (And I find it quite frustrating myself that the LLVM developers chose to replace a working - if not perfect - compiler implementation with a not-yet-functional redesign that bears the same name)

**Comment by brada4** [comment]
As much as it pertains OpenBLAS - it happily detected and avoided another non-compiler. It is always frustrating that software that is supposed to do something actually does exactly nothing )or half of that expected something)

**Comment by MehdiChinoune** [comment]
> I find it quite frustrating myself that the LLVM developers chose to replace a working - if not perfect - compiler implementation with a not-yet-functional redesign that bears the same name

Not LLVM developers, It was NVIDIA developers.
After they extracted PGI Frontend and open-sourced it they tried to integrate it with LLVM. After almost two years they concluded that it will never happen because it was a monolithic legacy  C code.
They decided to start a new project from scratch instead. They started with parsing and now they are working on code generation via MLIR.
I think it will be ready with LLVM 15.0

**Comment by carlkl** [comment]
@MehdiChinoune, do you have contact to FLANG developers? it is not easy to find information about the status of FLANG, especially when it comes to Windows.

**Comment by MehdiChinoune** [comment]
> @MehdiChinoune, do you have contact to FLANG developers? it is not easy to find information about the status of FLANG, especially when it comes to Windows.

I don't know which one you mean.
Anyway the LLVM/Flang builds successfully on Windows with both MSVC and mingw-w64.
for the Classic one, I think they have merged some PRs related to Windows but never tried to build it myself.
Classic Flang:
- https://github.com/flang-compiler/flang

Mailing lists for both:
https://lists.llvm.org/cgi-bin/mailman/listinfo/flang-dev

**Comment by MehdiChinoune** [comment]
https://github.com/flang-compiler/flang/issues/1154

**Comment by carlkl** [comment]
@MehdiChinoune, thank you!

**Comment by carlkl** [comment]
@bmiyuan - since it's the same issue - please take a look at:
[armadillo: Use f2cblaslapack for clang builds. #10566](https://github.com/msys2/MINGW-packages/pull/10566) to resolve
[mingw-w64-clang-x86_64-armadillo ld.lld: error: undefined symbol: wrapper2_* error #10556
](https://github.com/msys2/MINGW-packages/issues/10556)

**Comment by brada4** [comment]
Could you drop a line if you manage to build openblas BLAS with f2cblaslapack into same frankenstein library? That would ease life of android/iOPS people a bit.

**Comment by carlkl** [comment]
Maybe I also should try to build and test scipy with clang64 then. Lets see...
Android and iOS builds are outside my scope.

**Comment by brada4** [comment]
Thank you already, just tell approximately how (if/when) you succeed on mingw, somebody may pick that up and extend the success to mobile phones.

**Comment by bmiyuan** [comment]
> @bmiyuan - since it's the same issue - please take a look at: [armadillo: Use f2cblaslapack for clang builds. #10566](https://github.com/msys2/MINGW-packages/pull/10566) to resolve [mingw-w64-clang-x86_64-armadillo ld.lld: error: undefined symbol: wrapper2_* error #10556 ](https://github.com/msys2/MINGW-packages/issues/10556)

Thanks Carlkl, I just update the mingw-w64-clang-x86_64-f2cblaslapack, but it still has ld.lld: error: undefined symbol: wrapper2_dgelsd_ such error.   Actually, I added -DARMA_DONT_USE_WRAPPER in CMakeFile to fixed wrapper issue.

**Comment by brada4** [comment]
You nred to use consistent function prefixes across armadillo wrapper and callers, indeed taking wrapper away solves the confusion.

**Comment by martin-frbg** [comment]
If and when this works, it would probably make sense to look into updating at least those parts of their 2012 version of LAPACK that have not morphed into Fortran95 or later code (that f2c cannot handle). I have not found the original toclapack.sh script mentioned in an old posting on the petsc-users mailing list, but a derivative work can be found in the `primme` project on github. (The script actually preprocesses the fortran source before running it through f2c). At first glance, only a small number of files in the actual LAPACK code (as opposed to the testsuite and reference blas/cblas) are not translatable, mostly due to their use of the TRANSFER intrinsic. (I also notice that f2c warns about recursive calls it encounters - not sure if they are actually safely translated, I have not used f2c in ages)
