### ISSUE TITLE
Supporting Intel 12-gen Alder Lake Processors

### ISSUE THREAD

**Issue by Hs293Go** [xianyi/OpenBLAS#3512]
Hi all. I hit a snag trying to do `vcpkg install openblas` at the `Detecting CPU failed. Please set TARGET explicitly` message. 

I actually anticipated this and do NOT think this is an vcpkg issue, since I don't see any `ALDER_LAKE` option in `TargetList.txt`. Can this issue be solved upstream with a patch? Otherwise, what is the value for `TARGET` that best approximates my processor architecture?

Output of `cat /proc/cpuinfo | awk '1;/power management/{exit}'` is shown below
```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 151
model name	: 12th Gen Intel(R) Core(TM) i5-12600K
stepping	: 2
microcode	: 0x12
cpu MHz		: 1059.400
cache size	: 20480 KB
physical id	: 0
siblings	: 16
core id		: 0
cpu cores	: 10
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 32
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault cat_l2 invpcid_single cdp_l2 ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdt_a rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves split_lock_detect dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req umip pku ospke waitpkg gfni vaes vpclmulqdq tme rdpid movdiri movdir64b fsrm md_clear serialize pconfig arch_lbr flush_l1d arch_capabilities
vmx flags	: vnmi preemption_timer posted_intr invvpid ept_x_only ept_ad ept_1gb flexpriority apicv tsc_offset vtpr mtf vapic ept vpid unrestricted_guest vapic_reg vid ple shadow_vmcs ept_mode_based_exec tsc_scaling usr_wait_pause
bugs		: spectre_v1 spectre_v2 spec_store_bypass swapgs
bogomips	: 7372.80
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:
```

**Comment by martin-frbg** [comment]
Alder Lake should be autodetected as HASWELL in the current release (0.3.19). There is #3490 debating if this should be changed to something AVX512-capable for systems that have the low-power cores disabled.

**Comment by brada4** [comment]
No more https://www.tomshardware.com/news/intel-bios-update-disables-alder-lake-avx-512

**Comment by brada4** [comment]
It is 0.3.15 there https://github.com/microsoft/vcpkg/tree/master/ports/openblas
Please use TARGET=HASWELL while asking them to bump the version.

**Comment by brada4** [comment]
Seems solved by downstream in the meantime https://github.com/microsoft/vcpkg/pull/22435

**Comment by Hs293Go** [comment]
@brada4 ~~Confirming that~~ I checked that out, and it appears to be a vcpkg issue that went away when they updated their version of openblas. I was wrong. Closing this issue!

EDIT: rewording

**Comment by brada4** [comment]
Confirming what? We have no influence on downstream packages, as a end consumer you could have indeed.

**Comment by Hs293Go** [comment]
Edited my comment. Did "confirming" come off as demanding you take action? I don't mean that and I'll never say such words to a community contributor. Sorry for the misunderstanding.

**Comment by FCLC** [comment]
> 

Still usable on some versions, and it doesnt seem to be fully implemented across all revisions. 

Also relevant is that if a system is reverted to an older BIOS/ microcode revision, AVX-512 can be re-enabled. 

Been busy of late, but I think we should move forward with #3490

**Comment by brada4** [comment]
It is (commercially) understandable that it is gone for good with future microcodes, and new XEON-s will come out with proper AVX-512.
