### ISSUE TITLE
LAPACK functions exported if configured with `-DBUILD_WITHOUT_LAPACK=ON`

### ISSUE THREAD

**Issue by mmuetzel** [xianyi/OpenBLAS#3517]
When building with `cmake -DBUILD_WITHOUT_LAPACK=ON`, the OpenBLAS library still exports the following LAPACK functions:
`cspmv_`, `cspr_`, `csymv_`, `csyr_`, `zspmv_`, `zspr_`, `zsymv_`, `zsyr_`

Is that intentional? Is there a setting to have the library export none of the LAPACK symbols?

**Comment by martin-frbg** [comment]
Certainly unintentional, BUILD_WITHOUT_LAPACK should lead to the gensymbol script getting called with NO_LAPACK, which should omit all lapackobjs. Strange collection of function names that got through... I'll take a look later.

**Comment by martin-frbg** [comment]
Oh, I recognize that list now - these are actually reimplemented in OpenBLAS to take advantage of the corresponding AXPY kernels (just not stored under lapack but in driver/level2 "for historic reasons"). Good question if they should be suppressed though

**Comment by mmuetzel** [comment]
I noticed this when I tried to statically link a LAPACK compiled with f2c into the OpenBLAS library. The idea behind that was to provide a library for the clang environments of MSYS2 that exports the "full set" of BLAS and LAPACK functions even though no Fortran compiler is currently available for that environment.
That would maybe make it easier for dependent projects that "expect" all those functions in the OpenBLAS libraries.
When linking that "combined" library, I ran into issues with those duplicate symbols.

But I'm starting to wonder if that was a good idea in the first place. Maybe it would be better to resolve possible issues individually for each dependent project...
What do you think?

**Comment by martin-frbg** [comment]
I'm wondering why this particular duplication has not come up earlier - as far as I know, some Linux distributions already split up OpenBLAS into separate BLAS and LAPACK libraries to make it easier to "mix and match" them through their "alternatives" mechanism.
Perhaps it would make sense to offer a (modernized, if possible) f2clapack source within OpenBLAS, for use on platforms without a Fortran compiler. (This should make it easier to avoid duplication, the obvious drawback would be source "bloat" and possibly a dependency on the f2c libraries - still need to look into the latter). Unfortunately (from this particular perspective) Reference-LAPACK looks to be moving towards using more "modern" Fortran features that the ancient f2c tool fails to support.

**Comment by mmuetzel** [comment]
IIUC the duplicate symbols will only ever be an issue when linking statically. I guess most projects link to BLAS/LAPACK dynamically (e.g., to allow something like the alternatives mechanism). IIUC, the linker(?) will pick the (first?) matching symbol.
It's different for statically linked libraries (apparently)...

Having a more up-to-date LAPACK on platforms without Fortran compilers would be nice (at least until LLVM modern flang can generate code by itself).
Independently, it might make sense to (optionally?) not compile those LAPACK functions when configured with `BUILD_WITHOUT_LAPACK=ON`.

**Comment by mmuetzel** [comment]
There might also be an issue with dynamic linking on Windows when using an approach similar to Debian's alternatives mechanism:
IIUC, dynamically linking on Windows already correlates symbol names with library names.
Let's assume that to switch between different implementations of BLAS, different libraries are renamed to `libblas.dll` (e.g. from `libreferenceblas.dll` or `libopenblas.dll`). 
If a program is linked with `-lblas -llapack` while using reference BLAS, the above mentioned functions will be imported from `liblapack.dll`. In this case, it is possible to switch out `libblas.dll` to the OpenBLAS library.
If a program is linked with the same switches while using the OpenBLAS implementation, those functions will be imported from `libblas.dll` (which is a renamed `libopenblas.dll`). Switching to `libblas.dll` from the reference implementation will lead to undefined symbol errors.

I guess this is (part of?) the reason why we need to build GNU Octave linking to reference BLAS to allow switching between implementations later on in Windows.

**Comment by martin-frbg** [comment]
I'm currently working on a PR for this. Likely the source of the confusion was that the single and double precision real versions of these functions were codified in BLAS, but their complex equivalents ended up in LAPACK like as an afterthought.
