### ISSUE TITLE
add topics blas, openblas, lapack

### ISSUE THREAD

**Issue by Beliavsky** [xianyi/OpenBLAS#3519]
I suggest adding the topics `blas`, `openblas`, `lapack` in the About section.

**Comment by martin-frbg** [comment]
Sorry, what exactly do you want to see added (where) ? The "About" header on the github project page already mentions BLAS and (obviously) OpenBLAS, and anyone who got this far is welcome to find more information in the README.md that github conveniently presents at the bottom of the page.

**Comment by Beliavsky** [comment]
It should look like the About section of [linalg](https://github.com/jchristopherson/linalg). How to do it is desribed at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics .

The benefit of providing a topic such as openblas is that a GitHub search topic:openblas will bring up the repo.

**Comment by martin-frbg** [comment]
Ah, got it now, thanks for the detailed explanation. Interestingly I cannot edit the About section here (though I can on Reference-LAPACK where I also have Collaborator status) so this seems to be something for xianyi to address when he finds time.

**Comment by brada4** [comment]
Actually we hit 1st page of results on blas and openblas, so only lapack must be added if at all

**Comment by xianyi** [comment]
Done
