### ISSUE TITLE
test failures for ismax/ismin on sparc solaris (0.3.19)

### ISSUE THREAD

**Issue by wwcsig** [xianyi/OpenBLAS#3520]
As in #2433 for ppc64, the same issue exists on sparc

$ uname -a 
SunOS sunny 5.11 11.4.26.75.4 sun4v sparc sun4v Solaris

also big-endian.

```
./openblas_utest
TEST 1/34 max:smax_zero [OK]
TEST 2/34 max:dmax_positive [OK]
TEST 3/34 max:smax_negative [OK]
TEST 4/34 min:smin_zero [OK]
TEST 5/34 min:dmin_positive [OK]
TEST 6/34 min:smin_negative [OK]
TEST 7/34 amax:damax [OK]
TEST 8/34 amax:samax [OK]
TEST 9/34 ismax:negative_step_2 [FAIL]
  ERR: test_ismin.c:89  expected 9, got 50
TEST 10/34 ismax:positive_step_2 [OK]
TEST 11/34 ismin:negative_step_2 [FAIL]
  ERR: test_ismin.c:63  expected 9, got 1
TEST 12/34 ismin:positive_step_2 [OK]
TEST 13/34 drotmg:drotmg_D1_big_D2_big_flag_zero [OK]
TEST 14/34 drotmg:rotmg_D1eqD2_X1eqX2 [OK]
TEST 15/34 drotmg:rotmg_issue1452 [OK]
TEST 16/34 drotmg:rotmg [OK]
TEST 17/34 axpy:caxpy_inc_0 [OK]
TEST 18/34 axpy:saxpy_inc_0 [OK]
TEST 19/34 axpy:zaxpy_inc_0 [OK]
TEST 20/34 axpy:daxpy_inc_0 [OK]
TEST 21/34 zdotu:zdotu_offset_1 [OK]
TEST 22/34 zdotu:zdotu_n_1 [OK]
TEST 23/34 dsdot:dsdot_n_1 [OK]
TEST 24/34 swap:cswap_inc_0 [OK]
TEST 25/34 swap:sswap_inc_0 [OK]
TEST 26/34 swap:zswap_inc_0 [OK]
TEST 27/34 swap:dswap_inc_0 [OK]
TEST 28/34 rot:csrot_inc_0 [OK]
TEST 29/34 rot:srot_inc_0 [OK]
TEST 30/34 rot:zdrot_inc_0 [OK]
TEST 31/34 rot:drot_inc_0 [OK]
TEST 32/34 potrf:smoketest_trivial [OK]
TEST 33/34 potrf:bug_695 [OK]
TEST 34/34 kernel_regress:skx_avx [OK]
RESULTS: 34 tests (32 ok, 2 failed, 0 skipped) ran in 13 ms
```
the following 'fix' circumvents the problem
```
$ diff -u kernel/sparc/KERNEL ../OpenBLAS-0.3.19-fix/kernel/sparc/KERNEL   
--- kernel/sparc/KERNEL 2021-12-19 14:55:57.000000000 +0000
+++ ../OpenBLAS-0.3.19-fix/kernel/sparc/KERNEL        2022-01-27 08:53:56.839970000 +0000
@@ -67,3 +67,29 @@
 CGEMM_BETA = ../generic/zgemm_beta.c
 ZGEMM_BETA = ../generic/zgemm_beta.c
 
+SAMAXKERNEL  = ../arm/amax.c
+DAMAXKERNEL  = ../arm/amax.c
+SAMINKERNEL  = ../arm/amin.c
+DAMINKERNEL  = ../arm/amin.c
+ISAMAXKERNEL = ../arm/iamax.c
+IDAMAXKERNEL = ../arm/iamax.c
+ISAMINKERNEL = ../arm/iamin.c
+IDAMINKERNEL = ../arm/iamin.c
+ISMAXKERNEL  = ../arm/imax.c
+IDMAXKERNEL  = ../arm/imax.c
+ISMINKERNEL  = ../arm/imin.c
+IDMINKERNEL  = ../arm/imin.c
+ICAMAXKERNEL = ../arm/izamax.c
+IZAMAXKERNEL = ../arm/izamax.c
+ICAMINKERNEL = ../arm/izamin.c
+IZAMINKERNEL = ../arm/izamin.c
+SMAXKERNEL   = ../arm/max.c
+DMAXKERNEL   = ../arm/max.c
+SMINKERNEL   = ../arm/min.c
+DMINKERNEL   = ../arm/min.c
+CAMAXKERNEL  = ../arm/zamax.c
+ZAMAXKERNEL  = ../arm/zamax.c
+CAMINKERNEL  = ../arm/zamin.c
+ZAMINKERNEL  = ../arm/zamin.c
```

let me know if I can provide further information.

     Wolfgang

**Comment by martin-frbg** [comment]
Oops, thought I had caught all of them the last time round... however this looks to be a slightly different problem from #2433, I suspect the (ancient) bug is only that kernel/sparc/KERNEL errpneously defines ISMINKERNEL and IDMINKERNEL to i_a_max.S instead of imax.S (so taking the absolute value, like ISAMIN would - probably a copy/paste error in the KERNEL file).

Or do you have any additional evidence that makes it necessary to replace all min/max kernels with their generic implementation ?

**Comment by wwcsig** [comment]
> Oops, thought I had caught all of them the last time round... however this looks to be a slightly different problem from #2433, I suspect the (ancient) bug is only that kernel/sparc/KERNEL errpneously defines ISMINKERNEL and IDMINKERNEL to i_a_max.S instead of imax.S (so taking the absolute value, like ISAMIN would - probably a copy/paste error in the KERNEL file).
> 
> Or do you have any additional evidence that makes it necessary to replace all min/max kernels with their generic implementation ?

No - I was just lazy (overly careful). I can read C code, but no sparc assembly, but granted, I could have thought a bit more...
With the fix below

```
> diff -u kernel/sparc/KERNEL{,.orig}
--- kernel/sparc/KERNEL 2022-01-27 11:04:48.735554515 -0500
+++ kernel/sparc/KERNEL.orig    2022-01-27 11:04:40.531654409 -0500
@@ -39,11 +39,11 @@
 endif
 
 ifndef ISMINKERNEL
-ISMINKERNEL = imax.S
+ISMINKERNEL = iamax.S
 endif
 
 ifndef IDMINKERNEL
-IDMINKERNEL = imax.S
+IDMINKERNEL = iamax.S
 endif
 
 ifndef SNRM2KERNEL
```

the ismin tests pass now, the ismax still fails.

```
TEST 9/34 ismax:negative_step_2 [FAIL]
  ERR: test_ismin.c:89  expected 9, got 50
```

I tried setting also ISMAXKERNEL to imax.S but that didn't help...
Thanks for your quick response!

     Wolfgang
     
 <b>CORRECTION</b> After a make clean, everything builds okay.  Thanks again for the quick response!
