### ISSUE TITLE
How to add openBLAS in a requirements.txt file

### ISSUE THREAD

**Issue by nishantb06** [xianyi/OpenBLAS#3523]
I am using BM3D library which uses openBLAS behind the scenes. But while deploying my web app on streamlit, it is unable to install openBLAS. Therefore what addition should i make to my requirements.txt file to resolve this issue - Please find my [GitHub repo](https://github.com/nishantb06/Image_processing)

**Comment by brada4** [comment]
openblas is not a python library. 
if you are refering to commercial bm3d package on pypi they include openblas in package.

**Comment by martin-frbg** [comment]
Yes, please check the available documentation for BM3D and/or Streamlit to make sure you installed these packages correctly. 
This here : https://dsp.stackexchange.com/questions/62098/running-the-bm3d-denoising-algorithm-in-python suggests you may need to install OpenBLAS through the regular package management of your system installation, at least depending on which pythonized implementation of the BM3D algorithm you use.

**Comment by brada4** [comment]
Looking at your requirements.txt - you use bm3d that I guessed already - you have OpenBLAS included there. Also numpy has another copy. Please show any error messages to support of bm3d and streamlit, we are not in position to dismantle commercial package or cloud service (easily)

**Comment by brada4** [comment]
Random install today:
```
./numpy.libs/libopenblasp-r0-8a0c371f.3.13.so
./scipy.libs/libopenblasp-r0-085ca80a.3.9.so
$ ldd ./bm3d/bm3d_wie.so 
ldd: warning: you do not have execution permission for `./bm3d/bm3d_wie.so'
	linux-vdso.so.1 =>  (0x00007fff5d7e7000)
	libopenblas.so.0 => not found
	libm.so.6 => /lib64/libm.so.6 (0x00007f69f4e0f000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f69f4a3f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f69f5117000)

```
You need to install or symlink /usr/lib(64)/libopenblas.so.0 to a valid blas library, software says to include it, so ask them.
