### ISSUE TITLE
error undefined reference to `_mm512_reduce_add_pd' 

### ISSUE THREAD

**Issue by RomanShestakov** [xianyi/OpenBLAS#3530]
Hello

I have ran into the following error while building openBLAS 0.3.19 on RHEL7 with gcc-6.3 and DYNAMIC_ARCH=1

../libopenblas_nonthreaded-r0.3.19.a(dgemm_small_kernel_nn_SKYLAKEX.o): In function `dgemm_small_kernel_nn_SKYLAKEX':
dgemm_small_kernel_nn_skylakex.c:(.text+0x2ddd): undefined reference to `_mm512_reduce_add_pd'
dgemm_small_kernel_nn_skylakex.c:(.text+0x2e1c): undefined reference to `_mm512_reduce_add_pd'
dgemm_small_kernel_nn_skylakex.c:(.text+0x2e8e): undefined reference to `_mm512_reduce_add_pd'
dgemm_small_kernel_nn_skylakex.c:(.text+0x2eea): undefined reference to `_mm512_reduce_add_pd'
dgemm_small_kernel_nn_skylakex.c:(.text+0x30c7): undefined reference to `_mm512_reduce_add_pd'
../libopenblas_nonthreaded-r0.3.19.a(dgemm_small_kernel_nn_SKYLAKEX.o):dgemm_small_kernel_nn_skylakex.c:(.text+0x3106): more undefined references to `_mm512_reduce_add_pd' follow
../libopenblas_nonthreaded-r0.3.19.a(sgemm_small_kernel_nn_SKYLAKEX.o): In function `sgemm_small_kernel_nn_SKYLAKEX':
sgemm_small_kernel_nn_skylakex.c:(.text+0x2ca3): undefined reference to `_mm512_reduce_add_ps'
sgemm_small_kernel_nn_skylakex.c:(.text+0x2cdc): undefined reference to `_mm512_reduce_add_ps'
sgemm_small_kernel_nn_skylakex.c:(.text+0x2d42): undefined reference to `_mm512_reduce_add_ps'
sgemm_small_kernel_nn_skylakex.c:(.text+0x2d95): undefined reference to `_mm512_reduce_add_ps'
sgemm_small_kernel_nn_skylakex.c:(.text+0x2f25): undefined reference to `_mm512_reduce_add_ps'
../libopenblas_nonthreaded-r0.3.19.a(sgemm_small_kernel_nn_SKYLAKEX.o):sgemm_small_kernel_nn_skylakex.c:(.text+0x2f5e): more undefined references to `_mm512_reduce_add_ps' follow
collect2: error: ld returned 1 exit status

any ideas how to get around this issue?

Regards, Roman

**Comment by martin-frbg** [comment]
I _think_ that was a bug in 6.3 (missing definition in the avx512fintrin.h that comes with gcc). gcc 7 and above define it as
```
extern __inline double
__attribute__ ((__gnu_inline__, __always_inline__, __artificial__))
_mm512_reduce_add_pd (__m512d __A)
{
  __MM512_REDUCE_OP (+);
}
```
but I do not know if just adding this to the file in your installation is enough.

**Comment by RomanShestakov** [comment]
oh , thank you _ suspected some issue with gcc - unfortunately I can only use gcc-6.3 and can't patch it.
Is there any way to disable avx512 via some compiler options?

Regards, Roman

**Comment by martin-frbg** [comment]
You can build with `make NO_AVX512=1`

**Comment by RomanShestakov** [comment]
thank you - let me try this

**Comment by martin-frbg** [comment]
I'll add this instruction to the AVX512 compatibilty test that is run as part of c_check , so that the option gets set automatically for gcc 6.3 in the future ...

**Comment by RomanShestakov** [comment]
perfect - thank you so much for suggestion

**Comment by RomanShestakov** [comment]
to confirm - it worked ok - used the following flags and the build completed without error.

  $(MAKE)\
  TARGET=NEHALEM \
  DYNAMIC_ARCH=1 \
  CC=gcc \
  FC=gfortran \
  HOSTCC=gcc \
  BINARY=64 \
  INTERFACE=64 \
  NO_AFFINITY=1 \
  NO_WARMUP=1 \
  USE_OPENMP=0 \
  USE_THREAD=0 \
  USE_LOCKING=1 \
  NO_AVX512=1 \
  LIBNAMESUFFIX=nonthreaded

thank you very much again for the help
Regards, Roman

**Comment by brada4** [comment]
Dear @RomanShestakov sorry for coming late, you need newer SCL than v6 apparently. FAQ guide written for EL6, but still valid for EL7 https://github.com/xianyi/OpenBLAS/wiki/Faq#binutils . Also take care to install "full" devtoolset(-11), namely including binutils of same age. Looking at numbers seems EL8 has gcc8 included, probably from then on packages contain all needed headers.
AVX-512 CPUs come with one or two AVX-512 units, for first ones there is no significant gain in performance over HASWELL and AVX-2 codes. The 2-unit processors are Xeon W and Silver and better, you have to measure your processor, it is not in CPUID, and very blurry in CPU specs.

**Comment by brada4** [comment]
I edited FAQ entry - you need devtoolset-7 (package devtoolset-7-gcc-gfortran that pulls gcc and binutils-as as a dependency) or later, v6 had no intrinsics headers that were introduced after that FAQ entry was written. I just compile-tested an got SIGILL on a haswell hitting AVX-512 codes. You can try more realistic test, bump up requirement in FAQ if needed.

**Comment by RomanShestakov** [comment]
@brada4 thank you very much for the follow up - unfortunately for certain reasons  I can’t change the toolset :-(

Regards, Roman

**Comment by brada4** [comment]
You can copy header from newer toolset ;-) It is just a packaging error nobody noticed at the time. gcc5+ and much newer binutils support AVX-512 code generation. Though unless you have *-lake xeons, the HASWELL version is already OK

**Comment by brada4** [comment]
You can extract from package at [centos scl](http://mirror.centos.org/centos/7/sclo/x86_64/rh/Packages/d/devtoolset-7-gcc-7.3.1-5.16.el7.x86_64.rpm)
```
rpm -ql devtoolset-7-gcc | grep intrin
/opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/include/avx2intrin.h
/opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/include/avx5124fmapsintrin.h
....
/opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/include/avx512vpopcntdqintrin.h
/opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/include/avxintrin.h
```

**Comment by giordano** [comment]
> I think that was a bug in 6.3 (missing definition in the avx512fintrin.h that comes with gcc).

However this means that we can't use GCC 6 to build Skylake AVX512 kernels, which contradicts the [README](https://github.com/xianyi/OpenBLAS/blob/5ad66f0e96a41428d69e449761ad41d3271327d5/README.md#troubleshooting):

> Please use GCC version 6 or LLVM version 6 and above to compile Skylake AVX512 kernels.

And this also means one cannot target libgfortran3 systems with GCC, since GCC 6 was the latest version using that version of the ABI.

**Comment by martin-frbg** [comment]
This can (and needs to be) fixed by adding guards around the affected small_kernel files - other, older kernels already have an `if defined (gcc >6 or llvm > 9)` around them.
