### ISSUE TITLE
cholesky factorization fails using openblas from julia and R

### ISSUE THREAD

**Issue by ghost** [xianyi/OpenBLAS#3534]
Hi,

I am using openblas as the system blas on Linux, Kernel 5.16.9, with CPU Intel(R) Core(TM) i9-10980XE, avx2 and avx512 support.

Openblas is installed from the arch repository, and is currently version 0.3.19-1

Cholesky factorization attempts fail on matrices with are certainly positive definite and symmetric. I have posted a small example in R
[here](https://stackoverflow.com/questions/71181928/strange-problem-with-cholesky-in-matrix-class-possible-bug)

I am running into the same problem when repeating the test in Julia ........... which made me thinking that the problem may come from openblas.

Best

**Comment by brada4** [comment]
I cannot repeat the error with what is OPENBLAS_CORETYPE=HASWELL ( pls set that before re-running your sample - it could be a bug in OpenBLAS or might be as well gaming processor overclocked out of comfort spot.)

PS usually you attach repeaters/test cases instead of pointing to volatile forums.
```
#!/usr/bin/Rscript
if (!is.null(options("matprod")[[1]])) options(matprod = "blas")
require(Matrix)
set.seed(12345)
nrow <- 200
AM <- matrix(runif(nrow*nrow),nrow,nrow);AM[lower.tri(AM)] <- 0;AM[AM>0.2] <- 0;AM <- AM+t(AM);diag(AM) <- 1000;
A <- Matrix(AM)
cat("class A:",class(A),"\n")
cat("check symmetry A: ",max(abs(A-t(A))),"\n")
cat("rangen eigen A: ",range(eigen(A)$values),"\n")
cat("run chol(A)","\n")
C <- Matrix::chol(A)
cat("class AM:",class(AM),"\n")
cat("check symmetry AM: ",max(abs(AM-t(AM))),"\n")
cat("rangen eigen AM: ",range(eigen(AM)$values),"\n")
cat("run chol(AM)","\n")
C <- Matrix::chol(AM)
```

EDIT: add script interpreter / disable NaN check / safeguard c() function / Use Matrix::chol over base::chol

**Comment by martin-frbg** [comment]
Hopefully already fixed in current develop branch - there was a parameter mixup in the AVX512 GEMM of 0.3.18 when built for DYNAMIC_ARCH (multiple cpu model) support.

**Comment by brada4** [comment]
> chol()      This is an interface to the LAPACK routines ‘DPOTRF’ and ‘DPSTRF’,

**Comment by brada4** [comment]
> parameter mixup in the AVX512 GEMM 

Would downgrade help for package user or workaround is HASWELL core till next version?

**Comment by ghost** [comment]
Hi.

Thanks a lot for looking into this.

I have a workaround for R at the moment. Julia is using open-blas .............. I can certainly wait until the patch comes out.

WTR to chol(), from my understanding dpotrf etc. are calling blas routines.

Do you still need a Julia example .......... or is the problem confirmed?

**Comment by martin-frbg** [comment]
I am traveling and do not have access to a system with avx512 this weekend, will need to see if intel sde emulator is performant enough on what i have here.
As workaround for Julia you could try doing `export OPENBLAS_CORETYPE=HASWELL`

**Comment by brada4** [comment]
> confirmed?

Workaround is to disable AVX-512 using environment variable current package, you have a good test case with R. And remember to clear workaround after 0.3.20 is released downstream i.e Arch Linux (obviously with test failing reopen this one loudly)

**Comment by martin-frbg** [comment]
Indeed not reproducible with current `develop` branch (on Kaby Lake with Intel SDE in SkylakeX emulation mode). 0.3.20 still scheduled for tomorrow

**Comment by martin-frbg** [comment]
Closing as 0.3.20 is released now
