### ISSUE TITLE
Numpy using OpenBLAS is faster than calling OpenBLAS cblas_ sgemm from C?

### ISSUE THREAD

**Issue by LizardLad** [xianyi/OpenBLAS#3538]
Hi, 
I've been trying just to do a simple matrix multiplication faster than numpy on a Zen+ CPU. My code for both uses two matrices 100x100 and multiplies them together. Given that numpy uses BLAS internally (I've checked with numpy.show_config()) shouldn't it be slower given that it has to move data from Python types to C types and back? I have followed the documentation and yet my C code seems to be slower. I did notice that when I set OMP_NUM_THREADS and OPENBLAS_NUM_THREADS to 1 for both Python and C the C code is about 2x slower. Am I doing something wrong given it's slower than a Python program?

matrix.c
```
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <time.h>
#include <sys/time.h>
#include <cblas.h>

struct matrix_f {
    float *data;
    int x; //Number of rows
    int y; //Number of columns
};

double diff_ms(struct timespec start, struct timespec end)
{
        struct timespec temp;
        if ((end.tv_nsec - start.tv_nsec) < 0)
        {
                temp.tv_sec = end.tv_sec - start.tv_sec - 1;
                temp.tv_nsec = 1000000000 + end.tv_nsec - start.tv_nsec;
        }
        else
        {
                temp.tv_sec = end.tv_sec - start.tv_sec;
                temp.tv_nsec = end.tv_nsec - start.tv_nsec;
        }
        double ms = (temp.tv_sec * 1E9 + temp.tv_nsec) * 0.000001;
        return ms;
}

int matmul(struct matrix_f a, struct matrix_f b, struct matrix_f *result) {
    result->x=a.x;
    result->y=b.y;

    float *result_p = (float *)malloc(sizeof(float) * result->x * result->y);
    if(result_p == NULL) {return 1;}
    result->data = result_p;

    struct timespec start, end;
    clock_gettime(CLOCK_REALTIME, &start);
    cblas_sgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans, a.x, b.y, a.y, 1.0, a.data, a.y, b.data, b.y, 0.0, result->data, result->y);
    clock_gettime(CLOCK_REALTIME, &end);
    printf("Time taken: %lf ms\n", diff_ms(start, end));

    return 0;
}

int main() {
    struct matrix_f a = {.x=1000, .y=1000};
    a.data = (float *)malloc(a.x*a.y * sizeof(float));
    for(int i = 0; i < a.x*a.y+1; i++) {
        a.data[i] = (float) i;
    }

    struct matrix_f b = {.x=1000, .y=1000};
    b.data = (float *)malloc(b.x*b.y * sizeof(float));
    for(int i = 0; i < b.x*b.y+1; i++) {
        b.data[i] = (float) i;
    }

    struct matrix_f c = {0};

    matmul(a, b, &c);

    free(c.data);
    free(a.data);
    free(b.data);

    return 0;
}
```

matrix.py
```
import numpy as np
import time

row, col = (1000, 1000)

a = np.arange(row*col).reshape((row,col)).astype(np.float32)
b = np.arange(row*col).reshape((row,col)).astype(np.float32)
start = time.time()
c = a @ b
end = time.time()
print('Execution time: {}ms'.format((end-start)*1000))
```

Current times at threads=1
Python: 39ms
C: 66ms
Without threads=1
Python: 7.8ms
C: 27ms

Output of numpy.show_config()
```
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512CD,AVX512_KNL,AVX512_KNM,AVX512_SKX,AVX512_CLX,AVX512_CNL,AVX512_ICL
```

I'm compiling my C program with
```
gcc matrix.c -Wall -I/usr/include/x86_64-linux-gnu/openblas64-openmp/ -lopenblas -O3
```

**Comment by martin-frbg** [comment]
I'm not aware of any recent regression w.r.t  speed, but are you sure that your C program uses the same OpenBLAS library as the Python one at runtime (as shown by running `ldd` on your program) ?

**Comment by brada4** [comment]
If it is fedora rhen -lopenblas is single-threaded.

**Comment by brada4** [comment]
Please try to memset(arr,0x00,size) allocated "result". It might be the spectre mitigation stuff that makes physical memory asignments slow on some intel CPU-s.

**Comment by FCLC** [comment]
> Zen+ CPU.

> Supported SIMD extensions in this NumPy install:
>     baseline = SSE,SSE2,SSE3
>     found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2

> gcc matrix.c -Wall -I/usr/include/x86_64-linux-gnu/openblas64-openmp/ -lopenblas -O3

Based on the above, I wonder if GCC is failing to utilize AVX and AVX2 code paths, instead falling back on SSE. 

Could you share your version of GCC `gcc --version` as well as test with your previous arguments but appending `-march=native`  to gcc compilation?

**Comment by martin-frbg** [comment]
Zen SGEMM kernel uses AVX2 assembly instructions, so gcc version should not play a role I think.(And if cpu was misdetected it should affect both numpy and C)

**Comment by FCLC** [comment]
> Zen SGEMM kernel uses AVX2 assembly instructions, so gcc version should not play a role I think.(And if cpu was misdetected it should affect both numpy and C)

Fair enough. I just remember running into something with GCC and it defaulting to standard -march=core2duo (standard when no arch is specified to this day) and it then propagating that CPU choice/instruction availability down to a different library (I think it was PETSC?)

This is a while ago, something like GCC7 or 8. 

My theory is that because numpy would have it's own verification routine for detection (either via /proc, by direct assembly by running CPUID and checking EAX and so on, or some mechanism that doesnt rely on GCC propegation) it would have correctly detected and ran the AVX1/2 code paths. 

Reasoning was that the ration between the C and the Python was 

```
Current times at threads=1
Python: 39ms
C: 66ms
Without threads=1
Python: 7.8ms
C: 27ms
```
which seems to me like a different kernel must be being run. 


Edit: 

I've opened an issue in https://github.com/compiler-explorer/compiler-explorer/issues/3426 to add OpenBLAS as a supported library to help with diagnosis of these sort of issues

**Comment by martin-frbg** [comment]
for DYNAMIC_ARCH builds (as used by Linux distributions and included in NumPy), setting OPENBLAS_VERBOSE=2 would show the autodetected cpu type at runtime, which is the primary factor in determining which instruction set extensions are used.
NumPy and the user's C codev accessing different versions or builds of OpenBLAS still seems the most likely explanation to me

**Comment by LizardLad** [comment]
So it appears that numpy has its own version of the library that it links to. I'm using the version of OpenBLAS in the Ubuntu 20.10 repo at the moment. I've checked with OPENBLAS_VERBOSE=2 and it shows they both detect Core: Zen. Given the CPU is a Zen CPU it shouldn't be affected by the spectre mitigations the same way that Intel systems are right?

**Comment by brada4** [comment]
Might be newer version is somewhat better
[You can try latest](https://github.com/xianyi/OpenBLAS/wiki/Faq#replacing-system-blasupdating-apt-openblas-in-mintubuntudebian)
You can LD_PRELOAD the "other" openblas library to check if it gets better/worse for the tests.
