### ISSUE TITLE
Please consider annotating LAPACKE_lsame with __attribute__((const))

### ISSUE THREAD

**Issue by davidmalcolm** [xianyi/OpenBLAS#3543]
`LAPACKE_lsame` is a case-insensitive char comparison, but is implemented in its own object file, so a compiler has no was of knowing (without LTO) that multiple calls to it with the same inputs have the same results.

GCC has `__attribute__((const))` for marking functions that always return the same result on the same inputs:
  https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-const-function-attribute

I'm the maintainer of the [GCC static analyzer](https://gcc.gnu.org/wiki/DavidMalcolm/StaticAnalyzer).  When building openblas-0.3.15 with my analyzer, I noticed slightly over 2000 false positives from -Wanalyzer-malloc-leak on code like this:

```
        if( LAPACKE_lsame( vect, 'b' ) || LAPACKE_lsame( vect, 'p' ) ) {
            pt_t = (lapack_complex_float*)
                LAPACKE_malloc( sizeof(lapack_complex_float) *
                                ldpt_t * MAX(1,n) );
            if( pt_t == NULL ) {
                info = LAPACK_TRANSPOSE_MEMORY_ERROR;
                goto exit_level_2;
            }
        }

	[...snip...]

exit_level_2:
        if( LAPACKE_lsame( vect, 'b' ) || LAPACKE_lsame( vect, 'q' ) ) {
            LAPACKE_free( q_t );
        }
```
e.g. in https://github.com/xianyi/OpenBLAS/blob/c5f280a7f0e875d83833d895b2b8b0e341efabf4/lapack-netlib/LAPACKE/src/lapacke_cgbbrd_work.c

where my analyzer naively assumes that `LAPACKE_lsame( vect, 'b' ) || LAPACKE_lsame( vect, 'p' )` can be true at the malloc guard, and false at the free guard; other compilers/analyzers may have similar behavior.

I'm testing a fix for the GCC analyzer to take account of `__attribute__((const))`, and in my tests so far it fixes the OpenBLAS false positives when the attribute is added to `LAPACKE_lsame`.  (I'm tracking this for GCC as https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104434).  Presumably some kind of configuration define would be needed to support compilers that don't have the attribute.

Hope this is constructive

**Comment by martin-frbg** [comment]
Thanks - I must admit it is not entirely clear to me what the practical implications are, apart from misleading the static analyzer. The LAPACKE code in OpenBLAS is taken from https://github.com/Reference-LAPACK/lapack (also know as "netlib"), I can forward the issue if you like.

**Comment by davidmalcolm** [comment]
There's a chance it could affect code generation, in that with that attribute the compiler is allowed to assume that the result of e.g. `LAPACKE_lsame( vect, 'b' )` doesn't change if `vect` doesn't change, and could thus stash the result in a synthetic local.

**Comment by brada4** [comment]
There are other text processing libraries out there. EN_US EBCDIC is handled well by both linux libiconv, or lighter licensed (inline-able) netbsd iconv. This function has no callers, no sign of linear projection or algebra whatsoever. Probably left there from some mainframe tests in early nineties.

**Comment by martin-frbg** [comment]
@brada4 that is a bit besides the point. LSAME is used a lot internally in LAPACK, and I see no reason why third-party code that already makes use of LAPACKE for other purposes should resort to other libraries for what LSAME does. (Though this is of course trivial to do in C as well nowadays)

**Comment by brada4** [comment]
I think it s quite impractical to expect EBCDIC character in that place.
