### ISSUE TITLE
the Compile is not stable

### ISSUE THREAD

**Issue by SmileGoat** [xianyi/OpenBLAS#3552]
when I type make:
the log is :
gcc: error: warning:: No such file or directory
gcc: error: GREP_OPTIONS: No such file or directory
gcc: error: is: No such file or directory
gcc: error: deprecated: No such file or directory
gcc: fatal error: no input files
compilation terminated.
/bin/sh: 1: please: not found
make: *** [getarch] Error 127
Makefile.system:283: Makefile.conf: No such file or directory
Makefile.system:1434: Makefile.: No such file or directory
make: *** No rule to make target 'Makefile.'.  Stop.

sometimes: it can work.
gcc: error: warning:: No such file or directory
gcc: error: GREP_OPTIONS: No such file or directory
gcc: error: is: No such file or directory
gcc: error: deprecated: No such file or directory
gcc: fatal error: no input files
compilation terminated.
/bin/sh: 1: please: not found
make: *** [getarch] Error 127
Makefile.system:283: Makefile.conf: No such file or directory
Makefile.system:1434: Makefile.: No such file or directory
make: *** No rule to make target 'Makefile.'.  Stop.
make[1]: Entering directory '....../interface'

**Comment by martin-frbg** [comment]
Which version of OpenBLAS, and on what kind of system are you trying to compile ? This reads as if you are missing some fundamental tools (like `grep` and/or `perl`), or they are behaving strangely.

**Comment by brada4** [comment]
just unset GREP_OPTIONS env var and profile scripts.

Noteworthy changes in release 3.6 (2020-11-08) [stable]

** Changes in behavior

  The GREP_OPTIONS environment variable no longer affects grep's behavior.
  The variable was declared obsolescent in grep 2.21 (2014), and since
  then any use had caused grep to issue a diagnostic.
