### ISSUE TITLE
./test1: symbol lookup error: ./test1: undefined symbol: cblas_sbgemm

### ISSUE THREAD

**Issue by zsy-v** [xianyi/OpenBLAS#3555]
I build openblas whith "make BUILD_BFLOAT16=1". Why I got an error when I ran my program?
./test1: symbol lookup error: ./test1: undefined symbol: cblas_sbgemm

**Comment by brada4** [comment]
What is your CPU type?
Does it build without parameter?
Full build log (after `make clean` )?

**Comment by zsy-v** [comment]
I have solved the problem. Openblas has no problem.
