### ISSUE TITLE
How to use function cblas_sbstobf16.

### ISSUE THREAD

**Issue by zsy-v** [xianyi/OpenBLAS#3556]
I am learning how to use openblas. I can not find useful information about the function cblas_sbstobf16. I want to know the meaning of  n, incin and incout. Any guidance you provide would be appreciated.

> /* convert float array to BFLOAT16 array by rounding */
void   cblas_sbstobf16(OPENBLAS_CONST blasint n, OPENBLAS_CONST float  *in, OPENBLAS_CONST blasint incin, bfloat16 *out, OPENBLAS_CONST blasint incout);

**Comment by martin-frbg** [comment]
n= number of elements in input array that are to be converted, incin/incout= stride (increment) between elements in input and output respectively. (I agree this should be documented on the "OpenBLAS Extensions" wiki page.

**Comment by zsy-v** [comment]
Thank you. I know how to use the function now.

**Comment by wonda** [comment]
> Thank you. I know how to use the function now.

Hello, I also have no idea about the meaning of incin and incout, could you please provide an example on how to use this function? Many thanks!

**Comment by martin-frbg** [comment]
The increments are standard arguments in all BLAS functions - often named INCX and INCY for the variables they refer to. Normally you would leave them at 1 here, you only need to change this if you want to convert e.g. only every second number in your input, or put the converted values at different regularly spaced intervals in the output vector:
```
y[0]=bfloat16(x[0]);
y[1]=bfloat16(x[1]);
...
y[n]=bfloat16(x[n]);
```
is cblas_sbstobf16(n,x,1,y,1)
```
y[0]=bfloat16(x[0]);
y[1]=bfloat16(x[2]);
y[2]=bfloat16(x[4]);
...
```
is cblas_sbstobf16(n,x,2,y,1)
```
y[0]=bfloat16(x[0]);
y[3]=bfloat16(x[1]);
y[6]=bfloat16(x[2]);
```
is cblas_sbstobf16(n,x,1,y,3)
etc.

**Comment by wonda** [comment]
Many thanks Martin, the examples help a lot. I have referred to the documents of BLAS before, but it seems too concise for me to understand. Thank you again!

**Comment by zsy-v** [comment]
1111
