### ISSUE TITLE
Auto-detection of NO_AVX512 incorrect and potentially causing issues with x86_64 Builds 

### ISSUE THREAD

**Issue by e4t** [xianyi/OpenBLAS#3557]
Commit 21eda8b5 introduced a detection feature for compiler support of AVX512 on x86_64 while patch 7a9a4dbc4 attempted to extend this to the 'native' CPU the compiler is running on.
These patches (and patches on top attempting to 'fix' these) are problematic for several reasons:
1. The check in is incorrect. To check for AVX512 support one would have to check whether `__AVX512F__` is defined to 1. The check for `__AVX2__` does just that: check if the compiler in its present settings will know of the AVX2 instruction set.
2. The check is orthogonal to multiple paradigms of OpenBLAS:
    1. It assumes that HOSTCC is the same as CC thus breaks cross compiling - which admittedly is not an important feature for x86_64.
    2. On top of 1. using `-march=native` assumes that the build machine has identical hardware to the machine the code will run on. Different build systems may provide different results.
    3. An `-march=native` test is not really valid in connection with DYNAMIC_ARCH.

There are several options to fix this. 
- The test could simply be removed. This would require the user to specify set the make variable NO_AVX512 explicitly. Not sure how relevant it is today to support a gcc version that doesn't support  AVX512 - especially when used on systems that provide this feature. Those users will lose some convenience.
- Since this test is limited to gcc meanwhile and we know which version of gcc has introduced AVX256 support, another easy solution would be to set NO_AVX512 depending on the gcc version used. This would allow to limit this features to gcc versions where support for AVX512 has stabilized.
- The automated detection could be retained by doing:
   `NO_AVX512=$(shell /bin/sh -c '{ echo | $(CC) -mavx512f -E - &>/dev/null; } && echo 1 || echo 0')`
  in Makefile.system.
I'd like to put this up for discussion - I'm happy to provide a patch for whatever solution is favored.

**Comment by brada4** [comment]
It would work like that in a perfect world.
There are systems where AVX-es are in compiler but not in assembler and vice versa (think ubuntu16, rhel6, they are still alive for those willing to pay)
PR that does cleanup of related detection and ifdef-s is always welcome.

**Comment by e4t** [comment]
Indeed. The current test would not have detected this either as it operates on the preprocessor level.
In theory, commit 7a9a4db (ie testing with `-march=native`) may have fixed an issue with CPU auto-detection. But the comment to it doesn't seem that this was the reason.
I will submit a patch to clean this up.

**Comment by brada4** [comment]
The build without parameters is best that can be made on local machine, it tries to detect things that will not work and build the most efficient thing local compiler can make for local CPU. Obviously you want to skip local CPU detection to reuse library on other machine.
Do not mangle cross-compilation to x86_64. You need that to build windows DLL-s on Linux, or Windows DLL-s using cygwin. Less necessary with clang-cl being available, but far from losing relevance. Also Win32 DLL is important as a drop-in for tons of ancient compute products.

**Comment by martin-frbg** [comment]
Regarding your points above:
1. relying on the compiler defines alone is insufficient as already mentioned, the assembler must be able to handle AVX512 instructions as well.
2.
  I. the test is performed on the CC (and associated toolchain), not HOSTCC so I do not see how this is supposed to be breaking crossbuilds. Of necessity, the getarch tool will be built using HOSTCC as it is run on the build host, but with the TARGET name provided in a cross-compilation, its only purpose is to extract suitable parameters for the given cpu, not do any autodetection.
II. identity or difference between the build host and the machine the code will run on is orthogonal to the capabilities of the compiler or toolchain - DYNAMIC_ARCH builds do their own cpu detection at runtime to select the code to use, and if the compiler used for the build happened to be incapable of processing AVX512 instructions they will not have any such code to offer anyway.
III. again the workings of DYNAMIC_ARCH are different from what build-time autodetection or naming of a single TARGET does

**Comment by e4t** [comment]
> Regarding your points above:
> I. the test is performed on the CC (and associated toolchain), not HOSTCC so I do not see how this is supposed to be breaking crossbuilds. Of necessity, the getarch tool will be built using HOSTCC as it is run on the build host, but with the TARGET name provided in a cross-compilation, its only purpose is to extract suitable parameters for the given cpu, not do any autodetection. 

I was referring to the code in getarch.c which checks for `__AVX2__` defined by the preprocessor of `$(HOSTCC)` - running with `-march=native ` and decides depending on the outcome of the test whether a Cooperlake CPU target should be flagged as Haswell or indeed Cooperlake. The parameters generated for config_kernel.h are clearly different and do influence the compilation.

> II. identity or difference between the build host and the machine the code will run on is orthogonal to the capabilities of the compiler or toolchain - DYNAMIC_ARCH builds do their own cpu detection at runtime to select the code to use, and if the compiler used for the build happened to be incapable of processing AVX512 instructions they will not have any such code to offer anyway. 

Yes, a Cooperlake processor is identified as such and the kernel is picked accordingly. This kernel has however been compiled with Haswell parameters if the host arch (not the target compiler!) was incapable to use AVX2 instructions.

> III. again the workings of DYNAMIC_ARCH are different from what build-time autodetection or naming of a single TARGET does

I do realize this and I don't think I've stated anything different. 
My point was different:  the 'detection' performed by `$(HOSTCC)  -march=native` when building getarch.c does have impact on the build target and this is clearly wrong.
The problem does not only arise with DYNAMIC_ARCH  but potentially anywhere where the build platform differs from the target platform (cross-compiling or not). The reason for the check for `__AVX2__` (which should have been for `__AVX512__`) is purely to determine of the compiler is capable of AVX512 instructions or not - at least this is what the comment in 21eda8b suggests. For cross-compiling it should be the compiler for the target, instead, this test is done with the host compiler.

Let me propose a fix tomorrow, this may help to clarify what I mean.

**Comment by martin-frbg** [comment]
Got it, you are referring to the ` __GNUC__   > 6 && defined(__AVX2__)) ` ? This does indeed look inconsistent - it was a copypasta of checks introduced to guard various then-new SkylakeX kernels (e.g. its DAXPY microkernel) which do look like they should be addressing __AVX512CD__ throughout. And yes, cross-compilation would be problematic in that case, but at the core this problem lies in a circular dependency between what is known at the time getarch gets built and what getarch would be able to figure out. To really break things however one would probably need either an outdated host compiler or an outdated cross-compiler (either of them incapable of AVX512), so maybe less of an issue now than it was when AVX512 was introduced(?)
I do acknowledge that cross-compilation from x86_64 to x86_64 is comparativiely poorly supported right now, with cmake one would not even get parameters for recent cpu targets.

**Comment by martin-frbg** [comment]
probably the actual cause of #3454 (which only has a weird workaround so far). Maybe just omitting the AVX512 check in CROSS or DYNAMIC_ARCH builds would be sufficient - at worst the build would stop if the toolchain is too ancient

**Comment by e4t** [comment]
For builds with version 0.3.20 using DYNAMIC_ARCH or TARGET a gcc is required that's at least able to handle `-march=skylake-avx512` as this is the fallback for the Sapphire Rapids and Cooperlake targets - and of course the Skylake-X target itself. That's what's set by kernel/Makefile for these arches (*).  Compiler toolchains  that are unable to handle this option can only be used when targeting older platforms. On these AVX512 is not relevant anyway. 
Therefore if at all,  any such detection would have a place only when the target platform is auto-detected (ie when neither DYNAMIC_ARCH nor TARGET are set) by keeping in mind that this check will not protect from a inconsistent compiler toolchain where the assembler or linker cannot handle what the compiler has put out.
It probably doesn't make sense to use the TARGET option with a target that's not supported by the compiler. For DYNAMIC_ARCH one should limit the targets in DYNAMIC_LIST.

(*) The '-march' settings are specified in two places: getarch.c and kernel/Makefile. I'm unable to find where the former are used. When using autodetection these flags should probably be used everywhere.
I'll propose a fix.

**Comment by martin-frbg** [comment]
Protection against an inconsistent toolchain is supposed to come from a separate compile test in the c_check script. Unfortunately there is a chicken-and-egg problem with utilizing its findings to guide getarch.c so the misguided test crept in. (Indeed originally in conjunction with autodetection at a time when gcc 4.x was still a fairly common default.) I still need to check where the idea to check for __AVX2__ rather than __AVX512CD__ comes from, but both are guards used around individual SKX kernel files. (And I suspect both the Intel guy who contributed said kernels _and_ my former self mistakenly assumed the macro to be set to identify a compiler with the requisite capability regardless of the build host's cpu, _viz._ the clang branch of the conditional doing just a version check. I further suspect a minimal fix would be to just check for gcc version >= 6.x )

**Comment by martin-frbg** [comment]
(*) `-march` settings are in Makefile.x86_64 for single-target, and in kernel/Makefile for DYNAMIC_ARCH builds. The one in getarch.c for non-autodetected TARGETs has probably become redundant lately, but I'd need to check.

**Comment by brada4** [comment]
If I recall correctly that was because some copy function used AVX2 intrinsics even initially intended for SKX.

**Comment by e4t** [comment]
This issue has been fixed with the mentioned commits.
