### ISSUE TITLE
RFC: remove support for US AMD and INTEL processors

### ISSUE THREAD

**Issue by qg0** [xianyi/OpenBLAS#3558]
### Due to NATO support of Ukrainian Nazis genocide against Donbass people, the support of AMD and Intel processors should be removed: 

![FJ8Kgv-WQAQBqZ0](https://user-images.githubusercontent.com/919099/156775502-390c39c9-a495-44d2-a158-0d4ca3aedcb5.jpg)
![FMwuXJfXsAIVNXM](https://user-images.githubusercontent.com/919099/156775537-8e0c9701-649e-4354-b154-fc6b9ca43e3c.jpg)
![bank_48176_62195](https://user-images.githubusercontent.com/919099/156775783-a1e9d4e2-8915-4d38-a49b-6c29fabf97dd.jpg)
![5ca012d58f67cc71d78f07a60b4f0749](https://user-images.githubusercontent.com/919099/156775829-a5635e79-ccd7-4ece-a9eb-c3233a96d3de.jpg)
![fashisti](https://user-images.githubusercontent.com/919099/156775943-b184c40a-1a18-4fb2-9bea-9a1b4d640e8e.jpg)
![2014-05-05_Odessa-15](https://user-images.githubusercontent.com/919099/156777883-6968e6fe-dc60-4770-8347-ff38cb472a58.jpg)

### 2 may 2014: NATO backed Ukrainian Nazis burned people alive:

![2014-05-05_Odessa-17](https://user-images.githubusercontent.com/919099/156777885-4667264c-7d4c-4adf-906f-332f94b7b537.jpg)
![2014-05-05_Odessa-09](https://user-images.githubusercontent.com/919099/156777890-7f235d61-f340-46a6-968a-d484070df9ab.jpg)
![2014-05-05_Odessa-10](https://user-images.githubusercontent.com/919099/156777874-d8aee33d-d72a-4a28-98a0-568ccd8d170a.jpg)
![1399398701-1189-odessa](https://user-images.githubusercontent.com/919099/156778244-31cd1e11-4238-4595-9d02-de180c4333b6.jpg)

2016:  NATO backed Ukrainian Nazis buried people alive::
https://metro.co.uk/2016/06/23/man-buried-alive-by-ukrainian-soldiers-in-shocking-video-5962704/?ito=article.desktop.share.top.twitter

Because NATO is using AMD and INTEL processors to make a genocide against people we should remove its support!

![FMSWNEFacAIrpoJ](https://user-images.githubusercontent.com/919099/156779552-10510ece-63c3-46f7-a903-d840df3932f8.jpg)

**NATO genocide against Belgrad 1999**

They definitely used INTEL and AMD processors in those acts of genocides.

![image](https://user-images.githubusercontent.com/919099/156779971-d3b886f9-6f54-4264-b622-fda4f1e48cc6.png)

![be](https://user-images.githubusercontent.com/919099/156780077-2bcce696-7f86-43af-8344-285f81a29f4b.jpg)

NATO made a fake statement that they found WMD in IRAQ, then they bombed it to steal oil:

![powell-b4d35ec5ed3831370ad3c717a6e3c6a93f224815-s6-c30](https://user-images.githubusercontent.com/919099/156780232-2a74bb21-002a-4538-a925-4b349a1e5780.jpg)

![cd846f2c-5727-44b0-bc58-05ed24c75109](https://user-images.githubusercontent.com/919099/156780927-c1355427-352a-4371-a074-9aedf196644b.jpg)
![iraq_body_bloated](https://user-images.githubusercontent.com/919099/156780934-14c57e69-7b04-42f6-bb49-371d806ca1af.jpg)

![image](https://user-images.githubusercontent.com/919099/156783106-5699165f-f8cf-4e27-a1c6-5e461460763d.png)

**NATO's tortures in Abu Ghraib**
![1634318331_666](https://user-images.githubusercontent.com/919099/156781576-eb13c5b8-76b3-4806-88de-6f9d3980eb02.jpg)
![MXETQKZOSA2HMBURMV3FI7MIJE](https://user-images.githubusercontent.com/919099/156781594-8d5772a9-9b1f-4fab-8349-14e60ac0ce94.jpg)
![regnum_picture_159256734354293_normal](https://user-images.githubusercontent.com/919099/156781613-5e7dd762-ef34-4474-b459-90087298f1c3.jpg)
![image](https://user-images.githubusercontent.com/919099/156781783-73b85bd0-65e9-41e2-b510-cd925a40d75e.png)
![image](https://user-images.githubusercontent.com/919099/156781830-1b8c7998-9929-4c50-976a-41865d73c5a1.png)
![image](https://user-images.githubusercontent.com/919099/156782178-5706226a-fd20-4038-a27e-4dbaea4d1f2d.png)
![image](https://user-images.githubusercontent.com/919099/156782258-9cd1d3f6-1d1e-49cf-b486-538f26d37db9.png)
![image](https://user-images.githubusercontent.com/919099/156782439-249eb218-4842-4168-9701-2a7a0db0c6f1.png)
![image](https://user-images.githubusercontent.com/919099/156782485-6a212b6c-46cf-42b2-850f-06ccb64b687c.png)

**NATO is using AMD and INTEL processors so we should remove its support!**

**Comment by Blezigen** [comment]
NATO is using AMD and INTEL processors so we should remove its support!
