### ISSUE TITLE
Function cblas_sbgemm run slower than function cblas_sgemm

### ISSUE THREAD

**Issue by zsy-v** [xianyi/OpenBLAS#3559]
Hello. I am going to use function cblas_sbgemm to improve my code, however, function cblas_sbgemm run slower than function cblas_sgemm. I wonder how to use the function correctly or why function cblas_sbgemm run slower than function cblas_sgemm.
Here is my cpu info:

> model name      : AMD EPYC 7302 16-Core Processor
stepping        : 0
microcode       : 0x830104d
cpu MHz         : 2994.634
cache size      : 512 KB
physical id     : 1
siblings        : 32
cpu cores       : 16
fpu             : yes
fpu_exception   : yes
cpuid level     : 16
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc art rep_good nopl nonstop_tsc extd_apicid aperfmperf eagerfpu pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_l2 cpb cat_l3 cdp_l3 hw_pstate sme retpoline_amd ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip overflow_recov succor smca
bogomips        : 5989.33
TLB size        : 3072 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 43 bits physical, 48 bits virtual

I use openblas-0.3.20 and my test code is test1.c.

```c++
#include <cblas.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/time.h>
#include <time.h>

void quan(OPENBLAS_CONST blasint n, OPENBLAS_CONST float *src_ptr, bfloat16 *dst_ptr)
{
  cblas_sbstobf16(n, src_ptr, 1, dst_ptr, 1);
}

void dequan(OPENBLAS_CONST blasint n, OPENBLAS_CONST bfloat16 *src_ptr, float *dst_ptr)
{
  cblas_sbf16tos(n, src_ptr, 1, dst_ptr, 1);
}


int main()
{     
  int m = 1024;
  int n = 1024;
  int k = 1024;
  float* A = (float*)malloc(sizeof(float)*m*k);
  float* B = (float*)malloc(sizeof(float)*k*m);
  float* C = (float*)malloc(sizeof(float)*m*n);

  openblas_set_num_threads(64);

  struct timeval start,finish;
  double duration;

  bfloat16* A1 = (bfloat16*)malloc(sizeof(bfloat16)*m*k);
  bfloat16* B1 = (bfloat16*)malloc(sizeof(bfloat16)*k*n);
  bfloat16* C1 = (bfloat16*)malloc(sizeof(bfloat16)*m*n);
  float* C2 = (float*)malloc(sizeof(float)*m*n);

  srand((unsigned)time(NULL));

  for (int i=0; i<m*k; i++)
    A[i] = (rand()%100)/100.0;
  for (int i=0; i<k*n; i++)
    B[i] = (rand()%100)/100.0;

  gettimeofday(&start, NULL);
  cblas_sgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans, m, n, k, 1, A, k, B, n, 0, C, n);
  gettimeofday(&finish, NULL);

  duration = ((double)(finish.tv_sec-start.tv_sec)*1000000 + (double)(finish.tv_usec-start.tv_usec)) / 1000000;
  printf("fp32 %dx%dx%d\t%lf s\n", m, n, k, duration);

  gettimeofday(&start, NULL);
  quan(m*k, A, A1);
  quan(k*n, B, B1);
  cblas_sbgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans, m, n, k, 1, A1, k, B1, n, 0, C2, n);
  gettimeofday(&finish, NULL);

  duration = ((double)(finish.tv_sec-start.tv_sec)*1000000 + (double)(finish.tv_usec-start.tv_usec)) / 1000000;
  printf("fp16 %dx%dx%d\t%lf s\n", m, n, k, duration);

  free(A);
  free(B);
  free(C);
  free(A1);
  free(B1);
  free(C1);
  free(C2);
}
```

result:
```shell
fp32 1024x1024x1024     0.030065 s
fp16 1024x1024x1024     0.415468 s
```

Any help would be appreciated.

**Comment by brada4** [comment]
fp16 is fast only on cooperlake cpu, for others is same as if you cast-ed yourself.

**Comment by zsy-v** [comment]
> fp16 is fast only on cooperlake cpu, for others is same as if you cast-ed yourself.

Thank you very much.
