### ISSUE TITLE
About remove support for Russian Elbrus processor

### ISSUE THREAD

**Issue by xintrea** [xianyi/OpenBLAS#3560]
2 [xianyi](https://github.com/xianyi) & [rubicon1042](https://github.com/rubicon1042)

For issue https://github.com/xianyi/OpenBLAS/issues/3551

Suddenly, Elbrus has native support for the x86/amd64 architecture. And there are two modes - Lintel and RTS. Lintel is a complete emulation of the Intel architecture. RTS - launching Intel binaries from the native VLIW operating system. Therefore, even if OpenBLAS support for Elbrus is removed, this processor can still use OpenBLAS. So what's the point of distorting the project code if this project will still work on Elbrus?

I recommend not dividing people who work in science and open source into countries and political regimes. The open source movement has no boundaries, especially academic developments.

Thanks.

PS: who is strange GitHub user [rubicon1042](https://github.com/rubicon1042)? Registry at 02.03.2022, no repositories, no commits, nothing.

**Comment by martin-frbg** [comment]
Some users register with github only when they want to create an issue or PR, I see nothing wrong with that. And at least it was a polite question, even if one does not agree with the underlying assumptions. As mentioned in the locked issue, the disputed commit does not provide any actual optimizations for Elbrus, just a small convenience for building OpenBLAS in its most basic x86_64 support mode.

**Comment by orbea** [comment]
As a general contributor to free software and mostly an outsider to OpenBLAS I just want to say I appreciate it when projects support niche hardware. I also resent the constant political campaigns to create an "other" class often based upon lies. fiction and half truths. This is not something that should be tolerated in free software projects where code should be judged entirely upon technical reasons such as quality, maintainability, licenses and value for users.

By all means if there are technical reasons to remove elbrus related code that is worth discussing, but I suspect this would not even be a consideration without bad faith on part of western media sources.
