### ISSUE TITLE
OpenBLAS Windows and dgemv - Debug build not loading symbols

### ISSUE THREAD

**Issue by balamurata123** [xianyi/OpenBLAS#3568]
Hi all, 
I am using OpenBLAS on Windows with several other libraries on C++ (project is linked to numerical integration). BLAS appears to be couple well with the rest but I noticed some numerical instabilities coming from dgemv output. My feeling is that my inputs to dgemv are not in the right data type which results in loss of precision. I am using VS debugger and my intention was to check what dgemv does those inputs runtime.

I created a Debug build of OpenBLAS by 1) following xianyi's approach for x64 and 2) changed the build config with Debug flags:  
`cmake .. -G "Ninja" -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DCMAKE_Fortran_COMPILER=flang -DCMAKE_MT=mt -DBUILD_WITHOUT_LAPACK=no -DBUILD_SHARED_LIBS=ON -DNOFORTRAN=0 -DDYNAMIC_ARCH=ON -DCMAKE_BUILD_TYPE=Debug`
`cmake --build . --config Debug`

When built, openblas.pdb is produced. Attaching the Visual Studio debugger to my process however cannot load any symbols for dgemv.c or dgemv.f if I try to add a breakpoint in them in the source code. In debug, I reach to the point where the .cxx source calls dgemv and cannot force VS to load symbols for any OpenBLAS src code.

Are you guys aware if there is a way to build OpenBLAS with all routines having pdbs to allow this or the way to access the routines runtime in debug is different? Looking at the static library openblas.lib post build, it appears that all routines are compiled as individual dlls and lumped in openblas.lib : example 2730.openblas.dll    __imp_cblas_dgemv  2730.openblas.dll    cblas_dgemv

Maybe my approach to tapping in the brain of dgemv routine is wrong. 

Thanks for the help!

**Comment by brada4** [comment]
You need to load PDB file into VS GUI. Certainly a thing you just built locally is not present on default microsoft PDB server.
Probably you need cblas_dgemv via cblas.h header in target install directory. Fortran calling convention is that all parameters are pointers , including to single character and integer args. Really use C functions.

**Comment by balamurata123** [comment]
The symbols are loaded for openblas.dll into Debug -> Windows -> Modules. See screenshot. A breakpoint in cblas_dgemv.c is not shown as being hit. Sharing an overview of the project src code below; I have given extern "C" for the cblas functions. 

 In math.h (part of my project), I define 
```
// BLAS/lapack defs
extern "C" {
  void dgetrf_(const int & m, const int & n, double* A, const int & lda, int* ipiv, int & info);
  void dgetri_(const int & n, double* A, const int & lda, int* ipiv, double* work, const int & lwork, int & info);
  void dgesv_(const int & n, const int & nrhs, double * A, const int & lda, int * ipiv, double * b, const int & ldb, int & info);
  void dgemv_(const char * trans, const int & m, const int & n, const double & alpha, const double * A, const int & lda, const double * x, const int & incx, const double & beta, double * y, const int & incy);
  void dgemm_(const char * transa, const char * transb, const int & m, const int & n, const int & k, const double & alpha, const double * A, const int & lda, const double * B, const int & ldb, const double & beta, double * C, const int & ldc);
  void dger_(const int & m, const int & n, const double & alpha, const double * x, const int & incx, const double * y, const int & incy, double * A, const int & lda);
  void dgecon_(const char * norm, const int & n, double * A, const int & lda, const double & anrom, double & rcond, double * work, int * lwork, int & info);
  void dgttrf_(const int & N, double * DL, double * D, double * DU, double * DU2, int * IPIV, int & INFO);
  void dgttrs_(const char * TRANS, const int & N, const int & NRHS, double * DL, double * D, double * DU, double * DU2, int * IPIV, double * B, const int & LDB, int & info);
  void dsyev_(const char * JOBZ, const char * UPLO, const int & N, double * A, const int & LDA, double * W, double * WORK, const int & LWORK, const int & INFO);
}
```
In math.cxx, the function 

`int mat_vec(const double * const A, int m, const double * const b, int n, double * const c)`

calls dgemv_ as

```
int mat_vec(const double * const A, int m, const double * const b, int n, 
            double * const c)
{
  dgemv_("T", n, m, 1.0, A, n, b, 1, 0.0, c, 1);

  return 0;
}
```

The source code for my project including math.cxx and .h are located in C:\Projects\Project_1\src while project_1.dll including .lib, .pdb are in C:\Projects\Project_1\lib . 

On the other hand, OpenBLAS is built in C:\Projects\OpenBLAS with libs in \build. The install is in C:\Projects\OpenBLAS\opt (the cblas.h in \opt\include is there). 

Env variables on PATH are pointing to both C:\Projects\Project_1\lib and C:\Projects\OpenBLAS\opt and \OpenBLAS\lib. 


![Screenshot 2022-03-12 143536](https://user-images.githubusercontent.com/80645158/158037404-8c6c2ff5-167e-466f-abb3-7eb93530b64a.jpg)


Do you think I am missing anything? Could it be that I missed adding `#include 'cblas.h'` in my math.h? I would be surprised because math.cxx does not complain finding dgemv and producing some output during execution of project_1.dll. 
thanks

**Comment by martin-frbg** [comment]
Can't really help with the pdb files, but perhaps try adding a `printf` to interface/gemv.c to see if your build of the OpenBLAS dll gets called at all ?

**Comment by balamurata123** [comment]
Thanks for the tip. You mean add printf to gemv.c, rebuild OpenBLAS and see if it prints, right? I think it does get called - as I said calling this function dgemv actually returns an output for a given inputs but it is not the correct output.

**Comment by brada4** [comment]
Yup, debugger should recognize function signature that comes from crt runtime.

Just guesses around:

The dialog actually shows that PDB symbols are loaded. Try calling cblas_dgemv (w different but at least stable arg prototypes) - i suspect your flang is gfortran wrapper, because (old) flang never worked on windows, and thus does generate only dwarf debug info that VS does not understand(?)

What more you could try:
x64dbg - just load symbols, maybe your visual studio needs updates and patches
and
[Generate PDB from mingw build](https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-in-Microsoft-Visual-Studio#generate-windows-native-pdb-files-from-gccgfortran-build)

**Comment by balamurata123** [comment]
Thanks for the feedback guys. I am more inclined to write up the several matrix operation functions I need as standalone functions in my code rather than using a library; in my case the less dependencies the better. I am closing this issue but happy to support in future if other user open a similar one.
