### ISSUE TITLE
Check Wiki for hijacked links

### ISSUE THREAD

**Issue by lordofbikes** [xianyi/OpenBLAS#3572]
Like our Wiki at [LibreCAD](https://github.com/LibreCAD/LibreCAD/wiki) yours has been hijacked too.
Check your [Wiki history](https://github.com/xianyi/OpenBLAS/wiki/_history).
Especially commit [75bba70](https://github.com/xianyi/OpenBLAS/wiki/_compare/8215a997e998320e8e7feb456fec8b75e9cb3b84...75bba70832f8765faee693931c4a9e3eb6c84d98).

I checked this because the user `neitann`, who hijacked ours, has also a fork of OpenBLAS.
User `neitann` is already reported to GitHub support by me.
Also user `rumiv`, who did the last two commits in your Wiki, same as in our Wiki.

**Comment by martin-frbg** [comment]
Right, thanks. It is a pity that the wiki here has quite poor security options.

**Comment by brada4** [comment]
It started even earlier.
https://github.com/xianyi/OpenBLAS/wiki/Installation-Guide/_compare/b8da0e8523b898a2206d1e2fe99dbfb4ebb0ffa8...c3b1ca5b4dc79d9a86588562cc214de62b21d563

**Comment by brada4** [comment]
First one is [ cecf8cf ](https://github.com/xianyi/OpenBLAS/wiki/Installation-Guide/_compare/b8da0e8523b898a2206d1e2fe99dbfb4ebb0ffa8...c3b1ca5b4dc79d9a86588562cc214de62b21d563)

[virustotal](https://www.virustotal.com/gui/url/bc5c154904b88fc1d0253ecc8482fc49261729ff9b28cfc050c44ef364b68e13/details)

All four implicated users are already dealt with by github.

Let me back flipping wiki editing checkbox, you cannot go as granular as to say "new/non-contributor cannot edit (download) links without review"

@isuruf  so far was succeeding at reverting rogue edits in wiki pages. Thank you ;-)

**Comment by martin-frbg** [comment]
I had blocked and reported the offending users to github support, after reverting the latest edit (which was hijacked again the following night, and again put back by me). Kudos to Isuruf for rewriting it as a proper interwiki link, I am now waiting for xianyi's decision whether to lockdown the wiki.
