### ISSUE TITLE
ARMv8 & ARMv8SVE DGEMM performance

### ISSUE THREAD

**Issue by wxmwy** [xianyi/OpenBLAS#3581]
I ran some tests using the GEM5 simulator.

Compile GEM5:
`
scons build/arm/gem5.opt
`
Run the program using GEM5:
`
build/ARM/gem5.opt configs/example/se.py --cmd=/root/test_openblas/arm_gemm
`
Compile openblas:
`
make TARGET=ARMV8 HOSTCC=gcc BINARY=64 CC=aarch64-none-linux-gnu-gcc FC=aarch64-none-linux-gnu-gfortran NUM_THREADS=1 blas
`
Correctness verification:
Compare the first five data of C obtained using OpenBLas with normal calculations.(Small difference in accuracy is considered correct)

I have tested DGEMM versions 0.3.17~0.3.20. Here are the simple test results.
1.For the compile option ARMV8, DGEMM performance degrades from version 0.3.19 onwards.
![17-20](https://user-images.githubusercontent.com/40709496/159836866-3a17cfd7-a06f-48db-ac63-99cfb1397b2d.png)

2.For compile option ARMV8SVE, version 0.3.20, ARMV8SVE is less effective than ARMV8, using LD1RQD instead of LD1RD is better than ARMV8.
![20diff](https://user-images.githubusercontent.com/40709496/159837166-9588224b-b2c8-4ae6-abdd-0a80a9107b73.png)

3.And I test the https://github.com/docularxu/OpenBLAS project implementation 256bits SVE kernel.(also use LD1RQD)(This implementation is very fast, but there seems to be something wrong with the accuracy, perhaps the incompatibility caused by the fixed 256 bits?)
![tsv_sve](https://user-images.githubusercontent.com/40709496/159837191-c433e467-be59-46b8-abb7-4724840da0d1.png)

Now I have a lot of confusion:
1. 0.3.19 was there anything added that would degrade the performance of the ARMV8 option?
2. 0.3.20 ARMV8SVE performing worse than ARMV8 is or not due to gem5 simulator setup?

The test code I used and kernel modified with LD1RQD are as follows:
https://github.com/wxmwy/openblas_sve

**Comment by martin-frbg** [comment]
1. No intentional changes, will need to bisect if this is reproducible on actual hardware
2. I hope to get (small) ARMV9 hardware soon, which should hopefully help with benchmarking SVE code

**Comment by brada4** [comment]
It looks like one more cycle in 1024Hz clock. Just rise iterations so that they spin between one and ten seconds. Most likely you will see fluctuations of same scale using same versions. Benchmarks were calibrated dozen years ago, nowadays they are so small that small samples often fall under system timer resolution.

Only changes between versions is applying optimisation flags to CLANG on par of those of GCC, and changing apple silicon configurations, which does not touch you as you use GCC since beginning and an emulator.

Your measurement of @docularxu WiP branch looks inspiring.

**Comment by binebrank** [comment]
I would **not** draw any foregone conclusions based on the Gem5 simulator. Please be aware that results will depend a lot on the model and what kind of hardware you are simulating... Especially if you use Gem5 out of the box, you are probably using some default model configurations which are most likely outdated. 

I was not aware of the 256-fixed width implementation but such a big difference is very hard to understand without more context. (Gem5 model, SVE size,..) I also tested my kernels in the Gem5 simulator with a model loosely based on the Neoverse N1 core and the results on a single core were around 95%, 92% and 80% of a peak performance for 128-, 256- and 512-bit SVE, respectively. This gave me confirmation that the kernels are "ok", but again, simulators are one thing and hardware is another.

**Comment by wxmwy** [comment]
Thank you to everyone for your answers. The current tests seem pointless. I will close this issue, please kick me if there are reliable test results.

**Comment by brada4** [comment]
> Thank you to everyone for your answers. The current tests seem pointless. I will close this issue, please kick me if there are reliable test results.

You need reliable hardware, along lines of raspberry or top-end wifi router. Emulators of whatever jit/acceleration level are only a test of correctness, sometimes their own.

**Comment by wxmwy** [comment]
Hi, guys, I found the reason why the 0.3.19 default ARMV8 is slowing down.

In **param.h** file, for Other/undetected ARMv8 cores

0.3.18 and before

#define DGEMM_DEFAULT_UNROLL_M  8
#define DGEMM_DEFAULT_UNROLL_N  4

change to:

0.3.19 and after

#define DGEMM_DEFAULT_UNROLL_M  4
#define DGEMM_DEFAULT_UNROLL_N  8

Normally this does not cause a performance change. However, in **KERNRL.ARMV8**, MxN=8x4 use .S assembler code, otherwise generic/*.c files are used. 

## in KERNEL.ARMV8
ifeq ($(DGEMM_UNROLL_M), 8)
DGEMMINCOPY    =  dgemm_ncopy_$(DGEMM_UNROLL_M).S
DGEMMITCOPY    =  dgemm_tcopy_$(DGEMM_UNROLL_M).S
else
DGEMMINCOPY    =  ../generic/gemm_ncopy_$(DGEMM_UNROLL_M).c
DGEMMITCOPY    =  ../generic/gemm_tcopy_$(DGEMM_UNROLL_M).c
endif

DGEMMINCOPYOBJ =  dgemm_incopy$(TSUFFIX).$(SUFFIX)
DGEMMITCOPYOBJ =  dgemm_itcopy$(TSUFFIX).$(SUFFIX)
endif

ifeq ($(DGEMM_UNROLL_N), 4)
DGEMMONCOPY    =  dgemm_ncopy_$(DGEMM_UNROLL_N).S
DGEMMOTCOPY    =  dgemm_tcopy_$(DGEMM_UNROLL_N).S
else
DGEMMONCOPY    =  ../generic/gemm_ncopy_$(DGEMM_UNROLL_N).c
DGEMMOTCOPY    =  ../generic/gemm_tcopy_$(DGEMM_UNROLL_N).c
endif

Maybe add 4x8 support for KERNRL.ARMV8? This doesn't require too many file changes. Or restore the default MN parameter.

**Comment by martin-frbg** [comment]
Oops.@binebrank, that was in your #3425 - probably spurious and leftover in your fork from earlier testing, as the ARMV8SVE DGEMM is already set to 2x8 ?

**Comment by binebrank** [comment]
Oh, this is bad, I cannot believe I left this in the merge request. Can you change this @martin-frbg ?
Hopefully, not a lot of real hardware takes this code path (undetected ARMv8 cores)...

**Comment by wxmwy** [comment]
Now I realize how stupid my previous test was.

I corrected the parameter, and the sve bit length was unified to 256bits.
`
build/ARM/gem5.opt configs/example/se.py --param 'system.cpu[:].isa[:].sve_vl_se = 2'  --caches --l2cache
`
The new performance data is as follows:
4.32 GFlops/s   ARMV8
7.22 GFlops/s   ARMV8SVE
8.20 GFlops/s   ARMV8SVE(use LD1RQD)
8.22 GFlops/s   ARMV8SVE(use LD1RQD and unroll sve_n/tcopy four times)
10.28 GFlops/s TSV110SVE(by docularxu, this time the test results are correct)

TSV110SVE is fast because it is optimized for 256bits only, a larger kernel(16x4) was used and n/tcopy was divided in detail. The test results are normal this time (just seem to be). In fact, the “--caches --l2cache” parameter did not seem to cause a performance change in the tests. I think I need to continue learning GEM5 about cache usage. I wanted to write a large kernel, but my little assembly experience even made it difficult for me to read the existing kernel. As a novice, I would continue to explore possible optimizations in my spare time, thanks to BineBrank for the advices.

**Comment by ProgrammerWLY** [comment]
Hello, what is the theoretical peak GFLOPS of this processor platform (double and float)?


| |
computer12315
|
|
***@***.***
|
签名由网易邮箱大师定制
On 3/30/2022 ***@***.***> wrote：

Now I realize how stupid my previous test was.

I corrected the parameter, and the sve bit length was unified to 256bits.
build/ARM/gem5.opt configs/example/se.py --param 'system.cpu[:].isa[:].sve_vl_se = 2' --caches --l2cache
The new performance data is as follows:
4.32 GFlops/s ARMV8
7.22 GFlops/s ARMV8SVE
8.20 GFlops/s ARMV8SVE(use LD1RQD)
8.22 GFlops/s ARMV8SVE(use LD1RQD and unroll sve_n/tcopy four times)
10.28 GFlops/s TSV110SVE(by docularxu, this time the test results are correct)

TSV110SVE is fast because it is optimized for 256bits only, a larger kernel(16x4) was used and n/tcopy was divided in detail. The test results are normal this time (just seem to be). In fact, the “--caches --l2cache” parameter did not seem to cause a performance change in the tests. I think I need to continue learning GEM5 about cache usage. I wanted to write a large kernel, but my little assembly experience even made it difficult for me to read the existing kernel. As a novice, I would continue to explore possible optimizations in my spare time, thanks to BineBrank for the advices.

**Comment by wxmwy** [comment]
This was tested using the default option of the GEM5 emulator, not the actual CPU. As for how the theoretical peak of the GEM5 simulator is calculated, this may depend on the parameters used.

> Hello, what is the theoretical peak GFLOPS of this processor platform (double and float)? | | computer12315 | | ***@***.*** | 签名由网易邮箱大师定制 On 3/30/2022 ***@***.***> wrote： Now I realize how stupid my previous test was. I corrected the parameter, and the sve bit length was unified to 256bits. build/ARM/gem5.opt configs/example/se.py --param 'system.cpu[:].isa[:].sve_vl_se = 2' --caches --l2cache The new performance data is as follows: 4.32 GFlops/s ARMV8 7.22 GFlops/s ARMV8SVE 8.20 GFlops/s ARMV8SVE(use LD1RQD) 8.22 GFlops/s ARMV8SVE(use LD1RQD and unroll sve_n/tcopy four times) 10.28 GFlops/s TSV110SVE(by docularxu, this time the test results are correct) TSV110SVE is fast because it is optimized for 256bits only, a larger kernel(16x4) was used and n/tcopy was divided in detail. The test results are normal this time (just seem to be). In fact, the “--caches --l2cache” parameter did not seem to cause a performance change in the tests. I think I need to continue learning GEM5 about cache usage. I wanted to write a large kernel, but my little assembly experience even made it difficult for me to read the existing kernel. As a novice, I would continue to explore possible optimizations in my spare time, thanks to BineBrank for the advices. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by martin-frbg** [comment]
Trying to get some real-world data with non-supercomputer hardware... On a Snapdragon 8Gen1 system (Cortex X2/710/510), I  get a single-thread performance of 20.3 vs. 22.8 GFlops for the original SVE kernel compared to the one with LD1RQD. (Had to add back a j=1000 loop to that GEMM benchmark to get stable results - as this is with Termux on an un-rooted Android 12 device, I do not see a way to actively bind the task to the single Cortex X2)
Edit: 29.8 vs. 34.2 when not powersaving...

**Comment by wxmwy** [comment]
There are also some changes to be made in KERNEL.A64FX and KERNEL.ARMV8SVE, just like:
SGEMMONCOPY    =  sgemm_ncopy_$(DGEMM_UNROLL_N).S
SGEMMOTCOPY    =  sgemm_tcopy_$(DGEMM_UNROLL_N).S

CGEMMONCOPY    =  ../generic/zgemm_ncopy_$(ZGEMM_UNROLL_N).c
CGEMMOTCOPY    =  ../generic/zgemm_tcopy_$(ZGEMM_UNROLL_N).c

These use the wrong GEMM_UNROLL_N, resulting in SGEMM error when I adjust UNROLL_N of DGEMM. @martin-frbg
