### ISSUE TITLE
OpenBlas Armadillo Conan

### ISSUE THREAD

**Issue by FurchRadeon** [xianyi/OpenBLAS#3582]
Hi. 

I am trying to use openblas and armadillo. But i have issue saying that '-lgfortran' could not be found.

As package manager, i am using conan. 

Do i did something worng in current configuration ? 

conanfile.txt 

```
[requires]
gfortran/10.2
openblas/0.3.17
armadillo/10.7.3

[options]
armadillo:shared=True
armadillo:use_wrapper=False
armadillo:use_blas=openblas
armadillo:use_lapack=openblas

[generators]
cmake
```

CMakeFile 

```
cmake_minimum_required(VERSION 3.15)
project(armadillo_project CXX)

include(build/conanbuildinfo.cmake)
conan_basic_setup()

find_package(Armadillo REQUIRED)

include_directories(${ARMADILLO_INCLUDE_DIRS})

add_executable(armadillo_project src/main.cpp)

# Use the global target
target_link_libraries(armadillo_project PUBLIC openblas gfortran)
```

**Comment by brada4** [comment]
Install fortran compiler systemwide just like C compiler.

**Comment by FurchRadeon** [comment]
i tried already. It doesn't work.

**Comment by FurchRadeon** [comment]
> Install fortran compiler systemwide just like C compiler.
i tried already. It doesn't work.

**Comment by martin-frbg** [comment]
Do you see a libgfortran.so installed on the system ? (Just in case it is packaged as a separate libgfortran or gfortran-dev - I don't know conan)

**Comment by brada4** [comment]
https://conan.io/center/openblas?version=0.3.17&os=Linux&tab=configuration
There is this strange line:
```
26: "fPIC": True,
```
Try taking that option out completely, including down in the file, sort of gfortran 10.2 does not add it, so best to go with (same) defaults everywhere, which are likely on ASLR side anyway.

**Comment by FurchRadeon** [comment]
> https://conan.io/center/openblas?version=0.3.17&os=Linux&tab=configuration There is this strange line:
> 
> ```
> 26: "fPIC": True,
> ```
> 
> Try taking that option out completely, including down in the file, sort of gfortran 10.2 does not add it, so best to go with (same) defaults everywhere, which are likely on ASLR side anyway.

If i understood right : delete -> gfortran/10.2 and "fPIC": False or to delete at all. 
I need to use Lapack. So i need to compile openblas to have access to lapack.

**Comment by martin-frbg** [comment]
Uh, pretty sure the `-fPIC` is required for compilation of libopenblas... anyway it should not have anything to do with not finding libgfortran in the link step. Perhaps you need to set LD_LIBRARY_PATH to its location if it is non-standard.

**Comment by FurchRadeon** [comment]
> Uh, pretty sure the `-fPIC` is required for compilation of libopenblas... anyway it should not have anything to do with not finding libgfortran in the link step. Perhaps you need to set LD_LIBRARY_PATH to its location if it is non-standard.

this is my very simple build.sh


```
CRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
cd $SCRIPT_DIR;
mkdir -p build && cd build || exit

echo $SCRIPT_DIR

conan install .. --build missing 
cmake -DCMAKE_Fortran_COMPILER="usr/bin/gfortran" ..
make
```

And it doesn't work. But i have installed gfortran 

Is possible to add LD_LIBRARY_PATH in conanfile.txt as [env] part ? 
I tried, but seems it if ignored

**Comment by martin-frbg** [comment]
Strange, I'd think cmake would check if the supplied CMAKE_Fortran_COMPILER is able to build executables, and a missing libgfortran would stop the build before it actually gets to compiling OpenBLAS. On the other hand I do not recall that there had been any typos or omissions in the cmake support files of 0.3.17 that could cause this.

**Comment by wxmwy** [comment]
> > Uh, pretty sure the `-fPIC` is required for compilation of libopenblas... anyway it should not have anything to do with not finding libgfortran in the link step. Perhaps you need to set LD_LIBRARY_PATH to its location if it is non-standard.
> 
> this is my very simple build.sh
> 
> ```
> CRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
> cd $SCRIPT_DIR;
> mkdir -p build && cd build || exit
> 
> echo $SCRIPT_DIR
> 
> conan install .. --build missing 
> cmake -DCMAKE_Fortran_COMPILER="usr/bin/gfortran" ..
> make
> ```
> 
> And it doesn't work. But i have installed gfortran
> 
> Is possible to add LD_LIBRARY_PATH in conanfile.txt as [env] part ? I tried, but seems it if ignored

Maybe CMAKE_Fortran_COMPILER="usr/bin/gfortran" should be CMAKE_Fortran_COMPILER="/usr/bin/gfortran" ?

**Comment by FurchRadeon** [comment]
> > > Uh, pretty sure the `-fPIC` is required for compilation of libopenblas... anyway it should not have anything to do with not finding libgfortran in the link step. Perhaps you need to set LD_LIBRARY_PATH to its location if it is non-standard.
> > 
> > 
> > this is my very simple build.sh
> > ```
> > CRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
> > cd $SCRIPT_DIR;
> > mkdir -p build && cd build || exit
> > 
> > echo $SCRIPT_DIR
> > 
> > conan install .. --build missing 
> > cmake -DCMAKE_Fortran_COMPILER="usr/bin/gfortran" ..
> > make
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And it doesn't work. But i have installed gfortran
> > Is possible to add LD_LIBRARY_PATH in conanfile.txt as [env] part ? I tried, but seems it if ignored
> 
> Maybe CMAKE_Fortran_COMPILER="usr/bin/gfortran" should be CMAKE_Fortran_COMPILER="/usr/bin/gfortran" ?

I tried with "/usr...", still the same. Meanwhile i observed " ABI INFO -> Failed ".

**Comment by martin-frbg** [comment]
"Detecting ... compiler ABI INFO ->Failed" would suggest it failed to get any output from the compiler (many possible reasons for that - disk full, wrong permissions, wrong compiler binary for the cpu architecture). Are you sure that gfortran is in /usr/bin, can you call  `/usr/bin/gfortran -v` from the command line and get the version number ?

**Comment by FurchRadeon** [comment]
> "Detecting ... compiler ABI INFO ->Failed" would suggest it failed to get any output from the compiler (many possible reasons for that - disk full, wrong permissions, wrong compiler binary for the cpu architecture). Are you sure that gfortran is in /usr/bin, can you call `/usr/bin/gfortran -v` from the command line and get the version number ?
Yes, ican. 

<img width="1787" alt="image" src="https://user-images.githubusercontent.com/46250186/160144426-c6063035-6491-435b-ba78-49f1d372d2a7.png">

**Comment by martin-frbg** [comment]
Good. Is there any additional info in the CMakeError.log and CMakeOutput.log that should be under CMakeFiles in your build directory ? (And I think we still do not know if/where there is any `libgfortran.so*` on that system)

**Comment by FurchRadeon** [comment]
> Good. Is there any additional info in the CMakeError.log and CMakeOutput.log that should be under CMakeFiles in your build directory ? (And I think we still do not know if/where there is any `libgfortran.so*` on that system)

Is present in "/usr/lib".  It looks okay from this point.

**Comment by martin-frbg** [comment]
Interesting. (And it is a regular file,not just a link pointing nowhere ?) Can you please upload (attach) your CMakeError.log and -if it exists - the CMakeOutput.log as well ?

And just for testing, you could try running `make` from the toplevel OpenBLAS directory, just to see if that finds gfortran and builds LAPACK.

**Comment by FurchRadeon** [comment]
> Interesting. (And it is a regular file,not just a link pointing nowhere ?) Can you please upload (attach) your CMakeError.log and -if it exists - the CMakeOutput.log as well ?
> 
> And just for testing, you could try running `make` from the toplevel OpenBLAS directory, just to see if that finds gfortran and builds LAPACK.

Thank you for your support ! 
I reinstalled the gcc, gfortran and now is compiling okay . 

Now on Ubuntu i have "Killed, reason out of memory". 

According to "top" app , it used many many threads and resources.  I am using multithreading process. 

I just installed armadillo with openblas from conan. 

Do i need to make some other pre-configuration from OpenBlas side ? 

I did " NO_AFFINITY=1" according to this link :  [https://gist.github.com/BERENZ/ff274ebbf00ee111c708]

**Comment by martin-frbg** [comment]
You can limit the number of threads OpenBLAS will use by setting the environment variable OPENBLAS_NUM_THREADS

**Comment by FurchRadeon** [comment]
![image](https://user-images.githubusercontent.com/46250186/160297841-69640305-0aab-4b2f-8e51-80b903243910.png)

 I did something like that, but i am not so sure that this will help.

**Comment by brada4** [comment]
How much memory you have? Typically you need 100MB + a bit of swap for each MAKE_NB_JOBS , shich defaults to `nproc`

**Comment by FurchRadeon** [comment]
> How much memory you have? Typically you need 100MB + a bit of swap for each MAKE_NB_JOBS , shich defaults to `nproc`

![image](https://user-images.githubusercontent.com/46250186/160357225-b102d9ec-1967-4e7a-a104-1e2e34d1781d.png)
 
This is what i can see in "dmesg"

Base Memory(ram) arround 3072 MB and nproc = 4

It looks like "oom" kill the process because is consumes too much memory

**Comment by martin-frbg** [comment]
Just to clarify - does this happen when compiling (MAKE_NB_JOBS as brada4 suggested), or when running Armadillo ? If with Armadillo, can you run the examples that come with Armadillo (as mentioned in the gist you linked to), or do they run out of memory as well ?

**Comment by FurchRadeon** [comment]
> Just to clarify - does this happen when compiling (MAKE_NB_JOBS as brada4 suggested), or when running Armadillo ? If with Armadillo, can you run the examples that come with Armadillo (as mentioned in the gist you linked to), or do they run out of memory as well ?

When running Armadillo with OpenBlas. 

I run example1 from examples folder from Armadillo, and it was okay.

**Comment by martin-frbg** [comment]
Then maybe your problem size is simply too large to fit in 3 GB (plus available swap) ? 
You could try recompiling OpenBLAS with "NUM_THREADS=1" to save a little memory when you are only going to use one thread anyway, or even "USE_THREAD=0 USE_LOCKING=1" to leave out all the thread management, but I doubt this will free up much memory.

**Comment by brada4** [comment]
> simply too large to fit in 3 GB

If you see the dmesg again - process has 7GB mapped data, while dies at 2,5GB resident usage. BLAS will use all arguments end to end, there is no other way, that is overcommited result will certainly grow to full allocated size of 7GB.

**Comment by FurchRadeon** [comment]
> > simply too large to fit in 3 GB
> 
> If you see the dmesg again - process has 7GB mapped data, while dies at 2,5GB resident usage. BLAS will use all arguments end to end, there is no other way, that is overcommited result will certainly grow to full allocated size of 7GB.

If i understood right, this is normal behaviour to have such a big memory allocated ?

**Comment by martin-frbg** [comment]
> If i understood right, this is normal behaviour to have such a big memory allocated ?

Depends on how big your data is, and what requirements Armadillo has. OpenBLAS itself does not automatically require gigabytes of memory, especially if you use a single-threaded build. Only the multithreaded OpenBLAS reserves some memory for a data buffer where threads can exchange partial results, which on x86_64 is 128MB per thread. You can try reducing this value by setting the BUFFERSIZE variable at compile time (e.g. `make BUFFERSIZE=20` - the actual value is `32 << BUFFERSIZE`)

**Comment by brada4** [comment]
>  this is normal behaviour to have such a big memory allocated

If you use 2x 1GB input array and output 1GB, BLAS as per specification will use all of that, your crashed app has 7GB allocated but so far 2,5GB touched. You certainly need 7GB physical+swap for task at hand (plus buffers Martin talks about plus some breathing space for the rest of system)
