### ISSUE TITLE
ddot returns value inconsistent with sum(a*b) on newer Intel CPUs

### ISSUE THREAD

**Issue by bernstei** [xianyi/OpenBLAS#3583]
I'm using OpenBLAS 0.3.18 (apparently), from anaconda3, and for this simple fortran program I get an output that is different from 0 by of order 1e-16 on some Intel CPUs (it's not threading, or at least setting `OPENBLAS_NUM_THREADS=1` doesn't change it).  With MKL the difference is 0 for all CPUs I've tried.  I have to admit that I'm a bit confused by the anaconda3 versioning, so if there's a canonical version of OpenBLAS (that'd run on CentOS 7), I'd be happy to compare to that.

```
program test_dot
implicit none
      double precision :: p(3), v(3)
      double precision, external :: ddot
      double precision :: val_sum, val_dot

      p = (/ 16.90513420661038423986610723659396171569824218750000D0, &
             0.50000000000000000000000000000000000000000000000000D0, &
             -1.71583683999999991875995419832179322838783264160156D0 /)
      v = (/ 0.01628648030646704172874628113731887424364686012268D0, &
            -0.17188353256547875269610869963798904791474342346191D0, &
            -0.98498264035059979182307188239064998924732208251953D0 /)

    val_sum = sum(p*v)
    write (*, '(A15,F55.50)') "sum", val_sum
    val_dot = ddot(3, p, 1, v, 1)
    write (*, "(A15,F55.50)") "dot", val_dot
    write (*, '(A15,F55.50)') "dot - sum", (val_dot - val_sum)

end program
```

The newest CPU that does _not_ show a difference is 
```
Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm epb invpcid_single intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm xsaveopt cqm_llc cqm_occup_llc dtherm ida arat pln pts md_clear spec_ctrl intel_stibp flush_l1d
```
and the oldest that does is
```
Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 invpcid_single intel_ppin intel_pt ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke md_clear spec_ctrl intel_stibp flush_l1d
```

**Comment by brada4** [comment]
Why dont you use v0.3.20 that has important AVX-512 fixes?
If you take newest CPU and set OPENBLAS_CORETYPE=HASWELL - does it start working?

How big is the difference you are talking about?
double precision is accurate to 15-16 decimal numbers.

**Comment by bernstei** [comment]
Thanks.  I'll test that version and update this issue.

**Comment by bernstei** [comment]
The numerical error is of order 1e-16, which I agree isn't unreasonable for double precision, but it's inconvenient for unit testing that it's so CPU dependent.  I guess even if this doesn't happen in v0.3.20, I'll need to work around it in my unit testing, because it needs to work with anaconda3/numpy which packages 0.3.18 for now.

Adding `OPENBLAS_CORETYPE=HASWELL` _does_ make the two expressions equal, yes, so that's a possible workaround for me (as is fundamentally modifying my unit test, I guess).

I've so far been unable to compile 0.3.20 with either gcc 7 or gcc 10. With 10.3.0 I get an internal compiler error (seg fault) compiling `sblat1`, and with 7 I get an error compiling `dasum.c`.  If you have any suggestions for setups that are known to work or sources for binary versions for CentOS 7 x86_64, I'd appreciate any suggestions.
```
../kernel/x86_64/dasum_microk_skylakex-2.c: In function ‘dasum_kernel’:
../kernel/x86_64/dasum_microk_skylakex-2.c:42:38: error: incompatible type for argument 1 of ‘_mm512_abs_pd’
             accum_0 += _mm512_abs_pd(_mm512_load_pd(&x1[i + 0]));
                                      ^~~~~~~~~~~~~~
```

If you feel that this is just the expected level of accuracy, I'd completely understand if you close the issue as is.  If you want me to pursue it further by testing in the latest version, I'd be happy to continue trying.

**Comment by brada4** [comment]
Solution is to allow expected errors i.e abs(N - ref) < 1/ 2^51 instead of 1:1 comparison.

**Comment by bernstei** [comment]
The problem is that later calculations build upon earlier ones, and that process is unstable. I do know how to fix it in my tests, and I agree that it's not necessarily indicative of an OpenBLAS bug (although if there are avx512 fixes in later versions, it might be). As I said, I'm happy for this issue to be closed or kept open, if anyone cares, until I determine whether or not it also happens in 0.3.20.

**Comment by brada4** [comment]
They balance out due to rounding back and forth. If you want same results every time use netlib lapack with -O0, or symbolic computations to get absolute truth.
There is no problem, your unit test should accomodate floating point rounding and FMA instructions that do multiple operations with higher precision (read different end result) in one CPU instruction.
Example `0.07*10-0.7`

**Comment by brada4** [comment]
[CentOS7](https://github.com/xianyi/OpenBLAS/wiki/Faq#binutils) or use package from fedora EPEL which is compiled without AVX-512 support.

**Comment by martin-frbg** [comment]
I doubt that 0.3.20 will be any different - no change in the AVX512 ddot microkernel there, the "issue" is probably that it accumulates intermediate results at higher precision. (And I suspect you could run into the same kind and magnitude of problem with compiler optimizations alone...)

**Comment by brada4** [comment]
The point is that tests need to acknowledge
`(1/2^52)*log2(floating point operations per result value)` inaccuracy by abs(a-b)< inaccuracy
It cannot be == comparison.
Please check numpy test suite, I think ddot/sdot tests still pass on any CPU with OpenBLAS or anything else.

**Comment by brada4** [comment]
As per faq/softwarecollections web
```
yum install centos-release-scl-rh
yum install make perl devtoolset-7-gcc-gfortran
```

```
$ scl enable devtoolset-7 -- make -s DYNAMIC_ARCH=1 TARGET=CORE2 NUM_THREADS=128

 OpenBLAS build complete. (BLAS CBLAS LAPACK LAPACKE)

  OS               ... Linux             
  Architecture     ... x86_64               
  BINARY           ... 64bit                 
  C compiler       ... GCC  (cmd & version : cc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5))
  Fortran compiler ... GFORTRAN  (cmd & version : GNU Fortran (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5))
  Library Name     ... libopenblasp-r0.3.20.a (Multi-threading; Max num-threads is 128)
  Supporting multiple x86_64 cpu models with minimum requirement for the common code being CORE2

To install the library, you can run "make PREFIX=/path/to/your/installation install".
```

**Comment by bernstei** [comment]
The `scl enable ... make ...` command gives the same error as I was getting before with gcc 7.3.0 (which was the scl version, just invoked in a different way), specifically
```
> scl enable devtoolset-7 -- make -s  DYNAMIC_ARCH=1 TARGET=CORE2 NUM_THREADS=128
In file included from ../kernel/x86_64/dasum.c:8:0:
../kernel/x86_64/dasum_microk_skylakex-2.c: In function ‘dasum_kernel’:
../kernel/x86_64/dasum_microk_skylakex-2.c:42:38: error: incompatible type for argument 1 of ‘_mm512_abs_pd’
             accum_0 += _mm512_abs_pd(_mm512_load_pd(&x1[i + 0]));
                                      ^~~~~~~~~~~~~~
In file included from /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/include/immintrin.h:45:0,
                 from ../kernel/x86_64/dasum_microk_skylakex-2.c:6,
                 from ../kernel/x86_64/dasum.c:8:
/opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/include/avx512fintrin.h:7301:1: note: expected ‘__m512 {aka __vector(16) float}’ but argument is of type ‘__m512d {aka __vector(8) double}’
 _mm512_abs_pd (__m512 __A)
 ^~~~~~~~~~~~~
In file included from ../kernel/x86_64/dasum.c:8:0:
../kernel/x86_64/dasum_microk_skylakex-2.c:43:38: error: incompatible type for argument 1 of ‘_mm512_abs_pd’
             accum_1 += _mm512_abs_pd(_mm512_load_pd(&x1[i + 8]));
                                      ^~~~~~~~~~~~~~
In file included from /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/include/immintrin.h:45:0,
                 from ../kernel/x86_64/dasum_microk_skylakex-2.c:6,
                 from ../kernel/x86_64/dasum.c:8:
/opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/include/avx512fintrin.h:7301:1: note: expected ‘__m512 {aka __vector(16) float}’ but argument is of type ‘__m512d {aka __vector(8) double}’
 _mm512_abs_pd (__m512 __A)
 ^~~~~~~~~~~~~
In file included from ../kernel/x86_64/dasum.c:8:0:
../kernel/x86_64/dasum_microk_skylakex-2.c:44:38: error: incompatible type for argument 1 of ‘_mm512_abs_pd’
             accum_2 += _mm512_abs_pd(_mm512_load_pd(&x1[i +16]));
                                      ^~~~~~~~~~~~~~
In file included from /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/include/immintrin.h:45:0,
                 from ../kernel/x86_64/dasum_microk_skylakex-2.c:6,
                 from ../kernel/x86_64/dasum.c:8:
/opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/include/avx512fintrin.h:7301:1: note: expected ‘__m512 {aka __vector(16) float}’ but argument is of type ‘__m512d {aka __vector(8) double}’
 _mm512_abs_pd (__m512 __A)
 ^~~~~~~~~~~~~
In file included from ../kernel/x86_64/dasum.c:8:0:
../kernel/x86_64/dasum_microk_skylakex-2.c:45:38: error: incompatible type for argument 1 of ‘_mm512_abs_pd’
             accum_3 += _mm512_abs_pd(_mm512_load_pd(&x1[i +24]));
                                      ^~~~~~~~~~~~~~
In file included from /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/include/immintrin.h:45:0,
                 from ../kernel/x86_64/dasum_microk_skylakex-2.c:6,
                 from ../kernel/x86_64/dasum.c:8:
/opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/include/avx512fintrin.h:7301:1: note: expected ‘__m512 {aka __vector(16) float}’ but argument is of type ‘__m512d {aka __vector(8) double}’
 _mm512_abs_pd (__m512 __A)
 ^~~~~~~~~~~~~
make[1]: *** [Makefile.L1:683: dasum_k_SKYLAKEX.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:174: libs] Error 1
```

**Comment by martin-frbg** [comment]
This was #2949, determined to be a header bug in gcc-7.3.0. (A simple patch was proposed as a workaround in #2999, perhaps I should merge it after all, if this keeps biting people). Can't really help with the gfortran-10.3 ICE in sblat1.f, except you could hack the Makefile in test to remove the "level1" BLAS tests from the "all .." line near the top.

**Comment by brada4** [comment]
I built with all present versions up to 11 when editing FAQ entry. For crash I would suggest verifying system integrity - hardware like RAM first, and files on the disk and disk itself after. There is no chance mass-market software crashes predictably.
```
scl enable devtoolset-7 -- $SHELL
$ gcc --version
gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
$ gfortran --version
GNU Fortran (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
$ as --version
GNU assembler version 2.28-11.el7
This assembler was configured for a target of `x86_64-redhat-linux'.
```
It was/is packaging bug with EL6 for sure.

**Comment by bernstei** [comment]
Perhaps our scl devtools are not up to date, since I'm getting gcc 7.3.0, so I'll see if that needs to be done (note that we're using CentOS 7, not 6).

By the way, we now have an example (from a piece of software that's too complex to be useful as a test case here, I think), that using the explicit sum is noticeably better behaved than ddot (in this case that's actually python vs. numpy `np.dot`), which might indicate that whatever OpenBLAS is doing is systematically less accurate than it could be.  I'll try to find a way to test this explicitly for a simple case, and post it later today.

**Comment by brada4** [comment]
Please follow the rituals from FAQ - install release/repo package, then target package.
(dressing my work-for-bread hat)
do package-cleanup --orphans // --leaves // rpm -Va // yum distribution-synchronization and clean up whatever half-installs are there, 
in principle I dont see anthing holding you back from (as) clean (as possible) devtoolset-11 install.

**Comment by bernstei** [comment]
> Please follow the rituals from FAQ - install release/repo package, then target package. (dressing my work-for-bread hat) do package-cleanup --orphans // --leaves // rpm -Va // yum distribution-synchronization and clean up whatever half-installs are there, in principle I dont see anthing holding you back from (as) clean (as possible) devtoolset-11 install.

I'm afraid I don't know what FAQ you're referring to exactly.  I went to the FAQ I could find https://github.com/xianyi/OpenBLAS/wiki/faq, and I don't see any procedures that refer to anything in your message.    Regardless, I did as much of the commands you list as I could without breaking this production machine (e.g. distribution-synchronization wanted to downgrade ucx, which would break out MPI), but none indicated they wanted to do anything related to compilers or devtoolset.

I was never able to get OpenBLAS v0.3.20 compiled with devtoolset-7, even after upgrading it to 7.3.1, but with devtoolset-11 it did compile.  I'll try with that, and let you know what happens.

**Comment by bernstei** [comment]
OK - no change between anaconda's v0.3.18 and my devtoolset-11 compiled v0.3.20, consistent with the fact that the ddot kernel hasn't changed.

I've also now compared double precision "manual" multiplication and summation, quad precision manual multiplication and summation, and OpenBLAS ddot. As someone above suggested, the ddot expression does appear to be more accurate - it's certainly closer to the quad precision `sum(a*b)` result.

Closing this issue, since OpenBLAS is more accurate, not less (although now I'm not sure why using OpenBLAS makes our code converge less well, but that's probably not related to OpenBLAS itself).

**Comment by brada4** [comment]
> [CentOS7](https://github.com/xianyi/OpenBLAS/wiki/Faq#binutils) or use package from fedora EPEL which is compiled without AVX-512 support.

https://github.com/xianyi/OpenBLAS/wiki/Faq#binutils

Please run `make clean` in build tree and compare compiler versions. My trivially installed toolset plainly works, no sleeve tricks on my side

**Comment by martin-frbg** [comment]
Well, OpenBLAS is not that monolithic, could be there is another function you use that actually has lower precision. (One hint could be if convergence varies between cpu generations). Or there is some spot in your production code where it tries to compare floating point values to exact zero (or to each other) without allowing for some suitable epsilon.

**Comment by bernstei** [comment]
@brada4 I don't know why it's not working, but I can assure you that with devtoolset-7 my compilers report the same versions as you posted above, I'm using a fresh git clone + checkout v0.3.20, and it gives the error I reported earlier. I'll post the output. 

@martin-frbg I agree that our code may well be doing things in lower precision someplace else.  The thing I find weird is that it's doing a gradient-based minimization (preconditioned LBFGS), and the failure mode is what we expect when the gradients, which are computed analytically, are not sufficiently accurate, i.e. not consistent with the computed quantity which is being minimized. I'm surprised that _increasing_ the precision in one place by using `ddot` (actually `numpy.dot`, but I believe it's calling `ddot`) makes the gradients and value _less_ consistent.  Of course there's a limit to how accurate they can be due to roundoff, but I find it very surprising that doing two things inaccurately is less well behaved than one inaccurately and one accurately.  It's possible, of course, but just surprising (to me).  I'd expect the overall accuracy (i.e. consistency of the gradient and value) would be the same, because it's dominated by the least accurate (or least numerically stable, anyway) operation.  I guess one possibility is that `numpy.dot` is _not_ calling `ddot`, but rather some other BLAS or LAPACK function, and that function really does have a bug that makes it less accurate in the presence of the newer CPUs (probably avx512).  I'll try to confirm that `np.dot` calls `ddot`, and if not, do a pure OpenBLAS test of whatever it calls.

**Comment by bernstei** [comment]
Here's the output from compiling a fresh v0.3.20 from an `scl enable devtoolset-7 -- $SHELL` shell with the error.
[openblass_err.txt](https://github.com/xianyi/OpenBLAS/files/8353702/openblass_err.txt)

**Comment by brada4** [comment]
Your actions look absolutely correct.
Please `yum reinstall /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/include/immintrin.h`
I have this
`e0fb930cf376411fa9ff58eba8edd4f89976a38c  /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/include/immintrin.h`

There is some improvement in AVX-512 detection in `develop` branch, but for me it works no matter build host CPU or cross-building for same platform :-(

What else comes in mind - do you have CFLAGS or something set before build? Unset them all.

**Comment by brada4** [comment]
devtoolset7 gcc malfunctions in presence of system gcc. use devtoolset 11, i will bisect and up faq version, and sorry for confusion.

**Comment by bernstei** [comment]
> Your actions look absolutely correct. Please `yum reinstall /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/include/immintrin.h` I have this `e0fb930cf376411fa9ff58eba8edd4f89976a38c /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/include/immintrin.h`

Sounds like it isn't the issue, but for what it's worth I have `c211cc29678c0f465f0a19b7985188a0  /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/include/immintrin.h` before and after the yum reinstall, so I'm not sure how that could be different from yours.

**Comment by brada4** [comment]
No /ust/bin/gcc + devtoolset7 - OK
/usr/bin/gcc + devtoolset7  -KO
any + devtoolset8 - OK

**Comment by brada4** [comment]
i reinstalled and insist on my sha1sym ;-) really makes little sense, i trust you did same thing as me...

**Comment by bernstei** [comment]
You didn't say "sha1sum" -   I was using "md5sum".  SHA1 is the same as yours `e0fb930cf376411fa9ff58eba8edd4f89976a38c  /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/include/immintrin.h`.  I'm not sure if that makes it more or less weird.

**Comment by brada4** [comment]
We have same file, no ghosts. But devtoolset-8+ is needed as per my testing.

**Comment by martin-frbg** [comment]
From the time the patch for the gcc problem was posted on the gcc mailing lists (something like two weeks before 7.4 was released), I assume it first appeared in gcc-7.5.0 So if devtoolset-7 is 7.3.1 it is stilll too old.
I have not  looked up if including the cast (from the old PR) would cost anything in terms of precision or performance, but I guess at worst it could be made codintional on `if defined __GNUC_PREREQ and GNUC_PREREQ(7,5) --except there will probably be numerous other reasons to upgrade gcc when using AVX512

**Comment by bernstei** [comment]
I'm happy to switch to devtools-11.  Just would be nice if the minimum (or at least a known working tested) gcc version was documented.

**Comment by brada4** [comment]
I built TARGET=SKYLAKEX with devtoolset-8 `gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)` and updated FAQ accordingly.
Seems there is something that downgrades to AVX2 when devtoolset-7 is used without system gcc, and I cannot giuess dependency.
I am sure you find if documented when you click on documentation links provided to you twice.
