### ISSUE TITLE
Error occurred when Rblas.dll replaced by OpenBLAS-0.3.20-x64 binary version in Win11

### ISSUE THREAD

**Issue by rexdeng** [xianyi/OpenBLAS#3592]
After the replacement, R (4.1.2) starts slower than before and displays the following error message:
Error in .External(list(name = "CppMethod__invoke_notvoid", address = <pointer: (nil)>,  : 
  NULL value passed as symbol address
Error in .External(list(name = "CppMethod__invoke_notvoid", address = <pointer: (nil)>,  : 
  NULL value passed as symbol address
Error in .External(list(name = "CppMethod__invoke_notvoid", address = <pointer: (nil)>,  : 
  NULL value passed as symbol address
Error in .External(list(name = "CppMethod__invoke_notvoid", address = <pointer: (nil)>,  : 
  NULL value passed as symbol address
Error in .External(list(name = "CppMethod__invoke_notvoid", address = <pointer: (nil)>,  : 
  NULL value passed as symbol address
Error in .External(list(name = "CppMethod__invoke_notvoid", address = <pointer: (nil)>,  : 
  NULL value passed as symbol address

On another laptop with Win10 it was successful without any problems.

**Comment by martin-frbg** [comment]
Unfortunately I cannot really help here - the current pre-compiled binaries for Windows are cross-compiled with mingw-w64 on Linux, and I do not have a Win11 system to test. Are you using the exact same build of R on both computers ? (It could be that the R on your Win11 machine was built with a different compiler, or requires a Rblas that was built with specific parameters, e.g. using OpenMP for multithreading. Hard to tell without a symbol name in that error message)

**Comment by brada4** [comment]
Are you sure OpenBLAS causes the problem?
That error is due to data handled by modules in autosaved .RData that causes slow start. you can list() those. Core libs do not load CRAN RCpp...
Best resolution is to list modules in old path (something like $HOME/.R/lib/3.6) and install those in new installation, then restore RData. I dont know exact windows paths, I think it is My Documents\R or so.
