### ISSUE TITLE
cblas_dbf16tod 

### ISSUE THREAD

**Issue by ozgaga6688** [xianyi/OpenBLAS#3596]
can't use this function: cblas_dbf16tod
wrong message is: undefined reference to `cblas_dbf16tod'

in ubuntu20.04

**Comment by martin-frbg** [comment]
The bfloat16 extensions are not compiled in by default, you need to build OpenBLAS with `make BUILD_BFLOAT16=1` to get them.

**Comment by ozgaga6688** [comment]
ok, thank you, it's useful

**Comment by ozgaga6688** [comment]
> The bfloat16 extensions are not compiled in by default, you need to build OpenBLAS with `make BUILD_BFLOAT16=1` to get them.

ok, thank you, it's useful!     But, i don't know how to use this function, do you have the 'instruction manual' of all functions.

**Comment by ozgaga6688** [comment]
> The bfloat16 extensions are not compiled in by default, you need to build OpenBLAS with `make BUILD_BFLOAT16=1` to get them.

I tested `cblas_dbf16tod' in this program-->
int n = 10;                          
bfloat16 *dx;                   
double *dy;                   
dx = (bfloat16 *) malloc(sizeof(bfloat16) * n);
dy = (double *) malloc(sizeof(double) * n);

for(int i=0;i<n;i++){
        dx[i] = (bfloat16)(n-i);
        dy[i] = (n-i);
        printf("%d ", dx[i]);  
}
cblas_dbf16tod(n,dx,1,dy,1);
printf("\n");
for(int i=0;i<n;i++){
        printf("%f ", dy[i]);    
}

result of this program is:
10 9 8 7 6 5 4 3 2 1 
0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
but i think it should be:
10 9 8 7 6 5 4 3 2 1 
10.000000 9.000000 8.000000 7.000000 6.000000 5.000000 4.000000 3.000000 2.000000 1.000000

**Comment by martin-frbg** [comment]
I don´t think you can create a valid bfloat16 just by casting...

**Comment by ozgaga6688** [comment]
> I don´t think you can create a valid bfloat16 just by casting...

so, could you tell me how to use it ( i think i need an example)? 
I can't see this function in "OpenBLAS Extensions" wiki page.

**Comment by martin-frbg** [comment]
Your usage of dbf16tod was correct, only the input was not what you intended - it seems the values were all so small that they were denormal (and mapped to zero in the conversion). BFLOAT16 is not what I usually work with, but with  help from https://stackoverflow.com/questions/55253233/convert-fp32-to-bfloat16-in-c, I can suggest the following addition to your test code (using floats and sbf16tos for simplicity):
```
#include "cblas.h"
#include "stdlib.h"
bfloat16 float2bfloat(float val) {
bfloat16 ret;
#if __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__
    memcpy(&ret, &val, sizeof ret);
#else
    memcpy(&ret, (char*)(&val) + sizeof val - sizeof ret, sizeof ret);
#endif
    return ret;
}
void main(){
int n = 10;
bfloat16 *dx;
float *dy;
dx = (bfloat16 *) malloc(sizeof(bfloat16) * n);
dy = (float *) malloc(sizeof(float) * n);

for(int i=0;i<n;i++){
dx[i] = float2bfloat((float)(n-i));
dy[i] = (n-i);
printf("%d ", dx[i]);
}
cblas_sbf16tos(n,dx,1,dy,1);
printf("\n");
for(int i=0;i<n;i++){
printf("%f ", dy[i]);
}
}

```
