### ISSUE TITLE
vector plus a constant

### ISSUE THREAD

**Issue by ozgaga6688** [xianyi/OpenBLAS#3597]
is there a function which can plus every elements in vector with a constant ?
just like this: [1,2,3,4,5,6](vector) + 10(constant) = [11,12,13,14,15,16](vector)

**Comment by brada4** [comment]
memset other vector with constants and AXPY.

**Comment by martin-frbg** [comment]
Generally you can find the list of supported operations in BLAS at https://www.netlib.org/blas/#_blas_routines (this is the documentation of the reference implementation).

**Comment by ozgaga6688** [comment]
> memset other vector with constants and AXPY.

but memset can only  initialize -1 and 0 with type of int;
i can't use memset to initialize a value in type of double

**Comment by TiborGY** [comment]
> > memset other vector with constants and AXPY.
> 
> but memset can only initialize -1 and 0 with type of int; i can't use memset to initialize a value in type of double

std::fill works for doubles

**Comment by brada4** [comment]
more like encouragement to make a blocking loop like generic/axpy.c ....

**Comment by ozgaga6688** [comment]
> > > memset other vector with constants and AXPY.
> > 
> > 
> > but memset can only initialize -1 and 0 with type of int; i can't use memset to initialize a value in type of double
> 
> std::fill works for doubles

i will use OpenBLAS in C, not in C++

**Comment by brada4** [comment]
You have to write (blocking) loop yourself if you dont want to waste 2nd array of tens
blocking example:
https://github.com/xianyi/OpenBLAS/blob/65a14d4b40a592dcc13953ae7a332990c97e5c59/kernel/x86_64/caxpy.c#L60

i.e the operation is 2...4...8...16 times just adding in place or to result array then a naive end loop.
compiler is very likely to emit better and better instructions if you use sse avx and so on in -m parameters.
You need such loop anyway to populate that waste-array for axpy...
