### ISSUE TITLE
The compiler doesn't support lp64v, can I compile the riscv version with lp64?

### ISSUE THREAD

**Issue by dozhier** [xianyi/OpenBLAS#3606]
The compiler doesn't support lp64v, can I compile the riscv version with lp64?

**Comment by xianyi** [comment]
Hi,
You could try `make TARGET=RISCV64_GENERIC`

**Comment by martin-frbg** [comment]
You may be able to find a better compiler on the t-head website, see https://github.com/xianyi/OpenBLAS/issues/3290#issuecomment-874512182 .

**Comment by xianyi** [comment]
> You may be able to find a better compiler on the t-head website, see [#3290 (comment)](https://github.com/xianyi/OpenBLAS/issues/3290#issuecomment-874512182) .

Please download 1.x version from t-head toolchain. In 2.x version, the toolchain changes the intrinsic api, I am working on it.

**Comment by martin-frbg** [comment]
Just to clarify - I assume the current kernels adhere to draft v0.71 of the intrinsics API, and the more recent t-head compiler has moved to supporting v1.0 . Is that correct? (We might want to add this to the README.txt )

**Comment by xianyi** [comment]
> Just to clarify - I assume the current kernels adhere to draft v0.71 of the intrinsics API, and the more recent t-head compiler has moved to supporting v1.0 . Is that correct? (We might want to add this to the README.txt )

Yes, they changed to 1.0 style.

**Comment by martin-frbg** [comment]
totally forgot that this detail is already mentioned in the readme, sorry...
