### ISSUE TITLE
Several symbols missing in `libopenblas.a` from `OpenBLAS-0.3.20-x64.zip`

### ISSUE THREAD

**Issue by hzhangxyz** [xianyi/OpenBLAS#3608]
I download the prebuild file from [release page](https://github.com/xianyi/OpenBLAS/releases/download/v0.3.20/OpenBLAS-0.3.20-x64.zip). But there are several symbols missing in `lib/libopenblas.a`. The missing symbols list is followed:
```
__emutls_get_address
__powidf2
__powisf2
_gfortran_concat_string
_gfortran_etime
```
The problem could occur if someone wants to statically link openblas with target `x86_64-pc-windows-msvc` instead of `x86_64-pc-windows-gnu`.

BTW, those symbols are included in `bin/libopenblas.dll`, why not to include them in `lib/libopenblas.a`?

**Comment by martin-frbg** [comment]
The .dll is actually created _from_ the .a , but these symbols are part of the (mingw) gcc/gfortran runtime libraries, not OpenBLAS itself.

**Comment by martin-frbg** [comment]
Not sure if it is even advisable/possible to statically link `*-pc-windows-gnu` objects with `*-pc-windows-msvc` ones (?)

**Comment by hzhangxyz** [comment]
> Not sure if it is even advisable/possible to statically link `*-pc-windows-gnu` objects with `*-pc-windows-msvc` ones (?)

I do not know whether it is proper, but it is possible to link them with clang in windows.

**Comment by brada4** [comment]
those should be provided by libgcc , 2x libm, 2x libgfortran static libraries. While missing and unfair, on Windows it is best to link dynamically so that you can use MKL or CUDA if environment suggests.
EDIT: those are LGPL, so they need to be in separate file from commercial software. While comfortable to have monoliths, be careful.

**Comment by carlkl** [comment]
Those symbols are not LGPL'd AFAIK. `libquadmath` (which is often linked into as well due to the `quadmath_snprintf` symbol is LGPL'd.

**Comment by hzhangxyz** [comment]
> those should be provided by libgcc , 2x libm, 2x libgfortran static libraries. While missing and unfair, on Windows it is best to link dynamically so that you can use MKL or CUDA if environment suggests. EDIT: those are LGPL, so they need to be in separate file from commercial software. While comfortable to have monoliths, be careful.

So, not only libopenblas.a does not contain those symbol, but also libopenblas.dll should not contain?

**Comment by martin-frbg** [comment]
Where do you get that idea from ? If you are using/distributing anything not your own in commercial software, it is your obligation to ensure that all third-party licenses are complied with. (And you'd probably want to compile everything from source using one particular compiler suite for all components anyway.)
And as far as the static libopenblas.a is concerned, it contains only the object modules of OpenBLAS itself. As far as I know, the
only way to add the gcc/gfortran symbols that you are missing for your hypothetical case would be to extract them from libgcc and/or libgfortran. Besides adding a manual step that would benefit few users, I suspect having these symbols in the .a might
actually create complications such as duplicate or conflicting symbols when linking.
The precompiled binaries are provided for convenience, if they do not suite your individual needs you are invited to compile OpenBLAS yourself.

**Comment by brada4** [comment]
* Just that OP discovered that those symbols are needed but .a files missing. Probably best is to acquire mingw or so and do own build where you have all the static files around.
* Why would anyone make static binaries nowadays, by large dynamic linking time is negligible nowadays. i.e dll is OK.

**Comment by carlkl** [comment]
@hzhangxyz, you told us you want to use `x86_64-pc-windows-msvc` so I guess you are using clang-cl. If you are using clang-cl you will using the MSVC `link.exe` as the linker. In this case you have to link dynamically against the libopenblas.dll. First create the MSVC compatible import library files: `libopenblas.lib` and `libopenblas.exp`. Please read the section **Generate import library (before 0.2.10 version)** in the Wiki page https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-in-Microsoft-Visual-Studio.

Linking static import file libraries generated with GNU Binutils together MSVC object files with the MSVC linker as you requested is something that should be avoided under all circumstances.

**Comment by hzhangxyz** [comment]
> * Just that OP discovered that those symbols are needed but .a files missing. Probably best is to acquire mingw or so and do own build where you have all the static files around.
> * Why would anyone make static binaries nowadays, by large dynamic linking time is negligible nowadays. i.e dll is OK.

Yeah, I am using DLL now. I just tried to statically link by the way and find some symbol missing, so I post this issue.

I just think it should work fine if the released static prebuilt binary provided.

**Comment by hzhangxyz** [comment]
@carlkl So why not build prebuilt binary with msvc abi? then in both msvc and mingw environment people could use it easily?

**Comment by hzhangxyz** [comment]
> Where do you get that idea from ? If you are using/distributing anything not your own in commercial software, it is your obligation to ensure that all third-party licenses are complied with. (And you'd probably want to compile everything from source using one particular compiler suite for all components anyway.) And as far as the static libopenblas.a is concerned, it contains only the object modules of OpenBLAS itself. As far as I know, the only way to add the gcc/gfortran symbols that you are missing for your hypothetical case would be to extract them from libgcc and/or libgfortran. Besides adding a manual step that would benefit few users, I suspect having these symbols in the .a might actually create complications such as duplicate or conflicting symbols when linking. The precompiled binaries are provided for convenience, if they do not suite your individual needs you are invited to compile OpenBLAS yourself.

Well, I am using openblas in a gpl project so it is ok. I thought brada4 means openblas under bsd should not contain those symbol under lgpl in single file.

And I am persuaded that static library should not contain those symbol to avoid symbol conflicting. But i still think building binary with msvc abi may solve all problem above.

**Comment by martin-frbg** [comment]
That would probably mean an _additional_ binary package built with msvc abi (else one would get the same problem in reverse when working in a mingw environment). Maybe someday when we have some sort of infrastructure set up for autobuilding packages with each release. Maybe the [vcpkg](https://github.com/microsoft/vcpkg) package already fits the bill ?
