### ISSUE TITLE
DYNAMIC_ARCH, unidentified AMDs and AVX

### ISSUE THREAD

**Issue by MJRutter** [xianyi/OpenBLAS#3620]
As far as I can tell from driver/others/dynamic.c an unidentified AMD CPU is not regarded as even supporting AVX.

As an example, OpenBLAS as provided with Ubuntu 20.04LTS gives just 20GFLOPS on Linpack10K on a single core of a Zen3 with dynamic detection. If OPENBLAS_CORETYPE=Haswell or =Zen is set explicitly, this improves to a little over 53GFLOPS. If OPENBLAS_CORETYPE=Barcelona is set, 20GFLOPS is again achieved. Ubuntu 20.04 predates the Zen3 CPUs.

Whilst the else if (exfamily == 10)  clause fixed this for Zen3 a couple of years ago, it is still not fixed for any new unidentified exfamily, so unexpected exfamily values end up be treated as Barcelona (which lacks AVX). (c. line 866 of dynamic.c). This may be an issue for Zen4 when that is released, for instance.

I suggest that unidentified AMD CPUs should be checked for the presence of AVX, and treated as Zen (or Haswell) if found. Or is the test for AVX unsafe on older AMDs?

**Comment by martin-frbg** [comment]
I do not have any old AMD hardware to test this with, so I only implemented the feature-based fallback for Intel so far (#3485)- my guess is that the fallback to Barcelona is a holdover from original GotoBLAS. Still adding new cpuid(s) in time for a release would seem to be the more important step with AMD cpus, at least as long as they do not mimick Intel's proliferation of model numbers. (By all accounts Zen4 is still going to be exfamily 10, but with added support for AVX512 including AVX512_BF16, so initial support will probably just map it to Intel Cooperlake. I have a small backlog of things for which I have not done PRs yet).

**Comment by MJRutter** [comment]
Adding new cpuid(s) promptly would be good, but I don't think it entirely solves the issue. Thanks to long term support releases, such as Ubuntu LTS, there will be many sites running quite old versions of OpenBLAS, perhaps up to five years old or more. One cannot anticipate the next five years of new CPUs from Intel or AMD, and the performance hit of a undetected CPU is quite high. Of course accurate, precise, detection is best, but I think the fallback position could usefully be improved for those whose hardware is newer than their software.

I have just typed "apt-get update; apt-get install libopenblas0" and my Ubuntu 20.04LTS machine assures me that I am completely up to date with 0.3.8+ds-1ubuntu0.20.04.1. Not sufficiently up to date that a Zen3 machine which has just joined the fleet I look after is treated well though. If I don't explicitly set OPENBLAS_CORETYPE its performance is only about 10% better than an ancient Athlon II, and poorer than an Intel Sandy Bridge. Ubuntu 20.04LTS will be supported until April 2025, and, if one waits for the .1 releases before updating, it is the most recent LTS with a .1 release available.

**Comment by martin-frbg** [comment]
Yes but that is mainly a problem for distributions (or users) to solve I think - with an aging "LTS" or "Enterprise" distro that only provides security updates, not only will you miss out on new hardware support but also on quite a serious number of bug fixes. Looking back five years to the spring of 2017, OpenBLAS was just barely beginning to become thread safe. (An aspect that
curiously did not appear to have major consequences with the earlier hardware and compilers)

**Comment by brada4** [comment]
Please check here:
https://github.com/xianyi/OpenBLAS/wiki/Faq#debianlts
If you dont want to build yourself set OPENBLAS_CORETYPE=ZEN permanently in login scripts.

**Comment by brada4** [comment]
PS Ubuntu 22.04 LTS is out, contains OpenBLAS 0.3.20, completely supporting all CPUs currently in market
If you want to build your own private DEB for 20.04LTS , you need to patch to latest released driver/others/dynamic.c , FreeBSD had that for 5 years or so, or try to build package from new release like Ubuntu HWE kernels do.

**Comment by brada4** [comment]
@MJRutter you must approach ubuntu for their packaging. It is not granted that avx isa presence makes it best performing.

**Comment by MJRutter** [comment]
Unfortunately Ubuntu's policy on providing security updates, but not feature updates, is pretty firm.

I agree that the presence of AVX does not guarantee that it is faster than SSE2, although the reduced pressure on instruction decoding tends to mean that it is, even when the execution units are only 128 bits wide (the original Zen). I am quite happy with OpenBLAS trying to detect individual CPU types, rather than just doing something generic based on the presence of AVX, AVX512, etc.

However, I still believe that when an unknown AMD CPU is detected it would be better to use an AVX path if that CPU supports AVX. "Unknown" presumably means "new", and I would be surprised if any AMD (let alone a new one) passed the CPUID test for AVX but did not actually support it, and I would be surprised if any new, AVX-supporting, AMD CPU ran faster on non-AVX code than on AVX code. So I don't see much downside. The upside could be a performance gain of over a factor of two on whatever the next generation of AMD CPU not to be detected properly is.

Intel's MKL has a very bad reputation for ignoring Intel's recommendations for detecting AVX and producing poor performance on both AMD and new Intel CPUs (although more recent MKL versions have improved in this respect). Some allege that Intel has an incentive to choose suboptimal paths for AMD CPUs. OpenBLAS does not, so it is disappointing when it does.

Yes, I will address my Zen3 problems, but there are a lot of scientists who just would not realise why their Zen3 system is slow, or that it could be fixed easily. I doubt we can solve this for U20.04, but we can reduce the chances of it happening in the future.

**Comment by brada4** [comment]
it is described in FAQ for quite some time, cannot do better.
