### ISSUE TITLE
Why is the stdio.h missing in getarch.c

### ISSUE THREAD

**Issue by dozhier** [xianyi/OpenBLAS#3621]
I am trying to compile OpenBlas with BitBake and the error is like this
getarch.c:80:10: fatal error: stdio.h: No such file or directory
|    80 | #include <stdio.h>
|       |          ^~~~~~~~~
| compilation terminated.
(but when i just make openblas,it's ok)

**Comment by martin-frbg** [comment]
There is something wrong in your setup of BitBake that makes it leave out the standard include file paths of your system (normally /usr/include on Unix-like systems, or the sysroot of your compiler toolchain if you are cross-compiling)

**Comment by brada4** [comment]
You can run compilers inside qemu images provided for target CPU, usermode library has nothing to do with device configuration aka BSP. 
Toolset init sets CC variable, so you need to run something like `make HOSTCC=gcc CC=$CC FC=$FC` to cross-build. There could be some gotchas as somewhere in build process those env variables may override `make` parameter.
