### ISSUE TITLE
Consider using int64_t instead of long on macOS 12?

### ISSUE THREAD

**Issue by leavelet** [xianyi/OpenBLAS#3627]
I tried to compile develop branch on my mac, my system version is macOS 12.3 with m1 pro chip, my compiler is clang13

I encountered the problem below. And I tried to use int64_t instead of long to typedef BLASLONG, and it works on my machine.

I guess this may be of some help to you :)

```bash

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.1.6/include/arm_sve.h:15652:10: note: candidate function
svbool_t svwhilelt_b32(int64_t, int64_t);
         ^
../kernel/arm64/trmm_lncopy_sve_v1.c:130:14: error: call to 'svwhilelt_b32' is ambiguous
        pn = svwhilelt_b32(js, n);
             ^~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.1.6/include/arm_sve.h:15628:10: note: candidate function
svbool_t svwhilelt_b32(uint32_t, uint32_t);
         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.1.6/include/arm_sve.h:15636:10: note: candidate function
svbool_t svwhilelt_b32(uint64_t, uint64_t);
         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.1.6/include/arm_sve.h:15644:10: note: candidate function
svbool_t svwhilelt_b32(int32_t, int32_t);
         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.1.6/include/arm_sve.h:15652:10: note: candidate function
svbool_t svwhilelt_b32(int64_t, int64_t);

```

**Comment by leavelet** [comment]
but then i found there are some problems though, like:

```bash
Note: The following floating-point exceptions are signalling: IEEE_DIVIDE_BY_ZERO
OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 ./cblat1

Program received signal SIGILL: Illegal instruction.

Backtrace for this error:
#0  0x101095147
#1  0x1010941db
#2  0x1841214c3
/bin/sh: line 1: 27333 Illegal instruction: 4  OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 ./sblat3 < ./sblat3.dat
make[1]: *** [level3] Error 132
```

**Comment by martin-frbg** [comment]
Did you specify a custom cpu TARGET in the compilation ? From what you posted, the main issue appears to be that you built for a cpu with SVE (vector) instruction support, and as far as I know the M1 "Vortex" family lacks that.

**Comment by leavelet** [comment]
It works!

I used the command, as I assumed A64FX has something to do with "apple chip". It's a mistake though.

```bash
make TARGET=A64FX
```
Thank you for reply!

**Comment by martin-frbg** [comment]
an a64fx mac would be nice I guess (Fujitsu supercomputer core).
Normally the build system should figure out the cpu model automatically when you just type `make`,  does your M1pro have a cpuid that is not yet recognized ?

**Comment by leavelet** [comment]
How can I check my cpuid?

**Comment by martin-frbg** [comment]
`sysctl -a hw machdep.cpu` and look at the hw.cpufamily number. We currently know 131287967 and 458787763 for first and second generation M1.

**Comment by leavelet** [comment]
It's 458787763. Does this have something to do with my operation of changing BLASLONG to int64_t?

**Comment by martin-frbg** [comment]
I don't think so - the "value" variable in cpuid_arm64.c is declared as int32_t (which is big enough for the 9-digit number returned by the sysctl). `make` alone should have been sufficient to get a libopenblas built for your M1

**Comment by martin-frbg** [comment]
Ah sorry, that is actually a bug in 0.3.20 that I fixed a while ago - one of the commits that went into that release had added a few new cpu types but added them __in the middle of the existing list__ which threw off all the list indices behind that point, including the one for Vortex

**Comment by brada4** [comment]
sysctl returns 32bit integers
