### ISSUE TITLE
Building OpenBLAS 0.3.20 w/ Spack using OneAPI 2022.1.0: DT_NEEDED missing libifcore

### ISSUE THREAD

**Issue by eugeneswalker** [xianyi/OpenBLAS#3634]
When I build `OpenBLAS@0.3.20 %oneapi@2022.1.0` with Spack, `libopenblas.so` doesn't include `libifcore` in the DT_NEEDED:

```
$> objdump -x $(spack location -i openblas)/lib/libopenblas.so | grep -i needed
  NEEDED               libm.so.6
  NEEDED               libpthread.so.0
  NEEDED               libsvml.so
  NEEDED               libirng.so
  NEEDED               libintlc.so.5
  NEEDED               libdl.so.2
  NEEDED               libiomp5.so
  NEEDED               libc.so.6
  NEEDED               ld-linux-x86-64.so.2
```

This creates issues downstream when trying to build some other packages that rely on OpenBLAS:
```
$> spack install plasma...
...
==> Installing plasma-21.8.29-y5otmtsxindyp3tuguijpg7wmypjyl7q
==> Fetching https://mirror.spack.io/_source-cache/archive/e0/e0bb4d9143c8540f9f46cbccac9ed0cbea12500a864e6954fce2fe94ea057a10.tar.gz
==> No patches needed for plasma
==> plasma: Executing phase: 'cmake'
==> plasma: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'
...
  >> 6547    /usr/bin/ld: /spack/opt/spack/linux-ubuntu20.04-x86_64/oneapi-2022.1.0/openblas-0.3.20-q6ovcjsiw3mkzigitn7q4vvidcrki424/lib/libopen
             blas.so: undefined reference to `for_cpystr'
  >> 6548    /usr/bin/ld: /spack/opt/spack/linux-ubuntu20.04-x86_64/oneapi-2022.1.0/openblas-0.3.20-q6ovcjsiw3mkzigitn7q4vvidcrki424/lib/libopen
             blas.so: undefined reference to `for_concat'
  >> 6549    /usr/bin/ld: /spack/opt/spack/linux-ubuntu20.04-x86_64/oneapi-2022.1.0/openblas-0.3.20-q6ovcjsiw3mkzigitn7q4vvidcrki424/lib/libopen
             blas.so: undefined reference to `for_cpstr'
  >> 6550    clang: error: linker command failed with exit code 1 (use -v to see invocation)
  >> 6551    make[2]: *** [CMakeFiles/plasmatest.dir/build.make:3147: plasmatest] Error 1
...
```

You can see the linker can't find definition for symbols:
* `for_cpstr`
* `for_concat`
* `for_cpystr`

These are defined in the `libifcore.so.5` bundled with OneAPI:
```
$> nm -D /opt/intel/oneapi/compiler/2022.1.0/linux/compiler/lib/intel64_lin/libifcore.so.5 | grep for_cpstr
00000000000c1b60 T for_cpstr

$> nm -D /opt/intel/oneapi/compiler/2022.1.0/linux/compiler/lib/intel64_lin/libifcore.so.5 | grep for_cpystr
00000000000c1ed0 T for_cpystr

$> nm -D /opt/intel/oneapi/compiler/2022.1.0/linux/compiler/lib/intel64_lin/libifcore.so.5 | grep for_concat
00000000000c1ce0 T for_concat
```

I've not encountered this type of issue before so please forgive me if this isn't an issue with the OpenBLAS build. Perhaps it is an issue with the OneAPI compiler, I don't know. I can manually patch `libopenblas.so` using `patchelf` so that `libifcore.so.5` is listed as needed -- this resolves the undefined symbol problem with downstream packages that rely on OpenBLAS.

What do you think?

@wspear

**Comment by martin-frbg** [comment]
Not sure if this is an issue with OpenBLAS - we obtain the list of libraries to link to by feeding a small test program to the compiler and parsing the verbose output from the compiler and linker. So there is nothing expressly removing libifcore anywhere in the build system, but possibly the oneAPI compiler has become so modularized that the test program would actually need to contain a string concatenation or copy operation to make sure that libifcore features in the link list.
Alternatively, the error you are seeing comes about as your "plasma" code appears to be using `ld` rather than `ifort` for the link step, so any implicit "knowledge" the latter has about standard link requirements of ifort code is unavailable. (And I notice you seem to be using clang rather than oneAPI here, which may lead to your code referencing two competing OpenMP runtimes)

**Comment by eugeneswalker** [comment]
> Alternatively, the error you are seeing comes about as your "plasma" code appears to be using `ld` rather than `ifort` for the link step, so any implicit "knowledge" the latter has about standard link requirements of ifort code is unavailable. (And I notice you seem to be using clang rather than oneAPI here, which may lead to your code referencing two competing OpenMP runtimes)

The same undefined symbol error I see with `plasma`, I also see with:
* `mfem`
* `superlu-dist` 
* `py-scipy`

I am using the `icx/icpx/ifx` compilers -- aren't those based on clang?

**Comment by martin-frbg** [comment]
I see now we've been there before with #1956 , but this was supposedly fixed years ago by ensuring that the final linking of libopenblas.so is done with the Fortran compiler ( in exports/Makefile) if it is Intel.

**Comment by martin-frbg** [comment]
Oh - `icx/icpx/ifx` you say ?  Chances are that the f_check script does not recognize `ifx` yet so is not setting F_COMPILER=INTEL in Makefile.conf

**Comment by eugeneswalker** [comment]
> Oh - `icx/icpx/ifx` you say ? Chances are that the f_check script does not recognize `ifx` yet so is not setting F_COMPILER=INTEL in Makefile.conf

I bet that is it! It was that past issue that got me on this track in the first place, and yes, I see that is the older intel and now we have the newer ifx as well! Thank you for your help!

We would need to patch the f_check script then?

**Comment by martin-frbg** [comment]
Yes, something like this  (remove the .txt extension that github insists on):
[f_check.txt](https://github.com/xianyi/OpenBLAS/files/8773168/f_check.txt)
not fully tested as I need to update my oneAPI installation - with the 2021.2.0 release it is running into what looks like an internal script error where invalid arguments like "+avx2" get passed to `xfortcom`

**Comment by eugeneswalker** [comment]
> Yes, something like this (remove the .txt extension that github insists on): [f_check.txt](https://github.com/xianyi/OpenBLAS/files/8773168/f_check.txt) not fully tested as I need to update my oneAPI installation - with the 2021.2.0 release it is running into what looks like an internal script error where invalid arguments like "+avx2" get passed to `xfortcom`

This resolves the issue!
