### ISSUE TITLE
Model number FMA4 check can cause issues on some virtualized platforms

### ISSUE THREAD

**Issue by lnicola** [xianyi/OpenBLAS#3638]
Unfortunately I don't have the `/proc/cpuinfo` output any more, but I had a VM where OpenBLAS crashed because it picked the Piledriver code paths on a `AMD Opteron 63xx class` CPU that didn't support FMA4. The fine-grained check (as done by https://gist.github.com/rindeal/81198b1cf8f55c356743#file-cpuid-dump2-c) gave correct results (no FMA4 support).

Of course, `OPENBLAS_CORETYPE` works, so feel free to close this if you don't think it's worth changing the code to do feature detection. I'm still filing this in case anyone else runs into the same issue.

**Comment by martin-frbg** [comment]
Not sure what to make of this - if your VM reported the CPUID of an existing AMD processor that definitely has FMA4,  but failed to provide the actual FMA4 support, then it looks more like a VM configuration error to me.

**Comment by lnicola** [comment]
Agreed, but the "proper" way to check for FMA4 is by [feature detection](https://en.wikipedia.org/wiki/CPUID#EAX=80000001h:_Extended_Processor_Info_and_Feature_Bits).

It's fine if you think this is out of scope for OpenBLAS, though.

**Comment by brada4** [comment]
KVM host-model on a piledriver APU yields Opteron_G5 and same CPUID name as you and the FMA4 is working inside VM, kernel ubuntu 20.04
If you want to wipe CPUID bit from the guest you can use
`<feature policy='disable' name='fma4'/>`
via `virsh edit` as described in:
https://libvirt.org/formatdomain.html#cpu-model-and-topology

**Comment by lnicola** [comment]
`/proc/cpuinfo` from one of those VMs:

```
processor : 0
vendor_id : AuthenticAMD
cpu family : 21
model : 2
model name : AMD Opteron 63xx class CPU
stepping : 0
microcode : 0x1000065
cpu MHz : 2499.760
cache size : 512 KB
physical id : 0
siblings : 1
core id : 0
cpu cores : 1
apicid : 0
initial apicid : 0
fpu : yes
fpu_exception : yes
cpuid level : 13
wp : yes
flags : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx mmxext fxsr_opt pdpe1gb lm art rep_good nopl extd_apicid eagerfpu pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw retpoline_amd ssbd ibrs ibpb vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 arat spec_ctrl
bogomips : 4999.52
TLB size : 1024 4K pages
clflush size : 64
cache_alignment : 64
address sizes : 40 bits physical, 48 bits virtual
power management:
```

**Comment by martin-frbg** [comment]
Thanks. Interesting to see it has FMA4 missing from flags, but at the same time advertises AVX2 - quite the fantasy machine to sport an AMD Piledriver ID. I wonder what the underlying hardware and hypervisor is, but so far this still looks like a (rare?) misconfiguration to me.

**Comment by lnicola** [comment]
I got confirmation that these are indeed EPYC CPUs. I don't know any details about the hypervisor, but `dmidecode -t 3 ` reports QEMU.

**Comment by brada4** [comment]
@martin-frbg it is qemu with KVM, I suspect outdated.

Please check that your libvirt is released after your CPU.
It defaults to piledriver aka Opteron_G5 via host-model parameter whose presence which means it is at least 2020 or later but still XMLs in /usr/share/libvirt/cpuwhatever are out of date.

You can try host-passthrough, you get directly all ISA-s from the host CPU minus physical CSR-s

Sad story between paragraphs here - i,e FMA4 is a child of 3dnow:
https://en.wikipedia.org/wiki/FMA_instruction_set#FMA4_instruction_set

You can force to pre-FMA4 Opteron_G3, no AVX1 then.

PS I got similar on RHEL7 with skylake-x SoC that came without AVX-512 and VMs were crashing with sigill-s in kernel unless one of those hackish actions taken.

**Comment by lnicola** [comment]
Just to be clear, I don't control the host system and already reported this to those who do, so it will probably be fixed. But I still think it's an OpenBLAS bug, though a minor one.

**Comment by brada4** [comment]
This is not OpenBLAS bug, it is QEMU not supporting CPU, and as a result announcing inside VM instructions that do not work on outer CPU.

You can try OPENBLAS_CORETYPE=ZEN, but ultimately your admin needs to get rid of FMA4 in CPUID via methods I described, in best case exposing authentic ZEN CPU in VM

Rest identical, in authentic environment one gets this.
```
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm rep_good nopl cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw xop fma4 tbm perfctr_core ssbd vmmcall tsc_adjust bmi1 virt_ssbd arat arch_capabilities
bugs		: fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass
address sizes	: 42 bits physical, 48 bits virtual
```

**Comment by brada4** [comment]
In /usr/share/libvirt/cpuid_map I have these that may seem relevant, I suspect you(r admin) dont.
```
-rw-r--r--. 1 root root  1961 Jun  1 10:28 x86_Dhyana.xml
-rw-r--r--. 1 root root  2048 Jun  1 10:28 x86_EPYC-IBPB.xml
-rw-r--r--. 1 root root  2549 Jun  1 10:28 x86_EPYC-Milan.xml
-rw-r--r--. 1 root root  2289 Jun  1 10:28 x86_EPYC-Rome.xml
-rw-r--r--. 1 root root  2016 Jun  1 10:28 x86_EPYC.xml
```

**Comment by lnicola** [comment]
No, that's what I'm trying to say. CPUID reports that FMA4 is unsupported, but OpenBLAS sees a Piledriver CPU (or similar) and assumes FMA4 works,. without checking.

Setting the target manually or fixing the hypervisor config solves the problem, but OpenBLAS is not as robust as it could be.

**Comment by brada4** [comment]
Workaround would be pessimal and just masks underlying misconfiguration. Really make it ZEN generation IDs and everything will shine.
