### ISSUE TITLE
libopenvlas-dev includes dgetri in the .a, but there is no prototype in f77blas.h

### ISSUE THREAD

**Issue by albert-mathews** [xianyi/OpenBLAS#3639]
[f77blas.txt](https://github.com/xianyi/OpenBLAS/files/8792428/f77blas.txt)
thats the file we got from `apt install -y libopenblas-dev`

no sign of dgetri declaration in f77blas.h...but, a colleague noticed that if we write the declaration ourselves like this in some test .c file:
```
int
dgetri_(
  blasint *, // N
  double *,  // A
  blasint *, // LDA
  blasint *, // IPIV
  double *,  // WORK
  blasint *,  // LWORK
  blasint *  // info
);
```
then, in the main() function of that test file we can do this:
`dgetri_(&nn,AA,&lda,piv,WORK,&nn,&INFO);`

so somehow it seems we got a version of openblas which has the dgetri function, but the declaration doesn't appear in any of the header files we got with the install. 

anyone know what's going on here?

**Comment by martin-frbg** [comment]
DGETRI is a LAPACK function, you should find its prototype in lapack.h

**Comment by albert-mathews** [comment]
@martin-frbg , there was no lapack.h with our installation. What do we need to do to have lapack.h placed in /usr/include/x86_64-linux-gnu or /usr/include/x86_64-linux-gnu\openblas-pthread during openblas installation? 

I was able to find lapacke.h from the web, but that has different declarations. 
For what's its worth, dgetrf is also a LAPACK function, but a declaration for it appears in f77blas.h.

**Comment by martin-frbg** [comment]
dgetrf is in OpenBLAS' f77blas.h because OpenBLAS reimplements it (overriding the non-optimized version from the "netlib" reference implementation). Possibly your distribution build of libopenblas-dev is a bit old and contains lapacke.h but not lapack.h - the latter was split out from the former some time ago, what you found on the web is probably the newer lapacke.h that only defines LAPACKE_dgetri with the matrix layout flag as first argument and no WORK array.
You can grab lapack.h from the source package (or just download that file from lapack-netlib/LAPACKE/include on the "Code" tab of the github project page for OpenBLAS

**Comment by albert-mathews** [comment]
thanks @martin-frbg for your help sorting this out. Our installation did not have lapacke.h either, at least #include <lapacke.h> failed until I installed lapacke. I've tried removing/purging openblas, and re-installing but I'm not seeing lapack.h. Could you provide specific instructions as to how I can install correctly?

**Comment by martin-frbg** [comment]
Well then I guess your distribution broke up the OpenBLAS installation into separate sub-packages. Now that you have a lapacke.h, are you certain that it does not contain the DGETRI prototype ? Like I mentioned, older LAPACKE (and by extension, older OpenBLAS) had only lapacke.h with both LAPACKE_dgetri and dgetri_ (or possibly LAPACK_dgetri) and no separate lapack.h yet . Anyway the definition in lapack.h (or lapacke.h) is not going to be different from what your colleague wrote himself, so I guess you might as well go with that.

**Comment by albert-mathews** [comment]
I'm using WSL/ubuntu, so maybe that has something to do with it? anyway, I fully reset WSL, apt update , apt upgrade, and installed libopenblas-dev, still no sign of lapack.h nor lapacke.h from openBlas install. Maybe I'm not looking for them in the right places? Any help is appreciated. 
Yeah, we could use the manually written declaration, but that means we need to maintain a company copy of these to share with all developers, I think it's better if we can get the installation correct.

**Comment by martin-frbg** [comment]
What about the lapacke.h from the lapacke package ? (That package will either be an Ubuntu split-off from their OpenBLAS build, or a split-off from the equivalent version Reference-LAPACK - I have no influence or insight into how they decide to repackage things).

**Comment by brada4** [comment]
For C you sort of need to use cblas.h and lapacke.h, which are provided as separate packages (add -dev), those wrap fortran API-s which are managed by update-alternatives.
You may try to convince Debian to make alternating cblas and lapacke libs to call openblas (or atlas - another alternative) directly, it will take some time to get further downstream to Ubuntu. Probably growing relevance of ML and NN can serve as one of weights on your side.
Good luck if you decide to try ;-)

**Comment by albert-mathews** [comment]
> For C you sort of need to use cblas.h and lapacke.h, which are provided as separate packages (add -dev), those wrap fortran API-s which are managed by update-alternatives. You may try to convince Debian to make alternating cblas and lapacke libs to call openblas (or atlas - another alternative) directly, it will take some time to get further downstream to Ubuntu. Probably growing relevance of ML and NN can serve as one of weights on your side. Good luck if you decide to try ;-)

thanks, this is good confirmation that our choice to go with lapacke in the end (liblapacke-dev). Why is cblas.h recommended over openBlas for C? or did I mis-understand what you were suggesting. We chose openBlas because of its multi-platform support, is this feature shared by cblas.h?

**Comment by brada4** [comment]
BLAS and LAPACK are Fortran APIs, while you can make synthetic headers to call any library from C, the C bindings for BLAs and LAPACK are cblas.h and lapacke.h, i.e not dgetrf_ but LAPACKE_dgetrf , not SGEMM_ but cblas_sgemm. 

For CBLAS - OpenBLAS exposes cblas interfaces directly, you need wrapper only for the header (but check `nm` against packaged library)

**Comment by albert-mathews** [comment]
thank you @martin-frbg and @brada4 for your patience and help. i think we can close this issue.
