### ISSUE TITLE
openblas on riscv64 platform

### ISSUE THREAD

**Issue by kush930** [xianyi/OpenBLAS#3646]
Hi all , 

**I clone openblas from link-https://github.com/xianyi/OpenBLAS**
  **I am using gcc-10.2 and glibc-2.32** 
 
**I want to build openblas-0.3.20 on riscv platform, i am using below command and facing issue:--**

**root@kush-Linux-1:/opt/kaldi/tools# make -C OpenBLAS ONLY_CBLAS=1 ${ARCH=riscv64} HOSTCC=gcc USE_LOCKING=1 USE_THREAD=0 all**

make: Entering directory '/opt/kaldi/tools/OpenBLAS'
**getarch_2nd.c: In function 'main':
getarch_2nd.c:22:35: error: 'SGEMM_DEFAULT_UNROLL_M' undeclared (first use in this function); did you mean 'SBGEMM_DEFAULT_UNROLL_M'?

22 | printf("SGEMM_UNROLL_M=%d\n", SGEMM_DEFAULT_UNROLL_M);
| ^~~~~~~~~~~~~~~~~~~~~~
| SBGEMM_DEFAULT_UNROLL_M
getarch_2nd.c:22:35: note: each undeclared identifier is reported only once for each function it appears in
getarch_2nd.c:23:35: error: 'SGEMM_DEFAULT_UNROLL_N' undeclared (first use in this function); did you mean 'SBGEMM_DEFAULT_UNROLL_N'?

23 | printf("SGEMM_UNROLL_N=%d\n", SGEMM_DEFAULT_UNROLL_N);
| ^~~~~~~~~~~~~~~~~~~~~~
| SBGEMM_DEFAULT_UNROLL_N
getarch_2nd.c:24:35: error: 'DGEMM_DEFAULT_UNROLL_M' undeclared (first use in this function); did you mean 'XGEMM_DEFAULT_UNROLL_M'?

24 | printf("DGEMM_UNROLL_M=%d\n", DGEMM_DEFAULT_UNROLL_M);
| ^~~~~~~~~~~~~~~~~~~~~~
| XGEMM_DEFAULT_UNROLL_M
getarch_2nd.c:25:35: error: 'DGEMM_DEFAULT_UNROLL_N' undeclared (first use in this function); did you mean 'XGEMM_DEFAULT_UNROLL_N'?

25 | printf("DGEMM_UNROLL_N=%d\n", DGEMM_DEFAULT_UNROLL_N);
| ^~~~~~~~~~~~~~~~~~~~~~
| XGEMM_DEFAULT_UNROLL_N
getarch_2nd.c:29:35: error: 'CGEMM_DEFAULT_UNROLL_M' undeclared (first use in this function); did you mean 'XGEMM_DEFAULT_UNROLL_M'?

29 | printf("CGEMM_UNROLL_M=%d\n", CGEMM_DEFAULT_UNROLL_M);
| ^~~~~~~~~~~~~~~~~~~~~~
| XGEMM_DEFAULT_UNROLL_M
getarch_2nd.c:30:35: error: 'CGEMM_DEFAULT_UNROLL_N' undeclared (first use in this function); did you mean 'XGEMM_DEFAULT_UNROLL_N'?

30 | printf("CGEMM_UNROLL_N=%d\n", CGEMM_DEFAULT_UNROLL_N);
| ^~~~~~~~~~~~~~~~~~~~~~
| XGEMM_DEFAULT_UNROLL_N
getarch_2nd.c:31:35: error: 'ZGEMM_DEFAULT_UNROLL_M' undeclared (first use in this function); did you mean 'XGEMM_DEFAULT_UNROLL_M'?

31 | printf("ZGEMM_UNROLL_M=%d\n", ZGEMM_DEFAULT_UNROLL_M);
| ^~~~~~~~~~~~~~~~~~~~~~
| XGEMM_DEFAULT_UNROLL_M
getarch_2nd.c:32:35: error: 'ZGEMM_DEFAULT_UNROLL_N' undeclared (first use in this function); did you mean 'XGEMM_DEFAULT_UNROLL_N'?

32 | printf("ZGEMM_UNROLL_N=%d\n", ZGEMM_DEFAULT_UNROLL_N);
| ^~~~~~~~~~~~~~~~~~~~~~
| XGEMM_DEFAULT_UNROLL_N
make: *** [Makefile.prebuild:78: getarch_2nd] Error 1

make: *** No rule to make target 'riscv64'. Stop.
make: Leaving directory '/opt/kaldi/tools/OpenBLAS'**

**can anyone suggest me where i am wrong.**

T&R
Kush

**Comment by martin-frbg** [comment]
If you are not building on the target hardware itself (where the build system would try to autodetect the architecture and cpu), you need to specify a TARGET argument to `make`. Currently this would be either `TARGET=C910V` for the XuanTie cpu which supports the RISCV Vector Extension, or `TARGET=RISCV64_GENERIC` for any other RISCV64. Most likely you will also need to set CC to the full path for your RISCV compiler toolchain.

**Comment by kush930** [comment]
> Hi all ,
> 
> **I clone openblas from link-https://github.com/xianyi/OpenBLAS** **I am using gcc-10.2 and glibc-2.32**
> 
> **I want to build openblas-0.3.20 on riscv platform, i am using below command and facing issue:--**
> 
> **root@kush-Linux-1:/opt/kaldi/tools# make -C OpenBLAS ONLY_CBLAS=1 ${ARCH=riscv64} HOSTCC=gcc USE_LOCKING=1 USE_THREAD=0 all**
> 
> make: Entering directory '/opt/kaldi/tools/OpenBLAS' **getarch_2nd.c: In function 'main': getarch_2nd.c:22:35: error: 'SGEMM_DEFAULT_UNROLL_M' undeclared (first use in this function); did you mean 'SBGEMM_DEFAULT_UNROLL_M'?
> 
> 22 | printf("SGEMM_UNROLL_M=%d\n", SGEMM_DEFAULT_UNROLL_M); | ^~~~~~~~~~~~~~~~~~~~~~ | SBGEMM_DEFAULT_UNROLL_M getarch_2nd.c:22:35: note: each undeclared identifier is reported only once for each function it appears in getarch_2nd.c:23:35: error: 'SGEMM_DEFAULT_UNROLL_N' undeclared (first use in this function); did you mean 'SBGEMM_DEFAULT_UNROLL_N'?
> 
> 23 | printf("SGEMM_UNROLL_N=%d\n", SGEMM_DEFAULT_UNROLL_N); | ^~~~~~~~~~~~~~~~~~~~~~ | SBGEMM_DEFAULT_UNROLL_N getarch_2nd.c:24:35: error: 'DGEMM_DEFAULT_UNROLL_M' undeclared (first use in this function); did you mean 'XGEMM_DEFAULT_UNROLL_M'?
> 
> 24 | printf("DGEMM_UNROLL_M=%d\n", DGEMM_DEFAULT_UNROLL_M); | ^~~~~~~~~~~~~~~~~~~~~~ | XGEMM_DEFAULT_UNROLL_M getarch_2nd.c:25:35: error: 'DGEMM_DEFAULT_UNROLL_N' undeclared (first use in this function); did you mean 'XGEMM_DEFAULT_UNROLL_N'?
> 
> 25 | printf("DGEMM_UNROLL_N=%d\n", DGEMM_DEFAULT_UNROLL_N); | ^~~~~~~~~~~~~~~~~~~~~~ | XGEMM_DEFAULT_UNROLL_N getarch_2nd.c:29:35: error: 'CGEMM_DEFAULT_UNROLL_M' undeclared (first use in this function); did you mean 'XGEMM_DEFAULT_UNROLL_M'?
> 
> 29 | printf("CGEMM_UNROLL_M=%d\n", CGEMM_DEFAULT_UNROLL_M); | ^~~~~~~~~~~~~~~~~~~~~~ | XGEMM_DEFAULT_UNROLL_M getarch_2nd.c:30:35: error: 'CGEMM_DEFAULT_UNROLL_N' undeclared (first use in this function); did you mean 'XGEMM_DEFAULT_UNROLL_N'?
> 
> 30 | printf("CGEMM_UNROLL_N=%d\n", CGEMM_DEFAULT_UNROLL_N); | ^~~~~~~~~~~~~~~~~~~~~~ | XGEMM_DEFAULT_UNROLL_N getarch_2nd.c:31:35: error: 'ZGEMM_DEFAULT_UNROLL_M' undeclared (first use in this function); did you mean 'XGEMM_DEFAULT_UNROLL_M'?
> 
> 31 | printf("ZGEMM_UNROLL_M=%d\n", ZGEMM_DEFAULT_UNROLL_M); | ^~~~~~~~~~~~~~~~~~~~~~ | XGEMM_DEFAULT_UNROLL_M getarch_2nd.c:32:35: error: 'ZGEMM_DEFAULT_UNROLL_N' undeclared (first use in this function); did you mean 'XGEMM_DEFAULT_UNROLL_N'?
> 
> 32 | printf("ZGEMM_UNROLL_N=%d\n", ZGEMM_DEFAULT_UNROLL_N); | ^~~~~~~~~~~~~~~~~~~~~~ | XGEMM_DEFAULT_UNROLL_N make: *** [Makefile.prebuild:78: getarch_2nd] Error 1
> 
> make: *** No rule to make target 'riscv64'. Stop. make: Leaving directory '/opt/kaldi/tools/OpenBLAS'**
> 
> **can anyone suggest me where i am wrong.**
> 
> T&R Kush

**issue is resolved**
