### ISSUE TITLE
What if the codename of my CPU isn't included in the TARGETLIST.TXT

### ISSUE THREAD

**Issue by Satinelamp** [xianyi/OpenBLAS#3649]
The codename of my CPU is ICE LAKE, which is NOT included in the TARGETLIST.TXT, how should choose the TARGET?

**Comment by martin-frbg** [comment]
Normally it should be autodetected if compiling on the target host. If you are cross-compiling, choose the supported TARGET that belongs to an earlier generation with the same general features (such as AVX2 or AVX512, etc.). In your case, that should be SKYLAKEX.
