### ISSUE TITLE
Linux kernel starts to warn about executable stack which is not necessary.

### ISSUE THREAD

**Issue by brada4** [xianyi/OpenBLAS#3663]
Seems small assembly decoration is needed? https://wiki.ubuntu.com/SecurityTeam/Roadmap/ExecutableStacks

`dmesg> process 'tmp.OWk4ps2HhT/OpenBLAS/getarch' started with executable stack`

certainly on rawhide and tumbleweed x86_64 incarnations, no idea when it started, no change in overall behaviour, no danger on being force-fed with no-exec stack in future.

**Comment by martin-frbg** [comment]
Would anybody seriously consider `getarch` as an attack vector ? As there as no reason to assume that any distribution packager will include it, the impact should be infinitesimally low.
