### ISSUE TITLE
Linking OpenBLAS causes an alarming program execution delay

### ISSUE THREAD

**Issue by patztablook22** [xianyi/OpenBLAS#3667]
After linking OpenBLAS to my project, instead of some generec BLAS that i used before, it takes about 500 ms for the program to even reach the main function. It used to be instant before using OpenBLAS. I installed OpenBLAS using VCPKG and my project is configured with CMake.

I am assuming this is not normal and something probably went wrong with configuring or compiling OpenBLAS.

I am using void-linux on Dell's XPS 13 9370. 
Currently I have vcpkg 2022-06-17-9268e366206712e38102b28dbd1617697a99ff2e, but I experienced this with older versions too.

**GETARCH results:**
```
CORE=HASWELL
LIBCORE=haswell
NUM_CORES=8
HAVE_MMX=1
HAVE_SSE=1
HAVE_SSE2=1
HAVE_SSE3=1
HAVE_SSSE3=1
HAVE_SSE4_1=1
HAVE_SSE4_2=1
HAVE_AVX=1
HAVE_AVX2=1
HAVE_FMA3=1
MAKE += -j 8
```

I am attaching the **VCPKG install release output** file too
[install-x64-linux-rel-out.log](https://github.com/xianyi/OpenBLAS/files/8986526/install-x64-linux-rel-out.log)

**Comment by martin-frbg** [comment]
OpenBLAS builds are multithreaded by   default, which causes some overhead from threadpool creation on loading and may not be something you want if your problem sizes are always going to be very small and/or the calling program is multithreaded itself.
Try building with additional cmake options `-DUSE_TLS=ON` if you need multithread (presumably smaller overhead from using thread-local storage). Or options `USE_THREAD=0 USE_LOCKING=1` for singlethreaded OpenBLAS called from multiple parent threads (can leave out the USE_LOCKING if caller is singlethreaded as well)

**Comment by brada4** [comment]
half of that delay is reading 50 MB DLL file over SATA wire. Windows was never fit for starting and stopping processes quickly.
What I suspect is that you have some greedy antivirus that re-reads dll past cache on every execution, unmaps it from cache, and then process reads it again.

**Comment by brada4** [comment]
You can get OpenBLAS from void-linux. Please compare `time ldd` between .so files.
PS sorry I thought you are on windows because of vcpkg.

**Comment by brada4** [comment]
nothing anomalous in the build log, only deviation is usage of `-O3` compiler flag which means C-only compute code will round in an inconsistent ways, but not regarding loading time.

@patztablook22 could you try to trace ld.so as described in its manuals? There is nothing very custom regarding OpenBLAs startup, it loads file, locates few thousands of entry points, starts `nproc` worker threads and executes some yielding instructions, like nop 10x or nanosleep(1) depending on platform in each of them.

**Comment by brada4** [comment]
It is most likely your ld.so doing ASLR. Your old library was without ASLR (non-PIE if you check `file blas.so`) and you missed 10 years of security. You can check `sysctl kernel.random` , if `avail < size*.75` that is the problem, you need to get more entropy on system. like haveged or rng-tools or new kernel running. Nothing to do with build parameters of OpenBLAS.
