### ISSUE TITLE
Cross compilation with w64-mingw32 compilers under fedora 36

### ISSUE THREAD

**Issue by hbadi** [xianyi/OpenBLAS#3668]
Hi,

I tried to cross-compile openblas with w86_64-w64-mingw32 compilers under fedora 36 `make BINARY=64 CC=x86_64-w64-mingw32-gcc FC=x86_64-w64-mingw32-gfortran HOSTCC=gcc TARGET=LOONGSON3A` but it got this error when archiving 
` ar  -ru ../libopenblas_loongson3r3p-r0.3.20.a [list obj files]`
` ar: sgemm_kernel.obj: No such file or directory`

`sgemm_kernel.obj` file doesn't exist... 

This is a bug ?

**Comment by martin-frbg** [comment]
Are you sure that you got the correct compiler for cross-compiling to Loongson3 target ? This is a MIPS cpu 
 so I would expect the cross-compiler name to be something like mips-linux-gnu-gcc - yours looks like the pc linux-to-windows toolchain.

**Comment by martin-frbg** [comment]
Or to put it differently, are you sure you want to cross-compile to a Loongson3A system at all ? The section on cross-compiling in our README uses this particular example as it was what users were struggling with at the time, but the important information there is the use of HOSTCC (some build tools still need to be created on the system where the compiler is installed), and the use of proper paths in the CC and FC options. The TARGET on the other hand always needs to reflect the cpu you actually want to run the code on (which the build files cannot guess). MIPS hardware is nowadays usually found in routers and similar appliances...

**Comment by brada4** [comment]
if you need Windows DLL to rename into blas.dll you need to set TARGET=GENERIC DYNAMIC_ARCH=1 and probably more cpu threads than you will have in near future in a single system. If you target embedded system, you must use SDK/BSP compilers supplied with it unless tkhat system runs full Linux.

**Comment by martin-frbg** [comment]
assuming solved (based on your recent scivision issue), please comment if you need further assistance
