### ISSUE TITLE
sbgemm support for ARM Neoverse N2

### ISSUE THREAD

**Issue by imzhuhl** [xianyi/OpenBLAS#3671]
The previous issue has discussed how valuable BFloat16 is in the field of Deep Learning and Machine Learning, and the `develop`  branch also supports bf16 on a few Intel platform. However, there seems to be no implementation for the ARM platform.

Currently, I have a need for optimization of matrix multiplication of type BFloat16 on ARM Neoverse N2. I found that the original implementation used the `gemmkernel_2x2.c` file in the `generic` directory, which resulted in low efficiency. On ARM Neoverse N2, we can use BFMMLA instruction to accelerate calculation.

Currently, some cloud service vendors have launched ARM servers, such as AWS Graviton and Alibaba Cloud Yitian 710. Maybe there will be a lot of demand for ARM service platforms. Does OpenBLAS have an optimization plan for the ARM platform?

**Comment by imzhuhl** [comment]
I've already done a preliminary implementation on the Neoverse N2 platform with a single thread of around 90GFLOPS compared to FP32 with a single thread of 40 GFLOPS

**Comment by martin-frbg** [comment]
Unfortunately the core developer team of OpenBLAS is very small (mostly just me in my limited spare time, trying to keep the number of open issues from exploding), so patches/PRs are always welcome.

**Comment by martin-frbg** [comment]
Closing as resolved by your PR #3672

**Comment by snadampal** [comment]
Hi @imzhuhl , Please let me know how you tested this feature? 
When I tried the "test_sbgemm", to compare the sgemm vs sbgemm output, it was failing with the data mismatch.
Appreciate if you can share details on what and how it has been tested. Thank you!

**Comment by martin-frbg** [comment]
That's weird, I'm pretty sure it passed on my Cortex-X2.,. reopening

**Comment by imzhuhl** [comment]
> Hi @imzhuhl , Please let me know how you tested this feature? When I tried the "test_sbgemm", to compare the sgemm vs sbgemm output, it was failing with the data mismatch. Appreciate if you can share details on what and how it has been tested. Thank you!

I tried again and it passed `test_sbgemm`. In addition to `test_sbgemm` I have my own implementation of a test where I directly compare results between sbgemm and naive loop (triple for loop).

Could you run the test again on your machine with the following modifications:
1. force a single threaded run (make sure to exclude multi-thread errors)
2. change the test data to random integers (make sure to exclude errors due to precision)

**Comment by snadampal** [comment]
the test is passing for integers, but not floats. and the difference doesn't look like due to precision, the diff is very large. 
btw, I'm trying it on V1, I have ported the PR to KERNEL.NEORVERSEV1 and used the same unroll_M and N values as in N2. I was able to compile it with sve+bf16 (without sve2) and the "sbgemm_kernel_8x4_neoversen2_impl.c" doesn't seem to be having any sve2 specific instructions. Do you expect any other dependency on N2 architecture for this sbgemm kernel?

**Comment by imzhuhl** [comment]
> the test is passing for integers, but not floats. and the difference doesn't look like due to precision, the diff is very large. 
That's weird...

> btw, I'm trying it on V1, I have ported the PR to KERNEL.NEORVERSEV1 and used the same unroll_M and N values as in N2.

the vector register length of V1 is 256bit, which is different from N2 (128bit). I'm not sure whether this implementation can be directly ported to V1

**Comment by imzhuhl** [comment]
> the test is passing for integers, but not floats. and the difference doesn't look like due to precision, the diff is very large.

That's weird...

> btw, I'm trying it on V1, I have ported the PR to KERNEL.NEORVERSEV1 and used the same unroll_M and N values as in N2.

The vector register length of V1 is 256 bit, which is different from N2(128bit). I'm not sure whether there would be problems with direct porting (at least ncopy and tcopy must be modified).

Yes, I don't use sve2 specific instructions currently.

**Comment by imzhuhl** [comment]
@snadampal Hi, I checked the `sbgemm_kernel_8x4_neoversen2_impl` and if you want to port to V1, it is needed to modify the code, especially the boundary case.

**Comment by snadampal** [comment]
@imzhuhl , thanks for checking!

**Comment by snadampal** [comment]
Hi @imzhuhl , I see that the unit test (compare_sgemm_sbgemm.c)covers only 'alpha=1.0' scenario which is passing for me on V1 for any random floats. However, when I change the the alpha to bigger number, e.g. 128.0, it fails due to the sgemm vs sbgemm differences being larger than the acceptable threshold. And the error value is higher for larger alpha as it is a multiplication factor for the output.
Have you observed similar thing on N2? I wanted to understand whether it is a known issue or something I need to take care specific to V1.

one such failure:

> diff C[0:0]=154.880005, CC[0:0]=153.125000

**Comment by martin-frbg** [comment]
That looks like a fragility in the test code itself - presumably the extra multiplication in itself increases numerical error beyond the given threshold (and I also note that the naive loop to calculate DD does not take alpha or beta into account either). I see similar test failures on POWER8 if I play with the alpha value there.

**Comment by snadampal** [comment]
@martin-frbg , thanks for checking on the other platforms! btw, I had locally added the missing alpha factor for DD loop already. I've seen the difference go upto 3.0! if we want to make the test pass we can just use the alpha factor for dividing the output difference before checking the threshold, but I would like to see what scaling factors are typical for ML applications in general.

**Comment by snadampal** [comment]
Hi @imzhuhl , for performance benchmarking did you use the openBLAS test or your customer application? what was the improvement for single and multi-threaded sbgemm? I wanted to measure the performance before finalizing my changes for PR. Thank you!

**Comment by imzhuhl** [comment]
> Hi @imzhuhl , for performance benchmarking did you use the openBLAS test or your customer application? what was the improvement for single and multi-threaded sbgemm? I wanted to measure the performance before finalizing my changes for PR. Thank you!

Hi, I test OpenBLAS directly. Here is my results, `m = n = k = Size`
<img width="472" alt="image" src="https://user-images.githubusercontent.com/17999964/184465923-14409c04-c6d8-4f37-8e18-5b9a02d8d07c.png">
