### ISSUE TITLE
Cannot use Openblas in M1 Mac properly 

### ISSUE THREAD

**Issue by rickypang0219** [xianyi/OpenBLAS#3674]
Hi all, I am a newbie to use C++ for computing tensor network related stuff. I use homebrew to install openblas on my M1 mac. There are some outputs of terminal which is listed below: 
```
openblas is keg-only, which means it was not symlinked into /opt/homebrew,
because macOS provides BLAS in Accelerate.framework.

For compilers to find openblas you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/openblas/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/openblas/include"
```
I follow the instruction and simply type these two command in terminal. To test whether the openblas can work, I copy a sample code from internet and place it direclty under the include file of Openblas
```
#include <iostream>
#include "cblas.h"
#include "lapacke.h"

using namespace std;

int main(){
    float b[] = {3, 1, 3, 1, 5};
    cblas_sasum(5, b, 1);
    cout << "Program finished";
}
``` 
However, I cannot compile this test code and the error messges are
```
Undefined symbols for architecture arm64:
  "_cblas_sasum", referenced from:
      _main in main-841db8.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Could anyone give me some guidelines on solving this problem?

**Comment by martin-frbg** [comment]
How did you compile this ? Having a library on your computer does not mean that the compiler automatically knows when to use it. You need to tell the compiler/linker that it needs to link to libopenblas, so something like `-lopenblas` needs to be on the command line.

**Comment by dnoan** [comment]
I've been able to run OpenBLAS on M1 but in my case I build it myself.

**Comment by rickypang0219** [comment]
Thank you for the comments. I have no idea on how the compiler/linker that link to the libopenblas. I follow the instruction on [Stackoverflow](https://stackoverflow.com/questions/15045748/how-to-use-external-libraries-and-headers-in-c-makefile) by making a makefile that contains all the paths. Then I can compile the above test code even the test code file is in different directories. By the way, is it possible to use Openblas on Xcode instead of terminal? Xcode always show "cblas.h" cannot be found. 



Now my makefile like the following:
```
CC = g++
INCLUDES = -I/opt/homebrew/Cellar/openblas/0.3.20/include
CPPFLAGS = -g -Wall $(INCLUDES)
LDFLAGS = -L/opt/homebrew/opt/openblas/lib

all:main.o /opt/homebrew/opt/openblas/lib/libopenblas.a
        $(CC) main.o $(LDFLAGS) -lopenblas -o main.out

main.o:main.cpp /opt/homebrew/Cellar/openblas/0.3.20/include/cblas.h
        $(CC) $(CPPFLAGS) -c main.cpp
clean:
        rm -f main.out
```

**Comment by martin-frbg** [comment]
This looks quite good, maybe you do not have the `libopenblas.dylib` in /opt/homebrew/opt/openblas/lib ? (Or - less likely - it was not built with the CBLAS functions). Does it link when you replace the
```
 $(CC) main.o $(LDFLAGS) -lopenblas -o main.out
```
with
```
 $(CC) main.o /opt/homebrew/opt/openblas/lib/libopenblas.a -o main.out
```
("static linking", which will produce a bigger executable with everything from the library permanently built in)

Unfortunately I cannot help with the Xcode question

**Comment by rickypang0219** [comment]
I have ```libopenblas.dylib``` in lib. I cannot compile my code  once I replace  ``` $(CC) main.o $(LDFLAGS) -lopenblas -o main.out```  with ``` $(CC) main.o /opt/homebrew/opt/openblas/lib/libopenblas.a -o main.out```. For the Xcode problem, I think I solve it by adding extra flags in Xcode. I follow the instructions of this[ youtube video](https://www.youtube.com/watch?v=7miwnp8iDm8).

**Comment by martin-frbg** [comment]
Same error with the libopenblas.a, or something different ? Does `nm -g /opt/homebrew/opt/openblas/lib/libopenblas.dylib` show you any symbols with `cblas_` prefix ?

**Comment by brada4** [comment]
[Actually homebrew test does cblas](https://github.com/Homebrew/homebrew-core/blob/d5e5fc63cc47e74e95885dfcbc0344be77d49f20/Formula/openblas.rb#L56)
They do not use environment variables but `-Iinclude -Llibdir -lopenblas` in command line.

**Comment by brada4** [comment]
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

`CC = g++`

Can you elaborate?

**Comment by martin-frbg** [comment]
@brada4 that's been normal on OSx ever since they dropped GCC in favor of (their) LLVM - gcc and g++ are just links/frontends to clang unless one install an actual GCC from homebrew or whatever. I do not think this plays a role here, but it would certainly be good to have some more detailed information than just "I cannot compile"

**Comment by brada4** [comment]
Yup, question if both snips are from same config in regard to what is g++

**Comment by Lyndseylou37** [comment]
/nix/store/b6gvzjyb2pg0kjfwrjmg1vfhh54ad73z-firefox-33.1/
Esquires Lyndsey Watson Copyright Copyright©️

**Comment by Lyndseylou37** [comment]
![Uploading 1659102304922.jpg…]()

**Comment by Lyndseylou37** [comment]
![Uploading 1659099292929.jpg…]()
