### ISSUE TITLE
Query about RVV 1.0 support

### ISSUE THREAD

**Issue by fanghuaqi** [xianyi/OpenBLAS#3681]
Hi guys, 

  Is there any support for RISC-V Vector 1.0 support in OpenBLAS, currently I see only RVV 0.7.1 is supported, if there is a rvv 1.0 version, could you kindly point it out to me, thank you!

Thanks
Huaqi

**Comment by xianyi** [comment]
Hi fanghuaqi,

RVV 1.0 is working in process.

Xianyi

**Comment by fanghuaqi** [comment]
Hi xianyi, thanks for the information, any plan to release the support for it, maybe we can help to contribute and test it in our qemu.
