### ISSUE TITLE
Guide: How to compile OpenBLAS on Ubuntu ( Ubuntu 20.04 / Ubuntu 22.04)

### ISSUE THREAD

**Issue by soulteary** [xianyi/OpenBLAS#3683]
Recently in the tossing project, openBLAS is used in the project, and using an older version, happens to have no binary release, and also needs to support ARM builds.

So, I wrote a document describing how to build OpenBLAS from zero to one:

- The document: https://soulteary.com/2022/07/08/into-vector-computing-compiling-openblas-from-source.html (maybe need google translate)
- The tossing project I mentioned: https://github.com/milvus-io/milvus

Hope the project will get better and better!

**Comment by brada4** [comment]
Ubuntu has installable package libopenblas-dev
You can build for particular host with just typing `make ; sudo make install` - library will be in /opt/OpenBLAS/
Or more profound walk-through: https://github.com/xianyi/OpenBLAS/wiki/Faq#debianlts

i.e I suspect you intend to use BLAS and/or LAPACK, thus you actually can use system alternatives mechanism, build for -lblas -llapack, and then switch between atlas/openblas/blis/mkl/netlib at runtime.

You almost got it right, I suggest you minimize the parametritis that follows your `make` command (doc in Makefile.rule)
 and certainly do not run compilers as root user.

EDIT: if you need to use web translate I can write with reduced vocabulary aka simple english.

**Comment by martin-frbg** [comment]
Thanks for the pointer, great writeup, just some quick comments:
- why use such an old version as 0.3.9 ?
- you can find all available `make` options with a short description in Makefile.rule
- there is usually no need to run the `make` under sudo, it is generally safer to do it only for the `make install`(where you usually need to write into system folders)
- you can use `make lapack-test` for extensive testing of BLAS and LAPACK correctness, or get xianyi's BLAS-Tester project from github (BLAS testsuite adapted from ATLAS)
- the libjulia-openblas64 you found for newer Debian is _probably_ built with the INTERFACE64=1 option (use 64bit integers), which may not be compatible with your own programs unless you use similar options when building your code
- the history of OpenBLAS actually goes back ten more years, it starts with the groundbreaking GotoBLAS library of Japanese developer Kazushige Goto - Goto had to abandon it when he left academia and started work at Microsoft. (Nowadays he is probably one of the masterminds behind Intel's MKL)

**Comment by brada4** [comment]
You can cross-compile aarch64 binaries on x86_64 , using gcc and gfortran (and binutils) cross packages. i.e
`HOSTCC=cc CC=aarch64-linux-gnu-gcc FC=aarch64-linux-gnu-gfortran TARGET=ARMV8 DYNAMIC_ARCH=1 NUM_THREADS=256`

(note DYNAMIC_OLDER has no effect there)

Process is fairly similar to embedded SDK-s around. You can even use qemu binfmt to run them emulated as if they were native executables for tests. Raspberry jumps circles around emulator.

If you wish to make single package for all debians, you should use one (with) oldest (glibc) to make the package.

**Comment by soulteary** [comment]
thank you very much @brada4 ! I will update some content later, about the above content suggestion.

**Comment by soulteary** [comment]
Also thanks for your correction. @martin-frbg 

Regarding the question, as far as I understand it:

Most projects, especially complex projects with multiple dependencies, do not have much research and investigation on the version of the basic computing library, and the updated version may have potential risks for maintainers: A lot of unanticipated workload.

Finally, an additional suggestion that I didn't mention in the article: Is it possible to have OpenBLAS use GitHub Actions to build, so that the artifacts can be added to the GitHub Release page with clarity and transparency, even to complement previous ancient releases binary file.

Thank you again for your pointers and suggestions, it is very necessary for me to write a detailed content. @martin-frbg

**Comment by brada4** [comment]
Binaries are provided for Windows where median developer has MSVC compiler that itself cannot build assembly and fortran code paths, as to save extreme complexity for casual end user. No problem building or getting distributed package on others (by distro, manylinux2 from conda, or if you choose to embed version tested by you)

**Comment by martin-frbg** [comment]
yes I guess it should be possible to set up Github Actions that create binary packages for various platforms at release time. Still need to look up how that is done... the current Windows binaries are compiled and uploaded manually by me with each release.
