### ISSUE TITLE
Using OpenBLAS to Compile CBLAS 

### ISSUE THREAD

**Issue by Jinzz98** [xianyi/OpenBLAS#3688]
Error occurs when I compile CBLAS with OpenBLAS in clusters. Here are the Info and Makefile：

gfortran  -o xscblat1 c_sblat1.o c_sblas1.o ../lib/cblas_LINUX.a ../lib/libopenblas.a
../lib/libopenblas.a(memory.o): In function `openblas_fork_handler':
memory.c:(.text+0x2b0): undefined reference to `pthread_atfork'
../lib/libopenblas.a(blas_server.o): In function `blas_thread_init':
blas_server.c:(.text+0x452): undefined reference to `pthread_create'
../lib/libopenblas.a(blas_server.o): In function `goto_set_num_threads':
blas_server.c:(.text+0x917): undefined reference to `pthread_create'
../lib/libopenblas.a(blas_server.o): In function `blas_thread_shutdown_':
blas_server.c:(.text+0xb33): undefined reference to `pthread_join'
../lib/libopenblas.a(blas_server.o): In function `openblas_setaffinity':
blas_server.c:(.text+0x317): undefined reference to `pthread_setaffinity_np'
blas_server.c:(.text+0x333): undefined reference to `pthread_setaffinity_np'
collect2: error: ld returned 1 exit status
make[1]: *** [xscblat1] Error 1

SHELL = /bin/sh
PLAT = LINUX
BLLIB = ../lib/libopenblas.a
CBLIB = ../lib/cblas_$(PLAT).a
CC = gcc
FC = gfortran
LOADER = $(FC)
CFLAGS = -fPIC -O3 -DADD_
FFLAGS = -fPIC -O3
ARCH = ar
ARCHFLAGS = r
RANLIB = echo

**Comment by martin-frbg** [comment]
You need to add the path to your system libpthread.a (or `-lpthread` for dynamic linking against it) to your BLLIB entry if you link with a multithreaded OpenBLAS. 
(Out of curiosity: are you just splitting OpenBLAS into separate BLAS and CBLAS libraries, or are you building the CBLAS from Reference-LAPACK with OpenBLAS here ?)

**Comment by Jinzz98** [comment]
> You need to add the path to your system libpthread.a (or `-lpthread` for dynamic linking against it) to your BLLIB entry if you link with a multithreaded OpenBLAS. (Out of curiosity: are you just splitting OpenBLAS into separate BLAS and CBLAS libraries, or are you building the CBLAS from Reference-LAPACK with OpenBLAS here ?)

Thanks a lot, especially words in parentheses. I just want the CBLAS library.

**Comment by Jinzz98** [comment]
> You need to add the path to your system libpthread.a (or `-lpthread` for dynamic linking against it) to your BLLIB entry if you link with a multithreaded OpenBLAS. (Out of curiosity: are you just splitting OpenBLAS into separate BLAS and CBLAS libraries, or are you building the CBLAS from Reference-LAPACK with OpenBLAS here ?)

Thanks a lot, especially words in parentheses. I just want the CBLAS library.
