### ISSUE TITLE
Missing linkage towards m (math library) for QNX

### ISSUE THREAD

**Issue by ghost** [xianyi/OpenBLAS#3697]
If you follow official guidelines for cross-compiling on QNX (https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling-for-qnx) you will expose: `set(CMAKE_SYSTEM_NAME QNX)`, resulting in linkage failure when OpenBLAS is cross-compiled for QNX due to: https://github.com/xianyi/OpenBLAS/blob/a4303ae37817e85eacf459327dea834df6cd23d8/utest/CMakeLists.txt#L62 missing check for `CMAKE_SYSTEM_NAME MATCHES "QNX"`

**Comment by martin-frbg** [comment]
Thank you for the hint, now fixed as you suggested
