### ISSUE TITLE
Timeline for 0.3.21?

### ISSUE THREAD

**Issue by h-vetinari** [xianyi/OpenBLAS#3701]
Sorry to ask, there's just a number of issues that affect numpy/scipy that have been fixed on the develop branch already, but not yet in 0.3.20, to the point that people are [looking](https://github.com/conda-forge/openblas-feedstock/pull/141) to backport the fixes (resp. scipy being stuck on 0.3.18).

I don't mind the backports per se (and happy to do that if it's still going to take a while), but wanted to check at least if a new version is already on the horizon.

**Comment by larsoner** [comment]
Cross-ref to https://github.com/xianyi/OpenBLAS/issues/861#issuecomment-1175440938 from a few weeks ago about the last outstanding 0.3.21-marked issue/PR. I was indirectly asking a similar question I guess :)

**Comment by martin-frbg** [comment]
I am currently trying to clean out my backlog as my one-man business is experiencing a lull, so hopefully within the next couple of weeks - I usually set a date on the milestone when I'm confident enough, but what is listed there as outstanding may not always be the actual blocker (maybe I should even take that list private?). No guarantees that there won't be another family emergency though, and calls of "are we there yet" do not exactly count as encouragement

**Comment by larsoner** [comment]
> and calls of "are we there yet" do not exactly count as encouragement

Sorry if I have seemed impatient -- I do appreciate your work here, especially finding fixes to stuff like https://github.com/xianyi/OpenBLAS/issues/3654 (rather than following my suggestion just to live with a slower workaround)!

**Comment by h-vetinari** [comment]
> No guarantees that there won't be another family emergency though, and calls of "are we there yet" do not exactly count as encouragement

I understand that, which is why I started off with "sorry to ask". It's fair enough that things take as long as they do (especially in a situation like yours), but I think it's still justified for users to ask for a rough status - AFAICT this is one of the longer breaks in recent OpenBLAS release history (not that this is a complaint, just that the questions about a new release increase over time and proportionally to what bugfixes are relevant to people), so having a tracking issue hopefully helps clarify the situation also for others who are affected & curious.

And to be clear: "perhaps in a few weeks, maybe months" is a completely acceptable answer, but will impact how much importance the backporting work in conda-forge takes on (for example).

**Comment by martin-frbg** [comment]
Welp, guess we're back to pre-CZI release cycles (not that this has been my intention, mostly just real life interfering in ways I could have done without)

**Comment by martin-frbg** [comment]
Milestone due date now set to next sunday.
