### ISSUE TITLE
[Help] can openblas be built for Hifi3 DSP

### ISSUE THREAD

**Issue by NormonisPing** [xianyi/OpenBLAS#3710]
Help...

**Comment by martin-frbg** [comment]
Unfortunately I am not aware that anybody has ever tried, and if I read the available descriptions correctly it is not a general purpose cpu in the sense that OpenBLAS expects but more like a fixed-point coprocessor. If there is a C compiler for it, you could perhaps reuse individual BLAS kernels from the kernel/generic subtree, but I am not sure if that will be worth the effort

**Comment by NormonisPing** [comment]
> Unfortunately I am not aware that anybody has ever tried, and if I read the available descriptions correctly it is not a general purpose cpu in the sense that OpenBLAS expects but more like a fixed-point coprocessor. If there is a C compiler for it, you could perhaps reuse individual BLAS kernels from the kernel/generic subtree, but I am not sure if that will be worth the effort

thanks Martin for your instruction. I will try.
