### ISSUE TITLE
How do I check if my project is already using opanblas

### ISSUE THREAD

**Issue by Maple-yhj** [xianyi/OpenBLAS#3728]
I didn't notice a significant speed-up in my project after following the documentation, so I wanted to make sure that my armadillo was using opanblas for matrix operations

**Comment by martin-frbg** [comment]
That is really a question for the armadillo people - if there is a command/function in armadillo that shows the configured dependencies. What is your hardware and operating system ? (On Linux, you could probably run `ldd` on the libarmadillo.so to see what dependencies it has)

**Comment by Maple-yhj** [comment]
> That is really a question for the armadillo people - if there is a command/function in armadillo that shows the configured dependencies. What is your hardware and operating system ? (On Linux, you could probably run `ldd` on the libarmadillo.so to see what dependencies it has)
My operating system is windows 7 and my compiler is Mingw

**Comment by Maple-yhj** [comment]
> 

My operating system is windows 7 and my compiler is Mingw

**Comment by Maple-yhj** [comment]
I would like to know if Armadillo has included Openblas on its own in the windows environment.

**Comment by brada4** [comment]
It is described in armadillo faq, not here.

**Comment by martin-frbg** [comment]
As far as I could find out, the binary distribution of Armadillo contains a copy of the OpenBLAS dll - actually the MXE/gcc compiled binaries that I provide with OpenBLAS releases - that is referenced at least by the VS solution file for the example1.cpp that comes with Armadillo. I guess a trivial test would be to remove (rename or zip) this dll and see if your code still compiles and runs. Please direct any followup questions at the Armadillo developers, unless you have a plain C, non-Armadillo code that demonstrates poor performance with OpenBLAS. (There are several reasons why e.g. a simple hand-coded loop _may_ be faster than going through libraries like Armadillo and OpenBLAS - overhead from initializations and thread setup, variables allocated on the heap or the stack, and lastly not all  BLAS kernels in OpenBLAS are equally well optimized on all generations of Intel/AMD cpus)
