### ISSUE TITLE
C program calls LAPACK function

### ISSUE THREAD

**Issue by shadowtwinkle** [xianyi/OpenBLAS#3730]
When calling the dgbtrs' function of LAPACK, there is a DGER function. How should the parameter 1 be passed? When I passed it, I tried many methods, saying that the parameter was illegal.
  dger_(&lm,&(*NRHS),-ONE,AB_2[(kd+1)*j],1,B[j],&(*LDB),B[j+1],&(*LDB));
  On entry to DGER parameter number  5 had an illegal value

**Comment by martin-frbg** [comment]
Which function is your code calling, cger from BLAS or dgbtrs from LAPACK ? There are C bindings for both (CBLAS,LAPACKE).
Also, try putting your literal 1 into a variable for the dger call, and check that you are passing the other arguments correctly. See benchmark/ger.c in the OpenBLAS sources for an example (where the GER becomes dger_ when building the double precision version)

**Comment by shadowtwinkle** [comment]
Hello, I called the DGER function in dgbtrs. I don't know why the parameter 1 is always displayed as an illegal value.

**Comment by shadowtwinkle** [comment]
Hello, I called the DGER function in dgbtrs. I don't know why the parameter 1 is always displayed as an illegal value.

**Comment by martin-frbg** [comment]
Again, what are you calling - are you calling DGBTRS and getting an "illegal value" error from the DGER call in there, or are you trying to call DGER directly from your code, with parameters like you saw them in the dgbtrs.f ?

**Comment by shadowtwinkle** [comment]
I called the DGER function directly from the C code, showing that the parameter 1 is illegal.

**Comment by martin-frbg** [comment]
Probably one of your other parameters is wrong and overwrites, can you try using https://github.com/xianyi/OpenBLAS/blob/develop/benchmark/ger.c as example ?

**Comment by shadowtwinkle** [comment]
OK, I'll try to refer to it. Thank you very much.
