### ISSUE TITLE
Why openblas gemm prefers to use a smaller micro kernel

### ISSUE THREAD

**Issue by lilh9598** [xianyi/OpenBLAS#3734]
I'm very curious why openblas prefers to use a smaller micro kernel. In theory, a larger micro kernel will bring better data reuse and achieve better performance.  
For example, 12x8 micro kernel(24 for c, 3 for a, 2 for b) can be used on arm64-neon-sgemm instead of a 16x4(16 for c, 4 for a, 1 for b) micro kernel.

**Comment by lilh9598** [comment]
I try to understand...

**Comment by martin-frbg** [comment]
In practice, cache sizes and cache line contention will also play a role. But also most kernels were written for older hardware (or still need to have good performance on older hardware), not all of them may have optimum performance. You would need to code a larger kernel and then measure its performance on actual hardware to see if there is actually an improvement. PRs are certainly very welcome here.

**Comment by lilh9598** [comment]
> In practice, cache sizes and cache line contention will also play a role. But also most kernels were written for older hardware (or still need to have good performance on older hardware), not all of them may have optimum performance. You would need to code a larger kernel and then measure its performance on actual hardware to see if there is actually an improvement. PRs are certainly very welcome here.

Get it, thx for your kindly reply.
