### ISSUE TITLE
Eigenvalue errors in 0.3.20 and 0.3.21 on ARM / M1

### ISSUE THREAD

**Issue by kburns** [xianyi/OpenBLAS#3735]
Hello, I'm noticing some errors in results and nonconvergence in eigenvalue routines on mac M1.  I've put together some simple test problems using numpy, scipy, and libopenblas builds from conda-forge:

```
import numpy as np
import numpy.linalg
import scipy.linalg

A = np.array([[0, 1j], [-1j, 0]])

test_unitary = lambda A: np.allclose(np.eye(2), A.T.conj() @ A)

w, v = numpy.linalg.eigh(A)
print("numpy.linalg.eigh:", test_unitary(v))

w, v = scipy.linalg.eigh(A)
print("scipy.linalg.eigh:", test_unitary(v))

w, v = numpy.linalg.eig(A)
print("numpy.linalg.eig:", test_unitary(v))

w, v = scipy.linalg.eig(A)
print("scipy.linalg.eig:", test_unitary(v))

B = np.eye(2)
w, v = scipy.linalg.eig(A, B)
print("scipy.linalg.eig (gen):", test_unitary(v))
```

With openblas 0.3.18, all of these tests pass on M1.  With openblas 0.3.20 or 0.3.21, the numpy Hermitian test returns wrong results, and the scipy generalized non-Hermitian routine fails to converge.  I wasn't sure if I should bring this up on the scipy/numpy or any of the conda-forge repositories, but thought I'd start here. Any thoughts?

**Comment by martin-frbg** [comment]
Possibly related to https://github.com/numpy/numpy/issues/21950 (which I cannot reproduce on non-OSX systems, including an M1 running Linux). Not sure if this could be a conda build problem (or a particular set of build options there that I may have missed) or something that really only shows up in an OSX environment. Fact is that after 0.3.18, the BLAS kernel mix used on M1 was upgraded to include some codes originally written for the ThunderX2T99 platform, a corner case in the DNRM2 kernel
was subsequently identified in 0.3.20 and fixed in 0.3.21. Unfortunately my only M1 access is through the GCC compile farm, and its sole OSX M1 has been unavailable lately.

**Comment by martin-frbg** [comment]
Getting "True" for all five calls in your test case on the Linux M1 with OpenBLAS built from source and numpy/scipy both installed via pip (and the libopenblas that came with them both replaced of course)

**Comment by catmyc** [comment]
From my side this problem appears when I install Scipy from Conda. Once with Scipy uninstalled, numpy.linalg.eigh() can give the correct eigenvectors.
Then I tried installing Scipy from source. No issue of the eigenvectors is observed.
I also observed that the Openblas library from Conda is quite inefficient for M1. The  Numpy I'm currently using is installed from PyPi channel and Scipy is built from source with Openblas library from Homebrew. My code runs 3~4 times faster than with the Conda installation.

**Comment by h-vetinari** [comment]
AFAIU that speed difference is due to setting `DYNAMIC_ARCH=0` in conda-forge, though this is probably more owed to support for osx-arm still maturing at the time it was added. I also don't really understand where such a behavioural difference could come from. We build pretty vanilla openblas.

**Comment by martin-frbg** [comment]
h-vetinary what are the full build options you use ? DYNAMIC_ARCH=0 with TARGET=VORTEX should be a bit _faster_ than DYNAMIC_ARCH=1 (which would settle for generic ARMV8), not slower as reported here. Do NumPy and Scipy bring their own copy of OpenBLAS when installed via conda ? I noticed yesterday that a `pip install` on the Linux M1 brought in an INTERFACE64=1 build of OpenBLAS with NumPy, and an additional, non-INTERFACE64 version with SciPy. If both libraries got loaded in the same python instance, there could be some unwanted crossover if there is a symbol missing its 64 suffix in the
INTERFACE64 version, or a call to an internal function manages to cross into the "other" library. ( https://github.com/MacPython/openblas-libs/issues/79 which I had begun to address in #3658 )

**Comment by h-vetinari** [comment]
> Do NumPy and Scipy bring their own copy of OpenBLAS when installed via conda?

They share one openblas that's built separately, so they don't bring their own copies.

> DYNAMIC_ARCH=0 with TARGET=VORTEX should be a bit _faster_ than DYNAMIC_ARCH=1

Thanks, makes sense. I had confused myself.

> what are the full build options you use?

Build script is [here](https://github.com/conda-forge/openblas-feedstock/blob/main/recipe/build.sh) + some relevant config [here](https://github.com/conda-forge/openblas-feedstock/blob/main/recipe/conda_build_config.yaml).

> I noticed yesterday that a `pip install` on the Linux M1 brought in an INTERFACE64=1 build of OpenBLAS with NumPy, and an additional, non-INTERFACE64 version with SciPy

Not sure what's happening with pip install. In conda-forge, the ILP64 stuff is not default and must be selected specifically (and we strongly recommend not mixing conda-forge with pip installs; not least to these sorts of potential problems).

**Comment by brada4** [comment]
Nothing scary in build script
Long ago it was overall that SOMETHING=0 was inconsistent config, like `#ifdef SOMETHING` all over the place, but should be correct nowadays. 
https://github.com/conda-forge/openblas-feedstock/blob/9d5671d1e06d0c81fdaeb7e4e96292948c56558c/recipe/build.sh#L68
I would suggest a test build that does minimal overrides over Makefile.rule only, from the set actually written in that command line, if that fixes something, we have to address legacy problems.

**Comment by martin-frbg** [comment]
Nothing suspicious in the build options (if I read them correctly). I have rerun my build tests with clang 13 instead of gcc and did not reproduce the problem there either,  with the only _caveat_ that I cannot test a clang build with OpenMP on the gccfarm host.
I have also checked (again) that none of the assembly kernels used in the "VORTEX" target - and in particular none of those brought in from ThunderX2T99 since 0.3.18 - uses the x18 register that is reserved on OSX.

**Comment by isuruf** [comment]
I can confirm that this issue is only with the openmp build and there are no issues with a pthread build on a mac M1

**Comment by martin-frbg** [comment]
Thank you. I saw no issue with gcc/libgomp on Linux/M1, and the only recent OpenMP-related change would be #3703 (reverting omp threadpool resizing behaviour to its pre-0.3.11 form). Anyway OpenMP behaviour should not be influenced by choice of "VORTEX" target over "ARMV8", Might this be a coincidental bug in the clang/libomp version used to build the conda package ?

**Comment by isuruf** [comment]
Sorry. That was a pthreads build and TARGET=armv8 build. Let me try a pthreads and TARGET=VORTEX build

**Comment by isuruf** [comment]
A pthreads build with TARGET=VORTEX gives the wrong results too.

**Comment by martin-frbg** [comment]
compiler version and build options please ?

**Comment by isuruf** [comment]
Same as conda-forge build options except `USE_OPENMP=0` and clang=13

**Comment by martin-frbg** [comment]
Thanks. With the OSX M1 in gccfarm still unavailable and the problem irreproducible on Linux, I can only suggest further steps to test: (1) change kernel/arm64/KERNEL.VORTEX to include KERNEL.ARMV8 instead of KERNEL.NEOVERSEN1. (2) if that makes it work, bring back individual thunderx2t99 kernels from KERNEL.NEOVERSEN1 until it breaks again. These changes are limited to DAXPY, all ?ASUM (but probably only DASUM relevant here), similarly ?COPY, I?AMAX, ?NRM2, ?DOT.

**Comment by martin-frbg** [comment]
Trying to setup Cirrus-CI now which claims to offer M1 instances

**Comment by isuruf** [comment]
> (1) change kernel/arm64/KERNEL.VORTEX to include KERNEL.ARMV8 instead of KERNEL.NEOVERSEN1. 

Did the change, but the test still fails with TARGET=VORTEX.

**Comment by martin-frbg** [comment]
Very strange - all the (few) other M1-specific settings in the codebase should be unchanged from the initial M1 support that went into 0.3.19. But a build with TARGET=ARMV8 passes the tests ?

**Comment by isuruf** [comment]
> But a build with TARGET=ARMV8 passes the tests ?

Yes

**Comment by martin-frbg** [comment]
Well, the only differences I see are (1)`-march=armv8.3-a` vs. `-march=armv8-a` (in Makefile.arm64 - suggests compiler error if this should be the cause) and (2) bigger GEMM P,Q in param.h (which should not have this effect, and may even have little effect in terms of performance)

**Comment by isuruf** [comment]
>  (1)-march=armv8.3-a vs. -march=armv8-a 

Bingo. Changing to armv8-a fixes the tests even with `KERNEL.NEOVERSEV1` in `KERNEL.VORTEX`

**Comment by martin-frbg** [comment]
Borked compiler or assembler ? Guess this is Apple's very own version of their LLVM, after all I did not see this in the Asahi Linux builds.

**Comment by isuruf** [comment]
> Guess this is Apple's very own version of their LLVM

Nope. Using vanilla clang builds. Let me try clang 14.

**Comment by martin-frbg** [comment]
Just checked gcc103.fsffrance.org again - I was fairly certain that I had used clang 13 there, but clang --version now says 14.0.6-2 and system file dates suggest that at least llvm has been reinstalled this morning.

**Comment by isuruf** [comment]
> Let me try clang 14.

Nope. clang 14 fails the test as well.

**Comment by isuruf** [comment]
gfortran 11 is the issue. `-armv8.3-a` in CCOMMON_OPT works fine and `-armv8.3-a` in FCOMMON_OPT fails. I'll try to update the gfortran compiler.

**Comment by martin-frbg** [comment]
(gcc+)gfortran-11 build still passes on Asahi Linux/M1 without changing anything in OpenBLAS

**Comment by isuruf** [comment]
This is a slightly older build of gfortran 11. I'll try a few versions, but I think it's safe to close this issue for now as a compiler bug.

**Comment by martin-frbg** [comment]
I guess I could add a gfortran version check to that section of Makefile.arm64 if necessary, but my options for testing are currently limited (cirrus-ci setup appears to be hampered by their M1 being a VM with zeroed or atypical sysctl entries, brew fails to install just about anything related to python/numpy)

**Comment by martin-frbg** [comment]
The Asahi Linux machine has gcc/gfortran 11.3.0 in addition to 12.1. I suppose I could build an older release from source there if necessary

**Comment by isuruf** [comment]
This one was a 11.0.1 build which is old when talking about M1 support. 

> cirrus-ci setup appears to be hampered by their M1 being a VM with zeroed or atypical sysctl entries, brew fails to install just about anything related to python/numpy)

Shameless plug (:smile:), you could use conda.

**Comment by martin-frbg** [comment]
Sure, but how do I get conda there when `brew install --cask conda` (or anaconda, or whatever) explodes with `unexpected method "arch" called on` (lots of dependencies) -- but same goes for pip

**Comment by isuruf** [comment]
```
curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
bash Mambaforge-$(uname)-$(uname -m).sh -b -p $HOME/mambaforge
source $HOME/mambaforge/bin/activate
```

**Comment by martin-frbg** [comment]
Thank you, I got it working now. (And tests pass as the installation obviously picked up your build openmp_hcb59c3b_1 from two days ago that uses TARGET=ARMV8 as a workaround)

**Comment by kburns** [comment]
Thanks @martin-frbg and @isuruf for drilling down into this!  I'm happy to close since it seems like there's nothing to do here on the openblas side. 

@isuruf, do you think the current TARGET=ARMV8 build on conda-forge is the right solution for the time being, or is fixing the underlying gfortran issue and change back to TARGET=VORTEX something that might happen soon?  Definitely not trying to rush anybody -- the speed here has been really impressive -- I'm just wondering if we should change things downstream to link to that build at this point, or if holding off a few more days makes sense.  Thanks again!

**Comment by isuruf** [comment]
> Thank you, I got it working now. (And tests pass as the installation obviously picked up your build openmp_hcb59c3b_1 from two days ago that uses TARGET=ARMV8 as a workaround)

Great. You can install `libopenblas=0.3.21=*_0` to get the old build. (btw, Matti sent you an email about getting you SSH access to a M1)

> is fixing the underlying gfortran issue and change back to TARGET=VORTEX something that might happen soon? 

Working on updating to gfortran 11.3 in https://github.com/conda-forge/gfortran_impl_osx-64-feedstock/pull/48

**Comment by isuruf** [comment]
@kburns, I uploaded a TARGET=VORTEX build with gfortran 11.3 which should not have the errors.

**Comment by kburns** [comment]
Great, thanks!
