### ISSUE TITLE
Default compilers and compilation flags for optimal performance on most relatively recent machines

### ISSUE THREAD

**Issue by sj90101** [xianyi/OpenBLAS#3736]
Hi,

First, many thanks for your great work! It seems that ubuntu only has prebuilt amd64 version of openblas, which is 5-6 times
slower than mkl on my machine with Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz. When I tried to build the library on my own using default settings, openblas is still slower than mkl by a factor of 3. So I tried to set CC=gcc, FC=gfortran,
COMMON_OPT += -O3 -march=native -fPIC -funroll-loops, and openblas is slower than mkl by a factor of 2. My question is,
could you please change relevant files to set the right compilers and compilation flags so that openblas has optimal performance on relatively recent machines? This is relatively easy to do, but has enormous impact on the actual performance of openblas. Default setting CC=cc, gfortran=f77 is really outdated for most machines. And compilation flags -O2 ... do not seem to be optimal. I very much would like to see that openblas is as good as mkl at currently popular laptops and workstations, just as gcc is now as good as or even better than intel compilers. This is really a very small set of all available machines, so hopefully it may not require too much effort.

Many thanks again and best regards,
Shidong

**Comment by martin-frbg** [comment]
"set the right compiler" does not really make sense when we want OpenBLAS to build with whatever compiler a user has at their disposal - gcc,llvm,intel,aocc,nvidia,craycc,... and "best options" will vary accordingly. So the default is to try to detect the compiler, while allowing the user to provide specific choices of CC,FC,CLAGS etc.
Collecting reliable benchmark data is also a non-trivial task,and there is no sizable team or organization behind OpenBLAS - contributions welcome.

Lastly it should be noted that the LAPACK functions provided with OpenBLAS are almost all direct copies of the unoptimized Reference implementation also known as "netlib" LAPACK. Its performance is not expected to rival MKL. On the BLAS side, not all kernels are optimized for modern hardware, which _may_ have more impact than compiler options. Again a question of time and expertise.

**Comment by brada4** [comment]
@sj90101 please show the test code that yields 3x speed difference. 
Ubuntu build should use OPENBLAS_CORETYPE=HASWELL for your CPU as Ubuntu most likely pre-dates its production.
gcc version?
Ubuntu version?

**Comment by brada4** [comment]
>  prebuilt amd64 version 

Debian and derivatives call it amd64 since the time before Intel made compatible CPUs, rather old version packaged lacks cpuid code to identify your CPU as Haswell-equivalent (i.e Intel CPU with AVX2 and no AVX-512), you may help it setting variable, or build new version with latest CPUID code similar to https://github.com/xianyi/OpenBLAS/wiki/Faq#debianlts
default build is -O2 -march-haswell for C and -O2 -march=core3 -mtune=generic fro fortran.
cc and f77 are handled by alternatives in Ubuntu (update-alternatives --list), so you can choose best compiler like clang or later gcc etc.
It is rather interesting that your code gets 1.5x speedup by -O2 -> -O3 change - could you try to bisect which of -O3 options gives that? https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html

**Comment by sj90101** [comment]
Thanks for very useful suggestions. After recompilation with correct flags, openblas is almost as fast as intel mkl. The difference in my first email is mostly due to the difference in gfortran and ifort. My code is very long, but it uses dgemm and zgemm. 

Many thanks again.

**Comment by brada4** [comment]
_GEMM is written in AVX2 assembly, compiler plays no role there, OPENBLAS_CORETYPE=HASWELL should enable that if auto-detection fails as in case with Ubuntu build.
For LAPACK code mkl > ifort > -O3 > -O2, especially if you have loops that do something like memcpy in a loop and the likes of low FLOPS per memory access.
