### ISSUE TITLE
OpenBLAS for iPhone iOS (ARMv8) cannot used LAPACKE

### ISSUE THREAD

**Issue by tppqt** [xianyi/OpenBLAS#3741]
I followed the step https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-iPhone-iOS-(ARMv8)#how-to-build-openblas-for-iphoneios, but the resut openBLAS.a not contain LAPACKE_sgesvd、LAPACKE_dgesvd... why , I am a NewBee，can anybody help me

**Comment by martin-frbg** [comment]
does it have any LAPACKE function entries ? and did you get any error messages during the build ?

**Comment by martin-frbg** [comment]
Possibly the instructions in the wiki are outdated and unnecessarily complicated, at least our Azure CI job appears to build just fine with just
```
     CC=/Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
     CFLAGS= -O2 -Wno-macro-redefined -isysroot /Applications/Xcode_12.4.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.4.sdk -arch arm64 -miphoneos-version-min=10.0
     make TARGET=ARMV8 DYNAMIC_ARCH=1 NUM_THREADS=32 HOSTCC=clang NOFORTRAN=1
```

**Comment by tppqt** [comment]
> does it have any LAPACKE function entries ? and did you get any error messages during the build ?

the build was success，but when I put my openBLAS.a in my Xcode project，and used LAPACKE_sgesvd .... and so on，it ocurred  error:
Undefined symbols for architecture arm64:
  "_LAPACKE_dgetrf", referenced from:
      _utility_dinv in libAmbiSonicsSDK.a(saf_veclib.o)
  "_LAPACKE_cgetrf", referenced from:
      _utility_cinv in libAmbiSonicsSDK.a(saf_veclib.o)
  "_LAPACKE_dgetri", referenced from:
      _utility_dinv in libAmbiSonicsSDK.a(saf_veclib.o)
  "_LAPACKE_sgetri", referenced from:
      _utility_sinv in libAmbiSonicsSDK.a(saf_veclib.o)
  "_LAPACKE_spotrf", referenced from:
      _utility_schol in libAmbiSonicsSDK.a(saf_veclib.o)
  "_LAPACKE_dgesvd", referenced from:
      _utility_dpinv in libAmbiSonicsSDK.a(saf_veclib.o)
  "_LAPACKE_sposv", referenced from:
      _utility_sslslv in libAmbiSonicsSDK.a(saf_veclib.o)
  "_LAPACKE_cgesv", referenced from:
      _utility_cglslv in libAmbiSonicsSDK.a(saf_veclib.o)
  "_LAPACKE_zgesv", referenced from:
      _utility_zglslv in libAmbiSonicsSDK.a(saf_veclib.o)
  "_LAPACKE_cgetri", referenced from:
      _utility_cinv in libAmbiSonicsSDK.a(saf_veclib.o)
  "_LAPACKE_dgesv", referenced from:
      _utility_dglslv in libAmbiSonicsSDK.a(saf_veclib.o)
  "_LAPACKE_cposv", referenced from:
      _utility_cslslv in libAmbiSonicsSDK.a(saf_veclib.o)
  "_LAPACKE_sgesv", referenced from:
      _utility_sglslv in libAmbiSonicsSDK.a(saf_veclib.o)
  "_LAPACKE_sgetrf", referenced from:
      _utility_sinv in libAmbiSonicsSDK.a(saf_veclib.o)
  "_LAPACKE_cpotrf", referenced from:
      _utility_cchol in libAmbiSonicsSDK.a(saf_veclib.o)
  "_LAPACKE_cgeev", referenced from:
      _utility_ceig in libAmbiSonicsSDK.a(saf_veclib.o)
  "_LAPACKE_cggev", referenced from:
      _utility_ceigmp in libAmbiSonicsSDK.a(saf_veclib.o)
  "_LAPACKE_zggev", referenced from:
      _utility_zeigmp in libAmbiSonicsSDK.a(saf_veclib.o)
  "_LAPACKE_cheev", referenced from:
      _utility_cseig in libAmbiSonicsSDK.a(saf_veclib.o)
  "_LAPACKE_ssyev", referenced from:
      _utility_sseig in libAmbiSonicsSDK.a(saf_veclib.o)
  "_LAPACKE_zgesvd", referenced from:
      _utility_zpinv in libAmbiSonicsSDK.a(saf_veclib.o)
  "_LAPACKE_cgesvd", referenced from:
      _utility_csvd in libAmbiSonicsSDK.a(saf_veclib.o)
      _utility_cpinv in libAmbiSonicsSDK.a(saf_veclib.o)
  "_LAPACKE_sgesvd", referenced from:
      _utility_ssvd in libAmbiSonicsSDK.a(saf_veclib.o)
      _utility_spinv in libAmbiSonicsSDK.a(saf_veclib.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

and I used "grep LAPACKE_sgesvd openBLAS.a" ,found the openBLAS.a not contain this function，but the openBlas build for android are good.

**Comment by tppqt** [comment]
it work! thanks

**Comment by martin-frbg** [comment]
Thanks for confirming, I have updated the wiki page now.
