### ISSUE TITLE
NOFORTRAN: Install Warning

### ISSUE THREAD

**Issue by ax3l** [xianyi/OpenBLAS#3746]
Hi,

Thanks a lot for the no-Fortran build option, this is wonderful.

In Spack (https://github.com/spack/spack/pull/32398), I saw the following warning during `NOFORTRAN=1` build & install (which otherwise succeeded). I think this might be an upstream warning, but cannot spot the location yet:
```
expr: syntax error: unexpected argument 'cc]'
expr: syntax error: unexpected argument 'cc]'
```

Compiler & Platform:
- GCC 10.3.0
- x86_64 Ubuntu 20.04

Build:
```console
make -j8 CC=/usr/bin/gcc-10 MAKE_NB_JOBS=0 ARCH=x86_64 TARGET=SKYLAKEX NO_AVX512=1 NOFORTRAN=1 USE_LOCKING=1 USE_OPENMP=0 USE_THREAD=0 RANLIB=ranlib libs netlib shared
```

**Comment by martin-frbg** [comment]
expr is used to parse compiler version number output in a few Makefiles, looks like either there is a rogue call without a compiler name argument or your system has an expr that does not like GNU expr argument syntax
