### ISSUE TITLE
Build errors using Yocto

### ISSUE THREAD

**Issue by buddybu** [xianyi/OpenBLAS#3751]
here is my issue.  The compilation works great, but I am failing in the testing, which I would like to see complete at least once.  It seems to be picking up the local libc library rather than the cross compiled libc library.  is there a way to correct this?  

here is my error log:
`
x86_64-wrs-linux-gfortran -m64 -march=nehalem -mtune=generic -mfpmath=sse -msse4.2 -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/home/burnhaj/usb/JBT_BASE21/zelda/tmp-glibc/work/corei7-64-wrs-linux/openblas/0.3.21-r0/recipe-sysroot -O2 -Wall -frecursive -fno-optimize-sibling-calls -m64  -msse3 -mssse3 -msse4.1 -mavx -mavx2 -mavx2 -fno-tree-vectorize -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -Wl,-z,relro,-z,now -o sblat1 sblat1.o ../libopenblas_haswellp-r0.3.21.a -lm -lpthread -lgfortran -lm -lpthread -lgfortran -L/home/burnhaj/usb/JBT_BASE21/zelda/tmp-glibc/work/corei7-64-wrs-linux/openblas/0.3.21-r0/recipe-sysroot-native/usr/bin/x86_64-wrs-linux/../../lib/x86_64-wrs-linux/gcc/x86_64-wrs-linux/10.3.0 -L/home/burnhaj/usb/JBT_BASE21/zelda/tmp-glibc/work/corei7-64-wrs-linux/openblas/0.3.21-r0/recipe-sysroot-native/usr/bin/x86_64-wrs-linux/../../lib/x86_64-wrs-linux/gcc -L/home/burnhaj/usb/JBT_BASE21/zelda/tmp-glibc/work/corei7-64-wrs-linux/openblas/0.3.21-r0/recipe-sysroot/lib64/../lib64 -L/home/burnhaj/usb/JBT_BASE21/zelda/tmp-glibc/work/corei7-64-wrs-linux/openblas/0.3.21-r0/recipe-sysroot/usr/lib64/../lib64/x86_64-wrs-linux/10.3.0 -L/home/burnhaj/usb/JBT_BASE21/zelda/tmp-glibc/work/corei7-64-wrs-linux/openblas/0.3.21-r0/recipe-sysroot/usr/lib64/x86_64-wrs-linux/10.3.0 -L/home/burnhaj/usb/JBT_BASE21/zelda/tmp-glibc/work/corei7-64-wrs-linux/openblas/0.3.21-r0/recipe-sysroot/usr/lib64/../lib64 -L/home/burnhaj/usb/JBT_BASE21/zelda/tmp-glibc/work/corei7-64-wrs-linux/openblas/0.3.21-r0/recipe-sysroot/lib64 -L/home/burnhaj/usb/JBT_BASE21/zelda/tmp-glibc/work/corei7-64-wrs-linux/openblas/0.3.21-r0/recipe-sysroot/usr/lib64  -lc
| OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 ./sblat1
| ./sblat1: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.32' not found (required by ./sblat1)
| make[1]: *** [Makefile:30: level1] Error 1
`

Here is my recipe:

`DESCRIPTION = "OpenBLAS is an optimized BLAS library based on GotoBLAS2 1.13 BSD version."`
`SUMMARY = "OpenBLAS : An optimized BLAS library"`
`AUTHOR = "Alexander Leiva <norxander@gmail.com>"`
`HOMEPAGE = "http://www.openblas.net/"`
`SECTION = "libs"`
`LICENSE = "BSD-3-Clause"`
``
`DEPENDS = "make libgfortran"`
``
`INHERIT += "make pkgconfig logging"`
``
`LIC_FILES_CHKSUM = "file://LICENSE;md5=5adf4792c949a00013ce25d476a2abc0"`
``
`SRC_URI = "https://github.com/xianyi/OpenBLAS/releases/download/v${PV}/OpenBlas-${PV}.tar.gz"`
`SRC_URI[md5sum] = "ffb6120e2309a2280471716301824805"`
`SRC_URI[sha256sum] = "f36ba3d7a60e7c8bcc54cd9aaa9b1223dd42eaf02c811791c37e8ca707c241ca"`
``
`EXTRA_OECONF = " -D BUILD_TESTING=OFF"`
``
`S = "${WORKDIR}/OpenBLAS-${PV}"`
``
`def map_arch(a, d):`
`        import re`
`        if re.match('i.86$', a): return 'HASWELL'`
`        elif re.match('x86_64$', a): return 'HASWELL'`
`        elif re.match('aarch32$', a): return 'CORTEXA9'`
`        elif re.match('aarch64$', a): return 'ARMV8'`
`        return a`
``
`def map_bits(a, d):`
`        import re`
`        if re.match('i.86$', a): return 32`
`        elif re.match('x86_64$', a): return 64`
`        elif re.match('aarch32$', a): return 32`
`        elif re.match('aarch64$', a): return 64`
`        return 32`
``
`do_compile () {`
`        oe_runmake HOSTCC="${BUILD_CC}"                                         \`
`                                CC="${TARGET_PREFIX}gcc ${TOOLCHAIN_OPTIONS}" `
`                                -D BUILD_TESTING=OFF \`
`                                PREFIX=${exec_prefix} \`
`                                CROSS_SUFFIX=${HOST_PREFIX} \`
`                                BINARY='${@map_bits(d.getVar('TARGET_ARCH', True), d)}' \`
`                                TARGET='${@map_arch(d.getVar('TARGET_ARCH', True), d)}'`
`}`
``
`do_install() {`
`		install -d ${D}${libdir}`
`		install -d ${D}${libdir}/cmake`
`		install -d ${D}${libdir}/pkgconfig`
`        oe_runmake HOSTCC="${BUILD_CC}"                                         \`
`                                CC="${TARGET_PREFIX}gcc ${TOOLCHAIN_OPTIONS}" \`
`                                PREFIX=${exec_prefix} \`
`                                CROSS_SUFFIX=${HOST_PREFIX} \`
`                                BINARY='${@map_bits(d.getVar('TARGET_ARCH', True), d)}' \`
`                                TARGET='${@map_arch(d.getVar('TARGET_ARCH', True), d)}' \`
`								MY_DEBUG="${PN}"\`
`                                DESTDIR=${D} \`
`                                install`
`		cp -r ${D}/usr/lib/* ${D}/usr/lib64/`
`		rm -rf ${D}/usr/lib`
`		rm -rf ${D}/usr/bin        rm -rf ${D}${libdir}/cmake`
``		
`		bbnote "FILES_${PN} = ${libdir}/lib${PN}*"`
`}`
``
`RDEPENDS_${PN}-dev = ""`
`RDEPENDS_${PN}-staticdev = ""`
``
``
`FILES_${PN}-libs = "${libdir}/*"`
``
`FILES_${PN}     += "/usr/lib64"`
`FILES_${PN}-dev = "${includedir} ${libdir}/lib${PN}.so"`
``
`INSANE_SKIP_${PN} += "staticdev"`
``

**Any thoughts?**

**Comment by buddybu** [comment]
I am building against version 0.3.21-r0

**Comment by martin-frbg** [comment]
Could be something wrong in your sysroot definition, or maybe you just need to set up LD_LIBRARY_PATH so that the cross-compiled testcases can find their native libc. (The normal build process is not expected to actually run the tests when cross-compiling, I assume you are invoking that part manually ? Or is this not recognized as a crossbuild situation perhaps - should be obvious from the generated Makefile.conf having "CROSS=1" somewhere in it)

**Comment by buddybu** [comment]
I have corrected my issue.  Here is the resulting bitbake recipe:

DESCRIPTION = "OpenBLAS is an optimized BLAS library based on GotoBLAS2 1.13 BSD version."
SUMMARY = "OpenBLAS : An optimized BLAS library"
AUTHOR = "Alexander Leiva <norxander@gmail.com>"
HOMEPAGE = "http://www.openblas.net/"
SECTION = "libs"
LICENSE = "BSD-3-Clause"

DEPENDS = "libgfortran"

TARGET_ARCH = "x86_64"

LIC_FILES_CHKSUM = "file://LICENSE;md5=5adf4792c949a00013ce25d476a2abc0"

SRC_URI = "https://github.com/xianyi/OpenBLAS/releases/download/v${PV}/OpenBlas-${PV}.tar.gz"
SRC_URI[md5sum] = "ffb6120e2309a2280471716301824805"
SRC_URI[sha256sum] = "f36ba3d7a60e7c8bcc54cd9aaa9b1223dd42eaf02c811791c37e8ca707c241ca"


EXTRA_OEMAKE = "\
	CROSS=1 \
	BUILD_TESTING=NO \
    PREFIX=${exec_prefix} \	
	CROSS_SUFFIX=${HOST_PREFIX} \
	BINARY=64 \
	TARGET='HASWELL'	\
	"

S = "${WORKDIR}/OpenBLAS-${PV}"

RDEPENDS_${PN}-dev = ""
RDEPENDS_${PN}-staticdev = ""


FILES_${PN}-libs = "${libdir}/*"

FILES_${PN}     += "/usr/lib64"
FILES_${PN}-dev = "${includedir} ${libdir}/lib${PN}.so"

INSANE_SKIP_${PN} += "staticdev"

**Comment by martin-frbg** [comment]
Ah, ok. Thanks for posting the updated recipe here.
There is probably no safe way to detect all cases of cross-compiling (at least not without keeping a list of cross-compiler names), IIRC early on we used to check for dashes in the compiler name but obviously that did not work well with vendor-gcc, gcc-7 etc.

**Comment by buddybu** [comment]
Yeah, instead of checking for compilers and such, I ended up just coding to target system and dev tools.
