### ISSUE TITLE
Fortran detection causing issues with AVX512 building-Gnu fortran12 

### ISSUE THREAD

**Issue by FCLC** [xianyi/OpenBLAS#3755]
Platform: 

<details><summary>Neofetch: </summary>

OS: Pop!_OS 22.04 LTS x86_64 

Kernel: 5.19.0-local-fclc 

Shell: bash 5.1.16 

CPU: 12th Gen Intel i7-12700K (16) 

GPU: AMD ATI Radeon RX 5600 OEM/5600 XT / 5700/5700 XT 

GPU: Intel AlderLake-S GT1 

Memory: 13152MiB / 31801MiB 

Compilers: GCC/G++/Gfort-12
</details>

Whilst I work on PR #3754 I've come across a problem with detection and propagation of AVX512 which will subsequently cause a build to fail. 

Initially, any build target including `make, make TARGET=SKYLAKEX, make TARGET=COOPERLAKE` etc. (targets that enable AVX512) would fail.

I was able to track this down to my gfortran-12 being linked to `/usr/bin/fortcom` where as OpenBLAS expected `/usr/bin/fortc`

thinking this could be related I then tried soft linking gfortran-12 to fortc. 

This allowed AVX512 builds when using a specified target. 

Currently this only leaves builds using `make` with no target being problematic. 

Something else I've noticed is that, while building with --silent (to make catching errors easier to find) OpenBLAS still seems to be strugling with Gfortran-12, sending out the error message of
`OpenBLAS: Detecting fortran compiler failed. Can only compile BLAS and f2c-converted LAPACK.`

**Comment by martin-frbg** [comment]
There is nothing in the build system that expects either "fortcom" or "fortc", however initial detection tries to use the environment variable FC (which on your system may be set erroneously to either name). If FC is not set, a fixed list of executable names is tried, which happens to contain "fort" without a terminal "c" among others, and plain "gfortran" without any version number.  Most likely there is something wrong with your build host, such as wrong FC variable or missing symlinks.

**Comment by FCLC** [comment]
> There is nothing in the build system that expects either "fortcom" or "fortc", however inizial detection tries to use the environment variable FC (which on your system may be set erroneously to either name). If FC is not set, a fixed list of executable names is tried, which happens to contain "fort" without a terminal "c" among others, and plain "gfortran" without any version number. Most likely there is something wrong with your build host, such as wrong FC variable or missing symlinks.

Strange, as I installed directly from the package manager. Just in case I also re-sourced bashrc for good measure to no avail. 

The interesting part is that the build used to fail before symlinking to fortc specifically and using target

so
make + no fortc = fail 
make TARGET=SAPPHIRERAPIDS + no fortc = fail

make + fortc = fail

make TARGET=SAPPHIRERAPIDS + fortc = success

All circumstances com back with:
`OpenBLAS: Detecting fortran compiler failed. Can only compile BLAS and f2c-converted LAPACK.`


As an extra measure I've attempted with the Intel fortran compiler (2021.5.0) to the same result. 

after returning /usr/bin/fortc to gfortran-12, I manually set FC to gfortran12. 

see attached screen shots 
<img width="672" alt="Screen Shot 2022-09-05 at 6 22 35 PM" src="https://user-images.githubusercontent.com/20584423/188517265-db96a055-2a1d-43c8-8e65-b03d3567cc77.png">
<img width="657" alt="Screen Shot 2022-09-05 at 6 24 51 PM" src="https://user-images.githubusercontent.com/20584423/188517267-ff26f2c7-79ff-45ff-b06d-30db3824b734.png">

**Comment by martin-frbg** [comment]
Now looks like recent breakage from #3722 (excessive quoting added to Makefile.prebuild) but how your fortc Voodoo manages to work around this is still a mystery to me. (Or are you using fortc interchangeably with FC here ? I am not aware of any actual compiler of that name, nor a convention that "fortc" should be the default Fortran compiler name  on a system, similar to "cc")

**Comment by FCLC** [comment]
> how your fortc Voodoo manages to work around this is still a mystery to me

I'm not certain, but I remember seeing it somewhere. 

> (Or are you using fortc interchangeably with FC here ? I am not aware of any actual compiler of that name, nor a convention that "fortc" should be the default Fortran compiler name on a system, similar to "cc")

I'm using and testing each separately (testing fortc and fc).

I've also tried linking gfortran-12 to /usr/bin/fc but the result is the same as prior, where I get a complaint about fortran version detection as well as avx512 errors if I don't specify an avx512 target (or avx2 target If that was wanted).

I've also added gfortran-11.2 to the list of attempted compilers with no success.

**Comment by FCLC** [comment]
Just pulled  #3758 and checked in a fully clean directory to see what the results would be, seems to have done the trick for detecting fortran. 
![image](https://user-images.githubusercontent.com/20584423/188882614-b0a1f156-9899-4b56-b65a-737cd14450ac.png)

Still have the detection issue with avx512 when target isnt specified, but that's a separate issue.

**Comment by martin-frbg** [comment]
I had installed  Pop!_OS 22.04 LTS in a VM in the meantime, and found that this appears to install a /usr/bin/gfortran" symlink along with at least the gfortran-11 package (which matches the system default gcc-11), just like other distributions do. So I think there should be no need to add versioned program names to the list in f_check (which would incur the risk of picking a gfortran that does not match the selected gcc)
