### ISSUE TITLE
How can i cross-complie use mac m1

### ISSUE THREAD

**Issue by Veango** [xianyi/OpenBLAS#3757]
I want to complie arch x86_64 with mac m1 that I can use in iphonesimulator, please tell me how to do

**Comment by brada4** [comment]
It is not well tested:
https://clang.llvm.org/docs/CrossCompilation.html
And gfortran is certainly not usable, thus 
`make CC="clang -target x86_64-unknown-unknown" TARGET=GENERIC DYNAMIC_ARCH=1 FC=none`

**Comment by Veango** [comment]
Like this?
     CC=/Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang

CFLAGS= -O2 -Wno-macro-redefined -isysroot /Applications/Xcode_12.4.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.4.sdk -arch arm64 -miphoneos-version-min=10.0

make CC="clang -target x86_64-unknown-unknown" TARGET=GENERIC DYNAMIC_ARCH=1 FC=none

**Comment by brada4** [comment]
So you want to build aarch64 binary for iphone on M1? not x86_64 intel one? Follow normal guide: https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-iPhone-iOS-(ARMv8)

**Comment by Veango** [comment]
> 

No，i want to build x86_64 binary for iphonesimulator, but my mac is m1 cpu

if I used TARGET=GENERIC clang make some error like "clang: error: the clang compiler does not support '-march=native'"

**Comment by brada4** [comment]
you need to replace -arch arm64 with x86_64 in line from faqto build for x86_64 simulator as opposed to real aarch phone? 
You need to set TARGET= to something basic like GENERIC or CORE2 if cross-building.
EDIT I missed out HOSTCC=clang -> that is to denote cross-compilation.

**Comment by Veango** [comment]
Yes,i tried  to set arch and hostcc. But i don't know witch TARGET set is suitable for m1 cpu to build x86_64

**Comment by brada4** [comment]
Which CPU is suitable for x86_64 in iphone simulator, CORE2 certainly

**Comment by Veango** [comment]
OS_NAME="$(echo $(uname -s) | tr '[:upper:]' '[:lower:]')"

IOS_VERSION=15.5
MIN_IOS_VERSION=10.0
MACOSX_VERSION=12.3

DEVROOT=$(xcode-select -print-path)
BLAS_ARCH=CORE2
HOST=x86_64-apple-darwin
ARCHFLAGS=""
platform=iPhoneSimulator
os=iphonesimulator
arch=x86_64

TOOLCHAIN_PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
SYSROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/${platform}.platform/Developer/SDKs/${platform}.sdk

make -C OpenBLAS TARGET=${BLAS_ARCH} BINARY=64 ONLY_CBLAS=1 AR="$(xcrun --sdk ${os} --find ar)" \
    CC="$(xcrun --sdk ${os} --find clang) -isysroot $SYSROOT_PATH -arch ${arch} -miphoneos-version-min=10.0" \
    HOSTCC="$(xcrun --find clang) -isysroot $(xcrun --show-sdk-path)" \
    ARM_SOFTFP_ABI=1 USE_THREAD=0 NUM_THREADS=1 NO_EXPRECISION=1 -j 4
make -C OpenBLAS install PREFIX=./local

thank you so much , is this script right?

**Comment by brada4** [comment]
looks quite elabprate, do `make clean` between builds

**Comment by Veango** [comment]
Ok，Thanks again

**Comment by martin-frbg** [comment]
I have now gotten it to compile (in Cirrus CI) with the following variation of the script from our wiki 
```
  export CC=/Applications/Xcode-13.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
  export CFLAGS="-O2 -Wno-macro-redefined -isysroot /Applications/Xcode-13.4.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.5.sdk -arch x86_64 -miphoneos-version-min=10.0"
  make TARGET=CORE2 DYNAMIC_ARCH=1 NUM_THREADS=32 HOSTCC=clang NOFORTRAN=1
```
but a small fix to the Makefile in kernel/ is also necessary to make it compile the Haswell and Zen parts of DYNAMIC_ARCH,
as the Apple clang apparently (now?) requires `-mfma` alongside `-mavx2` to actually enable all AVX2 instructions.

**Comment by martin-frbg** [comment]
fixed "kernel/Makefile" included here for convenience
[Makefile.zip](https://github.com/xianyi/OpenBLAS/files/9567665/Makefile.zip)
