### ISSUE TITLE
Unable to conda install package libopenblas

### ISSUE THREAD

**Issue by datamongerbonny** [xianyi/OpenBLAS#3762]
"The package for libopenblas located at .../pkgs/libopenblas-0.3.21-openmp_h429af6e_3
appears to be corrupted. The path 'lib/libopenblasp-r0.3.21.dylib'
specified in the package manifest cannot be found."

**Comment by martin-frbg** [comment]
That looks like an issue for https://github.com/conda-forge/openblas-feedstock/issues or possibly just a server or network fault

**Comment by martin-frbg** [comment]
Please inquire with the conda-forge project if the problem persists. Distribution packaging is outside our scope.
