### ISSUE TITLE
GNU Fortran compilers misidentified as Cray compilers on Cray machines

### ISSUE THREAD

**Issue by jamesgabbard** [xianyi/OpenBLAS#3775]
I work primarily on the NERSC Cori and Perlmutter machines, which are maintained by Cray but offer compilers from several different vendors. The recent PR #3712 added support for Cray compilers, but on Cray machines it incorrectly identifies standard GNU compilers as Cray compilers. This causes compilation errors when flags intended for Cray compilers are passed to gfortran.

In more detail, when the `f_check` script performs a test compilation on `ftest.f` using GNU Fortran 11.2.0, the output on the NERSC machines is  
```
        .file   "ftest.f"
        .text
        .p2align 4
        .globl  zhoge_
        .type   zhoge_, @function
zhoge_:
.LFB0:
        .cfi_startproc
        pxor    0mm1, 0mm1
        movapd  0mm1, 0mm0
        ret
        .cfi_endproc
.LFE0:
        .size   zhoge_, .-zhoge_
        .ident  "GCC: (GNU) 11.2.0 20210728 (Cray Inc.)"
        .section        .note.GNU-stack,"",@progbits
```
Importantly, both the words `GNU` and `Cray` appear, and because `Cray` is checked first in `f_test` the compiler is identified as a Cray compiler. This causes several compilation issues, including no `-fopenmp` flags even when `USE_OPENMP = 1` and no additional libraries identified as necessary when linking FORTRAN code.

**Comment by martin-frbg** [comment]
Could you please check if reordering the two cases in `f_check` does fix this ? Unfortunately I do not have access to these systems, and while misidentifying `vendor` would almost certainly break library detection I do not see how the `-fopenmp` would get suppressed.

**Comment by jamesgabbard** [comment]
After reordering the two cases I can compile with no issues.

I'm not familiar with Cray compilers, but based on the Makefiles it seems that OpenBLAS handles Cray + OpenMP as follows
https://github.com/xianyi/OpenBLAS/blob/667d0e0b48ee1170ef0e918545cc31cc30a910c1/Makefile.system#L1287-L1298
The only action is to add `-O noomp` when OpenMP is NOT requested, which is not sufficient if the underlying compiler is actually gfortran.
