### ISSUE TITLE
What's the reason for TerminateThread?

### ISSUE THREAD

**Issue by lb90** [xianyi/OpenBLAS#3785]
Hi! Many thanks for the excellent work!

I see that OpenBLAS on Windows may end up calling TerminateThread. This is very dangerous API which should never be used under normal circumstances, as described in https://github.com/xianyi/OpenBLAS/commit/1f6071590d5b4fa3b52aa1456a9648ae354b2c7a

May I ask what's the reason for the TerminateThread call? I see that it's also excluded in UWP builds, could we just remove it?

Thank you very much!!!
Luca

**Comment by brada4** [comment]
Linux equivalent is https://github.com/xianyi/OpenBLAS/blob/eece0dfd143013ca6572a8d3750af159209eb019/driver/others/blas_server.c#L1083

I think windows API does not have equivalent, one has to post CloseThread to the thread so it goes away, if it is busy at the point, i.e inside BLAS computation the terminatethread is the only option. i.e we shoot the cannon at the sparrow, and assume it went away, while we could try to whistle n clap first.

**Comment by martin-frbg** [comment]
From `git blame`, this appears to have been originally put in by xianyi (https://github.com/xianyi/OpenBLAS/commit/a2942456ef7c88fba952851bdd94c1951c59dd4d) to "fix" a potential hang when freeing the dll (reported as #307).
There has been an effort to remove this code in #2350, but only a small part of that PR got merged as the key change was found to cause freezes in other code (namely GIMP which does a rapid load/unload cycle of all its dependencies on startup)

**Comment by brada4** [comment]
I think it is a call for some softer albeit more complex thread exit

**Comment by lb90** [comment]
Thanks for the informations! I guess I can work on that
