### ISSUE TITLE
Does OpenBLAS support lanugae C (not C plus plus)?

### ISSUE THREAD

**Issue by XiDianZuoYun** [xianyi/OpenBLAS#3792]
It's hard to finish our program with C++ on our platform, actually we shall follow MISRA C 2012. Can I use OpenBlas with C interface without any wrapper or Change?

**Comment by brada4** [comment]
It is written in C and supports CBLAS that in turn can be used by C++ via including C header called cblas.h, actually it can be compiled to not export original Fortran API. See Makefile.rule.

**Comment by martin-frbg** [comment]
`#include <cblas.h>` in your program for BLAS functions, and  `include <lapacke.h>` for LAPACK functions.
