### ISSUE TITLE
utest fails using ARM Cortex-A57 - recipe for target 'openblas_utest' failed

### ISSUE THREAD

**Issue by signebramsen** [xianyi/OpenBLAS#3797]
When trying to build OpenBLAS on an ARM Cortex-A57 with: 
'make -j 4 TARGET=CORTEXA57' or 'make TARGET=CORTEXA57'
the utest fails as follows:

```
../libopenblas_cortexa57p-r0.3.21.dev.a(ssyrk_thread_UT.o): In function inner_thread':
syrk_k.c:(.text+0x658): undefined reference to aarch64_swp8_acq_rel'
syrk_k.c:(.text+0x804): undefined reference to `aarch64_swp8_acq_rel'
../libopenblas_cortexa57p-r0.3.21.dev.a(ssyrk_thread_LN.o): In function inner_thread':
syrk_k.c:(.text+0x688): undefined reference to aarch64_swp8_acq_rel'
syrk_k.c:(.text+0x840): undefined reference to `aarch64_swp8_acq_rel'
../libopenblas_cortexa57p-r0.3.21.dev.a(dsyrk_thread_UT.o): In function inner_thread':
syrk_k.c:(.text+0x650): undefined reference to aarch64_swp8_acq_rel'
../libopenblas_cortexa57p-r0.3.21.dev.a(dsyrk_thread_UT.o):syrk_k.c:(.text+0x7fc): more undefined references to `aarch64_swp8_acq_rel' follow
collect2: error: ld returned 1 exit status
Reaping losing child 0x559d9bf010 PID 25930 
Makefile:48: recipe for target 'openblas_utest' failed
```

It seems as the binary file 'openblas_utest' is is not created. 

Any suggestions on how to fix it?

**Comment by martin-frbg** [comment]
What kind of system is this ? Googling the undefined reference suggests it is a Debian installation using musl-libc, where the compiler apparently does not inline atomic operations but expects them to be present in the libc (which does not appear to be true for musl). According to https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1802783.html adding `-mno-outline-atomics` to the CFLAGS might help

**Comment by signebramsen** [comment]
It is a Jetson TX2 running Ubuntu 18.04.6. I'm not that familiar with Makefiles, so does that mean to change:

```
$(UTESTBIN): $(OBJS)
        $(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^ ../$(LIBNAME) $(EXTRALIB) $(FEXTRALIB)

```
To:

```
$(UTESTBIN): $(OBJS)
        $(CC) $(CFLAGS) -mno-outline-atomics $(LDFLAGS) -o $@ $^ ../$(LIBNAME) $(EXTRALIB) $(FEXTRALIB)
```

This change doesn't work. It gives the same error plus this extra error: 

```
make[1]: Leaving directory '/../OpenBLAS/utest'
Makefile:155: recipe for target 'tests' failed
make: *** [tests] Error 2
```

**Comment by martin-frbg** [comment]
Your change is technically correct, but you need to recompile all of OpenBLAS with this option, not just utest - best uncomment the `COMMON_OPT = -O2` line in the toplevel `Makefile.rule` and add it there

**Comment by signebramsen** [comment]
When doing so, it fails with the following for make:

`gfortran: error: unrecognized command line option ‘-mno-outline-atomics’; did you mean ‘-fno-inline-atomics’?`

We tried to change it to that but that also fails.

However, we tried to run utest seperately and it fails with this now:

`test_potrs.o: In function __ctest_potrf_bug_695_run':
test_potrs.c:(.text+0xd8): undefined reference to zpotrs_'
test_kernel_regress.o: In function __ctest_kernel_regress_skx_avx_run':
test_kernel_regress.c:(.text+0xec): undefined reference to LAPACKE_dgesvd'
collect2: error: ld returned 1 exit status
Reaping losing child 0x55b0215d90 PID 20793 
Makefile:48: recipe for target 'openblas_utest' failed
make: *** [openblas_utest] Error 1`

**Comment by martin-frbg** [comment]
Hm, that's unfortunate - I did not expect gfortran to error out just because of an unknown option. (This then led to an incomplete build, which causes the new error.) So next try, please comment out the line in Makefile.rule again and instead add the `-mno-outline-atomics` to the `CCOMMON_OPT` line after the `ifeq ($(CORE), CORTEXA57)` in Makefile.arm64

**Comment by signebramsen** [comment]
It seems the system also had different versions of gcc, g++ and gfortran, but after changing them to 9.4 and changing mno-outline-atomics to the Makefile.arm64 it worked! Thank you for helping :-)

**Comment by martin-frbg** [comment]
If it had different compilers, I wonder if using the most recent availble version would have worked even without the extra option. But I do not have a Jetson system for testing, and there are very few google hits for this problem (some suggesting it is a compiler packaging problem, wrong libgcc_s.so e.g. https://bugzilla.redhat.com/show_bug.cgi?id=1830472) Not sure if/how to handle this in the OpenBLAS makefiles by default at this point...

**Comment by brada4** [comment]
It is ought to reduce CPU generation in presence of archaic compiler (omit TARGET option for native build)
Ubuntu 18 gcc 7 i.e gcc/gfortran used for whole system is completely sufficient.
