### ISSUE TITLE
Provide documentation for software distributions

### ISSUE THREAD

**Issue by lazka** [xianyi/OpenBLAS#3798]
As a distro packager without much insight into openblas it's not very clear to me how a software distribution (like a Linux distro, homebrew, MSYS2 etc.) should ideally build openblas and package it, with the goal of providing a generic package, or a set of packages, that can be re-used by other packages. They all seem to handle it slightly differently:

* Arch Linux: https://github.com/archlinux/svntogit-community/blob/packages/openblas/trunk/PKGBUILD
* MSYS2: https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-openblas/PKGBUILD
* homebrew: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/openblas.rb
* Debian: https://salsa.debian.org/science-team/openblas/-/blob/master/debian/rules

There is probably no easy answer for this, but maybe there could be some recommendations/tips/tricks in the wiki? Maybe it's already there and I missed it somehow.

**Comment by martin-frbg** [comment]
There is indeed no easy answer, much will depend on other design choices made by the respective distributors - do they want a monolithic library comprising both BLAS and LAPACK (plus or minus their C interface libraries CBLAS and LAPACKE), do they want to support programs that utilize OpenMP, etc. "Historically" OpenBLAS (and the original GotoBLAS of Kazushige Goto before it) was a source-only package that was expected to be compiled according to the individual user's needs and I still consider packaging to be outside the scope of the project.

**Comment by lazka** [comment]
I see, thanks. This at least means I didn't miss anything obvious :)

feel free to close this then

**Comment by brada4** [comment]
Among obvious - Fedora + EL EPEL build https://src.fedoraproject.org/rpms/openblas/blob/rawhide/f/openblas.spec

There are multiple OpenMP implementations even on Windows (intel iomp, clang openmp, gomp and ms-openmp)
They do not interop even exported functions are identically named, often even identically prototyped. Like clang and gomp in same process in Linux yield  crashes aka "unpredictable behaviour" aka "DLL Hell" if meeting in same process. 
One could wish to settle on MS-OPENMP to avoid shipping extra redist in a cross-compiled product.

**Comment by brada4** [comment]
For the other issue on igraph - probably single-threaded openblas with locking (see Makefile.rule) could serve  in the meantime.

**Comment by rgommers** [comment]
@lazka the docs added in gh-4165 were hopefully what you were looking for? I'd be happy to take any input and add or tweak things in a follow-up PR as needed.

@brada4 good points on OpenMP compatibility issues. We've seen those a lot in the Python ecosystem, in particular with `libgomp` and `libiomp` mixing on Linux. I documented a number of the issues at https://pypackaging-native.github.io/key-issues/native-dependencies/blas_openmp/. It's probably a little out of scope for OpenBLAS docs I'd think, but if there's something to clarify either in the doc added in gh-4165 or in the pypackaging-native docs, I'd be happy to do so too.

**Comment by brada4** [comment]
It is summarized in scipy quite well - if you use openmp you need to use same compiler(version) for whole binary/process.

If you use nested parallelism from different frameworks you land with N^2 threads which is peanuts with few CPUs as long as L+1 cache covers the rise, but on more it yields RAM<->L1 thrashing and no performance cf normal operation.

Basically `grep omp.so /proc/<pid>/maps` and if you see 2 loaded you are in the bad.

**Comment by martin-frbg** [comment]
I _think_ I have seen claims of programs even getting stuck due to having both the GNU and LLVM omp library loaded (though that could be due to a bug in either). Not sure if we cover this in the FAQ in the wiki already, but I guess that would be a place for it.

**Comment by rgommers** [comment]
Oh yes, that's definitely a problem too. I think (a) if any two OpenMP libraries get loaded at the same time you're already in a not so good place and potentially in for trouble, and (b) GNU OpenMP is extra problematic because it isn't fork-safe (which in Python with users heavily using `multiprocessing` is pretty painful).

**Comment by brada4** [comment]
b) https://github.com/xianyi/OpenBLAS/blob/develop/utest/test_fork.c contributions welcome if you have test case failing GOMP.

**Comment by rgommers** [comment]
Thanks @brada4! I'll have to think a bit about whether the things I have in mind could be added there. Given that the failure modes are typically involving Python + 2 OpenMP libs, it seems a little complicated to have them in `test_fork.c`.

**Comment by brada4** [comment]
You implied GOMP alone, if that is the case, it is a very good place that OpenBLAS invalidates library at build time.
Obviously we will not get both libs at once in simple tests.
