### ISSUE TITLE
Segfaults with scipy/openblas  since 4989e039a5 

### ISSUE THREAD

**Issue by carlkl** [xianyi/OpenBLAS#3803]
Since ['Define SBGEMM_ALIGN_K for DYNAMIC_ARCH build'](https://github.com/xianyi/OpenBLAS/commit/4989e039a5b37de140b41df9a042720599336e29) I get segfaults and failures with scipy.test() in the following setting:

OS: Windows 64-bit
Compiler: msys2 GCC-12
OpenBLAS: [4989e039a5 ](https://github.com/xianyi/OpenBLAS/commit/4989e039a5b37de140b41df9a042720599336e29)
Python: vanilla CPython-3.10
Scipy: local scipy-meson build 

No further examinations were carried out right now other than narrowing down the problem to the mentioned commit.

**Comment by martin-frbg** [comment]
Can you be more specific about your build please ? It seems surprising to me that this particular commit would cause segfaults (where?) on an unrelated platform - do the scipy tests even use bfloat16 ?

**Comment by carlkl** [comment]
In `kernel/setparam-ref.c` the parameter `align_k` was removed, and _this_ is related to a Windows `DYNAMIC_ARCH` build, maybe by accident, in this commit.

**Comment by martin-frbg** [comment]
uh-oh, there is a stray "1" in kernel/setparam-ref.c as a leftover from the initial placement of the "align_k"....

**Comment by carlkl** [comment]
Maybe (wild guess) related to: https://github.com/xianyi/OpenBLAS/issues/3801?

**Comment by carlkl** [comment]
I will try to test this PR with scipy later this evening.

**Comment by martin-frbg** [comment]
unlikely to be related to 3801 as I only merged the "offending" PR yesterday while the (original) Julia ticket is a week old. (plus I don't think they use bleeding-edge builds in Julia, so more likely something to do with "recent" LAPACK 3.10.1 or a general (Windows-specific?) threading issue that only happened to be "felt" now

**Comment by carlkl** [comment]
I can confirm, that with [Remove excess initializer (leftover from rework of PR 3793) ](https://github.com/xianyi/OpenBLAS/pull/3804) scipy.test() is running without failures and segfaults again.
