### ISSUE TITLE
Building OpenBLAS v0.3.21 with spack stop working

### ISSUE THREAD

**Issue by fspiga** [xianyi/OpenBLAS#3805]
See documented issue here: https://github.com/spack/spack/issues/33693

**Comment by martin-frbg** [comment]
Looks like you are building with DYNAMIC_ARCH support, i.e. all supported arm64 targets, and your compiler is too old to understand the `-march` option for the more recently added NeoverseN2 cpus. Which is a bit weird as this is guarded against in Makefile.arm64, requiring a sufficiently recent gcc.  You appear to be using 11.2(?), while a comment in the Makefile claims that 
N2 support was added in gcc-9.4

**Comment by martin-frbg** [comment]
Hmm, the "9.4 or newer" looks like copypasta from the N1 section, but gcc online docs suggest that 10.x onwards should support all of `+sve` `+sve2` `+bf16` feature modifiers as used in the `-march` option. @imzhuhl which gcc version(s) are you using to develop and test your contributions ?

**Comment by imzhuhl** [comment]
```bash
root@62869467bcb3:/# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/11/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.3.0-1ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04)
```

**Comment by brada4** [comment]
Your binutils are wildly outdated.
Especially for rocky8 https://github.com/xianyi/OpenBLAS/wiki/Faq#binutils - get latest scl devtoolset and from there binutils.

**Comment by brada4** [comment]
```
yum install gcc-toolset-11-binutils
scl enable gcc-toolset-11 $SHELL
```

**Comment by brada4** [comment]
@imzhuhl - the original spack issue is filed regarding rocky linux. 
basically `gcc -march=armv8.5-a+sve+sve2+bf16` calls `as -march=armv8.5-a+sve+sve2+bf16` under the hood.
For Ubuntu - append `--version` to both commands. Likely you need to set `as` and `ld` that got installed in "modernised" compiler in front of $PATH.

**Comment by martin-frbg** [comment]
@brada4 imzhuhl _contributed_ the NeoverseN2 code...

**Comment by brada4** [comment]
OK, got it. Ubuntu good, EL still keeps old binutils like 10yrs ago.

**Comment by fspiga** [comment]
> Your binutils are wildly outdated. Especially for rocky8 https://github.com/xianyi/OpenBLAS/wiki/Faq#binutils - get latest scl devtoolset and from there binutils.

Ah ha!I will look into this

**Comment by brada4** [comment]
You should report/fix the spack. Somebody fixed EL6 already there:
https://github.com/spack/spack/blob/078767946c1290b225a7b8e0d64241944dbfa1db/var/spack/repos/builtin/packages/gcc/package.py#L344

There is no problem with RedHat-s packaging - each gcc toolset contains unskippable own binutils in same directory as that gcc.
gcc-toolset-10 is 10.3, i.e will not support neoverse n2, you need 11 only.

**Comment by bernhardkaindl** [comment]
> gcc-toolset-10 is 10.3, i.e will not support neoverse n2, you need 11 only.

No, gcc-10.3 should be good enough, at least it is on Ubuntu 20.04.4 LTS:
```
> gcc-10 -march=armv8.5-a+sve+sve2+bf16 main.c;gcc-10 --version|head -1
gcc-10 (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0
```
Also, since gcc-5, the gcc-10.x releases are actually bugfix-only releases, no longer feature upgrades.

@imzhuhl:
That means, IMHO, it's should be a bug in the thinking of the OpenBLAS `Makefile.arm64` that they say one needs the
gcc-9.4 or gcc-10.4 version.

The only justification would be if 9.4 or 10.4 fixed some compiler bug which 9.3 / 10.3 did have with these -march flags, but that would be rather unusual.

**Comment by martin-frbg** [comment]
We can certainly argue whether 10.4 or 10.1 should be the minimum requirement (last time we saw a critical error with a minor release <4 was with 7.3), but @fspiga here is either not actually using the gcc-11 he has installed (through some kind of PATH mixup, or maybe having /usr/bin/cc softlinked to something ancient), or some other part of the toolchain on his system is outdated.

**Comment by bernhardkaindl** [comment]
Correct, one should obviously use the gcc with the highest minor number when correctness is important. Agreed.

I asked @fspiga  in the spack issue for the configured gcc path using `spack compiler info gcc@11.2.0` to get it:
https://github.com/spack/spack/issues/33693#issuecomment-1319536193

**Comment by brada4** [comment]
> feature upgrades

GCC 10.3 supports AMD CPUs based on the znver3 core via -march=znver3 // from respective release notes, this is feature significant for OpenBLAS.

@bernhardkaindl  the binutils `as` as shipped with rhel8 is too old for gcc-11. I proposed fixup to use binutils from rhel gcc-11, but I suspect spack can include compatible  binutils to fix gcc11 on rhel8.

**Comment by bernhardkaindl** [comment]
Thanks, I've submitted https://github.com/spack/spack/pull/33994 for spack to require local binutils when building gcc@10:

**Comment by brada4** [comment]
You migh want to also include  rhel7. See grievances history here:
https://github.com/xianyi/OpenBLAS/wiki/Faq#binutils
@martin-frbg I think compiler dilemma is solved

**Comment by bernhardkaindl** [comment]
Thanks @brada4, I updated https://github.com/spack/spack/pull/33994 to include RHEL7 as well.

**Comment by bernhardkaindl** [comment]
The remaining PR to be merged to fix this for Rocky5 and Almalinux too is https://github.com/spack/spack/pull/33190:

@fspiga: It needs somebody doing a performance test without it and with it applied, ideally on RHEL6/Rocky. I don't have such OS available right now, so we'd help from some user who has such OS running.

**Comment by brada4** [comment]
I followed your instructions to build gcc 11.2.0 with binutils included. It compiled current OpenBLAS branch for TARGET=NEOVERSEN2 on a raspberry4 , getting SIGILL during tests as expected. There are no performance implications to be accomodated, new binutils will simply be able to generate code for more advanced CPU as commanded in presence of respective compiler options. You are not alone, RHEL6 had gcc with AVX2 but no binutils support ;-)
