### ISSUE TITLE
 ImportError: libopenblaso.so.0 

### ISSUE THREAD

**Issue by Ashutosh-432** [xianyi/OpenBLAS#3807]
Hi Team  i am getting this error 
[ ImportError: libopenblaso.so.0 ].

 when I am installing  OpenBLAS from source referring this link  " https://iq.opengenus.org/install-openblas-from-source/" ,  

I am getting this file  [  [libopenblas.so]

but i need  libopenblaso.so.0 this file .

could you pls help me on that.

**Comment by martin-frbg** [comment]
libopenblaso is the name Linux distributions use to denote a version of the library that was built with support for OpenMP, so if you want to build from source rather than just install a precompiled package from your distribution (package name probably something like openblas-openmp),  please use `make USE_OPENMP=1`. Then just renaming or linking the generated library to libopenblaso.so.0 should work.

**Comment by Ashutosh-432** [comment]
Hi @martin-frbg  Thanks for your help. it worked for me .
but now i am getting another error  [ ImportError: liblapack.so.3 ].

could you pls help me where i can install this from source.
I am referring this link : https://github.com/bgeneto/build-install-compile-openblas 

[ 3.4. Build and install openblas openmp version ]
Thanks for ur help .

**Comment by martin-frbg** [comment]
OpenBLAS includes LAPACK by default, so you could just create another link. (Some distributions split out LAPACK so that implementations can be switched separately, e.g. if one wants to use ATLAS for BLAS and/or the unoptimized "netlib" reference implementation for LAPACK)

**Comment by Ashutosh-432** [comment]
Hi @martin-frbg  I found LAPACK folder inside OpenBLAS directory . But i did not find liblapack.so.3 file inside it .

could you help me to find on which folder i should look into after LAPACK  directory . 

![image](https://user-images.githubusercontent.com/104203359/200274551-5f60c053-1eb6-47c8-a7c0-368ff5a7df35.png)

**Comment by Ashutosh-432** [comment]
Hi @martin-frbg  As I am adding this file inside docker container , so pls guide me the exact location where i can find  [ liblapack.so.3 ] inside OpenBLAS folder.

I am referring this link : https://github.com/bgeneto/build-install-compile-openblas 

[ 3.4. Build and install openblas openmp version ]
I am referring above link to install from source.

**Comment by martin-frbg** [comment]
There is no separate liblapack.so in standard OpenBLAS builds, but all LAPACK functions are included in libopenblas.so (unless you specify NO_LAPACK=1 to make). That is why I suggested to link or copy libopenblas.
If you really need an original liblapack.so.3, get Reference-LAPACK/lapack from github

**Comment by brada4** [comment]
You need to install openblas package in alpine/ubuntu/whatever inside container.
Apparently you need to debug container install output yourself, or learn installation from containers' root shell.
Those guides are of 'worksforme' quality, not related to openblas.
Plese run `ldd` against binary you are throwing into the container.

**Comment by brada4** [comment]
[This section](https://github.com/bgeneto/build-install-compile-openblas#6-compiling-and-linking-with-openblas-using-your-openblas-library) is WRONG, please familiarize with openblas faq, the readme, and makefile.rule. There is a paragraph on Wl flag if you install openblas in non-system paths
