### ISSUE TITLE
Updated RISC-V vector support for review. 

### ISSUE THREAD

**Issue by ken-unger** [xianyi/OpenBLAS#3808]
Hi Xianyi and Martin,

A colleague and I have worked on an updated RISC-V Vector (RVV) implementation the past few months and are now looking to contribute our work back.   Our motivation was to support OpenBLAS on the SiFive X280 which is RVV 1.0 compliant.  The existing C910V implementation has a number of limitations which we encountered, and as such we decided it was better to create *_rvv.c implementations within kernel/riscv64, leaving the existing *_vector.c implementation for C910V untouched.  

Some of the improvements with this RVV implementation:
-	Support vector ABS (apparently not supported on C910V)
-	Support segment load/stores for complex data types, for better performance.
-	Alternative (in our view better) implementation choices.  Rather than loops using a predetermined vector length (VL), and a subsequent tail,  we found that determining VL within the loop was actually more efficient (in addition to cleaner/smaller code).
-	Generally faster for most kernels.
-	Significantly faster version of GEMM, modeled after what was done for SVE (8xVLEN). 
-	All implementations using vector intrinsics,  even the faster GEMM.   No assembler required.
 
Prior to submitting a PR, for your and others review, what tests should be run?  All of the CTESTs currently pass.  In the course of our work, we’ve also run the benchmark suite many times.

Thank you,
Ken

P.S  Our eventual PR would add the following, all of which is copyright OpenBLAS 2022:

        kernel/riscv64/KERNEL.x280
        kernel/riscv64/amax_rvv.c
        kernel/riscv64/amin_rvv.c
        kernel/riscv64/asum_rvv.c
        kernel/riscv64/axpby_rvv.c
        kernel/riscv64/axpy_rvv.c
        kernel/riscv64/copy_rvv.c
        kernel/riscv64/dot_rvv.c
        kernel/riscv64/gemm_beta_rvv.c
        kernel/riscv64/gemm_ncopy_rvv_v1.c
        kernel/riscv64/gemm_tcopy_rvv_v1.c
        kernel/riscv64/gemmkernel_rvv_v1x8.c
        kernel/riscv64/gemv_n_rvv.c
        kernel/riscv64/gemv_t_rvv.c
        kernel/riscv64/iamax_rvv.c
        kernel/riscv64/iamin_rvv.c
        kernel/riscv64/imax_rvv.c
        kernel/riscv64/imin_rvv.c
        kernel/riscv64/izamax_rvv.c
        kernel/riscv64/izamin_rvv.c
        kernel/riscv64/max_rvv.c
        kernel/riscv64/min_rvv.c
        kernel/riscv64/nrm2_rvv.c
        kernel/riscv64/rot_rvv.c
        kernel/riscv64/scal_rvv.c
        kernel/riscv64/sum_rvv.c
        kernel/riscv64/swap_rvv.c
        kernel/riscv64/symm_lcopy_rvv_v1.c
        kernel/riscv64/symm_ucopy_rvv_v1.c
        kernel/riscv64/symv_L_rvv.c
        kernel/riscv64/symv_U_rvv.c
        kernel/riscv64/trmm_lncopy_rvv_v1.c
        kernel/riscv64/trmm_ltcopy_rvv_v1.c
        kernel/riscv64/trmm_uncopy_rvv_v1.c
        kernel/riscv64/trmm_utcopy_rvv_v1.c
        kernel/riscv64/trmmkernel_rvv_v1x8.c
        kernel/riscv64/trsm_kernel_LN_rvv_v1.c
        kernel/riscv64/trsm_kernel_LT_rvv_v1.c
        kernel/riscv64/trsm_kernel_RN_rvv_v1.c
        kernel/riscv64/trsm_kernel_RT_rvv_v1.c
        kernel/riscv64/trsm_lncopy_rvv_v1.c
        kernel/riscv64/trsm_ltcopy_rvv_v1.c
        kernel/riscv64/trsm_uncopy_rvv_v1.c
        kernel/riscv64/trsm_utcopy_rvv_v1.c
        kernel/riscv64/zamax_rvv.c
        kernel/riscv64/zamin_rvv.c
        kernel/riscv64/zasum_rvv.c
        kernel/riscv64/zaxpby_rvv.c
        kernel/riscv64/zaxpy_rvv.c
        kernel/riscv64/zcopy_rvv.c
        kernel/riscv64/zdot_rvv.c
        kernel/riscv64/zgemm_beta_rvv.c
        kernel/riscv64/zgemmkernel_rvv_v1x4.c
        kernel/riscv64/zgemv_n_rvv.c
        kernel/riscv64/zgemv_t_rvv.c
        kernel/riscv64/znrm2_rvv.c
        kernel/riscv64/zrot_rvv.c
        kernel/riscv64/zscal_rvv.c
        kernel/riscv64/zsum.c
        kernel/riscv64/zsum_rvv.c
        kernel/riscv64/zswap_rvv.c
        kernel/riscv64/ztrmmkernel_2x2_rvv.c

**Comment by xianyi** [comment]
Thank you for your work.

Do you run test in https://github.com/xianyi/OpenBLAS/wiki/Developer-manual#run-openblas-test

**Comment by martin-frbg** [comment]
Thank you for this - running the LAPACK testsuite (`make lapack-test`) would be my suggestion. Beyond that, you'd need to install larger projects like numpy to run their tests.
Unfortunately I lack the hardware to test this myself.

**Comment by brada4** [comment]
check with scan-build/clang-analyzer and cppcheck, and for any compiler warnings. unitialized vars break long computations, gcc indentation noise is no-op but pollutes output.

**Comment by xianyi** [comment]
@ken-unger What is the current status? Thank you

**Comment by ken-unger** [comment]
Hi Xianyi,

We're very nearly ready to issue our PR.  We did run the additional tests Martin requested.  The utests did in fact catch two issues which were not covered by the ctests, which we resolved.  There is a remaining utest which was newly added in 0.3.21 that does have an issue and for which we are uncertain of a clean solution.  The C910V implementation of nrm2_vector.c also exhibits the same failure.

TEST 32/38 dnrm2:dnrm2_inf [FAIL]
  ERR: test_dnrm2.c:52  expected inf, got nan (diff nan, tol 1.000e-13)
TEST 33/38 dnrm2:dnrm2_tiny [FAIL]
  ERR: test_dnrm2.c:65  expected 0.000e+00, got nan (diff nan, tol 1.000e-13)

May we issue a PR despite this known issue?   Our newly added code builds clean, with no warnings.  I suppose we can issue our PR and you/Martin/others can determine what is best once you review.

Thanks

**Comment by ken-unger** [comment]
My colleague Heller Zheng, who collaborated with me on this implementation for several months, has issued a PR for these changes.   https://github.com/xianyi/OpenBLAS/pull/3825

We'll let you review once you are able.

Thanks.

**Comment by martin-frbg** [comment]
The NRM2 corner case in utest (originally from issue #2998 ,later seen on other platforms as well) is usually triggered by computing an intermediate fraction with the denominator being INF. The solution adapted on the other platforms was to return the INF in that case (see e.g. #3695 , similar examples in arm64 and mips64)

**Comment by sz-ok** [comment]
@ken-unger 
Hi ken，I have a problem when I work on risc-v branch,   see
https://github.com/xianyi/OpenBLAS/issues/3889

do you have some suggestions？

thanks

**Comment by ken-unger** [comment]
hi @xianyi.   Heller will be submitting another PR in the next few days to update the C intrinsics used in our _rvv.c files to match the latest standard and llvm 15+ that @sergei-lewis mentioned in #3919.  If possible, would you be able to merge Heller's outstanding PR #3893 to the riscv branch so that we don't end up with merge conflicts.  Thank you.

**Comment by martin-frbg** [comment]
I will merge it if I/we do not hear back from xianyi within the next 24 hours - looks zero risk to me but I do not want to step on anything when he is the one with actual working hardware

**Comment by HellerZheng** [comment]
> hi @xianyi. Heller will be submitting another PR in the next few days to update the C intrinsics used in our _rvv.c files to match the latest standard and llvm 15+ that @sergei-lewis mentioned in #3919. If possible, would you be able to merge Heller's outstanding PR #3893 to the riscv branch so that we don't end up with merge conflicts. Thank you.

Updated for latest standard, https://github.com/xianyi/OpenBLAS/pull/3971

**Comment by xianyi** [comment]
Thank you for the patch. I plan to check the status of vector intrinsic API.

> > hi @xianyi. Heller will be submitting another PR in the next few days to update the C intrinsics used in our _rvv.c files to match the latest standard and llvm 15+ that @sergei-lewis mentioned in #3919. If possible, would you be able to merge Heller's outstanding PR #3893 to the riscv branch so that we don't end up with merge conflicts. Thank you.
> 
> Updated for latest standard, #3971

**Comment by martin-frbg** [comment]
If my reading of the recent meeting minutes from https://github.com/riscv-admin/rvv-intrinsics/tree/main/meeting_minutes is correct, API freeze appears to be anticipated for sometime in june, with GCC13 and LLVM 16 being "mostly" on track with being compatible (?)

**Comment by ken-unger** [comment]
Thanks for the link Martin.   Looks like we (Heller) will need to do one more round in the future when the changes to "Tuple-type for the segment load/store" are implemented.  We make use of segment load/stores in a number if the _rvv.c kernels.

**Comment by martin-frbg** [comment]
Running xianyi's BLAS-Tester on an LLVM16 build of the risc-v branch under qemu 7.1 (qemu-riscv64 -cpu rv64,v=true,vlen=512,elen=64) currently yields the following results for TARGET=x280:

single-precision BLAS1 (xsl1blastst -R all) 132 tests run, 118 passed (failures in AMIN and AMAX, some of them just out of memory - the VM had 16GB assigned to it)
double precision BLAS1 112 run, 96 passed (one additional failure in ROT)
 complex BLAS1 121/103, (failures in AMIN and AMAX)
double precision complex BLAS1 121/102 (failures in AMIN and AMAX)
single precision BLAS2 160/151 (failures in SBMV and all except one SYMV)
double precision BLAS2 160/150 (failures in SBMV and all SYMV)
complex BLAS2 170 run, 170 passed
double precision complex BLAS2 170/170
single precision BLAS3 60 run, 60 passed
double precision BLAS3 60/60
complex BLAS3 90 run, 84 passed (failures in some SYR2K,SYRK,HEMM and HERK runs)
double precision complex BLAS3 90 run, all passed

**Comment by martin-frbg** [comment]
Running xianyi's BLAS-Tester on an LLVM16 build of the risc-v branch under qemu 7.1 (qemu-riscv64 -cpu rv64,v=true,vlen=512,elen=64) currently yields the following results for TARGET=x280:

single-precision BLAS1 (xsl1blastst -R all) 132 tests run, 118 passed (failures in AMIN and AMAX, some of them just out of memory - the VM had 16GB assigned to it)
double precision BLAS1 112 run, 96 passed (one additional failure in ROT)
 complex BLAS1 121/103, (failures in AMIN and AMAX)
double precision complex BLAS1 121/102 (failures in AMIN and AMAX)
single precision BLAS2 160/151 (failures in SBMV and all except one SYMV)
double precision BLAS2 160/150 (failures in SBMV and all SYMV)
complex BLAS2 170 run, 170 passed
double precision complex BLAS2 170/170
single precision BLAS3 60 run, 60 passed
double precision BLAS3 60/60
complex BLAS3 90 run, 84 passed (failures in some SYR2K,SYRK,HEMM and HERK runs)
double precision complex BLAS3 90 run, all passed

**Comment by ken-unger** [comment]
Thanks @martin-frbg  for the test results.  We will review and correct.

**Comment by martin-frbg** [comment]
I saw now that the reported failures in AMIN/AMAX also occur with the generic C kernels, so may actually be indicative of riscv64-linux-gnu-gfortran 12.2 miscompiling the "netlib" reference BLAS that is used for comparison. This obviously casts doubt on the other test failures, sorry for the noise.
I'll see if I can feed the original fortran through f2c so that it all compiles with just the clang from LLVM16

**Comment by martin-frbg** [comment]
risc-v branch merged now through #4472
