### ISSUE TITLE
Inconsistent use of line end characters in source code. 

### ISSUE THREAD

**Issue by pneerincx** [xianyi/OpenBLAS#3822]
Small subset of source code uses CRLF Windows/DOS style line end characters, whereas the majority uses LF UNIX style line end characters. The CRLF characters can cause problems for example when trying to use the `patch` utility to patch source code.

**Comment by brada4** [comment]
Cmake uses crlf because of visusl studio (the huge dinosaur kind, not code), others with crlf are mistake.To summarise - you say that cmake usage  breaks patch. Resisting it seems futile.

**Comment by martin-frbg** [comment]
I do not think cmake has anything to do with it, more likely a few recent contributors were creating their PRs on Windows systems and the line endings went unnoticed. At first glance, only a small number of files in the kernel tree appear to be affected (with at least one of them even having both kinds of line endings). I'll fix them later today or tomorrow.

**Comment by brada4** [comment]
```
file `find OpenBLAS -type f` | grep CRLF
```
What I am saying that CMake will emit CRLF before ninja/make anyway which limits patching at large. For the rest probably worth shaving off those few bits with patch-incompatible patch.

**Comment by pneerincx** [comment]
Thanks!

**Comment by martin-frbg** [comment]
I guess we could add a `.gitattributes` file _if_ this becomes a repeat problem. (I have not seen many projects use them, but e.g. numpy does have one)
