### ISSUE TITLE
CPU detection fails for Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz

### ISSUE THREAD

**Issue by haampie** [xianyi/OpenBLAS#3823]
We see OpenBLAS fail to detect the host CPU for Intel Xeon Platinum 8375C.

```
==> [2022-11-12-07:01:17.244931] 'make' '-j32' 'CC=/builds/spack/spack/lib/spack/env/gcc/gcc' 'FC=/builds/spack/spack/lib/spack/env/gcc/gfortran' 'MAKE_NB_JOBS=0' 'ARCH=x86_64' 'DYNAMIC_ARCH=1' 'USE_LOCKING=1' 'USE_OPENMP=0' 'USE_THREAD=0' 'libs' 'netlib' 'shared'
getarch_2nd.c: In function 'main':
getarch_2nd.c:14:35: error: 'SGEMM_DEFAULT_UNROLL_M' undeclared (first use in this function); did you mean 'SHGEMM_DEFAULT_UNROLL_M'?
     printf("SGEMM_UNROLL_M=%d\n", SGEMM_DEFAULT_UNROLL_M);
                                   ^~~~~~~~~~~~~~~~~~~~~~
                                   SHGEMM_DEFAULT_UNROLL_M
...
```

**Comment by martin-frbg** [comment]
Strange, which version of OpenBLAS is this please ? Intel Ice Lake (family 6, model 6A) should be recognized since 0.3.16 (more than a year ago)

**Comment by haampie** [comment]
Ah, sorry for wasting your time :( The [build log](https://gitlab.spack.io/spack/spack/-/jobs/4339809) shows 0.3.10, that explains a few things.

I see now, it takes the "best" openblas that can be built by GCC 7.3 (ref https://github.com/xianyi/OpenBLAS/issues/2949). Will update compilers in CI...

**Comment by haampie** [comment]
@martin-frbg when building with `'ARCH=x86_64' 'DYNAMIC_ARCH=1'`, is it possible to avoid host CPU detection altogether?

**Comment by martin-frbg** [comment]
You can (and usually want to) supply a `TARGET=...` when building for DYNAMIC_ARCH - this is used to define compiler options for the common code so should roughly correspond to the oldest cpu you expect to have to support. Only in the absence of a TARGET option will it default to the detected cpu of the build host - which, depending on compiler version, could lead to e.g. AVX512 instructions appearing in the general, C-based setup code.

**Comment by haampie** [comment]
Thanks, we'll need to make a proper spack -> openblas target map
