### ISSUE TITLE
ZSYTRF yields wrong result when OpenBLAS is built using CMake

### ISSUE THREAD

**Issue by A205B064** [xianyi/OpenBLAS#3856]
# Brief

For version 0.3.16 - 0.3.21, if I build OpenBLAS with `cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON`, `ZSYTRF` can yield wrong result.

**But the result is correct for version 0.3.15, or if I simply build OpenBLAS with `make`.**

# How to Reproduce

It can be tested with the following code

```c++
#include <complex>
#include <iostream>
#include <lapacke.h>

int main()
{
    std::complex<double> A[9]{
        {2, 2}, {0, 0}, {1, 1},
        {0, 0}, {2, 2}, {0, 0},
        {1, 1}, {0, 0}, {2, 2}
    };
    lapack_int ipiv[3]{ 0 };

    auto info = LAPACKE_zsytrf(LAPACK_COL_MAJOR, 'L', 3, (lapack_complex_double*)A, 3, ipiv);

    std::cout << "info = " << info << '\n';
    std::cout << "ipiv = " << ipiv[0] << ", " << ipiv[1] << ", " << ipiv[2] << '\n';
    std::cout << "A =\n";
    std::cout << A[0] << '\n';
    std::cout << A[1] << ", " << A[4] << '\n';
    std::cout << A[2] << ", " << A[5] << ", " << A[8] << '\n';

    return 0;
}
```

It prints
```
info = 0
ipiv = 1, 2, 3
A =
(2,2)
(0,0), (2,2)
(0.5,0), (0,0), (2,2)
```

Whereas the correct A after factorization should be
```
(2,2)
(0,0), (2,2)
(0.5,0), (0,0), (1.5,1.5)
```

It's not the only error case, I just picked a simple one for demonstration. And I can reproduce it on various platforms, including Linux+GCC, Windows+MinGW64, Intel 8700, Intel E5 2620 v3, AMD Ryzen 5900HX

# My Question
Is my way of build OpenBLAS using CMake wrong, or there are some bugs in the project's CMake scripts?

**Comment by martin-frbg** [comment]
Offhand the only difference between the build systems should be that a CMAKE "Release" build defaults to `-O3` while the Makefile predefines only `-O2`

**Comment by A205B064** [comment]
@martin-frbg I tried adding `-DCMAKE_C_FLAGS_RELEASE=-O2 -DCMAKE_Fortran_FLAGS_RELEASE=-O2` to CMake Release build, the result was still wrong. (I checked with the terminal output that it is using -O2 instead of -O3)

I also tried CMake Debug build, it didn't work neither.

I haven't figured out how to let `make` build with -O3 for cross verification.

Another thing I just noticed is that when linked against OpenBLAS built by CMake, the above sample programm can take up to about 2 seconds if OMP_NUM_THREADS and OPENBLAS_NUM_THREADS are unspecified, but it finished instantaneously when the 2 envs are set to 1. Whereas when linked against OpenBLAS built by `make`, it always finished instantaneously no matter whether the 2 envs are set to 1 or unspecified.

**Comment by martin-frbg** [comment]
Reproduced but no idea yet (you can uncomment the COMMON_OPT line in Makefile.rule and set `-O3` there but it appears to be unrelated)

**Comment by brada4** [comment]
RelWithDebInfo build type is -O2

**Comment by martin-frbg** [comment]
bisecting now. (There also appears to be a problem with the HAVE_feature settings in the universal intrinsics when building for a specific TARGET with cmake, could even be related)

**Comment by martin-frbg** [comment]
Bisect points to my commit d6d7a668 of May 27, 2021 "Add shortcuts for (small) cases that do not need expensive buffer allocation" although the choice of build system should play no role there.

**Comment by martin-frbg** [comment]
Looks like the Makefile build does not actually override the (Z)SYR from LAPACK with OpenBLAS' reimplementation (that has been there since the days of GotoBLAS), while the CMAKE build does. The change in the Makefile build occured with #1046 , the update of LAPACK to 3.7.0 six years ago - for some unknown reason that contributor decided to disable a number of OpenBLAS functions that are also present in the netlib LAPACK. (Incidentally this was also one of the last commits from this long-time contributor before contact with him was lost)

**Comment by martin-frbg** [comment]
And my commit #3252 omitted a factor of two in the stride calculation, leading to the wrong result reported here. :(

**Comment by martin-frbg** [comment]
reopening for the make/cmake difference

**Comment by martin-frbg** [comment]
Excessive startup time is caused by CMAKE not defaulting to NO_WARMUP=1 as Makefile.rule does. (So consuming almost two seconds in the run_bench() function of memory.c trying to find the best location for the big buffer array). However `cmake -DNO_WARMUP=1` does work as expected.

**Comment by A205B064** [comment]
@martin-frbg Thanks. That's really useful knowledge.

**Comment by Mousius** [comment]
@martin-frbg is the intent to eventually fully move to CMake?

**Comment by martin-frbg** [comment]
No, the plan is for both to be supported and equivalent (which means I will prepare a PR to add the NO_WARMUP=1 default), and perhaps even add support for one of the newer alternatives like meson at some later time.
