### ISSUE TITLE
make BINARY64=1 INTERFAE64=1 does not actually compile lapack-netlib with ilp64 interface on riscv64

### ISSUE THREAD

**Issue by alexfanqi** [xianyi/OpenBLAS#3859]
On riscv64 with gfortran, to make INTEGER 8 bytes, it requires -fdefault-integer-8, however by checking my build log, this flag is not passed into gfortran for lapack-netlib. The output libopenblas64.so then contains 8 bytes blasint for c functions and 4 bytes integer for fortran functions.

I find out this is caused by riscv64 setting NO_BINARY_MODE=1 and it enters this ifdef branch, https://github.com/xianyi/OpenBLAS/blob/de4d5646eb1ac6a0e663a4c9bc797dad8226aedb/Makefile.system#L1072 skipping the existing fdefault-integer-8 branch here https://github.com/xianyi/OpenBLAS/blob/de4d5646eb1ac6a0e663a4c9bc797dad8226aedb/Makefile.system#L1091 

The variable NO_BINARY_MODE is very confusing to me.  It vaguely looks like to express if ARCH supports -m64/-m32. Most platforms set it and there are also repeated code around it. I am not sure the best way to handle this, so only sending this as a patch.
```
diff --git a/Makefile.system b/Makefile.system
index a52ee35..b1903e2 100644
--- a/Makefile.system
+++ b/Makefile.system
@@ -1065,5 +1065,11 @@ FCOMMON_OPT += -mabi=n32
 endif
 else ifeq ($(ARCH), $(filter $(ARCH),mips))
 FCOMMON_OPT += -mabi=32
+else ifeq ($(ARCH), $(filter $(ARCH),riscv64))
+ifdef INTERFACE64
+ifneq ($(INTERFACE64), 0)
+FCOMMON_OPT +=  -fdefault-integer-8
+endif
+endif
 endif
 else
```

**Comment by brada4** [comment]
This should be correct place:
https://github.com/xianyi/OpenBLAS/blob/de4d5646eb1ac6a0e663a4c9bc797dad8226aedb/Makefile.system#L1085
