### ISSUE TITLE
out of memory allocating 38654705683 bytes after a total of 62951424 bytes

### ISSUE THREAD

**Issue by yamato720** [xianyi/OpenBLAS#3860]
i use this command:
''make BINARY=64 CC=/home/yamato/crosschain_middle/Xuantie-900-gcc-linux-5.10.4-glibc-x86_64-V2.6.0/bin/riscv64-unknown-linux-gnu-gcc FC=/home/yamato/crosschain_middle/Xuantie-900-gcc-linux-5.10.4-glibc-x86_64-V2.6.0/bin/riscv64-unknown-linux-gnu-gfortran HOSTCC=gcc TARGET=C910V''
Although it is good at the begining,the error happens,just like the title:"ar: out of memory allocating 38654705683 bytes after a total of 62951424 bytes".38654705683 bytes is equal to nearly 38GB.
i have restarted the Ubuntu virtual machine and make again ，but there is still the same error.

**Comment by brada4** [comment]
<del> Seems 21.10 enabled LTO compilation by default, excluding OpenBLAS https://git.launchpad.net/ubuntu/+source/lto-disabled-list/tree/lto-disabled-list?h=applied/ubuntu/devel&id=704f9463c026d96926dbe062d391ffe0ee028f5f#n995

<del>You may use `COMMON_OPT="-O2 -fno-lto"` to build, though not sure you dont need more inverting parameters.

<del> The source of problem is "static" library containing all compiled objects that in case of LTO grows to enormous size, though resulting dynamic library would be normal 40 GB later.

<del> Should be similar in RHEL9 (???) </del>

There is no reason to have such memory usage. Could you post full build output to the point it fails? Like record with `script` or something?

**Comment by martin-frbg** [comment]
No idea what happened there, and unfortunately I only have a 2021 version of the t-head gcc where this is not reproducible. One wild guess is that maybe in your case the `ar` of the host system got called instead of the one from the cross-compiler toolchain.

**Comment by brada4** [comment]
Or one from ubuntu's riscv64 binutils named `riscv64-linux-gnu-ar` , please check directory of compilers if there is not something equally named in the directory next to crosscompilers.

**Comment by yamato720** [comment]
here is the full build output
make BINARY=64 CC=/home/yamato/crosschain_middle/Xuantie-900-gcc-linux-5.10.4-glibc-x86_64-V2.6.0/bin/riscv64-unknown-linux-gnu-gcc FC=/home/yamato/crosschain_middle/Xuantie-900-gcc-linux-5.10.4-glibc-x86_64-V2.6.0/bin/riscv64-unknown-linux-gnu-gfortran HOSTCC=gcc TARGET=C910V
In file included from getarch_2nd.c:3:
config.h:1:1: warning: null character(s) ignored
    1 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 #define OS_LINUX        1
      | ^
Makefile.conf:1: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:2: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:3: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:4: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:5: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:6: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:7: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:8: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:9: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:10: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:11: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:12: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:13: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:14: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:15: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:16: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:17: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:18: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:19: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:20: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:21: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:22: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:23: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:24: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:25: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:26: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:27: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:28: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:29: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:30: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:31: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:32: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:33: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:34: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:35: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:36: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:37: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:38: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:39: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:40: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:41: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:42: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:43: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:44: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:45: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:46: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:47: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:48: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:49: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:50: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:51: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:52: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:53: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:54: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:55: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:56: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:57: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:58: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:59: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:60: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:61: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:62: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:63: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:64: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:65: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:66: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:67: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:68: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:69: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:70: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:71: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:72: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:73: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:74: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:75: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:76: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:77: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:78: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:79: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:80: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:81: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:82: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:83: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:84: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:85: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:86: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:87: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:88: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:89: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:90: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:91: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:92: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:93: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:94: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:95: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:96: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:97: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:98: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:99: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:100: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:101: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:102: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:103: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:104: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:105: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:106: 警告：遇到了 NUL 字符；忽略行的剩余部分
Makefile.conf:107: 警告：遇到了 NUL 字符；忽略行的剩余部分
make[1]: 进入目录“/mnt/hgfs/专门传输双系统的文件夹/new openblas/OpenBLAS-0.3.21/interface”
ar  -ru ../libopenblas_c910vp-r0.3.21.a saxpy.o sswap.o scopy.o sscal.o sdot.o sdsdot.o dsdot.o sasum.o ssum.o snrm2.o smax.o samax.o ismax.o isamax.o smin.o samin.o ismin.o isamin.o srot.o srotg.o srotm.o srotmg.o saxpby.o cblas_isamax.o cblas_isamin.o cblas_sasum.o cblas_saxpy.o cblas_scopy.o cblas_sdot.o cblas_sdsdot.o cblas_dsdot.o cblas_srot.o cblas_srotg.o cblas_srotm.o cblas_srotmg.o cblas_sscal.o cblas_sswap.o cblas_snrm2.o cblas_saxpby.o cblas_ismin.o cblas_ismax.o cblas_ssum.o sgemv.o sger.o strsv.o strmv.o ssymv.o ssyr.o ssyr2.o sgbmv.o ssbmv.o sspmv.o sspr.o sspr2.o stbsv.o stbmv.o stpsv.o stpmv.o cblas_sgemv.o cblas_sger.o cblas_ssymv.o cblas_strmv.o cblas_strsv.o cblas_ssyr.o cblas_ssyr2.o cblas_sgbmv.o cblas_ssbmv.o cblas_sspmv.o cblas_sspr.o cblas_sspr2.o cblas_stbmv.o cblas_stbsv.o cblas_stpmv.o cblas_stpsv.o sgemm.o ssymm.o strmm.o strsm.o ssyrk.o ssyr2k.o somatcopy.o simatcopy.o sgeadd.o cblas_sgemm.o cblas_ssymm.o cblas_strmm.o cblas_strsm.o cblas_ssyrk.o cblas_ssyr2k.o cblas_somatcopy.o cblas_simatcopy.o cblas_sgeadd.o sgetrf.o sgetrs.o spotrf.o sgetf2.o spotf2.o slaswp.o sgesv.o slauu2.o slauum.o strti2.o strtri.o strtrs.o daxpy.o dswap.o dcopy.o dscal.o ddot.o dasum.o dsum.o dnrm2.o dmax.o damax.o idmax.o idamax.o dmin.o damin.o idmin.o idamin.o drot.o drotg.o drotm.o drotmg.o daxpby.o cblas_idamax.o cblas_idamin.o cblas_dasum.o cblas_daxpy.o cblas_dcopy.o cblas_ddot.o cblas_drot.o cblas_drotg.o cblas_drotm.o cblas_drotmg.o cblas_dscal.o cblas_dswap.o cblas_dnrm2.o cblas_daxpby.o cblas_idmin.o cblas_idmax.o cblas_dsum.o dgemv.o dger.o dtrsv.o dtrmv.o dsymv.o dsyr.o dsyr2.o dgbmv.o dsbmv.o dspmv.o dspr.o dspr2.o dtbsv.o dtbmv.o dtpsv.o dtpmv.o cblas_dgemv.o cblas_dger.o cblas_dsymv.o cblas_dtrmv.o cblas_dtrsv.o cblas_dsyr.o cblas_dsyr2.o cblas_dgbmv.o cblas_dsbmv.o cblas_dspmv.o cblas_dspr.o cblas_dspr2.o cblas_dtbmv.o cblas_dtbsv.o cblas_dtpmv.o cblas_dtpsv.o dgemm.o dsymm.o dtrmm.o dtrsm.o dsyrk.o dsyr2k.o domatcopy.o dimatcopy.o dgeadd.o cblas_dgemm.o cblas_dsymm.o cblas_dtrmm.o cblas_dtrsm.o cblas_dsyrk.o cblas_dsyr2k.o cblas_domatcopy.o cblas_dimatcopy.o cblas_dgeadd.o dgetrf.o dgetrs.o dpotrf.o dgetf2.o dpotf2.o dlaswp.o dgesv.o dlauu2.o dlauum.o dtrti2.o dtrtri.o dtrtrs.o caxpy.o caxpyc.o cswap.o ccopy.o cscal.o csscal.o cdotc.o cdotu.o scasum.o scsum.o scnrm2.o scamax.o icamax.o scamin.o icamin.o csrot.o crotg.o caxpby.o cblas_icamax.o cblas_icamin.o cblas_scasum.o cblas_caxpy.o cblas_ccopy.o cblas_cdotc.o cblas_cdotu.o cblas_cdotc_sub.o cblas_cdotu_sub.o cblas_cscal.o cblas_csscal.o cblas_cswap.o cblas_scnrm2.o cblas_caxpby.o cblas_icmin.o cblas_icmax.o cblas_scsum.o cblas_csrot.o cblas_crotg.o cgemv.o cgeru.o cgerc.o ctrsv.o ctrmv.o csyr2.o cgbmv.o csbmv.o cspr2.o ctbsv.o ctbmv.o ctpsv.o ctpmv.o chemv.o chbmv.o cher.o cher2.o chpmv.o chpr.o chpr2.o cblas_cgemv.o cblas_cgerc.o cblas_cgeru.o cblas_cgbmv.o cblas_chbmv.o cblas_chemv.o cblas_cher.o cblas_cher2.o cblas_chpmv.o cblas_chpr.o cblas_chpr2.o cblas_ctbmv.o cblas_ctbsv.o cblas_ctpmv.o cblas_ctpsv.o cblas_ctrmv.o cblas_ctrsv.o cgemm.o csymm.o ctrmm.o ctrsm.o csyrk.o csyr2k.o chemm.o cherk.o cher2k.o comatcopy.o cimatcopy.o cgeadd.o cblas_cgemm.o cblas_csymm.o cblas_ctrmm.o cblas_ctrsm.o cblas_csyrk.o cblas_csyr2k.o cblas_chemm.o cblas_cherk.o cblas_cher2k.o cblas_comatcopy.o cblas_cimatcopy.o cblas_cgeadd.o cgetrf.o cgetrs.o cpotrf.o cgetf2.o cpotf2.o claswp.o cgesv.o clauu2.o clauum.o ctrti2.o ctrtri.o ctrtrs.o zaxpy.o zaxpyc.o zswap.o zcopy.o zscal.o zdscal.o zdotc.o zdotu.o dzasum.o dzsum.o dznrm2.o dzamax.o izamax.o dzamin.o izamin.o zdrot.o zrotg.o zaxpby.o cblas_izamax.o cblas_izamin.o cblas_dzasum.o cblas_zaxpy.o cblas_zcopy.o cblas_zdotc.o cblas_zdotu.o cblas_zdotc_sub.o cblas_zdotu_sub.o cblas_zscal.o cblas_zdscal.o cblas_zswap.o cblas_dznrm2.o cblas_zaxpby.o cblas_izmin.o cblas_izmax.o cblas_dzsum.o cblas_zdrot.o cblas_zrotg.o zgemv.o zgeru.o zgerc.o ztrsv.o ztrmv.o zsyr2.o zgbmv.o zsbmv.o zspr2.o ztbsv.o ztbmv.o ztpsv.o ztpmv.o zhemv.o zhbmv.o zher.o zher2.o zhpmv.o zhpr.o zhpr2.o cblas_zgemv.o cblas_zgerc.o cblas_zgeru.o cblas_zgbmv.o cblas_zhbmv.o cblas_zhemv.o cblas_zher.o cblas_zher2.o cblas_zhpmv.o cblas_zhpr.o cblas_zhpr2.o cblas_ztbmv.o cblas_ztbsv.o cblas_ztpmv.o cblas_ztpsv.o cblas_ztrmv.o cblas_ztrsv.o zgemm.o zsymm.o ztrmm.o ztrsm.o zsyrk.o zsyr2k.o zhemm.o zherk.o zher2k.o zomatcopy.o zimatcopy.o zgeadd.o cblas_zgemm.o cblas_zsymm.o cblas_ztrmm.o cblas_ztrsm.o cblas_zsyrk.o cblas_zsyr2k.o cblas_zhemm.o cblas_zherk.o cblas_zher2k.o cblas_zomatcopy.o cblas_zimatcopy.o cblas_zgeadd.o zgetrf.o zgetrs.o zpotrf.o zgetf2.o zpotf2.o zlaswp.o zgesv.o zlauu2.o zlauum.o ztrti2.o ztrtri.o ztrtrs.o cblas_xerbla.o
ar: `u' 修饰符被忽略，因为 `D' 为默认（参见 `U'）

ar: out of memory allocating 38654705683 bytes after a total of 62951424 bytes

**Comment by martin-frbg** [comment]
Looks like you are building on a Windows filesystem that you access via VMware's shared folder mechanism, and Windows is inserting its end-of-line characters into at least some of the generated files (The "NULL character" warnings for Makefile.conf and config.h). 
Can you please try with the OpenBLAS sources actually unpacked "inside" the virtual machine, on the Linux filesystem ?

**Comment by yamato720** [comment]
thanks for your help!i successfully build it! the respond is that To install the library, you can run "make PREFIX=/path/to/your/installation install".is it over?what should i do next to compile openblas code for risc-v cpu?

**Comment by brada4** [comment]
You need to include cblas.h and /or lapacke.h ,  then use
`-Wl,-rpath=/opt/OpenBLAS -L/opt/OpenBLAS -lopenblas` likrly some smaller combo of those.
Hints to API rreference on NetLib and some tutorials on front pagr.

**Comment by yamato720** [comment]
Thanks! I finally make it! Thanks!
