### ISSUE TITLE
PHP Startup: Unable to load dynamic library 'php_rindow_openblas'

### ISSUE THREAD

**Issue by gatesplan** [xianyi/OpenBLAS#3864]
I ran through installation guide and finally generate openblas.dll file.

**************************************************************************
Install the required PHP extensions for Rindow Neural Networks.

Download and unzip the latest version of rindow_openblas from https://github.com/rindow/rindow-openblas/releases.
Download and unzip OpenBLAS with the corresponding release number from https://github.com/xianyi/OpenBLAS/releases.
Set the OpenBLAS DLL path to the execution path.
Copy php_rindow_openblas.dll to PHP’s ext directory.
**************************************************************************

In this guide, I cannot underestand `set the openblas dll path to the execution path`. Does it mean environment variable path or any other configuration needed?

I understand that there might be some standard rule but, current guide (including openblas itself) does not instructive for me. Could you give me more detail info?

Even if it means environment variable path, problem is still there. I cannot start php anymore due to extension loading failure. Need help. Stackoverflow kicked me out because its too community specific question lol

**Comment by martin-frbg** [comment]
I know nothing of rindow or rindow-openblas, please open an issue ticket in their project if you need installation help with it. That said, their README.md at https://github.com/rindow/rindow-openblas gives a clear example of what to do in addition to copying the dlls, you need to add the installation path to the environment variable `%PATH%`
