### ISSUE TITLE
Ninja with MinGW produces dll.a on Windows

### ISSUE THREAD

**Issue by wutzig** [xianyi/OpenBLAS#3865]
I compile the dynamic (sequential) library using Ninja and MinGW's gcc and gfortran compilers on Windows 10 with
```
cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_STATIC_LIBS=FALSE -DBUILD_SHARED_LIBS=TRUE -DUSE_THREAD=0 -DUSE_LOCKING=1 -DUSE_OPENMP=1
cmake --build . --target openblas_shared -j --config Release
```
This works but produces libopenblas.dll and libopenblas.dll.a, which looks like mixing Linux and Windows library naming conventions.
Simply renaming the .dll.a into .lib seems to work though. I'm not sure if I'm doing something wrong, if it's a Ninja issue or an OpenBLAS cmake naming hickup.

**Comment by isuruf** [comment]
This is the norm for MinGW. Nothing special about openblas. See for eg: https://stackoverflow.com/questions/55610732/cmake-dll-vs-dll-a-vs-a-what-library-should-i-specify-in-the-cmake-configur

**Comment by wutzig** [comment]
My bad. Thank's for the explanation.
