### ISSUE TITLE
Large matrix mul can't be run on Xuantie C906

### ISSUE THREAD

**Issue by yamato720** [xianyi/OpenBLAS#3871]
Matrix A is m*m, matrix B is also m*m, I use this function ''cblas_dgemm()''to calculate A*B on Xuantie C906, a RISC-V CPU. 
However, when m>=8,it reports error "Illegal instruction"; When m<8,it works and gives a correct answer.
But when I run it on my laptop, even m==3200,it still runs well.

**Comment by martin-frbg** [comment]
So far I have been assuming that the C906 supports the same instruction set as the C910 for which the kernels were contributed - unfortunately I do not have any actual hardware to test.
This reddit thread may be relevant (although it refers to the older rvv 0.7 version) https://www.reddit.com/r/RISCV/comments/z3u0ld/issue_with_64bit_element_size_with_rvv_07_on/ @xianyi

**Comment by brada4** [comment]
You should build TARGET=RISCV64_GENERIC to make it work. It wkll be slower than intended till problem is figured out

**Comment by martin-frbg** [comment]
May be fixed by #3891 but I only just received a C906-based developer board (Sipeed Lichee RV dock) and have not yet gotten it to work.
