### ISSUE TITLE
Building from OpenBLAS 0.3.21 error due to LAPACK_FORTRAN_STRLEN_END

### ISSUE THREAD

**Issue by mfauvel** [xianyi/OpenBLAS#3877]
Hello,

I have a c function that use `dpbrtf` as follows
``` c
 dpbtrf_("U", n_, order_, Ab, ldab, info)
```
The program compiled and openblas was provided by the debian repo of my distribution:

``` sh
libopenblas-dev/stable,now 0.3.13+ds-3 amd64  [installé]
  Optimized BLAS (linear algebra) library (dev, meta)
```
And it runs fine (assessed with some handcrafted tests). I try to use the last openblas version (0.3.21) : the compilation was fine but when I try to compile my program with the new openblas library I got an error because of missing argument:

``` c
gcc -I /opt/OpenBLAS/include/ -L /opt/OpenBLAS/lib/ -O3 -Wall -pedantic -fpic -shared -o shared_function.so ref_c_func.c -lopenblas -fopenmp -lgfortran
ref_c_func.c: In function ‘batch_cholesky_banded’:
ref_c_func.c:579:7: error: too few arguments to function ‘dpbtrf_’
  579 |       dpbtrf_("U", n_, order_, Ab, ldab, info);
      |       ^~~~~~~
In file included from /opt/OpenBLAS/include/lapack.h:11,
                 from ref_c_func.c:5:
/opt/OpenBLAS/include/lapack.h:12304:42: note: declared here
12304 | #define LAPACK_dpbtrf_base LAPACK_GLOBAL(dpbtrf,DPBTRF)
      |                                          ^~~~~~
/opt/OpenBLAS/include/lapacke_mangling.h:12:39: note: in definition of macro ‘LAPACK_GLOBAL’
   12 | #define LAPACK_GLOBAL(lcname,UCNAME)  lcname##_
      |                                       ^~~~~~
/opt/OpenBLAS/include/lapack.h:12305:6: note: in expansion of macro ‘LAPACK_dpbtrf_base’
12305 | void LAPACK_dpbtrf_base(
      |      ^~~~~~~~~~~~~~~~~~
```

When I check in `lapack.h`, I see that when `LAPACK_FORTRAN_STRLEN_END` is defined it adds a new parameter to the function `dpbtrf_` (from lapack.h)

``` c
#define LAPACK_dpbtrf_base LAPACK_GLOBAL(dpbtrf,DPBTRF)
void LAPACK_dpbtrf_base(
    char const* uplo,
    lapack_int const* n, lapack_int const* kd,
    double* AB, lapack_int const* ldab,
    lapack_int* info
#ifdef LAPACK_FORTRAN_STRLEN_END
    , size_t
#endif
);
#ifdef LAPACK_FORTRAN_STRLEN_END
    #define LAPACK_dpbtrf(...) LAPACK_dpbtrf_base(__VA_ARGS__, 1)
#else
    #define LAPACK_dpbtrf(...) LAPACK_dpbtrf_base(__VA_ARGS__)
#endif
```

I try to comment the line `#define LAPACK_FORTRAN_STRLEN_END` : the program now compile but I get a segmentation fault. 

I don't know how to handle this point: I search but I did not find what is the meaning of the parameter `size_t` and how to provide this value to the function ? 

I am aware of the FAQ to replace the library (https://github.com/xianyi/OpenBLAS/wiki/faq#replacing-system-blasupdating-apt-openblas-in-mintubuntudebian). 

ps: the objective of using compiled version of openblas is to use my program on another computer were I cannot install packages.

**Comment by mfauvel** [comment]
Ok my bad, when I build the openblas library with the option `FC=gfortran` I do not have any segmentation fault and I got correct result.

Still, I need to comment the line `#define LAPACK_FORTRAN_STRLEN_END` before compiling my program. 

I don't understand why there is one more parameter with the function per default now ?

**Comment by martin-frbg** [comment]
This is a change introduced with recent LAPACK version 3.10 (which OpenBLAS imports from the Reference-LAPACK project (also known as "netlib").
The background is that string handling differs between C and Fortran such that the Fortran compiler needs to be told the length of each string argument via extra arguments added at the end of the list. Many old codes do/did not fo this for single-character arguments, and it was argued that this meant relying on undefined behaviour.
see #2154 and related https://github.com/Reference-LAPACK/lapack/issues/339

**Comment by mfauvel** [comment]
Many thanks @martin-frbg for your explanation. However, I am not sure about the correct way to modify my code:

- Should I add `1` (or any number, but from the `lapack.h` it seems to be `1`)  at the end of my call to dpbtrf such as ` dpbtrf_("U", n_, order_, Ab, ldab, info, 1)`
- Or comment the definition of `LAPACK_FORTRAN_STRLEN_END` is a correct way to handle this change. But in that case, as far as I understand, we do no tell to the copmpiler the length of the strings ?

**Comment by martin-frbg** [comment]
The correct way should be to add the "1" for the length of the single-character "U" argument at the end of your dpbtrf line, but as you wrote you could also comment the definition of LAPACK_FORTRAN_STRLEN_END to stay with the old behaviour (which has been implicated in a few otherwise unexplained problems as seen in the Reference-LAPACK issue ticket and others mentioned therein).
Some discussion happened in https://github.com/Reference-LAPACK/lapack/issues/604 - from that two possible solutions would be to (a) always use the corresponding LAPACKE interface instead of calling a LAPACK function directly or (b) have your own code check if LAPACK_FORTRAN_STRLEN_END is defined and supply arguments accordingly

**Comment by mfauvel** [comment]
Thanks @martin-frbg. I close the issue.
Best wishes
