### ISSUE TITLE
dbdsdc segfault using ILP64

### ISSUE THREAD

**Issue by mckib2** [xianyi/OpenBLAS#3883]
Building the ILP64 version of OpenBLAS with cmake (both Debug and Release) on x86_64, I encounter a segfault in `dbdsdc`.  The debugger shows the following calls:

```
dswap_k swap_sse2.S:562
dswap_ swap.c:98
dlasdq dlasdq.f:400
dbdsdc dbdsdc.f:351
main reproducer.cpp:31
__libc_start_call_main 0x00007ffff7c29d90
__libc_start_main_impl 0x00007ffff7c29e40
_start 0x0000555555556425
```

The issue appears to be when dereferencing `INCX` and `INCY` in `swap.c` -- garbage values come out (and I've also seen the same thing happen in `rot.c`).  In this case, `dlasdq.f:400` passes `INCX=1` and `INCY=1` but `swap.c` sees `incx=-73682745238224895` and `incy=-73682745238224895`.

There is no issue when linking against `-lopenblas` instead of `-lopenblas_64` (with appropriate typedefs, of course).

Here is as minimal a reproducer as I could get quickly:

```c++
typedef long long BLAS_INT; // -lopenblas_64
// typedef int BLAS_INT; // -lopenblas

extern "C" {
void dbdsdc_(char *uplo, char *compq, BLAS_INT *n, double *d, double *e,
             double *u, BLAS_INT *ldu, double *vt, BLAS_INT *ldvt, double *q,
             BLAS_INT *iq, double *work, BLAS_INT *iwork, BLAS_INT *info);
}

int main() {
    char uplo = 'u';
    char compq = 'I';
    const BLAS_INT n = 2;
    double d[n] = {5.4649857042190426, 0.3659661906262579};
    double e[n - 1] = {0.0};
    const BLAS_INT ldu = 2;
    double u[ldu * n] = {0.99999999863569311, 0.0, -5.2236139796668049e-05, 1.0};
    const BLAS_INT ldvt = 2;
    double vt[ldvt * n] = {0.99999969576576153, -0.00078004383487901934,
                           0.00078004383487901934, 0.99999969576576153};
    double q;
    BLAS_INT iq;
    double work[3 * n * n * 2 + 4 * n];
    BLAS_INT iwork[8 * n];
    BLAS_INT info;
    dbdsdc_(&uplo, &compq, const_cast<BLAS_INT *>(&n), d, e, u,
            const_cast<BLAS_INT *>(&ldu), vt, const_cast<BLAS_INT *>(&ldvt), &q,
            &iq, work, iwork, &info);
}
```

**Comment by martin-frbg** [comment]
Can you please share which version you built, and how you built it (compiler version and cmake options) ?

**Comment by mckib2** [comment]
> Can you please share which version you built, and how you built it (compiler version and cmake options) ?

OpenBLAS commit c4a3bd9f4660c3df68fbf07a6322bd97a883a5ca
cmake version 3.22.1
GNU Make 4.3 Built for x86_64-pc-linux-gnu
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

`uname -a` reports:

```
Linux system76-pc 6.0.12-76060006-generic #202212290932~1671652965~22.04~452ea9d~dev-Ubuntu SMP PREEMPT_DY x86_64 x86_64 x86_64 GNU/Linux
```

I built like this:

```
git clone [this repo]
cd OpenBLAS
mkdir build
cd build
cmake -DINTERFACE64=ON -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=OFF ..
make -j
```

**Comment by brada4** [comment]
I think gfortran11 would use "new" ABI where sizeof() needs to be passed after each char?

**Comment by martin-frbg** [comment]
I cannot reproduce this (and I do not think the "hidden" extra arguments are an issue). Are you sure that you are linking your testcase against your build of OpenBLAS rather than something preinstalled with Ubuntu ?

**Comment by mckib2** [comment]
> I cannot reproduce this (and I do not think the "hidden" extra arguments are an issue). Are you sure that you are linking your testcase against your build of OpenBLAS rather than something preinstalled with Ubuntu ?

In GDB, it jumps to the sources of my local clone, so I don't believe it's linking against the wrong thing.  I'll try reproducing in a container to see if it's a local environment issue

**Comment by mckib2** [comment]
Couldn't reproduce in a container using Debian or Ubuntu base with g++-10 and g++-11 respectively, so I suspect you are correct that something is polluting my local environment.  Will close as there appears to be nothing wrong with the library itself
