### ISSUE TITLE
Passing appropriate compile flags to `getarch`

### ISSUE THREAD

**Issue by smartalecH** [xianyi/OpenBLAS#3885]
I'm building `openblas` on a `Centos7` system with two `libc` versions. As such, I need to specify the proper `libc` location along with the dynamic linker as compiler flags (e.g. `LDFLAGS='-Wl,-rpath,/some/path/lib -Wl,--dynamic-linker,/some/other/path/ld.so`). 

When `getarch` gets compiled, it manages to pick up on the new `libc` at compile time, but can't pick it up at *runtime*. As such, the `make` process dies the first time `getarch` is called.

Looking through the `Makefile`, I see that `getarch` is compiled with a few env variables:

https://github.com/xianyi/OpenBLAS/blob/fab84910ea320d3e7401752acc6b3997cd0e4f94/Makefile.prebuild#L79-L82

I tried to manually set `$HOST_CFLAGS` and `$GETARCH_FLAGS` in my shell before making, but that didn't seem to help (I'm assuming it just gets overwritten).

Is there a recommended way to pass extra flags to `getarch` (along with any other auxilliary binaries that may be compiled during the build process)?

**Comment by martin-frbg** [comment]
"can't pick it up at runtime" reads like you need to set LD_LIBRARY_PATH . (And it is not quite clear to me why you would be running a system with two "competing" libc versions - isn't that just asking for trouble when you could use a chroot environment, container or virtual machine for the "other" instance ?)

**Comment by smartalecH** [comment]
Thanks, @martin-frbg, for your comment.

> "can't pick it up at runtime" reads like you need to set LD_LIBRARY_PATH .

Unfortunately, you can't add arbitrary `libc` libraries to `LD_LIBRARY_PATH` without crashing your system (where the kernel etc. depend on the system-loaded `libc`). The solution is to bake it _privately_ in the binary's `rpath`. (you also need to bake in the updated dynamic linker of course).

> And it is not quite clear to me why you would be running a system with two "competing" libc versions

This is quite common on large-scale system fleets containing several complicated build tools and messy build matrices. Working with multiple `libc` distributions isn't an issue provided you can ship dynamic runtime paths.

> isn't that just asking for trouble when you could use a chroot environment, container or virtual machine for the "other" instance

I'm working with some complicated internal infra that doesn't allow any of these "tricks", unfortunately.

I'm guessing the easiest path forward is for me to just manually patch the makefile with a custom flag I can set.

**Comment by martin-frbg** [comment]
That would probably be the best solution for your scenario. (Though I still do not quite understand why you wouldn't simply build on a "system" (as above) with just the desired libc, thus avoiding the getarch conundrum, and then deploy to your multilib infra from there.)

**Comment by brada4** [comment]
You need to set HOSTCC=cc to run it flagless. Careful  - it will detect TARGET name and cpu count from  host unless explicitly specified
