### ISSUE TITLE
how to build openblas with openmpi in non standard location

### ISSUE THREAD

**Issue by beew** [xianyi/OpenBLAS#3887]
Hi, I am trying to build openblas from source  against openmpi installed in /opt/openmpi. How should I pass that information to make?

OS is Ubuntu 22.04.

Thanks.

**Comment by martin-frbg** [comment]
Try setting CC and FC to the full path of the respective wrapper script for the C and Fortran compilers, as in `make CC=/opt/openmpi/bin/mpicc  FC=/opt/openmpi/bin/mpifort`.

**Comment by martin-frbg** [comment]
Did that work for you, i.e. can this ticket be closed ?

**Comment by beew** [comment]
Yes it works. thanks.
