### ISSUE TITLE
[QUESTION] How OpenBLAS manages big.LITTLE configurations?

### ISSUE THREAD

**Issue by jgpallero** [xianyi/OpenBLAS#3888]
Hi,

How OpenBLAS works in big.LITTLE configurations? This chipsets have M performance cores (P-core) and N efficient cores (E-core). Works OpenBLAS with the total number of cores or uses only the P-cores?

Thanks

**Comment by martin-frbg** [comment]
There is currently no mechanism in OpenBLAS to distinguish between big and little, so either total number or however the OS reacts to compute demand (unless the cores are different enough that one can build for either cpu type as a specific TARGET)
