### ISSUE TITLE
MSB3073  command:setlocal

### ISSUE THREAD

**Issue by lannisite110** [xianyi/OpenBLAS#3890]
已启动生成…
1>------ 已启动生成: 项目: genlapacke, 配置: Release x64 ------
2>------ 已启动生成: 项目: INSTALL, 配置: Release x64 ------
2>-- Install configuration: "Release"
2>CMake Error at cmake_install.cmake:39 (file):
2>  file cannot create directory: C:/Program Files/OpenBLAS/lib.  Maybe need
2>  administrative privileges.
2>
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: 命令“setlocal
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: "C:\Program Files\CMake\bin\cmake.exe" -DBUILD_TYPE=Release -P cmake_install.cmake
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :cmEnd
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :cmErrorLevel
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: exit /b %1
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :cmDone
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :VCEnd”已退出，代码为 1。
2>已完成生成项目“INSTALL.vcxproj”的操作 - 失败。
========== 生成: 成功 1 个，失败 1 个，最新 24 个，跳过 0 个 ==========

**Comment by martin-frbg** [comment]
This is your problem:
2> file cannot create directory: C:/Program Files/OpenBLAS/lib. Maybe need
2> administrative privileges.

Either run Visual Studio as Administrator (so that you are allowed to write to C:\Program Files), or set  CMAKE_INSTALL_PREFIX to some other folder where you have write permissions.
