### ISSUE TITLE
Missing libm linkage when building with cmake

### ISSUE THREAD

**Issue by antonio-rojas** [xianyi/OpenBLAS#3892]
I'm building openblas with
```
  cmake -B build64 -S OpenBLAS \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DBUILD_SHARED_LIBS=ON \
    -DBUILD_WITHOUT_LAPACK=ON \
    -DBUILD_WITHOUT_CBLAS=ON \
    -DBUILD_TESTING=OFF \
    -DNO_AFFINITY=ON \
    -DUSE_OPENMP=1 \
    -DCORE=CORE2 \
    -DDYNAMIC_ARCH=ON \
    -DINTERFACE64=1
```
and the resulting `libopenblas64.so` library is not linked to `libm.so`, even though it calls libm functions, such as `sqrt`.
Building without `-DINTERFACE64=1` produces a library which is correctly linked to `libm.so`

**Comment by martin-frbg** [comment]
What is your operating system please ? I cannot seem to reproduce this on Linux.

**Comment by antonio-rojas** [comment]
Arch Linux x86_64

**Comment by martin-frbg** [comment]
Interesting. Are you building the 0.3.21 release, or current github `develop` branch ?

**Comment by antonio-rojas** [comment]
Tried both, same result

**Comment by martin-frbg** [comment]
Hmm, what compiler (and version) ?

**Comment by antonio-rojas** [comment]
gcc 12.2.1

**Comment by martin-frbg** [comment]
Got it now - appears to be independent from the INTERFACE64 setting. The changed CMakeLists.txt from #3895 should address it (and I am currently doubting if the EXTRALIB that gets so painstakingly set as in the gmake build is actually used anywhere in the cmake build at all...)

**Comment by antonio-rojas** [comment]
> Got it now - appears to be independent from the INTERFACE64 setting. 

Right, sorry for the confusion - I was actually testing an older build made with the plain Makefile
