### ISSUE TITLE
Builder insists on using p7-64 for some reason.

### ISSUE THREAD

**Issue by cponder** [xianyi/OpenBLAS#3901]
I'm using these commands (Dockerfile syntax):
```
ENV CC  "nvc"
ENV CXX "nvc++"
ENV F90 "nvfortran"
ENV FC  "nvfortran"
ENV  FCFLAGS "-O2 -m64 -tp=zen2 -fpic"
ENV   CFLAGS "-O2 -m64 -tp=zen2 -fpic"
ENV CXXFLAGS "-O2 -m64 -tp=zen2 -fpic"
ENV  LDFLAGS "-O2 -m64 -tp=zen2 -fpic"

ARG OPENBLAS_VERSION=0.3.21
RUN cd /usr/local/src && \
    curl --retry 5 -fSsL "https://github.com/xianyi/OpenBLAS/archive/refs/tags/v${OPENBLAS_VERSION}.tar.gz" | tar xz && \
    cd OpenBLAS-* && \
    export CFLAGS="-O2 -m64 -tp=zen2 -fpic" && \
    make USE_OPENMP=1 && \
    make install PREFIX=/usr/local && \
    rm -Rf /usr/local/src/*
```
I get a lot of these messages
```
nvc-Warning--tp p7-64 is not supported. Defaulting to -tp px. See -help -tp for supported target processors.
nvc-Warning--tp p7-64 is not supported. Defaulting to -tp px. See -help -tp for supported target processors.
```
Note that the compile-line starts off correctly with ```-tp=zen2``` but then the ```-tp p7-64``` garbage gets appended:
```
nvc -O2 -m64 -tp=zen2 -fpic -O2 -DMAX_STACK_ALLOC=2048 -mp -tp p7-64 -D__MMX__ -Mnollvm -DF_INTERFACE_PGI -fPIC -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=16 -DMAX_PARALLEL_NUMBER=1 -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.21\" -msse3 -mssse3 -msse4.1 -mavx -mavx2 -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I. -O2 -DSMALL_MATRIX_OPT -DMAX_STACK_ALLOC=2048 -mp -tp p7-64 -D__MMX__ -Mnollvm -DF_INTERFACE_PGI -fPIC -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=16 -DMAX_PARALLEL_NUMBER=1 -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.21\" -msse3 -mssse3 -msse4.1 -mavx -mavx2 -DASMNAME=samin -DASMFNAME=samin_ -DNAME=samin_ -DCNAME=samin -DCHAR_NAME=\"samin_\" -DCHAR_CNAME=\"samin\" -DNO_AFFINITY -I.. -I. -UDOUBLE  -UCOMPLEX -c -DUSE_ABS -DUSE_MIN max.c -o samin.o
```
How do I prevent this? There are other failures later, I want to get this cleaned up.

**Comment by cponder** [comment]
This is using 0.3.21. It also gives this syntax error at the beginning:
```
getarch.c:
"cpuid_x86.c", line 433: warning: variable "numcalls" was set but never used [set_but_not_used]
      int numcalls;
          ^
Remark: individual warnings can be suppressed with "--diag_suppress <warning-name>"
./f_check: 96: [: Illegal number:   
expr: syntax error: unexpected argument '11'
make[1]: Entering directory '/usr/local/src/OpenBLAS-0.3.21/interface'
expr: syntax error: unexpected argument '11'
```

**Comment by brada4** [comment]
If you set cflags to garbage you get garbage back.
You must use parameters CC=nvcc FC=nvfortran TARGET=ZEN without setting CFLAGS etc.
Also you need to repeat those parameters for `make install`
Best way to prevent this from happening again is to read README markdown file supplied and not deleting build artifacts to cover up failures (in Docker syntax if you prefer)

**Comment by martin-frbg** [comment]
p7-64 used to be the safest choice in earlier pgc/nvc versions to achieve a 64bit build, that's why it still gets added in the makefiles. Does this prevent compilation for you now, or is it only a nuisance ?
The expr error is _probably_ coming from a failed attempt to query the compiler version, which release of nvidia hpc is this ?

**Comment by cponder** [comment]
I'm using an NVHPC development version post- 23.1.
This may just be a problem with these dev-compilers.
It'd just been a nuisance before, but I'm seeing another error now and I want to make sure the architecture flags are set correctly before I troubleshoot further.
The ```/proc/cpuinfo``` on the node says
```
model name  : AMD EPYC 7742 64-Core Processor
```

**Comment by martin-frbg** [comment]
Makefile.system is where the p7-64 gets added for old nvc, newer releases should get `-tp px` instead but apparently the
parsing of  `nvc --version` fails (which is probably where the expr error is generated, not in f_check). Most likely your development version has some new formatting of the version message (perhaps even just from being an internal development build?), f_check probably stumbles over some mention of GNU or GCC in it as it tries to identify the make and version of the fortran compiler

**Comment by cponder** [comment]
Here's a sample (from installing an earlier version of the dev-compiler):
```
--> ./nvc --version

nvc Rel Dev-r221300 64-bit target on x86-64 Linux -tp haswell 
NVIDIA Compilers and Tools
Copyright (c) 2022, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
```
Is there a setting I can use to bypass this check?

**Comment by martin-frbg** [comment]
OK, thanks, I guess this looks nowhere like what your official releases have, no wonder parsing fails here.
Unfortunately I do not see an easy way to override this, probably best to hack f_check and Makefile.system for now (setting both NEWPGI and NEWPGI2 to 1 in the latter around line 960)

**Comment by cponder** [comment]
Here's what the official release gives:
```
--> nvc --version

nvc 23.1-0 64-bit target on x86-64 Linux -tp haswell 
NVIDIA Compilers and Tools
Copyright (c) 2023, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
```
So, aside from the year on the third line, it looks like this is the diff:
```
nvc Rel Dev-r221300 64-bit target on x86-64 Linux -tp haswell 
nvc 23.1-0 64-bit target on x86-64 Linux -tp haswell 
```

**Comment by cponder** [comment]
And, just for the record, clearing the ```CFLAGS``` etc. and making the ```TARGET``` explicit didn't make any difference:
```
ARG OPENBLAS_VERSION=0.3.21

RUN cd /usr/local/src && \
    curl --retry 5 -fSsL "https://github.com/xianyi/OpenBLAS/archive/refs/tags/v${OPENBLAS_VERSION}.tar.gz" | tar xz && \
    cd OpenBLAS-* && \
    unset FCFLAGS CFLAGS CXXFLAGS LDFLAGS && \
    make TARGET=ZEN USE_OPENMP=1 && \
    make install TARGET=ZEN PREFIX=/usr/local && \
    rm -Rf /usr/local/src/*
```

**Comment by martin-frbg** [comment]
ok, but the missing version number (and non-numerical stuff put in its place) make a world of difference for poor dumb scripts... and for something never to be seen in the wild. Does nvc have a hidden option to fake a normal-looking version number ? I do not think what we are doing here is extremely unusual (though there may be some more elegant ways like looking for a `-tp` option already present)

**Comment by brada4** [comment]
You nwed ro eepeat openmp for install

**Comment by martin-frbg** [comment]
Does this help to avoid the added `-tp p7-64`  (cannot test it myself immediately) ?
[Makefile.system.txt](https://github.com/xianyi/OpenBLAS/files/10683676/Makefile.system.txt)

**Comment by cponder** [comment]
Yeah it looks like it works for me. Is this a proposed fix to the code, or just a workaround for me to use?
If I use it as-is then it doesn't assign any architecture:
```
nvc -O2 -DSMALL_MATRIX_OPT -DMAX_STACK_ALLOC=2048 -mp -D__MMX__ -Mnollvm -DF_INTERFACE_PGI -fPIC -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=16 -DMAX_PARALLEL_NUMBER=1 -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.21\" -msse3 -msse4.1 -mavx -mavx2 -DASMNAME=dgemm_tt -DASMFNAME=dgemm_tt_ -DNAME=dgemm_tt_ -DCNAME=dgemm_tt -DCHAR_NAME=\"dgemm_tt_\" -DCHAR_CNAME=\"dgemm_tt\" -DNO_AFFINITY -I../.. -DDOUBLE  -UCOMPLEX  -c -DDOUBLE -UCOMPLEX -DTT gemm.c -o dgemm_tt.o
```
I can fall back to using my own assignments then
```
ENV  FCFLAGS "-O2 -m64 -tp=zen2 -fpic"
ENV   CFLAGS "-O2 -m64 -tp=zen2 -fpic"
ENV CXXFLAGS "-O2 -m64 -tp=zen2 -fpic"
ENV  LDFLAGS "-O2 -m64 -tp=zen2 -fpic"
```
and I see the flags come through:
```
nvc -O2 -m64 -tp=zen2 -fpic -O2 -DMAX_STACK_ALLOC=2048 -mp -D__MMX__ -Mnollvm -DF_INTERFACE_PGI -fPIC -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=256 -DMAX_PARALLEL_NUMBER=1 -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.21\" -msse3 -msse4.1 -mavx -mavx2 -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I. -O2 -DSMALL_MATRIX_OPT -DMAX_STACK_ALLOC=2048 -mp -D__MMX__ -Mnollvm -DF_INTERFACE_PGI -fPIC -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=256 -DMAX_PARALLEL_NUMBER=1 -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.21\" -msse3 -msse4.1 -mavx -mavx2 -DASMNAME=dgemm_tt -DASMFNAME=dgemm_tt_ -DNAME=dgemm_tt_ -DCNAME=dgemm_tt -DCHAR_NAME=\"dgemm_tt_\" -DCHAR_CNAME=\"dgemm_tt\" -DNO_AFFINITY -I../.. -DDOUBLE  -UCOMPLEX  -c -DDOUBLE -UCOMPLEX -DTT gemm.c -o dgemm_tt.o
```
I'm don't think that the ```-Mnollvm``` is relevant these days.

**Comment by cponder** [comment]
There's also still this error-message, I gather it's from the parser not recognizing the string it's getting:
```
./f_check: 96: [: Illegal number:   
expr: syntax error: unexpected argument '11'
make[1]: Entering directory '/usr/local/src/OpenBLAS-0.3.21/interface'
expr: syntax error: unexpected argument '11'
```

**Comment by martin-frbg** [comment]
> Yeah it looks like it works for me. Is this a proposed fix to the code, or just a workaround for me to use? If I use it as-is then it doesn't assign any architecture:

It was supposed to be a(n untested) fix - the intention was that it would not add any `-tp` option if there was one already in the user-provided flags. Maybe the `findstring` should actually still be run against CFLAGS and not CCOMMON_OPT at that point in the build so that it still does the `-tp px` when there is none specified.

The other problems will certainly go away once the compiler actually identifies as `nvc 23.2` or whatever:
> I'm don't think that the `-Mnollvm` is relevant these days.

Certainly, you are only seeing this because your pre-release compiler has no usable version number that would identify it as a "NEWPGI" not requiring it

> There's also still this error-message, I gather it's from the parser not recognizing the string it's getting:

Yes, both f_check and Makefile.system try to extract the major version number, but both come up empty so the subsequent conditionals see only one argument in a comparison.

**Comment by martin-frbg** [comment]
Try this one please (findstring syntax fix and now checking CFLAGS instead of CCOMMON_OPT, plus I actually gave this a very quick test):
[Makefile.system.txt](https://github.com/xianyi/OpenBLAS/files/10690150/Makefile.system.txt)

**Comment by cponder** [comment]
This one still gives the
```
./f_check: 96: [: Illegal number:   
expr: syntax error: unexpected argument '11'
make[1]: Entering directory '/usr/local/src/OpenBLAS-0.3.21/interface'
expr: syntax error: unexpected argument '11'
```
and the ```-Mnollvm```.

**Comment by martin-frbg** [comment]
Of course it does - as I wrote above, this is _only_ to address the unwanted `-tp p7-64` . Everything else is caused by your non-release compiler not having a regular version number and IMHO is not worth "fixing" in OpenBLAS. I do not expect that they break the build for you - if you are wary of possible side effects of the unwanted ` -D__MMX__ -Mnollvm` you can just delete that line in Makefile.system for your internal tests. (Or set NEWPGI=1 and NEWPGI2=1 right above the conditionals like a working version check would.)

**Comment by brada4** [comment]
@cponder what is `/bin/sh`  in your container?
In ideal world shell should not spit diagnostics from `[ -z`

**Comment by martin-frbg** [comment]
There _is_ no test for an empty version string, but this would not happen with a "regular" build of the compiler anyway and there is nothing to be gained from blindly suppressing the error message.

**Comment by cponder** [comment]
I use this command in the container
```
SHELL ["/bin/bash", "-c"]
```
I'm not an expert on this, though, I just copied elements from other Dockerfile's that I've looked at.

**Comment by cponder** [comment]
The real build failure I'm seeing is this:
```
NVC++-S-0155-Invalid atomic update statement.  (zherk_k.c: 392)
NVC++-S-0155-Invalid atomic update statement.  (zherk_k.c: 452)
NVC++-S-0155-Invalid atomic update statement.  (gemm3m.c: 755)
NVC++-S-0155-Invalid atomic update statement.  (gemm3m.c: 795)
NVC++/x86-64 Linux Rel Dev-r224273: compilation completed with severe errors
```
I'm taking this up with my compiler people. But I wanted to clear-out the issue of conflicting ```-tp``` flags to make sure that wasn't triggering this problem.

**Comment by martin-frbg** [comment]
Strange message, and unfortunately hard to put a source line to it due to the inclusion of another source file. (Does nvc  include comments and preprocessor statements in its line count at the stage this error message was generated ?) Certainly nothing obvious to me and nothing any other compiler has flagged before on any platform AFAIK.

**Comment by cponder** [comment]
Yeah. I figure this is a problem a the compiler end -- but wanted to make sure it wasn't just caused by trying to use the wrong instruction set.
Pulling down this new Makefile is enough of a workaround for the purpose of using this development compiler; I don't know if you want to use it as the standard one or not.
I'll go ahead and close this as a bug since I don't expect you to support the dev-compiler.
Hopefully I'll have some resolution on the Atomic stuff that I can clarify later.
