### ISSUE TITLE
Upload source tarballs to old releases

### ISSUE THREAD

**Issue by giordano** [xianyi/OpenBLAS#3903]
For OpenBLAS v0.3.10 and older releases there's no stable URL to use to download the source code from as a tarball, this is important for downstream packagers.  No, github-generated archives [are not stable](https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/).  It'd be helpful if you could upload the source archives as you did for newer releases.

**Comment by martin-frbg** [comment]
I do not understand why anybody would want to package a release from three years ago today, so why is this suddenly important ?

**Comment by brada4** [comment]
Concerns were raised around time of 0.3.11 and since then checksums of files generated at time of release are published along with sourceforge links. For sake of history pick those ancient file sums from debian or freebsd.

**Comment by giordano** [comment]
> I do not understand why anybody would want to package a release from three years ago today

Some users may have old pipelines which rely on being able to reproduce old software stacks.  For example Spack makes quite easy to build older versions of Spack, but [it currently uses](https://github.com/spack/spack/blob/02d3bd782d22d91aa8b18529db197efc749846ec/var/spack/repos/builtin/packages/openblas/package.py#L17) the automatically generated `/archive/` URL which isn't stable, and so this may break in the future.  Spack mitigates the problem by keeping a mirror of sources, but this is besides the point, other package managers may have similar needs but not a mirroring system in place.

Having stable source archives is important for multiple reasons, including reproducibility and security, see the discussion at https://github.com/orgs/community/discussions/46034 for plenty of examples, and why using a git repository as source is inconvenient in certain settings, so that a release tarball is really needed.

> so why is this suddenly important ?

Because GitHub [recently actively broke stability of automatically generated archives](https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/) (already linked my post above), which is something they did already in the past, but this just highlights the need for more permanent archives to use for posterity.

**Comment by martin-frbg** [comment]
I'd advise very strongly against using an ancient OpenBLAS tarball (with all the defects found and fixed since then) in production. And for fault finding, git bisect should be a superior tool.
I am not even sure I have a complete set of "old" tarballs with known provenance down to their respective release date - certainly not all the way back to xianyi's first releases. So at best I would re-upload whatever github now carries with their current checksums.

**Comment by giordano** [comment]
> So at best I would re-upload whatever github now carries with their current checksums.

That'd be great, thanks.

**Comment by brada4** [comment]
>  GitHub recently actively broke 

It has happened previously silently.

**Comment by giordano** [comment]
I believe [I said the same already](https://github.com/xianyi/OpenBLAS/issues/3903#issuecomment-1424061272) in the following sentence of the text you quoted

> which is something they did already in the past, but this just highlights the need for more permanent archives to use for posterity.

**Comment by martin-frbg** [comment]
It just occured to me that the earlier releases and their md5sums are still available on openblas.sourceforge.net where releases are automatically copied to

**Comment by martin-frbg** [comment]
Done. (Not using the sourceforge packages as they turned out to be named by git hash instead of version number internally, which seemed impractical to me)

**Comment by giordano** [comment]
Perfect, thanks!
