### ISSUE TITLE
Cmake build fails with errors

### ISSUE THREAD

**Issue by 3e33** [xianyi/OpenBLAS#3908]
xianyi-OpenBLAS-b89fb70

Visual Studio compiler only, no Fortran

```
cmake -S . -B build -G "Ninja" -DDYNAMIC_ARCH=ON -DCMAKE_BUILD_TYPE=Release
cmake --build build --config Release

FAILED: driver/level3/CMakeFiles/driver_level3.dir/CMakeFiles/dsyrk_kernel_U.c.obj
xianyi-OpenBLAS-b89fb70/driver/level3/syrk_kernel.c(65): error C2057: expected constant expression
xianyi-OpenBLAS-b89fb70/driver/level3/syrk_kernel.c(65): error C2466: cannot allocate an array of constant size 0
xianyi-OpenBLAS-b89fb70/driver/level3/syrk_kernel.c(65): error C2133: 'subbuffer': unknown size

FAILED: driver/level3/CMakeFiles/driver_level3.dir/CMakeFiles/zsyrk_kernel_U.c.obj
xianyi-OpenBLAS-b89fb70/driver/level3/syrk_kernel.c(65): error C2057: expected constant expression
xianyi-OpenBLAS-b89fb70/driver/level3/syrk_kernel.c(65): error C2466: cannot allocate an array of constant size 0
xianyi-OpenBLAS-b89fb70/driver/level3/syrk_kernel.c(65): error C2133: 'subbuffer': unknown size

etc...

```

**Comment by martin-frbg** [comment]
which version of Visual C is this ? Apparently it is unable to preprocess the compile-time defined array size (or it "thinks" either of GEMM_UNROLL_MN or COMPSIZE is zero).
(In general you would be much better of with _any_ other compiler rather than VC, as it does not support any of the optimized assembly kernels)

**Comment by martin-frbg** [comment]
btw our CI jobs use "Visual Studio 17 2022" without problem (see config file azure-pipelines.yml), I think compilation also worked with VS2015 but  the same error was reported against VS2017 some time ago.

**Comment by 3e33** [comment]
It's Visual Studio 2022.
Microsoft (R) C/C++ Optimizing Compiler Version 19.32.31332 for x64

**Comment by martin-frbg** [comment]
Does it work when you use the cmake generator for Visual Studio instead of the one for Ninja ?This is what the CI job does.

**Comment by 3e33** [comment]
For now I was able to build it with LLVM following [the guide here](https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-in-Microsoft-Visual-Studio).

**Comment by 3e33** [comment]
I ran into another issue, even though I'm using `-DBUILD_SHARED_LIBS=ON` it's not generating a .dll file.
