### ISSUE TITLE
openblass.dll cannot be loaded (file not found error) Windows

### ISSUE THREAD

**Issue by 3e33** [xianyi/OpenBLAS#3911]
I see a similar unresolved issue here:
https://github.com/xianyi/OpenBLAS/issues/1321

The "file not found" error seems to happen when the .dll itself cannot be loaded, it's a very unhelpful error but I know at least one thing  that causes it and that's the .dll file not being able to find its dependencies. Unfortunately that didn't fix it for me.

I'm certain it has something to do with the compilation, but I don't know what it might be.
I have a working .dll downloaded from the internet, but I don't remember where I got it from.
[libopenblas.zip](https://github.com/xianyi/OpenBLAS/files/10744709/libopenblas.zip)

The interesting thing is the official conda openblas.dll also fails to load for me.
https://anaconda.org/conda-forge/libopenblas/files

So far I can't understand (other than the size difference) why one of them works and the other doesn't, and my own compiled .dll also doesn't work. Would be nice to figure this out. I'm hoping one of these build methods will eventually work.

Overall I have to say compiling OpenBLAS has been exceedingly painful. 😅

**Comment by martin-frbg** [comment]
Guess you could try the "dependencies" tool https://github.com/lucasg/Dependencies to find which other dll it is looking for. (Possibly it is something brought in by VS2022, and hopefully can be changed through some setting there).
The working dll you downloaded may have been from the OpenBLAS "Releases" page - this would have been a build I did with mingw.
Lastly I'd think your pain comes from trying to do all this on Windows...

**Comment by 3e33** [comment]
It's looking for flang.dll and its friends, but adding them to the same folder hasn't helped, so I'm out of ideas on  that.
The working libopenblas.dll doesn't have any dependencies at all, does that mean it was built without fortran?

**Comment by martin-frbg** [comment]
Could also mean that the fortran runtime was compiled in (i.e. statically linked), also with the latest release (0.3.21) it is possible to compile a slightly older (3.9 vs 3.11) version of LAPACK that has been converted to C, (mostly) removing the need for a fortran compiler.

**Comment by 3e33** [comment]
> Could also mean that the fortran runtime was compiled in (i.e. statically linked)

If you have time could you please go into detail on how that can be done? Maybe that could get it working.

**Comment by 3e33** [comment]
Alright I was able to get it working. Here are the build options, which are from `- job: Windows_clang_cmake` in [azure-pipelines.yml](https://github.com/xianyi/OpenBLAS/blob/develop/azure-pipelines.yml).

Also IMPORTANT is to use the LLVM that comes from conda, which I think is version 11. The latest LLVM doesn't work or maybe it's because flang isn't included in it, I don't know. Hope this helps anyone else trying to compile on Windows.

```
cmake -S . -B build -G "Ninja"^
 -DCMAKE_CXX_COMPILER=clang-cl^
 -DCMAKE_C_COMPILER=clang-cl^
 -DDYNAMIC_ARCH=ON^
 -DBUILD_SHARED_LIBS=ON^
 -DCMAKE_BUILD_TYPE=Release^
 -DBUILD_TESTING=OFF^
 -DBUILD_STATIC_LIBS=OFF^
 -DNOFORTRAN=1^
 -DMSVC_STATIC_CRT=ON^
 -DCMAKE_MT=mt
```
