### ISSUE TITLE
Feature Difference: Reference-LAPACK, lapack-netlib, this implementation (openblas)?

### ISSUE THREAD

**Issue by hergljkds** [xianyi/OpenBLAS#3912]
Simply explained, what are the general differences between:

Reference-LAPACK
lapack-netlib
this implementation (openblas)

?

**Comment by martin-frbg** [comment]
"netlib" and "Reference-LAPACK" are one and the same, the original reference implementation of LAPACK (and BLAS) written in Fortran.
OpenBLAS is an optimized reimplementation of the BLAS written in a mix of C and cpu-specific Assembler, it includes the LAPACK part of the reference implementation in its lapack-netlib directory
