### ISSUE TITLE
Windows平台使用vs Release下报错

### ISSUE THREAD

**Issue by ZhanghHaoDev** [xianyi/OpenBLAS#3916]
我在Windows下使用openblas，工具是vs2022，编译好openblas后调用openblas
在debug下没有问题，编译通过，但是在release下同样的配置却报错
这是我按文档添加的
![image](https://user-images.githubusercontent.com/29505921/220852485-ecea371e-3dfe-4a2e-843b-6155705644f3.png)
这是release下报错的信息
![image](https://user-images.githubusercontent.com/29505921/220852541-439041f0-86c5-4494-9796-f338055a91e0.png)

**Comment by martin-frbg** [comment]
Looks like an error in your installation of Visual Studio 2022 - I see no reason why a "Release" build would ignore complex.h. Maybe something like https://stackoverflow.com/questions/72968399/visual-studio-2022-showing-errors-for-everything

**Comment by ZhanghHaoDev** [comment]
我使用的是vs2022，没有安装NuGet 包，将.vs文件夹删除后，release下还是编译不过，还是报上面的错误，换成vs2017后release下也同样编译不过去
我尝试将vs修复也没有解决该问题
![image](https://user-images.githubusercontent.com/29505921/221080308-95eb2608-8621-4a4d-ad2f-99955ad0292f.png)

**Comment by ZhanghHaoDev** [comment]
但是在我的项目中只要包含#include "lapacke.h"该文件就会导致项目无法编译，vs没有识别#if defined(_MSC_VER) ，去掉“lapacke.h”后vs是可以识别#if defined(_MSC_VER)，编译也是可以通过的
我编译的方式是按照（https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-in-Microsoft-Visual-Studio）该文章编译的

**Comment by ZhanghHaoDev** [comment]
问题已经解决，是vs的问题，重新创建一个空的工程，将代码复制过去，重新链接，就可以解决

**Comment by martin-frbg** [comment]
Did you get it working with VS2022 now as well ? It looks like that version may have some problems with its own _MSC_VER macro - https://developercommunity.visualstudio.com/t/VS-2022-PREVIEW-_MSC_VER-not-displayed-c/1516513
