### ISSUE TITLE
[QUESTION] Does openblas_set_num_threads make global or thread-local effects?

### ISSUE THREAD

**Issue by A205B064** [xianyi/OpenBLAS#3917]
I want to know whether `openblas_set_num_threads`
- a) Make global effects and will cause problems when called currently. or
- b) Make thread-local effects. That is, if thread A calls `openblas_set_num_threads(n)`, then only subsequent calls to OpenBLAS functions in thread A will use `n` thread(s), like the MKL function [`mkl_set_num_threads_local`](https://www.intel.com/content/www/us/en/develop/documentation/onemkl-developer-reference-c/top/support-functions/threading-control/mkl-set-num-threads-local.html).

**Comment by brada4** [comment]
a) TRUE and FALSE = ?
b) it will be 1 thread in OMP parallel section,  and openblas_set_num_threads wdaps respective OMP function.

**Comment by martin-frbg** [comment]
global , like mkl_set_num_threads

**Comment by brada4** [comment]
... and it will not "cause problems"

**Comment by A205B064** [comment]
> it will be 1 thread in OMP parallel section, and openblas_set_num_threads wdaps respective OMP function.
@brada4 So OpenBLAS will honor OpenMP threading settings, and if nested parallism is need, it suffices to configure OpenMP setting accordingly? (Say `OMP_NUM_THREADS=2,4`, upper level code makes 2 concurrent calls to `DGEMM`, each `DGEMM` uses 4 threads)

**Comment by brada4** [comment]
It will always be one thread for calls inside OMP parallel section.
