### ISSUE TITLE
NUM_PARALLEL not taking effect

### ISSUE THREAD

**Issue by A205B064** [xianyi/OpenBLAS#3921]
I just noticed the NUM_PARALLEL build option which I never noticed before. Here's the comments for it in [Makefile.rule](https://github.com/xianyi/OpenBLAS/blob/v0.3.21/Makefile.rule#L93-L98)

> \# If you have enabled USE_OPENMP and your application would call
\# OpenBLAS's calculation API from multiple threads, please comment this in.
\# This flag defines how many instances of OpenBLAS's calculation API can actually
\# run in parallel. If more than NUM_PARALLEL threads call OpenBLAS's calculation API,
\# they need to wait for the preceding API calls to finish or risk data corruption.
\# NUM_PARALLEL = 2

My app can make up to 8 concurrent calls into OpenBLAS, which according to the comments, might suffer performance loss or even data corruption. To find it out, I did the following test.

I built OpenBLAS-v0.3.21 with `USE_OPENMP=1 NUM_THREADS=16 NUM_PARALLEL=2`, and run my app using 8 threads. According to the comments, since my app makes up to `8 > NUM_PARALLEL` concurrent calls into OpenBLAS, there might be performance loss or even data corruption. But neither happened. (and I checked that CPU usage was 800%)

Is it simply by luck that my app worked normally?

**Comment by martin-frbg** [comment]
Could be luck (threads finishing in time), could also be the kind of calls your code makes. If I remember correctly, it was primarily GEMV that this problem was seen with

**Comment by A205B064** [comment]
> Could be luck (threads finishing in time), could also be the kind of calls your code makes. If I remember correctly, it was primarily GEMV that this problem was seen with

If so, is there big overhead of setting a large `NUM_PARALLEL`?

**Comment by martin-frbg** [comment]
I hope not, but there are some are areas that have not been properly tested, especially on bigger multicore hardware. Some of the defects that led to the introduction of NUM_PARALLEL may have been simple locking bugs in the earlier versions of OpenBLAS they were observed with. But there are a few old issue tickets still kept open in case the problem persists.

**Comment by brada4** [comment]
It is a measure to avoid oversubscription of CPU-s that would sometimes add misery to numproc ** 3 . Say not issue with 4 cores, but quite some for 128.
