### ISSUE TITLE
openblas_set_num_threads with USE_OPENMP=1 

### ISSUE THREAD

**Issue by grisuthedragon** [xianyi/OpenBLAS#3933]
During some tests with OpenBLAS and StarPU I ran into trouble since the algorithms implemented using StarPU run themselves in parallel, but require OpenBLAS to run with only thread. Outside the StarPU code, I need OpenBLAS with OpenMP enabled since it is used in different workshare constructs.  So wrote the following piece of code:

```C

 int old_threads = openblas_get_num_threads(); 
 openblas_set_num_threads(1); 
 
 // .... do the stuff in STARPU 

 openblas_set_num_threads(old_threads); 

 // ... continue with the code. 
```
Inside the StarPU code, OpenBLAS is called from PThreads. Since I recognized a drastic performance decrease in the STARPU part, I took a closer look at the number of threads, by placing a `printf` in `static __inline int num_cpu_avail(int level)` (`common_thread.h`). After running the code on my six-core system, each call to `num_cpu_avail` showed 6 cores available instead of one, as set before. Regarding the behavior of `openblas_set_num_threads` this should be changed, since using it from a Pthread-enabled OpenBLAS, it does exactly what I expected in the code above (and warns afterwards being used in OpenMP workshare constructions)

**Comment by martin-frbg** [comment]
Not sure if I understand the problem correctly, but if you are on 0.3.21 does defining the environment variable OMP_ADAPTIVE get you closer to the desired behaviour ? (And I assume here that StarPU is using OpenMP itself, and it is somehow not desirable to keep a separate, singlethreaded build of libopenblas just for use with StarPU)

**Comment by grisuthedragon** [comment]
Outside the StarPU enabled algorithms, I want to use OpenMP in multithreaded mode. StarPU does not use OpenMP for threading. It has its own scheduler on top of PTHreads, thus OpenBLAS-OpenMP does not detect that it runs in parallel. When I am using OpenBLAS-Pthread, I can set the number of threads to 1 using `openblas_set_num_threads` and reset it afterward. With OpenBLAS-OpenMP this does not work.  I tried the `OMP_ADAPTIVE` variable with the latest OpenBLAS and it does not change its behavior. Using a sequential OpenBLAS library would not be an option since the non-StarPU parts of the code still require a multithreaded BLAS for fast operation.

**Comment by brada4** [comment]
Set `STARPU_NCPU=1` (questionable - may set thread affinity to one core) or use starpu openmp as openmp implementation for openblas.
different openmp implementations are compatible at source code level, not binarily.

**Comment by martin-frbg** [comment]
Hm, are we certain that StarPU does not import any OpenMP on startup, even if your code does not make use of it directly ? (The other explanation would be that it is some recent regression in OpenBLAS, but I do not think my introduction of OMP_ADAPTIVE could be the culprit, and there were complaints about the performance impact of tearing down OpenMP threads on set_num_threads(1) before this change that is actually a conditional reversal of a prior PR )

**Comment by martin-frbg** [comment]
(TLDR: is it different with 0.3.20 ?)

**Comment by brada4** [comment]
> StarPU can also be used through OpenMP pragmas

So it is an OpenMP implementation on its own.

**Comment by grisuthedragon** [comment]
StarPU can provide it's own OpenMP implementation, which needs to be enabled during compile time and only working with a special compiler suite. For this reason we are using StarPU without OpenMP support. 

We have:
```
grep -Rn "OPENMP" include/starpu/1.3/starpu_config.h 
97:/* #undef STARPU_OPENMP */
```
and 
```
$ nm lib/libstarpu-1.3.so | grep omp_ 
``` 
gives nothing. 

Again, I did some tests and checking the return value of `num_cpu_avail` and it seems that it does not get influences by the setting of `openblas_set_num_threads`.

So I could recreate the problem without using  StarPU. 
See https://gist.github.com/grisuthedragon/99c282f9322fb0319be990f49b525621 
I compiled and linked the Code against OpenBLAS with OpenMP and get on a six-core System:
```
$ ./gemm_test 
blas_cpu_number: 6
blas_cpu_number: 6
blas_cpu_number: 6
blas_cpu_number: 6
blas_cpu_number: 6
blas_cpu_number: 6
time: 0.992275
$ OMP_NUM_THREADS=1 ./gemm_test 
blas_cpu_number: 1
blas_cpu_number: 1
blas_cpu_number: 1
blas_cpu_number: 1
blas_cpu_number: 1
blas_cpu_number: 1
time: 0.626285
$ OMP_NUM_THREADS=2 ./gemm_test 
blas_cpu_number: 2
blas_cpu_number: 2
blas_cpu_number: 2
blas_cpu_number: 2
blas_cpu_number: 2
blas_cpu_number: 2
time: 1.14317
```
(I added a printf at the end of `num_cpu_avail`.)
So setting the number of threads gets ignored. Even if I use `omp_set_num_threads` before starting the pthreads, this does not work. 

If I use OpenBLAS-PThread with the same example, I get:
```
$ ./gemm_test 
blas_cpu_number: 1
blas_cpu_number: 1
blas_cpu_number: 1
blas_cpu_number: 1
blas_cpu_number: 1
blas_cpu_number: 1
time: 0.679818
```
which is the behaviour one should expect after a call to `openblas_set_num_threads`.

**Comment by brada4** [comment]
There is no other way for StarPU to automatically communicate "in parallel section" to OpenBLAS than OpenBLAS using StarPU as OpenMP implementation.

**Comment by grisuthedragon** [comment]
@brada4 As I said we do not use StarPU as OpenMP implementation due to the problems with the compilers, e.g. it does not with GCC and  GOMP. I already ask the StarPU team how to deal with this problem, and their answer was to reduce the number of threads used by the BLAS libary to 1 before starting the StarPU codes and reset the number of threads afterward. 

The crucial point of this bug is not that we are using StarPU in parts of our code. The problem is that `openblas_set_num_threads` behaves different depending on OpenBLAS is compiled with OpenMP or PThread threading. (As my gist example shows).

**Comment by brada4** [comment]
So use pthread OpenBLAS, it is default when compiling OpenBLAS, in OpenMP case thread number functions are wrappers for OpenMP functions. Sort of it is made sure they get called, but you taste the result.

**Comment by grisuthedragon** [comment]
We have to use OpenBLAS with OpenMP since other parts of the code require this.  So discussing using a different OpenBLAS-flavor here does not make sense. 

I figured out that when setting the number of threads with `openblas_set_num_threads` calls `omp_set_num_threads` correctly, but once a new pthread is starting the internal `icv` for the maximum number of threads in GNU OpenMP is reset to the number of CPU cores / the value of `OMP_NUM_THREADS`. But the OpenBLAS variable `blas_cpu_number` stays 1. Now the next call to `num_cpu_avail` calls `omp_get_max_threads` which returns the higher value again and thus the number of threads gets increased again.

**Comment by martin-frbg** [comment]
Could be that there is some circular logic in place where the number of openmp threads always gets reinitialized from the environment variable when  queried by openblas_get_num_threads. I will probably need a few hours before I can turn my attention to this

**Comment by brada4** [comment]
did you get anywhere with STARPU_NCPU=1, i.e that OMP runs in all cores while starpu serializes ?work units? or its always affined to single core then?

**Comment by grisuthedragon** [comment]
@brada4  `STARPU_NCPU=1` and `openblas_set_num_threads(1)` leads to the usage of 6 CPU cores. It is the same result setting `THREADS=1` in my gist example.

**Comment by martin-frbg** [comment]
this is num_cpu_avail (from common_thread.h) unconditionally setting the thread count from the OMP environment variable on every invocation (which makes it happen in the interface codes of basically all BLAS functions, when what they actually want to do is to _know_ the count). At the very least this code must learn to recognize that the thread count was actively changed by set_num_threads already...

**Comment by grisuthedragon** [comment]
So introducing an internal flag, that is set once the user calls `openblas_set_num_threads` such that `num_cpu_avail` knows about this and avoids calling `omp_get_max_threads`. Additionally (to restore the default behavior), reset the flag if `openblas_set_num_threads(omp_get_max_num_threads())` is called or `-1` is passed as number of threads?

**Comment by brada4** [comment]
You can make gomp parallel section with one thread when called from starpu thread?

Yes, that API is not very strongly defined. zero and negative values can serve your purpose as they are kinda undefined now.

**Comment by grisuthedragon** [comment]
> You can make gomp parallel section with one thread when called from starpu thread?

Such things are possible. But you have to specify the `num_threads` clause and specify that the worker task is a multithreaded one. The number of threads is given by star pu and this value needs to be included in the `num_threads` clause.

**Comment by brada4** [comment]
Its a possibility within current state of APIs - make fake parallel section to suppress openblas+openmp threading. No need to use shaky set_num_threads API.

**Comment by grisuthedragon** [comment]
That sound like a dirty workaround then getting a proper working set-number-of-threads function.

**Comment by brada4** [comment]
You probably mean proper OMP support out of starpu? proposed workaround will work before and after. But discussion on future of _num_cpu_ functions is welcome.

**Comment by grisuthedragon** [comment]
@brada4 As I figured out with the example, it is NOT only a problem of StarPU. One can get into the same trouble if OpenBLAS-OpenMP is used from pure PThread-enabled code. And thus, the behaviour of `openblas_set_num_threads` must be fixed. Indeed, the interoperability of StarPU and OpenMP needs to be improved as well.

**Comment by brada4** [comment]
You cannot have stable mix of varied thread control mechanisms. Its not OpenBLAS-s fault, its like you know, computers work that way.

**Comment by grisuthedragon** [comment]
That the behavior of `openblas_set_num_threads` function changes its behaviour is, from my point of view, not covered by the variety of thread control mechanism.

**Comment by martin-frbg** [comment]
@brada4 you spend way too much energy here just to be contrarian. Kindly stop alienating other contributors.

**Comment by martin-frbg** [comment]
@grisuthedragon yes such an internal flag is what I have in mind, there may be other, more elegant solutions though
