### ISSUE TITLE
Cross compiling fails with cmake for CORTEXA53 since 0.3.19

### ISSUE THREAD

**Issue by qubeck** [xianyi/OpenBLAS#3937]
The optimizations introduced in 0.3.19 with [302f226](https://github.com/xianyi/OpenBLAS/commit/302f22693a6dabe0d04d22e2e0e17d80c9242b6a) are leading to the following cross compilation error if cmake build is used:

> /build/openblas/kernel/CMakeFiles/dgemm_kernel.c:8:10: fatal error: /src/openblas/kernel/arm64/dgemm_kernel_**8x4**_cortexa53.c: No such file or directory
>     8 | #include "/src/openblas/kernel/arm64/dgemm_kernel_8x4_cortexa53.c"

I nailed it down to the fact that while in cross compile the prebuild.cmake becomes involved to apply the architecture specific settings, subsequently setting the DGEMM_UNROLL_M to the wrong/old value. It seems that the cross compile case wasn't covered by [302f226](https://github.com/xianyi/OpenBLAS/commit/302f22693a6dabe0d04d22e2e0e17d80c9242b6a) for the CORTEXA53 yet...

A propper fix would be to apply the DGEM_UNROLL_M/N also TCORE specific in [prebuild.cmake:889](https://github.com/xianyi/OpenBLAS/blob/develop/cmake/prebuild.cmake#L889) for the CORTEXA53:

```
if ("${TCORE}" STREQUAL "CORTEXA53")
    set(DGEMM_UNROLL_M 4)
    set(DGEMM_UNROLL_N 4)
else ()
    set(DGEMM_UNROLL_M 8)
    set(DGEMM_UNROLL_N 4)
endif ()
```

[fix_DGEMM_UNROLL_MN_for_cortexa53.patch](https://github.com/xianyi/OpenBLAS/files/10932685/fix_DGEMM_UNROLL_MN_for_cortexa53.patch)

**Comment by martin-frbg** [comment]
Oh right, sorry that happened. Guessing it would probably make sense to replace that long and ungainly table with a proper parser for  param.h at some point to prevent this from happening again.

**Comment by JonathanGirardeau** [comment]
Hi @martin-frbg , I encounter the same build issue with v0.3.24:
`src/kernel/arm64/dgemm_kernel_8x4_cortexa53.c: No such file or directory`
I build with `DYNAMIC_ARCH=true`, do you think it is related ?

**Comment by martin-frbg** [comment]
Strange, the fix in prebuild.cmake is still in place and the same code path should be taken by DYNAMIC_ARCH builds. Are you also cross-compiling ?

**Comment by JonathanGirardeau** [comment]
Yes I am also cross compiling

**Comment by ssssjiang** [comment]
I also encountered the same problem, which also occurred when cross-compiling

**Comment by martin-frbg** [comment]
What kind of system (cpu and operating system) are you running the cross-compilation on ? Maybe there is some special case where the parameter table in prebuild.cmake is not used - there is a single intentional exception for the host OS being "WINDOWSSTORE" that I don't quite remember the history of.
