### ISSUE TITLE
Latest clang fails to compile OpenBLAS on Linux and Windows

### ISSUE THREAD

**Issue by 3e33** [xianyi/OpenBLAS#3942]
It throws pointer to integer conversion errors almost as soon as the build starts. This doesn't happen with clang 11 but does with version 15, tested on Windows and Linux.

Using the following compile flags:
```
cmake -S . -B build -G "Ninja" \
-DCMAKE_CXX_COMPILER=clang++ \
-DCMAKE_C_COMPILER=clang \
-DDYNAMIC_ARCH=ON \
-DBUILD_SHARED_LIBS=ON \
-DCMAKE_BUILD_TYPE=Release \
-DBUILD_TESTING=OFF \
-DBUILD_STATIC_LIBS=OFF \
-DNOFORTRAN=1 \
-DCMAKE_MT=mt
```

**Comment by martin-frbg** [comment]
I do not remember seeing that with 15.0.6  - NOFORTRAN=1 will probably give you lots of warnings for the f2c-converted files under the lapack-netlib tree, but nothing critical (or are you perhaps using an option in CFLAGS to turn warnings into errors ?)

**Comment by 3e33** [comment]
I'm not adding any extra options, just what's above. Not a big issue since I can just use LLVM 11 (which does give lots of warnings, but no fails), maybe LLVM 15 is just more strict about some things?

**Comment by martin-frbg** [comment]
I can only assume that it is something already fixed on the `develop` branch (except that gave me the dreaded "inline assembly requires more registers than available" for some avx512 kernels a moment ago - seems the workarounds for earlier versions are no match for 15.0.6, but adding NO_AVX512 to drop Skylake/Cooperlake from the list led to a normal build). Will retry with 0.3.21 later when I find the time

**Comment by brada4** [comment]
Please save ninja output on linux. CMAKE_MT is windows-only.

**Comment by 3e33** [comment]
These are the kind of errors I get with clang-15

```
OpenBLAS-0.3.21/lapack-netlib/SRC/slalsa.c:1008:25: error: incompatible pointer to integer conversion passing 'integer *' (aka 'int *') to parameter of type 'integer' (aka 'int'); remove & [-Wint-conversion]
            lf = pow_ii(&c__2, &i__2);
                               ^~~~~
```

Build command
`cmake -S . -B build -G "Ninja" -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++"`

**Comment by brada4** [comment]
https://reviews.llvm.org/D129881 please disable error as instructed there. OpenBLAS latest release is 2 weeks older than change.

**Comment by 3e33** [comment]
Oh I see, thanks, just FYI for other people clang-14 works, so this is for version 15 and up.

**Comment by brada4** [comment]
Particular error from old warning is in LAPACKE from Netlib reference implementation. It is imported here now and then and historically builds with warnings. Probably fix upstream is welcome.

**Comment by martin-frbg** [comment]
no, that one is in the LAPACK sources that I converted to C for the convenience of people/platforms without a working fortran compiler. And the error no longer appears in my build of the current develop branch with llvm 15.0.6
