### ISSUE TITLE
OpenBLAS builds on Linux with LLVM but CMAKE cannot detect it

### ISSUE THREAD

**Issue by 3e33** [xianyi/OpenBLAS#3944]
I built on Linux with LLVM 11
```
cmake -S . -B build -G "Ninja" \
-DCMAKE_CXX_COMPILER=clang++ \
-DCMAKE_C_COMPILER=clang \
-DDYNAMIC_ARCH=ON \
-DBUILD_SHARED_LIBS=ON \
-DCMAKE_BUILD_TYPE=Release \
-DBUILD_TESTING=OFF \
-DBUILD_STATIC_LIBS=OFF \
-DNOFORTRAN=1
```

And everything seems to build properly, the OpenBLAS install folder has all the libraries.

```
── lib
│   ├── libopenblas.so -> libopenblas.so.0
│   ├── libopenblas.so.0 -> libopenblas.so.0.3
│   ├── libopenblas.so.0.3
│   └── pkgconfig
│       └── openblas.pc
```

And cmake  FindBLAS finds the file itself, from what I can tell, `libopenblas.so`, but it fails when it tests it.
```
-- Looking for sgemm_
-- Looking for sgemm_ - not found
CMake Error at miniconda3/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find BLAS (missing: BLAS_LIBRARIES)
```

It's the exact same build process I used on Windows, which all works fine. Any ideas?

**Comment by martin-frbg** [comment]
run `nm` on the library to confirm that symbol names are as expected, check the contents of the generated pkgconfig file, also check which cmake version you are using - I _think_ their FindBLAS went through several revisions

**Comment by 3e33** [comment]
Thanks, that all looks good. `nm` shows sgemm_, pkgconfig looks similar to the Windows one, I'll have to check Cmake but I think it's the current version.

**Comment by brada4** [comment]
You can teach cmake to use pkg-config, but basically shared files need to be in shared paths, like /usr/local etc.
Their documantation here: https://cmake.org/cmake/help/latest/module/FindBLAS.html

**Comment by 3e33** [comment]
I'm still having trouble with this, `--trace-expand` shows that cmake finds `libopenblas.so` but fails after that.
```
/usr/local/share/cmake-3.26/Modules/FindBLAS.cmake(367):  check_function_exists(sgemm_ BLAS_openblas_WORKS )
/usr/local/share/cmake-3.26/Modules/CheckFunctionExists.cmake(58):  if(NOT DEFINED BLAS_openblas_WORKS OR x STREQUAL xBLAS_openblas_WORKS )
/usr/local/share/cmake-3.26/Modules/FindBLAS.cmake(369):  set(CMAKE_REQUIRED_LIBRARIES )
/usr/local/share/cmake-3.26/Modules/FindBLAS.cmake(370):  set(_libraries_work  )
```

So from I understand `sgemm_` isn't working. But I don't understand why because it works on Windows.
I could be wrong but it seems like
```
cmake -S . -B build -G "Ninja" \
-DCMAKE_CXX_COMPILER=clang++ \
-DCMAKE_C_COMPILER=clang \
-DDYNAMIC_ARCH=ON \
-DBUILD_SHARED_LIBS=ON \
-DCMAKE_BUILD_TYPE=Release \
-DBUILD_TESTING=OFF \
-DBUILD_STATIC_LIBS=OFF \
-DNOFORTRAN=1
```
Just doesn't build a working OpenBLAS for some reason, even though it successfully compiles.
Building with Make does work, but then you need all the gcc dependencies and I'd like to avoid that.
Has anyone actually tried building on Linux with clang?

**Comment by martin-frbg** [comment]
I'm not sure if your exact option set will work with DYNAMIC_ARCH builds - in particular the `-S . -B build` part - what is definitely known to work is the (to me much more usual) method of running cmake from the build directory and having it store all generated files there instead of "polluting" the source tree.
So `mkdir build; cd build; cmake -G "Ninja" -DCMAKE_C_COMPILER=clang (...other options...) -DNOFORTRAN=1 ..`

**Comment by 3e33** [comment]
That's already what it's doing, `cmake -S .` is the current directory and `-B build` is the same as `mkdir build`. The build itself is fine and it outputs all the correct files, the issue is `libopenblas.so` doesn't "load" when cmake tests that it works. The exact same build works fine on Windows, since clang is multi-platform it should all work the same on Linux too and even MacOS, but something is off.
Does anybody know if there are any issues compiling / running OpenBLAS inside a VM?

**Comment by martin-frbg** [comment]
Inside a VM is not a problem in itself - what has been known to go wrong (in various ways) is compiling sources that are stored on the filesystem of the host, and supplied to the VM via a "shared folder" mechanism like vmhgfs

**Comment by martin-frbg** [comment]
BTW the cmake check_function_exists() makes no attempts to verify that a given function actually "works", all it does is try to compile a template C source with the desired symbol name inserted. So wrong LD_LIBRARY_PATH or unmet other dependencies will probably be sufficient to make it fail, and OS differences in this regard will work against your assumption that "it is multi-platform so should all work the same". (Not sure if any output from the try_compile can be made to end up in the cmake logs)

**Comment by 3e33** [comment]
That's interesting, I wonder if it could be a problem with `check_function_exists` itself.
The documentation for cmake actually recommends using `check_symbol_exists` instead.

**Comment by martin-frbg** [comment]
Maybe related to cmake builds missing an explicitly declared dependency on libm until recently - in that case building from the current develop branch instead of the 0.3.21 release should fix it

**Comment by 3e33** [comment]
I did a small experiment and changed FindBLAS.cmake and FindLAPACK.cmake to ignore the check_function_exists test, and everything works at the end of the day. So there's definitely something wrong with that when clang is involved.

**Comment by martin-frbg** [comment]
That does not tell us much unfortunately - did you check the CMakeOutput.log and CMakeError.log for any indication of why the test fails ? (I notice FindBLAS is still a recurring topic on the cmake bugtracker, with something like 20 open tickets covering all kinds of BLAS implementations)

**Comment by 3e33** [comment]
I know this is probably a bug with cmake's FindBLAS, but because libraries usually use FindBLAS and the OpenBLASConfig is ignored I wonder if it might be a good for for OpenBLAS to provide its own FindBLAS.cmake that supersedes Cmake's and makes sure that OpenBLAS is found?

**Comment by martin-frbg** [comment]
Maintaining bits of cmake would be well outside the scope of the project, and as suggested earlier you should already be able to tell cmake to use the pkgconfig file (if you are already certain you  want to link to a particular implementation). Plus in this specific case it is entirely possible that the non-detection occurs because of a missing dependency on libm that is already fixed on the develop branch.

**Comment by 3e33** [comment]
For other people that run into similar issues you can use the pkgconfig like so:
```
set(BLA_VENDOR OpenBLAS)
set(BLA_PREFER_PKGCONFIG 1)
set(BLA_PKGCONFIG_BLAS "openblas")
set(BLA_PKGCONFIG_LAPACK "openblas")
```
