### ISSUE TITLE
Issue with Termux

### ISSUE THREAD

**Issue by alexg93333** [xianyi/OpenBLAS#3947]
I'm trying to run "make && make install" but run into this error:
[ 3%] Performing build step for 'extern_openblas'
OpenBLAS: Detecting fortran compiler failed. Cannot compile LAPACK. Only compile BLAS.
make[4]: warning: -j8 forced in submake: resetting jobserver mode.
make[4]: /data/data/com.termux/files/usr/bin/-Wno-unused-but-set-ar: No such file or directory
make[4]: *** [../Makefile.tail:40: libs] Error 127
make[3]: *** [Makefile:144: libs] Error 1
make[2]: *** [CMakeFiles/extern_openblas.dir/build.make:86: third_party/openblas/src/extern_openblas-stamp/extern_openblas-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:4606: CMakeFiles/extern_openblas.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by martin-frbg** [comment]
Looks like you are trying to   an older(?) version of OpenBLAS as part of some other project, which is it ? (The `(...)Only compile BLAS" message suggests 0.3.20 or even earlier - current 0.3.21 would use a C version of the LAPACK library here).
The error suggests that something in the build scripts of the other project is adding a compiler option that somehow ends up as the name to use for the `ar` tool. (Again, would need to know what project that is, to see what it puts in its compile scripts )

**Comment by alexg93333** [comment]
Thanks for the quick reply. I am trying to build this project:
git clone https://github.com/PaddlePaddle/Paddle.git --depth 1 
on Termux which runs on my android phone.

**Comment by martin-frbg** [comment]
Hmm, looks like it is trying to fetch&build the ancient 0.3.7 release from three years ago, so maybe updating the version number in line 20 of cmake/external/openblas.cmake to 0.3.21 would already help 
 
https://github.com/PaddlePaddle/Paddle/blob/c658be9b6086d287e92214ba85d43de9261933d6/cmake/external/openblas.cmake#L20

**Comment by alexg93333** [comment]
Should I change the version only in this single line? If yes then unfortunately it didn't help. The the exact same error as before.

**Comment by martin-frbg** [comment]
That's unfortunate - I had hoped that the improvements in the build system since 0.3.7 would take care of the error. But the warning line about "Only build BLAS" is gone now ? (If it is still there, then maybe the script did not do a new checkout)
Perhaps if you change line 40/41 to just `set (OpenBLAS_CC ${CMAKE_C_COMPILER})` without the two `-Wno` options it will find the correct tools for compiling

**Comment by alexg93333** [comment]
Oh wait, after I made the changes, I have to rerun "cmake ."? or just "make && make install"?

**Comment by martin-frbg** [comment]
You'll need to rerun `cmake` as that prepares everything for the subsequent `make` - note I have not tried to do an actual paddle installation (and I'm unlikely to have the time for that), but building OpenBLAS in a termux environment is known to work.

**Comment by alexg93333** [comment]
Yes! It actually worked. Thank you so much. 
But unfortunately now I ran into the next error. But it's not connected to OpenBLAS I suppose?

```
[ 1%] Building CXX object CMakeFiles/cryptopp-object.dir/cpu.cpp.o
/data/data/com.termux/files/home/Paddle/third_party/cryptopp/src/extern_cryptopp/cpu.cpp:51:11: fatal error: 'cpu-features.h' file not found
# include "cpu-features.h"
^~~~~~~~~~~~~~~~
1 error generated.
make[5]: *** [CMakeFiles/cryptopp-object.dir/build.make:90: CMakeFiles/cryptopp-object.dir/cpu.cpp.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:90: CMakeFiles/cryptopp-object.dir/all] Error 2
make[3]: *** [Makefile:146: all] Error 2
make[2]: *** [CMakeFiles/extern_cryptopp.dir/build.make:86: third_party/cryptopp/src/extern_cryptopp-stamp/extern_cryptopp-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:4736: CMakeFiles/extern_cryptopp.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

```

**Comment by martin-frbg** [comment]
Yes, that looks to be something else, maybe cryptopp (whatever that is :) ) does not expect to be built under termux, or you need to have the Android NDK installed ? https://github.com/termux/termux-packages/issues/7515 looks related

**Comment by alexg93333** [comment]
I will try to setup my termux env correctly. Thanks! You really helped me a lot!
