### ISSUE TITLE
Create security.md file? 

### ISSUE THREAD

**Issue by Salkimmich** [xianyi/OpenBLAS#3948]
Hey there! I do security on a project downstream to yours. I have no security vulnerabilities to report at this time for your project, but if I do need to report a vulnerability, would you make a security.md file that lets security researches know how to contact and patch? Having Github SA enabled catches a lot of vulnerabilities -  but with a project this size a clear coordinated disclosure can help to catch vulnerabilities/snippets detected downstream.

**Comment by martin-frbg** [comment]
That seems to be one of those things that never really caught on, and we do not have much of an organizational structure. So the info to put there would not go beyond the (hopefully) obvious "please email the current maintainer(s) through the email addresses given in their profiles". But I guess neither counts as reasons _not_ to do it ? :)

**Comment by martin-frbg** [comment]
First draft added - hope this is approximately what you had in mind

**Comment by Salkimmich** [comment]
It's totally up to you on your maintenance workflow preference -  I'd recommend putting one in place for 3-6 months, take it off if it's noise? Github SA catches most known vulnerabilities, but there's a few automated scripts scrapping at the snippet level for python that would reach out directly via that security.md contact when its machine readable. 

Either way, it's an active project and I'm happy to reach out beyond automation if anything comes up, but this project looks pretty healthy overall so I'm not worried. Thanks!

**Comment by brada4** [comment]
Worth noting that
- tricking calling code into passing garbage pointers and sizes to API and consequences thereof are bugs in calling code.

**Comment by martin-frbg** [comment]
@Salkimmich thanks. Also happy to look into any non-security issues the unfortunate downstream project may have with OpenBLAS - I know there may still be a few performance issues, and I don't think we've had much input from ML-related projects (which appear to be your specialization ?) lately.
@brada4 bit of a gray area I think - we don't do fuzzing to harden the library against malicious inputs as normally done in other fields, but being low-level with a focus on performance and established APIs that require callers to specify the number of elements etc. at some point you have to trust the inputs.

**Comment by brada4** [comment]
There is not much chance of hardening against invalid parameters (cf memcpy), but crash will be in (Open)BLAS code. Just that not all crashes are born 2 code lines before abrt....
