### ISSUE TITLE
Cray CCE 14 Fortran compiler detection broken by change for #3778

### ISSUE THREAD

**Issue by rothpc** [xianyi/OpenBLAS#3954]
Although the change for issue #3778 may have allowed the f_check script to correctly detect the gfortran compiler on a Cray system, it breaks the software's detection of the Cray CCE 14 Fortran compiler with at least some versions of the Cray CCE compilers.  In particular, when f_check compiles the ftest.f program with the Cray Fortran compiler, it generates a section with name '.note.GNU-stack', so the resulting ftest.s file contains the string "GNU" *and* the string "Cray".  By moving the case for the string "Cray" after "GNU" in f_check, the Fortran compiler is detected as GNU Fortran when in fact it is Cray Fortran.

(A preliminary check with CCE 15 worries me more - the string "Cray" is not in the ftest.s file at all, but the "GNU" section name still is.  Will file a separate issue if I can verify that f_check actually does misidentify the Cray 15 Fortran compiler also.)

**Comment by martin-frbg** [comment]
Can you please attach the ftest.s files created by both versions 14 and 15 of CCE ? I'm unlikely to get access to any system that has these Cray compilers installed, and I'd hate to see successful detection swing back and forth between gfortran and CCE with every future patch. ftest.f has nothing in it that would force the compiler to spell out its name, so if it does not do so voluntarily we'd need to fall back to something like checking the executable name. (Which might even be enough to solve the current problem, if that check is added inside the "GNU" block - I guess the days when non-GNU vendor compilers had version numbers below 4 are long gone now)

**Comment by rothpc** [comment]
The output from CCE Fortran version 14.0.2 is in [ftest.s.14.txt](https://github.com/xianyi/OpenBLAS/files/11063902/ftest.s.14.txt).  The output from CCE Fortran version 15.0.0 is in [ftest.s.15.txt](https://github.com/xianyi/OpenBLAS/files/11063905/ftest.s.15.txt).  Again, I'm concerned about the test using assembly language output given there's no mention of Cray in the output from the CCE 15 compiler.  Perhaps it is sufficient to check for 'Hewlett Package Enterprise' now?

I note that 'ftn --version' reports 'Cray Fortran: Version x.y.z' for both CCE 14 and CCE 15 compilers.

**Comment by martin-frbg** [comment]
Strange that CCE15 would not write its identifier in the section header like everybody else - but indeed matching on Messrs. Hewlett or Packard would appear to achieve the same goal (unless there is another fortran compiler with non-cray heritage elsewhere in the HP universe). Historically, trawling the intermediate compiler output for version strings was probably easier than trying all variants of `-v``-version``--version`
