### ISSUE TITLE
Update to LAPACK 3.11 (latest release right now)

### ISSUE THREAD

**Issue by ViralBShah** [xianyi/OpenBLAS#3955]
It would be nice to update to the latest LAPACK release, which has some really nice performance improvements. Especially for the blocked generalized eigenvalue calculations as described in https://github.com/JuliaLang/julia/pull/49037

**Comment by martin-frbg** [comment]
openblas is at 3.11 plus later PRs already, maybe I missed a version string somewhere when i merged the changes ?

**Comment by ViralBShah** [comment]
I think this README.md made me think it had not been upgraded: https://github.com/xianyi/OpenBLAS/tree/develop/lapack-netlib

**Comment by ViralBShah** [comment]
I guess we'll also need to wait for a new release of openblas to get the new LAPACK.

**Comment by martin-frbg** [comment]
yes the readme is outdated as I only pulled individual code PRs. will try to remember updating that file before the 0.3.22 release (currently scheduled for sunday)
