### ISSUE TITLE
No rule to make target 'cspmv.o', needed by 'libs'

### ISSUE THREAD

**Issue by fawltylanguage** [xianyi/OpenBLAS#3974]
with NO_LAPACK=1

**Comment by brada4** [comment]
Could you post full command lines you used?

**Comment by martin-frbg** [comment]
Ah, sorry, I understand what happened here - I should have actually (re)added cspmv & friends to the list of reimplemented) LAPACK objects instead. PR incoming, just need to sort it out with the pending ones that affect the same Makefile in interface...
