### ISSUE TITLE
unable to build dll with MSVC

### ISSUE THREAD

**Issue by jbensabat** [xianyi/OpenBLAS#3982]
Hello 
I am able to build static openblas with CMAKE and MSVC 
if I switch of the static library option (meaning that I request a dll) CMAKE with switch it on back 
this prevents from creating a dll.
is this behavior known ?
thanks
jac

**Comment by martin-frbg** [comment]
Are you switching on the option to build a dynamic library at the same time (BUILD_SHARED_LIBS=ON on the CMAKE command line, don't know what it looks like in the MSVC gui)  ? At least by what is intended with the code in the toplevel CMakelists.txt, static openblas is only enforced when (1) neither static nor dynamic library were selected, or (2) on Windows when _both_ static and dynamic are selected at the same time, as MSVC supposedly cannot handle that.

**Comment by jbensabat** [comment]
hi 
I have added an entry to the CMAKE GUI -  BUILD_SHARED_LIBS=ON and it creates a porject workspace for a dll
thanks
best
jac

**Comment by jbensabat** [comment]
just to inform you 
it worked 
i was able to create a dll (also the export library)
best
jac

**Comment by martin-frbg** [comment]
Glad you got it working
