### ISSUE TITLE
Fortran  complex dot routines error

### ISSUE THREAD

**Issue by Euler-37** [xianyi/OpenBLAS#3993]
``` fortran
program main
   implicit none
   complex(8)::a(3)
   complex(4)::b(3)
   complex(8),external::zdotu
   complex(4),external::cdotu
   complex(8),external::zdotc
   complex(4),external::cdotc
   a=cmplx(1.d0,1.d0,8)
   b=cmplx(1.0,1.0,4)
   write(*,*)"zdotu/cdotu"
   write(*,*)dot_product(conjg(a),a)
   write(*,*)zdotu(3,a,1,a,1)
   write(*,*)cdotu(3,b,1,b,1)
   write(*,*)"zdotc/cdotc"
   write(*,*)dot_product(a,a)
   write(*,*)zdotc(3,a,1,a,1)
   write(*,*)cdotc(3,b,1,b,1)
end program main
```
openblas version 3.20
wsl2-ubuntu 22.04
gfortran-11/oneapi 2023

gfortran's result is correct,but both  ifort and ifx give the wrong results

``` bash
> ifx test.f90 -lopenblas -check all -g -traceback -O0
> ./a.out
zdotu/cdotu
 (0.000000000000000E+000,6.00000000000000)
 (0.000000000000000E+000,0.000000000000000E+000)
 (0.0000000E+00,0.0000000E+00)
 zdotc/cdotc
 (6.00000000000000,0.000000000000000E+000)
 (0.000000000000000E+000,0.000000000000000E+000)
 (0.0000000E+00,0.0000000E+00)
```
and sdot/ddot is correct for all of them.

**Comment by martin-frbg** [comment]
Interesting - there is some precedent in gcc12 breaking things with its `-ftree-optimize` now on by default. What's your cpu please ?

**Comment by Euler-37** [comment]
It is ~~Intel i10900k~~ Intel(R)Core(TM)i9-10900K,Thanks！！

**Comment by martin-frbg** [comment]
Not reproduced with the current 0.3.23 so far...

**Comment by Euler-37** [comment]
libopenblas 0.3.20 is installed from "apt install". I built the source code of 0.3.23, the error still exists. 

By the way,  `MSYS2 llvm-flang` is not true either.
``` bash
> flang --version
flang-new version 15.0.7
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: G:/software/msys2/ucrt64/bin

```

**Comment by bartoldeman** [comment]
zdot*/cdot* have different ABIs in gfortran compared to ifx/ifort (ifx/ifort, like the old g77 pass a pointer to the return value as a hidden extra parameter, but gfortran returns it in FPU registers). If you compile OpenBLAS with ifx/ifort you can use zdot*/cdot* from that library directly with ifx/ifort.

If you want to use the same binary OpenBLAS library in both, you can't use zdot*/cdot*, but you can use cblas_[cz]dot* using iso_c_binding. It's a bit ugly but it shold work.

**Comment by Euler-37** [comment]
Thank you for your answer !! I see.

**Comment by martin-frbg** [comment]
Ah, so you were mixing builds (and thus Fortran ABIs), I did not take that into account. Perhaps this is something that could be addressed in our documentation...
