### ISSUE TITLE
testing openblas dll under MSVC

### ISSUE THREAD

**Issue by jbensabat** [xianyi/OpenBLAS#4001]
Hello 
I managed to build openblas using CMAKE and MSVC
I created the shared libraries.
I ran the utest under debug and it conducted 34 tests all of them passed
then I tried to run it under release and I do not get an error but it does not conduct any test
Is it a problem related to the library or a problem related to the way the tests are loaded ?
has anybody experienced such a behavior ?
thanks
jac

**Comment by martin-frbg** [comment]
There is no difference in test setup between DEBUG and RELEASE builds, so probably the test calls get optimized out of the binary in the latter case. There is an alternative implementation of the main utest source file that is already used for build with the clang compiler - you could try if removing the `AND $CMAKE_C_COMPILER_ID MATCHES clang` part from the "if" at the top of utest/CMakeLists.txt solves the problem for you.
