### ISSUE TITLE
Unable to compile on MacOS

### ISSUE THREAD

**Issue by chuckcoleman** [xianyi/OpenBLAS#4008]
I followed the installation directions, with minor exceptions for my OS version (13.3.1).  I have the latest Xcode installed and made sure my other software was setup per directions.

I changed "export MACOSX_DEPLOYMENT_TARGET=11.0" to use targets 13.0 and 13.3.

In short, I get Fortran runtime errors when I make the OpenBLAS:

> At line 170 of file sblat2.f (unit = 6, file = 'stdout')
> Fortran runtime error: Bad STATUS parameter in OPEN statement

then

> At line 145 of file sblat3.f (unit = 6)
> Fortran runtime error: Cannot open file '': No such file or directory

Make then gives up with a segmentation fault.

I need OpenBLAS to run wxmaxima, which has it as a dependency (but does not try to compile it properly).

The log is attached.
[OpenBLASerror.txt](https://github.com/xianyi/OpenBLAS/files/11252222/OpenBLASerror.txt)

**Comment by chuckcoleman** [comment]
It's GNU Octave that requires OpenBLAS.

**Comment by martin-frbg** [comment]
The warnings about stdio.h look a bit strange - what compiler version does `cc` point to, could this be some outdated version of gcc ?  (What does `cc -v` report ?)

**Comment by chuckcoleman** [comment]
cc points to clang, which reports v. 14.0.3:

$ cc -v
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: x86_64-apple-darwin22.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by chuckcoleman** [comment]
Everything points to Clang, even though I also have GNU C suite.

**Comment by martin-frbg** [comment]
Very strange, also the fortran warnings about a bad STATUS parameter - these should definitely not occur with any somewhat recent gfortran. Is it possible that you have multiple versions of gfortran installed, and your build is picking up parts (e.g. runtime libraries) of an incompatible earlier version (as was the case in #2303) ?

**Comment by chuckcoleman** [comment]
It turns out my gcc/gfortran configuration was a mess.  After cleaning it up and reinstalling gcc using Homebrew, I used Macports to install OpenBLAS, which it refused to do in the first place without raising an error message.  So, everything is working better now.  Thanks!
