### ISSUE TITLE
Point to `cblas.h` using `-lblas` instead of `-lopenblas`

### ISSUE THREAD

**Issue by ddelange** [xianyi/OpenBLAS#4012]
Hi 👋

In a fresh Debian bullseye docker image, I installed [libopenblas-openmp-dev](https://packages.debian.org/search?searchon=names&keywords=libopenblas-openmp-dev).

I can now point to the newly installed `cblas.h` using `-lblas`, and that gets picked up. Without the `apt-get install libopenblas-openmp-dev`, it will not get picked up. So did apt 'symlink' `-lopenblas` to `-blas`?

Because in the docs here I read about `-lopenblas` and I'm not sure what's the difference.

More specifically, here is my PR to support OpenBLAS: https://github.com/openvenues/libpostal/pull/625

Is that change sufficient to leverage OpenMP?

**Comment by ddelange** [comment]
Update: just to be sure (not sure if Mac or other Unix distros will also 'symlink' to `-lblas`):

I added a [commit](https://github.com/openvenues/libpostal/pull/625/commits/6f9567742711dbd929ab6df7eb2caf01ab6325e0) with explicit OpenBLAS support. Still curious about your thoughts though!

**Comment by ddelange** [comment]
Or did `-lblas` only become available because apt also installed generic BLAS in order to compile OpenBLAS? So it's not a 'symlink'?

**Comment by martin-frbg** [comment]
Debian (and a few other Linux distributions) make use of an "alternatives" mechanism whereby alternate implementations of some "generic" functionality, like OpenBLAS and the unoptimized "netlib" reference implementation of BLAS can be managed through a set of symlinks (or more user-friendly with the update-alternatives command). I'm assuming that is why you see the unspecific `-lblas` used by default - what it points at will be down to the individual Debian installation and its user.

**Comment by ddelange** [comment]
Thanks for the quick reply!

On Mac it looks like `-lopenblas` is [symlinked](https://github.com/Homebrew/homebrew-core/blob/f1674c7605d0b28e1a1a8be438ca3fdfa4e387ec/Formula/openblas.rb#L50) to `-lblas`. Not sure how to verify that for apt package manager 🤔

> what it points at will be down to the individual Debian installation and its user

That's what I wanted to hear :) that warrants my latest commit linked above to make it explicit 👍

Will close with that, thanks again!
