### ISSUE TITLE
'const' missing in cblas_xerbla

### ISSUE THREAD

**Issue by angsch** [xianyi/OpenBLAS#4020]
A deviation between OpenBLAS and reference-LAPACK gives me a warning in my code when using `cblas_xerbla`.

[Reference-LAPACK](https://github.com/Reference-LAPACK/lapack/blob/6d6189d1dab0130c2e64d56148c908ae396ea675/CBLAS/include/cblas.h#L615) uses `const` input arguments

```
cblas_xerbla(CBLAS_INT info, const char *rout, const char *form, ...)
```

whereas OpenBLAS omits these:
https://github.com/xianyi/OpenBLAS/blob/e9a8d5b45ffdfdb8425deeb6af7d1a369e3c029e/cblas.h#L353

**Comment by martin-frbg** [comment]
Thanks for the hint - this is probably a remnant of original GotoBLAS code, matching an early CBLAS implementation
