### ISSUE TITLE
cmake - ONLY_CBLAS=1 fails utest

### ISSUE THREAD

**Issue by tburow** [xianyi/OpenBLAS#4021]
cblas only via cmake fails on utest

Install settings
`cmake -DCMAKE_INSTALL_PREFIX=/usr -DFC=/usr/bin/gcc10-gfortran -DCMAKE_BUILD_TYPE=Release -DONLY_CBLAS=1 ..
  cmake --build .
  cmake --build . --target install`

Utest Log
`==> amazon-ebs.base-ami-build: CMakeFiles/openblas_utest.dir/test_min.c.o:test_min.c:function __ctest_min_smin_negative_run: error: undefined reference to 'smin_'
==> amazon-ebs.base-ami-build: CMakeFiles/openblas_utest.dir/test_min.c.o:test_min.c:function __ctest_min_smin_zero_run: error: undefined reference to 'smin_'
==> amazon-ebs.base-ami-build: CMakeFiles/openblas_utest.dir/test_min.c.o:test_min.c:function __ctest_min_dmin_positive_run: error: undefined reference to 'dmin_'
==> amazon-ebs.base-ami-build: CMakeFiles/openblas_utest.dir/test_min.c.o:test_min.c:function __ctest_max_smax_negative_run: error: undefined reference to 'smax_'
==> amazon-ebs.base-ami-build: CMakeFiles/openblas_utest.dir/test_min.c.o:test_min.c:function __ctest_max_smax_zero_run: error: undefined reference to 'smax_'
==> amazon-ebs.base-ami-build: CMakeFiles/openblas_utest.dir/test_min.c.o:test_min.c:function __ctest_max_dmax_positive_run: error: undefined reference to 'dmax_'
==> amazon-ebs.base-ami-build: CMakeFiles/openblas_utest.dir/test_amax.c.o:test_amax.c:function __ctest_amax_samax_run: error: undefined reference to 'samax_'
==> amazon-ebs.base-ami-build: CMakeFiles/openblas_utest.dir/test_amax.c.o:test_amax.c:function __ctest_amax_damax_run: error: undefined reference to 'damax_'
==> amazon-ebs.base-ami-build: CMakeFiles/openblas_utest.dir/test_ismin.c.o:test_ismin.c:function __ctest_ismin_positive_step_2_run: error: undefined reference to 'ismin_'
==> amazon-ebs.base-ami-build: CMakeFiles/openblas_utest.dir/test_ismin.c.o:test_ismin.c:function __ctest_ismin_negative_step_2_run: error: undefined reference to 'ismin_'
==> amazon-ebs.base-ami-build: CMakeFiles/openblas_utest.dir/test_ismin.c.o:test_ismin.c:function __ctest_ismax_positive_step_2_run: error: undefined reference to 'ismax_'
==> amazon-ebs.base-ami-build: CMakeFiles/openblas_utest.dir/test_ismin.c.o:test_ismin.c:function __ctest_ismax_negative_step_2_run: error: undefined reference to 'ismax_'
==> amazon-ebs.base-ami-build: CMakeFiles/openblas_utest.dir/test_rotmg.c.o:test_rotmg.c:function __ctest_drotmg_rotmg_run: error: undefined reference to 'drotmg_'
==> amazon-ebs.base-ami-build: CMakeFiles/openblas_utest.dir/test_rotmg.c.o:test_rotmg.c:function __ctest_drotmg_rotmg_issue1452_run: error: undefined reference to 'drotmg_'
==> amazon-ebs.base-ami-build: CMakeFiles/openblas_utest.dir/test_rotmg.c.o:test_rotmg.c:function __ctest_drotmg_rotmg_D1eqD2_X1eqX2_run: error: undefined reference to 'drotmg_'
==> amazon-ebs.base-ami-build: CMakeFiles/openblas_utest.dir/test_rotmg.c.o:test_rotmg.c:function __ctest_drotmg_drotmg_D1_big_D2_big_flag_zero_run: error: undefined reference to 'drotmg_'
==> amazon-ebs.base-ami-build: CMakeFiles/openblas_utest.dir/test_rot.c.o:test_rot.c:function __ctest_rot_drot_inc_0_run: error: undefined reference to 'drot_'
==> amazon-ebs.base-ami-build: CMakeFiles/openblas_utest.dir/test_rot.c.o:test_rot.c:function __ctest_rot_zdrot_inc_0_run: error: undefined reference to 'zdrot_'
==> amazon-ebs.base-ami-build: CMakeFiles/openblas_utest.dir/test_rot.c.o:test_rot.c:function __ctest_rot_srot_inc_0_run: error: undefined reference to 'srot_'
==> amazon-ebs.base-ami-build: CMakeFiles/openblas_utest.dir/test_rot.c.o:test_rot.c:function __ctest_rot_csrot_inc_0_run: error: undefined reference to 'csrot_'
==> amazon-ebs.base-ami-build: CMakeFiles/openblas_utest.dir/test_axpy.c.o:test_axpy.c:function __ctest_axpy_daxpy_inc_0_run: error: undefined reference to 'daxpy_'
==> amazon-ebs.base-ami-build: CMakeFiles/openblas_utest.dir/test_axpy.c.o:test_axpy.c:function __ctest_axpy_zaxpy_inc_0_run: error: undefined reference to 'zaxpy_'
==> amazon-ebs.base-ami-build: CMakeFiles/openblas_utest.dir/test_axpy.c.o:test_axpy.c:function __ctest_axpy_saxpy_inc_0_run: error: undefined reference to 'saxpy_'
==> amazon-ebs.base-ami-build: CMakeFiles/openblas_utest.dir/test_axpy.c.o:test_axpy.c:function __ctest_axpy_caxpy_inc_0_run: error: undefined reference to 'caxpy_'
==> amazon-ebs.base-ami-build: CMakeFiles/openblas_utest.dir/test_dsdot.c.o:test_dsdot.c:function __ctest_dsdot_dsdot_n_1_run: error: undefined reference to 'dsdot_'
==> amazon-ebs.base-ami-build: CMakeFiles/openblas_utest.dir/test_dnrm2.c.o:test_dnrm2.c:function __ctest_dnrm2_dnrm2_inf_run: error: undefined reference to 'dnrm2_'
==> amazon-ebs.base-ami-build: CMakeFiles/openblas_utest.dir/test_dnrm2.c.o:test_dnrm2.c:function __ctest_dnrm2_dnrm2_tiny_run: error: undefined reference to 'dnrm2_'
==> amazon-ebs.base-ami-build: CMakeFiles/openblas_utest.dir/test_swap.c.o:test_swap.c:function __ctest_swap_dswap_inc_0_run: error: undefined reference to 'dswap_'
==> amazon-ebs.base-ami-build: CMakeFiles/openblas_utest.dir/test_swap.c.o:test_swap.c:function __ctest_swap_zswap_inc_0_run: error: undefined reference to 'zswap_'
==> amazon-ebs.base-ami-build: CMakeFiles/openblas_utest.dir/test_swap.c.o:test_swap.c:function __ctest_swap_sswap_inc_0_run: error: undefined reference to 'sswap_'
==> amazon-ebs.base-ami-build: CMakeFiles/openblas_utest.dir/test_swap.c.o:test_swap.c:function __ctest_swap_cswap_inc_0_run: error: undefined reference to 'cswap_'
==> amazon-ebs.base-ami-build: CMakeFiles/openblas_utest.dir/test_dotu.c.o:test_dotu.c:function __ctest_zdotu_zdotu_n_1_run: error: undefined reference to 'zdotu_'
==> amazon-ebs.base-ami-build: CMakeFiles/openblas_utest.dir/test_dotu.c.o:test_dotu.c:function __ctest_zdotu_zdotu_offset_1_run: error: undefined reference to 'zdotu_'
==> amazon-ebs.base-ami-build: collect2: error: ld returned 1 exit status
==> amazon-ebs.base-ami-build: gmake[2]: *** [utest/openblas_utest] Error 1
==> amazon-ebs.base-ami-build: gmake[1]: *** [utest/CMakeFiles/openblas_utest.dir/all] Error 2
==> amazon-ebs.base-ami-build: gmake: *** [all] Error 2`

**Comment by martin-frbg** [comment]
Looks like it is behaving a bit too strict here - building "only cblas" without even the actual implementations of the BLAS functions. Arguably this would have made some sense in the original, Fortran-based Reference BLAS, but the gmake build already appears to treat this option as a synonym of NO_LAPACK, so it would probably best to be consistent with that rather than disable the tests . Or what was it you were hoping to achieve ?

**Comment by tburow** [comment]
honestly - I inherited this build and I'm just trying to update versions.   To me this is just another piece of compiled SW requested by the developers and admittedly I lack a lot of the context here.   This is feeding into a GDAL build as a prerequisite for the includes.   I can run the full build successfully but it takes to long (unrelated environment problem)

**Comment by martin-frbg** [comment]
Ok, most likely NO_LAPACK=1 instead would work for you then. (though I did not see anything on the GDAL website about which BLAS and/or LAPACK functions it needs)

**Comment by tburow** [comment]
ill give that a try - thanks for the assist

**Comment by brada4** [comment]
you can build armadillo  without lapack and blas, but if you build it with it you need lapacke.h which implies fortran blas

**Comment by martin-frbg** [comment]
Right - if GDAL depends on LAPACK as well, this build shortcut is pointless (but so would building with ONLY_CBLAS be - unless the underlying platform issue is lack of a Fortran compiler). Pity that the GDAL website apparently fails to mention all dependencies, while the SPACK package description has them. (Though from the spack package.py for gdal, the dependency on BLAS/LAPACK comes from Armadillo, which _appears_ to be needed only for speeding up "computations related to the Thin Plate Spline transformer").

**Comment by tburow** [comment]
Thanks everyone for the assist - im going to push this back down to our developers to figure out.

**Comment by martin-frbg** [comment]
reopening as a reminder to get the cmake behavior sorted

**Comment by brada4** [comment]
normally you get armadillo included in some distribution packages, linked to system BLAS, so easiest way is to learn packaging system, or at least force GDAL to use existing prebuilt system packages.
