### ISSUE TITLE
KNeighborsClassifier OpenBLAS warning: precompiled NUM_THREADS exceeded, adding auxiliary array for thread metadata

### ISSUE THREAD

**Issue by linuxl7** [xianyi/OpenBLAS#4026]
mybe too many cpus, change \site-packages\joblib\externals\loky\backend\context.py can solved

os_cpu_count = min(os.cpu_count() or 1,12)

cpu_count_user = min(_cpu_count_user(os_cpu_count),12)

**Comment by martin-frbg** [comment]
Are you sure you opened this ticket in the correct project ? Indeed you will get this warning when you are using a pre-compiled libopenblas on a system with more cpu cores than it was built for, but this should be addressed in the project that makes the BLAS call (or by whoever provided the precompiled libopenblas). 12 is quite a small number, probably NUM_THREADS was not set when building OpenBLAS so the number of cores in the build host was used.

**Comment by linuxl7** [comment]
KNeighborsClassifier from sklearn,when i change this indeed solve it(warning show on 56 core cpus).

**Comment by martin-frbg** [comment]
can you please report this to sklearn or whoever provided the openblas that you used with it ? (openblas uses a builtin minimum of 50, so in a way you were just unlucky with having 56 cores in your machine. but it should keep running after showing this warning, just less efficiently)

**Comment by linuxl7** [comment]
Okay, I'm just an amateur developer and I'm providing a solution to this issue here just to help anyone who encounters this problem. Thank you for your response!

**Comment by martin-frbg** [comment]
It probably makes sense to bring back the explanatory part from the old abort message, which already had the suggestion to set OPENBLAS_NUM_THREADS to the supported maximum or rebuild OpenBLAS with an increased one.
