### ISSUE TITLE
Default value of USE_LOCKING when not set explicitly?

### ISSUE THREAD

**Issue by samfux84** [xianyi/OpenBLAS#4030]
Hi,

I read in the changelog of OpenBLAS, that since version 0.3.7 a new option USE_LOCKING was introduced.

I have built version 0.3.20 from source code and did not set the USE_LOCKING option. Therefore I would like to ask, what is the default for this option when not set?

From the build logs, it is not obvious if USE_LOCKING=0 or USE_LOCKING=1 was used as default.

Any help is appreciated.

Best regards

Sam

**Comment by brada4** [comment]
If you build on a single CPU or any other way force single-threaded - MP locking is not default. It is enabled in all other cases.

**Comment by samfux84** [comment]
Thank you for your reply.

I was building OpenBLAS with

'make' 'CC=/cluster/apps/spack/lib/spack/env/gcc/gcc' 'FC=/cluster/apps/spack/lib/spack/env/gcc/gfortran' 'MAKE_NO_J=1' 'NO_AVX512=1' 'USE_OPENMP=0' 'USE_THREAD=0' 'libs' 'netlib' 'shared'

So I guess USE_LOCKING was not enabled. Is this correct?

**Comment by brada4** [comment]
Yes, locking was disabled in your build due to USE_THREAD=0 which implies NUM_THREADS=1 and consequently USE_LOCKING=0

**Comment by samfux84** [comment]
Thank you for the help.
