### ISSUE TITLE
v0.2.9 compile utest throw error

### ISSUE THREAD

**Issue by braindevices** [xianyi/OpenBLAS#406]
I try to build it with unit test but it throw out error when compiling utest. 

rule:

```
UTEST_CHECK = 1
FUNCTION_PROFILE = 1
NO_WARMUP = 1
NO_AFFINITY = 1
FCOMMON_OPT = -frecursive
COMMON_PROF = -pg
```

try to build on linux x64

```
./quickbuild.64bit
...
make -j 4 -C utest all
make[1]: Entering directory `/tmp/OpenBLAS/utest'
gcc -O2 -DUTEST_CHECK -DSANITY_CHECK -DREFNAME=mainf_ -Wall -m64 -DF_INTERFACE_GFORT -fPIC  -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME=main -DASMFNAME=main_ -DNAME=main_ -DCNAME=main -DCHAR_NAME=\"main_\" -DCHAR_CNAME=\"main\" -DNO_AFFINITY -DFUNCTION_PROFILE -I..   -c -o main.o main.c
gcc -O2 -DUTEST_CHECK -DSANITY_CHECK -DREFNAME=test_rotf_ -Wall -m64 -DF_INTERFACE_GFORT -fPIC  -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME=test_rot -DASMFNAME=test_rot_ -DNAME=test_rot_ -DCNAME=test_rot -DCHAR_NAME=\"test_rot_\" -DCHAR_CNAME=\"test_rot\" -DNO_AFFINITY -DFUNCTION_PROFILE -I..   -c -o test_rot.o test_rot.c
gcc -O2 -DUTEST_CHECK -DSANITY_CHECK -DREFNAME=test_swapf_ -Wall -m64 -DF_INTERFACE_GFORT -fPIC  -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME=test_swap -DASMFNAME=test_swap_ -DNAME=test_swap_ -DCNAME=test_swap -DCHAR_NAME=\"test_swap_\" -DCHAR_CNAME=\"test_swap\" -DNO_AFFINITY -DFUNCTION_PROFILE -I..   -c -o test_swap.o test_swap.c
In file included from test_swap.c:33:0:
common_utest.h:35:25: fatal error: CUnit/CUnit.h: No such file or directory
compilation terminated.
tar xjf CUnit-2.1-2-src.tar.bz2
In file included from test_rot.c:33:0:
common_utest.h:35:25: fatal error: CUnit/CUnit.h: No such file or directory
compilation terminated.
In file included from main.c:36:0:
common_utest.h:35:25: fatal error: CUnit/CUnit.h: No such file or directory
compilation terminated.
make[1]: *** [test_swap.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [test_rot.o] Error 1
make[1]: *** [main.o] Error 1
make[1]: Leaving directory `/tmp/OpenBLAS/utest'
```

The CUnit-2.1-2 has correctly created. But it has not been compiled.

I then cd the /utest and make. The CUnit can be build correctly.

```
$ ls CUnit-2.1-2/lib
libcunit.a  libcunit.la  libcunit.so  libcunit.so.1  libcunit.so.1.0.1  pkgconfig
 $ ls CUnit-2.1-2/include/CUnit/
Automated.h  Console.h  CUnit.h       MyMem.h   TestRun.h
Basic.h      CUError.h  CUnit_intl.h  TestDB.h  Util.h
```

but still `common_utest.h:35:25: fatal error: CUnit/CUnit.h: No such file or directory`

**Comment by Sem754** [comment]
Hello xianyi, I tried the developer version of OpenBlas and when issuing  sudo make TARGET=AMD in Ubuntu 16.04 I got this message:
[ 62%] Built target openblas
[ 99%] Built target openblas_static
[ 99%] Linking C executable openblas_utest
../lib/libopenblas.so.0.2: undefined reference to `strsm_kernel_RN'
../lib/libopenblas.so.0.2: undefined reference to `strevc3_'
../lib/libopenblas.so.0.2: undefined reference to `ztrevc3_'
../lib/libopenblas.so.0.2: undefined reference to `strsm_kernel_LT'
../lib/libopenblas.so.0.2: undefined reference to `ctrevc3_'
../lib/libopenblas.so.0.2: undefined reference to `dtrevc3_'
../lib/libopenblas.so.0.2: undefined reference to `strsm_kernel_LN'
collect2: error: ld returned 1 exit status
utest/CMakeFiles/openblas_utest.dir/build.make:147: recipe for target 'utest/openblas_utest' failed
make[2]: *** [utest/openblas_utest] Error 1
CMakeFiles/Makefile2:501: recipe for target 'utest/CMakeFiles/openblas_utest.dir/all' failed
make[1]: *** [utest/CMakeFiles/openblas_utest.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
sem@Fjordforsk:~/Downloads/OpenBLA

What is wrong? I have tried many alternatives, but it doesn't work.
Thanks

**Comment by psprashX** [comment]
I had similar issues when building the "cmake" way from another build directory. Compilation went fine using the usual make style from the source directory.

**Comment by martin-frbg** [comment]
@Sem754 this is most likely due to giving an unknown TARGET (some generic routines will be built but at some point the build system will be unable to pick a specific one for your system). Please try with TARGET=EXCAVATOR (or BULLDOZER etc as appropriate for your CPU - see available targets in TargetList.txt)
@psprashX it is possible that the cmake files are not yet as sophisticated as the "conventional" Makefiles. If you can provide more details of your experience perhaps this can be fixed.
