### ISSUE TITLE
cmake shared lib build fails

### ISSUE THREAD

**Issue by mseminatore** [xianyi/OpenBLAS#4064]
Using LLVM16 compiler toolchain on Windows. VS2022 is also installed.

Steps taken
1. git clone OpenBLAS, md build, cd build
2. cmake .. -G Ninja -DDYNAMIC_ARCH=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
3. attempt to build using straight `ninja` command or cmake .. --build --config Release

Fails with ninja subcommand failure message. It looks like it fails attempting to link test executables. Linker missing a number of CBLAS routines.

Same process succeeds building static libs.

**Comment by martin-frbg** [comment]
Can you share your build log please ? I cannot reproduce this in our CI so far (though actually running the tests requires putting the DLL somewhere on the search path, e.g. by copying it from build/lib to build/test and build/ctest)

**Comment by mseminatore** [comment]
I will try again and share the log. I am working on the Windows Threading
issue right now.
