### ISSUE TITLE
Multiple segfaults and test failures with INTERFACE64=1

### ISSUE THREAD

**Issue by felixonmars** [xianyi/OpenBLAS#4072]
Hello. I am packaging openblas for Arch Linux, and just tried to run the test suite for both variants (with INTERFACE64 or not).

The build without INTERFACE64 passes all tests, but the one with INTERFACE64=1 and all other options unchanged is getting multiple test failures and segfaults:

```
Test project /build/openblas/src/build64
      Start  1: openblas_utest
 1/25 Test  #1: openblas_utest ...................***Exception: SegFault  0.00 sec
      Start  2: sblas1
 2/25 Test  #2: sblas1 ...........................***Exception: SegFault  0.16 sec
      Start  3: sblas2
 3/25 Test  #3: sblas2 ...........................   Passed    0.16 sec
      Start  4: sblas3
 4/25 Test  #4: sblas3 ...........................   Passed    0.16 sec
      Start  5: dblas1
 5/25 Test  #5: dblas1 ...........................***Exception: SegFault  0.16 sec
      Start  6: dblas2
 6/25 Test  #6: dblas2 ...........................   Passed    0.16 sec
      Start  7: dblas3
 7/25 Test  #7: dblas3 ...........................   Passed    0.16 sec
      Start  8: cblas1
 8/25 Test  #8: cblas1 ...........................***Exception: SegFault  0.15 sec
      Start  9: cblas2
 9/25 Test  #9: cblas2 ...........................   Passed    0.16 sec
      Start 10: cblas3
10/25 Test #10: cblas3 ...........................   Passed    0.16 sec
      Start 11: zblas1
11/25 Test #11: zblas1 ...........................***Exception: SegFault  0.15 sec
      Start 12: zblas2
12/25 Test #12: zblas2 ...........................   Passed    0.15 sec
      Start 13: zblas3
13/25 Test #13: zblas3 ...........................***Failed    0.01 sec
      Start 14: xscblat1
14/25 Test #14: xscblat1 .........................***Exception: SegFault  0.15 sec
      Start 15: xscblat2
15/25 Test #15: xscblat2 .........................   Passed    0.00 sec
      Start 16: xscblat3
16/25 Test #16: xscblat3 .........................   Passed    0.01 sec
      Start 17: xdcblat1
17/25 Test #17: xdcblat1 .........................***Exception: SegFault  0.15 sec
      Start 18: xdcblat2
18/25 Test #18: xdcblat2 .........................   Passed    0.00 sec
      Start 19: xdcblat3
19/25 Test #19: xdcblat3 .........................   Passed    0.00 sec
      Start 20: xccblat1
20/25 Test #20: xccblat1 .........................***Exception: SegFault  0.15 sec
      Start 21: xccblat2
21/25 Test #21: xccblat2 .........................   Passed    0.00 sec
      Start 22: xccblat3
22/25 Test #22: xccblat3 .........................   Passed    0.01 sec
      Start 23: xzcblat1
23/25 Test #23: xzcblat1 .........................***Exception: SegFault  0.16 sec
      Start 24: xzcblat2
24/25 Test #24: xzcblat2 .........................   Passed    0.00 sec
      Start 25: xzcblat3
25/25 Test #25: xzcblat3 .........................   Passed    0.01 sec

60% tests passed, 10 tests failed out of 25

Total Test time (real) =   2.38 sec

The following tests FAILED:
          1 - openblas_utest (SEGFAULT)
          2 - sblas1 (SEGFAULT)
          5 - dblas1 (SEGFAULT)
          8 - cblas1 (SEGFAULT)
         11 - zblas1 (SEGFAULT)
         13 - zblas3 (Failed)
         14 - xscblat1 (SEGFAULT)
         17 - xdcblat1 (SEGFAULT)
         20 - xccblat1 (SEGFAULT)
         23 - xzcblat1 (SEGFAULT)
Errors while running CTest
```

Not sure why I didn't get coredumps for the segfault, but here is the generated Testing/Temporary/LastTest.log:
[LastTest.log](https://github.com/xianyi/OpenBLAS/files/11647352/LastTest.log)

Build command w/options: https://gitlab.archlinux.org/archlinux/packaging/packages/openblas/-/blob/0.3.23-2/PKGBUILD#L32

**Comment by brada4** [comment]
I dont see any reference on how you built the tests. They have to be built with ILP64 just like OpenBLAS itself.

**Comment by felixonmars** [comment]
The tests should have been built within the same "cmake --build" above.

Further testing with Julia's test suite confirms that the problem is in OpenBLAS itself instead of just the tests: https://bugs.archlinux.org/task/66092#comment218505

**Comment by brada4** [comment]
Like a build log where one can see parameters for tests built vs the functions tested? Without installing arch preferably.

**Comment by martin-frbg** [comment]
not immeduately reproducible with current develop, and I don't recall a recent operand mismatch that would have caused something like this. can you post build host, compilers, ~~cmake~~ options please ?

**Comment by martin-frbg** [comment]
also note that `-DCORE=` is not a supported option (unless it gets mangled by your build script before actually being passed to cmake), you'll want to use `-DTARGET=` instead.
(not sure if pre-setting the internally used CORE variable would be sufficient to cause problems though)

**Comment by felixonmars** [comment]
I have tried to reproduce it with a minimum configuration and here it is:

- cmake -B build64 -DINTERFACE64=1
- cmake --build build64
- cd build64/ && ctest

So it seems none of the flags were the problem. I have also removed the 32bit integer build part so that it doesn't interfere. Also the problem only occurs with gcc-fortran installed and f95 used as the fortran compiler.

Compiler version, in case it is related:
GCC 13.1.1

**Comment by felixonmars** [comment]
I have narrowed it down to a cmake problem since it doesn't reproduce with the plain Makefile. 

None of the configured Fortran compiler flags are present with the default setup because `CMAKE_Fortran_COMPILER` is `/usr/bin/f95` which made `F_COMPILER` to be `f95` and thus fails all conditions like `if (${F_COMPILER} STREQUAL "GFORTRAN")`.

Setting `FC=gfortran` fixes the problem here.

**Comment by martin-frbg** [comment]
can you please  make sure that "f95" is actually from  GCC13 as well and not a remnant of some older installation ? An ABI mismatch between different generations of GNU C and Fortran would explain random crashes

**Comment by felixonmars** [comment]
Yes, f95 is actually from the same GCC 13 installation. It's just the name difference causing the problem in the cmake routines.

**Comment by martin-frbg** [comment]
unfortunately f95 is/was also a name used by some commercial compiler(s), the name probably triggers some older code paths in f_check leading to settings for a different ABI

**Comment by felixonmars** [comment]
It may make more sense to set `F_COMPILER` according to `CMAKE_Fortran_COMPILER_ID` instead of `CMAKE_Fortran_COMPILER`, which will always be `GNU` for gfortran. Not sure how to better incorporate this with the Makefile approach though.
