### ISSUE TITLE
Why I can't use builed lib and include after building with Visual Studio 2019?

### ISSUE THREAD

**Issue by Kunlei-Hong** [xianyi/OpenBLAS#4073]
sorry,something shoule be wrong in my project.
step1:make
step2:make install
and i got bin include and libe folders and adding them to my project environment. when generating in vs 2019,it annonunced 128 errors.
could anyone tell me why and how to solve it. thanks all the way.
![image](https://github.com/xianyi/OpenBLAS/assets/64198368/e92ca5ee-43ce-48e1-808d-68559902116e)

**Comment by martin-frbg** [comment]
probably related to #3661

**Comment by martin-frbg** [comment]
which version of OpenBLAS did you build ?

**Comment by Kunlei-Hong** [comment]
> which version of OpenBLAS did you build ?

hey,the version was the lastest so far. I doubt I used the wrong compiler in VS 2019. I am trying to change deault compiler and to be continued.

**Comment by martin-frbg** [comment]
Nothing wrong with the compiler (except that it is VS :) ), I was just wondering if it could be fixed similarly to what seemed to be working for #3661 - does your project build when you add something like
```
#if defined(_MSC_VER)
#if !defined(LAPACK_COMPLEX_CUSTOM)
    #include <complex>
    #define LAPACK_COMPLEX_CUSTOM
    #define lapack_complex_float _Fcomplex
    #define lapack_complex_double _Dcomplex
#endif
#endif

before you include lapack.h ?
```

**Comment by nanthony21** [comment]
The #include should be <complex.h>, not <complex>. Also it looks like newer versions of MSVC need to #define _CRT_USE_C_COMPLEX_H before including <complex.h> .  It would be nice if the documentation was updated to reflect this. https://github.com/microsoft/STL/issues/3280

**Comment by martin-frbg** [comment]
Thank you - added to lapack.h in #4368 , which should be more effective than adding to documentation (I think)
