### ISSUE TITLE
benchmark/spr[2].c has executable permission

### ISSUE THREAD

**Issue by angsch** [xianyi/OpenBLAS#4095]
Nit: The file permissions of

- benchmark/spr2.c
- benchmark/spr.c

are `-rwxrwxr-x`, opposed to `-rw-rw-r--` of the other source files.

**Comment by brada4** [comment]
@martin-frbg Also 
kernel/arm64/sgemm_beta.S
kernel/generic/ztrmmkernel_4x4.c

(scripts/ are intentionally executable with interpreter)

**Comment by martin-frbg** [comment]
Fixed now in fec4867 (benchmark sources from original issue) and 7976def (kernel files), thanks
