### ISSUE TITLE
Getting random colon during gfortran linking 

### ISSUE THREAD

**Issue by squintingsmile** [xianyi/OpenBLAS#4099]
During make using gcc-11 on my mac I got the following error from gfortran
```
gfortran -O2 -m128bit-long-double -Wall -frecursive -fno-optimize-sibling-calls -m64 -fopenmp -fPIC -msse3 -mssse3 -msse4.1 :-L/usr/local/opt/libomp/lib -all_load -headerpad_max_install_names -install_name "/Users/squintingsmile/Downloads/OpenBLAS-0.3.23/exports/../libopenblas.0.dylib" -dynamiclib -o ../libopenblas_nehalemp-r0.3.23.dylib ../libopenblas_nehalemp-r0.3.23.a -Wl,-exported_symbols_list,osx.def  -L/usr/local/Cellar/gcc@11/11.4.0/bin/../lib/gcc/11/gcc/x86_64-apple-darwin22/11 -L/usr/local/Cellar/gcc@11/11.4.0/bin/../lib/gcc/11/gcc -L. -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib -L/usr/local/Cellar/gcc@11/11.4.0/bin/../lib/gcc/11/gcc/x86_64-apple-darwin22/11/../../..  -lgfortran -lgomp -lquadmath -lSystem
ld: file not found: :-L/usr/local/opt/libomp/lib
collect2: error: ld returned 1 exit status
make[1]: *** [libopenblas_nehalemp-r0.3.23.dylib] Error 1
make: *** [shared] Error 2
```

The error is due to the colon before `-L/usr/local/opt/libomp/lib`, which becomes `:-L/usr/local/opt/libomp/lib`. I tried removing the colon and manually typed this in my terminal and worked pretty well. I figure there is some bug in the makefile for OSX system.

System: Ventura (13.3.1 (22E261))
Compiler: gcc 11.4.0, gfortran 11.4.0
CPU: M1 Pro

**Comment by martin-frbg** [comment]
The colon is not the only strangeness here - it was probably obtained from a similar linker error message like the "ld: file not found" seen in your output. If it is an M1, why would the build be for Intel Nehalem - or are you intentionally trying to cross-compile for x86 systems ? Can you please provide your `make` command options ?

**Comment by brada4** [comment]
You certainly should use aarch64 gfortran to link against native gomp on m1

**Comment by squintingsmile** [comment]
> The colon is not the only strangeness here - it was probably obtained from a similar linker error message like the "ld: file not found" seen in your output. If it is an M1, why would the build be for Intel Nehalem - or are you intentionally trying to cross-compile for x86 systems ? Can you please provide your `make` command options ?

The command I used was `make -j8`. It seems automatically build x86 version for me. The compilers are from homebrew installation.

**Comment by martin-frbg** [comment]
Very strange. It should autodetect the cpu as "VORTEX", but even if autodetection failed it should recognize the arm64 architecture and fall back to generic ARMV8 as the build target. Maybe you have an x86 emulator installed (not sure if that is installed by default on the M1), and the only compiler on your system is the one for x86, not the native arm64/aarch64 version of gcc ?

**Comment by brada4** [comment]
Seems x86 homebrew runs on aarch64, while /local/ library is aarch.

**Comment by squintingsmile** [comment]
> Very strange. It should autodetect the cpu as "VORTEX", but even if autodetection failed it should recognize the arm64 architecture and fall back to generic ARMV8 as the build target. Maybe you have an x86 emulator installed (not sure if that is installed by default on the M1), and the only compiler on your system is the one for x86, not the native arm64/aarch64 version of gcc ?


I checked homebrew config and it said rosetta 2 on. Seems it's running x86 homebrew and should be downloading x86 gcc. The problem should be what brada mentioned, I'm using gcc for x86 system. I don't really bother to fix that by installing everything using arm brew for now. 

However, removing the colon and type the command manually does seem to fix the problem so I'll call it a day (at least it doesn't spit out error)

**Comment by martin-frbg** [comment]
Oh, ok, that's alright if it is fast enough for you that way. Not much we could do to prevent this problem from happening anyway, when the compiler/linker picks up the wrong type of library and part of the error message ends up in the build options. (We could certainly strip out any colon character, but would it solve this rare problem in all cases ?)
