### ISSUE TITLE
How to uninstall OpenBLAS

### ISSUE THREAD

**Issue by HengamehB** [xianyi/OpenBLAS#4111]
Hi, 
I installed OpenBlas on MacOS M2 using 

 $ export MACOSX_DEPLOYMENT_TARGET=11.0
 $ make CC=cc FC=gfortran

But for my own reasons I need to uninstall the package now. 
How can I do that?

**Comment by martin-frbg** [comment]
If you have only run `make` and not `make install` as well, just remove the directory you put the sources in.
If you installed it, it will probably be in /opt/OpenBLAS (just remove that) or in /usr/local (remove the cblas,lapack and lapacke headers and the openblas_config.h from include, remove the libopenblas from lib)

**Comment by HengamehB** [comment]
I did install it using:

$make install PREFIX=path/to/OpenBLAS

There is no folder  /opt/OpenBLAS when I look for it.

**Comment by HengamehB** [comment]
Also I couldn't find any of the cblas,lapack and lapacke headers anywhere either.

**Comment by martin-frbg** [comment]
Ok, what did you give as "path to openblas" ? If you just copied that literally, you will probably see a directory named "path" under your OpenBLAS source directory...

**Comment by HengamehB** [comment]
I put in a new address. I did find the header files under that path and deleted that whole folder.
Thanks.
