### ISSUE TITLE
A more clear guide on how to install on windows

### ISSUE THREAD

**Issue by FerLuisxd** [xianyi/OpenBLAS#4124]
I get that the binaries are only given to windows.
However I think the only in depth guide on how to install in the manual way but not using the binaries given.
How can I install OpenBLAS with the official binaries to Windows?

**Comment by martin-frbg** [comment]
Oh well, the "official" binaries are just a zip archive of what one would get from following section 2 of the wiki page about using OpenBLAS with Windows/Visual Studio https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-in-Microsoft-Visual-Studio#2-gnu-mingw-abi - I know better documentation is needed, but I am not the ideal person to provide information on anything Windows-related

**Comment by brada4** [comment]
You just copy files and rename to blas.dll cblas.dll lapack.dll lapacke.dll Rblas.dll and so on. If you build them it wiki is full on how to fit BLAS into visual studio with headers, debug symbols etc.

**Comment by martin-frbg** [comment]
Added a short paragraph to the Windows section of the Installation Guide in the wiki https://github.com/xianyi/OpenBLAS/wiki/Installation-Guide#windows - suggestions for improvement welcome. (Unfortunately we had to lock down the wiki after repeated instances of vandalism and addition of malicious links)

**Comment by brada4** [comment]
Couldnt have made it any better.

**Comment by brada4** [comment]
You probably have to mention INTERFACE64=0 for compatibility with default x86_64 netlib build options

**Comment by martin-frbg** [comment]
Added, thanks

**Comment by FerLuisxd** [comment]
> Added a short paragraph to the Windows section of the Installation Guide in the wiki https://github.com/xianyi/OpenBLAS/wiki/Installation-Guide#windows - suggestions for improvement welcome. (Unfortunately we had to lock down the wiki after repeated instances of vandalism and addition of malicious links)

Thanks a lot for this! One last question, What folder should be added to the path so it can be access via the command line?

**Comment by brada4** [comment]
It should not be in universal PATH as there are int32/int64 functions under same name imported by various programs. It has to replace generic version where the original generic DLL is. It is really primarily to do a zero-effort retrofit and speed up old program on new hardware ;-)
For short practice - install R statistics package anc compare generic dll vs openblas dll wirh benchmarks/scripts/R/*.R

**Comment by martin-frbg** [comment]
Depends on what you are doing (I think) - if you want your own programs (or others that expect to link to openblas.dll) to find it, add that folder to your PATH. If you have third-party programs that already link to a lapack.dll and/or blas.dll, replace those dlls with the openblas.dll.
