### ISSUE TITLE
imatcopy: wrong info on invalid ldb

### ISSUE THREAD

**Issue by angsch** [xianyi/OpenBLAS#4132]
https://github.com/xianyi/OpenBLAS/blob/4d0b7fbec04c95c90291938a5974f00673e10e68/interface/imatcopy.c#L103-L104
https://github.com/xianyi/OpenBLAS/blob/4d0b7fbec04c95c90291938a5974f00673e10e68/interface/imatcopy.c#L108-L109

should all return `info = 8`.

This is likely a copy&paste error from `omatcopy`, where `ldb` is the 9th argument. `imatcopy` has one argument less.

**Comment by martin-frbg** [comment]
Good catch, thanks
