### ISSUE TITLE
`gemmt` missing from docs about extensions

### ISSUE THREAD

**Issue by david-cortes** [xianyi/OpenBLAS#4135]
Non-standard BLAS extension `GEMMT` was added in the latest version of OpenBLAS:
https://github.com/xianyi/OpenBLAS/pull/3796

But this function is not mentioned in the wiki for OpenBLAS extensions:
https://github.com/xianyi/OpenBLAS/wiki/OpenBLAS-Extensions

It's also currently missing from the `cblas.h` header shipped by `libopenblas-openmp-dev` in debian12, but `readelf` confirms that the `.so` file contains the cblas and fortran variants of this new addition.

**Comment by martin-frbg** [comment]
Yes, this has become intentional as the implementation in 0.3.23 turned out to be not fully functional. Header and wiki will be updated with 0.3.24
