### ISSUE TITLE
Runtime check failure: "data02 is uninitialized"

### ISSUE THREAD

**Issue by cristianPanaite** [xianyi/OpenBLAS#4144]
Hello!

I encountered this "Debug Error" when I tried to run the CTests on 2 different machines with the same OS.

### Environement 
- x64 and Arm64 machines with Windows 11
- I used VSCode with CMake extensions for CMake configuration, with Visual Studio Professional 2022 Release for Kit  (similar as in the picture but for Arm64 for the Arm64 device)
![image](https://github.com/xianyi/OpenBLAS/assets/57230852/e9a13b93-440f-4808-826c-d2ce38d28a8f)

### Step to reproduce
1. Clone OpenBLAS
2. Open the folder in VSCode
3. Build OpenBLAS using CMake extension in VSCode
4. Run CTests
![image](https://github.com/xianyi/OpenBLAS/assets/57230852/04dfa64c-c596-40b7-9e4f-57e5108f42a4)
    - At some point during the run, an error message is displayed, indicating an issue with the test `xccbla.exe`:
![image](https://github.com/xianyi/OpenBLAS/assets/57230852/44350064-fa0b-453f-94c5-b181cdc52576)
    - The execution of the tests does not proceed unless one of the options is pressed. After some time, a similar error occurs for the test `xzcbla.exe`:
![image](https://github.com/xianyi/OpenBLAS/assets/57230852/4003f74e-c8fb-4bed-b170-6c609b701299)

### Workaround

[This commit](https://github.com/Blackhex/OpenBLAS/commit/f6c9c72ca47038aa8a45efb57c171083a20b43a2) illustrates an workaround for this problem, but I think there might be a better solution.

**Comment by martin-frbg** [comment]
Ouch, looks like we've been there before and I erroneously reverted a zero-initializing PR for the affected file(s) some time ago while (probably) intending to revert a change to the respective ztrmm files.
