### ISSUE TITLE
build.openblas.net redirects to www.maineiat.org

### ISSUE THREAD

**Issue by fodinabor** [xianyi/OpenBLAS#4148]
I am slightly confused as to why the build.openblas.net site redirects to a seemingly unrelated webpage..?

**Comment by martin-frbg** [comment]
Oops. Looks like xianyi let the domain registration expire without updating the wiki, and we've been lucky that the IP address went to such a pleasant and useful endeavour while some nameservers still have its entry cached.

 (www._projectname_.net is automatically provided by github as a redirect to their servers, but anything else in the .openblas.net domain would have to be hosted separately)
Buildbot has been out of service for a few years, basically replaced by github CI jobs - though xianyi looked into bringing it back early last year in #3554 (the address mentioned there is currently unavailable as well)  I have removed the reference to it in the Developer Guide for now.
