### ISSUE TITLE
Cortex-A72 Flops?

### ISSUE THREAD

**Issue by jfikar** [xianyi/OpenBLAS#4149]
Hi, I'm running HPL-2.3 on a Cortex-A72 (Raspberry Pi 4) and I'm wondering, how fast is Cortex-A72 supposed to be. Wikipedia says Cortex-A72 should achieve only [2 Flop per clock per core](https://en.wikipedia.org/wiki/FLOPS#Floating-point_operations_per_clock_cycle_for_various_processors) (FP64).

But on a single core I'm getting like 3.2 Flop per clock per core (OpenBLAS 0.3.23). So maybe Wikipedia is wrong and [Cortex-A72 should actually achieve 4 Flop per clock per core as Cortex-A57](https://community.arm.com/support-forums/f/high-performance-computing-forum/47220/cortex-a72-maximum-theoretical-linpack-performance-r_peak)?

What about Cortex-A73? Wikipedia says again only 2 here.

Also Cortex-A55 gives 2.2 Flop per clock per core, but Wikipedia says again 2 here.

Thanks

**Comment by angsch** [comment]
One FMA instruction is usually counted as two flops (multiplication and addition). The A72 has a 128 bit pipeline, ie 2 FP64s are processed at a time. So a single core has the peak calculated as 2 [FMA] x 2 [FP64s per vector pipeline] x clock speed

**Comment by jfikar** [comment]
Makes sense. So Wikipedia is wrong, A72 can do 4 FP64 per cycle. What about the other Cortexes? Is there a better table than the one on Wikipedia?

**Comment by brada4** [comment]
Wikipedia does not refer to ARM documentation, they have instruction table per core type.

**Comment by jfikar** [comment]
I'm looking at the [Cortex-A72 Software Optimization Guide](https://documentation-service.arm.com/static/5ed75eeeca06a95ce53f93c7), but probably I do not understand it correctly. Let's look at Aarch64 FMADD (not sure, if this is the rigth op) on page 17. It says latency 7 (3) and throughput 2. How can I combine it to 4 FP64/cycle? Am I missing something?

**Comment by brada4** [comment]
Latency 7 or 3 for 4-8 2-flop operations using SIMD register.
Why dont you cast your doubts at wikipedia?

**Comment by jfikar** [comment]
Well, I was not sure that Wikipedia is wrong. I just had doubts. Wikipedia probably should be corrected by someone, who really knows the matter.

I'm finally starting to understand the A72 FMADD. For Flop/cycle I should not look a the exec latency, but at the execution throughput, which is 2. As @angsch  said, it is 128bit (in all ARMv8a?), so it gives 4 FP64 Flop/cycle, right?

Looking at other Cortexes I get: Cortex-A55, Cortex-A57, Cortex-A76, and Cortex-A77 also 4 FP64 Flop/cycle. But I could not find anything for A53 and A73.

**Comment by brada4** [comment]
4 FP64 flops (as FMA) in 3 or 7 cycles depending on core configuration in factory. 
EDIT: the wikipedia source does not refer to ARM documentation, but probably the proportion one core vs another is right like SIMD width etc.

**Comment by jfikar** [comment]
> 4 FP64 flops (as FMA) in 3 or 7 cycles depending on core configuration in factory.

This is confusing me again. 4 Flop in 3 or 7 cycles would mean only 4/3=1.3 Flop/cycle or 4/7=0.6 Flop/cycle? I thought the throughput is already in op/cycle, so there is no need to divide by latency.

_• Execution Throughput is defined as the maximum throughput (in instructions / cycle) of the specified
instruction group that can be achieved in the entirety of the Cortex®-A72 microarchitecture._

> EDIT: the wikipedia source does not refer to ARM documentation, but probably the proportion one core vs another is right like SIMD width etc.

I don't think the Wikipedia numbers are just relative for core-to-core comparison. [ Just above the table](https://en.wikipedia.org/wiki/FLOPS#Computational_performance) there are formulas, which basically say: take the number from table in Flop/cycle/core and multiply by frequency and core number and you get the total theoretical peak Flop/s of the CPU. This is also the number reported by [top500.org](https://top500.org) as Rpeak. (But the Top 500 list is sorted by Rmax, which is the performance measured by HPL. Rmax < Rpeak).

It also works for example for x86 Haswell (AVX2). Table gives 16 Flop/cycle/core for FP64 and with HPL I can measure slightly less on one core around 14.5 Flop/cycle/core.

**Comment by brada4** [comment]
You have to solve your doubts with wikipedia, there is no intent to slow down openblas to make wikipedia correct.

**Comment by jfikar** [comment]
I've changed the Wikipedia page accordingly.
