### ISSUE TITLE
make install with TARGET not working with intel ice lake processor

### ISSUE THREAD

**Issue by xyzeng-lehigh** [xianyi/OpenBLAS#4154]
Hi, I was trying to build openblas-0.3.23 on a workstation with Intel ice lake processor. Following another thread, I am using the SKYLAKEX as the TARGET, and I specify it using:

> make CC=${PATHCC}/gcc CXX=${PATHCC}/g++ FC=${PATHCC}/gfortran TARGET=SKYLAKEX
> make install PREFIX=${INSTALLBLAS} TARGET=SKYLAKEX

However, it seems that the code is still looking for a haswell version of the library and generates the following output and error message. Could you help me with the issue? It just seems that the TARGET option on the "make install" line is not taking effect.

>  OpenBLAS build complete. (BLAS CBLAS LAPACK LAPACKE)
> 
>   OS               ... Linux
>   Architecture     ... x86_64      
>   BINARY           ... 64bit      
>   C compiler       ... GCC  (cmd & version : gcc (GCC) 9.3.0)
>   Fortran compiler ... GFORTRAN  (cmd & version : GNU Fortran (GCC) 9.3.0)
>   Library Name     ... libopenblas_skylakexp-r0.3.23.a (Multi-threading; Max num-threads is 64)
> 
> To install the library, you can run "make PREFIX=/path/to/your/installation install".
> 
> Note that any flags passed to make during build should also be passed to make install
> to circumvent any install errors.
> 
> make -j 64 -f Makefile.install install
> make[1]: Entering directory `/home/user/MyDocuments/C/Support/package/gcc9.3/openblas-0.3.23-build/openblas-0.3.23'
> Generating openblas_config.h in /home/user/MyDocuments/C/Support/gcc-9.3.0/openblas/include
> Generating f77blas.h in /home/user/MyDocuments/C/Support/gcc-9.3.0/openblas/include
> Generating cblas.h in /home/user/MyDocuments/C/Support/gcc-9.3.0/openblas/include
> Copying LAPACKE header files to /home/user/MyDocuments/C/Support/gcc-9.3.0/openblas/include
> Copying the static library to /home/user/MyDocuments/C/Support/gcc-9.3.0/openblas/lib
> install: cannot stat ‘libopenblas_haswellp-r0.3.23.a’: No such file or directory

**Comment by martin-frbg** [comment]
Does it work when you repeat the CC and FC options from the build command line as well ? (I suspect that you have another, older compiler installed as default that does not yet support AVX512, and the build system downgrades your target to the best it can support)

**Comment by xyzeng-lehigh** [comment]
Work like a charm! 
I do have a default CC (gcc 4.8.5) that is shipped with the OS (Scientific Linux 7.9), and following your suggestion (adding the CC options on the make install line) solves the problem.
