### ISSUE TITLE
在麒麟系统编译paddle时需要第三方库

### ISSUE THREAD

**Issue by Phoenix2Legend** [xianyi/OpenBLAS#4156]
执行命令make TARGET=ARMV8 extern_openblas -j$(nproc)以后，显示正克隆到extern_openblas，然后长时间未响应。最后出现报错：error：RPC失败
fatal：远端意外挂断了
fatal：过早的文件结束符EOF
fatal：index-pack 失败
然后自动切换分支以后报了一些语法错误。
不知道什么原因以及如何解决。

**Comment by martin-frbg** [comment]
Looks like network timeout. Can you try again, or try to download a tar or zip archive of the sources from the release page
https://github.com/xianyi/OpenBLAS/releases , unpack and rename from OpenBLAS-0.3.23 to extern_openblas  ?

**Comment by Phoenix2Legend** [comment]
martin你好，我使用的是麒麟v10系统，系统内核为Linux-4.4.131-20200710.kylin.desktop-generic-aarch64-with-Kylin-V10-juniper;CPU为Phytium,FT-2000/4(64位，4核)。

**Comment by Phoenix2Legend** [comment]
我直接将https://github.com/xianyi/OpenBLAS.git的代码下载下来以后，把OpenBLAS-develop文件夹放到Paddle/build/third_party/openblas/src下面，删除该文件夹下原有的的extern_openblas并把OpenBLAS-develop重命名为extern_openblas，然后返回build目录下执行make TARGET=ARMV8 extern_openblas -j$(nproc)后报错：
λ wangan-GW-001M1A-FTF /workspace/Paddle/build {develop} make TARGET=ARMV8 extern_openblas -j$(nproc)
Performing build step for 'extern_openblas'
make[4]: 警告: 子 make 中强制 -jN: 关闭 jobserver 模式。
make[4]: 警告: jobserver 不可用: 正使用 -j1。添加 “+” 到父 make 的规则。
/bin/sh: ./c_check: 权限不够
/bin/sh:行1: ./c_check: 权限不够
/bin/sh: ./c_check: 权限不够
make[4]: *** [Makefile.prebuild:63：config.h] 错误 126
Makefile.system:1504: Makefile.: 没有那个文件或目录
make[4]: *** 没有规则可制作目标“Makefile.”。 停止。
make[3]: *** [CMakeFiles/extern_openblas.dir/build.make:116：third_party/openblas/src/extern_openblas-stamp/extern_openblas-build] 错误 2
make[2]: *** [CMakeFiles/Makefile2:4541：CMakeFiles/extern_openblas.dir/all] 错误 2
make[1]: *** [CMakeFiles/Makefile2:4548：CMakeFiles/extern_openblas.dir/rule] 错误 2
make: *** [Makefile:297：extern_openblas] 错误 2

**Comment by martin-frbg** [comment]
FT2000 should work as "TARGET=ARMV8". But there is something strange about your filesystem that keeps programs and shell scripts from running - "/bin/sh: ./c_check: 权限不够" - and in your paddle issue you had the same message for the "getarch" executable.  (c_check is a simple shell script that finds out C compiler options) . Maybe /workspace is mounted with "noexec" option, or it is a non-Linux filesystem that does not store Linux/Unix file permissions ?
