### ISSUE TITLE
OpenBLAS  cross-compiled to AARCH64 without the problems of the gfortran toolchain

### ISSUE THREAD

**Issue by cx421774557** [xianyi/OpenBLAS#4173]
Hello, I'm using aarch64's cross-compile toolchain (no gfortran tool) to compile kaldi,. Due to the use of the OpenBLAS library, which has .f files, gfortran is required, resulting in compilation failure.

 After tracking, these issues all point to the https://github.com/NIRALUser/CLAPACK in the replaced library.
But when testing unit tests, there are some test cases that fail,

How do I deal with this situation?

**Comment by martin-frbg** [comment]
The replacement C files in OpenBLAS correspond to LAPACK 3.9.0 which is a bit newer than what you found in the (unrelated) NIRALUser account. What unit tests are you running, and which of them fail ?
If all you need is BLAS, you can compile OpenBLAS with NO_LAPACK=1 which leaves out all the .f files and their C replacements.
Hopefully there will be standard aarch64 toolchains with Fortran again once LLVM17 is released.
