### ISSUE TITLE
micro-kernel size for skylake

### ISSUE THREAD

**Issue by HPC4AI** [xianyi/OpenBLAS#4175]
Hello. I was confused when I read the code in the source file `kernel/x86_64/dgemm_kernel _16x2_skylakex.c`. OpenBLAS will pack the matrix into 16 * kc row panels and kc * 2 column panels. However, the main micro-kernel size is 16 * 12 in this file. Are my conclusions correct?

**Comment by XiWeiGu** [comment]
From the parameters, the micro-kernel should be 16 * 2, but it is indeed 16 * 12 in terms of implementation.
16 * 12 can be understood as 6 sets of 16 * 2, which can reduce the number of outermost cycles and improve performance.

**Comment by HPC4AI** [comment]
> From the parameters, the micro-kernel should be 16 * 2, but it is indeed 16 * 12 in terms of implementation. 16 * 12 can be understood as 6 sets of 16 * 2, which can reduce the number of outermost cycles and improve performance.

Thanks. For `TSV110`, OpenBLAS will pack the matrix into 8 * kc row panels and kc * 4 column panels. The main micro-kernel size is 8 * 4 in the file `kernel/arm64/dgemm_kernel_8x4.S`. Am I right?

**Comment by XiWeiGu** [comment]
Based on what I understand, you are correct.

**Comment by martin-frbg** [comment]
There are also some interesting implementation notes hidden in some of the pull requests and issues related to individual kernels, e.g. https://github.com/xianyi/OpenBLAS/pull/2376#issuecomment-577326734 Maybe we should try to gather them when we tackle the documentation updates outlined in #4166

**Comment by XiWeiGu** [comment]
Indeed, this information is important, and gathering it together can be more helpful than having it scattered everywhere. Perhaps within my capacity, I can collect some relevant PRs and issues to contribute material for the documentation updates.
