### ISSUE TITLE
Incorrect results with the MIPS64_GENERIC kernel

### ISSUE THREAD

**Issue by svillemot** [xianyi/OpenBLAS#4181]
Hi,

OpenBLAS 0.3.22 introduced the `MIPS64_GENERIC` kernel. I changed the Debian package to use it on the `mips64el` architecture, but it turns out that this kernel gives incorrect results. In particular, quite a few tests fail in the BLAS and CBLAS testsuites with the `FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE` message. See the [Debian bug report](http://bugs.debian.org/1043048) and the [Debian build log](https://buildd.debian.org/status/fetch.php?pkg=openblas&arch=mips64el&ver=0.3.23%2Bds-2&stamp=1686760279&raw=0).

Actually the problem also manifests on the GitHub CI, where tests also fail with the same error message. See for example this [CI log](https://github.com/xianyi/OpenBLAS/actions/runs/5775175797/job/15652871809).

On a side note, I don’t understand why the testsuite failure does not trigger a failure of the CI job.

Thanks for your work.

**Comment by martin-frbg** [comment]
Looks like it's picking up the wrong kernel files for TRMM (MIPS64_GENERIC should be a copy of GENERIC, I am not even sure it is still needed). test/ctest failures only triggering a warning is a feature inherited from reference BLAS - under the assumption that some failures may be harmless differences in accuracy. It is certainly unfortunate that this one went unnoticed for so long.
