### ISSUE TITLE
Different results of dgetrf_ on different platforms

### ISSUE THREAD

**Issue by AlekseiNikiforovIBM** [xianyi/OpenBLAS#4194]
I've noticed that dgetrf_ may produce different results on different
platforms.

Here's somewhat minimized example:
```
#include <stdio.h>

void dgetrf_(int *m, int *n, double *a, int *lda, int *ipiv, int *info);

int main(int argc, char **argv)
{
    int m = 5;
    int n = 5;
    int lda = 5;

    double a[] = {
        0.72857546562820341,
        -0.78281609716933998,
        0.86046155246780609,
        -1.0006287963975689,
        1.5611716761308798,
        0.41911784786867096,
        -0.6454528622624528,
        0.41128486717490204,
        -0.94252011314907469,
        1.5177029668084923,
        0.3450071123222726,
        -0.42495485776980968,
        0.50896485191514396,
        -0.55082163903276304,
        0.84641169749513157,
        0.81046059079204757,
        -0.10383394280963526,
        -0.051601994141029284,
        0.017058483822232351,
        0.72535356734870426,
        -0.51269675072665255,
        -0.098946294965133214,
        -0.75082005371623339,
        -0.46603827004164611,
        0.48025114546825054,
    };

    int ipiv[] = {
        682,
        607260352,
        682,
        607541760,
        0,
    };

    int info[] = {
        682,

    };

     dgetrf_(&m, &n, a, &lda, ipiv, info);

     for (int i = 0; i < 25; ++i)

     {
        printf("a[%d] = %e\n", i, a[i]);
     }

    return 0;
}
```

I compile it with `gcc blas.c -O0 -g -ggdb -lopenblas -o blas` and run.
On linux on x86_64 `a[24] = 6.938894e-17`, on linux on s390x `a[24] =
0.000000e+00`.

It looks like on x86_64 there are separate vector multiply and vector
add instructions used:

https://github.com/xianyi/OpenBLAS/blob/develop/kernel/x86_64/dgemv_n_4.c#L155-L158

On s390x similar code uses combined vector multiply and add instructions:

https://github.com/xianyi/OpenBLAS/blob/develop/kernel/zarch/dgemv_n_4.c#L318-L325

Due to that, precision is higher, but results are different.

I've also noticed that in other parts of x86_64 code, like here,
combined instructions are used as well:

https://github.com/xianyi/OpenBLAS/blob/develop/kernel/x86_64/dgemv_n_microk_haswell-4.c#L62-L63

So I have a question: are both results considered within acceptable
precision or is one of results invalid?

**Comment by martin-frbg** [comment]
If I'm not completely mistaken, that difference is in the same range as the numerical precision of a double so I would think it is acceptable (and similar to what one would get from compiling the same C or Fortran code with different compilers or at different optimization levels).

**Comment by brada4** [comment]
You are expected to lose some bits vs symbolic result. e.g 9 bits of precision simply adding bigest and smallest cells in test set.
