### ISSUE TITLE
Assessment of the difficulty in porting CPU architecture for openBLAS

### ISSUE THREAD

**Issue by wangyuliu** [xianyi/OpenBLAS#4215]
Hello everyone! I am working on implementing a tool to assess the complexity of CPU architecture porting. It primarily focuses on RISC-V architecture porting. As part of my dataset, I have collected the openBLAS project. I would like to gather community opinions to support my assessment. I appreciate your help and response! Based on scanning tools, the porting complexity is determined to be high, with a significance amount of code related to the CPU architecture in the project. It would require a professional team, to handle this task (referring to the overall workload from adapting the project to a specific architecture to achieving full functionality on that architecture). Is this assessment accurate? I look forward to your help and response.
各位网友大家好啊~~~~我正在实施一个工具，以评估CPU架构移植的复杂性。它主要关注RISC-V体系结构的移植。作为我的数据集的一部分，我收集了openblas项目。我希望收集社会人士的意见，以支持我的评估。我很感谢你的帮助和回应！基于扫描工具，移植的复杂性被确定为较难，与项目中的CPU架构相关的代码量较多。这将需要一个专业的团队，来处理这个任务（指的是从使项目适应特定架构到在该架构上实现全部功能的总体工作量）。这样的评价准确吗？我期待着你的帮助和回应。

**Comment by martin-frbg** [comment]
Porting is addressed (though not in much detail) in the wiki. Basically one can start with cloning the generic C kernels for a new architecture, though good knowledge of either the assembly language for the target architecture or the equivalent C intrinsics (if available) would be required to create highly performant code. This does not necessarily mean that a "professional team" would be required to do it, just one or two people with the time and knowledge.

Not sure how you plan to implement a tool to assess this - if it just checks whether a codebase contains any cpu-specific files you would be less well informed than from just looking at the source and documentation provided. (And creating bug report tickets  (or worse, dummy pull requests) in numerous projects just to ask a general question will not win you friends on github)

**Comment by wangyuliu** [comment]
Thank you for your feedback. We apologize for any inconvenience caused by using this feature for the first time!

**Comment by wangyuliu** [comment]
> Porting is addressed (though not in much detail) in the wiki. Basically one can start with cloning the generic C kernels for a new architecture, though good knowledge of either the assembly language for the target architecture or the equivalent C intrinsics (if available) would be required to create highly performant code. This does not necessarily mean that a "professional team" would be required to do it, just one or two people with the time and knowledge.
> 
> Not sure how you plan to implement a tool to assess this - if it just checks whether a codebase contains any cpu-specific files you would be less well informed than from just looking at the source and documentation provided. (And creating bug report tickets (or worse, dummy pull requests) in numerous projects just to ask a general question will not win you friends on github)

Sorry to bother you again. After further analysis of the questions you raised above, our tool evaluates and predicts openblas. The information obtained is that openblas has millions of lines of assembly code, and statistics indicate that there are more than a thousand Intrinsic functions， so our tool evaluates the porting complexity is  high. Do you agree with this, or do you think it is only moderately difficult to port?

**Comment by martin-frbg** [comment]
Well, as I wrote before it all depends on what "porting" means to you and how experienced the person doing it is. 
You can quite easily get OpenBLAS running on a new architecture by using the generic C kernels, which should already be a bit faster than the reference implementation of BLAS.
To create optimized kernels you would need someone who knows either the assembly language or its corresponding C intrinsics for the new system and has some experience either with writing optimized code from scratch or optimizing what a compiler produces from the generic C code. (Or if you had a machine translation tool or a library like SIMDe that transforms x86_64 or arm64 instructions into whatever the new machine has, maybe you could have that port optimized kernels)
