### ISSUE TITLE
Scalability of GEMM Performance on ARM  

### ISSUE THREAD

**Issue by darshanp4** [xianyi/OpenBLAS#4219]
Hi,

is anyone did analyses why the scalability of GEMM performance is not good on ARM?
Till 32 threads it is scaling good and later for 64 threads it is flat.
I tried benchmarking using the OpenBlas/benchmark/gemm.c and got below result on Graviton3.

![image](https://github.com/xianyi/OpenBLAS/assets/129051745/56e934fc-28f0-42d7-bdbb-af591d4caf36)

OpenBlas version - develop branch 
I build it with OpenMP enable.

Is there any setting that i am missing for higher number threads for OpenBlas.
Is there any plan for this optimization or any on going work pointers, will be helpful.

Thanks,
Darshan

**Comment by Mousius** [comment]
The thing that springs to mind is https://github.com/xianyi/OpenBLAS/issues/3581, which had some kernels which used `ld1rq` (https://github.com/wxmwy/openblas_sve) that may reduce memory bandwidth. 

Also worth considering using some [non-temporal loads](https://developer.arm.com/documentation/ddi0596/2020-12/SVE-Instructions/LDNT1D--scalar-plus-immediate---Contiguous-load-non-temporal-doublewords-to-vector--immediate-index--) to hint that data has been used and doesn't need to be cached?

Maybe we need non-temporal loads in the copies as well to hint that we don't want to re-use the input matrix (The caveat is that non-temporal gather is SVE2 if I recall correctly):
* https://github.com/xianyi/OpenBLAS/blob/develop/kernel/arm64/gemm_ncopy_sve_v1x8.c
* https://github.com/xianyi/OpenBLAS/blob/develop/kernel/arm64/gemm_tcopy_sve_v1x8.c

Just some ideas 😸

**Comment by martin-frbg** [comment]
Sadly I'm still waiting for xianyi (the only one with full admin access) to approve&add a CI interface for a third-party sponsored AWS account.
The perfect flatness of the curve has me wondering if "something" capped the thread count at 32 (which I think could not be happening in OpenBLAS code, unless it gets the core count wrong on big arm64 architectures.) Did the "maximum number of threads" reported at the end of the build (or NUM_CORES in the generated Makefile.conf) show (at least) 64 ?

**Comment by darshanp4** [comment]
> The thing that springs to mind is #3581, which had some kernels which used `ld1rq` (https://github.com/wxmwy/openblas_sve) that may reduce memory bandwidth.
> 
> Also worth considering using some [non-temporal loads](https://developer.arm.com/documentation/ddi0596/2020-12/SVE-Instructions/LDNT1D--scalar-plus-immediate---Contiguous-load-non-temporal-doublewords-to-vector--immediate-index--) to hint that data has been used and doesn't need to be cached?
> 
> Maybe we need non-temporal loads in the copies as well to hint that we don't want to re-use the input matrix (The caveat is that non-temporal gather is SVE2 if I recall correctly):
> 
> * https://github.com/xianyi/OpenBLAS/blob/develop/kernel/arm64/gemm_ncopy_sve_v1x8.c
> * https://github.com/xianyi/OpenBLAS/blob/develop/kernel/arm64/gemm_tcopy_sve_v1x8.c
> 
> Just some ideas 😸

Thanks for the ideas @Mousius this might be helpful in performance improvement.
I will definitely look into this.

**Comment by darshanp4** [comment]
> Sadly I'm still waiting for xianyi (the only one with full admin access) to approve&add a CI interface for a third-party sponsored AWS account. The perfect flatness of the curve has me wondering if "something" capped the thread count at 32 (which I think could not be happening in OpenBLAS code, unless it gets the core count wrong on big arm64 architectures.) Did the "maximum number of threads" reported at the end of the build (or NUM_CORES in the generated Makefile.conf) show (at least) 64 ?

Thank you @martin-frbg  this helps to resolve the issue for now, i seen NUM_CORES was 32 after updating to 64 issue got resolved and curves looks good now.

**Comment by darshanp4** [comment]
This might required dynamic detect of number of cores, if it is built on 32 cores machine and run on 64 cores machine.  
If we are not setting number of threads then by default it is taking the number of cores.
Makefile.system:317:NUM_THREADS = $(NUM_CORES)
isn't it adapt the max core available on system.

**Comment by Mousius** [comment]
> This might required dynamic detect of number of cores, if it is built on 32 cores machine and run on 64 cores machine. If we are not setting number of threads then by default it is taking the number of cores. Makefile.system:317:NUM_THREADS = $(NUM_CORES) isn't it adapt the max core available on system.

I believe this already happens @darshanp4, `NUM_THREADS` gets renamed to a constant called `MAX_CPU_NUMBER`:

https://github.com/xianyi/OpenBLAS/blob/6bc079687fc09546d02e08951494c51baa9a5535/Makefile.system#L1459

You have to set a high enough value to accommodate most CPUs; NumPy uses `64` for this reason if I recall correctly. This value has to be predetermined to optimize the size of various arrays throughout the codebase.

**Comment by martin-frbg** [comment]
Exactly, if this keeps tripping up people perhaps this should be mentioned directly in README.md instead of referring to Makefile.rule which has all the build-time options.

**Comment by darshanp4** [comment]
> > This might required dynamic detect of number of cores, if it is built on 32 cores machine and run on 64 cores machine. If we are not setting number of threads then by default it is taking the number of cores. Makefile.system:317:NUM_THREADS = $(NUM_CORES) isn't it adapt the max core available on system.
> 
> I believe this already happens @darshanp4, `NUM_THREADS` gets renamed to a constant called `MAX_CPU_NUMBER`:
> 
> https://github.com/xianyi/OpenBLAS/blob/6bc079687fc09546d02e08951494c51baa9a5535/Makefile.system#L1459
> 
> You have to set a high enough value to accommodate most CPUs; NumPy uses `64` for this reason if I recall correctly. This value has to be predetermined to optimize the size of various arrays throughout the codebase.


It means if build from source we need to export env flags , if we are going to use the higher threads system.

I can see this details available in readme , it will better if import this details also [https://github.com/xianyi/OpenBLAS/blob/6bc079687fc09546d02e08951494c51baa9a5535/README.md#setting-the-number-of-threads-using-environment-variables](url)

Thank you @Mousius and @martin-frbg , for now i am closing the issue.
