### ISSUE TITLE
Wrong number in warning when OMP_NUM_THREADS is larger than NUM_THREADS

### ISSUE THREAD

**Issue by dev-zero** [xianyi/OpenBLAS#4220]
Using OpenBLAS v0.3.24 built with `NUM_THREADS=128 USE_THREAD=1 USE_OPENMP=1` with `OMP_NUM_THREADS=256` gives this warning:

```
OpenBLAS warning: precompiled NUM_THREADS exceeded, adding auxiliary array for thread metadata.
To avoid this warning, please rebuild your copy of OpenBLAS with a larger NUM_THREADS setting
or set the environment variable OPENBLAS_NUM_THREADS to 256 or lower
```

which I think is wrong and should be:

```
OpenBLAS warning: precompiled NUM_THREADS exceeded, adding auxiliary array for thread metadata.
To avoid this warning, please rebuild your copy of OpenBLAS with a larger NUM_THREADS setting
or set the environment variable OPENBLAS_NUM_THREADS to 128 or lower
```

I would fix it with this:

```
diff --git a/driver/others/memory.c b/driver/others/memory.c
index 4fceae754..fb7f36cdc 100644
--- a/driver/others/memory.c
+++ b/driver/others/memory.c
@@ -3012,7 +3012,7 @@ void *blas_memory_alloc(int procpos){
  if (memory_overflowed) goto terminate;
   fprintf(stderr,"OpenBLAS warning: precompiled NUM_THREADS exceeded, adding auxiliary array for thread metadata.\n");
   fprintf(stderr,"To avoid this warning, please rebuild your copy of OpenBLAS with a larger NUM_THREADS setting\n");
-  fprintf(stderr,"or set the environment variable OPENBLAS_NUM_THREADS to %d or lower\n", NUM_BUFFERS);
+  fprintf(stderr,"or set the environment variable OPENBLAS_NUM_THREADS to %d or lower\n", MAX_CPU_NUMBER);
   memory_overflowed=1;
   new_release_info = (struct release_t*) malloc(512*sizeof(struct release_t));
   newmemory = (struct newmemstruct*) malloc(512*sizeof(struct newmemstruct));
```

@martin-frbg what do you think?

Also, I am seeing a segfault on cleanup here:

```
(gdb) bt
#0  0x00007f916c0007e0 in ?? ()
#1  0x00000000062dbfea in blas_shutdown () at memory.c:3198
#2  0x0000000000406c34 in gotoblas_quit () at memory.c:3404
#3  0x00007f9aabbad843 in _dl_fini () from /lib64/ld-linux-x86-64.so.2
#4  0x00007f9aab28cb79 in __run_exit_handlers () from /lib64/libc.so.6
#5  0x00007f9aab28cd0a in exit () from /lib64/libc.so.6
#6  0x00007f9aab274254 in __libc_start_main () from /lib64/libc.so.6
#7  0x0000000000406cfa in _start () at ../sysdeps/x86_64/start.S:120
```

In our case OpenBLAS routines are called from either the main thread and then expected to parallelise automatically AND we have OpenMP parallel sections which concurrently call `dgemm` on independent blocks.

And if built with `NUM_THREADS=64` and run with `OMP_NUM_THREADS=256` I see random segfaults during `dgemm` (called from inside OMP threads) originating from `memory.c` when checking whether `newmemory` is used (second line in the example below):

```
#if defined(USE_OPENMP)
      if (!newmemory[position-NUM_BUFFERS].used) {
        blas_lock(&newmemory[position-NUM_BUFFERS].lock);
#endif
```

`OMP_STACKSIZE` is set to `1G`.

**Comment by martin-frbg** [comment]
There appears to be a race condition in that recovery path (#4216) but if you get there it means you would have seen an abort with earlier versions and really should rebuild OpenBLAS with a NUM_THREADS value that is at least as large as the number of threads you expect your code to exercise. (Guess you are right about MAX_CPU_NUMBER here, somehow did not anticipate the case with a runtime OMP_NUM_THREADS being that much bigger - and it would probably have been clamped - unintentionally - to a smaller value in 0.3.23 and earlier)
