### ISSUE TITLE
Ominous comment in symcopy.h

### ISSUE THREAD

**Issue by TiborGY** [xianyi/OpenBLAS#4223]
Looking through some source files, I have found an ominous comment in symcopy.h:

https://github.com/xianyi/OpenBLAS/blob/6bc079687fc09546d02e08951494c51baa9a5535/symcopy.h#L39C23-L39C24

This dates back to GotoBLAS, and the file has not seen any meaningful changes since then.
Does anyone have a guess what Goto et. al could have meant by "completely wrong", or is it lost to history?

The functions defined in it are getting used in kernel/generic/symv_k.c so they are certainly working to some extent.
I can try carefully reading the code in symcopy.h, to figure out if I can see any potential problems, but I am asking in case someone already knows.

**Comment by martin-frbg** [comment]
No errors have been traced back to this in about 20 years, so I am inclined to read it as "this works, but it is a lot less elegant than I think it could be". Given that there is next to no development history from Goto's time(apart from research papers and release tarballs), it is even conceivable that he did rewrite whatever part it was that worried him, but did not want (or remember) to remove the comment right away

**Comment by TiborGY** [comment]
Thanks, I may go through the code anyways when I have the time.
