### ISSUE TITLE
Missing suffix  _64 for symbols related to gemmt

### ISSUE THREAD

**Issue by amontoison** [xianyi/OpenBLAS#4224]
I wanted to interface the function `gemmt` in Julia but remarked that the suffix `_64` at the end of the four symbols was missing.
OpenBLAS was compiled with the options `INTERFACE64=1` and `SYMBOLSUFFIX=64_`.
I only tested with the version 0.3.23. It could be fixed with the release 0.3.24.

**Comment by martin-frbg** [comment]
Definitely fixed in 0.3.24 , and the GEMMT implementation in 0.3.23 was incomplete anyway
