### ISSUE TITLE
openblas with sve

### ISSUE THREAD

**Issue by garadeaniket** [xianyi/OpenBLAS#4234]
how to check sve with openblas is enabled or not ?

**Comment by Mousius** [comment]
How did you build/acquire OpenBLAS?

**Comment by garadeaniket** [comment]
make TARGET=ARMV8SVE CC=gcc FC=gfortran , i use this make command

**Comment by Mousius** [comment]
That should build a library specifically built to use the SVE kernels; what leads you to question whether or not it's using SVE?

**Comment by garadeaniket** [comment]
I am not finding any sve specific registers(z0, p0) in the dissassembly of openblas function

**Comment by martin-frbg** [comment]
Which function is it you are looking at ? Not all BLAS kernels use SVE yet.

**Comment by garadeaniket** [comment]
i have tried with cblas_ddot , cblas_dgemm , cblas_dgemv functions

**Comment by garadeaniket** [comment]
currently which blas functions uses sve? how we can verify at register level?

**Comment by martin-frbg** [comment]
GEMV currently is the same old NEON kernel as used for older ARMV8-a, but DDOT and DGEMM are definitely implemented with SVE (DOT using C intrinsics, DGEMM assembly instructions). (see KERNEL.ARMV8SVE in kernel/arm64 in the source tree). Note that the cblas function itself is just a small C wrapper around the actual BLAS kernel used

**Comment by garadeaniket** [comment]
how to use sve for dgemm and ddot functions

**Comment by darshanp4** [comment]
if you are interested in to see if SVE kernel are calling then you can keep print statement at SVE kernel call. for example dot sve call : https://github.com/OpenMathLib/OpenBLAS/blob/develop/kernel/arm64/dot.c#L61C34-L61C34 you can see if sve kernel is called or not!

**Comment by martin-frbg** [comment]
Or for DGEMM, run under gdb and put a breakpoint on `dgemm_kernel`, then disassemble from there. It should look very much like https://github.com/OpenMathLib/OpenBLAS/blob/develop/kernel/arm64/dgemm_kernel_sve_v2x8.S (if you are using the current 0.3.24 release).

**Comment by garadeaniket** [comment]
> Or for DGEMM, run under gdb and put a breakpoint on `dgemm_kernel`, then disassemble from there. It should look very much like https://github.com/OpenMathLib/OpenBLAS/blob/develop/kernel/arm64/dgemm_kernel_sve_v2x8.S (if you are using the current 0.3.24 release).

and what about ddot and dgemv functions?

**Comment by martin-frbg** [comment]
ddot as darshanp4 wrote - but of course you could also set a breakpoint for ddot_kernel in gdb if you want to check at runtime without adding print statements.
For gemv, someone would need to write new code

**Comment by brada4** [comment]
You can cast gemv to reduced gemm and "use SVE"
