### ISSUE TITLE
Warning: a function declaration without a prototype is deprecated in all versions of C 

### ISSUE THREAD

**Issue by SAbdulah** [xianyi/OpenBLAS#4241]
I've encountered a warning during the compilation of OpenBLAS using clang. 

`Warning: a function declaration without a prototype is deprecated in all versions of C `

I want to resolve this warning because I rely on OpenBLAS in an R project, and it's essential to eliminate all warnings to submit my package to CRAN platform.

**Comment by rgommers** [comment]
These warnings were enabled in Clang 15, and it would indeed be nice to resolve them. I've just been doing that for SciPy, it's usually straightforward.

@SAbdulah it would be useful to post a more complete build log showing all the warnings in full, as well as the exact build setup you used (OS, compiler version, how you installed it).

**Comment by SAbdulah** [comment]
Thanks @rgommers, please check this for more details:
https://win-builder.r-project.org/incoming_pretest/MPCR_1.0_20230925_112714/Debian/00check.log

**Comment by martin-frbg** [comment]
I cannot make sense of some of the line numbers, maybe they refer to the preprocessed sources, but most if not all appear to be only generated with the non-default `-Wstrict-prototypes` where the source has `()` instead of `(void)`

**Comment by martin-frbg** [comment]
Updating all the `int (*function)()` in common_thread.h to the exact signatures is likely going to be a bit tedious...

**Comment by brada4** [comment]
You cannot clash with blas.f symbols in your project, nor have -march=native  build for rest of windows users.

https://github.com/r-devel/r-svn/tree/master/src/extra/blas

**Comment by martin-frbg** [comment]
will send a PR to address these tomorrow

**Comment by SAbdulah** [comment]
Thanks, @martin-frbg 

We still encounter similar warnings from various other functions.. Please check here: https://win-builder.r-project.org/incoming_pretest/MPCR_1.0_20231004_160705/Debian/00check.log

**Comment by martin-frbg** [comment]
I am working on the other half of the patch (mostly LAPACK, but also part of ctest) which has over 2000 affected files.

**Comment by brada4** [comment]
Package in question is here: https://cran.r-project.org/incoming/archive/MPCR_1.0.tar.gz
It fails CRAN formal requirement by virtue of all LAPACKE aborting entire program on malloc failure. While particular issue here is to be fixed, you should really re-target to existing libRblas.so which may be netlib, MKL, OpenBLAS, Flexiblas or update-alternatives depending on how user acquired R package, in the most default encounter it does not have CBLAS, LAPACKE, or single-precision support.
