### ISSUE TITLE
Cross-Compile OpenBLAS for RISCV 

### ISSUE THREAD

**Issue by srianvesh** [xianyi/OpenBLAS#4262]
I am trying to cross compile python-scipy using RISCV target. SCIPY requires OpenBLAS. so, i have been trying to cross-compile OpenBLAS. But unable to make it.   I could see that when i use make libs command then .a file gets generated. But scipy doesn't recognized the .a file. I am confused whether a .so file should be the output or .a file. please help me in cross-compiling to the target arch.

I am building on Ubuntu OS. My target is RISCV_GENERIC board.
I have installed riscv64-linux-gnu-gcc and riscv64-linux-gnu-gfortrantoolchains on ubuntu.

I am using the following command to make.

make TARGET=RISCV64_GENERIC CC=riscv64-linux-gnu-gcc FC=riscv64-linux-gnu-gfortran CXX=riscv64-linux-gnu-g++  CROSS=1 CFLAGS="-march=rv64 -mabi=lp64 -O2"
I am getting the following errors 
cc1: error: ‘-march=rv64’: first ISA subset must be ‘e’, ‘i’ or ‘g’
cc1: error: ABI requires ‘-march=rv64’
C Compiler (riscv64-linux-gnu-gcc) is something wrong.
cc1: error: ‘-march=rv64’: first ISA subset must be ‘e’, ‘i’ or ‘g’
cc1: error: ABI requires ‘-march=rv64’
C Compiler (riscv64-linux-gnu-gcc) is something wrong.
cc1: error: ‘-march=native’: ISA string must begin with rv32 or rv64
cc1: error: requested ABI requires ‘-march’ to subsume the ‘D’ extension
cc1: error: ABI requires ‘-march=rv64’
cc1: error: ‘-march=native’: ISA string must begin with rv32 or rv64
cc1: error: requested ABI requires ‘-march’ to subsume the ‘D’ extension
cc1: error: ABI requires ‘-march=rv64’
make: *** [Makefile.prebuild:80: getarch] Error 1
OpenBLAS: Detecting fortran compiler failed. Can only compile BLAS and f2c-converted LAPACK.
make[1]: Entering directory '/home/vboxuser/k510_build/OpenBLAS/interface'
make[1]: warning: -j5 forced in makefile: resetting jobserver mode.
.....................
ranlib ../../../libopenblas_nehalemp-r0.3.24.dev.a
make[3]: Leaving directory '/home/vboxuser/k510_build/OpenBLAS/lapack-netlib/LAPACKE/utils'
make[2]: Leaving directory '/home/vboxuser/k510_build/OpenBLAS/lapack-netlib/LAPACKE'
make[1]: Leaving directory '/home/vboxuser/k510_build/OpenBLAS/lapack-netlib'
make[1]: Entering directory '/home/vboxuser/k510_build/OpenBLAS/exports'
make[1]: warning: -j5 forced in makefile: resetting jobserver mode.
riscv64-linux-gnu-gcc -march=rv64 -mabi=lp64 -O2 -O2 -DSMALL_MATRIX_OPT -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DC_LAPACK -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=5 -DMAX_PARALLEL_NUMBER=1 -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.24.dev\" -msse3 -mssse3 -msse4.1 -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  -shared -o ../libopenblas_nehalemp-r0.3.24.dev.so \
-Wl,--whole-archive ../libopenblas_nehalemp-r0.3.24.dev.a -Wl,--no-whole-archive \
-Wl,-soname,libopenblas.so.0 -lm -lpthread -lm -lpthread
riscv64-linux-gnu-gcc: error: unrecognized command line option ‘-m64’
riscv64-linux-gnu-gcc: error: unrecognized command line option ‘-msse3’
riscv64-linux-gnu-gcc: error: unrecognized command line option ‘-mssse3’
riscv64-linux-gnu-gcc: error: unrecognized command line option ‘-msse4.1’
make[1]: *** [Makefile:195: ../libopenblas_nehalemp-r0.3.24.dev.so] Error 1
make[1]: Leaving directory '/home/vboxuser/k510_build/OpenBLAS/exp

[openBLAS_error_131023.txt](https://github.com/OpenMathLib/OpenBLAS/files/12889685/openBLAS_error_131023.txt)
[openBLAS_make.inc.txt](https://github.com/OpenMathLib/OpenBLAS/files/12889688/openBLAS_make.inc.txt)

**Comment by rgommers** [comment]
> SCIPY requires OpenBLAS

I'll note that that is not a hard requirements; any BLAS/LAPACK library will work. E.g., to use plain `libblas`/`liblapack`, use:
```
pip install scipy -C-Dblas=blas -C-Dlapack=lapack
```
Your `pip` should be version >=23.1 for that. Cross compiling is a little trickier - there's some docs on that at http://scipy.github.io/devdocs/building/cross_compilation.html.

Your immediate problem seems to be with your cross-compilation toolchain + the `-march=rv64` flag though. Cross-compiling OpenBLAS is easier than cross-compiling SciPy, so I'd try to finish a cross OpenBLAS build and ensure that that toolchain works.

You should be able to get past this problem by using one of the given `-march=ISA-string` options at https://gcc.gnu.org/onlinedocs/gcc/RISC-V-Options.html, as hinted at by the first error:
```
cc1: error: ‘-march=rv64’: first ISA subset must be ‘e’, ‘i’ or ‘g’
```

**Comment by martin-frbg** [comment]
Try with `-march=rv64g` instead of just rv64, add HOSTCC pointing to your native compiler (e.g. HOSTCC=gcc), and make sure that your cross compiler (especially the gfortran part) are actually in your PATH (or enter the full path on the CC= and FC=)

**Comment by srianvesh** [comment]
Thanks for the prompt response. 
have tried 
make TARGET=RISCV64_GENERIC CC=riscv64-linux-gnu-gcc FC=riscv64-linux-gnu-gfortran CXX=riscv64-linux-gnu-g++  CROSS=1 CFLAGS="-march=rv64g -mabi=lp64 -O2" 
but still gets 
cc1: error: ‘-march=native’: ISA string must begin with rv32 or rv64
cc1: error: requested ABI requires ‘-march’ to subsume the ‘D’ extension
cc1: error: ABI requires ‘-march=rv64’
cc1: error: ‘-march=native’: ISA string must begin with rv32 or rv64
cc1: error: requested ABI requires ‘-march’ to subsume the ‘D’ extension
cc1: error: ABI requires ‘-march=rv64’
make: *** [Makefile.prebuild:80: getarch] Error 1
OpenBLAS: Detecting fortran compiler failed. Can only compile BLAS and f2c-converted LAPACK.
.............
riscv64-linux-gnu-gcc -march=rv64e -mabi=lp64 -O2 -O2 -DSMALL_MATRIX_OPT -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DC_LAPACK -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=5 -DMAX_PARALLEL_NUMBER=1 -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.24.dev\" -msse3 -mssse3 -msse4.1 -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  -shared -o ../libopenblas_nehalemp-r0.3.24.dev.so \
-Wl,--whole-archive ../libopenblas_nehalemp-r0.3.24.dev.a -Wl,--no-whole-archive \
-Wl,-soname,libopenblas.so.0 -lm -lpthread -lm -lpthread
riscv64-linux-gnu-gcc: error: unrecognized command line option ‘-m64’
riscv64-linux-gnu-gcc: error: unrecognized command line option ‘-msse3’
riscv64-linux-gnu-gcc: error: unrecognized command line option ‘-mssse3’
riscv64-linux-gnu-gcc: error: unrecognized command line option ‘-msse4.1’
make[1]: *** [Makefile:195: ../libopenblas_nehalemp-r0.3.24.dev.so] Error 1
make[1]: Leaving directory '/home/vboxuser/k510_build/OpenBLAS/exports'
make: *** [Makefile:134: shared] Error 2
[openBLAS_error_131023_i2.txt](https://github.com/OpenMathLib/OpenBLAS/files/12890067/openBLAS_error_131023_i2.txt)

**Comment by srianvesh** [comment]
have tried
make TARGET=RISCV64_GENERIC CC=riscv64-linux-gnu-gcc FC=riscv64-linux-gnu-gfortran CXX=riscv64-linux-gnu-g++  CROSS=1 CFLAGS="-march=rv64i -mabi=lp64 -O2" HOSTCC=gcc
Now arch related errors are gone. but still fails when generating .so file.

make[1]: Entering directory '/home/vboxuser/k510_build/OpenBLAS/exports'
make[1]: warning: -j5 forced in makefile: resetting jobserver mode.
riscv64-linux-gnu-gcc -march=rv64i -mabi=lp64 -O2 -O2 -DMAX_STACK_ALLOC=2048 -Wall -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=5 -DMAX_PARALLEL_NUMBER=1 -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.24.dev\" -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  -shared -o ../libopenblas_riscv64_genericp-r0.3.24.dev.so \
-Wl,--whole-archive ../libopenblas_riscv64_genericp-r0.3.24.dev.a -Wl,--no-whole-archive \
-Wl,-soname,libopenblas.so.0 -lm -lpthread -lgfortran -lm -lpthread -lgfortran
/usr/lib/gcc-cross/riscv64-linux-gnu/9/../../../../riscv64-linux-gnu/bin/ld: ../libopenblas_riscv64_genericp-r0.3.24.dev.a(saxpy.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/riscv64-linux-gnu/9/../../../../riscv64-linux-gnu/bin/ld: ../libopenblas_riscv64_genericp-r0.3.24.dev.a(saxpy.o): Relocations in generic ELF (EM: 62)
/usr/lib/gcc-cross/riscv64-linux-gnu/9/../../../../riscv64-linux-gnu/bin/ld: ../libopenblas_riscv64_genericp-r0.3.24.dev.a(saxpy.o): error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:195: ../libopenblas_riscv64_genericp-r0.3.24.dev.so] Error 1
make[1]: Leaving directory '/home/vboxuser/k510_build/OpenBLAS/exports'
make: *** [Makefile:134: shared] Error 2


[openBLAS_error_131023_i3.txt](https://github.com/OpenMathLib/OpenBLAS/files/12890127/openBLAS_error_131023_i3.txt)

**Comment by martin-frbg** [comment]
Did you do `make clean` before retrying ?

**Comment by srianvesh** [comment]
After make clean
i am getting the following error
make TARGET=RISCV64_GENERIC CC=riscv64-linux-gnu-gcc FC=riscv64-linux-gnu-gfortran CXX=riscv64-linux-gnu-g++  CROSS=1 CFLAGS="-march=rv64i -mabi=lp64 -O2" HOSTCC=gcc
make[1]: Entering directory '/home/vboxuser/k510_build/OpenBLAS/interface'
make[1]: warning: -j5 forced in makefile: resetting jobserver mode.
riscv64-linux-gnu-gcc -march=rv64i -mabi=lp64 -O2 -O2 -DMAX_STACK_ALLOC=2048 -Wall -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=5 -DMAX_PARALLEL_NUMBER=1 -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.24.dev\" -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME=saxpy -DASMFNAME=saxpy_ -DNAME=saxpy_ -DCNAME=saxpy -DCHAR_NAME=\"saxpy_\" -DCHAR_CNAME=\"saxpy\" -DNO_AFFINITY -I.. -I. -UDOUBLE  -UCOMPLEX -c axpy.c -o saxpy.o
riscv64-linux-gnu-gcc -march=rv64i -mabi=lp64 -O2 -O2 -DMAX_STACK_ALLOC=2048 -Wall -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=5 -DMAX_PARALLEL_NUMBER=1 -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.24.dev\" -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME=sswap -DASMFNAME=sswap_ -DNAME=sswap_ -DCNAME=sswap -DCHAR_NAME=\"sswap_\" -DCHAR_CNAME=\"sswap\" -DNO_AFFINITY -I.. -I. -UDOUBLE  -UCOMPLEX -c swap.c -o sswap.o
riscv64-linux-gnu-gcc -march=rv64i -mabi=lp64 -O2 -O2 -DMAX_STACK_ALLOC=2048 -Wall -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=5 -DMAX_PARALLEL_NUMBER=1 -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.24.dev\" -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME=scopy -DASMFNAME=scopy_ -DNAME=scopy_ -DCNAME=scopy -DCHAR_NAME=\"scopy_\" -DCHAR_CNAME=\"scopy\" -DNO_AFFINITY -I.. -I. -UDOUBLE  -UCOMPLEX -c copy.c -o scopy.o
riscv64-linux-gnu-gcc -march=rv64i -mabi=lp64 -O2 -O2 -DMAX_STACK_ALLOC=2048 -Wall -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=5 -DMAX_PARALLEL_NUMBER=1 -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.24.dev\" -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME=sscal -DASMFNAME=sscal_ -DNAME=sscal_ -DCNAME=sscal -DCHAR_NAME=\"sscal_\" -DCHAR_CNAME=\"sscal\" -DNO_AFFINITY -I.. -I. -UDOUBLE  -UCOMPLEX -c scal.c -o sscal.o
riscv64-linux-gnu-gcc -march=rv64i -mabi=lp64 -O2 -O2 -DMAX_STACK_ALLOC=2048 -Wall -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=5 -DMAX_PARALLEL_NUMBER=1 -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.24.dev\" -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME=sdot -DASMFNAME=sdot_ -DNAME=sdot_ -DCNAME=sdot -DCHAR_NAME=\"sdot_\" -DCHAR_CNAME=\"sdot\" -DNO_AFFINITY -I.. -I. -UDOUBLE  -UCOMPLEX -c dot.c -o sdot.o
In file included from /usr/riscv64-linux-gnu/include/features.h:485,
                 from /usr/riscv64-linux-gnu/include/bits/libc-header-start.h:33,
                 from /usr/riscv64-linux-gnu/include/stdio.h:27,
                 from axpy.c:39:
/usr/riscv64-linux-gnu/include/gnu/stubs.h:8:11: fatal error: gnu/stubs-lp64.h: No such file or directory
    8 | # include <gnu/stubs-lp64.h>
      |           ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /usr/riscv64-linux-gnu/include/features.h:485,
                 from /usr/riscv64-linux-gnu/include/bits/libc-header-start.h:33,
                 from /usr/riscv64-linux-gnu/include/stdio.h:27,
                 from copy.c:39:
/usr/riscv64-linux-gnu/include/gnu/stubs.h:8:11: fatal error: gnu/stubs-lp64.h: No such file or directory
    8 | # include <gnu/stubs-lp64.h>
      |           ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /usr/riscv64-linux-gnu/include/features.h:485,
                 from /usr/riscv64-linux-gnu/include/bits/libc-header-start.h:33,
                 from /usr/riscv64-linux-gnu/include/stdio.h:27,
                 from swap.c:39:
/usr/riscv64-linux-gnu/include/gnu/stubs.h:8:11: fatal error: gnu/stubs-lp64.h: No such file or directory
    8 | # include <gnu/stubs-lp64.h>
      |           ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:823: saxpy.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from /usr/riscv64-linux-gnu/include/features.h:485,
                 from /usr/riscv64-linux-gnu/include/bits/libc-header-start.h:33,
                 from /usr/riscv64-linux-gnu/include/stdio.h:27,
                 from scal.c:39:
/usr/riscv64-linux-gnu/include/gnu/stubs.h:8:11: fatal error: gnu/stubs-lp64.h: No such file or directory
    8 | # include <gnu/stubs-lp64.h>
      |           ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:895: sswap.o] Error 1
make[1]: *** [Makefile:877: scopy.o] Error 1
make[1]: *** [Makefile:850: sscal.o] Error 1
In file included from /usr/riscv64-linux-gnu/include/features.h:485,
                 from /usr/riscv64-linux-gnu/include/bits/libc-header-start.h:33,
                 from /usr/riscv64-linux-gnu/include/stdio.h:27,
                 from dot.c:39:
/usr/riscv64-linux-gnu/include/gnu/stubs.h:8:11: fatal error: gnu/stubs-lp64.h: No such file or directory
    8 | # include <gnu/stubs-lp64.h>
      |           ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:796: sdot.o] Error 1
make[1]: Leaving directory '/home/vboxuser/k510_build/OpenBLAS/interface'
make: *** [Makefile:186: libs] Error 1
[openBLAS_error_131023_i4.txt](https://github.com/OpenMathLib/OpenBLAS/files/12890262/openBLAS_error_131023_i4.txt)

**Comment by srianvesh** [comment]
could find stubs-lp64d.h
/usr/riscv64-linux-gnu$ find . -name stubs-*.h
./include/gnu/stubs-lp64d.h

**Comment by srianvesh** [comment]
when i try
make TARGET=RISCV64_GENERIC CC=riscv64-linux-gnu-gcc FC=riscv64-linux-gnu-gfortran CXX=riscv64-linux-gnu-g++  CROSS=1 CFLAGS="-march=rv64i -mabi=lp64d -O2" HOSTCC=gcc
cc1: error: requested ABI requires ‘-march’ to subsume the ‘D’ extension
C Compiler (riscv64-linux-gnu-gcc) is something wrong.
cc1: error: requested ABI requires ‘-march’ to subsume the ‘D’ extension
C Compiler (riscv64-linux-gnu-gcc) is something wrong.
cc1: error: requested ABI requires ‘-march’ to subsume the ‘D’ extension
C Compiler (riscv64-linux-gnu-gcc) is something wrong.
make: *** [Makefile.prebuild:63: config.h] Error 1
Makefile.system:1526: Makefile.: No such file or directory
make: *** No rule to make target 'Makefile.'.  Stop.

**Comment by martin-frbg** [comment]
That last error tells that you need to use `-march=rv64d` when you set `-mabi=lp64d`

**Comment by srianvesh** [comment]
getting error:
make TARGET=RISCV64_GENERIC CC=riscv64-linux-gnu-gcc FC=riscv64-linux-gnu-gfortran CXX=riscv64-linux-gnu-g++  CROSS=1 CFLAGS="-march=rv64d -mabi=lp64d -O2" HOSTCC=gcc

cc1: error: ‘-march=rv64d’: first ISA subset must be ‘e’, ‘i’ or ‘g’
cc1: error: requested ABI requires ‘-march’ to subsume the ‘D’ extension
cc1: error: ABI requires ‘-march=rv64’
C Compiler (riscv64-linux-gnu-gcc) is something wrong.
cc1: error: ‘-march=rv64d’: first ISA subset must be ‘e’, ‘i’ or ‘g’
cc1: error: requested ABI requires ‘-march’ to subsume the ‘D’ extension
cc1: error: ABI requires ‘-march=rv64’
C Compiler (riscv64-linux-gnu-gcc) is something wrong.
cc1: error: ‘-march=rv64d’: first ISA subset must be ‘e’, ‘i’ or ‘g’
cc1: error: requested ABI requires ‘-march’ to subsume the ‘D’ extension
cc1: error: ABI requires ‘-march=rv64’
C Compiler (riscv64-linux-gnu-gcc) is something wrong.
make: *** [Makefile.prebuild:63: config.h] Error 1
Makefile.system:1526: Makefile.: No such file or directory
make: *** No rule to make target 'Makefile.'.  Stop.

**Comment by martin-frbg** [comment]
Probably something like `-march=rv64id` then, see e.g. https://www.sifive.com/blog/all-aboard-part-1-compiler-args (I wonder if you could simply leave out your CFLAGS and go with the defaults of your cross-compiler)

**Comment by srianvesh** [comment]
if i leave out CFLAGS then i am getting the following error..
make TARGET=RISCV64_GENERIC CC=riscv64-linux-gnu-gcc FC=riscv64-linux-gnu-gfortran CXX=riscv64-linux-gnu-g++  CROSS=1
cc1: error: ‘-march=native’: ISA string must begin with rv32 or rv64
cc1: error: requested ABI requires ‘-march’ to subsume the ‘D’ extension
cc1: error: ABI requires ‘-march=rv64’
cc1: error: ‘-march=native’: ISA string must begin with rv32 or rv64
cc1: error: requested ABI requires ‘-march’ to subsume the ‘D’ extension
cc1: error: ABI requires ‘-march=rv64’
make: *** [Makefile.prebuild:80: getarch] Error 1
Makefile.system:1526: Makefile.: No such file or directory
make: *** No rule to make target 'Makefile.'.  Stop.

**Comment by martin-frbg** [comment]
Ok, seems life was easier with the first generation of vendor compilers for riscv.  So does it work when you try with march=rv64id (or something more elaborate like march=rv64imafdc) ?

**Comment by srianvesh** [comment]
still error persists.
OpenBLAS$ make TARGET=RISCV64_GENERIC CC=riscv64-linux-gnu-gcc FC=riscv64-linux-gnu-gfortran CXX=  CROSS=1 CFLAGS="-march=rv64imafdc -mabi=lp64d -O2"
cc1: error: ‘-march=native’: ISA string must begin with rv32 or rv64
cc1: error: requested ABI requires ‘-march’ to subsume the ‘D’ extension
cc1: error: ABI requires ‘-march=rv64’
cc1: error: ‘-march=native’: ISA string must begin with rv32 or rv64
cc1: error: requested ABI requires ‘-march’ to subsume the ‘D’ extension
cc1: error: ABI requires ‘-march=rv64’
make: *** [Makefile.prebuild:80: getarch] Error 1
Makefile.system:1526: Makefile.: No such file or directory
make: *** No rule to make target 'Makefile.'.  Stop.

**Comment by brada4** [comment]
You need tp set HOSTCC.

**Comment by srianvesh** [comment]
did git clone again and then updated make.inc and then ran
make TARGET=RISCV64_GENERIC CC=riscv64-linux-gnu-gcc FC=riscv64-linux-gnu-gfortran CXX=riscv64-linux-gnu-g++ HOSTCC=gcc CROSS=1 
(i removed CFLAGS since error kept coming.)

OpenBLAS build complete. (BLAS CBLAS LAPACK LAPACKE)

  OS               ... Linux             
  Architecture     ... riscv64               
  BINARY           ... 64bit                 
  C compiler       ... GCC  (cmd & version : riscv64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0)
  Fortran compiler ... GFORTRAN  (cmd & version : GNU Fortran (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0)
  Library Name     ... libopenblas_riscv64_genericp-r0.3.24.dev.a (Multi-threading; Max num-threads is 5)

To install the library, you can run "make PREFIX=/path/to/your/installation install".

**Comment by srianvesh** [comment]
make install also gives OK.

OpenBLAS$ make TARGET=RISCV64_GENERIC CC=riscv64-linux-gnu-gcc FC=riscv64-linux-gnu-gfortran CXX=riscv64-linux-gnu-g++ HOSTCC=gcc CROSS=1 install PREFIX=./
make -f Makefile.install install
make[1]: Entering directory '/home/vboxuser/k510_build/OpenBLAS'
make[1]: warning: -j5 forced in makefile: resetting jobserver mode.
Generating openblas_config.h in .//include
Generating f77blas.h in .//include
Generating cblas.h in .//include
Copying LAPACKE header files to .//include
Copying the static library to .//lib
Copying the shared library to .//lib
PKGFILE=".//lib/pkgconfig/openblas.pc"
Generating openblas.pc in .//lib/pkgconfig
Generating OpenBLASConfig.cmake in .//lib/cmake/openblas
Generating OpenBLASConfigVersion.cmake in .//lib/cmake/openblas
Install OK!
make[1]: Leaving directory '/home/vboxuser/k510_build/OpenBLAS'

**Comment by srianvesh** [comment]
i have got openblas.pc and when i try to link it to the scipy i am getting error.

/home/vboxuser/.local/bin/meson setup build --cross-file=scipy_cross_config.ini

The Meson build system
Version: 1.2.2
Source dir: /home/vboxuser/k510_build/k510_buildroot/package/scipy
Build dir: /home/vboxuser/k510_build/k510_buildroot/package/scipy/build
Build type: cross build
Project name: SciPy
Project version: 1.12.0.dev0
C compiler for the host machine: riscv64-linux-gnu-gcc (gcc 9.4.0 "riscv64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0")
C linker for the host machine: riscv64-linux-gnu-gcc ld.bfd 2.34
C++ compiler for the host machine: riscv64-linux-gnu-g++ (gcc 9.4.0 "riscv64-linux-gnu-g++ (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0")
C++ linker for the host machine: riscv64-linux-gnu-g++ ld.bfd 2.34
Cython compiler for the host machine: cython (cython 3.0.3)
C compiler for the build machine: cc (gcc 9.4.0 "cc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0")
C linker for the build machine: cc ld.bfd 2.34
C++ compiler for the build machine: c++ (gcc 9.4.0 "c++ (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0")
C++ linker for the build machine: c++ ld.bfd 2.34
Cython compiler for the build machine: cython (cython 3.0.3)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Program python3 found: YES (/usr/bin/python3)
Found Pkg-config: NO
Run-time dependency python found: YES 3.8
Program cython found: YES (/home/vboxuser/.local/bin/cython)
Compiler for C supports arguments -Wno-unused-but-set-variable: YES 
Compiler for C supports arguments -Wno-unused-function: YES 
Compiler for C supports arguments -Wno-conversion: YES 
Compiler for C supports arguments -Wno-misleading-indentation: YES 
Library m found: YES
Fortran compiler for the host machine: riscv64-linux-gnu-gfortran (gcc 9.4.0 "GNU Fortran (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0")
Fortran linker for the host machine: riscv64-linux-gnu-gfortran ld.bfd 2.34
Compiler for Fortran supports arguments -Wno-conversion: YES 
Checking if "-Wl,--version-script" : links: YES 
Program pythran found: YES (/home/vboxuser/.local/bin/pythran)
Found CMake: NO
Run-time dependency xsimd found: NO (tried pkgconfig and cmake)
Run-time dependency threads found: YES
Library npymath found: YES
Library npyrandom found: YES
pybind11-config found: YES (/home/vboxuser/.local/bin/pybind11-config) 2.11.1
Run-time dependency pybind11 found: YES 2.11.1
Run-time dependency openblas found: NO (tried pkgconfig and cmake)
Run-time dependency openblas found: NO 

scipy/meson.build:159:9: ERROR: Dependency lookup for OpenBLAS with method 'pkgconfig' failed: Pkg-config binary for machine 1 not found. Giving up.

A full log can be found at /home/vboxuser/k510_build/k510_buildroot/package/scipy/build/meson-logs/meson-log.txt


[meson_output_error.txt](https://github.com/OpenMathLib/OpenBLAS/files/12893732/meson_output_error.txt)

[scipy_cross_config.ini.txt](https://github.com/OpenMathLib/OpenBLAS/files/12893716/scipy_cross_config.ini.txt)

**Comment by brada4** [comment]
Your OpenBLAS RC64 is built. Now you need to use pip with arch overrides to build scipy. Dozen unrelated products are helped with in respective forums, certainly not here.

**Comment by martin-frbg** [comment]
The error message "Pkg-config binary for machine 1 not found" suggests that you do not have the program "pkgconfig"
installed - this has nothing to do with OpenBLAS itself. (But I also notice that you appear to have told the "make install" to install itself into its own source/build directory, which is at least highly unusual (normally you'd choose something like /opt/OpenBLAS or /usr/local) and may mean that your openblas.pc will not be found by pkgconfig unless you put its location into the PKG_CONFIG_PATH variable)
