### ISSUE TITLE
detected architecture is Prescott on a recent CPU

### ISSUE THREAD

**Issue by jeromedockes** [xianyi/OpenBLAS#4267]
This causes the scikit-learn error [#27613](https://github.com/scikit-learn/scikit-learn/issues/27613)

```
python -m threadpoolctl -i scipy

[
  {
    "user_api": "blas",
    "internal_api": "openblas",
    "num_threads": 4,
    "prefix": "libopenblas",
    "filepath": "/home/jerome/miniconda3/envs/3.11/lib/libopenblasp-r0.3.24.so",
    "version": "0.3.24",
    "threading_layer": "pthreads",
    "architecture": "Prescott"
  }
]
```

`lscpu`
<details>
<pre>
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      46 bits physical, 48 bits virtual
Byte Order:                         Little Endian
CPU(s):                             20
On-line CPU(s) list:                0-19
Vendor ID:                          GenuineIntel
Model name:                         13th Gen Intel(R) Core(TM) i7-1370P
CPU family:                         6
Model:                              186
Thread(s) per core:                 2
Core(s) per socket:                 14
Socket(s):                          1
Stepping:                           2
CPU max MHz:                        5200.0000
CPU min MHz:                        400.0000
BogoMIPS:                           4377.60
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves avx_vnni dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req hfi umip pku ospke waitpkg gfni vaes vpclmulqdq tme rdpid movdiri movdir64b fsrm md_clear serialize pconfig arch_lbr ibt flush_l1d arch_capabilities
Virtualization:                     VT-x
L1d cache:                          544 KiB (14 instances)
L1i cache:                          704 KiB (14 instances)
L2 cache:                           11.5 MiB (8 instances)
L3 cache:                           24 MiB (1 instance)
NUMA node(s):                       1
NUMA node0 CPU(s):                  0-19
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected
</pre>
</details>

discussing with @ogrisel , we are wondering why the feature-based fallback strategy added in https://github.com/OpenMathLib/OpenBLAS/pull/3485 does not apply here

**Comment by martin-frbg** [comment]
I'm wondering too - unless the operating system disabled AVX/AVX2 support (or "something" set OPENBLAS_CORETYPE=PRESCOTT in the environment), it should have been mapped to Haswell.

**Comment by martin-frbg** [comment]
Looks like a missing "break" statement has (always had) the code fall through to the ancient "family 15" entry for Prescott when no match is found among family 6. Of course this did not matter back when the default fallback was Prescott anyway... (Also of note is that the compile-time cpu detection already recognizes the various Alder Lake types - I was relying on the feature-based fallback for DYNAMIC_ARCH myself)

**Comment by jeromedockes** [comment]
> Also of note is that the compile-time cpu detection already recognizes the various Alder Lake types

indeed I don't see the problem anymore if I compile OpenBLAS on my machine

**Comment by martin-frbg** [comment]
not sure how that meshes with ogrisel's fix on the scikit-learn side - are there two bugs, and the Prescott misdetection is just incidental, or is there something in the ancient BLAS kernels for Prescott that delivers a wrong result which then derails scikit-learn ?

**Comment by ogrisel** [comment]
I am fixing the scikit-learn bug that happens when OpenBLAS is used with the prescott architecture, but the fact that prescott is detected on this host is a bug in the OpenBLAS side by itself (when built with DYNAMIC_ARCH).

**Comment by martin-frbg** [comment]
understood, but my question is whether there is a deeper issue with the old Prescott kernels _in addition to the fact that they should not have been selected on an Alder Lake host_

**Comment by ogrisel** [comment]
They used to crash on non-memory aligned data as we already discussed in the past:

- https://github.com/OpenMathLib/OpenBLAS/issues/3453#issuecomment-977982062

I believe this root cause was never fixed, the problem only hidden by not falling back to PRESCOTT on recent CPUs.

**Comment by ogrisel** [comment]
But from now on this will never be a problem again in scikit-learn because since joblib 1.2.0 all memory mapped arrays are allocated in an aligned manner by default. In https://github.com/scikit-learn/scikit-learn/pull/27614 I clean-up the broken workaround code we had put in place in scikit-learn and just update joblib 1.2.0 as a minimum dependency instead.

**Comment by martin-frbg** [comment]
OK, so "only" the known alignment issue (which #4268 should sweep under the rug again). Thanks.
