### ISSUE TITLE
VisualStudio's findBLAS.cmake fails to locate a precompiled libopenblas when building SuiteSparse

### ISSUE THREAD

**Issue by Marshdweller** [xianyi/OpenBLAS#4273]
Hi all

I've been struggling with the combination Windows/OpenBLAS/Suitesparse/MS VisualStudio/CMake for several month already, so I finally decided to ask for help.

1) I build Suitesparse under Windowsx64 with MSVS. I download precompiled OpenBLASx64 binaries to a local directory and want to link Suitespase to it.

2) Suitesparse's CMakeLists.txt calls SuiteSparseBLAS.cmake, which it its turn calls `find_package(BLAS)`. It translates to a call to findBLAS.cmake (shipped with MSVS).

3) findBLAS.cmake fails to locate OpenBLAS (actually, it can be verified directly, without Suitesparse)

4) I experimented a lot with different options (BLA_VENDOR/ALLOW_64BIT_BLAS etc) and debugged findBLAS.cmake. So I am pretty confident that something wrong with the findBLAS.cmake logic. For example, findBLAS.cmake expects "64" in lib names, whereas the precompiled binaries are named simply "libopenblas". However, I suspect that there are more serious problems in the logic.

5)The only solution I found is to edit Suitesparse's cmake files, remove `find_package(BLAS)` call,and set everything manually:
```
set(BLAS_FOUND ON);
set(BLAS_LABRARIES ..);
..
```
Which is ugly of course.

6) Note that the "Config.cmake" files shipped with OpenBLAS are of little help, because `find_package()` looks for findXXX.cmake files first - and the file is there.

7) **The question: how to force findBLAS.cmake to locate precompiled OpenBLAS libraries, privided that `find_package(BLAS)` is called somewhere inside another library?**

**Comment by martin-frbg** [comment]
If the findBLAS.cmake really looks specifically for a libopenblas64, it probably expects a library built with the INTERFACE64=1 option to declare all integers as 64bit long rather than the standard 32bits to extend the range of numbers (addressable array elements) The provided binaries are built with standard 32bit integers only, I can see if I can find the time to build another package with INTERFACE64 for you. 
However it appears to me that using a "64bit" BLAS in SuiteSparse is still entirely optional and depends on the settings made in/with SuiteSparse_config - the ALLOW_64BIT_BLAS option you saw.

**Comment by Marshdweller** [comment]
@martin-frbg Thank you for your quick reply

You say "the provided binaries are x32", but I downloaded archive named "OpenBLAS-0.3.24-x64.zip" - it seems to be x64, right?

I think that the main problem with findBLAS.cmake is this call below. It actually performs the OpenBLAS search:

```
    check_blas_libraries(
      BLAS_LIBRARIES
      BLAS
      sgemm
      ""
      "${_blas_openblas_lib}"  //<---  this guy here is "openblas64"
      ""
      ""
      ""
      )
```

So you see, that all directories provided for `check_blas_libraries()` are empty. I looked inside `check_blas_libraries()` under debugger and discovered that the actual job is done with the call
```
        find_library(${_prefix}_${_lib_var}_LIBRARY  //<-- "BLAS_openblas64_LIBRARY"
          NAMES ${_library}  //<--- "openblas64"
          NAMES_PER_DIR  //<-- empty
          PATHS ${_extaddlibdir} //<--- "ENV;LIB"
          PATH_SUFFIXES ${_subdirs} //<--- empty
        )
```

No local directories are given to `find_library` function, apart from "ENV" and "LIB". After this call BLAS_openblas64_LIBRARY has value "BLAS_openblas64_LIBRARY-NOTFOUND".

**Comment by martin-frbg** [comment]
No, x32/x64 is a different thing altogether - this is not about 32bit platform, but about using a larger than usual type for integral numbers - "long long" instead of "long" in MSVC syntax.
I wonder where  the "openblas64" in _blas_openblas_lib comes from - from the SuiteSparse docs I would expect it to search for this variant only when ALLOW_64BIT_BLAS is set in Suitesparse_config

**Comment by Marshdweller** [comment]
> No, x32/x64 is a different thing altogether - this is not about 32bit platform, but about using a larger than usual type for integral numbers - "long long" instead of "long" in MSVC syntax. I wonder where the "openblas64" in _blas_openblas_lib comes from - from the SuiteSparse docs I would expect it to search for this variant only when ALLOW_64BIT_BLAS is set in Suitesparse_config

Ok, now I see. I use ALLOW_64BIT_BLAS=ON, and then it translates into BLA_SIZEOF_INTEGER=8 somewhere inside Suitesparse cmake files. If I change ALLOW_64BIT_BLAS=OFF, then BLA_SIZEOF_INTEGER=4, then findBLAS.cmake searches for "openblas", and then fails anyway.

So the problem persists.

**Comment by martin-frbg** [comment]
So this probably reduces to where did you install (unpack) the zip of OpenBLAS, and which locations does FindBLAS.cmake check - and problems finding BLAS appear to be quite a popular question on the Usage forum at discourse.cmake.org. Incidentally, which version of VisualStudio (one thread there suggested using at least VS 2017 15.0 to have detection work), and have you tried running the cmake build with `--debug-find` ?

**Comment by Marshdweller** [comment]
@martin-frbg 

You were right in that it boiles down to where `find_library` search for the libraries. After one another investigation I found the following solution.

1. Set BLA_VENDOR="OpenBLAS"  ALLOW_64BIT_BLAS="OFF" (it is also possible to set ALLOW_64BIT_BLAS="ON" **AND** ask @martin-frbg to compile openblas64.lib)
2. Specify additional CMake search directory by setting CMAKE_LIBRARY_PATH="C: ../OpenBLAS-0.3.24-x64/lib"  (path to the *.lib)
3. Rename precompiled binary by removing leading "lib" from file names ( "libopenblas.lib" ->"openblas.lib" )

If someone wants to debug it in the future, I extracted a piece of code from findBLAS.cmake that actually performs the search when find_package(BLAS) with BLA_VENDOR="OpenBLAS" is called.

```
        find_library(BLAS_openblas_LIBRARY #  or BLAS_openblas64_LIBRARY
          NAMES openblas  #<---  or "openblas64"
          ""
          PATHS "LIB;ENV"
          PATH_SUFFIXES ""
        )
```

Normally after the call it should be BLAS_openblas_LIBRARY="C:/.../openblas.lib"

PS I use Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.6.5

**Comment by martin-frbg** [comment]
so the main problem on OpenBLAS' side is the unwanted Linux-like "lib" prefix on the library files ?  Not sure if we've alwayss had it (and nobody bothered to complain) or if it crept in during some rearrangement of the build files,  but if its only purpose is to cause trouble I'll remove it for future versions

**Comment by Marshdweller** [comment]
"so the main problem on OpenBLAS' side is the unwanted Linux-like "lib" prefix on the library files" - yes. Not that serious:) I think that the issue can be marked as resolved. Thank you.

**Comment by brada4** [comment]
See the buttons below ....

**Comment by martin-frbg** [comment]
I just noticed OpenCV changed their own version of  FindBLAS.cmake to add "libopenblas" as a name variant to look for. On the other hand, having the Windows libraries named with the Unix-style "lib" prefix appears to have been a (mis?)feature even in the original GotoBLAS2, and as far as I can tell, distributors like MSYS2 do not appear to patch that out(?)
