### ISSUE TITLE
MAX_THREADS/NUM_THREADS not propagated to Makefile.conf_last

### ISSUE THREAD

**Issue by StefanBruens** [xianyi/OpenBLAS#4275]
Makefile.install uses MAX_THREADS when writing the pkgconfig file, and falls back to the build host core/thread count when "NUM_THREADS" is not passed to `make install`.

NUM_THREADS is not written to Makefile.conf_last, contrary to e.g. DYNAMIC_ARCH. This is probably an oversight.

There are other options which apparently are not saved when building the library (i.e. everything related to install directories), and are evaluated by `make install`/`Makefile.install`, but there is unfortunately no documentation when each option is evaluated - by `make`, `make install`, or both.

It is probably save to pass all options to both calls, but this is not what the current documentation suggests or uses in the examples.

**Comment by martin-frbg** [comment]
This is probably far from ideal, but the output produced at the end of the build says to repeat all the command  line arguments given to `make` in the `make install`. You are certainly right that this should be made clearer in the README

**Comment by martin-frbg** [comment]
(And I do not recall offhand why it has to be like this - probably related to the cursed recursive operation of the makefiles)

**Comment by StefanBruens** [comment]
Another variable which is not saved correctly is "CORE", it is exported as TARGET to Makefile.conf_last.

The  pkgconfig file then contains "UNKNOWN".

https://github.com/martin-frbg/OpenBLAS/blob/d11e7340024e919bde0dad4e8945ac86cf5fd06b/Makefile.install#L181
