### ISSUE TITLE
Cross Compile

### ISSUE THREAD

**Issue by showaker** [xianyi/OpenBLAS#4281]
I use command "make BINARY=64 CC=aarch64-linux-gnu-gcc FC=aarch64-linux-gnu-gfortran HOSTCC=gcc TARGET=ARMV8
" to make a ARMV8 .so on ubuntu , get some wrong information as following: ans.o lapacke_make_complex_float.o lapacke_make_complex_double.o
ar: `u' 修饰符被忽略，因为 `D' 为默认（参见 `U'）
aarch64-linux-gnu-ranlib ../../../libopenblas_armv8p-r0.3.24.dev.a
make[3]: 离开目录“/home/showaker/htwa/OpenBLAS/lapack-netlib/LAPACKE/utils”
make[2]: 离开目录“/home/showaker/htwa/OpenBLAS/lapack-netlib/LAPACKE”
make[1]: 离开目录“/home/showaker/htwa/OpenBLAS/lapack-netlib”
make[1]: 进入目录“/home/showaker/htwa/OpenBLAS/exports”
aarch64-linux-gnu-gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -DF_INTERFACE_GFORT -fPIC -DNO_SVE -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DMAX_PARALLEL_NUMBER=1 -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.24.dev\" -march=armv8-a -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  -shared -o ../libopenblas_armv8p-r0.3.24.dev.so \
-Wl,--whole-archive ../libopenblas_armv8p-r0.3.24.dev.a -Wl,--no-whole-archive \
-Wl,-soname,libopenblas.so.0 -lm -lpthread -lgfortran -lm -lpthread -lgfortran
/usr/lib/gcc-cross/aarch64-linux-gnu/7/../../../../aarch64-linux-gnu/bin/ld: ../libopenblas_armv8p-r0.3.24.dev.a(saxpy.o)：普通ELF重定位（M: 62）
/usr/lib/gcc-cross/aarch64-linux-gnu/7/../../../../aarch64-linux-gnu/bin/ld: ../libopenblas_armv8p-r0.3.24.dev.a(saxpy.o)：普通ELF重定位（M: 62）
../libopenblas_armv8p-r0.3.24.dev.a(saxpy.o): 无法添加符号: 文件格式错误
collect2: error: ld returned 1 exit status
Makefile:195: recipe for target '../libopenblas_armv8p-r0.3.24.dev.so' failed
make[1]: *** [../libopenblas_armv8p-r0.3.24.dev.so] Error 1
make[1]: 离开目录“/home/showaker/htwa/OpenBLAS/exports”
Makefile:136: recipe for target 'shared' failed
make: *** [shared] Error 2

Could anyone tell me what's wrong with it?

**Comment by martin-frbg** [comment]
This looks like you may have some x86_64 objects mixed in with the aarch64 ones, did you perhaps start a normal compile first (or forget one of the CC or HOSTCC options) and then switched to the cross-compile without doing `make clean` in between ?

**Comment by showaker** [comment]
Cool! I truely started a normal compile first without doing  `make clean` , thanks so much!
