### ISSUE TITLE
kernel/arm64/gemm_ncopy_sve_v1x8.c:30:10: fatal error: arm_sve.h: No such file or directory

### ISSUE THREAD

**Issue by puyuanOT** [xianyi/OpenBLAS#4284]
![image](https://github.com/OpenMathLib/OpenBLAS/assets/121119211/4a4ed285-cce0-4d8a-8d49-05695dec2bad)
Got this error when using AWS EC2 c7d clusters, whose cpu is [AWS Graviton3](https://en.wikipedia.org/wiki/AWS_Graviton)

**Comment by darshanp4** [comment]
what is the build command used?

**Comment by martin-frbg** [comment]
What compiler (and version) please ? Looks like it is too old to support ARM SVE extensions

**Comment by puyuanOT** [comment]
> What compiler (and version) please ? Looks like it is too old to support ARM SVE extensions

Yeah it was the problem of gcc version, solved the issue after upgrading it.
