### ISSUE TITLE
Issue while Debugging cblas_dsymm();

### ISSUE THREAD

**Issue by Jai-40** [xianyi/OpenBLAS#4292]
While debuggin cblas_dsymm() I am getting the error " gdb
On entry to DSYMM parameter number 1 had an illegal value
61 return 0;" Please check it once.

Variable Declaration:
**double *A, B, C;
int m, n, k, i, j;
int side=CblasLeft, uplo=CblasUpper;
double alpha, beta;
printf("enter the value of m : ");
scanf ("%d",&m);
alpha = 1.0; beta = 0.0;

printf("enter the value of m : ");
(gdb) n
14 scanf ("%d",&m);
(gdb) n
enter the value of m : 2
22 A = (double )malloc( mmsizeof( double ));
(gdb)
23 B = (double )malloc( mmsizeof( double ) );
(gdb)
24 C = (double )malloc( mm*sizeof( double ) );
(gdb)
39 clock_gettime(CLOCK_REALTIME, &begin);
(gdb)
40 cblas_dsymm(CblasColMajor, side, uplo, m, m, alpha, A, m, B, m, beta, C, m);
(gdb) step
cblas_dsymm (order=order@entry=CblasColMajor, Side=Side@entry=76, Uplo=Uplo@entry=85, m=2, n=2, alpha=alpha@entry=1,
a=a@entry=0x425bf0, lda=2, b=b@entry=0x425c20, ldb=2, beta=beta@entry=0, c=c@entry=0x425c50, ldc=2) at symm.c:273
273 args.alpha = (void *)α
(gdb)
281 args.ldc = ldc;
(gdb)
287 if (order == CblasColMajor) {
(gdb)
288 if (Side == CblasLeft) side = 0;
(gdb)
289 if (Side == CblasRight) side = 1;
(gdb)
291 if (Uplo == CblasUpper) uplo = 0;
(gdb)
292 if (Uplo == CblasLower) uplo = 1;
(gdb)
296 args.m = m;
(gdb)
301 if (!side) {
(gdb)
312 args.a = (void *)b;
(gdb)
315 args.lda = ldb;
(gdb)
318 if (args.lda < MAX(1, args.m)) info = 9;
(gdb)
319 if (args.ldb < MAX(1, args.n)) info = 7;
(gdb)
322 if (args.n < 0) info = 4;
(gdb)
323 if (args.m < 0) info = 3;
(gdb)
365 if (uplo < 0) info = 2;
(gdb)
366 if (side < 0) info = 1;
(gdb)
325 if (side < 0) info = 1;
(gdb)
328 if (order == CblasRowMajor) {
(gdb)
370 BLASFUNC(xerbla)(ERROR_NAME, &info, sizeof(ERROR_NAME));
(gdb)
__xerbla (message=message@entry=0xffffbe6602b8 "DSYMM ", info=info@entry=0xffffffffc1f4, length=length@entry=7)
at xerbla.c:58
58 printf(MSGFMT,
(gdb)
** On entry to DSYMM parameter number 1 had an illegal value
61 return 0;
(gdb)
cblas_dsymm (order=order@entry=CblasColMajor, Side=Side@entry=76, Uplo=Uplo@entry=85, m=,
n=, alpha=, alpha@entry=1, a=a@entry=0x425bf0, lda=,
b=b@entry=0x425c20, ldb=2, beta=, beta@entry=0, c=c@entry=0x425c50, ldc=2) at symm.c:371
371 return;
(gdb) step
main () at dsymm.c:44
44 clock_gettime(CLOCK_REALTIME, &end);

**Comment by martin-frbg** [comment]
What does your code look like, did you `#include cblas.h` and use the `CblasLeft` as defined there ? The gdb trace looks as if you specified a verbatim 'L' character like you would when calling DSYMM without the CBLAS interface, e.g. from Fortran.
This does not match the `enum` value from CBLAS that is expected here, which is why you get the INFO=1 error for "the value of side was neither left nor right"
