### ISSUE TITLE
SVE Implementation

### ISSUE THREAD

**Issue by Jai-40** [xianyi/OpenBLAS#4296]
Does HERK/HER2K uses any other routines internally for sve ? I don't see dedicated kernels for these in kernel/arm64/KERNEL.ARMV8SVE.
I don't see any kernels for level 2 routines, does this mean non of the  level 2 routine has sve implementation?

**Comment by martin-frbg** [comment]
Yes, as I answered in #4291. Level 2 functions do not have SVE implementations yet.

**Comment by Jai-40** [comment]
> Yes, as I answered in #4291. Level 2 functions do not have SVE implementations yet.

HERK/HER2K  are level 3 routines right? Do they also use other SVE implemented routines internally.

**Comment by martin-frbg** [comment]
Yes. See in drivers/level3 how it is done

**Comment by Jai-40** [comment]
1)Could you please confirm that whether all the routines of LEVEL 2 also has implementation of sve or not. 
2) I see for dot product dot_kernel_sev.c is written in kernel/arm64 but while debugging the dot product example i don't see this function called by dot.c.

**Comment by Jai-40** [comment]
> 1)Could you please confirm that whether all the routines of LEVEL 1 also has implementation of sve or not. 
2) I see for dot product dot_kernel_sev.c is written in kernel/arm64 but while debugging the dot product example i don't see this function called by dot.c.

**Comment by brada4** [comment]
L1 is bound to memory access. Very low power cpu may not be able to do 2 flops per cacheline access, average cpu can do like 50 flops while next cache line is pre-fetched. Yhere is absolutely no effect in result time in bulking dozen memory accesses for a single simd instruction.

**Comment by Jai-40** [comment]
Does that mean sve is not implemented for level 1?

**Comment by martin-frbg** [comment]
The SVE kernel for SDOT/DDOT is only used (1) when your compiler supports SVE and (2) when the x and y increments are both 1 - see for yoursefl in kernel/arm64/dot.c.  OpenBLAS is a developing project with a small number of contributors, someone needs to write, test and benchmark the kernels, and using SVE will not necessarily make _every_ function magically faster.

**Comment by Jai-40** [comment]
If we want to implement sve in level 1 , Which all kernel functions need to be rewritten/replaced with sve under kernel/arm64.

**Comment by Jai-40** [comment]
If we want to implement sve in level 1 , Which all kernel functions need to be rewritten/replaced with sve under kernel/arm64.

**Comment by brada4** [comment]
You can research your study topics with google.
