### ISSUE TITLE
gemm.c of driver and interface.

### ISSUE THREAD

**Issue by Jai-40** [xianyi/OpenBLAS#4299]
I see that gemm.c function is implemented in both driver and interface. While debugging the gemm.c function calls level3.c which is included in gemm.c function of driver. What is the difference between these interface and driver.

**Comment by martin-frbg** [comment]
The code in "interface" is just that - it takes the BLAS/CBLAS call, does some setup and calls the driver code which does more setup before calling the actual kernel (in parallel if desired). There is some documentation in the wiki, for details read Kazushige Goto's seminal papers. (Please stop creating issue tickets for every question that comes to your mind, this is not an interactive CS101 class - there are simply no resources for that)
