### ISSUE TITLE
blas level2 optimization using sve

### ISSUE THREAD

**Issue by Juliya32** [xianyi/OpenBLAS#4301]
Dear,

In openblas level 3 (matrix matrix multiplication like dgemm,sgemm,cgemm)blas functions are optimized with sve codes. I want to use sve(Scalable Vector Extension) in level 2 blas functions(matrix vector multiplication like dgemv , cgemv, sgemv).But when i searched only level3.c is available in driver folder. when i debug the dgemv function it internally  calling the gemv.c function under interface folder. but that is not an optimized code .While debugging dgemm blas function it internally calls gemm.c  and level3.c functions under the driver folder  that is already optimized with sve. so From where i get the leve2.c code or is there any other options for optimizing blas level 2 codes using sve .How can i solve the issue?

**Comment by martin-frbg** [comment]
Please look in driver/level2 for level 2 driver codes. But there should be no need to change anything in that folder, the optimized BLAS kernels are in kernel/arm64 - you would need to rewrite/replace the gemv_n and gemv_t kernels listed in KERNEL.ARMV8SVE there. The kernel/arm folder (for ARMV7) has generic C codes for reference.

**Comment by brada4** [comment]
What issue you are trying to solve? You just described normal control flow. Yes, it works like you see.

**Comment by Juliya32** [comment]
I want to apply sve  in all the routines of  level 2   tmartin-frbg told to rewrite/replace the gemv_n and gemv_t kernels listed in KERNEL.ARMV8SVE for level 2 routines. 
1)These kernel functions are written in assembly language, 
will it work if I change the assembly code and apply sve in it  ? And does modifying these two kernel functions will implement sve in all routines of level 2 ?
2)Is there any other way to implement sve in all routines of level 2 without modifying the assembly code?

**Comment by brada4** [comment]
Since you use 2 accounts to ask same questions - go ask google.

**Comment by martin-frbg** [comment]
You can also use C with sve intrinsics if you prefer that over assembly - and maybe you can even get the compiler to use some sve instructions if you just take the plain C kernels from the "arm" directory", but I doubt it. Modifying the gemv kernels will implement sve in those routines that use gemv internally (these will have GEMV_N and/or GEMV_T in their code in driver/level2), but there are also some like syr that build on the respective axpy kernel (macro name AXPYU).
