### ISSUE TITLE
Is -lpthread needed when linking if I want to get multi-thread accelation?

### ISSUE THREAD

**Issue by ShadowBlack666** [xianyi/OpenBLAS#4319]
I'm a novice. After read wiki and some issues, I think that openblas functions will generate threads internally and automatically when them called in single thread. Is my opinion right? 
if my opinion is right, then if it's need to add "-lpthread" flag when linking? 
precondition is : I use "make" without any argument and let it detect by itself, and I get a version with max threads 32.

**Comment by martin-frbg** [comment]
All multithreading in OpenBLAS is based on pthreads (or OpenMP, but that is usually implemented on top of pthreads on Linux and BSD at least). If you do a single-threaded build (USE_THREAD=0) then OpenBLAS will simply assume there is only one cpu core and there will be no partitioning of workloads. So for multithreaded acceleration you will always need to link with `-lpthread`.

**Comment by brada4** [comment]
Makefile.rule contains all parameters, namely target and cpu number are detected from build environment. If you want to redist you might want to change that via command line DYNAMIC_ARCH=1 or appending same to named file...
Defaults means you run single thread, openblas does the rest.

**Comment by ShadowBlack666** [comment]
Thank you very much!
