### ISSUE TITLE
Support for compiling and linking with OpenMP in CMake

### ISSUE THREAD

**Issue by gkaf89** [xianyi/OpenBLAS#4321]
I exploring using the CMake scripts instead of the Makefiles. I noticed that in the CMake files the variable `USE_OPENMP` is used. Is it enough to set `USE_OPENMP=1`, or is the feature not fully supported yet in CMake builds?

**Comment by martin-frbg** [comment]
Yes `-DUSE_OPENMP=1` is sufficient and should be fully supported.

**Comment by gkaf89** [comment]
Thank you!
