### ISSUE TITLE
dgemm performance degradation on ARM NEOVERSEV1 with lower P*Q 

### ISSUE THREAD

**Issue by darshanp4** [xianyi/OpenBLAS#4323]
I see about 2-10% perf degradation in OpenBLAS/gemm.c benchmark on single core ( also seen on multicore) of graviton3 machine. 
This is the issue due to P*Q used in NEOVERSEV1 is not comparable to what it’s  L2 cache size (which is 1MB).
from the faq of OpenBLAS  : A general rule of thumb for selecting a starting point seems to be that PxQ is about half the size of L2 cache.

![image](https://github.com/OpenMathLib/OpenBLAS/assets/129051745/b14837de-be1d-4f1a-88d1-c537d54e2166)

So may be we should update the NEOVERSEV1 param P*Q as per the  L2 cache size.

Or can anyone help in understanding why NEOVERSEV1 P*Q is kept that low.

**Comment by martin-frbg** [comment]
As far as I can tell from the git history, it could be simply that the entries were copied from the very conservative ones for  more generic armv8 chips (which may be used in small appliances with little L2) when initial support was added. Afterwards, providing SVE kernels was a bigger initial win than fine-tuning the GEMM parameters, but this should indeed be an attractive fix.

**Comment by darshanp4** [comment]
Thanks for your comment will add fix for this after further evaluating preferable settings for NEOVERSEV1.

**Comment by martin-frbg** [comment]
BTW if you look for e.g. TSV110 in param.h, there is a very questionable hack already where bigger PQ are used when the number of cores is large enough to be sure it is not a primitive mobile phone

**Comment by darshanp4** [comment]
@martin-frbg  can you please help to review this https://github.com/OpenMathLib/OpenBLAS/pull/4381
