### ISSUE TITLE
Confusing questions about building with Intel compiler

### ISSUE THREAD

**Issue by jokervTv** [xianyi/OpenBLAS#4331]
I can't understand why I get this error, this should be the correct syntax.

```log
'make' '-j16' '-s' 'CC=/public/home/zhangyp_hx/sortware/spack/lib/spack/env/intel/icc' 'FC=/public/home/zhangyp_hx/sortware/spack/lib/spack/env/intel/ifort' 'MAKE_NB_JOBS=0' 'ARCH=x86_64' 'DYNAMIC_ARCH=1' 'DYNAMIC_OLDER=1' 'TARGET=GENERIC' 'USE_LOCKING=1' 'USE_OPENMP=0' 'USE_THREAD=0' 'RANLIB=ranlib' 'all'

13 errors found in build log:
     293    icc: command line warning #10121: overriding '-march=core-avx2' with '-march=skylake-avx512'
     294    icc: command line warning #10121: overriding '-march=skylake-avx512' with '-march=skylake-avx512'
     295    icc: command line warning #10121: overriding '-march=core-avx2' with '-march=skylake-avx512'
     296    icc: command line warning #10121: overriding '-march=skylake-avx512' with '-march=skylake-avx512'
     297    icc: command line warning #10121: overriding '-march=core-avx2' with '-march=skylake-avx512'
     298    icc: command line warning #10121: overriding '-march=skylake-avx512' with '-march=skylake-avx512'
  >> 299    ../kernel/x86_64/sgemm_small_kernel_nt_skylakex.c(385): error: expected an expression
     300                for (int ii = 0; ii < 16; ii++) {
     301                     ^
     302    
  >> 303    ../kernel/x86_64/sgemm_small_kernel_nt_skylakex.c(385): error: identifier "ii" is undefined
     304                for (int ii = 0; ii < 16; ii++) {
     305                                 ^
     306    
     307    compilation aborted for ../kernel/x86_64/sgemm_small_kernel_nt_skylakex.c (code 2)
  >> 308    make[1]: *** [Makefile.L3:4730: sgemm_small_kernel_nt_SKYLAKEX.o] Error 2
```

Thanks for your reading.

**Comment by martin-frbg** [comment]
Is this a very old version of icc ? It looks as if it is not C99-compliant and wants to see the `int ii;` declaration outside the loop, like `int ii; for (ii=0;ii <16; ii++) ...`

**Comment by codeworm96** [comment]
You can check https://www.intel.com/content/www/us/en/developer/articles/technical/c99-support-in-intel-c-compiler.html for C99 support for icc.

**Comment by martin-frbg** [comment]
@jokervTv  what is your icc version and operating system ? From the path names and command line options in your message I woud assume Linux  but the Linux version of icc has `-std=c99` as its default for years.

**Comment by jokervTv** [comment]
Thanks for all your help.

I installed in CentOS 7 with Intel compiler 2021.3 using [SPACK](https://github.com/spack/spack). If I add `cflag=-std=c99` to spack it works fine.

For everything else, just download it from github realease and everything will be fine.

So, there seems to be some issues with SPACK.

Thanks again for the help.

**Comment by martin-frbg** [comment]
CentOS7 may be the decisive difference as it came with gcc4 - the icc manpage mentions that when a gcc version earlier than 5.0 is present on the system, the default for the C standard changes to `-std=c11` . Now one would expect a C11-compliant compiler to support the same flexibility of variable declarations as in the earlier C99, but I guess there may have been bugs in whatever part of gcc4 backend icc ties into.
