### ISSUE TITLE
CMake based build created `include/openblas/openblas`

### ISSUE THREAD

**Issue by catap** [xianyi/OpenBLAS#4343]
Original report at MacPorts: https://trac.macports.org/ticket/68783

A trivial install without any MacPorts specific manipulation of destroot (after make install) leads to: 
```
catap@catalina work % ls destroot/opt/local/include/openblas 
cblas.h			lapack.h		lapacke_config.h	lapacke_mangling.h	openblas
f77blas.h		lapacke.h		lapacke_example_aux.h	lapacke_utils.h		openblas_config.h
catap@catalina work % ls destroot/opt/local/include/openblas/openblas
lapacke_mangling.h
catap@catalina work %
```

**Comment by martin-frbg** [comment]
Oh, indeed. This appears to be due to an oversight (by me) that happened five years ago. Will fix after merging your PR as it is in the toplevel CMakeLists.txt as well.
