### ISSUE TITLE
Incorrect results with cblas_sgemm when called no of times

### ISSUE THREAD

**Issue by goplanid** [xianyi/OpenBLAS#4345]
I get different results when I call cblas_sgemm no of times (I am calling cblas_sgemm 500 times, parallelized with openmp pragma directive).  I don't see any race condition or any other reason for getting very different values on each run.  Kindly find the below results and sample code to reproduce the issue. 

Run 1 result : 39960 
Run 2(sometimes after several runs) : 52880

Flags used to build OpenBLAS: USE_THREAD=1 and USE_OPENMP=1

Sample code:
#include <iostream>
#include <cblas.h>
#include <vector>

const int MATRIX_DIMENSION = 999;
const int NUM_GEMM_CALLS = 500;

template <typename T>
void initialize_matrix(std::vector<T>& matrix, T value) {
    std::fill(matrix.begin(), matrix.end(), value);
}

template <typename T>
void print_matrix(const std::vector<T>& matrix, int rows, int cols) {
    for (int i = 0; i < std::min(rows, MATRIX_DIMENSION); ++i) {
        for (int j = 0; j < std::min(cols, MATRIX_DIMENSION); ++j) {
            std::cout << matrix[i * MATRIX_DIMENSION + j] << "\t";
        }
        std::cout << std::endl;
    }
}

int main() {
    std::vector<float> A(MATRIX_DIMENSION * MATRIX_DIMENSION, 8.0);
    std::vector<float> B(MATRIX_DIMENSION * MATRIX_DIMENSION, 5.0);
    std::vector<float> C(MATRIX_DIMENSION * MATRIX_DIMENSION, 0.5);

    #pragma omp parallel for
    for (int i = 0; i < NUM_GEMM_CALLS; ++i) {
        cblas_sgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans,
                    MATRIX_DIMENSION, MATRIX_DIMENSION, MATRIX_DIMENSION,
                    1.0, A.data(), MATRIX_DIMENSION,
                    B.data(), MATRIX_DIMENSION,
                    0.0, C.data(), MATRIX_DIMENSION);
    }

    // Print a portion of the result matrix for diagnostics
    std::cout << "Result Matrix (partial):" << std::endl;
    print_matrix(C, 1, 1);

    return 0;
}

**Comment by martin-frbg** [comment]
Try building OpenBLAS with option NUM_PARALLEL set to a value matching the number of parallel calls your OpenMP code is making (it is probably less than 500 unless you have that many cpu cores/threads available). Otherwise some of your calls are probably reusing memory buffers allocated by one of the other instances.

**Comment by martin-frbg** [comment]
Not entirely sure your sample code is correct, sharing the result matrix C between the omp threads may not be safe. (I do get identical results within the parallel region if I add `firstprivate(C)` to the pragma, but then C remains at its initial value outside the omp block of course)

**Comment by goplanid** [comment]
Thank you Martin for your suggestions. Please find my comments below:

1. I tried building OpenBLAS with option NUM_PARALLEL set to both 500 and 32(using a 32 core machine) but I still see the issue. 

2. Based on the suggestion mentioned in the wiki, https://github.com/OpenMathLib/OpenBLAS/wiki/faq#multi-threaded - I tried building OpenBLAS using 
USE_THREAD=0 USE_LOCKING=1 but still see the same issue. 

3. Next thing, I removed USE_OPENMP=1 and USE_THREAD=1 from my build command. I don't see any issues now but I get the below warning as "OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option." So does this mean there is no issue with OpenBLAS Pthreads backend? 

4. I agree on your last suggestion that there might be a race condition but not sure why I don't see any issues with smaller matrix dimensions. Any idea why? But now that I think each iteration would write to C which means multiple threads might try to update the same memory concurrently so I have modified the code for loop as below. I see correct value printed but seeing free:invalid pointer error.

#pragma omp parallel for schedule(static)
    for (int i = 0; i < NUM_GEMM_CALLS; i++) {
        blas_function(CblasRowMajor, CblasNoTrans, CblasNoTrans,
                      MATRIX_DIMENSION, MATRIX_DIMENSION, MATRIX_DIMENSION,
                      static_cast<T>(1.0), A.data(), MATRIX_DIMENSION,
                      B.data(), MATRIX_DIMENSION,
                      static_cast<T>(0.0), C.data() + i * MATRIX_DIMENSION * MATRIX_DIMENSION, MATRIX_DIMENSION);
    }
Let me know your thoughts on this.

**Comment by goplanid** [comment]
Another way I can think of - each thread has its own private copy (privateC) of the result matrix. After the parallel region, a reduction operation is performed to accumulate the results from all threads into the shared matrix C.

**Comment by martin-frbg** [comment]
Did you adjust the size of `C` accordingly ? Otherwise you'll be writing beyond the end of allocated memory with each i greater than zero

**Comment by goplanid** [comment]
Thank you @martin-frbg. I adjusted the size of C. However with this approach, I am unable to run my code for larger matrices. I see vector size large error.
