### ISSUE TITLE
Build errors on changing nthreads to a specific number in dot.c

### ISSUE THREAD

**Issue by goplanid** [xianyi/OpenBLAS#4349]
Hi,

I have enabled SMP(multithreading) in dot.c code and trying to change nthreads to a specific number(2 in the below case). Build is failing with accuracy errors for many BLAS functions(error screenshot attached below). Kindly advise:

**Code - dot.c**
#if defined(SMP)
	nthreads= 2;
	// if (inc_x == 0 || inc_y == 0 || n <= 10000)
	// 	nthreads = 1;
	// else
	// 	nthreads = num_cpu_avail(1);
	if (nthreads == 1) {
		dot = dot_compute(n, x, inc_x, y, inc_y);
	} else {
		int mode, i;
		char result[MAX_CPU_NUMBER * sizeof(double) * 2];
		RETURN_TYPE *ptr;

**Error:**
 DTRSV  PASSED THE TESTS OF ERROR-EXITS

 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
           EXPECTED RESULT   COMPUTED RESULT
       1       0.00000           0.00000    
       2      0.117383          0.135833    
 ******* DTRSV  FAILED ON CALL NUMBER:
     62: DTRSV ('U','T','N',  2, A,  3, X, 1)                     .

 DTBSV  PASSED THE TESTS OF ERROR-EXITS

 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
           EXPECTED RESULT   COMPUTED RESULT
       1       0.00000           0.00000    
       2      0.916583          0.659984    
 ******* DTBSV  FAILED ON CALL NUMBER:
    254: DTBSV ('U','T','N',  2,  1, A,  3, X, 1)     

**Build command used:** make BUFFERSIZE=20 DYNAMIC_ARCH=1 USE_OPENMP=1 NUM_THREADS=80 TARGET=NEOVERSEV1 INTERFACE64=1

**Comment by martin-frbg** [comment]
Are you sure that dot.c is the only file you changed in the branch you are working with ? (`git status` and `git diff` should tell)

**Comment by goplanid** [comment]
Yes, sharing the output of both the commands:

**git status**
On branch develop
Your branch is up to date with 'origin/develop'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   kernel/arm64/dot.c

no changes added to commit (use "git add" and/or "git commit -a")

 **git diff**
diff --git a/kernel/arm64/dot.c b/kernel/arm64/dot.c
index 4607ebc59..9068f80d8 100644
--- a/kernel/arm64/dot.c
+++ b/kernel/arm64/dot.c
@@ -38,6 +38,7 @@ USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #endif 
 #endif
 #endif
+#define SMP 1
 
 #ifdef USE_SVE
 #include "dot_kernel_sve.c"
@@ -85,10 +86,11 @@ RETURN_TYPE CNAME(BLASLONG n, FLOAT *x, BLASLONG inc_x, FLOAT *y, BLASLONG inc_y
        RETURN_TYPE dot = 0.0;
 
 #if defined(SMP)
-       if (inc_x == 0 || inc_y == 0 || n <= 10000)
-               nthreads = 1;
-       else
-               nthreads = num_cpu_avail(1);
+       nthreads = 2;
+       // if (inc_x == 0 || inc_y == 0 || n <= 10000)
+       //      nthreads = 1;
+       // else
+       //      nthreads = num_cpu_avail(1);
 
        if (nthreads == 1) {
                dot = dot_compute(n, x, inc_x, y, inc_y);

**Comment by martin-frbg** [comment]
Hmm, I don't have time to look now, but can you try leaving the "use nthreads=1 for incx=0 or incy=0" intact ?

**Comment by goplanid** [comment]
I tried with the below code, build works this time but I also wanted to experiment for different values of nthreads when n <=10000. 

#if defined(SMP)
	if (inc_x == 0 || inc_y == 0 || n <= 10000)
		nthreads = 1;
	else
		nthreads = 4;

Also if I try to change the condition from n <= 10000 to n <= 1, build is again stuck.

**Comment by martin-frbg** [comment]
Please consider that not all code paths support special cases like increment = 0 or n = 0 that they are normally protected from by conditionals in the interface.

**Comment by brada4** [comment]
nust move that n<10000 part to new if() It is 2 conditionals merged together.

**Comment by goplanid** [comment]
Hi @martin-frbg , Sorry for reverting back late.  moving n<10000 part to new if()  didn't help, gives the same initial accuracy errors: 
#if defined(SMP)
	if (inc_x == 0 || inc_y == 0)
		nthreads = 1;
	else if ( n <= 10000)
	{
		nthreads = 6;
	}
	else
		nthreads = 6;

**Comment by goplanid** [comment]
Also when nthreads>1, I see almost all the cores used. Is there a way to verify that only nthreads are being used.

**Comment by brada4** [comment]
OpenBLAS does not control more threads than nthreads computed for particular call.
You got your clarification on how to not break algorithm modifying threading threshold.

If you want to calibrate threading threshold you can use benchmarks included, and set the config overrides in `Makefile.rule` then try to point to good direction, like doubling/halving that 10k, then measure speeds at least 10x back/forth from that break point.

If you want to tune for your hardware you need to describe your hardware and at least show some benchmark results that seem illogical/ are worse than arm hpc blas/blis/atlas etc. 

Neither of 2 is to do with initial correction.

**Comment by goplanid** [comment]
Thank you @brada4. Can you please elaborate on which config to override in Makefile? So, currently I am using the benchmark to check the performance of dot with different number of threads.  I am modifying the kernel/arm64/dot.c code only to change the nthreads value I want to experiment with.  I am unable to change the 10k condition as I get test case failures on accuracy issues.

**Comment by brada4** [comment]
> Build command used: make BUFFERSIZE=20 DYNAMIC_ARCH=1 USE_OPENMP=1 NUM_THREADS=80 TARGET=NEOVERSEV1 INTERFACE64=1

Just add make variables in separate lines by end of file.

**Comment by martin-frbg** [comment]
Strange issue - apart from the obvious corner cases like n<=1 I would not expect hangs or  serious accuracy issues from multithreading "too early". Does the problem go away when you do not override the default BUFFERSIZE ? And are you actually running the code on Neoverse V1 or something else ?
