### ISSUE TITLE
Incorrect result from X'y in Julia

### ISSUE THREAD

**Issue by droodman** [xianyi/OpenBLAS#4352]
Please see [this issue](https://github.com/JuliaLang/LinearAlgebra.jl/issues/1041) posted at JuliaLang.

**Comment by martin-frbg** [comment]
Interestingly this appears to use the same GEMV_T codepath as assumed to cause a problematic loss of precision in JuliaLang/julia#4324 - though here the exact same kernel works when compiled for AVX2-only ~~but not when AVX512 instructions are available.~~

**Comment by martin-frbg** [comment]
Actually not related as it only happens with the ancient SSE kernel for Core2 that was the default for an unrecognized (too recent) cpu in past versions.
