### ISSUE TITLE
Explicit init vs. lazy init of thread server

### ISSUE THREAD

**Issue by mseminatore** [xianyi/OpenBLAS#4361]
I am sure there is some legacy knowledge here that I don't have. So hoping one of the maintainers can elaborate. 

**Question**: Why is **blas_thread_init**() called via the constructor mechanism in driver/others/memory.c? While at the same time there is code inside **exec_blas_async**() to evaluate whether the server has been started and call **blas_thread_init**() if needed. If we always init at startup, is there a use-case scenario where the server is shutdown and then later restarted?

The concern I have is that **blas_thread_init**() allocates a default number of threads (ie. number of cpu cores) before any possible call to **openblas_set_num_threads(**). If I have a 64 core machine, then 64 threads are created even if the code intends to limit usage to only one thread/core. This requires the worker_thread code path to deal with an odd case where the actual number of worker threads exceeds the number of threads we ever intend to use.

What I'd like to do is avoid paying the cost of an initialization check on every submission of work if we can safely guarantee that the server is always initialized on startup. But obviously that is not possible if there are valid startup-shutdown-startup patterns.

Alternatively I'd prefer to kill any extra worker threads when an **openblas_set_num_threads**() call reduces the number of threads. More threads can be created as needed.

Any thoughts? I have an amended PR ready to go for the latter strategy in blas_server_win32.c

**Comment by martin-frbg** [comment]
Initializing in the constructor before any openblas_set_num_threads can be seen or processed is IMO unavoidable for shared libraries. The startup-shutdown-startup scenario is relevant (only) when the calling program does a fork(). Killing unneeded workers has been experimented with in the past, but IIRC the overhead turned out to be prohibitive at least in certain OpenMP settings. None of this may be particularly relevant in your Windows scenario.

**Comment by mseminatore** [comment]
Couldn't this be solved, even for shared libraries, by having an explicit **openblas_init**() call which could in turn call **blas_thread_init**()? This would allow for initialization and resource allocation to be deterministic rather than defined by shared library load time. The call to **openblas_set_num_threads**() already calls **blas_thread_init**(). Allowing that pattern would keep the library from creating unused threads.

I'll admit that the forked process scenario is one that I've not thought through so maybe I am missing something important there.

**Comment by pitrou** [comment]
Sorry for reviving this issue, but I'm not sure why it was closed. The fact that OpenBLAS launches N threads at startup is compounded by the fact that [each OpenBLAS thread consumes 40ms of CPU time just initializing](https://github.com/numpy/numpy/issues/29193#issuecomment-2967594275). This is extremely wasteful on a machine with many CPU cores, especially when OpenBLAS is not even used afterwards (this is quite common with NumPy: many uses of NumPy do not involve any linear algebra).

Judging by the comments above, there seem to be a confusion between:
1) launching threads eagerly vs. lazily
2) killing unneeded workers

While I agree that killing unneeded workers is not necessarily useful (and can make the implementation more complex), avoiding eager spawning of worker threads at startup sounds desirable. That, or fixing the issue of consuming 40ms CPU time at thread startup.

I also don't understand this statement:

> Initializing in the constructor before any openblas_set_num_threads can be seen or processed is IMO unavoidable for shared libraries

Lazy initialization should be doable, regardless of whether OpenBLAS is sitting in a shared library or not. [`pthread_once`](https://pubs.opengroup.org/onlinepubs/9799919799/functions/pthread_once.html) is a possible solution to this.
