### ISSUE TITLE
NO_AFFINITY=1 when using OpenBLAS on multi-threaded applications

### ISSUE THREAD

**Issue by eddy16112** [xianyi/OpenBLAS#4363]
I tried to use OpenBLAS on nested OpenMP + pthread applications. I tried to set the affinity for omp threads before calling OpenBLAS using the following approach:
```
void pthread_func()
{
    // bind omp threads
    #pragma omp parallel
    {
        int omp_tid = omp_get_thread_num();
        int core_id = pthread_tid * nb_cores_per_pthread + omp_tid;
        cpu_set_t omp_cpu_set;
        CPU_ZERO(&omp_cpu_set);
        CPU_SET(core_map[core_id], &omp_cpu_set);
        int val = sched_setaffinity(0, sizeof(cpu_set_t), &omp_cpu_set);
    }

    // call openblas
}
```

When I compile OpenBLAS with `USE_OPENMP=1, NO_AFFINITY=1, NUM_PARALLEL=4`, then the OpenBLAS calls will not follow the affinity that I set for omp threads, but if I compile it with `NO_AFFINITY =0`, then omp threads affinity works. 

According to the [FAQ](https://github.com/OpenMathLib/OpenBLAS/wiki/Faq#how-could-i-disable-openblas-threading-affinity-on-runtime), `NO_AFFINITY=1` means disable threading affinity for the OpenBLAS, so I was assuming that the OpenBLAS will not set threading affinity, but follow any affinity set by applications. However, from my experiment, `NO_AFFINITY=1` will ignore any threading affinity, so I am confused about how to interpret `NO_AFFINITY=1`.

**Comment by martin-frbg** [comment]
Exactly as documented - NO_AFFINITY=1 ignores any affinity mask and does not bind threads to cores, NO_AFFINITY=0 applies any affinity mask already set by the caller, or binds to all cores if no affinity mask is present. (Maybe it would be more readable if the option was USE_AFFINITY or  similar, but that is one of the peculiarities of working with a library that has been around for a long time.)

**Comment by brada4** [comment]
you can rise smp migration cost in Linux or rise sched quantum in windows to make thread migrations negligible for performance.
