### ISSUE TITLE
Error in installation of openBLAS-0.3.24

### ISSUE THREAD

**Issue by Jai-40** [xianyi/OpenBLAS#4377]
I am trying to install openBLAS-0.3.24 on ARM. I am getting the following error.
Is there any problem with this version?
DOUBLE -UCOMPLEX ../kernel/arm64/sgemm_beta.S -o sgemm_beta.o
make[1]: *** No rule to make target '../kernel/arm64/sgemm_ncopy_sve_v1.c', needed by 'sgemm_incopy.o'.  Stop.
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '*/blas/OpenBLAS-0.3.24/kernel'

**Comment by martin-frbg** [comment]
The kernel definition files for CortexA710, CortexX1 and Fugaku were inadvertently not updated in that version. Please try the latest (0.3.25) release or build for TARGET=ARMV8SVE if you really need to use 0.3.24 for some reason.
