### ISSUE TITLE
Horribly slow multithreading used for small matrices

### ISSUE THREAD

**Issue by jmtilli** [xianyi/OpenBLAS#4387]
I'm about to develop an application that needs to solve linear systems of equations several million times, with each system being about 23 equations (rough estimate). So I started to research how quickly systems of equations can be solved. I thought the simplest way to come up with an answer is using GNU Octave, since it's probably using the most efficient lapack functions there are, and the eventual application written in C would use those same functions. My theory is that the interpreted nature of GNU Octave shouldn't slow down it as long as the matrices are medium-sized.

So I came up with the following program:

````
$ cat octave.m
A = rand(23);
B = rand(23,1);
for n = 1:2e6
         X = A\B;
end
````

Let's run it on Ubuntu 20.04 LTS:

````
$ time octave-cli octave.m

real    8m5,582s
user    19m17,712s
sys     32m22,377s
````

Ouch! It's so slow it would kill my idea of the software, since waiting for the results takes too long. But it seems to do multithreading which my GNU Octave code does not do. So let's run it using a single thread:

````
$ time OPENBLAS_NUM_THREADS=1 octave-cli octave.m

real    0m30,371s
user    0m30,324s
sys     0m0,021s
````

Now it's starting to have more acceptable performance.

The same problem affects `LAPACK_dgetrf` and for example `LAPACK_dgesv` when called directly from C code.

I checked what version of lapack is being used then linking new applications:

````
$ ll /usr/lib/x86_64-linux-gnu/liblapack.so
lrwxrwxrwx 1 root root 47 touko  20  2020 /usr/lib/x86_64-linux-gnu/liblapack.so -> /etc/alternatives/liblapack.so-x86_64-linux-gnu
$ ll /etc/alternatives/liblapack.so-x86_64-linux-gnu
lrwxrwxrwx 1 root root 45 touko  20  2020 /etc/alternatives/liblapack.so-x86_64-linux-gnu -> /usr/lib/x86_64-linux-gnu/lapack/liblapack.so
$ ll /usr/lib/x86_64-linux-gnu/lapack/liblapack.so
lrwxrwxrwx 1 root root 18 maalis 21  2020 /usr/lib/x86_64-linux-gnu/lapack/liblapack.so -> liblapack.so.3.9.0
````

So it's linking against `liblapack.so.3`. Let's see what version is being used at runtime:

````
$ ll /usr/lib/x86_64-linux-gnu/liblapack.so.3
lrwxrwxrwx 1 root root 49 touko  19  2020 /usr/lib/x86_64-linux-gnu/liblapack.so.3 -> /etc/alternatives/liblapack.so.3-x86_64-linux-gnu
$ ll /etc/alternatives/liblapack.so.3-x86_64-linux-gnu
lrwxrwxrwx 1 root root 57 touko  19  2020 /etc/alternatives/liblapack.so.3-x86_64-linux-gnu -> /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3
````

So it's using openblas-pthread at runtime even though not at link time.

I think the idea of using multiple threads here is wrong. The matrix is very small, and multithreading slows it down instead of speeding it up.

My opinion is that OpenBLAS should only use multithreading if the matrix size is so large that it actually helps. It shouldn't be the user's responsibility to discover there's the environment variable `OPENBLAS_NUM_THREADS` that needs to be set to 1 for certain applications.

**Comment by martin-frbg** [comment]
Most if not all functions in OpenBLAS do have size limits for when to use multithreading nowadays, though of course it could be that values are not optimal for your hardware. Which version do you have installed ?

**Comment by jmtilli** [comment]
On Ubuntu 20.04 LTS the following is the version:

````
$ dpkg -l|grep openblas|grep pthread
ii  libopenblas0-pthread:amd64                 0.3.8+ds-1ubuntu0.20.04.1             amd64        Optimized BLAS (linear algebra) library (shared lib, pthread)
````

...but I have observed the same issue on Ubuntu 22.04 LTS as well, which seems to have 0.3.20+ds-1

**Comment by martin-frbg** [comment]
0.3.8 is ancient and will most likely use multithreading for any size (just like the original GotoBLAS). Seeing the same with 0.3.20 would be disconcerting as at least ?GETRF should be single-threading for small sizes (it does look like there's an oversight in the interface code for ?GESV)

**Comment by dasergatskov** [comment]
I do not see this problem on Fedora / Centos with 0.3.21 -- with this example it is always running single thread with either pthreads or OpenMP library.

**Comment by jmtilli** [comment]
Indeed, I did observe on 0.3.20 (Ubuntu 22.04 LTS) that the GNU Octave code runs fast. Also LAPACK_dgetrf is fast with that version, as is LAPACK_dsgesv but LAPACK_dgesv is very slow.

**Comment by martin-frbg** [comment]
copypasted the limits into gesv for posterity
