### ISSUE TITLE
when link with openblas.lib, my antivirus software(endpoint) prompted Trojan

### ISSUE THREAD

**Issue by arminghz** [xianyi/OpenBLAS#4395]
when link with openblas.lib, my antivirus software(endpoint) prompted Trojan

**Comment by martin-frbg** [comment]
where did you get the lib from ? (but antivirus software can only check for "known" byte sequences that can also occur in legitimate software)

**Comment by martin-frbg** [comment]
I have no indication or reason to suspect that the system I created the import lib in the "official" OpenBLAS binary package on is compromised. If you got the package from the Releases page, please verify its MD5 checksum and submit the suspect openblas.lib file to your antivirus vendor (if they offer an upload path for that). By the way you can recreate the .lib file yourself from the included .def file using lib.exe

**Comment by brada4** [comment]
Care to share name of antivirus and the trojan type it detects? Virustotal sees nothing wrong with any release file on gh.
