### ISSUE TITLE
Changes for ddot in version 24.

### ISSUE THREAD

**Issue by Juliya32** [xianyi/OpenBLAS#4404]
Hello,
Could anybody explain the changes made in version 24/25. When I debug ddot(dot product) routine in both version 23 and 24, I found that 
i) In  version 23 the dot.c (written in interface) calls dot.S of kernel/arm64 while in case of 24 it calls dot.c which in turn calls dot_kernel_sve.c (sve program for dot product calculation) . 
There are some changes in kernel/arm64/KERNEL.ARMV8SVE  and MAKEFILES(dot.S to dot.c) but I could not trace the significant difference . 
It would be great if you help.
Thank you.

**Comment by martin-frbg** [comment]
This must have been #4161 which switched the kernel definition for SVE-capable targets  from the older, single-threaded dot.S kernel to the dot.c (in kernel/arm64) that conditionally includes dot_kernel_sve.c

**Comment by martin-frbg** [comment]
Do you suspect a problem in the SVE implementation of DDOT on arm64 ?

**Comment by Juliya32** [comment]
No, I just wanted to know the changes made.
