### ISSUE TITLE
SVE implementation for dgemv using sve intrinsics

### ISSUE THREAD

**Issue by Juliya32** [xianyi/OpenBLAS#4411]
I am trying to implement dgemv function using sve intrinsic , for that I have created a c file( program using sve intrinsic for dgemv in c).
Please guide me how should i add this c file to existing openblas library. So that whenever dgemv function is called , it calls my sve implemented function.
Thank You.

**Comment by martin-frbg** [comment]
OpenBLAS uses separate kernel files dgemv_t and dgemv_n for GEMV with and without transposition of the matrix. The name of the kernel files to use is specified in the KERNEL files (which are basically Makefile segments that get included by the main makefiles). So in kernel/arm64/KERNEL.ARMV8SVE (which is also used by KERNEL.NEOVERSEV1 and all the other cpus that support SVE) you will see (around line 75)
```
SGEMVNKERNEL = gemv_n.S
DGEMVNKERNEL = gemv_n.S
CGEMVNKERNEL = zgemv_n.S
ZGEMVNKERNEL = zgemv_n.S

SGEMVTKERNEL = gemv_t.S
DGEMVTKERNEL = gemv_t.S
```
where you need to replace the old NEON kernels gemv_n.S and gemv_t.S on the DGEMV... lines with your new code. (The current code has the same gemv_n.S and gemv_t.S for both single and double precision as it has conditional code with lots of `#if defined(DOUBLE)`, but it is perfectly possible to have different implementations for sgemv and dgemv)

**Comment by Juliya32** [comment]
I made gemv_n.c file under kernel/arm64 according to the parameters call by the function pointer gemv under interface. 
This gemv_n.c function calls dgemv_kernel_sve.c (it computes matrix vector multiplication using sve). I changed DGEMVNKERNEL = gemv_n.S to DGEMVNKERNEL = gemv_n.c and tried rebuilding the library but I am getting the following error. 
../libopenblas_armv8svep-r0.3.24.so: undefined reference to `dgemv_n'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:196: ../libopenblas_armv8svep-r0.3.24.so] Error 1
make[1]: Leaving directory '/home/sushil/blasT4/OpenBLAS-0.3.24/exports'
make: *** [Makefile:132: shared] Error 2

**Comment by Juliya32** [comment]
I made gemv_n.c file under kernel/arm64 according to the parameters call by the function pointer gemv under interface.
This gemv_n.c function calls dgemv_kernel_sve.c (it computes matrix vector multiplication using sve). I changed DGEMVNKERNEL = gemv_n.S to DGEMVNKERNEL = gemv_n.c and tried rebuilding the library but I am getting the following error.
../libopenblas_armv8svep-r0.3.24.so: undefined reference to `dgemv_n'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:196: ../libopenblas_armv8svep-r0.3.24.so] Error 1
make[1]: Leaving directory '/blas24/OpenBLAS-0.3.24/exports'
make: *** [Makefile:132: shared] Error 2

**Comment by martin-frbg** [comment]
Compare with the generic kernel in kernel/arm/gemv_n.c - maybe it is because your new function is not named "CNAME" (macro name supplied by the build system)

**Comment by Juliya32** [comment]
Thank You @martin-frbg it's working with gemv function. I tried same approach (naming the function "CNAME" and changing the KERNEL File) with swap function but it's not working. Is there anything else that i need to change for level1 routines?

**Comment by martin-frbg** [comment]
Swap kernel is called directly from interface/swap.c (like all level1 functions) with the multithreading setup provided by the blas_level1_thread function from driver/others/blas_l1_thread.c . Other than that there should be no difference, is your new function not getting called at all or do you get unexpected results ?

 (Actually multithreading SWAP is disabled on most platforms except the ARMV8 ones since #873 - maybe this needs revisiting for newer platforms now, but it should not affect your build as ARMV8 should be automatically defined  for ARMV8SVE target).

**Comment by Juliya32** [comment]
my new function is not getting called.

**Comment by Juliya32** [comment]
I tried with the same swap.c function with version 25, It got build without error (stills calls same swap.S and not my swap.c)  but when  tried with version 26 i am getting the following error.
<command-line>: error: conflicting types for ‘sswap_k’; have ‘int(BLASLONG,  BLASLONG,  BLASLONG,  float,  float *, BLASLONG,  float *, BLASLONG)’ {aka ‘int(long int,  long int,  long int,  float,  float *, long int,  float *, long int)’}
../kernel/arm64/swap.c:16:5: note: in expansion of macro ‘CNAME’
   16 | int CNAME(BLASLONG n, BLASLONG dummy0, BLASLONG dummy1, float da, float *x, BLASLONG inc_x, float *y, BLASLONG inc_y)
      |     ^~~~~
In file included from ../common.h:838,
                 from ../kernel/arm64/swap.c:1:
../common_level1.h:89:8: note: previous declaration of ‘sswap_k’ with type ‘int(BLASLONG,  BLASLONG,  BLASLONG,  float,  float *, BLASLONG,  float *, BLASLONG,  float *, BLASLONG)’ {aka ‘int(long int,  long int,  long int,  float,  float *, long int,  float *, long int,  float *, long int)’}
   89 | int    sswap_k (BLASLONG, BLASLONG, BLASLONG, float,
      |        ^~~~~~~
make[1]: *** [Makefile.L1:875: sswap_k.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/blas26/OpenBLAS-0.3.26/kernel'
make: *** [Makefile:188: libs] Error 1.

**Comment by martin-frbg** [comment]
common_level1.h did not change between 0.3.25 and 26, it looks like you do not have the correct number of (dummy) arguments in your swap kernel - compare with what kernel/arm/swap.c (as an example of a trivial C implementation) has

**Comment by brada4** [comment]
swap is memcpy, it has to be CL/PAGE/THP aligned&padded work units.

**Comment by martin-frbg** [comment]
@brada4 which has nothing to do with call arguments, so why mention it ?

**Comment by brada4** [comment]
It is hard to benchmark when caches are clustered for multiple cores etc.
