### ISSUE TITLE
Issue with i*nan where i is the imaginary unit (while nan*i works)

### ISSUE THREAD

**Issue by vincentcouvert** [xianyi/OpenBLAS#4413]
```
#include <stdio.h>
#include <cblas.h>
#include <math.h>
int main(int argc, char ** argv)
{
    double i[] = {0, 1};
    double nan[] = {NAN, 0};
    cblas_zscal(1, i, &nan, 1);
    printf("result of i*NAN=%g+%g*i\n", nan[0], nan[1]);
    
    nan[0] = NAN;
    nan[1] = 0;
    cblas_zscal(1, &nan, &i, 1);
    printf("result of NAN*i=%g+%g*i\n", i[0], i[1]);
    return 0;
}
```
returns:
result of i*NAN=-0+nan*i
result of NAN*i=nan+nan*i

While I get nan+nan*i & nan+nan*i with refblas, mkl or atlas.

cblas.h is provided by blas

See also #86

**Comment by vincentcouvert** [comment]
Same issue for `inf*i` and `i*inf` which should both return `nan + inf*i`

**Comment by vincentcouvert** [comment]
Thanks @martin-frbg  👍

**Comment by vincentcouvert** [comment]
Hello @martin-frbg,

Using OpenBLAS 0.3.27, we still have this issues:
 - `inf*i` and `i*inf` do not return the same result:
   - `inf*i` => `nan + inf*i`
   - `i*inf` => `0 + inf*i`
   - Both should return `nan + inf*i` as refBLAS and MKL
 -  `nan*i` and `i*nan` do not return the same result:
   - `nan*i` => `nan + nan*i`
   - `i*nan` => `0 + nan*i`
   - both should return `nan + nan*i` as refBLAS and MKL.

We should reopen this issue for further investigations.

Best regards,
Vincent

**Comment by martin-frbg** [comment]
what compiler ? This used to work with at least gcc and clang and now even has an utest to be sure, but #4713 reports that it fails with oneAPI.

**Comment by vincentcouvert** [comment]
We use GCC 8.3.0 for our Linux version and CONDA packages for macOS version.
See Scilab associated issue: https://gitlab.com/scilab/scilab/-/issues/15639 & MR https://gitlab.com/scilab/scilab/-/merge_requests/938

**Comment by martin-frbg** [comment]
I cannot reproduce this with any version of gcc so far - are you using any scary non-default compiler options like `-ffast-math` by any chance ?

**Comment by vincentcouvert** [comment]
You're right it seems to be an issue on our side, sorry...
We will keep you informed when the source of the issue will be identified.

**Comment by davidcl** [comment]
> You're right it seems to be an issue on our side, sorry... We will keep you informed when the source of the issue will be identified.

There was some issue on Scilab side where we did not call zscal on all cases. I opened #4726 for a remaining issue on `i * complex(0, Inf)`
