### ISSUE TITLE
Random usage of memory

### ISSUE THREAD

**Issue by JonathanGirardeau** [xianyi/OpenBLAS#4414]
Hello, I use openBLAS with Kaldi (https://github.com/kaldi-asr/kaldi) to do speech recognition.
When I start the program, a speech recognition model is loaded in memory.
Once the model is loaded I expect the usage of the memory to be deterministic, however each time I launch the program I get a new value of memory usage (between ~600MiB and ~800MiB).
I use `top` to monitor memory usage (`RES` column).

I have tried to replace openBLAS by MKL and I always get a memory usage of 440MiB.
So I guess it comes from openBLAS, do you have any idea why the memory usage varies so much ?

The experiment was done on Linux x86_64, with openBLAS v0.3.20 (USE_THREAD: False, DYNAMIC_ARCH: True, USE_LOCKING: True).

PS: I cannot use MKL because I also need to make it work on ARM CPU.

**Comment by martin-frbg** [comment]
Same hardware and same number of cores (threads) in each case ?

**Comment by JonathanGirardeau** [comment]
Yes same hardware and same number of cores and same number of thread (1 because USE_THREAD=False).

I have just noticed that each time I launch the program, even before loading the model, I get a new value of memory usage: from ~7MiB to ~150MiB (always 6MiB with MKL).

I have tried with USE_THREAD=True but the memory used is much larger.

**Comment by martin-frbg** [comment]
Sorry, missed the USE_THREAD=0. With multithreading you would get memory buffers allocated per thread. I do not see why the resident memory size would vary that wildly between invocations - could Kaldi be doing something in the background that affects its memory usage ?

**Comment by JonathanGirardeau** [comment]
It is possible but it is unlikely because it does not happen with MKL.

I have found that openBLAS does memory allocation with mmap, can it explains these variations ?

I have also found that openBLAS does a "warm up" (https://github.com/OpenMathLib/OpenBLAS/blob/1412d2deeb32cfc1d80150eba520a5bba915f1c6/Makefile.rule#L152C1-L155C14), can it be related to my issue ?

**Comment by martin-frbg** [comment]
"warmup" is disabled by default, and if anything I would expect `top` to show smaller RES for pages that are mapped but not accessed (not sure about the latter though, probably need a small standalone reproducer and/or valgrind's massif)

**Comment by JonathanGirardeau** [comment]
I use `CMake` to build openBLAS v0.3.20 and the parameter `NO_WARMUP` is in `Makefile.rule` but not in `CMakeLists.txt`:
https://github.com/OpenMathLib/OpenBLAS/blob/v0.3.20/Makefile.rule
https://github.com/OpenMathLib/OpenBLAS/blob/v0.3.20/CMakeLists.txt
In this case , what is the default value of parameter `NO_WARMUP`  ?

**Comment by martin-frbg** [comment]
Oh, I see. Using "warmup" would almost certainly cause unnecessary (and time consuming) memory operations.
This was actually fixed in 0.3.22 (released March 26, 2023) - the toplevel CMakeLists.txt defaults it to ON now
```
fixed startup delays resulting from a wrong default setting of
NO_WARMUP in CMAKE builds
```

**Comment by JonathanGirardeau** [comment]
When I build with makefile instead of cmake, the issue disapears: the memory allocated is always 440MiB (like MKL).
The problem probably comes from `NO_WARMUP` that is was not defined in CMakeLists.txt in v0.3.20.

**Comment by martin-frbg** [comment]
Thanks for confirming. If you need to use 0.3.20 built with cmake, it seems all you would need to do is add the `-DNO_WARMUP=1` on the cmake commandline, as it was only the default setting that was missing back then, not the handling of this option in the cmake build itself
