### ISSUE TITLE
Having Trouble Getting Meson to Find Lapack in OpenBLAS

### ISSUE THREAD

**Issue by MarcMignolet** [xianyi/OpenBLAS#4427]
Hello,

I am trying to compile binaries using Meson, however Meson is unable to find lapack in OpenBLAS. I am very new to Fortran compilation so any assistance is appreciated.

I have changed the path inside the pkg-config file as well as the cmake file and added them to the environmental variables. What else should I do?

[meson-log.txt](https://github.com/OpenMathLib/OpenBLAS/files/13929493/meson-log.txt)

**Comment by martin-frbg** [comment]
if I am reading your log correctly, it is complaining about not having a pkg-config exe so it may not be able to use the provided openblas.pc file?

**Comment by martin-frbg** [comment]
also not clear to me from the log what exactly I tries for finding lapack (is the trace file mentioned in the log present anywhere, maybe it has more detailed error messages ?). At least in the end it seems to be blindly trying to link against a liblapack, which will not work if everything is in libopenblas. Does copying the libopenblas file to liblapack make the build go further ?

**Comment by MarcMignolet** [comment]
I accidentally uploaded an older version of the log after I had fixed the issue with the pkg-config executable. I apologize for the confusion. 

I am very much out of my depth here, so could you please explain what you would like me to do in greater detail?

[meson-log.txt](https://github.com/OpenMathLib/OpenBLAS/files/13930000/meson-log.txt)

**Comment by martin-frbg** [comment]
The new log has
```
Package openblas was not found in the pkg-config search path.
Perhaps you should add the directory containing `openblas.pc'
to the PKG_CONFIG_PATH
```
in what appears to be the only attempt to locate OpenBLAS, so it will probably work if you can fix that.

**Comment by MarcMignolet** [comment]
I appreciate the clarification.

Are you referring to openblas64.pc? I cannot find an openblas.pc in the latest OpenBLAS binaries for windows. With regards to openblas64.pc, I had already added it to the PKG_CONFIG_PATH environmental variable.

**Comment by martin-frbg** [comment]
Oh, I think there was no way for me to know that you are using an ILP64 build (INTEGER64=1) of OpenBLAS. Maybe the problem is simply that your Meson scripts are only looking for openblas.pc while the file is named openblas64.pc in your installation and a simple copy or rename would solve that.

**Comment by MarcMignolet** [comment]
Switching to x64 from x64-64 worked. Thank you for your help!
