### ISSUE TITLE
recent commit broke zscal tests on s390x

### ISSUE THREAD

**Issue by sharkcz** [xianyi/OpenBLAS#4428]
Seems that commit e48627c999e3aadfbcdb2b1f1589d4e75840dfca broke `zscal` tests on s390x (Fedora 38 with gcc-13.2.1-4.fc38.s390x running on z14 machine)
````
make TARGET=ZARCH_GENERIC
...
TEST 35/44 dnrm2:dnrm2_inf [OK]
TEST 36/44 zscal:inf_i [OK]
TEST 37/44 zscal:i_inf [FAIL]
  ERR: test_zscal.c:39  should be true
TEST 38/44 zscal:nan_i [OK]
TEST 39/44 zscal:i_nan [FAIL]
  ERR: test_zscal.c:17  should be true
TEST 40/44 potrf:smoketest_trivial [OK]
TEST 41/44 potrf:bug_695 [OK]
TEST 42/44 kernel_regress:skx_avx [OK]
TEST 43/44 fork:safety [OK]
TEST 44/44 fork:safety_after_fork_in_parent [OK]
RESULTS: 44 tests (42 ok, 2 failed, 0 skipped) ran in 1314 ms
````

**Comment by martin-frbg** [comment]
oops, sorry, seemed to be fine in CI (Idk offhand what OSUOSL has, probably z13 but z14 should be same zscal kernel ?)

**Comment by sharkcz** [comment]
let me check the Z13 and Z14 targets too ...

**Comment by sharkcz** [comment]
and it looks like the Z13 and Z14 targets/kernels are OK, seems it's only the "GENERIC" target that fails. They report
````
...
TEST 36/44 zscal:inf_i [OK]
TEST 37/44 zscal:i_inf [OK]
TEST 38/44 zscal:nan_i [OK]
TEST 39/44 zscal:i_nan [OK]
...
````

**Comment by martin-frbg** [comment]
Ah I see... s390 would be using zarch_generic which is the C kernel that lives in kernel/arm - and it looks like I did not include that one in my PR. (This is most likely identical to the zscal in kernel/mips - which I did update)

**Comment by sharkcz** [comment]
and fix has been verified, thanks for the quick response

**Comment by martin-frbg** [comment]
thanks for the quick report and confirmation of the fix
