### ISSUE TITLE
compiler version detection incorrect - segfault on aarch64 with ACfL

### ISSUE THREAD

**Issue by dslarm** [xianyi/OpenBLAS#4430]
f_check makes incorrect assumptions about compiler version naming for those that are based on LLVM, which is then causing OpenBLAS to use the incorrect Fortran interface and then segfault during build.

#. The F_INTERFACE_FLANG is not defined, F_INTERFACE_GFORT is defined instead
#. the -Kieee flag is not set (matters only for ACfL older than 23.10 as now it is the default)
What are consequences of setting F_INTERFACE incorrectly? One of those two:
#. In case of ACfL23.04 and earlier, wrong computations
#. In case of ACfL23.10 and later, segfault in cblat1.

ACfL 23.10 does not use New Flang.   

The output from Arm Compiler for Linux 23.10 is:
```
armflang -v
Arm C/C++/Fortran Compiler version 23.10 (build number 32) (based on LLVM 17.0.0)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/arm/arm-linux-compiler-23.10_AmazonLinux-2023/bin
Found candidate GCC installation: /opt/arm/gcc-12.2.0_AmazonLinux-2023/lib/gcc/aarch64-linux-gnu/12.2.0
Selected GCC installation: /opt/arm/gcc-12.2.0_AmazonLinux-2023/lib/gcc/aarch64-linux-gnu/12.2.0
Candidate multilib: .;@m64
Selected multilib: .;@m64

```

The relevant commit was:
```
Author: Martin Kroeker <[martin@ruby.chemie.uni-freiburg.de](mailto:martin@ruby.chemie.uni-freiburg.de)>
Date:   Fri Aug 4 15:31:03 2023 +0200

    Identify the new generation of flang that comes with LLVM17

diff --git a/f_check b/f_check
index d071e016e..526c41dc6 100755
--- a/f_check
+++ b/f_check
@@ -101,7 +101,14 @@ else
                         *flang*)
                             vendor=FLANG
                             openmp='-fopenmp'
-                            ;;
+                           data=`$compiler -v 2>&1 > /dev/null `
+                           v="${data#*version *}"
+                           v="${v%%*.}"
+                           major="${v%%.*}"
+                           if [ "$major" -ge 17 ]; then
+                               vendor=FLANGNEW
+                           fi
+                       ;;
```

**Comment by martin-frbg** [comment]
Thanks for notifying - compiler detection is primarily based on what the compiler writes into its object files rather than what its version output is, but with everybody deriving from either GCC or LLVM nowadays there is always a risk of misdetection with new compiler versions.
