### ISSUE TITLE
Building with CMake build system on AVX512 platform add -march=znver4

### ISSUE THREAD

**Issue by jnytra** [xianyi/OpenBLAS#4432]
Hi,

I am building the OpenBLAS by the CMake with the following parameters:
```
cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX="/openblas-0.3.25" -DNOFORTRAN="ON" -DC_LAPACK="ON" -DBUILD_WITHOUT_LAPACK="OFF" -DDYNAMIC_ARCH="ON" -DUSE_THREAD="OFF" -DUSE_LOCKING="ON" -DMSVC_STATIC_CRT="OFF" -DANDROID="ON" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" -DBUILD_SHARED_LIBS="ON" ..
```

I found that ZEN core is built with `-march=znver4`, which causes a runtime crash (SIGILL) on `AMD Ryzen 9 3900X`.

When I use make (`make DYNAMIC_ARCH=1 USE_THREAD=0 -j4`) instead of CMake, everything works. Is this correct?

**Comment by martin-frbg** [comment]
Are you building on the Zen4 system ? If so, it is usually safer to add a TARGET option that defines what to use for all the common code - this would be the oldest/weakest kind of cpu you expect to support with the DYNAMIC_ARCH build. Without a TARGET, it is determined automatically by the build system, which may mean that the library cannot run on anything with a smaller instruction set even if it has dedicated BLAS kernels for them.
(But the reason why it works with make but not cmake is that the makefile build simply treats Zen4 as Cooper Lake, while the cmake build tries to be creative with varying `-march` options for the one ZEN target. This does need cleaning up)

**Comment by jnytra** [comment]
Thanks so much. I didn't know about `TARGET` option. Now it works perfectly.

**Comment by w-bruns** [comment]
I have compiled normaliz, using flint (mainly) via e-antic. The binary built with original Mekefile crashes on several systems with` Illegal instruction`.  `march=znever4` seems to be critical. On the contrary, a version compiled with `march=znever3` sems to be more resilient.
