### ISSUE TITLE
SVE kernels use `-mtune=native` breaking cross-compilation

### ISSUE THREAD

**Issue by giordano** [xianyi/OpenBLAS#4433]
Following up from #4431, in https://github.com/JuliaPackaging/Yggdrasil/pull/7952 I'm trying to compile OpenBLAS v0.3.26 for libgfortran5 with GCC 10, but we cross-compile on an x86-64 machine and the compiler flags for the SVE kernels contain `-mtune=native`, which break cross-compilation:
https://github.com/OpenMathLib/OpenBLAS/blob/2527afaaa2a42350d6cb99f69b0f310f5cdac818/Makefile.arm64#L107
For reference the build log is available at https://buildkite.com/julialang/yggdrasil/builds/7771#018d0eae-525e-45dd-926d-848476008e0d/6-2898, but the problem is basically using `-mtune=native`.

**Comment by martin-frbg** [comment]
right, that is a bit disingenious to say the least...  you are on the fallback kludge path here as actual "native" support for the respective cpu(s) did only come with a later GCC (though 10.x with a recent x _should_ suffice for anything Neoverse, I guess your GCC10 is not 10.4 ?). Probably best to delete the `-mtune=native`

**Comment by giordano** [comment]
> though 10.x with a recent x should suffice for anything Neoverse, I guess your GCC10 is not 10.4 ?)

Yes, I'm using gcc 10.2, but can go to 11 if that helps, although I think it'd still be nice to remove the mtune=native flag.

**Comment by Mousius** [comment]
> > though 10.x with a recent x should suffice for anything Neoverse, I guess your GCC10 is not 10.4 ?)
> 
> Yes, I'm using gcc 10.2, but can go to 11 if that helps, although I think it'd still be nice to remove the mtune=native flag.

11 would be more ideal 😸 but I agree we should be wary of `-mtune=native`

**Comment by Mousius** [comment]
@giordano looking at https://github.com/JuliaPackaging/Yggdrasil/blob/b7f5e3c48f292078bbed4c9fdad071da7875c0bc/0_RootFS/gcc_sources.jl#L108 it's configured up to GCC-13, is it possible to use that? 😸

**Comment by giordano** [comment]
Thanks for the quick fix on `-mtune=native`!

> @giordano looking at [JuliaPackaging/Yggdrasil@b7f5e3c/0_RootFS/gcc_sources.jl#L108](https://github.com/JuliaPackaging/Yggdrasil/blob/b7f5e3c48f292078bbed4c9fdad071da7875c0bc/0_RootFS/gcc_sources.jl#L108) it's configured up to GCC-13, is it possible to use that? 😸

Yes, we have also GCC 13, but we usually try to be conservative with the versions of the compilers for compatibility reasons, and try to use a newer one only when necessary, and getting better performance on SVE systems looks a good one 🙂
