### ISSUE TITLE
Github actions for Windows on Arm

### ISSUE THREAD

**Issue by i-lina** [xianyi/OpenBLAS#4443]
Hey folks,

At Linaro, we are working with our partners in enabling the WoA ecosystem to thrive on its own. Microsoft has announced the preview of GHA for Windows on Arm. But in order to be selected, the OpenBLAS team needs to apply. Could you register at this website please.

https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/
https://resources.github.com/devops/accelerate-your-cicd-with-arm-and-gpu-runners-in-github-actions/

We will work with our partner in prioritizing OpenBLAS project for the preview.

**Comment by martin-frbg** [comment]
Done, thank you very much for your support.

**Comment by i-lina** [comment]
Thank you for the quick turnaround.

**Comment by i-lina** [comment]
Hello,

I was informed that GitHub Actions should be available for Windows on Arm64 for OpenBLAS. Could you check and let me know? Thanks.

**Comment by martin-frbg** [comment]
Great - would you happen to know what keyword I need to specify for `runs-on` ? Unfortunately I haven't found any documentation

**Comment by i-lina** [comment]
I will find out and respond.

**Comment by martin-frbg** [comment]
Thank you - I failed to find any documentation (or other projects already using it in their workflow), and my own attempt only got me a conventional x64 Windows host so far

**Comment by i-lina** [comment]
Sorry, but I have asked. Hope to hear back on the documentation and status of the GHA preview.

**Comment by martin-frbg** [comment]
I have now received a message from github stating that they shut down the waitlist as they made the  WoA beta available for commercial customers on Enterprise plans.

**Comment by i-lina** [comment]
Yes, they are now providing GHA private for enterprise and per the blog, open source projects are expected to get GHA end of 2024.
https://github.blog/2024-06-03-arm64-on-github-actions-powering-faster-more-efficient-build-systems
