### ISSUE TITLE
LoongArch64: AXPBY Interface Correctness Assurance

### ISSUE THREAD

**Issue by XiWeiGu** [xianyi/OpenBLAS#4455]
AXPBY is introduced as BLAS extensions, but I haven't found corresponding correctness tests. LoongArch64 has added corresponding optimizations, but correctness cannot be guaranteed. What should be done in this case?

**Comment by martin-frbg** [comment]
Hmm, awkward. Seems this was added ten years ago (#285) without test cases - and as it is an extension, it is not covered by the small testsuites in test and ctest (which were taken from the Reference BLAS) and neither by the standalone BLAS-Tester (based on the ATLAS testsuite). No other implementation uses it internally (except GEADD which is an extension without testcases itself). Guess one would need to create at least something simple in utest (comparing to known good results from a C implementation like the one in kernel/arm, or from certain "competing" packages)

**Comment by martin-frbg** [comment]
Oops, your wish was just fulfilled by @kseniyazaytseva in #4457 - sometimes things are moving a bit too fast here for me

**Comment by XiWeiGu** [comment]
Thank you for your prompt reply. I have an additional question: Is it forgotten or is there some other reason that `{s/d/sc/dz}amax` doesn't have CBLAS interfaces.

**Comment by martin-frbg** [comment]
Can't say if it was forgotten, or if it was intentionally excluded as it is a BLAS extension. This appears to be a historical choice (or oversight) dating back to GotoBLAS, and it seems only the (comparatively recent) cmake build creates these cblas functions "by accident" while the Makefile does not have them.
