### ISSUE TITLE
Instructions on how to cross compile Windows (amd64 -> arm64)

### ISSUE THREAD

**Issue by borrrden** [xianyi/OpenBLAS#4459]
Since this was a rather annoying process and I thought maybe it would be helpful, I will share my steps on how I was able to successfully build (still haven't tried to consume but even getting an output is a win) an arm64 static openblas library on windows amd64.

1. Load into the appropriate cross compiling developer shell (in my case powershell but for cmd.exe it would be `vcvarsamd64_arm64.bat`):  `& 'C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\Tools\Launch-VsDevShell.ps1' -Arch arm64 -HostArch amd64`
2. Invoke the following CMake, based primarily on the example for arm64 -> arm64 in the wiki:  `cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DDYNAMIC_ARCH=0 -DTARGET=ARMV8 -DCMAKE_CROSSCOMPILING=ON -DCMAKE_SYSTEM_NAME="Windows" -DARCH=arm64 -DBINARY=64 -DCMAKE_SYSTEM_PROCESSOR=ARM64 -DCMAKE_C_COMPILER=clang-cl -DCMAKE_C_COMPILER_TARGET=arm64-pc-windows-msvc -DCMAKE_ASM_COMPILER_TARGET=arm64-pc-windows-msvc`.  Notable additions include using clang-cl instead of clang, and adding in the <LANG>_COMPILER_TARGET entries.  Without C_COMPILER_TARGET, clang-cl will be trying to compile x64 machine code and not make it past the cmake generation step.  Without ASM_COMPILER_TARGET the assembly files in openblas will fail to assemble because the assembler is trying to interpret them as x64 assembly.  
3. `ninja` and profit!

**Comment by martin-frbg** [comment]
Thank you very much, I will copy it to the wiki (shame we had to lock it down, there were just too many link spam and phishing edits). Which version of LLVM/clang did you use for the crossbuild ?

**Comment by borrrden** [comment]
This is the clang-cl / LLVM that ships as part of the latest Visual studio 2022 (not sure if the toolchain version will differ between patch releases or not, it is currently 17.8.3) -> 16.0.5.

**Comment by martin-frbg** [comment]
Ah great, thank you, so no separate installing of llvm necessary.

**Comment by borrrden** [comment]
Hmmmm probably not in the way you envision, but it is an _optional_ part of Visual Studio.  The visual studio component `Microsoft.VisualStudio.Component.Llvm.Clang` must be installed.

**Comment by martin-frbg** [comment]
Thanks, got it now (I hope).
