### ISSUE TITLE
GH actions and MSVC 2019/ MSVC 2022 with precompiled release

### ISSUE THREAD

**Issue by chris-hld** [xianyi/OpenBLAS#4466]
Is it confirmed that the latest release with https://github.com/OpenMathLib/OpenBLAS/pull/4368 actually fixed this issue https://github.com/OpenMathLib/OpenBLAS/issues/3661? 
On github actions, with MSVC 2019, and MSVC2022 I still get a lot of the  
`D:\a\SAFpy\SAFpy\OpenBLAS\include\lapack.h(128,72): error C2143: syntax error: missing ',' before '*' [D:\a\SAFpy\SAFpy\Spatial_Audio_Framework\build\test\saf_test.vcxproj]`
etc.

I am downloading the latest release from Github, Using the headers of that folder and I am also setting in cmake
```
       if(MSVC)
            add_compile_definitions(HAVE_LAPACK_CONFIG_H)
        endif()
```

Am I missing something else?

It might be worth noting that https://github.com/chris-hld/SAFpy/tree/CI-setup only compiles  C code, but I also see C++ errors?
`D:\a\SAFpy\SAFpy\OpenBLAS\include\lapack.h(576,31): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [D:\a\SAFpy\SAFpy\Spatial_Audio_Framework\build\test\saf_test.vcxproj]`

**Comment by martin-frbg** [comment]
Have you tried if manually replacing the `lapack_complex_float` on line 128 with `_Fcomplex` fixes the error for that one line ? (If it does, the next step would be to find out if/why the header does not get included despite your cmake setting)

**Comment by chris-hld** [comment]
It turned out that HAVE_LAPACK_CONFIG_H didn't propagate deep enough.
```
        if(MSVC)
            target_compile_definitions(${PROJECT_NAME} PUBLIC HAVE_LAPACK_CONFIG_H=1)
        endif()
```
fixed the issue regarding the compilation.
