### ISSUE TITLE
[Feature request] Allow linking a single non-versioned shared object

### ISSUE THREAD

**Issue by mattip** [xianyi/OpenBLAS#4468]
Over a few PRs to MacPython/openblas-libs, I changed the end result to be a Python wheel. This required packaging a single shared object with no symbolic links. I needed to
- use a prefix so the shared object is unique and can be globally loaded along side a different OpenBLAS build
- changed the Makefiles to allow building a single shared object, with no versioning and no symlinks
- changed the pkg-config file to reflect this

[Here](https://github.com/MacPython/openblas-libs/blob/main/patches/0001-create-a-single-shared-object.patch) is the patch to OpenBLAS 0.3.26 to remove all the symlinking and versioning. Note the prefixing requires [this line](https://github.com/MacPython/openblas-libs/blob/7bc05d17b4ef4aaa0112a66a83a8d1cceb60fffc/patches/0001-create-a-single-shared-object.patch#L131) and [this change](https://github.com/MacPython/openblas-libs/blob/7bc05d17b4ef4aaa0112a66a83a8d1cceb60fffc/patches/0001-create-a-single-shared-object.patch#L179-L180) in order to support prefixes in the pkg-config file. The rest of the patch is "just" removing things. 

Would you be open to merging these changes, toggled with a build option, to reduce openblas-lib's maintenance burden?

**Comment by martin-frbg** [comment]
this looks a bit like PR #4252 ? (that I haven't had time to address properly yet)

**Comment by mattip** [comment]
Yup, it seems so. Anything I can do to help move that one along?

**Comment by martin-frbg** [comment]
I hope to get to this now, with the other issues out of the way

**Comment by martin-frbg** [comment]
hmm, I'm slightly confused by your patch to openblas.pc.in
```
-Libs: -L${libdir} -lopenblas${libsuffix}
+Libs: -L${libdir} -l${libprefix}openblas${libsuffix}
```
which I would have expected to be something like `${libprefix}.${libsuffix}` ?

**Comment by mattip** [comment]
The prefix I am thinking of goes before openblas. So in my case, where `libprefix` is `scipy_` and `libsuffix` is `64_`, the shared object generated is `libscipy_openblas64_.so`.

**Comment by martin-frbg** [comment]
I'm getting a feeling the makefiles have grown some unhealthy mix of automatic and manual prefix and suffix options lately.

**Comment by martin-frbg** [comment]
#4485 implements the basic idea but I still need to sort out the dual use of LIBPREFIX which is an internally generated variable already. (This also needs porting to cmake and integrating with the most recent realization from #3998 that symbol rewriting does not work when applied directly to a shared library ,as it is currently done in the cmake build)
