### ISSUE TITLE
Too much memory committed at static initialization

### ISSUE THREAD

**Issue by adrienclerc** [xianyi/OpenBLAS#4492]
I am using OpenBLAS via OpenCV, compiled on SuSE 15SP5. The key point is that I used `vm.overcommit_memory=2` for the whole system, to avoid OOM.

It works really fine until, we had systems with dual 20-cores with HT (so 80 virtual cores) systems. My program starts allocating a lot of memory, and in either `free` or `htop`, a lot of it is available, because it wasn't written, but the kernel see this as *committed* memory, and if I launch a second instance, it terminates. Worse, either program can't be launched anymore because of this committed memory.

So far, I've seen those solutions:
- Use `vm.overcommit_memory=0`, but what if OpenBLAS really starts to use the allocated memory?
- Use `vm_overcommit_ratio` higher than 100 and hope for the best
- Use a low number of `OPENBLAS_NUM_THREADS` so that allocated memory is constrained, but how about performance?

Is there any preferred path? Is there any other runtime tunable? For maintenance and security, I can't recompile those library.

I hoped OpenBLAS provides something like "I want not too much memory", but it seems it's not possible.

**Comment by martin-frbg** [comment]
OpenBLAS uses a statically allocated buffer for splitting/sharing matrix data between threads, its size is only configurable at compile time (BUFFERSIZE in Makefile.rule). So OPENBLAS_NUM_THREADS is your only option if memory is constrained. Do you happen to know how the library was compiled (even if you cannot change that right now) ? I've seen occasional cases where someone inadvertently built with NO_WARMUP=0 which causes a lot of memory trashing on startup as the library tries to find the fastest contiguous memory region to put the buffer.

**Comment by adrienclerc** [comment]
The generated pkg-config files says: `openblas_config= USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS= NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 CORE2 MAX_THREADS=16`

So I guess there's no BUFFERSIZE defined, and the default value of `32 << 22` is used.

**Comment by martin-frbg** [comment]
Thanks. Is that the stock SuSE Enterprise package ? (In that case I hope the spec file is available somewhere, the pkgconfig does not list all options, only those that turned out to be useful to know in the past). Not sure how to address this in the code - dynamic allocation of the buffer is bound to be a bit slower, though it should solve the problem with adapting to individual use cases. (The default buffersize is probably oversized for at least some AI applications, on the other hand there have been crashes in the likes of NumPy or Octave when someone tried to diagonalize a really huge matrix)

**Comment by adrienclerc** [comment]
Yes, it's the stock SuSE Enterprise package. But it's hard to find the spec file for that. It's available for openSuse, though.

My use case is "basic" computer vision, so yes, I guess that buffer is oversized. As a hint, htop report "only" 5 GB, while `Committed_AS` from `/proc/meminfo` gave ~36GB.

**Comment by martin-frbg** [comment]
OpenBLAS' ancestor GotoBLAS was basically "build on your computer, with options according to your needs" - nobody thought of distributions packaging prebuilt libraries that are expected to cover all use cases. Maybe the /etc/alternatives mechanism could be leveraged to offer "small", "medium", "large" builds or some such, or OpenCV could bundle its own build (I guess nobody is going to love this idea...)

**Comment by adrienclerc** [comment]
Thanks for the support, history and ideas. I'd go for `OPENBLAS_NUM_THREADS`, that I'll try to guess as a "best" according to my need and the combination of CPU count and RAM.

**Comment by martin-frbg** [comment]
Chances are that the hyperthreading nodes are not offering that much more in terms of compute power, so something in between physical core count and full HT count may give best performance - and when your problem size is very small, most if not all BLAS functions in OpenBLAS should switch to single-threading anyway. (though I guess SuSE may carry a fairly old version of OpenBLAS where that may not be a given)

**Comment by adrienclerc** [comment]
> Chances are that the hyperthreading nodes are not offering that much more in terms of compute power, so something in between physical core count and full HT count may give best performance - and when your problem size is very small, most if not all BLAS functions in OpenBLAS should switch to single-threading anyway. (though I guess SuSE may carry a fairly old version of OpenBLAS where that may not be a given)

https://scc.suse.com/packages/23596440
0.3.21 so that's not really bad

**Comment by martin-frbg** [comment]
if I had fixed the bugs that caused gemv and gesv to use all-core multithreading even for small problem sizes back then already...
