### ISSUE TITLE
Build Fail in Arch Linux

### ISSUE THREAD

**Issue by gramian** [xianyi/OpenBLAS#450]
Hi,
I get the following error when running make:

getarch_2nd.c: In function ‘main’:
getarch_2nd.c:12:35: error: ‘SGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function)
     printf("SGEMM_UNROLL_M=%d\n", SGEMM_DEFAULT_UNROLL_M);
                                   ^
getarch_2nd.c:12:35: note: each undeclared identifier is reported only once for each function it appears in
getarch_2nd.c:13:35: error: ‘SGEMM_DEFAULT_UNROLL_N’ undeclared (first use in this function)
     printf("SGEMM_UNROLL_N=%d\n", SGEMM_DEFAULT_UNROLL_N);
                                   ^
getarch_2nd.c:14:35: error: ‘DGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function)
     printf("DGEMM_UNROLL_M=%d\n", DGEMM_DEFAULT_UNROLL_M);
                                   ^
getarch_2nd.c:15:35: error: ‘DGEMM_DEFAULT_UNROLL_N’ undeclared (first use in this function)
     printf("DGEMM_UNROLL_N=%d\n", DGEMM_DEFAULT_UNROLL_N);
                                   ^
getarch_2nd.c:19:35: error: ‘CGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function)
     printf("CGEMM_UNROLL_M=%d\n", CGEMM_DEFAULT_UNROLL_M);
                                   ^
getarch_2nd.c:20:35: error: ‘CGEMM_DEFAULT_UNROLL_N’ undeclared (first use in this function)
     printf("CGEMM_UNROLL_N=%d\n", CGEMM_DEFAULT_UNROLL_N);
                                   ^
getarch_2nd.c:21:35: error: ‘ZGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function)
     printf("ZGEMM_UNROLL_M=%d\n", ZGEMM_DEFAULT_UNROLL_M);
                                   ^
getarch_2nd.c:22:35: error: ‘ZGEMM_DEFAULT_UNROLL_N’ undeclared (first use in this function)
     printf("ZGEMM_UNROLL_N=%d\n", ZGEMM_DEFAULT_UNROLL_N);
                                   ^
getarch_2nd.c:67:50: error: ‘SGEMM_DEFAULT_Q’ undeclared (first use in this function)
     printf("#define SLOCAL_BUFFER_SIZE\t%ld\n", (SGEMM_DEFAULT_Q \* SGEMM_DEFAULT_UNROLL_N \* 4 \* 1 \*  sizeof(float)));
                                                  ^
getarch_2nd.c:68:50: error: ‘DGEMM_DEFAULT_Q’ undeclared (first use in this function)
     printf("#define DLOCAL_BUFFER_SIZE\t%ld\n", (DGEMM_DEFAULT_Q \* DGEMM_DEFAULT_UNROLL_N \* 2 \* 1 \*  sizeof(double)));
                                                  ^
getarch_2nd.c:69:50: error: ‘CGEMM_DEFAULT_Q’ undeclared (first use in this function)
     printf("#define CLOCAL_BUFFER_SIZE\t%ld\n", (CGEMM_DEFAULT_Q \* CGEMM_DEFAULT_UNROLL_N \* 4 \* 2 \*  sizeof(float)));
                                                  ^
getarch_2nd.c:70:50: error: ‘ZGEMM_DEFAULT_Q’ undeclared (first use in this function)
     printf("#define ZLOCAL_BUFFER_SIZE\t%ld\n", (ZGEMM_DEFAULT_Q \* ZGEMM_DEFAULT_UNROLL_N \* 2 \* 2 \*  sizeof(double)));
                                                  ^
make: **\* [getarch_2nd] Error 1
make[1]: Entering directory '/tmp/OpenBLAS/interface'
gcc -c -O2 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME=sgemv -DASMFNAME=sgemv_ -DNAME=sgemv_ -DCNAME=sgemv -DCHAR_NAME=\"sgemv_\" -DCHAR_CNAME=\"sgemv\" -DNO_AFFINITY -I.. -I. -UDOUBLE  -UCOMPLEX -o sgemv.o gemv.c
gcc -c -O2 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME=sspr -DASMFNAME=sspr_ -DNAME=sspr_ -DCNAME=sspr -DCHAR_NAME=\"sspr_\" -DCHAR_CNAME=\"sspr\" -DNO_AFFINITY -I.. -I. -UDOUBLE  -UCOMPLEX spr.c -o sspr.o
gcc -c -O2 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME=sspr2 -DASMFNAME=sspr2_ -DNAME=sspr2_ -DCNAME=sspr2 -DCHAR_NAME=\"sspr2_\" -DCHAR_CNAME=\"sspr2\" -DNO_AFFINITY -I.. -I. -UDOUBLE  -UCOMPLEX spr2.c -o sspr2.o
gcc -c -O2 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME=stbsv -DASMFNAME=stbsv_ -DNAME=stbsv_ -DCNAME=stbsv -DCHAR_NAME=\"stbsv_\" -DCHAR_CNAME=\"stbsv\" -DNO_AFFINITY -I.. -I. -UDOUBLE  -UCOMPLEX tbsv.c -o stbsv.o
gemv.c: In function ‘sgemv_’:
gemv.c:219:41: error: ‘GEMM_MULTITHREAD_THRESHOLD’ undeclared (first use in this function)
   if ( MNK <= (24.0 \* 24.0  \* (double) (GEMM_MULTITHREAD_THRESHOLD_GEMM_MULTITHREAD_THRESHOLD) )  )
                                         ^
gemv.c:219:41: note: each undeclared identifier is reported only once for each function it appears in
Makefile:819: recipe for target 'sgemv.o' failed
make[1]: *_\* [sgemv.o] Error 1
make[1]: **\* Waiting for unfinished jobs....
make[1]: Leaving directory '/tmp/OpenBLAS/interface'
Makefile:141: recipe for target 'libs' failed
make: **\* [libs] Error 1

I am using:

 59e2c20557e63779f1515c44b48879045f2e4eaf

on:

CPU~Quad core AMD A4-5000 APU with Radeon HD Graphics (-MCP-) clocked at Min:800.000Mhz Max:1500.000Mhz Kernel~3.16.2-1-ARCH x86_64 Up~5:23 Mem~1053.0/7357.7MB HDD~1128.2GB(56.8% used)

Thank you

**Comment by leitao** [comment]
I am trying to run it on a IBM POWER8 machine with Ubuntu 15.04, and using this option makes the compiler go longer, but now I face the following problem:

In file included from symm_k.c:77:0:
level3_thread.c: In function ‘inner_thread’:
level3_thread.c:233:22: warning: variable ‘l2size’ set but not used [-Wunused-but-set-variable]
   BLASLONG l1stride, l2size;
                      ^
In file included from symm_k.c:77:0:
level3_thread.c: In function ‘inner_thread’:
level3_thread.c: In function ‘dsymm_thread_RL’:
level3_thread.c:685:12: warning: variable ‘n’ set but not used [-Wunused-but-set-variable]
   BLASLONG n = args -> n;
            ^
level3_thread.c:684:12: warning: variable ‘m’ set but not used [-Wunused-but-set-variable]
   BLASLONG m = args -> m;
            ^
level3_thread.c:233:22: warning: variable ‘l2size’ set but not used [-Wunused-but-set-variable]
   BLASLONG l1stride, l2size;
                      ^
level3_thread.c: In function ‘dsymm_thread_RU’:
level3_thread.c:685:12: warning: variable ‘n’ set but not used [-Wunused-but-set-variable]
   BLASLONG n = args -> n;
            ^
level3_thread.c:684:12: warning: variable ‘m’ set but not used [-Wunused-but-set-variable]
   BLASLONG m = args -> m;
            ^
In file included from ../../common.h:421:0,
                 from gemm.c:40:
level3.c: In function ‘cgemm_nn’:
../../param.h:398:25: error: ‘cgemm_r’ undeclared (first use in this function)
 #define CGEMM_DEFAULT_R cgemm_r
                         ^
../../common_param.h:982:18: note: in expansion of macro ‘CGEMM_DEFAULT_R’
 #define CGEMM_R  CGEMM_DEFAULT_R
                  ^
../../common_param.h:1127:18: note: in expansion of macro ‘CGEMM_R’
 #define GEMM_R   CGEMM_R
                  ^
level3.c:287:37: note: in expansion of macro ‘GEMM_R’
   for(js = n_from; js < n_to; js += GEMM_R){
                                     ^
../../param.h:398:25: note: each undeclared identifier is reported only once for each function it appears in
 #define CGEMM_DEFAULT_R cgemm_r
                         ^
../../common_param.h:982:18: note: in expansion of macro ‘CGEMM_DEFAULT_R’
 #define CGEMM_R  CGEMM_DEFAULT_R
                  ^
../../common_param.h:1127:18: note: in expansion of macro ‘CGEMM_R’
 #define GEMM_R   CGEMM_R
                  ^
level3.c:287:37: note: in expansion of macro ‘GEMM_R’
   for(js = n_from; js < n_to; js += GEMM_R){
                                     ^
Makefile:323: recipe for target 'cgemm_nn.o' failed
make[1]: *** [cgemm_nn.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from ../../common.h:421:0,
                 from gemm.c:40:
level3.c: In function ‘cgemm_cn’:
../../param.h:398:25: error: ‘cgemm_r’ undeclared (first use in this function)
 #define CGEMM_DEFAULT_R cgemm_r
                         ^
../../common_param.h:982:18: note: in expansion of macro ‘CGEMM_DEFAULT_R’
 #define CGEMM_R  CGEMM_DEFAULT_R
                  ^
../../common_param.h:1127:18: note: in expansion of macro ‘CGEMM_R’
 #define GEMM_R   CGEMM_R
                  ^
level3.c:287:37: note: in expansion of macro ‘GEMM_R’
   for(js = n_from; js < n_to; js += GEMM_R){
                                     ^
../../param.h:398:25: note: each undeclared identifier is reported only once for each function it appears in
 #define CGEMM_DEFAULT_R cgemm_r
                         ^
../../common_param.h:982:18: note: in expansion of macro ‘CGEMM_DEFAULT_R’
 #define CGEMM_R  CGEMM_DEFAULT_R
                  ^
../../common_param.h:1127:18: note: in expansion of macro ‘CGEMM_R’
 #define GEMM_R   CGEMM_R
                  ^
level3.c:287:37: note: in expansion of macro ‘GEMM_R’
   for(js = n_from; js < n_to; js += GEMM_R){
                                     ^
Makefile:359: recipe for target 'cgemm_cn.o' failed
make[1]: *** [cgemm_cn.o] Error 1
make[1]: Leaving directory '/home/ubuntu/OpenBLAS/driver/level3'
Makefile:141: recipe for target 'libs' failed
make: *** [libs] Error 1

**Comment by xianyi** [comment]
Hi, we didn't support POWER 8 yet.

**Comment by leitao** [comment]
How hard is it to support it? Can we help with the development?

**Comment by xianyi** [comment]
Please refer to #512 , https://github.com/xianyi/OpenBLAS/issues/512#issuecomment-77442658

Firstly, I cannot access a POWER 8 machine.

Secondly, I didn't optimize BLAS on POWER before. We need do some experiments.

**Comment by Nestarneal** [comment]
Hi xianyi,

I have similar problem when executing the program that is linked to OpenBLAS.
After I build my toy program by including and linking to built openblas shared library,
I met
    Illegal instruction (core dumped)
issue.

My machine use AMD A6-5200 APU, which is Jaguar architecture.
And the APU used by gramian is AMD A4-5000 APU, which is also Jaguar architecture, too.
I can build OpenBLAS and install it successfully by typing

    sudo make TARGET=PILEDRIVER
    sudo make install

And the header files and shared library files are installed into /opt/OpenBLAS.

My toy program using cblas_dgemm() function for testing is as following

    #include <iostream>
    extern "C" {
        #include <cblas.h>
    }

    void mat_mat_mul(
        const double* A, const int ra, const int ca,
        const double* B, const int rb, const int cb,
        double* C);

    int main(int argc, char**) {
        const double A[9] = { 1, 2, 3,
                                          4, 5, 6,
                                          7, 8, 9 };
        const double B[3] = { 1,
                                          1,
                                          1 };
        double* C = new double[3];
        mat_mat_mul(A, 3, 3, B, 3, 1, C);
        for (int i=0 ; i<3 ; i++)
            std::cout << C[i] << std::endl;
        delete[] C;
        return 0;
    }

    void mat_mat_mul(
        const double* A, const int ra, const int ca,
        const double* B, const int rb, const int cb,
        double* C) {
        cblas_dgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans,
            ra, cb, ca, 1, A, ca, B, cb, 0, C, cb);
    }

And my CMakeLists.txt is as following

    cmake_minimum_required(VERSION 2.8.4)
    project(CppGEMM)
    include_directories(SYSTEM /opt/OpenBLAS/include)
    add_executable(cpp_gemm cpp_gemm.cpp)
    target_link_libraries(cpp_gemm /opt/OpenBLAS/lib/libopenblas.so)

I can build the toy program by typing

    cmake ..
    make

However, when I execute it, I met 

    Illegal instruction (core dumped)

I searched the keyword "openblas illegal instruction" and found that
this issue may be occurred due to my AMD A6-5200 APU doesn't support the instruction
that the built shared library used.

I'm confused why I met this issue, is there any solution to this issue?
Many thanks.
