### ISSUE TITLE
How to make sure to get exactly the same numerical results on Intel and AMD machines?

### ISSUE THREAD

**Issue by VInbv** [xianyi/OpenBLAS#4510]
I am using OpenBLAS 0.3.25 version in a Docker container and wonder which build and/or runtime configuration I should use to make sure to get exactly the same results on different computers based on Intel or AMD CPUs, even if there is a little loss in performance

This is using GNU compilers, one thread, and no processor specific options I am aware of, so I guess I have to add options when compiling OpenBLAS, but which ones?

**Comment by martin-frbg** [comment]
Specify the same TARGET (e.g, HASWELL) in both builds, or if using a precompiled DYNAMIC_ARCH build as usually provided by Linux distributions, specify OPENBLAS_CPUTYPE=HASWELL at runtime. (If that does not provide same results due to different hardware/microcode implementations, try building TARGET=GENERIC.

**Comment by VInbv** [comment]
That does not work and I am still getting different results on Intel Xeon and AMD EPYC
I switched to OpenBLAS-0.3.26 and compiled it with 
```
make CC=gcc FC=gfortran USE_OPENMP=0 TARGET=GENERIC
make install USE_OPENMP=0 TARGET=GENERIC
```

Would it be better to specify a different target?
But then which target would provide minimal "tuning" and hence be fully compatible with both the Intel and AMD?

**Comment by martin-frbg** [comment]
TARGET=GENERIC uses plain C algorithms throughout, so any variation should be down to compiler options, system libraries and differences in cpu implementation - this should be as "minimal tuning" as you can get with OpenBLAS.
Maybe using Docker creates an artificial difference between the two hardwares as well (e.g. by not exposing a cpu feature)

 I wonder how large the differences are in your case - are they significantly larger than the precision of the data types involved ? And do you get identical results when you use the reference implementations of BLAS and LAPACK instead ?

**Comment by sjkelly** [comment]
@VInbv I think the env var @martin-frbg meant was `OPENBLAS_CORETYPE`

**Comment by martin-frbg** [comment]
> @VInbv I think the env var @martin-frbg meant was `OPENBLAS_CORETYPE`

Indeed, sorry for that typo

**Comment by VInbv** [comment]
Thanks, I'll try  that
