### ISSUE TITLE
Compile and run OpenBLAS with TIMING flag

### ISSUE THREAD

**Issue by goplanid** [xianyi/OpenBLAS#4526]
Hi,I want to use the TIMING flag for debugging:

#ifdef TIMING
#define START_RPCC()		rpcc_counter = rpcc(); 
#define STOP_RPCC(COUNTER)	COUNTER  += rpcc() - rpcc_counter; 
#else
#define START_RPCC() 
#define STOP_RPCC(COUNTER)
#endif

I am using the compiler flag CFLAGS="-DTIMING=1" but it isn't working. Kindly suggest the right method.

**Comment by martin-frbg** [comment]
TIMING is only present in the level3 driver code and the main thread server - and at least some of the files contain an unconditional `undef TIMING`. These are most likely all just remnants of original GotoBLAS development code, if you really want to use them it is probably best to edit the files directly to make sure TIMING is defined where you need it.

**Comment by martin-frbg** [comment]
Checked it now, adding `-DTIMING=1` to CFLAGS as you said you did does actually work on those few files that have `ifdef TIMING` (and no `undef TIMING`) in them. As said, you may have to copy the relevant code parts to the files you are actually interested in - but depending on what you are debugging, it may be more fruitful to use the simple benchmarks.

**Comment by goplanid** [comment]
Thank you @martin-frbg. Defining the Timing flag in the file helped.
