### ISSUE TITLE
Problems with windows and LIBNAMEPREFIX

### ISSUE THREAD

**Issue by mattip** [xianyi/OpenBLAS#4528]
#4485 went a long way to adding a prefix and suffix to the lib name, and allowing `FIXED_LIBNAME=1`, thanks.

But ... there is a difference between windows and posix. I used HEAD in https://github.com/MacPython/openblas-libs/pull/141. On non-windows, I need to define both `SYMBOLPREFIX=scipy_` and `LIBNAMEPREFIX=scipy_` (and correspondingly, `SYMBOLSUFFIX=64_` and `LIBNAMESUFFIX=64_` when using `INTERFACE64=1`). But on windows, I must only define `SYMBOLPREFIX=scipy_`. Defining `LIBNAMEPREFIX=scipy_` as well results in `libscipy_scipy_openblas...`

I currently worked around this since the CI runs are separate, but I wonder if this is intentional? The "offending" uses are in `Makefile.system`.

**Comment by martin-frbg** [comment]
Thought I had tracked down all sources of stuttering... will try to fix this tomorrow.

**Comment by martin-frbg** [comment]
Hmm. Actually it should be the same on non-Windows systems with the current solution - or are you building with gmake in one case and cmake in the other ?
