### ISSUE TITLE
OpenBLAS gets available cpu using _SC_NPROCESSORS_CONF

### ISSUE THREAD

**Issue by Irvingwangjr** [xianyi/OpenBLAS#4545]
Hey All, we are recently shifting our numpy-based workload from VMs to Containers. We noticed that the open blas use the following code to get the available cpus for linux.
```
  if (!nums) nums = sysconf(_SC_NPROCESSORS_CONF);
```
This will read the all cpus of the host, rather than the online cpus that, for instance, LXCFS might inject for container isolation.

We currently use some env like OPENBLAS_NUM_THREADS to explicitly set the number of thread, but is it possible to change the code to read the online cpus like using sysconf(_SC_NPROCESSORS_ONLN)?

**Comment by martin-frbg** [comment]
the obvious drawback of _SC_NPROCESSORS_ONLN is that it isn't useful on systems where cpus are brought online by the os in response to demand, which is why this code was changed to use the _CONF value

**Comment by Irvingwangjr** [comment]
> the obvious drawback of _SC_NPROCESSORS_ONLN is that it isn't useful on systems where cpus are brought online by the os in response to demand, which is why this code was changed to use the _CONF value

Sorry, I might not quite understand what you refer to. 

You mean the os might bring more cpus online, while the program is running and by using _SC_NPROCESSORS_CONF can handle this situation?  

I thought it's highly unlikely to occur (please correct me if I'm mistaken, but it has never occurred in our cases). However, in a containerized environment, using `_SC_NPROCESSORS_CONF` will result in a thread pool size that is too large, potentially leading to significant context switch costs.

**Comment by martin-frbg** [comment]
see #981 - it might be possible to make that behaviour architecture- and/or OS-dependent, but there will probably be some overlap with container use on those platforms we single out too. The other question that comes to mind is whether your containerized environment should expose the global _SC_NPROCESSORS_CONF to the container at all, rather than the limited subset assigned to it.

**Comment by Irvingwangjr** [comment]
many thanks for mentioning those issues, We might optimize our containerized environment by modifying the  _SC_NPROCESSORS_CONF as you suggest.
