### ISSUE TITLE
Fork Bug Not Fixed

### ISSUE THREAD

**Issue by mattcbro** [xianyi/OpenBLAS#455]
I hate to do this, but I have a strong suspicion that the fork bug,  previously created and closed here
https://github.com/xianyi/OpenBLAS/issues/294
is not entirely fixed, at least when doing multithreaded applications through python, that call into openblas.

I have a very complex proprietary program that makes a lot of numpy dot calls on large complex matrices. It certainly calls openblas quite a bit and in fact it eventually crashes when using openblas (but runs fine using a tuned multithreaded atlas library).

The symptoms are that all 12 hyper threads on my box go to 100%,  the execution time per iteration starts to increase and then eventually processing stops.  In this case when it stops, all execution reverts to single processor mode and the processing drops to almost nothing, but it makes no further progress.

I can not easily reproduce this bug in a test program, however I can provide a program that shows some performance issues using multithreading in python.

``` python

import os
import sys
import numpy as np
import pylab as lab
import multiprocessing as mp
import scipy.linalg as la

Msize = 1000
Niters = 100
Ninner = 4
# more direct exercise of blas
def trsquare(x) :
    y= np.dot(x,x)
    return np.trace(y)

def randzmat(n) :
    """ random complex square matrix of size n """
    z = np.random.randn(n,n) + 1j * np.random.randn(n,n)
    return z



import timeit
p=mp.Pool(4)

def testfunc() :
    """ The function under test """
    return p.map(trsquare, [randzmat(Msize) for i in range(Ninner)])

def testiter(n) :
    """ simple iteration of testfunction in the outer loop """
    alltimes = np.zeros((n,))
    for qq in range(n) :
        tim = timeit.timeit("testfunc()", setup="from __main__ import testfunc",number=1)
        alltimes[qq] = tim
        print "iter %d of %d elapsed time: %g" % (qq,Niters, tim)
        sys.stdout.flush()
    return alltimes

# all dependent functions must be defined prior to creating the pool p

if __name__ == '__main__' :
    alltimes = testiter(Niters)
    np.savez('openblastest.npz', alltimes=alltimes)
    iters = np.arange(Niters)
    #  linear regression plot
    fit = np.polyfit(iters,alltimes,1)
    fitfn = np.poly1d(fit)
    lab.title('Complex gemm Times vs iteration in Numpy')
    lab.plot(iters, alltimes, '.', iters, fitfn(iters))
    lab.grid(True)
    lab.savefig('openblastest.png')
    lab.show()
    os._exit(0)


# original openblas fail test code
# print p.map(la.eigvals, [np.random.rand(i,i) for i in range(2,10)])

```

This program runs at about 0.83 seconds per iteration using openblas, but atlas runs at 0.78 s per iteration.  If you remove the multi-threading,  the openblas case drops to around 0.71 s per iteration,  whereas the atlas timing is about the same for the multi-threaded and single threaded cases.

It may be that different problem sizes would make the problem stand out a little better.  Until I can figure out a way to isolate my complex case that hangs,  using openblas,  it will be difficult to completely characterize the bug.

**Comment by juliocesark** [comment]
It would be good to close the issue because the author has not made the requested changes since 2014.
