### ISSUE TITLE
BUG: dnrm2 basic failures on a subset of platforms (observed in SciPy)

### ISSUE THREAD

**Issue by tylerjereddy** [xianyi/OpenBLAS#4551]
We recently experimented with bumping SciPy OpenBLAS version used in wheels from a pretty old version (`v0.3.20-571-g3dec11c6`) to `0.3.26` stable release in https://github.com/scipy/scipy/pull/20215, in the hopes of fixing the reproducer in https://github.com/scipy/scipy/issues/16930, which can be summarized as the following test, which we should perhaps adjust to be a tractable C-level test in this project:

```python
def test_gh_169309():
    x = np.repeat(10, 9)
    actual = scipy.linalg.blas.dnrm2(x, 5, 3, -1)
    expected = math.sqrt(500)
    assert_allclose(actual, expected)
```

Bumping to `0.3.26` appeared to fix the issue on x86_64 Linux, but not on some other platforms, including MacOS ARM and Linux `aarch64`. In both cases, looks like `actual` ends up as `0.`.

I could probably help draft in the regression test if you tell me where to put it, but I'm unlikely to have the expertise to provide the fix.

**Comment by martin-frbg** [comment]
The only recent change to the (x86_64) NRM2 kernels happens to have been to add support for negative x increments, which reflected a relatively recent change in Reference-BLAS' definition of the NRM2 API. Looks like an "old-style" early exit  has been overlooked in one or more of the aarch64 kernels. Can you tell me which other platforms besides  Apple M are affected ?

**Comment by tylerjereddy** [comment]
I think I only have evidence for failure on two architectures:

1. MacOS M series (ARM)
2. Linux ARM/aarch64

**Comment by martin-frbg** [comment]
Is that Linux aarch64 across the range of processors ? And 32-bit ARM as well, or just aarch64 ? Offhand i see no similar early exit in the assembly kernel for the Cortex cpu models

**Comment by tylerjereddy** [comment]
> Is that Linux aarch64 across the range of processors ?  

I think we only test with one native 64-bit ARM hardware for Linux `aarch64`, and it would be whatever the Cirrus CI service uses by default for ARM Linux. Looking at the log, we do call some OpenBLAS info stuff in case that helps:

```
python /project/tools/openblas_support.py --check_version
OpenBLAS get_config returned b'OpenBLAS 0.3.26 DYNAMIC_ARCH NO_AFFINITY neoversen1 MAX_THREADS=64'
b'OpenBLAS 0.3.26'

python -c 'import openblas_support; print(openblas_support.get_plat())'
PLATFORM=linux-aarch64
```

>  And 32-bit ARM as well, or just aarch64 ? 

Only the 64-bit ARM hardware is tested/distributed binaries by SciPy.

> Cortex cpu models

Not sure I even have access to that, don't see it at https://portal.cfarm.net/machines/list/ for example.

**Comment by martin-frbg** [comment]
ok, Neoverse N1, Apple M and ThunderX2 share the same nrm2 kernels for which I've already posted the PR. Cortex (typical phone cpus) should be unaffected I think

**Comment by ev-br** [comment]
https://github.com/OpenMathLib/OpenBLAS/pull/4554 proposes a small addition to the test suite with a regression test.
