### ISSUE TITLE
About the using of bfloat16 in OpenBLAS

### ISSUE THREAD

**Issue by chen7086** [xianyi/OpenBLAS#4558]
I have been learning how to use OpenBlas recently, and I noticed in the extensions documentation that bfloat16 was available when OpenBLAS was compiled with BUILD_BFLOAT16=1. I read the document "How to use OpenBLAS in Microsoft Visual Studio" and installed it using GNU (MinGW) ABI.

I used "make BUILd_BFLOAT16=1" and "make PREFIX=/D/OpenBLAS-I BUILd_BFLOAT16=1" for installation. But when using the functions in "BFLOAT16 and INT8 extensions", the compiler shows "1>test.obj : error LNK2019: unresolved external symbol cblas_sbstobf16 referenced in function main
1>test.obj : error LNK2019: unresolved external symbol cblas_sbgemm referenced in function main"

When I used the functions in "cblas.h" except for BLAS extension functions, these functions can be used normally. Is it because my installation method is incorrect that I can't normally use bfloat16?

**Comment by martin-frbg** [comment]
This is strange, and I cannot reproduce it immediately with the current version. I do notice that you spelled BUILD_BFLOAT16=1 with a lowercase "d" - probably this is just a typo here, but if that is how you actually wrote it then the option will have been ignored.

**Comment by chen7086** [comment]
When I run it, the Compiler error “test.obj : error LNK2019: unresolved external symbol cblas_sbdtobf16 referenced in function main”
According to the error, I try to find the function of “cblas_sbdtobf16” in the source code. But I can’t find this function in a .c file. Actually, all extension functions in the cblas.h (include “/*** BLAS extensions ***/” and ”/*** BFLOAT16 and INT8 extensions ***/”) are the same, and I cannot find them in the .c file either.

This is all I encountered while studying openblas. I am still a rookie in programming and OpenBlas; thank you for your guidance!

**Comment by chen7086** [comment]
Thanks for your reply, Martin(@martin-frbg )!
I have redone my operation and paid attention to capitalization issues, but I still cannot use bf16.
Here are all my operations, from installing OpenBlas to coding. If you could help me check if there are any errors, I would greatly appreciate it!

First, I put the source code of the OpenBLAS 0.3.26 version into the folder ”D:\openblas” and ran “make BUILD_BFLOAT16=1” in it. Then I install the library to “D:\OpenBLAS-I” by the code "make PREFIX=/D/OpenBLAS-I BUILD_BFLOAT16=1 install".

Now, I have created a new project called OpenBLAS_TEST for BLAS testing.
In the properties of the project, I add “D:\OpenBLAS-I\include” into C/C++→General→Additional Include Directories. 
Then, I add “D:\OpenBLAS-I\include” into Linker→General→Additional Library Directories.
After that, I added “libopenblas.dll.a” to Linker→Input→Additional Dependencies.
At last, I add the “libopenblas.dll.a” and “libopenblas.dll” into my project(“D:\UIC\Research\BLAS\For_Test\OpenBLAS_TEST\x64\Debug”).

Now, I thought OpenBLAS had been installed. So, I asked GPT to write some test code for me. The first is:

#include <stdio.h>
#include <stdlib.h>
#include <time.h>

void traditionalMatrixMultiply(double *A, double *B, double *C, int M, int K, int N) {
    for (int i = 0; i < M; i++) {
        for (int j = 0; j < N; j++) {
            double sum = 0.0;
            for (int k = 0; k < K; k++) {
                sum += A[i*K + k] * B[k*N + j];
            }
            C[i*N + j] = sum;
        }
    }
}

void matrixAddition(double *C, double *A, double *D, int M, int N) {
    for (int i = 0; i < M; i++) {
        for (int j = 0; j < N; j++) {
            D[i*N + j] = C[i*N + j] + A[i*N + j];
        }
    }
}

int main() {
    int M = 500, K = 500, N = 500; // Large matrices for clearer timing differences
    double *A = (double *)malloc(M * K * sizeof(double)); // MxK
    double *B = (double *)malloc(K * N * sizeof(double)); // KxN
    double *C = (double *)malloc(M * N * sizeof(double)); // MxN, result of A*B
    double *D = (double *)malloc(M * N * sizeof(double)); // MxN, result of C+A

    // Initialize matrices A and B
    for (int i = 0; i < M*K; i++) A[i] = (double)(i % 100);
    for (int i = 0; i < K*N; i++) B[i] = (double)(i % 100);

    clock_t start, end;
    double cpu_time_used;

    start = clock();
    traditionalMatrixMultiply(A, B, C, M, K, N);
    matrixAddition(C, A, D, M, N);
    end = clock();
    cpu_time_used = ((double) (end - start)) / CLOCKS_PER_SEC;

    printf("Traditional method took %f seconds to execute \n", cpu_time_used);

    free(A);
    free(B);
    free(C);
    free(D);

    return 0;
}

Then I ask it to use openblas to calculate it, I run:

#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <cblas.h>

void cblasMatrixAddition(double *C, double *A, double *D, int M, int N) {
    for (int i = 0; i < M; i++) {
        for (int j = 0; j < N; j++) {
            D[i*N + j] = C[i*N + j] + A[i*N + j];
        }
    }
}

int main() {
    int M = 500, K = 500, N = 500; // Same size for fair comparison
    double *A = (double *)malloc(M * K * sizeof(double));
    double *B = (double *)malloc(K * N * sizeof(double));
    double *C = (double *)malloc(M * N * sizeof(double)); // Result of A*B
    double *D = (double *)malloc(M * N * sizeof(double)); // Result of C+A

    // Initialize matrices A and B
    for (int i = 0; i < M*K; i++) A[i] = (double)(i % 100);
    for (int i = 0; i < K*N; i++) B[i] = (double)(i % 100);

    clock_t start, end;
    double cpu_time_used;

    start = clock();
    cblas_dgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans, M, N, K, 1.0, A, K, B, N, 0.0, C, N);
    cblasMatrixAddition(C, A, D, M, N);
    end = clock();
    cpu_time_used = ((double) (end - start)) / CLOCKS_PER_SEC;

    printf("CBLAS method took %f seconds to execute \n", cpu_time_used);

    free(A);
    free(B);
    free(C);
    free(D);

    return 0;
}


The first program cost 0.32s and the second only cost 0.002s, I think OpenBlas has significantly improved the speed of calculation!

Then I want try to use bfloat16 for calculation. So I try to use some bf16 function first:

#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <cblas.h>

typedef unsigned short bfloat16;

void cblasMatrixAddition(float* C, float* A, float* D, int M, int N) {
    for (int i = 0; i < M; i++) {
        for (int j = 0; j < N; j++) {
            D[i * N + j] = C[i * N + j] + A[i * N + j];
        }
    }
}

int main() {
    int M = 500, K = 500, N = 500; // Same size for fair comparison
    double* A = (double*)malloc(M * K * sizeof(double));
    double* B = (double*)malloc(K * N * sizeof(double));
    double* C = (double*)malloc(M * N * sizeof(double)); // Result of A*B
    double* D = (double*)malloc(M * N * sizeof(double)); // Result of C+A

    bfloat16* bf16_A = (bfloat16*)malloc(M * K * sizeof(bfloat16));
    bfloat16* bf16_B = (bfloat16*)malloc(K * N * sizeof(bfloat16));

    cblas_sbdtobf16(M * K, A, 1, bf16_A, 1);
    cblas_sbdtobf16(K * N, B, 1, bf16_B, 1);

    free(A);
    free(B);
    free(C);
    free(D);
    free(bf16_A);
    free(bf16_B);

    return 0;
}

When I run it, the Compiler error “test.obj : error LNK2019: unresolved external symbol cblas_sbdtobf16 referenced in function main”
According to the error, I try to find the function of “cblas_sbdtobf16” in the source code. But I can’t find this function in a .c file. Actually, all extension functions in the cblas.h (include “/*** BLAS extensions ***/” and ”/*** BFLOAT16 and INT8 extensions ***/”) are the same, and I cannot find them in the .c file either.

This is all I encountered while studying openblas. I am still a rookie in C programming and OpenBlas; thank you for your guidance!

**Comment by chen7086** [comment]
Thanks for your reply, Martin(@martin-frbg )!
I have redone my operation and paid attention to capitalization issues, but I still cannot use bf16.
Here are all my operations, from installing OpenBlas to coding. If you could help me check if there are any errors, I would greatly appreciate it!

First, I put the source code of the OpenBLAS 0.3.26 version into the folder ”D:\openblas” and ran “make BUILD_BFLOAT16=1” in it. Then I install the library to “D:\OpenBLAS-I” by the code "make PREFIX=/D/OpenBLAS-I BUILD_BFLOAT16=1 install".

Now, I have created a new project called OpenBLAS_TEST for BLAS testing.
In the properties of the project, I add “D:\OpenBLAS-I\include” into C/C++→General→Additional Include Directories.
Then, I add “D:\OpenBLAS-I\include” into Linker→General→Additional Library Directories.
After that, I added “libopenblas.dll.a” to Linker→Input→Additional Dependencies.
At last, I add the “libopenblas.dll.a” and “libopenblas.dll” into my project(“D:\UIC\Research\BLAS\For_Test\OpenBLAS_TEST\x64\Debug”).

Now, I thought OpenBLAS had been installed. So, I asked GPT to write some test code for me. The first is:
```c
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

void traditionalMatrixMultiply(double *A, double *B, double *C, int M, int K, int N) {
    for (int i = 0; i < M; i++) {
        for (int j = 0; j < N; j++) {
            double sum = 0.0;
            for (int k = 0; k < K; k++) {
                sum += A[i*K + k] * B[k*N + j];
            }
            C[i*N + j] = sum;
        }
    }
}

void matrixAddition(double *C, double *A, double *D, int M, int N) {
    for (int i = 0; i < M; i++) {
        for (int j = 0; j < N; j++) {
            D[i*N + j] = C[i*N + j] + A[i*N + j];
        }
    }
}

int main() {
    int M = 500, K = 500, N = 500; // Large matrices for clearer timing differences
    double *A = (double *)malloc(M * K * sizeof(double)); // MxK
    double *B = (double *)malloc(K * N * sizeof(double)); // KxN
    double *C = (double *)malloc(M * N * sizeof(double)); // MxN, result of A*B
    double *D = (double *)malloc(M * N * sizeof(double)); // MxN, result of C+A

    // Initialize matrices A and B
    for (int i = 0; i < M*K; i++) A[i] = (double)(i % 100);
    for (int i = 0; i < K*N; i++) B[i] = (double)(i % 100);

    clock_t start, end;
    double cpu_time_used;

    start = clock();
    traditionalMatrixMultiply(A, B, C, M, K, N);
    matrixAddition(C, A, D, M, N);
    end = clock();
    cpu_time_used = ((double) (end - start)) / CLOCKS_PER_SEC;

    printf("Traditional method took %f seconds to execute \n", cpu_time_used);

    free(A);
    free(B);
    free(C);
    free(D);

    return 0;
}
``` 
Then I ask it to use openblas to calculate it, I run:
```c
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <cblas.h>

void cblasMatrixAddition(double *C, double *A, double *D, int M, int N) {
    for (int i = 0; i < M; i++) {
        for (int j = 0; j < N; j++) {
            D[i*N + j] = C[i*N + j] + A[i*N + j];
        }
    }
}

int main() {
    int M = 500, K = 500, N = 500; // Same size for fair comparison
    double *A = (double *)malloc(M * K * sizeof(double));
    double *B = (double *)malloc(K * N * sizeof(double));
    double *C = (double *)malloc(M * N * sizeof(double)); // Result of A*B
    double *D = (double *)malloc(M * N * sizeof(double)); // Result of C+A

    // Initialize matrices A and B
    for (int i = 0; i < M*K; i++) A[i] = (double)(i % 100);
    for (int i = 0; i < K*N; i++) B[i] = (double)(i % 100);

    clock_t start, end;
    double cpu_time_used;

    start = clock();
    cblas_dgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans, M, N, K, 1.0, A, K, B, N, 0.0, C, N);
    cblasMatrixAddition(C, A, D, M, N);
    end = clock();
    cpu_time_used = ((double) (end - start)) / CLOCKS_PER_SEC;

    printf("CBLAS method took %f seconds to execute \n", cpu_time_used);

    free(A);
    free(B);
    free(C);
    free(D);

    return 0;
}
``` 

The first program cost 0.32s and the second only cost 0.002s, I think OpenBlas has significantly improved the speed of calculation!

Then I want try to use bfloat16 for calculation. So I ask GPT to give an example for me, and the code is:
```c
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <cblas.h>

typedef unsigned short bfloat16;

void cblasMatrixAddition(float* C, float* A, float* D, int M, int N) {
    for (int i = 0; i < M; i++) {
        for (int j = 0; j < N; j++) {
            D[i * N + j] = C[i * N + j] + A[i * N + j];
        }
    }
}

int main() {
    int M = 500, K = 500, N = 500; // Same size for fair comparison
    double* A = (double*)malloc(M * K * sizeof(double));
    double* B = (double*)malloc(K * N * sizeof(double));
    double* C = (double*)malloc(M * N * sizeof(double)); // Result of A*B
    double* D = (double*)malloc(M * N * sizeof(double)); // Result of C+A

    bfloat16* bf16_A = (bfloat16*)malloc(M * K * sizeof(bfloat16));
    bfloat16* bf16_B = (bfloat16*)malloc(K * N * sizeof(bfloat16));

    cblas_sbdtobf16(M * K, A, 1, bf16_A, 1);
    cblas_sbdtobf16(K * N, B, 1, bf16_B, 1);

    free(A);
    free(B);
    free(C);
    free(D);
    free(bf16_A);
    free(bf16_B);

    return 0;
}
``` 

When I run it, the Compiler error “test.obj : error LNK2019: unresolved external symbol cblas_sbdtobf16 referenced in function main”
According to the error, I try to find the function of “cblas_sbdtobf16” in the source code. But I can’t find this function in a .c file. Actually, all extension functions in the cblas.h (include “/*** BLAS extensions ***/” and ”/*** BFLOAT16 and INT8 extensions ***/”) are the same, and I cannot find them in the .c file either.

This is all I encountered while studying openblas. I am still a rookie in C programming and OpenBlas; thank you for your guidance!

**Comment by martin-frbg** [comment]
The functions `sbstobf16` and `sbdtobf16` are generated from the common source file interface/tobf16.c - similarly, most type-specific functions are created from a common source there, with the appropriate `#define` s for DOUBLE and/or COMPLEX passed in by the (C)makefile. Do you see any messages about compiling any of the `sb` functions in your compile log ?

**Comment by chen7086** [comment]
Hi Martin(@martin-frbg ), thanks for your reply.
I found the file tobf16.c in this path:”D:\UIC\Research\BLAS\OpenMathLib-OpenBLAS-6c77e5e\interface”, and the path of my project is “D:\UIC\Research\BLAS\For_Test\OpenBLAS_TEST”, it seems that the OpenMathLib is not in the project, does it wrong?

**Comment by chen7086** [comment]
By the way, I also found “sbdtob16.c”, “sbftob16.c”, “cblas_“sbdtob16.c” and “sbftob16.c” in another folder(“D:\OpenBLAS_CMake\build\interface\CMakeFiles”). This folder is created when I try to use Native (MSVC) ABI(in document”How to use OpenBLAS in Microsoft Visual Studio”). Actually I first tried this way to install openblas, 

Because I have had the anaconda3 so I directly try to use the anaconda prompt to install. 
I have complected the steps of
1,2,3,4(Now install all of the tools we need:) :

```
conda update -n base conda
conda config --add channels conda-forge
conda install -y cmake flang clangdev perl libflang ninja
``` 

And I check cmake flang clangdev perl libflang ninja is in my python environment by the anaconda navigator.

Than I successfully completed step 5 and 6. To use bfloat16, I add -DBUILD_SHARED_LIBS=ON in cmake and all my command is:

```
cmake .. -G "Ninja" -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DCMAKE_Fortran_COMPILER=flang -DCMAKE_MT=mt -DBUILD_WITHOUT_LAPACK=no -DNOFORTRAN=0 -DDYNAMIC_ARCH=ON -DBUILD_BFLOAT16=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
``` 

Everything went very smoothly until the 7 step. When I use the command “cmake --build . --config Release”, there are always erro in:

```
(base) D:\OpenBLAS_CMake\build>cmake --build . --config Release
[2455/17642] Building Fortran object CMakeFiles\LAPACK_OVERRIDES.dir\lapack-netlib\SRC\sgedmd.f90.obj
FAILED: CMakeFiles/LAPACK_OVERRIDES.dir/lapack-netlib/SRC/sgedmd.f90.obj
C:\Users\CH\anaconda3\Library\bin\flang.exe  -ID:\OpenBLAS_CMake\lapack-netlib\SRC -ID:\OpenBLAS_CMake\lapack-netlib\LAPACKE\include -Mrecursive -Kieee    -Mrecursive -Kieee -o CMakeFiles\LAPACK_OVERRIDES.dir\lapack-netlib\SRC\sgedmd.f90.obj -c CMakeFiles\LAPACK_OVERRIDES.dir\lapack-netlib\SRC\sgedmd.f90-pp.f90
F90-F-0004-Unable to open MODULE file iso_fortran_env.mod (CMakeFiles\LAPACK_OVERRIDES.dir\lapack-netlib\SRC\sgedmd.f90-pp.f90: 543)
F90/x86-64 Windows Flang - 1.5 2017-05-01: compilation aborted
[2456/17642] Building Fortran object CMakeFiles\LAPACK_OVERRIDES.dir\lapack-netlib\SRC\sgedmdq.f90.obj
FAILED: CMakeFiles/LAPACK_OVERRIDES.dir/lapack-netlib/SRC/sgedmdq.f90.obj
C:\Users\CH\anaconda3\Library\bin\flang.exe  -ID:\OpenBLAS_CMake\lapack-netlib\SRC -ID:\OpenBLAS_CMake\lapack-netlib\LAPACKE\include -Mrecursive -Kieee    -Mrecursive -Kieee -o CMakeFiles\LAPACK_OVERRIDES.dir\lapack-netlib\SRC\sgedmdq.f90.obj -c CMakeFiles\LAPACK_OVERRIDES.dir\lapack-netlib\SRC\sgedmdq.f90-pp.f90
F90-F-0004-Unable to open MODULE file iso_fortran_env.mod (CMakeFiles\LAPACK_OVERRIDES.dir\lapack-netlib\SRC\sgedmdq.f90-pp.f90: 8)
F90/x86-64 Windows Flang - 1.5 2017-05-01: compilation aborted
[2475/17642] Building Fortran object CMakeFiles\LAPACK_OVERRIDES.dir\lapack-netlib\INSTALL\slamch.f.obj
F90-W-0130-Floating point underflow. Check constants and constant expressions (CMakeFiles\LAPACK_OVERRIDES.dir\lapack-netlib\INSTALL\slamch.f-pp.f: 114)
  0 inform,   1 warnings,   0 severes, 0 fatal for slamch
[2476/17642] Building Fortran object CMakeFiles\LAPACK_OVERRIDES.dir\lapack-netlib\SRC\slapy3.f.obj
ninja: build stopped: subcommand failed.
``` 

GPT explain that the compiler can’t found the “iso_fortran_env.mod”, but I’m sure it was in my environment and the path is “C:/Users/CH/anaconda3/pkgs/flang-5.0.0-he025d50_20180525/Library/include”. so I add the path in cmake:

```
cmake .. -G "Ninja" -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DCMAKE_Fortran_COMPILER=flang -DCMAKE_MT=mt -DBUILD_WITHOUT_LAPACK=no -DNOFORTRAN=0 -DDYNAMIC_ARCH=ON -DBUILD_BFLOAT16=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DCMAKE_Fortran_FLAGS="-I C:\Users\CH\anaconda3\pkgs\flang-5.0.0-he025d50_20180525\Library\include"
``` 

But this error still appear again, so I gave up this method of installation.

**Comment by chen7086** [comment]
I deleted one of the comments above because I found some errors. After searching, I found interface/tobf16. c is indeed in the source code folder(“d:\openblas”, I ran “make BUILD_BFLOAT16=1” in this folder). I searched "sb" in the msys2 and got the following result(PICTURE1). Do you mean this?
![PICTURE1](https://github.com/OpenMathLib/OpenBLAS/assets/55655169/cd525c32-6e17-46c1-a07e-e887da1b1ac4)

**Comment by martin-frbg** [comment]
Yes, from the screenshot of the msys2 window it looks as if it compiled sbstobf16 and sbdtobf16 without problems, and they should be at least in the static library (and I cannot think of a reason why they would not be copied from there to the dll)

**Comment by chen7086** [comment]
Yep...I'm still try to fix this problem. May be there is something wrong with my environment. Is there any code  to test BF16?

**Comment by martin-frbg** [comment]
The "test" folder has compare_sgemm_sbgemm.c, which compiles to test_sbgemm.exe

**Comment by chen7086** [comment]
> The "test" folder has compare_sgemm_sbgemm.c, which compiles to test_sbgemm.exe

Got it, thanks!

**Comment by martin-frbg** [comment]
Maybe you can use `dumpbin /exports /symbols` on your OpenBLAS library to check if it has any of the function names starting with sb ?

**Comment by martin-frbg** [comment]
Did you get it working ? According to my tests, both the .dll and the .dll.a built with MinGW on Windows11 contain all the bfloat16 functions (including sbdtobf16 and cblas_sbdtobf16) and your test program compiles and runs fine with it.

**Comment by chen7086** [comment]
Hello Martin(@martin-frbg ), I'm sorry for the late reply. I can use it normally after compiling on my other computer, and the previous issue may be due to my hardware. Thank you for your assistance!

**Comment by martin-frbg** [comment]
Good to know that it is working for you now, thank you for the reply
