### ISSUE TITLE
Odd attach and detach behavior on Windows

### ISSUE THREAD

**Issue by borrrden** [xianyi/OpenBLAS#4561]
Forgive my pretty severe inexperience in this area but I was diagnosing why my test suite was causing out of control memory usage and I've narrowed it down to the following:

If statically compiling OpenBLAS inside of a DLL, and then loading that DLL at runtime, then `gotoblas_init` is called for some reason having to do with OS runtime semantics.  That's all fine, but when the DLL is unloaded `gotoblas_quit` is NOT called.  I am using OpenBLAS inside of a SQLite extension, so it is expected that it frequently gets loaded and unloaded, and I have 57 tests (most of them will load the SQLite extension that has OpenBLAS inside).  This means every time the DLL is loaded, another 400 or so MiB of memory gets leaked.  

I am out of my depth in understanding WHY this happens, however I did manage to find a solution.  If I pilfer dllinit.c from this repo and compile it directly into my own DLL, then `gotoblas_quit` is called as expected (and `gotoblas_init` is called twice each time, once via OS semantics regarding global initialization or something, and once via `DllMain`).  Is this something that is somewhat expected given my sort of odd way of building?  Or should `gotoblas_quit` be automatically called in the same fashion as `gotoblas_init`

Some more details on the "OS semantics" I refer to above.  It seems that the compiler will insert some stub code into the DLL, which results in the following stack (flowing from bottom to top):

```
gotoblas_init()
ucrtbased.dll!_initterm(void(*)() * first, void(*)() * last)
dllmain_crt_process_attach(HINSTANCE__ * const instance, void * const reserved)
dllmain_crt_dispatch(HINSTANCE__ * const instance, const unsigned long reason, void * const reserved)
dllmain_dispatch(HINSTANCE__ * const instance, const unsigned long reason, void * const reserved)
_DllMainCRTStartup(HINSTANCE__ * const instance, const unsigned long reason, void * const reserved)
```

Based on previous experience working on OS development, `_initterm` looks like a function that operates on some identifiers in the binary that group together a set of global initializers.  I'm curious how `gotoblas_init` registers itself into there.

**Comment by martin-frbg** [comment]
Not a Windows expert, but what you are doing seems to be a bit unusual. Maybe the automatic initialization is working by pure chance already, just from having OpenBLAS' DllMain symbol somewhere inside your DLL, which the compiler may have managed to extract into its startup stub. If you already know that you have built OpenBLAS into your DLL, can't you simply call gotoblas_quit() from its DLL_PROCESS_DETACH handler ?

**Comment by borrrden** [comment]
I didn’t actually have a DllMain before now but what you said is exactly what I ended up doing to solve the issue. I was just wondering if that is what was expected. I don’t know if there is any documentation around the use of the gotoblas functions or anything like that. 

The dllmain function I found is not in fact being called  I put a function breakpoint on it and confirmed it is just a stub prior to this. gotoblas_init just happened to be registered as a global initializer it seems (that’s how it work on non windows right?). It looks like it doesn’t hurt anything to call init multiple times and quit just once so if that is advisable I’ll work that into my permanent solution.

**Comment by martin-frbg** [comment]
Yes, multiple initialization (attempts) should not hurt as there is a static variable to record if initialization has already been performed. 
Beyond that, I cannot really advise on this topic - I notice we carry a second (and largely identical) DllMain for explicit inclusion in the openblas.dll we build (in exports/dllinit.c) in addition to the one in driver/others/memory.c that is `ifdef`d  for compilations with MSVC. 
Apart from that, gotoblas_init is declared with the constructor attribute (unless compiled with MSVC) - but gotoblas_quit is equallly declared as a destructor, so if one worked automagically, the other should too (?)

**Comment by borrrden** [comment]
It's a magical new world for me using clang on windows as well.  Thanks for the advice.  I'll look a little bit more and see if I can find more information.  Perhaps it's even a clang-cl bug or something that gotoblas_quit is not called.

**Comment by borrrden** [comment]
Yeah, even if I define my own destructor, it is never called so it's either just something that is not a thing in Windows (which is concerning that only constructor would be implemented) or a bug somewhere in either clang-cl or the c runtime.  It's something to be aware of though when linking statically as I assume the intent is to not pass this responsibility onto the consumer of OpenBLAS.

**Comment by brada4** [comment]
Use dynamic libraries? Static lib dont have init/fini/import sections and you have to fill in those manually.

**Comment by borrrden** [comment]
Yes, sorry, I meant I am building a dynamic library that links with a statically built OpenBLAS and adds other functionality in with it.  That way we don't have to spend the better part of an hour rebuilding OpenBLAS every time we make a change to the layer on top of it, but also get link time advantages and optimizations.

**Comment by brada4** [comment]
Life will get much easier if you build openblas dll separately. It takes 2 minutes and 2GB ramdisk to build TARGET=GENERIC openblas dll.

**Comment by borrrden** [comment]
That's probably correct and something I can investigate for sure.  I think this issue has enough information to consider this solved for both me and anyone in the future who happens to be as haphazard as me.
