### ISSUE TITLE
OpenBLAS 0.3.26 segfault when building regression testing on armv8

### ISSUE THREAD

**Issue by sdavejones** [xianyi/OpenBLAS#4572]
According to https://github.com/OpenMathLib/OpenBLAS/issues/4424,  my compiler is gcc 8.4.0, not the clang, same as gfortran.  I also tested on rock5b, encounter the same error.

**Comment by martin-frbg** [comment]
Does it build when you leave out the DYNAMIC_ARCH=1 option (much shorter build time, less risk of overheating) ?

**Comment by sdavejones** [comment]
> Does it build when you leave out the DYNAMIC_ARCH=1 option (much shorter build time, less risk of overheating) ?

leaving out the DYNAMIC_ARCH=1 option,  I still get a segfault, thanks.

**Comment by martin-frbg** [comment]
Strange - as noted in your earlier https://github.com/OpenMathLib/OpenBLAS/issues/4424 I could not reproduce this on my Pi4 with gcc-8.5.0. Maybe a problem in gcc-8.4.0 then ?

**Comment by martin-frbg** [comment]
Works on my Pi4 even with 8.4 built from the official gcc sources, so it must be some issue with your hardware or power supply. (The only other cause that comes to mind is that you may have mixed gcc and gfortran from different versions, _if_ you happen to have multiple versions of the compilers installed). There are also no known issues with Rock5B hardware apart from the cpu performance issue brought up in #4581
