### ISSUE TITLE
The parameter GEMM_PREFERED_SIZE is not set for Neoverse V1

### ISSUE THREAD

**Issue by tetsuzo-usui** [xianyi/OpenBLAS#4590]
Hello.
The parameter GEMM_PREFERED_SIZE is set for recent XEON and POWER CPUs, but no specific value is set for Arm CPUs in param.h. Isn’t it better to set the parameter, especially for CPUs with SIMD features?
If so, I would like to evaluate the appropriate value for Neoverse V1 using Graviton3E up to 64 threads.

**Comment by martin-frbg** [comment]
Yes, this has not yet been explored for any of the SVE targets as far as I am aware - I'm not sure if it is as important for Arm hardware as it was for x86_64, but it is certainly worth a look.

**Comment by tetsuzo-usui** [comment]
Thanks for your comment.  I will add fix for this after evaluating preferable settings.
