### ISSUE TITLE
How to know if Openblas be built multi-threaded?

### ISSUE THREAD

**Issue by chasingegg** [xianyi/OpenBLAS#4591]
I install openblas by `apt install libopenblas-dev` at ubuntu20.04, and when I run `sgemm` function, it seems that only one cpu is occupied, is this the default behavior, or how can we know if it is built with multi-threaded or not

**Comment by martin-frbg** [comment]
It is the default for small matrix sizes. You could try running `ldd` on the libopenblas.so installed by the Ubuntu package, a multithreaded OpenBLAS will show a dependency on libpthread (and/or possibly libgomp or libomp for OpenMP support). Or call openblas_get_config() from your program, which returns a version string with key configuration options, including the maximum number of threads.

**Comment by chasingegg** [comment]
Thanks! So there is some dynamic mechanism for openblas parallelism. I have tried your advice and do find out libpthread dependency, also the maximum number of threads is 64.
