### ISSUE TITLE
Installation of openblas-devel on ubi9

### ISSUE THREAD

**Issue by MohammadAliAmir** [xianyi/OpenBLAS#4599]
Hi,

I was trying to install openblas-devel as a requirement for rhel9 based rpm for R on my ubi9 container. This is however not available on the default [ubi9 appstream repo](https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi9/9/x86_64/appstream/os/Packages/o/) where as openblas is available. I tried to install it from a different repository Centos 9 Stream Centos CRB. On [this page](https://centos.pkgs.org/9-stream/centos-crb-x86_64/openblas-devel-0.3.15-3.el9.x86_64.rpm.html) it mentions that I could install it with the following command:
``dnf --enablerepo=crb install openblas-devel``
I would think this will only work if I have the related .repo file installed but I'm not so sure.
An alternative would be quite cumbersome to install all the rpms manually by providing the link.
Considering the last option, I get a status code 403 back when trying to install the openblas-devel package. I'd doubt that I am behind any sort of firewall so perhaps its blocked from the server side?

My question here is how could I install openblas-devel when it is not available in the default repos that are shipped with my distribution?

**Comment by martin-frbg** [comment]
This is best asked of the relevant distribution maintainers - they package openblas in rpm or whatever format, and they decide what if anything to put into a seperate "devel" package. Perhaps there even is no separate "devel" package in the distribution you are using (see if you have a file openblas_config.h anywhere on your system) ?
The alternative would be to build OpenBLAS from source - either from a source package provided by your distribution, or from the .tar.gz you can find in the Releases section here.

**Comment by martin-frbg** [comment]
Closing here as the rstudio folks are apparently working to resolve their dependency issue via the redhat bugtracker

**Comment by MohammadAliAmir** [comment]
Hey @martin-frbg, thanks for your feedback! In the meantime, I had noticed that building my container with podman on a licensed rhel9 server did provide me an additional repository from CodeReady Builder, where openblas-devel is available (and alot of other packages). 

This can indeed be closed.
