### ISSUE TITLE
Test failure when using MAX_STACK_ALLOC 

### ISSUE THREAD

**Issue by goplanid** [xianyi/OpenBLAS#4600]
Hi,

I am trying to use stack allocation (STACK_ALLOC) by setting MAX_STACK_ALLOC when building OpenBLAS.

As per the defintion of STACK_ALLOC in https://github.com/OpenMathLib/OpenBLAS/blob/develop/common_stackalloc.h, I am making sure the below condition is not true so that stack_alloc_size is not 0 and is set to the size I am passing as an input . 

` if (stack_alloc_size > MAX_STACK_ALLOC / sizeof(TYPE)) stack_alloc_size = 0;`

However, I am facing below issue at compile time:
TEST 63/67 potrf:bug_695 [OK]
TEST 64/67 potrf:smoketest_trivial [SIGNAL 11: Segmentation fault]
make[1]: *** [Makefile:81: run_test] Segmentation fault

Any advise would be really appreciated.

**Comment by martin-frbg** [comment]
What is your current stack size limit (`ulimit -s`) ? Perhaps try setting `ulimit -s unlimited`

**Comment by martin-frbg** [comment]
Tried on x86_64 with varied MAX_STACK_ALLOC (1024,4096,8192) without encountering any problem, so have to assume you are hitting the default stacksize limit of your system (which `ulimit -s` should take care of, as suggested)

**Comment by goplanid** [comment]
Hi @martin-frbg , Thank you for your quick reply. I am trying this on ARM. 

ulimit -s returns 8192 bytes.
I tried this setting(ulimit -s unlimited) but still see the above test errors

Below is the code I have added:
```
  int size=128;
  STACK_ALLOC(size, XFLOAT, buffer);
```

I am setting MAX_STACK_ALLOC to 8192 in the command line.

**Comment by martin-frbg** [comment]
So you are adding your own calls to STACK_ALLOC somewhere in the code (where? and is there a corresponding STACK_FREE?) Have you tried debugging (gdb,valgrind,...) to find out where/why it crashes - the "potrf smoketest_trivial" in utest/test_potrs.c is fairly simple ? Possibly the crash is not even directly related to the allocation but to something else your added code does.
