### ISSUE TITLE
Feature request: OpenBLAS support in CMake's FindBLAS module

### ISSUE THREAD

**Issue by rzoom** [xianyi/OpenBLAS#461]
I am a user and fan of OpenBLAS, I think that the work being done here is excellent, and it really speeds up the work that I (and many others) do everyday.

One thing that would improve the adoption of OpenBLAS (and simplify my code and deployment needs) is having OpenBLAS recognized by CMake's FindBLAS module.  There are two reasons for this.

First, it would mean that developers do not have to maintain their own FindOpenBLAS module.  

Second, using CMake with LAPACK means that CMake uses FindLAPACK module, which uses FindBLAS and that will fail due to OpenBLAS not being recognized as a legitimate BLAS implementation.  This results in my having to install a recognized BLAS implementation (and not use OpenBLAS), or override FindLAPACK and FindBLAS and get them to run a custom version, etc.  It is painful, when all we want to do is drop in our favorite BLAS implementation (OpenBLAS!)

So, I am sure that it would mean quite a bit if the OpenBLAS developers asked for OpenBLAS to be included in CMake's FindBLAS.cmake module.  (And it would also make OpenBLAS easier to use in projects that use CMake!)

Best Regards,
Rob

**Comment by imikejackson** [comment]
I have just downloaded the prebuilt 0.2.13 version for windows and the OpenBLASConfig.cmake file has hard coded paths for the libraries. Can you change the generated .cmake file to be the following:

#-----------------------------------------------------------------------------
# OpenBLAS Config file for compiling against OpenBLAS install directory
#-----------------------------------------------------------------------------
GET_FILENAME_COMPONENT (SELF_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
GET_FILENAME_COMPONENT(_IMPORT_PREFIX "${SELF_DIR}" PATH)
if (NOT WIN32)
  GET_FILENAME_COMPONENT(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
endif (NOT WIN32)

#-----------------------------------------------------------------------------
# Directories
#-----------------------------------------------------------------------------
SET(OpenBLAS_INCLUDE_DIRS ${_IMPORT_PREFIX}/include)
SET(OpenBLAS_LIBRARIES ${_IMPORT_PREFIX}/lib/libopenblas.dll.a)


This will allow the prebuilts to be used from any install location on the users drive.

Thanks
