### ISSUE TITLE
[Doc][RFC]fix runtime error in examples in User Document

### ISSUE THREAD

**Issue by cyk2018** [xianyi/OpenBLAS#4619]
In user_manual.md, there are some error about running problem. so I add two PR.
[https://github.com/OpenMathLib/OpenBLAS/pull/4618](url).
[https://github.com/OpenMathLib/OpenBLAS/pull/4617](url).

**Comment by martin-frbg** [comment]
Thanks - seen them but a bit undecided as at least one of them is a fairly general Unix/Linux topic
