### ISSUE TITLE
Linking against static library compiled from source with USE_THREAD = 0

### ISSUE THREAD

**Issue by Xofrio** [xianyi/OpenBLAS#4621]
Problem description lies in title, but let me provide some details.  
I've done those steps:
1. `make`
2. Changed `Makefile.rule`, in particular:
    - `USE_THREAD = 0`
    - `USE_LOCKING = 1`
    - `PREFIX = ../OpenBLAS/`
3. `make install`
4. Created a sample code, namely:
```C
#include <stdio.h>
#include <math.h>
/* Yes, I'm not using <lapacke.h> and -I key, it doesn't matter rn */
#include "./OpenBLAS/include/lapacke.h"


int main()
{
    /*
        FYI example matrix is taken from:
        https://www.ibm.com/docs/en/essl/6.3?topic=subroutines-sgetrf-dgetrf-cgetrf-zgetrf-general-matrix-factorization
    */
    double A[] =
    {
        1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2, 2.4, 2.6,
        1.2, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2, 2.4,
        1.4, 1.2, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2,
        1.6, 1.4, 1.2, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0,
        1.8, 1.6, 1.4, 1.2, 1.0, 1.2, 1.4, 1.6, 1.8,
        2.0, 1.8, 1.6, 1.4, 1.2, 1.0, 1.2, 1.4, 1.6,
        2.2, 2.0, 1.8, 1.6, 1.4, 1.2, 1.0, 1.2, 1.4,
        2.4, 2.2, 2.0, 1.8, 1.6, 1.4, 1.2, 1.0, 1.2,
        2.6, 2.4, 2.2, 2.0, 1.8, 1.6, 1.4, 1.2, 1.0,
    };
    size_t const    size   = sizeof( A ) / sizeof( A[ 0 ]);
    int32_t const   dim    = sqrt( size );
    int32_t         pivot[ dim ];

    /* Let's try matrix inverse */
    if ( LAPACKE_dgetrf( LAPACK_ROW_MAJOR, dim, dim, A, dim, pivot ) == 0 )
    {
        if ( LAPACKE_dgetri( LAPACK_ROW_MAJOR, dim, A, dim, pivot ) == 0 )
        {
            for ( size_t i = 0; i < size; ++i )
            {
                printf
                (
                    "%s%10.5lf",
                    i % dim == 0 && i != 0
                    ? "\n"
                    : "",
                    A[ i ]
                );
            }
        }
    }
    putc( '\n', stdout );
}
```

Now let's proceed to the problem.

### Compiling and linking against shared library.

1. Input:
```bash
❯ gcc main.c -o test -L./OpenBLAS/lib -lopenblas -lm
❯ ./test
```
2. Output:
```bash
-2.36111     2.50000     0.00000    -0.00000     0.00000    -0.00000     0.00000     0.00000     0.13889
2.50000    -5.00000     2.50000     0.00000    -0.00000     0.00000     0.00000     0.00000    -0.00000
0.00000     2.50000    -5.00000     2.50000     0.00000    -0.00000     0.00000    -0.00000     0.00000
-0.00000     0.00000     2.50000    -5.00000     2.50000     0.00000    -0.00000     0.00000     0.00000
0.00000    -0.00000     0.00000     2.50000    -5.00000     2.50000     0.00000    -0.00000     0.00000
0.00000    -0.00000    -0.00000     0.00000     2.50000    -5.00000     2.50000     0.00000    -0.00000
-0.00000     0.00000    -0.00000    -0.00000     0.00000     2.50000    -5.00000     2.50000     0.00000
0.00000    -0.00000     0.00000    -0.00000    -0.00000     0.00000     2.50000    -5.00000     2.50000
0.13889     0.00000    -0.00000     0.00000     0.00000    -0.00000     0.00000     2.50000    -2.36111
```
Everything is perfect. Result seems to be correct. Mission accomplished.

### Compiling and linking against static library.

1. Input:
```bash
❯ gcc main.c -o test ./OpenBLAS/lib/libopenblas.a -lm
```
2. Output:
```bash
/usr/bin/ld: ./OpenBLAS/lib/libopenblas.a(blas_server.o): in function `blas_thread_init':
blas_server.c:(.text+0x50a): undefined reference to `pthread_create'
/usr/bin/ld: ./OpenBLAS/lib/libopenblas.a(blas_server.o): in function `goto_set_num_threads':
blas_server.c:(.text+0x9be): undefined reference to `pthread_create'
/usr/bin/ld: ./OpenBLAS/lib/libopenblas.a(blas_server.o): in function `blas_thread_shutdown_':
blas_server.c:(.text+0xbe2): undefined reference to `pthread_join'
/usr/bin/ld: ./OpenBLAS/lib/libopenblas.a(blas_server.o): in function `openblas_setaffinity':
blas_server.c:(.text+0x31b): undefined reference to `pthread_setaffinity_np'
/usr/bin/ld: blas_server.c:(.text+0x333): undefined reference to `pthread_setaffinity_np'
/usr/bin/ld: ./OpenBLAS/lib/libopenblas.a(blas_server.o): in function `openblas_getaffinity':
blas_server.c:(.text+0x39b): undefined reference to `pthread_getaffinity_np'
/usr/bin/ld: blas_server.c:(.text+0x3b3): undefined reference to `pthread_getaffinity_np'
collect2: error: ld returned 1 exit status
```

So, why am I seeing all those `pthread` messages, huh?  
Why won't it compile?  
Am I missing something?  
Yes, I'm sure that I "removed `#` before `USE_THREAD`".  

Guide provided [there](https://github.com/OpenMathLib/OpenBLAS/wiki/User-Manual#link-the-library) told me this:
> - Link static library
> ```bash
> gcc -o test test.c /your/path/libopenblas.a
> ```

**Comment by martin-frbg** [comment]
Are you sure that the shared and static libraries are from the same build ? And did you really change the Makefile.rule as step 2, _after_ building the library with default settings ? (This would probably cause the `make install` to redo part of the build, but without a `make clean` in between you would end up with a mix of old and new settings)

**Comment by Xofrio** [comment]
Yep, they are from the same build.

My order was as follows: `make` -> `Makefile.rule` modification -> `make install`.
Then I even tried this: `Makefile.rule` modification -> `make` -> `make install`.

So I went through both paths, but I end up with same result.
And I really want to be able to statically link it.

**Comment by martin-frbg** [comment]
try a `make clean` after modifying Makefile.rule please

**Comment by Xofrio** [comment]
Been there, done that.
That's why I've posted my question.
Guess I can try to make everything on another host probably.

**Comment by martin-frbg** [comment]
The correct order for what you are trying to do is 
```
1. Change Makefile.rule
2. make
3. make install
```
If you follow this, you should find that you only need to link to libm (for the fundamental math functions) and probably the runtime library of your fortran compiler (libgfortran or whatever, for the LAPACK code included with OpenBLAS). When you change your mind halfway through and edit Makefile.rule between the `make` and `install` steps, you'll end up with a mix of object files corresponding to the "old" and "new" configuration.
