### ISSUE TITLE
ZGESVD failure on some matrices of decaying exponentials

### ISSUE THREAD

**Issue by jasonkaye** [xianyi/OpenBLAS#4626]
This is a follow-up to [Issue #4583](https://github.com/OpenMathLib/OpenBLAS/issues/4583), which was closed.

While the problem described in that issue is indeed fixed in OpenBLAS 0.3.27, it persists if one changes the double matrices to complex double, and uses LAPACK_zgesvd instead of LAPACK_dgesvd. However, the modification below fixes the problem in that case as well:

```
diff --git a/kernel/arm64/KERNEL.NEOVERSEN1 b/kernel/arm64/KERNEL.NEOVERSEN1
index 9fe981c58..5b3174473 100644
--- a/kernel/arm64/KERNEL.NEOVERSEN1
+++ b/kernel/arm64/KERNEL.NEOVERSEN1
@@ -93,8 +93,8 @@ IZAMAXKERNEL   = izamax_thunderx2t99.c

 SNRM2KERNEL    = nrm2.S
 DNRM2KERNEL    = nrm2.S
-CNRM2KERNEL    = scnrm2_thunderx2t99.c
-ZNRM2KERNEL    = dznrm2_thunderx2t99.c
+CNRM2KERNEL    = znrm2.S
+ZNRM2KERNEL    = znrm2.S

 DDOTKERNEL     = dot.c
 SDOTKERNEL     = dot.c
```

Should this change be made in OpenBLAS?

**Comment by martin-frbg** [comment]
Unfortunate, but not unlikely given that these were written by the same developer. Sadly I haven't been able to spot the problem in these kernels.
