### ISSUE TITLE
Multi-threaded DGEMM becomes less efficient on many-core CPUs

### ISSUE THREAD

**Issue by yamazakimitsufumi** [xianyi/OpenBLAS#4644]
OpenBLAS DGEMM achieves high efficiency, for example, over 90% of peak performance with 1 thread on Graviton3E, but the efficiency drops to about 73% when running DGEMM with 64 threads.
As is known, it is becoming difficult to keep high efficiency for multi-thread execution on recent many-core CPUs,  even if high-performance kernels are implemented for single-thread execution.

I am considering to adjust the shape of the submatrix handled by each thread by modifying [2D thread distribution](https://github.com/OpenMathLib/OpenBLAS/pull/1320).
I would appreciate it if you could let me know if you have any suggestions.

![graph](https://github.com/OpenMathLib/OpenBLAS/assets/166666378/12597c18-6746-4dcb-995f-d55c40bc4906)

**Comment by brada4** [comment]
8mb matrices are probably less than caches by magnitude.

**Comment by martin-frbg** [comment]
Closing as fixed by your #4655 , thank you again
