### ISSUE TITLE
矩阵的边角问题，请问OpenBlas是如何处理的？【How does OpenBLAS handle the corner cases of matrices?】

### ISSUE THREAD

**Issue by ztjjj9** [xianyi/OpenBLAS#4659]
如果a矩阵大小是7*9；b矩阵大小是9*11
如果分块大小是4*4的话，请问openblas是如何处理b矩阵剩下的那3列呀？
是把b矩阵的列补成4的倍数嘛？
对于a矩阵来说，a矩阵用不用补呢？a矩阵是有专门的边角处理吗？
感谢！
——————————————————————————————————————————————————————————
If matrix A has a size of 7x9 and matrix B has a size of 9x11, and if the block size is 4x4, then how does OpenBLAS handle the remaining 3 columns of matrix B? Are they padded to a multiple of 4?
As for matrix A, does it need padding as well? Does matrix A have special handling for its corners?
Thanks!

**Comment by xianyi** [comment]
The gemm kernel will handle the corner case.

**Comment by ztjjj9** [comment]
Thanks for your prompt response！ So, you mean there’s no need to pad the matrices to specific shapes, as the kernel handles all cases, right?

**Comment by xianyi** [comment]
> Thanks for your prompt response！ So, you mean there’s no need to pad the matrices to specific shapes, as the kernel handles all cases, right?

Yes.  The OpenBLAS/GotoBLAS kernels handle the corner case.

BLIS pad the matrices before gemm micro-kernel.

**Comment by ztjjj9** [comment]
okok，Thanks！
