### ISSUE TITLE
Issues when building openblas 0.3.26 or 0.3.27 with cmake in loongarch64

### ISSUE THREAD

**Issue by azuresky01** [xianyi/OpenBLAS#4660]
Hello,

I want to report some issues when I tried to build openblas 0.3.26 or 0.3.27 with cmake and the solutions to them.

Operating system: Arch Linux loongarch64 (can also be repeated on other systems such as loongnix, AOSC, etc.)
Host: Loongson-3A6000-HV-7A2000-1w-V0.1-EVB

cmake build commands: 
1. CC=gcc FC=gfortran cmake -B build -DCMAKE_INSTALL_PREFIX=/opt/OpenBLAS -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=OFF -DNO_AFFINITY=ON -DUSE_OPENMP=1 -DNO_WARMUP=1
2. cmake --build build
3. cmake --install build

****** When executing command 1, I met the the following error:

CMake Error at cmake/cc.cmake:39 (CHECK_CXX_COMPILER_FLAG):
  Unknown CMake command "CHECK_CXX_COMPILER_FLAG".
Call Stack (most recent call first):
  cmake/system.cmake:332 (include)
  CMakeLists.txt:97 (include)

Solution 1:

step one: at the top of CMakeLists.txt or cmake/cc.cmake add: include(CheckCCompilerFlag)
step two: in cmake/cc.cmake and cmake/fc.cmake in the part related to LOONGARCH64 modify from:
 CHECK_CXX_COMPILER_FLAG("-mabi=lp64d" COMPILER_SUPPORT_LP64D_ABI)  to  CHECK_C_COMPILER_FLAG("-mabi=lp64d" COMPILER_SUPPORT_LP64D_ABI)
 CHECK_CXX_COMPILER_FLAG("-mabi=ilp32d" COMPILER_SUPPORT_ILP32D_ABI)  to  CHECK_C_COMPILER_FLAG("-mabi=ilp32d" COMPILER_SUPPORT_ILP32D_ABI)

Solution 2:

at the top of CMakeLists.txt or cmake/cc.cmake add: include(CheckCXXCompilerFlag)
and also modify the project from: project(OpenBLAS C ASM) to project(OpenBLAS C ASM CXX)

****** When executing command 2 I met the following error:

[ 92%] Building ASM object kernel/CMakeFiles/kernel.dir/CMakeFiles/dsdot_k.S.o
/home/xxx/OpenBLAS-0.3.27/kernel/loongarch64/dot_lasx.S: Assembler messages:
/home/xxx/OpenBLAS-0.3.27/kernel/loongarch64/dot_lasx.S:168: error：no match insn: fsub.s	$f9,$f9,$f9,
make[2]: *** [kernel/CMakeFiles/kernel.dir/build.make:1027：kernel/CMakeFiles/kernel.dir/CMakeFiles/dsdot_k.S.o] error 1
make[1]: *** [CMakeFiles/Makefile2:511：kernel/CMakeFiles/kernel.dir/all] error 2
make: *** [Makefile:146：all] error 2

Solution:
check /home/xxx/OpenBLAS-0.3.27/kernel/loongarch64/dot_lasx.S at the line 168, there is an extra comma before the comment:
    fsub.s    s2,     s2,      s2,  /* set s2 to 0.0 */
so remove it and now it becomes:
    fsub.s    s2,     s2,      s2  /* set s2 to 0.0 */

**Comment by martin-frbg** [comment]
Oops, sorry. Thank you for reporting and providing the solution. 
@XiWeiGu  if you agree I'd go with solution 1 as the build does not actually need to depend on having a C++ compiler installed.

**Comment by XiWeiGu** [comment]
> Oops, sorry. Thank you for reporting and providing the solution. @XiWeiGu if you agree I'd go with solution 1 as the build does not actually need to depend on having a C++ compiler installed.

LGTM

**Comment by azuresky01** [comment]
Sorry for any inconvenience. I just found that there is a stray comma too in the file kernel/loongarch64/dot_lsx.S at the line 168:

https://github.com/OpenMathLib/OpenBLAS/blob/5500b4ab2629c72645b9a2a8785d643908534df5/kernel/loongarch64/dot_lsx.S#L168

Could you remove it as well?

@martin-frbg 
@XiWeiGu

**Comment by martin-frbg** [comment]
Oops, thought I had looked for that ? Gone now, thanks
