### ISSUE TITLE
Compilation fails with GCC14

### ISSUE THREAD

**Issue by busykai** [xianyi/OpenBLAS#4668]
Straightforward `make` would fail (in my case x86-64, Skylake). For example:

```
pstrf.c: In function 'spstrf_':
spstrf.c:830:43: error: passing argument 1 of 'dmaxloc_' from incompatible pointer type [-Wincompatible-pointer-types]
  830 |                         itemp = mymaxloc_(&work[1], &i__4, &i__5, &c__1);
      |                                           ^~~~~~~~
      |                                           |
      |                                           real * {aka float *}
spstrf.c:259:37: note: in definition of macro 'mymaxloc_'
  259 | #define mymaxloc_(w,s,e,n) dmaxloc_(w,*(s),*(e),n)
      |                                     ^
spstrf.c:367:33: note: expected 'double *' but argument is of type 'real *' {aka 'float *'}
  367 | static integer dmaxloc_(double *w, integer s, integer e, integer *n)
      |                         ~~~~~~~~^
```

From the [GCC14 porting guide](https://gcc.gnu.org/gcc-14/porting_to.html#incompatible-pointer-types):

> **Type checking on pointer types (-Werror=incompatible-pointer-types)**
> GCC no longer allows implicitly casting all pointer types to all other pointer types. This behavior is now restricted to the void * type and its qualified variations.
> 
> To fix compilation errors resulting from that, you can add the appropriate casts, and maybe consider using void * in more places (particularly for old programs that predate the introduction of void * into the C language).

**Comment by martin-frbg** [comment]
This is - I believe - addressed already in all "regular" parts of OpenBLAS, but you are getting the error as you are using the f2c-converted fallback version of the LAPACK codes. It should not be an issue if you install/use GCC14's gfortran.

**Comment by martin-frbg** [comment]
As does adding `-Wno-error=incompatible-pointer-types` to the compiler flags, which is probably more sensible than correcting a harmless flaw in around 2500 machine-translated files that only serve as fallback

**Comment by busykai** [comment]
Thanks for the background! The use we give OpenBLAS is very specific and agnostic (ignorant). We do need the C build to work though. Is there a plan to enable the fallback code for gcc14?

**Comment by martin-frbg** [comment]
Let me see if older gccs tolerate the `-Wno-error`, and gcc14.1 isn't even officially released yet... 
Intriguing "very specific" use, guess it must be as a deterrent of some sort :)

**Comment by busykai** [comment]
> Let me see if older gccs tolerate the `-Wno-error`, and gcc14.1 isn't even officially released yet... Intriguing "very specific" use, guess it must be as a deterrent of some sort :)

Our team uses OpenBLAS in order to create a "representative" stress on the system without trying to achieve meaningful results or solve real-world problem. We can work it around, of course, but I thought it would be better if we had a solution at the source. :) Thank you for the fix!
