### ISSUE TITLE
sparse matrix times dense matrix

### ISSUE THREAD

**Issue by jiaen-liu** [xianyi/OpenBLAS#4669]
I'm wondering if OpenBlas support the multiplication between a sparse matrix and a dense matrix.
Thanks

Jiaen

**Comment by martin-frbg** [comment]
OpenBLAS does not have specialized code for handling sparse matrix operations efficiently, use a higher level code like SuiteSparse for that

**Comment by martin-frbg** [comment]
https://github.com/OpenMathLib/OpenBLAS/wiki/Faq#sparse

**Comment by jiaen-liu** [comment]
I will look into this. Thanks for the advice!

Best
Jiaen
