### ISSUE TITLE
Generic target fails to compile

### ISSUE THREAD

**Issue by s-macke** [xianyi/OpenBLAS#467]
A "make TARGET=GENERIC" or "make TARGET=SSE_GENERIC"
fails in creating the libopenblas_generic archive with the error:

"sgemm_kernel.o: No such file or directory" 

The same result in the develop branch.
Tested it with Linux 64 Bit and under Windows with MinGW 32 Bit.

**Comment by xianyi** [comment]
I think we support GENERIC target on x86 and x86-64 now.
