### ISSUE TITLE
../libopenblas_haswellp-r0.3.27.a(cblas_isamax.o): error adding symbols: File in wrong format

### ISSUE THREAD

**Issue by pzhong4** [xianyi/OpenBLAS#4670]
export PATH=/opt/aarch64/gcc7.3/bin/:${PATH}

make BINARY=64 CC=aarch64-linux-gnu-gcc FC=aarch64-linux-gnu-gfortran HOSTCC=gcc TARGET=CORTEXA53 AR=aarch64-linux-gnu-gcc-ar AS=aarch64-linux-gnu-as ONLY_CBLAS=1  #pass

make PREFIX=./_install  #error

error message:
ar: `u' modifier ignored since `D' is the default (see `U')
ranlib ../../../libopenblas_haswellp-r0.3.27.a
make[3]: Leaving directory '/home/zhongpeng/work/source/OpenBLAS/lapack-netlib/LAPACKE/utils'
make[2]: Leaving directory '/home/zhongpeng/work/source/OpenBLAS/lapack-netlib/LAPACKE'
make[1]: Leaving directory '/home/zhongpeng/work/source/OpenBLAS/lapack-netlib'
make[1]: Entering directory '/home/zhongpeng/work/source/OpenBLAS/exports'
cc -O2 -DSMALL_MATRIX_OPT -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=16 -DMAX_PARALLEL_NUMBER=1 -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.27\" -msse3 -mssse3 -msse4.1 -mavx -mavx2 -mavx2 -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  -shared -o ../libopenblas_haswellp-r0.3.27.so \
-Wl,--whole-archive ../libopenblas_haswellp-r0.3.27.a -Wl,--no-whole-archive \
-Wl,-soname,libopenblas.so.0 -lm -lpthread -lgfortran -lm -lpthread -lgfortran
/usr/bin/ld: ../libopenblas_haswellp-r0.3.27.a(cblas_isamax.o): Relocations in generic ELF (EM: 183)
../libopenblas_haswellp-r0.3.27.a(cblas_isamax.o): error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
Makefile:207: recipe for target '../libopenblas_haswellp-r0.3.27.so' failed
make[1]: *** [../libopenblas_haswellp-r0.3.27.so] Error 1
make[1]: Leaving directory '/home/zhongpeng/work/source/OpenBLAS/exports'
Makefile:140: recipe for target 'shared' failed
make: *** [shared] Error 2

**Comment by martin-frbg** [comment]
Please repeat all the options from the initial`make` run when you do the `make install`. Otherwise the build will just start anew and assume that you are trying to build for your current (Haswell) system - that is why there suddenly is a conflict with the aarch64 object files

**Comment by pzhong4** [comment]
I finally found that I had used the wrong command, lacking the ”install“
make PREFIX=./_install **install**

**Comment by pzhong4** [comment]
close this issue and thanks for your help @martin-frbg
