### ISSUE TITLE
Building without `-DDYNAMIC_ARCH=ON` failed on Windows

### ISSUE THREAD

**Issue by moderato** [xianyi/OpenBLAS#4697]
Hi there, I'm trying to build OpenBLAS on a Windows machine with AMD CPU on Anaconda Prompt. Enabling `-DDYNAMIC_ARCH=ON` works well but takes a lot of time to build. It somehow fails, however, when I remove this flag. Anyone knows how to fix this issue?

### Error message:
```
-- GETARCH results:
CORE=COOPERLAKE
LIBCORE=cooperlake
NUM_CORES=12
HAVE_MMX=1
HAVE_SSE=1
HAVE_SSE2=1
HAVE_SSE3=1
HAVE_SSSE3=1
HAVE_SSE4_1=1
HAVE_SSE4_2=1
HAVE_SSE4A=1
HAVE_AVX=1
HAVE_AVX2=1
HAVE_AVX512VL=1
HAVE_AVX512BF16=1
HAVE_FMA3=1
MAKEFLAGS += -j 12

-- Compiling a 64-bit binary.
clang-cl: warning: unknown argument ignored in clang-cl: '-dumpversion' [-Wunknown-argument]
clang-cl: error: no input files
CMake Error at cmake/cc.cmake:143 (if):
  if given arguments:

    "VERSION_GREATER" "10.1" "OR" "VERSION_EQUAL" "10.1"

  Unknown arguments specified
Call Stack (most recent call first):
  cmake/system.cmake:332 (include)
  CMakeLists.txt:104 (include)


-- Configuring incomplete, errors occurred!
```

### CMake command:
```
cmake .. -G "Ninja" -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DCMAKE_Fortran_COMPILER=flang -DCMAKE_MT=mt -DBUILD_BFLOAT16=ON -DBUILD_WITHOUT_LAPACK=yes -DNOFORTRAN=1 -DDYNAMIC_ARCH=ON -DCMAKE_BUILD_TYPE=Release
```

**Comment by martin-frbg** [comment]
Meh... clang supports `-dumpversion` for version information, and I am fairly sure that clang-cl used to keep quiet about options it did not understand. But CMAKE already queried the compiler version for us anyway, so that entire line should be replaced by `SET (GCC_VERSION ${CMAKE_C_COMPILER_VERSION} )

**Comment by moderato** [comment]
Thanks for the fix Martin, it works well. There might be a type in the PR and I commented there.
