### ISSUE TITLE
DTRTRS fails when using lowercase character arguments

### ISSUE THREAD

**Issue by rainbowsend** [xianyi/OpenBLAS#4701]
dear devs,

The subroutine [DTRTRS](https://netlib.org/lapack/explore-html/d4/dc1/group__trtrs_gab0b6a7438a7eb98fe2ab28e6c4d84b21.html#gab0b6a7438a7eb98fe2ab28e6c4d84b21) throws the error `On entry to DTRTRS parameter number  3 had an illegal value` when using lowercase letters for the character input arguments  `uplo` or `diag`. I expected that these arguments are not case-sensitive as in other LAPACK routines. Of course this is easy to fix by using capital letters, but it is inconsistent to the calls of other LAPACK routines.

This error occurred on a dual socket Intel(R) Xeon(R) Platinum 8468 ("Sapphire Rapids") computer with OpenBLAS/0.3.20, compiled with GCC-11.3.0  and installed via [easybuild](https://docs.easybuild.io/common-toolchains/#toolchains_diagram)).

**Comment by martin-frbg** [comment]
This has actually been found and fixed about a month ago (PR #4598), the fix luckily made it into the current release (0.3.27) one day later.

**Comment by rainbowsend** [comment]
great, sorry for overlooking this
