### ISSUE TITLE
`cblas_sbstobf16` seg fault for big shapes

### ISSUE THREAD

**Issue by moderato** [xianyi/OpenBLAS#4706]
Hi, I was trying to convert an array from fp32 to bf16 using the function `cblas_sbstobf16`. However I got a segmentation fault when the size of the array becomes big (e.g. 16777216 in my test program). Anyone could help?

### Test Program Code
```
#include <iostream>
#include <vector>
#include "cblas.h"

int main(int argc, char const *argv[])
{

    for (int shape = 2; shape < 4294967296; shape *= 2) {
        std::vector<float> input_fp32_vec(shape, 1.0f);
        std::vector<bfloat16> input_bf16_vec(shape, 0.0f);
        auto input_fp32 = &input_fp32_vec[0];
        auto input_bf16 = &input_bf16_vec[0];

        cblas_sbstobf16(shape, input_fp32, 1, input_bf16, 1);
        std::cout << "Converted vector of shape " << shape << " from fp32 to bf16." << std::endl;
    }
    return 0;
}
```

### Build Commands
(I built and ran the code both WSL and Anaconda Prompt and had the same problem. Only the build commands of WSL are provided here.)
```
g++ -c -o test_sbstobf16.o test_sbstobf16.cc -I/mnt/c/Users/moderato/Documents/repos/build/OpenBLAS/linux/include/openblas
g++ -o test_sbstobf16 test_sbstobf16.o -I/mnt/c/Users/moderato/Documents/repos/build/OpenBLAS/linux/include/openblas -L/mnt/c/Users/moderato/Documents/repos/build/OpenBLAS/linux/lib -lopenblas
```

### Example Output
```
Converted vector of shape 2 from fp32 to bf16.
Converted vector of shape 4 from fp32 to bf16.
Converted vector of shape 8 from fp32 to bf16.
Converted vector of shape 16 from fp32 to bf16.
Converted vector of shape 32 from fp32 to bf16.
Converted vector of shape 64 from fp32 to bf16.
Converted vector of shape 128 from fp32 to bf16.
Converted vector of shape 256 from fp32 to bf16.
Converted vector of shape 512 from fp32 to bf16.
Converted vector of shape 1024 from fp32 to bf16.
Converted vector of shape 2048 from fp32 to bf16.
Converted vector of shape 4096 from fp32 to bf16.
Converted vector of shape 8192 from fp32 to bf16.
Converted vector of shape 16384 from fp32 to bf16.
Converted vector of shape 32768 from fp32 to bf16.
Converted vector of shape 65536 from fp32 to bf16.
Converted vector of shape 131072 from fp32 to bf16.
Converted vector of shape 262144 from fp32 to bf16.
Converted vector of shape 524288 from fp32 to bf16.
Converted vector of shape 1048576 from fp32 to bf16.
Converted vector of shape 2097152 from fp32 to bf16.
Converted vector of shape 4194304 from fp32 to bf16.
Converted vector of shape 8388608 from fp32 to bf16.
Segmentation fault
```

**Comment by martin-frbg** [comment]
Most likely "only" an index overflow, given the big dimension - you need to build OpenBLAS with INTERFACE64=1 (which turns all 32bit "int" variables into 64bit "long" for extended value range)

**Comment by moderato** [comment]
> Most likely "only" an index overflow, given the big dimension - you need to build OpenBLAS with INTERFACE64=1 (which turns all 32bit "int" variables into 64bit "long" for extended value range)

Thanks for the info. The seg fault is gone now. However when I applied those converted vectors to `cblas_sbgemm` I did see the deviation from fp32 reference values getting too big e.g. > 0.1. Any ideas why it happens?

**Comment by martin-frbg** [comment]
accumulation of rounding errors would be my guess - bf16 _is_ reduced precision after all

**Comment by moderato** [comment]
> accumulation of rounding errors would be my guess - bf16 _is_ reduced precision after all

So I figured out there might be some data range issue in my test case. I shrink the input data to 0.1x and loose the atol from 0.01 to 0.025 and it passed. Thanks anyway!
