### ISSUE TITLE
0.3.27 fails zscal tests when compiled with Intel icx

### ISSUE THREAD

**Issue by zzzoom** [xianyi/OpenBLAS#4713]
Building 0.3.27 (with Spack but it didn't apply any patches) using both Intel OneAPI 2024.0.0 and 2024.1.0 fails the test suite with:
```
TEST 39/67 zscal:i_nan [FAIL]
  ERR: test_zscal.c:21  should be true
TEST 40/67 zscal:i_nan_inc_2 [FAIL]
  ERR: test_zscal.c:35  should be true
TEST 41/67 zscal:nan_i [FAIL]
  ERR: test_zscal.c:46  should be true
TEST 42/67 zscal:nan_i_inc_2 [FAIL]
  ERR: test_zscal.c:60  should be true
```

[Build log](https://github.com/OpenMathLib/OpenBLAS/files/15414146/spack-build-out.txt)

**Comment by martin-frbg** [comment]
what hardware (cpu) did you use for the build (and test) please ?

**Comment by zzzoom** [comment]
I've been able to reproduce this with:
- OneAPI 2023.0.0 on Intel Broadwell and `'TARGET=HASWELL' 'DYNAMIC_ARCH=1'`.
- OneAPI 2024.0.0 and 2024.1.0 on AMD Zen4 and `'TARGET=ZEN' 'DYNAMIC_ARCH=1'`.

**Comment by martin-frbg** [comment]
Thank you. Strangely it seems to be optimizing away the argument checks that have been put in the zscal code precisely to fix this scenario...

**Comment by martin-frbg** [comment]
Looks like it is not even reaching the zscal kernel when building with a recent oneAPI - apparently it hits the quick return in the interface code where it checks if the scale factor alpha is equal to 1. So NaN is equal to any number when one asks icx ?

**Comment by zzzoom** [comment]
Oh. It's that `-fp-model fast` default, isn't it.

Yeah, that seems to be the case.

**Comment by martin-frbg** [comment]
"fast and furious" apparently. I guess that needs to be overridden in the Makefiles, no good to put pragmas in individual files that are affected _now_ grrrr
