### ISSUE TITLE
double inclusion from Makefile.system

### ISSUE THREAD

**Issue by matzeri** [xianyi/OpenBLAS#472]
As I build with all warning enable, on all *.o compilations I see:

gcc -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/pub/deve
l/openblas/openblas-0.2.13-1.x86_64/build=/usr/src/debug/openblas-0.2.13-1 -fdeb
ug-prefix-map=/pub/devel/openblas/openblas-0.2.13-1.x86_64/src/OpenBLAS-0.2.13=/
usr/src/debug/openblas-0.2.13-1 -O2 -Wall -m64 -DF_INTERFACE_GFORT -DDYNAMIC_ARC
H -DNO_LAPACK -DNO_LAPACKE -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=16 -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I. -O2 -Wall -m64 -DF_INTERFACE_GFORT -DDYNAMIC_ARCH -DNO_LAPACK -DNO_LAPACKE -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=16 -DASMNAME=sswap -DASMFNAME=sswap_ -DNAME=sswap_ -DCNAME=sswap -DCHAR_NAME=\"sswap_\" -DCHAR_CNAME=\"sswap\" -DNO_AFFINITY -I.. -I. -UDOUBLE  -UCOMPLEX -c swap.c -o sswap.o
<command-line>:0:0: warning: "ASMNAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "ASMFNAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "NAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "CNAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "CHAR_NAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "CHAR_CNAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "ASMNAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "ASMFNAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "NAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "CNAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "CHAR_NAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
<command-line>:0:0: warning: "CHAR_CNAME" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition

This is caused by Makefile.system to be included two times:
1) in the makefile at root level where most of the variable are yet not defined
2) in the makefile's where the source are 

so command like
CCOMMON_OPT     += -DASMNAME=$(FU)$(*F) -DASMFNAME=$(FU)$(*F)$(BU) -DNAME=$(*F)$(BU) -DCNAME=$(*F) -DCHAR_NAME=\"$(*F)$(BU)\" -DCHAR_CNAME=\"$(*F)\"

are executed 2 times, creating a double chain of definitions.
I counted that a full build logging is 118K lines but 98K are just
"<command-line>:0:0:.." ones. 

Is it possible to split the Makefile.system in 2:
- what is needed at root level
- what is needed at source level
to avoid this very annoying problem ?

**Comment by jakirkham** [comment]
So, this got closed, but it doesn't seem there was a fix. Am I missing something?

**Comment by matzeri** [comment]
No fix, that I am aware but  #818 is equivalent
