### ISSUE TITLE
gemm3m test failed

### ISSUE THREAD

**Issue by XiWeiGu** [xianyi/OpenBLAS#4737]
Testing platform：

> 架构：                              x86_64
> CPU 运行模式：                      32-bit, 64-bit
> 字节序：                            Little Endian
> Address sizes:                      36 bits physical, 48 bits virtual
> CPU:                                8
> 在线 CPU 列表：                     0-7
> 每个核的线程数：                    2
> 每个座的核数：                      4
> 座：                                1
> NUMA 节点：                         1
> 厂商 ID：                           GenuineIntel
> CPU 系列：                          6
> 型号：                              58
> 型号名称：                          Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
> 步进：                              9
> CPU MHz：                           1600.000
> CPU 最大 MHz：                      3900.0000
> CPU 最小 MHz：                      1600.0000
> BogoMIPS：                          6784.31
> L1d 缓存：                          128 KiB
> L1i 缓存：                          128 KiB
> L2 缓存：                           1 MiB
> L3 缓存：                           8 MiB
> NUMA 节点0 CPU：                    0-7

Testing command: `make TARGET=GENERIC NO_LAPACK=1`
Testing results:

>  cblas_cgemm3 PASSED THE TESTS OF ERROR-EXITS
> 
>  ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
>                        EXPECTED RESULT                    COMPUTED RESULT
>        1  (   0.476726E-01,   0.695009E-01)  (  -0.872175E-01,   0.656287E-01)
>       THESE ARE THE RESULTS FOR COLUMN   1
>  ******* cblas_cgemm3m FAILED ON CALL NUMBER:
>    5026: cblas_cgemm3m( CblasColMajor,  CblasNoTrans,  CblasNoTrans,
>             1,  5,  2, ( 1.0, 0.0) , A,  2, B,  3, ( 0.0, 0.0) , C,  2).
>  ******* cblas_cgemm3m FAILED ON CALL NUMBER:
>    3403: cblas_cgemm3m( CblasRowMajor,  CblasNoTrans,  CblasNoTrans,
>             1,  1,  0, ( 0.0, 0.0) , A,  2, B,  1, ( 0.0, 0.0) , C,  2).
> 
>  ******* FATAL ERROR - TESTS ABANDONED *******
> OPENBLAS_NUM_THREADS=2 ./xzcblat3_3m < zin3_3m
> TESTS OF THE COMPLEX*16        LEVEL 3 BLAS
> 
>  THE FOLLOWING PARAMETER VALUES WILL BE USED:
>    FOR N                   0     1     2     3     5     9    35
>    FOR ALPHA          ( 0.0, 0.0)  ( 1.0, 0.0)  ( 0.7,-0.9)
>    FOR BETA           ( 0.0, 0.0)  ( 1.0, 0.0)  ( 1.3,-1.1)
> 
>  ROUTINES PASS COMPUTATIONAL TESTS IF TEST RATIO IS LESS THAN   16.00
> 
>  COLUMN-MAJOR AND ROW-MAJOR DATA LAYOUTS ARE TESTED
> 
>  RELATIVE MACHINE PRECISION IS TAKEN TO BE  2.2E-16
> 
>  cblas_zgemm3 PASSED THE TESTS OF ERROR-EXITS
> 
>  ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
>                        EXPECTED RESULT                    COMPUTED RESULT
>        1  (   0.140886    ,  -0.953292E-01)  (  -0.724470E-01,   0.217884    )
>       THESE ARE THE RESULTS FOR COLUMN   1
>  ******* cblas_zgemm3m FAILED ON CALL NUMBER:
>    6403: cblas_zgemm3m(  CblasColMajor,  CblasNoTrans,  CblasNoTrans,
>             1,  5,  2, ( 1.0, 0.0) , A,  2, B,  3, ( 0.0, 0.0) , C,  2).
>  ******* cblas_zgemm3m FAILED ON CALL NUMBER:
>    4537: cblas_zgemm3m(  CblasRowMajor,  CblasNoTrans,  CblasNoTrans,
>             1,  1,  0, ( 0.0, 0.0) , A,  2, B,  1, ( 0.0, 0.0) , C,  2).
> 
>  ******* FATAL ERROR - TESTS ABANDONED *******

**Comment by martin-frbg** [comment]
Oops. I do not think the generic target should be attempting to do GEMM3M at all - this looks to be a black hole that xianyi created nine years ago by committing some debug code. :(

**Comment by XiWeiGu** [comment]
Should we consider removing it then?

**Comment by martin-frbg** [comment]
I'm going to disable it in the Makefile for now - have not yet checked if the ?gemm3mkernel_dump.c in kernel/generic could be used as a starting point for an eventual implementation.
