### ISSUE TITLE
ARM performance library comparisons

### ISSUE THREAD

**Issue by jianshu93** [xianyi/OpenBLAS#4744]
Dear OpenBLAS team,

Just curious how OpenBLAS on ARM will look like when compared to the ARM official performance library here, on ARM CPUs: https://developer.arm.com/Tools%20and%20Software/Arm%20Performance%20Libraries.  It is only for ARM CPUs though.

Thanks,

Jianshu

**Comment by martin-frbg** [comment]
I don't have data for that right now , best you do the comparison on the hardware and functions you want to use. I expect performance will be pretty similar for GEMM, but OpenBLAS does not yet have SVE kernels for every function where it would make sense (e.g. complex dot product has fairly poor performance)

**Comment by jianshu93** [comment]
I will probably run some test on M1 chips since both can be easily installed on my Mac. What other functions you suggest I can test except GEMM?

Thanks,

Jianshu

**Comment by martin-frbg** [comment]
I'd think DOT and AXPY, as a number of other BLAS functions can/will be implemented in terms of them. Maybe TRMM for completeness (will not necessarily be close to GEMM). Of course M1 is a bit special as it does not provide SVE support - on the other hand, if you (can) include Apple's own Accelerate library in your comparison you gain access to the (officially) undocumented matrix math coprocessor (AMX).

**Comment by martin-frbg** [comment]
to be followed up at some point in the future in https://github.com/OpenMathLib/BLAS-Benchmarks/issues/8
