### ISSUE TITLE
Build Error: Cannot build OpenBLAS with OpenMP enabled and having NUM_PARALLEL > 30

### ISSUE THREAD

**Issue by shivammonaka** [xianyi/OpenBLAS#4745]
I am doing some experiment, I want to build OpenBLAS with OpenMP enabled with NUM_PARALLEL=60 on a 64 core machine. I know it might have some issues during run-time but I am not even able to build it.

It fails this check always:
![image](https://github.com/OpenMathLib/OpenBLAS/assets/140997965/ed74904a-3766-4331-8608-19a508375d13)

Please let me know how to fix this issue.

**Comment by martin-frbg** [comment]
I suspect you may be running out of stack space, check your ulimit settings ?

**Comment by shivammonaka** [comment]
I tried with `ulimit -s unlimited`, Still the same issue

**Comment by martin-frbg** [comment]
it is running out of memory in the "fork after fork" test - where it tries to fork another 64-thread instance from the already forked process. If you really need to experiment with this, comment out the fork tests in the utest makefile

**Comment by martin-frbg** [comment]
I will add `perror` statements to the test case later when I have time - they should make it clearer why the test failed
