### ISSUE TITLE
Cross compile problem

### ISSUE THREAD

**Issue by jsmith173** [xianyi/OpenBLAS#4756]
I'm trying to cross compile OpenBLAS on Ubuntu 22 (to Windows)
My cmake config

````
#!/bin/sh
SRCDIR=$HOME/work/OpenBLAS-0.3.27
ARCHDIR=$HOME/blas_cross

cmake \
-DCMAKE_SYSTEM_NAME="Linux" \
-DCMAKE_TRY_COMPILE_TARGET_TYPE="STATIC_LIBRARY" \
-DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc \
-DCMAKE_SYSTEM_PROCESSOR="x86_64" \
-DCMAKE_INSTALL_PREFIX=$ARCHDIR \
-DBUILD_SHARED_LIBS=ON \
-DBUILD_STATIC_LIBS=ON \
-DUSE_THREAD=ON \
-DNUM_THREADS=64 \
-DUSE_OPENMP=ON \
-DTARGET=CORE2 \
-DDYNAMIC_ARCH=ON \
$SRCDIR

cmake --build .
````

Error messages

````
/home/xxx/work/OpenBLAS-0.3.27/kernel/x86_64/amax_sse.S: Assembler messages:
/home/xxx/work/OpenBLAS-0.3.27/kernel/x86_64/amax_sse.S:55: Warning: .type pseudo-op used outside of .def/.endef: ignored.
/home/xxx/work/OpenBLAS-0.3.27/kernel/x86_64/amax_sse.S:55: Error: junk at end of line, first unrecognized character is `s'
/home/xxx/work/OpenBLAS-0.3.27/kernel/x86_64/amax_sse.S:475: Warning: .size pseudo-op used outside of .def/.endef: ignored.
/home/xxx/work/OpenBLAS-0.3.27/kernel/x86_64/amax_sse.S:475: Error: junk at end of line, first unrecognized character is `s'
/home/xxx/work/OpenBLAS-0.3.27/kernel/x86_64/amax_sse.S:475: Error: junk at end of line, first unrecognized character is `-'
gmake[2]: *** [kernel/CMakeFiles/kernel_SAPPHIRERAPIDS.dir/build.make:75: kernel/CMakeFiles/kernel_SAPPHIRERAPIDS.dir/CMakeFiles/samax_k_SAPPHIRERAPIDS.S.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1060: kernel/CMakeFiles/kernel_SAPPHIRERAPIDS.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2

````

Please help

**Comment by martin-frbg** [comment]
looks like it's not picking up that you are cross-compiling, maybe try adding `-DCMAKE_CROSSCOMPILING=ON`

**Comment by jsmith173** [comment]
I have added this option but I still have this error messages.

**Comment by martin-frbg** [comment]
haven't had time to debug this yet, but fairly sure your CMAKE_SYSTEM_NAME should reflect the target i.e. Windows not Linux, and you'll also need CMAKE_SYSTEM_VERSION to be defined as well for the former to take any effect

**Comment by martin-frbg** [comment]
You definitely need to set `-DCMAKE_SYSTEM_NAME="Windows"` not Linux - setting CMAKE_SYSTEM_VERSION to whatever SDK version your Windows target has is likely optional for  what OpenBLAS does. Tested on Ubuntu22 with the mingw-gcc10 that comes with it.

**Comment by jsmith173** [comment]
Did you compiled to 100% ?
It is better but I still have problems at 44%.

Could you copy your cmake invocation here?

**Comment by martin-frbg** [comment]
Have only tried `cmake -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc -DCMAKE_Fortran_COMPILER=x86_64-w64-mingw32-gfortran -DTARGET=HASWELL -DCMAKE_SYSTEM_NAME="Windows"` so far but do not expect OpenMP or DYNAMIC_ARCH to make a difference. (Currently at 84% with these two added)

**Comment by jsmith173** [comment]
Thanks. It is working now.
