### ISSUE TITLE
dgemv is not thread safe

### ISSUE THREAD

**Issue by susilehtola** [xianyi/OpenBLAS#477]
I found out to my surprise that OpenBLAS is not thread safe.

Running in parallel with OpenMP, each thread running an eigenvalue decomposition of the same matrix yields a different result than running the decomposition in sequential mode.

**Comment by IvanUkhov** [comment]
@susilehtola, may I ask if what you did was only uncommenting [this](https://github.com/xianyi/OpenBLAS/blob/v0.2.18/Makefile.rule#L160) line. Was there anything else? What puzzles me a mite is that you experienced this problem when calling `dgemv`, but this routine belongs to BLAS, not LAPACK. Probably that flag affects both then.

**Comment by susilehtola** [comment]
@IvanUkhov IIRC the only change I did was adding the -frecursive flag to the Fedora netlib BLAS/LAPACK package, after which OpenBLAS worked as its supposed to.

But this was 1.5 years ago, and the Fedora package has changed since then due to changed guidelines. Now the packages are always built with -frecursive enabled.

BTW the comment "enable this flag only on 64bit Linux and if you need a thread safe lapack library" is rather misguiding: the -frecursive flag isn't exclusive to 64-bit, it's necessary on all architectures to make the library thread safe.

**Comment by IvanUkhov** [comment]
@susilehtola, thanks a lot!
