### ISSUE TITLE
cblas.h has incorrect declarations when using 

### ISSUE THREAD

**Issue by mattip** [xianyi/OpenBLAS#4771]
From MacPython/openblas-libs#163:
> `cblas.h` contains
  ```
  typedef void (*scipy_openblas_dojob_callback)64_(int thread_num, void *jobdata, int dojob_data);
  typedef void (*scipy_openblas_threads_callback)64_(int sync, ...
  ```

Note the stray `64_`, which should be follow the `callback` and not the `)`. This build is defining these arguments to `make`:
```
SYMBOLSUFFIX=64_ LIBNAMESUFFIX=64_ SYMBOLPREFIX=scipy_ LIBNAMEPREFIX=scipy_ FIXED_LIBNAME=1
```

I am not sure how those headers are getting generated. cc @serge-sans-paille

**Comment by martin-frbg** [comment]
I note the complete lack of a function name, and the scipy...callback cast must have been created by a script downstream from me - could this be a regex replace going wrong on your side ?

**Comment by mattip** [comment]
The beginning of this is in this repo here https://github.com/OpenMathLib/OpenBLAS/blob/1ba1b9c357fb7d5916a56a6c388b4aea47aad395/cblas.h#L30

I think the function names are `*openblas_dojob_callback` and `*openblas_threads_callback`, the suffix is being applied before the `(` (which is correct) but after the `)` (which is wrong). Ahh, is this renaming done in my repo, and you only do library renaming in this repo?

**Comment by isuruf** [comment]
https://github.com/OpenMathLib/OpenBLAS/blob/1ba1b9c357fb7d5916a56a6c388b4aea47aad395/Makefile.install#L83 is probably the culprit

**Comment by martin-frbg** [comment]
apologies for that - I had not even realized that this was about current develop and fallout from #4577 - indeed the sed logic was not yet ready for parenthesized expressions as introduced by that PR.
I will try to resume normal work tomorrow
