### ISSUE TITLE
SVE support for SGEMV kernel and DGEMV kernel on A64FX

### ISSUE THREAD

**Issue by iha-taisei** [xianyi/OpenBLAS#4786]
Issue #4779 may also discuss similar improvements, but I am not sure if the target platform is the same as mine, so I am posting this issue.
The SGEMV kernel and DGEMV kernel on A64FX do not currently use SVE, so they do not seem to have enough performance. This may not be a problem on NeoverseV1, since it can execute four 128-bit NEON instructions per cycle, which is the same number of floating operations as executing two 256-bit SVE instructions.  However, A64FX executes two 512-bit SVE or two 128-bit NEON arithmetic instructions per cycle, so the current SGEMV kernel and DGEMV kernel do not perform well.
So I am thinking of providing new kernels using SVE specifically for the A64FX.

**Comment by martin-frbg** [comment]
closing as fixed by your #4803
