### ISSUE TITLE
DYNAMIC_ARCH does not support A64FX

### ISSUE THREAD

**Issue by yamazakimitsufumi** [xianyi/OpenBLAS#4808]
Hello

DYNAMIC_ARCH does not currently support A64FX.
https://github.com/OpenMathLib/OpenBLAS/blob/develop/Makefile.system#L683
When I built OpenBLAS with DYNAMIC_ARCH=1 and ran it on an A64FX, ARMV8SVE was selected.
However, as mentioned in Pull Request #4803  , A64FX has different characteristics from other CPUs with SVE.
Therefore, it is better to have separate kernels for A64FX from those for ARMV8SVE.

**Comment by martin-frbg** [comment]
Ah yes, that is kind of a holdover from when it was the only SVE target, somehow its kernels then got a bit cannibalized for the more easily accessible Neoverse designs. I guess the alternative to having it as a separate entry in DYNAMIC_ARCH would be to update the GEMV entries in ARMV8SVE to your new kernels and add overrides to keep using the NEON ones on Neoverse. (Not sure what is better here - I guess we may want to avoid the multitude of targets the x86_64 DYNAMIC_ARCH/DYNAMIC_OLDER build has, but we are still a fair bit away from that)

**Comment by Mousius** [comment]
I will look at GEMV and see if we can move it to the ARMV8SVE target as a first step 😸
