### ISSUE TITLE
incompatible-pointer-types error while building with conan

### ISSUE THREAD

**Issue by Giully271** [xianyi/OpenBLAS#4812]
Hello I hope you are doing well. I'm trying to use openblas with conan but the compilation fails with: 
lapack-netlib/SRC/spstf2.c:796:35: error: passing argument 1 of ‘dmaxloc_’ from incompatible pointer type [-Wincompatible-pointer-types]
   itemp = mymaxloc_(&work[1], &i__2, &i__3, &c__1); (converting a float* to a double*)
The same error is also in:
lapack-netlib/SRC/spstrf.c

I'm compiling with gcc14. 

Thanks for your time and your work.

**Comment by martin-frbg** [comment]
Oh, right - that is an error I must have introduced a while back when I did the f2c translations of the original Fortran code, sorry. Surely the declaration of mymaxloc near the top of the file should be choosing between dmaxloc and smaxloc depending on the size of the first argument, not sure why I commented that out in favor of mapping to dmaxloc everywhere...
