### ISSUE TITLE
DllMain for static lib

### ISSUE THREAD

**Issue by RyderFL** [xianyi/OpenBLAS#4824]
Hi,
I'm using openblas as a static library on windows visual studio.  I linked it to a dynamic library. But i get an error:
`> 1>dllmain.obj : error LNK2005: DllMain 已经在 openblas.lib(memory.obj) 中定义`
I review #4561, found that DllMain will call gotoblas_init, gotoblas_quit. 
But if is it possible to provide a switch for static library to disable DllMain, and export gotoblas_init, gotoblas_quit for calling in other place? it may be easy use under some condition.

**Comment by martin-frbg** [comment]
this has come up before, but I do not know what one is allowed to do in this case on Windows (search issues and discussions here for openblas_init or gotoblas_init). Does it work when you call blas_thread_init() from your code ?

**Comment by RyderFL** [comment]
@martin-frbg Thanks. I found #1652, #1661. But it not really for this conflict. I found the easy way is disable my DllMain and link it directy in static lib. Any way, this work for me. Thanks again.
