### ISSUE TITLE
Failed to build OpenBLAS on power8 system

### ISSUE THREAD

**Issue by ma-chao** [xianyi/OpenBLAS#485]
Hello all,

I tried to build OpenBLAS on power8 system (os ubuntu 14.10), I met these errors:
../common_param.h:850:23: error: ‘GEMM_DEFAULT_OFFSET_B’ undeclared (first use in this function)
 #define GEMM_OFFSET_B GEMM_DEFAULT_OFFSET_B

I did some search on web, it shows I didn't set the "TARGET", I checked the "getarch.c" file and there is no choice for power8, so I tried to use "TARGET=POWER6" instead.

After I used "TARGET=POWER6", I met these errors when it tried to build lapack:
/usr/bin/ld: ../libgoto2_power6p-r1.13.a(lsame.o): ABI version 1 is not compatible with ABI version 2 output

Any idea about it?

Thank you for your help.
Chao

**Comment by xianyi** [comment]
I am going to close this issue.
Please don't hesitate to reopen the issue if you have any questions.
