### ISSUE TITLE
search path for openmp

### ISSUE THREAD

**Issue by paulandrewjohnson** [xianyi/OpenBLAS#4858]
I am trying to make OpenBLAS on a Mac (i7 Intel chip).

I get to
`[ 98%] Linking C shared library lib/libopenblas.dylib
ld: warning: search path '/opt/local/lib/libomp' not found`

libomp was installed with homebrew and I know it is located at
/usr/local/opt/libomp
rather than
/opt/local/lib/libomp

Can I set an environment variable so that make will find the correct path?

**Comment by martin-frbg** [comment]
I'm not that familiar with homebrew, but from https://github.com/Homebrew/brew/issues/13481 (which seems to mostly boil down to "no solution, except that it magically works when you have brew install things in /usr/local") you can probably set DYLD_LIBRARY_PATH

**Comment by martin-frbg** [comment]
Seems to work just fine in our Azure CI setup even when I update that to use the latest available OS with homebrew, so may be a local problem with your homebrew installation.
