### ISSUE TITLE
Build OpenBLAS on NVIDIA Grace (NeoVerseV2)

### ISSUE THREAD

**Issue by Kihang-Youn** [xianyi/OpenBLAS#4867]
Hi, I am trying build OpenBLAS v0.3.28 on NVIDIA Grace like below.

1) Cannot find rule/config.h and cannot matched -march option from Makefile.arm64 (-march=armv9-a -mtune=neoverse-v2)

```
> make TARGET=NEOVERSEV2 DYNAMIC_ARCH=1
getarch.c:1781:2: error: #error "The TARGET specified on the command line or in Makefile.rule is not supported. Please choose a target from TargetList.txt"
1781 | #error "The TARGET specified on the command line or in Makefile.rule is not supported. Please choose a target from TargetList.txt"
|  ^~~~~
make: *** [Makefile.prebuild:100: getarch] Error 1

make[1]: Entering directory '/apps/openblas/OpenBLAS/interface'
cc -O2 -DSMALL_MATRIX_OPT -DGEMM_GEMV_FORWARD -DMAX_STACK_ALLOC=2048 -Wall -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER= -DMAX_PARALLEL_NUMBER=1 -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.28.dev\" -march=armv8-a -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME=saxpy -DASMFNAME=saxpy -DNAME=saxpy -DCNAME=saxpy -DCHAR_NAME=\"saxpy\" -DCHAR_CNAME=\"saxpy\" -DNO_AFFINITY -I.. -I. -UDOUBLE  -UCOMPLEX -c axpy.c -o saxpy.o
In file included from axpy.c:40:
../common.h:62:10: fatal error: config.h: No such file or directory
compilation terminated.
```
2) How do I build using the information below?
added support for the NeoverseV2 cpu in DYNAMIC_ARCH builds

Here is my error message, please correct me, Thanks.

**Comment by martin-frbg** [comment]
Please use a more generic cpu as the TARGET in a DYNAMIC_ARCH build, like `TARGET=ARMV8 DYNAMIC_ARCH=1` or `TARGET=ARMV8SVE DYNAMIC_ARCH=1`.
(TARGET is only used to determine compiler options for all the shared code outside the cpu-specific BLAS kernels, code that needs to run on all of the computers you want to use the library on)
The NeoverseV2 support is currently not available as a standalone build as we wanted to figure out how to add it without duplicating too much data from other cpus.
