### ISSUE TITLE
build of OpenBLAS-0.3.28 fails conditional on BUILD_LAPACK_DEPRECATED = 0

### ISSUE THREAD

**Issue by AllinCottrell** [xianyi/OpenBLAS#4869]
Building OpenBLAS 0.3.28 on Linux (x86_64) using gcc 14.2.1, I run into an error at the linker_test stage if BUILD_LAPACK_DEPRECATED is set to 0 (I have no use for deprecated Lapack functions). The message is that the symbols for various deprecated functions are undefined. Setting BUILD_LAPACK_DEPRECATED=1 solves the problem, but it seems like a bug in the build process.

**Comment by martin-frbg** [comment]
This is probably related to Reference-LAPACK deprecating a few functions some months ago, which may not have been accurately reflected in our linktest at the time (i.e. probably broken since about 0.3.25)

**Comment by AllinCottrell** [comment]
OK, not a big deal.
