### ISSUE TITLE
Cannot be used in Windows Visual Studio 2022

### ISSUE THREAD

**Issue by liushang0322** [xianyi/OpenBLAS#4889]
I am trying to use lapacke functionality in my code and found a problem with the function definition. How can I use openblas in windows visualstudio2022

![image](https://github.com/user-attachments/assets/488b7519-e295-484a-86dd-f8421e7830fe)

there are so many error

**Comment by martin-frbg** [comment]
Are these the first error messages ? It looks like you are missing one of the standard C headers (stddef.h) that defines the `size_t` type. If you can fix that, maybe (most of) the other errors will go away too. Possibly you need to install (or update) the appropriate Windows SDK
