### ISSUE TITLE
Parameter INFERFACE64=1 not make change

### ISSUE THREAD

**Issue by rachot** [xianyi/OpenBLAS#4897]
Host for build cross compile : AMD x64
Target : ARM CortexA53
Version : OpenBLAS-0.3.25
```
make clean
make TARGET=ARMV8 BINARY=64 INTERFACE64=1 HOSTCC=gcc CC=aarch64-linux-gnu-gcc FC=aarch64-linux-gnu-gfortran -j16
make install
```
Complete make and make install
![image](https://github.com/user-attachments/assets/49631078-c6b8-425d-8b3d-a4418d8d2539)

after we check with  `nm /home/target/workspace/install/lib/libopenblas.so | grep _64_`   but don't see anything

**Comment by martin-frbg** [comment]
Please add the SYMBOLSUFFIX= option to change the symbol names as desired.

**Comment by rachot** [comment]
> Please add the SYMBOLSUFFIX= option to change the symbol names as desired.

Thank you @martin-frbg

**Comment by rachot** [comment]
> Please add the SYMBOLSUFFIX= option to change the symbol names as desired.

Now it's solved.
