### ISSUE TITLE
LNK2001: unresolved external symbol __imp_strncpy

### ISSUE THREAD

**Issue by ANANTH5354** [xianyi/OpenBLAS#4898]
Hello guys,
                Here i am facing linker issue i attached supported lib like 1.soem.lib, ws2_32.lib, Packet.lib,Packet.lib, winmm.lib all lib attached but still i am facing these issue "Visual studio 2022" version.

simple_test.c(351,5): warning C4098: 'ecatcheck': 'void' function returning a value
1>LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library
1>soem.lib(ethercatcoe.obj) : error LNK2001: unresolved external symbol __imp_strncpy
1>soem.lib(oshw.obj) : error LNK2001: unresolved external symbol __imp_strncpy
1>soem.lib(nicdrv.obj) : error LNK2001: unresolved external symbol pcap_close
1>soem.lib(nicdrv.obj) : error LNK2001: unresolved external symbol pcap_next_ex
1>soem.lib(nicdrv.obj) : error LNK2001: unresolved external symbol pcap_sendpacket
1>soem.lib(nicdrv.obj) : error LNK2001: unresolved external symbol pcap_open
1>soem.lib(oshw.obj) : error LNK2001: unresolved external symbol pcap_findalldevs
![Screenshot (7)](https://github.com/user-attachments/assets/4b94b622-31fb-4ca5-9afa-acd01d116cea)

1>soem.lib(oshw.obj) : error LNK2001: unresolved external symbol pcap_freealldevs

thanks & Regards
Ananth

**Comment by martin-frbg** [comment]
This does not appear to have anything to do with OpenBLAS, looks like you need to link to msvcrt.lib (or ucrt) for the strncpy and probably wpcap.lib for all the pcap things.

**Comment by ANANTH5354** [comment]
Here I inserted properties-->linker-->Input-->msvcrt.lib, but only one error is gone; the remaining errors are there.

1>soem.lib(nicdrv.obj): error LNK2001: unresolved external symbol pcap_close
1>soem.lib(nicdrv.obj): error LNK2001: unresolved external symbol pcap_next_ex
1>soem.lib(nicdrv.obj): error LNK2001: unresolved external symbol pcap_sendpacket
1>soem.lib(nicdrv.obj): error LNK2001: unresolved external symbol pcap_open
1>soem.lib(oshw.obj): error LNK2001: unresolved external symbol pcap_findalldevs
1>soem.lib(oshw.obj): error LNK2001: unresolved external symbol pcap_freealldevs                

 How to fix it These are errors.

**Comment by martin-frbg** [comment]
please ask somewhere where they know whatever program that is you are trying to build - this has nothing to do with OpenBLAS. Like I already wrote, you will probably need to insert something like wpcap.lib as well to get rid of the pcap errors

**Comment by ANANTH5354** [comment]
I appreciate your help. @martin-frbgI finished, and this problem was once more resolved. Many thanks!
