### ISSUE TITLE
pkgconfig returns `-fopenmp` option

### ISSUE THREAD

**Issue by vabenil** [xianyi/OpenBLAS#4908]
The pkgconfig for openblas returns the  `-fopenmp` flag for library. So that when pkg-config is run like so:
```
$ pkg-config --libs openblas
```
The returned output is: `-fopenmp -lopenblas`.

This should be considered as an error because `-fopenmp` is not a linking flag (Not something you would pass to `ld`). The `-fopenmp` flag should be returned by `pkg-config --cflags`  instead, since `-fopenmp` is a C specific option.

I came across this problem when compiling a D project using `dub` with the openblas library. There `dub` tries to use `pkg-config` to figure out linking flags, tries to add `-fopenmp` which then causes an error because `-fopenmp`is not a linking flag and has no meaning in D.

This issue was downstreamed from https://gitlab.archlinux.org/archlinux/packaging/packages/openblas/-/issues/10.

**Comment by isuruf** [comment]
Don't you need `-fopenmp` sent to the compiler in the linking phase in order for the binary to link to `libgomp`/`libomp`?

**Comment by martin-frbg** [comment]
I'm led to believe the link line needs to be parsable by ld, also this line will have the appropriate `-l` option for linking the openmp library as well.

**Comment by vabenil** [comment]
@isuruf As far as I understand the only things that are considered linking flags are flags with `-l` as @martin-frbg mentioned. The `gcc` docs also mention that `-fopenmp` is a option and it's C dependent, which as in my case in D causes problems when requesting linking flags (that should work independent of language) and receiving a C option flag instead.
