### ISSUE TITLE
Linking to OpenBLAS causes process CPU time clock go crazy on some machines

### ISSUE THREAD

**Issue by vadimkantorov** [xianyi/OpenBLAS#491]
Hi,
I'm linking the last commit of OpenBLAS to this program:

```cpp
#include <cstdio>
#include <ctime>
#include <cstdlib>

timespec diff(timespec start, timespec end)
{
    timespec temp;
    if ((end.tv_nsec-start.tv_nsec)<0) {
        temp.tv_sec = end.tv_sec-start.tv_sec-1;
        temp.tv_nsec = 1000000000+end.tv_nsec-start.tv_nsec;
    } else {
        temp.tv_sec = end.tv_sec-start.tv_sec;
        temp.tv_nsec = end.tv_nsec-start.tv_nsec;
    }
    return temp;
}

int main(int argc, char* argv[])
{
    timespec before_cpu, before_real, after_cpu, after_real;
    clock_gettime(CLOCK_REALTIME, &before_real);
    clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &before_cpu);
    double x = 0;
    for(int i = 0; i < 20000; i++)
    {
        x += clock();
        x += clock();
        x += clock();
        x += clock();
        x += clock();
        x += clock();
    }
    fprintf(stderr, "%lf\n", x);
    clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &after_cpu);
    clock_gettime(CLOCK_REALTIME, &after_real);

    timespec d = diff(before_cpu, after_cpu);
    fprintf(stderr, "CPU elapsed: %.4lf sec\n", d.tv_sec + double(d.tv_nsec) / 1000000000.0);
    d = diff(before_real, after_real);
    fprintf(stderr, "REAL elapsed: %.4lf sec\n", d.tv_sec + double(d.tv_nsec) / 1000000000.0);
}
```

On a crazy machine having OpenBLAS linked causes this report:
```
37689210000.000000
CPU elapsed: 0.5191 sec
REAL elapsed: 0.0577 sec
```

On another machine running this same binary produces:
```
7546770000.000000
CPU elapsed: 0.0902 sec
REAL elapsed: 0.0228 sec
```
(CPU time is still 5 times larger than wall clock time)

Disabling linking with OpenBLAS produces this (on both machines):
```
27990000.000000
CPU elapsed: 0.0150 sec
REAL elapsed: 0.0150 sec
```
CPU and real times reasonably match.

I install OpenBLAS like this:
```shell
mkdir -p lib
cd lib
git clone https://github.com/xianyi/OpenBLAS
cd OpenBLAS
git checkout 63c6fcfa0a25084ef5da727c8669b6f65543b273
make -j4 NO_AFFINITY=1 USE_OPENMP=0 FC=gfortran
make PREFIX=./.. install
```

The program is compiled like this:
```shell
g++ main.cpp -o bad -lrt -lopenblas -Llib/lib
```

**Comment by martin-frbg** [comment]
Without any calls to OpenBLAS functions in your code I wonder if OpenBLAS comes into the picture at all ? (If it does, i.e. if the linker does not simply omit it as unneeded, I believe it can only be some thread initialization that messes with your clock calls).
Also, which hardware (and what does OpenBLAS think it is - from Makefile.rule ?), and - just in case - which compiler version ?

**Comment by xianyi** [comment]
Could you try single thread OpenBLAS?
···
make NO_AFFINITY=1 USE_OPENMP=0 FC=gfortran USE_THREAD=0
···

I think the CPU time is the sum of cpu cores.

Xianyi

**Comment by vadimkantorov** [comment]
@xianyi USE_THREAD=0 helped, but it's still weird that thread initialization "takes" so much time. Originally I've stumbled upon this problem in a large program which had to use a library that required BLAS. Even when linking with BLAS, the clock timers didn't always go crazy, it depended randomly on some other calls. So it was super awkward to remove some lines and see time measurements go through the roof.

@martin-frbg I use g++ 4.8.1. The processor is Intel Xeon E5640, I think that OpenBLAS guesses nehalemp because it produces a binary with that name. I couldn't find anything about proc architecture in Makefile.rule.

**Comment by vadimkantorov** [comment]
Super weird. Starting today this example (regardless of config options) started working fine on both machines. Maybe cluster admins updated some software (though unlikely)... Truth is that I don't have a stable repro anymore...

**Comment by wernsaar** [comment]
Hi,
The Xeon E5650 is a processor with the codename WESTMERE
and I think that this processor has 4 real cores. It may be that the
operating sees 8 cores beause of hyperthreading.

NEHALEM is the right choice in OpenBLAS.
But you can do something.

1. You can set the number of cores to 4 in Makefile.rule
     NUM_THREADS = 4

2. If the operating is linux, you can enable affinity in Makefile.rule
     # NO_AFFINITY = 1

Please use only one of the above options.

Best regards

Werner

**Comment by vadimkantorov** [comment]
@wernsaar Thanks for suggestions. However, even USE_THREAD=0 is okay for me as a workaround because I don't actually need multi-threaded OpenBLAS. Please let me know if you are willing to debug and dig deeper, I can try things on my weird machine. 

A correction, it's X5650. The machine has several processors, output of `cat /proc/cpuinfo | grep 'model name'`: 
```
model name      : Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
model name      : Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
model name      : Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
model name      : Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
model name      : Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
model name      : Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
model name      : Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
model name      : Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
model name      : Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
model name      : Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
model name      : Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
model name      : Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
```

**Comment by vadimkantorov** [comment]
It's sort of understandable that total CPU time we get includes all threads' initialization time. I guess the solution is to either use one thread or to measure clock of just one thread... I guess the case is solved.
