### ISSUE TITLE
LapackE compile on windows

### ISSUE THREAD

**Issue by wavedreamer0822** [xianyi/OpenBLAS#4911]
![{A403A756-5F80-4396-993F-A1A451740BD8}](https://github.com/user-attachments/assets/27639780-c1aa-48f6-a5a7-6374059e915d)
when I compile openblas-0.3.28 on windows，it stuck and cannot continue  while compiling LAPACKE
I use mysys2’s make gcc and gfortran  x86_64-12.2.0 
computer Arch i7-14700KF windows 11

**Comment by martin-frbg** [comment]
Sorry, this is almost certainly a problem with your compiler or hardware. There are many files in LAPACKE but they are short and simple. Can you check with task manager what is actually hanging ? Can you try a newer msys2 gcc ?

**Comment by martin-frbg** [comment]
It definitely compiles on Windows11 with msys2's gcc/gfortran 14.1.0 here, and I do not recall seeing anything like this with earlier versions
