### ISSUE TITLE
`geadd` and `const` qualifiers

### ISSUE THREAD

**Issue by david-cortes** [xianyi/OpenBLAS#4912]
In the wiki for OpenBLAS extensions:
https://github.com/OpenMathLib/OpenBLAS/wiki/OpenBLAS-Extensions

It describes `?geadd` as follows:
> ATLAS-like matrix add B = α*A+β*B

But in the header for function `geadd`:
https://github.com/OpenMathLib/OpenBLAS/blob/f10d47c4bbc752efca8cf93d6a02a1eeedf4d65a/cblas.h#L412

The type for A is a regular pointer instead of a `const` pointer.

Other extensions such as `?omatcopy` use `const` qualifiers in the pointers to data that they do not modify:
https://github.com/OpenMathLib/OpenBLAS/blob/f10d47c4bbc752efca8cf93d6a02a1eeedf4d65a/cblas.h#L394

Is `?geadd` meant to have a `const` qualifier for A in the signature, or can it potentially modify the data that it gets passed?

**Comment by martin-frbg** [comment]
I do not think there is a code path that would modify the A array - on first glance this looks more like a simple oversight from the time when GEADD was added, almost ten years ago (PR #509).
