### ISSUE TITLE
wrong result on zsyr with negative incx, for OpenBLAS 0.2.13.

### ISSUE THREAD

**Issue by zym1010** [xianyi/OpenBLAS#492]
I found this problem initially because the scipy linked against OpenBLAS won't pass a test related to z/c syr. (https://github.com/scipy/scipy/issues/4453). I translated the related test code (https://github.com/scipy/scipy/blob/master/scipy/linalg/tests/test_blas.py#L315) into C and linked it against three different libraries (OpenBLAS, ATLAS, and Accelerate on a mac).

```
#include <stdio.h>
#include <complex.h> 
int main(void)
{
    int i, n;
    double complex alpha;
    char lowerOrUpper = 'U';
    double complex a[] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}; /* to save the result */
    double complex w[] = {0, 1 + 2*I, 0, 0, 3+4*I, 0, 0, 5+6*I, 0, 0, 7+8*I, 0};
    int offx;  
    int incx;
    alpha = 1.0;
    n = 4;
    offx = 1;
    incx = -3;

    zsyr_(&lowerOrUpper, &n, &alpha, w + offx, &incx, a, &n);

    for (i = 0; i < n*n; ++i) {
        printf("%.2f + %.2fi\t ", creal(a[i]), cimag(a[i]));
        if ((i+1)%n == 0) {
            printf("\n");
        } 
    }
    return 0;
}
```

The reference result in scipy test is 
```
In [6]: resz_reverse
Out[6]:
array([[-15.+112.j, -13. +82.j, -11. +52.j,  -9. +22.j],
       [  0.  +0.j, -11. +60.j,  -9. +38.j,  -7. +16.j],
       [  0.  +0.j,   0.  +0.j,  -7. +24.j,  -5. +10.j],
       [  0.  +0.j,   0.  +0.j,   0.  +0.j,  -3.  +4.j]])
```

The output of my test program using OpenBLAS is 
```
0.00 + 0.00i	 0.00 + 0.00i	 0.00 + 0.00i	 0.00 + 0.00i
0.00 + 0.00i	 0.00 + 0.00i	 0.00 + 0.00i	 0.00 + 0.00i
0.00 + 0.00i	 0.00 + 0.00i	 64.00 + 0.00i	 0.00 + 0.00i
0.00 + 0.00i	 0.00 + 0.00i	 16.00 + 24.00i	 -5.00 + 12.00i
```

yet the outputs for ATLAS and Accelerate are the same (transpose it to match the result from scipy, since C and Fortran have different storage schemes):
```
-15.00 + 112.00i	 0.00 + 0.00i	 0.00 + 0.00i	 0.00 + 0.00i
-13.00 + 82.00i	 -11.00 + 60.00i	 0.00 + 0.00i	 0.00 + 0.00i
-11.00 + 52.00i	 -9.00 + 38.00i	 -7.00 + 24.00i	 0.00 + 0.00i
-9.00 + 22.00i	 -7.00 + 16.00i	 -5.00 + 10.00i	 -3.00 + 4.00i
```

I wonder if this is a bug in OpenBLAS in general, or it's limited to my processor (dual E5-2620 v3, Ubuntu Server 14.04.1)

**Comment by martin-frbg** [comment]
Seeing all zeros on both Haswell and Nehalem here (and even a few NaNs when I compile without optimization).

**Comment by martin-frbg** [comment]
Already broken in final gotoblas (from which OpenBLAS derives), while netlib lapack gives the same result as your ATLAS and Accelerate on my system. Wonder if it could be due to "historic" assumptions about the memory layout of the "double complex" data type, seeing that gotoblas/openblas zsyr appears to expect an array of doubles according to common_interface.h,
while lapacke has std::complex<double> array arguments ?
Cf. http://icl.cs.utk.edu/lapack-forum/viewtopic.php?f=12&t=4330

**Comment by zym1010** [comment]
@martin-frbg thanks for your testing and investigation. While there seems to be some differences on the interface on zsyr between OpenBLAS (gotoblas) and other implementations, it's interesting that it's only when incx is negative that OpenBLAS seems buggy.

**Comment by matthew-brett** [comment]
@zym1010 - you mentioned 'differences in the interface' - but just to be clear, do you agree that the other libraries are correct and that this is a bug?

**Comment by zym1010** [comment]
@matthew-brett Well, from the thread you referred to it seems that there are interface differences. And I agree that other libraries can produce the correct input expected by Scipy developers.

**Comment by matthew-brett** [comment]
I wanted to check that when you say 'interface differences' rather than 'bug' you are saying that the answer given by OpenBLAS could be considered correct in some sense.   Can you explain why?

**Comment by martin-frbg** [comment]
I believe the "interface differences" comment is related to my observation that openblas passes the complex arguments as an array of doubles rather than as std:complex (as netlib, atlas et al. do) - this
however appears to be a red herring. Unfortunately I did not get around to comparing earlier versions
of the original gotoBlas yet, all I can say is that the last one, which was the starting point of OpenBLAS already displayed the erroneous behaviour with negative incx.

**Comment by martin-frbg** [comment]
Same effect with GotoBLAS2-1.08, the oldest source tarball I could find in my backups. (Copies of even older first-generation gotoblas failed to compile on even moderately recent hardware.) Debugging seemed to implicate the SSE2 copy routine invoked as COPY_K in level2/z_syr_k.c, but forcing use of the non-SSE copy.S did not change the result. As my knowledge of assembler is both sketchy and outdated I will probably not venture further.

**Comment by xianyi** [comment]
Hi @zym1010 ,
Thank you for the feedback. Please try the develop branch. I think I fixed this bug.

Xianyi

**Comment by lixiangnlp** [comment]
I make the test for scipy. And I also meet the test fail.

FAIL: test_syr_her (test_blas.TestFBLAS2Simple)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/anaconda/lib/python2.7/site-packages/scipy/linalg/tests/test_blas.py", line 316, in test_syr_her
    resz_reverse, rtol=rtol)
  File "/home/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "/home/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

(mismatch 100.0%)
 x: array([[ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j]], dtype=complex64)
 y: array([[-15.+112.j, -13. +82.j, -11. +52.j,  -9. +22.j],
       [  0.  +0.j, -11. +60.j,  -9. +38.j,  -7. +16.j],
       [  0.  +0.j,   0.  +0.j,  -7. +24.j,  -5. +10.j],
       [  0.  +0.j,   0.  +0.j,   0.  +0.j,  -3.  +4.j]])

----------------------------------------------------------------------

**Comment by martin-frbg** [comment]
@lixiangnlp did you do your test with the current development branch of OpenBLAS (the only one containing the fix - which seems to work for me) ?

**Comment by lixiangnlp** [comment]
@martin-frbg I used the latest OpenBLAS.

**Comment by martin-frbg** [comment]
Strange. I just redid my tests with the standalone C code from the start of this thread and got the desired result (though I could only test on aged Nehalem and ancient Prescott hardware right away)
Will reconfirm on Haswell later today.

**Comment by lixiangnlp** [comment]
The used CPU is Haswell i4790K. And I used the 0.15.1 scipy.

**Comment by martin-frbg** [comment]
Again current "develop" branch works fine for me on i4770 both in multithreaded and singlethread builds. Could it be that your scipy environment pulls in an older version of OpenBLAS inadvertently ?

**Comment by zym1010** [comment]
@xianyi Sorry for the late reply. I just tested the latest release and it works now! Thanks.
