### ISSUE TITLE
Don't understand how to actually use multithreading

### ISSUE THREAD

**Issue by antobazir** [xianyi/OpenBLAS#4935]
Hello, 

I am reaching out after two days of trying to understand how to use multithreading with OpenMP in a C code. More specifically I'm trying use the LAPACK function dgesv_(). 

I downloaded the OpenBLAS-0.3.28 and built it with the command "make USE_THREAD=1 USE_OPENMP=1". I link statically against "libopenblas_haswellp-r0.3.28.a" library built with the preceding command.

I compile the code with the following commands :"
gcc -O3  -g  -I$(OPENBLAS_DIR)/OpenBLAS-0.3.28 -c -o FD3D_LOD_OpenBLAS.o FD3D_LOD_OpenBLAS.c
gfortran -O2 -frecursive -g -fopenmp -lgfortran  -o FD3D_LOD_OpenBLAS FD3D_LOD_OpenBLAS.o (OPENBLAS_DIR)/libopenblas_haswellp-r0.3.28.a"

The code compiles fine (also with gcc in both steps) and runs but does not use multithreading regardless of the OMP_NUM_THREADS value. I know it because it uses 25% of cpu, which on other applications that I have successfully parallelized correspond to a single thread. I have also used the LAPACKE functions but the results are the same.

I'm running out of ideas, and looking into the documentation and functions prototypes and implementation did not help me any further.

Thanks for your time.

Here is the full code if it can help  : 
`#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "common.h"
#include <time.h>
#include <omp.h>

/*compile w/  gcc -fopenmp
gcc -O2 -c -I /home/antonybazir/lapack-3.12.0/LAPACKE/include FD3D_LOD_LPCKE.c
gcc -O2 -fopenmp -o FD3D_LOD FD3D_LOD_LPCKE.o -L /home/antonybazir/lapack-3.12.0 -llapacke -lm*/
/*env OMP_NUM_THREADS=4 ./FD3D_LOD*/

/*gcc -O3 -fopenmp -I. -I../include -c -o example_DGESV_rowmajor.o example_DGESV_rowmajor.c
gcc -O3 -fopenmp -I. -I../include -c -o lapacke_example_aux.o lapacke_example_aux.c
gfortran -O2 -frecursive -fopenmp -fopenmp -o xexample_DGESV_rowmajor example_DGESV_rowmajor.o lapacke_example_aux.o ../../liblapacke.a ../../liblapack.a ../../librefblas.a
this what the compilation should look like*/

/*attempt with longer solving time*/

void solve(int argc, char *argv[])
{

	blasint i,j,k,n1,n, lda, ldb, info,nrhs;
	int nt, dd, t;
	n1=11;
	n = n1*n1*n1;
	double dtt[5];
	double dt,dx,r,*A,*B,*C, *kG, *G, *D,*a,*b,*c;
	double time_taken[5];
	char *file_G;
	clock_t start, end;
	FILE *ft,*ftt;
	blasint *ipiv;

	dtt[0] = 1e-4;dtt[1] =  1e-3; dtt[2] = 1e-2; dtt[3] = 1e-1; dtt[4] = 1e-0;
	r=7.0;
	dx=20.0;

	A =  malloc(n*n*sizeof(double));
	B =  malloc(n*n*sizeof(double));
	C =  malloc(n*n*sizeof(double));
	a =  malloc(n*sizeof(double));
	b =  malloc(n*sizeof(double));
	c =  malloc(n*sizeof(double));
	kG  = malloc(n1*n1*n1*sizeof(double));
	G  = malloc(n1*n1*n1*sizeof(double));
	D  = malloc(n1*n1*n1*sizeof(double));
	ipiv  = malloc(n*sizeof(int));

	lda = n;
	ldb = n;
    nrhs =1;

	ftt = fopen("time_LOD_LPCKE.txt","w+");
 	for(dd=2;dd<4;dd++)
	{

		start = clock();
		if(dd==0)
		{
			ft = fopen("GtLx_1b","w+");
			file_G = "GLx_final_1b";
		}

		if(dd==1)
		{
			ft = fopen("GtLx_2b","w+");
			file_G = "GLx_final_2b";
		}

		if(dd==2)
		{
			ft = fopen("GtLx_3b","w+");
			file_G = "GLx_final_3b";
		}

		if(dd==3)
		{
			ft = fopen("GtLx_4b","w+");
			file_G = "GLx_final_4b";
		}

		if(dd==4)
		{
			ft = fopen("GtLx_5b","w+");
			file_G = "GLx_final_5b";
		}
		
		dt = dtt[dd];

		printf("%lf\n",dt);

		for(i=0;i<n1;i++)
		{
			for(j=0;j<n1;j++)
			{
				for(k=0;k<n1;k++)
				{

					if((i-n1/2)*(i-n1/2)+(j-n1/2)*(j-n1/2)+(k-n1/2)*(k-n1/2)<r*r)
					{
						D[i+j*n1+k*n1*n1] = 60000.0;
						kG[i+j*n1+k*n1*n1] = 1.0;
					}
					else
					{
						D[i+j*n1+k*n1*n1] = 100000.0;
						kG[i+j*n1+k*n1*n1] = 0.0;
					}

					G[i+j*n1+k*n1*n1] = 5.0;

				}
			}
		}
		

		/*filling the A matrix*/
		for(k=0;k<n1;k++)
		{
			for(j=0;j<n1;j++)
			{
				for(i=0;i<n1;i++)
				{
					/*x-diagonal*/
					if(i==0)A[(i+(j)*n1+(k)*n1*n1)+
					n*(i+(j)*n1+(k)*n1*n1)]=
					1.0 + ( 0.0 + ((dt*(D[i+j*n1+k*n1*n1]+D[i+1+j*n1+k*n1*n1]))/(2.0*dx*dx))/2.0);
						
					if(i>0&&i<n1-1)A[(i+(j)*n1+(k)*n1*n1)+
					n*(i+(j)*n1+(k)*n1*n1)]=
					1.0 + ( ((dt*(D[i+j*n1+k*n1*n1]+D[i-1+j*n1+k*n1*n1]))/(2.0*dx*dx))/2.0 + 
					((dt*(D[i+j*n1+k*n1*n1]+D[i+1+j*n1+k*n1*n1]))/(2.0*dx*dx))/2.0);

					if(i==n1-1)A[(i+(j)*n1+(k)*n1*n1)+
					n*(i+(j)*n1+(k)*n1*n1)]=
					1.0 + ( ((dt*(D[i+j*n1+k*n1*n1]+D[i-1+j*n1+k*n1*n1]))/(2.0*dx*dx))/2.0 + 0.0);					
					
					/*x-up-diagonal*/
					if(i>0&&i<n1-1)A[(i+(j)*n1+(k)*n1*n1)+
					n*(i-1+(j)*n1+(k)*n1*n1)]=
					( -((dt*(D[i+j*n1+k*n1*n1]+D[i-1+j*n1+k*n1*n1]))/(2.0*dx*dx))/2.0);

					if(i==n1-1)A[(i+(j)*n1+(k)*n1*n1)+
					n*(i-1+(j)*n1+(k)*n1*n1)]=
					( -((dt*(D[i+j*n1+k*n1*n1]+D[i-1+j*n1+k*n1*n1]))/(2.0*dx*dx))/2.0 - (((0.0))/(2.0*dx*dx))/2.0);						
					
					
					/*x-low-diagonal*/
					if(i==0)A[(i+(j)*n1+(k)*n1*n1)+
					n*(i+1+(j)*n1+(k)*n1*n1)]=
					 ( -(0.0) - (dt*(D[i+j*n1+k*n1*n1]+D[i+1+j*n1+k*n1*n1]))/(2.0*dx*dx))/2.0;	
					
					if(i>0&&i<n1-1)A[(i+(j)*n1+(k)*n1*n1)+
					n*(i+1+(j)*n1+(k)*n1*n1)]=
					-((dt*(D[i+j*n1+k*n1*n1]+D[i+1+j*n1+k*n1*n1]))/(2.0*dx*dx))/2.0;
		
				}
			}		
		}

		/*filling the B matrix*/
		for(i=0;i<n1;i++)
		{
			for(k=0;k<n1;k++)
			{
				for(j=0;j<n1;j++)
				{
					/*y-diagonal*/
					if(j==0)B[(j+(k)*n1+(i)*n1*n1)+
					n*(j+(k)*n1+(i)*n1*n1)]=
					1.0 + ( 0.0 + ((dt*(D[i+j*n1+k*n1*n1]+D[i+(j+1)*n1+k*n1*n1]))/(2.0*dx*dx))/2.0);						

					if(j>0&&j<n1-1)B[(j+(k)*n1+(i)*n1*n1)+
					n*(j+(k)*n1+(i)*n1*n1)]=
					1.0 + ( ((dt*(D[i+j*n1+k*n1*n1]+D[i+(j-1)*n1+k*n1*n1]))/(2.0*dx*dx))/2.0 + 
					((dt*(D[i+j*n1+k*n1*n1]+D[i+(j+1)*n1+k*n1*n1]))/(2.0*dx*dx))/2.0);

					if(j==n1-1)B[(j+(k)*n1+(i)*n1*n1)+
					n*(j+(k)*n1+(i)*n1*n1)]=
					1.0 + ( ((dt*(D[i+j*n1+k*n1*n1]+D[i+(j-1)*n1+k*n1*n1]))/(2.0*dx*dx))/2.0 + 0.0);

					/*y-up-diagonal*/
					if(j>0&&j<n1-1)B[(j+(k)*n1+(i)*n1*n1)+
					n*(j-1+(k)*n1+(i)*n1*n1)]=
					( -((dt*(D[i+j*n1+k*n1*n1]+D[i+(j-1)*n1+k*n1*n1]))/(2.0*dx*dx))/2.0);

					if(j==n1-1)B[(j+(k)*n1+(i)*n1*n1)+
					n*(j-1+(k)*n1+(i)*n1*n1)]=
					( -((dt*(D[i+j*n1+k*n1*n1]+D[i+(j-1)*n1+k*n1*n1]))/(2.0*dx*dx))/2.0 - ((0.0)/(2.0*dx*dx))/2.0);						
					
					/*y-low-diagonal*/
					if(j==0)B[(j+(k)*n1+(i)*n1*n1)+
					n*(j+1+(k)*n1+(i)*n1*n1)]=
					(-((0.0)) - (dt*(D[i+j*n1+k*n1*n1]+D[i+(j+1)*n1+k*n1*n1]))/(2.0*dx*dx))/2.0;						
					
					if(j>0&&j<n1-1)B[(j+(k)*n1+(i)*n1*n1)+
					n*(j+1+(k)*n1+(i)*n1*n1)]=
					( -((dt*(D[i+j*n1+k*n1*n1]+D[i+(j+1)*n1+k*n1*n1]))/(2.0*dx*dx))/2.0);
				}
			}
		}

		/*filling the C matrix*/
		for(j=0;j<n1;j++)
		{
			for(i=0;i<n1;i++)
			{
				for(k=0;k<n1;k++)
				{
					/*z-diagonal*/
					if(k==0)C[(k+(i)*n1+(j)*n1*n1)+
					n*(k+(i)*n1+(j)*n1*n1)]=
					1.0 + ( 0.0 + ((dt*(D[i+j*n1+k*n1*n1]+D[i+(j)*n1+(k+1)*n1*n1]))/(2.0*dx*dx))/2.0);				
	
					if(k>0&&k<n1-1)C[(k+(i)*n1+(j)*n1*n1)+
					n*(k+(i)*n1+(j)*n1*n1)]=
					1.0 + ( ((dt*(D[i+j*n1+k*n1*n1]+D[i+(j)*n1+(k-1)*n1*n1]))/(2.0*dx*dx))/2.0 + ((dt*(D[i+j*n1+k*n1*n1]+D[i+(j)*n1+(k+1)*n1*n1]))/(2.0*dx*dx))/2.0);

					if(k==n1-1)C[(k+(i)*n1+(j)*n1*n1)+
					n*(k+(i)*n1+(j)*n1*n1)]=
					1.0 + ( ((dt*(D[i+j*n1+k*n1*n1]+D[i+(j)*n1+(k-1)*n1*n1]))/(2.0*dx*dx))/2.0 + 0.0);

					/*z-up-diagonal*/					
					if(k>0&&k<n1-1)C[(k+(i)*n1+(j)*n1*n1)+
					n*(k-1+(i)*n1+(j)*n1*n1)]=
					( -((dt*(D[i+j*n1+k*n1*n1]+D[i+(j)*n1+(k-1)*n1*n1]))/(2.0*dx*dx))/2.0);

					if(k==n1-1)C[(k+(i)*n1+(j)*n1*n1)+
					n*(k-1+(i)*n1+(j)*n1*n1)]=
					( -((dt*(D[i+j*n1+k*n1*n1]+D[i+(j)*n1+(k-1)*n1*n1]))/(2.0*dx*dx))/2.0 - ((0.0)/(2.0*dx*dx))/2.0);						
					
					/*z-low-diagonal*/
					if(k==0)C[(k+(i)*n1+(j)*n1*n1)+
					n*(k+1+(i)*n1+(j)*n1*n1)]=
					(-((0.0)) - (dt*(D[i+j*n1+k*n1*n1]+D[i+(j)*n1+(k+1)*n1*n1]))/(2.0*dx*dx))/2.0;
					
					if(k>0&&k<n1-1)C[(k+(i)*n1+(j)*n1*n1)+
					n*(k+1+(i)*n1+(j)*n1*n1)]=
					( -((dt*(D[i+j*n1+k*n1*n1]+D[i+(j)*n1+(k+1)*n1*n1]))/(2.0*dx*dx))/2.0);
				}
			}
		}
		
		 /* Print Entry Matrix */
        /*print_matrix_rowmajor( "Entry Matrix A", n, n, A, n );*/

		printf("inversion started...\n");
		for(nt=0;nt<5/dt;nt++)
		{
			printf("%d/%d\n",nt,(int)(5/dt));
			/*x rhs*/
			for(k=0;k<n1;k++)
			{
				for(j=0;j<n1;j++)
				{
					for(i=0;i<n1;i++)
					{
						/*x-direction*/
						if(i==0)a[i+(j)*n1+(k)*n1*n1]=
						((0.0/(2.0*dx*dx)) + (dt*(D[i+j*n1+k*n1*n1]+D[i+1+j*n1+k*n1*n1]))/(2.0*dx*dx))/2.0*G[i+1 + j*n1 + k*n1*n1] +
						(1.0 - (0.0 + (dt*(D[i+j*n1+k*n1*n1]+D[i+1+j*n1+k*n1*n1]))/(2.0*dx*dx))/2.0)*G[i + j*n1 + k*n1*n1]- 
						kG[i+j*n1+k*n1*n1]*dt/3.0;
	
						if(i>0&&i<n1-1)a[i+(j)*n1+(k)*n1*n1]=
						((dt*(D[i+j*n1+k*n1*n1]+D[i-1+j*n1+k*n1*n1]))/(2.0*dx*dx))/2.0*G[i-1 + j*n1 + k*n1*n1] +
						((dt*(D[i+j*n1+k*n1*n1]+D[i+1+j*n1+k*n1*n1]))/(2.0*dx*dx))/2.0*G[i+1 + j*n1 + k*n1*n1] + 
						(1.0 - (((dt*(D[i+j*n1+k*n1*n1]+D[i-1+j*n1+k*n1*n1]))/(2.0*dx*dx)) + (dt*(D[i+j*n1+k*n1*n1]+D[i+1+j*n1+k*n1*n1]))/(2.0*dx*dx))/2.0)*G[i + j*n1 + k*n1*n1]
						-kG[i+j*n1+k*n1*n1]*dt/3.0;
						
						if(i==n1-1)a[i+(j)*n1+(k)*n1*n1]=
						(((0.0)+ ((dt*(D[i+j*n1+k*n1*n1]+D[i-1+j*n1+k*n1*n1]))/(2.0*dx*dx)))/2.0)*G[i-1 + j*n1 + k*n1*n1] + 
						(1.0 - (0.0+ ((dt*(D[i+j*n1+k*n1*n1]+D[i-1+j*n1+k*n1*n1]))/(2.0*dx*dx)))/2.0)*G[i + j*n1 + k*n1*n1] - 
						kG[i+j*n1+k*n1*n1]*dt/3.0;				
						
					}
				}
			}

			goto_set_num_threads(2);

			/*solve*/
			/* Executable statements */
			/*printf( "LAPACKE_dgesv (row-major, high-level) Example Program Results\n" );
			/* Solve the equations A*X = B */
			dgesv_(&n, &nrhs, A, &lda, ipiv,
                        a, &ldb, &info);
			/* Check for the exact singularity */
			if( info > 0 ) {
                printf( "The diagonal element of the triangular factor of A,\n" );
               /*printf( "U(%" LAPACK_IFMT ",%" LAPACK_IFMT ") is zero, so that A is singular;\n", info, info );*/
                printf( "the solution could not be computed.\n" );
                exit( 1 );
			}
			if (info <0) 
			{
				printf(" 296 : %d",info);
				exit( 1 );
			}
			
			/*y rhs*/
			for(i=0;i<n1;i++)
			{
				for(k=0;k<n1;k++)
				{
					for(j=0;j<n1;j++)
					{

						/*y-direction*/
						if(j==0)b[j+(k)*n1+(i)*n1*n1]=
						(((0.0/(2.0*dx*dx)) + (dt*(D[i+j*n1+k*n1*n1]+D[i+(j+1)*n1+k*n1*n1]))/(2.0*dx*dx))/2.0)*a[i + (j+1)*n1 + k*n1*n1] + 
						(1.0 - ((0.0)/(2.0*dx*dx) + (dt*(D[i+j*n1+k*n1*n1]+D[i+(j+1)*n1+k*n1*n1]))/(2.0*dx*dx))/2.0)*a[i + (j)*n1 + k*n1*n1]- 
						kG[i+j*n1+k*n1*n1]*dt/3.0;

						if(j>0&&j<n1-1)b[j+(k)*n1+(i)*n1*n1]=
						(((dt*(D[i+j*n1+k*n1*n1]+D[i+(j-1)*n1+k*n1*n1]))/(2.0*dx*dx))/2.0)*a[i + (j-1)*n1 + k*n1*n1] + 
						(((dt*(D[i+j*n1+k*n1*n1]+D[i+(j+1)*n1+k*n1*n1]))/(2.0*dx*dx))/2.0)*a[i + (j+1)*n1 + k*n1*n1] + 
						(1.0 - ((dt*(D[i+j*n1+k*n1*n1]+D[i+(j-1)*n1+k*n1*n1]))/(2.0*dx*dx) + (dt*(D[i+j*n1+k*n1*n1]+D[i+(j+1)*n1+k*n1*n1]))/(2.0*dx*dx))/2.0)*a[i + (j)*n1 + k*n1*n1]
						-kG[i+j*n1+k*n1*n1]*dt/3.0 ;

						if(j==n1-1)b[j+(k)*n1+(i)*n1*n1]=
						(((0.0)+ ((dt*(D[i+j*n1+k*n1*n1]+D[i+(j-1)*n1+k*n1*n1]))/(2.0*dx*dx)))/2.0)*a[i + (j-1)*n1 + k*n1*n1] + 
						(1 - ((0.0)+ ((dt*(D[i+j*n1+k*n1*n1]+D[i+(j-1)*n1+k*n1*n1]))/(2.0*dx*dx)))/2.0)*a[i + (j)*n1 + k*n1*n1] 
						- kG[i+j*n1+k*n1*n1]*dt/3.0;				
					}
				}
			}

			/*vector x_i must be shifted to follow y-axis*/
			for(i=0;i<n1;i++)
			{
				for(k=0;k<n1;k++)
				{
					for(j=0;j<n1;j++)
					{
							b[j+(k)*n1+(i)*n1*n1] = a[i + (j)*n1 + k*n1*n1] ;
					}
				}
			}

						/*solve*/
			/* Executable statements */
			/*printf( "LAPACKE_dgesv (row-major, high-level) Example Program Results\n" );
			/* Solve the equations A*X = B */
			dgesv_(&n, &nrhs, B, &lda, ipiv,
                        b, &ldb, &info);
			/* Check for the exact singularity */
			if( info > 0 ) {
                printf( "The diagonal element of the triangular factor of A,\n" );
                /*printf( "U(%" LAPACK_IFMT ",%" LAPACK_IFMT ") is zero, so that A is singular;\n", info, info );*/
                printf( "the solution could not be computed.\n" );
                exit( 1 );
			}
			if (info <0) 
			{
				printf(" 351 : %d",info);
				exit( 1 );
			}
;
			
			/*z rhs*/
			for(j=0;j<n1;j++)
			{
				for(i=0;i<n1;i++)
				{
					for(k=0;k<n1;k++)
					{
						/*z-direction*/
						if(k==0)c[k+(i)*n1+(j)*n1*n1]=
						((0.0/(2.0*dx*dx) + (dt*(D[i+j*n1+k*n1*n1]+D[i+(j)*n1+(k+1)*n1*n1]))/(2.0*dx*dx))/2.0)*b[j + (k+1)*n1 + (i)*n1*n1] 
						+ (1 - ((0.0)/(2.0*dx*dx) + (dt*(D[i+j*n1+k*n1*n1]+D[i+(j)*n1+(k+1)*n1*n1]))/(2.0*dx*dx))/2.0)*b[j + (k)*n1 + i*n1*n1]
						- kG[i+j*n1+k*n1*n1]*dt/3.0;
						
						if(k>0&&k<n1-1)c[k+(i)*n1+(j)*n1*n1]=
						(((dt*(D[i+j*n1+k*n1*n1]+D[i+(j)*n1+(k-1)*n1*n1]))/(2.0*dx*dx))/2.0)*c[j + (k-1)*n1 + (i)*n1*n1] + 
						(((dt*(D[i+j*n1+k*n1*n1]+D[i+(j)*n1+(k+1)*n1*n1]))/(2.0*dx*dx))/2.0)*c[j + (k+1)*n1 + (i)*n1*n1] + 
						(1 - ((dt*(D[i+j*n1+k*n1*n1]+D[i+(j)*n1+(k-1)*n1*n1]))/(2.0*dx*dx) + (dt*(D[i+j*n1+k*n1*n1]+D[i+(j)*n1+(k+1)*n1*n1]))/(2.0*dx*dx))/2.0)*c[j + (k)*n1 + i*n1*n1]
						-kG[i+j*n1+k*n1*n1]*dt/3.0;
						
						if(k==n1-1)c[k+(i)*n1+(j)*n1*n1]=				
						((0.0)+ ((dt*(D[i+j*n1+k*n1*n1]+D[i+(j)*n1+(k-1)*n1*n1]))/(2.0*dx*dx))/2.0)*c[j + (k-1)*n1 + (i)*n1*n1] +
						(1 - ((0.0/(2.0*dx*dx))+ ((dt*(D[i+j*n1+k*n1*n1]+D[i+(j)*n1+(k-1)*n1*n1]))/(2.0*dx*dx)))/2.0)*c[j + (k)*n1 + i*n1*n1] 
						- kG[i+j*n1+k*n1*n1]*dt/3.0;
					}
				}
			}

		

			/*vector x_m must be shifted to follow y-axis*/
			for(j=0;j<n1;j++)
			{
				for(i=0;i<n1;i++)
				{
					for(k=0;k<n1;k++)
					{
							c[k+(i)*n1+(j)*n1*n1] = b[j + (k)*n1 + i*n1*n1] ;
					}
				}
			}

									/*solve*/
			/* Executable statements */
			/*printf( "LAPACKE_dgesv (row-major, high-level) Example Program Results\n" );
			/* Solve the equations A*X = B */
			dgesv_(&n, &nrhs, C, &lda, ipiv,
                        c, &ldb, &info);
			/* Check for the exact singularity */
			if( info > 0 ) {
                printf( "The diagonal element of the triangular factor of A,\n" );
                /*printf( "U(%" LAPACK_IFMT ",%" LAPACK_IFMT ") is zero, so that A is singular;\n", info, info );*/
                printf( "the solution could not be computed.\n" );
                exit( 1 );
			}
			if (info <0) 
			{
				printf(" 407 : %d",info);
				/*print_matrix_rowmajor( "Right Rand Side c", n, 1, c, 1 );*/
				printf( "\n" );
				exit( 1 );
			}

				for(k=0;k<n1;k++)
				{
					for(j=0;j<n1;j++)
					{
						for(i=0;i<n1;i++)
						{
							G[i+(j)*n1+(k)*n1*n1] = c[k + (i)*n1 + j*n1*n1];
						}
					}
				}

			fprintf(ft,"%lf \n",G[(n1/2+(n1/2)*n1+(n1/2)*n1*n1)]);/*saving the value*/

			
		}
		printf("inversion finished...\n");

		end = clock();
		time_taken[dd] = (double)(end - start) / (double)(CLOCKS_PER_SEC);
		printf("Time taken is : %3.2lf sec \n",time_taken[dd]);
		fprintf(ftt,"%lf \n",time_taken[dd]);
		fclose(ft);

		printf("G_center: %lf \n",G[n1/2 + n1/2*n1+ n1/2*n1*n1]);

	}
	fclose(ftt);
	free(kG);
	free(G);
	free(D);
	free(A);
	free(B);
	free(C);

}

int main(int argc, char *argv[])
{
	solve(argc,argv);
}
`

**Comment by martin-frbg** [comment]
What is your typical matrix size ? OpenBLAS will not use more than one thread when the problem size is too small (which e.g. for dgetrf means M*N less than 10000). Another possible reason for this behavior might be that you built the library on a (virtual) machine with only a single cpu core and did not specify a larger NUM_THREADS value at build time.

**Comment by antobazir** [comment]
Okay it works.

I had not pushed past 9000 points. I had read about the fact that multithreading was not use for small problems but did not have the actual lower bound for that. 

Thanks a lot

**Comment by martin-frbg** [comment]
I forgot to mention that this limit is defined in interface/lapack/getrf.c (there are similar threshold values for most if not all BLAS functions in the respective files in the interface folder),
in case that number is not optimal (for your hardware, or in general - sometimes later code changes shift the optimum crossover point to a higher or lower number without anybody realizing that the threshold must be adjusted).
Note also that getrf is one of only a handful of LAPACK functions that are reimplemented in OpenBLAS, the majority uses the original, single-threaded code from the Reference (or "netlib")
implementation of LAPACK.

**Comment by antobazir** [comment]
**EDIT : The thing seems to be that the dgesv routine can use multithreading while the dgtsv routine cannot...***

Hello, 

I'm coming back...

The code I showed you worked and used multithreading as expected on my DELL laptop with Ubuntu 22.04 installed.

Then, I tried to compile and run the same code on a more powerful computer with 24 cores. It's a windows machine but I use WSL (windows subsystem for linux) to compile and run C and Fortran code in an Ubuntu 22.04 subsystem.

I built the library fine with the same options as before.  (USE_OPENMP=1) and the build was fine. The prompt reported "(Multi-threading; Max num-threads is 32)" which is expected.

I compiled and executed the code shown above with gdb, and gdb does start thread debugging using libthread_db. This suggest that multithreading and openmp instructions are fine. But then, no matter how many elements I put in my system no multithreading occurs on the second machine....

I checked the limits in getrf.c but the values are consistent between the two computers. (10000) So the code should use at least two threads with the number of elements I'm testing...

Any idea of what is happening ?

Thanks

**Comment by martin-frbg** [comment]
right - the page for DGTSV appears to be missing from the online documentation of the Reference LAPACK, but SGTSV is here: https://www.netlib.org/lapack//explore-html/d6/ddb/group__gtsv_ga4d4e62f504a5776f6b29efa23299efb9.html (scroll all the way down for the call graph that makes it clear that the ?TGSV routines call no other function except the error handler) and like 99 percent of the Reference or "netlib" LAPACK it is not parallelized. OpenBLAS contains a handful of parallelized rewrites of standard LAPACK functions but sadly not ?GTSV

**Comment by martin-frbg** [comment]
seeing that you already use OpenMP in your code, maybe you could get away with throwing a few `#pragma OpenMP parallel for` around the loops in lapack-netlib/SRC/dgtsv.f but I have not checked if it is actually that simple (probably not)

**Comment by antobazir** [comment]
Hello again,

So I found a "dgtsv.c" file in the lapack-netlib src folder. I figured the code in this file is practically self-sufficient, so I just copied the function into my previous code 

It was then rather easy to put parallel sections in but I found out pretty quickly why the OpenBLAS version didn't parallelize this function in the first place. It would seem the algorithm does not benefit from that type of parallelism. There were no performance gains no matter the number of core I used (2, 4, 8 ,24)

So i guess this is a bit of a dead end for me. Still a good  learning experience 

Thanks for your assistance

**Comment by martin-frbg** [comment]
Seems there are a few papers around that claim to present alternative implementations of DGTSV for parallel applications - however these appear to focus on GPU, and I have not checked if what they implement is actually still the same basic algorithm. If you look in the Intel MKL support forums, "is there a parallelized GTSV" is answered with "yes, use GETRF/GETRS" (which is what DGESV does internally)

**Comment by antobazir** [comment]
I looked those up on the Lapack library. To me it seems counterintuitive as it means treating a tridiagonal matrix as a full one.

I will try but my feeling is that the gain I'll make from being able to use multithreading will to a degree be negated by the additional computational load.

Thanks for the tip though

**Comment by martin-frbg** [comment]
Guess you could ask over in Reference-LAPACK/lapack where the true and pure mathematicians hang out :)
