### ISSUE TITLE
Spack install of openblas on arm64 commands not working?

### ISSUE THREAD

**Issue by sbrewskier13** [xianyi/OpenBLAS#4938]
How does one call openblas within spack environment to install on something like a raspberry pi 5 arm64 architecture?

**Comment by sbrewskier13** [comment]
tried using 

spack install --add openblas

and 

spack install openblas target=aarch64


those error out and don't work

**Comment by sbrewskier13** [comment]
All prereqs are installed cmake, gmake, ninja, gcc

**Comment by sbrewskier13** [comment]
spack install --add  openblas target=armv8
==> Error: failed to concretize `openblas arch=None-None-armv8`, `openblas@0.3.28/yor6hfw`, `py-numpy@2.1.2/a5hvgpa`, `ninja@1.12.1/qenxiub`, ..., `python@3.11.7/fwu2c3a` for the following reasons:
     1. 'openblas target=neoverse_n1' cannot satisfy constraint 'target=armv8'. Couldn't concretize without changing the existing environment. If you are ok with changing it, try `spack concretize --force`. You could consider setting `concretizer:unify` to `when_possible` or `false` to allow multiple versions of some packages.

**Comment by martin-frbg** [comment]
This is a problem within spack - their tool "helpfully" presets compiler/target options that conflict with what you actually want to use. There must be at least one open issue ticket in spack from at least a year ago - I untagged myself there after the comments became a stream of "me too" without any actual developer activity

**Comment by sbrewskier13** [comment]
So there's no fix

**Comment by martin-frbg** [comment]
I honestly do not know if anyone has come up with a workaround - but this is not an OpenBLAS problem, please take it up with Spack (and search their open issue list for existing discussions).

**Comment by martin-frbg** [comment]
https://github.com/spack/spack-packages/issues/930 is the issue I remember - one of the latest comments on it has a workaround but discussion stalled again after that instead of adopting this or any other solution...
