### ISSUE TITLE
Build for sifive P870

### ISSUE THREAD

**Issue by liut89** [xianyi/OpenBLAS#4970]
Hi, 
I want to buid a .bin for sifive P870 core, can I reuse any of the targets in TargetList.txt? Or should I modify the Makefile? could you give me some guidence please, thank you~

**Comment by martin-frbg** [comment]
I think this would be the RISCV64_ZVL128B target (if I remember correctly that P870 has 128b vector length)

**Comment by liut89** [comment]
Thank you. So I think I just need to modify Makefile.riscv64:

```
ifeq ($(CORE), x280)
CCOMMON_OPT += -march=rv64imafdcv_zba_zbb_zfh_zvl512b -mabi=lp64d -ffast-math //change zvl512b to zvl128b 
FCOMMON_OPT += -march=rv64imafdcv_zba_zbb_zfh -mabi=lp64d -static
endif
```

Right?

**Comment by martin-frbg** [comment]
Which version of OpenBLAS are you trying to build ? Don't you have COMMON_OPT settings for the RISCV64_ZVL128B target in Makefile.riscv64 ? (Modifying the entries for x280 will probably not be enough, as all the BLAS kernels for x280 require the longer vector length)

**Comment by liut89** [comment]
> Which version of OpenBLAS are you trying to build ? Don't you have COMMON_OPT settings for the RISCV64_ZVL128B target in Makefile.riscv64 ? (Modifying the entries for x280 will probably not be enough, as all the BLAS kernels for x280 require the longer vector length)

So you mean I should choose target RISCV64_ZVL128B for P870?
![image](https://github.com/user-attachments/assets/07fd5c98-7392-471d-813f-7e9694f7e1c8)

**Comment by martin-frbg** [comment]
Yes I think this should be the appropriate one for the P870.
