### ISSUE TITLE
Incompatible Pointer type [-Wincompatible-pointer-types]

### ISSUE THREAD

**Issue by ghost** [xianyi/OpenBLAS#4972]
**Env details:** 
- Release: OpenBLAS-0.3.26
- Architecture: ppc64el
- Type: P8 (regression exists in p9 also)

**Following is the error:** 

`gemmt.c:605:61: note: expected ‘float *’ but argument is of type ‘bfloat16 *’ {aka ‘short unsigned int *’}
gemmt.c:609:61: error: passing argument 10 of ‘gemv_thread[transa]’ from incompatible pointer type [-Wincompatible-pointer-types]
  609 |                                                             buffer, nthreads);
      |                                                             ^~~~~~
      |                                                             |
      |                                                             bfloat16 * {aka short unsigned int *}
gemmt.c:609:61: note: expected ‘float *’ but argument is of type ‘bfloat16 *’ {aka ‘short unsigned int *’}
`

**Comment by martin-frbg** [comment]
this was fixed in 0.3.27 (through #4488 and #4491)
