### ISSUE TITLE
undefined reference to openblas_setaffinity

### ISSUE THREAD

**Issue by rongcuid** [xianyi/OpenBLAS#4973]
I am trying to use OpenBLAS on a Linux machine. No matter what config I use, I can't build openblas with the ability to set thread affinity. The current OpenBLAS is built with:

```
OpenBLAS Config: OpenBLAS 0.3.28 USE_OPENMP HASWELL MAX_THREADS=28
```

I turned `NO_AFFINITY` off, but it doesn't have any effects.

**Comment by martin-frbg** [comment]
openblas_setaffinity is implemented for plain pthread builds only (and the NO_AFFINITY option only regulates whether OpenBLAS should bind itself to the cores it "sees" on startup - which can have unwanted consequences when it is dynamically loaded by some other process, such as bind anything loaded after it to the same core(s) )
When building with USE_OPENMP, use OpenMP environment variables (OMP_PROC_BIND, OMP_PLACES) at runtime to specify how/where to bind threads to processes

**Comment by rongcuid** [comment]
Ah I see. It turns out my build script had a problem that didn't respect my option to disable OPENMP. Do you think it's better to disable the functions in header if `USE_OPENMP`?

**Comment by martin-frbg** [comment]
I'm undecided - maybe having a dummy implementation in the non-pthreads codes would be safer and simpler ?

**Comment by rongcuid** [comment]
> I'm undecided - maybe having a dummy implementation in the non-pthreads codes would be safer and simpler ?

I'm not sure. In my current case I am writing a microbenchmark and I absolutely need threads pinned exactly where I want them.

My thought is that because the decision of pthreads vs openmp is done at build time, the libraries are probably not interchangeable already. I don't know if the build system can handle a change in header definition, though.
