### ISSUE TITLE
Performance improvement of transposed [SD]GEMV on A64FX and Neoverse V1.

### ISSUE THREAD

**Issue by iha-taisei** [xianyi/OpenBLAS#4989]
I provided Pull Request #4803 for SVE-enablement of [SD]GEMV on A64FX, but there is still room for performance improvement.
Therefore, I'd like to propose another patch for such improvement of transposed [SD]GEMV on A64FX and Neoverse V1.

**Comment by Mousius** [comment]
Hi @iha-taisei,

It's always good to keep adding new optimized kernels 😸 

How would this be different from https://github.com/OpenMathLib/OpenBLAS/blob/develop/kernel/arm64/gemv_t_sve.c ?

**Comment by iha-taisei** [comment]
Hi @Mousius,

As you see above, I did loop-unrolling too.

**Comment by martin-frbg** [comment]
closing as resolved/implemented by your #4996 - thank you very much
