### ISSUE TITLE
compile error with openmp

### ISSUE THREAD

**Issue by machakann** [xianyi/OpenBLAS#499]
Hello I met a compile error when I tried to compile the latest 1ccd57ce80c6c4c42ccc6c75335623db26436f89 with openmp feature. I ran "make USE_THREAD=0 USE_OPENMP=1 NO_LAPACK=1", then got the following error message at last.

>make[1]: Entering directory '/path/to/workingdir/OpenBLAS/exports'
>perl ./gensymbol win2k    x86 dummy 0 0 0 0 0 0 "" "" > libopenblas.def
>gcc -O2 -DMS_ABI -mincoming-stack-boundary=2 -fopenmp -Wall -m32 -DF_INTERFACE_GFORT -DNO_AVX -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME=_dllinit -DASMFNAME=_dllinit_ -DNAME=dllinit_ -DCNAME=dllinit -DCHAR_NAME=\"dllinit_\" -DCHAR_CNAME=\"dllinit\" -DNO_AFFINITY -I.. -c -o dllinit.obj -s dllinit.c
>ranlib ../libopenblas_sandybridge-r0.2.13.a
>gcc -O2 -DMS_ABI -mincoming-stack-boundary=2 -fopenmp -Wall -m32 -DF_INTERFACE_GFORT -DNO_AVX -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME=_ -DASMFNAME=__ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  libopenblas.def dllinit.obj \
>-shared -o ../libopenblas.dll -Wl,--out-implib,../libopenblas.dll.a \
>-Wl,--whole-archive ../libopenblas_sandybridge-r0.2.13.a -Wl,--no-whole-archive  -defaultlib:advapi32 -lgfortran -defaultlib:advapi32 -lgfortran -lgfortran -lgomp
>Cannot export openblas_get_num_procs: symbol not defined

>../libopenblas_sandybridge-r0.2.13.a(memory.obj):memory.c:(.text+0x2a7): undefined reference to `blas_get_cpu_number'

>../libopenblas_sandybridge-r0.2.13.a(openblas_get_num_procs.obj):openblas_get_num_procs.c:(.text+0x7): undefined reference to `openblas_get_num_procs'

>collect2.exe: error: ld returned 1 exit status

>Makefile:85: recipe for target '../libopenblas.dll' failed
>make[1]: *** [../libopenblas.dll] Error 1
>make[1]: Leaving directory '/path/to/workingdir/OpenBLAS/exports'
>Makefile:104: recipe for target 'shared' failed
>make: *** [shared] Error 2

I modified only working directory paths in the message. I put the whole log here (https://gist.github.com/machakann/82aeca0cd24c0c86d472#file-compile_error-log).

After checked out to the commit 07ff001981e5fff2f0765fd410f9023b41e92565, I succeeded to compile. So it seems the latest commit is doubtful. Could you please check it? I am using windows 7, gcc 4.8.1(mingw).

**Comment by xianyi** [comment]
Thank you for your report. This is a bug for single thread version. I already fixed it on develop.

If you want use OpenMP, please try `make  USE_OPENMP=1 NO_LAPACK=1` without `USE_THREAD=0`

**Comment by machakann** [comment]
I see. Now I tried and got succeeded. Thank you for your quick response!
