### ISSUE TITLE
Support for ios simulator

### ISSUE THREAD

**Issue by LinkinPony** [xianyi/OpenBLAS#4991]
I'm trying to build OpenBLAS v0.3.28 for ios simulator with these script and environments:

- macOS 12.7.6
- Xcode 14.2
- Clang 14.0
- Build script:

(`ios-cmake/ios.toolchain.cmake` comes from this repo: https://github.com/leetal/ios-cmake)

```
cmake \
 -B "build" \
 -DDYNAMIC_ARCH=FALSE \
 -DC_LAPACK=ON \
 -DBUILD_TESTING=OFF \
 -DNOFORTRAN=ON \
 -DBUILD_RELAPACK=OFF \
 -DCMAKE_TOOLCHAIN_FILE="ios-cmake/ios.toolchain.cmake" \
 -DENABLE_VISIBILITY=ON \
 -DPLATFORM=SIMULATOR64 \
 -DTARGET=NEHALEM
```

And I encount this error:

```
[ 88%] Building ASM object kernel/CMakeFiles/kernel.dir/CMakeFiles/samax_k.S.o
/Users/momo/Desktop/Lib/OpenBLAS/kernel/x86_64/amax_sse.S:55:2: error: invalid instruction mnemonic 'prologue'
 PROLOGUE
 ^~~~~~~~
/Users/momo/Desktop/Lib/OpenBLAS/kernel/x86_64/amax_sse.S:56:2: error: invalid instruction mnemonic 'profcode'
 PROFCODE
 ^~~~~~~~
/Users/momo/Desktop/Lib/OpenBLAS/kernel/x86_64/amax_sse.S:475:2: error: invalid instruction mnemonic 'epilogue'
 EPILOGUE
 ^~~~~~~~
make[2]: *** [kernel/CMakeFiles/kernel.dir/CMakeFiles/samax_k.S.o] Error 1
make[1]: *** [kernel/CMakeFiles/kernel.dir/all] Error 2
make: *** [all] Error 2

```

In `samax_k.S` (and many other similar files), `PROLOGUE`, `PROFCODE` and `EPILOGUE` is not defined. This is because in `build/config.h`, the system info is detect as `OS_IOS`, and `commom_x86_64.h` can't handle this definition to generate proper `PROLOGUE` and other mnemonic. 

To solve this, I handly change `#define OS_IOS 1` in generated `config.h` to `#define OS_DARWIN 1`, and It seems to work fine. But I'm not familiar with assamble and not sure if there's any potential problem. I'm still trying to figure out how `config.h` is generated and adding support for it. Thanks a lot for any help or information.

**Comment by martin-frbg** [comment]
Are you actually compiling _on_ an IOS system or simulator ? I think cmake/system_check.cmake is simply getting the OS name from CMake's CMAKE_SYSTEM_NAME variable (and possibly nobody tried to compile OpenBLAS with CMake on IOS yet). Right on top of the file are a few lines that already convert CMake's "WINDOWS" into the "WINNT" that OpenBLAS uses internally, you could try if copying those right after the first "endif ()" already solves your problem:
```
if (${HOST_OS} STREQUAL "IOS")
  set(HOST_OS DARWIN)
endif ()
```

**Comment by LinkinPony** [comment]
> Are you actually compiling _on_ an IOS system or simulator ? I think cmake/system_check.cmake is simply getting the OS name from CMake's CMAKE_SYSTEM_NAME variable (and possibly nobody tried to compile OpenBLAS with CMake on IOS yet). Right on top of the file are a few lines that already convert CMake's "WINDOWS" into the "WINNT" that OpenBLAS uses internally, you could try if copying those right after the first "endif ()" already solves your problem:
> 
> ```
> if (${HOST_OS} STREQUAL "IOS")
>   set(HOST_OS DARWIN)
> endif ()
> ```

This patch works for my problem, thansk a lot! 

I'm compiling _on_ MacOS _for_ iOS simulator, so ios-cmake toolchain is trying to compile for iOS with x86_64 arch, and I think this is the problem's cause.
