### ISSUE TITLE
Build Instructions for Native Compilation of OpenBLAS on Windows for ARM(WoA)

### ISSUE THREAD

**Issue by MugundanMCW** [xianyi/OpenBLAS#5001]
This issue is regarding updating the [documentation](https://github.com/OpenMathLib/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Windows-on-ARM64) for the native compilation of OpenBLAS on WoA. The build uses the latest LLVM toolchain for WoA along with Microsoft Visual Studio.  
**Note:** A fortran compiler is necessary for building OpenBLAS included with LAPACK functions. The section below describes using flang-new which is part of LLVM’s toolchain for building LAPACK functionality with OpenBLAS.

**Prerequisites for native Compilation:**
```
1. LLVM toolchain for WoA
2. Microsoft Visual Studio 2022 Community Edition - Desktop development with C++
3. CMake for Windows
4. Ninja build tool
```
**Steps for Native Compilation:**

A fully functional native OpenBLAS for WoA that can be built as both a static and dynamic library using LLVM toolchain and Visual Studio 2022. Before starting to build, make sure that you have installed Visual Studio 2022 on your ARM device.

1. Clone OpenBLAS to your local machine and checkout to latest release of OpenBLAS 
```
git clone https://github.com/OpenMathLib/OpenBLAS.git
cd OpenBLAS
git checkout v0.3.28
```
2. Install Latest LLVM toolchain for WoA:
  - Download the Latest LLVM toolchain for WoA from the [Release](https://github.com/llvm/llvm-project/releases/tag/llvmorg-19.1.2) page.
  - Make sure to enable the option “Add LLVM to the system PATH for all the users”
  - Note: Make sure that the path of LLVM toolchain is at the top of Environment Variables section to avoid conflicts between the set of compilers available in the system path

3. Launch the Native Command Prompt for Windows ARM64:

- From the start menu search for “ARM64 Native Tools Command Prompt for Visual Studio 2022”
- Alternatively open command prompt, run the following command to activate the environment:
`"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsarm64.bat"`

4. Navigate to OpenBLAS source code directory and start building OpenBLAS by invoking Ninja:
```
cd OpenBLAS
mkdir build
cd build

cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DTARGET=ARMV8 -DCMAKE_SYSTEM_NAME="Windows" -DARCH=arm64 -DBINARY=64 -DCMAKE_SYSTEM_PROCESSOR=ARM64 -DCMAKE_C_COMPILER=clang-cl -DCMAKE_C_COMPILER_TARGET=arm64-pc-windows-msvc -DCMAKE_ASM_COMPILER_TARGET=arm64-pc-windows-msvc -DCMAKE_Fortran_COMPILER=flang-new

ninja -j16

```
**Note:** You might want to include additional options in the cmake command here. For example, the default configuration only generates a static.lib version of the library. If you prefer a DLL, you can add -DBUILD_SHARED_LIBS=ON.

**Running Tests for OpenBLAS:**

Run the test suite for OpenBLAS by invoking the ctest in the build directory:
`ctest`

**Note:** If you are running test cases with dynamic library, You might need to add the path for OpenBLAS library to the environmental path variable.

**Comment by martin-frbg** [comment]
Thank you - I take it this is intended as an improved rewording of what is currently in the included documentation (and deprecated wiki), or did you find factual errors with what is already there ?

**Comment by hendryklassen189** [comment]
- The updated build steps would able to generate both static and dynamic version of OpenBLAS library, whereas the steps in the documentation would generate only static library.

- Building OpenBLAS without using the native ARM64 command prompt will result in errors when generating source files. This issue is addressed in the updated build steps.

- The build process also includes native compilation flags for ARM64 to prevent conflicts during compilation

**Comment by MugundanMCW** [comment]
- The updated build steps would able to generate both static and dynamic version of OpenBLAS library, whereas the steps in the documentation would generate only static library.
- Building OpenBLAS without using the native ARM64 command prompt will result in errors when generating source files. This issue is addressed in the updated build steps.
- The build process also includes native compilation flags for ARM64 to prevent conflicts during compilation

**Comment by martin-frbg** [comment]
I see, thank you. What is currently there is based on a quick test with WoA in a Parallels VM on Mac, while I await delivery of an actual WoA device. Interestingly, I did not seem to need to include the additional CMake variables like SYSTEM NAME and PROCESSOR, only the gmake build was not picking up the correct `ar` and `ranlib`. I wonder why that is - if you are on an actual device, I'd think it should be even easier for CMake to figure out these settings automatically ?

**Comment by MugundanMCW** [comment]
Yes it is true, as you mentioned the CMake variables like CMAKE_SYSTEM_PROCESSOR, CMAKE_SYSTEM_NAME are not necessary, since the  CMake configuration would be able to detect these variables.

**Comment by MugundanMCW** [comment]
@martin-frbg Any further updates on this issue?
Thanks

**Comment by martin-frbg** [comment]
been too busy elsewhere, sorry. hopefully tonight...

**Comment by martin-frbg** [comment]
(Note I've only updated the copy in the docs, as the Wiki is scheduled to be removed soon, replaced by the formatted docs within the source tree. Having a Wiki was nice while it was still possible to let anybody add their build notes, but that went away when spammers and scammers started doing malicious edits every other day)

**Comment by MugundanMCW** [comment]
@martin-frbg Understandable! Thanks
