### ISSUE TITLE
crosscompile with CMake causing a problem

### ISSUE THREAD

**Issue by shrit** [xianyi/OpenBLAS#5004]
Hi,

I followed the instructions on this page and CMake did not build successfully:

https://github.com/OpenMathLib/OpenBLAS/wiki/How-to-use-OpenBLAS-on-Cortex-M

This is the problem I am getting:

```cmake
CMake Error at cmake/utils.cmake:23 (file):
  file STRINGS file
  "/build/deps/OpenBLAS-0.3.26/kernel/arm/KERNEL.ARMv5"
  cannot be read.
Call Stack (most recent call first):
  kernel/CMakeLists.txt:13 (ParseMakefileVars)
  kernel/CMakeLists.txt:1371 (build_core)
```
The file does exist and it seems that it is readable to me with correct permissions.
Any reason why this is happening?

**Comment by martin-frbg** [comment]
Is the lowercase "v" in "KERNEL.ARMV5" only a typo in your post here, or did you accidentally misspell the `TARGET=ARMV5` part of the command line ? The target (and accordingly its kernel configuration file in the sources) is all  uppercase.

**Comment by shrit** [comment]
Yes, I did, sorry for the mistake, now it works.
I did not imagine that it was related, it is parsing and matching the CMake commands
Thanks, Martin, I will close the issue
