### ISSUE TITLE
openblas make error

### ISSUE THREAD

**Issue by tudi8899** [xianyi/OpenBLAS#501]
when i make the file .It appears many errors like that:

symm.c:387: error: for each function it appears in.)
symm.c:388: error: GEMM_DEFAULT_P?undeclared (first use in this function)

why?

**Comment by xianyi** [comment]
What is your CPU? It looks like OpenBLAS cannot detect CPU correctly.

Zhang Xianyi
2015年2月9日 上午2:20于 "tudi8899" <notifications@github.com>写道：

**Comment by tudi8899** [comment]
My CPU is  Intel(R)  Itanium(R) . And my server have many CPUs.
![qq 20150210094618](https://cloud.githubusercontent.com/assets/10918243/6119878/adcfd0ca-b109-11e4-95bc-288757a89b4d.png)

**Comment by xianyi** [comment]
I am not sure OpenBLAS can support your Itanium CPU. 
You can try `make TARGET=ITANIUM2`, which uses the old codes from GotoBLAS2. The performance may slow.

**Comment by tudi8899** [comment]
Thank you  for your advince,but it still has the same errors when i use   make TARGET=ITANIUM2.
Are there any other way，or I have to change another computer?

**Comment by xianyi** [comment]
Sorry. I think we cannot support Itantium.
