### ISSUE TITLE
Some symbols missing in the ILP64 interface

### ISSUE THREAD

**Issue by ajinkya-k** [xianyi/OpenBLAS#5013]
@amontoison  and I seem to have found a bug. The `sgeqp3rk` and the `cgeqp3rk` subroutines seem to be missing in the ILP64 interface. 

See output of `nm` from one of your computers
```
nm -D libopenblas64_.0.3.28.so | grep geqp3rk
00000000018fc4e0 T cgeqp3rk_
00000000017b2060 T dgeqp3rk_64_
000000000166da70 T sgeqp3rk_
0000000001a85f40 T zgeqp3rk_64_
```

**Comment by amontoison** [comment]
I think that the symbols are just not correctly mangled (missing suffix `64_` for the ILP64 API).

**Comment by martin-frbg** [comment]
Looks like I may have forgotten to add them to the `gensymbol` script, sorry.

**Comment by ajinkya-k** [comment]
No worries! Thanks for the swift response.

**Comment by ajinkya-k** [comment]
@martin-frbg When is 0.3.29 version release planned?

**Comment by martin-frbg** [comment]
End of the year at the latest, maybe early next week if I can find the time (and nothing blocking comes up)

**Comment by ajinkya-k** [comment]
thanks! just checking. No rush!
