### ISSUE TITLE
can we build openblas for riscv (bare metal system ) using riscv64-unknown-elf toolchain

### ISSUE THREAD

**Issue by 93c59** [xianyi/OpenBLAS#5017]
I tried from following cmd
make TARGET=RISCV64_GENERIC BINARY=64 CC=riscv64-unknown-elf-gcc FC=riscv64-unknown-elf-gfortran HOSTCC=gcc NO_SHARED=1 USE_THREAD=0 NO_AFFINITY=1 CFLAGS="-march=rv64gc -mabi=lp64d -mcmodel=medany -O2 -z noexecstack -DOS_EMBEDDED" FCFLAGS="-march=rv64gc -mabi=lp64d -mcmodel=medany -O2 -z noexecstack" LDFLAGS="-lm" PREFIX=/path/to/build/ -j16
I got errors like
touch libopenblas_riscv64_generic-r0.3.28.dev.a
make -C test all
make[1]: Entering directory '/home/openblas_riscv/OpenBLAS/test'
make[1]: warning: -j16 forced in makefile: resetting jobserver mode.
riscv64-unknown-elf-gfortran -O2 -Wall -frecursive -fno-optimize-sibling-calls  -march=rv64imafdc -mabi=lp64d -fno-tree-vectorize -lm -o sblat1 sblat1.o ../libopenblas_riscv64_generic-r0.3.28.dev.a -lgfortran -lgfortran -L/home/openblas_riscv/riscv_elf/lib/gcc/riscv64-unknown-elf/14.2.0/rv64imafdc/lp64d -L/home/openblas_riscv/riscv_elf/lib/gcc/riscv64-unknown-elf/14.2.0/../../../../riscv64-unknown-elf/lib/rv64imafdc/lp64d -L/home/openblas_riscv/riscv_elf/riscv64-unknown-elf/lib/rv64imafdc/lp64d -L/home/openblas_riscv/riscv_elf/lib/gcc/riscv64-unknown-elf/14.2.0 -L/home/openblas_riscv/riscv_elf/lib/gcc/riscv64-unknown-elf/14.2.0/../../../../riscv64-unknown-elf/lib -L/home/openblas_riscv/riscv_elf/riscv64-unknown-elf/lib  -lc -lgloss 
riscv64-unknown-elf-gfortran -O2 -Wall -frecursive -fno-optimize-sibling-calls  -march=rv64imafdc -mabi=lp64d -fno-tree-vectorize -lm -o zblat3 zblat3.o ../libopenblas_riscv64_generic-r0.3.28.dev.a -lgfortran -lgfortran -L/home/openblas_riscv/riscv_elf/lib/gcc/riscv64-unknown-elf/14.2.0/rv64imafdc/lp64d -L/home/openblas_riscv/riscv_elf/lib/gcc/riscv64-unknown-elf/14.2.0/../../../../riscv64-unknown-elf/lib/rv64imafdc/lp64d -L/home/openblas_riscv/riscv_elf/riscv64-unknown-elf/lib/rv64imafdc/lp64d -L/home/openblas_riscv/riscv_elf/lib/gcc/riscv64-unknown-elf/14.2.0 -L/home/openblas_riscv/riscv_elf/lib/gcc/riscv64-unknown-elf/14.2.0/../../../../riscv64-unknown-elf/lib -L/home/openblas_riscv/riscv_elf/riscv64-unknown-elf/lib  -lc -lgloss 
riscv64-unknown-elf-gfortran -O2 -Wall -frecursive -fno-optimize-sibling-calls  -march=rv64imafdc -mabi=lp64d -fno-tree-vectorize -lm -o cblat3 cblat3.o ../libopenblas_riscv64_generic-r0.3.28.dev.a -lgfortran -lgfortran -L/home/openblas_riscv/riscv_elf/lib/gcc/riscv64-unknown-elf/14.2.0/rv64imafdc/lp64d -L/home/openblas_riscv/riscv_elf/lib/gcc/riscv64-unknown-elf/14.2.0/../../../../riscv64-unknown-elf/lib/rv64imafdc/lp64d -L/home/openblas_riscv/riscv_elf/riscv64-unknown-elf/lib/rv64imafdc/lp64d -L/home/openblas_riscv/riscv_elf/lib/gcc/riscv64-unknown-elf/14.2.0 -L/home/openblas_riscv/riscv_elf/lib/gcc/riscv64-unknown-elf/14.2.0/../../../../riscv64-unknown-elf/lib -L/home/openblas_riscv/riscv_elf/riscv64-unknown-elf/lib  -lc -lgloss 
riscv64-unknown-elf-gfortran -O2 -Wall -frecursive -fno-optimize-sibling-calls  -march=rv64imafdc -mabi=lp64d -fno-tree-vectorize -lm -o dblat3 dblat3.o ../libopenblas_riscv64_generic-r0.3.28.dev.a -lgfortran -lgfortran -L/home/openblas_riscv/riscv_elf/lib/gcc/riscv64-unknown-elf/14.2.0/rv64imafdc/lp64d -L/home/openblas_riscv/riscv_elf/lib/gcc/riscv64-unknown-elf/14.2.0/../../../../riscv64-unknown-elf/lib/rv64imafdc/lp64d -L/home/openblas_riscv/riscv_elf/riscv64-unknown-elf/lib/rv64imafdc/lp64d -L/home/openblas_riscv/riscv_elf/lib/gcc/riscv64-unknown-elf/14.2.0 -L/home/openblas_riscv/riscv_elf/lib/gcc/riscv64-unknown-elf/14.2.0/../../../../riscv64-unknown-elf/lib -L/home/openblas_riscv/riscv_elf/riscv64-unknown-elf/lib  -lc -lgloss 
... (rest of the output follows the same pattern) ...
make[1]: Leaving directory '/home/openblas_riscv/OpenBLAS/test'

make -C utest all
make[1]: Entering directory '/home/.../openblas_riscv/OpenBLAS/utest'
make[1]: warning: -j16 forced in makefile: resetting jobserver mode.
riscv64-unknown-elf-gcc -march=rv64gc -mabi=lp64d -mcmodel=medany -O2 -z noexecstack -DOS_EMBEDDED -O2 -DUTEST_CHECK -DSANITY_CHECK -DREFNAME=f_ -DMAX_STACK_ALLOC=2048 -Wall -DF_INTERFACE_GFORT -fPIC -DNO_WARMUP -DMAX_CPU_NUMBER=16 -DMAX_PARALLEL_NUMBER=1 -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.28.dev\" -march=rv64imafdc -mabi=lp64d -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I.. -lm -o openblas_utest utest_main.o test_min.o test_amax.o test_ismin.o test_rotmg.o test_axpy.o test_dotu.o test_dsdot.o test_swap.o test_rot.o test_dnrm2.o test_zscal.o test_amin.o test_axpby.o test_gemv.o test_potrs.o test_kernel_regress.o test_fork.o test_post_fork.o ../libopenblas_riscv64_generic-r0.3.28.dev.a -lgfortran -lgfortran 
.../lib/gcc/riscv64-unknown-elf/14.2.0/.../ld: test_potrs.o: in function `__ctest_potrf_smoketest_trivial_run':
test_potrs.c:(.text+0x496): undefined reference to `cabsf'
.../lib/gcc/riscv64-unknown-elf/14.2.0/.../ld: test_potrs.c:(.text+0x4cc): undefined reference to `cabs'
.../lib/gcc/riscv64-unknown-elf/14.2.0/.../ld: ../libopenblas_riscv64_generic-r0.3.28.dev.a(dnrm2_k.o): in function `dnrm2_k':
nrm2.c:(.text+0xc4): undefined reference to `sqrt'
.../lib/gcc/riscv64-unknown-elf/14.2.0/.../ld: ../libopenblas_riscv64_generic-r0.3.28.dev.a(spotf2_U.o): in function `spotf2_U':
potf2_U.c:(.text+0x152): undefined reference to `sqrt'
.../lib/gcc/riscv64-unknown-elf/14.2.0/.../ld: ../libopenblas_riscv64_generic-r0.3.28.dev.a(spotf2_L.o): in function `spotf2_L':
potf2_L.c:(.text+0x150): undefined reference to `sqrt'
.../lib/gcc/riscv64-unknown-elf/14.2.0/.../ld: ../libopenblas_riscv64_generic-r0.3.28.dev.a(cpotf2_U.o): in function `cpotf2_U':
zpotf2_U.c:(.text+0x164): undefined reference to `sqrt'
.../lib/gcc/riscv64-unknown-elf/14.2.0/.../ld: ../libopenblas_riscv64_generic-r0.3.28.dev.a(cpotf2_L.o): in function `cpotf2_L':
zpotf2_L.c:(.text+0x178): undefined reference to `sqrt'
.../lib/gcc/riscv64-unknown-elf/14.2.0/.../ld: ../libopenblas_riscv64_generic-r0.3.28.dev.a(dbdsqr.o): in function `dbdsqr_':
dbdsqr.f:(.text+0x2f8): undefined reference to `pow'
.../lib/gcc/riscv64-unknown-elf/14.2.0/.../ld: ../libopenblas_riscv64_generic-r0.3.28.dev.a(iparmq.o): in function `iparmq_':
iparmq.f:(.text+0xbc): undefined reference to `logf'
collect2: error: ld returned 1 exit status
make[1]: * [Makefile:78: openblas_utest] Error 1
make[1]: Leaving directory '/home/.../openblas_riscv/OpenBLAS/utest'
make: * [Makefile:172: tests] Error 2

is it possible to build openblas

**Comment by martin-frbg** [comment]
I'm not sure if anyone has tried this for RISCV64 yet, but I do not think it would be fundamentally different from the ARM case for which the OS_EMBEDDED option was originally created. The error messages suggest that the linker is simply missing a math library for standard functions like square root or logarithms. 
If your baremetal toolchain has this, the solution is probably as simple as  adding a line `EXTRALIB += -lm` somewhere at the top of `utest/Makefile` (This is normally declared in the toplevel Makefile.system and inherited by the test/ctest/utest, but presently it is conditional on particular operating systems, which obviously does not apply to your baremetal case).

**Comment by martin-frbg** [comment]
Sorry, overlooked the `LDFLAGS=-lm` in your commandline but according to the logs this does not appear to have been sufficient. Maybe the problem lies in the parameter sequence on the `ld` line, your `-lm` from the LDFLAGS appears to be applied before the list of objects and the libopenblas.a itself. (Notice how the `-lgfortran` follows all the files that could depend on it). In that case, the EXTRALIB line I suggested should work...

**Comment by 93c59** [comment]
I have successfully built openblas using make TARGET=RISCV64_GENERIC CC=riscv64-unknown-elf-gcc FC=riscv64-unknown-elf-gfortran HOSTCC=gcc NO_SHARED=1 USE_THREAD=0 NO_AFFINITY=1 CFLAGS="-march=rv64imafd_zicsr -mabi=lp64d -mcmodel=medany -O2 -DOS_EMBEDDED" FCFLAGS="-march=rv64imafd_zicsr -mabi=lp64d -mcmodel=medany -O2" LDFLAGS="-lm" PREFIX=/home/ram/openblas_riscv/elf_openblas
for this i installed riscv toolchain with  -march=rv64imafd_zicsr ,-mabi=lp64d and also added EXTRALIB += -lm flag in makefile.system as you said earlier from these steps i have built it 
 OpenBLAS build complete. (BLAS CBLAS LAPACK LAPACKE)

  OS               ...              
  Architecture     ... riscv64               
  BINARY           ... 64bit                 
  C compiler       ... GCC  (cmd & version : riscv64-unknown-elf-gcc (g04696df09) 14.2.0)
  Fortran compiler ... GFORTRAN  (cmd & version : GNU Fortran (g04696df09) 14.2.0)
  Library Name     ... libopenblas_riscv64_generic-r0.3.28.dev.a (Single-threading)
  make[1]: Entering directory '/home/ram/openblas_riscv/OpenBLAS'
make[1]: warning: -j16 forced in makefile: resetting jobserver mode.
Generating openblas_config.h in /home/ram/openblas_riscv/elf_openblas/include
Generating f77blas.h in /home/ram/openblas_riscv/elf_openblas/include
Generating cblas.h in /home/ram/openblas_riscv/elf_openblas/include
Copying LAPACKE header files to /home/ram/openblas_riscv/elf_openblas/include
Copying the static library to /home/ram/openblas_riscv/elf_openblas/lib
PKGFILE="/home/ram/openblas_riscv/elf_openblas/lib/pkgconfig/openblas.pc"
Generating openblas.pc in /home/ram/openblas_riscv/elf_openblas/lib/pkgconfig
Generating OpenBLASConfig.cmake in /home/ram/openblas_riscv/elf_openblas/lib/cmake/openblas
Generating OpenBLASConfigVersion.cmake in /home/ram/openblas_riscv/elf_openblas/lib/cmake/openblas
Install OK!
make[1]: Leaving directory '/home/ram/openblas_riscv/OpenBLAS'
but i have problem now it giving error of multiple defination 
/home/ram/openblas_riscv/riscv_zicsr/lib/gcc/riscv64-unknown-elf/14.2.0/../../../../riscv64-unknown-elf/bin/ld: /home/ram/openblas_riscv/elf_openblas/lib/libopenblas.a(memory.o): in function `printf':
/home/ram/openblas_riscv/riscv_zicsr/lib/gcc/riscv64-unknown-elf/14.2.0/../../../../riscv64-unknown-elf/bin/ld: /home/ram/openblas_riscv/elf_openblas/lib/libopenblas.a(memory.o): in function `atoi':
/home/ram/openblas_riscv/riscv_zicsr/lib/gcc/riscv64-unknown-elf/14.2.0/../../../../riscv64-unknown-elf/bin/ld: /home/ram/openblas_riscv/elf_openblas/lib/libopenblas.a(memory.o): in function `alloc_malloc':
memory.c:(.text+0x8): undefined reference to `malloc'
/home/ram/openblas_riscv/riscv_zicsr/lib/gcc/riscv64-unknown-elf/14.2.0/../../../../riscv64-unknown-elf/bin/ld: memory.c:(.text+0x68): undefined reference to `free'
/home/ram/openblas_riscv/riscv_zicsr/lib/gcc/riscv64-unknown-elf/14.2.0/../../../../riscv64-unknown-elf/bin/ld: /home/ram/openblas_riscv/elf_openblas/lib/libopenblas.a(memory.o): in function `blas_memory_alloc':
memory.c:(.text+0x1f2): undefined reference to `_impure_ptr'
/home/ram/openblas_riscv/riscv_zicsr/lib/gcc/riscv64-unknown-elf/14.2.0/../../../../riscv64-unknown-elf/bin/ld: memory.c:(.text+0x20c): undefined reference to `fwrite'
/home/ram/openblas_riscv/riscv_zicsr/lib/gcc/riscv64-unknown-elf/14.2.0/../../../../riscv64-unknown-elf/bin/ld: memory.c:(.text+0x226): undefined reference to `fwrite'
/home/ram/openblas_riscv/riscv_zicsr/lib/gcc/riscv64-unknown-elf/14.2.0/../../../../riscv64-unknown-elf/bin/ld: memory.c:(.text+0x23c): undefined reference to `fprintf'
/home/ram/openblas_riscv/riscv_zicsr/lib/gcc/riscv64-unknown-elf/14.2.0/../../../../riscv64-unknown-elf/bin/ld: memory.c:(.text+0x250): undefined reference to `malloc'
/home/ram/openblas_riscv/riscv_zicsr/lib/gcc/riscv64-unknown-elf/14.2.0/../../../../riscv64-unknown-elf/bin/ld: memory.c:(.text+0x260): undefined reference to `malloc'

**Comment by TommyMurphyTM1234** [comment]
- https://github.com/riscv-collab/riscv-gnu-toolchain/issues/1644#issuecomment-2545475284

**Comment by martin-frbg** [comment]
This is what is also mentioned on the Wiki page regarding compilation for "bare metal" CortexM - on a "bare metal" system you usually need to supply your own memory management functions like "malloc" and "free" (things that normally would be handled by an operating system) - the author of the Wiki page suggested libmemory, there are probably other implementations.

**Comment by martin-frbg** [comment]
Based on the comments in your linked riscv-gnu-toolchain issue it might make sense to try without the OS_EMBEDDED keyword, as the riscv "newlib" is said to include all necessary function.

**Comment by 93c59** [comment]
Thank you I will try this

**Comment by 93c59** [comment]
I have successfully built OpenBLAS for a bare-metal system using the following command:

bash
Copy code
make TARGET=RISCV64_GENERIC CC=riscv64-unknown-elf-gcc FC=riscv64-unknown-elf-gfortran HOSTCC=gcc NO_SHARED=1 USE_THREAD=0 CFLAGS="-march=rv64imafd_zicsr -mabi=lp64d -mcmodel=medany -O2 -DOS_EMBEDDED -fno-builtin-printf -fno-builtin-puts -fno-builtin-atoi -fno-builtin-malloc -fno-builtin-free" FCFLAGS="-march=rv64imafd_zicsr -mabi=lp64d -mcmodel=medany -O2" LDFLAGS="-lm" -j16
Using this library, all Level-1 functions (e.g., daxpy, dcopy, dnrm2, srot, drot, dscal, sscal) work fine. However, Level-2 and Level-3 functions do not work. I tried using the following program:

c
Copy code
#include <stdio.h>
#include <cblas.h>

#define N 3 // Use a preprocessor macro for a constant size

// Function to print a vector
void print_vector(const char* name, float* vec, int size) {
    printf("%s:\n", name);
    for (int i = 0; i < size; i++) {
        printf("%8.2f\n", vec[i]);
    }
    printf("\n");
}

// Function to print a symmetric matrix
void print_matrix(const char* name, float* mat, int size) {
    printf("%s (symmetric):\n", name);
    for (int i = 0; i < size; i++) {
        for (int j = 0; j < size; j++) {
            printf("%8.2f ", mat[i * size + j]);
        }
        printf("\n");
    }
    printf("\n");
}

int main() {
    // Symmetric matrix A (stored in row-major order)
    float A[N * N] = {
         1.0,  2.0,  3.0,
         2.0,  5.0,  6.0,
         3.0,  6.0,  9.0
    };

    // Input vector x
    float x[N] = {1.0, 2.0, 3.0};

    // Output vector y (initialized)
    float y[N] = {0.5, 1.0, 1.5};

    // Scalars
    const float alpha = 2.0;
    const float beta = 0.5;

    // Print input matrix and vectors
    print_matrix("Matrix A", A, N);
    print_vector("Vector x", x, N);
    print_vector("Vector y (before)", y, N);

    // Perform the symmetric matrix-vector multiplication
    cblas_ssymv(CblasRowMajor, CblasUpper, N, alpha, A, N, x, 1, beta, y, 1);

    // Print the result vector y
    print_vector("Vector y (after)", y, N);

    return 0;
}
The output is as follows:

markdown
Copy code
Matrix A (symmetric):
    1.00     2.00     3.00 
    2.00     5.00     6.00 
    3.00     6.00     9.00 

Vector x:
    1.00
    2.00
    3.00

Vector y (before):
    0.50
    1.00
    1.50
    TRAP
EPC : Cause : reg 0 : reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg
The program then traps with the error message:

yaml
Copy code
TRAP EPC: Cause: reg ...
After removing USE_THREAD=0 from the make command, I encountered the following error:

vbnet
Copy code
level3_thread.c: In function 'gemm_driver':
level3_thread.c:572:44: error: 'PTHREAD_MUTEX_INITIALIZER' undeclared
This error occurs repeatedly in level3_thread.c:

javascript
Copy code
level3_thread.c:572:44: error: 'PTHREAD_MUTEX_INITIALIZER' undeclared (first use in this function)
It continues with several errors regarding PTHREAD_MUTEX_INITIALIZER and PTHREAD_COND_INITIALIZER, followed by errors related to the implicit declaration of pthread_mutex_lock:

javascript
Copy code
level3_thread.c:643:3: error: implicit declaration of function 'pthread_mutex_lock' [-Wimplicit-function-declaration]
I tried using -I with the appropriate include path, but the issue remains unresolved. can you suggest any solution

**Comment by 93c59** [comment]
I have successfully built OpenBLAS for a bare-metal system using the following command:

```bash
make TARGET=RISCV64_GENERIC CC=riscv64-unknown-elf-gcc FC=riscv64-unknown-elf-gfortran HOSTCC=gcc NO_SHARED=1 USE_THREAD=0 CFLAGS="-march=rv64imafd_zicsr -mabi=lp64d -mcmodel=medany -O2 -DOS_EMBEDDED -fno-builtin-printf -fno-builtin-puts -fno-builtin-atoi -fno-builtin-malloc -fno-builtin-free" FCFLAGS="-march=rv64imafd_zicsr -mabi=lp64d -mcmodel=medany -O2" LDFLAGS="-lm" -j16
```

Using this library, all Level-1 functions (e.g., `daxpy`, `dcopy`, `dnrm2`, `srot`, `drot`, `dscal`, `sscal`) work fine. However, Level-2 and Level-3 functions do not work. I tried using the following program:

```c
#include <stdio.h>
#include <cblas.h>

#define N 3 // Use a preprocessor macro for a constant size

// Function to print a vector
void print_vector(const char* name, float* vec, int size) {
    printf("%s:\n", name);
    for (int i = 0; i < size; i++) {
        printf("%8.2f\n", vec[i]);
    }
    printf("\n");
}

// Function to print a symmetric matrix
void print_matrix(const char* name, float* mat, int size) {
    printf("%s (symmetric):\n", name);
    for (int i = 0; i < size; i++) {
        for (int j = 0; j < size; j++) {
            printf("%8.2f ", mat[i * size + j]);
        }
        printf("\n");
    }
    printf("\n");
}

int main() {
    // Symmetric matrix A (stored in row-major order)
    float A[N * N] = {
         1.0,  2.0,  3.0,
         2.0,  5.0,  6.0,
         3.0,  6.0,  9.0
    };

    // Input vector x
    float x[N] = {1.0, 2.0, 3.0};

    // Output vector y (initialized)
    float y[N] = {0.5, 1.0, 1.5};

    // Scalars
    const float alpha = 2.0;
    const float beta = 0.5;

    // Print input matrix and vectors
    print_matrix("Matrix A", A, N);
    print_vector("Vector x", x, N);
    print_vector("Vector y (before)", y, N);

    // Perform the symmetric matrix-vector multiplication
    cblas_ssymv(CblasRowMajor, CblasUpper, N, alpha, A, N, x, 1, beta, y, 1);

    // Print the result vector y
    print_vector("Vector y (after)", y, N);

    return 0;
}
```

The output is as follows:

```
Matrix A (symmetric):
    1.00     2.00     3.00 
    2.00     5.00     6.00 
    3.00     6.00     9.00 

Vector x:
    1.00
    2.00
    3.00

Vector y (before):
    0.50
    1.00
    1.50
```

The program then traps with the error message:

```
TRAP
EPC : Cause : reg 0 : reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg reg
```

I tried  by removing `USE_THREAD=0` (I thought issue with this flag) from the `make` command for building openblas, I encountered the following error:

```
level3_thread.c: In function 'gemm_driver':
level3_thread.c:572:44: error: 'PTHREAD_MUTEX_INITIALIZER' undeclared
```

This error occurs repeatedly in `level3_thread.c`:

```
level3_thread.c:572:44: error: 'PTHREAD_MUTEX_INITIALIZER' undeclared (first use in this function)
```

It continues with several errors regarding `PTHREAD_MUTEX_INITIALIZER` and `PTHREAD_COND_INITIALIZER`, followed by errors related to the implicit declaration of `pthread_mutex_lock`:

```
level3_thread.c:643:3: error: implicit declaration of function 'pthread_mutex_lock' [-Wimplicit-function-declaration]
```
I tried using `-I` with the appropriate include path, but the issue remains unresolved.
make TARGET=RISCV64_GENERIC CC=riscv64-unknown-elf-gcc FC=riscv64-unknown-elf-gfortran HOSTCC=riscv64-unknown-elf-gcc NO_SHARED=1 USE_THREAD=0 CFLAGS="-march=rv64imafd_zicsr -mabi=lp64d -mcmodel=medany -O2 -DOS_EMBEDDED -fno-builtin-printf -fno-builtin-puts -fno-builtin-atoi -fno-builtin-malloc -fno-builtin-free -I/riscv-gnu-toolchain/glibc/include" FCFLAGS="-march=rv64imafd_zicsr -mabi=lp64d -mcmodel=medany -O2" LDFLAGS="-lm" 
Can you suggest me any solution
---

**Comment by TommyMurphyTM1234** [comment]
Try debugging your program to see where and why it traps?

**Comment by 93c59** [comment]
It getting trap at cblas_ssymv  function statement

**Comment by martin-frbg** [comment]
can't look right now, but if the library passed the supplied BLAS and CBLAS tests during build the error is probably in your code. if you run into pthread-related errors when trying to build a multithreaded library, check if you have pthread.h in your toolchain's include directory at all. if it has it but does not declare mutex locks, you can try with -DUSE_PTHREAD_SPINLOCK - anyway this should not be related to your ssymv problem

**Comment by 93c59** [comment]
But sir level 1 function like daxpy,dcopy ,dscal ,sscal ,dswap working fine it's just problem with sgemv ,strmv function of cblas and I checked program also . It's getting compiled successfully when I am sending it's bin file to my riscv FPGA board it getting TRAP

**Comment by martin-frbg** [comment]
RISCV64_GENERIC uses pure C kernels that are in use on other platforms as well - getting a trap would suggest either the call parameters were seriously wrong or the compiler misoptimized a function. Can you please check if xscblat2 from the ctest folder runs correctly  on your board, when you feed it the file `sin2` as standard input ?
Also, how much memory does your FPGA board have ?

**Comment by 93c59** [comment]
- My FPGA board have 256MB RAM.
- I am sending the bin file which I am created using riscv64-unknown-elf- toolchain(cross-compiling for riscv) through ethernet to the FPGA board .
- That's why I am not able give any command line argument to run  xscblat2 which need sin2. (TRAP exception )
- Following are my compilation and linking command in make file
>Compiling input.c
riscv64-unknown-elf-gcc -march=rv64imafd -mabi=lp64d -mcmodel=medany -fno-builtin-printf -fno-builtin-puts -fno-builtin-malloc -fno-builtin-free -fdata-sections -ffunction-sections -fno-builtin-memcmp  -I/bsp/include -I/openblas_riscv/elf_openblas/include --specs=nano.specs  -c input.c -o build/input.o

> Linking build/input.o 
riscv64-unknown-elf-gcc -Wl,--gc-sections -Wl,-Map,build/input.map -nostartfiles -march=rv64imafd -mabi=lp64d -mcmodel=medany -T /bsp/common/mbl.lds -L/bsp  build/input.o -Wl,--start-group -lvega -Wl,--whole-archive -lopenblas -Wl,--no-whole-archive -lc -lgcc -lm -Wl,--end-group -L/openblas_riscv/elf_openblas/lib -o build/input.elf
Build successful!
ELF     : input
Binary  : input.bin
Hex     : input.hex
Dump    : input.dump
Files are generated in build folder.
Size information
   text    data     bss     dec     hex filename
  15732      64      84   15880    3e08 build/input.elf
  then I send input.bin to FPGA board using UART

**Comment by martin-frbg** [comment]
There's a small chance that  you are simply running out of space for internal memory buffers, try building with `-DBUFFERSIZE=18` or a smaller number. But unfortunately I have no experience with embedded systems and I wouldn't be able to tell you if the problem is e.g. with your compiler options.

**Comment by TommyMurphyTM1234** [comment]
> * I am sending the bin file which I am created using riscv64-unknown-elf- toolchain(cross-compiling for riscv) through UART to the FPGA board .
> * That's why I am not able give any command line argument to run  xscblat2 which need sin2. (TRAP exception )

Can't you fake the command line arguments by modifying the code in `main()`?

**Comment by TommyMurphyTM1234** [comment]
Are you sure that you're compiling everything with a consistent RISC-V `arch/abi`? There are three different versions mentioned in this thread and it's not clear which one you're using now and if you're using it consistently. 

- `rv64gc/lp64d`
- `rv64imafd_zicsr/lp64d`
- `rv64imafd/lp64d`

**Comment by 93c59** [comment]
I am using other flags earlier but now I am just using "rv64imafd_zicsr/lp64d"

**Comment by TommyMurphyTM1234** [comment]
> I am using other flags earlier but now I am just using "rv64imafd_zicsr/lp64d"

That's not what this says:

- https://github.com/OpenMathLib/OpenBLAS/issues/5017#issuecomment-2553166617

**Comment by 93c59** [comment]
I think there might have been a small oversight here.Thanks for pointing.But sir I have tried with both the flags rv64imafd_zicsr/lp64d and rv64imafd/lp64d but the problem is same with both flags,the level-1 function are working and the level-2 function giving TRAP exception

**Comment by TommyMurphyTM1234** [comment]
> the problem is same with both flags,the level-1 function are working and the level-2 function giving TRAP exception

Is the trap in question a low level RISC-V exception or a higher level OpenBLAS library trap (handler?)? If it's the former then there are established ways to investigate RISC-V exceptions using CSRs such as `mcause`, `mepc`, `mtval` etc. If this is relevant here then you should be able to find more about this by doing a web search.
