### ISSUE TITLE
Tracing OpenBLAS Function Calls During Benchmark Function Execution

### ISSUE THREAD

**Issue by Harishmcw** [xianyi/OpenBLAS#5019]
This issue is about tracing the execution flow when running the bench_blas.py script to benchmark OpenBLAS on x64:

- When a function like GEMM is called for benchmarking in the Python script, from our understanding it is internally mapped to the corresponding optimized [kernel implementation](https://github.com/OpenMathLib/OpenBLAS/blob/develop/kernel/x86_64/) supported by system architecture in OpenBLAS.
- Each benchmarking function provides different variant of tests(c, z, d, s.) that are imported using [openblas_wrap](https://github.com/OpenMathLib/OpenBLAS/blob/develop/benchmark/pybench/openblas_wrap/__init__.py) module inside benchmarks. The module "openblas_wrap" gets these functions from _flapack module which acts as a wrapper that provides openblas function attributes for running each test with different variants.
- When running benchmarks for the OpenBLAS library, I would like to track the function flow and identify which core implementation (as mentioned in the link above) is mapped to each benchmark test. However, using Python profilers like [CProfile](https://docs.python.org/3/library/profile.html#module-cProfile) or [LineProfiler](https://github.com/pyutils/line_profiler) only provides information up to the point of the wrapped function call, but does not give insights into the time taken by the different call stacks to core implementation of tests.
- Additionally, is there a tool available that can be run on local machines to track function calls during the benchmark, from the Python function call to the actual assembly-level kernel implementation?

Thanks

**Comment by martin-frbg** [comment]
I'm not intimately familiar with the Python side of things, but in general it will probably make more sense to use the KERNEL.cpu files in the relevant kernel/(architecture) directory to learn which source file maps to each BLAS kernel. Anything not mentioned there is either in the non-suffixed KERNEL file, or has fallbacks declared in the respective (C)Makefiles in the kernel directory. (The KERNEL files are in gmake syntax and actually used as such by the Makefiles,
for CMake a translation function is provided in cmake/utils.cmake.)
Call flow is from the respective file in interface/ to driver code in driver/level2 or level3 and from there to the optimized kernel. Some of the files in interface call the optimized kernel directly. If you're on Linux, the `perf` tool is probably a good starting point for identifying bottlenecks, for general code flow you could e.g. put a breakpoint on the kernel in gdb or lldb and call up a backtrace.
