### ISSUE TITLE
Trying to build in Windows10 with IntelLLVM

### ISSUE THREAD

**Issue by sephenisee** [xianyi/OpenBLAS#5020]
Hello,

I am trying to build OpenBLAS in Windows with Intel's C and Fortran compilers. I am also using VS2022 preview for build environment.
Intel made their IntelLLVM compilers icx for C language and ifx for Fortran as default, and it seems to cause some conflict with prebuild setup.

In the x64 Native Tools, I activate the Intel's environment. Then, I try to configure by executing the line: cmake .. -G "Ninja" -DCMAKE_CXX_COMPILER=icx -DCMAKE_C_COMPILER=icx -DCMAKE_Fortran_COMPILER=ifx -DCMAKE_MT=mt -DBUILD_WITHOUT_LAPACK=no -DNOFORTRAN=0 -DDYNAMIC_ARCH=OFF -DCMAKE_BUILD_TYPE=Release

It tries to compile the cpuid.S, which seems to be ARM related and gives other error messages.
Full error messages are copied in configure_errors.txt files.
[configure_errors.txt](https://github.com/user-attachments/files/18169775/configure_errors.txt)

In the prebuild.cmake, should I edit the line so that it configures with -DFORCE_GENERIC like MSVC?

Thank you in advance,
Sean

**Comment by martin-frbg** [comment]
Hmm, I've read in other contexts that the 2025 version is not yet correctly handled by CMake. I'm fairly certain that icx used to be able to process cpuid.S - which contains only conditionally-compiled i386 assembly for ancient Macs anyway.

I think you could try just removing the `list (append getarch_src ` line in prebuild.cmake that adds cpuid.S to the compilation - forcing everything to use the generic C kernels would cost quite a bit of performance. (Though you might run into similar errors with other .S files later on - for the moment I hope it is only CMake getting confused, and not the compiler - ".S" is an "ASM" file so it should not balk at it.

 BTW which version of OpenBLAS are you trying to build - is it 0.3.28 (or develop) ?

**Comment by sephenisee** [comment]
Thanks for the prompt response. Commenting out the line you mention helped to complete the configuring process. I cloned the develop branch. 
During the build, it complains about the _Fcomplex and _Dcomplex. I already had some experience with this. I believe IntelLLVM for MSVC environment does not follow MSVC complex ... Also, it does not seem to support C99 in Windows environment.  
I think the easiest option is to define LAPACK_COMPLEX_STRUCTURE in lapacke_config.h. Do you have other suggestions?

**Comment by martin-frbg** [comment]
I'm not sure - where does it complain ? LAPACK_COMPLEX_STRUCTURE should already get defined by system.cmake line 670 when the operating system is identified as Windows, so something seems to be odd here.

**Comment by sephenisee** [comment]
The line 71 in lapacke_config.h has $if defined(_MSC_VER) and it defines _CRT_USE_C_COMPLEX_H and uses MSVC complex definition. 
I just edited it to "_MSC_VER1" so it does not go through that condition, so it automatically defines LAPACK_COMPLEX_STRUCTURE. After this change, the build process proceeds but I get a bunch of link errors at the end.
It looks like openblas.lib is built, but many of external symbols are undefined, causing unresolved external symbol. 
For example, I tried to build only cblat1.exe. I get linking error message: unresolved external symbol CAXPY referenced in function HEADER. All the externals in function HEADER are not resolved.

**Comment by martin-frbg** [comment]
Does icx define _MSC_VER ? I'd normally assume this to be set by the Microsoft compiler, maybe the ifdef needs to be expanded to include "but not Intel". Not sure why you'd get a bunch of link errors now, unless building the caxpy kernel (or its interface code) failed earlier.

**Comment by sephenisee** [comment]
I forgot which CMake file I saw this, but I remember that the compiler-frontend-variant and compiler-simulate-id are MSVC for IntelLLVM. Do you think these might be related? 
I will try to see if kernel or the interface code are compiled properly.

**Comment by martin-frbg** [comment]
Could be related, yes. But then this does not appear to have caused problems in the past (unless it is a very recent change in the Intel compiler package, and as said there are some concerns about its interfacing with current CMake). Might also want to check if the "missing symbol" problem only affects complex functions, or if you get the same for sblat1/saxpy.

**Comment by sephenisee** [comment]
I am checking the external symbols in openblas.lib. It looks like caxpy symbols have underscore "_". Do you think this might be related to the linking issue? I attached the image of output from dumpbin.
![dumpbin_image](https://github.com/user-attachments/assets/b0c91433-e4a9-472c-99dc-d4c4fd904c9e)

**Comment by martin-frbg** [comment]
Seems unlikely to me but I can't rule it out. The CMake build has a few compiler specifics hardcoded (or relying on CMake's own checks) that the gmake build calls the c_check and f_check scripts for. But so far these settings worked... I'll see if I can set up a quick test tomorrow (getting a bit late here already)

**Comment by sephenisee** [comment]
Thank you so much for your help today!

**Comment by martin-frbg** [comment]
Haven't quite succeeded yet, unfortunately. So far, I got the build to use consistent (no) trailing underlines on symbol names, but I cannot get CMake to include build instructions for the assembly (.S) kernels in the Ninja build file. (CMake appears to identify the compiler/assembler correctly as IntelLLVM though, and invoking icx manually on any .S file generates an object without complaint as well.)

**Comment by sephenisee** [comment]
Thanks for the update. I was not able to get much progress either on linking. I am trying to see if there were any problems during the compilation of the library. Missing symbol problem also appears for sblat1/saxpy and for dblat1/daxpy. Please let me know if you have any suggestion for me to try.

**Comment by sephenisee** [comment]
It looks like ifx uses Uppercase without trailing underscore for name mangling for Fortran. But symbols in openblas.lib after compilation are stored following gfortran name mangling convention which is lowercase with trailing underscore. What would you suggest in editing CMake file(s) so that .f.obj files and openblas.lib have same name mangling style?

**Comment by parteimeister** [comment]
I also encountered this problem. As a temporary solution - you can compile the library with dynamic linking using MinGW and use it in a project with the MSVC compiler. As far as I remember, the library compiled this way does not pass testing, but this seems to be a bug in the tests themselves. Nevertheless, this option is definitely suitable if you plan to use the library as a dependency for the Eigen library in a CMake project on Windows.

**Comment by martin-frbg** [comment]
When you compile with dynamic linking on Windows, the tests currently require the freshly created dll to be in the path (or in the same place as the respective test executable), which will not be the case...
I haven't found an explanation for the problem with Ninja yet (seems this occured before with an earlier version of cmake, but should be fixed since 3.23 or so - I think my Windows setup has 3.29.something, which may not be the latest anymore either... Trying with `-G "MinGW Makefiles" currently ends up with "rc.exe not found" but that may be a path setup problem between oneAPI and MSVC... I think I saw that before but can't remember the solution...

**Comment by parteimeister** [comment]
I just checked how testing works - the problem there is not that ctest can't find dll files, but that ctest can't find tests

```
C:\Users\User\libs\temp\OpenBLAS\build>ctest --progress --output-on-failure
Test project C:/Users/User/libs/temp/OpenBLAS/build
  0/120 Test   #1: openblas_utestExit code 0xc0000135
  1/120 Test   #1: openblas_utest...............................................................................***Exception:   0.01 sec

  1/120 Test   #2: openblas_utest_extExit code 0xc0000135
  2/120 Test   #2: openblas_utest_ext...........................................................................***Exception:   0.00 sec

  2/120 Test   #3: sblas1Exit code 0xc0000135
  3/120 Test   #3: sblas1.......................................................................................***Exception:   0.01 sec

  4/120 Test   #4: sblas2.......................................................................................***Failed    0.26 sec
Get-Content : Cannot find path 'C:\Users\User\libs\temp\OpenBLAS\build\test\SBLAT2.SUMM' because it does not exist.
At C:\Users\User\libs\temp\OpenBLAS\build\test\test_helper.ps1:5 char:6
+ If ((Get-Content $args[2] | %{$_ -match "FATAL"}) -contains $true) {
+      ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\User\l...est\SBLAT2.SUMM:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand


  5/120 Test   #5: sblas3.......................................................................................***Failed    0.27 sec
Get-Content : Cannot find path 'C:\Users\User\libs\temp\OpenBLAS\build\test\SBLAT3.SUMM' because it does not exist.
At C:\Users\User\libs\temp\OpenBLAS\build\test\test_helper.ps1:5 char:6
+ If ((Get-Content $args[2] | %{$_ -match "FATAL"}) -contains $true) {
+      ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\User\l...est\SBLAT3.SUMM:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand


  5/120 Test   #6: dblas1Exit code 0xc0000135
  6/120 Test   #6: dblas1.......................................................................................***Exception:   0.01 sec

  7/120 Test   #7: dblas2.......................................................................................***Failed    0.27 sec
Get-Content : Cannot find path 'C:\Users\User\libs\temp\OpenBLAS\build\test\DBLAT2.SUMM' because it does not exist.
At C:\Users\User\libs\temp\OpenBLAS\build\test\test_helper.ps1:5 char:6
+ If ((Get-Content $args[2] | %{$_ -match "FATAL"}) -contains $true) {
+      ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\User\l...est\DBLAT2.SUMM:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand


  8/120 Test   #8: dblas3.......................................................................................***Failed    0.27 sec
Get-Content : Cannot find path 'C:\Users\User\libs\temp\OpenBLAS\build\test\DBLAT3.SUMM' because it does not exist.
At C:\Users\User\libs\temp\OpenBLAS\build\test\test_helper.ps1:5 char:6
+ If ((Get-Content $args[2] | %{$_ -match "FATAL"}) -contains $true) {
+      ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\User\l...est\DBLAT3.SUMM:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand


  8/120 Test   #9: cblas1Exit code 0xc0000135
  9/120 Test   #9: cblas1.......................................................................................***Exception:   0.01 sec

 10/120 Test  #10: cblas2.......................................................................................***Failed    0.28 sec
Get-Content : Cannot find path 'C:\Users\User\libs\temp\OpenBLAS\build\test\CBLAT2.SUMM' because it does not exist.
At C:\Users\User\libs\temp\OpenBLAS\build\test\test_helper.ps1:5 char:6
+ If ((Get-Content $args[2] | %{$_ -match "FATAL"}) -contains $true) {
+      ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\User\l...est\CBLAT2.SUMM:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand


 11/120 Test  #11: cblas3.......................................................................................***Failed    0.30 sec
Get-Content : Cannot find path 'C:\Users\User\libs\temp\OpenBLAS\build\test\CBLAT3.SUMM' because it does not exist.
At C:\Users\User\libs\temp\OpenBLAS\build\test\test_helper.ps1:5 char:6
+ If ((Get-Content $args[2] | %{$_ -match "FATAL"}) -contains $true) {
+      ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\User\l...est\CBLAT3.SUMM:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand


 12/120 Test  #12: cblas3_3m....................................................................................***Failed    0.26 sec
Get-Content : Cannot find path 'C:\Users\User\libs\temp\OpenBLAS\build\test\CBLAT3_3M.SUMM' because it does not exist.
At C:\Users\User\libs\temp\OpenBLAS\build\test\test_helper.ps1:5 char:6
+ If ((Get-Content $args[2] | %{$_ -match "FATAL"}) -contains $true) {
+      ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\User\l...\CBLAT3_3M.SUMM:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand


 12/120 Test  #13: zblas1Exit code 0xc0000135
 13/120 Test  #13: zblas1.......................................................................................***Exception:   0.01 sec

 14/120 Test  #14: zblas2.......................................................................................***Failed    0.29 sec
Get-Content : Cannot find path 'C:\Users\User\libs\temp\OpenBLAS\build\test\ZBLAT2.SUMM' because it does not exist.
At C:\Users\User\libs\temp\OpenBLAS\build\test\test_helper.ps1:5 char:6
+ If ((Get-Content $args[2] | %{$_ -match "FATAL"}) -contains $true) {
+      ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\User\l...est\ZBLAT2.SUMM:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand


 15/120 Test  #15: zblas3.......................................................................................***Failed    0.28 sec
Get-Content : Cannot find path 'C:\Users\User\libs\temp\OpenBLAS\build\test\ZBLAT3.SUMM' because it does not exist.
At C:\Users\User\libs\temp\OpenBLAS\build\test\test_helper.ps1:5 char:6
+ If ((Get-Content $args[2] | %{$_ -match "FATAL"}) -contains $true) {
+      ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\User\l...est\ZBLAT3.SUMM:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand


 16/120 Test  #16: zblas3_3m....................................................................................***Failed    0.27 sec
Get-Content : Cannot find path 'C:\Users\User\libs\temp\OpenBLAS\build\test\ZBLAT3_3M.SUMM' because it does not exist.
At C:\Users\User\libs\temp\OpenBLAS\build\test\test_helper.ps1:5 char:6
+ If ((Get-Content $args[2] | %{$_ -match "FATAL"}) -contains $true) {
+      ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\User\l...\ZBLAT3_3M.SUMM:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand


106/120 Test #107: xscblat1Exit code 0xc0000135ares_routinesDecomposition_routinesbalanced_matricesesriceses
107/120 Test #107: xscblat1.....................................................................................***Exception:   0.01 sec

109/120 Test #110: xdcblat1Exit code 0xc0000135
110/120 Test #110: xdcblat1.....................................................................................***Exception:   0.01 sec

112/120 Test #113: xccblat1Exit code 0xc0000135
113/120 Test #113: xccblat1.....................................................................................***Exception:   0.01 sec

116/120 Test #117: xzcblat1Exit code 0xc0000135
117/120 Test #117: xzcblat1.....................................................................................***Exception:   0.01 sec

120/120 Test #120: xzcblat3_3m
83% tests passed, 20 tests failed out of 120

Total Test time (real) =  26.49 sec

The following tests FAILED:
          1 - openblas_utest (Exit code 0xc0000135
)
          2 - openblas_utest_ext (Exit code 0xc0000135
)
          3 - sblas1 (Exit code 0xc0000135
)
          4 - sblas2 (Failed)
          5 - sblas3 (Failed)
          6 - dblas1 (Exit code 0xc0000135
)
          7 - dblas2 (Failed)
          8 - dblas3 (Failed)
          9 - cblas1 (Exit code 0xc0000135
)
         10 - cblas2 (Failed)
         11 - cblas3 (Failed)
         12 - cblas3_3m (Failed)
         13 - zblas1 (Exit code 0xc0000135
)
         14 - zblas2 (Failed)
         15 - zblas3 (Failed)
         16 - zblas3_3m (Failed)
        107 - xscblat1 (Exit code 0xc0000135
)
        110 - xdcblat1 (Exit code 0xc0000135
)
        113 - xccblat1 (Exit code 0xc0000135
)
        117 - xzcblat1 (Exit code 0xc0000135
)
Errors while running CTest
```

**Comment by martin-frbg** [comment]
@parteimeister it won't find output files for checking if the tests weren't run - the BLAS2/3 tests write their output to file which the helper script then checks for occurrence of the word "FAILED". But anyway that is a wholly different topic

**Comment by sephenisee** [comment]
@parteimeister Thank you for your suggestion on the temporary solution using dynamic linking with MinGW. 

@martin-frbg I am still interested in solving this issue but I don't want to bother you too much on this, especially close to holiday season. If you think there is no simple solution, I can try with MinGW as @parteimeister suggested. Do you think this issue may be considered to be fixed by next release?

**Comment by sephenisee** [comment]
I wrote a .asm that maps ifx's default naming to gfortran naming convention just to build 'dblat1.exe', and added this during the linking process. 
It looks like there is another issue on openblas.lib. After compilation, I get .S files for some kernel files such as dcopy_k.S, dnrm2_k.S and etc. That seems to be related on why dcopy_k, dnrm2_k, and etc are undefined in openblas.lib. Besides the inconsistency in the name mangling, this .S files also seem to cause trouble with IntelLLVM and Window's VS2022 combination with current prebuild.cmake.

**Comment by martin-frbg** [comment]
This is what I wrote yesterday - the erroneous underscores added to the symbols can be worked around, actually they are the result of a bad assumption in the cmake files that "every" compiler will produce/want them anyway. (In contrast, the gmake build runs a shell script that parses compiler output to find out). The main issue however is that while the CMake environment creates all the correct build wrappers for the .S files, it apparently does not write the corresponding build
rules into the build.ninja file. This appears to be a fault of CMake, most likely specific to its interaction with the very new Intel2025 as it did not happen in the past.

**Comment by sephenisee** [comment]
I see ... Thanks for the explanation on the main issue.

**Comment by martin-frbg** [comment]
Major progress - the assembler problem can be solved by additionally specifying `-DCMAKE_ASM_SOURCE_FILE_EXTENSIONS=S` (although .S is one of the documented defaults already, and we saw it in the initial error message for cpuid.S).
Now the build of the "extended" utests is failing due to a symbol clash between the BLAS ?copy and a local utility function of the same name, but the library itself looks good

**Comment by sephenisee** [comment]
Nice! Thanks for the fix. I checked out your branch and just built the library. As you mentioned, it fails during linking for building test executables such as dblat1.exe but I see that dcopy_k and dnrm2_k, etc are defined in the library. I think name mangling is case sensitive. Currently, your fix removes the trailing underscore, but it seems to keep the symbols in lowercase. Fortran object files like dblat1.f.obj look for external symbols in uppercase like DASUM, DAXPY, etc. Do you think this might be a reason causing the linking issue?

**Comment by martin-frbg** [comment]
I have just updated the PR to take care of the remaining symbol name conflicts (actually I redid the entire PR to avoid the large diff from inadvertently committing with Windows line endings), turns out I only needed to propagate the "NOCHANGE" flag from LAPACKE mangling to the tests.
Maybe I'll try if I can handle the gotcha of the ASM_SOURCE_FILE_EXTENSIONS=S internally too

**Comment by sephenisee** [comment]
Thanks! I will check out the new PR.

**Comment by martin-frbg** [comment]
(CMAKE_ASM_SOURCE_FILE_EXTENSIONS "S") now declared in toplevel CMakeLists.txt

**Comment by jiangjianshan** [comment]
@martin-frbg ,  I have make a little different patch comparing from your for OpenBLAS version 0.3.28. So that can use icx-cl and ifx to build it. Some part of patch are from your but add some modification. The the build behaviour can be more close to use clang-cl and flang-new. 
 The patch is on my repository [msvc-pkg](https://github.com/jiangjianshan/msvc-pkg). The patch and build script for OpenBLAS package is located at packages/OpenBLAS in https://github.com/jiangjianshan/msvc-pkg.
