### ISSUE TITLE
Develop a suite of RVV-optimized code that can be applied to various vector lengths (VLENs).

### ISSUE THREAD

**Issue by tingboliao** [xianyi/OpenBLAS#5028]
Is there a plan to develop a suite of RVV-optimized code that can be applied to various vector lengths (VLENs), rather than developing RVV-optimized code specific to certain VLENs for each processor with built-in vectors, , such as C910, X280, etc., shown as below in the Makefile.riscv64 file?

![image](https://github.com/user-attachments/assets/f8f5bcad-5b99-47c2-9da5-a7a5e9d7d793)

**Comment by martin-frbg** [comment]
see #4050 - RVV length specificity was a necessary evil while  the standards were maturing and individual physical implementations were key

**Comment by tingboliao** [comment]
> see #4050 - RVV length specificity was a necessary evil while the standards were maturing and individual physical implementations were key

Thanks

**Comment by martin-frbg** [comment]
(C910V will have to remain a separate target as it only supports RVV 0.7.1)
