### ISSUE TITLE
Two different tarballs offered for download

### ISSUE THREAD

**Issue by nalimilan** [xianyi/OpenBLAS#506]
A Julia user noticed (https://github.com/JuliaLang/julia/issues/10295) that two different tarballs of OpenBLAS are offered  for download, with different checksums. This can create some confusion.

The GitHub releases webpage at https://github.com/xianyi/OpenBLAS/releases gives this link:
https://github.com/xianyi/OpenBLAS/archive/v0.2.13.tar.gz

While http://www.openblas.net/ gives this link:
http://github.com/xianyi/OpenBLAS/tarball/v0.2.13

Is there any reason for this?

**Comment by xianyi** [comment]
@nalimilan , I just noticed that they are the different links.

Should I change the link on www.openblas.net?

**Comment by nalimilan** [comment]
Probably. If the tarball is simply the result of `git export`, i.e. if it only contains the files tracked by git in the tagged commit, then using the URL from GitHub is more logical.
