### ISSUE TITLE
Make error: /usr/bin/ld: cannot find -lgfortran

### ISSUE THREAD

**Issue by piselin** [xianyi/OpenBLAS#507]
This is the error I get after using make:

/usr/bin/ld: cannot find -lgfortran

The same happens if I build with 
>make FC=gfortran

CPU is a Intel i7-3720QM CPU @ 2.60GHz and gfortran (4.6.4) is installed.
What am I doing wrong?

**Comment by xianyi** [comment]
I think the library was built fine. You need to use gfortran as the linker.

**Comment by piselin** [comment]
Thanks for your quick answer. I had a wrong symbolic link which pointed to the wrong version of gcc. It works now.

**Comment by Murmele** [comment]
How did you solve your symbolic link problem? I have the same problem

**Comment by Murmele** [comment]
How did you solve your symbolic link problem? I have the same problem
