### ISSUE TITLE
Link error during build with TARGET=P2

### ISSUE THREAD

**Issue by ttuegel** [xianyi/OpenBLAS#510]
With `TARGET=P2`, I get the following link error when building OpenBLAS 0.2.13 on Linux:
```
building ../libopenblas_p2p-r0.2.13.so
cc -O2 -Wall -m32 -DF_INTERFACE_GFORT -fPIC -DNO_AVX -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  -shared -o ../libopenblas_p2p-r0.2.13.so \
-Wl,--whole-archive ../libopenblas_p2p-r0.2.13.a -Wl,--no-whole-archive \
-Wl,-soname,libopenblas.so.0 -lm -lpthread -lgfortran -lm -lpthread -lgfortran
cc -O2 -Wall -m32 -DF_INTERFACE_GFORT -fPIC -DNO_AVX -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  -w -o linktest linktest.c ../libopenblas_p2p-r0.2.13.so  && echo OK.
../libopenblas_p2p-r0.2.13.so: undefined reference to `sgemm_itcopy'
../libopenblas_p2p-r0.2.13.so: undefined reference to `cgemm_incopy'
../libopenblas_p2p-r0.2.13.so: undefined reference to `sgemm_incopy'
../libopenblas_p2p-r0.2.13.so: undefined reference to `cgemm_itcopy'
collect2: error: ld returned 1 exit status
make[1]: *** [../libopenblas_p2p-r0.2.13.so] Error 1
make[1]: Leaving directory `/tmp/nix-build-openblas-0.2.13.drv-0/xianyi-OpenBLAS-aceee4e/exports'
make: *** [shared] Error 2
```

(I am trying to build a generic i686 library for the NixOS Linux distribution. If there is a preferred `TARGET` setting for distribution builds, please let me know. I couldn't find any particular recommendation in the OpenBLAS documentation.)

**Comment by xianyi** [comment]
@ttuegel , I think TARGET=NEHALEM is a safe choice for current generic x86 CPUs.

**Comment by xianyi** [comment]
If you want to support more old CPUs by only one target, please try `make TARGET=PRESCOTT`

**Comment by ttuegel** [comment]
We'll go with `TARGET=PRESCOTT`. Our performance-oriented users can set an option to get a custom build for their local machine anyway; the goal of the generic build is to support as many CPUs as possible without regard for performance, so Nehalem is much too new in that regard. Thank you!
