### ISSUE TITLE
Installation problems on Ubuntu 14.04

### ISSUE THREAD

**Issue by araymund** [xianyi/OpenBLAS#511]
I follow the instructions from:

http://deeplearning.net/software/theano/install_ubuntu.html

but unfortunately i issue the following command:

sudo make PREFIX=/usr/local/ install

i got this error:

make -j 1 -f Makefile.install install
make[1]: Entering directory `/home/vagrant/OpenBLAS'
Generating openblas_config.h in /usr/local//include
Generating f77blas.h in /usr/local//include
Generating cblas.h in /usr/local//include
Copying LAPACKE header files to /usr/local//include
Copying the static library to /usr/local//lib
Copying the shared library to /usr/local//lib
install: cannot stat ‘libopenblas_nehalem-r0.2.13.so’: No such file or directory

make[1]: *** [install] Error 1
make[1]: Leaving directory `/home/vagrant/OpenBLAS'
make: *** [install] Error 2
vagrant@vagrant-ubuntu-trusty-64:~/OpenBLAS$

My OS:is:

$ -uname:

Linux vagrant-ubuntu-trusty-64 3.13.0-30-generic #55-Ubuntu SMP Fri Jul 4 21:40:
53 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Yours Sincerely

Alfredo Raymundo

araymund@imp.mx

**Comment by martin-frbg** [comment]
The actual error must have come before that, can you post more of the error messages please ? (Also, do  you see any libopenblas_* in /home/vagrant/OpenBLAS ?)

**Comment by araymund** [comment]
Mark:

I found:

libopenblas_nehalem-r0.2.13.a

Thanks

Alfredo Raymundo

________________________________

**Comment by xianyi** [comment]
I am going to close this issue. If you any questions, please don't hesitate to reopen it.
