### ISSUE TITLE
IBM POWER 8 arch support

### ISSUE THREAD

**Issue by fcannini** [xianyi/OpenBLAS#512]
Hello!

Are there any plans to support this architecture in the near future? I'm aware that GotoBLAS supported older POWER architectures, like 6 and 7. Would i be able to use this older GotoBLAS code in the newer POWER 8 ?

TIA,
Fabricio

**Comment by xianyi** [comment]
I cannot access the POWER 8 machine. Thus, I am not sure how to use older GotoBLAS code on the newer POWER.  According to #463 , I think it not easy to port old code on the new POWER and AIX.

**Comment by leitao** [comment]
I can provide you access to a POWER8 machine running current OS, as Debian, Ubuntu or Fedora. Is it something you might be interested in?

**Comment by xianyi** [comment]
I am interesting in optimizing OpenBLAS on newer CPUs. I can try it on my spare time.

**Comment by leitao** [comment]
Great. Please ask for the account on a POWER box using the following request:

http://openpower.ic.unicamp.br/minicloud/

**Comment by fabioperez** [comment]
Hi @xianyi, any updates on this?

**Comment by xianyi** [comment]
@fabioperez  Sorry, I am very busy. I didn't try it yet.
