### ISSUE TITLE
error: expected ')' before 'n'

### ISSUE THREAD

**Issue by moakanoni** [xianyi/OpenBLAS#513]
Hi,

Someone else had this issue, and I can't tell if it was addressed.
I am attempting to compile the current master branch (I have also
tried the current development branch) with

HOSTCC = gcc
CC = x86_64-w64-mingw32-gcc
FC = x86_64-w64-mingw32-gfortran
BINARY=64
USE_THREAD = 0
NUM_THREADS = 1
INTERFACE64 = 1

Whether I use a Windows command shell, or msys.bat,
the make process terminates with this error message:

imax.c:148:27: error: expected ')' before 'n'
 CBLAS_INDEX CNAME(blasint n, FLOAT *x, blasint incx){
                           ^
make[1]: *** [cblas_isamax.obj] Error 1

I have make version 3.79.1 and gcc version 4.9.2:

Thread model: win32
gcc version 4.9.2 (x86_64-win32-seh-rev1, Built by MinGW-W64 project)

**Comment by xianyi** [comment]
@moakanoni , could you upload your Config.h and Makefine.conf on gist?

What's CPU?

If you build on Windows, please try `make CC=gcc FC=gfortran INTERFACE64=1 BINARY=64 USE_THREAD=0`.

**Comment by moakanoni** [comment]
Sure, files are at gist.github.com/moakanoni/dd3cd52e2018992f3597

I tried gcc 4.8.1 as well, since I have it installed, but no luck.
The CPU is a Core i5-2520M.

**Comment by moakanoni** [comment]
It may be the msys "make" executable. I have substituted mingw32-make
(version 4.2) and it has got beyond the point where in failed previously.
Still compiling ... will update with outcome.

**Comment by moakanoni** [comment]
Compiled successfully! Problem is msys make.

**Comment by xianyi** [comment]
Great!
