### ISSUE TITLE
The computer shuts down when OMP_NUM_THREADS is more than 2 for testing numpy

### ISSUE THREAD

**Issue by lixiangnlp** [xianyi/OpenBLAS#514]
I install numpy-1.9.2 with OpenBLAS. But the computer is automaticlly robooted using the testing script https://gist.github.com/raw/3842524/df01f7fa9d849bec353d6ab03eae0c1ee68f1538/test_numpy.py when OMP_NUM_THREADS is set as more than 2.
My OS is ubuntu 14.04. And gcc verison is 4.8.2 (Ubuntu 4.8.2-19ubuntu1). 
I use the current branch of OpenBLAS.
The cpu is i7-4790K.
Python 2.7.9

**Comment by martin-frbg** [comment]
Insufficient cooling of the CPU could cause this, as could a weak power supply. Do you get any error messages in the logs immediately before the shutdown ?
Also, what does "the current branch" refer to, github "master" or "develop" of OpenBLAS ?

**Comment by lixiangnlp** [comment]
@martin-frbg I use the master of OpenBLAS. I have no error message.

**Comment by martin-frbg** [comment]
All fixes since the beginning of December are only on develop (though this is more relevant to your comment on issue #492). Still, system shutdown during heavy calculations is usually some kind of hardware problem in my experience.

**Comment by lixiangnlp** [comment]
Sorry, I just use the develop of OpenBLAS.

**Comment by xianyi** [comment]
@lixiangnlp , any updates? Is it still crash?

**Comment by lixiangnlp** [comment]
@xianyi Yes, it also doesn't work. The computer power is 750W.

**Comment by lixiangnlp** [comment]
@xianyi 

lixiang@lixiang-ubuntu:~/library$ OPENBLAS_NUM_THREADS=1 python test_numpy.py
FAST BLAS
version: 1.9.2
maxint: 9223372036854775807

dot: 0.0358132362366 sec

lixiang@lixiang-ubuntu:~/library$ OPENBLAS_NUM_THREADS=2 python test_numpy.py
FAST BLAS
version: 1.9.2
maxint: 9223372036854775807
dot: 0.0213746070862 sec

lixiang@lixiang-ubuntu:~/library$ OPENBLAS_NUM_THREADS=3 python test_numpy.py
FAST BLAS
version: 1.9.2
maxint: 9223372036854775807

dot: 0.0153140068054 sec

lixiang@lixiang-ubuntu:~/library$ OPENBLAS_NUM_THREADS=4 python test_numpy.py
FAST BLAS
version: 1.9.2
maxint: 9223372036854775807

dot: 0.0119540214539 sec
But when the OPENBLAS_NUM_THREADS is more than 4, the computer shuts down without any error messages.
lixiang@lixiang-ubuntu:~/library$ OPENBLAS_NUM_THREADS=5 python test_numpy.py
FAST BLAS
version: 1.9.2
maxint: 9223372036854775807

**Comment by lixiangnlp** [comment]
@xianyi 

lixiang@lixiang-ubuntu:~/library$ OPENBLAS_NUM_THREADS=1 python test_scipy.py
FAST BLAS
version: 1.9.2
maxint: 9223372036854775807

dot: 0.0359404087067 sec
lixiang@lixiang-ubuntu:~/library$ OPENBLAS_NUM_THREADS=2 python test_scipy.py
FAST BLAS
version: 1.9.2
maxint: 9223372036854775807

dot: 0.0214948177338 sec
lixiang@lixiang-ubuntu:~/library$ OPENBLAS_NUM_THREADS=3 python test_scipy.py
FAST BLAS
version: 1.9.2
maxint: 9223372036854775807

dot: 0.015279006958 sec
lixiang@lixiang-ubuntu:~/library$ OPENBLAS_NUM_THREADS=4 python test_scipy.py
FAST BLAS
version: 1.9.2
maxint: 9223372036854775807

dot: 0.0118727684021 sec
lixiang@lixiang-ubuntu:~/library$ OPENBLAS_NUM_THREADS=5 python test_scipy.py
FAST BLAS
version: 1.9.2
maxint: 9223372036854775807

dot: 0.0160964012146 sec

But when the OPENBLAS_NUM_THREADS is more than 5, the computer shuts down without any error messages.

lixiang@lixiang-ubuntu:~/library$ OPENBLAS_NUM_THREADS=6 python test_scipy.py
FAST BLAS
version: 1.9.2
maxint: 9223372036854775807

**Comment by lixiangnlp** [comment]
@xianyi 
An interesting problem is that it works after reboot with the command:

ixiang@lixiang-ubuntu:~/library$ OPENBLAS_NUM_THREADS=6 python test_scipy.py
FAST BLAS
version: 1.9.2
maxint: 9223372036854775807

dot: 0.0154094219208 sec

But I again run it, it doesn't work and shuts down.


lixiang@lixiang-ubuntu:~/library$ OPENBLAS_NUM_THREADS=6 python test_scipy.py
FAST BLAS
version: 1.9.2
maxint: 9223372036854775807

**Comment by xianyi** [comment]
Any updates?

**Comment by lixiangnlp** [comment]
@xianyi The issue still exists now. I find it works for scipy test when the num_threads is set to  1 and 2. But the server shuts down when the number of threads is more than 2, such as 4 and 8. The cpu is i7-4790k. The OS is Ubuntu 14.04.

**Comment by xianyi** [comment]
@lixiangnlp.  Is it laptop or desktop? Could you give me more details? e.g.  memory, vendor.

**Comment by lixiangnlp** [comment]
@xianyi It is a desktop which has 32GB memory (4*8G).

**Comment by zerothi** [comment]
Could you try with other threaded blas implementations?
If this is happening with other implementations it is due to your configuration of the system rather than the blas implementation.
