### ISSUE TITLE
Failed to compile on MacBook Air

### ISSUE THREAD

**Issue by dongli** [xianyi/OpenBLAS#515]
I have tried to install `Armadillo` on one MacBook Air with 1.7 GHz Intel Core i7, which depends on `OpenBLAS`. The compile command is
```
export CFLAGS="-O2" && export CC="/usr/bin/clang" && export CXXFLAGS="-O2" && export CXX="/usr/bin/clang++" &&  make
```
and the errors I got are
```
<instantiation>:18:7: error: invalid operand for instruction
 addq *4, %rsi
      ^
../kernel/x86_64/sgemm_kernel_16x4_haswell.S:2075:2: note: while in macro instantiation
 KERNEL1x6_SUB
 ^
```
The `clang` version is:
```
$ clang --version
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix
```
Any suggestion?

**Comment by xianyi** [comment]
@dongli , could you try OpenBLAS develop branch?

**Comment by dongli** [comment]
@xianyi I tried the develop branch, and it should work. I terminated the compilation since the fan ran crazily on the MacBook Air. Thanks for suggestion!
