### ISSUE TITLE
Does this support GPU?

### ISSUE THREAD

**Issue by marker68** [xianyi/OpenBLAS#516]
I wonder if this library supports GPU like [cuBLAS](https://developer.nvidia.com/cuBLAS)?

**Comment by xianyi** [comment]
@marker68 , OpenBLAS didn't support GPU so far. 

@wernsaar, Werner has optimized some kernels for GPU by OpenCL.  We plan to release GPU optimization codes in the near future.

**Comment by guangwei** [comment]
When you will release GPU like cuda or through OpenCL?

**Comment by xianyi** [comment]
@guangwei , there are some experiment codes at https://github.com/xianyi/clOpenBLAS

**Comment by guangwei** [comment]
@xianyi  thank you for your information

**Comment by Foadsf** [comment]
Any updates on this? It would be awesome to have an OpenCL implementation of OpenBLAS.

**Comment by martin-frbg** [comment]
By the looks of it, the last work on clOpenBLAS happened in April 2015 (and wernsaar its primary developer was last seen on github in January 2017,  even xianyi himself appears to be absorbed in his own business lately). Have you looked at clBLAS and/or clBLAST ?

**Comment by Foadsf** [comment]
@martin-frbg Sad to hear that the main developers have abandoned their work. 

I'm actually aware of several OpenCL implementations of BLAS API:  [CLBlast](https://github.com/CNugteren/CLBlast), [clBLAS](https://github.com/clMathLibraries/clBLAS), [clMAGMA](http://icl.cs.utk.edu/magma/software/view.html?id=190), [ArrayFire](https://arrayfire.com/) and [ViennaCL](http://viennacl.sourceforge.net/), to mention a few. Although they are great, OpenBLAS seems to be the most prominent BLAS implementation of the API, used by a great majority of other projects. If we should have true cross platform and vendor natural GPGPU accelerated BLAS, OpenBLAS is the best one to invest in. 

P.S. Unfortunately CUDA is eating away the whole GPGPU world and there will be a monopoly if the community keeps ignoring the issue.

**Comment by martin-frbg** [comment]
You can certainly fork and continue the project (I do not have collaborator status there, so would not be able to merge PRs in the original clOpenBLAS repository). I think it is possible that the block algorithms originally introduced by K.Goto to make the most use of (x86) CPU caches are less well suited for GPU hardware. (This seems to be a major performance obstacle in the RISC V port of OpenBLAS at least, I know very little about OpenCL coding)

**Comment by dmikushin** [comment]
Nowadays, most of the GPUs have tensor cores that do a multiply of 16x16 matrices at once. So, GPUs work at tile granularity, not at the element granularity as it was in the classical GPGPU. From what I see, OpenBLAS uses tiling/dispatching strategy and calls tiled multiplies as elemental operations of its scheduler. Therefore it feels that the GPU tensor cores could serve as drop-in implementation of tiled multiplies within the existing OpenBLAS scheduler. Of course, threading has to change, but overall the OpenBLAS design and GPU tensor cores are potentially highly compatible.

**Comment by martin-frbg** [comment]
potentially, yes. not sure offhand if "the threading has to change" wouldn't be a major obstacle, especially if one wants new GPU kernels and the present CPU code to coexist. I feel I dont know enough about current GPU offloading techniques to assess if it would make (more) sense now, or if one would be fighting the existing codebase most of the time.
