### ISSUE TITLE
ONLY_CBLAS flag still tries to compile for Fortran

### ISSUE THREAD

**Issue by vijaykartik** [xianyi/OpenBLAS#520]
I am trying to compile OpenBLAS on Mac OS X Yosemite with only CBLAS. On running "make ONLY_CBLAS=1" (as per Issue #279 ), I get the following error:

f77 -O2 -m128bit-long-double -Wall -m64 -fPIC -all_load -headerpad_max_install_names -install_name /Users/username/openblas/exports/../libopenblas_sandybridgep-r0.2.13.dylib -dynamiclib -o ../libopenblas_sandybridgep-r0.2.13.dylib ../libopenblas_sandybridgep-r0.2.13.a -Wl,-exported_symbols_list,osx.def
make[1]: f77: No such file or directory
make[1]: *** [libopenblas_sandybridgep-r0.2.13.dylib] Error 1
make: *** [shared] Error 2

I am running clang, and don't have an f77 binary. Here's the output for gcc -v:

$gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix

I'm happy to provide any further information that you might need.

**Comment by xianyi** [comment]
Thank you for the report. Please try the develop branch. I just uploaded the fix.

**Comment by vijaykartik** [comment]
Thanks for the prompt fix, it works now!
