### ISSUE TITLE
sdot inaccuracy

### ISSUE THREAD

**Issue by cmr** [xianyi/OpenBLAS#522]
Via fuzzing, I've found a potential problem, and this behavior differs from the reference BLAS. Here is a testcase:

```c
#include <cblas.h>
#include <stdio.h>
#include <math.h>

static float x[16] = {0, 0, 0, 0, 0, 0, 0, 0, -28, 0, 41, -15, 0, 20, -55.744289, -76.930283};
static float y[16] = {0, 0, 0, 0, 0, 0, 0, 0, -54.654705, 0, 23.670898, -4.533447, 0, 79.964569, -65.6026, -4};

int main() {
    float expected = 0;
    for (int i = 0; i < 16; i++) {
        expected += x[i] * y[i];
    }

    float actual = cblas_sdot(16, x, 1, y, 1);
    printf("Expected %f, got %f, ==? %s, diff = %f\n", expected, actual, expected == actual ? "true" : "false", fabs(expected - actual));
}
```

It seems that the number of leading zeros is important. If you have any more or less than 8 leading zeros in the array, it will give the expected answer. The output here: `Expected 8132.823242, got 8132.822754, ==? false, diff = 0.000488`

**Comment by jeromerobert** [comment]
With cdefdb2 (develop - 6 commits) and  `MAX_STACK_ALLOC=2048`  `DYNAMIC_ARCH=1` `NO_AFFINITY=1` on Sandybridge/AVX I get:

    $ gcc -std=c99 -pthread bug.c /home/robert/openblas-current/lib/libopenblas.a
    $ ./a.out 
    Expected 8132.823242, got 8132.823242, ==? true, diff = 0.000000

May be you should tell more about the version you are using, the way you built it, and the hardware you are using.

**Comment by martin-frbg** [comment]
I can reproduce this on Nehalem but not Haswell, so probably sse-related.

**Comment by cmr** [comment]
I built with just `make` on `cdefdb2` as well. I discovered the bug in a VM, which exposes the Intel model "Westmere E56xx/L56xx/X56xx (Nehalem-C)" with the following features:

```
fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes avx f16c rdrand hypervisor lahf_lm abm fsgsbase bmi1 avx2 smep bmi2 erms invpcid
```

I *cannot* replicate it on the host, which is Haswell with the following features:

```
fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb pln pts dtherm tpr_shadow vnmi flexpriority ept vpid stronguderef fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt
```

**Comment by martin-frbg** [comment]
Actual Nehalem cpu does not have AVX, and neither does Westmere as far as I know. So if your VM sports a Westmere cpuid your VM build will be sse-only even if your virtualization software somewhat erroneously exposes the avx capability of the host cpu.

**Comment by martin-frbg** [comment]
Issue trivially tracked to commit 5d97b07 of August 22, which happens to be "added optimized sdot kernel for Nehalem" by wernsaar.

**Comment by wernsaar** [comment]
Hi,

I checked the sdot function on Nehalem and Bulldozer.
There are rounding differences at  the 8th position. But
with single precision, you can only trust 7 positions.
I you compile your test code with the flags -Ofast
or -O3 -ffast-math, you will not see a difference.

Werner

**Comment by xianyi** [comment]
I didn't read Werner's sdot kernel. I wonder the difference is relate to the different sequence of accessing the numbers.

**Comment by brada4** [comment]
One cannot expect BLAS to do dot addition in order
Integer result is 8132.8230685514
So both your libm/FPU and and OpenBLAS is similar amount off (and all within expected 23-bit precision of 32bit floating point, i.e log(2**23) ~ 6.9 decimal digits.
Similar way 14th decimal digit with Double differs from pure integer result.
