### ISSUE TITLE
'amax.S' causing problems in building OpenBLAS-0.2.13 for ARM

### ISSUE THREAD

**Issue by ShehabElsayed** [xianyi/OpenBLAS#523]
Hi everyone,

I have been trying to build OpenBLAS-0.2.13 for ARM using this command "make BINARY=64 TARGET=ARMV7 USE_THREAD=1", but the building stops with this error:

make[1]: *** No rule to make target `../kernel/arm64/amax.S', needed by `samax_k.o'.  Stop.

Any ideas how to fix this problem ??

Thank you very much in advance.

**Comment by xianyi** [comment]
The ARMV7 is 32-bit. Please try `make BINARY=32 TARGET=ARMV7 USE_THREAD=1`

**Comment by ShehabElsayed** [comment]
Thank you very much for your reply. So what if I needed t build 64-bit versions of OpenBLAS for ARM. ARMV8 is not mentioned in the TargetList. Is it supported? If yes, which TARGET would be the correct one to choose?

**Comment by xianyi** [comment]
We support ARMV8 by APM's patch. However, I didn't test it since lacking the ARMV8 hardware.

`make TARGET=ARMV8 BINARY=64`

**Comment by ShehabElsayed** [comment]
Thank you very much for the prompt reply. I will give it a try

**Comment by wernsaar** [comment]
Hi,

make  TARGET=ARMV7 USE_THREAD=1

ARMV7 is a 32-bit processor

Werner

**Comment by ShehabElsayed** [comment]
I am afraid the problem still exists even when I use "make TARGET=ARMV7 BINARY=32 USE_THREAD=1" for building

**Comment by xianyi** [comment]
@ShehabElsayed what's the output?

**Comment by ShehabElsayed** [comment]
The build stops with the same error as before:
"make[1]: *** No rule to make target `../kernel/arm64/amax.S', needed by `samax_k.o'.  Stop."

**Comment by xianyi** [comment]
Please try the following.
1) `make clean`
2) `make TARGET=ARMV7 USE_THREAD=1`

**Comment by ShehabElsayed** [comment]
This is what I did, every time I "make clean" before changing the make options. I just added the "BINARY=32" option to make sure that it is building the 32 version not the 64 one. 

I am not sure if this piece of information makes any difference or not but I am trying to do the build on an image of ubuntu-trusty 64-bit for ARM mounted through the qemu emulator.

**Comment by xianyi** [comment]
@ShehabElsayed , please don't add "BINARY=32".

**Comment by ShehabElsayed** [comment]
Ok, I am doing so right now and will update the thread when it is done. Thank you very much for your help.

**Comment by ShehabElsayed** [comment]
It still gives the exact same error "make[1]: *** No rule to make target `../kernel/arm64/amax.S', needed by `samax_k.o'.  Stop."

**Comment by xianyi** [comment]
Please provide `config.h` and `Makefile.conf`

**Comment by ShehabElsayed** [comment]
This is config.h:

#define OS_LINUX        1
#define ARCH_ARM64      1
#define C_GCC   1
#define __64BIT__       1
#define PTHREAD_CREATE_FUNC     pthread_create
#define BUNDERSCORE     _
#define NEEDBUNDERSCORE 1
#define ARMV7
#define L1_DATA_SIZE 65536
#define L1_DATA_LINESIZE 32
#define L2_SIZE 512488
#define L2_LINESIZE 32
#define DTB_DEFAULT_ENTRIES 64
#define DTB_SIZE 4096
#define L2_ASSOCIATIVE 4
#define HAVE_VFPV3
#define HAVE_VFP
#define CORE_ARMV7

#define CHAR_CORENAME "ARMV7"
#define SLOCAL_BUFFER_SIZE      15360
#define DLOCAL_BUFFER_SIZE      7680
#define CLOCAL_BUFFER_SIZE      7680
#define ZLOCAL_BUFFER_SIZE      7680
#define GEMM_MULTITHREAD_THRESHOLD      4
---------------------------------------------------------------------------------------------------------------

and this is Makefile.conf

OSNAME=Linux
ARCH=arm64
C_COMPILER=GCC
BINARY32=
BINARY64=1
CROSS=1
CEXTRALIB=-L/usr/lib/gcc/aarch64-linux-gnu/4.8 -L/usr/lib/gcc/aarch64-linux-gnu/4.8/../../../aarch64-linux-gnu -L/usr/lib/gcc/aarch64-linux-gnu/4.8/../../../../lib -L/lib/aarch64-linux-gnu -L/lib/../lib -L/usr/lib/aarch64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/aarch64-linux-gnu/4.8/../../..  -lc
F_COMPILER=GFORTRAN
FC=gfortran
BU=_
CORE=ARMV7
LIBCORE=armv7
NUM_CORES=2
MAKE += -j 2
SGEMM_UNROLL_M=4
SGEMM_UNROLL_N=4
DGEMM_UNROLL_M=4
DGEMM_UNROLL_N=4
QGEMM_UNROLL_M=2
QGEMM_UNROLL_N=2
CGEMM_UNROLL_M=2
CGEMM_UNROLL_N=2
ZGEMM_UNROLL_M=2
ZGEMM_UNROLL_N=2
XGEMM_UNROLL_M=2
XGEMM_UNROLL_N=2
CGEMM3M_UNROLL_M=4
CGEMM3M_UNROLL_N=4
ZGEMM3M_UNROLL_M=4
ZGEMM3M_UNROLL_N=4
XGEMM3M_UNROLL_M=2
XGEMM3M_UNROLL_N=2

**Comment by xianyi** [comment]
Are you on real ARM machine or simulator? It looks like AARCH64 (ARM 64-bit).

**Comment by ShehabElsayed** [comment]
No, it is not a real ARM machine, an emulator/simulator called qemu

**Comment by xianyi** [comment]
I think your gcc toolchain is AARCH64.  You can check the predefined macros from this link.
http://www.commandlinefu.com/commands/view/3918/display-gcc-predefined-macros

Please use `make TARGET=ARMV8`.

**Comment by ShehabElsayed** [comment]
I tried "make TARGET=ARMV8" before and it still gave the same error message. Is the APM patch you mentioned before for ARMV8 already included in OpenBLAS-0.2.13 or do I have to apply it?

**Comment by xianyi** [comment]
@ShehabElsayed , did you try develop branch?

**Comment by ShehabElsayed** [comment]
I do not think I tried the latest one. I will check and if I hadn't, I will try it.

**Comment by ShehabElsayed** [comment]
I got the develop branch and tried "make TARGET=ARMV8" but still the same error exists

**Comment by xianyi** [comment]
I update the develop. I think it can fix this issue. Please try it.

**Comment by ShehabElsayed** [comment]
This seems to work. Thank you very much.

**Comment by zhangyifu2016** [comment]
Hi, @xianyi    I have the same problem. I used "make TARGET=ARMV8 BINARY=64 HOSTCC=gcc CC=/home/linux/gcc-linaro-arm-linux-gnueabihf-4.9-2014.07_linux/bin/arm-linux-gnueabihf-gcc NOFORTRAN=1 USE_THREAD=1".  but the building stops with this error:

make[1]: *** No rule to make target ../kernel/arm64/amax.S', needed bysamax_k.o'. Stop.

I find that libopenblas_armv8p-r0.2.19.a has been generated, but .so not. 

How to setup it?

Thank you in advance.
