### ISSUE TITLE
ARMv8-a SSWAP/DSWAP/CAXPY/ZAXPY/ZSWAP test failed.

### ISSUE THREAD

**Issue by huazhuaz** [xianyi/OpenBLAS#526]
Log msg:

OPENBLAS_NUM_THREADS=2 ./sblat1
 Test of subprogram number  6            SSWAP 
                                       FAIL

 CASE  N INCX INCY MODE  I                             COMP(I)                             TRUE(I)  DIFFERENCE     SIZE(I)

```
6  2    1    1 9999  2                     -0.89999998E+00                     -0.89999998E+00  0.1000E+01  0.0000E+00
```

OPENBLAS_NUM_THREADS=2 ./dblat1
 Test of subprogram number  6            DSWAP 
                                       FAIL

 CASE  N INCX INCY MODE  I                             COMP(I)                             TRUE(I)  DIFFERENCE     SIZE(I)

```
6  2    1    1 9999  2                     -0.90000000D+00                     -0.90000000D+00  0.1000D+01  0.0000D+00
```

OPENBLAS_NUM_THREADS=2 ./cblat1
 Test of subprogram number  3            CAXPY 
                                       FAIL

 CASE  N INCX INCY MODE  I                             COMP(I)                             TRUE(I)  DIFFERENCE     SIZE(I)

```
3  2    1    1 9999  3                     -0.89999998E+00                     -0.15500000E+01  0.6500E+00  0.1540E+01
```

OPENBLAS_NUM_THREADS=2 ./zblat1
 Test of subprogram number  3            ZAXPY 
                                       FAIL

 CASE  N INCX INCY MODE  I                             COMP(I)                             TRUE(I)  DIFFERENCE     SIZE(I)

```
3  2    1    1 9999  3                     -0.90000000D+00                     -0.15500000D+01  0.6500D+00  0.1540D+01
3  4    2   -2 9999  1                      0.60000000D+00                      0.78000000D+00 -0.1800D+00  0.1540D+01
3  4    2   -2 9999  2                     -0.60000000D+00                      0.60000000D-01 -0.6600D+00  0.1540D+01
3  4   -1   -2 9999  1                      0.60000000D+00                      0.32000000D+00  0.2800D+00  0.1540D+01
3  4   -1   -2 9999  2                     -0.60000000D+00                     -0.14100000D+01  0.8100D+00  0.1540D+01
```

 Test of subprogram number  5            ZSWAP 
                                       FAIL

 CASE  N INCX INCY MODE  I                             COMP(I)                             TRUE(I)  DIFFERENCE     SIZE(I)

```
5  2    1    1 9999  3                     -0.40000000D+00                     -0.90000000D+00  0.5000D+00  0.0000D+00
5  2    1    1 9999  4                     -0.70000000D+00                      0.50000000D+00 -0.1200D+01  0.0000D+00
5  4    2   -2 9999  9                     -0.90000000D+00                      0.70000000D+00 -0.1600D+01  0.0000D+00
5  4    2   -2 9999 10                     -0.40000000D+00                     -0.60000000D+00  0.2000D+00  0.0000D+00
5  4    2   -2 9999 13                     -0.60000000D+00                      0.60000000D+00 -0.1200D+01  0.0000D+00
5  4    2   -2 9999 14                      0.60000000D+00                     -0.60000000D+00  0.1200D+01  0.0000D+00
```

**Comment by xianyi** [comment]
@huazhuaz , thank you for the report.
I cannot access ARMv8 machine now. Thus, I afraid I cannot debug this issue.

**Comment by huazhuaz** [comment]
Based on the above and the following msgse, it mean that these issues are caused by multi-thread?

OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 ./sblat1
 Real BLAS Test Program Results


 Test of subprogram number  1             SDOT 
                                    ----- PASS -----

 Test of subprogram number  2            SAXPY 
                                    ----- PASS -----

 Test of subprogram number  3            SROTG 
                                    ----- PASS -----

 Test of subprogram number  4             SROT 
                                    ----- PASS -----

 Test of subprogram number  5            SCOPY 
                                    ----- PASS -----

 Test of subprogram number  6            SSWAP 
                                    ----- PASS -----

 Test of subprogram number  7            SNRM2 
                                    ----- PASS -----

 Test of subprogram number  8            SASUM 
                                    ----- PASS -----

 Test of subprogram number  9            SSCAL 
                                    ----- PASS -----

 Test of subprogram number 10            ISAMAX
                                    ----- PASS -----
OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 ./dblat1
 Real BLAS Test Program Results


 Test of subprogram number  1             DDOT 
                                    ----- PASS -----

 Test of subprogram number  2            DAXPY 
                                    ----- PASS -----

 Test of subprogram number  3            DROTG 
                                    ----- PASS -----

 Test of subprogram number  4             DROT 
                                    ----- PASS -----

 Test of subprogram number  5            DCOPY 
                                    ----- PASS -----

 Test of subprogram number  6            DSWAP 
                                    ----- PASS -----

 Test of subprogram number  7            DNRM2 
                                    ----- PASS -----

 Test of subprogram number  8            DASUM 
                                    ----- PASS -----

 Test of subprogram number  9            DSCAL 
                                    ----- PASS -----

 Test of subprogram number 10            IDAMAX
                                    ----- PASS -----
OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 ./cblat1
 Complex BLAS Test Program Results


 Test of subprogram number  1            CDOTC 
                                    ----- PASS -----

 Test of subprogram number  2            CDOTU 
                                    ----- PASS -----

 Test of subprogram number  3            CAXPY 
                                    ----- PASS -----

 Test of subprogram number  4            CCOPY 
                                    ----- PASS -----

 Test of subprogram number  5            CSWAP 
                                    ----- PASS -----

 Test of subprogram number  6            SCNRM2
                                    ----- PASS -----

 Test of subprogram number  7            SCASUM
                                    ----- PASS -----

 Test of subprogram number  8            CSCAL 
                                    ----- PASS -----

 Test of subprogram number  9            CSSCAL
                                    ----- PASS -----

 Test of subprogram number 10            ICAMAX
                                    ----- PASS -----
OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 ./zblat1
 Complex BLAS Test Program Results


 Test of subprogram number  1            ZDOTC 
                                    ----- PASS -----

 Test of subprogram number  2            ZDOTU 
                                    ----- PASS -----

 Test of subprogram number  3            ZAXPY 
                                    ----- PASS -----

 Test of subprogram number  4            ZCOPY 
                                    ----- PASS -----

 Test of subprogram number  5            ZSWAP 
                                    ----- PASS -----

 Test of subprogram number  6            DZNRM2
                                    ----- PASS -----

 Test of subprogram number  7            DZASUM
                                    ----- PASS -----

 Test of subprogram number  8            ZSCAL 
                                    ----- PASS -----

 Test of subprogram number  9            ZDSCAL
                                    ----- PASS -----

 Test of subprogram number 10            IZAMAX
                                    ----- PASS -----

**Comment by xianyi** [comment]
@huazhuaz ，I am not sure. How could you compile the library? Could you try `make USE_OPENMP=1`?

**Comment by martin-frbg** [comment]
Ancient issue, not reproducible with current OpenBLAS on current ARMV8 hardware.
