### ISSUE TITLE
OpenBLAS unable to detect architecture correctly, failing on new Macbook Pro

### ISSUE THREAD

**Issue by sbromberger** [xianyi/OpenBLAS#529]
During a Julia build:

```
Makefile:131: *** OpenBLAS: Detecting CPU failed. Please set TARGET explicitly, e.g. make TARGET=your_cpu_target. Please read README for the detail..  Stop.
*** Clean the OpenBLAS build with 'make -C deps clean-openblas'. Rebuild with 'make OPENBLAS_USE_THREAD=0 if OpenBLAS had trouble linking libpthread.so, and with 'make OPENBLAS_TARGET_ARCH=NEHALEM' if there were errors building SandyBridge support. Both these options can also be used simultaneously. ***
make[1]: *** [openblas-v0.2.13/libopenblas.dylib] Error 1
```

Explicitly setting the target architecture to HASWELL (even though it's broadwell) solves the issue. What information can I provide that will assist in a fix?

This is from Julia's `versioninfo()`:
```
Platform Info:
  System: Darwin (x86_64-apple-darwin14.1.1)
  CPU: Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT NO_AFFINITY HASWELL)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by xianyi** [comment]
Thank you for the report. Please try the develop branch. I think it can detect broadwell CPU.

**Comment by sbromberger** [comment]
Not sure how to use the develop branch within a Julia build....

**Comment by xianyi** [comment]
@ViralBShah , could you give us any suggestions?

**Comment by tkelman** [comment]
Try setting `override OPENBLAS_VER = develop` in `Make.user`.

P.S. congrats @xianyi on your position at UT, I see you're making some good contributions to BLIS lately. Very cool.

**Comment by ViralBShah** [comment]
Yes, congrats!

**Comment by xianyi** [comment]
@tkelman , @ViralBShah ,  Thank you. Actually, I am a visiting scholar at UT.

**Comment by simonbyrne** [comment]
For anyone else coming across this issue: you now need
```
override OPENBLAS_BRANCH=develop
```
in your `Make.user` file.

**Comment by sbromberger** [comment]
FYI, this is no longer working (Make.user):
```
override OPENBLAS_BRANCH=develop
override OPENBLAS_TARGET_ARCH=Broadwell
```

Failing with 
```fatal: reference is not a tree: d0c51c4de91b2356b770f92862c6b0e1d54953cd
make[1]: *** [openblas/Makefile] Error 128
```

**Comment by sbromberger** [comment]
Appears to work when I do an explicit `git fetch --unshallow` in `deps/openblas` (thanks, @tkelman !)
