### ISSUE TITLE
Parallelized ZDOT?

### ISSUE THREAD

**Issue by hiccup7** [xianyi/OpenBLAS#537]
In testing ZDOTU() AND ZDOTC() functions on long vectors in Julia, I noticed that execution is single-threaded on my Haswell Core-i7 in 64-bit Windows.  I regularly use these functions on GB-size vectors. Could these functions could be parallelized or optimized for Haswell in some other way?

**Comment by wernsaar** [comment]
Now there are optimized cdot- and zdot functions in the repository. The dot functions are memory bound, multi-threading cannot really increase the performance.

**Comment by xianyi** [comment]
@wernsaar , is it possible to get the benefit on very large problem size? e.g. larger than L3 cache.

**Comment by wernsaar** [comment]
Hi,

the memory read performance is the limiting factor, also with 
multi-threading.
On big numa machines, multi-threading may be usefull, but I think, that 
you have
to split the vectors ( create or compute ) on the numa nodes and then 
call the blas
function.

Best regards
Werner

**Comment by hiccup7** [comment]
@wernsaar , thanks for optimizing the cdot- and zdot- functions in the repository.  They will save me a lot of execution time.
