### ISSUE TITLE
how to choose TARGET manually at runtime when compiled with DYNAMIC_ARCH

### ISSUE THREAD

**Issue by carlkl** [xianyi/OpenBLAS#545]
I didn't found a way to manually choose the computing kernel via enironment variable or function instead of relying on the automatism. Is this possible?

**Comment by jeromerobert** [comment]
The environment variable which control the kernel selection is OPENBLAS_CORETYPE (see driver/others/dynamic.c).

**Comment by carlkl** [comment]
I overviewed that, thanks. And the function openblas_get_corename() returns the used target.
Can this be emphasized in the FAQ, please?

**Comment by xianyi** [comment]
@carlkl , I added it in FAQ.
https://github.com/xianyi/OpenBLAS/wiki/Faq#choose_target_dynamic

**Comment by carlkl** [comment]
@xianyi Great!
