### ISSUE TITLE
scipy error - linalg/_fblas.so: undefined symbol: PyArray_API

### ISSUE THREAD

**Issue by coral1801** [xianyi/OpenBLAS#551]
I built openblas(v0.2.14) from source and installed locally, using the instructions from here: http://osdf.github.io/blog/numpyscipy-with-openblas-for-ubuntu-1204-second-try.html. After this I installed numpy and scipy. numpy seems to be fine (tested with testnumpy.py) but scipy gave the following error on import:
   site-packages/scipy/linalg/_fblas.so: undefined symbol: PyArray_API

According to this, this could be due to incomplete LAPACK or BLAS sources:http://wiki.scipy.org/FAQ

Any idea what I am doing wrong? 

I am working on RHat and do not have sudo privileges. 

Thank you.

**Comment by martin-frbg** [comment]
"Incomplete LAPACK or BLAS sources" would apply if it was a LAPACK or BLAS function that is reported as undefined (such as the srotmg and sgesdd examples used in the scipy FAQ you linked to).
What you seem to be missing is a numpy symbol, so most probably not an OpenBLAS but a numpy build issue. The closest topic I could find was https://github.com/numpy/numpy/issues/2521 (though the underlying issue there appears to have been fixed a year ago, you may be using older packages from your distribution?)

**Comment by coral1801** [comment]
Thanks for the reply martin. I am using the latest versions of numpy and scipy but both are installed locally using the --prefix option. My PYTHONPATH is point to the local version of numpy. My LD_LIBRARY_PATH is pointing to openblas. BLAS and LAPACK are set to libopenblas.a. Is it possible that the scipy build pulled another older previously installed version of numpy, even with these settings?

**Comment by coral1801** [comment]
A clean rebuild fixed the issue. Posted details here: https://github.com/scipy/scipy/issues/4767
