### ISSUE TITLE
OpenBLAS unable to detect architecture correctly, failing on Intel Edison

### ISSUE THREAD

**Issue by amellnik** [xianyi/OpenBLAS#555]
I'm stuck on this while trying to build Julia:

    Makefile:131: *** OpenBLAS: Detecting CPU failed. Please set TARGET explicitly, e.g. make TARGET=your_cpu_target. Please read README for the detail..  Stop.
    *** Clean the OpenBLAS build with 'make -C deps clean-openblas'. Rebuild with 'make OPENBLAS_USE_THREAD=0 if OpenBLAS had trouble linking libpthread.so, and with 'make OPENBLAS_TARGET_ARCH=NEHALEM' if there were errors building SandyBridge support. Both these options can also be used simultaneously. ***

Trying to feed the target architecture with OPENBLAS_TARGET_ARCH=SILVERMONT doesn't seem to do anything (is this parameter still in use?)  Any ideas?

**Comment by amellnik** [comment]
Whoops, just saw the list of acceptable targets and seems to be working so far with ATOM.

**Comment by xianyi** [comment]
I think you can try `OPENBLAS_TARGET_ARCH=NEHALEM`

**Comment by amellnik** [comment]
Just to follow up, it did build fine using ATOM and Julia was able to build as a result!
