### ISSUE TITLE
compilation failure of xccblat3 test when GEMM3M not available

### ISSUE THREAD

**Issue by sebastien-villemot** [xianyi/OpenBLAS#559]
On those arches where GEMM3M is not enabled (ARM, ARM64, sparc…), the testsuite fails to compile (when running `make -C ctest`). More precisely, under `ctest/`, the `xccblat3` test cannot be compiled because it hardcodes calls to the `cblas_cgemm3m` function (among others).

I guess the solution is to make some parts of the tests conditionally compiled, depending on the presence or not of GEMM3M.

**Comment by wernsaar** [comment]
fixed the gemm3m ctest bug
