### ISSUE TITLE
Segmentation fault error when running dlinpack.goto benchmark on armv6

### ISSUE THREAD

**Issue by carma03** [xianyi/OpenBLAS#573]
Hi, 
I'm trying to use <a href="https://github.com/xianyi/OpenBLAS" target="_blank">OpenBLAS</a> on <a href="https://www.raspberrypi.org/documentation/hardware/raspberrypi/models/README.md#modelb" target="_blank">Raspberry Pi model B</a> with armv6 processor and Raspbian--Debian OS--. I downloaded (without make and install OpenBlas)  <a href="http://sourceforge.net/projects/openblas/files/v0.2.8-arm/openblas-v0.2.8-armv6-rc2.tar.gz/download" target="_blank">openblas-v0.2.8-armv6-rc2.tar.gz</a> and <a href="http://sourceforge.net/projects/openblas/files/v0.2.9-rc2-arm/openblas-0.2.9-rc2-2-armv6.tar.gz/download" target="_blank">openblas-0.2.9-rc2-2-armv6.tar.gz</a> compiled files for armv6 processor. Next I followed the steps in "INSTALLATION+USAGE.txt" for benchmark "./dlinpack.goto" with "400 4000 400" parameters and I get the error: "Segmentation fault". If I'm doing something wrong please help me.
Thanks...

**Comment by wernsaar** [comment]
See Ref#574
