### ISSUE TITLE
Error when Normal compile on RaspberryPi model B armv6 processor

### ISSUE THREAD

**Issue by carma03** [xianyi/OpenBLAS#574]
Hi,
I'm trying to Install from Source <a href="https://github.com/xianyi/OpenBLAS" target="_blank">OpenBLAS</a> on <a href="https://www.raspberrypi.org/documentation/hardware/raspberrypi/models/README.md#modelb" target="_blank">Raspberry Pi model B</a>(with armv6 processor and Raspbian--Debian OS--) and I get the next errors in both case when execute the commands: "make TARGET=ARMV6" or "make TARGET=ARMV6 FC=gfortran":
<pre><code>
make[1]: Leaving directory '/home/pi/OpenBLAS/driver/level3'
make[1]: Entering directory '/home/pi/OpenBLAS/driver/others'
gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -DF_INTERFACE_GFORT -fPIC -DNO_WARMUP -DMAX_CPU_NUMBER=1 -marm -mfpu=vfp -mfloat-abi=hard  -march=armv6 -DASMNAME=memory -DASMFNAME=memory_ -DNAME=memory_ -DCNAME=memory -DCHAR_NAME=\"memory_\" -DCHAR_CNAME=\"memory\" -DNO_AFFINITY -I../.. -c memory.c -o memory.o
memory.c:899:13: warning: ‘gotoblas_memory_init’ declared ‘static’ but never defined [-Wunused-function]
 static void gotoblas_memory_init(void);
             ^
/tmp/cctFODpd.s: Assembler messages:
/tmp/cctFODpd.s:241: Error: selected processor does not support ARM mode `dmb ish'
/tmp/cctFODpd.s:291: Error: selected processor does not support ARM mode `dmb ish'
/tmp/cctFODpd.s:302: Error: selected processor does not support ARM mode `dmb ish'
/tmp/cctFODpd.s:488: Error: selected processor does not support ARM mode `dmb ish'
Makefile:98: recipe for target 'memory.o' failed
make[1]: *** [memory.o] Error 1
make[1]: Leaving directory '/home/pi/OpenBLAS/driver/others'
Makefile:143: recipe for target 'libs' failed
make: *** [libs] Error 1

</code></pre>

**Comment by wernsaar** [comment]
Hi,
I fixed the memory barrier bug for armv5 and armv6, which means, that these platforms don't have
a barrier and are not really thread-safe.

You can download binaries from http://sourceforge.net/projects/openblas/files/v0.2.14/OpenBLAS-v0.2.14-armv6.tar.gz.

Regards
Werner

**Comment by carma03** [comment]
Thank you very much <a href="https://github.com/wernsaar">wernsaar</a>. Worked perfect native and with Cross Compile too.
