### ISSUE TITLE
Why looking for g77 in the first place?

### ISSUE THREAD

**Issue by IvanUkhov** [xianyi/OpenBLAS#575]
OpenBLAS [does not support](https://github.com/xianyi/OpenBLAS/wiki/Installation-Guide) `g77` on Linux. I am wondering why it is then the [first compiler](https://github.com/xianyi/OpenBLAS/blob/develop/f_check#L28) to look for when no Fortran compiler is specified explicitly. In my case, I have both `g77` and `gfortran` installed, and OpenBLAS picks up the former even though it fails to compile using this compiler. Thank you.

Regards,
Ivan

**Comment by xianyi** [comment]
@IvanUkhov  thank you for your patch. I just delete g77 from the list.

**Comment by IvanUkhov** [comment]
@xianyi, that is even better! Thanks a lot!
