### ISSUE TITLE
TEST failure in complex BLAST tests

### ISSUE THREAD

**Issue by kotoroshinoto** [xianyi/OpenBLAS#579]
Complex BLAS Test Program Results

 Test of subprogram number  1            CDOTC 

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7F96E9653B87
#1  0x7F96E9652D80
#2  0x39896328FF
#3  0x408AAC in cdotc_k

Makefile:7: recipe for target 'level1' failed

the Makefile.conf file contains lines like this:

OSNAME=Linux
ARCH=x86_64
C_COMPILER=GCC
BINARY32=
BINARY64=1
CORE=BULLDOZER
LIBCORE=bulldozer
NUM_CORES=4

system contains a 4 core AMD Opteron(TM) Processor 6274

what am I missing?

**Comment by martin-frbg** [comment]
Which version of OpenBLAS is this ? Both the *dot* functions and the Bulldozer-specific code received updates after 0.2.14 was released, so it would probably be best to try a snapshot of the current "develop" source branch. 
Also, is this a virtualized system by any chance ? I am not familiar with the numbering scheme, and all I can find about the model 6274 seems to indicate that it is a 16-core cpu (or do you actually mean 4x CPU workstation ?)

**Comment by kotoroshinoto** [comment]
they might be fiddling with things, its a cluster login server, so they might have sharded the login sessions virtually somehow, or limited cpu core access. I couldn't tell you, as in the past I have seen all 16 cores, this may be a recent change. Its probably easier to reset a login vm than it is to reboot the entire server if someone foolishly causes a crash.

I'm not an admin on the system, i'm merely an end user, which is why I have to build all this instead of installing it with a package manager.

here is the content of /proc/cpuinfo:
http://pastebin.com/FsEyGKs2

uname -a says this: Linux login-0-0.local 2.6.32-220.el6.x86_64 #1 SMP Tue Dec 6 19:48:22 GMT 2011 x86_64 GNU/Linux

**Comment by kotoroshinoto** [comment]
I would think it should be using core=opteron instead of bulldozer, given the cpu IS an operton. No idea why the autodetection wants to use bulldozer specs

**Comment by kotoroshinoto** [comment]
oh and I was building the release file, not current git development branch

**Comment by martin-frbg** [comment]
Could be that the autodetection is confused by what the vm tells it - which is why I was asking if it is a vm.
(Not really sure if this is an issue, as the server opterons are probably derived from the bulldozer architecture - I would have to study the code to see where the differences lie). You could try building with
"make TARGET=OPTERON" to see if that helps

**Comment by kotoroshinoto** [comment]
I did try that earlier, but with that flag it does not appear to recognize tests as a valid make target.

**Comment by martin-frbg** [comment]
Closing this very old issue as it appears to be no longer reproducible (at least on Ryzen with Bulldozer or Opteron builds)
