### ISSUE TITLE
DYNAMIC_ARCH on arm

### ISSUE THREAD

**Issue by ViralBShah** [xianyi/OpenBLAS#582]
If DYNAMIC_ARCH is enabled on `arm`, openblas seems to try and build AVX kernels and such, and the build fails.

**Comment by xianyi** [comment]
@ViralBShah , we only support DYNAMIC_ARCH on x86 and x86_64. If you enable DYNAMIC_ARCH on other architecture, you will build failed.

**Comment by ViralBShah** [comment]
Ok - that is exactly what happened. I guess you could error out much earlier with a message? Not a big deal though - feel free to close.

**Comment by ViralBShah** [comment]
What would be the right way to build a generic openblas for ARM?

**Comment by xianyi** [comment]
I suggest `make TARGET=ARMV7`

**Comment by ViralBShah** [comment]
Will that work on Raspberry Pi? That is the most common platform people are building julia on arm on.

**Comment by wernsaar** [comment]
Hi,

I think, that the TARGET for Raspberry Pi should be ARMV6 ( no vfpv3 support).
Test it, by simply typing make in the OpenBLAS directory.
OpenBLAS tries to detect the cpu type at build time using values from /proc/cpuinfo

This has nothing to do with dynamic_arch. Dynamic_arch tries to find
the cpu type at runtime.

Regards
Werner

**Comment by ViralBShah** [comment]
So, no way to make generic ARM openblas binaries that work on any ARM machine, the way we can on x86?

**Comment by wernsaar** [comment]
Hi,

x86 and x86_64 have simple assembly instructions, to get the cpu type.

Similar instructions on ARM and ARM64 processors are protected, which
means, they can only be used in kernel mode, not from user space.

Regards
Werner

**Comment by ViralBShah** [comment]
Thanks. I did not know that. Can /proc/cpuinfo be read and an architecture be picked at runtime?

**Comment by wernsaar** [comment]
Hi,

That would be possible, but I think, that the overhead is too big.

Regards
Werner
