### ISSUE TITLE
"Detecting CPU failed" on Intel i7-5500U (Broadwell)

### ISSUE THREAD

**Issue by bjornfor** [xianyi/OpenBLAS#583]
I cannot build OpenBLAS on my system:

```
Makefile:131: *** OpenBLAS: Detecting CPU failed. Please set TARGET explicitly, e.g. make TARGET=your_cpu_target. Please read README for the detail..  Stop.
```

Looking at the list of supported CPUs (TargetList.txt), it seems BROADWELL is not listed.

**Comment by martin-frbg** [comment]
"make TARGET=HASWELL" will probably work, but you probably guessed that already.

**Comment by bjornfor** [comment]
No, I didn't know that. Thanks for the tip.

**Comment by xianyi** [comment]
Could you try develop branch? I think it already supports broadwell
.

**Comment by bjornfor** [comment]
(I forgot to say that I initially tested the latest release, 0.2.14.)

The develop branch, at commit f38cb67ca813c1c41b7e23795750ced97d794554, builds fine. Yay!

Any plans for making a new release?

**Comment by bjornfor** [comment]
This issue is coming back to haunt me: numpy apparently has issues with openblas 0.2.15, so it is typically being used with old openblas 0.2.14 instead.

https://github.com/NixOS/nixpkgs/commit/73e9cb9748bdd5e3343972aafd094669d629ff3a#commitcomment-16220494

This makes it a bit clumsy to use numpy/openblas from a Linux distro user perspective, one still have to build openblas from source and set TARGET=.

Is there any way you guys could backport broadwell support to 0.2.14? Or point to a commit to cherry-pick that I can suggest for inclusion in NixOS (my distro of choice)? (I tried back-porting the above referenced commit, but that didn't work.)

**Comment by zerothi** [comment]
I do not have troubles using numpy with 0.2.15.

So I guess it depends on how you have build it?

2016-02-20 13:06 GMT+01:00 Bjørn Forsman <notifications@github.com>:

> This issue is coming back to haunt me: numpy apparently has issues with
> openblas 0.2.15, so it is typically being used with old openblas 0.2.14
> instead.
>
> NixOS/nixpkgs@73e9cb9#commitcomment-16220494
> <https://github.com/NixOS/nixpkgs/commit/73e9cb9748bdd5e3343972aafd094669d629ff3a#commitcomment-16220494>
>
> This makes it a bit clumsy to use numpy/openblas from a Linux distro user
> perspective, one still have to build openblas from source and set TARGET=.
>
> Is there any way you guys could backport broadwell support to 0.2.14? Or
> point to a commit to cherry-pick that I can suggest for inclusion in NixOS
> (my distro of choice)? (I tried back-porting the above referenced commit,
> but that didn't work.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xianyi/OpenBLAS/issues/583#issuecomment-186578789>.
>



-- 
Kind regards Nick

**Comment by martin-frbg** [comment]
Guess you could try cherry-picking cpuid_x86.c and driver/others/dynamic.c from the develop branch
(935356c was the most recent commit that updated cpu target detection, or go back in the commit history of these files to find the one that added Broadwell as a type).
Have the "some segmentation faults with numpy and scipy when using 2.15" as mentioned in the nixos comment thread ever been reported here ?

**Comment by bjornfor** [comment]
> Have the "some segmentation faults with numpy and scipy when using 2.15" as mentioned in the nixos comment thread ever been reported here ?

Don't know, deferring to @FRidh (who made that statement).

**Comment by FRidh** [comment]
No, I haven't reported them, since numpy and scipy upstream test against 2.14, and the issues with those packages.

**Comment by martin-frbg** [comment]
Who is your "upstream" then - numpy project itself appears to use Atlas in its automated (travis) checks and recommends to use at least 0.2.15 of OpenBLAS on Linux in its INSTALL document, while scipy's INSTALL.rst document appears to mention only netlib, atlas and closed-source alternatives ?

**Comment by FRidh** [comment]
Hmm, seems I am wrong then. Last time I checked I thought they were using openblas 0.2.14 on Travis.

**Comment by zerothi** [comment]
I would refer to the numpy install document. scipy is so heavily linked
with numpy that they should have the same references.

However, scipy does provide other kinds of interfaces for blas/lapack which
makes it require a stricter interface model (for instance the latest 3.6
LAPACK obsoleted a few functions which will eventually be made obsolete in
the scipy as well).
This is the reason they suggest these implementations.
However, as OpenBLAS follows netlib interface for lapack etc. there should
be no problem in this regard.



2016-02-20 15:07 GMT+01:00 Martin Kroeker <notifications@github.com>:

> Who is your "upstream" then - numpy project itself appears to use Atlas in
> its automated (travis) checks and recommends to use at least 0.2.15 of
> OpenBLAS on Linux in its INSTALL document, while scipy's INSTALL.rst
> document appears to mention only netlib, atlas and closed-source
> alternatives ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xianyi/OpenBLAS/issues/583#issuecomment-186610364>.
>



-- 
Kind regards Nick

**Comment by FRidh** [comment]
Before, we were also using Atlas+Lapack for numpy/scipy. Then we changed to openblas. Since scipy 0.17 we got segfaults
https://github.com/NixOS/nixpkgs/pull/12129
https://github.com/scipy/scipy/issues/5620

**Comment by xianyi** [comment]
@FRidh , could you try develop branch for your segfault?

**Comment by FRidh** [comment]
@xianyi alright, building now.

**Comment by FRidh** [comment]
Aside from a Nix-related issue (incorrect wrapper) I encountered no issues with 6e7be06e072cddc5d34617f28f60a32484b9e910
The specific failing test now passes.

**Comment by xianyi** [comment]
@FRidh , thank you for the update.

**Comment by FRidh** [comment]
@xianyi Any idea when a new version of OpenBLAS would be released?

**Comment by xianyi** [comment]
I try to release a rc version next week.

**Comment by FRidh** [comment]
No more segmentation faults with 0.2.16.rc1.
