### ISSUE TITLE
make test [level1] Segmentation fault E5-2620

### ISSUE THREAD

**Issue by gmsh** [xianyi/OpenBLAS#588]
Hi, there
I failed to compile OpenBLAS. Please Help. Thanks. There are some info below. If you need more, contact me please.
git checked out version a2eaf234fcac38652134b23fa81bb0c85a0baa92 of OpenBLAS
uname -r 
3.10.0-123.20.1.el7.x86_64
Here is the output:

OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 ./sblat1

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f881212c669
#1  0x7f881212bbf2
#2  0x7f881147e6cf
#3  0x7f88114bd15f
#4  0x7f881212dccb
#5  0x401439
#6  0x7f881146e3d8
#7  0x4014b0
#8  0xffffffffffffffff
Makefile:7: recipe for target 'level1' failed
make[1]: *** [level1] Segmentation fault
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/users3/msguo/OpenBLAS/test'
Makefile:117: recipe for target 'tests' failed
make: *** [tests] Error 2

-----------

Here is the make.conf

OSNAME=Linux
ARCH=x86_64
C_COMPILER=GCC
BINARY32=
BINARY64=1
CEXTRALIB=-L/users3/msguo/.linuxbrew/lib -L/users3/msguo/.linuxbrew/Cellar/gcc/5.1.0/lib/gcc/x86_64-unknown-linux-gnu/5.1.0 -L/users3/msguo/.linuxbrew/lib  -lc  
F_COMPILER=GFORTRAN
FC=/users3/msguo/.linuxbrew/bin/gfortran
BU=_
FEXTRALIB=-L/users3/msguo/.linuxbrew/lib -Wl,-rpath,/users3/msguo/.linuxbrew/lib -L/users3/msguo/.linuxbrew/Cellar/gcc/5.1.0/lib/gcc/x86_64-unknown-linux-gnu/5.1.0 -L/users3/msguo/.linuxbrew/lib  -lgfortran -lm -lquadmath -lm -lc  
CORE=SANDYBRIDGE
LIBCORE=sandybridge
NUM_CORES=24
HAVE_MMX=1
OSNAME=Linux
ARCH=x86_64
C_COMPILER=GCC
BINARY32=
BINARY64=1
CEXTRALIB=-L/users3/msguo/.linuxbrew/lib -L/users3/msguo/.linuxbrew/Cellar/gcc/5.1.0/lib/gcc/x86_64-unknown-linu
x-gnu/5.1.0 -L/users3/msguo/.linuxbrew/lib  -lc  
F_COMPILER=GFORTRAN
FC=/users3/msguo/.linuxbrew/bin/gfortran
BU=_
FEXTRALIB=-L/users3/msguo/.linuxbrew/lib -Wl,-rpath,/users3/msguo/.linuxbrew/lib -L/users3/msguo/.linuxbrew/Cell
ar/gcc/5.1.0/lib/gcc/x86_64-unknown-linux-gnu/5.1.0 -L/users3/msguo/.linuxbrew/lib  -lgfortran -lm -lquadmath -l
m -lc  
CORE=SANDYBRIDGE
LIBCORE=sandybridge
NUM_CORES=24
HAVE_MMX=1
HAVE_SSE=1
HAVE_SSE2=1
HAVE_SSE3=1
HAVE_SSSE3=1
HAVE_SSE4_1=1
HAVE_SSE4_2=1
HAVE_AVX=1
MAKE += -j 24
SGEMM_UNROLL_M=16
SGEMM_UNROLL_N=4
DGEMM_UNROLL_M=8
DGEMM_UNROLL_N=4
QGEMM_UNROLL_M=2
QGEMM_UNROLL_N=2
CGEMM_UNROLL_M=8
CGEMM_UNROLL_N=2
ZGEMM_UNROLL_M=1
ZGEMM_UNROLL_N=4
XGEMM_UNROLL_M=1
XGEMM_UNROLL_N=1
CGEMM3M_UNROLL_M=4
CGEMM3M_UNROLL_N=8
ZGEMM3M_UNROLL_M=2
ZGEMM3M_UNROLL_N=8
XGEMM3M_UNROLL_M=2
XGEMM3M_UNROLL_N=2

---------------------

Here is the /proc/cpuinfo
......
processor	: 23
vendor_id	: GenuineIntel
cpu family	: 6
model		: 45
model name	: Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz
stepping	: 7
microcode	: 0x710
cpu MHz		: 1999.921
cache size	: 15360 KB
physical id	: 1
siblings	: 12
core id		: 5
cpu cores	: 6
apicid		: 43
initial apicid	: 43
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid
bogomips	: 4004.53
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

**Comment by wernsaar** [comment]
Please checkout again the latest develop version.

if you get the same errors, could you try to use gcc and gfortran from
the distribution.

**Comment by gmsh** [comment]
Thanks. Compilers from the distribution work fine with version a2eaf23. I'll check out the latest version later.
