### ISSUE TITLE
Fail to build on PPC64 LE

### ISSUE THREAD

**Issue by fabioperez** [xianyi/OpenBLAS#590]
When building OpenBLAS on a PowerPC 64 (POWER7) Little Endian machine, I'm getting the following error:

`ABI version 1 is not compatible with ABI version 2 output`.

**Comment by xianyi** [comment]
@fabioperez , we didn't support POWER7 yet.

**Comment by mtbrandy** [comment]
Submitted pull request 612 for this issue.

**Comment by xianyi** [comment]
@mtbrandy , thank you for the patch. @fabioperez , please try it.

**Comment by fabioperez** [comment]
@mtbrandy, thanks for the patch.

@xianyi I just tested this patch on POWER7 and POWER8 machines. `make` was enough for POWER7. However, for POWER8, I had to run `make TARGET=POWER6` since the architecture detection was failing. This is fixed by https://github.com/xianyi/OpenBLAS/pull/613.

I also ran [BLAS-Tester](https://github.com/xianyi/BLAS-Tester) and everything is passing.

**Comment by leitao** [comment]
Thanks for the patch!
