### ISSUE TITLE
Build failed on Mac OS X 10.10.3

### ISSUE THREAD

**Issue by dongli** [xianyi/OpenBLAS#593]
I used `clang 6.1.0` and `gfortran 4.9.2` to build OpenBLAS on Mac OS X 10.10.3, and encountered the following errors:
```
ld: -rpath can only be used when targeting Mac OS X 10.5 or later
collect2: error: ld returned 1 exit status
```
Because I have added the compiler option `-Wl,-rpath,/opt/packman/gcc/4.9.2/lib`. After some digging, I found the cause:
```
$ grep -r 'MACOS' *
Makefile.system:195:export MACOSX_DEPLOYMENT_TARGET=10.2
```
As you can see, the Mac OS X target has been hardcoded as `10.2`! After I changed it to `10.10`, the problem is gone!

**Comment by xianyi** [comment]
Thank you for the feedback. I just changed to 10.6.
