### ISSUE TITLE
Something strange in C interface for ?geadd() subroutines.

### ISSUE THREAD

**Issue by EpsilonQM** [xianyi/OpenBLAS#594]
Hello, world!

?geadd subroutines perform calculation C := alpha \* A + beta \* C; A and C are matrices, alpha and beta are scalars. 

Matrix A stays intact here, so I expected that pointer on A has to be a pointer on constant. 

Instead of that file cblas.h contains declaration of function for example cblas_sgeadd with pointer on A parameter as float_, but not const float_. Other ?geadd functions have the same problem. 

Is this a bug or feature?

**Comment by xianyi** [comment]
@EpsilonQM ，after installing the library (`make install`), the `cblas.h` will add `const` for `?geadd`.

**Comment by EpsilonQM** [comment]
__xianyi__, thanks for your answer.

Actually I used binary package for Win32 from http://sourceforge.net/projects/openblas/files/v0.2.14/ only and of course added 'const' in my copy of cblas.h manually. It was the simplest way to stop C compiler's crying. Sorry for possibly bad english, I didn't have enough practice.

So my question acually was: will you add const for ?geadd in the cblas.h for everyone, or it must stay unmodified for some reasons? Now I see. Thanks again.
