### ISSUE TITLE
Error when make with USE_OPENMP=1

### ISSUE THREAD

**Issue by chwangaa** [xianyi/OpenBLAS#600]
At the beginning I ran into:

```
BLAS: Program is Terminated. Because you tried to allocate too many memory regions. Segmentation fault

```

So I followed some advice from other issues and try to do:

```
make USE_OPENMP=1
```

However, this gives me the error:

```
Cannot set both USE_OPENMP=1 and USE_THREAD=0. The USE_THREAD=0 is only for building single thead version
```

I also tried to modify the values of USE_THREAD before `make` but the same error persists

Any help please?

**Comment by xianyi** [comment]
Did you build OpenBLAS on single core machine? 
How many cores on your running machine? 

You can try
`make USE_OPENMP=1 NUM_THREADS=32`

**Comment by chwangaa** [comment]
I was running on Jetson TK1 board, I think it has 192 cores.

**Comment by cbergstrom** [comment]
It certainly does not have 192 cores. It may have 192 cuda cores, but not CPU cores.

**Comment by chwangaa** [comment]
Yeah, definitely.

I am wondering whether it is the OPENBLAS setting or the memory which is causing the problem

**Comment by ccccdd** [comment]
@xianyi  i am tried 
make USE_OPENMP=1 NUM_THREADS=32
But still failed
![qq 20151020154859](https://cloud.githubusercontent.com/assets/15207024/10599973/137f60da-7742-11e5-9ffc-bce5bfeed5b5.png)

**Comment by martin-frbg** [comment]
Try "make clean" before the "make USE_OPENMP=1 NUM_THREADS=32" so that all files get rebuilt - you seem to have some conflicting files left over from the first build attempt.
