### ISSUE TITLE
c_check assumes nonempty $cross_suffix if run in a path with a dash

### ISSUE THREAD

**Issue by yesimon** [xianyi/OpenBLAS#605]
When executing make in a path with a dash it in, the `c_check` program automatically detects cross_suffix, but it seems like anything with a dash is assumed to be a cross compile. I don't know whether this is intentional or not, but perhaps a README warning is in order.
```
make[1]: /idi/yesimon-ar: Command not found
../Makefile.tail:40: recipe for target 'libs' failed
make[1]: *** [libs] Error 127
make[1]: Leaving directory '/idi/yesimon-scratch/yesimon/tmp/openblas20150724-14846-n6dn4n/OpenBLAS-0.2.14/interface'
Makefile:141: recipe for target 'libs' failed
make: *** [libs] Error 1
```
From `c_check`: https://github.com/xianyi/OpenBLAS/blob/3f1b57668e3d73944981d7bda194ca133f4660b7/c_check#L28

**Comment by xianyi** [comment]
Thank you for the feedback. I will update README.

**Comment by xianyi** [comment]
@yesimon , I added a dash in the path. However, I cannot reproduce this error.

**Comment by yesimon** [comment]
Sorry, this is because I am using a separate gcc installed in directory with a dash, but it's not actually cross-compiling. This is because `$ARGV` is unshifted in `c_check`, which I originally assumed was just the path of the makefile.

**Comment by xianyi** [comment]
@yesimon , I also tried the gcc with dash path. I cannot reproduce it yet. :(
