### ISSUE TITLE
dgemv_t SIGSEGV

### ISSUE THREAD

**Issue by msuaeronautics13** [xianyi/OpenBLAS#607]
I am using RHEL6 kernel 2.6.32-220.el6.x86_64. Bulldozer architecture. I continuously get a segfault at dgemv_t(). When I set OPENBLAS_NUM_THREADS=1, this issue is avoided (though not desirable).

**Comment by jeromerobert** [comment]
Could you give the openblas version and the compilation options you are using ?

**Comment by msuaeronautics13** [comment]
I'm using OpenBLAS 0.2.14, no compilation options.

**Comment by xianyi** [comment]
@msuaeronautics13 ， could you try develop branch?

**Comment by msuaeronautics13** [comment]
Hi @xianyi,

I've just compiled and tried the develop branch. Unfortunately, I still have this issue. 

More info- I am using OpenBLAS in conjunction with Armadillo. The segfault occurs when I call svd_econ function in my code. 

I have some for loops parallelized by OpenMP which are independent of OpenBLAS. Does this still cause conflict?

**Comment by xianyi** [comment]
@msuaeronautics13 , could you try to build OpenBLAS with `make USE_OPENMP=1`?
@wernsaar ,  any suggestions?

**Comment by msuaeronautics13** [comment]
Building with USE_OPENMP=1 works. However, I am unsure of what's happening here. Is this a worse option in terms of performance? 

Any comment on this discrepancy between Intel and AMD? As stated, I am able to run the same code normally on an Intel CPU.

**Comment by xianyi** [comment]
The performance of `USE_OPENMP=1` is very closed to pthread version.

For AMD bulldozer, I think we need to reproduce on our machine.
