### ISSUE TITLE
cblas_cgemv()

### ISSUE THREAD

**Issue by anim1995** [xianyi/OpenBLAS#608]
hi :) 
i have problem with cblas_cgemv() function. I haven't idea how i can transfer to it the complex matrix A (convert complex float to float).If you know what i mean. The  const void Matrix A is UnsafePointer[Void], but i need complex matrix. If someone could show me any example of using this function? I would be very grateful.

**Comment by anim1995** [comment]
i'm using the code for multiple Y <- alphaAX + bethaY:

- My matrix A:
float A[1024];
z2 = openblas_make_complex_float(a , b);   //a,b I declaated earlier 
A[i]= creal(z2)/c + cimag(z2)/d;    // <- this is my problem with convert complex matrix  to float matrix

- My vector X:
float X[64];
z1 = openblas_make_complex_float(a , b);   //a,b I declarated earlier 
A[i]= creal(z1)/c + cimag(z1)/d;  // < this is my problem with convert complex matrix  to float matrix

- My vector Y:
float Y[16];
z3 = openblas_make_complex_float(0.0 ,0.0);
Y[i]= creal(z3) + cimag(z3);

The cblas_cgemv function call:
float alpha = 1.0;
float beta = 0.0;
cblas_cgemv(CblasRowMajor, CblasNoTrans,16,64,&alpha,A,16,X,1,&beta,Y,1);

Compiler often (not alweys) give me the answer:
- error:segmentation fault
or
- On entry to CGEMM  parameter number 10 had an illegal value

Where is the error in my reasoning? Could you help me ? :) 

Sorry for bad edit text...

**Comment by xianyi** [comment]
@anim1995 , 
You don't need to convert complex matrix A to float. Just input the pointer of matrix A

**Comment by anim1995** [comment]
Thank you :) Best wishes.

**Comment by xianyi** [comment]
I am going to close this issue. If you have any question, please don't hesitate to reopen it.
