### ISSUE TITLE
OpenBLAS crashes Octave when inverting matrices sized 10x10 or bigger

### ISSUE THREAD

**Issue by mxmlnkn** [xianyi/OpenBLAS#609]
When OpenBLAS is installed Octave quits with a segmentation fault when trying to invert matrices sized 10x10 or bigger. This fault happened because OpenBLAS was installed as a dependency. My temporary solution is to replace the shared libraries with those from BLAS.
For additional information see:
https://savannah.gnu.org/bugs/?45651
https://bugs.launchpad.net/yade/+bug/1480173

I'm using the following packages (everything should be packages from the stable Debian repository + Yade repository: yade-dem.org/packages)
* openblas 0.2.12-1
* lapack 3.5.0-4
* eigen 3.2.2-3
* python-minieigen 0.41~dfsg~bzr51
* Octave 3.8.2
* Yade 1.12.0
* Debian 8.1
* libblas3  1.2.20110419-5

steps to reproduce
<pre>
%N=11;
N=12;
A=zeros(N);
for n=2:N-1
A(n,n-1)= 1;
A(n,n )=-2;
A(n,n+1)= 1;
end
A=A(2:end-1,2:end-1);
disp(A);
inv(A); 
</pre>

temporary solution
<pre>
sudo cp /usr/lib/libblas/libblas.so.3 /usr/lib/libblas.so.3
sudo cp /usr/lib/liblapack/liblapack.so.3 /usr/lib/liblapack.so.3
</pre>

<pre>
lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    2
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 58
Model name:            Intel(R) Core(TM) i3-3120M CPU @ 2.50GHz
Stepping:              9
CPU MHz:               1459.960
CPU max MHz:           2500.0000
CPU min MHz:           1200.0000
BogoMIPS:              4988.55
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              3072K
NUMA node0 CPU(s):     0-3
</pre>

**Comment by martin-frbg** [comment]
0.2.12 is outdated, current "stable" is 0.2.14 and your best choice would be to compile a snapshot of the current "develop" branch

**Comment by mxmlnkn** [comment]
Ok, thanks for this hint.
I now configured apt with pinning to install some packages from debian testing.
Unfortunately "testing" also only has OpenBlas 2.12, but with octave 4.0.0 which comes with testing (instead of 3.8.4 in severely outdated debian ""'stable'"") the bug doesn't appear anymore.
