### ISSUE TITLE
Dormlq incorrect size test for Row Major

### ISSUE THREAD

**Issue by btracey** [xianyi/OpenBLAS#615]
Please see https://github.com/gonum/lapack/pull/32 for more information and a reproducer.

The size test in Dormlq for row major is incorrect. Line 56 of https://github.com/xianyi/OpenBLAS/blob/develop/lapack-netlib/lapacke/src/lapacke_dormlq_work.c tests that the stride of A is less than m. However, the size of m is dependent on the Side on which A is multiplied. If A is on the left, the stride must be at least m, but if A is on the right, it only has to have stride n. Thus, the check should be conditional on the Side of the matrix multiplication.

**Comment by xianyi** [comment]
Thank you for the report.

Could you also report this bug to LAPACK developers? http://icl.cs.utk.edu/lapack-forum/viewforum.php?f=13

**Comment by btracey** [comment]
Oh, is that where we report bugs? I tried to send an email to the netlib peolpe which bounced. Thanks.

**Comment by btracey** [comment]
Bug submitted, but it needs to wait for moderation.

**Comment by btracey** [comment]
Lapack bug #133
http://www.netlib.org/lapack/Errata/index2.html#_strong_span_class_maroon_bug_133_span_strong_dormlq_c_interface_error_check

Forum post:
https://github.com/xianyi/OpenBLAS/blob/develop/lapack-netlib/lapacke/src/lapacke_dormlq_work.c

**Comment by xianyi** [comment]
@btracey , Thank you for the update.

**Comment by xianyi** [comment]
@btracey , did I merge the patch to fix this issue?

**Comment by btracey** [comment]
I downloaded the latest OpenBLAS, but our tests still fail for Dormlq. I'll look into it when I have the chance.

**Comment by btracey** [comment]
No. It did not fix the problem. The size comparison is still wrong in OpenBLAS. OpenBLAS has https://github.com/xianyi/OpenBLAS/blob/develop/lapack-netlib/lapacke/src/lapacke_dormlq_work.c
````
else if( matrix_order == LAPACK_ROW_MAJOR ) {
        lda_t = MAX(1,k);
        ldc_t = MAX(1,m);
        /* Check leading dimension(s) */
        if( lda < m ) {
            info = -8;
            LAPACKE_xerbla( "LAPACKE_dormlq_work", info );
            return info;
        }
````

While Lapack has
````
     r = LAPACKE_lsame( side, 'l' ) ? m : n;
        lda_t = MAX(1,k);
        ldc_t = MAX(1,m);
        /* Check leading dimension(s) */
        if( lda < r ) {
            info = -8;
            LAPACKE_xerbla( "LAPACKE_dormlq_work", info );
            return info;
        }
````
OpenBLAS is missing this computation of r.

**Comment by btracey** [comment]
This code has not been fixed. The appropriate lines need to change to 

````
  if (LAPACKE_lsame( side, 'l' )){
            a_t = (double*)LAPACKE_malloc( sizeof(double) * lda_t * MAX(1,m) );
        }else{
            a_t = (double*)LAPACKE_malloc( sizeof(double) * lda_t * MAX(1,n) );
        }
        if( a_t == NULL ) {
            info = LAPACK_TRANSPOSE_MEMORY_ERROR;
            goto exit_level_0;
        }
        c_t = (double*)LAPACKE_malloc( sizeof(double) * ldc_t * MAX(1,n) );
        if( c_t == NULL ) {
            info = LAPACK_TRANSPOSE_MEMORY_ERROR;
            goto exit_level_1;
        }
        /* Transpose input matrices */
        if (LAPACKE_lsame( side, 'l' )){
            LAPACKE_dge_trans( matrix_layout, k, m, a, lda, a_t, lda_t );
        }else{
            LAPACKE_dge_trans( matrix_layout, k, n, a, lda, a_t, lda_t );
        }
````

Again, the size of a depends on the value of side, so the allocation of a_t and the transpose must as well.
