### ISSUE TITLE
GEMM has probably a bug in RowMajor implementation

### ISSUE THREAD

**Issue by Arech** [xianyi/OpenBLAS#620]
Hi
I was playing with GEMM routine while stuck on something strange: when I fed the routine with ColMajor matrices, it works nice. But if I change ordering parameter from ColMajor to RowMajor (all other parameters remaining the same), routine fails with an error saying something about wrong parameter 10. From my point of view, this is strange, because all matrices dimensions remains the same and ordering should influence only how underlying data should be treated. With that in mind, I expected the GEMM to calculate matrix product (of course, the result should be different from the same product in ColMajor ordering), but it just failed.
I was intrigued by the problem and dug into sources and here is what I've found:

OpenBLAS uses a nice trick to allow RowMajor matrix multiplication, that is based on the fact that ColMajor'ed matrix unrolls into the same linear array as would unroll transposed RowMajor'ed matrix and vice-versa. Then using linear algebra properties we can get multiplication result of A * B->C in form of (B' * A')->C'
This means, that in order to get a matrix product of two RowMajor'ed matrices AA [m_rows * k_column] * BB [k * n] -> CC [m * n] we can use the GEMM routine for ColMajored matrices, provided that we call it like we want to get a product of BT[n * k] * AT[k * m]->CT[n * m]. Here ColMajor'ed matrix BT has exactly the same underlying linear representation as RowMajor'ed matrix BB, CM-matrix AT - like RM-matrix AA and CT - like CC.
That was the theory.
In practice the following call to ?gemm() to obtain RowMajor'ed product of AA[m * k] * BB[k * n]->CC[m * n]
```
?gemm(RowMajor, "N", "N",
    m<-CC.rows()/*=m*/, n<-CC.cols()/*=n*/, k<-AA.cols()/*=k*/, alpha,
    AA, lda<-m_param/*=CC.rows()=m*/,
    BB, ldb<-k_param/*=AA.cols()=k*/,...)
```
should be treated as ColMajor multiplication of matrices BT[n * k] * AT[k * m]->CT [n * m], which looks like this call:
```
?gemm(ColMajor, "N", "N",
    m<-CT.rows()/*=CC.cols()=n*/, n<-CT.cols()/*=CC.rows()=m*/, k<-BT.cols()/*=BB.rows()=k*/, alpha,
    BB, lda<-m_param/*=CT.rows()=CC.cols()=n*/,
    AA, ldb<-k_param/*=BT.cols()=BB.rows()=k*/,...)
```
Or in short: treat A as B, m as n (and vice-versa). k- remains the same, lda changes from m to n, ldb remains the same.
Now lets look at the code, file ./interface/gemm.c. Line 326 starts a segment that does this permutations. Lines 335-366 have this content:
```c
    args.lda = ldb;
    args.ldb = lda;

    /* skipped not relevant code here, it doesn't use neither ldb/lda, nor args.ldb / args.lda */

    nrowb = args.k;
    if (transb & 1) nrowb = args.n;

/* not relevant */

    if (args.ldb < nrowb)  info = 10;
```
So what this basically does is just swap lda and ldb content, which is wrong idea provided that my previous thoughts are correct, and then compares invalid args.ldb with nrowb, and that in turn triggers an error that points to invalid parameter 10 (exactly the same error I got while playing with precompiled gemm).

Any thoughts?

[?gemm parameter reference](https://software.intel.com/ru-ru/node/520775#AE8380B9-CAC8-4C57-9AF3-2EAAC6ACFC1B)

**Comment by xianyi** [comment]
I think you give the wrong input for leading dimension with Row Major.

e.g.

```
cblas_dgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans, 
                m, n, k, alpha, A, k, B, n, beta, C, n);
```

**Comment by Arech** [comment]
@xianyi , thanks for reply. Could you please elaborate, why do you think lda- and ldb-params should have the values you've set for them?
As far as I understand the documentation, lda=k and ldb=n are corresponds to transposed matrices, not the normal (as we're using).

**Comment by xianyi** [comment]
The mkl document only described the lda and ldb with the column major matrix.  For row major matrix, it should be k and n.
