### ISSUE TITLE
The procedure entry point cabsf could not be located in the dynamic link library

### ISSUE THREAD

**Issue by frpunzalan** [xianyi/OpenBLAS#621]
Good day everyone.

I am trying to use OpenBLAS in Visual Studio (2013) and was able to build the latest develop branch using the command

$ make TARGET=HASWELL BINARY=32

However, while running the debugger in VS, I run into this error:

"The procedure entry point cabsf could not be located in the dynamic link library"

I think cabsf is part of the C complex support (complex.h). I am using the MinGW and followed the instructions in https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-in-Microsoft-Visual-Studio. I read somewhere though that the MinGW version 4.x does not support complex numbers.

http://mingw-users.1079350.n2.nabble.com/Follow-up-Undefined-reference-to-cabsf-td7582564.html

The project that I am doing does not use complex numbers so I was thinking of just disabling the complex number support during compile. I am not sure how to do this so I tried commenting out the complex.h declarations and the functions that uses _Complex return type (like cdot.c and zdot.c) but I just run into more compile errors. Does anyone know how to disable complex numbers for the compilation?

Note: I am also using NO_LAPACK=1 option.

**Comment by xianyi** [comment]
@frpunzalan ,  Could you try our pre built binary( http://sourceforge.net/projects/openblas/files/v0.2.14/OpenBLAS-v0.2.14-Win32.zip/download)? 

You may also need mingw32 dll. (http://sourceforge.net/projects/openblas/files/v0.2.14/mingw32_dll.zip/download)

If you want to only build single and double real numbers, please edit `OpenBLAS/Makefile.tail`.

Form 
```
BLASOBJS    = $(SBLASOBJS)   $(DBLASOBJS)   $(CBLASOBJS)   $(ZBLASOBJS)
BLASOBJS_P  = $(SBLASOBJS_P) $(DBLASOBJS_P) $(CBLASOBJS_P) $(ZBLASOBJS_P)

```

to

```
BLASOBJS    = $(SBLASOBJS)   $(DBLASOBJS)   
BLASOBJS_P  = $(SBLASOBJS_P) $(DBLASOBJS_P) 
```

Then, you need to edit `OpenBLAS/exports/gensymbol` to delete complex functions (e.g. cgemm, zgemm and others).

**Comment by frpunzalan** [comment]
Thanks for the suggestions, will try that. cheers!

**Comment by frpunzalan** [comment]
I tried using the pre built binary to test the cblas gemm using the test code in the OpenBLAS install page:

#include "stdafx.h"
#include <cblas.h>
#include <stdio.h>
#include <intrin.h>

void main()
{
	printf("openblastest! \n");
	int i = 0;
	double A[6] = { 1.0, 2.0, 1.0, -3.0, 4.0, -1.0 };
	double B[6] = { 1.0, 2.0, 1.0, -3.0, 4.0, -1.0 };
	double C[9] = { .5, .5, .5, .5, .5, .5, .5, .5, .5 };
	cblas_dgemm(CblasColMajor, CblasNoTrans, CblasTrans, 3, 3, 2, 1, A, 3, B, 3, 2, C, 3);

	for (i = 0; i<9; i++)
		printf("%lf ", C[i]);
	printf("\n");
}

The result was [ 11.000 -9.000 5.000 -9.000 21.000 -1.000 5.000 -1.0000 3.000 ].

I then tried to build the develop source without the complex numbers code. I changed the Makefile.tail as you suggested above and also deleted the complex functions in OpenBLAS/exports/gensymbol. The build options I used are

$ make TARGET=NEHALEM HOSTCC=gcc BINARY=32 NO_LAPACK=1

After compiling, I installed using

$ make PREFIX=path/to/install install

Once I got the library and include files, I tried compiling the gemm test again but I run into some errors:

openblas_config.h error: long should be preceded by ";"

I looked into the openblas_config.h fiie and there seems to be a misplaced text in it:

-------------------------------------------------------
...
#define OPENBLAS_HAVE_SSE4_1
 
#define OPENBLAS_HAVE_SSE4_2
 
#define OPENBLAS_CORE_NEHALEM
 

 OPENBLAS_    <--- this was the source of the error
#define OPENBLAS_CHAR_CORENAME "NEHALEM"
--------------------------------------------------------

I deleted the errant line and the project compiled. I run the test again and the result was the same.

Just a note, I noticed that the defined core name in the openblas_config.h file is NEHALEM even though I indicated HASWELL as the TARGET in the build and my PC's core is HASWELL.
 
Sorry for the long winded response but in summary, the build seems to be working. Thanks for the help and the quick response. 

Cheers!

**Comment by xianyi** [comment]
@frpunzalan , because you use 32-bit OpenBLAS, we didn't optimize sandy bridge, haswell on 32-bit OS. Therefore, it uses the old Nehalem kernels.

**Comment by frpunzalan** [comment]
@xianyi ,
I see. Thanks for the info.
