### ISSUE TITLE
Link the library

### ISSUE THREAD

**Issue by Chasego** [xianyi/OpenBLAS#623]
I follow the command line in section __Link the library__  on [User Manual] (https://github.com/xianyi/OpenBLAS/wiki/User-Manual).

What is the __test.c__ file, and where can I find it?

Thanks

**Comment by xianyi** [comment]
The `test.c` is your test code to call BLAS. For example, you can download it from https://gist.github.com/xianyi/5780018

**Comment by Chasego** [comment]
Thank you for your quick reply.
