### ISSUE TITLE
Octave 4.0 PPA crashes when multiplying matrices

### ISSUE THREAD

**Issue by nno** [xianyi/OpenBLAS#625]
Greetings,

as reported in https://github.com/CoSMoMVPA/CoSMoMVPA/issues/33 and https://github.com/matlab2tikz/matlab2tikz/issues/745, a recent upgrade from GNU Octave 3.8 to 4.0 using a PPA on Ubuntu (https://launchpad.net/~octave/+archive/ubuntu/stable) by @mtmiller results in GNU Octave crashing on the travis-ci system. I observed crashes when evaluating simple expressions such as:

```
mtimes([1;2],[1,2])
```

which gives the following error when using the GNU Octave 4.0 PPA referenced above:

```
panic: Illegal instruction -- stopping myself...
attempting to save variables to 'octave-workspace'...
save to 'octave-workspace' complete
/home/travis/build.sh: line 41:  5843 Illegal instruction     $OCTAVE --eval "${TC}"
```

A full transcript from the travis system is here: https://travis-ci.org/nno/CoSMoMVPA/builds/78056101.

Note that I was unable to reproduce this on my laptop using the same Ubuntu version as used by travis running in virtualbox, or on a 64-core machine running Debian. On both machines the code runs fine.

Removing OpenBLAS (through `apt-get purge libopenblas-base`; changeset: https://github.com/nno/CoSMoMVPA/commit/d02d964a88912d33f66fd94944a9979933782410) fixes the issue; tests run fine again (https://travis-ci.org/nno/CoSMoMVPA/builds/78072774). This suggests that in certain circumstances the presence of OpenBLAS is related to GNU Octave crashing.

@mtmiller suggested to raise the issue here. If I can provide further assistance in tracking down the issue, fee free to contact / tag me.

Thanks for you consideration.

**Comment by xianyi** [comment]
@nno , @mtmiller,

I think libopenblas-base of  Ubuntu 12.04 is very old. Is it possible to test OpenBLAS 0.2.14 or develop branch?

Xianyi

**Comment by mtmiller** [comment]
Good point, I hadn't noticed which release these failed builds were tracking. @nno was this illegal instruction error only ever seen on 12.04? If so then the right solution is probably for me to drop the recommendation on OpenBLAS for that specific backport.

**Comment by nno** [comment]
@xianyi, It's not easy (at least for me) to test OpenBLAS 0.2.14 as I don't have direct access to the travis machines; I can only provide it with build configurations.
@mtmiller, I have not encountered the illegal instruction error before. It did not see it using Octave 3.8 on Ubuntu 12.04.  

Thanks to both of you for the quick and helpful replies.

**Comment by mtmiller** [comment]
@nno I mean to ask, do you have any equivalent Travis jobs running on 14.04 without error, and this error only appears on 12.04. It seems to me this is the case, and I should simply drop OpenBLAS from the dependency list as it's too old.

**Comment by nno** [comment]
@mtmiller: Travis only supports running jobs on 12.04 (http://docs.travis-ci.com/user/ci-environment/) at the moment.

Travis support for 14.04 has been asked for in March 2014 (https://github.com/travis-ci/travis-ci/issues/2046) and there is a milestone for it (https://github.com/travis-ci/travis-ci/milestones/Ubuntu%2014.04%20-%20Trusty%20Tahr). The milestone has currently six issues remaining.

Thus, it seems impossible to have equivalent Travis jobs on 14.04.

**Comment by mtmiller** [comment]
And @nno, I will have an update coming to the PPA soon that will drop the `libopenblas-base` dependency in favor of ATLAS for 12.04. If/when you get Travis builds on 14.04, OpenBLAS should work much better there.

**Comment by nno** [comment]
Very good @mtmiller, thanks for your support.

**Comment by tkelman** [comment]
It's not the absolute latest version, but we have a more recent version of openblas available in a ppa at https://launchpad.net/~staticfloat/+archive/ubuntu/julia-deps/ that you might be able to use.

**Comment by martin-frbg** [comment]
The abovementioned travis milestone for Ubuntu 14.04LTS support appears to have been completed
in march of this year, so assuming all is well (and has been for some time)
