### ISSUE TITLE
no test.c file

### ISSUE THREAD

**Issue by babylonico** [xianyi/OpenBLAS#626]
after compiling and installing to /opt/OpenBLAS, I try to link the library with:

gcc -o test test.c -I /opt/OpenBLAS/include/ -L/opt/OpenBLAS/lib -lopenblas
gcc -o test test.c /opt/OpenBLAS/lib/libopenblas.a

but for both keep receiving the error:
gcc: error: test.c: No such file or directory

I can't seem to find it anywhere in the repo...

Any help please? Thanks

**Comment by xianyi** [comment]
Pleae try this test file.
https://gist.github.com/xianyi/5780018

**Comment by babylonico** [comment]
Thanks, this worked for linking the shared library but for linking the static library I got the following:

/opt/OpenBLAS/lib/libopenblas.a(memory.o): In function `openblas_fork_handler':
memory.c:(.text+0x1a0): undefined reference to `pthread_atfork'
/opt/OpenBLAS/lib/libopenblas.a(blas_server.o): In function `blas_thread_init':
blas_server.c:(.text+0x3ae): undefined reference to `pthread_create'
/opt/OpenBLAS/lib/libopenblas.a(blas_server.o): In function `goto_set_num_threads':
blas_server.c:(.text+0x7fa): undefined reference to `pthread_create'
/opt/OpenBLAS/lib/libopenblas.a(blas_server.o): In function `blas_thread_shutdown_':
blas_server.c:(.text+0xa23): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status

**Comment by xianyi** [comment]
`gcc -o test test.c /opt/OpenBLAS/lib/libopenblas.a -lpthread`

**Comment by babylonico** [comment]
Thank you
