### ISSUE TITLE
These function declarations in "cblas.h", where can find the function definitions

### ISSUE THREAD

**Issue by dongxf369** [xianyi/OpenBLAS#627]
Hi 
   
    function declarations in "cblas.h",such as:
            void cblas_saxpy(........);
            void cblas_segmm(........);
            void cblas_sdot(........);
 in which file can  find the function definitions of them ?
                                                                                               Thanks

**Comment by xianyi** [comment]
Please check `OpenBLAS/interface` folder. e.g. `gemm.c`, `axpy.c`, and `dot.c`.
