### ISSUE TITLE
Cholesky factorization .

### ISSUE THREAD

**Issue by anim1995** [xianyi/OpenBLAS#628]
Hi. i would like to use a  SPOTRF function, which computes the Cholesky factorization. I i have one question: how using this function:
- spotrf() 
or
cblas_spotrf() ?

And from which include to use? cblas.h ? 

thank a lot for attansion and for the help.

**Comment by xianyi** [comment]
After OpenBLAS installation (e.g. `make PREFIX=/your/path install`), you can include `lapacke.h`.
Then, call `LAPACK_spotrf` in your C source file.

**Comment by anim1995** [comment]
Thank you :)

**Comment by anim1995** [comment]
So, but i have the next problem. Here:
- http://www.netlib.org/lapack/explore-html/dd/dce/cpotrf_8f.html 
function is described: cpotrf(char, int, complex diemension, int, int);

but in my linux, when i use lapacke_cportf I get an error:
LAPACKE_cpotrf(int, char, int, float __complex__*, int)...

Sorry, but i dont know how i should use this function. Could you give me same example ?
