### ISSUE TITLE
The build system doesn't know about SkyLake

### ISSUE THREAD

**Issue by yuyichao** [xianyi/OpenBLAS#632]
I'm trying to compile OpenBLAS on a SkyLake desktop and see many compile errors very similar to the one reported in https://github.com/xianyi/OpenBLAS/issues/332 . I can understand that it would take some time to tune the kernels on a newly release hardware but it would be nice to be able to compile first.

**Comment by yuyichao** [comment]
I'm adding `TARGET=HASWELL` to make it compile now. (Tried `BROADWELL` and `SKYLAKE` but they don't seem to be acceptable names yet.)

**Comment by martin-frbg** [comment]
"TARGET=BROADWELL" should work on the "develop" branch (which you will probably want to try rather than the already somewhat dated 0.2.14 release)

**Comment by yuyichao** [comment]
I'm pulling from the default branch from github (which should be develop) and `TARGET=BROADWELL` doesn't seem to work. The commit I'm on is 40a3fed and the full make command line argument I have is

```bash
_config=(
  'SMP=1'
  'USE_OPENMP=1'
  'USE_THREAD=1'
  'MAJOR_VERSION=3'
  'NO_LAPACK=0'
  'NUM_THREAD=8'
  'TARGET=BROADWELL'
  'DYNAMIC_ARCH=1'
)
```

**Comment by martin-frbg** [comment]
My mistake, seems the fix from #583 only added the cpuid mapping for Broadwell, not a BROADWELL target as such.

**Comment by yuyichao** [comment]
That's what it seems like for me after a `git grep` as well. =)

**Comment by xianyi** [comment]
@yuyichao , I didn't optimize skylake yet. Therefore, please use haswell kernels. make TARGET=HASWELL

**Comment by yuyichao** [comment]
Generic binary with DYNAMIC_ARCH recognize skylake as Prescott. Would probably be good enough for now to just fix this first.

**Comment by yuyichao** [comment]
Since this issue is about recognising SkyLake rather than optimize for it, I'll close this now.
