### ISSUE TITLE
Recent performance regression on np.dot linked to openBLAS with large matrices

### ISSUE THREAD

**Issue by Newmu** [xianyi/OpenBLAS#637]
Not quite sure if it's an issue with openBLAS or numpy yet. Regularly setup high performance environments from source on a ~monthly basis on the same hardware system and noticed a 2x performance regression that sometimes results in very long/hanging calls to `np.dot` with large matrices (i.e. 4096x4096 and up).

For reference, building both from source this morning results in the issue while using these commits from when last built works fine.
openBLAS 5408074941d5cc0f4aad180562cafcf4cf27a56d
numpy d750cba
cython d6cf8959a58395daacb1e338644a698ef263ce98 (in case its relevant)

The system is ubuntu 14.04.3 on a 8 core haswell 5960x with 64 GB of ddr4. When `np.dot` is called a task manager first shows load distributed across all cores (as expected) and when hanging occurs it appears distributed across only 8 threads (out of 16 with hyperthreading) to begin with and slowly those threads exit till it seems to stall for 10+ minutes on only two threads remaining. The probability of hanging appears to be linked to the size of the matrices, at 8192x8192 it has always hanged (even waiting 100x the normal amount of time it takes) at 4096x4096 it happens ~ 1 in 3 times and at 128x128 it never appears to hang.

Example code

``` python
import numpy as np
a = np.random.randn(4096, 4096)
b = np.random.randn(4096, 4096)
np.dot(a, b)
```

**Comment by martin-frbg** [comment]
There was only a handful of commits since 5408074, none of which seems particularly relevant to your problem. (Android build fixes, Ximatcopy speedup, lapacke_lantr fixes, Intel Skylake CPU detection)

**Comment by xianyi** [comment]
@Newmu , do you have the same problem?
