### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by cddlyf** [xianyi/OpenBLAS#641]
Hello, I just use "make PREFIX="./build/" " to build the openblas in MSYS shell, the error is like below:

make[3]: Leaving directory '/e/Selflearning/OpenBLAS/lapack-netlib/lapacke/utils'
make[2]: Leaving directory '/e/Selflearning/OpenBLAS/lapack-netlib/lapacke'
make[1]: Leaving directory '/e/Selflearning/OpenBLAS/lapack-netlib'
make[1]: Entering directory '/e/Selflearning/OpenBLAS/exports'
ranlib ../libopenblas_sandybridgep-r0.2.14.a
gcc -O2 -DMS_ABI -Wall -m64 -DF_INTERFACE_GFORT -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  libopenblas.def dllinit.obj \
-shared -o ../libopenblas.dll -Wl,--out-implib,../libopenblas.dll.a \
-Wl,--whole-archive ../libopenblas_sandybridgep-r0.2.14.a -Wl,--no-whole-archive  -defaultlib:advapi32 -lgfortran -defaultlib:advapi32 -lgfortran -lgfortran
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgfortran
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgfortran
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgfortran
collect2.exe: error: ld returned 1 exit status
Makefile:85: recipe for target '../libopenblas.dll' failed
make[1]: *** [../libopenblas.dll] Error 1
make[1]: Leaving directory '/e/Selflearning/OpenBLAS/exports'
Makefile:104: recipe for target 'shared' failed
make: *** [shared] Error 2

I am new to openblas and msys, could you help me to solve this error? Thank you!.

**Comment by martin-frbg** [comment]
Your MSYS environment appears to lack the runtime library for the fortran language (probably the fortran compiler "gfortran" as well, but this would have been reported earlier in the log).

**Comment by cddlyf** [comment]
@martin-frbg  I have installed "gcc-fortran" which includes gfortran, 

gfortran --version
GNU Fortran (GCC) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.

GNU Fortran comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of GNU Fortran
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING

**Comment by martin-frbg** [comment]
Strange. Do you have a libgfortran.dll, libgfortran.so or libgfortran.a on your system ? (Depending on your needs you could use "make NO_LAPACK=1" to build only the BLAS part of OpenBLAS, which is written in C)

**Comment by lan2720** [comment]
Hi, I met the similar errors as well. Have you solved the problem?

**Comment by cddlyf** [comment]
@lan2720  which was the system you used, linux or windows?
