### ISSUE TITLE
Dgetri does not permute the matrix inverse. 

### ISSUE THREAD

**Issue by btracey** [xianyi/OpenBLAS#643]
See https://github.com/gonum/lapack/pull/53 for the test.

Dgetri is supposed to return the inverse of A. I find that in the OpenBLAS implementation, a permutation is found, so if D is the result of Dgetri, D * A = P (a permutation matrix) instead of D * A = I.

**Comment by martin-frbg** [comment]
As far as I can tell, "the OpenBLAS implementation" is an unchanged copy of netlib LAPACK.

**Comment by martin-frbg** [comment]
I wonder if it could be related to this (finite precision arithmetic leading to singularities not always being caught):
http://icl.cs.utk.edu/lapack-forum/archives/lapack/msg00777.html
though it could be that I misinterpreted the layout of your test matrix

**Comment by martin-frbg** [comment]
Probably related to #644 (Go interface converting the index array IPIV from FORTRAN to C/Go semantics on return, which will mean its members are off by one in a succeeding call to a LAPACK routine) ?

**Comment by btracey** [comment]
The exact problem was my fault. I forgot that the c-lapack interface uses 1-indexed permutation indices. 

Sorry for the noise.
