### ISSUE TITLE
LAPACK_dgetri segfaults with valid input

### ISSUE THREAD

**Issue by kortschak** [xianyi/OpenBLAS#644]
The following code segfaults:

```
#include <stdio.h>
#include <lapacke.h>

int row_major = 101;

int main() {
    int n = 5, lda = 5;
    double a[25]= {
	    1.0068682307286712, 0.0006563701921747622, 0.0015651925473279123, 0.0009696951891448456, 0.0030091186058528708,
	    0.0029505605052340634, 1.0075237936955501, 0.00206120842382375, 0.008650488985688404, 0.006958313070952352,
	    0.004656913691308816, 0.0028061717948115127, 1.002917945501823, 0.006762056214196472, 0.0021519910984140996,
	    0.002018008617674593, 0.0035804510329558873, 0.005679621307385239, 1.0085535789504505, 0.0028879336245419863,
	    0.005116981674247539, 0.00807230660610453, 0.00211182875664514, 0.003685972023618826, 1.0030938250227397
	};
	int ipiv[5] = {0, 4, 2, 3, 4};

    int res;
    res = LAPACKE_dgetri( row_major, n, a, lda, ipiv );
    printf("dgetri res=%d\n", res);
}
```

The segfault is abolished if the LAPACKE_dgetri_work call to LAPACK_dgetri is commented out - this is the minimal change. It is not clear from inspection of dgetri.f what is causing the problem.

**Comment by martin-frbg** [comment]
Apparently the IPIV array of pivot indices is setup incorrectly on entry to dgetri - looks as if the LAPACKE interface sees no need to convert your input to FORTRAN default array semantics (indices starting from 1). No idea if there is any documentation that claims it will, so possibly user error.
(Header of dgtri.f states that IPIV members have to be between 1 and N

**Comment by kortschak** [comment]
The input values here are produced by a call to LAPACKE_dgetrf.

**Comment by martin-frbg** [comment]
That would appear to indicate that dgetf2 (called from dgetrf) created an invalid (zero) IPIV member, wonder if it had a nonzero "INFO" return value. At least I saw no code that would shift IPIV values by -1 later on.

**Comment by kortschak** [comment]
Found it thanks! The Go wrapper does that on exit from Dgetrf and the Dgetri didn't reverse that. Sorry for the noise here.

**Comment by martin-frbg** [comment]
So I suppose #643 can go down as well ?

**Comment by kortschak** [comment]
Yes, I think so. I just ran those tests with the corrected Go code and we pass.
