### ISSUE TITLE
git describe shows the wrong tag

### ISSUE THREAD

**Issue by jeanfrancisroy** [xianyi/OpenBLAS#645]
Forgive me if the issue is only on my side, but it seems that there is a problem with the tags on this Git repository.

I am trying to create an git version of the ArchLinux OpenBLAS package, and the standard way of getting the version number is to execute the following :

$ git describe --tags

Currently, it gives the following :
v0.2.9.rc1-679-ga96a4cb

But it seems to me that the latest tag should be at least v0.2.14. Is something wrong with the way that tags are handled in the git repo?

Thanks!

**Comment by martin-frbg** [comment]
This appears to be a peculiarity of the "develop" branch (which may rightly be git's default for "HEAD"), probably this was tagged only once very early in its lifetime. If I explicitly clone with "-b master" the "git describe" reports v0.2.14 as expected.

**Comment by martin-frbg** [comment]
I remember the version number in the tag on the develop branch being "correct" for some while in the 0.2.16 timeframe, but a current git clone operation again gets an outdated version number in the tag - v0.2.17-268-g8f9975e (note the hash after the "g" correctly matches the current state)
I suspect this tagging business is a manual step that is all too easy to miss when doing releases, and version numbers probably make sense for static releases only, while the develop branch is best characterised by the hash only (though it may be nice to know what its last versioned ancestor was).
Thoughts ?

**Comment by jeromerobert** [comment]
Yes you are right, this bug should be closed. In `v0.2.9.rc1-679-ga96a4cb` only `a96a4cb` is meaningful, that's how git and `git describes` works.

**Comment by martin-frbg** [comment]
Thanks for your insight. Closing.

**Comment by martin-frbg** [comment]
FWIW, in https://github.com/Reference-LAPACK/lapack/issues/123 this is now claimed to be the result of using "git tag" rather than "git tag -a"

**Comment by zerothi** [comment]
@martin-frbg 

Well not exactly, `git describe --tags` takes _all_ tags into consideration. And the tags for `v0.2.19` in `master` is already annotated.  
However, the thing about the OpenBLAS development is that the `master` branch the release branch, whereas the `develop` branch is... well... the development branch. The tags are created on hash's in the `master` branch. Hence `git describe` in the `develop` branch cannot _reach_ the hash in the `master` branch.   
Do this and you will see:

    $> git clone https://github.com/xianyi/OpenBLAS.git
    $> git describe --tags # or git describe (`--tags` simply takes the most recent tag, lightweight or annotated)
    v0.2.17-381-ge2489c9
    $> git checkout master
    $> git describe --tags # or git describe
    v0.2.19-2-gbcfc298

There is no surprise here. Whether the OpenBLAS team wants `describe` to work on the develop branch requires the tag to be made on the `develop` branch (or just so the tagged hash is reachable from the `develop` branch).

**Comment by martin-frbg** [comment]
Ah thanks, and sorry for the noise.
