### ISSUE TITLE
Error with make install

### ISSUE THREAD

**Issue by groutr** [xianyi/OpenBLAS#648]
When compiling openblas on linux64:
`make FC=gfortran USE_THREAD=1 NUM_THREADS=128`
(note that this is a single core machine, but trying to compile for multi-core machines).

At the end of compilation, I have a library named
`  Library Name     ... libopenblas_nehalemp-r0.2.14.a (Multi threaded; Max num-threads is 128)`

but when I try to `make PREFIX=$PREFIX install`
it fails with:
```
Copying the static library to /opt/xxxx/lib
install: cannot stat `libopenblas_nehalem-r0.2.14.a': No such file or directory
```
It seems the flag that triggers this error is `NUM_THREADS`.  `make install` runs successfully when openblas is compiled without this flag, but fails with the flag.  Even if I use `NO_STATIC=1`, the error persists.

**Comment by martin-frbg** [comment]
Does "make PREFIX=$PREFIX USE_THREAD=1 install" work for you ? Suspect if you give all the important information on the make command line instead of editing Makefile.rule, "make install" will not know that you expect it to install the threaded (...p...) version of the library

**Comment by groutr** [comment]
That resolves the problem.  It would be nice if the documentation mentioned something about that.  I typically don't pass flags to make install.
