### ISSUE TITLE
Two errors happen when running "make FC=gfortran"

### ISSUE THREAD

**Issue by lan2720** [xianyi/OpenBLAS#649]
the error script as following:
"""
Makefile:125: recipe for target '../libopenblas_piledriverp-r0.2.14.so' failed
make[1]: *** [../libopenblas_piledriverp-r0.2.14.so] Error 1
make[1]: Leaving directory '/home/lan/Packages/OpenBLAS/exports'
Makefile:89: recipe for target 'shared' failed
make: *** [shared] Error 2
"""
How can i solve such a problem?

Thanks.

**Comment by martin-frbg** [comment]
Please post more of the error message - what you copied so far is just the summary telling us that "something" failed, nothing about the actual problem that led to it failing. Do you have gfortran installed ? Depending on your system (what is your hardware and operating system, by the way ?), you may have to install a separate package gfortran-devel as well.

**Comment by martin-frbg** [comment]
@lan2720: Any updates on this, or can this bug report be closed ? (Depending on the circumstances, you may have to install the gfortran package for your operating system, or some related package probably named "binutils","build-essentials" or similar. If you did a build with different settings in this directory earlier, run "make clean" before the "make")

**Comment by xianyi** [comment]
@lan2720 , I am going to close this issue. If you has any further questions, please create an issue. Thank you
