### ISSUE TITLE
Windows build with rubenvb's builds is not possible

### ISSUE THREAD

**Issue by varosi** [xianyi/OpenBLAS#650]
Windows 10 x64

I follow installation instructions using:
"rubenvb's Personal Builds: 32-bit or 64-bit."

And then they say we have to proceed with running "make". "make" executable is not exist in rubenvb's build. How am I supposed to build it with rubenvb's builds?

**Comment by martin-frbg** [comment]
Do you have a make.exe anywhere ? (If yes, you may have to adjust your PATH variable accordingly,
if no you will probably have to download a separate package to get the mingw version of "make". (And from a quick look at the sourceforge page, rubenvb's packages appear to be outdated ?)

**Comment by varosi** [comment]
With MSYS2 with installed:

- Install MSYS2
- Do inside:
pacman -S make
pacman -S autoconf
pacman -S gcc
pacman -S gcc-fortran

Build is done. There are errors and I have opened another issue.
This is about instructions to build OpenBLAS under Windows.

**Comment by martin-frbg** [comment]
I suppose this issue can be closed now ?

**Comment by varosi** [comment]
I'm still cannot build it on Windows. May be someone should try on Windows and update building instructions accordingly. There are some intermediate steps that are not written there, like pacman installations.

**Comment by martin-frbg** [comment]
Perhaps something in #380,#381 helps ? My guess is that the reference to "rubenvb's build" in the documentation is outdated - someone may have provided anecdotal information that it could be used about three years ago when these builds were still actively maintained. As regards intermediate steps like installing compilers from pacman or similar archives, perhaps what you are looking for is a more general introduction to msys/mingw and related build tools like "make" or "install" that are commonly used in unix-like environments.

**Comment by varosi** [comment]
You're right. But what if for installing on Linux I give "Windows"
instructions... It's not logical. Windows instructions should be based on
Windows experiance and tools. If steps doesn't work - everyone that try
them will lose shes time, which will be multiplied by people that are
trying. It's much better if first one that have done successful build write
down all steps needed. If I succeed when I have some more time to try, I'll
write down here my steps.

2015-11-03 15:25 GMT+02:00 Martin Kroeker <notifications@github.com>:

**Comment by martin-frbg** [comment]
I have now modified the Installation Guide to make it clearer that msys installation is required to get the "make" utility, and also added instructions for msys2/pacman installs based on your suggestion.

**Comment by varosi** [comment]
Thank you! I'll try it.
