### ISSUE TITLE
Tests fail due to unliking OpenMP libraries (undefined reference to `omp_in_parallel')

### ISSUE THREAD

**Issue by weijianwen** [xianyi/OpenBLAS#651]
Dear all,

```make tests``` fails due to missing OpenMP libraries when I tried to build OpenBLAS-0.2.14 with GCC 4.9.3. This issue is similar to #456  .

Steps to reproduce this issue
------

	$ tar xzpf OpenBLAS-0.2.14.tar.gz; cd OpenBLAS-0.2.14
	$ make clean; make TARGET=SANDYBRIDGE USE_OPENMP=1 NO_AFFINITY=1; make tests

Error messages
------

	gfortran -O2 -Wall -m64   -o cblat1 cblat1.o ../libopenblas_sandybridgep-r0.2.14.a -lm -lpthread -lgfortran -lm -lpthread -lgfortran 
	gfortran -O2 -Wall -m64   -o zblat1 zblat1.o ../libopenblas_sandybridgep-r0.2.14.a -lm -lpthread -lgfortran -lm -lpthread -lgfortran 
	gfortran -O2 -Wall -m64   -o dblat1 dblat1.o ../libopenblas_sandybridgep-r0.2.14.a -lm -lpthread -lgfortran -lm -lpthread -lgfortran 
	../libopenblas_sandybridgep-r0.2.14.a(zaxpy.o): In function `zaxpy_':
	zaxpy.c:(.text+0x91): undefined reference to `omp_in_parallel'
	zaxpy.c:(.text+0xd9): undefined reference to `omp_get_max_threads'

A workaround
------

Setting ```-fopenmp``` as the ```LDFLAGS``` is a workaround.

	$ make clean; make TARGET=SANDYBRIDGE USE_OPENMP=1 NO_AFFINITY=1; make LDFLAGS="-fopenmp" tests

My environment variables
------

	LANG=zh_CN.UTF-8
	LC_CTYPE=zh_CN.UTF-8
	USER=rpmbuild
	LOGNAME=rpmbuild
	HOME=/home/rpmbuild
	PATH=/home/rpmbuild/.local/bin:/home/rpmbuild/bin:/usr/local/bin:/usr/local/sbin:/usr/lib64/qt-3.3/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/bin:/bin:/usr/bin:/home/rpmbuild/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/bin
	MAIL=/var/spool/mail/rpmbuild
	SHELL=/bin/zsh
	SSH_TTY=/dev/pts/1
	TERM=screen-256color
	SHLVL=1
	PWD=/home/rpmbuild
	OLDPWD=/home/rpmbuild
	HISTCONTROL=ignoredups
	HISTSIZE=10000
	CVS_RSH=ssh
	G_BROKEN_FILENAMES=1
	KDEDIRS=/usr
	KDE_IS_PRELINKED=1
	LESSOPEN=||/usr/bin/lesspipe.sh %s
	MODULESHOME=/usr/share/Modules
	LOADEDMODULES=
	QTDIR=/usr/lib64/qt-3.3
	QTINC=/usr/lib64/qt-3.3/include
	QTLIB=/usr/lib64/qt-3.3/lib
	MODULEPATH=/lustre/usr/modulefiles/pi
	PAGER=less
	LESS=-R
	ZSH_TMUX_TERM=screen-256color
	_ZSH_TMUX_FIXED_CONFIG=/home/rpmbuild/dotfiles/oh-my-zsh/plugins/tmux/tmux.extra.conf
	VISUAL=vim
	EDITOR=vim
	GIT_EDITOR=vim
	CLICOLOR=1

**Comment by weijianwen** [comment]
My environment variable list above is incomplete. Compiler-related variables are set by environemtn modules. For example,

    setenv          CC                      gcc
    setenv          GCC                     gcc
    setenv          CXX                     g++
    setenv          FC                      gfortran
    setenv          F77                     gfortran

In my environemnt, ```$FC``` is equivalent to gfortran by default. So I don't need to add ```FC=gfortran``` option at building.

**Comment by xianyi** [comment]
Please use `make USE_OPENMP=1 tests`.

**Comment by weijianwen** [comment]
```make USE_OPENMP=1 tests``` works. Thank you!
