### ISSUE TITLE
openblas win64 int64 visual stodio2015 0x000007b error

### ISSUE THREAD

**Issue by mxmxlwlw** [xianyi/OpenBLAS#653]
My computer is x64 based, and I compiled the program with x64 compiler. When I run my program, it gives 0x000007b error code.

**Comment by martin-frbg** [comment]
From a quick google for the code, this error could mean that your program finds a 32bit dll at runtime instead of the required 64bit version.

**Comment by xianyi** [comment]
Please use win64-int32 dll

**Comment by mxmxlwlw** [comment]
Thank you! Blas can run well now. But there is another problem. When I include lapacke.h, the program can't even be complied. 
It suggests that loss ';' in front of  the name "lapack_make_complex_float"
Is there something I forgot to do?

**Comment by xianyi** [comment]
Oh, this maybe a bug at lapacke.h
