### ISSUE TITLE
Build failure in Ubuntu 14.04 Linux

### ISSUE THREAD

**Issue by Hamstak** [xianyi/OpenBLAS#655]
getarch_2nd.c: In function ‘main’:
[redacted]
gemv.c:232:41: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [sgemv.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/tmp/OpenBLAS/interface'
make: *** [libs] Error 1

From looking at other issues I've figured out that OpenBLAS isn't recognizing the architecture of my CPU. Using AMD a6-3420m. I might be looking in the wrong direction however.

**Comment by xianyi** [comment]
Yes, I think OpenBLAS didn't detect your CPU correctly. Please try `make TARGET=BARCELONA`.

**Comment by Hamstak** [comment]
Getting a new error this time, takes quite a while to get through the whole text, but the end looks like this:

make[3]: Leaving directory `/tmp/OpenBLAS/lapack-netlib/lapacke/utils'
make[2]: Leaving directory `/tmp/OpenBLAS/lapack-netlib/lapacke'
make[1]: Leaving directory `/tmp/OpenBLAS/lapack-netlib'
make[1]: Entering directory `/tmp/OpenBLAS/exports'
perl ./gensymbol linktest  x86 _ 0 0 0 0 0 0 "" "" > linktest.c
gcc -O2 -Wall -m32 -DF_INTERFACE_GFORT -fPIC -DNO_AVX -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  -shared -o ../libopenblas_barcelonap-r0.2.14.so \
	-Wl,--whole-archive ../libopenblas_barcelonap-r0.2.14.a -Wl,--no-whole-archive \
	-Wl,-soname,libopenblas.so.0 -lm -lpthread -lgfortran -lm -lpthread -lgfortran
gcc -O2 -Wall -m32 -DF_INTERFACE_GFORT -fPIC -DNO_AVX -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  -w -o linktest linktest.c ../libopenblas_barcelonap-r0.2.14.so  && echo OK.
../libopenblas_barcelonap-r0.2.14.so: undefined reference to `omp_in_parallel'
../libopenblas_barcelonap-r0.2.14.so: undefined reference to `omp_get_max_threads'
collect2: error: ld returned 1 exit status
make[1]: *** [../libopenblas_barcelonap-r0.2.14.so] Error 1
make[1]: Leaving directory `/tmp/OpenBLAS/exports'
make: *** [shared] Error 2


Any ideas? Checking for other issues I haven't found anything specifically that helps in anyway.

**Comment by xianyi** [comment]
Did you use OpenMP?

`make TARGET=BARCELONA USE_OPENMP=1`

**Comment by Hamstak** [comment]
Success! Thank you for your assistance!

**Comment by sainisanjay** [comment]
Hello xianyi , 
I have got all most same error and i have tried your mentioned both commands but it gives me the same error: any idea how to solve? Thanks

make[1]: Leaving directory `/home/sanjay/OpenBLAS/ctest'
make[1]: Entering directory `/home/sanjay/OpenBLAS/exports'
gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  -shared -o ../libopenblas_barcelonap-r0.2.14.so \
	-Wl,--whole-archive ../libopenblas_barcelonap-r0.2.14.a -Wl,--no-whole-archive \
	-Wl,-soname,libopenblas.so.0 -lm -lpthread -lgfortran -lm -lpthread -lgfortran
/usr/bin/ld: cannot find -lgfortran
collect2: error: ld returned 1 exit status
make[1]: *** [../libopenblas_barcelonap-r0.2.14.so] Error 1
make[1]: Leaving directory `/home/sanjay/OpenBLAS/exports'
make: *** [shared] Error 2

**Comment by xianyi** [comment]
Please install gfortran
