### ISSUE TITLE
OpenMP symbols without USE_OPENMP=1

### ISSUE THREAD

**Issue by buffer51** [xianyi/OpenBLAS#661]
Hi,

I have a question regarding building OpenBLAS with multi-threading: does it use OpenMP by default (i.e. when you just have USE_THREAD=1)?

I had built with USE_THREAD=1 and again with USE_THREAD=1 USE_OPENMP=0 but I still end up with a symbol called omp_in_parallel in the generated library.

This results in undefined symbols when I link with OpenBLAS (no error is raised since it is probably never used, but I don't like having undefined symbols around). Is this normal behavior?

**Comment by xianyi** [comment]
@buffer51 , OpenBLAS should use pthread by default (USE_THREAD=1) without OpenMP.

**Comment by buffer51** [comment]
Ok, that's what I imagined. Still
```nm -s libopenblas.a | grep omp```
gives
```w omp_in_parallel```

The symbol shouldn't be there at all, should it?

**Comment by xianyi** [comment]
@buffer51 , please check line 748 at `OpenBLAS/driver/other/blas_server.c`. OpenBLAS detects whether the library is used in an OpenMP region.  

The `w` of `w omp_in_parallel` means weak.
At `common.h`,  the declare is `int omp_in_parallel  (void) __attribute__ ((weak));`.

http://www.cs.virginia.edu/~wh5a/blog/The%20weak%20attribute%20of%20gcc.html
The linker will fill in 0 for undefined weak symbols.

**Comment by buffer51** [comment]
Hm ok. i was just worried because in the final shared library I build, `readelf` still gives me:
```00000000     0 NOTYPE  WEAK   DEFAULT  UND omp_in_parallel```

But if that's normal, everything is good! Thanks
