### ISSUE TITLE
OpenBLAS fails compiling MATGEN

### ISSUE THREAD

**Issue by edniner** [xianyi/OpenBLAS#663]
Hi,

I've been attempting to install version 2.14.  My install command is:

make DYNAMIC_ARCH=1 NO_AVX=1 NO_AVX2=1
I have found these install errors necessary to avoid other errors earlier in the compilation.

My cpu is:
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 13
model name	: QEMU Virtual CPU version (cpu64-rhel6)
stepping	: 3
microcode	: 1
cpu MHz		: 2659.996
cache size	: 4096 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 4
wp		: yes
flags		: fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm up unfair_spinlock pni cx16 hypervisor lahf_lm
bogomips	: 5319.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

The installation gets to the point where MATGEN is being installed and produces the following error.

( cd TESTING/MATGEN; make )
make[2]: Entering directory `/scratch/nova/caffe_externals/OpenBLAS-develop/lapack-netlib/TESTING/MATGEN'
gfortran -O0 -Wall -m64 -fPIC -c slaran.f
gfortran -O0 -Wall -m64 -fPIC -c dlaran.f
ar -ru ../../../libopenblas-r0.2.14.a slatms.o slatme.o slatmr.o slatmt.o slagge.o slagsy.o slakf2.o slarge.o slaror.o slarot.o slatm2.o slatm3.o slatm5.o slatm6.o slatm7.o slahilb.o clatms.o clatme.o clatmr.o clatmt.o clagge.o claghe.o clagsy.o clakf2.o clarge.o claror.o clarot.o clatm1.o clarnd.o clatm2.o clatm3.o clatm5.o clatm6.o clahilb.o slatm1.o slaran.o slarnd.o dlatms.o dlatme.o dlatmr.o dlatmt.o dlagge.o dlagsy.o dlakf2.o dlarge.o dlaror.o dlarot.o dlatm2.o dlatm3.o dlatm5.o dlatm6.o dlatm7.o dlahilb.o zlatms.o zlatme.o zlatmr.o zlatmt.o zlagge.o zlaghe.o zlagsy.o zlakf2.o zlarge.o zlaror.o zlarot.o zlatm1.o zlarnd.o zlatm2.o zlatm3.o zlatm5.o zlatm6.o zlahilb.o dlatm1.o dlaran.o dlarnd.o
ar: slatms.o: No such file or directory
make[2]: *** [../../../libopenblas-r0.2.14.a] Error 1
make[2]: Leaving directory `/scratch/nova/caffe_externals/OpenBLAS-develop/lapack-netlib/TESTING/MATGEN'
make[1]: *** [tmglib] Error 2
make[1]: Leaving directory `/scratch/nova/caffe_externals/OpenBLAS-develop/lapack-netlib'
make: *** [netlib] Error 2

I can confirm that indeed slatms.o does not exist, although slatms.f is present.

Any suggestions?

**Comment by martin-frbg** [comment]
Look for any error messages at the point where slatms.f is compiled (or try building the current development version from github, there have been several important fixes since the 0.2.14 release).

**Comment by martin-frbg** [comment]
Also see suggestions in #502

**Comment by xianyi** [comment]
I am going to close this issue. If you have any questions, please reopen it.
