### ISSUE TITLE
Does this support sparse vector - matrix operation?

### ISSUE THREAD

**Issue by amartya18x** [xianyi/OpenBLAS#665]
What I am particular interested in is multiplying dense matrix with sparse vector

**Comment by xianyi** [comment]
@amartya18x , we didn't support sparse vectors or matrices.

**Comment by amartya18x** [comment]
What would you recommend I use for this particular type of operation I mentioned? I would love to continue using BLAS .

**Comment by xianyi** [comment]
I don't know which library supports your operation. You can implement it.
Or, fille the zero in your sparse vector and call gemv.

**Comment by amartya18x** [comment]
Okay.
I was looking for a wrapper to sparse blas but maybe I can implement by
filing out the zeros as you said and calling gemv.

On Mon, Oct 12, 2015 at 5:12 PM Zhang Xianyi <notifications@github.com>
wrote:

> I don't know which library supports your operation. You can implement it.
> Or, fille the zero in your sparse vector and call gemv.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xianyi/OpenBLAS/issues/665#issuecomment-147464307>.
>
-- 
======================================================
Amartya Sanyal
Third Year Undergraduate
Dept. of Computer Science And Engineering
IIT Kanpur

*"You sort of start thinking anything’s possible if you’ve got enough
nerve." - Ginny Weasley*

**Comment by xianyi** [comment]
I don't think sparse blas supports the multiplication of dense matrix and sparse vector.

**Comment by amartya18x** [comment]
yes, it doesn't. Have been searching the whole day for something. I am not
sure but maybe transposing the whole expression and using level 3 matrix -
matrix operations along with transposing  might work, but I am not sure
whether representing the vector as a matrix in the format would actually
help in optimizing.

On Mon, Oct 12, 2015 at 5:16 PM Zhang Xianyi <notifications@github.com>
wrote:

> I don't think sparse blas supports the multiplication of dense matrix and
> sparse vector.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xianyi/OpenBLAS/issues/665#issuecomment-147466028>.
>
-- 
======================================================
Amartya Sanyal
Third Year Undergraduate
Dept. of Computer Science And Engineering
IIT Kanpur

*"You sort of start thinking anything’s possible if you’ve got enough
nerve." - Ginny Weasley*

**Comment by grisuthedragon** [comment]
The standard about spblas(the sparse blas defintion) ( See "I. Duff, M. Heroux, R. Pozo, "An Overview of the Sparse Basic Linear Algebra Subprograms: The New Standard from the BLAS Technical Forum," ACM TOMS, Vol. 28, No. 2, June 2002, pp. 239-267" ) only focuses on sparse vector-vector operations and on sparse matrix with dense vector operations. Looking into the documentation of the MKL will tell you the same. But I think a possible (and efficient) workaround to implement 

    x :=  alpha * A * y + beta *x 

where y is a sparse vector stored as y_data and  y_idx will by something like 

    for j in length(y_idx) 
        AXPBY(alpha*y_data(j), A(:,y_idx(j)), beta, x) 
    endfor

The AXPBY operation ( which is also not officially in the reference BLAS ) is supported by OpenBLAS. 

Another way is to create a intermediate copy of A containing only the affected columns and the run the norm GEMV operation on it. 

The question is, do we need this special operation in OpenBLAS or not. From my experience operations where sparse vectors appear are not very common, we do need it.

**Comment by amartya18x** [comment]
In recent times, a lot of work is being done in Sparse Recovery,
Compressive Sensing etc and in these sparse vector is quite common, so I
think we should be incorporating this one.

On Tue, Oct 13, 2015 at 9:32 AM Martin Köhler <notifications@github.com>
wrote:

> The standard about spblas(the sparse blas defintion) ( See "I. Duff, M.
> Heroux, R. Pozo, "An Overview of the Sparse Basic Linear Algebra
> Subprograms: The New Standard from the BLAS Technical Forum," ACM TOMS,
> Vol. 28, No. 2, June 2002, pp. 239-267" ) only focuses on sparse
> vector-vector operations and on sparse matrix with dense vector operations.
> Looking into the documentation of the MKL will tell you the same. But I
> think a possible (and efficient) workaround to implement
>
> x :=  alpha * A * y + beta *x
>
> where y is a sparse vector stored as y_data and y_idx will by something
> like
>
> for j in length(y_idx)
>     AXPBY(alpha*y_data(j), A(:,y_idx(j)), beta, x)
> endfor
>
> The AXPBY operation ( which is also not officially in the reference BLAS )
> is supported by OpenBLAS.
>
> Another way is to create a intermediate copy of A containing only the
> affected columns and the run the norm GEMV operation on it.
>
> The question is, do we need this special operation in OpenBLAS or not.
> From my experience operations where sparse vectors appear are not very
> common, we do need it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xianyi/OpenBLAS/issues/665#issuecomment-147662971>.
>
-- 
======================================================
Amartya Sanyal
Third Year Undergraduate
Dept. of Computer Science And Engineering
IIT Kanpur

*"You sort of start thinking anything’s possible if you’ve got enough
nerve." - Ginny Weasley*

**Comment by zerothi** [comment]
I do not think this should be directly incorporated in OpenBLAS, at least not until it has been adopted by the reference BLAS implementation.

Doing so will expose a non-standard routine in a library following standards. I think this is sub-optimal.
Better use/create a 3rd party library which can link to standard BLAS libraries.

**Comment by grisuthedragon** [comment]
Because of the fact, that the reference BLAS will only change slowly, if it changes. I would say as long as the MKL(on one of the other major BLAS implementations)  does not provide this feature as a reference it is better to build your own implementation on top of basic operations from  OpenBLAS or MKL. For my own software projects I use my own extension-BLAS library implementing such operations that are BLAS like but not in the standard.  

I would implement both ideas I stated above and run  a micro benchmark to determine the best performing one.

**Comment by martin-frbg** [comment]
moved to the faq in the wiki
