### ISSUE TITLE
Error when compiling to ARM7

### ISSUE THREAD

**Issue by j-bo** [xianyi/OpenBLAS#673]
When compiling to android arm7 on a linux host I get the following error : 
```
blas_server.c: In function 'blas_thread_init':
blas_server.c:575:16: error: storage size of 'rlim' isn't known
  struct rlimit rlim;
                ^
blas_server.c:578:9: warning: implicit declaration of function 'getrlimit' [-Wimplicit-function-declaration]
         if(0 == getrlimit(RLIMIT_NPROC, &rlim)) {
         ^
blas_server.c:578:27: error: 'RLIMIT_NPROC' undeclared (first use in this function)
         if(0 == getrlimit(RLIMIT_NPROC, &rlim)) {
                           ^
blas_server.c:578:27: note: each undeclared identifier is reported only once for each function it appears in
blas_server.c:575:16: warning: unused variable 'rlim' [-Wunused-variable]
  struct rlimit rlim;
                ^
make[1]: *** [blas_server.o] Erreur 1
```
Here's how I start the build : 
```
make HOSTCC=gcc CC=arm-linux-androideabi-gcc NO_LAPACK=1 TARGET=ARMV7
```

I managed to correct the error modifying the file `driver/others/blas_server.c` from this : 
```
#if defined(OS_LINUX) || defined(OS_NETBSD) || defined(OS_DARWIN)
#include <dlfcn.h>
#include <signal.h>
#include <sys/time.h>
#include <sys/resource.h>
#endif
```
To this : 
```
#if defined(OS_LINUX) || defined(OS_NETBSD) || defined(OS_DARWIN)
#include <dlfcn.h>
#include <signal.h>
#include <sys/time.h>
#endif
#include <sys/resource.h>
```

It works but it obviously broke everything on other platforms ! Is there something as a OS_ARM define ?

**Comment by martin-frbg** [comment]
There is OS_ANDROID (at least since a11555c) , though I wonder why this issue would not have come up in preparation or testing of that commit ? (But I have no experience with that platform)

**Comment by RYOBG** [comment]
Just got similar issue when compiling on FreeBSD. I had to pull out <signal.h> and <sys/resource.h>.

**Comment by xianyi** [comment]
@RYOBG , sorry. I didn't test it on FreeBSD.

**Comment by RYOBG** [comment]
@xianyi, this is the only build error which I encountered. I suppose the FreeBSD macro can just be added next to the rest. Great work & thank you!
