### ISSUE TITLE
Linking against the math library for Android

### ISSUE THREAD

**Issue by buffer51** [xianyi/OpenBLAS#675]
Hi everyone,

I am wondering how does OpenBLAS rely on the math library. When building for ARMv7 on Android, you can choose to build against the hard math library using a compile flag (`-D_NDK_MATH_NO_SOFTFP=1`) and linking flag (`-lm_hard` instead of `-lm`). If this is not used, then the math library will still be softfp.

I know how to add easily the compile flag in Makefile.arm. Does your build system link against the math library for Android targets, and if so how would I change properly `-lm` to `-lm_hard`?

**Comment by xianyi** [comment]
@buffer51 , I don't think OpenBLAS heavily relies on the cmath library.

We implement the ARM assembly kernels in `hard` ABI. if you compile the rest C codes of OpenBLAS with softfp ABI, there is the ABI conflict bug.

**Comment by buffer51** [comment]
Thanks @xianyi, just checking. The thing is building for Android (with the JNI to put in Apps, not for standalone executable) forces you to use the `-Wl,--no-warn-mismatch` flag, which means such conflicts wouldn't show up.

I checked the output of the whole make step, and the flags I could find in Makefiles, and didn't find any `-lm` for ARMv7, but better safe than sorry!
