### ISSUE TITLE
OpenBLAS make error on Windows 7 x64 with mingw-w64

### ISSUE THREAD

**Issue by ikarth** [xianyi/OpenBLAS#680]
When running ````make```` on my Windows machine, I get this error:
    make[1]: Leaving directory 'F:/Isaac/Dev/nanogenmo2015/OpenBLAS-0.2.15/kernel'
    make[1]: Entering directory 'F:/Isaac/Dev/nanogenmo2015/OpenBLAS-0.2.15/lapack'
    /bin/sh: line 2: c:/Program: No such file or directory
    makefile:10: recipe for target 'libs' failed
    make[1]: *** [libs] Error 1
    make[1]: Leaving directory 'F:/Isaac/Dev/nanogenmo2015/OpenBLAS-0.2.15/lapack'
    makefile:143: recipe for target 'libs' failed
    make: *** [libs] Error 1
https://gist.github.com/ikarth/eca453776ae1780a0e74

As far as I can tell, there aren't any issues with the rest of the system (though that's always a possibility with Windows toolchains, I guess). It seems to be failing on a file path, though I can't work out which makefile or script it might be having issues with. 

I did a web search and found some similar issues, but nothing close enough to my problem that also had a successful solution.

Is there something special that lapack would be invoking that nothing prior would have accessed? gfortran should be installed, though if it's having a problem with the space in "Program Files" I suspect a work-around may be needed. Is there a way to substitute a binary of LAPACK?

**Comment by martin-frbg** [comment]
You can use "make NO_LAPACK=1" or uncomment the equivalent line in Makefile.rule until you have figured out what could be wrong with your installation of gfortran.

**Comment by ikarth** [comment]
../libopenblas_haswellp-r0.2.15.a(ztrtri.obj):ztrtri.c:(.rdata+0x50): undefined reference to `ztrtri_LU_single'
    ../libopenblas_haswellp-r0.2.15.a(ztrtri.obj):ztrtri.c:(.rdata+0x58): undefined reference to `ztrtri_LN_single'
    collect2.exe: error: ld returned 1 exit status
    makefile:85: recipe for target '../libopenblas.dll' failed
    make[1]: *** [../libopenblas.dll] Error 1
    make[1]: Leaving directory 'F:/Isaac/Dev/nanogenmo2015/OpenBLAS-0.2.15/exports'
    makefile:106: recipe for target 'shared' failed
    make: *** [shared] Error 2````
https://gist.github.com/ikarth/4e020d1630ecd38d2782

Well, that gets a lot further. But when it gets to /exports there's a wall of "undefined reference" errors.

**Comment by martin-frbg** [comment]
Did you do a "make clean" before this ? (If not, the linker probably picked up some modules from the failed build - things that would not get built with NO_LAPACK)

**Comment by ikarth** [comment]
Thanks for the feedback; once I had that I was able to track down the actual issue.

An error running "make clean", of all things, lead me to suspect that the problem was entirely because mingw-w64 was installed under "Program Files", which has a space in the path. Uninstalling it and then reinstalling it in a directory that didn't have a space resolved the issue.

I'm not sure why only LAPACK and the final export invoke scripts that fail on spaces with the file path, but it's most likely a mingw-w64 issue.

**Comment by cheyuanxiaozi** [comment]
@ikarth　the same problem is met by me,  do you have solve it ?
