### ISSUE TITLE
Providing Windows DLLs for math.h functions with MinGW DLLs already there

### ISSUE THREAD

**Issue by varosi** [xianyi/OpenBLAS#683]
We have some hard time building "hmatrix" library with OpenBLAS because of missing "atanh" symbol. Is it possible to provide math.h related functions in the DLL that you have built OpenBLAS with?

Related: https://github.com/mikeizbicki/subhask/issues/22

**Comment by xianyi** [comment]
Thank you for the report. I will look at this issue. However, I don't think OpenBLAS uses atanh.

**Comment by martin-frbg** [comment]
Not sure how you build your hmatrix code on windows, but perhaps this helps:
http://stackoverflow.com/questions/15539116/atanh-arc-hyperbolic-tangent-function-missing-in-ms-visual-c

**Comment by varosi** [comment]
Thanks! It's good idea! But the problem is that many other math functions are missing.

**Comment by martin-frbg** [comment]
Boost provides a lot more than atanh, and if you are missing fundamental math functions like sin,cos
that have been in the c/c++ standards for ages it is probably indicative of some more general problem with your build environment. (Missing a linker directive like "-lm" to bind the standard math library perhaps ?)

**Comment by varosi** [comment]
Yes, you're right! There is missing "libm" around with building that. I'm trying to find why Cabal build system cannot find it.
