### ISSUE TITLE
cannot build OpenBLAS-0.2.6 with TARGET=GENERIC

### ISSUE THREAD

**Issue by pescobar** [xianyi/OpenBLAS#685]
Hi

I need to build openblas version 0.2.6 without any cpu optimization so it can run in any intel or amd x86_64 cpu. I tried to compile it with "TARGET=GENERIC" and "TARGET=SSE_GENERIC" but I always get this error

```
sgemm_kernel.o: No such file or directory
```

I have read that this problem is fixed in latest release but I need to use version 0.2.6. Is there any way I can compile a generic version of openblas-0.2.6?

thanks

**Comment by xianyi** [comment]
@pescobar , I think you need to back port some codes to 0.2.6.

**Comment by pescobar** [comment]
Hi @xianyi thanks for your reply

I think I don´t have knowledge enough to do such a modification. Is there any patch available or any documentation about the required commits which need to be backported? 

In case there is no available patch could you recommend me which is the "most generic" target which I can use in version 0.2.6 without requiring code changes?

thanks

**Comment by xianyi** [comment]
Why do you focus on 0.2.6 version?

I think you can use NEHALEM target. `make TARGET=NEHALEM`.

**Comment by pescobar** [comment]
I would like to use 0.2.6 because I am using easybuild to build all the software in my cluster and I have a huge software stack using the toolchain goolf-1.4.10 (https://github.com/hpcugent/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/g/goolf/goolf-1.4.10.eb) which uses openblas-0.2.6. My intention is to rebuild my complete software stack but making it as much portable as possible so I can execute it in any x86_64 cpu from intel or amd.

@xianyi to make openblas as much portable as possible (without taking care about performance) I supposed the right choose was "TARGET=CORE2" which I thought it's the oldest x86_64 target, isn't it? why do you recommend nehalem?

**Comment by carlkl** [comment]
You may use NORTHWOOD on x86:  ```make TARGET=NORTHWOOD``` that uses SSE2 instructions. It's very hard to find non-SSE2 x86 CPUs today. For x86-64 use the PRESCOTT target.
Nehalem needs at least SSE4.1 instructions and is less generic.

**Comment by brada4** [comment]
Best is to link against netlib BLAS (preferably one shipped with your system, libblas.so.3/liblapack.so.3), and then replace/redirect to faster library where actually using it.
