### ISSUE TITLE
Cannot built OpenBLAS 0.2.16 on windows

### ISSUE THREAD

**Issue by tbsflk** [xianyi/OpenBLAS#687]
Hi,

I'm trying to compile OpenBLAS under windows 64bit but it doesn't work. Would be great if someone can check if that's a bug or if I do something wrong.

What I did:
- Installed MinGW and MSYS
- gcc, gfortran an wget are installed
- Downloaded the source code from the github repository
- Ran make BINARY=64 CC=gcc FC=gfortran in a MinGW session

It stops with the following error:
C:\MinGW\bin\ar.exe: strmm_kernel_LN.obj: No such file or directory
make[1]: *** [libs] Error 1
make: *** [libs] Error 1

My machine has an i7-5600U. Without explicitly specifying TARGET, it is built for Haswell, which seems to be correct based on what I understand.

Thanks,
Tobias

**Comment by martin-frbg** [comment]
Any warnings or errors before the one from ar.exe ? Is this the first attempt at compiling, or did you try with other command line options first (and forgot to run "make clean" before trying with BINARY=64 etc ?) Perhaps check closed bugs #680,#681 for ideas.

**Comment by tbsflk** [comment]
Going over the whole error log, I see
- "make: [libs] Error 1 (ignored)" which is ok according to the wiki,
- "unused variable" warnings,
- "passing argument 12 of 'blas_level1_thread' from incompatible pointer typ" ???
- "linker input file unused because linking not done"

Anything suspicious there? If yes, I can post the corresponding part of the log.

I also retried with a "make clean", still the same result. I also checked 680 and 681, but I don't have spaces in my path as in 680. 681 is about make install, I don't even get to that step.

**Comment by xianyi** [comment]
@tbsflk , I just tried compiling OpenBLAS develop branch on Windows haswell. It works fine.

For 64-bit, you need MinGW-w64.

**Comment by bozothegrey** [comment]
Hi, I had the same problem that @tbsflk is experiencing.
Properly installing MinGW-64 fixed it (I had 32bit version before).

**Comment by jakirkham** [comment]
So, is the answer here that 32-bit is unsupported?

**Comment by jeromerobert** [comment]
@jakirkham No. mingw-w64.org  support both 32bit and 64bit. I did not try mingw.org but it should be able to build a 32bit OpenBLAS. If not please open an other bug report, including the build log.

**Comment by jakirkham** [comment]
I see so just always use mingw-w64. Is there some option I need to pass to force it into 32-bit mode when needed?

**Comment by jeromerobert** [comment]
@jakirkham it depends on how it's built, packaged and installed. Either you have two different gcc executable, either you can use the `-m32` flag.

**Comment by jakirkham** [comment]
Alright, thanks. I'll give this a try.

**Comment by HJiaoBME** [comment]
'make TARGET=NEHALEM'
