### ISSUE TITLE
Support for compiling OpenBLAS with MSVC?

### ISSUE THREAD

**Issue by groutr** [xianyi/OpenBLAS#688]
Are there plans to support compiling OpenBLAS with MSVC?

**Comment by xianyi** [comment]
Now, OpenBLAS supports MSVC by cmake. However, it can only compile reference/generic C kernels. The performance is not good.

I hope we can compile assembly kernels by Microsoft LLVM/C2.

**Comment by groutr** [comment]
That is good to hear.  Didn't see the release notes until now.
