### ISSUE TITLE
Unable to build for Jetson TK1

### ISSUE THREAD

**Issue by vidda13** [xianyi/OpenBLAS#689]
Hi, I am trying to build OpenBlas for Jetson TK1 and set the TARGET to CORTEXA57. When I build, I get issues of not recognizing the Target. I tried ARMV8 too.

**Comment by vidda13** [comment]
I get the following error. No rule to make target `../kernel/arm/amax.S', needed by `samax_k.o'.  Stop.

**Comment by martin-frbg** [comment]
From the hardware overview of the Nvidia Jetson kit, shouldn't this be "CORTEXA15" (and implied ARMV7) rather than "A57" ? (Try "make clean; make TARGET=CORTEXA15")

**Comment by vidda13** [comment]
I tried Cortex A15 at first.. But I got memory segmentation faults when I
ran some torch scripts. Even the OpenBlas tests failed.

**Comment by martin-frbg** [comment]
Any details of the test failures ? What other build options did you use (e.g. USE_OPENMP ?)

**Comment by vidda13** [comment]
I used ARCH-arm64 and BINARY=64 as it wasnt able to detect it was a 64 bit architecture when I gave the target option as cortexa57. And when I built it with these options I got gcc failure to detect cortexa57.

**Comment by martin-frbg** [comment]
Might be a silly question, but are you certain that it is the brand-new A57-based TX1 rather than the TK1 ? And which version of gcc (-mtune=cortex-a57 as written in Makefile.arm64 should be supported since 5.0 or so)

**Comment by vidda13** [comment]
Yes.. I did a cat proc/cpuinfo to get the processor information.The gcc
version is 4.8.4. Are there any other options which I can try out other
than TARGET and AARCH?

**Comment by martin-frbg** [comment]
Try changing the "-mtune=cortex-a57" to "-mcpu=cortex-a57" in Makefile.arm64 ? From the gcc release notes, 4.8.4 provided "initial support" for the A57 (the entire AArch64 port apparently was new in that version), while cpu-specific "-mtune" appears only in the gcc-5 "changes" document.

I also see an "#ifdef FORCE_CORTEXA57" in getarch.c that would set the architecture to arm64&armv8, perhaps adding a corresponding "#define FORCE_CORTEXA57" in that file before
a "make clean" and "make" would push things in the right direction IF it is an autodetection problem.

**Comment by vidda13** [comment]
Well i still get the error - make[1]: *** No rule to make target `../kernel/arm/amax.S', needed by `samax_k.o'.  Stop.
make[1]: Leaving directory `/tmp/OpenBLAS/kernel'
The config.h file is below:
#define OS_LINUX        1
#define ARCH_ARM        1
#define C_GCC   1
#define __32BIT__       1
#define PTHREAD_CREATE_FUNC     pthread_create
#define BUNDERSCORE     _
#define NEEDBUNDERSCORE 1
#define CORTEXA57
#define L1_CODE_SIZE 49152
#define L1_CODE_LINESIZE 64
#define L1_CODE_ASSOCIATIVE 3
#define L1_DATA_SIZE 32768
#define L1_DATA_LINESIZE 64
#define L1_DATA_ASSOCIATIVE 2
#define L2_SIZE 2097152
#define L2_LINESIZE 64
#define L2_ASSOCIATIVE 16
#define DTB_DEFAULT_ENTRIES 64
#define DTB_SIZE 4096
#define HAVE_VFPV4
#define HAVE_VFPV3
#define HAVE_VFP
#define HAVE_NEON
#define CORE_CORTEXA57

#define CHAR_CORENAME "CORTEXA57"
#define SLOCAL_BUFFER_SIZE      15360
#define DLOCAL_BUFFER_SIZE      65536
#define CLOCAL_BUFFER_SIZE      131072
#define ZLOCAL_BUFFER_SIZE      65536
#define GEMM_MULTITHREAD_THRESHOLD      4

**Comment by martin-frbg** [comment]
"Still" in what circumstances ? The config.h seems to define a 32bit environment (which would appear to be in accordance with the error message, I would expect it to look for amax.S in kernel/arm64) - did you try to hack the getarch.c (which at least according to my intepretation of the code would force everything to 64bit) ?

**Comment by xianyi** [comment]
I think you need use CORTEXA15 or ARMV7 target.

**Comment by vidda13** [comment]
I tried forcing it to CortexA57

In file included from ../common.h:404:0,
                 from swap.c:40:
../common_arm.h:135:2: error: #error "you must define ARMV5, ARMV6, ARMV7 or ARMV8"
 #error "you must define ARMV5, ARMV6, ARMV7 or ARMV8"
  ^
In file included from ../common.h:404:0,
                 from copy.c:40:
../common_arm.h:135:2: error: #error "you must define ARMV5, ARMV6, ARMV7 or ARMV8"
 #error "you must define ARMV5, ARMV6, ARMV7 or ARMV8"
  ^
In file included from ../common.h:404:0,
                 from axpy.c:40:
../common_arm.h:135:2: error: #error "you must define ARMV5, ARMV6, ARMV7 or ARMV8"
 #error "you must define ARMV5, ARMV6, ARMV7 or ARMV8"
  ^
In file included from ../common.h:404:0,
                 from scal.c:40:
../common_arm.h:135:2: error: #error "you must define ARMV5, ARMV6, ARMV7 or ARMV8"
 #error "you must define ARMV5, ARMV6, ARMV7 or ARMV8"
  ^
make[1]: *** [saxpy.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [scopy.o] Error 1
make[1]: *** [sswap.o] Error 1
make[1]: *** [sscal.o] Error 1
make[1]: Leaving directory `/tmp/OpenBLAS/interface'
make: *** [libs] Error 1

**Comment by vidda13** [comment]
The cpuinfo gives me this information. Processor	: Cortex A57 Processor rev 1 (aarch64)
Also, when I tried to build for cortex A15, the build works fine but the OpenBlas tests due to segmentation fault.

**Comment by xianyi** [comment]
@vidda13 , how about the OS? Is it 64-bit or 32-bit?

**Comment by vidda13** [comment]
It is 64 bit

**Comment by xianyi** [comment]
It is weird.
Could I access your machine remotely?

**Comment by martin-frbg** [comment]
I think if you #define FORCE_CORTEXA57 at the top of getarch.c, this should define ARMV8 etc. automatically - but from comparing to the surrounding entries, maybe it is missing a "-DARMV8" on
the long "#define ARCHCONFIG" entry starting at line 830 in getarch.c ?

**Comment by vidda13** [comment]
@xianyi I am sorry. I am not sure if I can provide access. I could try out options and provide you with the results if it helps debug the issue. Has this been tested on TK1 before just to confirm that I am not missing anything.

**Comment by xianyi** [comment]
I tested OpenBLAS on tk1. However, I think tk1 is ARMv7.

```
Hardware	: jetson-tk1
Revision	: 0000
Serial		: 0177000003450000
Processor	: ARMv7 Processor rev 3 (v7l)
```

**Comment by vidda13** [comment]
Yes, I am sorry I meant to ask if you tested on TX1 the 64 bit architecture with cortexA57 (typo). I tried with TK1 too and it worked fine.,

**Comment by xianyi** [comment]
@vidda13 , the good news is that we get a Nvidia TX1 recently. I think we can set it up this week. Then, I can try to investigate this issue.

**Comment by vidda13** [comment]
That's great.  For now. I managed to build OpenBlas with target set as
cortex a15. Thanks.

**Comment by SaMnCo** [comment]
Hi there, 

I am having the same issues to compile, either directly on a Geekbox (cortex A57) or cross compiling with the linaro toolchain. See http://pastebin.com/u6sLryrF

command issued: make ARCH=arm64 BINARY=64 CROSS_COMPILE=aarch64-linux-gnu-

I edited getarch.c to add -DARMV8 line 830 as explained. Before that, I don't even go that far. 
If I add a TARGET=CORTEXA57, it doesn't even start. With a CORTEXA15 target, it gets exactly as far.

**Comment by ccb98** [comment]
Hi there,

I am having problems in running OpenBLAS in TK1. I can compile and install it fine, but when I run a test case (time_dgemm) it gives me a "Bus Error" when it tries to call the dgemm function. 

I have used make TARGET=ARMV7 and make TARGET=CORTEXA15, and I am getting the same problem in both cases.

Any ideas?

**Comment by caojiaqi** [comment]
Hi, @xianyi , I encounterd the same problem on TX1, I used JetPack 2.0 flashing OS, and the info in "About This Computer" indicates I am running a 32 bit system. I tried the dev branch and various options, TARGET, ARCH..., it didn't work. Any good news about support on TX1? Thank you!

**Comment by xianyi** [comment]
@caojiaqi , you can try the latest develop branch. It detected ARMV8 32-bit mode by using ARMV7 kernels.
