### ISSUE TITLE
Lapack test errors

### ISSUE THREAD

**Issue by groutr** [xianyi/OpenBLAS#692]
Building openblas v0.2.15 on my Centos5 32bit machine with gcc/gfortran 4.4 results in a number of precision errors.  This only happens on my 32bit machine.

```
            -->   LAPACK TESTING SUMMARY  <--
SUMMARY                 nb test run     numerical error     other error
================    =========== =================   ================
REAL                1108097     25  (0.002%)    0   (0.000%)
DOUBLE PRECISION    1109435     19  (0.002%)    0   (0.000%)
COMPLEX             580690      62  (0.011%)    0   (0.000%)
COMPLEX16           581502      65  (0.011%)    0   (0.000%)

--> ALL PRECISIONS  3379724     171 (0.005%)    0   (0.000%)
```

The tests that fail are the Nonsymmetric Generalized Eigenvalue Problem for each type.

**Comment by xianyi** [comment]
@groutr , which CPU did you use? I didn't test 32bit totally :(

**Comment by groutr** [comment]
The CPU itself is a 64bit CPU, but it is running a 32bit CentOS install.  The CPU is a Intel(R) Xeon(R) CPU E5-2620 v2.  The test suite passes on my 64bit install with the same processor.

**Comment by xianyi** [comment]
For 32-bit, we used old Intel Penryn kernels from GotoBLAS2.  They may exist some bugs.

**Comment by martin-frbg** [comment]
five years later, only a single failure (in one of the SVD tests, for one particular random seed value) remains - and interestingly,
the failure carries over to a pure C  `TARGET=GENERIC` build (so may actually be related to some instability in gcc or the test itself)
```
                        -->   LAPACK TESTING SUMMARY  <--
SUMMARY                 nb test run     numerical error         other error  
================        ===========     =================       ================  
REAL                    1308195         0       (0.000%)        0       (0.000%)
DOUBLE PRECISION        1298747         1       (0.000%)        0       (0.000%)
COMPLEX                 768366          0       (0.000%)        0       (0.000%)
COMPLEX16               769178          0       (0.000%)        0       (0.000%)

--> ALL PRECISIONS      4144486         1       (0.000%)        0       (0.000%)

```
