### ISSUE TITLE
ELAPS experiment and benchmarking

### ISSUE THREAD

**Issue by bhack** [xianyi/OpenBLAS#693]
What do you think of [elaps](http://hpac.rwth-aachen.de/~peise/elaps/)?

**Comment by martin-frbg** [comment]
Seems to be a framework for performance testing of BLAS/LAPACK implementations, could you provide some background or own opinion of what advantages it would offer over the benchmarks used so far?

**Comment by bhack** [comment]
http://arxiv.org/abs/1504.08035

**Comment by martin-frbg** [comment]
Thank you. This does look like it would be a valuable tool in the right hands (though not mine probably). As an aside I assume that xianyi will be quite familiar with the libflame code that was used in their comparison demo run.

**Comment by elmar-peise** [comment]
ELAPS is indeed a framework or experimentation with dense linear algebra kernels with BLAS/LAPACK like interfaces.  Regarding OpenBLAS, I imagine ELAPS might come in handy when interactively testing and optimizing the kernels and various blocking factors.  On the other hand, OpenBLAS's existing benchmarks serve their purpose well and introducing ELAPS into the project only to replace these static benchmarks would be overkill.

Do you have a specific problem or task in mind concerning ELAPS?

**Comment by bhack** [comment]
Probably It can have a role in kernel optimization and testing. @xianyi What do you think?

**Comment by xianyi** [comment]
@bhack , ELAPS is a good tool on desktop. However, I usually develop OpenBLAS on a server by ssh. Therefore, I prefer cmd line tools on server. I uses OpenBLAS/benchmark and https://github.com/xianyi/BLAS-Tester

**Comment by bhack** [comment]
I don't that it is embedded with the GUI. I read that:
>Experiments are designed either through Python scripts or a specialized GUI, and run on the whole spectrum of architectures, ranging from laptops to clusters, accelerators, and supercomputers.
