### ISSUE TITLE
Support for F16C

### ISSUE THREAD

**Issue by hagrid-the-developer** [xianyi/OpenBLAS#694]
Recent Intel CPUs include support for F16C. It isn't possible to do direct math with it, but it is possible to convert between half-precision floats and single-precision floats. It still can make certain calculations faster, because only half of the memory is used, what can increase cache usage. Are there any plans for adding of F16C support to OpenBlas?

**Comment by xianyi** [comment]
We didn't have the plan for F16C yet.

**Comment by brada4** [comment]
F16C is meant to convert half-precision float to normal float to apply FMA/AVX instructions (which completely lack for half-precision floats)
What would be the purpose of use of such instruction - adding never-seen half-precision BLAS API?

**Comment by hagrid-the-developer** [comment]
Yes, I am talking about adding half-precision API here. In particular we use sgemm for calculations related to neural networks and half-precision should help us because more data would fit into caches.

**Comment by brada4** [comment]
As mentioned there are no vector instructions for 16bit floats, so F16C comes to rescue that you can quickly convert them to single precision, process using general purpose math library and convert back, tripling space used where you intended to save anything.

**Comment by xianyi** [comment]
@brada4 , I think @hagrid-the-developer suggests using F16C to convert F16 to F32 at YMM registers. Then, use the same AVX single floating point instructions.

What's the performance benefit by F16 instead of F32? For sgemm, the performance can reach 80-90% of peak performance.

**Comment by brada4** [comment]
Fallback in absence of F16C (Like Sandy Bridge CPU) is a bit heavy.

**Comment by xianyi** [comment]
@brada4 , only support on haswell :)

**Comment by brada4** [comment]
Or divorce between sandy and ivy bridge...

**Comment by hagrid-the-developer** [comment]
How common is reaching 80% of peak performance, especially for big matrices (MB or tens of MB)? For >80% of peak perf, F16C really cannot help too much.

**Comment by hagrid-the-developer** [comment]
It seems that F16C rally doesn't help too much. Conversions between F32 and F16C use CPU ports 1, 5 and even 0 (on skylake) so they would compete with FMA and AVX instructions for ports 0 and 1. I am closing this issue for now.
