### ISSUE TITLE
Error while building on Windows with lapack 3.6.0

### ISSUE THREAD

**Issue by tuannhtn** [xianyi/OpenBLAS#699]
Hello,
It is a good news when OpenBLAS updates to lapack 3.6.0. But I encoutered the following error when building it with GCC and msys 1.0 on Windows 7 64 bit:
make[3]: execvp: ar: Bad file number.
This error was not appeared with lapack 3.4.2.
Could some one suggest a solution for this issue? Thanks in advance

**Comment by martin-frbg** [comment]
A bit of googling turned up your very own #325 - probably the same changes to the lapacke Makefile need to be made get past the limitation on the number of object files the mingw ar.exe can handle - if this is still a problem for recent versions of mingw.

**Comment by tico-tico** [comment]
MSYS2 x64 + x86_64-w64-mingw32 report  **make[3]: execvp: ar: Argument list too long** error. I guess it's the same issue.

**Comment by tuannhtn** [comment]
Thanks for your suggestions. I did the trick from #325 but it did not help.

**Comment by martin-frbg** [comment]
Possibly the addition of other new routines to lapack now causes the same problem in other subdirectories, not just in lapacke. Can you tell from the error messages where it was in the build process that the error occured ? (I.e. what were the message lines immediately before the "make [3]: execvp: ar: Bad file number.")

**Comment by tico-tico** [comment]
This works for me:
```patch
diff --git a/lapack-netlib/LAPACKE/src/Makefile b/lapack-netlib/LAPACKE/src/Makefile
index 642b875..636ca35 100644
--- a/lapack-netlib/LAPACKE/src/Makefile
+++ b/lapack-netlib/LAPACKE/src/Makefile
@@ -34,7 +34,7 @@
 #
 include ../../make.inc
 
-SRC_OBJ = \
+SRC_OBJA = \
 lapacke_cbbcsd.o \
 lapacke_cbbcsd_work.o \
 lapacke_cbdsqr.o \
@@ -996,7 +996,9 @@ lapacke_dsytri2.o \
 lapacke_dsytri2_work.o \
 lapacke_dsytri2x.o \
 lapacke_dsytri2x_work.o \
-lapacke_dsytri_work.o \
+lapacke_dsytri_work.o
+
+SRC_OBJB = \
 lapacke_dsytrs.o \
 lapacke_dsytrs_rook.o \
 lapacke_dsytrs2.o \
@@ -2189,7 +2191,8 @@ lapacke_slagsy_work.o \
 lapacke_zlagsy.o \
 lapacke_zlagsy_work.o
 
-ALLOBJ = $(SRC_OBJ) $(MATGEN_OBJ) 
+ALLOBJA = $(SRC_OBJA)
+ALLOBJB = $(SRC_OBJB) $(MATGEN_OBJ)
 
 ifdef USEXBLAS
 ALLXOBJ = $(SXLASRC) $(DXLASRC) $(CXLASRC) $(ZXLASRC)
@@ -2203,8 +2206,9 @@ OBJ_FILES := $(C_FILES:.o=.o)
 
 all: ../../$(LAPACKELIB)
 
-../../$(LAPACKELIB): $(ALLOBJ) $(ALLXOBJ) $(DEPRECATED)
-	$(ARCH) $(ARCHFLAGS) ../../$(LAPACKELIB) $(ALLOBJ) $(ALLXOBJ) $(DEPRECATED)
+../../$(LAPACKELIB): $(ALLOBJA) $(ALLOBJB) $(ALLXOBJ) $(DEPRECATED)
+	$(ARCH) $(ARCHFLAGS) ../../$(LAPACKELIB) $(ALLOBJA)
+	$(ARCH) $(ARCHFLAGS) ../../$(LAPACKELIB) $(ALLOBJB) $(ALLXOBJ) $(DEPRECATED)
 	$(RANLIB) ../../$(LAPACKELIB)
 
 .c.o: 
```

**Comment by xianyi** [comment]
@tico-tico , I merged your patch at develop branch. Thank you.
