### ISSUE TITLE
Compiling on Solaris failed - memory.c: error: constructor priorities are not supported

### ISSUE THREAD

**Issue by wuhwyy** [xianyi/OpenBLAS#700]
Hi Xianyi,

I am trying to compiling the latest version 0.2.15 and the develop version on Sun Solaris using gcc 4.7.3.

However, it stop at
...
memory.c:1342:1: error: constructor priorities are not supported
memory.c:1397:1: error: destructor priorities are not supported
...

I saw a similar problem with Mac. Do you have any idea how to fix it?

Thank
Archy

**Comment by martin-frbg** [comment]
Looks like this is probably caused by the change in 11ac4665
that added a priority number to the definitions of "constructor" and "destructor"
in driver/others/memory.c around line 150. Try changing the "elif" line to read
#elif ( defined(OS_DARWIN) || defined(OS_SUNOS) ) && defined(C_GCC)
(not sure if SUNOS is correct, but I do not see OS_SOLARIS defined) or just delete
the "(101)" from the two lines in the "else" block for now.

**Comment by susilehtola** [comment]
I get a similar message with GCC 4.1.2 on Red Hat Enterprise 5

memory.c:1341: error: wrong number of arguments specified for 'constructor' attribute
memory.c:1384: error: wrong number of arguments specified for 'destructor' attribute
make[1]: *** [memory.o] Error 1

Presumably this is the same issue?

**Comment by martin-frbg** [comment]
Yes, constructor priorities were not available in GCC 4.1 (which must be about ten years old) so this #elif would need a GCC version check a la  http://stackoverflow.com/questions/6580947/error-wrong-number-of-arguments-specified-for-constructor-attribute as well to support such platforms. (Wonder if you will run into further compatibility issues in the code if you remove the priority argument to get past this one)

**Comment by susilehtola** [comment]
Compiled fine by removing the CONSTRUCTOR and DESTRUCTOR statement in memory.c.

**Comment by martin-frbg** [comment]
The (101) argument, not the entire statement surely ?
Could you check if changing the "elif" condition as suggested above works as well (which would avoid having to edit this file for each and every new version of OpenBLAS) ?

**Comment by lotheac** [comment]
I ran into this and several other issues building on OmniOS. The suggested fix does work, I have a PR coming with it and several others...

**Comment by susilehtola** [comment]
martin-frbg: the patch I used is available at
http://pkgs.fedoraproject.org/cgit/rpms/openblas.git/tree/openblas-0.2.15-constructor.patch

**Comment by lotheac** [comment]
Oh yeah, I forgot to mention: my failure was on gcc 4.8.1 with the same "constructor priorities are not supported" error. So I'm not sure just checking the version is enough.

**Comment by martin-frbg** [comment]
Guess both checks could coexist, i.e. adding "||defined(SUN_OS) " to the OS_DARWIN line as above to take care of Solaris/Illumos where apparently no version of the gcc port supports constructor priorities, and susilehtola's patch to add a version guard for gcc on all other platforms in the "else" branch ?
(And @lotheac, I suspect you could borrow the "hostos" determination line from the top of the c_check script to build a condition for the linker argument mangling in f_check that you left out of your pull request)

**Comment by lotheac** [comment]
On Fri, Jan 22 2016 13:14:05 -0800, Martin Kroeker wrote:
> (And @lotheac, I suspect you could borrow the "hostos" determination line from the top of the c_check script to build a condition for the linker argument mangling in f_check that you left out of your pull request)

Maybe, but I'm happy with it now since it builds. Might revisit later.

-- 
Lauri Tirkkonen | lotheac @ IRCnet

**Comment by martin-frbg** [comment]
Fully understand, it just would be a pity if this ended up like #463, with the requirements basically known but nobody with the "relatively uncommon" platform in question around to finalise and test the build system patch.
