### ISSUE TITLE
AMD A10-5750M piledriver CPU not detected by 0.2.15

### ISSUE THREAD

**Issue by brada4** [xianyi/OpenBLAS#701]
It looks like my laptop CPU is not detected correctly with 0.2.15
It features here:
https://en.wikipedia.org/wiki/Piledriver_%28microarchitecture%29#Mobile
Short test shows OPENBLAS_CORETYPE=Piledriver doubles matrix multiplication speed.

First quarter of /proc/cpuinfo:
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 21
model           : 19
model name      : AMD A10-5750M APU with Radeon(tm) HD Graphics
stepping        : 1
microcode       : 0x6001119
cpu MHz         : 1400.000
cache size      : 2048 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 2
apicid          : 16
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt lwp fma4 tce nodeid_msr tbm topoext perfctr_core perfctr_nb arat cpb hw_pstate npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold bmi1
bogomips        : 4990.28
TLB size        : 1536 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management: ts ttp tm 100mhzsteps hwpstate cpb eff_freq_ro

**Comment by martin-frbg** [comment]
So what type does it autodetect instead ?

**Comment by brada4** [comment]
? none ? 
$ make
Makefile:133: *** OpenBLAS: Detecting CPU failed. Please set TARGET explicitly, e.g. make TARGET=your_cpu_target. Please read README for the detail..  Stop.

**Comment by brada4** [comment]
openblas_get_corename says it is Prescott

**Comment by xianyi** [comment]
Please try develop branch. I already fixed it a month ago.

**Comment by brada4** [comment]
Perfect. It works!!!
...
 OpenBLAS build complete. (BLAS CBLAS LAPACK LAPACKE)
  OS               ... Linux             
  Architecture     ... x86_64               
  BINARY           ... 64bit                 
  C compiler       ... GCC  (command line : gcc)
  Fortran compiler ... GFORTRAN  (command line : gfortran)
  Library Name     ... libopenblas_piledriverp-r0.2.16.dev.a (Multi threaded; Max num-threads is 4)
