### ISSUE TITLE
xerbla functions appear multiple times

### ISSUE THREAD

**Issue by tuannhtn** [xianyi/OpenBLAS#702]
When I create .lib file by VS's lib command: lib /def:libopenblas.def /MACHINE:X64, 3 warnings appear:
warning LNK4197: export 'xerbla' specified multiple times; using first specification
warning LNK4197: export 'xerbla_' specified multiple times; using first specification
warning LNK4197: export 'XERBLA' specified multiple times; using first specification
I took a look at the file libopenblas.def and noticed that there were 3 appearances of each function and wonder whether they are errors or not?

**Comment by xianyi** [comment]
@tuannhtn , it looks like a bug.
