### ISSUE TITLE
Incremental rebuilds fail with undefined references in linktest.c

### ISSUE THREAD

**Issue by tkelman** [xianyi/OpenBLAS#705]
Reproduce (on develop at f88ee184095cfc4923a310735be6d77bb4a4c1c1) via:

``` sh
make -j16 all > make1.log 2>&1
rm libopenblas*
make all > make2.log 2>&1
```

make1.log: https://gist.github.com/8bec961d9cd617871eb7
make2.log (with undefined reference errors starting at line 1180): https://gist.github.com/d6bfe55809b13c484b97

Something in the makefiles can probably be adjusted to fix this, but I'm not sure where. Any ideas? We hit this in Julia source builds whenever we upgrade our version of OpenBLAS, it would be nice to avoid having to clean and rebuild from scratch since we're using DYNAMIC_ARCH and it takes a while to build.

**Comment by brada4** [comment]
1st run makes archive
-ar -ru ../../libopenblas_haswellp-r0.2.16.dev.a spotrf2.o ... ../INSTALL/slamch.o  
-ranlib ../../libopenblas_haswellp-r0.2.16.dev.a
2nd run does not
+make[2]: Nothing to be done for `all'.

Does it help to delete one .o file to help make to build archive again?

**Comment by tkelman** [comment]
Or maybe better to build each subfolder to a separate .a name then combine them at the end. If the subfolder sources have not changed, then that subfolder .a command thinks it doesn't need to rerun, but it does if it's appending to a single file. If the big .a depended on the subfolder .a files then it would hopefully rebuild properly if any of the sub .a files change, or stay in place if they don't.
