### ISSUE TITLE
Remove obsoleted functions

### ISSUE THREAD

**Issue by susilehtola** [xianyi/OpenBLAS#707]
Referring to Fedora bug
https://bugzilla.redhat.com/show_bug.cgi?id=1287405

OpenBLAS uses some LAPACK(E) functions that have been deprecated in LAPACK 3.6.0.

**Comment by xianyi** [comment]
@susilehtola , could you try develop branch? We just upgraded to LAPACK 3.6.0

**Comment by susilehtola** [comment]
Okay, so you're already aware of this.

Well, the thing is currently the Fedora packages compile against the system version of lapack, which might be problematic if the upcoming version of OpenBLAS assumes LAPACK 3.6.0 which has symbols that aren't defined in earlier versions of LAPACK.

The Fedora guidelines have changed since I introduced the OpenBLAS package, so now I could just stop using the system version and use the version of LAPACK you bundle in the package. Any thoughts?

**Comment by martin-frbg** [comment]
Just a thought from another user, but in recent times there have been more frequent releases of OpenBLAS than of LAPACK, and accordingly also patches and/or workarounds for LAPACK bugs appeared in OpenBLAS releases much earlier.

**Comment by tkelman** [comment]
I think most downstream consumers of BLAS and LAPACK should have learned how to handle the configuration where blas and lapack are in the same library by now, considering MKL does it that way. The only reason to leave them separate is to allow switching blas implementations via update-alternatives symlinks while leaving in place netlib lapack, but I don't think there's all that much utility in that functionality right now. Maybe if there were a wider array of open-source optimized blas implementations packaged in Linux distributions, but considering threading and other non-standard API's always differ from one optimized implementation to another, a lot of libraries these days do things more specifically targeting one implementation or another.

**Comment by carlkl** [comment]
this pops up with scipy compiled against OpenBLAS https://github.com/mingwpy/mingwpy-wheel-builder/issues/2#issuecomment-181597823 
The symbol `cgegv` is missing in OpenBLAS binaries compiled with Lapack 3.6.0

**Comment by martin-frbg** [comment]
That seems to be the opposite of the original issue, and wouldn't the same happen to the scipy build if you tried to link against stock netlib LAPACK 3.6 (or ATLAS built against that) ? (It seems that the netlib-lapack makefiles already support an option BUILD_DEPRECATED, perhaps this needs to be exposed e.g. in Makefile.rule to make it more visible ?)

**Comment by martin-frbg** [comment]
Scipy discussion of this appears to happen in https://github.com/scipy/scipy/issues/5266

**Comment by martin-frbg** [comment]
Confirmed just now that "make BUILD_DEPRECATED=1" already does the trick.

**Comment by carlkl** [comment]
That's true, but the deprecated symbols has to be incuded in `export/gensymbol` as well.

**Comment by martin-frbg** [comment]
Yeah sorry, seems I am still too new to this to notice all the workings. From my reading of the files involved, the Makefile in export just passes a stream of ones and zeros for the various options as arguments to gensymbol. This list would need to be modified to accomodate BUILD_DEPRECATED,
then a wordlist of lapack_deprecated_objs function names could be conditionally appended to underscore_objs (around where lapackobjs2 get included).

**Comment by xianyi** [comment]
I am working on this issue.

**Comment by carlkl** [comment]
It works for me now with BUILD_LAPACK_DEPRECATED=1
