### ISSUE TITLE
Error using 0.2.15 in Visual Studio

### ISSUE THREAD

**Issue by kjbartel** [xianyi/OpenBLAS#708]
The changes to openblas_config.h in f874465bb81d10e7cdb88a10cff7d62df3fe370c (and further changed in a9d7eee0dcfdc9585806e9f8da65f20587ee3494 for C++) causes compile errors in Visual Studio when building C code. Specifically, even though the C99 complex functions are supported in Visual Studio 2013, the `double _Complex` syntax [is not supported](https://connect.microsoft.com/VisualStudio/feedback/details/1551173/msvc-2015-complex-hs-complex-i-macro-does-not-conform-to-the-standard). This gives an error:  
> error C2061: syntax error : identifier 'openblas_complex_double'

If it were instead changed from  
    `typedef double _Complex openblas_complex_double;`  
to  
    `typedef _Dcomplex openblas_complex_double`  
then there is no problem for both C and C++. Or just remove the line altogether and use the `OPENBLAS_COMPLEX_STRUCT` as it did before.

**Comment by xianyi** [comment]
Thank you. I fixed it in 0.2.16.rc1.
