### ISSUE TITLE
ARMv7 build failure

### ISSUE THREAD

**Issue by susilehtola** [xianyi/OpenBLAS#709]
I'm trying to extend the Fedora packages to the armv7hl architecture, but the build fails with

gcc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -march=armv7-a -mfpu=vfpv3-d16  -mfloat-abi=hard -DMAX_STACK_ALLOC=2048 -Wall -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DNO_WARMUP -DMAX_CPU_NUMBER=128 -marm -mfpu=vfpv3  -mfloat-abi=hard -march=armv7-a -DASMNAME=dynamic -DASMFNAME=dynamic_ -DNAME=dynamic_ -DCNAME=dynamic -DCHAR_NAME=\"dynamic_\" -DCHAR_CNAME=\"dynamic\" -DNO_AFFINITY -I../.. -c dynamic.c -o dynamic.o
dynamic.c: In function 'support_avx':
dynamic.c:107:3: warning: implicit declaration of function 'cpuid' [-Wimplicit-function-declaration]
   cpuid(1, &eax, &ebx, &ecx, &edx);
   ^
dynamic.c:97:3: error: impossible constraint in 'asm'
   __asm__ __volatile__
   ^
Makefile:83: recipe for target 'dynamic.o' failed
make[1]: Leaving directory '/builddir/build/BUILD/openblas-0.2.15/serial/driver/others'
make[1]: *** [dynamic.o] Error 1
Makefile:139: recipe for target 'libs' failed
make: *** [libs] Error 1

**Comment by susilehtola** [comment]
Full build log at https://kojipkgs.fedoraproject.org//work/tasks/5837/12055837/build.log

**Comment by brada4** [comment]
no dynamic arch on arm (asm is i386 btw)

**Comment by xianyi** [comment]
@susilehtola , we don't support dynamic arch on ARM.

**Comment by susilehtola** [comment]
Ah, OK.

I guess the same situation is on ppc64le?

**Comment by brada4** [comment]
Yes

**Comment by susilehtola** [comment]
Packages built for armv7 and ppc64le.
