### ISSUE TITLE
OpenBLAS(0.2.15) build for android get the wrong answer

### ISSUE THREAD

**Issue by fhowen** [xianyi/OpenBLAS#710]
what I have:
XiaoMIi note : CPU:QUALCOMM 801

I want to use your blas on my phone, so I follow the instructions 
make HOSTCC=gcc CC=arm-linux-androideabi-gcc NO_LAPACK=1 TARGET=ARMV7

then I got the .a file.

I also use

TARGET_CFLAGS += -mhard-float -D_NDK_MATH_NO_SOFTFP=1
TARGET_LDFLAGS += -Wl,--no-warn-mismatch -lm_hard

in my makefile of my code . everything goes well and I got my program binary file,But on the mobile phone the result of cblas_sgemm is always wrong.
I think I might have made some mistakes in the compile progress,but I don't know where.
can you help me?

**Comment by brada4** [comment]
Can you capture small inputs and output and re-check them on host computer (maybe even against netlib blas)? i.e make a very reduced case where it is wrong.

**Comment by xianyi** [comment]
What's the input?

**Comment by fhowen** [comment]
I use A=[1,2,3,4],B=[2,1,1,2],so the C should be C=[4,5,10,11].(the elements are float type)
I use OpenBLAS on my computer ,and the result is right.
but when I run it on my phone ,the output is:
9.65372e-309 , 8.69594e-311 , 8.69594e-311 , 8.69594e-311(always this result)

**Comment by fhowen** [comment]
I am using MXNET , and it need the OpenBLAS.
here is my makefile for my program:

https://github.com/qianglan/MXNetForward/blob/master/Makefile
(for now I am using library here  instead,,it works.
http://sourceforge.net/projects/openblas/files/v0.2.8-arm/openblas-v0.2.8-android-rc1.tar.gz/download
and when I compile the OpenBLAS myself,I will uncommit the flags (like -mhard-float etc ) )

**Comment by xianyi** [comment]
@fhowen , OpenBLAS only support hard float abi for ARMV7. Therefore, it need `-mhard-float`.
