### ISSUE TITLE
Incorrect size check in Dormbr

### ISSUE THREAD

**Issue by btracey** [xianyi/OpenBLAS#712]
The size of a changes from nq x k to k x nq depending on the value of vect. lapacke_dormbr_work.c does not take this into account.

**Comment by btracey** [comment]
Netlib issue created http://icl.cs.utk.edu/lapack-forum/viewtopic.php?f=13&t=4863

**Comment by martin-frbg** [comment]
Closing as btracey's fix was accepted into netlib on 9 Dec 2015 as well and OpenBLAS has recently been resynced to 3.6.1 so there is no discrepancy between the release trees anymore
