### ISSUE TITLE
Uninitialized variable in dscal.c

### ISSUE THREAD

**Issue by brada4** [xianyi/OpenBLAS#714]
While it is likely to pass single test, it certainly will pick some random garbage from stack in long run.
Unchanged between 0.2.15 and current version.
clang -Wall looks more explanatory than gcc:

../kernel/x86_64/dscal.c:140:16: warning: variable 'x1' is uninitialized when used here [-Wuninitialized]
          "r" (x1),     // 2
               ^~
../kernel/x86_64/dscal.c:90:11: note: initialize the variable 'x1' to silence this warning
        FLOAT *x1;
                 ^
                  = NULL

**Comment by wernsaar** [comment]
x1 is initialized inside the assembler code by the instruction:

leaq           (%1,%4,4), %2

To avoid the warnings, please change:

FLOAT *x1;

to

FLOAT *x1=NULL;

**Comment by brada4** [comment]
Yes, warning is useless. But not having it saves reading 5 lines of assembly...
