### ISSUE TITLE
installation on ubuntu 

### ISSUE THREAD

**Issue by javedaliasdf** [xianyi/OpenBLAS#715]
i ahve been trying to install openblas on ubuntu 64 bit version but have been unable to do so. I have also tried using gfortran but it throws error 
ar: `u' modifier ignored since `D' is the default (see `U')

and these following errors:

/usr/bin/ld: cannot find /usr/local/lib: File format not recognized
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
Makefile:121: recipe for target 'sblat1' failed
make[1]: *** [sblat1] Error 1
make[1]: *** Waiting for unfinished jobs....
Makefile:130: recipe for target 'cblat1' failed
make[1]: *** [cblat1] Error 1
Makefile:124: recipe for target 'dblat1' failed
make[1]: *** [dblat1] Error 1
Makefile:133: recipe for target 'zblat1' failed
make[1]: *** [zblat1] Error 1
make[1]: Leaving directory '/home/javed/OpenBLAS/test'
Makefile:117: recipe for target 'tests' failed
make: *** [tests] Error 2
Please help.

**Comment by martin-frbg** [comment]
The message from "ar" is probably harmless, I suspect the actual problem occured earlier in the log.
Please post the earliest errors or warnings you see, and tell us more about your system and which version of OpenBLAS you are trying to build.

**Comment by brada4** [comment]
You have some older openblas shipped with ubuntu that you can use.
try to run (as non-root) make clean ; make 
and then repeat make install (as root)
