### ISSUE TITLE
catastrophic error: unknown register name %1 in asm statement 

### ISSUE THREAD

**Issue by akakcolin** [xianyi/OpenBLAS#718]
I got an error :

../kernel/x86_64/cscal_microk_haswell-2.c(233): catastrophic error: unknown register name %1 in asm statement 
 
compilation aborted for ../kernel/x86_64/cscal.c (code 4) 
make[1]: *** [cscal_k.o] Error 4 
../kernel/x86_64/zscal_microk_haswell-2.c(309): catastrophic error: unknown register name %1 in asm statement 
 
compilation aborted for ../kernel/x86_64/zscal.c (code 4) 
make[1]: *** [zscal_k.o] Error 4 
make: *** [libs] Error 1

**Comment by brada4** [comment]
Which linux, which compiler? Compiler flags?

**Comment by martin-frbg** [comment]
Could be that your version of binutils (assembler and related files) is too old

**Comment by akakcolin** [comment]
The linux system is  Centos
>Distributor ID:	CentOS
>Description:	CentOS Linux release 7.1.1503 (Core) 
>Release:	7.1.1503
>Codename:	Core
Linux hsw-01 3.10.0-229.20.1.el7.x86_64

The Package binutils-2.23.52.0.1-55.el7.x86_64  is already installed and is the latest version

Using gcc/gfortran can build  successully.
Using icc/ifort   cannot build and  with the same error 
 
using "make BINARY=64 CC=icc FC=ifort"

**Comment by martin-frbg** [comment]
Hmm. #493 was solved by updating to binutils 2.25 ? (The error message there was different -
but the only reference to your "unknown register name %<number>" I can find was relevant for an icc version from ten years ago that did not yet recognize the gcc-style register naming.).
If you are sharing the same source tree between different machines or different compilers, be sure to do a "make clean" before the "make"

**Comment by brada4** [comment]
It means ICC does not support AVX2 asm in OpenBLAS. You can link gcc-built libraries using icc.

**Comment by xianyi** [comment]
@akakcolin ， could you try gcc? `make CC=gcc FC=ifort`

**Comment by akakcolin** [comment]
@xiaoyi, thx

OpenBLAS build complete. (BLAS CBLAS LAPACK LAPACKE)

  OS               ... Linux             
  Architecture     ... x86_64               
  BINARY           ... 64bit                 
  C compiler       ... GCC  (command line : gcc)
  Fortran compiler ... INTEL  (command line : ifort)
  Library Name     ... libopenblas_haswellp-r0.2.15.a (Multi threaded; Max num-threads is 56)
