### ISSUE TITLE
Error install on Ubuntu 14.04

### ISSUE THREAD

**Issue by anoidgit** [xianyi/OpenBLAS#719]
I'm trying to install torch7 which need install OpenBLAS,but some errors happened while make.
I downloaded the latest stable version and try to build it,reports that:
ar: strmm_kernel_LN.o: 没有那个文件或目录(means Can not find that file or directory)
make[1]: *** [libs] 错误 1
make[1]:正在离开目录 `/home/ano/下载/xianyi-OpenBLAS-53e849f/kernel'
make: *** [libs] 错误 1

**Comment by anoidgit** [comment]
gcc -O2 -DMAX_STACK_ALLOC=2048 -fopenmp -Wall -m32 -DF_INTERFACE_GFORT -fPIC -DNO_AVX -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME=dtrmm_kernel_RN -DASMFNAME=dtrmm_kernel_RN_ -DNAME=dtrmm_kernel_RN_ -DCNAME=dtrmm_kernel_RN -DCHAR_NAME=\"dtrmm_kernel_RN_\" -DCHAR_CNAME=\"dtrmm_kernel_RN\" -DNO_AFFINITY -I.. -DDOUBLE  -UCOMPLEX -c -DTRMMKERNEL -DDOUBLE -UCOMPLEX -ULEFT -UTRANSA ../kernel/x86/ -o dtrmm_kernel_RN.o
gcc: warning: ../kernel/x86/: linker input file unused because linking not done
gcc -O2 -DMAX_STACK_ALLOC=2048 -fopenmp -Wall -m32 -DF_INTERFACE_GFORT -fPIC -DNO_AVX -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME=dtrmm_kernel_RT -DASMFNAME=dtrmm_kernel_RT_ -DNAME=dtrmm_kernel_RT_ -DCNAME=dtrmm_kernel_RT -DCHAR_NAME=\"dtrmm_kernel_RT_\" -DCHAR_CNAME=\"dtrmm_kernel_RT\" -DNO_AFFINITY -I.. -DDOUBLE  -UCOMPLEX -c -DTRMMKERNEL -DDOUBLE -UCOMPLEX -ULEFT -DTRANSA ../kernel/x86/ -o dtrmm_kernel_RT.o
gcc: warning: ../kernel/x86/: linker input file unused because linking not done
gcc: warning: ../kernel/x86/: linker input file unused because linking not done
gcc -O2 -DMAX_STACK_ALLOC=2048 -fopenmp -Wall -m32 -DF_INTERFACE_GFORT -fPIC -DNO_AVX -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME=ctrmm_kernel_LN -DASMFNAME=ctrmm_kernel_LN_ -DNAME=ctrmm_kernel_LN_ -DCNAME=ctrmm_kernel_LN -DCHAR_NAME=\"ctrmm_kernel_LN_\" -DCHAR_CNAME=\"ctrmm_kernel_LN\" -DNO_AFFINITY -I.. -UDOUBLE  -DCOMPLEX -c -DTRMMKERNEL -UDOUBLE -DCOMPLEX -DLEFT -UTRANSA -UCONJ -DNN ../kernel/x86/ -o ctrmm_kernel_LN.o
gcc -O2 -DMAX_STACK_ALLOC=2048 -fopenmp -Wall -m32 -DF_INTERFACE_GFORT -fPIC -DNO_AVX -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME=ctrmm_kernel_LT -DASMFNAME=ctrmm_kernel_LT_ -DNAME=ctrmm_kernel_LT_ -DCNAME=ctrmm_kernel_LT -DCHAR_NAME=\"ctrmm_kernel_LT_\" -DCHAR_CNAME=\"ctrmm_kernel_LT\" -DNO_AFFINITY -I.. -UDOUBLE  -DCOMPLEX -c -DTRMMKERNEL -UDOUBLE -DCOMPLEX -DLEFT -DTRANSA -UCONJ -DNN ../kernel/x86/ -o ctrmm_kernel_LT.o
gcc -O2 -DMAX_STACK_ALLOC=2048 -fopenmp -Wall -m32 -DF_INTERFACE_GFORT -fPIC -DNO_AVX -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME=ctrmm_kernel_LR -DASMFNAME=ctrmm_kernel_LR_ -DNAME=ctrmm_kernel_LR_ -DCNAME=ctrmm_kernel_LR -DCHAR_NAME=\"ctrmm_kernel_LR_\" -DCHAR_CNAME=\"ctrmm_kernel_LR\" -DNO_AFFINITY -I.. -UDOUBLE  -DCOMPLEX -c -DTRMMKERNEL -UDOUBLE -DCOMPLEX -DLEFT -UTRANSA -DCONJ -DCN ../kernel/x86/ -o ctrmm_kernel_LR.o
gcc: warning: ../kernel/x86/: linker input file unused because linking not done
gcc: warning: ../kernel/x86/: linker input file unused because linking not done
gcc: warning: ../kernel/x86/: linker input file unused because linking not done
gcc: warning: ../kernel/x86/: linker input file unused because linking not done
gcc -O2 -DMAX_STACK_ALLOC=2048 -fopenmp -Wall -m32 -DF_INTERFACE_GFORT -fPIC -DNO_AVX -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME=ctrmm_kernel_LC -DASMFNAME=ctrmm_kernel_LC_ -DNAME=ctrmm_kernel_LC_ -DCNAME=ctrmm_kernel_LC -DCHAR_NAME=\"ctrmm_kernel_LC_\" -DCHAR_CNAME=\"ctrmm_kernel_LC\" -DNO_AFFINITY -I.. -UDOUBLE  -DCOMPLEX -c -DTRMMKERNEL -UDOUBLE -DCOMPLEX -DLEFT -DTRANSA -DCONJ -DCN ../kernel/x86/ -o ctrmm_kernel_LC.o
gcc -O2 -DMAX_STACK_ALLOC=2048 -fopenmp -Wall -m32 -DF_INTERFACE_GFORT -fPIC -DNO_AVX -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME=ctrmm_kernel_RN -DASMFNAME=ctrmm_kernel_RN_ -DNAME=ctrmm_kernel_RN_ -DCNAME=ctrmm_kernel_RN -DCHAR_NAME=\"ctrmm_kernel_RN_\" -DCHAR_CNAME=\"ctrmm_kernel_RN\" -DNO_AFFINITY -I.. -UDOUBLE  -DCOMPLEX -c -DTRMMKERNEL -UDOUBLE -DCOMPLEX -ULEFT -UTRANSA -UCONJ -DNN ../kernel/x86/ -o ctrmm_kernel_RN.o
gcc: warning: ../kernel/x86/: linker input file unused because linking not done
gcc -O2 -DMAX_STACK_ALLOC=2048 -fopenmp -Wall -m32 -DF_INTERFACE_GFORT -fPIC -DNO_AVX -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME=ctrmm_kernel_RT -DASMFNAME=ctrmm_kernel_RT_ -DNAME=ctrmm_kernel_RT_ -DCNAME=ctrmm_kernel_RT -DCHAR_NAME=\"ctrmm_kernel_RT_\" -DCHAR_CNAME=\"ctrmm_kernel_RT\" -DNO_AFFINITY -I.. -UDOUBLE  -DCOMPLEX -c -DTRMMKERNEL -UDOUBLE -DCOMPLEX -ULEFT -DTRANSA -UCONJ -DNN ../kernel/x86/ -o ctrmm_kernel_RT.o
gcc -O2 -DMAX_STACK_ALLOC=2048 -fopenmp -Wall -m32 -DF_INTERFACE_GFORT -fPIC -DNO_AVX -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME=ctrmm_kernel_RR -DASMFNAME=ctrmm_kernel_RR_ -DNAME=ctrmm_kernel_RR_ -DCNAME=ctrmm_kernel_RR -DCHAR_NAME=\"ctrmm_kernel_RR_\" -DCHAR_CNAME=\"ctrmm_kernel_RR\" -DNO_AFFINITY -I.. -UDOUBLE  -DCOMPLEX -c -DTRMMKERNEL -UDOUBLE -DCOMPLEX -ULEFT -UTRANSA -DCONJ -DNC ../kernel/x86/ -o ctrmm_kernel_RR.o
gcc -O2 -DMAX_STACK_ALLOC=2048 -fopenmp -Wall -m32 -DF_INTERFACE_GFORT -fPIC -DNO_AVX -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME=ctrmm_kernel_RC -DASMFNAME=ctrmm_kernel_RC_ -DNAME=ctrmm_kernel_RC_ -DCNAME=ctrmm_kernel_RC -DCHAR_NAME=\"ctrmm_kernel_RC_\" -DCHAR_CNAME=\"ctrmm_kernel_RC\" -DNO_AFFINITY -I.. -UDOUBLE  -DCOMPLEX -c -DTRMMKERNEL -UDOUBLE -DCOMPLEX -ULEFT -DTRANSA -DCONJ -DNC ../kernel/x86/ -o ctrmm_kernel_RC.o
gcc: warning: ../kernel/x86/: linker input file unused because linking not done
gcc: warning: ../kernel/x86/: linker input file unused because linking not done
gcc: warning: ../kernel/x86/: linker input file unused because linking not done
gcc -O2 -DMAX_STACK_ALLOC=2048 -fopenmp -Wall -m32 -DF_INTERFACE_GFORT -fPIC -DNO_AVX -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME=ztrmm_kernel_LN -DASMFNAME=ztrmm_kernel_LN_ -DNAME=ztrmm_kernel_LN_ -DCNAME=ztrmm_kernel_LN -DCHAR_NAME=\"ztrmm_kernel_LN_\" -DCHAR_CNAME=\"ztrmm_kernel_LN\" -DNO_AFFINITY -I.. -DDOUBLE  -DCOMPLEX -c -DTRMMKERNEL -DDOUBLE -DCOMPLEX -DLEFT -UTRANSA -UCONJ -DNN ../kernel/x86/ -o ztrmm_kernel_LN.o
gcc -O2 -DMAX_STACK_ALLOC=2048 -fopenmp -Wall -m32 -DF_INTERFACE_GFORT -fPIC -DNO_AVX -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME=ztrmm_kernel_LT -DASMFNAME=ztrmm_kernel_LT_ -DNAME=ztrmm_kernel_LT_ -DCNAME=ztrmm_kernel_LT -DCHAR_NAME=\"ztrmm_kernel_LT_\" -DCHAR_CNAME=\"ztrmm_kernel_LT\" -DNO_AFFINITY -I.. -DDOUBLE  -DCOMPLEX -c -DTRMMKERNEL -DDOUBLE -DCOMPLEX -DLEFT -DTRANSA -UCONJ -DNN ../kernel/x86/ -o ztrmm_kernel_LT.o
gcc -O2 -DMAX_STACK_ALLOC=2048 -fopenmp -Wall -m32 -DF_INTERFACE_GFORT -fPIC -DNO_AVX -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME=ztrmm_kernel_LR -DASMFNAME=ztrmm_kernel_LR_ -DNAME=ztrmm_kernel_LR_ -DCNAME=ztrmm_kernel_LR -DCHAR_NAME=\"ztrmm_kernel_LR_\" -DCHAR_CNAME=\"ztrmm_kernel_LR\" -DNO_AFFINITY -I.. -DDOUBLE  -DCOMPLEX -c -DTRMMKERNEL -DDOUBLE -DCOMPLEX -DLEFT -UTRANSA -DCONJ -DCN ../kernel/x86/ -o ztrmm_kernel_LR.o
gcc: warning: ../kernel/x86/: linker input file unused because linking not done
gcc: warning: ../kernel/x86/: linker input file unused because linking not done
gcc: warning: ../kernel/x86/: linker input file unused because linking not done
gcc -O2 -DMAX_STACK_ALLOC=2048 -fopenmp -Wall -m32 -DF_INTERFACE_GFORT -fPIC -DNO_AVX -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME=ztrmm_kernel_LC -DASMFNAME=ztrmm_kernel_LC_ -DNAME=ztrmm_kernel_LC_ -DCNAME=ztrmm_kernel_LC -DCHAR_NAME=\"ztrmm_kernel_LC_\" -DCHAR_CNAME=\"ztrmm_kernel_LC\" -DNO_AFFINITY -I.. -DDOUBLE  -DCOMPLEX -c -DTRMMKERNEL -DDOUBLE -DCOMPLEX -DLEFT -DTRANSA -DCONJ -DCN ../kernel/x86/ -o ztrmm_kernel_LC.o
gcc -O2 -DMAX_STACK_ALLOC=2048 -fopenmp -Wall -m32 -DF_INTERFACE_GFORT -fPIC -DNO_AVX -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME=ztrmm_kernel_RN -DASMFNAME=ztrmm_kernel_RN_ -DNAME=ztrmm_kernel_RN_ -DCNAME=ztrmm_kernel_RN -DCHAR_NAME=\"ztrmm_kernel_RN_\" -DCHAR_CNAME=\"ztrmm_kernel_RN\" -DNO_AFFINITY -I.. -DDOUBLE  -DCOMPLEX -c -DTRMMKERNEL -DDOUBLE -DCOMPLEX -ULEFT -UTRANSA -UCONJ -DNN ../kernel/x86/ -o ztrmm_kernel_RN.o
gcc -O2 -DMAX_STACK_ALLOC=2048 -fopenmp -Wall -m32 -DF_INTERFACE_GFORT -fPIC -DNO_AVX -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME=ztrmm_kernel_RT -DASMFNAME=ztrmm_kernel_RT_ -DNAME=ztrmm_kernel_RT_ -DCNAME=ztrmm_kernel_RT -DCHAR_NAME=\"ztrmm_kernel_RT_\" -DCHAR_CNAME=\"ztrmm_kernel_RT\" -DNO_AFFINITY -I.. -DDOUBLE  -DCOMPLEX -c -DTRMMKERNEL -DDOUBLE -DCOMPLEX -ULEFT -DTRANSA -UCONJ -DNN ../kernel/x86/ -o ztrmm_kernel_RT.o
gcc: warning: ../kernel/x86/: linker input file unused because linking not done
gcc -O2 -DMAX_STACK_ALLOC=2048 -fopenmp -Wall -m32 -DF_INTERFACE_GFORT -fPIC -DNO_AVX -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME=ztrmm_kernel_RR -DASMFNAME=ztrmm_kernel_RR_ -DNAME=ztrmm_kernel_RR_ -DCNAME=ztrmm_kernel_RR -DCHAR_NAME=\"ztrmm_kernel_RR_\" -DCHAR_CNAME=\"ztrmm_kernel_RR\" -DNO_AFFINITY -I.. -DDOUBLE  -DCOMPLEX -c -DTRMMKERNEL -DDOUBLE -DCOMPLEX -ULEFT -UTRANSA -DCONJ -DNC ../kernel/x86/ -o ztrmm_kernel_RR.o
gcc: warning: ../kernel/x86/: linker input file unused because linking not done
gcc: warning: ../kernel/x86/: linker input file unused because linking not done
gcc: warning: ../kernel/x86/: linker input file unused because linking not done
gcc: warning: ../kernel/x86/: linker input file unused because linking not done
gcc -O2 -DMAX_STACK_ALLOC=2048 -fopenmp -Wall -m32 -DF_INTERFACE_GFORT -fPIC -DNO_AVX -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME=ztrmm_kernel_RC -DASMFNAME=ztrmm_kernel_RC_ -DNAME=ztrmm_kernel_RC_ -DCNAME=ztrmm_kernel_RC -DCHAR_NAME=\"ztrmm_kernel_RC_\" -DCHAR_CNAME=\"ztrmm_kernel_RC\" -DNO_AFFINITY -I.. -DDOUBLE  -DCOMPLEX -c -DTRMMKERNEL -DDOUBLE -DCOMPLEX -ULEFT -DTRANSA -DCONJ -DNC ../kernel/x86/ -o ztrmm_kernel_RC.o
gcc: warning: ../kernel/x86/: linker input file unused because linking not done
ar  -ru ../libopenblas_haswellp-r0.2.15.a samax_k.o samin_k.o smax_k.o smin_k.o isamax_k.o isamin_k.o ismax_k.o ismin_k.o sasum_k.o saxpy_k.o scopy_k.o sdot_k.o sdsdot_k.o dsdot_k.o snrm2_k.o srot_k.o sscal_k.o sswap_k.o saxpby_k.o sgemv_n.o sgemv_t.o ssymv_U.o ssymv_L.o sger_k.o sgemm_kernel.o sgemm_oncopy.o sgemm_otcopy.o sgemm_beta.o strmm_kernel_LN.o strmm_kernel_LT.o strmm_kernel_RN.o strmm_kernel_RT.o strsm_kernel_LN.o strsm_kernel_LT.o strsm_kernel_RN.o strsm_kernel_RT.o strmm_iunucopy.o strmm_iunncopy.o strmm_ilnucopy.o strmm_ilnncopy.o strmm_iutucopy.o strmm_iutncopy.o strmm_iltucopy.o strmm_iltncopy.o strmm_ounucopy.o strmm_ounncopy.o strmm_olnucopy.o strmm_olnncopy.o strmm_outucopy.o strmm_outncopy.o strmm_oltucopy.o strmm_oltncopy.o strsm_iunucopy.o strsm_iunncopy.o strsm_ilnucopy.o strsm_ilnncopy.o strsm_iutucopy.o strsm_iutncopy.o strsm_iltucopy.o strsm_iltncopy.o strsm_ounucopy.o strsm_ounncopy.o strsm_olnucopy.o strsm_olnncopy.o strsm_outucopy.o strsm_outncopy.o strsm_oltucopy.o strsm_oltncopy.o ssymm_iutcopy.o ssymm_iltcopy.o ssymm_outcopy.o ssymm_oltcopy.o somatcopy_k_cn.o somatcopy_k_rn.o somatcopy_k_ct.o somatcopy_k_rt.o simatcopy_k_cn.o simatcopy_k_rn.o simatcopy_k_ct.o simatcopy_k_rt.o sgeadd_k.o sneg_tcopy.o slaswp_ncopy.o damax_k.o damin_k.o dmax_k.o dmin_k.o idamax_k.o idamin_k.o idmax_k.o idmin_k.o dasum_k.o daxpy_k.o dcopy_k.o ddot_k.o dnrm2_k.o drot_k.o dscal_k.o dswap_k.o daxpby_k.o dgemv_n.o dgemv_t.o dsymv_U.o dsymv_L.o dger_k.o dgemm_kernel.o dgemm_incopy.o dgemm_itcopy.o dgemm_oncopy.o dgemm_otcopy.o dgemm_beta.o dtrmm_kernel_LN.o dtrmm_kernel_LT.o dtrmm_kernel_RN.o dtrmm_kernel_RT.o dtrsm_kernel_LN.o dtrsm_kernel_LT.o dtrsm_kernel_RN.o dtrsm_kernel_RT.o dtrmm_iunucopy.o dtrmm_iunncopy.o dtrmm_ilnucopy.o dtrmm_ilnncopy.o dtrmm_iutucopy.o dtrmm_iutncopy.o dtrmm_iltucopy.o dtrmm_iltncopy.o dtrmm_ounucopy.o dtrmm_ounncopy.o dtrmm_olnucopy.o dtrmm_olnncopy.o dtrmm_outucopy.o dtrmm_outncopy.o dtrmm_oltucopy.o dtrmm_oltncopy.o dtrsm_iunucopy.o dtrsm_iunncopy.o dtrsm_ilnucopy.o dtrsm_ilnncopy.o dtrsm_iutucopy.o dtrsm_iutncopy.o dtrsm_iltucopy.o dtrsm_iltncopy.o dtrsm_ounucopy.o dtrsm_ounncopy.o dtrsm_olnucopy.o dtrsm_olnncopy.o dtrsm_outucopy.o dtrsm_outncopy.o dtrsm_oltucopy.o dtrsm_oltncopy.o dsymm_iutcopy.o dsymm_iltcopy.o dsymm_outcopy.o dsymm_oltcopy.o domatcopy_k_cn.o domatcopy_k_rn.o domatcopy_k_ct.o domatcopy_k_rt.o dimatcopy_k_cn.o dimatcopy_k_rn.o dimatcopy_k_ct.o dimatcopy_k_rt.o dgeadd_k.o dneg_tcopy.o dlaswp_ncopy.o camax_k.o camin_k.o icamax_k.o icamin_k.o casum_k.o caxpy_k.o caxpyc_k.o ccopy_k.o cdotc_k.o cdotu_k.o cnrm2_k.o csrot_k.o cscal_k.o cswap_k.o caxpby_k.o cgemv_n.o cgemv_t.o cgemv_r.o cgemv_c.o cgemv_o.o cgemv_u.o cgemv_s.o cgemv_d.o csymv_U.o csymv_L.o chemv_U.o chemv_L.o chemv_V.o chemv_M.o cgeru_k.o cgerc_k.o cgerv_k.o cgerd_k.o cgemm_kernel_n.o cgemm_kernel_r.o cgemm_kernel_l.o cgemm_kernel_b.o cgemm_oncopy.o cgemm_otcopy.o cgemm_beta.o ctrmm_kernel_LN.o ctrmm_kernel_LT.o ctrmm_kernel_LR.o ctrmm_kernel_LC.o ctrmm_kernel_RN.o ctrmm_kernel_RT.o ctrmm_kernel_RR.o ctrmm_kernel_RC.o ctrsm_kernel_LN.o ctrsm_kernel_LT.o ctrsm_kernel_LR.o ctrsm_kernel_LC.o ctrsm_kernel_RN.o ctrsm_kernel_RT.o ctrsm_kernel_RR.o ctrsm_kernel_RC.o cgemm3m_kernel.o ctrmm_iunucopy.o ctrmm_iunncopy.o ctrmm_ilnucopy.o ctrmm_ilnncopy.o ctrmm_iutucopy.o ctrmm_iutncopy.o ctrmm_iltucopy.o ctrmm_iltncopy.o ctrmm_ounucopy.o ctrmm_ounncopy.o ctrmm_olnucopy.o ctrmm_olnncopy.o ctrmm_outucopy.o ctrmm_outncopy.o ctrmm_oltucopy.o ctrmm_oltncopy.o ctrsm_iunucopy.o ctrsm_iunncopy.o ctrsm_ilnucopy.o ctrsm_ilnncopy.o ctrsm_iutucopy.o ctrsm_iutncopy.o ctrsm_iltucopy.o ctrsm_iltncopy.o ctrsm_ounucopy.o ctrsm_ounncopy.o ctrsm_olnucopy.o ctrsm_olnncopy.o ctrsm_outucopy.o ctrsm_outncopy.o ctrsm_oltucopy.o ctrsm_oltncopy.o csymm_iutcopy.o csymm_iltcopy.o csymm_outcopy.o csymm_oltcopy.o chemm_iutcopy.o chemm_iltcopy.o chemm_outcopy.o chemm_oltcopy.o cgemm3m_incopyb.o cgemm3m_itcopyb.o cgemm3m_incopyr.o cgemm3m_itcopyr.o cgemm3m_incopyi.o cgemm3m_itcopyi.o cgemm3m_oncopyb.o cgemm3m_otcopyb.o cgemm3m_oncopyr.o cgemm3m_otcopyr.o cgemm3m_oncopyi.o cgemm3m_otcopyi.o csymm3m_iucopyb.o csymm3m_oucopyb.o csymm3m_iucopyr.o csymm3m_oucopyr.o csymm3m_iucopyi.o csymm3m_oucopyi.o csymm3m_ilcopyb.o csymm3m_olcopyb.o csymm3m_ilcopyr.o csymm3m_olcopyr.o csymm3m_ilcopyi.o csymm3m_olcopyi.o chemm3m_iucopyb.o chemm3m_oucopyb.o chemm3m_iucopyr.o chemm3m_oucopyr.o chemm3m_iucopyi.o chemm3m_oucopyi.o chemm3m_ilcopyb.o chemm3m_olcopyb.o chemm3m_ilcopyr.o chemm3m_olcopyr.o chemm3m_ilcopyi.o chemm3m_olcopyi.o comatcopy_k_cn.o comatcopy_k_rn.o comatcopy_k_ct.o comatcopy_k_rt.o comatcopy_k_cnc.o comatcopy_k_rnc.o comatcopy_k_ctc.o comatcopy_k_rtc.o cimatcopy_k_cn.o cimatcopy_k_rn.o cimatcopy_k_ct.o cimatcopy_k_rt.o cimatcopy_k_cnc.o cimatcopy_k_rnc.o cimatcopy_k_ctc.o cimatcopy_k_rtc.o cgeadd_k.o cneg_tcopy.o claswp_ncopy.o zamax_k.o zamin_k.o izamax_k.o izamin_k.o zasum_k.o zaxpy_k.o zaxpyc_k.o zcopy_k.o zdotc_k.o zdotu_k.o znrm2_k.o zdrot_k.o zscal_k.o zswap_k.o zaxpby_k.o zgemv_n.o zgemv_t.o zgemv_r.o zgemv_c.o zgemv_o.o zgemv_u.o zgemv_s.o zgemv_d.o zsymv_U.o zsymv_L.o zhemv_U.o zhemv_L.o zhemv_V.o zhemv_M.o zgeru_k.o zgerc_k.o zgerv_k.o zgerd_k.o zgemm_kernel_n.o zgemm_kernel_r.o zgemm_kernel_l.o zgemm_kernel_b.o zgemm_incopy.o zgemm_itcopy.o zgemm_oncopy.o zgemm_otcopy.o zgemm_beta.o ztrmm_kernel_LN.o ztrmm_kernel_LT.o ztrmm_kernel_LR.o ztrmm_kernel_LC.o ztrmm_kernel_RN.o ztrmm_kernel_RT.o ztrmm_kernel_RR.o ztrmm_kernel_RC.o ztrsm_kernel_LN.o ztrsm_kernel_LT.o ztrsm_kernel_LR.o ztrsm_kernel_LC.o ztrsm_kernel_RN.o ztrsm_kernel_RT.o ztrsm_kernel_RR.o ztrsm_kernel_RC.o zgemm3m_kernel.o ztrmm_iunucopy.o ztrmm_iunncopy.o ztrmm_ilnucopy.o ztrmm_ilnncopy.o ztrmm_iutucopy.o ztrmm_iutncopy.o ztrmm_iltucopy.o ztrmm_iltncopy.o ztrmm_ounucopy.o ztrmm_ounncopy.o ztrmm_olnucopy.o ztrmm_olnncopy.o ztrmm_outucopy.o ztrmm_outncopy.o ztrmm_oltucopy.o ztrmm_oltncopy.o ztrsm_iunucopy.o ztrsm_iunncopy.o ztrsm_ilnucopy.o ztrsm_ilnncopy.o ztrsm_iutucopy.o ztrsm_iutncopy.o ztrsm_iltucopy.o ztrsm_iltncopy.o ztrsm_ounucopy.o ztrsm_ounncopy.o ztrsm_olnucopy.o ztrsm_olnncopy.o ztrsm_outucopy.o ztrsm_outncopy.o ztrsm_oltucopy.o ztrsm_oltncopy.o zsymm_iutcopy.o zsymm_iltcopy.o zsymm_outcopy.o zsymm_oltcopy.o zhemm_iutcopy.o zhemm_iltcopy.o zhemm_outcopy.o zhemm_oltcopy.o zgemm3m_incopyb.o zgemm3m_itcopyb.o zgemm3m_incopyr.o zgemm3m_itcopyr.o zgemm3m_incopyi.o zgemm3m_itcopyi.o zgemm3m_oncopyb.o zgemm3m_otcopyb.o zgemm3m_oncopyr.o zgemm3m_otcopyr.o zgemm3m_oncopyi.o zgemm3m_otcopyi.o zsymm3m_iucopyb.o zsymm3m_oucopyb.o zsymm3m_iucopyr.o zsymm3m_oucopyr.o zsymm3m_iucopyi.o zsymm3m_oucopyi.o zsymm3m_ilcopyb.o zsymm3m_olcopyb.o zsymm3m_ilcopyr.o zsymm3m_olcopyr.o zsymm3m_ilcopyi.o zsymm3m_olcopyi.o zhemm3m_iucopyb.o zhemm3m_oucopyb.o zhemm3m_iucopyr.o zhemm3m_oucopyr.o zhemm3m_iucopyi.o zhemm3m_oucopyi.o zhemm3m_ilcopyb.o zhemm3m_olcopyb.o zhemm3m_ilcopyr.o zhemm3m_olcopyr.o zhemm3m_ilcopyi.o zhemm3m_olcopyi.o zomatcopy_k_cn.o zomatcopy_k_rn.o zomatcopy_k_ct.o zomatcopy_k_rt.o zomatcopy_k_cnc.o zomatcopy_k_rnc.o zomatcopy_k_ctc.o zomatcopy_k_rtc.o zimatcopy_k_cn.o zimatcopy_k_rn.o zimatcopy_k_ct.o zimatcopy_k_rt.o zimatcopy_k_cnc.o zimatcopy_k_rnc.o zimatcopy_k_ctc.o zimatcopy_k_rtc.o zgeadd_k.o zneg_tcopy.o zlaswp_ncopy.o lsame.o scabs1.o dcabs1.o cpuid.o

something before it

**Comment by anoidgit** [comment]
my 32-bit ubuntu installed on vmware workstation 12

**Comment by martin-frbg** [comment]
Error messages from compiling strmm_kernel_LN appear to have been some lines before the part you posted. But if your system is 32bit, this is probably the same as #657 (compile with make BINARY=32, and do not expect the resulting library to make full use of the Haswell cpu)

**Comment by anoidgit** [comment]
Thank you ,I'm retrying,at least seems no problems occured right now

**Comment by easyupdo** [comment]
MinGW7.2：
openBLAS:OpenBLAS-0.2.20

use make BINARY=64 try to build it,reports that：*** No rule to make target '../kernel/x86/', needed by 'strmm_kernel_LN.obj'.  Stop.

use quickbuild.win64 report the same error

what should i do?

I used to use make BINARY=32 can successed

**Comment by martin-frbg** [comment]
@JayGuan06 what is your cpu ? Probably the automatic detection failed, and you need to provide a target like `make TARGET=HASWELL` . 0.2.20 is a year old, you may want to try again with 0.3.0 (which unfortunately is not yet linked from the openblas.net page)

**Comment by easyupdo** [comment]
OK. There is this possibility， I will be try it.
Thanks.
