### ISSUE TITLE
ONLY_CBLAS=1 needs -lgfortran

### ISSUE THREAD

**Issue by kilmarnock** [xianyi/OpenBLAS#720]
Hi!
I checked out the current code today, did 

```
make TARGET=SANDYBRIDGE, ONLY_CBLAS=1

 OpenBLAS build complete. (CBLAS)

  OS               ... Linux             
  Architecture     ... x86_64               
  BINARY           ... 64bit                 
  C compiler       ... GCC  (command line : gcc)
  Library Name     ... libopenblas_sandybridgep-r0.2.16.dev.a (Multi threaded; Max num-threads is 48)

make PREFIX=/my/prefix
```
and compile fails with
```
/bin/ld: cannot find -lgfortran
```
which is correct because I do not want to install fortran. I expected the ONLY_CBLAS=1 option to be fortran-free?

Never mind, I installed another gcc which solved the problem for me.

**Comment by jakirkham** [comment]
May have also been solved by this PR ( https://github.com/xianyi/OpenBLAS/pull/677 ).
