### ISSUE TITLE
wiki/doc: Say what BLAS stands for in FAQ

### ISSUE THREAD

**Issue by jowagner** [xianyi/OpenBLAS#721]
The wiki FAQ "What is OpenBLAS?" (and the project homepage) should say what "BLAS" means. Something like the first sentence on wikipedia would be also useful.

Advantages: (1) Developers coming across OpenBLAS while working through a list of dependencies would learn what it is for, take a mental note and maybe use it in a future project. (2) Relevant search queries would lead to your site.

**Comment by martin-frbg** [comment]
By that same reasoning, it would seem necessary to explain "linear algebra" next ?!

**Comment by jowagner** [comment]
No, if somebody cannot place "linear algebra" into the "matrices and maths" box they are unlikely to need something like OpenBLAS.

However, a developer needing an efficient library for linear algebra may never have heard about BLAS. It is rarely mentioned in computer science and mathematics classes. Foundational classes will require students to implement functions from scratch and more advanced classes will use something like Mathematica or R.

Googling a bit more, I also notice that OpenBLAS isn't in Wikipedia's List_of_numerical_libraries.

See also www.blas.ie for another meaning of blas.

**Comment by kthohr** [comment]
And those 'advanced classes' fail to mention that R's matrix operations are built on BLAS/Lapack?

**Comment by xianyi** [comment]
@jowagner , @martin-frbg , Thanks.

I just add an item at FAQ.
https://github.com/xianyi/OpenBLAS/wiki/Faq#whatblas
I am not sure it answers the question. I think anyone can edit the wiki :)

**Comment by jowagner** [comment]
Thanks. I didn't edit the FAQ as I'm outside the dev team and I didn't want to force anything on you.

@kthohr Correct. The names of libraries or standards they conform to is not the topic of typical classes using R. Explanations like "it uses specialised libraries for efficiency" are sufficient.
