### ISSUE TITLE
add zrot and crot signatures to f77blas.h

### ISSUE THREAD

**Issue by DarthLaran** [xianyi/OpenBLAS#724]
Hello!

One can see that there are no signatures of  zrot and crot subroutines in f77blas.h.
Following the LAPACK description at netlib.org,  it is correct, but a bit uncomfortable for practical usage. 
Is it possible to add these signatures to f77blas.h or other  *.h file by openblas library?

**Comment by brada4** [comment]
It is lapack routine and not included in LAPACKE by netlib. It is not BLAS routine
Either:
Report to netlib and get it included in LAPACKE in a year or two
or
Bake your own liblapackrot.so that wraps fortran ?rot functions in a way similar to what LAPACKE does.
