### ISSUE TITLE
More work needed on stack allocation to improve performance on small matrices

### ISSUE THREAD

**Issue by jeromerobert** [xianyi/OpenBLAS#727]
I open this issue to log my work on stack allocation. #478 was only for `gemv` and `ger` but there are many other use of blas_memory_alloc who kill performance when matrices are small. For my applications I need to fix:
* `zgemv`
* `zger`
* `ztrmv`
* possibly `trmv`
* possibly `getrf`

The 3 firsts are already done in my [fork](https://github.com/jeromerobert/OpenBLAS/) but IMHO this is not yet ready for a pull request (but reviews or tests are of course welcome).

As #478 log show the tricky part is to find the smallest buffer size which will work with all cases and all kernels. If this size is too large it lower performance, if it's too small there is a stack smashing. It currently pass `make test`, `make ctest`, my applications tests, on barcelona and sandybridge.

My plan is:
* Factorize code to a #define (a function is not possible here as we allocate to the stack) for ease of maintenance and reuse.
* Add a smallscaling.c test to the benchmark directory to show the benefit of stack allocation
* Run more tests to ensure that the buffer size is ok

**Comment by brada4** [comment]
Can you share your measurements? Maybe it is worth integrating stack allocations uniformly in blas_memory_alloc instead?

**Comment by jeromerobert** [comment]
I only have a low-end pentium D for a few days so I cannot reproduce the blas_memory_alloc perf issue. I currently only have the [https://gist.github.com/jeromerobert/e4fffc1eb2a9168f6205](old measurement) I ran on dgemv before adding MAX_STACK_ALLOC.

I'll run benchmark/smallscaling.c (available on my repo) on a good PC next week, and post results here.

About uniform integration of stack allocation, that's a bit the idea of factorizing the existing code to a macro/#define. Yet, as said above the main problem is not to add stack allocation, but to find the right buffer size for each function.

**Comment by martin-frbg** [comment]
I can provide benchmark figures for an i4770 Haswell later today if desired, any specific options to use ?

**Comment by jeromerobert** [comment]
@martin-frbg Just run with OPENBLAS_NUM_THREADS=1. You may have to increase [https://github.com/jeromerobert/OpenBLAS/blob/develop/benchmark/smallscaling.c#L14](NLOOP) to get more precise measures, because I chose it for my Pentium D.

**Comment by martin-frbg** [comment]
First results without increased NLOOP attached - "nehalem" is my aging i7 M640 laptop
[haswell.txt](https://github.com/xianyi/OpenBLAS/files/75649/haswell.txt)
[nehalem.txt](https://github.com/xianyi/OpenBLAS/files/75651/nehalem.txt)

**Comment by jeromerobert** [comment]
@brada4 Here are measurements:
* with `MAX_STACK_ALLOC=0` (no stack allocation): [sandybridge-without-stackalloc.txt](https://github.com/xianyi/OpenBLAS/files/77257/sandybridge-without-stackalloc.txt)
* with default (`MAX_STACK_ALLOC=2048`): [sandybridge-with-stackalloc.txt](https://github.com/xianyi/OpenBLAS/files/77258/sandybridge-with-stackalloc.txt)

`zgemv` and `zger` are around 10 time faster with stack allocation than without. I have to find why `ztrmv` still use `blas_memory_alloc` (the reason why it's slow) even in my branch.

@martin-frbg Thanks for the test ! Your OpenMP implementation seems magical as it gives a speedup of 80 on 4 threads. There is probably a bug in measurement but I don't know where. The speed-up with pthreads seems more reasonable but a bit too low. May be you should disable the CPU turbo:

    echo -n 1 > /sys/devices/system/cpu/intel_pstate/no_turbo
    echo 1 > /sys/module/processor/parameters/ignore_ppc

Or may be you have hyperthreading enable and in that case you have to set the number of thread with `OMP_NUM_THREADS=real number of core`.

The speed-up on of `ger` in your haswell test is as bad as if there was no stack allocation. That's also strange.

**Comment by martin-frbg** [comment]
Not sure what is going on, I disabled core boost now and made sure to have OMP_NUM_THREADS set to 4 in addition to the OPENBLAS_NUM_THREADS=1 you suggested earlier. 
Nothing much changed, dger with matrix sizes below 10 still reports speedups in excess of 40 with omp, while speedups for ztrmv and ger remain  poor. This is with a complete new checkout of your git tree (including smallscaling.c, hence no results for dtrmv), default build options for OpenBLAS except setting USE_OPENMP=1 in Makefile.rule
[haswell3.txt](https://github.com/xianyi/OpenBLAS/files/77681/haswell3.txt)

**Comment by brada4** [comment]
probably you use TSC as clock source and it is not constant. Make longer measurements or use stable clock source.

**Comment by jeromerobert** [comment]
I use clock_gettime(CLOCK_MONOTONIC which avoid this problem.

**Comment by brada4** [comment]
It is monotonic in regard that it counts ahead, no matter speed. It is still not synchronized between CPUs or cores. hpet or acpi_pm are synchronized between CPUs.

**Comment by martin-frbg** [comment]
This is a Haswell system, cpuinfo has both constant_tsc and nonstop_tsc flags set. Hence at worst I would expect the conversion from ticks to seconds to be off, but not an unstable tsc as such (as may have been found on earlier generation cpus).

**Comment by brada4** [comment]
Still there is no synchronisation between cores.

**Comment by martin-frbg** [comment]
According to the Intel documentation there should be, with these bits in the cpuid set (synchronisation on the same die, just not across multiple cpus in a system, which would be irrelevant here). Anyway, somebody may be able to provide additional data in case my system happens to suffer from a strange BIOS quirk or whatever...

**Comment by xianyi** [comment]
@jeromerobert , I aligned the stack buffer address on 32-bit. In `x86_64/cgemv_n.S` kernel, the `movaps` instruction need 16-bit alignment.
