### ISSUE TITLE
Build issues on Docker Hub

### ISSUE THREAD

**Issue by wielandbrendel** [xianyi/OpenBLAS#735]
I am experiencing a strange build error on Docker Hub that I cannot reproduce on my own machine. The minimum version of the problem takes a clean Ubuntu 14.04 and installs OpenBLAS from the master branch as follows (please find all details in the short [Dockerfile](https://github.com/wielandbrendel/openblas-dockerhub-error-minimum-example/blob/master/Dockerfile)):

    git clone -q --branch=master https://github.com/xianyi/OpenBLAS.git
    (cd OpenBLAS \
        && make DYNAMIC_ARCH=1 NO_AFFINITY=1 NUM_THREADS=32 \
            && make install)

The [build on Docker Hub](https://hub.docker.com/r/wielandbrendel/openblas-dockerhub-error-minimum-example/builds/) then fails with the following error message,

    OS               ... Linux             
    Architecture     ... x86_64               
    BINARY           ... 64bit                 
    C compiler       ... GCC  (command line : gcc)
    Fortran compiler ... GFORTRAN  (command line : gfortran)
    Library Name     ... libopenblasp-r0.2.15.a (Multi threaded; Max num-threads is 32)
   
    To install the library, you can run "make PREFIX=/path/to/your/installation install".
    
    [91m+ make install
    [0mmake -j 1 -f Makefile.install install
    make[1]: Entering directory `/tmp/build/OpenBLAS'
    Generating openblas_config.h in /opt/OpenBLAS/include
    Generating f77blas.h in /opt/OpenBLAS/include
    Generating cblas.h in /opt/OpenBLAS/include
    Copying LAPACKE header files to /opt/OpenBLAS/include
    Copying the static library to /opt/OpenBLAS/lib
    [91minstall: [0m[91mcannot stat ‘libopenblas-r0.2.15.a’[0m[91m: No such file or directory[0m[91m
    [0m[91mmake[1]: [0m[91m*** [install] Error 1[0m[91m
    [0mmake[1]: Leaving directory `/tmp/build/OpenBLAS'
    [91mmake: [0m[91m*** [install] Error 2[0m[91m
    [0mRemoving intermediate container 96cd4f9c5fef
    The command '/bin/sh -c bash /tmp/build_scipy_stack.sh' returned a non-zero code: 1

The complete log can be found [here](https://hub.docker.com/r/wielandbrendel/openblas-dockerhub-error-minimum-example/builds/bdjwrwundvfatvtulde7zrq/). It seems the build searches for 'libopenblas-r0.2.15.a' where the library is rather 'libopenblas**p**-r0.2.15.a'. Unfortunately, the same build passes happily fine on my own machine. For sanity check, I also forked the popular Ubuntu + OpenBLAS installation by [ogrisel](https://github.com/ogrisel/docker-openblas) but I get the same [error](https://hub.docker.com/r/wielandbrendel/docker-openblas/builds/bmrkv5nsfld64ykmh39nyal/). Any idea what the issue could be?

**Comment by jeromerobert** [comment]
`make DYNAMIC_ARCH=1 && make install` never worked for me. From `Makefile.install` and `Makefile.system`, `DYNAMIC_ARCH=1` must also be set when running `make install`, else it build a wrong `LIBNAME` variable.

**Comment by martin-frbg** [comment]
Yes, options given to the initial "make" do not carry over to subsequent invocations like "make test" or "make install" (cf. #651). An alternative would be to edit Makefile.rule accordingly before running make.

**Comment by wielandbrendel** [comment]
Ah, interesting. I adjusted the Dockerfile accordingly and now put 'DYNAMIC_ARCH=1 NO_AFFINITY=1 NUM_THREADS=32' after make install. The builds on Docker Hub are successful and I could successfully compile Numpy against OpenBLAS. Thanks a lot for your help!

**Comment by martin-frbg** [comment]
Could you please close this ticket then ?
