### ISSUE TITLE
Build and Run on arm platforms is broken

### ISSUE THREAD

**Issue by wernsaar** [xianyi/OpenBLAS#736]
Hi Xianyi,

The build of OpenBLAS in latest develop branch  is completely broken on arm platforms.
I always get bus-errors, tested on three different arm platforms.
I don't know the reason, It could be the merge, that introduced common_stackalloc.h.

I think, that you should revert the develop branch to a stable version.

Best regards
Werner

**Comment by martin-frbg** [comment]
Could you try doing a "git checkout e3e20e2" (which would be before Jerome's common_stackalloc work) or "git checkout c96c6a2" (before some earlier arm-related asm changes from yuyichao's #733) ?

**Comment by jeromerobert** [comment]
It's possible to build and test an `arm64` on Debian Linux with:

    sudo dpkg --add-architecture arm64
    sudo apt-get update
    sudo apt-get install qemu-user-binfmt gfortran-5-aarch64-linux-gnu libgfortran3:arm64
    make TARGET=ARMV8  CC=aarch64-linux-gnu-gcc-5 FC=aarch64-linux-gnu-gfortran-5

Then apply the following patch to enable make tests:

```patch
--- a/Makefile
+++ b/Makefile
@@ -112,8 +112,6 @@ endif
 
 tests :
 ifndef NOFORTRAN
-ifndef TARGET
-ifndef CROSS
 	touch $(LIBNAME)
 ifndef NO_FBLAS
 	$(MAKE) -C test all
@@ -125,8 +123,6 @@ ifndef NO_CBLAS
 	$(MAKE) -C ctest all
 endif
 endif
-endif
-endif
```

`make tests` will be long because it's pure CPU emulation.

I don't have any failure in `make test` doing that.

I also tried with `arm`:

    sudo dpkg --add-architecture armhf
    sudo apt-get update
    sudo apt-get install qemu-user-binfmt gfortran-5-arm-linux-gnueabihf libgfortran3:armhf
    make TARGET=ARMV8 CC=arm-linux-gnueabihf-gcc-5 CC=arm-linux-gnueabihf-gfortran-5

but building fail with:

    make[1]: Entering directory '/home/jerome/OpenBLAS-arm/kernel'
    make[1]: *** No rule to make target '../kernel/arm/amax.S', needed by 'samax_k.o'.  Stop.

**Comment by jeromerobert** [comment]
It does build with TARGET=ARMV5. The error is actually in my commit. I made the stack smashing 64bit only. I fix it right now.

**Comment by martin-frbg** [comment]
Ah, good point about qemu, thanks (now I only need a firmware update to understand assembler to become useful here). Guess this problem is also what bit the guy who last commented on #689.

**Comment by xianyi** [comment]
@jeromerobert , I think your patch didn't fix this bug. I also meet bus error on my ARM Cortex-A15. I will try to investigate it.

**Comment by jeromerobert** [comment]
So you mean there is 2 bugs ? The one I added and fixed happen with any 32bit architecture (including Cortex-A15) and looks like:

    sblat2: gemv.c:254: sgemv_: Assertion `stack_check == 0x7ff8010203040506' failed.
    
    Program received signal SIGABRT: Process abort signal.

The one you talk about may happen before so it hide the one I fixed, and may not happen with *qemu* (else I would see it).

**Comment by martin-frbg** [comment]
Both wernsaar above and the latest comment in #689 (same timeframe) mention bus errors (#689 specifically in gem, which recently saw changes in the arm assembler code). I trust some of you checked that they are not caused by e3e20e2 which immediately preceded jeromerobert's commit.

**Comment by xianyi** [comment]
Fix the bus error. Please try it.
