### ISSUE TITLE
Running make test on Travis ?

### ISSUE THREAD

**Issue by jeromerobert** [xianyi/OpenBLAS#738]
As `TARGET=NEHALEM` is set on Travis `make test` is not run. Running make test would have avoided problems such as #736.

If that does not make the build too long would be possible to either:
* Modify `Makefile` so it run make test even if `TARGET` is set.
* Remove `TARGET=NEHALEM` from the `.travis.yml` file

If that make the build too long (I guess Travis have limits), add a new `env` with:
* DYNAMIC_ARCH not set to save compilation time
* TARGET not set to enable tests

**Comment by brada4** [comment]
Actually DYNAMIC_ARCH disables tests. They would be somewhat pointless with 100s of other kernels compiled not tested at all. with tests displaying prominent OK.
There is no DYNAMIC_ARCH in #736 architectures.

**Comment by xianyi** [comment]
@jeromerobert , I can modify .travis.yml to run test today.

**Comment by xianyi** [comment]
Finish it in recent commit.

**Comment by jeromerobert** [comment]
Thanks !
