### ISSUE TITLE
non homegenous GEMM_MULTITHREAD_THRESHOLD usage

### ISSUE THREAD

**Issue by jeromerobert** [xianyi/OpenBLAS#742]
In gemv.c `GEMM_MULTITHREAD_THRESHOLD` is squared so it's homogenous to a matrix size. In gemm.c it's not squared so it's homogeneous to a number of floating point operations

So there is no chance that changing `GEMM_MULTITHREAD_THRESHOLD` in `Makefiles.rules` would give good results for both gemm and gemv.

Shouldn't `gemv.c` be fixed so that is use `GEMM_MULTITHREAD_THRESHOLD` as a number of floating point operations ?

A possibly related bug is #216 .

**Comment by jeromerobert** [comment]
As `gemv.c`, `trsm.c` also consider `GEMM_MULTITHREAD_THRESHOLD` as a matrix size.

**Comment by xianyi** [comment]
@jeromerobert ,  I think `GEMM_MULTITHREAD_THRESHOLD` of `gemv.c` is also a number of floating point operations since `gemv` is O(n^2).

**Comment by jeromerobert** [comment]
The `gemv.c` code is:
```C
if ( MNK <= (24.0 * 24.0  * (double) (GEMM_MULTITHREAD_THRESHOLD*GEMM_MULTITHREAD_THRESHOLD) )  )
```

MNK is the number of floating point operation. But we compare to `a_const * GEMM_MULTITHREAD_THRESHOLD * GEMM_MULTITHREAD_THRESHOLD` while we should, IMHO, compare to `a_const * GEMM_MULTITHREAD_THRESHOLD`, as done in gemm.

> Or, different threshold for different functions?

I'm not sure that's a good idea because that will make `OpenBLAS` very difficult to calibrate and maintain.

**Comment by jeromerobert** [comment]
I think we need something like:
```C
if(MNK <= 2304 * GEMM_MULTITHREAD_THRESHOLD)
```
which is equivalent when GEMM_MULTITHREAD_THRESHOLD = 4.

**Comment by jeromerobert** [comment]
@wernsaar Could we have your feeling, as you are the author of `gemv` and `trsm` thresholding ?

**Comment by wernsaar** [comment]
Yes, that's right.
