### ISSUE TITLE
[s|d]dot yields NaN on ARM if outputting a NaN before

### ISSUE THREAD

**Issue by buffer51** [xianyi/OpenBLAS#750]
Hi,

I am currently experimenting with OpenBLAS on a Raspberry Pi 2 (ARMv7 processor).
It compiled fine with the latest develop branch, however when running this example, I get a weird behavior: the same computation yields a NaN if I just outputted a NaN.

Could it be linked to #740?

See following snippet:
```
#include "cblas.h"
#include <iostream>
#include <cmath>

int main() {
    int N = 2;
    int stepA = 1;
    int stepB = 1;

    {
        float A[] = {1.0f, 0.0f};
        float B[] = {1.0f, 0.0f};
        float f = std::nanf("");
        float g = 0.0f;

        std::cout << "sdot: " << cblas_sdot(N, A, stepA, B, stepB) << std::endl;
        std::cout << "dump a NaN: " << f << std::endl;
        std::cout << "sdot: " << cblas_sdot(N, A, stepA, B, stepB) << std::endl;
        std::cout << "dump a 0: " << g << std::endl;
        std::cout << "sdot: " << cblas_sdot(N, A, stepA, B, stepB) << std::endl;
    }

    {
        double A[] = {1.0, 0.0};
        double B[] = {1.0, 0.0};
        double f = std::nan("");
        double g = 0.0;

        std::cout << "ddot: " << cblas_ddot(N, A, stepA, B, stepB) << std::endl;
        std::cout << "dump a NaN: " << f << std::endl;
        std::cout << "ddot: " << cblas_ddot(N, A, stepA, B, stepB) << std::endl;
        std::cout << "dump a 0: " << g << std::endl;
        std::cout << "ddot: " << cblas_ddot(N, A, stepA, B, stepB) << std::endl;
    }

    return 0;
}
```
gives:
```
sdot: 1
dump a NaN: nan
sdot: nan
dump a 0: 0
sdot: 1
ddot: 1
dump a NaN: nan
ddot: nan
dump a 0: 0
ddot: 1
```
For reference, on Ubuntu 14.04 x86_64, I get:
```
sdot: 1
dump a NaN: nan
sdot: 1
dump a 0: 0
sdot: 1
ddot: 1
dump a NaN: nan
ddot: 1
dump a 0: 0
ddot: 1
```

**Comment by wernsaar** [comment]
Hi Paul,

I commited some bugfixes.

I also modified your testcode:

#include "include/cblas.h"
#include <iostream>
#include <cmath>

int main() {
    int N = 2;
    int stepA = 1;
    int stepB = 1;

    {
        float A[] = {1.0f, 0.0f};
        float B[] = {1.0f, 0.0f};
        float f = 0.0f/0.0f;
        float g = 1.0f/0.0f;
        float h = 0.0f;

        std::cout << "sdot: " << cblas_sdot(N, A, stepA, B, stepB) <<  "     ";
        std::cout << "dump a NaN: " << f << std::endl;
        std::cout << "sdot: " << cblas_sdot(N, A, stepA, B, stepB) <<  "     ";
        std::cout << "dump a INF: " << g << std::endl;
        std::cout << "sdot: " << cblas_sdot(N, A, stepA, B, stepB) <<  "     ";
        std::cout << "dump a Zero: " << h << std::endl << std::endl;
    }


    {
        float A[] = {1.0f, 0.0f};
        float B[] = {1.0f, 0.0f};
        double f = 0.0/0.0;
        double g = 1.0/0.0;
        double h = 0.0;

        std::cout << "dsdot: " << cblas_dsdot(N, A, stepA, B, stepB) <<  "     ";
        std::cout << "dump a NaN: " << f << std::endl;
        std::cout << "dsdot: " << cblas_dsdot(N, A, stepA, B, stepB) <<  "     ";
        std::cout << "dump a INF: " << g << std::endl;
        std::cout << "dsdot: " << cblas_dsdot(N, A, stepA, B, stepB) <<  "     ";
        std::cout << "dump a Zero: " << h << std::endl << std::endl;
    }

    {
        double A[] = {1.0, 0.0};
        double B[] = {1.0, 0.0};
        double f = 0.0/0.0;
        double g = 1.0/0.0;
        double h = 0.0;

        std::cout << "ddot: " << cblas_ddot(N, A, stepA, B, stepB) <<  "     ";
        std::cout << "dump a NaN: " << f << std::endl;
        std::cout << "ddot: " << cblas_ddot(N, A, stepA, B, stepB) <<  "     ";
        std::cout << "dump a INF: " << g << std::endl;
        std::cout << "ddot: " << cblas_ddot(N, A, stepA, B, stepB) <<  "     ";
        std::cout << "dump a Zero: " << h << std::endl << std::endl;
    }

    return 0;
}

Thank you for your investigation and the bug report.

Best regards
Werner

**Comment by wernsaar** [comment]
Hi Paul,

Sorry, It seems, that cut and paste does not really work on github.
There are some errors in the my source code.

Best regards
Werner

**Comment by buffer51** [comment]
Hi wernsaar,

This effectively fixes that bug. I also confirmed that cdot & zdot are correct (xianyi committed for those).
I see in #740 that there are more similar bugs around, so I'll try to check if anything else has problem with our use of OpenBLAS.

Thanks for the quick fixes!
Paul
