### ISSUE TITLE
Improve _spr2 for small data sizes

### ISSUE THREAD

**Issue by brada4** [xianyi/OpenBLAS#752]
same motivation as #751 
interface/spr2.c
```
 #ifdef SMP
   nthreads = num_cpu_avail(2);
+  
+  if (sizeof(FLOAT)*n*(abs(incx)+abs(incy)+n/2)<2*1024*1024) nthreads=1;
 
   if (nthreads == 1) {
 #endif
```

**Comment by brada4** [comment]
it could be some function next to thread server to tell optimal thread number based on current CPUID L1d L2 L3 L4

**Comment by xianyi** [comment]
@brada4 , I agree with you. It should be a function related to L1 or L2 cache size.

**Comment by brada4** [comment]
And outer cache and numa stride after.
int howmanycpusineed(int ineedthismanybytes,boot amistrcopy)
first we hold back 2nd thread until it really fills L1d etc (here all DSP cases cheer already)
then we make up as many of them as share L2 (aka hyperthreading)
and hold back this herd until we fill 2nd L2 cache
...
...
L99 ... L100
...
At least on Linux we can read numa stride size and hold back next CPU's worth of threads until that 2nd numa stride is full

I do that with excel for few CPU types I run but i am sure you can do much better.
