### ISSUE TITLE
Commit 31aff44 breaks 'make install' on Centos 7

### ISSUE THREAD

**Issue by mkocikowski** [xianyi/OpenBLAS#763]
Hi, the move from `awk` to `nawk` in 31aff44 breaks builds on Centos (nawk not available in default install or as a yum package). Seeing how functionally moving to `nawk` achieves nothing, perhaps the change is not necessary? The workaround is to invoke `make AWK=awk`, but I'd rather have the default work. Thanks, Mik.

**Comment by martin-frbg** [comment]
Changing AWK across all supported architectures is certainly unwarranted (and most likely unintentional, there is an "ifeq ($(OSNAME), SunOS)" block a few lines up in Makefile.system that would have been perfect for this)

**Comment by brada4** [comment]
Posixly correct in makefile.install should be
```
awk '{print $1, "OPENBLAS_"$2, $3}' config_last.h  > ....
```
In posix awk you need to getline before NF (and gawk too)
(no nawk on SuSE either)
