### ISSUE TITLE
OT:brada4 

### ISSUE THREAD

**Issue by cbergstrom** [xianyi/OpenBLAS#765]
Hi brada4,

Github doesn't give me any other means to contact you, but I'm interested to talk more about working together on OpenBLAS. We, PathScale, typically work on compilers, but working on libs is also on our table.

email: cbergstrom@pathscale.com

Thanks

Christopher
-----
ps - Apologies everyone about the OT "bug report"

**Comment by martin-frbg** [comment]
@cbergstrom : suggest you pick an existing bugreport by that person and write your off-topic request
there, perhaps with a "mention" (at sign plus username) as I did here to increase the chance that the addressee receives a notification. That way you would at least not create needless bug tickets on tangentially involved projects (or even have your ticket subject cause concern that something untoward may have happened to that person)
