### ISSUE TITLE
vsub issues on ARM kernels

### ISSUE THREAD

**Issue by buffer51** [xianyi/OpenBLAS#766]
Hi,

Recently I had a problem with NaN being introduced in the results of ARM kernels (#750), which @wernsaar fixed. I see several other kernels have been changed.

The last vsub instruction that I see used as a way to initialize registers is in kernel/arm/gemv_t_vfpv3.S.
I see that it's not currently in use, however in this commit 63a7d7fb2427c7dd4f3c01720b0636ede0260665 @wernsaar fixed the same problem for gemv_n_vfpv3.S (I'm guessing transposed problem?) and enabled it in the KERNEL.ARMV7 file.

I would attempt to fix it myself, but I'm not sure what to check for; I've tried to create a test case where it fails because of NaN in the buffer without success.

Paul

**Comment by nagya11** [comment]
that I see used as a way to initialize registers is in kernel/arm/gemv_t_vfpv3.S.
I see that it's not currently in use, however in this commit 63a7d7f @wernsaar fixed the same problem for gemv_n_vfpv3.S (I'm guessing transposed problem?) and enabled it in the KERNEL.ARMV7 file.

I would attempt to fix it myself, but I'm not sure what to?

**Comment by wernsaar** [comment]
Hi,

gemv_t_vfpv3.S is not in use, because the results are wrong.
We should remove bad an unused sources from the repository.

Best regards

Werner


2016-01-28 16:49 GMT+01:00 Nagy Anna <notifications@github.com>:

**Comment by buffer51** [comment]
Thanks for the reply.
I agree that removing unused (especially incorrect) sources would be good, or at least flagging them somehow.

Paul
