### ISSUE TITLE
Make Failing : wrong number of arguments specified for ‘constructor/destructor’ attribute

### ISSUE THREAD

**Issue by kartiklakhotia** [xianyi/OpenBLAS#767]
Make fails and throws this error :

memory.c:1341: error: wrong number of arguments specified for ‘constructor’ attribute
memory.c:1384: error: wrong number of arguments specified for ‘destructor’ attribute

The memory.c referred here is located in OpenBLASDir/driver/others.
I am trying to compile OpenBLAS 0.2.15 via source, on RHEL

**Comment by martin-frbg** [comment]
See closed issue #700 - either remove the "(101)" from both lines or perhaps download and build a snapshot of the current "develop" branch that will eventually morph into 0.2.16

**Comment by brada4** [comment]
What is "RHEL" ? Which "RHEL"? What compiler version?

**Comment by kartiklakhotia** [comment]
It worked by removing the argument. RHEL is red hat enterprise Linux.
Wasn't referring to compiler :P

**Comment by brada4** [comment]
Can you answer me? Red Hat Linux 7 has compiler that supports constructor priorities in base system. For others you can get later compilers under name of "software collections".

**Comment by martin-frbg** [comment]
@brada4 not sure why you are so insisting - a quick search reveals that it is probably RHEL5 (same as one guy in #700 just a few weeks ago), as RHEL6 already shipped with gcc4.4 according to RH. And the folks who still run such "outdated" systems are often reluctant to "mess with" the base system components for some reason or other (certification, similarly old and finicky software or attached special hardware)...

**Comment by brada4** [comment]
There is EPEL for those not willing to mess base system components, perfectly providing latest release of OpenBLAS.

**Comment by brada4** [comment]
Or developer toolset 2.1 for RHEL5.9+ with AVX2 binutils for those willing to walk the fires.

**Comment by brada4** [comment]
I think #645 should be renabled a "cold call" and "fix" reverted. 
It just sacrifices builds that would have worked before in order to help somebody who copied pasted code and could not add named change in his code.

**Comment by martin-frbg** [comment]
I see nothing wrong with #654 (sic!), and the fix resulting from #700 solves the compilation problems for older compilers essentially by "reverting" the change for them.

**Comment by brada4** [comment]
Those older compilers are in fairly modern operating systems... 
It does not solve a single problem in standalone openblas distribution. 
It just avoids a problem of single person who included openblas and his code in same module.
Then comes next one who wants to run his own say mprotect(), and start that certainly before openblas. Now tell me which kid you will like more? 99 or 101 ?
