### ISSUE TITLE
ARM cortex A17 cpu （32 bit）support problem

### ISSUE THREAD

**Issue by catchmyself** [xianyi/OpenBLAS#772]
1. I want to use  SGEMM matrix multiple algorithm in openblas in arm cpu. The cpu is A17 and it is 32 bit.  I know openblas now support target= armv7, cortex-A9, cortex-A15. Is there any plan to support the cortex-A17 target?
2. performance issue with comparing intel cpu (Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz) and arm:
    I use openblas 's SGEMM in x86 cpu and arm A17 cpu. But I found when the N=M=K=1024 and N=M=K=2048, the performance of x86 cpu is 15-~20 times faster than arm A17 (compile with target= armv7).  But when I write one matrix multiple and add operation function like classic algorithm as below:

void matrix_mul(float c[][N], float a[][N], float b[][N])
{
    for (uint32_t i = 0; i < N; ++i) {
        for (uint32_t j = 0; j < N; ++j) {
            for (uint32_t k = 0; k < N; ++k) {
                c[i][j] += a[i][k] \* b[k][j];
            }
        }
    }  
}

The performance difference is just 5 times faster than arm A17.  Is this situation normal?

**Comment by wernsaar** [comment]
Hi,

we don't have a machine with Cortex-A17 for testing.
But the Cortex-A17 is a Cortex-A15 paired with a Cortex-A7 in
Big.Little configuration.
The Cortex-A7, that has very low power consumption, is very slow.
I you have built OpenBLAS with support for SMP and you simply
run the sgemm benchmark, some threads run the fast Cortex-A15 and
some threads on slow Cortex-A7. Because threads have to be synchronized,
the overall performance is that of Cortex-A7.
So, use fewer threads and use tasket to bind the benchmark test to 
Cortex-A15 core's only.

Best regards
Werner

**Comment by cbergstrom** [comment]
@wernsaar can you help with Power8?

**Comment by catchmyself** [comment]
@wernsaar , Big.LITTLE support is just one feature of A17.  In fact, A17 can stand alone as one CPU without A7. 
"The Cortex-A17 processor also added big.LITTLE support. Whilst many partners are using this to provide heterogeneous Cortex-A17 and Cortex-A7 processor solutions, some are also delivering standalone Cortex-A17 processor solutions,  which are now almost indistinguishable from Cortex-A12 only solutions. "  You can refer to the link: https://community.arm.com/groups/processors/blog/2014/09/30/arm-cortex-a17-cortex-a12-processor-update

http://www.arm.com/zh/products/processors/cortex-a/cortex-a17-processor.php

**Comment by catchmyself** [comment]
@wernsaar , If I want to add optimization codes for using sgemm for arm cortex-A17, How can I do for this optimizatioin?  Is there any document to expain the related codes to help me to add new optimization?

**Comment by xianyi** [comment]
@catchmyself , I try to write a developer manual at https://github.com/xianyi/OpenBLAS/wiki/Developer-manual

**Comment by catchmyself** [comment]
@xianyi , thanks for your developer-manual.  Another question: if I just want to use the sgemm function seperately, is there any method to split this function from all the openblas lib?  That means I just want to use sgemm function stand alone.

**Comment by xianyi** [comment]
@catchmyself , you can try to take `interface/gemm.c` and `driver/level3/level3.c` and your kernels.

**Comment by catchmyself** [comment]
@xianyi , Thank for your answer. I just want to use cblas_sgemm function. I only want to compile the related source file. As you metioned above,  I need interface/gemm.c , driver/level3/level3.c and kernels files. I want to use the pure C codes files for the kernels in the kernel/generic directory.  Which files are need to be compiled.  What are the compiling options ?  You know, there is a lot of macro in the source files and they are hard to config for a new user.
