### ISSUE TITLE
Access violation on windows with an openblas compiled with visual studio

### ISSUE THREAD

**Issue by slegall56** [xianyi/OpenBLAS#773]
Dear xianyi,
I compiled OpenBlas with visual studio 2012 in X86 
But when I call cblas_sgemm with small matrices it works but with big matrices , I got an access violation.

Below a piece of code
float* AA = (float*)malloc(270000*sizeof(float)); // matrice of 10000x27
memset(AA, 0.1, 270000*sizeof(float));
float* BB = (float*)malloc(864*sizeof(float)); // matrice of 27x32
memset(BB, 0.2, 864*sizeof(float));
float* CC = (float*)malloc(320000*sizeof(float)); //Matrice of 10000x32

  cblas_sgemm(CblasColMajor, CblasNoTrans, CblasNoTrans, 10000, 32, 27,
    1.0, AA, 10000, BB, 27, 0.0, CC, 10000);

  free(AA);
  free(BB);
  free(CC);

This piece of code above works with openblas compiled MinGW but not with the version compile with visual studio

Any idea ?

**Comment by brada4** [comment]
can you point (using debugger) to the line in OpenBLAS code it crashes ( Assuming OpenBLAS 0.2.15)
there is nothing wrong with your BLAS call.

**Comment by slegall56** [comment]
Yes I am on OpenBlas 0.2.15
It crashes in gemm_beta.c line 62 when it tries to set c_offset1 to 0

do {
	  *(c_offset1 + 0) = ZERO;
	  *(c_offset1 + 1) = ZERO;
	  *(c_offset1 + 2) = ZERO;
	  *(c_offset1 + 3) = ZERO;
	  *(c_offset1 + 4) = ZERO;
	  *(c_offset1 + 5) = ZERO;
	  *(c_offset1 + 6) = ZERO;
	  *(c_offset1 + 7) = ZERO;
	  c_offset1 += 8;
	  i --;
	} while (i > 0);

"i" start value is 89478485 and it decreases to 44739243 then it crashes

**Comment by slegall56** [comment]
I tried to compile in x64 an it works fine. 
No access violation and 
"i" start value is 312 and not a weird value like 89478485. 

Unfortunatly I must compile in x86

**Comment by xianyi** [comment]
How do you compile OpenBLAS? By MinGW? or CMake+Visual Studio?

**Comment by slegall56** [comment]
By CMake+Visual Studio

**Comment by brada4** [comment]
Plain miscompilation.  How increasing any integer can bring value down?

**Comment by xianyi** [comment]
I can reproduce this bug now. Try to fix it.

**Comment by xianyi** [comment]
Please try the latest develop branch.

**Comment by slegall56** [comment]
Well done it works. 

Thank you very much
