### ISSUE TITLE
Enable and Optimize OpenBLAS for LinuxOne zEC13 (IBM mainframe)

### ISSUE THREAD

**Issue by edelsohn** [xianyi/OpenBLAS#775]
Enhance OpenBLAS to support IBM LinuxOne zEC13 processor including SIMD instructions in s390x 64 bit Linux environment.

**Comment by brada4** [comment]
I think both installations of your system can find C compiler knobs to enable those instructions compiling openblas with cc or netlib blas with fc.

**Comment by edelsohn** [comment]
OpenBLAS will work on Z in generic mode, but the issue is optimized kernels equivalent to x86 AVX enablement.

**Comment by brada4** [comment]
How exactly s390x is mainstream or popular? Like listed on ebay at a proce under that of 5 year old car?

**Comment by edelsohn** [comment]
Please troll somewhere else.

**Comment by brada4** [comment]
Follow me

**Comment by martin-frbg** [comment]
I expect this can be closed, as all its subtopics #836 #884 #992 #993 #1044 have been implemented ?
