### ISSUE TITLE
How to enable OpenMP with CMake ?(Windows and VS2013)

### ISSUE THREAD

**Issue by mrgloom** [xianyi/OpenBLAS#776]
How to enable OpenMP via CMake ?

I use Windows 10 and VS2013.

**Comment by xianyi** [comment]
I didn't test CMake & OpenMP on VS2013.

**Comment by brada4** [comment]
It is not a supported combiation by microsoft. Part of unsupported might be that no matter what options you enable OpenMP stays disabled.

**Comment by martin-frbg** [comment]
Googling "openmp vs2013 cmake" produces a number of pointers, including 
https://devtalk.nvidia.com/default/topic/911916/how-to-write-cmake-file-to-use-openmp-in-thrust-with-visual-studio-/ 
(and vs supposedly supports openmp from 2012 onwards)

**Comment by brada4** [comment]
If you do same action with Windows 10 and vs2013 you get to nice appcompat dialogs...

**Comment by mrgloom** [comment]
Is there any other way to enable more than one core on Windows build?

**Comment by martin-frbg** [comment]
Is using VS2013 an absolute requirement for your project ? 
While I can't seem to find anything definite for VS2013, there is
http://visp-doc.inria.fr/doxygen/visp-daily/tutorial-install-win10-msvc14.html
as an example of a larger project that builds using VS2015,cmake and openmp on Win10.
(and any appcompat dialog could also possibly point at a problem with the version of cmake used)
Other alternatives would seem to be clang and mingw  (windows port of the gcc compiler)

**Comment by xianyi** [comment]
By default, it is multi-threading on Windows.

2016-02-04 16:23 GMT-05:00 mrgloom <notifications@github.com>:

**Comment by mrgloom** [comment]
But how to enable it ?
Seems `set OPENBLAS_NUM_THREADS=4` don't work.

I use this fork of caffe https://github.com/willyd/caffe-builder
openblas seems to build by mingw https://github.com/willyd/caffe-builder/blob/master/cmake/packages/OpenBLAS.cmake
When I run caffe in cpu mode only one core is working.

On ubuntu when I build caffe with openblas and use `export OPENBLAS_NUM_THREADS=4` it use all cpu's.

**Comment by brada4** [comment]
It does not "build" anything of OpenBLAS, it just downloads and unzips 0.2.14 DLLs.
You dont have to set OPENBLAS_NUM_THREADS at runtime to enable threading. (and make sure respective OMP_ and GOTO_ variables are not set)
Can you peek with process explorer if after starting your program and doing anything calling BLAS/LAPACK you see 3 extra threads created in that process? At least I see so with windows numpy adding some useless 5min sleep before program exit.

**Comment by mrgloom** [comment]
Yes, you are right. I was confused by `OpenBLAS needs MinGW to be compiled.`

I download `process explorer` https://technet.microsoft.com/ru-ru/sysinternals/processexplorer.aspx

But I don't know where to look at *.exe threads.
I tried right click on caffe.exe properties->Threads

Here is result 

![img](https://cloud.githubusercontent.com/assets/4003908/12872588/035e5c16-cdb8-11e5-9c20-375db41ee208.PNG)

**Comment by brada4** [comment]
It detected 2 CPUs in your machine. (i.e 1 main thread and one more thread), see driver/others/blas_server.c for explanation. E.g. on 16-core server CPU you get 15 extra threads

Now lets try to see why openblas detected different number of CPUs than you thought.

a) what is your CPU (all numbers, so that it can be found in intel ARK and AMD product DB)
b) does it change anything if you replace openblas & mingw gfortran DLLs to v0.2.15 where your cafe installs them?
c) how many CPUs you can count in device manager and in %NUMBER_OF_PROCESSORS% variable, and in _NUM_THREADS variables? And then in running program (i.e in environment tab of this process in your process explorer, not system's environment)

**Comment by mrgloom** [comment]
I tested it on [Core 2 Duo E8500](http://ark.intel.com/ru/products/33911/Intel-Core2-Duo-Processor-E8500-6M-Cache-3_16-GHz-1333-MHz-FSB)

In device manager I see 2 CPU and `echo %NUMBER_OF_PROCESSORS%` give me 2.

I don't know where to find `_NUM_THREADS`

Also I tested it on [Core i5 M 430](http://ark.intel.com/ru/products/43537/Intel-Core-i5-430M-Processor-3M-Cache-2_26-GHz)
In device manager I see 4 CPU and `echo %NUMBER_OF_PROCESSORS%` give me 4.

![img4](https://cloud.githubusercontent.com/assets/4003908/12874715/2b84290a-cdea-11e5-921b-07adce6c2253.PNG)

But CPU utilization is still about 50%.

Same with v0.2.15.

**Comment by brada4** [comment]
There is environment tab in process properties picture you show above. No need to check it - CPU is detected correctly and correct number of threads is started.
In your last picture - 4*6 pieces of work are in parallel while 12 are serial. [Which in turn means that with 100 CPUs it will become 3x faster than single CPU version](https://en.wikipedia.org/wiki/Amdahl's_law)
Without resorting to heavy profiling I'd lean to tell that 1/3 of work that is not parallel is outside OpenBLAS and cannot be improved by OpenBLAS.
You can try different windows power settings like locking CPU cores at top speeds or disabling hyperthreads, it may yield small improvement but the single-threaded code will always be there to make it as slow as it is .

**Comment by mrgloom** [comment]
Maybe you are right, but on Ubuntu I see that 2 cores are 100% using `htop`.

Can it help if I upload builded binaries?

**Comment by brada4** [comment]
No need, nobody can process those. You need to dig down and reduce test case to few BLAS/LAPACK calls.
There is no problem with OpenBLAS. OpenCV calls BLAS routines with very small sample sizes (5..50kB with 100x100 images as in examples), which means that most single-threaded OpenBLAS is optimal for demos (but you can run a copy on each CPU), and probably worth trying for other cases.

Should it show up as measurable regression (i.e multiprocessor version slower than single-processor) it can be looked at.

**Comment by brada4** [comment]
I think you misunderstood something. All cores are enabled properly, no build options needed (especially when nothing is being built), just that data matrix supplied as parameter to OpenBLAS is so small that it cannot be efficiently processed on multiple CPU cores.

**Comment by mrgloom** [comment]
No, I understand you correctly. Just add this thread to my previuosly asked question in `willyd/caffe-builder` to help maintainer.

**Comment by brada4** [comment]
You can close this and other issue ticket. Both products already have and use what you ask for.
