### ISSUE TITLE
Why does OpenBLAS not support sofftp with ARMv7

### ISSUE THREAD

**Issue by jainanshul** [xianyi/OpenBLAS#777]
As per https://github.com/xianyi/OpenBLAS/issues/363#issuecomment-117226070 softfp is not supported with ARMv7. I tested it on the device and I do get a segmentation fault. Wondering why is softfp only supported for ARMv5?

**Comment by brada4** [comment]
ARMv5 is C-only. You can compile it with exact -march flag for your architecture to get optimal code. ARMv7 kernels gets all enhancements from use of VFP which you dont have. Also you must measure if libm or gcc builtins are faster (-fno-builtins vs -fbuiltins). Probably it is best to avoid double precision alltogether as one double precision instruction will be emulated in 30-40 int32 instructions.

**Comment by xianyi** [comment]
For ARMv7, we write hard fp ABI in assembly kernels. If we support softfp ABI, we must change these assembly manually. It can be done but lots of work.

**Comment by jainanshul** [comment]
Thanks for your replies. I change the target to ARMV5 and I don't see any crash with softfp. However the performance is abysmal 27secs to load and predict using caffe with softp openblas vs 7secs with hardfp openblas.

Does OpenBLAS support 64bit ARM architecture?

**Comment by xianyi** [comment]
The ARMv5 is naive C kernels. Therefore, it is very slow. 

We support ARM 64bit including Cortex-A57.

**Comment by brada4** [comment]
Yes, performance is abysmal as your CPU lacks floating point support and everything is done in integer ALU. 4 instructions to emulate floating point instruction is very very reasonable. 

You can try -fbuiltins - maybe GCC can optimize something, but will not get better than 3x slowdown.

Example: http://www.jhauser.us/arithmetic/SoftFloat.html find 32bit mul in integer c. 4 instructions according to my brain's optimistic C compiler (or 3 if you really really dont do anything about NaNs.

**Comment by xianyi** [comment]
@brada4 , there are three FP ABI mode `soft`, `softfp`, and `hard`.

The `soft` uses software FPU (as you mentioned) and `soft` calling convention.
The `softfp` uses hardware FPU and compatible `soft` calling convention.
The `hard` uses hardware FPU and different calling convention. The `hard` calling convention is passing the floating point argument by FP registers.

OpenBLAS uses `hard` FP ABI mode. It conflicts with `soft` and `softfp`.

**Comment by brada4** [comment]
...which is a call to libm which may or may not use FPU which may or may not exist.

**Comment by brada4** [comment]
Actually "does not support" claim is now void as per @jainanshul
It is hard to tell why is it so slow without pieces of code. softfp slows down all calls involving floating point arguments. Depending of GCC flags you chose it might be much more or much less of such calls. Without code or compiler arguments - there is no issue.

**Comment by jainanshul** [comment]
@brada4 well openBLAS crashes with ARMv7 and softfp support so I would still say openBLAS doesn't support softfp with ARMv7.

**Comment by brada4** [comment]
ARMv7 is name of Debian architecture, i.e hardfp
ARMv5 means any ARM, just like Prescott means Any x86.

 
--------------------------------------------
On Mon, 2/8/16, Anshul Jain <notifications@github.com> wrote:

 Subject: Re: [OpenBLAS] Why does OpenBLAS not support sofftp with ARMv7 (#777)
 To: "xianyi/OpenBLAS" <OpenBLAS@noreply.github.com>
 Cc: "brada4" <bradatajs@yahoo.com>
 Date: Monday, February 8, 2016, 3:03 AM
 
 @brada4 well openBLAS
 crashes with ARMv7 and softfp support so I would still say
 openBLAS doesn't support softfp with ARMv7.
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by lygstate** [comment]
What's the point of ARMV6?

**Comment by martin-frbg** [comment]
> What's the point of ARMV6?
Older models of Raspberry Pi and similar (support was added in early 2013) ?

**Comment by lygstate** [comment]
Does it also use the hard ABI?

**Comment by martin-frbg** [comment]
I'm not that experienced with ARM coding, but the assembly used in the v6-specific routines under kernel/arm look suspiciously similar to the v7 counterparts (and both were written by the same developer), so probably yes.

**Comment by epicstar** [comment]
@xianyi what is the current timeline for this feature to be complete? Thanks for working on this btw.

**Comment by martin-frbg** [comment]
Expected to be resolved through #1221, so closing
