### ISSUE TITLE
Skylake i7-6700HQ on MSI GS60-6QE using Torch7

### ISSUE THREAD

**Issue by fusiller** [xianyi/OpenBLAS#781]
Hello xianyi,

just a quick note to report a strange behavior with the mentioned hardware.
First built torch with the current openblas package (received from apt-get install)
Then removed package and git cloned it (producing a 2.16 library)

In both cases torch was unable to perform normally. As a sanity check I run Andrej Karpathy's char-rnn. Running the exact same code took about 8 seconds per batch with OpenBLAS installed on this MSI laptop, 1.8 seconds with the standard GNU BLAS, and approx 0.7-1.2 sec with OpenBLAS on an old Intel Core2 Duo machine.

I had to use MKL but I am happy to help solve the issue if I can help / trace / report something to you.
As an indicator the same code is running in 0.15 to 0.50 sec per batch with MKL on this laptop, so obviously 8 seconds means something is going really crazy there.

 *-cpu
          product: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
          vendor: Intel Corp.
          physical id: 1
          bus info: cpu@0
          size: 2600MHz
          capacity: 2600MHz
          width: 64 bits
          capabilities: fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp x86-64 constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch ida arat epb pln pts dtherm hwp hwp_noitfy hwp_act_window hwp_epp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 cpufreq

With my highest consideration for your amazing work.
Regards,
Alex

**Comment by xianyi** [comment]
Thank you for the feedback.

Could you run some benchmark at `OpenBLAS/benchmark`? e.g. sgemm, sgemv.

**Comment by fusiller** [comment]
Sure.
I just built OpenBLAS simply with make NO_AFFINITY=1 USE_OPENMP=1
I obtained libopenblas_haswellp-r0.2.16.dev.a and libopenblas_haswellp-r0.2.16.dev.so
Then I built and ran all of the benchmarks except for smallscaling that is generating errors.
I only provide GOTO and MKL for the moment. For some reason the current Atlas under Ubuntu does not include libptcblas nor libptf77blas.
The results are in the file attached ( for each of them GOTO runs first, then MKL).
Hope it helps.
Best regards,
Alex
[bench.log.txt](https://github.com/xianyi/OpenBLAS/files/143024/bench.log.txt)

**Comment by martin-frbg** [comment]
MFlops numbers appear to be all over the place in that log, often zero or infinite for both builds. Unstable clocksource (time running backwards occasionally) ?

**Comment by fusiller** [comment]
I did not notice it. For the moment I am not even using the internet to set the time, it is in manual mode.
Running Ubuntu 14.04.3 LTS by the way.
I shall investigate and let you know asap.

**Comment by jeromerobert** [comment]
@fusiller could you run your Torch benchmark program this way:
```
sudo perf record ...
perf report > report.txt
```
and make the report.txt file available to us so we can see where it is spending time ?
For more about `perf` see: <https://perf.wiki.kernel.org>.

**Comment by fusiller** [comment]
Regarding the clocksource it doesn't seem that unstable. Added some assert(time1>=0) in a few of the benchmark .c source and did not have trouble.
I traced down tv_usec for start and stop and they were similar on occasions. Are you sure your library is just not too quick ;) ?
My current clocksource is tsc.

**Comment by fusiller** [comment]
Guys,
I guess this is good news but I could not reproduce the issue with the dev OpenBLAS.
After careful environment checking and Torch rebuilding I can even confirm that performance is better than with MKL.
I could reproduce the very slow behavior with the libopenblas-dev package received by apt-get
I suspect I got this package https://launchpad.net/ubuntu/+source/openblas

Just for information here are the perf reports in the various cases.

Many thanks to all of you.
The issue is not an issue any longer I suppose.

Alex
[report_devopenblas.txt](https://github.com/xianyi/OpenBLAS/files/143527/report_devopenblas.txt)
[report_mkl.txt](https://github.com/xianyi/OpenBLAS/files/143525/report_mkl.txt)
[report_openblas.txt](https://github.com/xianyi/OpenBLAS/files/143526/report_openblas.txt)

**Comment by brada4** [comment]
with openblas 0.2.8 you will get better results with OPENBLAS_CORETYPE=Sandybridge (instead of default Prescott for unrecognized CPU)
That release predates AVX2, half speed is duly expected, just like if you use MKL predating AVX2.
Can you try to compare to pthread -dev build (i.e without parameters) and to any -dev build with OMP_NUM_THREADS=1  just for comparison?

**Comment by fusiller** [comment]
@brada4 just to make sure I understand clearly
- i should use the latest dev version available from github
- make one build without any parameter (not even NO_AFFINITY=1 USE_OPENMP=1)
- make one build with OMP_NUM_THREADS=1
For each build I run my Torch benchmark and let you know (I shall even perf it)

**Comment by brada4** [comment]
Yes, you got me right. 
- Anything that identifies your CPU is good
- It should build pthread version (if it is better than OpenMP - enjoy)
- It is environment variable to set before running any OpenBLAS-enabled program. If you get better performance without threading - some threading cutoff is misplaced (then it is a bug, but you know a workaround, but nothing can be done to improve unless you show parameters BLAS SGEMM is called with. If you find performance regression here just tell it - i will help you with debugger (basically you must set breakpoint at sgemm_ or sgemm or so and read parameters) )
