### ISSUE TITLE
Android fails to run basic example compiled with openblas (in emulator)

### ISSUE THREAD

**Issue by shkyang** [xianyi/OpenBLAS#787]
Hi,

I'm running into the following error: arm-linux-androideabi-gcc -mfloat-abi=hard ex.cpp -I/opt/arm-tools/include  /opt/arm-tools/lib/libopenblas.a
arm-linux-androideabi/bin/ld: error:  **uses VFP register arguments, output does not**

ex.cpp is a simple example taken from the web:
#include <cblas.h>
#include <stdio.h>
int main()
{
  int i=0;
  double A[6] = {1.0,2.0,1.0,-3.0,4.0,-1.0};
  double B[6] = {1.0,2.0,1.0,-3.0,4.0,-1.0};
  double C[9] = {.5,.5,.5,.5,.5,.5,.5,.5,.5};
  cblas_dgemm(CblasColMajor, CblasNoTrans, CblasTrans,3,3,2,1,A, 3, B, 3,2,C,3);

  for(i=0; i<9; i++)
    printf("%lf ", C[i]);
  printf("\n");
  return 0;
}

I compiled the android toolchain following instructions here: http://developer.android.com/ndk/guides/standalone_toolchain.html

make-standalone-toolchain.sh --arch=arm --platform=android-21 --install-dir=/tmp/my-android-toolchain

I compiled OpenBlas following instructions here: https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android

make HOSTCC=gcc CC=arm-linux-androideabi-gcc NO_LAPACK=1 TARGET=ARMV7

I have noticed that this error goes away when I edit Makefile.arm, and replace -mfloat-abi=hard with -mfloat-abi=soft (had to do this for building and linking ex.cpp as well).

Reading the ABI compatibility section of the standalone toolchain page: 
If you want to target the armeabi-v7a ABI, you must set the following flags:
CFLAGS= -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16

I think that while I've built ex.cpp, the binary will be slower than if it was build to use the FPU. Could someone help me figure out how to build this properly?

Thanks,
Kevin

**Comment by brada4** [comment]
Is that ld error complete? There should be some library name + preceding command line at least.

**Comment by shkyang** [comment]
Here is the full output:
 
/tmp/my-android-toolchain/bin/arm-linux-androideabi-gcc -mfloat-abi=hard  ex.cpp -I/opt/arm-tools/include  /opt/arm-tools/lib/libopenblas.a
/private/tmp/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /var/folders/5l/kndj2q_1371gmqd_sr703fl40000gn/T//ccKe1jnm.o uses VFP register arguments, output does not
/private/tmp/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /opt/arm-tools/lib/libopenblas.a(cblas_dgemm.o) uses VFP register arguments, output does not
/private/tmp/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /opt/arm-tools/lib/libopenblas.a(dgemm_nn.o) uses VFP register arguments, output does not
/private/tmp/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /opt/arm-tools/lib/libopenblas.a(dgemm_nt.o) uses VFP register arguments, output does not
/private/tmp/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /opt/arm-tools/lib/libopenblas.a(dgemm_tn.o) uses VFP register arguments, output does not
/private/tmp/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /opt/arm-tools/lib/libopenblas.a(dgemm_tt.o) uses VFP register arguments, output does not
/private/tmp/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /opt/arm-tools/lib/libopenblas.a(dgemm_thread_nn.o) uses VFP register arguments, output does not
/private/tmp/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /opt/arm-tools/lib/libopenblas.a(dgemm_thread_nt.o) uses VFP register arguments, output does not
/private/tmp/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /opt/arm-tools/lib/libopenblas.a(dgemm_thread_tn.o) uses VFP register arguments, output does not
/private/tmp/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /opt/arm-tools/lib/libopenblas.a(dgemm_thread_tt.o) uses VFP register arguments, output does not
/private/tmp/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /opt/arm-tools/lib/libopenblas.a(memory.o) uses VFP register arguments, output does not
/private/tmp/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /opt/arm-tools/lib/libopenblas.a(xerbla.o) uses VFP register arguments, output does not
/private/tmp/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /opt/arm-tools/lib/libopenblas.a(blas_server.o) uses VFP register arguments, output does not
/private/tmp/my-android-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: /opt/arm-tools/lib/libopenblas.a(dgemm_beta.o) uses VFP register arguments, output does not
collect2: error: ld returned 1 exit status

**Comment by brada4** [comment]
Are you sure these 2 are set?
```
TARGET_CFLAGS += -mhard-float -D_NDK_MATH_NO_SOFTFP=1
TARGET_LDFLAGS += -Wl,--no-warn-mismatch -lm_hard
```

**Comment by shkyang** [comment]
Looking at the build output, I don't think I've set those properly, how can I set those, besides editing Makefile.arm?

**Comment by shkyang** [comment]
Ok, I think I've figured it out, those flags are meant for when I compile and link ex.cpp, not for compiling the existing library. I'll go ahead and close the issue.

**Comment by shkyang** [comment]
Closed it a little too fast. I've edited the OpenBLAS wiki page with new build instructions so I can build ex.cpp. 

The problem now is I cannot run the compiled executable, I can get printouts before the call to cblas_dgemm, but not after.

Here's how I'm running it.

1. I'm using android emulator, with default choices for spinning up a new avd.
2. adb push ./a.out /
3. adb shell
4. ./a.out

Here's I get that the shell exited (no printouts). I don't have a segfault, but I don't get the expected printout of the matrix either.

**Comment by martin-frbg** [comment]
So are you building with hardfp or softfp option now ? An emulator may not show the exact same behaviour as the actual hardware, which might explain the exit without an accompanying segfault.
From #777 I understand that the assembler notation used in the optimized kernels would have to be completely different for softfp, hence the current requirement for building everything for the hardfp API as that is what is used in the OpenBLAS routines.

**Comment by shkyang** [comment]
I figured this out. I was mixing up hard and soft floating point in the compiles. The issue went away after I cleaned and started from scratch.

**Comment by lygstate** [comment]
To be clear Android are already removed the armeabi-v7a-hard
