### ISSUE TITLE
Do you have plan to support Raspberry Pi 3?

### ISSUE THREAD

**Issue by guangwei** [xianyi/OpenBLAS#792]

**Comment by guangwei** [comment]
The cpu of Raspberry Pi 3 is BCM2837, it's a coretex-a53 core, can we use the cortex-a57 building block?

**Comment by brada4** [comment]
Wikipedia says instruction sets are identical... Why dont you try and report any problems?

**Comment by xianyi** [comment]
I think you can use Coretex-A57 kernel. The performance may be not optimized.

**Comment by guangwei** [comment]
@xianyi  thank you for your information
