### ISSUE TITLE
POWER8 VSX BLAS 3 single precision

### ISSUE THREAD

**Issue by edelsohn** [xianyi/OpenBLAS#794]
Optimize BLAS 3 single precision for POWER8 VSX

**Comment by wernsaar** [comment]
Hi,

the sgemm- strmm- cgemm- and ctrmm-kernels are now in the repository,
branch develop.

The sgemm performance is 40 Gflops on 1 core
The cgemm performance is 39 Gflops on 1 core

Best regards
Werner
