### ISSUE TITLE
POWER8 VSX BLAS 1/2 single precision

### ISSUE THREAD

**Issue by edelsohn** [xianyi/OpenBLAS#796]
Optimize BLAS 1/2 single precision for POWER8 VSX

**Comment by seyi** [comment]
Hi,, can I get one of these processors for development?

**Comment by dzabawa** [comment]
I'm seeing several power8 implementations of level 1/2 routines. Is there a clarification of what's yet needed, including possible improvements to existing code?

**Comment by martin-frbg** [comment]
Seeing that none of the original participants appears to be available at the moment, my humble view is
that (a) wernsaar implemented (most of?) the desired functions in the weeks following edelsohn's request (b) #950 is directly related (c) some followup can be found in various topics on the developer mailing list linked from #795 - including some benchmarks and recent comments on perceived coding issues that _apparently_ went without replies.

**Comment by barkovv** [comment]
@edelsohn 
What the status of this issue? It seems that many of functions are already implemented (this is already mentioned by @martin-frbg ).

**Comment by edelsohn** [comment]
The initial implementation contained some bugs and performance issues that never were addressed by the original author. The issue never was closed.

I robust, optimized solution in OpenBLAS would be great. The bounties need to be distributed among all of the people who contributed to the effort.

**Comment by JulianVolodia** [comment]
@edelsohn @martin-frbg still, any concerns? Is there any other place where discuss happens?

But... @edelsohn about bounty. Is there any clue how to do it practically? ;)

**Comment by edelsohn** [comment]
What's the specific question?

**Comment by quickwritereader** [comment]
Guys, I'm going to do this task. Actually I took this 2-3 weeks ago,  but due to some personal issues I haven't started yet. I forgot to comment here about start.

**Comment by quickwritereader** [comment]
#1963 I decided to provide missing Blas1 kernels implemented with vector builtins . 
{saxpy, caxpy, cdot, crot(refactored version of srot),isamax ,isamin, icamax, icamin}
Performance is far better than using base c kernels.

I will focus on sgemv and cgemv pairs which are missing from Blas2.   

And also for some Blas1 I try to do hand written assembly to see if I can improve performance further

**Comment by quickwritereader** [comment]
all these missing important kernels implemented using vector c code
saxpy.c ---vector---
caxpy.c --vector--
cdot.c  --vector --
crot.c    ---refactored srot inline assembly ---
sgemv_n.c --vector --
cgemv_n.c --vector --
sgemv_t.c --vector --
cgemv_t.c --vector --
isamax.c,isamin.c --vector--
icamax.c,icamin.c --vector--

**Comment by quickwritereader** [comment]
Blas1 results compared to generic kernels 
I wrote script for plot. Also it can plot in sixel supported terminal emulators [bench_plot.py](https://gist.github.com/quickwritereader/ab81299eb2ec48ac4b1b5ac4412a32a7)  
export OMP_NUM_THREADS=1
export OPENBLAS_LOOPS=10
*_base are generic ones   
![](https://i.imgur.com/71qTAVK.png)

**Comment by edelsohn** [comment]
Impressive gains. Vector C code means vector intrinsics, not inline assembly?

Vector intrinsics should leverage instructions at each architecture level without re-writing.

**Comment by quickwritereader** [comment]
yes I used vector codes only. Most times I avoided using even intrinsics. As I noticed gcc did decent job

**Comment by edelsohn** [comment]
C code with Intrinsics should be more than enough for BLAS 1/2. I'm a little concerned about the amount of inline assembly code in the IBMz work.

The main area that needs focus with each processor revision seems to be BLAS 3.

**Comment by quickwritereader** [comment]
yes there is not any great gain  using inline for blas 1/2 .
Sometime I also noticed that gcc 7.2 did not include some vector intrinsics like this one .
[mergee mergeo](https://github.com/xianyi/OpenBLAS/pull/1994/files#diff-18137ea0fd51adf9ad0751abba45ed3f) 
I tried it for icamax but guess included vec_perm with mask yielded better result so I just ifdef-ed it but keep it for future.

**Comment by quickwritereader** [comment]
Some power blas1 vector codes blas2 gemv  easily could be translated for Ibm z series. But under hood there is one difference that z13 has only 32 vector registers, but  power8 has 64 vector registers so  compiler have many options

**Comment by quickwritereader** [comment]
here are gemv results. please also note that actually it is compared with hand written assemblies prefixed _old ( not generic c code. )
_
![](https://i.imgur.com/NlobMxz.png)
#1994

**Comment by quickwritereader** [comment]
I think if vector codes considered sufficient then most important kernels are already implemented. and also as @edelsohn said it will easily propagated to new series as no assembly was used.

**Comment by quickwritereader** [comment]
@edelsohn I believe this issue could be closed. Please check and let me know if I need to do anything else
thanks

**Comment by edelsohn** [comment]
Any idea why sgemv_n drops below the original implementation at large sizes?

Other than that, it looks great.

**Comment by quickwritereader** [comment]
right recall I should  investigate it to see if I can make it a little stable across size. 
- first thing to do is to check NBMAX mem size to solve it. 
- if not I could try for inner 8x8 or 4x4 floats,, currently it is 4x8 
I only used perf to see main usage percentage. It showed that  4x8 kernel was underload for both small and big sizes. afaik I also have ibmsdk tools but  I use it rarely

**Comment by quickwritereader** [comment]
So far I noticed that making NBMAX=4096 made it stable:
here are results for tests from 100 to 16000 stepped 200:
![](https://i.imgur.com/gjoUe2s.png)

current 2048 is yellow
4096 is red
old assembly is pink
Scripts:
[bench_plot](https://gist.github.com/quickwritereader/ab81299eb2ec48ac4b1b5ac4412a32a7)
(for command line usage see help. it  plots when terminal supports sixel or saves into png)
within jupyter notebook
``` python
import bench_plot 
import glob
a=glob.glob('sgemvn/*')
print(a)
bench_plot.plot_files(*a,sixel=False)
```
Run from OpenBlas directory
[bash script for running old kernel](https://gist.github.com/quickwritereader/05107ff728c5aabb38c387bb04721256)
[nbmax script](https://gist.github.com/quickwritereader/785179f2bebeb32ae570b43582f8839d)

**Comment by edelsohn** [comment]
It looks a lot better at 4096 than 2048.

The Power files seem to define NBMAX as 2048 and the x86-64 files seem to define NBMAX as 4096.  Should the default be bumped for Power?

**Comment by quickwritereader** [comment]
Yes I think we need to increase them. I gonna try 8x8 kernel too to see if there be any improvement. . For transposed I uploaded 8x8  but default is still 4x8. 
What I learnt that sometimes trying to understand the reason behind kernel is hard and you can't come with calculated tuned parameter. So just choosing the winner among tested ones is the way to go unless you have an alternative algorithm or thinking

**Comment by quickwritereader** [comment]
@edelsohn #1996 Ok I increased it to 4096.  
And also added sgemvn with 8x8 blocking. It did not perform good enough so that I could make it default. Plus strangely small reordering inside 8x8 loop made gcc to produce a little clever code. So finally I decided to go with small blocking but uploaded this kernel too. Maybe it be helpful when there be any need to switch to inline assembly to produce the most desired output in future.

**Comment by edelsohn** [comment]
Okay. Thanks for testing the variants and updating NBMAX.
I think we can declare victory.

**Comment by quickwritereader** [comment]
I'm glad that after long pause I could return and did this work this month.

**Comment by quickwritereader** [comment]
@martin-frbg I believe this issue could be closed as initial support

**Comment by martin-frbg** [comment]
Yes, thanks a lot for your work. I had only assumed edelsohn would close it as it was "his" issue ticket.
