### ISSUE TITLE
Compile OpenBLAS for Android problem

### ISSUE THREAD

**Issue by zhaozj89** [xianyi/OpenBLAS#804]
Hi, xianyi,

I am using Ubuntu to compile OpenBLAS for Android platform, and follow exactly the command:

`export PATH=/tmp/my-android-toolchain/bin:$PATH`

`make HOSTCC=gcc CC=arm-linux-androideabi-gcc NO_LAPACK=1 TARGET=ARMV7`

by changing the right toolchain path. But **make** complains that it cannot find "stdio.h" which I think is located in NDK Android platform folder, in my case, is `android-ndk-r10e/platforms/android-19/arch-arm/usr`.

Could you tell me how to modify the **Makefile** to let it find the right Android platform dependency? It is too complicated for me to do it myself. Thanks a lot.

**Comment by zhaozj89** [comment]
I think I have find the answer [1]. Do not know how to delete this issue. Sorry.

[1] http://developer.android.com/intl/zh-cn/ndk/guides/standalone_toolchain.html

**Comment by santo4ul** [comment]
I was able to build libopenblas.so for Android using the below simple commands,

**Step 1:** Install standalone toolchain as given [here](https://developer.android.com/ndk/guides/standalone_toolchain) (Choose your API level accordingly)
**Step 2:** export PATH=$PATH:/your/toolchain_dir/bin/
**Step 3:** Make OpenBLAS using the below make command
`make TARGET=ARMV8 ONLY_CBLAS=1 AR=aarch64-linux-android-ar CC="aarch64-linux-android-clang" HOSTCC=gcc -j4`


Thanks,
San
