### ISSUE TITLE
Use BUILD_LAPACK_DEPRECATED=1 by default

### ISSUE THREAD

**Issue by nalimilan** [xianyi/OpenBLAS#807]
OpenBLAS 0.2.16 does not include deprecated LAPACK symbols by default. This strikes me as a bit extreme, given that some of these have only been deprecated since version 3.6. This triggered build failures in Fedora. Don't you agree that `BUILD_LAPACK_DEPRECATED` should default to `1`?

**Comment by xianyi** [comment]
I see. I will enable it by default on next release.

**Comment by nalimilan** [comment]
Thanks!

**Comment by nalimilan** [comment]
Actually I would say this justifies a minor release shortly. Indeed, distribution packagers are going to switch to the new version without noticing that they introduce a major ABI break, which will waste a lot of time.

**Comment by xianyi** [comment]
I already created release-0.2.17 branch. After some tests, I will release 0.2.17.

**Comment by xianyi** [comment]
Released 0.2.17 version.
