### ISSUE TITLE
[VS2013] Access violation in ntdll.dll while using static compiled cblas_sgemv

### ISSUE THREAD

**Issue by theoractice** [xianyi/OpenBLAS#810]
Steps to reproduce this issue:

1. Use CMake to generate VS2013 solution files using default settings.
2. Open the OpenBLAS solution and change the configurations to compile as **Win32 static library** (change **/MD** to **/MT**), then compile.
3. Compile and run the code below, linking against the static OpenBLAS library in step 2:

```
#include <Windows.h>
#include <opencv2/opencv.hpp>
#include <cblas.h>

using namespace std;
using namespace cv;

int main(int argc, char* argv[])
{
	LARGE_INTEGER freq, start, end;

	QueryPerformanceFrequency(&freq);

	RNG &rng = theRNG();
	rng.state = getTickCount();

	float alpha = 1.f, beta = 0;
	int m = 25, p = 10000, n = 1;

	Mat_<float> A(m, p, CV_32F), B(p, n, CV_32F);
	Mat C1 = Mat(m, n, CV_32F, 0.0);
	Mat C2 = Mat(m, n, CV_32F, 0.0);
	rng.fill(A, RNG::NORMAL, 1, 100);
	rng.fill(B, RNG::NORMAL, 2, 50);
	float *src1, *src2, *src3, *src4;
	src1 = (float *)A.data;
	src2 = (float *)B.data;
	src3 = (float *)C1.data;
	src4 = (float *)C2.data;

	QueryPerformanceCounter(&start);
	cblas_sgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans, m, n, p,
		alpha, src1, p, src2, n, beta, src3, n);
	QueryPerformanceCounter(&end);
	cout << "cblas_sgemm: " << (end.QuadPart - start.QuadPart) / (float)freq.QuadPart * 1000.f << " ms " << endl;
	cout << C1 << endl;

	QueryPerformanceCounter(&start);
	cblas_sgemv(CblasRowMajor, CblasNoTrans, m, p, 
		alpha, src1, p, src2, n, beta, src4, n);
	QueryPerformanceCounter(&end);
	float duration = (end.QuadPart - start.QuadPart) / (float)freq.QuadPart * 1000.f;
	cout << "cblas_sgemv: " << (end.QuadPart - start.QuadPart) / (float)freq.QuadPart * 1000.f << " ms " << endl;
	cout << C2 << endl;

	return 0;
}
```
When using static linking, cblas_sgemm works fine while cblas_sgemv encounters **access violation** in ntdll.dll. However when using dynamic linking (don't change anything CMake generated), both cblas_sgemm and cblas_sgemv works as expected. The same applies to cblas_dgemm/cblas_dgemv (as for now I only tested these).
**Note:** Reduce p in the code above from 10000 to 100 seems to eliminate all access violations. Is this somehow related to issue #773?

I am compiling and testing OpenBLAS on this computer:
Intel T8300 / Windows 10 64bit / 4GB RAM
When used on several other systems below, the access violation still occurs:
Intel Z3735f / Windows 8 32bit / 1GB RAM
intel Xeon E3-1230 V2 / Windows 7 64bit / 16GB RAM

**Comment by xianyi** [comment]
Is this bug on both 32-bit and 64-bit Visual Studio project? Or just 32-bit.

**Comment by theoractice** [comment]
Hi xianyi,
Just tried to compile the whole program as 64-bit, the access violation persists :(

**Comment by theoractice** [comment]
Debugger shows the program crashes at blas_server_win32.c, line 361:
  
  EnterCriticalSection(&pool.lock);

  if (pool.queue) {
    current = pool.queue;
    while (current -> next) current = current -> next;
    current -> next = queue;
  } else {
    pool.queue = queue;
  }

  LeaveCriticalSection(&pool.lock);



theoractice@sina.com
 
From: Zhang Xianyi
Date: 2016-03-20 21:11
To: xianyi/OpenBLAS
CC: Theoractice
Subject: Re: [OpenBLAS] [VS2013] Access violation in ntdll.dll while using static compiled cblas_sgemv (#810)
Is this bug on both 32-bit and 64-bit Visual Studio project? Or just 32-bit.

**Comment by xianyi** [comment]
Thank you for the feedback. I didn't test MSVC static library before.

**Comment by brada4** [comment]
If you link outer .EXE with MD you have MSVCRT*.DLL linked twice in program. It is certain to cause conflicts.

**Comment by theoractice** [comment]
@brada4 Please recheck the post above. This access violation occurs when using static linking to a static library so it is nothing related to /MD and MSVCRT.
When linking EXE with /MD and MSVCRT, the whole program works fine. I don't know what you mean by linking MSVCRT twice, but /MD is the CMake default setting used by countless other projects. I don't see any conflicts here.

**Comment by brada4** [comment]
It occurs because P is 100x bigger than any matrix you allocate as argument, so heap is plundered to no recognition when blas call exits.

**Comment by theoractice** [comment]
@brada4 Thanks for another guess, however that cannot explain why shared library version works. Also changing heap size (I even tried 100MB) cannot fix the problem.
I also tried remove OpenCV completely from the test code above, but to no avail. So the problem is not OpenCV related.

**Comment by theoractice** [comment]
**Find a workaround**: Call openblas_set_num_threads(openblas_get_num_procs()); explicitly before any OpenBLAS call, then no more access violation! Maybe there is a easy way to fix this problem.

**Comment by brada4** [comment]
Not really, you tell BLAS matrix is 100x bigger than one you just allocated, so it just goes writing 99 times initial allocation after your data. It will not help even if you set 100TB heap, you still corrupt it. You need call parameters to reflect data exactly.

**Comment by brada4** [comment]
can you get backtrace of calls leading to the issue?
I think access violation is caught in event logs too.
Your windows licence forbids you to debug ntdll.dll, but still symbol name will be 100x better than offset.

**Comment by theoractice** [comment]
@brada4 Sorry, but are you saying I am calling OpenBlas incorrectly? Actually the original issue occurs in Armadillo, I traced the code down and locate cblas_sgemv. The test code is a modification of [code here](https://groups.google.com/forum/#!topic/openblas-users/llSRoHCWPjE), where the author uses very large parameters. If you read those code, you can see we both used variables like m, n and p to indicate matrix size (not 10000 and 100), so where is the 100x thing?
And of course, my original program (which uses Armadillo heavily) works fine now after the openblas_set_num_threads call.

From the debugger trace posted above, It seems that the critical section is not initialized properly. Will report later if I find a solution.

**Comment by theoractice** [comment]
Well, the reason is simple: when compiled as static library, the DllMain function (in memory.c) which calls gotoblas_init() is not called. 

AFAIK, there are two solutions: 
1. Split out and export gotoblas_xxxx that DllMain calls, so that they can be called by user in statically linked programs. however this seems unstable if the thread is terminated via TerminateThread, also the explicit call is inconvenient.
2. I also tried TLS relevant technique mentioned [here](https://sourceware.org/ml/pthreads-win32/2008/msg00028.html) and it seems to work, however still need some more test.

**Comment by theoractice** [comment]
pull request #813 sent.

**Comment by xianyi** [comment]
@theoractice , cool, thank you for the patch.
