### ISSUE TITLE
on_process_term

### ISSUE THREAD

**Issue by carlkl** [xianyi/OpenBLAS#815]
Q: is the code for `on_process_term` recently included (adapted) https://github.com/xianyi/OpenBLAS/commit/61cf8f74d9e23757844dc1e0d2a04e641a23fb7f from Google performance tools compatible with the BSD license from OpenBLAS?

**Comment by tomaklutfu** [comment]
It has just merged and it is for static linking but julia uses dynamic libraries for blas/lapack. Is there a context it is useful for julia?

**Comment by tomaklutfu** [comment]
Sorry wrong place.

**Comment by xianyi** [comment]
@carlkl , good question. I didn't be familiar with license issue.

@theoractice , any ideas?

**Comment by martin-frbg** [comment]
From https://github.com/gperftools/gperftools README:
gperftools is distributed under the terms of the BSD License

**Comment by theoractice** [comment]
Yeah I am aware of that, and actually function on_process_term is completely rewritten. I left that link there mainly for reference purposes.

**Comment by xianyi** [comment]
@martin-frbg , @theoractice , thank you for the answer.

Because of rewritten, it looks like I don't need to include gperftools BSD license file. Am I right?

**Comment by theoractice** [comment]
@xianyi Not 100% sure, but I bet so. 
@tomaklutfu If you are using official Julia packages, then chances are you will never run into this problem.

**Comment by tomaklutfu** [comment]
@theoractice I wasn't meant to write here, it was accident so I deleted it, nevermind me.

**Comment by martin-frbg** [comment]
Not a lawyer, but I agree that including the gperftools license file is most probably unnecessary. After all, this is not reusing a key functionality of the other codebase, but picking up a platform-specific implementation detail that you happened to see there.

**Comment by theoractice** [comment]
@carlkl BTW have you ever tried static linking in mingw? I have little experience using it and I don't know if mingw has the same access violation problem.

**Comment by carlkl** [comment]
static linking with mingw-w64 works without access violation, at least for my usecases.
Reminds me, that this piece of code should be embedded into an 
`#ifdef _MSC_VER`
clause, right?

**Comment by theoractice** [comment]
Good to hear that.
For `_MSC_VER` yes, otherwise those `#pragma` won't pass CI build.
