### ISSUE TITLE
Fail to compile on Mac

### ISSUE THREAD

**Issue by geyunxiang** [xianyi/OpenBLAS#835]
Hi all. I git cloned the source code to my Mac and issued `make`. After a while it complained something like `/var/folders/56/dlv5fjkx5912bdv9rf81lm380000gn/T//ccC7nthm.s:221:suffix or operands invalid for 'movq'`

My clang version: 
`Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.4.0
Thread model: posix`

My CPU: 
`machdep.cpu.brand_string: Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz`

I've tried `make TARGET=HASWELL`, `make CC=clang` yet none worked.

**Comment by martin-frbg** [comment]
Looks like it might be picking up a wrong assembler version a la http://stackoverflow.com/questions/34457801/error-with-gcc-5-for-varargs-function-suffix-or-operands-invalid-for-movq ?

**Comment by geyunxiang** [comment]
I was trying to compile [caffe](http://caffe.berkeleyvision.org) on my Mac which requires BLAS. So I tried to get OpenBLAS from here. Later on I found that Mac OS X comes with BLAS installed. So for anyone who tries to compile caffe and comes to this problem, [here](http://installing-caffe-the-right-way.wikidot.com/start) is a good tutorial.
