### ISSUE TITLE
Enable OpenBLAS for LinuxOne s390x zEC13 SIMD and optimize BLAS3 double precision

### ISSUE THREAD

**Issue by edelsohn** [xianyi/OpenBLAS#836]

**Comment by edelsohn** [comment]
This issue will be split into double (DGEMM, DTRMM) and double complex (ZGEMM, ZTRMM).

**Comment by martin-frbg** [comment]
@edelsohn Is PR #1043 endorsed by you, or could someone from your group review it ? (In that case I could execute my newly acquired janitorial powers to commit it in case xianyi is unavailable, but I would not want to do it prematurely for a platform I know very little about)

**Comment by edelsohn** [comment]
@martin-frbg Abdel and I are in agreement that the preliminary support for DGEMM and DTRMM are ready and should be merged. I will open a second, separate issue for BLAS3 double complex and the bounty will be split between them so that this issue can be closed and the 1/2 bounty claimed by Abdel.

**Comment by martin-frbg** [comment]
Duly merged on the somewhat dated z13 branch (sorry for getting tricked by the web interface to put just "Z13" into the merge comment...)

**Comment by edelsohn** [comment]
I created a new bounty for this. As soon as you and Xianyi are satisfied with the pull and merge, you can close this issue and Abdel can claim the bounty.
