### ISSUE TITLE
Where is LibGFORTRAN-3.DLL ?

### ISSUE THREAD

**Issue by Tunneller** [xianyi/OpenBLAS#838]
Hi, Xianyi, appreciate the time you put into this project.

I built the LibOpenBlas as per instruction from source and a few hours later got a LibOpenBlas.DLL great.

But when I look with Dependency Walker and it says that I will need to have LIBGFORTRAN-3.DLL

My goal is to create a valid standalone Windows .DLL  that python and Visual Studio can link to.

Should I have attached some parameters to the Make command?

**Comment by jeromerobert** [comment]
libgfortran-3.dll (and libgcc_s*.dll which you'll also probably need) can be found somewhere in your Mingw installation directory.

**Comment by carlkl** [comment]
You can download a version compiled for python usage here:

https://bitbucket.org/carlkl/mingw-w64-for-python/downloads

The gcc runtime code is linked statically, hence no  need for LIBGFORTRAN-3.DLL. The latest version has a small howto description if you want to build yourself.

**Comment by brada4** [comment]
You can disable compiling lapack and lapacke, especially if not using them, then it will not use any fortran or libraires.
