### ISSUE TITLE
Failed to build VS solution

### ISSUE THREAD

**Issue by shkyang** [xianyi/OpenBLAS#839]
This is with the latest source.

$ cmake -G "Visual Studio 12 Win64" .
CMake Error: Could not create named generator Visual Studio 12 Win64

Generators
  Unix Makefiles               = Generates standard UNIX makefiles.
  Ninja                        = Generates build.ninja files.
  CodeBlocks - Ninja           = Generates CodeBlocks project files.
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
  CodeLite - Ninja             = Generates CodeLite project files.
  CodeLite - Unix Makefiles    = Generates CodeLite project files.
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.
  KDevelop3                    = Generates KDevelop 3 project files.
  KDevelop3 - Unix Makefiles   = Generates KDevelop 3 project files.
  Kate - Ninja                 = Generates Kate project files.
  Kate - Unix Makefiles        = Generates Kate project files.
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files.

**Comment by theoractice** [comment]
Try "Visual Studio 12 2013 Win64".

**Comment by martin-frbg** [comment]
Also note that according to the wiki, VS does not support the ("AT&T") syntax used in the assembler mnemonics so most optimization will not be available in the VS build. (Supposedly "gcc -S -masm=intel" or "llvm-mc-3.2 -x86-asm-syntax=intel" can be used to convert to Intel syntax, but this would have to be done for a large fraction of the code and with appropriate #ifdef's so as not to break other platforms.)

**Comment by shkyang** [comment]
Thanks for the quick turnaround,

> It's your cmake cannot detect VS2013, not OpenBLAS's fault.

Do you know how to make cmake detect visual studio?

**Comment by shkyang** [comment]
Thanks guys, I was doing this on cygwin, it seems to have worked now that I moved over to powershell.
