### ISSUE TITLE
Lots of macro redefined warnings with clang

### ISSUE THREAD

**Issue by jakirkham** [xianyi/OpenBLAS#840]
Tried building 0.2.18 with `clang`, but seems that I quickly hit 4MB of just warnings about macros that were redefined. See this [log]( https://s3.amazonaws.com/archive.travis-ci.org/jobs/123199147/log.txt ). Also, here is the [recipe]( https://github.com/conda-forge/staged-recipes/commit/cf9c7b5305925cacdc6b9803bbb24124be6969e4 ) I used to build it.

**Comment by martin-frbg** [comment]
Same or at least similar problem as #818 ?

**Comment by jakirkham** [comment]
Don't think so as this is occurring on Mac with `clang` and I am not setting `CFLAGS` at all. So, even the proposed workaround cannot be applied here.

**Comment by martin-frbg** [comment]
Symptoms are very similar - I did not create a pull request for my Makefile changes as I was hoping for a more elegant solution, but that issue did not attract much interest apparently.
If you feel like experimenting, you could add my proposed "#ifdef DOIT" and "#endif" around the 
CCOMMON_OPT     += -DASMNAME ...
line (~ line 906) in Makefile.system and the corresponding "DOIT=1" between the "TOPDIR=" and the "include" at the top of interface/Makefile (and eventually the five other Makefiles named in #818)
and see if that removes the warnings from that part of the build.

**Comment by brada4** [comment]
Can you try to build on clean system with clean xcode?
"official" conda-forge recipe is officially failing, your guess at least builds some result.

**Comment by jakirkham** [comment]
After playing around some more, I agree with you @martin-frbg. This is a dup of this issue ( https://github.com/xianyi/OpenBLAS/issues/818 ). I was able to resolve my issue by following this [comment]( https://github.com/xianyi/OpenBLAS/issues/818#issuecomment-207365134 ).
