### ISSUE TITLE
Performance regression in benchmark/scripts/R/deig.R related to LAPACK wrappers

### ISSUE THREAD

**Issue by brada4** [xianyi/OpenBLAS#843]
Choose Your favourite rpm distribution (or compile R without any parameters so it builds replaceable netlib blas)
Replace libRblas.so with very default openblas build for first sample, make another without lapack for second sample (R tries to use libRblas as blas+lapack, failing on second part takes own libRlapack linked to libRblas.
Results are from laptop piledriver, but setting core type to atom in dynamic_arch did not change proportion, then fixed CPUs on minimum freq to make sure timings are stable - same result.
I closed chromium for measurement and repeated it couple of times.
I could not figure out the problem on the spot. There is 5% beef in holding back threads in interface/trmv.c, but thats minor compared to what shows up.

With openblas as lapack Rscript benchmark/scripts/R/deig.R

```
From 128 To 2048 Step=128 Loops=1
      SIZE             Flops                   Time
           128x128 :     340.92 MFlops   0.164000 sec
           256x256 :    1047.50 MFlops   0.427000 sec
           384x384 :    1605.93 MFlops   0.940000 sec
           512x512 :    1449.27 MFlops   2.469000 sec
           640x640 :    1830.00 MFlops   3.819000 sec
           768x768 :    2285.50 MFlops   5.284000 sec
           896x896 :    2714.39 MFlops   7.065000 sec
         1024x1024 :    2885.68 MFlops   9.920000 sec
         1152x1152 :    3715.78 MFlops  10.969000 sec
         1280x1280 :    4056.75 MFlops  13.782000 sec
         1408x1408 :    4593.60 MFlops  16.200000 sec
         1536x1536 :    4357.02 MFlops  22.174000 sec
         1664x1664 :    5301.90 MFlops  23.168000 sec
         1792x1792 :    5343.13 MFlops  28.713000 sec
         1920x1920 :    5386.40 MFlops  35.032000 sec
         2048x2048 :    4900.45 MFlops  46.732000 sec
```

with netlib lapack wrapping openblas blas

```
From 128 To 2048 Step=128 Loops=1
      SIZE             Flops                   Time
           128x128 :     980.88 MFlops   0.057000 sec
           256x256 :    2181.86 MFlops   0.205000 sec
           384x384 :    3369.58 MFlops   0.448000 sec
           512x512 :    2398.29 MFlops   1.492000 sec
           640x640 :    4674.76 MFlops   1.495000 sec
           768x768 :    5241.57 MFlops   2.304000 sec
           896x896 :    6766.82 MFlops   2.834000 sec
         1024x1024 :    4683.57 MFlops   6.112000 sec
         1152x1152 :    8559.10 MFlops   4.762000 sec
         1280x1280 :    8274.39 MFlops   6.757000 sec
         1408x1408 :    9685.84 MFlops   7.683000 sec
         1536x1536 :    6457.20 MFlops  14.962000 sec
         1664x1664 :   10696.14 MFlops  11.484000 sec
         1792x1792 :   10284.04 MFlops  14.918000 sec
         1920x1920 :   11540.36 MFlops  16.351000 sec
         2048x2048 :    7841.65 MFlops  29.204000 sec
```

**Comment by martin-frbg** [comment]
Could you do a "git bisect", or at least compare one or two of the previous releases to find when things went wrong ? (Most everything since 0.2.16 has been ARM-related changes, likely candidates would appear to be either the piledriver optimizations starting from c99cc41 or the import of fixes from netlib svn at 26b3b3a , both from about six weeks ago.)

**Comment by brada4** [comment]
I dont git or bisect. Nothing to do with piledriver as mentioned. I did not have patience to wait to test raspbery but I would bet on generic problem in C infrastructure.
http://github.com/xianyi/OpenBLAS/archive/v0.2.10.tar.gz has same problem

**Comment by brada4** [comment]
Same fish smells from12-core ivy bridge
```
      SIZE             Flops                   Time
           128x128 :     650.12 MFlops   0.086000 sec
           256x256 :    1927.93 MFlops   0.232000 sec
           384x384 :    2989.25 MFlops   0.505000 sec
           512x512 :    2860.31 MFlops   1.251000 sec
           640x640 :    3767.53 MFlops   1.855000 sec
           768x768 :    4863.70 MFlops   2.483000 sec
           896x896 :    5714.29 MFlops   3.356000 sec
         1024x1024 :    6519.23 MFlops   4.391000 sec
         1152x1152 :    7921.95 MFlops   5.145000 sec
         1280x1280 :    8770.21 MFlops   6.375000 sec
         1408x1408 :   10098.56 MFlops   7.369000 sec
         1536x1536 :   10427.70 MFlops   9.265000 sec
         1664x1664 :   11714.14 MFlops  10.486000 sec
         1792x1792 :   12270.43 MFlops  12.503000 sec
         1920x1920 :   13059.48 MFlops  14.449000 sec
         2048x2048 :   13223.68 MFlops  17.318000 sec
```
```
      SIZE             Flops                   Time
           128x128 :    1397.75 MFlops   0.040000 sec
           256x256 :    3696.53 MFlops   0.121000 sec
           384x384 :    6062.54 MFlops   0.249000 sec
           512x512 :    6948.05 MFlops   0.515000 sec
           640x640 :    9534.46 MFlops   0.733000 sec
           768x768 :   11339.51 MFlops   1.065000 sec
           896x896 :   13816.39 MFlops   1.388000 sec
         1024x1024 :   14384.90 MFlops   1.990000 sec
         1152x1152 :   17644.35 MFlops   2.310000 sec
         1280x1280 :   19252.78 MFlops   2.904000 sec
         1408x1408 :   21334.95 MFlops   3.488000 sec
         1536x1536 :   21555.69 MFlops   4.482000 sec
         1664x1664 :   23576.67 MFlops   5.210000 sec
         1792x1792 :   23719.42 MFlops   6.468000 sec
         1920x1920 :   25162.89 MFlops   7.499000 sec
         2048x2048 :   24365.11 MFlops   9.399000 sec
```
compile openblas
compile R (tar xf R-3.2.5.tar.gz; cd R-3.2.5 ;./configure ; make -j)
ln -fs ~/OpenBLAS-0.2.18/libopenblas.so.0 lib/libRblas.so
bin/Rscript ~/OpenBLAS-0.2.18/benchmark/scripts/R/deig.R
recompile openblas minus lapacks
repeat rscript

**Comment by martin-frbg** [comment]
This is multithreading with no explicit limit on number of threads, right ? How do benchmarks for single
(or small number of) thread runs compare ?

**Comment by brada4** [comment]
OPENBLAS_NUM_THREADS=1 bin/Rscript ~/OpenBLAS-0.2.18/benchmark/scripts/R/deig.R
CPU is E5-2697 v2 with HT off, sibling fried and is replaced with plastic cover, so openblas make builds with 12 CPUS max, pthread version

all openblas
```
           128x128 :     450.89 MFlops   0.124000 sec
           256x256 :    1996.79 MFlops   0.224000 sec
           384x384 :    2754.69 MFlops   0.548000 sec
           512x512 :    2579.84 MFlops   1.387000 sec
           640x640 :    3108.88 MFlops   2.248000 sec
           768x768 :    3940.16 MFlops   3.065000 sec
           896x896 :    4824.44 MFlops   3.975000 sec
         1024x1024 :    5217.05 MFlops   5.487000 sec
         1152x1152 :    6201.83 MFlops   6.572000 sec
         1280x1280 :    6831.63 MFlops   8.184000 sec
         1408x1408 :    7515.28 MFlops   9.902000 sec
         1536x1536 :    7897.70 MFlops  12.233000 sec
         1664x1664 :    8712.90 MFlops  14.098000 sec
         1792x1792 :    8862.93 MFlops  17.310000 sec
         1920x1920 :    9371.10 MFlops  20.136000 sec
         2048x2048 :    8878.67 MFlops  25.793000 sec
```
netlib lapack openblas blas 
```
           128x128 :    1694.24 MFlops   0.033000 sec
           256x256 :    4259.82 MFlops   0.105000 sec
           384x384 :    5943.20 MFlops   0.254000 sec
           512x512 :    6023.98 MFlops   0.594000 sec
           640x640 :    7442.77 MFlops   0.939000 sec
           768x768 :    8694.44 MFlops   1.389000 sec
           896x896 :   10125.21 MFlops   1.894000 sec
         1024x1024 :    9946.48 MFlops   2.878000 sec
         1152x1152 :   12801.02 MFlops   3.184000 sec
         1280x1280 :   14313.89 MFlops   3.906000 sec
         1408x1408 :   15375.27 MFlops   4.840000 sec
         1536x1536 :   15114.61 MFlops   6.392000 sec
         1664x1664 :   16496.70 MFlops   7.446000 sec
         1792x1792 :   16286.33 MFlops   9.420000 sec
         1920x1920 :   14950.99 MFlops  12.621000 sec
         2048x2048 :   14394.85 MFlops  15.909000 sec
```
netlib blas and lapack (as from that R, no clue about version)
```
           128x128 :    1471.32 MFlops   0.038000 sec
           256x256 :    1726.95 MFlops   0.259000 sec
           384x384 :    2085.04 MFlops   0.724000 sec
           512x512 :    2317.52 MFlops   1.544000 sec
           640x640 :    2708.82 MFlops   2.580000 sec
           768x768 :    2937.62 MFlops   4.111000 sec
           896x896 :    3151.55 MFlops   6.085000 sec
         1024x1024 :    3134.00 MFlops   9.134000 sec
         1152x1152 :    3499.48 MFlops  11.647000 sec
         1280x1280 :    3871.35 MFlops  14.442000 sec
         1408x1408 :    3592.04 MFlops  20.717000 sec
         1536x1536 :    3351.93 MFlops  28.823000 sec
         1664x1664 :    3497.86 MFlops  35.117000 sec
         1792x1792 :    3478.77 MFlops  44.101000 sec
         1920x1920 :    3574.34 MFlops  52.792000 sec
         2048x2048 :    3445.43 MFlops  66.467000 sec
```

**Comment by martin-frbg** [comment]
Strange. As far as I can tell, most of the lapack-related code is virtually unchanged from K. Goto's time. I could understand deficiencies with multithreading as that was not as widespread on desktop systems back then, but  not this. That would seem to leave the equally unlikely options that either the
R-provided lapack is something other than netlib or was compiled with vastly superior optimization.

**Comment by brada4** [comment]
nm tells it is gfortran-only double-only pretty generic netlib produce (400k Rblas 4M Rlapack)
lapack release notes src/modules/lapack/README state:
``
zgelsd zgesdd zlacp2 zlacrm zlals0 zlalsa zlalsd zlarcm
were added in R 3.1.0.
zlahrd is 'deprecated' in LAPACK 3.6.0 and may not be included in
external libraries.
``
src/extra/blas has none so lets assume same.

**Comment by xianyi** [comment]
Interesting. I cannot open this issue on github.com

2016-04-20 11:54 GMT-04:00 brada4 <notifications@github.com>:

**Comment by martin-frbg** [comment]
> Interesting. I cannot open this issue on github.com
Yes, seems the entire brada4 account is gone, and all comments he ever posted in any
of the bug reports. Did he finally get on somebody's nerves or did he rip himself in two, 
rumpelstiltskin-style ?
-- 
Dr. Martin Kroeker            martin@ruby.chemie.uni-freiburg.de
c/o Prof.Dr. Caroline Roehr
Institut fuer Anorganische und Analytische Chemie der Universitaet Freiburg

**Comment by wernsaar** [comment]
Hi,

I see your account and your issues.

Best regards
Werner

**Comment by martin-frbg** [comment]
Good to know it was just a github glitch. Did not get around to trying to reproduce the issue yet but probably not needed now that the wizards are onto it.

**Comment by brada4** [comment]
This is the repeater, should not take very long:
> **compile** openblas
> **compile** R (tar xf R-3.2.5.tar.gz; cd R-3.2.5 ;./configure ; make -j)
> ln -fs ~/OpenBLAS-0.2.18/libopenblas.so.0 lib/libRblas.so
> bin/Rscript ~/OpenBLAS-0.2.18/benchmark/scripts/R/deig.R
> re**compile** openblas minus lapacks
> repeat rscript

**Comment by brada4** [comment]
Just looked at R ./src/modules/lapack/Lapack.c
It calls dsyevr twice - for workspace estimation and for real calculation ins square eigen() case
Since time is almost double time but never more I would speculate that somewhere calculation is done in place of workspace estimation. 
For non square cases same is done with dgeev, and maybe also twin problem causes #703

**Comment by martin-frbg** [comment]
As far as I can tell, OpenBLAS' dseyvr is the netlib one, and if called as a workspace query all it does is call ilaenv (again a stock netlib function) to pick the blocksize (from a fixed table based on function names) and multiply that value by the given matrix order. You could try putting a breakpoint on e.g. dsytrd and/or adding a write(*,*) lquery before that call in dsyevr.f to see if it actually gets to doing serious calculations on a workspace query (should never get there with LQUERY.EQ.TRUE I think)

**Comment by brada4** [comment]
i was thinking when i have spare hour to explore call graph and flip c lapack interfaces back to netlib ones at a time to see which is a bug.

**Comment by brada4** [comment]
workspace calculation turns out immediate
```
From 256 To 4096 Step=256 Loops=1
      SIZE             Flops                   Time

Breakpoint 1, dgeev (jobvl=..., jobvr=..., n=256, a=..., lda=256, wr=..., wi=..., vl=..., ldvl=256, vr=..., ldvr=256, work=..., lwork=-1, info=5, _jobvl=36303816, _jobvr=18949336) at dgeev.f:189
189     dgeev.f: No such file or directory.
(gdb) c
Continuing.

Breakpoint 1, dgeev (jobvl=..., jobvr=..., n=256, a=..., lda=256, wr=..., wi=..., vl=..., ldvl=256, vr=..., ldvr=256, work=..., lwork=8704, info=0, _jobvl=36303816, _jobvr=18949336) at dgeev.f:189
189     in dgeev.f
(gdb) 
Continuing.
           256x256 :      37.32 MFlops  11.984000 sec
[New Thread 0x7ffff24bb700 (LWP 42205)]
[New Thread 0x7ffff1cba700 (LWP 42204)]
[New Thread 0x7fffef4b9700 (LWP 42203)]

Breakpoint 1, dgeev (jobvl=..., jobvr=..., n=512, a=..., lda=512, wr=..., wi=..., vl=..., ldvl=512, vr=..., ldvr=512, work=..., lwork=-1, info=32767, _jobvl=36826536, _jobvr=18949336) at dgeev.f:189
189     in dgeev.f
(gdb) 
Continuing.

Breakpoint 1, dgeev (jobvl=..., jobvr=..., n=512, a=..., lda=512, wr=..., wi=..., vl=..., ldvl=512, vr=..., ldvr=512, work=..., lwork=17408, info=0, _jobvl=36826536, _jobvr=18949336) at dgeev.f:189
189     in dgeev.f
(gdb) 
Continuing.
           512x512 :     183.73 MFlops  19.476000 sec

Breakpoint 1, dgeev (jobvl=..., jobvr=..., n=768, a=..., lda=768, wr=..., wi=..., vl=..., ldvl=768, vr=..., ldvr=768, work=..., lwork=-1, info=32767, _jobvl=33422616, _jobvr=18949336) at dgeev.f:189
189     in dgeev.f
(gdb) 
Continuing.

Breakpoint 1, dgeev (jobvl=..., jobvr=..., n=768, a=..., lda=768, wr=..., wi=..., vl=..., ldvl=768, vr=..., ldvr=768, work=..., lwork=26112, info=0, _jobvl=33422616, _jobvr=18949336) at dgeev.f:189
189     in dgeev.f
(gdb) 
Continuing.
           768x768 :    1629.33 MFlops   7.412000 sec

Breakpoint 1, dgeev (jobvl=..., jobvr=..., n=1024, a=..., lda=1024, wr=..., wi=..., vl=..., ldvl=1024, vr=..., ldvr=1024, work=..., lwork=-1, info=32767, _jobvl=114937800, _jobvr=18949336) at dgeev.f:189
189     in dgeev.f
```
For very small dimensions it calls dsyevr, for bigger dgeev (strange,but no damage in there either)

**Comment by martin-frbg** [comment]
Hmm. I do not think that debug output tells us anything except that dgeev is called twice each time (which we knew already). Perhaps single-stepping in dgeev can confirm that it exits after the call to ilaenv - my suggestion was to put a breakpoint on the first "serious" function called from within dsyevr after any workspace calculation has been done. Obviously that breakpoint should trigger on every second invocation only.
dgeev could be interesting as the OpenBLAS version has several bugfixes from the netlib svn repository already applied (since march 7, i.e. 0.2.16), which will not (yet) be in the netlib LAPACK you use for comparison. I think any other slowdown would have to be traced back to some "*gem*" call, or some BLAS function, to explain differences between OpenBLAS and netlib.

**Comment by wernsaar** [comment]
Hi,

my benchmark results, that I ran today on my BULLDOZER machine, are attached.
It's important, to set a good optimization flag for gfortran.

[dgeev-test.txt](https://github.com/xianyi/OpenBLAS/files/288341/dgeev-test.txt)

Best regards
Werner

**Comment by brada4** [comment]
FCOMMON_OPT -O3 produces link errors for me (OpenSUSE 42.1 if that matters)
I mean this:
[log_log_log.TXT](https://github.com/xianyi/OpenBLAS/files/288389/log_log_log.TXT)

**Comment by martin-frbg** [comment]
I am seeing the same issue on Haswell (4770) currently, both R-3.2.5 and OpenBLAS-0.2.18 compiled with gcc-4.7.2 (older opensuse 12.3, will try to repeat with a more recent version later), using their respective default settings - replacing libRblas with libopenblas leads to MFlops figures that are about half of what gets reported for libRblas. (The lapack provided by R appears to be 3.5.0, or possibly a cherry-picked mix of netlib routines from 3.1.x onwards)

**Comment by brada4** [comment]
I see same on piledriver, atom, sandy-ivybridge

**Comment by martin-frbg** [comment]
The newer compiler and FCOMMON_OPT=-O3 does indeed do the trick here - though for a completely fair comparison I will need to recompile Rblas with -O3 as well.

**Comment by brada4** [comment]
R blas and lapack optimisation is just concatenating source files and building most of lapack in one go.
Probably it yields some extreme interprocedural optimisation effect like gfortran-5 *.f -o lapack.so

**Comment by martin-frbg** [comment]
@brada4 If you look at the deig.txt I posted, openblas wins consistently with both sources compiled at -O3, while with the default -O2, openblas was severly penalized at small matrix sizes similar to the results you posted earlier. I have not yet gotten around to trying the mixed builds that appeared to be fastest in your tests, nor to compiling with most recent gcc (6.1).

**Comment by brada4** [comment]
This one with Netlib-R version compiled with gcc 5.3.1 -O3 -frecursive vs OpenBLAS build system -O3 ..

[log_log.TXT](https://github.com/xianyi/OpenBLAS/files/288882/log_log.TXT)

**Comment by wernsaar** [comment]
Hi,

please use perf record and perf report, to see which functions
are called and the usage in %.

Best regards
Werner

**Comment by martin-frbg** [comment]
Not sure what conclusions if any to draw of this - should we bump the default FCOMMON_OPT in Makefile.system to "-O3 -frecursive" instead of "-O2 -frecursive" for gfortran ?

**Comment by brada4** [comment]
Long time no remember....
What is strange that the way R compiles LAPACK with all source O2 at once adds some mystery IPA that brings performance to -O3 level without (formally) sacrificing math correctness.
I am setting up tests in few hours.
Monday I will get back to old samples and re-test with old compilers.

**Comment by brada4** [comment]
No sunshine (single-threaded on piledriverM)
[843-measures.txt](https://github.com/xianyi/OpenBLAS/files/690482/843-measures.txt)
GC is triggered within timed loop, i will fix that first.

**Comment by martin-frbg** [comment]
There must be something special about libRlapack.so although I cannot pinpoint it yet - try replacing it with the netlib 3.6.1 one and performance figures for linking against a BLAS-only OpenBLAS are suddenly on par with the "complete" OpenBLAS. (Maybe due to using functions from earlier netlib releases - I have not matched the version numbers in the function comments of src/modules/lapack/dlapack.f against their netlib-3.6.1 counterparts ?)

**Comment by brada4** [comment]
[843-deig-R.txt](https://github.com/xianyi/OpenBLAS/files/691458/843-deig-R.txt)
[843-measuresV2.txt](https://github.com/xianyi/OpenBLAS/files/691460/843-measuresV2.txt)
netlib lapack is speedy.  is it interface/lapack/* to be flipped one by one to find culprit?
I will correct other 2 R scripts and make PR (bring GC out of timing, avoid duplication inside timed loop)
I can actually calculate GB/s against arguments, processors used even sys vs user...

**Comment by martin-frbg** [comment]
Sorry, it seems I must have mishandled the cmake build of netlib late last night, effectively pitching an un-optimized 3.6.1 against the libRlapack.so built at -O2. So it remains a mystery why the OpenBLAS copy of lapack appears to require building with -O3 to achieve similar performance as an externally built one. Did you get around to collecting perf data as suggested by wernsaar ?

**Comment by martin-frbg** [comment]
Next "duh" moment: unless one remembers to add (at least) "-O2" as a gfortran flag by some means (FFLAGS environment variable or by editing Makefile.system), OpenBLAS builds an unoptimized LAPACK tree as well, the default "-O2" mentioned in Makefile.rule is **not** applied to the fortran options.
I cannot be the only one caught out by this, or can I ?

**Comment by brada4** [comment]
Me too (but you keep the eagle eye badge)
```
gfortran -Wall -m64 -fPIC -c slarft.f -o slarft.o
gfortran -Wall -m64 -fPIC -c slarfx.f -o slarfx.o
gfortran -Wall -m64 -fPIC -c slargv.f -o slargv.o

```

**Comment by brada4** [comment]
Probably of no use any more perf record Rscript deig.R ; perf report -U > file
slow is openblas+ lapack
fast is openblas NO_LAPACK
[843-fast.txt](https://github.com/xianyi/OpenBLAS/files/691600/843-fast.txt)
[843-slow.txt](https://github.com/xianyi/OpenBLAS/files/691601/843-slow.txt)

**Comment by martin-frbg** [comment]
More like eagle eye **patch** I guess. My immediate suggestion is to change the
override FFLAGS += $(FCOMMON_OPT)
in line 1007 of Makefile.system to something like
override FFLAGS += $(COMMON_OPT) $(FCOMMON_OPT)
but I am not sure I fully understand the reasoning that must have led to the current situation (and the implication that default builds would have provided a slow LAPACK irrespective of the fortran compiler for some time)

**Comment by brada4** [comment]
#1047 to eliminate gc in benchmarks script used (+2 siblings)

**Comment by brada4** [comment]
Measurement says 1-line change is sufficient to fix my problem.
Peeking at typescript it shows that LAPACK _lamch _laruv _laran (machine parameters and slow unusable RNG-s) are built with -O0, unlikely they are widely used.
