### ISSUE TITLE
will OpenBLAS optimized with arm-neon ?

### ISSUE THREAD

**Issue by xylcbd** [xianyi/OpenBLAS#854]
it looks neon is more quick than vfp [http://stackoverflow.com/questions/4097034/arm-cortex-a8-whats-the-difference-between-vfp-and-neon]

so,is there any plan to optimize kernel with arm-neon ?

**Comment by martin-frbg** [comment]
See wernsaar's answers in #562 please.

**Comment by xianyi** [comment]
We used neon for ARMv8 architecture.

**Comment by martin-frbg** [comment]
Oops. Perhaps someone knowledgeable could add a section on hardfp vs softfp vs neon to the arm/android page of the wiki then ?

**Comment by wernsaar** [comment]
On Armv8, we use asimd, which is the successor of neon
