### ISSUE TITLE
building v0.2.18 fails depending on CC variable.

### ISSUE THREAD

**Issue by vondele** [xianyi/OpenBLAS#857]
/data/vjoost/toolchain-tst/build/OpenBLAS-0.2.18> make -j 12 CC=/data/vjoost/toolchain-tst/install/gcc-6.1.0/bin/gcc  FC=/data/vjoost/toolchain-tst/install/gcc-6.1.0/bin/gfortran >& log

/data/vjoost/toolchain-ar  -ru ../libopenblas_nehalemp-r0.2.18.a saxpy.o [...]
make[1]: /data/vjoost/toolchain-ar: Command not found
../Makefile.tail:40: recipe for target 'libs' failed

The reason seems to be that this leads to a definition in Makefile.conf of 

CROSS_SUFFIX=/data/vjoost/toolchain-

which causes other problems later on. This comes from c_check which is called as

perl ./c_check Makefile.conf config.h /data/vjoost/toolchain-tst/install/gcc-6.1.0/bin/gcc

and somehow gets confused by the path name in the CC definition, which includes dashes.

**Comment by martin-frbg** [comment]
Looks a lot like #605 (which xianyi failed to reproduce back then)

**Comment by vondele** [comment]
yes, looks like the same issue. Should be easy to reproduce, but the problem is not a dash in the path to openblas, but the dash in the path of CC. The detection in c_check would be somewhat more robust if the path were stripped first.

**Comment by buffer51** [comment]
Well the problem was that in your case, the path has one but the compiler executable doesn't, which isn't the case usually. Could you try [my commit](https://github.com/buffer51/OpenBLAS/commit/20b0ed1da598a98b2b5036bc0decbd4aae79aa20) to confirm that it fixes the issue?

I tried a bunch of combinations with dashes in the path or the executable itself, it seemed to handle them correctly.

**Comment by xianyi** [comment]
@buffer51 , thank you for the patch. Actually, I am not good at perl :)

**Comment by vondele** [comment]
@buffer51, unfortunately, it doesn't quite work. Since CC=/data/vjoost/toolchain-tst/install/gcc-6.1.0/bin/gcc this results in CROSS_SUFFIX=/data/vjoost/toolchain-tst/install/gcc-6.1.0/bin/ which causes the build to fail as this leads to executing /data/vjoost/toolchain-tst/install/gcc-6.1.0/bin/ar which doesn't exist. Note that I'm not cross-compiling, this is just gcc being installed in a non-standard place.

**Comment by buffer51** [comment]
@vondele Oh I see. We can fix this by enabling the CROSS_SUFFIX only if CROSS is set (I thought it behaved like that). Can you check that `CROSS=0` in Makefile.conf?

Also, if this is just where you installed gcc, why don't you have the corresponding ar along with it?

**Comment by vondele** [comment]
CROSS is not present in Makefile.conf (i.e. neither CROSS=0 nor CROSS=1).

ar would be part of binutils (in my case /data/vjoost/toolchain-tst/install/binutils-2.25/bin/ar). What is provided in a build of gcc is 'gcc-ar' which lives in /data/vjoost/toolchain-tst/install/gcc-6.1.0/bin/gcc-ar (and is a wrapper to the binutils ar)

**Comment by buffer51** [comment]
Alright, can you try [this](https://github.com/buffer51/OpenBLAS/commit/708dec5bb7fc2b1244934e585fd5e57ccbd66722)?

Since your install is not standard at all, you will probably have to set the desired path for `ar`, `ranlib`, ... using `AR=/path/to/ar RANLIB=/path/to/ranlib`.

**Comment by vondele** [comment]
yes, that works for me, should presumably be tested by somebody using cross-compiling as well.

All tools are in the PATH so are found as needed.

Thanks!

**Comment by brada4** [comment]
Can your gcc compile trivial int main {}; C file?

**Comment by buffer51** [comment]
@vondele Glad to hear it works.

@xianyi I checked cross-compilation with several combination of dashes/no dashes, worked well. Should the issue be closed?
