### ISSUE TITLE
Openblas does not pick up fortran from abs path

### ISSUE THREAD

**Issue by davydden** [xianyi/OpenBLAS#862]
````
make CC=clang FC=/abs/path/to/gfortran
````

fails to pick up the fortran compiler.

p.s. this is a mirror of https://groups.google.com/forum/#!topic/openblas-dev/C_oUHWQm4Tk as I think it is more convenient to discuss and track issues on GitHub.

**Comment by xianyi** [comment]
@davydden ， is it same to #857 ?

**Comment by davydden** [comment]
@xianyi let me see if the merged fix works from the upstream...

**Comment by davydden** [comment]
still fails to detect fortran with current github version:

```
==> make -j8 CC=clang FC=/path/to/gfortran CROSS=1 libs netlib shared
OpenBLAS: Detecting fortran compiler failed. Cannot compile LAPACK. Only compile BLAS.
```

**Comment by xianyi** [comment]
Thank you for the feedback.

**Comment by martin-frbg** [comment]
Is FC in your PATH - I am guessing it is not ? Try moving the line 61 of f_check which is
$vendor = "";
before the the preceding "data = `which $compiler_bin`..." - it looks to me as if this could prevent
 the error check ($?) that follows. 
("which gfortran" will fail if your gfortran installation is not in the search path, and if it fails the script is supposed to retry with the full path from the FC if I read it correctly. I suspect the intervening "make vendor blank" resets the error flag from the failed "which")

**Comment by martin-frbg** [comment]
Sorry, overlooked the "CROSS=1" in your response - are you actually cross-compiling, or does your
FC path only happen to contain a dash somewhere (a la #857, I guess the fix was just for CC not FC) ?

**Comment by davydden** [comment]
@martin-frbg perhaps i misinterpret the term `cross-cmpiling`, i do compile with a mixture of `clang` and `gfortran`. I will try you suggestions above and report back here...

**Comment by buffer51** [comment]
@martin-frbg If you are compiling for the same computer than you are building with? If so, it is not cross-compiling. Could you give us the full path that you have set for `gfortran`?

I've ran tests and my understanding is that `CROSS=1` doesn't do anything (except tests are not run), and f_check doesn't have the cross-suffix logic c_check has. However, it relies on the path to figure out which compiler & vendor for Fortran is used. It might be that you path doesn't tell enough for the detection to work.

**Comment by martin-frbg** [comment]
Cross-compiling normally refers to compiling for a different architecture or operating system, such as compiling phone apps on a desktop computer or building an EXE for Windows under Linux.

**Comment by davydden** [comment]
@martin-frbg i see, thanks. Then I am certainly don't do this!

**Comment by martin-frbg** [comment]
Try swapping the two lines in f_check then please...

**Comment by davydden** [comment]
Sorry for the noise, apparently this
```
 make -j8 CC=clang FC=/Users/davydden/spack/opt/spack/darwin-x86_64/clang-7.3.0-apple/gcc-5.3.0-ctakkbfikm76kcnssbb3gv53mlrwldbl/gfortran libs netlib shared
```
works even without swapping the lines. I was building it from the `spack` package manager and it must have to do with it not the Openblas.
