### ISSUE TITLE
Matrix operations in openblas

### ISSUE THREAD

**Issue by hchen1506** [xianyi/OpenBLAS#865]
Hi, I am looking for openblas functions for some matrix operations (e.g., add a constant to a matrix or multiply a scalar on a matrix). I can only find some examples for matrix multiplication. Is there any reference material for that?

**Comment by martin-frbg** [comment]
See the documentation of the generic reference implementations of BLAS and LAPACK at www.netlib.org for this (first link on the page, "Browse the netlib repository")
