### ISSUE TITLE
cannot stat libopenblas_armv7-r0.2.16.dev.a: No such file or directory

### ISSUE THREAD

**Issue by jainanshul** [xianyi/OpenBLAS#870]
I am compiling openblas for Arm and the make is successful but when I run `make install` I get an error `cannot stat libopenblas_armv7-r0.2.16.dev.a: No such file or directory`. When I search the tree I see a file libopenblas_armv7**p**-r0.2.16.dev.a instead. Note the letter `p` in the name. I am not sure why openblas `make install` is looking for a different name then the one that got generated.

**Comment by jeromerobert** [comment]
You have to run `make install` with the same arguments as make, particularly if you used the `TARGET=` option.

**Comment by jainanshul** [comment]
That did the trick, thanks for the prompt response.
