### ISSUE TITLE
OpenBLAS compilation error

### ISSUE THREAD

**Issue by rishu271** [xianyi/OpenBLAS#872]
Hi Friends,

I am trying to compile OpenBLAS on x64 under Windows 7, using MinGW. 
I am using MinGW: x86_64-w64-mingw32-gcc-4.7.4-release-win64_rubenvb.7z
with Msys 
I get the following error. 

![image](https://cloud.githubusercontent.com/assets/11375993/15237501/086531a6-18ec-11e6-9de7-41b4e092442b.png)

I have tried the compilation using several version of MinGW. Please suggest.

Thanks

**Comment by martin-frbg** [comment]
Do you see any earlier errors (i.e. when the BLAS functions srot,sdot, saxpy etc. are built) ? If you tried several versions of MinGW, did you do a "make clean" before each new attempt at "make" ?

**Comment by rishu271** [comment]
Hi Martin,

I am doing the make clean before every attempt. Chkd back I am seeing this error in the compilation.

![image](https://cloud.githubusercontent.com/assets/11375993/15243094/522c367e-1917-11e6-8316-2854e13fd89f.png)

**Comment by brada4** [comment]
Are you certain binutils (ar/ranlib) and gcc/gfortran come from same collection?

**Comment by rishu271** [comment]
yes Martin, they are coming from same collection. What makes you think this could be the error. Maybe I can think along that line to figure out the solution.

Thanks

**Comment by martin-frbg** [comment]
That comment wasn't me... the "ln" error you posted does not seem to be directly related (perhaps the underlying filesystem does not support unix-style softlinks). You could try using "nm -s" (if included in your msys kit) or (probably) the windows "link -dump -exports" on the libopenblas_haswellp-r0.2.19.dev.a to see if it has any entries for sdot, srot etc (and if so, how many underscores on them).

**Comment by brada4** [comment]
Try other compiler? There are 2 links to them.

**Comment by rishu271** [comment]
Hi Martin, 
Sorry, I realized later. I checked libopenblas_haswellp-r0.2.19.dev.a  contains the entries for sdot, srot and other compilation error files. Do you think using other openblas package or other combination of c compiler and fortran compiler might work. 
My system is: 
Window 7, 64 bit, Visual studio 2010 is also there. For OpenBLAS compilation I am using 
MinGW: x86_64-w64-mingw32-gcc-4.7.4-release-win64_rubenvb.7z which contains both c++ compiler and gfortran and batch file from msys. Is there something I am missing?
Do you think I need to play more with environment variables or something. 

Thanks

**Comment by rishu271** [comment]
Hi Brada,
I checked the link shared by you. You want me to test out different compilers or different version of OpenBLAS library package.

Thanks

**Comment by brada4** [comment]
I used mingw-builds without any problem.
You are still due to produce full build log from failing build.

**Comment by rishu271** [comment]
Somehow that is not working for me. Still to figure out the solution.

**Comment by jeromerobert** [comment]
@rishu271 We need the `build.log` file created by:

```
bash -c "make clean && make" > build.log 2>&1
```

NOT screenshots. You can upload it on gist.github.com or wherever you want.

I think you did not yet provided enough information to know if you have a compiler problem or not, so I don't think you should look for another compiler for now.

**Comment by brada4** [comment]
'bad reloc address' is very endemic on mingw gcc's. Changing compiler is just lazy shortcut to get around it.

**Comment by rishu271** [comment]
Hi reromerobert,

I am not sure what changed but by the command you wrote above the build was successful. 

I believe there is major difference when we compile using just "make" and "bash -c make". ??
Now I have successfully compiled the libraries and also installation is successful.
Thanks.

**Comment by jeromerobert** [comment]
No there is no difference between `make` and `bash -c make` because you shell is actually `bash`. You most probably forgot to run `make clean` the first time.
