### ISSUE TITLE
Windows build does not build parallel.

### ISSUE THREAD

**Issue by brada4** [xianyi/OpenBLAS#874]
It detects NUM_THREADS just fine but does not set MAKE_NB_JOBS leading to hours of compilation on a top notch CPU
Easy fix is MAKE_NB_JOBS=%NUMBER_OF_PROCESSORS%, but probably detected NUM_THREADS is better reused to mimic normal platforms

**Comment by xianyi** [comment]
Oh. I didn't test it on Windows. Thank you for the report.

**Comment by brada4** [comment]
It should help to speed up #872. In absence of windows DLL to rename into libtatlas.dll i had no choice but to 'test' ;)

**Comment by jeromerobert** [comment]
Multi job make is disabled on Windows by this:
https://github.com/xianyi/OpenBLAS/blob/develop/getarch.c#L1059
I see no reason why.

**Comment by brada4** [comment]
Maybe it has to do with visual studio? I used MSYS.

**Comment by xianyi** [comment]
@jeromerobert , it looks like the old codes from GotoBLAS2.

**Comment by jeromerobert** [comment]
Indeed: https://github.com/xianyi/OpenBLAS/blob/342bbc3/getarch.c#L684

**Comment by brada4** [comment]
@ifndef _MSC_VER

**Comment by jeromerobert** [comment]
@brada4 Could you check that removing the culprit #ifdef work, and does not lead to compilation bug with MSYS ?

**Comment by brada4** [comment]
In a week. I dont keep windows at home.

**Comment by martin-frbg** [comment]
@brada4 did you ever get around to checking if doing parallel makes works on windows nowadays ? (I could imagine it was a mingw limitation some eight years ago - and searching for "mingw make -j" brings up claims that the required jobserver functionality was added to mingw-make only in v3.82.90 of 2012)

**Comment by brada4** [comment]
Yes, MinGW works just fine. What comes to play is omnipresent antiviruses that do not scale anywhere. There is no limit on CPUs without antivirus, but as thay sit and steal kernel cycles build does not speed up (total time taken to build measured by 'time' before and after) past 5-6 CPUs even having 40 directly present.
One CPU limit is not necessary to solve any problem, but some higher upper limit would be nice, say 4...
I need to check with visual studio at least. I think ifdef windows is one needs to be reduced.

**Comment by Neiko2002** [comment]
"mingw make -j" works. Tested with MinGW from msys2.org. The build process of OpenBLAS is maxing out a two socket 56 core system most of the time and finishing the compilation in less than 10 minutes instead of hours. I think the issue can be closed.

**Comment by brada4** [comment]
The code is still there https://github.com/xianyi/OpenBLAS/blob/f5959f2543399b764ee9bf6bf1874dfb7caa9fee/getarch.c#L1184
I think it is one-off attempt to work with abundance of make tools on windows without -j parameter support 
I will make PR (remove -j above, and kill section crippling old windows)

**Comment by brada4** [comment]
Thanks
