### ISSUE TITLE
build error in linux: memory.c:1348, memory.c:1406

### ISSUE THREAD

**Issue by hainanwang** [xianyi/OpenBLAS#875]
Dear friends, 

I am building openblas in linux. I got the following error due to function defined in memory.c. Is this a bug or some other issue? Thanks! 
gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=32 -DASMNAME=memory -DASMFNAME=memory_ -DNAME=memory_ -DCNAME=memory -DCHAR_NAME=\"memory_\" -DCHAR_CNAME=\"memory\" -DNO_AFFINITY -I../.. -c memory.c -o memory.o
memory.c:1348: error: wrong number of arguments specified for 'constructor' attribute
memory.c:1406: error: wrong number of arguments specified for 'destructor' attribute
make[1]: **\* [memory.o] Error 1

line 1348: void CONSTRUCTOR gotoblas_init(void)
line 1406: void DESTRUCTOR gotoblas_quit(void)

Regards,

Hainan

**Comment by martin-frbg** [comment]
Which version of OpenBLAS are you trying to build ? This is closed issue #767, assumed to be fixed by adding compiler-specific guards around the use of "modern" constructor/destructor qualifiers.

**Comment by hainanwang** [comment]
Hi Martin,

I am building openblas 0.2.18.  I tried removing (101) following the instruction in #767 and #700. Now it can be built successfully. FYI, Here is my compiler/OS: 
gcc version 4.1.2 20080704 (Red Hat 4.1.2-52)

Thanks, 

Hainan

**Comment by brada4** [comment]
Your compiler is buggy
There are miscompilation fixes from 2012 and 2014 available from red hat.
If you get in retro computing- would you expect windows 7 to run on an i386?

**Comment by jeromerobert** [comment]
@hainanwang From #700 and http://pkgs.fedoraproject.org/cgit/rpms/openblas.git/tree/openblas-0.2.15-constructor.patch I guess you need:

```patch
--- a/driver/others/memory.c
+++ b/driver/others/memory.c
@@ -144,7 +144,7 @@ USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #if defined(_MSC_VER) && !defined(__clang__)
 #define CONSTRUCTOR __cdecl
 #define DESTRUCTOR __cdecl
-#elif (defined(OS_DARWIN) || defined(OS_SUNOS)) && defined(C_GCC)
+#elif (defined(OS_DARWIN) || defined(OS_SUNOS) || GCC_VERSION < 40300) && defined(C_GCC)
 #define CONSTRUCTOR	__attribute__ ((constructor))
 #define DESTRUCTOR	__attribute__ ((destructor))
 #else
```

Could you try this patch and tell us if it works ? Anyway I guess you'll run in other troubles because your binutils (mainly `as`) are probably too old to build AVX kernels.

**Comment by martin-frbg** [comment]
Sorry, thought susilehtola's patch from #700 had been merged (it should have been, in my opinion).
If necessary, a workaround for ancient RHEL as/binutils too old to support modern cpu instructions would probably be to select a sufficiently old cpu TARGET (make TARGET=... or edit Makefile.rule)

**Comment by brada4** [comment]
RHEL5 will be EOL in a year, and CentOS announced that it is de facto EOL since 2015.
@hainanwang has not updated the RHEL5U1  system for 8 years. There is officially desuported binutils SCL 2.1 with AVX2 support, requiring RHEL5U9 to run.
What about adding a link in FAQ advertising @susilehtola 's product instead?
