### ISSUE TITLE
Issue in make command

### ISSUE THREAD

**Issue by AakashKumarNain** [xianyi/OpenBLAS#880]
I installed cygwin on my windows8.1 and cloned the OpenBLAS. But when I type the 'make' command in the cygwin terminal it shows the following error:
make: perl: Command not found
make: *** [config.h] Error 127
Makefile.system:165: Makefile.conf: No such file or directory
Makefile.system:906: Makefile.: No such file or directory
make: *** No rule to make target 'Makefile.'.  Stop.

Please help!!

**Comment by brada4** [comment]
you have to use msys that includes perl and other basic unix tools (link is in install guide)

**Comment by jeromerobert** [comment]
@AakashKumarNain perl is also available in cygwin
