### ISSUE TITLE
Missing/invisible symbols 

### ISSUE THREAD

**Issue by fcannini** [xianyi/OpenBLAS#881]
Hello there

I'm trying to compile libflame as detailed in this thread:
https://groups.google.com/forum/#!topic/libflame-discuss/M6UbpFnFx6c

The offending code is this:
https://github.com/flame/libflame/blob/master/src/base/flamec/main/FLA_Blocksize.c#L19

As I said in the thread, It seems that the '[s|c|d|z]gemm_[p|q|r] symbols are not being made visible in the resulting .so file. Is this a bug on openblas linking or are these functions deprecated and libflame should not depend on them?

TIA,
Fabricio

**Comment by brada4** [comment]
Go and fix the offending code?
As in discussion thread you link to - it WAS an experimental option in flame library.
OpenBLAS provides only BLAS and LAPACK as seen on netlib.org

**Comment by martin-frbg** [comment]
Which platform, which version of OpenBLAS (and did you build it yourself) ? Does running "nm" on the library show you sgemm_p and others (I see them in the data segment of mine) ? Do you get the same linking problem with a trivial program that does nothing more than "extern long sgemm_p; long bla= sgemm_p; printf("%ld\n",bla);" ?

**Comment by jeromerobert** [comment]
@fcannini [s|c|d|z]gemm_[p|q|r] has never been in OpenBLAS. It was renamed to gotoblas->sgemm_q in GotoBLAS before it became OpenBLAS. So if you want to do such strange and unsupported things you need to:
* build with `DYNAMIC_ARCH=1`
* use `gotoblas_t` from `common_param.h`
* Fix libflame
* Not expect it will work forever as OpenBLAS internal may change again

**Comment by jeromerobert** [comment]
@fcannini I may be wrong. `gotoblas->sgemm_q` seems to be there only when building with `DYNAMIC_ARCH=1`. So may be building without `DYNAMIC_ARCH` will make `sgemm_q` appear again.

**Comment by jeromerobert** [comment]
I confirmed this is all about `DYNAMIC_ARCH`. `sgemm_q` is back again with DYNAMIC_ARCH unset.

**Comment by brada4** [comment]
Flame says option is for gotoblas only. Their ./configure script is wrong allowing build with wrong option.

**Comment by martin-frbg** [comment]
Flame documentation probably uses GotoBLAS/OpenBLAS interchangeably. Wonder what could be the intention between having gotoblas->sgemm_q in the DYNAMIC_ARCH=1 case and just sgemm_q 
for DYNAMIC_ARCH=0. (Though of course jeromerobert's comment on the perils of using "private" internal variables of a third-party library in your code still stands. Perhaps if someone from Flame can make a sufficient case for having access to such internals, OpenBLAS could grow an official interface function for it ?)

**Comment by fcannini** [comment]
@martin-frbg 
platform: centos 6.x
compiler: gcc 4.8.2
openblas version: 0.2.14
Yes, I did compile it myself.

@brada4 @jeromerobert I suspected that these functions were not in the public API, could not confirm for lack of deeper knowledge. :(

@jeromerobert I can confirm that disabling `DYNAMIC_ARCH` makes `sgemm_q` reappear, but we have some very heterogeneous setups out there, hence `DYNAMIC_ARCH` must stay.


Thank you all for your time and attention.

**Comment by heroxbd** [comment]
@fcannini Could you please elaborate how you built libflame with openBLAS?

**Comment by fcannini** [comment]
@heroxbd You mean the `./configure` options? It's all in the libflame thread.

**Comment by heroxbd** [comment]
@fcannini The thread you referred https://groups.google.com/forum/#!topic/libflame-discuss/M6UbpFnFx6c points to this issue.

Did I miss something?  Or just pass --enable-goto-interfaces and done?

**Comment by fcannini** [comment]
Not exactly.
When you pass '--enable-goto-interfaces' , libflame expects symbols that are only available when openblas is compiled **WITHOUT** `DYNAMIC_ARCH=1`, which I need because of the heterogeneity of my environment, so I configured like this:

`export LDFLAGS='-L/path/where/openblas/libs/are'`

`export LIBS='-lopenblaso'`

`./configure --prefix=/where/you/want/to/install --enable-debug --enable-static-build --enable-dynamic-build --enable-supermatrix --enable-lapack2flame --enable-vector-intrinsics=sse --enable-multithreading=openmp`

**Comment by heroxbd** [comment]
Thanks a lot for sharing, fcannini.  That's very helpful to me.
