### ISSUE TITLE
Questions about computing confusion for multi-thread program

### ISSUE THREAD

**Issue by AlfredXiangWu** [xianyi/OpenBLAS#882]
I implement a machine learning algorithm based on OpenBLAS and I encouter some problems about multi-thread program. The inputs of the promgram are two images and the output is a score.

If I use compile commands

1. "make FC=gfortran NUM_THREADS=64 USE_OPENMP=1"
For single thread implementation, the time consuming is about **100ms**. For 8 threads, the total time consuming is about **450ms**. However, for multi-thread implementation, **the scores are different from the single thread results.** 

2. "make FC=gfortran NUM_THREADS=64 USE_OPENMP=0"
For single thread, the time is about **120ms** and the total time is about **1s** for 8 threads. The scores are equal to the single thread results. 

3. "make FC=gfortran NUM_THREADS=64 USE_THREAD=0 USE_OPENMP=1"
For single thread, the time is about **162ms** and the total time is about **260ms** for 8 threads. The scores are equal to the single thread results. 

4. "make FC=gfortran NUM_THREADS=64 USE_THREAD=0 USE_OPENMP=0"
For single thread, the time is about **140ms** and the total time is about **260ms** for 8 threads. The scores are equal to the single thread results. 

I have some questions

1. I want to imporve both single thread and multi-thread efficiency. How do I select the compile command?

2. Why does the command "make FC=gfortran NUM_THREADS=64 USE_OPENMP=1" make the difference between single thread and multi thread implementation?

3. What difference between "USE_THREAD" and "USE_OPENMP"?

Thanks!

**Comment by jeromerobert** [comment]
`USE_THREAD` enable threading using pthread/winthreads while `USE_OPENMP` use OpenMP. `USE_OPENMP` is required if your application also use OpenMP, else you should not use it as it's slower.

I have no explanation for these strange results in your benchmark.

I guess you are working with small matrices. In that case the best that OpenBLAS can do is not multi-threading at all, because threading overhead is to high in comparison of computation time of each blocks. It's not yet perfect at detecting small matrices and we could improve this if your provide a test case.

**Comment by martin-frbg** [comment]
What is the underlying hardware - any chance some of your 8 threads ended up on Intel-style "hyperthreading" pseudocores instead of full-fledged ones ?

**Comment by brada4** [comment]
Can you dismantle your program into blas calls and tell which one is cause of regressions?
Just make loop of each lasting 1s per call until one shows signs of waste.
OPENBLAS_NUM_THREADS= is your good friend.

**Comment by AlfredXiangWu** [comment]
Thanks a lot for the reply!

**Comment by brada4** [comment]
It might never get addressed if you dont show the regression
It would be of value to try to track down the issue
