### ISSUE TITLE
(WINDOWS) _Undefined reference to '_gfortran_concat_string'

### ISSUE THREAD

**Issue by zesiha** [xianyi/OpenBLAS#892]
Hi, developers.

I am trying to apply OpenBlas on android app for solving pseudo inverse problem.
Thus, I need 'dgesvd_' function.

However when I was building that function using android NDK, I faced with _Undefined reference to '_gfortran_concat_string' problem.

I found closed issue#460 which is a same problem in linux environment but I realized the fact that I need android toolchains for windows with gfortran to apply '-lgfortran' option in Android.mk .

Unfortunately currently provided android toolchains are only for linux. I was trying to build android gfortran for windows myself based 'https://github.com/buffer51/android-gfortran' but I faced another problem which is relate to 'gmp : Could not find a working compiler'.

Following is a log of building process.

checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking ABI=32
checking compiler i386-linux-gnu-gcc -O2 -s -D__USE_MINGW_ANSI_STDIO=1 ... no
configure: error: could not find a working compiler, see config.log for details
Makefile:577: recipe for target 'stmp-config-host-gmp' failed
make[1]: *** [stmp-config-host-gmp] Error 1
make[1]: Leaving directory '/tmp/ndk-cmg/build/toolchain/host-i386-linux-gnu'
Makefile:268: recipe for target 'stmp-build-canadian-tools' failed
make: *** [stmp-build-canadian-tools] Error 2
Error while building mingw/darwin toolchain. See /tmp/ndk-cmg/build/toolchain/config.log
Traceback (most recent call last):
  File "./build.py", line 64, in <module>
    build_support.run(main, ArgParser)
  File "/home/cmg/ndk/build/lib/build_support.py", line 277, in run
    main_func(args)
  File "./build.py", line 61, in main
    build_support.build(build_cmd, args)
  File "/home/cmg/ndk/build/lib/build_support.py", line 148, in build
    subprocess.check_call(cmd + common_args, env=build_env)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bash', 'build-gcc.sh', '/home/cmg/toolchain', '/home/cmg/ndk', 'arm-linux-androideabi-4.9', '-j2', '--sysroot=/home/cmg/ndk/platforms/android-9/arch-arm', '--mingw', '--verbose', '--package-dir=/home/cmg/out/dist']' returned non-zero exit status 1

Please anyone help me.
Simply, I just need 'arm-linux-androideabi-gfortran.exe'.

Android Development Environment
OS : WINDOWS 7 64bit
IDE : eclipse
NDK : 11c
Taraget : armv7

gfortran building environment
OS : ubuntu 16.04 64bit (VMware)

Thanks.

**Comment by brada4** [comment]
None of your logs sez a single word about openblas.
This is not place to report bugs in https://github.com/buffer51/android-gfortran
Correct place to report bugs in other software is
https://github.com/buffer51/android-gfortran/issues/new
Please close this as a non-issue.

**Comment by zesiha** [comment]
I see...
