### ISSUE TITLE
/usr/bin/ld: cannot find -lopenblas

### ISSUE THREAD

**Issue by zc129** [xianyi/OpenBLAS#895]
Environment：
gcc 4.4.7
CentOS 6.5
Openblas 0.2.18

When i make rnnlib，it will print:
g++  -g -O2   -o ../bin/rnnlib DataExporter.o Main.o Random.o  -lnetcdf_c++ -lnetcdf -lm -lstdc++ -lopenblas
/usr/bin/ld: cannot find -lopenblas

But I have already installed the Openblas. I also add the library directory in /etc/ld.so.conf and  executive "ldconfig".
I want to know where there's a problem. Thanks.

**Comment by brada4** [comment]
How did you 'have installed' OpenBLAS?
yum install from fedora epel?

**Comment by zc129** [comment]
@brada4 
I use the compiler installation.
I tried to delete the library, add the library again,it works.
Thank you!
