### ISSUE TITLE
Compiling OpenBLAS for theano

### ISSUE THREAD

**Issue by Vivek-B** [xianyi/OpenBLAS#904]
Hi!

I was getting this error **"If on CPU, do you have a BLAS library installed Theano can link against?"**, while training a convolutional neural network in keras. I''m trying to install openblas as suggested in the theano page [here](http://deeplearning.net/software/theano/install_windows.html#install-windows) (under 'Compile a faster BLAS' section).

I unzipped openblas from [here](https://sourceforge.net/projects/openblas/files/) and from that folder when I run "quickbuild.win32 1>log.txt 2>err.txt" in the command prompt, it is not extracting the linopenblas.dll file. 

I've also tried **"mingw32-make"** command while in the openblas folder.

Could you please guide in how to get the libopenblas.dll file.

**Comment by jeromerobert** [comment]
Could you provide the error messages ?

**Comment by Vivek-B** [comment]
Please find it [here](https://github.com/Vivek-B/Kaggle/blob/master/Digit%20Recognition/Conv-2D%20--%20Keras.ipynb)

**Comment by martin-frbg** [comment]
Could you provide the two files "log.txt" and "err.txt" from the "quickbuild.win32" run ? (The "1>" and "2>" are redirection commands that store regular output and error messages in the respective files instead of displaying them, making it look like "its doing nothing", but allowing to review the messages later.)

**Comment by Vivek-B** [comment]
The issue is resolved. It worked with developer version of cygwin. 
I think there was an issue with mingw.

Anyway, there were no such .txt files generated.

**Comment by brada4** [comment]
Can you post exact error messages? That 'make says no no' does not look authentic.
Your guide does not mention any cygwin.
WinXX builds assume mingw, which you probably will never need if you read everything before 'build your own' chapter.

**Comment by Vivek-B** [comment]
When I run just **'mingw32-make'**, here is the error message 

![mingw-error](https://cloud.githubusercontent.com/assets/12795352/15768968/d0fe4c1e-2973-11e6-8541-19afb99ce7d8.png)

When I run **'mingw32-make quickbuild.win32 1>log.txt 2>err.txt**', Nothing was shown in cmd, but here are the .txt files in the folder. 

[log.txt](https://github.com/xianyi/OpenBLAS/files/296928/log.txt)

[err.txt](https://github.com/xianyi/OpenBLAS/files/296929/err.txt)

Yes, the theano guide doesn't mention cygwin, but when I tried **'make'** with it's developer's version it worked.

After extracting libopenblas.dll, I tried the convolutiona NN again, [here](https://github.com/Vivek-B/Kaggle/blob/master/Digit%20Recognition/Conv-2D_Keras.ipynb) is the latest error message.

Theano's guide say's that, in case of such error, try to find the missing dll's from dependency walker. Unfortunately, I cannot upload the dependency walker's error log file here.

**Comment by brada4** [comment]
You are missing MSYS from mingw:
https://github.com/xianyi/OpenBLAS/wiki/Installation-Guide#windows
I see you are using Anaconda python, in this case you have a copy of MKL BLAS libsrary included and can load Theano using pip. I dont see any errors in 'here' link past that you use out-of-date theano which calls deprecated functions from other libraries.
