### ISSUE TITLE
error accurs when compile benchmark for android after successfully compiling openblas for android, need  help

### ISSUE THREAD

**Issue by chenminminchen** [xianyi/OpenBLAS#914]
i've succesfully compiled openblas 0.2.18 for android on ubuntu by using the method:https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android, but when i enter benchmark floder,and make TARGET=ARMV8 BINARY=64 HOSTCC=gcc CC=aarch64-linux-android-gcc NOFORTRAN=1, it doesn't work:

ubuntu001:~/OpenBlas/OpenBLAS-0.2.18/benchmark$ make TARGET=ARMV8 BINARY=64 HOSTCC=gcc CC=aarch64-linux-android-gcc  > log.txt
slinpack.o: In function `main':
linpack.c:(.text.startup+0x32c): undefined reference to`sgetrf_'
linpack.c:(.text.startup+0x398): undefined reference to `sgetrs_'
collect2: error: ld returned 1 exit status
make: **\* [slinpack.goto] Error 1

by the way, i have installed the standalone toolchain by using :
$NDK/build/tools/make-standalone-toolchain.sh \
--arch=arm64 --platform=android-21 --install-dir=/tmp/my-android-toolchain
and add the path:
export NDK_HOME=~/NDK/android-ndk-r10e/tmp/my-android_toolchain
export PATH=$NDK_HOME/bin:$PATH

i'm a greenhand to openblas and cross compile, can anybody help me ?

**Comment by brada4** [comment]
_getrs are lapack functions which in turn need fortran to build that you disabled for library build but enabled for benchmarking. You must pass same build flags to benchmatks as to library build.

**Comment by chenminminchen** [comment]
@brada4 ,thanks for your reply. U mean that i must build openblas with 
make TARGET=ARMV8 BINARY=64 HOSTCC=gcc CC=aarch64-linux-android-gcc 
without NOFORTRAN=1? and build benchmark with the same command above? so that i need to install fortran , i'll try this and put on my test result.

**Comment by brada4** [comment]
google NDK does not have fortran, you have to read OpenBLAS FAQ to get it.
benchmarks expect to be on native CPU to run, they will build, but fail to measure anything unless on the Android v21
