### ISSUE TITLE
Build OpenBLAS for Android

### ISSUE THREAD

**Issue by luysome** [xianyi/OpenBLAS#919]
I tried` make TARGET=ARMV8 BINRAY=64 HOSTCC=gcc CC=aarch64-linux-android-gcc NOFORTRAN=1` However, compilation failed with error "stdio.h: no such file or directory". Shall I add Android standard c library?

**Comment by luysome** [comment]
I modified the Makefile.system, and add -I /path/to/platforms/android/arch-arm64/usr/include and fixed this issue

**Comment by brada4** [comment]
There is typo in your statement. Why dont you close the issue with your build environment?
