### ISSUE TITLE
Incorrect handling of linker option

### ISSUE THREAD

**Issue by qwer1304** [xianyi/OpenBLAS#920]
Hi,
For some reason my toolchain returns --exclude-libs option when asked for the options by c_check and f_check scripts when building Makefile.conf.
These options need to be prepended with "-Wl," (without the quotes), or the build will fail.

Cheers,
D

PS Took me a LONG to figure that out :(

**Comment by martin-frbg** [comment]
So what is your toolchain (and platform) ? Can you find out if it is c_check, f_check or both which get this result (running make NO_LAPACK=1 will probably omit the f_check) ?
A quick look in c_check suggests that it might depend on the presence of a "-Y" among the linker commands seen whether -Wl gets prepended to an option flag (around line 200 of that perl script, the linker options are determined by building ctest2). f_check has a similar loop around line 270 where only the -Y and -rpath options get a -Wl prepended. 
The trivial solution would probably be to copy and adapt the "if ($flags =~ /^\-rpath\@/) " block there (probably without the embedded vendor check for PGI).

**Comment by qwer1304** [comment]
Win 10 x64, Cygwin64, MinGW toolchain (TDM-GCC-64 4.9.2), HP Spectre X360 i7 5500U
I hacked a version of c_check and f_check to prepend -Wl, to the exclude-libs option.I'm not a Perl programmer or a toolchain expert, so feel free to do this in a proper way.

Date: Tue, 5 Jul 2016 00:35:13 -0700

**Comment by brada4** [comment]
Can you upload a build log?

**Comment by qwer1304** [comment]
The fixed or the broken?
And how do I get the log?

Date: Tue, 5 Jul 2016 23:16:43 -0700

**Comment by brada4** [comment]
You start command 'script', run your build, type quit and all terminal IO between is found in typescript file. Change extension to txt and attach via web interface. Broken build must get through faster and show error.

**Comment by qwer1304** [comment]
Problem is I'd need to rebuild the whole thing, which takes too long :(Recall that I managed to get a working system ;)

Date: Thu, 7 Jul 2016 15:02:23 -0700

**Comment by brada4** [comment]
unzip latast release in a new directory ;)

**Comment by qwer1304** [comment]
This is the log with the error from a fresh install

Date: Fri, 8 Jul 2016 17:25:22 -0700

**Comment by qwer1304** [comment]
Hi,I just noticed that it looks as if script didn't record the whole session.Anyway, the following is the tail of the run (where the error occurs):
gcc -O2 -DMS_ABI -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  libopenblas.def dllinit.obj \-shared -o ../libopenblas.dll -Wl,--out-implib,../libopenblas.dll.a \-Wl,--whole-archive ../libopenblas_haswellp-r0.2.18.a -Wl,--no-whole-archive -LC:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2 -LC:/TDM-GCC-64/bin/../lib/gcc -LC:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/lib/../lib -LC:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../lib -LC:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/lib -LC:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../..  -lgfortran -lmingw32 -lmoldname -lmingwex -lmsvcrt -lquadmath -lm -lmingw32 -lmoldname -lmingwex -lmsvcrt -lpthread -lmingw32 -lmoldname -lmingwex -lmsvcrt  --exclude-libs=libpthread.a  -defaultlib:advapi32 -lgfortran -defaultlib:advapi32 -lgfortrangcc.exe: error: unrecognized command line option '--exclude-libs=libpthread.a'make[1]: *** [Makefile:94: ../libopenblas.dll] Error 1make[1]: Leaving directory '/home/david/xianyi-OpenBLAS-3f6398a/exports'make: *** [Makefile:102: shared] Error 2

From: qwer1304@hotmail.com
To: reply@reply.github.com
Subject: RE: [xianyi/OpenBLAS] Incorrect handling of linker option (#920)
Date: Sat, 9 Jul 2016 11:56:38 +0300




This is the log with the error from a fresh install

Date: Fri, 8 Jul 2016 17:25:22 -0700

**Comment by brada4** [comment]
Linking to msvcrt.dll looks like mingw. 
Are you certain you have no mingw in path and all used tools are from cygwin?

**Comment by qwer1304** [comment]
Environment is cygwin,  but tool chain is mine.


Get Outlook for Android






On Sun, Jul 10, 2016 at 4:44 PM +0300, "Andrew" <notifications@github.com> wrote:





Linking to msvcrt.dll looks like mingw.
Are you certain you have no mingw in path and all used tools are from cygwin?

---

**Comment by brada4** [comment]
--exclude-libs parameter does not come from openblas.
It is a general problem with your toolchain

**Comment by qwer1304** [comment]
Yes, it's not a problem generated by openBLAS, but it's a problem which prevents openBLAS to be built, and I'm not the only one who experience it (see http://stackoverflow.com/questions/37817330/unrecognized-command-line-option-exclude-libs-libpthread-a-openblas-mingw-w6 ), which I traced down to where exactly it occurs and how to circumvent it.
You can integrate it into openBLAS for the benefit of other users or bury your head in the sand and disregard this. Your choice.

Date: Sun, 10 Jul 2016 14:05:00 -0700

**Comment by martin-frbg** [comment]
Just to clarify - did you find it necessary to modify both c_check and f_check for compilation to work (the latter already recognized some linker flags, the former not) ?
(BTW the github bugtracker does not distinguish between developers, users or for that matter anybody else. So it is perfectly possible to get categorical-sounding replies from somebody who never contributed a single line of code)

**Comment by qwer1304** [comment]
Yes, both c_check and f_check had to be changed in the same way.

Date: Mon, 11 Jul 2016 00:20:28 -0700

**Comment by martin-frbg** [comment]
Returning to this old issue with the intention to provide a pull request (i.e., patch) that would allow to close it, I now find that 
(a) this problem _appears_ to be peculiar to the TDM-GCC flavor of mingw (or its default specs file), see https://sourceforge.net/p/tdm-gcc/bugs/192/
(b) I am not sure how to test my changes with only a more common compiler environment. Could you please post your changes if you still have them, or tell me if just adding
>       if ($flags =~ /^\--exclude-libs/) {
>           $linker_L .= "-Wl,". $flags . " "
>       }

to both c_check and f_check is what you did to get it to compile ?

**Comment by atyahoodotcom** [comment]
Hello,

I'm running the TDM-GCC flavor of MingW and I am having this error.

I added those lines at line 237 in c_check and line 302 in f_check and it did not work.

**Comment by martin-frbg** [comment]
What does the Makefile.conf look like (I assume you _did_ do a "make clean" before trying with the proposed changes) ? Do you see the exclude-libs option there only without the -Wl, or do you see both variants now ? I just tried this substitution with the --enable-ssp flag that is a standard option for my gcc/gfortran and it did add the expected (though obviously nonsensical) -Wl,--enable-ssp to both CEXTRALIB and FEXTRALIB.

**Comment by atyahoodotcom** [comment]
Hello,

2 things: You are correct in that it affects the TDM-GCC flavor of MingW only. I tried with a different toolchain (MingW-w64) and it worked.

I ran "make clean" after editing c_check and f_check. 
`Makefile.conf`
```bash
OSNAME=WINNT
ARCH=x86_64
C_COMPILER=GCC
BINARY32=
BINARY64=1
CROSS=1
CEXTRALIB=-Wl,--exclude-libs=libpthread.a -LC:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0 -LC:/TDM-GCC-64/bin/../lib/gcc -LC:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x
86_64-w64-mingw32/lib/../lib -LC:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../lib -LC:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/lib -LC:/T
DM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../..  -lmingw32 -lmoldname -lmingwex -lmsvcrt -lpthread -lmingw32 -lmoldname -lmingwex -lmsvcrt  --exclude-libs=libpthread.a
F_COMPILER=GFORTRAN
FC=gfortran
BU=_
FEXTRALIB=-Wl,--exclude-libs=libpthread.a -LC:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0 -LC:/TDM-GCC-64/bin/../lib/gcc -LC:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x
86_64-w64-mingw32/lib/../lib -LC:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../lib -LC:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/lib -LC:/T
DM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../..  -lgfortran -lmingw32 -lmoldname -lmingwex -lmsvcrt -lquadmath -lm -lmingw32 -lmoldname -lmingwex -lmsvcrt -lpthread -lmingw32 -lmoldname -
lmingwex -lmsvcrt  --exclude-libs=libpthread.a
CORE=HASWELL^M
```

**Comment by martin-frbg** [comment]
Thanks. It looks as if the changes to c_check and f_check do work, but the unchanged parameter still creeps in at the end of the line (which, if I read c_check and f_check correctly, would appear to be the $linker_a argument that seems to collect all those linker flag options that end in a ".a" phrase).
I suspect all that is needed is a 
$flags = ""
in the new "if" block after the line that adds the -Wl for the linker_L argument in both c_check and f_check ?

**Comment by atyahoodotcom** [comment]
I replaced 

```bash
  if ($flags =~ /^\--exclude-libs/) {
      $linker_L .= "-Wl,". $flags . " "
  }
```

with this:
```bash
  if ($flags =~ /^\--exclude-libs/) {
      $linker_L .= "-Wl,". $flags . " "
      $flags = ""
  }
```

After a `make clean` I get:
```bash
Scalar found where operator expected at ./c_check line 239, near "$flags"
        (Missing semicolon on previous line?)
syntax error at ./c_check line 239, near "$flags "
Execution of ./c_check aborted due to compilation errors.
```

**Comment by martin-frbg** [comment]
Probably needs a semicolon on the end of at least the first of the two lines inside the braces
(my perl is a bit rusty to say the least)

**Comment by atyahoodotcom** [comment]
Hey thanks. It works now!
