### ISSUE TITLE
Compilation from source failed - Error Lapack install

### ISSUE THREAD

**Issue by lilouch** [xianyi/OpenBLAS#921]
Hi,

I try to compile OpenBlas but I get an error and I cannot figure out how to handle it. 
I did "make" then after 30s-1min, I got this error : 

```
       REAL               ETIME
                              1
Warning: Type specified for intrinsic function 'etime' at (1) is ignored [-Wsurprising]
/var/folders/9m/0wnj73xd2dx5l1npf3vclz2h0000gn/T//ccSGCXxv.s:26:suffix or operands invalid for `movq'
/var/folders/9m/0wnj73xd2dx5l1npf3vclz2h0000gn/T//ccSGCXxv.s:27:suffix or operands invalid for `movq'
make[2]: *** [dsecnd_INT_ETIME.o] Error 1
make[1]: *** [lapack_install] Error 2
make: *** [netlib] Error 2
```

I have OSX El Capital.
Could you please help me ?
Thank

**Comment by martin-frbg** [comment]
Looks like your build environment picks an assembler that belongs to a different compiler, or is too old for your cpu. Does https://github.com/JuliaLang/julia/issues/16876 or https://github.com/Homebrew/legacy-homebrew/issues/45258 help ?

**Comment by xianyi** [comment]
Please upgrade xcode to 7.3 version.
