### ISSUE TITLE
build openblas with cygwin+android-ndk-r12b,

### ISSUE THREAD

**Issue by wdbsf** [xianyi/OpenBLAS#928]
in cygwin, run ./build.sh,  get error result:

axpy.c:39:17: fatal error: stdio: No such file or directory
 #include <stdio>

how to solve it?

**Comment by wdbsf** [comment]
export PATH=$NDK_ROOT/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin:$PATH
make TARGET=ARMV7 HOSTCC=gcc CC=arm-linux-androideabi-gcc NOFORTRAN=1

get error result
axpy.c:39:19: fatal error: stdio.h: No such file or directory

**Comment by martin-frbg** [comment]
Seems there are fundamental parts missing from your toolchain, did you follow the  build notes from the wiki here: https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android ?

**Comment by wdbsf** [comment]
environment: win7+cygwin + android-ndk-r12b

do as same as : https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android 
export PATH=$NDK_ROOT/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin:$PATH
make TARGET=ARMV7 HOSTCC=gcc CC=arm-linux-androideabi-gcc NOFORTRAN=1

**Comment by brada4** [comment]
I have impression windows path separator is other one.

**Comment by martin-frbg** [comment]
I do not think the path separator plays a role here. Can you do a search for "stdio.h" below your ndk installation directory ? Searching the 'net for similar issues suggests you might have to define SYSROOT to point to the appropriate platform-specific directory.
(Failing that, can you try with an earlier release of the ndk in case it might be a packaging issue with what appears to be a beta pre-release of ndk12 ?)

**Comment by brada4** [comment]
stdio.h defines sizeof() macro
Unlikely this gcc builds anything.
From ndk r11you should (maybe) type clang where gcc is,and use 'make' in place of build.sh for any version

**Comment by martin-frbg** [comment]
Please see suggestions in #952,#953 if you still have this problem. (Please close if the problem is solved)

**Comment by martin-frbg** [comment]
More to the point, see the compilation script that quickwritereader posted in #963 - it sets up the sysroot entry in the CFLAGS so that stdio.h and other include files are found.
