### ISSUE TITLE
../libopenblas_sandybridge-r0.2.18.so: undefined reference to `zerbla_'

### ISSUE THREAD

**Issue by bin-mech** [xianyi/OpenBLAS#932]
compiled latest stable version with intel compiler version 15, ending up with following error.
`../libopenblas_sandybridge-r0.2.18.so: undefined reference to`zerbla_'`
for version less than 2.16, can be compiled perfectly.

**Comment by xianyi** [comment]
Could you try develop branch?

**Comment by martin-frbg** [comment]
To expand on what xianyi wrote,  this looks to be closed issue #910 - a "mostly harmless" z-for-an-x typo introduced in LAPACK-3.6.0 (which OpenBLAS was updated to around 2.16). If for some reason you cannot switch to the current develop branch, you can find the trivial fix to apply in #910.

**Comment by martin-frbg** [comment]
This fix was included in 0.2.19 which was released on September 1st.
