### ISSUE TITLE
I want to make sure that AVX is used

### ISSUE THREAD

**Issue by rmekdma** [xianyi/OpenBLAS#934]
In 'config.h' there is a line: `#define HAVE_AVX`
But I can't find any line using `HAVE_AVX` except when defining `xgetbv()` function.
Also I don't see compile flags related to AVX such as `-mavx` or `-mavx2`.

Is this normal? Is there any way I can check if AVX is successfully being used?
Thank you!

**Comment by martin-frbg** [comment]
I may be wrong, but I believe the HAVE_AVX #define is only used to pick the cpu type to optimize for (but you should see actual avx mnemonics being used in the optimized assembly implementations of
BLAS functions for such cpus, e.g. `kernel/x86_64/*haswell*` )

**Comment by rmekdma** [comment]
Thanks! I think I found [AVX2/FMA intrinsics](https://software.intel.com/en-us/node/513925) like `VFMADDPS` in those files.
