### ISSUE TITLE
Cross compiling ARMV5

### ISSUE THREAD

**Issue by henring** [xianyi/OpenBLAS#935]
Hello,

I try to compile OpenBLAS library on my MAC (OS X El capitan, Darwin, x86_64, i386) with this following command : 
`make TARGET=ARMV5 HOSTCC=gcc CC=arm-cortex_a8-linux-gnueabi-gcc ONLY_CBLAS=1 
`

It didn’t go so well, here the output :
```
../libopenblas_armv5p-r0.2.18.a: member ../libopenblas_armv5p-r0.2.18.a(cblas_isamax.o) in archive is not an object
collect2: error: ld returned 1 exit status
make[1]: *** [../libopenblas_armv5p-r0.2.18.so] Error 1
make: *** [shared] Error 2
```

**Comment by jeromerobert** [comment]
May be you need to set `FC` to a Fortran ARM compiler even if you set `ONLY_CBLAS=1`.

**Comment by martin-frbg** [comment]
Is this the first compile in that directory, or could it be picking up files from a previous, non-cross compilation ? The message suggests that the linker does not recognize the libopenblas.a as a valid ARM archive (could it be x86 from a native build - running "file" on it would probably tell)

**Comment by henring** [comment]
Thanks jeromerobert and martin-frbg for your help.

You are right, I precompile the library with make following the README, but the cross-compiling failed just after because I did not have clean the directory before that.

**Comment by martin-frbg** [comment]
Sounds good so far. Please close this ticket if running "make clean" before the cross-compilation actually solves the problem.
