### ISSUE TITLE
Cross compile to CORTEXA9 does not complete

### ISSUE THREAD

**Issue by davmaz** [xianyi/OpenBLAS#936]
After make clean, I ran 
sudo make BINARY=32 CC=/usr/local/bin/gcc FC=/usr/local/bin/gfortran HOSTCC=gcc TARGET=CORTEXA9

This goes a LONG way forward, but dies on 
ar  -ru ../libopenblas_cortexa9p-r0.2.19.dev.a samax_k.o samin_k.o smax_k.o smin_k.o isamax_k.o isamin_k.o ismax_k.o ismin_k.o sasum_k.o saxpy_k.o scopy_k.o sdot_k.o sdsdot_k.o dsdot_k.o snrm2_k.o srot_k.o
...
...
 zomatcopy_k_rt.o zomatcopy_k_cnc.o zomatcopy_k_rnc.o zomatcopy_k_ctc.o zomatcopy_k_rtc.o zimatcopy_k_cn.o zimatcopy_k_rn.o zimatcopy_k_ct.o zimatcopy_k_rt.o zimatcopy_k_cnc.o zimatcopy_k_rnc.o zimatcopy_k_ctc.o zimatcopy_k_rtc.o zgeadd_k.o zneg_tcopy.o zlaswp_ncopy.o lsame.o scabs1.o dcabs1.o cpuid.o
ar: sgemm_kernel.o: No such file or directory
make[1]: *** [libs] Error 1
make[1]: Leaving directory `/home/dmazzoni/Downloads/OpenBLAS/OpenBLAS-develop/kernel'
make: *** [libs] Error 1

**Comment by brada4** [comment]
There shpuld be some error before.
Can you attach full build output?
$ make clean
$ make [your params] 2>&1 >>make.log

**Comment by martin-frbg** [comment]
In non-cross compiling, this fault with sgemm_kernel.o appears to come up when the build system is confused about the type and capabilities of the cpu (wrong combination of arguments supplied to make, or running in an emulator that provides an unusual subset of host cpu features to the virtual machine).
What is your build environment here ?

**Comment by davmaz** [comment]
Hello all -
  Thanks for your suggestions and help. I've got OpenBLAS to cross compile using:

make CC=arm-linux-gnueabihf-gcc FC=arm-linux-gnueabihf-gfortran HOSTCC=gcc TARGET=CORTEXA9

Dave
________________________________________

**Comment by brada4** [comment]
An d who closes this ticket?

**Comment by martin-frbg** [comment]
Would it make sense to create a wiki entry out of this (I see there is "how to build for android, but no cross-compiling tip that fits davmaz' case) ?

**Comment by davmaz** [comment]
Yes, that would be nice. I can outline what I did for everything to work (thanks to you).
________________________________________

**Comment by martin-frbg** [comment]
I believe the wiki is currently open for anyone here to write.
(btw brada4's not so subtle hint refers to the fact that a ticket can only be closed by its creator or by the project owner - xianyi appears to be pretty busy with other things at the moment and there is a slow but steady buildup of resolved but not closed tickets that threatens to hide the really important open problems.)

**Comment by davmaz** [comment]
These steps worked:
Find all installed packages for the ARM compiler: sudo aptitude search arm-linux-gnueabi
Purge ALL gnueabi versions: sudo apt-get purge --auto-remove gfortran-arm-linux-gnueabi, etc for any "installed"
Install only gnueabihf versions: sudo aptitude install gfortran-arm-linux-gnueabihf (this also installs gnueabihf gcc)
From the OpenBLAS directory: make CC=arm-linux-gnueabihf-gcc FC=arm-linux-gnueabihf-gfortran HOSTCC=gcc TARGET=CORTEXA9
Install the ARM libs: sudo make PREFIX=/usr/local install

**Comment by davmaz** [comment]
I put the steps that worked for me in a final comment and closed the issue.
Thanks!
________________________________

**Comment by xianyi** [comment]
Add an example for cross compiling ARM.
https://github.com/xianyi/OpenBLAS/wiki/User-Manual#compile
