### ISSUE TITLE
OpenBLAS-0.2.18 compile error on Cygwin64

### ISSUE THREAD

**Issue by xiyaoxin** [xianyi/OpenBLAS#939]
Hi All,

I am trying to build openblas on Cygwin64. The pre-build configuration goes just fine, but when I start make, the error occurs:

cd 'G:/Xiyao/opensource/OpenBLAS-0.2.18'
C:\cygwin64\bin\make.exe -f Makefile
Scanning dependencies of target kernel
[  0%] Building C object kernel/CMakeFiles/kernel.dir/CMakeFiles/lsame.c.o
[  0%] Building C object kernel/CMakeFiles/kernel.dir/CMakeFiles/scabs1.c.o
In file included from /cygdrive/g/Xiyao/opensource/OpenBLAS-0.2.18/common.h:741:0,
                 from /cygdrive/g/Xiyao/opensource/OpenBLAS-0.2.18/kernel/generic/cabs.c:40,
                 from /cygdrive/g/Xiyao/opensource/OpenBLAS-0.2.18/kernel/CMakeFiles/scabs1.c:9:
/cygdrive/g/Xiyao/opensource/OpenBLAS-0.2.18/common_thread.h:107:3: error: unknown type name 'CRITICAL_SECTION'
   CRITICAL_SECTION lock;
   ^
/cygdrive/g/Xiyao/opensource/OpenBLAS-0.2.18/common_thread.h:108:3: error: unknown type name 'HANDLE'
   HANDLE finish;
   ^
make[2]: **\* [kernel/CMakeFiles/kernel.dir/build.make:87: kernel/CMakeFiles/kernel.dir/CMakeFiles/scabs1.c.o] Error 1
make[1]: **\* [CMakeFiles/Makefile2:392: kernel/CMakeFiles/kernel.dir/all] Error 2
make: **\* [Makefile:95: all] Error 2

Coud you please give me some advices?

Thank you.

Xiyao

**Comment by martin-frbg** [comment]
This looks as if your cygwin installation does not have (or does not find) a suitable windows.h (or for some reason OS_WINDOWS is not set, which normally triggers inclusion of windows.h from common.h around line 110, long before common_thread.h is read). It could be that you need to install the "w32api-headers" package from cygwin.

**Comment by martin-frbg** [comment]
Did you manage to resolve this in the meantime, or do you need further assistance ? Note also that the precompiled windows binaries on sourceforge have been updated to the current 0.2.19 release a few weeks ago so you could probably also try using those instead of building your own.

**Comment by gongliyu** [comment]
Hi Xiaoyi,

I got the same problem. And I had already installed the w32api-headers package. I want to build the library on cygwin because another library which I also want to build depends on this one. Does OpenBLAS support cygwin? If it is not, I should give up trying.

Thanks!
Liyu

**Comment by martin-frbg** [comment]
In principle it should, since the early days of libGoto. Perhaps there is something wrong with your PATH setting, leading to a stock Windows utility of the same name being called instead of the cygwin-supplied one ? The cygwin wiki has installation instructions for gcc at  http://cygwin.wikia.com/wiki/How_to_install_a_newer_version_of_GCC - while this is very obviously the wrong topic, maybe its sections "Verify Cygwin Prerequisites" and "Check Environment Variables" can provide a clue ?
