### ISSUE TITLE
Please, supply binary files for Windows

### ISSUE THREAD

**Issue by Arech** [xianyi/OpenBLAS#940]
Hi!
I think, it was a great idea to supply binary packages for Windows. However I've noticed that [registry](https://sourceforge.net/projects/openblas/files/) contains no new binaries for versions newer than 0.2.15.
Could you please continue making binaries for new versions?
Thank you!

**Comment by Jaxan** [comment]
I agree.

Also the homepage seems to be out of date regarding this issue. It advertitses binary packages, and then links to sourceforge where one can download the source (only if you know you have to get version 0.2.15, you will get to binaries).

**Comment by sarthakcbica** [comment]
Hi, are there any binaries available for Windows on Sourceforge? I still wasn't able to find any. Thanks!

**Comment by martin-frbg** [comment]
It appears that Windows binaries of 0.2.19 were uploaded to Sourceforge on November 8 so this can
probably be closed ?
(The big OpenBLAS-v0.2.19-Win64-int32.zip has .a and .dll versions of the library, the Win32
version appears to lack the dll ones however - not sure if this will create problems for anyone)

**Comment by sarthakcbica** [comment]
Yup, thanks!

**Comment by lofrank** [comment]
> the Win32
version appears to lack the dll ones however - not sure if this will create problems for anyone

@martin-frbg 
Is it possible to provide win32 dll?
I'm using windows and build 64 bit version via MSYS successfully, but unable to build the 32 bit version.

It's great helpful if the 32 bit dll can be provided officially.

Thanks

**Comment by martin-frbg** [comment]
I do not have access to xianyi's sourceforge account and probably cannot replicate his exact method of building the windows packages anyway. What I have done is upload a 32 bit dll I cross-compiled under Linux in response to #1073 where the topic came up again - the author of that issue ticket decided to go with the old 0.2.15 package rather than try my dll however.

**Comment by lofrank** [comment]
@martin-frbg 
Thanks very much. 
I will test it tonight and provide feedback on that topic.

**Comment by aureosun** [comment]
sir? I have downloaded the OpenBLAS-v0.2.19-Win64-int32,but when I test it on vs2013 with the example code given by xainyi:

#include <cblas.h>
#include <stdio.h>
void main()
{
	int i = 0;
	double A[6] = { 1.0, 2.0, 1.0, -3.0, 4.0, -1.0 };
	double B[6] = { 1.0, 2.0, 1.0, -3.0, 4.0, -1.0 };
	double C[9] = { .5, .5, .5, .5, .5, .5, .5, .5, .5 };
	cblas_dgemm(CblasColMajor, CblasNoTrans, CblasTrans, 3, 3, 2, 1, A, 3, B, 3, 2, C, 3);

	for (i = 0; i<9; i++)
		printf("%lf ", C[i]);
	printf("\n");
}

there are erors !
错误	1	error LNK2019: 无法解析的外部符号 _cblas_dgemm，该符号在函数 _main 中被引用	E:\code practise\OpenCompute\OpenCompute\speed.obj	OpenCompute
错误	2	error LNK1120: 1 个无法解析的外部命令	E:\code practise\OpenCompute\Debug\OpenCompute.exe	OpenCompute
I‘m using the chinese version of vs,Could you please give me some suggestions?

**Comment by martin-frbg** [comment]
Not sure I can help with VS build issues unfortunately. Are you sure that the libopenblas.dll is picked up by vs2013 at all ? (Perhaps try placing it in the same folder as the files you are trying to build just to see if that helps)
