### ISSUE TITLE
Compile error 

### ISSUE THREAD

**Issue by cklcklcklckl** [xianyi/OpenBLAS#945]
I was compiling Openblas but it didn't work.
What should I do next?

C:\MinGW\bin\ar.exe: sgemm_kernel.obj: No such file or directory
make[1]: **\* [libs] Error 1
make[1]: Leaving directory `/c/nopenblas/1/kernel'
make: **\* [libs] Error 1

**Comment by xianyi** [comment]
What's your CPU?

**Comment by cklcklcklckl** [comment]
AMD A8 8600p

**Comment by xianyi** [comment]
```
make clean
make TARGET=EXCAVATOR
```

**Comment by martin-frbg** [comment]
Did you manage to get it working in the meantime with xianyi's suggestions, or do you need further assistance ?
