### ISSUE TITLE
cann't find the body of the function: static int(*gemm[])(blas_arg_t *, BLASLONG *, BLASLONG *,

### ISSUE THREAD

**Issue by hjl150505** [xianyi/OpenBLAS#947]
In the directory interface/gemm.c 
the coed as below:
static int(*gemm[])(blas_arg_t *, BLASLONG *, BLASLONG *, FLOAT *, FLOAT *, BLASLONG) = {
#ifndef GEMM3M
	GEMM_NN, GEMM_TN, GEMM_RN, GEMM_CN,
	GEMM_NT, GEMM_TT, GEMM_RT, GEMM_CT,
	GEMM_NR, GEMM_TR, GEMM_RR, GEMM_CR,
	GEMM_NC, GEMM_TC, GEMM_RC, GEMM_CC,
#if defined(SMP) && !defined(USE_SIMPLE_THREADED_LEVEL3)
	GEMM_THREAD_NN, GEMM_THREAD_TN, GEMM_THREAD_RN, GEMM_THREAD_CN,
	GEMM_THREAD_NT, GEMM_THREAD_TT, GEMM_THREAD_RT, GEMM_THREAD_CT,
	GEMM_THREAD_NR, GEMM_THREAD_TR, GEMM_THREAD_RR, GEMM_THREAD_CR,
	GEMM_THREAD_NC, GEMM_THREAD_TC, GEMM_THREAD_RC, GEMM_THREAD_CC,
#endif
#else
	GEMM3M_NN, GEMM3M_TN, GEMM3M_RN, GEMM3M_CN,
	GEMM3M_NT, GEMM3M_TT, GEMM3M_RT, GEMM3M_CT,
	GEMM3M_NR, GEMM3M_TR, GEMM3M_RR, GEMM3M_CR,
	GEMM3M_NC, GEMM3M_TC, GEMM3M_RC, GEMM3M_CC,
#if defined(SMP) && !defined(USE_SIMPLE_THREADED_LEVEL3)
	GEMM3M_THREAD_NN, GEMM3M_THREAD_TN, GEMM3M_THREAD_RN, GEMM3M_THREAD_CN,
	GEMM3M_THREAD_NT, GEMM3M_THREAD_TT, GEMM3M_THREAD_RT, GEMM3M_THREAD_CT,
	GEMM3M_THREAD_NR, GEMM3M_THREAD_TR, GEMM3M_THREAD_RR, GEMM3M_THREAD_CR,
	GEMM3M_THREAD_NC, GEMM3M_THREAD_TC, GEMM3M_THREAD_RC, GEMM3M_THREAD_CC,
#endif
#endif
};
==================================
The question is: where is the function body? Where can i find it? could someone tell me? thank you!

**Comment by martin-frbg** [comment]
Look in driver/ (where the respective functions will call the appropriate optimized assembler routines for your cpu, which live under kernel/ )
You can find a short intro to the layout in https://github.com/xianyi/OpenBLAS/wiki/Developer-manual

**Comment by martin-frbg** [comment]
Please close this bug report if you are satisfied with the answer
