### ISSUE TITLE
Error  Cross-Compiled in MIPS

### ISSUE THREAD

**Issue by xyx361100238** [xianyi/OpenBLAS#949]
Hi:
When I just use "make" to complile, it's OK!
But use command:
 make BINARY=32 CC=mipsel-linux-gcc FC=mipsel-linux-gfortran HOSTCC=gcc
I get the error:
mipsel-linux-gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -mabi=32 -DF_INTERFACE_GFORT -fPIC -DNO_WARMUP -DMAX_CPU_NUMBER=1 -DASMNAME=sgemm_nn -DASMFNAME=sgemm_nn_ -DNAME=sgemm_nn_ -DCNAME=sgemm_nn -DCHAR_NAME=\"sgemm_nn_\" -DCHAR_CNAME=\"sgemm_nn\" -DNO_AFFINITY -I../.. -UDOUBLE  -UCOMPLEX  -c -UDOUBLE -UCOMPLEX -DNN gemm.c -o sgemm_nn.o
In file included from gemm.c:65:0:
level3.c: In function 'sgemm_nn':
level3.c:287:37: error: 'sgemm_r' undeclared (first use in this function)
level3.c:287:37: note: each undeclared identifier is reported only once for each function it appears in
make[1]: **\* [sgemm_nn.o] Error 1
make[1]: Leaving directory `/usr/src/mozart_DM6291/sndkit_x1000/Kaldi/kaldi-mips/tools/OpenBLAS/driver/level3'
make: **\* [libs] Error 1

Look forward to your reply!Thanks

**Comment by xyx361100238** [comment]
ADD: Linux ubuntu 3.13.0-32-generic #57-Ubuntu i686 GNU/Linux

**Comment by martin-frbg** [comment]
I think this kind of error usually comes up when the build system cannot figure out what CPU to build for - try adding an appropriate TARGET option for the cross-compile.

**Comment by xyx361100238** [comment]
can you give me some advice about TARGET option?I test "P5600" and "LOONGSON3A", got same error.

**Comment by martin-frbg** [comment]
Unfortunately I know next to nothing about MIPS. Is P5600 the type you intend to build for, or what is your target system ? (From #902 it might be worthwile to try without the "BINARY=32" if that is just a holdover from the native compilation). Then I see some MIPS support changes were committed as recently as two weeks ago so if you are currently trying with the 0.2.18 release it might also make sense to update to a current git snapshot

**Comment by xianyi** [comment]
@sva-img , could you look at this MIPS cross compiling issue?

**Comment by xyx361100238** [comment]
@martin-frbg @xianyi , I'm still in try, thx.

**Comment by xyx361100238** [comment]
@xianyi My system is Linux ubuntu i686 , according to file 'TargetList.txt', my ARGET option must be "P5600"? But when I run :
make BINARY=32 CC=mipsel-linux-gcc FC=mipsel-linux-gfortran HOSTCC=gcc TARTGET=P5600
at beginning tips:
mipsel-linux-gcc: error: unrecognized command line option '-mmsa'
mipsel-linux-gcc: error: unrecognized command line option '-msched-weight'
mipsel-linux-gcc: error: unrecognized command line option '-mload-store-pairs'
.
.
.
.
at last shows:
mipsel-linux-gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -mabi=32 -DF_INTERFACE_GFORT -fPIC -DNO_WARMUP -DMAX_CPU_NUMBER=1 -DASMNAME=sgemm_nn -DASMFNAME=sgemm_nn_ -DNAME=sgemm_nn_ -DCNAME=sgemm_nn -DCHAR_NAME=\"sgemm_nn_\" -DCHAR_CNAME=\"sgemm_nn\" -DNO_AFFINITY -I../.. -UDOUBLE  -UCOMPLEX  -c -UDOUBLE -UCOMPLEX -DNN gemm.c -o sgemm_nn.o
In file included from gemm.c:65:0:
level3.c: In function 'sgemm_nn':
level3.c:287:37: error: 'sgemm_r' undeclared (first use in this function)
level3.c:287:37: note: each undeclared identifier is reported only once for each function it appears in

and there is 'mips32r5' in configure file:
./Makefile.system:529:CCOMMON_OPT += -mips32r5 -mnan=2008 -mtune=P5600 $(MSA_FLAGS)
./Makefile.system:530:FCOMMON_OPT += -mips32r5 -mnan=2008 -mtune=P5600 $(MSA_FLAGS)
./Makefile.prebuild:21:TARGET_FLAGS = -mips32r5

**Comment by martin-frbg** [comment]
The "unrecognized command line option" warnings seem to suggest that your cross-compiler is older than what the OpenBLAS build system expects. (If it is possible to update the cross-compiler, with luck maybe the other error will go away as well, if it is just the result of some earlier compilation or capability check that failed)

**Comment by xyx361100238** [comment]
@martin-frbg  Thanks a lot. I think i must to upgrade cross-compiler. What if i downgrade OpenBlas,  that will be OK?

**Comment by martin-frbg** [comment]
No idea actually, but you would certainly run the risk of losing some functionality if you go back to an earlier OpenBLAS. Perhaps open the Makefile.system in the online "Code" view here and click on the "History" tab to see what mips-related changes were made to this component of the build system recently - at least this should give you an indication of how far back you would need to go.

**Comment by ksraste** [comment]
For mips targets you will need latest toolchains
P5600  - MTI GNU/Linux Toolchain
I6400, P6600  - IMG GNU/Linux Toolchain

The download link is below
(http://codescape-mips-sdk.imgtec.com/components/toolchain/2016.05-03/downloads.html)

You can use following commandlines for builds
IMG_TOOLCHAIN_DIR={full IMG GNU/Linux Toolchain path including "bin" directory -- for example, /opt/linux_toolchain/bin}
IMG_GCC_PREFIX=mips-img-linux-gnu
IMG_TOOLCHAIN=${IMG_TOOLCHAIN_DIR}/${IMG_GCC_PREFIX}

1. I6400 Build (n32):
make BINARY=32 BINARY32=1 CC=$IMG_TOOLCHAIN-gcc AR=$IMG_TOOLCHAIN-ar FC="$IMG_TOOLCHAIN-gfortran -EL -mabi=n32" RANLIB=$IMG_TOOLCHAIN-ranlib HOSTCC=gcc CFLAGS="-EL" FFLAGS=$CFLAGS LDFLAGS=$CFLAGS TARGET=I6400

2. I6400 Build (n64):
make BINARY=64 BINARY64=1 CC=$IMG_TOOLCHAIN-gcc AR=$IMG_TOOLCHAIN-ar FC="$IMG_TOOLCHAIN-gfortran -EL" RANLIB=$IMG_TOOLCHAIN-ranlib HOSTCC=gcc CFLAGS="-EL" FFLAGS=$CFLAGS LDFLAGS=$CFLAGS TARGET=I6400

3. P6600 Build (n32):
make BINARY=32 BINARY32=1 CC=$IMG_TOOLCHAIN-gcc AR=$IMG_TOOLCHAIN-ar FC="$IMG_TOOLCHAIN-gfortran -EL -mabi=n32" RANLIB=$IMG_TOOLCHAIN-ranlib HOSTCC=gcc CFLAGS="-EL" FFLAGS=$CFLAGS LDFLAGS=$CFLAGS TARGET=P6600

4. P6600 Build (n64):
make BINARY=64 BINARY64=1 CC=$IMG_TOOLCHAIN-gcc AR=$IMG_TOOLCHAIN-ar FC="$IMG_TOOLCHAIN-gfortran -EL" RANLIB=$IMG_TOOLCHAIN-ranlib HOSTCC=gcc CFLAGS="-EL" FFLAGS="$CFLAGS" LDFLAGS="$CFLAGS" TARGET=P6600



MTI_TOOLCHAIN_DIR={full MTI GNU/Linux Toolchain path including "bin" directory -- for example, /opt/linux_toolchain/bin}
MTI_GCC_PREFIX=mips-mti-linux-gnu
MTI_TOOLCHAIN=${IMG_TOOLCHAIN_DIR}/${IMG_GCC_PREFIX}

1. P5600 Build:

make BINARY=32 BINARY32=1 CC=$MTI_TOOLCHAIN-gcc AR=$MTI_TOOLCHAIN-ar FC="$MTI_TOOLCHAIN-gfortran -EL" RANLIB=$MTI_TOOLCHAIN-ranlib HOSTCC=gcc CFLAGS="-EL" FFLAGS=$CFLAGS LDFLAGS=$CFLAGS TARGET=P5600

**Comment by martin-frbg** [comment]
@xianyi Can we get this copied to the FAQ/wiki please ?

**Comment by xyx361100238** [comment]
@martin-frbg  Thanks a lot
