### ISSUE TITLE
cannot find -lgfortran error when make FC=gfortran

### ISSUE THREAD

**Issue by lan2720** [xianyi/OpenBLAS#954]
Hi, 

Error is like that
```
make[1]: Leaving directory `/home/lan/Packages/OpenBLAS/ctest'
make[1]: Entering directory `/home/lan/Packages/OpenBLAS/exports'
gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=8 -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  -shared -o ../libopenblas_piledriverp-r0.2.20.dev.so \
	-Wl,--whole-archive ../libopenblas_piledriverp-r0.2.20.dev.a -Wl,--no-whole-archive \
	-Wl,-soname,libopenblas.so.0 -lm -lpthread -lgfortran -lm -lpthread -lgfortran
/usr/bin/ld: cannot find -lgfortran
collect2: error: ld returned 1 exit status
make[1]: *** [../libopenblas_piledriverp-r0.2.20.dev.so] Error 1
make[1]: Leaving directory `/home/lan/Packages/OpenBLAS/exports'
make: *** [shared] Error 2

```
CPU is AMD FX8350. gfortran has been installed, its version is 4.8.5. The libgfortran-dev package is also installed.

**Comment by martin-frbg** [comment]
Still looks as if the build system does not know the location of libgfortran.so or libgfortran.so.4.8.5 - perhaps try invoking "ldconfig" before invoking "make" again. If that does not help, please state what operating system (or which vendor version of Linux) you are using.

**Comment by lan2720** [comment]
Thanks for your help! Yes that makes the same error. My operating system is Ubuntu 14.04.
And when I run `ldconfig -v | grep libgfortran`, it gives me something like that:
```
/sbin/ldconfig.real: Path `/lib/x86_64-linux-gnu' given more than once
/sbin/ldconfig.real: Path `/usr/lib/x86_64-linux-gnu' given more than once
/sbin/ldconfig.real: /lib/x86_64-linux-gnu/ld-2.19.so is the dynamic linker, ignoring

	libgfortran.so.3 -> libgfortran.so.3.0.0
/sbin/ldconfig.real: Cannot stat /usr/lib32/nvidia-367/libOpenGL.so: No such file or directory
/sbin/ldconfig.real: /lib32/ld-2.19.so is the dynamic linker, ignoring
```

**Comment by xianyi** [comment]
maybe reinstall gfortran?

**Comment by lan2720** [comment]
@xianyi Thanks, It solved now. I uninstall default gfortran(which is version 4.8) and install gfortran-4.9 using apt-get(must specfic 4.9 because v4.8 as default). And run the command `sudo ldconfig` then `make FC=gfortran-4.9`. Everthing is ok. I think maybe I use gcc 4.9. So it must be gfortran 4.9 to work fine?

**Comment by brada4** [comment]
Nope, OpenBLAS builds just fine with GCC 4.1 on CentOS 5

**Comment by xianyi** [comment]
@lan2720 I am going to close this issue. if you have any questions, please do not hesitate to open an issue on github.com.

**Comment by vrossum** [comment]
Just a comment for those installing on Ubuntu, as I ran into the same error.
I did gcc -v to get the compiler version (8 in my case)
and then apt install libgfortran-8-dev
After that, make worked fine.
