### ISSUE TITLE
CMake INSTALL project?

### ISSUE THREAD

**Issue by PrimarchOfTheSpaceWolves** [xianyi/OpenBLAS#957]
Hi all,

I'm using Windows 7 with Visual Studio 2013, and I use CMake a fair amount.  It would be nice if the current CMakeLists.txt file also generated the appropriate INSTALL project.

I've been trying to roll my own with some success; any suggestions would be welcome:

FILE(GLOB INCLUDE_FILES "${CMAKE_CURRENT_SOURCE_DIR}/*.h")
install (TARGETS ${OpenBLAS_LIBNAME} DESTINATION lib)
install (FILES ${INCLUDE_FILES} DESTINATION include)

**Comment by PrimarchOfTheSpaceWolves** [comment]
Followup: this is my patch file so far
[CMakeLists-patch.txt](https://github.com/xianyi/OpenBLAS/files/462355/CMakeLists-patch.txt)

**Comment by BarrySmith** [comment]
Could you turn this into a pull request? It's crazy the cmake stuff doesn't all ready have an install, but I am too incompetent at cmake (and spelling) to change the cmake files myself.

**Comment by martin-frbg** [comment]
While updating the pull request I built from your patch, I noticed that your proposal appears to be adding the _d postfix twice - once by redefining the LIBNAME, and a second time by attaching DEBUG_POSTFIX ?

**Comment by martin-frbg** [comment]
Now merged from PR #988 - please double-check if you can spare the time.
