### ISSUE TITLE
complex.h in kernel/arm/zdot.c - compile error when android_api < 21

### ISSUE THREAD

**Issue by darkbuddy** [xianyi/OpenBLAS#960]
When compiled under android_api < 21, there is no complex.h. Though common.h defined FORCE_OPENBLAS_COMPLEX_STRUCT in case of low android api version, zdot.c includes complex.h again.

I replaced FLOAT _Complex with OPENBLAS_COMPLEX_FLOAT, and the make succeeded.

```
#include "common.h"

#ifndef _MSC_VER
#include <complex.h>
FLOAT _Complex CNAME(BLASLONG n, FLOAT *x, BLASLONG inc_x, FLOAT *y, BLASLONG inc_y)
OPENBLAS_COMPLEX_FLOAT CNAME(BLASLONG n, FLOAT *x, BLASLONG inc_x, FLOAT *y, BLASLONG inc_y)
#else
OPENBLAS_COMPLEX_FLOAT CNAME(BLASLONG n, FLOAT *x, BLASLONG inc_x, FLOAT *y, BLASLONG inc_y)
#endif
{

```

**Comment by brada4** [comment]
You dont need to include complex.h extra time, it is already included via common.h if present.

**Comment by quickwritereader** [comment]
the same should be removed from mips too

**Comment by martin-frbg** [comment]
power and x86_64 versions have the same direct inclusion of complex.h as well (though in those cases it is probably just redundant rather than actually problematic). I'll see if I can find the time to prepare a trivial pull request tonight.
