### ISSUE TITLE
making benchmarks: undefined reference to sgetrf_/sgetrs_

### ISSUE THREAD

**Issue by Knoxort** [xianyi/OpenBLAS#961]
Compiling the benchmarks on an ARM Juno fails due to an undefined reference to sgetrf_ and sgetrs_. They seem to be lapack methods? Has anyone run into problems with the benchmark like this?

**Comment by ashwinyes** [comment]
Full benchmarks build  includes some benchmarks which uses LApack APIs. If you dont need them then you may comment them out from the Makefile in the benchmark directory.
