### ISSUE TITLE
Android binaries for all cpus and architectures 

### ISSUE THREAD

**Issue by quickwritereader** [xianyi/OpenBLAS#963]
Please, supply working binaries for all Android cpus and architectures .

**Comment by jht19880529** [comment]
@quickwritereader   Hi I am also interested in the Android version. I finished building the project, but met a link problem. I am trying to fix it.
Of course, it will be more convenient if officially supported.

**Comment by quickwritereader** [comment]
@jht19880529
Hi. Hope you will succeed. Please, post those binaries then. Currently, I am using armv5 version of openblas binary for both armeabi and armv7. And other cpu architectures even does not have slow version. Misc x86 armv8.
Thx

**Comment by blueardour** [comment]
As i post in another issue,  I built the openblas lib and run a demo on Huawei P9 successful.

###################
export NDK_ROOT=`which ndk-build | xargs dirname`
export APP_ABI=android-21
export PATH=${NDK_ROOT}/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin:$PATH
export CFLAGS="--sysroot=${NDK_ROOT}/platforms/${APP_ABI}/arch-arm64"

cd /workspace/ml/OpenBLAS

make clean
make TARGET=ARMV8 BINARY=64 HOSTCC=gcc CC=aarch64-linux-android-gcc NOFORTRAN=1 CFLAGS=${CFLAGS}
make PREFIX=/workspace/soft/openblas/arm64 install

cd -
###################

**Comment by xianyi** [comment]
@quickwritereader OpenBLAS supports Android + ARMv8.

**Comment by quickwritereader** [comment]
@blueardour @xianyi Hi thx for replies. What about Mips. Have you tested on that and have you got binaries for them?
@xianyi I have jni code that is using openblas. For armv7 I was obliged to use v5 version simply it did not work. Then I read that it might be cause of softfp and hardfp. Could you tell how to use openblas armv7a with jni?

**Comment by xianyi** [comment]
@quickwritereader  The current MIPS codes come from @sva-img . I didn't test MIPS with Android.

could you give me more information about your application on ARMv7 and Android? My email is traits.zhang@gmail.com

**Comment by quickwritereader** [comment]
@xianyi  Hi. When I said not worked I was meaning not compiled. I was building with ndk. Simply I forget to add  **armeabi-v7a-hard** (-hard in the end) option. Now it seems working.
I have sent part of my application to your email. which can be tested for each architecture with adb as it compiles to native executable

**Comment by quickwritereader** [comment]
I built openblas for android x86,x86_64 using  . It compiled. But I am suspicious about this
As it compiled for sandybridge. Can these work properly on intel Atom?
maybe I have specify Target other than default?

**Comment by martin-frbg** [comment]
By default the library will be built specifically for the CPU type of the system you build it on. You can specify "DYNAMIC_ARCH=1" either as a command line option to "make" or by uncommenting that line in Makefile.rule to include codes for all variants from which it will select at runtime. Or choose a suitable TARGET (a library built with TARGET=ATOM should still run on more capable cpus like Haswell or Skylake, just not as efficient as one built to match).

**Comment by quickwritereader** [comment]
@martin-frbg  Hi. what should I target for mips and mips64 for all androids?.  I could compile only mips64 targetting LOONGSON3A ( I got it from here). Thx

**Comment by quickwritereader** [comment]
Here is bash script that I am using currently
To run  ./scriptFile  arm64-v8a x86 etc
`
#!/bin/bash
echo "Build for Android"
APP_ABI="android-21" 
OUTPUT_DIR=${PWD}
NDK_ROOT=$(locate ndk-bundle | head -1)
echo "NDK_ROOT=$NDK_ROOT"
PATHI=$PATH 
if [ ! -d "OpenBLAS" ]; then  
  git clone https://github.com/xianyi/OpenBLAS.git
fi  

 
if [ -d "OpenBLAS" ]; then
 cd OpenBLAS 
else
    echo "Could not find OpenBLAS directory"
    exit -1
fi 
#architectureList=(armeabi armv7a arm64-v8a mips mips64 arm64-v8a x86 x86_64 )
architectureList=("$@") 
for architecture in ${architectureList[@]}; do 
    echo ${architecture}
    case ${architecture} in
        "armeabi")
            target="ARMV5"
            arch="arch-arm"
            CCFolder="arm-linux-androideabi-4.9" 
            CC="arm-linux-androideabi-gcc"
            ;;
        "armv7a")
            target="ARMV7"
            arch="arch-arm"
            CCFolder="arm-linux-androideabi-4.9"  
            CC="arm-linux-androideabi-gcc"
            ;;
        "arm64-v8a")
            target="ARMV8 BINARY=64"
            arch="arch-arm64"
            CCFolder="aarch64-linux-android-4.9"
            CC="aarch64-linux-android-gcc" 
            ;;
        "mips")
            target="LOONGSON3A"
            arch="arch-mips"
            CCFolder="mipsel-linux-android-4.9"
            CC="mipsel-linux-android-gcc" ;;
        "mips64")
            target="LOONGSON3A BINARY=64"
            arch="arch-mips64"
            CCFolder="mips64el-linux-android-4.9"
            CC="mips64el-linux-android-gcc" ;;
        "x86")
            target="ATOM"
            arch="arch-x86"
            CCFolder="x86-4.9"
            CC="i686-linux-android-gcc" 
             ;;
        "x86_64")
            target="ATOM BINARY=64"
            arch="arch-x86_64"
            CCFolder="x86_64-4.9"
            CC="x86_64-linux-android-gcc" ;;
        *) 
          echo "UNKNOWN"
          continue
          ;;
    esac

echo ${NDK_ROOT}/toolchains/${CCFolder}/prebuilt/linux-x86_64/bin
export PATH=${NDK_ROOT}/toolchains/${CCFolder}/prebuilt/linux-x86_64/bin:${PATHI}
command="make TARGET=${target} HOSTCC=gcc CC=${CC} NOFORTRAN=1 CFLAGS=--sysroot=${NDK_ROOT}/platforms/${APP_ABI}/${arch}"

echo $command
mkdir -p ../${architecture}
make clean
$command
make PREFIX=${OUTPUT_DIR}/${architecture} install
mv ${OUTPUT_DIR}/${architecture}/lib/*.a ${OUTPUT_DIR}/${architecture}/
rm -rf ${OUTPUT_DIR}/${architecture}/lib
rm -rf ${OUTPUT_DIR}/${architecture}/bin
if [ ! -d "${OUTPUT_DIR}/include" ]; then
 mv ${OUTPUT_DIR}/${architecture}/include ${OUTPUT_DIR}/
else
	rm -rf ${OUTPUT_DIR}/${architecture}/include
fi

done

`

**Comment by quickwritereader** [comment]
Changing  mips-64 target  to SICORTEX solved linkage problem later.
But I dont know if this will work on all mips64 android devices. On mips 32 I still got compilation error.
mipsel-linux-android-gcc: error: ../libopenblas_p5600p-r0.2.20.dev.a: No such file or directory  
mipsel-linux-android-gcc: error: unrecognized command line option '-ar'  
mipsel-linux-android-gcc: error: unrecognized command line option '-ru'  

I was targetting p5600. Frankly I dont know about mips architectures. Just found this in openblas issue list and wikipedia

**Comment by martin-frbg** [comment]
I do not know much if anything about mips, but SICORTEX appears to be a valid TARGET. 
And the unrecognized commands in the mips32 build run seem to come from a mis-identified build tool - "-ru" is a common argument to the archiver program "ar" used in building libraries, and the "-ar" above could mean that it was looking for a $SOMETHING-ar with the SOMETHING not filled in (mipsel-linux-android-ar probably ?) 
Perhaps you can get it to work if you specify it as an environment variable on the command line as something like "AR=mipsel-linux-android-ar make TARGET=P5600 ..."

**Comment by quickwritereader** [comment]
HI. thx it solved the problem.
 But now I am facing with linkage problem. I dont know which way to use. The problem is that in ndk it isusing for nans  -mnan=legacy (which is default) while with openblas it is -mnan=2008.  Which one should I change to work properly. The same problem I had when targetting LOONGSON3A. I solved it using just changing Target

**Comment by martin-frbg** [comment]
As far as I understand, there is no advantage to using one over the other, it just has to be consistent in all pieces of code that are linked together. Perhaps this setting was committed to OpenBLAS' Makefile.system (FCOMMON_OPT entry) by someone whose version of the ndk defaulted to 2008 ?

**Comment by quickwritereader** [comment]
@martin-frbg  Hi. So I can remove those options from MakeFile.system? I tried to add this option to ndk CFFlags  build but it was still giving the same error , .

**Comment by quickwritereader** [comment]
@martin-frbg  Removing that option fixed the problem.

**Comment by quickwritereader** [comment]
@martin-frbg  @xianyi  @notaz  @jht19880529  @blueardour 
Thx guys for the help. I was able to build and link with your help. Now I need to find  devices to test for correctness at least on some architectures. 
Here is  [script for compiling](https://github.com/quickwritereader/openblasBuildForAndroid/blob/master/compand.sh) and here are  [binaries](https://github.com/quickwritereader/openblasBuildForAndroid/tree/master/output)

**Comment by quickwritereader** [comment]
@martin-frbg I could test only on armv7. Yes you can add. If you have time check it for correctness.

**Comment by quickwritereader** [comment]
@martin-frbg I could test only on armv7. Ofcourse, you can add.

**Comment by quickwritereader** [comment]
@martin-frbg  I added how to build test executables and test them on device. I used other separate test project. Cause while building I define NOLAPACK and NOfortran which does not build test executables

See  [ReadMe file and scriptfiles](https://github.com/quickwritereader/openblasBuildForAndroid)
