### ISSUE TITLE
error when compile for android

### ISSUE THREAD

**Issue by charleslipku** [xianyi/OpenBLAS#964]
I follow the instructions to compile for android, but come to some errors.

ANGs-MacBook-Pro-2:~ ANGLI$ export PATH=Desktop/tmp/my-android-toolchain/bin/:$PATH
ANGs-MacBook-Pro-2:~ ANGLI$ cd Downloads/
ANGs-MacBook-Pro-2:Downloads ANGLI$ cd OpenBLAS-0.2.19/
ANGs-MacBook-Pro-2:OpenBLAS-0.2.19 ANGLI$ make TARGET=ARMV7 HOSTCC=gcc CC=arm-linux-androideabi-gcc NOFORTRAN=1
C Compiler (arm-linux-androideabi-gcc) is something wrong.
1 at ./c_check line 28.
make: *** [config.h] Error 2
Makefile.system:165: Makefile.conf: No such file or directory
Makefile.system:912: Makefile.: No such file or directory
make: *** No rule to make target `Makefile.'.  Stop.

**Comment by martin-frbg** [comment]
The PATH to the toolchain given in the first statement could be the problem - it appears to be relative to your home directory, and I do not believe it is automatically expanded to an absolute path. So once you enter the OpenBLAS source tree, the system will try to find the androideabi-gcc in a non-existing Desktop folder below that. Try export PATH=~/Desktop/tmp/... or /home/yourusername/Desktop/tmp/...

**Comment by blueardour** [comment]
Here is my build_android_openblas.sh:
`export NDK_ROOT=`which ndk-build | xargs dirname`
export APP_ABI=android-21
export PATH=${NDK_ROOT}/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin:$PATH
export CFLAGS="--sysroot=${NDK_ROOT}/platforms/${APP_ABI}/arch-arm64"

cd /workspace/ml/OpenBLAS

make clean
make TARGET=ARMV8 BINARY=64 HOSTCC=gcc CC=aarch64-linux-android-gcc NOFORTRAN=1 CFLAGS=${CFLAGS}
make PREFIX=/workspace/soft/openblas/arm64 install

cd -`

I have run the test demo on Huawei P9. Hope it helpful.

**Comment by charleslipku** [comment]
Thanks for your response. @martin-frbg @blueardour
