### ISSUE TITLE
symbol lookup error - undefined symbol "dlamch_" when using LAPACK in OpenBLAS

### ISSUE THREAD

**Issue by guangster** [xianyi/OpenBLAS#972]
Hi,

I encountered the following error when trying to use LAPACK from OpenBLAS:
`
/usr/lib/jvm/java-8-oracle/jre/bin/java: symbol lookup error: /tmp/jniloader7041787223867102319netlib-native_system-linux-x86_64.so: undefined symbol: dlamch_
`

The wrapper calling the OpenBLAS shared library is netlib-java.

The Makefile.rule I've used is
```
VERSION = 0.2.19
BINARY=64
USE_THREAD = 1
BUILD_LAPACK_DEPRECATED = 1
COMMON_PROF = -pg
```

the links are
```
sudo update-alternatives --install /usr/lib/libblas.so     libblas.so     /opt/OpenBLAS/lib/libopenblas.so 1000
sudo update-alternatives --install /usr/lib/libblas.so.3   libblas.so.3   /opt/OpenBLAS/lib/libopenblas.so 1000
sudo update-alternatives --install /usr/lib/liblapack.so   liblapack.so   /opt/OpenBLAS/lib/libopenblas.so 1000
sudo update-alternatives --install /usr/lib/liblapack.so.3 liblapack.so.3 /opt/OpenBLAS/lib/libopenblas.so 1000
```

If I change the last two to use default lapack like from `sudo apt-get install liblapack-dev`, I do not see the above error

I'm not sure what I did wrong, any help or advise is greatly appreciated.

EDIT:
to follow up, I checked the content of libopenblas.a with
`ar t /opt/OpenBLAS/lib/libopenblas.a | grep dlamch`
and was not able to find anything

**Comment by guangster** [comment]
to follow up, I checked the content of libopenblas.a with
` ar t /opt/OpenBLAS/lib/libopenblas.a | grep dlamch`
and was not able to find anything

**Comment by martin-frbg** [comment]
As far as I can see, dlamch should be included unconditionally (and my x86_64 builds definitely have it) anything in your build logs about leaving out driver/others ? (Also make sure that the libopenblas in /opt/OpenBLAS/lib is actually the one you built...)

**Comment by guangster** [comment]
Hi, thanks for the reply!

I re-ran make again and checked with `ar` on the file in the OpenBLAS build directory just in case, and still same result.

output of make did not mention anything about dlamch in particular, and only mentions entering and leaving /driver/others:

```
...
make[1]: Entering directory `/home/ubuntu/OpenBLAS-0.2.19/driver/others'
gcc -O2 -DMAX_STACK_ALLOC=2048 -fopenmp -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DNO_LAPACK -DNO_LAPACKE -DSMP_SERVER -DUSE_OPENMP -DMAX_CPU_NUMBER=4 -DASMNAME=memory -DASMFNAME=memory_ -DNAME=memory_ -DCNAME=memory -DCHAR_NAME=\"memory_\" -DCHAR_CNAME=\"memory\" -I../.. -c memory.c -o memory.o
...
ar  -ru ../../libopenblas_sandybridgep-r0.2.19.a memory.o xerbla.o c_abs.o z_abs.o openblas_set_num_threads.o openblas_get_num_threads.o openblas_get_num_procs.o openblas_get_config.o openblas_get_parallel.o openblas_error_handle.o openblas_env.o blas_server.o divtable.o blasL1thread.o init.o parameter.o
make[1]: Leaving directory `/home/ubuntu/OpenBLAS-0.2.19/driver/others'
```
--
As a side note, this error seems to occur only on an EC2 instance (m3.2xlarge, Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz)

I tried OpenBLAS on a different local machine with Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz, running
`ar t /opt/OpenBLAS/lib/libopenblas.a | grep dlamch`
shows
```
dlamch.o
lapacke_dlamch.o
lapacke_dlamch_work.o
```

both are running ubuntu 14.04

**Comment by martin-frbg** [comment]
Hmm. Is the -DNO_LAPACK in that log snippet intentional, given that you mentioned using BUILD_LAPACK_DEPRECATED=1 in your Makefile.rule above ?

**Comment by guangster** [comment]
I'm not sure about -DNO_LAPACK, the only thing I changed from the OpenBLAS Readme is the Makefile.rule, as I found that turning on CPU_AFFINITY worked better for my code.
I left BUILD_LAPACK_DEPRECATED=1 alone, which was the default setting.

I also make sure to do `make clean`.

**Comment by martin-frbg** [comment]
If you did not set NO_LAPACK=1 in Makefile.rule , the explanation could be that the EC2 setup lacks a
usable FORTRAN compiler ?

**Comment by guangster** [comment]
You are right! That was very silly of me. I will try again and update.

**Comment by guangster** [comment]
Hi, the fortran compiler was indeed the issue. Thanks so much for the quick response!
