### ISSUE TITLE
Build Makefile:94 error

### ISSUE THREAD

**Issue by binekk** [xianyi/OpenBLAS#974]
Hello,
I am trying to install the 0.2.19 version on 64bit Windows 10 using msys2/mingw64. The following errors occurred after running make and I am quite clueless on what might be the cause and solution.
```
../libopenblas_haswellp-r0.2.19.a(parameter.obj):parameter.c:(.text+0x31): undefined reference to `_cpuid'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:94: ../libopenblas.dll] Error 1
make[1]: Leaving directory '/c/OpenBLAS 0.2.19 version/xianyi-OpenBLAS-9a7e0ec/exports'
make: *** [Makefile:105: shared] Error 2
```
Don't know if relevant, but I my msys2 is the latest x86_64, downloaded from 
https://sourceforge.net/projects/msys2/files/Base/x86_64/
with base-devel and msys2-devel packages installed.

The log included hundreds of 'undefined reference to' warnings similar to the first line above. Will be thankful for any ideas/help.

**Comment by brada4** [comment]
Can you attach full output log? I dont see any GCC in your 'errors'

**Comment by binekk** [comment]
Please see attached
[err.txt](https://github.com/xianyi/OpenBLAS/files/510451/err.txt)
[log.txt](https://github.com/xianyi/OpenBLAS/files/510452/log.txt)

**Comment by martin-frbg** [comment]
The "i386 architecture of <something>.obj is incompatible with i386:x86_64 output" messages in err.txt
suggest that you may have some files lying around from an earlier compile attempt using different options. Did you perchance try once with the BINARY=32 option and once without, or are you sharing the folder with some other machine where you built OpenBLAS previously ?
In either case try doing "make clean" before running "make" again.

**Comment by binekk** [comment]
Running "make clean" did it. 

I don't think I tried BINARY=32 or anything like this, though I tried to compile before, so something left from than must have been the problem.
Thank you very much for help!

**Comment by martin-frbg** [comment]
Glad to know it worked. Could you close this issue then please ? (Only the submitter or one of the core developers can do this, so solved issues tend to hang around as zombies here sometimes)
