### ISSUE TITLE
undefined reference toGOMP_parallel

### ISSUE THREAD

**Issue by Stark123** [xianyi/OpenBLAS#975]
_Hi I am getting this error while building openBLAS for Android_-

make[1]: **\* [sblat2] Error 1
../libopenblas_armv8p-r0.2.20.dev.a(zaxpy.o): In function zaxpy_': zaxpy.c:(.text+0x94): undefined reference toomp_in_parallel'
zaxpy.c:(.text+0xfc): undefined reference to omp_get_max_threads' ../libopenblas_armv8p-r0.2.20.dev.a(zswap.o): In functionzswap_':
zswap.c:(.text+0x60): undefined reference to omp_in_parallel' zswap.c:(.text+0xe0): undefined reference toomp_get_max_threads'
../libopenblas_armv8p-r0.2.20.dev.a(zscal.o): In function zscal_': zscal.c:(.text+0x68): undefined reference toomp_in_parallel'
zscal.c:(.text+0xc0): undefined reference to omp_get_max_threads' ../libopenblas_armv8p-r0.2.20.dev.a(zdscal.o): In functionzdscal_':
zscal.c:(.text+0x68): undefined reference to omp_in_parallel' zscal.c:(.text+0xb8): undefined reference toomp_get_max_threads'
../libopenblas_armv8p-r0.2.20.dev.a(blas_server.o): In function exec_blas._omp_fn.0': blas_server_omp.c:(.text+0x20): undefined reference toomp_get_num_threads'
blas_server_omp.c:(.text+0x28): undefined reference to omp_get_thread_num' blas_server_omp.c:(.text+0x168): undefined reference toomp_get_thread_num'
../libopenblas_armv8p-r0.2.20.dev.a(blas_server.o): In function goto_set_num_threads': blas_server_omp.c:(.text+0x2d0): undefined reference toomp_set_num_threads'
../libopenblas_armv8p-r0.2.20.dev.a(blas_server.o): In function exec_blas': blas_server_omp.c:(.text+0x678): undefined reference toGOMP_parallel'
collect2: error: ld returned 1 exit status
make[1]: **\* [zblat1] Error 1
make[1]: Leaving directory `/home/gaurav/deeplearning/caffe-android-lib/OpenBLAS/test'
make: **\* [tests] Error 2
Failed to build OpenBLAS

Any suggestions?

**Comment by brada4** [comment]
There is no openmp on Android.
Please remove all your custom flags , make clean, and build again.

**Comment by martin-frbg** [comment]
> There is no openmp on Android.
As far as I can tell, there is (with some caveats for thread initialization bugs in Android ndk 10 and earlier appearently, see http://www.softwarecoven.com/parallel-computing-with-openmp-in-android/)
and the c_check part of the build system does not seem to differentiate between supported platforms regarding addition of the -fopenmp directive once it determines C_COMPILER is gcc.

"make clean; make" may still solve the problem if you had built OpenBLAS with different options (or for different systems if you share folders between them or cross-compile) in this location before.

**Comment by martin-frbg** [comment]
@Stark123 did you manage to fix this in the meantime ? Judging from the other issue tickets you created in the same timeframe it looks like you had a problem with the general setup of your build environment back then ?
