### ISSUE TITLE
patch for NetBSD, undefined get_num_procs with NO_AFFINITY=1

### ISSUE THREAD

**Issue by kuehro** [xianyi/OpenBLAS#979]
Building on NetBSD with NO_AFFINITY=1 fails with:

/usr/pkg/gcc7snapshot/bin/gfortran -m128bit-long-double -Wall -m64 -fopenmp   -o sblat1 sblat1.o ../libopenblas_nehalemp-r0.2.20.dev.a -lpthread -lgfortran -lpthread -lgfortran 
../libopenblas_nehalemp-r0.2.20.dev.a(memory.o): In function `openblas_get_num_procs':
memory.c:(.text+0x170): undefined reference to `get_num_procs'
collect2: error: ld returned 1 exit status
Makefile:129: recipe for target 'sblat1' failed
gmake[1]: *** [sblat1] Error 1
gmake[1]: *** Waiting for unfinished jobs....
gmake[1]: Leaving directory '/home/kue/build/OpenBLAS-develop/test'
Makefile:111: recipe for target 'tests' failed
gmake: *** [tests] Error 2

It can be fixed with this patch:

--- driver/others/memory.c.orig	2016-10-10 19:28:11.187848951 +0200
+++ driver/others/memory.c	2016-10-10 19:28:35.787948640 +0200
@@ -169,7 +169,7 @@
 
 #else
 
-#if defined(OS_LINUX) || defined(OS_SUNOS)
+#if defined(OS_LINUX) || defined(OS_SUNOS) || defined(OS_NETBSD)
 #ifndef NO_AFFINITY
 int get_num_procs(void);
 #else

Tested on NetBSD 7.99.39 amd64 with 
gmake BINARY=64 NO_AFFINITY=1 USE_OPENMP=1 \
CC=/usr/pkg/gcc7snapshot/bin/gcc FC=/usr/pkg/gcc7snapshot/bin/gfortran

**Comment by xianyi** [comment]
Thank you for the patch.

**Comment by kuehro** [comment]
>Thank you for the patch.

Thank you so much for all your work.

Kai-Uwe
