### ISSUE TITLE
Error Compiling on ARM Cortex-A57

### ISSUE THREAD

**Issue by pythonanonuser** [xianyi/OpenBLAS#994]
I'm having trouble compiling on my Jetson TX1 which has a ARM Cortex A57 CPU. I have tried both the develop branch and master but get the same error.

```
gemv.c: In function ‘sgemv_’:
gemv.c:223:29: error: ‘GEMM_MULTITHREAD_THRESHOLD’ undeclared (first use in this function)
   if ( 1L * m * n < 2304L * GEMM_MULTITHREAD_THRESHOLD )
                             ^
gemv.c:223:29: note: each undeclared identifier is reported only once for each function it appears in
Makefile:841: recipe for target 'sgemv.o' failed
```

I've tried both `make` and `make target=CORTEXA57` but both yield the same error. Any solutions would be much appreciated. Thanks!

**Comment by ashwinyes** [comment]
Use "make TARGET=CORTEXA57"

**Comment by pythonanonuser** [comment]
same error

**Comment by ashwinyes** [comment]
Could you please try falling back to tag v0.2.19 or v0.2.18 (using git checkout ) on the develop branch and try the same. I had built OpenBLAS on the TX1 SOC with no issues before, but unfortunately I don't have access to the board now.

Also, please remember to completely clean your OpenBLAS workspace before you start a build. You may use the following commands to do the same.
git clean -fdx
git reset --hard

**Comment by pythonanonuser** [comment]
Tried both tags and still got the same error

**Comment by pythonanonuser** [comment]
I got it to work. I was trying to install from an external drive rather than the main drive.

**Comment by damian1976** [comment]
Hi,
Any support for Cortex A-72? (TARGET=CORTEXA72 ?)

**Comment by ashwinyes** [comment]
TARGET=CORTEXA57 will work fine on CORTEXA72 as well.

But it may not be fully optimized for that processor.

**Comment by damian1976** [comment]
Ok, I can confirm :) It works. Thank you.
