### ISSUE TITLE
Single threaded version using commands like apt-get or homebrew

### ISSUE THREAD

**Issue by RobeDM** [xianyi/OpenBLAS#997]
I am using a single threaded version of openblas.

For project requirements I need to avoid any possibility of parallelization with environment variables.

I build openblas using:

make USE_THREAD=0

Is there any possibility to install a single thread version of openblas with commands like apt-get in ubuntu or hombrew in Os X?

**Comment by martin-frbg** [comment]
Not sure I understand your question, but both apt-get and homebrew rely on (local files or known internet repositories providing) a  prebuilt package, so I believe this boils down to "how does one package for homebrew/apt/rpm/whatever" ? 
You may want to contact the maintainers of the existing Ubuntu or OSX openblas packages if you do not find a single-threaded build already provided - or download their source packages to obtain (and modify) their build framework if you plan to provide your own packages.

**Comment by brada4** [comment]
Following variables will disable threading in OpenBLAS and many competing libraries' multithreaded versions:
OPENBLAS_NUM_THREADS=1
OMP_NUM_THREADS=1,1
MKL_NUM_THREADS=1
ATLAS_NUM_THREADS=1

RPM (suse/mandrive/fedora) have multiple packages with different thread configurations. -lopenblas is usually single threaded.
