### ISSUE TITLE
Does compilation require disabling CPU frequency scaling

### ISSUE THREAD

**Issue by edrozenberg** [xianyi/OpenBLAS#998]
The ATLAS project requires it and wondering if OpenBLAS would have the same requirement: "If throttling is enabled, the only way to get a decent ATLAS install is therefore to turn it off."
http://math-atlas.sourceforge.net/atlas_install/node5.html

On modern machines disabling this requires rebooting with kernel parameter "intel_pstate=disable" and the setting cpu freq to "performance",  compiling ATLAS then rebooting after removing the kernel setting. A bit of a pain for sure.

Have not been able to find documentation whether OpenBLAS would benefit from disabling CPU throttling/frequency scaling during compilation of OpenBLAS.

If OpenBLAS doesn't need this that's great.

**Comment by martin-frbg** [comment]
In short, no.
ATLAS is special in that it tries to optimize itself for the computer it is built on - it needs constant cpu speed to get meaningful benchmarks that allow the ATLAS build system to select the most appropriate functions from its pool of C source code. 
OpenBLAS does not need this as it uses a fixed set of hand-optimized assembler routines for the various cpu models it supports. Only if you want to perform your own benchmark calculations to compare the speed of your code when using different libraries you would need to disable frequency scaling.

**Comment by edrozenberg** [comment]
Thanks very much, great to know this is not required for OpenBLAS. Closing this issue.
