### ISSUE TITLE
Can't compile openblas

### ISSUE THREAD

**Issue by kenken64** [xianyi/OpenBLAS#999]
Makefile:133: recipe for target '../libopenblas_haswellp-r0.2.20.dev.so' failed

**Comment by martin-frbg** [comment]
Please show more of the log - the actual error must have come earlier. (One rather common case seems to be not having a fortran compiler installed - unless you build without lapack support).

**Comment by brada4** [comment]
or having old binutils on CentOS 6...

**Comment by martin-frbg** [comment]
Did you manage to get it working in the meantime, or do you need further assistance ?

**Comment by martin-frbg** [comment]
Please reopen with more information (as requested above) if this is still relevant.
